Inexor: inexor/engine/blend.cpp File Reference
blend.cpp File Reference
#include <SDL_opengl.h>
#include <boost/algorithm/clamp.hpp>
#include <math.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "inexor/client/network.hpp"
#include "inexor/engine/blend.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/image.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct BlendMapNode
struct BlendMapBranch
struct BlendMapSolid
struct BlendMapImage
struct BlendMapRoot
struct BlendMapCache
struct BlendBrush
union BlendMapNode.__unnamed__
Macros
#define BM_SCALE 1
#define BM_IMAGE_SIZE 64
#define DEFBMSOLIDS(n) n, n+1, n+2, n+3, n+4, n+5, n+6, n+7, n+8, n+9, n+10, n+11, n+12, n+13, n+14, n+15
Enumerations
enum { BM_BRANCH = 0, BM_SOLID, BM_IMAGE }
Functions
BlendMapCache * newblendmapcache ()
void freeblendmapcache (BlendMapCache *&cache)
bool setblendmaporigin (BlendMapCache *cache, const ivec &o, int size)
bool hasblendmap (BlendMapCache *cache)
static uchar lookupblendmap (int x, int y, BlendMapBranch *bm, int bmscale)
uchar lookupblendmap (BlendMapCache *cache, const vec &pos)
static void fillblendmap (uchar &type, BlendMapNode &node, int size, uchar val, int x1, int y1, int x2, int y2)
void fillblendmap (int x, int y, int w, int h, uchar val)
static void invertblendmap (uchar &type, BlendMapNode &node, int size, int x1, int y1, int x2, int y2)
void invertblendmap (int x, int y, int w, int h)
static void optimizeblendmap (uchar &type, BlendMapNode &node)
void optimizeblendmap ()
VARF (blendpaintmode, 0, 0, 5,{if(!blendpaintmode) stoppaintblendmap();})
static void blitblendmap (uchar &type, BlendMapNode &node, int bmx, int bmy, int bmsize, uchar *src, int sx, int sy, int sw, int sh, int smode)
void blitblendmap (uchar *src, int sx, int sy, int sw, int sh, int smode)
void resetblendmap ()
void enlargeblendmap ()
void shrinkblendmap (int octant)
void moveblendmap (uchar type, BlendMapNode &node, int size, int x, int y, int dx, int dy)
void moveblendmap (int dx, int dy)
void cleanupblendmap ()
void clearblendbrushes ()
void delblendbrush (const char *name)
void addblendbrush (const char *name, const char *imgname)
void nextblendbrush (int *dir)
void setblendbrush (const char *name)
void getblendbrushname (int *n)
void curblendbrush ()
COMMAND (clearblendbrushes,"")
COMMAND (delblendbrush,"s")
COMMAND (addblendbrush,"ss")
COMMAND (nextblendbrush,"i")
COMMAND (setblendbrush,"s")
COMMAND (getblendbrushname,"i")
COMMAND (curblendbrush,"")
bool canpaintblendmap (bool brush=true, bool sel=false, bool msg=true)
void rotateblendbrush (int *val)
COMMAND (rotateblendbrush,"i")
void paintblendmap (bool msg)
VAR (paintblendmapdelay, 1, 500, 3000)
VAR (paintblendmapinterval, 1, 30, 3000)
void stoppaintblendmap ()
void trypaintblendmap ()
ICOMMAND (paintblendmap,"D",(int *isdown),{if(*isdown){if(!paintingblendmap){paintblendmap(true);paintingblendmap=totalmillis;}}else stoppaintblendmap();})
void clearblendmapsel ()
COMMAND (clearblendmapsel,"")
void invertblendmapsel ()
COMMAND (invertblendmapsel,"")
void invertblendmap ()
COMMAND (invertblendmap,"")
void showblendmap ()
COMMAND (showblendmap,"")
COMMAND (optimizeblendmap,"")
ICOMMAND (clearblendmap,"",(),{if(noedit(true)||(nompedit &&multiplayer())) return;resetblendmap();showblendmap();})
ICOMMAND (moveblendmap,"ii",(int *dx, int *dy),{if(noedit(true)||(nompedit &&multiplayer())) return;if(*dx%(BM_IMAGE_SIZE<< BM_SCALE)||*dy%(BM_IMAGE_SIZE<< BM_SCALE)){Log.std->error("blendmap movement must be in multiples of {}",(BM_IMAGE_SIZE<< BM_SCALE));return;}if(*dx<=-worldsize||*dx >=worldsize||*dy<=-worldsize||*dy >=worldsize) resetblendmap();else moveblendmap(*dx >>BM_SCALE,*dy >>BM_SCALE);showblendmap();})
void renderblendbrush ()
bool loadblendmap (stream *f, uchar &type, BlendMapNode &node)
bool loadblendmap (stream *f, int info)
void saveblendmap (stream *f, uchar type, BlendMapNode &node)
void saveblendmap (stream *f)
uchar shouldsaveblendmap ()
Variables
static BlendMapSolid bmsolids [256]
static BlendMapRoot blendmap
static vector< BlendBrush * > brushes
static int curbrush = -1
SharedVar< int > nompedit
int paintingblendmap = 0
int lastpaintblendmap = 0
Class Documentation
struct BlendMapImage
Class Members
uchar data[BM_IMAGE_SIZE *BM_IMAGE_SIZE]
struct BlendMapCache
Class Members
BlendMapRoot node
ivec2 origin
int scale
union BlendMapNode.__unnamed__
Class Members
BlendMapBranch * branch
BlendMapImage * image
BlendMapSolid * solid
Macro Definition Documentation
#define BM_IMAGE_SIZE 64
Referenced by blitblendmap(), fillblendmap(), invertblendmap(), and lookupblendmap().
#define BM_SCALE 1
Referenced by blitblendmap(), clearblendmapsel(), fillblendmap(), invertblendmap(), invertblendmapsel(), lookupblendmap(), moveblendmap(), paintblendmap(), renderblendbrush(), and setblendmaporigin().
#define DEFBMSOLIDS (n) n, n+1, n+2, n+3, n+4, n+5, n+6, n+7, n+8, n+9, n+10, n+11, n+12, n+13, n+14, n+15
Enumeration Type Documentation
anonymous enum
Enumerator
BM_BRANCH
BM_SOLID
BM_IMAGE
Function Documentation
void addblendbrush (const char * name, const char * imgname)
References vector< T, MINSIZE >::add(), ImageData::bpp, brush, ImageData::data, BlendBrush::data, delblendbrush(), gle::end(), ImageData::h, vector< T, MINSIZE >::length(), loadimage(), Log, loopi(), inexor::rpc::max(), ImageData::pitch, inexor::util::log_manager::std, and ImageData::w.
static void blitblendmap (uchar & type, BlendMapNode & node, int bmx, int bmy, int bmsize, uchar * src, int sx, int sy, int sw, int sh, int smode) static
References BM_BRANCH, BM_IMAGE, BM_IMAGE_SIZE, BM_SOLID, loopi(), inexor::rpc::max(), inexor::rpc::min(), and BlendMapNode::splitsolid().
Referenced by blitblendmap(), moveblendmap(), and paintblendmap().
void blitblendmap (uchar * src, int sx, int sy, int sw, int sh, int smode)
References blitblendmap(), BM_SCALE, inexor::rpc::max(), inexor::rpc::min(), BlendMapRoot::type, and worldsize.
bool canpaintblendmap (bool brush = true, bool sel = false, bool msg = true)
References blendpaintmode, brush, inexor::util::log_manager::edit, vector< T, MINSIZE >::inrange(), Log, multiplayer(), noedit(), and sel.
Referenced by paintblendmap(), and rotateblendbrush().
void cleanupblendmap ()
References loopv.
Referenced by resetgl().
void clearblendbrushes ()
References vector< T, MINSIZE >::length(), and vector< T, MINSIZE >::pop().
void clearblendmapsel ()
References BM_SCALE, fillblendmap(), selinfo::grid, multiplayer(), noedit(), selinfo::o, previewblends(), selinfo::s, sel, and worldsize.
COMMAND (clearblendbrushes , "")
COMMAND (delblendbrush , "s")
COMMAND (addblendbrush , "ss")
COMMAND (nextblendbrush , "i")
COMMAND (setblendbrush , "s")
COMMAND (getblendbrushname , "i")
COMMAND (curblendbrush , "")
COMMAND (rotateblendbrush , "i")
COMMAND (clearblendmapsel , "")
COMMAND (invertblendmapsel , "")
COMMAND (invertblendmap , "")
COMMAND (showblendmap , "")
COMMAND (optimizeblendmap , "")
void curblendbrush ()
References intret().
void delblendbrush (const char * name)
References vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::length(), loopv, and vector< T, MINSIZE >::remove().
Referenced by addblendbrush().
void enlargeblendmap ()
References blendmap, BM_BRANCH, BM_SOLID, BlendMapBranch::children, loopi(), BlendMapBranch::type, and BlendMapRoot::type.
Referenced by enlargemap().
static void fillblendmap (uchar & type, BlendMapNode & node, int size, uchar val, int x1, int y1, int x2, int y2) static
References BM_BRANCH, BM_IMAGE, BM_IMAGE_SIZE, BM_SOLID, BlendMapNode::cleanup(), loopi(), inexor::rpc::max(), inexor::rpc::min(), and BlendMapNode::splitsolid().
Referenced by clearblendmapsel(), fillblendmap(), invertblendmap(), and moveblendmap().
void fillblendmap (int x, int y, int w, int h, uchar val)
References BM_SCALE, fillblendmap(), inexor::rpc::max(), inexor::rpc::min(), BlendMapRoot::type, and worldsize.
void freeblendmapcache (BlendMapCache *& cache)
Referenced by lightmapworker::~lightmapworker().
void getblendbrushname (int * n)
References vector< T, MINSIZE >::inrange(), and result().
bool hasblendmap (BlendMapCache * cache)
References BlendMapCache::node.
ICOMMAND (paintblendmap , "D" , (int *isdown) , {if(*isdown){if(!paintingblendmap){paintblendmap(true);paintingblendmap=totalmillis;}}else stoppaintblendmap();})
ICOMMAND (clearblendmap , "" , () , {if(noedit(true)||(nompedit &&multiplayer())) return;resetblendmap();showblendmap();})
ICOMMAND (moveblendmap , "ii" , (int *dx, int *dy) , {if(noedit(true)||(nompedit &&multiplayer())) return;if(*dx%(BM_IMAGE_SIZE<< BM_SCALE)||*dy%(BM_IMAGE_SIZE<< BM_SCALE)){Log.std->error("blendmap movement must be in multiples of {}",(BM_IMAGE_SIZE<< BM_SCALE));return;}if(*dx<=-worldsize||*dx >=worldsize||*dy<=-worldsize||*dy >=worldsize) resetblendmap();else moveblendmap(*dx >>BM_SCALE,*dy >>BM_SCALE);showblendmap();})
static void invertblendmap (uchar & type, BlendMapNode & node, int size, int x1, int y1, int x2, int y2) static
References BM_BRANCH, BM_IMAGE, BM_IMAGE_SIZE, BM_SOLID, fillblendmap(), loopi(), loopj, inexor::rpc::max(), and inexor::rpc::min().
Referenced by invertblendmap(), and invertblendmapsel().
void invertblendmap (int x, int y, int w, int h)
References BM_SCALE, invertblendmap(), inexor::rpc::max(), inexor::rpc::min(), BlendMapRoot::type, and worldsize.
void invertblendmap ()
References BM_SCALE, invertblendmap(), multiplayer(), noedit(), previewblends(), and worldsize.
void invertblendmapsel ()
References BM_SCALE, selinfo::grid, invertblendmap(), multiplayer(), noedit(), selinfo::o, previewblends(), selinfo::s, sel, and worldsize.
bool loadblendmap (stream * f, uchar & type, BlendMapNode & node)
References BM_BRANCH, BM_IMAGE, BM_SOLID, stream::getchar(), loopi(), and stream::read().
Referenced by load_world(), and loadblendmap().
bool loadblendmap (stream * f, int info)
References loadblendmap(), resetblendmap(), and BlendMapRoot::type.
static uchar lookupblendmap (int x, int y, BlendMapBranch * bm, int bmscale) static
References BM_IMAGE, BM_IMAGE_SIZE, BM_SOLID, BlendMapBranch::children, and BlendMapBranch::type.
Referenced by generatealpha(), and lookupblendmap().
uchar lookupblendmap (BlendMapCache * cache, const vec & pos)
References BM_IMAGE, BM_IMAGE_SIZE, BM_SCALE, BM_SOLID, f(), lookupblendmap(), loop, BlendMapCache::node, BlendMapCache::origin, BlendMapCache::scale, and BlendMapRoot::type.
void moveblendmap (uchar type, BlendMapNode & node, int size, int x, int y, int dx, int dy)
References blitblendmap(), BM_BRANCH, BM_IMAGE, BM_SOLID, and fillblendmap().
Referenced by moveblendmap().
void moveblendmap (int dx, int dy)
References blendmap, BM_SCALE, BM_SOLID, BlendMapRoot::cleanup(), moveblendmap(), BlendMapRoot::type, and worldsize.
BlendMapCache* newblendmapcache ()
Referenced by lightmapworker::lightmapworker().
void nextblendbrush (int * dir)
References vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::inrange(), and vector< T, MINSIZE >::length().
static void optimizeblendmap (uchar & type, BlendMapNode & node) static
References BM_BRANCH, BM_IMAGE, BM_SOLID, BlendMapNode::cleanup(), gle::end(), and loopi().
Referenced by calclight(), and optimizeblendmap().
void optimizeblendmap ()
References optimizeblendmap(), and BlendMapRoot::type.
void paintblendmap (bool msg)
References blendpaintmode, blitblendmap(), BM_SCALE, brush, canpaintblendmap(), curbrush, BlendBrush::data, f(), BlendBrush::h, previewblends(), BlendBrush::w, worldpos, and worldsize.
Referenced by trypaintblendmap().
void renderblendbrush ()
References blendpaintmode, BM_SCALE, brush, curbrush, BlendBrush::gentex(), BlendBrush::h, vector< T, MINSIZE >::inrange(), inexor::rpc::max(), inexor::rpc::min(), renderblendbrush(), BlendBrush::tex, BlendBrush::w, worldpos, and worldsize.
Referenced by gl_drawhud(), and renderblendbrush().
void resetblendmap ()
References BM_SOLID, BlendMapRoot::cleanup(), and BlendMapRoot::type.
Referenced by loadblendmap(), and resetmap().
void rotateblendbrush (int * val)
References brush, canpaintblendmap(), curbrush, and BlendBrush::reorient().
void saveblendmap (stream * f, uchar type, BlendMapNode & node)
References BM_BRANCH, BM_IMAGE, BM_SOLID, loopi(), stream::putchar(), and stream::write().
Referenced by save_world(), and saveblendmap().
void saveblendmap (stream * f)
References saveblendmap(), and BlendMapRoot::type.
void setblendbrush (const char * name)
References loopv.
bool setblendmaporigin (BlendMapCache * cache, const ivec & o, int size)
References blendmap, BM_BRANCH, BM_SCALE, BlendMapBranch::children, inexor::rpc::max(), inexor::rpc::min(), BlendMapCache::node, BlendMapCache::origin, BlendMapCache::scale, BlendMapBranch::type, BlendMapRoot::type, and worldscale.
Referenced by findlights(), and previewblends().
uchar shouldsaveblendmap ()
Referenced by save_world().
void showblendmap ()
References multiplayer(), noedit(), previewblends(), and worldsize.
void shrinkblendmap (int octant)
References BlendMapRoot::shrink().
Referenced by shrinkmap().
void stoppaintblendmap ()
References lastpaintblendmap.
Referenced by toggleedit().
void trypaintblendmap ()
References lastpaintblendmap, paintblendmap(), and totalmillis.
Referenced by tryedit().
VAR (paintblendmapdelay , 1 , 500 , 3000)
VAR (paintblendmapinterval , 1 , 30 , 3000)
VARF (blendpaintmode , 0 , 0 , 5 , {if(!blendpaintmode) stoppaintblendmap();})
Variable Documentation
BlendMapRoot blendmap static
Referenced by enlargeblendmap(), moveblendmap(), and setblendmaporigin().
BlendMapSolid bmsolids[256] static
Initial value:
=
{
    DEFBMSOLIDS(0x00), DEFBMSOLIDS(0x10), DEFBMSOLIDS(0x20), DEFBMSOLIDS(0x30),
    DEFBMSOLIDS(0x40), DEFBMSOLIDS(0x50), DEFBMSOLIDS(0x60), DEFBMSOLIDS(0x70),
    DEFBMSOLIDS(0x80), DEFBMSOLIDS(0x90), DEFBMSOLIDS(0xA0), DEFBMSOLIDS(0xB0),
    DEFBMSOLIDS(0xC0), DEFBMSOLIDS(0xD0), DEFBMSOLIDS(0xE0), DEFBMSOLIDS(0xF0),
}
vector<BlendBrush *> brushes static
int curbrush = -1 static
Referenced by paintblendmap(), renderblendbrush(), and rotateblendbrush().
int lastpaintblendmap = 0
Referenced by stoppaintblendmap(), and trypaintblendmap().
SharedVar<int> nompedit
Referenced by edithmap(), pasteprefab(), saveprefab(), shrinkmap(), swapundo(), and vlayer().
int paintingblendmap = 0