Inexor: inexor/engine/blob.cpp File Reference
blob.cpp File Reference
#include <SDL_opengl.h>
#include <limits.h>
#include <string.h>
#include <algorithm>
#include "inexor/engine/blob.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct blobinfo
struct blobvert
struct blobrenderer
Macros
#define GENFACEORIENT(orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERT(orient, vert, x, y, z, xv, yv, zv) pos[numverts++] = vec(x xv, y yv, z zv);
#define CLIPSIDE(clip, below, above)
Enumerations
enum { BL_DUP = 1<<0, BL_RENDER = 1<<1 }
Functions
VARNP (blobs, showblobs, 0, 1, 1)
VARFP (blobintensity, 0, 60, 100, resetblobs())
VARFP (blobheight, 1, 32, 128, resetblobs())
VARFP (blobfadelow, 1, 8, 32, resetblobs())
VARFP (blobfadehigh, 1, 8, 32, resetblobs())
VARFP (blobmargin, 0, 1, 16, resetblobs())
VAR (dbgblob, 0, 0, 1)
VARFP (blobstattris, 128, 4096, 16384, initblobs(BLOB_STATIC))
VARFP (blobdyntris, 128, 4096, 16384, initblobs(BLOB_DYNAMIC))
void initblobs (int type)
void resetblobs ()
void renderblob (int type, const vec &o, float radius, float fade)
void flushblobs ()
void cleanupblobs ()
Variables
SharedVar< int > intel_mapbufferrange_bug
static blobrenderer blobs []
Class Documentation
struct blobinfo
Class Members
ushort endindex
ushort endvert
ushort flags
int millis
ushort next
vec o
float radius
ushort startindex
ushort startvert
struct blobvert
Class Members
bvec4 color
vec pos
vec2 tc
Macro Definition Documentation
#define CLIPSIDE (clip, below, above)
Value:
{ \
                    vec *in = v; \
                    v = in==v1 ? v2 : v1; \
                    numv = clip(in, numv, below, above, v); \
                    if(numv < 3) continue; \
                }
Referenced by blobrenderer::gentris().
#define GENFACEORIENT (orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERT (orient, vert, x, y, z, xv, yv, zv) pos[numverts++] = vec(x xv, y yv, z zv);
Enumeration Type Documentation
anonymous enum
Enumerator
BL_DUP
BL_RENDER
Function Documentation
void cleanupblobs ()
References blobrenderer::cleanup(), and loopi().
Referenced by resetgl().
void flushblobs ()
References blobrenderer::cleanuprenderstate(), blobrenderer::flushblobs(), and loopi().
Referenced by endmodelbatches(), and rendermodel().
void initblobs (int type)
References BLOB_DYNAMIC, BLOB_STATIC, and showblobs.
Referenced by blobrenderer::renderblob().
void renderblob (int type, const vec & o, float radius, float fade)
References reflectz, blobrenderer::renderblob(), and showblobs.
Referenced by endmodelbatches(), and rendermodel().
void resetblobs ()
References blobrenderer::reset().
Referenced by allchanged(), and commitchanges().
VAR (dbgblob , 0 , 0 , 1)
VARFP (blobintensity , 0 , 60 , 100 , resetblobs())
VARFP (blobheight , 1 , 32 , 128 , resetblobs())
VARFP (blobfadelow , 1 , 8 , 32 , resetblobs())
VARFP (blobfadehigh , 1 , 8 , 32 , resetblobs())
VARFP (blobmargin , 0 , 1 , 16 , resetblobs())
VARFP (blobstattris , 128 , 4096 , 16384 , initblobs(BLOB_STATIC))
VARFP (blobdyntris , 128 , 4096 , 16384 , initblobs(BLOB_DYNAMIC))
VARNP (blobs , showblobs , 0 , 1 , 1)
Variable Documentation
blobrenderer blobs[] static
Initial value:
=
{
    blobrenderer("<grey>particle/blob.png"),
    blobrenderer("<grey>particle/blob.png")
}
SharedVar<int> intel_mapbufferrange_bug
Referenced by gl_checkextensions().