Inexor: inexor/engine/blob.hpp File Reference
blob.hpp File Reference
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/geom.hpp"
Enumerations
enum { BLOB_STATIC = 0, BLOB_DYNAMIC }
Functions
void initblobs (int type=-1)
void resetblobs ()
void renderblob (int type, const vec &o, float radius, float fade=1)
void flushblobs ()
Variables
SharedVar< int > showblobs
Enumeration Type Documentation
anonymous enum
Enumerator
BLOB_STATIC
BLOB_DYNAMIC
Function Documentation
void flushblobs ()
References blobrenderer::cleanuprenderstate(), blobrenderer::flushblobs(), and loopi().
Referenced by endmodelbatches(), and rendermodel().
void initblobs (int type = -1)
References BLOB_DYNAMIC, BLOB_STATIC, and showblobs.
Referenced by blobrenderer::renderblob().
void renderblob (int type, const vec & o, float radius, float fade = 1)
References reflectz, blobrenderer::renderblob(), and showblobs.
Referenced by endmodelbatches(), and rendermodel().
void resetblobs ()
References blobrenderer::reset().
Referenced by allchanged(), and commitchanges().
Variable Documentation
SharedVar<int> showblobs
Referenced by initblobs(), renderblob(), and rendermodel().