Inexor: inexor::util::Logger Class Reference
inexor::util::Logger Class Reference
Wrapper around spdlog::logger to put it into the InexorTree We want to set the pattern and the level on a per-logger-base and expose it.
#include <Logging.hpp>
Public Member Functions
Logger ()
Logger (const Logger &old)
const std::shared_ptr
< spdlog::logger > operator-> () const
void create_spdlog_logger (const std::string logger_name)
void recreate_spdlog_logger ()
Wrapper for create_spdlog_logger, taking the current logger_name as argument.
Public Attributes
std::shared_ptr< spdlog::logger > spdlog_logger
SharedVar< char * > pattern
SharedVar< int > level
Detailed Description
Wrapper around spdlog::logger to put it into the InexorTree We want to set the pattern and the level on a per-logger-base and expose it.
Constructor & Destructor Documentation
inexor::util::Logger::Logger () inline
Add the listeners for the pattern and the level variables.
References inexor::rpc::SharedVar< T >::onChange, pattern, and spdlog_logger.
inexor::util::Logger::Logger (const Logger & old) inline
Member Function Documentation
void inexor::util::Logger::create_spdlog_logger (const std::string logger_name)
References inexor::util::get_all_sinks(), pattern, and spdlog_logger.
Referenced by inexor::util::log_manager::create_and_register_logger(), and recreate_spdlog_logger().
const std::shared_ptr<spdlog::logger> inexor::util::Logger::operator-> () const inline
References spdlog_logger.
void inexor::util::Logger::recreate_spdlog_logger ()
Wrapper for create_spdlog_logger, taking the current logger_name as argument.
References create_spdlog_logger(), and spdlog_logger.
Referenced by inexor::util::log_manager::all_loggers_apply_sinks_change().
Member Data Documentation
SharedVar<int> inexor::util::Logger::level
Referenced by inexor::util::log_manager::create_and_register_logger().
SharedVar<char *> inexor::util::Logger::pattern
Referenced by create_spdlog_logger(), and Logger().
std::shared_ptr<spdlog::logger> inexor::util::Logger::spdlog_logger
Referenced by create_spdlog_logger(), Logger(), operator->(), and recreate_spdlog_logger().
The documentation for this class was generated from the following files:
inexor/io/Logging.hpp
inexor/io/Logging.cpp