Inexor: inexor::io::InputRouter Class Reference
inexor::io::InputRouter Class Reference
Forwards input events to the subsystem they are needed.
#include <InputRouter.hpp>
Public Member Functions
InputRouter ()
virtual ~InputRouter ()
void keyrepeat (bool on, int mask)
Check if key was pressed repeatedly using bit masking technique.
void inputgrab ()
Do grab the input depending on the current grab mode.
void set_grab_input (bool grab_input)
Sets input grab mode for mouse and keyboard.
bool interceptkey (int sym)
"abort" key to interrupt updating the masterlist, connecting to a server or computing lightmaps
void ignoremousemotion ()
void checkinput ()
Periodically checking for new input.
Public Attributes
bool relativemouse
Private Member Functions
void pushevent (const SDL_Event &e)
add a new event to event vector
bool filterevent (const SDL_Event &event)
filter mouse motion events depending on operating system
bool pollevent (SDL_Event &event)
poll and filter all events in the SDL (input) event queue
void resetmousemotion ()
move mouse to screen center
void checkmousemotion (int &dx, int &dy)
handle mouse motion coordinates
Private Attributes
std::vector< SDL_Event > events
global vector for input events
bool shouldgrab
controlling input devices using Simple DirectMedia Layer
bool grabinput
bool canrelativemouse
int keyrepeatmask
key repetition is stored in bit masks
int textinputmask
text input state is also stored in bit masks
Detailed Description
Forwards input events to the subsystem they are needed.
Constructor & Destructor Documentation
inexor::io::InputRouter::InputRouter ()
inexor::io::InputRouter::~InputRouter () virtual
Member Function Documentation
void inexor::io::InputRouter::checkinput ()
Periodically checking for new input.
References inexor::ui::cef_app, checkmousemotion(), decodeutf8(), events, g3d_movecursor(), gl_resize(), grabinput, inputgrab(), keycodeshift, keyrepeatmask, mousemove(), pollevent(), processkey(), processtextinput(), quit(), resetmousemotion(), inexor::rendering::screen::scr_h, SCR_MAXH, SCR_MAXW, SCR_MINH, SCR_MINW, inexor::rendering::screen::scr_w, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, inexor::rendering::screen::ScreenManager::sdl_window, set_grab_input(), inexor::rendering::screen::ScreenManager::set_minimized(), and shouldgrab.
Referenced by main().
void inexor::io::InputRouter::checkmousemotion (int & dx, int & dy) private
handle mouse motion coordinates
Returns
deltax and deltay (the difference of the mouse coords)
References events, and pollevent().
Referenced by checkinput().
bool inexor::io::InputRouter::filterevent (const SDL_Event & event) private
filter mouse motion events depending on operating system
References grabinput, relativemouse, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, and inexor::rendering::screen::ScreenManager::sdl_window.
Referenced by pollevent().
void inexor::io::InputRouter::ignoremousemotion ()
pumps the event loop, gathering events from the input devices.
check the event queue for messages and optionally return them
Referenced by main().
void inexor::io::InputRouter::inputgrab ()
Do grab the input depending on the current grab mode.
References canrelativemouse, grabinput, relativemouse, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::sdl_window, shouldgrab, and inexor::io::userelativemouse.
Referenced by checkinput(), main(), and resetgl().
bool inexor::io::InputRouter::interceptkey (int sym)
"abort" key to interrupt updating the masterlist, connecting to a server or computing lightmaps
ignore mouse motion events during loading processes
References events, pollevent(), and pushevent().
Referenced by check_calclight_canceled(), resolverwait(), and show_genpvs_progress().
void inexor::io::InputRouter::keyrepeat (bool on, int mask)
Check if key was pressed repeatedly using bit masking technique.
References keyrepeatmask.
Referenced by g3d_render(), inputcommand(), and toggleedit().
bool inexor::io::InputRouter::pollevent (SDL_Event & event) private
poll and filter all events in the SDL (input) event queue
See Also
SDL_PollEvent
filterevent
References filterevent().
Referenced by checkinput(), checkmousemotion(), and interceptkey().
void inexor::io::InputRouter::pushevent (const SDL_Event & e) private
add a new event to event vector
References events.
Referenced by interceptkey().
void inexor::io::InputRouter::resetmousemotion () private
move mouse to screen center
See Also
SDL_WarpMouseInWindow
References grabinput, relativemouse, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, and inexor::rendering::screen::ScreenManager::sdl_window.
Referenced by checkinput().
void inexor::io::InputRouter::set_grab_input (bool grab_input)
Sets input grab mode for mouse and keyboard.
References grabinput.
Referenced by checkinput(), and main().
Member Data Documentation
bool inexor::io::InputRouter::canrelativemouse private
Referenced by inputgrab().
std::vector<SDL_Event> inexor::io::InputRouter::events private
global vector for input events
Referenced by checkinput(), checkmousemotion(), interceptkey(), and pushevent().
bool inexor::io::InputRouter::grabinput private
Referenced by checkinput(), filterevent(), inputgrab(), resetmousemotion(), and set_grab_input().
int inexor::io::InputRouter::keyrepeatmask private
key repetition is stored in bit masks
Referenced by checkinput(), and keyrepeat().
bool inexor::io::InputRouter::relativemouse
Referenced by filterevent(), inputgrab(), and resetmousemotion().
bool inexor::io::InputRouter::shouldgrab private
controlling input devices using Simple DirectMedia Layer
Referenced by checkinput(), and inputgrab().
int inexor::io::InputRouter::textinputmask private
text input state is also stored in bit masks
The documentation for this class was generated from the following files:
inexor/io/input/InputRouter.hpp
inexor/io/input/InputRouter.cpp