Inexor: inexor::util::Subsystem::Register Class Reference
inexor::util::Subsystem::Register Class Reference
#include <Subsystem.hpp>
Static Public Member Functions
static Register & GetInstance ()
static bool Exist (const std::string &k)
Check if the given subsystem exists.
static void EnsureExist (const std::string &k)
Ensure that the given subsystem exists.
static Starter & Get (const std::string &k)
static void Set (const std::string &k, Starter v)
Thats an alias for setting a k/v pair in the map.
Public Attributes
K keys
STL member.
T elements
STL member.
Private Member Functions
Register ()
Register (Register const &)=delete
void operator= (Register const &)=delete
Constructor & Destructor Documentation
inexor::util::Subsystem::Register::Register () inline private
inexor::util::Subsystem::Register::Register (Register const &) private delete
Member Function Documentation
static void inexor::util::Subsystem::Register::EnsureExist (const std::string & k) inline static
Ensure that the given subsystem exists.
If it does not, throws an exception.
References Exist().
Referenced by inexor::util::Metasystem::start(), and inexor::util::Metasystem::stop().
static bool inexor::util::Subsystem::Register::Exist (const std::string & k) inline static
Check if the given subsystem exists.
References GetInstance().
Referenced by EnsureExist().
static Starter& inexor::util::Subsystem::Register::Get (const std::string & k) inline static
References GetInstance().
Referenced by inexor::util::Metasystem::start().
static Register& inexor::util::Subsystem::Register::GetInstance () inline static
Referenced by Exist(), Get(), and Set().
void inexor::util::Subsystem::Register::operator= (Register const &) private delete
static void inexor::util::Subsystem::Register::Set (const std::string & k, Starter v) inline static
Thats an alias for setting a k/v pair in the map.
Returns
Always 0. (In order so we can use that in SUBSYSTEM_REGISTER with a dummy variable).
References GetInstance().
Member Data Documentation
T std::unordered_map< K, T >::elements inherited
STL member.
K std::unordered_map< K, T >::keys inherited
STL member.
The documentation for this class was generated from the following file:
inexor/util/Subsystem.hpp