Inexor: inexor::ui::input::InexorKeyboardManager Class Reference
inexor::ui::input::InexorKeyboardManager Class Reference
#include <InexorKeyboardManager.hpp>
Public Member Functions
InexorKeyboardManager (CefRefPtr< inexor::ui::layer::InexorLayerManager > layer_manager)
void SendKeyEvent (SDL_Event &e)
Forward text input and key events to CEF.
void InitializeContext () override
bool Execute (const CefString &name, CefRefPtr< CefV8Value > object, const CefV8ValueList &arguments, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Get (const CefString &name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Set (const CefString &name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString &exception) override
std::string GetContextName () override
bool OnPreKeyEvent (CefRefPtr< CefBrowser > browser, const CefKeyEvent &key_event, CefEventHandle os_event, bool *is_keyboard_shortcut) override
bool OnKeyEvent (CefRefPtr< CefBrowser > browser, const CefKeyEvent &key_event, CefEventHandle os_event) override
CefRefPtr< CefV8Value > GetContext ()
void InitializeSubContexts ()
void AddSubContext (InexorContextProvider *sub_context)
Protected Member Functions
void CreateFunction (const CefString &name)
void CreateFunction (const CefString &name, CefRefPtr< CefV8Handler > handler)
void CreateVariable (const CefString &name, bool readonly=false)
void CreateSubContext (CefRefPtr< InexorContextProvider > sub_context)
Protected Attributes
std::list
< InexorContextProvider * > sub_contexts
CefRefPtr< CefV8Value > context
Private Member Functions
IMPLEMENT_REFCOUNTING (InexorKeyboardManager)
Private Attributes
CefRefPtr
< inexor::ui::layer::InexorLayerManager > layer_manager
Constructor & Destructor Documentation
inexor::ui::input::InexorKeyboardManager::InexorKeyboardManager (CefRefPtr< inexor::ui::layer::InexorLayerManager > layer_manager) inline
Member Function Documentation
void inexor::ui::context::InexorContextProvider::AddSubContext (InexorContextProvider * sub_context) inherited
References inexor::ui::context::InexorContextProvider::sub_contexts.
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name, CefRefPtr< CefV8Handler > handler) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::context::InexorContextProvider::CreateSubContext (CefRefPtr< InexorContextProvider > sub_context) protected inherited
References inexor::ui::context::InexorContextProvider::context.
Referenced by inexor::ui::context::InexorContextProvider::InitializeSubContexts().
void inexor::ui::context::InexorContextProvider::CreateVariable (const CefString & name, bool readonly = false) protected inherited
References inexor::ui::context::InexorContextProvider::context.
bool inexor::ui::input::InexorKeyboardManager::Execute (const CefString & name, CefRefPtr< CefV8Value > object, const CefV8ValueList & arguments, CefRefPtr< CefV8Value > & retval, CefString & exception) override
bool inexor::ui::input::InexorKeyboardManager::Get (const CefString & name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > & retval, CefString & exception) override
CefRefPtr< CefV8Value > inexor::ui::context::InexorContextProvider::GetContext () inherited
References inexor::ui::context::InexorContextProvider::context, inexor::ui::context::InexorContextProvider::GetContextName(), inexor::ui::context::InexorContextProvider::InitializeContext(), inexor::ui::context::InexorContextProvider::InitializeSubContexts(), Log, and inexor::util::log_manager::ui.
std::string inexor::ui::input::InexorKeyboardManager::GetContextName () inline override virtual
Implements inexor::ui::context::InexorContextProvider.
inexor::ui::input::InexorKeyboardManager::IMPLEMENT_REFCOUNTING (InexorKeyboardManager) private
void inexor::ui::input::InexorKeyboardManager::InitializeContext () inline override virtual
Implements inexor::ui::context::InexorContextProvider.
void inexor::ui::context::InexorContextProvider::InitializeSubContexts () inherited
References inexor::ui::context::InexorContextProvider::CreateSubContext(), and inexor::ui::context::InexorContextProvider::sub_contexts.
Referenced by inexor::ui::context::InexorContextProvider::GetContext().
bool inexor::ui::input::InexorKeyboardManager::OnKeyEvent (CefRefPtr< CefBrowser > browser, const CefKeyEvent & key_event, CefEventHandle os_event) override
References Log, and inexor::util::log_manager::ui.
bool inexor::ui::input::InexorKeyboardManager::OnPreKeyEvent (CefRefPtr< CefBrowser > browser, const CefKeyEvent & key_event, CefEventHandle os_event, bool * is_keyboard_shortcut) override
References Log, and inexor::util::log_manager::ui.
void inexor::ui::input::InexorKeyboardManager::SendKeyEvent (SDL_Event & e)
Forward text input and key events to CEF.
Key events can be seen like Joystick keys, textinput differs from that since it can be composited from multiply keys.
References convertSDLtoJSKeyCode(), getKeyboardModifiers(), layer_manager, and inexor::ui::input::utf8_to_utf16().
bool inexor::ui::input::InexorKeyboardManager::Set (const CefString & name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString & exception) override
Member Data Documentation
CefRefPtr<CefV8Value> inexor::ui::context::InexorContextProvider::context protected inherited
Referenced by inexor::ui::context::InexorContextProvider::CreateFunction(), inexor::ui::context::InexorContextProvider::CreateSubContext(), inexor::ui::context::InexorContextProvider::CreateVariable(), and inexor::ui::context::InexorContextProvider::GetContext().
CefRefPtr<inexor::ui::layer::InexorLayerManager> inexor::ui::input::InexorKeyboardManager::layer_manager private
Referenced by SendKeyEvent().
std::list<InexorContextProvider*> inexor::ui::context::InexorContextProvider::sub_contexts protected inherited
Referenced by inexor::ui::context::InexorContextProvider::AddSubContext(), and inexor::ui::context::InexorContextProvider::InitializeSubContexts().
The documentation for this class was generated from the following files:
inexor/ui/input/InexorKeyboardManager.hpp
inexor/ui/input/InexorKeyboardManager.cpp