Inexor: inexor/engine/command.cpp File Reference
command.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <ctype.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <cmath>
#include <memory>
#include "inexor/engine/console.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/fpsgame/config.hpp"
#include "inexor/io/Error.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/network/legacy/cube_network.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_unicode.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct nullval
struct identlink
struct sortitem
struct sortfun
struct sleepcmd
Macros
#define _GETVAR(id, vartype, name, retval)
#define GETVAR(id, name, retval) _GETVAR(id, ID_VAR, name, retval)
#define OVERRIDEVAR(errorval, saveval, resetval, clearval)
#define ARG(n) (id->argmask&(1<<n) ? (void *)args[n].s : (void *)&args[n].i)
#define CALLCOM(n)
#define MAXRUNDEPTH 255
#define LOOKUPU(aval, sval, ival, ioldval, fval, nval)
#define LOOKUP(aval)
#define LOOKUPARG(aval, nval)
#define CALLALIAS(offset)
#define ICOMMANDNAME(name) _stdcmd
#define CASECOMMAND(name, fmt, type, acc, compare)
#define STRMAPCOMMAND(name, map)
Typedefs
typedef void(__cdecl * comfun)()
typedef void(__cdecl * comfun1)(void *)
typedef void(__cdecl * comfun2)(void *, void *)
typedef void(__cdecl * comfun3)(void *, void *, void *)
typedef void(__cdecl * comfun4)(void *, void *, void *, void *)
typedef void(__cdecl * comfun5)(void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun6)(void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun7)(void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun8)(void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun9)(void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun10)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun11)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun12)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfunv)(tagval *, int)
Enumerations
enum { MAXARGS = 25, MAXCOMARGS = 12 }
Functions
VARN_NOSYNC (numargs, _numargs, MAXARGS, 0, 0)
static void freearg (tagval &v)
static void forcenull (tagval &v)
static float forcefloat (tagval &v)
static int forceint (tagval &v)
static const char * forcestr (tagval &v)
static void forcearg (tagval &v, int type)
static ident * forceident (tagval &v)
static void freeargs (tagval *args, int &oldnum, int newnum)
static void cleancode (ident &id)
void clear_command ()
void clearoverride (ident &i)
void clearoverrides ()
static ident * addident (const ident &id)
static bool initidents ()
static const char * debugline (const char *p, const char *fmt)
VAR (dbgalias, 0, 4, 1000)
static void debugalias ()
static void debugcode (const char *fmt,...) PRINTFARGS(1
static void debugcodeline (const char *p, const char *fmt,...) PRINTFARGS(2
ICOMMAND (nodebug,"e",(uint *body),{nodebug++;executeret(body,*commandret);nodebug--;})
void addident (ident *id)
static void pusharg (ident &id, const tagval &v, identstack &stack)
static void poparg (ident &id)
ICOMMAND (push,"rte",(ident *id, tagval *v, uint *code),{if(id->type!=ID_ALIAS||id->index< MAXARGS) return;identstack stack;pusharg(*id,*v, stack);v->type=VAL_NULL;id->flags &=~IDF_UNKNOWN;executeret(code,*commandret);poparg(*id);})
static void pushalias (ident &id, identstack &stack)
static void popalias (ident &id)
KEYWORD (local, ID_LOCAL)
static bool checknumber (const char *s)
ident * newident (const char *name, int flags)
ident * writeident (const char *name, int flags)
ident * readident (const char *name)
void resetvar (char *name)
COMMAND (resetvar,"s")
static void setarg (ident &id, tagval &v)
static void setalias (ident &id, tagval &v)
static void setalias (const char *name, tagval &v)
void alias (const char *name, const char *str)
void alias (const char *name, tagval &v)
ICOMMAND (alias,"st",(const char *name, tagval *v),{setalias(name,*v);v->type=VAL_NULL;})
int variable (const char *name, int min, int cur, int max, SharedVar< int > *storage, identfun fun, int flags)
int variable (const char *name, int min, int cur, int max, int *storage, identfun fun, int flags)
float fvariable (const char *name, float min, float cur, float max, SharedVar< float > *storage, identfun fun, int flags)
char * svariable (const char *name, const char *cur, SharedVar< char * > *storage, identfun fun, int flags)
void setvar (const char *name, int i, bool dofunc, bool doclamp)
void setfvar (const char *name, float f, bool dofunc, bool doclamp)
void setsvar (const char *name, const char *str, bool dofunc)
int getvar (const char *name)
int getvarmin (const char *name)
int getvarmax (const char *name)
float getfvarmin (const char *name)
float getfvarmax (const char *name)
ICOMMAND (getfvarmax,"s",(char *s), floatret(getfvarmax(s)))
ICOMMAND (getfvarmin,"s",(char *s), floatret(getfvarmin(s)))
ICOMMAND (getvarmax,"s",(char *s), intret(getvarmax(s)))
ICOMMAND (getvarmin,"s",(char *s), intret(getvarmin(s)))
bool identexists (const char *name)
ident * getident (const char *name)
void touchvar (const char *name)
const char * getalias (const char *name)
ICOMMAND (getalias,"s",(char *s), result(getalias(s)))
int clampvar (ident *id, int val, int minval, int maxval)
void setvarchecked (ident *id, int val)
float clampfvar (ident *id, float val, float minval, float maxval)
void setfvarchecked (ident *id, float val)
void setsvarchecked (ident *id, const char *val)
bool addcommand (const char *name, identfun fun, const char *args)
bool addkeyword (int type, const char *name)
const char * parsestring (const char *p)
int unescapestring (char *dst, const char *src, const char *end)
static char * conc (vector< char > &buf, tagval *v, int n, bool space, const char *prefix=nullptr, int prefixlen=0)
static char * conc (tagval *v, int n, bool space, const char *prefix, int prefixlen)
static char * conc (tagval *v, int n, bool space)
static char * conc (tagval *v, int n, bool space, const char *prefix)
static void skipcomments (const char *&p)
static char * cutstring (const char *&p, int &len)
static const char * parseword (const char *p)
static char * cutword (const char *&p, int &len)
static void compilestr (vector< uint > &code, const char *word, int len, bool macro=false)
static void compilestr (vector< uint > &code, const char *word=nullptr)
static void compileint (vector< uint > &code, int i)
static void compilenull (vector< uint > &code)
static void compileblock (vector< uint > &code)
static void compileident (vector< uint > &code, ident *id)
static void compileident (vector< uint > &code, const char *word=nullptr)
static void compileint (vector< uint > &code, const char *word=nullptr)
static void compilefloat (vector< uint > &code, float f)
static void compilefloat (vector< uint > &code, const char *word=nullptr)
static bool compilearg (vector< uint > &code, const char *&p, int wordtype)
static void compilestatements (vector< uint > &code, const char *&p, int rettype, int brak= '\0')
static void compileval (vector< uint > &code, int wordtype, char *word, int wordlen)
static bool compileword (vector< uint > &code, const char *&p, int wordtype, char *&word, int &wordlen)
static void compilelookup (vector< uint > &code, const char *&p, int ltype)
static bool compileblockstr (vector< uint > &code, const char *str, const char *end, bool macro)
static bool compileblocksub (vector< uint > &code, const char *&p)
static void compileblock (vector< uint > &code, const char *&p, int wordtype)
static void compilemain (vector< uint > &code, const char *p, int rettype=VAL_ANY)
uint * compilecode (const char *p)
void keepcode (uint *code)
void freecode (uint *code)
void printvar (ident *id, int i)
void printfvar (ident *id, float f)
void printsvar (ident *id, const char *s)
void printvar (ident *id)
static const uint * skipcode (const uint *code, tagval &result)
static void callcommand (ident *id, tagval *args, int numargs, bool lookup=false)
static const uint * runcode (const uint *code, tagval &result)
void executeret (const uint *code, tagval &result)
void executeret (const char *p, tagval &result)
char * executestr (const uint *code)
char * executestr (const char *p)
int execute (const uint *code)
int execute (const char *p)
static bool getbool (const char *s)
static bool getbool (const tagval &v)
bool executebool (const uint *code)
bool executebool (const char *p)
const char * getcurexecdir ()
bool execfile (const char *cfgfile, bool msg)
ICOMMAND (exec,"sb",(char *file, int *msg), intret(execfile(file,*msg!=0)?1:0))
const char * escapestring (const char *s)
ICOMMAND (escape,"s",(char *s), result(escapestring(s)))
ICOMMAND (unescape,"s",(char *s),{int len=strlen(s);char *d=newstring(len);d[unescapestring(d, s,&s[len])]= '\0';stringret(d);})
const char * escapeid (const char *s)
bool validateblock (const char *s)
void writecfg (const char *name)
COMMAND (writecfg,"s")
void changedvars ()
COMMAND (changedvars,"")
const char * intstr (int v)
void intret (int v)
const char * floatstr (float v)
void floatret (float v)
ICOMMAND (?,"ttt",(tagval *cond, tagval *t, tagval *f), result(*(getbool(*cond)?t:f)))
ICOMMAND (do,"e",(uint *body), executeret(body,*commandret))
ICOMMAND (if,"tee",(tagval *cond, uint *t, uint *f), executeret(getbool(*cond)?t:f,*commandret))
ICOMMAND (pushif,"rte",(ident *id, tagval *v, uint *code),{if(id->type!=ID_ALIAS||id->index< MAXARGS) return;if(getbool(*v)){identstack stack;pusharg(*id,*v, stack);v->type=VAL_NULL;id->flags &=~IDF_UNKNOWN;executeret(code,*commandret);poparg(*id);}})
void loopiter (ident *id, identstack &stack, const tagval &v)
void loopend (ident *id, identstack &stack)
static void setiter (ident &id, int i, identstack &stack)
ICOMMAND (loop,"rie",(ident *id, int *n, uint *body),{if(*n<=0||id->type!=ID_ALIAS) return;identstack stack;loopi(*n){setiter(*id, i, stack);execute(body);}poparg(*id);})
ICOMMAND (loopwhile,"riee",(ident *id, int *n, uint *cond, uint *body),{if(*n<=0||id->type!=ID_ALIAS) return;identstack stack;loopi(*n){setiter(*id, i, stack);if(!executebool(cond)) break;execute(body);}poparg(*id);})
ICOMMAND (while,"ee",(uint *cond, uint *body), while(executebool(cond)) execute(body))
char * loopconc (ident *id, int n, uint *body, bool space)
ICOMMAND (loopconcat,"rie",(ident *id, int *n, uint *body),{if(*n > 0 &&id->type==ID_ALIAS) commandret->setstr(loopconc(id,*n, body, true));})
ICOMMAND (loopconcatword,"rie",(ident *id, int *n, uint *body),{if(*n > 0 &&id->type==ID_ALIAS) commandret->setstr(loopconc(id,*n, body, false));})
void concat (tagval *v, int n)
COMMAND (concat,"V")
void concatword (tagval *v, int n)
COMMAND (concatword,"V")
void result (tagval &v)
void stringret (char *s)
void result (const char *s)
ICOMMAND (result,"t",(tagval *v),{*commandret=*v;v->type=VAL_NULL;})
void format (tagval *args, int numargs)
COMMAND (format,"V")
static void skiplist (const char *&p)
static bool parselist (const char *&s, const char *&start=liststart, const char *&end=listend, const char *&quotestart=listquotestart, const char *&quoteend=listquoteend)
void explodelist (const char *s, vector< char * > &elems, int limit)
char * indexlist (const char *s, int pos)
int listlen (const char *s)
ICOMMAND (listlen,"s",(char *s), intret(listlen(s)))
void at (tagval *args, int numargs)
COMMAND (at,"si1V")
void substr (char *s, int *start, int *count, int *numargs)
COMMAND (substr,"siiN")
void sublist (const char *s, int *skip, int *count, int *numargs)
COMMAND (sublist,"siiN")
ICOMMAND (stripcolors,"s",(char *s),{int len=strlen(s);char *d=newstring(len);filtertext(d, s, true, false, len);stringret(d);})
static void setiter (ident &id, char *val, identstack &stack)
void listfind (ident *id, const char *list, const uint *body)
COMMAND (listfind,"rse")
void looplist (ident *id, const char *list, const uint *body)
COMMAND (looplist,"rse")
void looplistconc (ident *id, const char *list, const uint *body, bool space)
ICOMMAND (looplistconcat,"rse",(ident *id, char *list, uint *body), looplistconc(id, list, body, true))
ICOMMAND (looplistconcatword,"rse",(ident *id, char *list, uint *body), looplistconc(id, list, body, false))
void listfilter (ident *id, const char *list, const uint *body)
COMMAND (listfilter,"rse")
void prettylist (const char *s, const char *conj)
COMMAND (prettylist,"ss")
int listincludes (const char *list, const char *needle, int needlelen)
ICOMMAND (indexof,"ss",(char *list, char *elem), intret(listincludes(list, elem, strlen(elem))))
char * listdel (const char *s, const char *del)
ICOMMAND (listdel,"ss",(char *list, char *del), commandret->setstr(listdel(list, del)))
void listsplice (const char *s, const char *vals, int *skip, int *count)
COMMAND (listsplice,"ssii")
ICOMMAND (loopfiles,"rsse",(ident *id, char *dir, char *ext, uint *body),{if(id->type!=ID_ALIAS) return;identstack stack;vector< char * > files;listfiles(dir, ext[0]?ext:NULL, files);loopvrev(files){char *file=files[i];bool redundant=false;loopj(i) if(!strcmp(files[j], file)){redundant=true;break;}if(redundant) delete[] files.removeunordered(i);}loopv(files){char *file=files[i];if(i){if(id->valtype==VAL_STR) delete[] id->val.s;else id->valtype=VAL_STR;id->val.s=file;}else{tagval t;t.setstr(file);pusharg(*id, t, stack);id->flags &=~IDF_UNKNOWN;}execute(body);}if(files.length()) poparg(*id);})
void findfile_ (char *name)
COMMANDN (findfile, findfile_,"s")
void sortlist (char *list, ident *x, ident *y, uint *body)
COMMAND (sortlist,"srre")
ICOMMAND (!,"t",(tagval *a), intret(!getbool(*a)))
ICOMMAND (!=,"ii",(int *a, int *b), intret((int)(*a!=*b)))
ICOMMAND (!=f,"ff",(float *a, float *b), intret((int)(*a!=*b)))
ICOMMAND && e1V (tagval *args, int numargs),{if(!numargs) intret(1
else loopi (numargs)
ICOMMAND & ii (int *a, int *b), intret(*a &*b)
ICOMMAND * f (float *a, float *b), floatret(*a **b)
ICOMMAND (+,"ii",(int *a, int *b), intret(*a+*b))
ICOMMAND (+f,"ff",(float *a, float *b), floatret(*a+*b))
ICOMMAND (-,"ii",(int *a, int *b), intret(*a-*b))
ICOMMAND (-f,"ff",(float *a, float *b), floatret(*a-*b))
ICOMMAND (<,"ii",(int *a, int *b), intret((int)(*a< *b)))
ICOMMAND (<<,"ii",(int *a, int *b), intret(*b< 32?*a<< max(*b, 0):0))
ICOMMAND (<=,"ii",(int *a, int *b), intret((int)(*a<=*b)))
ICOMMAND (<=f,"ff",(float *a, float *b), intret((int)(*a<=*b)))
ICOMMAND (=,"ii",(int *a, int *b), intret((int)(*a==*b)))
ICOMMAND (=f,"ff",(float *a, float *b), intret((int)(*a==*b)))
ICOMMAND (>,"ii",(int *a, int *b), intret((int)(*a > *b)))
ICOMMAND (>=,"ii",(int *a, int *b), intret((int)(*a >=*b)))
ICOMMAND (>=f,"ff",(float *a, float *b), intret((int)(*a >=*b)))
ICOMMAND (>>,"ii",(int *a, int *b), intret(*a >> clamp(*b, 0, 31)))
ICOMMAND (>f,"ff",(float *a, float *b), intret((int)(*a > *b)))
ICOMMAND (|,"ii",(int *a, int *b), intret(*a|*b))
ICOMMAND (|~,"ii",(int *a, int *b), intret(*a|~*b))
ICOMMAND (~,"i",(int *a), intret(~*a))
ICOMMAND (||,"e1V",(tagval *args, int numargs),{if(!numargs) intret(0);else loopi(numargs){if(i) freearg(*commandret);executeret(args[i].code,*commandret);if(getbool(*commandret)) break;}})
ICOMMAND (acos,"f",(float *a), floatret(acos(*a)/RAD))
ICOMMAND (asin,"f",(float *a), floatret(asin(*a)/RAD))
ICOMMAND (atan,"f",(float *a), floatret(atan(*a)/RAD))
ICOMMAND (atan2,"ff",(float *y, float *x), floatret(atan2(*y,*x)/RAD))
ICOMMAND (cos,"f",(float *a), floatret(cos(*a *RAD)))
ICOMMAND (div,"ii",(int *a, int *b), intret(*b?*a/*b:0))
ICOMMAND (divf,"ff",(float *a, float *b), floatret(*b?*a/*b:0))
ICOMMAND (exp,"f",(float *a), floatret(exp(*a)))
ICOMMAND (log10,"f",(float *a), floatret(log10(*a)))
ICOMMAND (log2,"f",(float *a), floatret(log2f(*a)))
ICOMMAND (loge,"f",(float *a), floatret(log(*a)))
ICOMMAND (mod,"ii",(int *a, int *b), intret(*b?*a%*b:0))
ICOMMAND (modf,"ff",(float *a, float *b), floatret(*b?fmod(*a,*b):0))
ICOMMAND (pow,"ff",(float *a, float *b), floatret(pow(*a,*b)))
ICOMMAND (sin,"f",(float *a), floatret(sin(*a *RAD)))
ICOMMAND (sqrt,"f",(float *a), floatret(sqrt(*a)))
ICOMMAND (tan,"f",(float *a), floatret(tan(*a *RAD)))
ICOMMAND (min,"V",(tagval *args, int numargs),{int val=numargs > 0?args[numargs-1].getint():0;loopi(numargs-1) val=min(val, args[i].getint());intret(val);})
ICOMMAND (max,"V",(tagval *args, int numargs),{int val=numargs > 0?args[numargs-1].getint():0;loopi(numargs-1) val=max(val, args[i].getint());intret(val);})
ICOMMAND (minf,"V",(tagval *args, int numargs),{float val=numargs > 0?args[numargs-1].getfloat():0.0f;loopi(numargs-1) val=min(val, args[i].getfloat());floatret(val);})
ICOMMAND (maxf,"V",(tagval *args, int numargs),{float val=numargs > 0?args[numargs-1].getfloat():0.0f;loopi(numargs-1) val=max(val, args[i].getfloat());floatret(val);})
ICOMMAND (abs,"i",(int *n), intret(abs(*n)))
ICOMMAND (absf,"f",(float *n), floatret(fabs(*n)))
ICOMMAND (cond,"ee2V",(tagval *args, int numargs),{for(int i=0;i< numargs;i+=2){if(i+1< numargs){if(executebool(args[i].code)){executeret(args[i+1].code,*commandret);break;}}else{executeret(args[i].code,*commandret);break;}}})
CASECOMMAND (case,"i", int, args[0].getint(), args[i].type==VAL_NULL||args[i].getint()==val)
CASECOMMAND (casef,"f", float, args[0].getfloat(), args[i].type==VAL_NULL||args[i].getfloat()==val)
CASECOMMAND (cases,"s", const char *, args[0].getstr(), args[i].type==VAL_NULL||!strcmp(args[i].getstr(), val))
ICOMMAND (!=s,"ss",(char *a, char *b), intret(strcmp(a, b)!=0))
ICOMMAND (<=s,"ss",(char *a, char *b), intret(strcmp(a, b)<=0))
ICOMMAND (=s,"ss",(char *a, char *b), intret(strcmp(a, b)==0))
ICOMMAND (>=s,"ss",(char *a, char *b), intret(strcmp(a, b)>=0))
ICOMMAND (>s,"ss",(char *a, char *b), intret(strcmp(a, b)>0))
ICOMMAND (codestr,"i",(int *i),{char *s=newstring(1);s[0]=char(*i);s[1]= '\0';stringret(s);})
ICOMMAND (echo,"C",(char *s), Log.std->info("{}{}", COL_GREEN, s);)
ICOMMAND (error,"C",(char *s), Log.std->error(s);)
ICOMMAND (rnd,"ii",(int *a, int *b), intret(*a-*b > 0?rnd(*a-*b)+*b:*b))
ICOMMAND (strcmp,"ss",(char *a, char *b), intret(strcmp(a, b)==0))
ICOMMAND (strcode,"si",(char *s, int *i), intret(*i > 0?(memchr(s, 0,*i)?0:uchar(s[*i])):uchar(s[0])))
ICOMMAND (strlen,"s",(char *s), intret(strlen(s)))
ICOMMAND (strstr,"ss",(char *a, char *b),{char *s=strstr(a, b);intret(s?s-a:-1);})
ICOMMAND (struni,"si",(char *s, int *i), intret(*i > 0?(memchr(s, 0,*i)?0:cube2uni(s[*i])):cube2uni(s[0])))
ICOMMAND (unistr,"i",(int *i),{char *s=newstring(1);s[0]=uni2cube(*i);s[1]= '\0';stringret(s);})
STRMAPCOMMAND (strlower, cubelower)
STRMAPCOMMAND (strupper, cubeupper)
char * strreplace (const char *s, const char *oldval, const char *newval)
ICOMMAND (strreplace,"sss",(char *s, char *o, char *n), commandret->setstr(strreplace(s, o, n)))
void strsplice (const char *s, const char *vals, int *skip, int *count)
COMMAND (strsplice,"ssii")
ICOMMAND (getmillis,"i",(int *total), intret(*total?totalmillis:lastmillis))
void addsleep (int *msec, char *cmd)
COMMANDN (sleep, addsleep,"is")
void checksleep (int millis)
void clearsleep (bool clearoverrides)
void clearsleep_ (int *clearoverrides)
COMMANDN (clearsleep, clearsleep_,"i")
Variables
hashnameset< ident > idents
vector< ident * > identmap
ident * dummyident = nullptr
int identflags = 0
nullval nullval
tagval noret = nullval
tagval * commandret = &noret
static bool initedidents = false
static vector< ident > * identinits = nullptr
static UNUSED bool forceinitidents = initidents()
static const char * sourcefile = nullptr
static const char * sourcestr = nullptr
static struct identlink noalias = { nullptr, nullptr, (1<<MAXARGS)-1, nullptr }
static struct identlink * aliasstack = &noalias
static int nodebug = 0
static int rundepth = 0
static string execdir = ""
static string retbuf [4]
static int retidx = 0
static const char * liststart = nullptr
static const char * listend = nullptr
static const char * listquotestart = nullptr
static const char * listquoteend = nullptr
vector< sleepcmd > sleepcmds
Class Documentation
struct identlink
Class Members
identstack * argstack
ident * id
identlink * next
int usedargs
struct sortitem
Class Members
const char * quoteend
const char * quotestart
const char * str
struct sleepcmd
Class Members
char * command
int delay
int flags
int millis
Macro Definition Documentation
#define _GETVAR (id, vartype, name, retval)
Value:
ident *id = idents.access(name); \
    if(!id || id->type!=vartype) return retval;
Referenced by getfvarmax(), getfvarmin(), setfvar(), and setsvar().
#define ARG (n) (id->argmask&(1<<n) ? (void *)args[n].s : (void *)&args[n].i)
#define CALLALIAS (offset)
Value:
{ \
                    identstack argstack[MAXARGS]; \
                    for(int i = 0; i < numargs-offset; i++) \
                        pusharg(*identmap[i], args[i+offset], argstack[i]); \
                    int oldargs = _numargs, newargs = numargs-offset; \
                    _numargs = newargs; \
                    int oldflags = identflags; \
                    identflags |= id->flags&IDF_OVERRIDDEN; \
                    identlink aliaslink = { id, aliasstack, (1<<newargs)-1, argstack }; \
                    aliasstack = &aliaslink; \
                    if(!id->code) id->code = compilecode(id->getstr()); \
                    uint *code = id->code; \
                    code[0] += 0x100; \
                    runcode(code+1, result); \
                    code[0] -= 0x100; \
                    if(int(code[0]) < 0x100) delete[] code; \
                    aliasstack = aliaslink.next; \
                    identflags = oldflags; \
                    for(int i = 0; i < newargs; i++) \
                        poparg(*identmap[i]); \
                    for(int argmask = aliaslink.usedargs&(~0<<newargs), i = newargs; argmask; i++) \
                        if(argmask&(1<<i)) { poparg(*identmap[i]); argmask &= ~(1<<i); } \
                    forcearg(result, op&CODE_RET_MASK); \
                    _numargs = oldargs; \
                    numargs = 0; \
                }
Referenced by runcode().
#define CALLCOM (n)
Value:
switch(n) \
        { \
            case 0: ((comfun)id->fun)(); break; \
            case 1: ((comfun1)id->fun)(ARG(0)); break; \
            case 2: ((comfun2)id->fun)(ARG(0), ARG(1)); break; \
            case 3: ((comfun3)id->fun)(ARG(0), ARG(1), ARG(2)); break; \
            case 4: ((comfun4)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3)); break; \
            case 5: ((comfun5)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4)); break; \
            case 6: ((comfun6)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4), ARG(5)); break; \
            case 7: ((comfun7)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4), ARG(5), ARG(6)); break; \
            case 8: ((comfun8)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4), ARG(5), ARG(6), ARG(7)); break; \
            case 9: ((comfun9)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4), ARG(5), ARG(6), ARG(7), ARG(8)); break; \
            case 10: ((comfun10)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4), ARG(5), ARG(6), ARG(7), ARG(8), ARG(9)); break; \
            case 11: ((comfun11)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4), ARG(5), ARG(6), ARG(7), ARG(8), ARG(9), ARG(10)); break; \
            case 12: ((comfun12)id->fun)(ARG(0), ARG(1), ARG(2), ARG(3), ARG(4), ARG(5), ARG(6), ARG(7), ARG(8), ARG(9), ARG(10), ARG(11)); break; \
        }
Referenced by callcommand(), and runcode().
#define CASECOMMAND (name, fmt, type, acc, compare)
Value:
ICOMMAND(name, fmt "te2V", (tagval *args, int numargs), \
    { \
        type val = acc; \
        int i; \
        for(i = 1; i+1 < numargs; i += 2) \
        { \
            if(compare) \
            { \
                executeret(args[i+1].code, *commandret); \
                return; \
            } \
        } \
    })
#define GETVAR (id, name, retval) _GETVAR(id, ID_VAR, name, retval)
#define ICOMMANDNAME (name) _stdcmd
#define LOOKUP (aval)
Value:
{ \
                    id = identmap[op>>8]; \
                    if(id->flags&IDF_UNKNOWN) debugcode("unknown alias lookup: %s", id->name); \
                    aval; \
                    continue; \
                }
Referenced by runcode().
#define LOOKUPARG (aval, nval)
Value:
{ \
                    id = identmap[op>>8]; \
                    if(!(aliasstack->usedargs&(1<<id->index))) { nval; continue; } \
                    aval; \
                    continue; \
                }
Referenced by runcode().
#define LOOKUPU (aval, sval, ival, ioldval, fval, nval)
Referenced by runcode().
#define MAXRUNDEPTH 255
Referenced by runcode().
#define OVERRIDEVAR (errorval, saveval, resetval, clearval)
Value:
if(identflags&IDF_OVERRIDDEN || id->flags&IDF_OVERRIDE) \
    { \
        if(id->flags&IDF_PERSIST) \
        { \
            debugcode("cannot override persistent variable %s", id->name); \
            errorval; \
        } \
        if(!(id->flags&IDF_OVERRIDDEN)) { saveval; id->flags |= IDF_OVERRIDDEN; } \
        else { clearval; } \
    } \
    else \
    { \
        if(id->flags&IDF_OVERRIDDEN) { resetval; id->flags &= ~IDF_OVERRIDDEN; } \
        clearval; \
    }
Referenced by setfvar(), setfvarchecked(), setsvar(), setsvarchecked(), setvar(), and setvarchecked().
#define STRMAPCOMMAND (name, map)
Value:
ICOMMAND(name, "s", (char *s), \
    { \
        int len = strlen(s); \
        char *m = newstring(len); \
        loopi(len) m[i] = map(s[i]); \
        m[len] = '\0'; \
        stringret(m); \
    })
Typedef Documentation
typedef void(__cdecl * comfun)()
typedef void(__cdecl * comfun1)(void *)
typedef void(__cdecl * comfun10)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun11)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun12)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun2)(void *, void *)
typedef void(__cdecl * comfun3)(void *, void *, void *)
typedef void(__cdecl * comfun4)(void *, void *, void *, void *)
typedef void(__cdecl * comfun5)(void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun6)(void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun7)(void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun8)(void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfun9)(void *, void *, void *, void *, void *, void *, void *, void *, void *)
typedef void(__cdecl * comfunv)(tagval *, int)
Enumeration Type Documentation
anonymous enum
Enumerator
MAXARGS
MAXCOMARGS
Function Documentation
bool addcommand (const char * name, identfun fun, const char * args)
References addident(), fatal(), inexor::util::fmt, ID_COMMAND, MAXARGS, and MAXCOMARGS.
Referenced by modelcommands< MDL, struct MDL::vertmesh >::modelcommand().
static ident* addident (const ident & id) inline static
References vector< T, MINSIZE >::add(), identmap, idents, ident::index, and initedidents.
Referenced by addcommand(), addident(), addkeyword(), fvariable(), initidents(), newident(), setalias(), svariable(), and variable().
void addident (ident * id)
References addident().
bool addkeyword (int type, const char * name)
References addident().
void addsleep (int * msec, char * cmd)
References vector< T, MINSIZE >::add(), sleepcmd::command, sleepcmd::delay, sleepcmd::flags, identflags, lastmillis, inexor::rpc::max(), sleepcmd::millis, and newstring().
void alias (const char * name, const char * str)
References newstring(), setalias(), and tagval::setstr().
Referenced by guibutton(), guiimage(), game::parsemessages(), delayedupdate::run(), hline::run(), and game::captureclientmode::setup().
void alias (const char * name, tagval & v)
References setalias().
void at (tagval * args, int numargs)
References commandret, gle::end(), tagval::getint(), tagval::getstr(), newstring(), parselist(), tagval::setstr(), and recorder::start().
Referenced by ai::init(), game::parsemessages(), and BIH::triintersect().
static void callcommand (ident * id, tagval * args, int numargs, bool lookup = false) inline static
References addreleaseaction(), CALLCOM, cleanup(), CODE_EXIT, CODE_START, compilemain(), conc(), vector< T, MINSIZE >::disown(), dummyident, f(), inexor::util::fmt, forcefloat(), forceident(), forceint(), forcestr(), freearg(), ident::fun, vector< T, MINSIZE >::getbuf(), getstr(), loopk, inexor::rpc::max(), ident::name, newstring(), vector< T, MINSIZE >::reserve(), tagval::setcode(), tagval::setfloat(), tagval::setident(), tagval::setint(), tagval::setnull(), and tagval::setstr().
Referenced by runcode().
CASECOMMAND (case , "i" , int , args. getint()[0], args. type[i] = =VAL_NULL||args[i].getint()==val)
CASECOMMAND (casef , "f" , float , args. getfloat()[0], args. type[i] = =VAL_NULL||args[i].getfloat()==val)
CASECOMMAND (cases , "s" , const char * , args. getstr()[0], args. type[i] = =VAL_NULL||!strcmp(args[i].getstr(), val))
void changedvars ()
References vector< T, MINSIZE >::add(), enumerate, hmap::flags, idents, IDF_OVERRIDDEN, loopv, printvar(), and vector< T, MINSIZE >::sortname().
static bool checknumber (const char * s) inline static
Referenced by compilestatements(), newident(), runcode(), and setalias().
void checksleep (int millis)
References sleepcmd::command, sleepcmd::delay, execute(), sleepcmd::flags, identflags, vector< T, MINSIZE >::inrange(), loopv, sleepcmd::millis, and vector< T, MINSIZE >::remove().
Referenced by main().
float clampfvar (ident * id, float val, float minval, float maxval)
References debugcode(), floatstr(), and ident::name.
Referenced by setfvarchecked().
int clampvar (ident * id, int val, int minval, int maxval)
References debugcode(), ident::flags, IDF_HEX, and ident::name.
Referenced by setvarchecked().
static void cleancode (ident & id) inline static
Referenced by clearoverride(), loopiter(), sortfun::operator()(), poparg(), pusharg(), setalias(), setarg(), and setiter().
void clear_command ()
References DELETEA, enumerate, ID_ALIAS, and idents.
Referenced by cleanup().
void clearoverride (ident & i)
References ident::changed(), cleancode(), ident::flags, ID_ALIAS, ID_FVAR, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, IDF_OVERRIDDEN, newstring(), ident::type, and VAL_STR.
Referenced by clearoverrides(), and resetvar().
void clearoverrides ()
References clearoverride(), enumerate, and idents.
Referenced by resetmap().
void clearsleep (bool clearoverrides)
References hmap::flags, IDF_OVERRIDDEN, loopv, and vector< T, MINSIZE >::shrink().
Referenced by clearsleep_(), and resetmap().
void clearsleep_ (int * clearoverrides)
References clearsleep(), identflags, and IDF_OVERRIDDEN.
COMMAND (resetvar , "s")
COMMAND (writecfg , "s")
COMMAND (changedvars , "")
COMMAND (concat , "V")
COMMAND (concatword , "V")
COMMAND (format , "V")
COMMAND (at , "si1V")
COMMAND (substr , "siiN")
COMMAND (sublist , "siiN")
COMMAND (listfind , "rse")
COMMAND (looplist , "rse")
COMMAND (listfilter , "rse")
COMMAND (prettylist , "ss")
COMMAND (listsplice , "ssii")
COMMAND (sortlist , "srre")
COMMAND (strsplice , "ssii")
COMMANDN (findfile , findfile_ , "s")
COMMANDN (sleep , addsleep , "is")
COMMANDN (clearsleep , clearsleep_ , "i")
static bool compilearg (vector< uint > & code, const char *& p, int wordtype) inline static
References compileval(), and compileword().
Referenced by compileblocksub(), and compilestatements().
static void compileblock (vector< uint > & code) inline static
References vector< T, MINSIZE >::add(), CODE_BLOCK, CODE_EXIT, CODE_OFFSET, vector< T, MINSIZE >::length(), and recorder::start().
Referenced by compileblock(), compilelookup(), compilestatements(), and compileword().
static void compileblock (vector< uint > & code, const char *& p, int wordtype) static
References vector< T, MINSIZE >::add(), CODE_BLOCK, CODE_COMPILE, CODE_CONCM, CODE_CONCW, CODE_ENTER, CODE_EXIT, CODE_FORCE, CODE_IDENTU, CODE_OFFSET, CODE_RET, compileblock(), compileblockstr(), compileblocksub(), compileident(), compilestatements(), compilestr(), compileval(), debugcodeline(), vector< T, MINSIZE >::length(), MAXARGS, newstring(), parsestring(), vector< T, MINSIZE >::pop(), RET_STR, recorder::start(), VAL_ANY, VAL_CODE, VAL_IDENT, VAL_NULL, and VAL_STR.
static bool compileblockstr (vector< uint > & code, const char * str, const char * end, bool macro) static
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::advance(), CODE_MACRO, CODE_VAL, vector< T, MINSIZE >::length(), parsestring(), vector< T, MINSIZE >::reserve(), RET_STR, and recorder::start().
Referenced by compileblock().
static bool compileblocksub (vector< uint > & code, const char *& p) static
References vector< T, MINSIZE >::add(), CODE_FVAR, CODE_IVAR, CODE_LOOKUP, CODE_LOOKUPARG, CODE_LOOKUPU, CODE_SVAR, compilearg(), compilestr(), cutstring(), ID_ALIAS, ID_FVAR, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, IDF_UNKNOWN, ident::index, iscubealnum(), MAXARGS, newident(), newstring(), RET_STR, recorder::start(), ident::type, and VAL_STR.
Referenced by compileblock().
uint* compilecode (const char * p)
References compilemain(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), and vector< T, MINSIZE >::reserve().
Referenced by guionclear(), and newgui().
static void compilefloat (vector< uint > & code, float f) inline static
References vector< T, MINSIZE >::add(), CODE_VAL, CODE_VALI, f(), and RET_FLOAT.
Referenced by compilefloat(), compilelookup(), compilestatements(), compileval(), and runcode().
static void compilefloat (vector< uint > & code, const char * word = nullptr) inline static
References compilefloat(), f(), and parsefloat().
static void compileident (vector< uint > & code, ident * id) inline static
References vector< T, MINSIZE >::add(), CODE_IDENT, CODE_IDENTARG, ident::index, and MAXARGS.
Referenced by compileblock(), compileident(), compilelookup(), compilestatements(), and compileval().
static void compileident (vector< uint > & code, const char * word = nullptr) inline static
References compileident(), dummyident, IDF_UNKNOWN, and newident().
static void compileint (vector< uint > & code, int i) inline static
References vector< T, MINSIZE >::add(), CODE_VAL, CODE_VALI, and RET_INT.
Referenced by compileint(), compilelookup(), compilestatements(), compileval(), and runcode().
static void compileint (vector< uint > & code, const char * word = nullptr) inline static
References compileint(), and parseint().
static void compilelookup (vector< uint > & code, const char *& p, int ltype) static
References vector< T, MINSIZE >::add(), CODE_COM, CODE_COMC, CODE_COMD, CODE_COMPILE, CODE_COMV, CODE_ENTER, CODE_EXIT, CODE_FVAR, CODE_IDENTU, CODE_IVAR, CODE_LOOKUP, CODE_LOOKUPARG, CODE_LOOKUPU, CODE_RET, CODE_SVAR, compileblock(), compilefloat(), compileident(), compileint(), compilenull(), compilestr(), compileval(), compileword(), cutstring(), cutword(), inexor::util::fmt, ID_ALIAS, ID_COMMAND, ID_FVAR, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, IDF_UNKNOWN, ident::index, MAXARGS, newident(), ident::type, VAL_ANY, VAL_CODE, VAL_FLOAT, VAL_IDENT, VAL_INT, VAL_NULL, and VAL_STR.
Referenced by compileword().
static void compilemain (vector< uint > & code, const char * p, int rettype = VAL_ANY) static
References vector< T, MINSIZE >::add(), CODE_EXIT, CODE_RET, CODE_START, compilestatements(), and VAL_ANY.
Referenced by callcommand(), compilecode(), execute(), executeret(), and runcode().
static void compilenull (vector< uint > & code) inline static
References vector< T, MINSIZE >::add(), CODE_VALI, and RET_NULL.
Referenced by compilelookup(), compilestatements(), and runcode().
static void compilestatements (vector< uint > & code, const char *& p, int rettype, int brak = '\0') static
References vector< T, MINSIZE >::add(), checknumber(), CODE_ALIAS, CODE_ALIASARG, CODE_ALIASU, CODE_CALL, CODE_CALLARG, CODE_CALLU, CODE_COM, CODE_COMC, CODE_COMD, CODE_COMV, CODE_CONC, CODE_FVAR1, CODE_IVAR1, CODE_IVAR2, CODE_IVAR3, CODE_LOCAL, CODE_POP, CODE_PRINT, CODE_RESULT, CODE_RET, CODE_SVAR1, compilearg(), compileblock(), compilefloat(), compileident(), compileint(), compilenull(), compilestr(), compileword(), debugcodeline(), gle::end(), ident::flags, inexor::util::fmt, ID_ALIAS, ID_COMMAND, ID_FVAR, ID_LOCAL, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, idents, IDF_HEX, IDF_UNKNOWN, ident::index, MAXARGS, newident(), RET_STR, skipcomments(), ident::type, VAL_ANY, VAL_CODE, VAL_FLOAT, VAL_IDENT, VAL_INT, and VAL_STR.
Referenced by compileblock(), compilemain(), compileval(), and compileword().
static void compilestr (vector< uint > & code, const char * word, int len, bool macro = false) inline static
References vector< T, MINSIZE >::add(), CODE_MACRO, CODE_VAL, CODE_VALI, gle::end(), vector< T, MINSIZE >::put(), and RET_STR.
Referenced by compileblock(), compileblocksub(), compilelookup(), compilestatements(), compilestr(), and compileval().
static void compilestr (vector< uint > & code, const char * word = nullptr) inline static
References vector< T, MINSIZE >::add(), CODE_VALI, compilestr(), and RET_STR.
static void compileval (vector< uint > & code, int wordtype, char * word, int wordlen) inline static
References vector< T, MINSIZE >::add(), CODE_BLOCK, CODE_EXIT, CODE_OFFSET, compilefloat(), compileident(), compileint(), compilestatements(), compilestr(), vector< T, MINSIZE >::length(), RET_STR, recorder::start(), VAL_ANY, VAL_CODE, VAL_FLOAT, VAL_IDENT, VAL_INT, and VAL_STR.
Referenced by compilearg(), compileblock(), and compilelookup().
static bool compileword (vector< uint > & code, const char *& p, int wordtype, char *& word, int & wordlen) static
References vector< T, MINSIZE >::add(), CODE_COMPILE, CODE_ENTER, CODE_EXIT, CODE_IDENTU, CODE_RET, compileblock(), compilelookup(), compilestatements(), cutstring(), cutword(), skipcomments(), VAL_ANY, VAL_CODE, and VAL_IDENT.
Referenced by compilearg(), compilelookup(), and compilestatements().
static char* conc (vector< char > & buf, tagval * v, int n, bool space, const char * prefix = nullptr, int prefixlen = 0) static
References vector< T, MINSIZE >::add(), f(), floatstr(), vector< T, MINSIZE >::getbuf(), intstr(), loopi(), vector< T, MINSIZE >::put(), VAL_FLOAT, VAL_INT, VAL_MACRO, and VAL_STR.
Referenced by callcommand(), conc(), concat(), concatword(), and runcode().
static char* conc (tagval * v, int n, bool space, const char * prefix, int prefixlen) static
References conc(), f(), floatformat(), intformat(), loopj, inexor::rpc::max(), MAXARGS, MAXSTRLEN, newstring(), VAL_FLOAT, VAL_INT, VAL_MACRO, and VAL_STR.
static char* conc (tagval * v, int n, bool space) inline static
References conc().
static char* conc (tagval * v, int n, bool space, const char * prefix) inline static
References conc().
void concat (tagval * v, int n)
References commandret, conc(), and tagval::setstr().
void concatword (tagval * v, int n)
References commandret, conc(), and tagval::setstr().
static char* cutstring (const char *& p, int & len) inline static
References gle::end(), newstring(), parsestring(), and unescapestring().
Referenced by compileblocksub(), compilelookup(), and compileword().
static char* cutword (const char *& p, int & len) inline static
References newstring(), and parseword().
Referenced by compilelookup(), and compileword().
static void debugalias () static
References aliasstack, Log, ident::name, identlink::next, noalias, and inexor::util::log_manager::std.
Referenced by debugcode(), and debugcodeline().
static void static void debugcode (const char * fmt, ...) static
References debugalias(), defvformatstring, Log, and inexor::util::log_manager::std.
Referenced by clampfvar(), clampvar(), newident(), resetvar(), runcode(), setalias(), setfvarchecked(), setsvarchecked(), and setvarchecked().
static void static void debugcodeline (const char * p, const char * fmt, ...) static
References debugalias(), defvformatstring, Log, and inexor::util::log_manager::std.
Referenced by compileblock(), and compilestatements().
static const char* debugline (const char * p, const char * fmt) static
References gle::end(), inexor::util::fmt, formatstring(), sourcefile, and sourcestr.
ICOMMAND&& e1V (tagval * args, int numargs)
const char* escapeid (const char * s)
References gle::end(), and escapestring().
Referenced by escapeid(), writecfg(), and writecompletions().
const char* escapestring (const char * s)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::put(), and vector< T, MINSIZE >::setsize().
Referenced by escapeid(), writebinds(), writecfg(), game::writeclientinfo(), writecompletions(), and writecrosshairs().
bool execfile (const char * cfgfile, bool msg)
References copystring(), execute(), getcurexecdir(), loadfile(), Log, makerelpath(), parentdir(), path(), sourcefile, sourcestr, and inexor::util::log_manager::std.
Referenced by emptymap(), md3::load(), obj::load(), md2::load(), iqm::load(), md5::load(), smd::load(), load_world(), loadshaders(), and main().
int execute (const uint * code)
References freearg(), tagval::getint(), result(), and runcode().
Referenced by game::allowedittoggle(), checksleep(), clearguis(), defershader(), entities::doleveltrigger(), execbind(), execfile(), Shader::force(), generateshader(), menu::gui(), guialign(), guilist(), guimerge(), guinoautotab(), guistayopen(), looplist(), main(), game::parsemessages(), pushgui(), delayedupdate::run(), hline::run(), game::startgame(), game::timeupdate(), entities::trypickup(), and vdelta().
int execute (const char * p)
References compilemain(), vector< T, MINSIZE >::disown(), freearg(), vector< T, MINSIZE >::getbuf(), tagval::getint(), vector< T, MINSIZE >::reserve(), result(), runcode(), and VAL_INT.
bool executebool (const uint * code)
References freearg(), getbool(), result(), and runcode().
Referenced by listfilter(), listfind(), and sortfun::operator()().
bool executebool (const char * p)
References executeret(), freearg(), getbool(), and result().
void executeret (const uint * code, tagval & result)
References runcode().
Referenced by executebool(), executestr(), loopconc(), loopi(), and looplistconc().
void executeret (const char * p, tagval & result)
References compilemain(), vector< T, MINSIZE >::disown(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::reserve(), result(), runcode(), and VAL_ANY.
char* executestr (const uint * code)
References forcestr(), result(), runcode(), tagval::type, and VAL_NULL.
Referenced by gl_drawhud().
char* executestr (const char * p)
References executeret(), forcestr(), result(), tagval::type, and VAL_NULL.
void explodelist (const char * s, vector< char * > & elems, int limit)
References vector< T, MINSIZE >::add(), gle::end(), vector< T, MINSIZE >::length(), newstring(), parselist(), and recorder::start().
Referenced by addcomplete(), server::addmaprotations(), server::addteamkillkick(), and skelcommands< MDL >::setanimpart().
ICOMMAND* f (float * a, float * b)
Referenced by vec2::add(), vec::add(), ecjacobian::add(), dvec4::add(), rendertarget::addblurtiles(), addcomplete(), server::adddemo(), game::adddynlights(), server::ctfservermode::addflag(), game::ctfclientmode::addflag(), ctfmode::addflag(), flarerenderer::addflare(), addmergedverts(), addmotionblur(), addnormals(), addtris(), vec4::addw(), skelmodel::blendcombo::addweight(), gui::adjustscale(), game::collectclientmode::aicheck(), game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::collectclientmode::aifind(), game::ctfclientmode::aifind(), game::ctfclientmode::aipursue(), entities::animatemapmodel(), ragdolldata::applyrotfriction(), ragdolldata::applyrotlimit(), avoidcollision(), game::collectclientmode::baseexplosion(), BIH::BIH(), blendfogoverlay(), bounce(), boxs(), boxsgrid(), partrenderer::calc(), matrix3::calcangleaxis(), animmodel::part::calcanim(), animmodel::calcbb(), dynlight::calccolor(), calclight(), calcmodelpreviewpos(), calcnormals(), skelmodel::skeleton::calcpitchcorrects(), dynlight::calcradius(), calcscissorbox(), calcskylight(), calcspherescissor(), calcvert(), callcommand(), canloadsurface(), game::ctfclientmode::checkitems(), inexor::rendering::screen::ScreenManager::cleargamma(), aviwriter::close(), mpr::collide(), compactvslots(), compilefloat(), complete(), computezoom(), conc(), consolebox(), ragdolldata::constraindist(), ragdolldata::constrainrot(), convertoldsurfaces(), cubecollideplanes(), cubecollidesolid(), damagecompass(), game::damageeffect(), rendertarget::debugblurtiles(), rendertarget::debugscissor(), ai::delselwaypoints(), disttoent(), disttooutsideent(), vec2::div(), vec::div(), vec4::div(), vec4::div3(), game::drawammohud(), game::hideandseekclientmode::drawblip(), game::bombclientmode::drawblip(), game::ctfclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), drawcubemap(), drawdamagecompass(), drawdepthfxtex(), drawenvbox(), drawenvoverlay(), drawfogdome(), drawglaretex(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::captureclientmode::drawhud(), recorder::drawhud(), game::drawhudgun(), game::drawhudmodel(), game::drawminimap(), drawminimap(), drawreflection(), drawreflections(), ai::drawroute(), gui::drawskin(), drawskybox(), drawskyoutline(), game::drawteammate(), dropentity(), server::ctfservermode::dropflag(), game::ctfclientmode::dropflag(), droptofloor(), inexor::util::dynamic_pointer_cast(), entities::editent(), ellipseboxcollide(), ellipsecollide(), aviwriter::endlistchunk(), game::explode(), fastskylight(), particleemitter::finalize(), finishlightmap(), ai::fixfullrange(), game::ctfclientmode::flagexplosion(), aviwriter::flushsegment(), forcecubemapload(), forcefloat(), game::gameplayhud(), genclipplanes(), gencubeverts(), gendds(), genedgespanvert(), generatelumel(), genfacevecs(), genpos< PT_TRAIL >(), genprefabmesh(), genpvs(), blobrenderer::gentris(), decalrenderer::gentris(), md2::md2meshgroup::genverts(), vacollect::genverts(), varenderer< T >::genverts(), ai::getaimpos(), getfloat(), getfps_(), ai::getweight(), gl_rendercef(), gl_rendercefmouse(), menu::gui(), game::scoreboardgui::gui(), applymenu::gui(), texturegui::gui(), guicheckbox(), vec::hexcolor(), game::hit(), fpsent::hitpush(), hthash(), game::hudgunorigin(), gui::icon_(), sphere::init(), fogdome::init(), server::ctfservermode::initclient(), game::ctfclientmode::invisflag(), vec::isnormalized(), isshadowmapreceiver(), game::lighteffects(), lightreaching(), gui::line_(), linecylinderintersect(), aviwriter::listchunk(), md3::md3meshgroup::load(), load_world(), md5::md5meshgroup::loadanim(), smd::smdmeshgroup::loadanim(), loaddds(), loadents(), loadfile(), loadhistory(), iqm::iqmmeshgroup::loadiqm(), md5::md5meshgroup::loadmesh(), smd::smdmeshgroup::loadmesh(), vertcommands< MDL >::loadpart(), skelcommands< MDL >::loadpart(), loadprefab(), animmodel::skin::loadshader(), ai::loadwaypoints(), lookupblendmap(), flarerenderer::makelightflares(), makeparticles(), physent::maymove(), mdlalphatest(), gui::modelpreview(), modifygravity(), modifyvelocity(), ragdolldata::move(), move(), moveplayer(), moveragdoll(), vec2::mul(), vec::mul(), vec4::mul(), dvec4::mul(), vec4::mul3(), game::newbouncer(), flarerenderer::newflare(), newfont(), gle::normal(), bvec::normalize(), game::offsetray(), aviwriter::open(), gzstream::open(), utf8stream::open(), inexor::util::StringFormatter::FmtMark::operator<<(), optiface(), server::ctfservermode::ownflag(), game::ctfclientmode::ownflag(), paintblendmap(), server::collectservermode::parsebases(), server::captureservermode::parsebases(), game::ctfclientmode::parseflags(), server::ctfservermode::parseflags(), game::parsemessages(), server::bombservermode::parsespawnloc(), patchlight(), game::ctfclientmode::pickholdspawn(), gui::playerpreview(), pointincube(), gui::prefabpreview(), previewblends(), gui::previewslot(), ai::process(), vec::projectxy(), game::projsplash(), pushscissor(), pushshadowmap(), raycube(), raycubeintersect(), game::raydamage(), recorder::readbuffer(), recalcdir(), recomputecamera(), regularflame(), regularshape(), reloadfonts(), game::ctfclientmode::removeplayer(), flarerenderer::render(), ai::render(), renderbackground(), renderblendbrush(), blobrenderer::renderblob(), game::renderbouncers(), renderclient(), rendereditcursor(), renderellipse(), renderentarrow(), renderentcone(), renderentselection(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), game::ctfclientmode::rendergame(), game::rendergame(), renderlightning(), rendermaterials(), rendermatgrid(), fireballrenderer::renderpart(), meterrenderer::renderpart(), game::bombclientmode::renderplayersposindicator(), renderpostfx(), renderprogress(), game::bombclientmode::renderscoreboard(), game::renderscoreboard(), rendershadowmap(), game::captureclientmode::rendertether(), rendertexturepanel(), rendertarget::rendertiles(), rendervertwater(), renderwater(), vec::rescale(), game::ctfclientmode::resetflag(), resolverwait(), game::ctfclientmode::respawned(), inexor::rendering::screen::ScreenManager::restoregamma(), server::ctfservermode::returnflag(), game::ctfclientmode::returnflag(), hmap::ripple(), runcode(), save_world(), savepng(), saveprefab(), savetga(), ai::savewaypoints(), ai::scaleyawpitch(), delayedupdate::schedule(), game::ctfclientmode::scoreflag(), varenderer< T >::seedemitter(), seedpos(), seedpos< PT_TRAIL >(), hmap::select(), game::selectcrosshair(), game::ctfclientmode::senditems(), skelmodel::blendcombo::serialize(), vec::set(), modelcommands< MDL, struct MDL::vertmesh >::setalphatest(), tagval::setfloat(), setfont(), setfvar(), setscreentexcoord(), animmodel::skin::setshaderparams(), setsunlightdir(), setupcaustics(), server::setupdemorecord(), setupgeom(), server::ctfservermode::setupholdspawns(), setupsurfaces(), shadowent(), shadowray(), game::shorten(), game::shoteffects(), game::spawnnextsplinter(), game::spawnsplinters(), splash(), gui::start(), aviwriter::startchunk(), vec2::sub(), vec::sub(), vec4::subw(), game::swayhudgun(), switchfloor(), game::ctfclientmode::takeflag(), server::ctfservermode::takeflag(), entities::teleport(), texagrad(), texalpha(), texcolor(), texcolorify(), texcolormask(), texmad(), texnormal(), texscroll(), bvec::tocolor(), bvec::tonormal(), bvec4::tonormal(), BIH::triintersect(), entities::trypickup(), trystepup(), unpackvslot(), server::ctfservermode::update(), game::updatebouncers(), inexor::sound::updatechannel(), updateparticles(), game::updateprojectiles(), updateva(), validatec(), valpha(), vcolor(), ai::viewdist(), ai::viewfieldx(), vscale(), game::weaponcollide(), writecfg(), aviwriter::writechunk(), writehistory(), writeinitcfg(), and writeobj().
void findfile_ (char * name)
References copystring(), fileexists(), findfile(), intret(), and path().
void floatret (float v)
References commandret, and tagval::setfloat().
Referenced by getfps_().
const char* floatstr (float v)
References floatformat(), and retidx.
Referenced by clampfvar(), conc(), forcestr(), getstr(), getsval(), printfvar(), runcode(), and writecfg().
static void forcearg (tagval & v, int type) inline static
References forcefloat(), forceint(), forcestr(), RET_FLOAT, RET_INT, RET_STR, tagval::type, VAL_FLOAT, VAL_INT, and VAL_STR.
Referenced by runcode(), and skipcode().
static float forcefloat (tagval & v) inline static
References f(), freearg(), parsefloat(), tagval::setfloat(), tagval::type, VAL_FLOAT, VAL_INT, VAL_MACRO, and VAL_STR.
Referenced by callcommand(), forcearg(), and runcode().
static ident* forceident (tagval & v) inline static
References dummyident, freearg(), IDF_UNKNOWN, newident(), tagval::setident(), tagval::type, VAL_IDENT, VAL_MACRO, and VAL_STR.
Referenced by callcommand(), and runcode().
static int forceint (tagval & v) inline static
References freearg(), parseint(), tagval::setint(), tagval::type, VAL_FLOAT, VAL_INT, VAL_MACRO, and VAL_STR.
Referenced by callcommand(), forcearg(), and runcode().
static void forcenull (tagval & v) inline static
References freearg(), tagval::setnull(), tagval::type, and VAL_NULL.
Referenced by runcode().
static const char* forcestr (tagval & v) inline static
References floatstr(), freearg(), intstr(), newstring(), tagval::setstr(), tagval::type, VAL_FLOAT, VAL_INT, VAL_MACRO, and VAL_STR.
Referenced by callcommand(), executestr(), forcearg(), and runcode().
void format (tagval * args, int numargs)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::getbuf(), tagval::getstr(), and result().
Referenced by addglobalparam(), addlocalparam(), allocglslactiveuniforms(), compressedformat(), cubemaploadwildcard(), gle::defattrib(), gle::defattribs(), gendds(), guessimageformat(), recorder::videobuffer::init(), loaddds(), newtexture(), screenshot(), sendf(), and setglsluniformformat().
static void freearg (tagval & v) inline static
References CODE_START, tagval::type, VAL_CODE, and VAL_STR.
Referenced by callcommand(), tagval::cleanup(), execute(), executebool(), forcefloat(), forceident(), forceint(), forcenull(), forcestr(), freeargs(), loopconc(), loopi(), looplistconc(), runcode(), and setalias().
static void freeargs (tagval * args, int & oldnum, int newnum) inline static
References freearg().
Referenced by runcode().
void freecode (uint * code)
References CODE_OFFSET, CODE_OP_MASK, and CODE_START.
Referenced by menu::clear(), clearguis(), guionclear(), and newgui().
float fvariable (const char * name, float min, float cur, float max, SharedVar< float > * storage, identfun fun, int flags)
References addident(), cur, and ID_FVAR.
const char* getalias (const char * name)
References aliasstack, ident::getstr(), ID_ALIAS, idents, ident::index, MAXARGS, ident::type, and identlink::usedargs.
Referenced by game::captureclientmode::setup().
static bool getbool (const char * s) inline static
References gle::end(), and parsefloat().
Referenced by executebool(), getbool(), and loopi().
static bool getbool (const tagval & v) inline static
References getbool(), tagval::type, VAL_FLOAT, VAL_INT, VAL_MACRO, and VAL_STR.
const char* getcurexecdir ()
References execdir.
Referenced by autograss(), execfile(), fonttex(), newfont(), and texlayer().
float getfvarmax (const char * name)
References _GETVAR, and ID_FVAR.
float getfvarmin (const char * name)
References _GETVAR, and ID_FVAR.
ident* getident (const char * name)
References idents.
Referenced by load_world(), and game::parsemessages().
int getvar (const char * name)
References ID_NOSYNC_VAR, ID_VAR, idents, and ident::type.
int getvarmax (const char * name)
References ID_NOSYNC_VAR, ID_VAR, idents, and ident::type.
Referenced by guislider().
int getvarmin (const char * name)
References ID_NOSYNC_VAR, ID_VAR, idents, and ident::type.
Referenced by guislider().
ICOMMAND (nodebug , "e" , (uint *body) , {nodebug++;executeret(body,*commandret);nodebug--;})
ICOMMAND (push , "rte" , (ident *id, tagval *v, uint *code) , {if(id->type!=ID_ALIAS||id->index< MAXARGS) return;identstack stack;pusharg(*id,*v, stack);v->type=VAL_NULL;id->flags &=~IDF_UNKNOWN;executeret(code,*commandret);poparg(*id);})
ICOMMAND (alias , "st" , (const char *name, tagval *v) , {setalias(name,*v);v->type=VAL_NULL;})
ICOMMAND (getfvarmax , "s" , (char *s) , floatret(getfvarmax(s)))
ICOMMAND (getfvarmin , "s" , (char *s) , floatret(getfvarmin(s)))
ICOMMAND (getvarmax , "s" , (char *s) , intret(getvarmax(s)))
ICOMMAND (getvarmin , "s" , (char *s) , intret(getvarmin(s)))
ICOMMAND (getalias , "s" , (char *s) , result(getalias(s)))
ICOMMAND (exec , "sb" , (char *file, int *msg) , intret(execfile(file,*msg!=0)?1:0))
ICOMMAND (escape , "s" , (char *s) , result(escapestring(s)))
ICOMMAND (unescape , "s" , (char *s) , {int len=strlen(s);char *d=newstring(len);d[unescapestring(d, s,&s[len])]= '\0';stringret(d);})
ICOMMAND (? , "ttt" , (tagval *cond, tagval *t, tagval *f) , result(*(getbool(*cond)?t:f)))
ICOMMAND (do , "e" , (uint *body) , executeret(body,*commandret))
ICOMMAND (if , "tee" , (tagval *cond, uint *t, uint *f) , executeret(getbool(*cond)?t:f,*commandret))
ICOMMAND (pushif , "rte" , (ident *id, tagval *v, uint *code) , {if(id->type!=ID_ALIAS||id->index< MAXARGS) return;if(getbool(*v)){identstack stack;pusharg(*id,*v, stack);v->type=VAL_NULL;id->flags &=~IDF_UNKNOWN;executeret(code,*commandret);poparg(*id);}})
ICOMMAND (loop , "rie" , (ident *id, int *n, uint *body) , {if(*n<=0||id->type!=ID_ALIAS) return;identstack stack;loopi(*n){setiter(*id, i, stack);execute(body);}poparg(*id);})
ICOMMAND (loopwhile , "riee" , (ident *id, int *n, uint *cond, uint *body) , {if(*n<=0||id->type!=ID_ALIAS) return;identstack stack;loopi(*n){setiter(*id, i, stack);if(!executebool(cond)) break;execute(body);}poparg(*id);})
ICOMMAND (while , "ee" , (uint *cond, uint *body) , while(executebool(cond)) execute(body))
ICOMMAND (loopconcat , "rie" , (ident *id, int *n, uint *body) , {if(*n > 0 &&id->type==ID_ALIAS) commandret->setstr(loopconc(id,*n, body, true));})
ICOMMAND (loopconcatword , "rie" , (ident *id, int *n, uint *body) , {if(*n > 0 &&id->type==ID_ALIAS) commandret->setstr(loopconc(id,*n, body, false));})
ICOMMAND (result , "t" , (tagval *v) , {*commandret=*v;v->type=VAL_NULL;})
ICOMMAND (listlen , "s" , (char *s) , intret(listlen(s)))
ICOMMAND (stripcolors , "s" , (char *s) , {int len=strlen(s);char *d=newstring(len);filtertext(d, s, true, false, len);stringret(d);})
ICOMMAND (looplistconcat , "rse" , (ident *id, char *list, uint *body) , looplistconc(id, list, body, true))
ICOMMAND (looplistconcatword , "rse" , (ident *id, char *list, uint *body) , looplistconc(id, list, body, false))
ICOMMAND (indexof , "ss" , (char *list, char *elem) , intret(listincludes(list, elem, strlen(elem))))
ICOMMAND (listdel , "ss" , (char *list, char *del) , commandret-> setstrlistdel(list, del))
ICOMMAND (loopfiles , "rsse" , (ident *id, char *dir, char *ext, uint *body) , {if(id->type!=ID_ALIAS) return;identstack stack;vector< char * > files;listfiles(dir, ext[0]?ext:NULL, files);loopvrev(files){char *file=files[i];bool redundant=false;loopj(i) if(!strcmp(files[j], file)){redundant=true;break;}if(redundant) delete[] files.removeunordered(i);}loopv(files){char *file=files[i];if(i){if(id->valtype==VAL_STR) delete[] id->val.s;else id->valtype=VAL_STR;id->val.s=file;}else{tagval t;t.setstr(file);pusharg(*id, t, stack);id->flags &=~IDF_UNKNOWN;}execute(body);}if(files.length()) poparg(*id);})
ICOMMAND (! , "t" , (tagval *a) , intret(!getbool(*a)))
ICOMMAND (! , "ii" , (int *a, int *b) , intret((int)(*a!=*b)))
ICOMMAND (! = f, "ff" , (float *a, float *b) , intret((int)(*a!=*b)))
ICOMMAND (+ , "ii" , (int *a, int *b) , intret *+* b)
ICOMMAND (+ f, "ff" , (float *a, float *b) , floatret *+* b)
ICOMMAND (- , "ii" , (int *a, int *b) , intret *-* b)
ICOMMAND (- f, "ff" , (float *a, float *b) , floatret *-* b)
ICOMMAND ()
ICOMMAND (<< , "ii" , (int *a, int *b) , intret(*< 32?*<< *, 0b:0)
ICOMMAND (<= , "ii" , (int *a, int *b) , intret((int)(*a<=*b)))
ICOMMAND (<= f, "ff" , (float *a, float *b) , intret((int)(*a<=*b)))
ICOMMAND ("ii" , (int *a, int *b) , intret((int)(*a==*b)))
ICOMMAND ("ff" , (float *a, float *b) , intret((int)(*a==*b)))
ICOMMAND ("ii" , (int *a, int *b) , intret((int)(*a > *b)))
ICOMMAND (>= , "ii" , (int *a, int *b) , intret((int)(*a >=*b)))
ICOMMAND (>= f, "ff" , (float *a, float *b) , intret((int)(*a >=*b)))
ICOMMAND (>> , "ii" , (int *a, int *b) , intret(* >> *, 0, 31b)
ICOMMAND (f , "ff" , (float *a, float *b) , intret((int)(*a > *b)))
ICOMMAND (| , "ii" , (int *a, int *b) , intret *|* b)
ICOMMAND (|~ , "ii" , (int *a, int *b) , intret *|~* b)
ICOMMAND (~ , "i" , (int *a) , intret(~*a))
ICOMMAND (|| , "e1V" , (tagval *args, int numargs) , {if(!numargs) intret(0);else loopi(numargs){if(i) freearg(*commandret);executeret(args[i].code,*commandret);if(getbool(*commandret)) break;}})
ICOMMAND (acos , "f" , (float *a) , floatret(acos(*a)/RAD))
ICOMMAND (asin , "f" , (float *a) , floatret(asin(*a)/RAD))
ICOMMAND (atan , "f" , (float *a) , floatret(atan(*a)/RAD))
ICOMMAND (atan2 , "ff" , (float *y, float *x) , floatret(atan2(*y,*x)/RAD))
ICOMMAND (cos , "f" , (float *a) , floatret(cos(*a *RAD)))
ICOMMAND (div , "ii" , (int *a, int *b) , intret *?*/*:0b)
ICOMMAND (divf , "ff" , (float *a, float *b) , floatret *?*/*:0b)
ICOMMAND (exp , "f" , (float *a) , floatret(exp(*a)))
ICOMMAND (log10 , "f" , (float *a) , floatret(log10(*a)))
ICOMMAND (log2 , "f" , (float *a) , floatret(log2f(*a)))
ICOMMAND (loge , "f" , (float *a) , floatret(log(*a)))
ICOMMAND (mod , "ii" , (int *a, int *b) , intret *?*%*:0b)
ICOMMAND (modf , "ff" , (float *a, float *b) , floatret(*?*,*b:0)
ICOMMAND (pow , "ff" , (float *a, float *b) , floatret(pow(*a,*b)))
ICOMMAND (sin , "f" , (float *a) , floatret(sin(*a *RAD)))
ICOMMAND (sqrt , "f" , (float *a) , floatret(sqrt(*a)))
ICOMMAND (tan , "f" , (float *a) , floatret(tan(*a *RAD)))
ICOMMAND (min , "V" , (tagval *args, int numargs) , {int val=numargs > 0?args[numargs-1].getint():0;loopi(numargs-1) val=min(val, args[i].getint());intret(val);})
ICOMMAND (max , "V" , (tagval *args, int numargs) , {int val=numargs > 0?args[numargs-1].getint():0;loopi(numargs-1) val=max(val, args[i].getint());intret(val);})
ICOMMAND (minf , "V" , (tagval *args, int numargs) , {float val=numargs > 0?args[numargs-1].getfloat():0.0f;loopi(numargs-1) val=min(val, args[i].getfloat());floatret(val);})
ICOMMAND (maxf , "V" , (tagval *args, int numargs) , {float val=numargs > 0?args[numargs-1].getfloat():0.0f;loopi(numargs-1) val=max(val, args[i].getfloat());floatret(val);})
ICOMMAND (abs , "i" , (int *n) , intret(abs(*n)))
ICOMMAND (absf , "f" , (float *n) , floatret(fabs(*n)))
ICOMMAND (cond , "ee2V" , (tagval *args, int numargs) , {for(int i=0;i< numargs;i+=2){if(i+1< numargs){if(executebool(args[i].code)){executeret(args[i+1].code,*commandret);break;}}else{executeret(args[i].code,*commandret);break;}}})
ICOMMAND (! = s, "ss" , (char *a, char *b) , intret(strcmp(a, b)!=0))
ICOMMAND (<= s, "ss" , (char *a, char *b) , intret(strcmp(a, b)<=0))
ICOMMAND ("ss" , (char *a, char *b) , intret(strcmp(a, b)==0))
ICOMMAND (>= s, "ss" , (char *a, char *b) , intret(strcmp(a, b)>=0))
ICOMMAND (s , "ss" , (char *a, char *b) , intret(strcmp(a, b)>0))
ICOMMAND (codestr , "i" , (int *i) , {char *s=newstring(1);s[0]=char(*i);s[1]= '\0';stringret(s);})
ICOMMAND (echo , "C" , (char *s) , Log.std->info("{}{}", COL_GREEN, s);)
ICOMMAND (error , "C" , (char *s) , Log.std->error(s);)
ICOMMAND (rnd , "ii" , (int *a, int *b) , intret(*-* > 0?*-*b+*b:* b)
ICOMMAND (strcmp , "ss" , (char *a, char *b) , intret(strcmp(a, b)==0))
ICOMMAND (strcode , "si" , (char *s, int *i) , intret(* > 0?(, 0,*i?0:uchar(s[*i]))
ICOMMAND (strlen , "s" , (char *s) , intret(strlen(s)))
ICOMMAND (strstr , "ss" , (char *a, char *b) , {char *s=strstr(a, b);intret(s?s-a:-1);})
ICOMMAND (struni , "si" , (char *s, int *i) , intret(* > 0?(, 0,*i?0:cube2uni(s[*i]))
ICOMMAND (unistr , "i" , (int *i) , {char *s=newstring(1);s[0]=uni2cube(*i);s[1]= '\0';stringret(s);})
ICOMMAND (strreplace , "sss" , (char *s, char *o, char *n) , commandret-> setstrstrreplace(s, o, n))
ICOMMAND (getmillis , "i" , (int *total) , intret *?:lastmillis)
bool identexists (const char * name)
References idents.
Referenced by game::allowedittoggle(), entities::doleveltrigger(), gl_drawhud(), game::parsemessages(), game::startgame(), game::timeupdate(), and entities::trypickup().
ICOMMAND ii (int * a, int * b)
char* indexlist (const char * s, int pos)
References gle::end(), loopi(), newstring(), parselist(), and recorder::start().
Referenced by guinameslider().
static bool initidents () static
References addident(), defformatstring, DELETEP, dummyident, IDF_ARG, IDF_UNKNOWN, initedidents, loopv, MAXARGS, and newident().
void intret (int v)
References commandret, and tagval::setint().
Referenced by curblendbrush(), entattr(), findfile_(), getcurtex(), getfps_(), getseltex(), glext(), listfind(), inexor::sound::mapsound(), inexor::sound::registersound(), and game::setmode().
const char* intstr (int v)
References intformat(), and retidx.
Referenced by conc(), forcestr(), getstr(), delayedupdate::getstring(), getsval(), guilistslider(), runcode(), gui::slider(), and gui::tab().
void keepcode (uint * code)
References CODE_OFFSET, CODE_OP_MASK, and CODE_START.
KEYWORD (local , ID_LOCAL)
char* listdel (const char * s, const char * del)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::empty(), gle::end(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), listincludes(), newstring(), parselist(), vector< T, MINSIZE >::put(), and recorder::start().
void listfilter (ident * id, const char * list, const uint * body)
References vector< T, MINSIZE >::add(), commandret, gle::end(), executebool(), vector< T, MINSIZE >::getbuf(), ID_ALIAS, vector< T, MINSIZE >::length(), newstring(), parselist(), poparg(), vector< T, MINSIZE >::put(), setiter(), tagval::setstr(), recorder::start(), and ident::type.
void listfind (ident * id, const char * list, const uint * body)
References gle::end(), executebool(), ID_ALIAS, intret(), newstring(), parselist(), poparg(), setiter(), recorder::start(), and ident::type.
int listincludes (const char * list, const char * needle, int needlelen)
References gle::end(), parselist(), and recorder::start().
Referenced by listdel().
int listlen (const char * s)
References parselist().
Referenced by prettylist().
void listsplice (const char * s, const char * vals, int * skip, int * count)
References vector< T, MINSIZE >::add(), commandret, vector< T, MINSIZE >::empty(), gle::end(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), loopi(), inexor::rpc::max(), newstring(), parselist(), vector< T, MINSIZE >::put(), tagval::setstr(), skiplist(), and recorder::start().
char* loopconc (ident * id, int n, uint * body, bool space)
References vector< T, MINSIZE >::add(), executeret(), freearg(), vector< T, MINSIZE >::getbuf(), tagval::getstr(), vector< T, MINSIZE >::length(), loopi(), newstring(), poparg(), vector< T, MINSIZE >::put(), and setiter().
void loopend (ident * id, identstack & stack)
References poparg().
else loopi (numargs)
References commandret, executeret(), freearg(), and getbool().
Referenced by capturemode_common::addbase(), addblendbrush(), addlight(), addmergedverts(), game::addmsg(), addnormals(), listrenderer::addpart(), addreflection(), depthfxtexture::addscissorbox(), addskyverts(), addtris(), game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), allocglslactiveuniforms(), animategrass(), ai::anynode(), skelmodel::skeleton::applybonemask(), server::autoteam(), avoidcollision(), BIH::BIH(), binddepthfxparams(), blitblendmap(), rendertarget::blur(), bounce(), boxs3D(), BIH::build(), ai::wpcache::build(), animmodel::mesh::buildnorms(), md5::md5mesh::buildverts(), ai::buildwpcache(), skelmodel::skeleton::calcantipodes(), vertmodel::vertmesh::calcbb(), skelmodel::skelmesh::calcbb(), calclightningjitter(), calcnormals(), pvsworker::calcpvs(), calcscissorbox(), shaft::calcshaft(), ImageData::calcsize(), calcskylight(), animmodel::mesh::calctangents(), aiman::calcteams(), calcvfcD(), checkdynentcache(), checkgrayscale(), server::checkserversockets(), skelmodel::skeleton::checkskelcache(), server::chooseworstteam(), cleanreflections(), queryframe::cleanup(), Shader::cleanup(), vertmodel::vertmeshgroup::cleanup(), skelmodel::skelmeshgroup::cleanup(), cleanupblobs(), cleanupdecals(), cleanupmaterialslots(), cleanupparticles(), cleanupva(), QuadNode::clear(), vacollect::clear(), cleardecals(), cleardynentcache(), cleargui(), clearparticles(), clearqueries(), clearslots(), clearsurfaces(), clearvas(), ai::clearwpcache(), blobrenderer::clip(), decalrenderer::clip(), clipfacevecs(), clipminimap(), clippoly(), mpr::collide(), compactvslots(), compileglslshader(), pvsworker::compresspvs(), conc(), consolekey(), ragdolldata::constrain(), convertoldsurfaces(), LightMap::copy(), copycube(), copylightmap(), editor::copyselectionto(), copyundoents(), countblock(), countviewcells(), game::createrays(), cubecollideplanes(), cubemaploadwildcard(), pvsworker::cullpvs(), game::cycleweapon(), game::deathstate(), rendertarget::debugblurtiles(), debugparticles(), discardchildren(), vec::dist_to_bb(), game::drawammohud(), drawconlines(), drawdamagecompass(), drawenvoverlay(), game::drawminimap(), drawminimap(), drawreflections(), ai::drawroute(), gui::drawskin(), server::collectservermode::droptokens(), editmat(), edittexcube(), emptymap(), endmodelbatches(), endmodelquery(), enlargeblendmap(), enlargemap(), entinmap(), game::explode(), familysize(), fastshader(), fastskylight(), fillblendmap(), vertmodel::vertmesh::fillverts(), skelmodel::skelmesh::fillverts(), ai::waypoint::find(), vector< facebounds >::find(), findanims(), ai::findassist(), skelmodel::skeleton::findbone(), fireballrenderer::finddepthfxranges(), finddepthfxranges(), blobrenderer::findescaped(), decalrenderer::findescaped(), findmaterial(), findmaterialname(), blobrenderer::findmaterials(), decalrenderer::findmaterials(), findmergedfaces(), server::maprotation::findmode(), findplayerspawn(), findslottex(), vertmodel::vertmeshgroup::findtag(), findwaterplanes(), gzstream::finishreading(), fixinsidefaces(), fixrotatedlightmaps(), queryframe::flip(), flipcube(), flushblobs(), flushvbo(), fontskip(), forcecubemapload(), forcemip(), freeblock(), freeocta(), fuzzycollideplanes(), genclipplanes(), gencubeedges(), gencubeverts(), gendynlightvariant(), genenvmap(), generategrass(), generatelightmap(), generatelightmaps(), gengrassquads(), genmatsurfs(), QuadNode::genmatsurfs(), genmergedfaces(), genmerges(), genprefabmesh(), genpvs(), genpvsnodes(), tiger::gensboxes(), genskyfaces(), BlendBrush::gentex(), blobrenderer::gentris(), decalrenderer::gentris(), genvbo(), vertmodel::vertmesh::genvbo(), skelmodel::skelmesh::genvbo(), md2::md2meshgroup::genverts(), varenderer< T >::genverts(), pvsworker::genviewcell(), genviewcells(), getcubevector(), getfps(), stream::getline(), getmaterial(), getmaterialdesc(), getmippedtexture(), game::getweapon(), game::gibeffect(), gl_drawhud(), game::groupplayers(), guessimageformat(), texturegui::gui(), halvetexture(), ai::hasgoodammo(), hashstring(), ai::aiinfo::hasprevnode(), hastexcube(), pvsworker::hidepvs(), htcmp(), vector< facebounds >::htfind(), hthash(), indexlist(), sphere::init(), fogdome::init(), initdecals(), initlerpbounds(), editor::input(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::insert(), insideface(), skelmodel::skeleton::interpbones(), game::intersectclosest(), invalidatemerges(), ai::invalidatewpcache(), invertblendmap(), isallclip(), isallempty(), isfoggedcube(), isfoggedsphere(), ishiddencube(), isvalidcube(), isvisiblecube(), isvisiblesphere(), keym::keym(), skelmodel::skeleton::linkchildren(), linkedpush(), linkglslprogram(), linkslotshaders(), ai::linkwaypoint(), listsplice(), obj::objmeshgroup::load(), inexor::sound::soundsample::load(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), load_world(), loadblendmap(), loadc(), loadcaustics(), loadchildren(), loadents(), iqm::iqmmeshgroup::loadiqmanims(), iqm::iqmmeshgroup::loadiqmmeshes(), loadmodel(), loadpvs(), loadsky(), loadviewcells(), loadvslot(), loadvslots(), ai::loadwaypoints(), lockpvs_(), loopconc(), make_file_packet(), materialreset(), mergefaces(), mergemats(), mergepolys(), mergepvsnodes(), mergetexs(), mincubeface(), movecamera(), moveplayer(), mpeditface(), mpremip(), mpreplacetex(), mprotate(), bigint< BI_DIGITS >::mul(), newcubes(), newtexture(), game::nextweapon(), occludesface(), aviwriter::open(), skelmodel::animcacheentry::operator==(), optimizeblendmap(), optimizematsurfs(), packblock(), packcube(), packundo(), packvslots(), ipmask::parse(), game::captureclientmode::parse_network_message(), server::collectservermode::parsebases(), server::captureservermode::parsebases(), bigint< BI_DIGITS >::parsedigits(), game::ctfclientmode::parseflags(), server::ctfservermode::parseflags(), ai::parseinterests(), game::parsemessages(), server::parsepacket(), server::bombservermode::parsespawnloc(), game::parsestate(), game::collectclientmode::parsetokens(), obj::objmeshgroup::parsevert(), particle_trail(), particleinit(), pasteundoents(), pointincube(), game::ctfclientmode::preload(), game::collectclientmode::preload(), game::captureclientmode::preload(), game::preloadbouncers(), entities::preloadentities(), game::preloadplayermodel(), game::preloadweapons(), previewblends(), previewlightmapalpha(), ipmask::print(), server::prunedemos(), QuadNode::QuadNode(), queryreflections(), ai::randomlink(), game::raydamage(), recorder::readbuffer(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readtriangles(), reduceslope(), regularflame(), regularshape(), skelmodel::skeleton::remapbones(), vacollect::remapunlit(), remapvslots(), ai::remapwaypoints(), remip(), server::projectilestate< 8 >::remove(), editor::removelines(), vector< facebounds >::removeobj(), game::removeprojectiles(), removetrackedparticles(), flarerenderer::render(), vertmodel::vertmeshgroup::render(), animmodel::part::render(), ai::render(), renderbackground(), rendercube(), renderdecals(), renderdepthobstacles(), rendereditcursor(), renderellipse(), renderentarrow(), renderentcone(), renderentring(), fireballrenderer::renderpart(), renderparticles(), game::renderplayerpreview(), renderpostfx(), rendertexturepanel(), renderwater(), BlendBrush::reorient(), reorients3tc(), reorienttexture(), replacetexcube(), vector< facebounds >::replacewithlast(), ai::request(), dynent::reset(), queryframe::reset(), resetfpshistory(), resetqueries(), varenderer< T >::resettracked(), resolverinit(), fpsstate::respawn(), restoregui(), vector< facebounds >::reverse(), hmap::ripple(), rotatecube(), rotatenormals(), ai::route(), runcode(), saveblendmap(), savec(), savepng(), savepvs(), savetga(), saveviewcells(), savevslots(), scaletexture(), editor::selectiontostring(), selextend(), sendf(), server::bombservermode::sendspawnlocs(), server::sendstate(), pvsworker::serializepvs(), gle::setattribs(), setcubevector(), setcubevisibility(), setmat(), setsurface(), setupbb(), setupblurkernel(), setupcaustics(), vacollect::setupdata(), setupmaterials(), setupsurface(), setupsurfaces(), setupthreads(), setva(), setvfcP(), setviewcell(), Shader::Shader(), pvsworker::shaftcullpvs(), ragdollskel::tri::shareverts(), shifttexture(), game::shoteffects(), shrinkmap(), hmap::smooth(), animmodel::mesh::smoothnorms(), skelmodel::blendcombo::sortcmp(), sortmaterials(), sortvisiblevas(), fpsstate::spawnstate(), splash(), blobrenderer::split(), splitocta(), BlendMapNode::splitsolid(), recorder::start(), recorder::stop(), fogdome::subdivide(), subdividecube(), sublist(), mpr::CubePlanes::supportpoint(), testpvs(), texblur(), texflip(), texreorient(), texturereset(), BIH::traverse(), unpackblock(), unpackcube(), unpackundo(), unpackvslot(), unpackvslots(), updateva(), uploadcompressedtexture(), uploadtexture(), validatec(), recorder::videoencoder(), viewcellnode::viewcellnode(), visibleorient(), visibletris(), vismatcmp(), waterpvsoccluded(), writecrosshairs(), BlendMapBranch::~BlendMapBranch(), keym::~keym(), skelmodel::skelmeshgroup::~skelmeshgroup(), vertmodel::vertmeshgroup::~vertmeshgroup(), and viewcellnode::~viewcellnode().
void loopiter (ident * id, identstack & stack, const tagval & v)
References cleancode(), IDF_UNKNOWN, pusharg(), and VAL_STR.
Referenced by loopiter().
void looplist (ident * id, const char * list, const uint * body)
References gle::end(), execute(), ID_ALIAS, newstring(), parselist(), poparg(), setiter(), recorder::start(), and ident::type.
void looplistconc (ident * id, const char * list, const uint * body, bool space)
References vector< T, MINSIZE >::add(), commandret, gle::end(), executeret(), freearg(), vector< T, MINSIZE >::getbuf(), tagval::getstr(), ID_ALIAS, vector< T, MINSIZE >::length(), newstring(), parselist(), poparg(), vector< T, MINSIZE >::put(), setiter(), tagval::setstr(), recorder::start(), and ident::type.
ident* newident (const char * name, int flags)
References addident(), checknumber(), debugcode(), dummyident, ID_ALIAS, idents, and newstring().
Referenced by compileblocksub(), compileident(), compilelookup(), compilestatements(), forceident(), initidents(), runcode(), and writeident().
static bool parselist (const char *& s, const char *& start = liststart, const char *& end = listend, const char *& quotestart = listquotestart, const char *& quoteend = listquoteend) static
References gle::end(), parsestring(), parseword(), skiplist(), and recorder::start().
Referenced by at(), explodelist(), indexlist(), listdel(), listfilter(), listfind(), listincludes(), listlen(), listsplice(), looplist(), looplistconc(), prettylist(), sortlist(), and sublist().
const char* parsestring (const char * p)
Referenced by compileblock(), compileblockstr(), cutstring(), parselist(), and validateblock().
static const char* parseword (const char * p) inline static
Referenced by cutword(), and parselist().
static void popalias (ident & id) inline static
References ID_ALIAS, MAXARGS, and poparg().
Referenced by runcode().
static void poparg (ident & id) inline static
References cleancode(), identstack::next, identstack::val, and VAL_STR.
Referenced by listfilter(), listfind(), loopconc(), loopend(), looplist(), looplistconc(), popalias(), and sortlist().
void prettylist (const char * s, const char * conj)
References vector< T, MINSIZE >::add(), gle::end(), vector< T, MINSIZE >::getbuf(), listlen(), parselist(), vector< T, MINSIZE >::put(), result(), and recorder::start().
void printfvar (ident * id, float f)
References floatstr(), Log, ident::name, and inexor::util::log_manager::std.
Referenced by printvar().
void printsvar (ident * id, const char * s)
References Log, ident::name, and inexor::util::log_manager::std.
Referenced by printvar().
void printvar (ident * id, int i)
References ident::flags, IDF_HEX, Log, ident::name, and inexor::util::log_manager::std.
Referenced by changedvars(), printvar(), and runcode().
void printvar (ident * id)
References ID_FVAR, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, printfvar(), printsvar(), printvar(), and ident::type.
static void pushalias (ident & id, identstack & stack) inline static
References ID_ALIAS, IDF_UNKNOWN, MAXARGS, and pusharg().
Referenced by runcode().
static void pusharg (ident & id, const tagval & v, identstack & stack) inline static
References cleancode(), identstack::next, identstack::val, and identstack::valtype.
Referenced by loopiter(), pushalias(), runcode(), setarg(), setiter(), sortlist(), and writeident().
ident* readident (const char * name)
References aliasstack, idents, ident::index, MAXARGS, and identlink::usedargs.
Referenced by getfval(), getsval(), and getval().
void resetvar (char * name)
References clearoverride(), debugcode(), ident::flags, idents, IDF_READONLY, and ident::name.
void result (tagval & v)
References commandret, tagval::type, and VAL_NULL.
Referenced by enttype(), execute(), executebool(), executeret(), executestr(), gui::field_(), format(), getbind(), getblendbrushname(), getKeyboardModifiers(), gettexname(), getWindowsKeyCode(), guifield(), guikeyfield(), game::hashpwd(), game::listclients(), mapcfgname(), mapname(), mdlname(), gfield::mul(), prettylist(), filestream::printf(), ai::process(), pvsworker::run(), runcode(), and ai::think().
void result (const char * s)
References commandret, newstring(), and tagval::setstr().
static const uint* runcode (const uint * code, tagval & result) static
References vector< T, MINSIZE >::add(), addreleaseaction(), aliasstack, identlink::argstack, CALLALIAS, CALLCOM, callcommand(), checknumber(), CODE_ALIAS, CODE_ALIASARG, CODE_ALIASU, CODE_BLOCK, CODE_CALL, CODE_CALLARG, CODE_CALLU, CODE_COM, CODE_COMC, CODE_COMD, CODE_COMPILE, CODE_COMV, CODE_CONC, CODE_CONCM, CODE_CONCW, CODE_ENTER, CODE_EXIT, CODE_FORCE, CODE_FVAR, CODE_FVAR1, CODE_IDENT, CODE_IDENTARG, CODE_IDENTU, CODE_IVAR, CODE_IVAR1, CODE_IVAR2, CODE_IVAR3, CODE_LOCAL, CODE_LOOKUP, CODE_LOOKUPARG, CODE_LOOKUPU, CODE_MACRO, CODE_OFFSET, CODE_OP_MASK, CODE_POP, CODE_PRINT, CODE_RESULT, CODE_RET_MASK, CODE_START, CODE_SVAR, CODE_SVAR1, CODE_VAL, CODE_VALI, commandret, compilefloat(), compileint(), compilemain(), compilenull(), conc(), debugcode(), vector< T, MINSIZE >::disown(), dummyident, f(), ident::flags, floatstr(), forcearg(), forcefloat(), forceident(), forceint(), forcenull(), forcestr(), freearg(), freeargs(), ident::fun, vector< T, MINSIZE >::getbuf(), ident::getfloat(), ident::getint(), ident::getstr(), ident::getval(), ID_ALIAS, ID_COMMAND, ID_FVAR, ID_LOCAL, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, identmap, idents, IDF_HEX, IDF_UNKNOWN, ident::index, intstr(), LOOKUP, LOOKUPARG, LOOKUPU, loopi(), loopj, MAXARGS, MAXRUNDEPTH, MAXSTRLEN, ident::name, newident(), newstring(), parsefloat(), parseint(), popalias(), printvar(), pushalias(), pusharg(), vector< T, MINSIZE >::reserve(), result(), RET_FLOAT, RET_INT, RET_NULL, RET_STR, rundepth, setalias(), setarg(), tagval::setcode(), tagval::setfloat(), setfvarchecked(), tagval::setident(), tagval::setint(), tagval::setmacro(), tagval::setnull(), tagval::setstr(), setsvarchecked(), setvarchecked(), skipcode(), tagval::type, ident::type, identlink::usedargs, VAL_FLOAT, VAL_INT, VAL_MACRO, VAL_NULL, and VAL_STR.
Referenced by execute(), executebool(), executeret(), and executestr().
static void setalias (ident & id, tagval & v) inline static
References cleancode(), identflags, and VAL_STR.
Referenced by alias(), runcode(), and setalias().
static void setalias (const char * name, tagval & v) static
References addident(), checknumber(), debugcode(), freearg(), ID_ALIAS, identflags, idents, ident::index, MAXARGS, ident::name, newstring(), setalias(), setarg(), and ident::type.
static void setarg (ident & id, tagval & v) inline static
References aliasstack, identlink::argstack, cleancode(), pusharg(), identlink::usedargs, and VAL_STR.
Referenced by runcode(), and setalias().
void setfvar (const char * name, float f, bool dofunc, bool doclamp)
References _GETVAR, f(), ID_FVAR, and OVERRIDEVAR.
Referenced by load_world(), and game::parsemessages().
void setfvarchecked (ident * id, float val)
References game::allowedittoggle(), clampfvar(), debugcode(), ident::flags, identflags, IDF_OVERRIDDEN, IDF_OVERRIDE, IDF_READONLY, ident::name, OVERRIDEVAR, and game::vartrigger().
Referenced by delayedupdate::run(), and runcode().
static void setiter (ident & id, int i, identstack & stack) inline static
References cleancode(), IDF_UNKNOWN, pusharg(), tagval::setint(), anonymous_namespace{utilTest.cpp}::t(), VAL_INT, and VAL_STR.
Referenced by listfilter(), listfind(), loopconc(), looplist(), and looplistconc().
static void setiter (ident & id, char * val, identstack & stack) inline static
References cleancode(), IDF_UNKNOWN, pusharg(), tagval::setstr(), anonymous_namespace{utilTest.cpp}::t(), and VAL_STR.
void setsvar (const char * name, const char * str, bool dofunc)
References _GETVAR, ID_SVAR, newstring(), and OVERRIDEVAR.
Referenced by connectserv(), load_world(), and game::parsemessages().
void setsvarchecked (ident * id, const char * val)
References game::allowedittoggle(), debugcode(), ident::flags, identflags, IDF_OVERRIDDEN, IDF_OVERRIDE, IDF_READONLY, ident::name, newstring(), OVERRIDEVAR, and game::vartrigger().
Referenced by delayedupdate::run(), and runcode().
void setvar (const char * name, int i, bool dofunc, bool doclamp)
References ID_NOSYNC_VAR, ID_VAR, idents, OVERRIDEVAR, and ident::type.
Referenced by connectserv(), emptymap(), load_world(), and game::parsemessages().
void setvarchecked (ident * id, int val)
References game::allowedittoggle(), clampvar(), debugcode(), ident::flags, ID_NOSYNC_VAR, identflags, IDF_OVERRIDDEN, IDF_OVERRIDE, IDF_READONLY, ident::name, OVERRIDEVAR, ident::type, and game::vartrigger().
Referenced by delayedupdate::run(), and runcode().
static const uint* skipcode (const uint * code, tagval & result) static
References CODE_BLOCK, CODE_ENTER, CODE_EXIT, CODE_MACRO, CODE_RET_MASK, CODE_VAL, forcearg(), RET_FLOAT, RET_INT, RET_NULL, and RET_STR.
Referenced by runcode().
static void skipcomments (const char *& p) inline static
Referenced by compilestatements(), and compileword().
static void skiplist (const char *& p) inline static
Referenced by listsplice(), parselist(), and sublist().
void sortlist (char * list, ident * x, ident * y, uint * body)
References vector< T, MINSIZE >::add(), commandret, gle::end(), ident::flags, ID_ALIAS, IDF_UNKNOWN, ai::items(), vector< T, MINSIZE >::length(), loopv, inexor::rpc::max(), newstring(), parselist(), poparg(), pusharg(), sortitem::quoteend, sortitem::quotestart, tagval::setstr(), vector< T, MINSIZE >::sort(), recorder::start(), and ident::type.
void stringret (char * s)
References commandret, and tagval::setstr().
Referenced by tabify().
STRMAPCOMMAND (strlower , cubelower)
STRMAPCOMMAND (strupper , cubeupper)
char* strreplace (const char * s, const char * oldval, const char * newval)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), and newstring().
void strsplice (const char * s, const char * vals, int * skip, int * count)
References commandret, newstring(), and tagval::setstr().
void sublist (const char * s, int * skip, int * count, int * numargs)
References commandret, gle::end(), loopi(), inexor::rpc::max(), newstring(), parselist(), tagval::setstr(), skiplist(), and recorder::start().
void substr (char * s, int * start, int * count, int * numargs)
References commandret, newstring(), and tagval::setstr().
char* svariable (const char * name, const char * cur, SharedVar< char * > * storage, identfun fun, int flags)
References addident(), ID_SVAR, and newstring().
void touchvar (const char * name)
References ID_FVAR, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, idents, and ident::type.
int unescapestring (char * dst, const char * src, const char * end)
References recorder::start().
Referenced by cutstring().
bool validateblock (const char * s)
References parsestring().
Referenced by writebinds(), writecfg(), and writecompletions().
VAR (dbgalias , 0 , 4 , 1000)
int variable (const char * name, int min, int cur, int max, SharedVar< int > * storage, identfun fun, int flags)
References addident(), cur, and ID_VAR.
int variable (const char * name, int min, int cur, int max, int * storage, identfun fun, int flags)
References addident(), cur, and ID_NOSYNC_VAR.
VARN_NOSYNC (numargs , _numargs , MAXARGS , 0 , 0)
void writecfg (const char * name)
References vector< T, MINSIZE >::add(), game::autoexec(), game::defaultconfig(), enumerate, escapeid(), escapestring(), f(), hmap::flags, floatstr(), getstr(), ID_ALIAS, ID_FVAR, ID_NOSYNC_VAR, ID_SVAR, ID_VAR, idents, IDF_OVERRIDDEN, IDF_PERSIST, loopv, openutf8file(), path(), stream::printf(), game::savedconfig(), vector< T, MINSIZE >::sortname(), VAL_FLOAT, VAL_INT, VAL_STR, validateblock(), writebinds(), game::writeclientinfo(), writecompletions(), and writecrosshairs().
Referenced by main(), and quit().
ident* writeident (const char * name, int flags)
References aliasstack, identlink::argstack, ident::index, MAXARGS, newident(), pusharg(), and identlink::usedargs.
Referenced by updateval().
Variable Documentation
struct identlink * aliasstack = &noalias static
Referenced by debugalias(), getalias(), readident(), runcode(), setarg(), and writeident().
tagval * commandret = &noret
Referenced by at(), concat(), concatword(), floatret(), intret(), listfilter(), listsplice(), loopi(), looplistconc(), result(), runcode(), sortlist(), stringret(), strsplice(), sublist(), and substr().
ident* dummyident = nullptr
Referenced by callcommand(), compileident(), forceident(), initidents(), newident(), and runcode().
string execdir = "" static
Referenced by getcurexecdir().
UNUSED bool forceinitidents = initidents() static
int identflags = 0
Referenced by addcomplete(), addsleep(), bindkey(), checksleep(), clearsleep_(), emptymap(), Shader::force(), keymap(), md3::load(), obj::load(), md2::load(), iqm::load(), md5::load(), smd::load(), load_world(), main(), mapmodelreset(), materialreset(), reloadshaders(), setalias(), setfvarchecked(), setsvarchecked(), setvarchecked(), and texturereset().
vector<ident>* identinits = nullptr static
vector<ident *> identmap
Referenced by addident(), and runcode().
hashnameset<ident> idents
Referenced by addident(), changedvars(), clear_command(), clearoverrides(), compilestatements(), complete(), getalias(), getident(), getvar(), getvarmax(), getvarmin(), identexists(), newident(), readident(), resetvar(), runcode(), save_world(), setalias(), setvar(), touchvar(), and writecfg().
bool initedidents = false static
Referenced by addident(), and initidents().
const char * listend = nullptr static
const char * listquoteend = nullptr static
const char * listquotestart = nullptr static
const char* liststart = nullptr static
struct identlink noalias = { nullptr, nullptr, (1<<MAXARGS)-1, nullptr } static
Referenced by debugalias().
int nodebug = 0 static
tagval noret = nullval
nullval nullval
string retbuf[4] static
int retidx = 0 static
Referenced by floatstr(), and intstr().
int rundepth = 0 static
Referenced by runcode().
vector<sleepcmd> sleepcmds
const char* sourcefile = nullptr static
Referenced by debugline(), and execfile().
const char * sourcestr = nullptr static
Referenced by debugline(), and execfile().