Inexor: inexor/shared/cube_tools.hpp File Reference
cube_tools.hpp File Reference
#include <algorithm>
#include <cassert>
#include <cstring>
Classes
struct isclass< T >
Check if a given type is a class.
struct stringslice
Macros
#define ASSERT(c) if(c) {}
#define RESTRICT
#define UNUSED
#define DELETEP(p) if(p) { delete p; p = 0; }
Delete Pointer, Wrapper around delete, sets pointer to NULL afterwards(!).
#define DELETEA(p) if(p) { delete[] p; p = 0; }
Delete Array, Wrapper around delete[], sets pointer to NULL afterwards(!).
#define __cdecl
#define _vsnprintf vsnprintf
Functions
char * copystring (char *d, const char *s, size_t len)
template<size_t N>
char * copystring (char(&d)[N], const char *s)
template<size_t N>
bool matchstring (const char *s, size_t len, const char(&d)[N])
Compare c-strings using memcmp.
char * newstring (size_t l)
char * newstring (const char *s, size_t l)
char * newstring (const char *s)
char * newstring (const stringslice &s)
const char * stringptr (const char *s)
const char * stringptr (const stringslice &s)
int stringlen (const char *s)
int stringlen (const stringslice &s)
char * copystring (char *d, const stringslice &s, size_t len)
template<size_t N>
char * copystring (char(&d)[N], const stringslice &s)
Macro Definition Documentation
#define __cdecl
#define _vsnprintf vsnprintf
Referenced by stream::printf(), and vformatstring().
#define ASSERT (c) if(c) {}
Referenced by calcocclusion(), clipfacevec(), clipfacevecs(), mpr::collide(), editor::currentline(), aviwriter::endchunk(), aviwriter::endlistchunk(), genedgespanvert(), insertlightmap(), insertunlit(), gfield::invert(), main(), vector< facebounds >::operator[](), editor::region(), rendervertwater(), vector< facebounds >::setsize(), setva(), vector< facebounds >::shrink(), gfield::sqrt(), bigint< BI_DIGITS >::sub(), and throttle().
#define DELETEA (p) if(p) { delete[] p; p = 0; }
Delete Array, Wrapper around delete[], sets pointer to NULL afterwards(!).
Referenced by autograss(), md5::md5mesh::cleanup(), blobrenderer::cleanup(), Shader::cleanup(), server::worldstate::cleanup(), recorder::soundbuffer::cleanup(), recorder::videobuffer::cleanup(), skelmodel::skeleton::cleanup(), skelmodel::skelmeshgroup::cleanup(), cleanuptexture(), clear_command(), gzstream::close(), complete(), defershader(), discardchildren(), Shader::force(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), gl_drawhud(), sphere::init(), decalrenderer::init(), blobrenderer::init(), fogdome::init(), varenderer< T >::init(), recorder::videobuffer::init(), skelmodel::skelpart::initanimparts(), inputcommand(), keymap(), recorder::soundbuffer::load(), lockpvs_(), newgui(), newshader(), reloadtex(), renderbackground(), Slot::reset(), hline::restore(), editor::setfile(), blobrenderer::~blobrenderer(), skelmodel::boneinfo::~boneinfo(), decalrenderer::~decalrenderer(), delayedupdate::~delayedupdate(), editor::~editor(), filesval::~filesval(), hline::~hline(), keym::~keym(), animmodel::mesh::~mesh(), animmodel::meshgroup::~meshgroup(), animmodel::part::~part(), prefab::~prefab(), Shader::~Shader(), skelmodel::skelanimspec::~skelanimspec(), skelmodel::skeleton::~skeleton(), skelmodel::skelmesh::~skelmesh(), skelmodel::skelmeshgroup::~skelmeshgroup(), skelmodel::skelpart::~skelpart(), inexor::sound::soundsample::~soundsample(), vertmodel::tag::~tag(), skelmodel::tag::~tag(), vertmodel::vertmesh::~vertmesh(), and vertmodel::vertmeshgroup::~vertmeshgroup().
#define DELETEP (p) if(p) { delete p; p = 0; }
Delete Pointer, Wrapper around delete, sets pointer to NULL afterwards(!).
Referenced by server::adddemo(), cleanragdoll(), PackNode::clear(), QuadNode::clear(), clearpvs(), game::clientdisconnected(), aviwriter::close(), gzstream::close(), utf8stream::close(), aiman::deleteai(), ai::destroy(), server::enddemoplayback(), server::enddemorecord(), flusheditors(), initidents(), QuadNode::insert(), Slot::loadlayermask(), loadmodel(), server::receivefile(), renderclient(), Slot::reset(), server::setupdemoplayback(), server::setupdemorecord(), recorder::start(), recorder::stop(), animmodel::meshgroup::~meshgroup(), skelmodel::skeleton::~skeleton(), and skelmodel::skelmeshgroup::~skelmeshgroup().
#define RESTRICT
Referenced by vertmodel::vertmesh::interpverts().
#define UNUSED
Referenced by main().
Function Documentation
char* copystring (char * d, const char * s, size_t len) inline
References hmap::d, and inexor::rpc::min().
Referenced by aiman::addai(), server::addmaprotation(), addpackagedir(), server::addteaminfo(), server::assign_team(), server::autoteam(), aviwriter::aviwriter(), backup(), aiman::balanceteams(), server::changemap(), complete(), concatstring(), conline(), game::connectattempt(), copystring(), createdir(), cubemaploadwildcard(), capturemode_common::baseinfo::enter(), entname(), execfile(), findfile(), findfile_(), capturemode_common::findscore(), server::findscore(), gendds(), gengenericvariant(), getmapfilename(), gettexture(), ai::init(), capturemode_common::initbase(), inputcommand(), listfiles(), obj::objmeshgroup::load(), load_world(), iqm::iqmmeshgroup::loadanim(), loadents(), iqm::iqmmeshgroup::loadiqmanims(), ai::loadwaypoints(), makerelpath(), mmodel(), newstring(), capturemode_common::baseinfo::occupy(), parentdir(), game::captureclientmode::parse_network_message(), game::parsemessages(), server::parsepacket(), path(), smd::smdmeshgroup::readnodes(), game::receivefile(), registertexture(), renderbackground(), game::captureclientmode::rendergame(), game::rendergame(), hline::restore(), screenshot(), server::serverslice(), server::hideandseekservermode::sethider(), server::hideandseekservermode::setseeker(), game::setteaminfo(), game::captureclientmode::setup(), game::startmap(), game::switchname(), texturedata(), textureload(), server::trykick(), game::captureclientmode::updatebase(), and server::vote().
template<size_t N> char* copystring (char(&) d[N], const char * s) inline
References copystring(), and hmap::d.
char* copystring (char * d, const stringslice & s, size_t len) inline
References hmap::d, stringslice::len, inexor::rpc::min(), and stringslice::str.
template<size_t N> char* copystring (char(&) d[N], const stringslice & s) inline
References copystring(), and hmap::d.
template<size_t N> bool matchstring (const char * s, size_t len, const char(&) d[N]) inline
Compare c-strings using memcmp.
References hmap::d.
Referenced by texturedata().
char* newstring (size_t l) inline
Referenced by addcomplete(), addpackagedir(), skelmodel::skeleton::addskelanim(), addsleep(), inexor::sound::soundtype::addslot(), skelmodel::skeleton::addtag(), alias(), at(), autograss(), bindkey(), callcommand(), clearoverride(), compileblock(), compileblocksub(), complete(), conc(), conline(), cutstring(), cutword(), defershader(), explodelist(), fontalias(), forcestr(), getshaderparamname(), ident::getval(), indexlist(), inputcommand(), keym::keym(), keymap(), listdel(), listdir(), listfilter(), listfind(), listsplice(), obj::objmeshgroup::load(), md3::md3meshgroup::load(), md5::md5mesh::load(), md2::md2meshgroup::load(), md5::md5meshgroup::load(), smd::smdmeshgroup::load(), loadhistory(), iqm::iqmmeshgroup::loadiqmmeshes(), md5::md5meshgroup::loadmesh(), smd::smdmeshgroup::loadmesh(), iqm::iqmmeshgroup::loadmesh(), loadprefab(), loopconc(), loopiter(), looplist(), looplistconc(), modelcommands< MDL, struct MDL::vertmesh >::modelcommand(), newfont(), newgui(), newident(), newshader(), newstring(), onrelease(), particle_textcopy(), preloadmodel(), smd::smdmeshgroup::readtriangles(), registertexture(), renderbackground(), hline::restore(), result(), runcode(), hline::save(), saveprefab(), delayedupdate::schedule(), editor::selectiontostring(), setalias(), editor::setfile(), setsvar(), setsvarchecked(), skelmodel::skelmeshgroup::shareskeleton(), sortlist(), strreplace(), strsplice(), sublist(), substr(), svariable(), tabify(), texlayer(), and editor::tostring().
char* newstring (const char * s, size_t l) inline
References copystring(), and newstring().
char* newstring (const char * s) inline
References hmap::d, and newstring().
char* newstring (const stringslice & s) inline
References stringslice::len, newstring(), and stringslice::str.
int stringlen (const char * s) inline
int stringlen (const stringslice & s) inline
References stringslice::len.
const char* stringptr (const char * s) inline
const char* stringptr (const stringslice & s) inline
References stringslice::str.