Inexor: inexor/texture/cubemap.hpp File Reference
cubemap.hpp File Reference
environment map loading routine.
#include "SDL_opengl.h"
#include "inexor/shared/cube_types.hpp"
Classes
struct cubemapside
Functions
Texture * cubemapload (const char *name, bool mipit=true, bool msg=true, bool transient=false)
Texture * cubemaploadwildcard (Texture *t, const char *name, bool mipit, bool msg, bool transient=false)
void initenvmaps ()
void genenvmaps ()
void clearenvmaps ()
ushort closestenvmap (const vec &o)
ushort closestenvmap (int orient, const ivec &co, int size)
GLuint lookupenvmap (ushort emid)
GLuint lookupenvmap (Slot &slot)
void drawcubemap (int size, const vec &o, float yaw, float pitch, const cubemapside &side)
Variables
cubemapside cubemapsides [6]
Detailed Description
environment map loading routine.
Class Documentation
struct cubemapside
Class Members
bool flipx
bool flipy
const char * name
bool swapxy
GLenum target
Function Documentation
void clearenvmaps ()
References cleanuptexture(), envmaps, loopv, skyenvmap, Texture::TRANSIENT, and Texture::type.
Referenced by cleanuptextures(), and initenvmaps().
ushort closestenvmap (const vec & o)
References vec::dist(), EMID_RESERVED, EMID_SKY, envmaps, loopv, envmap::o, and envmap::radius.
Referenced by closestenvmap(), gencubeverts(), genmergedfaces(), animmodel::render(), and setupmaterials().
ushort closestenvmap (int orient, const ivec & co, int size)
References C, closestenvmap(), dimcoord, dimension, and R.
Texture* cubemapload (const char * name, bool mipit = true, bool msg = true, bool transient = false)
References cubemaploadwildcard(), defformatstring, DIR_SKYBOX, inexor::filesystem::getmediapath(), Log, MAXSTRLEN, inexor::util::log_manager::std, and anonymous_namespace{utilTest.cpp}::t().
Referenced by initenvmaps(), Slot::load(), mdlenvmap(), and modelcommands< MDL, struct MDL::vertmesh >::setenvmap().
Texture* cubemaploadwildcard (Texture * t, const char * name, bool mipit, bool msg, bool transient = false)
References ImageData::align, Texture::ALPHA, alphaformat(), ImageData::bpp, Texture::bpp, ImageData::calclevelsize(), Texture::clamp, tiger::compress(), ImageData::compressed, Texture::COMPRESSED, compressed, compressedformat(), concatstring(), copystring(), createcompressedtexture(), createtexture(), Texture::CUBEMAP, cubemapsides, ImageData::data, cubemapside::flipx, cubemapside::flipy, forcecubemapload(), format(), formatsize(), gettexture(), GLenum(), ImageData::h, Texture::h, Texture::id, ImageData::levels, Log, loopi(), inexor::rpc::max(), inexor::rpc::min(), Texture::mipmap, Texture::name, ImageData::pitch, registertexture(), resizetexture(), inexor::util::log_manager::std, cubemapside::swapxy, anonymous_namespace{utilTest.cpp}::t(), cubemapside::target, texformat(), texreorient(), texturedata(), Texture::TRANSIENT, Texture::type, uncompressedformat(), ImageData::w, Texture::w, Texture::xs, and Texture::ys.
Referenced by cubemapload(), and reloadtexture().
void drawcubemap (int size, const vec & o, float yaw, float pitch, const cubemapside & side)
References matrix4::a, matrix4::b, matrix4::c, camera1, matrix4::d, drawskybox(), drawtex, DRAWTEX_ENVMAP, ENT_CAMERA, f(), farplane, cubemapside::flipx, cubemapside::flipy, gbatches, glde, limitsky(), lookupmaterial(), MATF_INDEX, MATF_VOLUME, physent::o, modelpreview::oldcamera, matrix4::perspective(), physent::pitch, player, projmatrix, renderalphageom(), rendergeom(), rendermapmodels(), physent::reset(), physent::roll, matrix4::scalexy(), setcamprojmatrix(), setfog(), setviewcell(), cubemapside::swapxy, physent::type, visiblecubes(), worldsize, xtraverts, xtravertsva, and physent::yaw.
Referenced by genenvmap().
void genenvmaps ()
References envmap::blur, envmaps, genenvmap(), loopv, inexor::rpc::min(), envmap::o, renderedframe, renderprogress(), envmap::size, and envmap::tex.
Referenced by drawtextures().
void initenvmaps ()
References entity::attr1, entity::attr2, entity::attr3, envmap::blur, clearenvmaps(), cubemapload(), entities::ents, envmaps, ET_ENVMAP, entities::getents(), loopv, entity::o, envmap::o, envmap::radius, envmap::size, skyenvmap, envmap::tex, and entity::type.
Referenced by allchanged().
GLuint lookupenvmap (ushort emid)
References EMID_CUSTOM, EMID_NONE, EMID_RESERVED, EMID_SKY, envmaps, GLuint(), Texture::id, and skyenvmap.
GLuint lookupenvmap (Slot & slot)
References Texture::id, loopv, skyenvmap, Slot::sts, and TEX_ENVMAP.
Referenced by changebatchtmus(), animmodel::render(), rendermaterials(), and renderwater().
Variable Documentation
cubemapside cubemapsides[6]
Referenced by cubemaploadwildcard(), genenvmap(), and loadsky().