Inexor: inexor/engine/depthfx.hpp File Reference
depthfx.hpp File Reference
#include <SDL_opengl.h>
#include "inexor/engine/rendertarget.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/geom.hpp"
Classes
struct depthfxtexture
Functions
void cleanupdepthfx ()
void viewdepthfxtex ()
bool binddepthfxtex ()
void binddepthfxparams (float blend, float minblend=0, bool allow=true, void *owner=nullptr)
void drawdepthfxtex ()
Variables
SharedVar< int > depthfx
SharedVar< int > depthfxsize
SharedVar< int > blurdepthfx
SharedVar< int > depthfxpartblend
SharedVar< int > depthfxblend
SharedVar< int > depthfxscale
SharedVar< int > depthfxbias
SharedVar< int > depthfxscissor
int numdepthfxranges
bool depthfxing
depthfxtexture depthfxtex
Function Documentation
void binddepthfxparams (float blend, float minblend = 0, bool allow = true, void * owner = nullptr)
References depthfx, depthfxbias, depthfxowners, depthfxranges, depthfxscale, depthfxtexture::emulatehighprecision(), depthfxtexture::highprecision(), LOCALPARAMF, loopi(), numdepthfxranges, reflecting, refracting, rendertarget::rendertex, hmap::select(), and texscale().
Referenced by fireballrenderer::renderpart(), and renderparticles().
bool binddepthfxtex ()
References depthfx, glActiveTexture_, numdepthfxranges, reflecting, refracting, and rendertarget::rendertex.
Referenced by renderparticles().
void cleanupdepthfx ()
References rendertarget::cleanup().
Referenced by resetgl().
void drawdepthfxtex ()
References blurdepthfx, depthfx, depthfxsize, f(), and rendertarget::render().
Referenced by gl_drawframe().
void viewdepthfxtex ()
References rendertarget::debug(), and depthfx.
Referenced by gl_drawhud().
Variable Documentation
SharedVar<int> blurdepthfx
Referenced by drawdepthfxtex(), depthfxtexture::emulatehighprecision(), and gl_checkextensions().
SharedVar<int> depthfx
Referenced by binddepthfxparams(), binddepthfxtex(), drawdepthfxtex(), fireballrenderer::startrender(), and viewdepthfxtex().
SharedVar<int> depthfxbias
Referenced by binddepthfxparams(), and fireballrenderer::finddepthfxranges().
SharedVar<int> depthfxblend
Referenced by fireballrenderer::finddepthfxranges(), and fireballrenderer::renderpart().
bool depthfxing
Referenced by depthfxtexture::dorender().
SharedVar<int> depthfxpartblend
Referenced by renderparticles().
SharedVar<int> depthfxscale
Referenced by binddepthfxparams(), depthfxtexture::dorender(), and fireballrenderer::finddepthfxranges().
SharedVar<int> depthfxscissor
Referenced by fireballrenderer::finddepthfxranges().
SharedVar<int> depthfxsize
Referenced by drawdepthfxtex(), and gl_checkextensions().
depthfxtexture depthfxtex
Referenced by fireballrenderer::finddepthfxranges(), renderparticles(), and fireballrenderer::startrender().
int numdepthfxranges
Referenced by binddepthfxparams(), binddepthfxtex(), depthfxtexture::dodebug(), depthfxtexture::dorender(), finddepthfxranges(), depthfxtexture::shouldrender(), and fireballrenderer::startrender().