Inexor: inexor/engine/depthfx.cpp File Reference
depthfx.cpp File Reference
#include <SDL_opengl.h>
#include <algorithm>
#include "inexor/engine/depthfx.hpp"
#include "inexor/engine/explosion.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/particles.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
Macros
#define MAXDFXRANGES 4
Functions
VARP (depthfxfpscale, 1, 4096, 65536)
VARP (depthfxscale, 1, 64, 256)
VARP (depthfxblend, 1, 16, 64)
VARP (depthfxpartblend, 1, 8, 64)
VAR (depthfxmargin, 0, 16, 64)
VAR (depthfxbias, 0, 1, 64)
void cleanupdepthfx ()
VARFP (fpdepthfx, 0, 0, 1, cleanupdepthfx())
VARP (depthfxemuprecision, 0, 1, 1)
VARFP (depthfxsize, 6, 7, 12, cleanupdepthfx())
VARP (depthfx, 0, 1, 1)
VARP (depthfxparts, 0, 1, 1)
VARP (blurdepthfx, 0, 1, 7)
VARP (blurdepthfxsigma, 1, 50, 200)
VAR (depthfxscissor, 0, 2, 2)
VAR (debugdepthfx, 0, 0, 1)
void finddepthfxranges ()
void viewdepthfxtex ()
bool binddepthfxtex ()
void binddepthfxparams (float blend, float minblend, bool allow, void *owner)
void drawdepthfxtex ()
Variables
void * depthfxowners [MAXDFXRANGES]
float depthfxranges [MAXDFXRANGES]
int numdepthfxranges = 0
vec depthfxmin (1e16f, 1e16f, 1e16f)
vec depthfxmax (1e16f, 1e16f, 1e16f)
depthfxtexture depthfxtex
bool depthfxing = false
Macro Definition Documentation
#define MAXDFXRANGES 4
Referenced by finddepthfxranges().
Function Documentation
void binddepthfxparams (float blend, float minblend, bool allow, void * owner)
References depthfx, depthfxbias, depthfxowners, depthfxranges, depthfxscale, depthfxtexture::emulatehighprecision(), depthfxtexture::highprecision(), LOCALPARAMF, loopi(), numdepthfxranges, reflecting, refracting, rendertarget::rendertex, hmap::select(), and texscale().
Referenced by fireballrenderer::renderpart(), and renderparticles().
bool binddepthfxtex ()
References depthfx, glActiveTexture_, numdepthfxranges, reflecting, refracting, and rendertarget::rendertex.
Referenced by renderparticles().
void cleanupdepthfx ()
References rendertarget::cleanup().
Referenced by resetgl().
void drawdepthfxtex ()
References blurdepthfx, depthfx, depthfxsize, f(), and rendertarget::render().
Referenced by gl_drawframe().
void finddepthfxranges ()
References partrenderer::adddepthfx(), depthfxtexture::addscissorbox(), bluefireballs, depthfxmax, depthfxmin, depthfxowners, depthfxranges, fireballrenderer::finddepthfxranges(), fireballs, loopi(), loopk, MAXDFXRANGES, numdepthfxranges, parts, PT_SOFT, and partrenderer::type.
Referenced by depthfxtexture::shouldrender().
VAR (depthfxmargin , 0 , 16 , 64)
VAR (depthfxbias , 0 , 1 , 64)
VAR (depthfxscissor , 0 , 2 , 2)
VAR (debugdepthfx , 0 , 0 , 1)
VARFP (fpdepthfx , 0 , 0 , 1 , cleanupdepthfx())
VARFP (depthfxsize , 6 , 7 , 12 , cleanupdepthfx())
VARP (depthfxfpscale , 1 , 4096 , 65536)
VARP (depthfxscale , 1 , 64 , 256)
VARP (depthfxblend , 1 , 16 , 64)
VARP (depthfxpartblend , 1 , 8 , 64)
VARP (depthfxemuprecision , 0 , 1 , 1)
VARP (depthfx , 0 , 1 , 1)
VARP (depthfxparts , 0 , 1 , 1)
VARP (blurdepthfx , 0 , 1 , 7)
VARP (blurdepthfxsigma , 1 , 50 , 200)
void viewdepthfxtex ()
References rendertarget::debug(), and depthfx.
Referenced by gl_drawhud().
Variable Documentation
bool depthfxing = false
Referenced by depthfxtexture::dorender().
vec depthfxmax(1e16f, 1e16f, 1e16f)
Referenced by depthfxtexture::dorender(), and finddepthfxranges().
vec depthfxmin(1e16f, 1e16f, 1e16f)
Referenced by depthfxtexture::dorender(), and finddepthfxranges().
void* depthfxowners[MAXDFXRANGES]
Referenced by binddepthfxparams(), and finddepthfxranges().
float depthfxranges[MAXDFXRANGES]
Referenced by binddepthfxparams(), depthfxtexture::dorender(), and finddepthfxranges().
depthfxtexture depthfxtex
Referenced by fireballrenderer::finddepthfxranges(), renderparticles(), and fireballrenderer::startrender().
int numdepthfxranges = 0
Referenced by binddepthfxparams(), binddepthfxtex(), depthfxtexture::dodebug(), depthfxtexture::dorender(), finddepthfxranges(), depthfxtexture::shouldrender(), and fireballrenderer::startrender().