Inexor: inexor/engine/dynlight.hpp File Reference
dynlight.hpp File Reference
#include "inexor/shared/geom.hpp"
Enumerations
enum { DL_SHRINK = 1<<0, DL_EXPAND = 1<<1, DL_FLASH = 1<<2 }
Functions
void updatedynlights ()
int finddynlights ()
void calcdynlightmask (vtxarray *va)
int setdynlights (vtxarray *va)
void adddynlight (const vec &o, float radius, const vec &color, int fade=0, int peak=0, int flags=0, float initradius=0, const vec &initcolor=vec(0, 0, 0), physent *owner=nullptr)
void dynlightreaching (const vec &target, vec &color, vec &dir, bool hud=false)
void removetrackeddynlights (physent *owner=nullptr)
Enumeration Type Documentation
anonymous enum
Enumerator
DL_SHRINK
DL_EXPAND
DL_FLASH
Function Documentation
void adddynlight (const vec & o, float radius, const vec & color, int fade = 0, int peak = 0, int flags = 0, float initradius = 0, const vec & initcolor = vec(0, 0, 0), physent * owner = nullptr)
References camera1, dynlight::color, gle::color(), hmap::d, vec::dist(), dynlight::expire, dynlight::fade, dynlight::flags, hmap::flags, dynlight::hud, dynlight::initcolor, dynlight::initradius, vector< T, MINSIZE >::insert(), lastmillis, loopvrev, dynlight::o, physent::o, dynlight::owner, dynlight::peak, and dynlight::radius.
Referenced by game::adddynlights(), game::collectclientmode::baseexplosion(), game::explode(), game::ctfclientmode::flagexplosion(), and game::shoteffects().
void calcdynlightmask (vtxarray * va)
References dynlight::curradius, hmap::d, vec::dist_to_bb(), DYNLIGHTBITS, vtxarray::dynlightmask, vtxarray::geommax, vtxarray::geommin, loopv, and dynlight::o.
Referenced by renderva().
void dynlightreaching (const vec & target, vec & color, vec & dir, bool hud = false)
References vec::add(), dynlight::curcolor, dynlight::curradius, hmap::d, vec::div(), dynlight::hud, vec::iszero(), loopv, vec::magnitude(), vec::mul(), vec::normalize(), dynlight::o, vec::squaredlen(), and vec::sub().
Referenced by rendermodel().
int finddynlights ()
References physent::aboveeye, camera1, mpr::collide(), dynlight::curradius, hmap::d, dynlight::dist, vec::dist(), DYNLIGHTMASK, ENT_CAMERA, physent::eyeheight, vector< T, MINSIZE >::insert(), isfoggedsphere(), vector< T, MINSIZE >::length(), loopvj, loopvrev, dynlight::o, physent::o, pvsoccludedsphere(), physent::radius, reflecting, reflectz, refracting, vector< T, MINSIZE >::setsize(), physent::type, physent::xradius, and physent::yradius.
Referenced by rendergeom().
void removetrackeddynlights (physent * owner = nullptr)
References loopvrev, and vector< T, MINSIZE >::remove().
Referenced by game::clientdisconnected().
int setdynlights (vtxarray * va)
References dynlight::curcolor, dynlight::curradius, hmap::d, DYNLIGHTBITS, vtxarray::dynlightmask, DYNLIGHTMASK, vector< T, MINSIZE >::empty(), GLOBALPARAMV, MAXDYNLIGHTS, minimizedynlighttcusage(), vec::mul(), dynlight::o, and vec::sub().
Referenced by changebatchtmus().
void updatedynlights ()
References game::adddynlights(), dynlight::calccolor(), dynlight::calcradius(), cleardynlights(), hmap::d, game::dynlighttrack(), dynlight::hud, loopv, dynlight::o, and dynlight::owner.
Referenced by gl_drawframe().