Inexor: inexor/engine/frame.cpp File Reference
frame.cpp File Reference
#include <algorithm>
#include "inexor/engine/frame.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/ui/legacy/menus.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
Macros
#define MAXFPSHISTORY 60
frames per seconds and timing
Functions
VAR (menufps, 0, 60, 1000)
VARP (maxfps, 0, 200, 1000)
int get_current_max_fps ()
The current fps limit.
void resetfpshistory ()
clear fps history array
void updatefpshistory (int millis)
add current frames per seconds score to fps history array
void getfps (int &fps, int &bestdiff, int &worstdiff)
get average fps, best fps and worst fps (see command fpsrange)
void getfps_ (int *raw)
cubescript: get fps as float
COMMANDN (getfps, getfps_,"i")
Variables
int fpspos = 0
int fpshistory [MAXFPSHISTORY]
bool inbetweenframes = false
bool renderedframe = true
Macro Definition Documentation
#define MAXFPSHISTORY 60
frames per seconds and timing
store the last MAXFPSHISTORY fps rates
Referenced by getfps(), getfps_(), resetfpshistory(), and updatefpshistory().
Function Documentation
COMMANDN (getfps , getfps_ , "i")
int get_current_max_fps ()
The current fps limit.
References mainmenu, inexor::rpc::min(), inexor::rendering::screen::ScreenManager::minimized, and inexor::rendering::screen::screen_manager.
Referenced by main().
void getfps (int & fps, int & bestdiff, int & worstdiff)
get average fps, best fps and worst fps (see command fpsrange)
References fpshistory, loopi(), and MAXFPSHISTORY.
Referenced by getfps_(), gl_drawhud(), and recorder::start().
void getfps_ (int * raw)
cubescript: get fps as float
See Also
floatret
References f(), floatret(), fpshistory, fpspos, getfps(), intret(), and MAXFPSHISTORY.
void resetfpshistory ()
clear fps history array
References fpshistory, fpspos, loopi(), and MAXFPSHISTORY.
Referenced by main().
void updatefpshistory (int millis)
add current frames per seconds score to fps history array
References fpshistory, fpspos, inexor::rpc::max(), MAXFPSHISTORY, and inexor::rpc::min().
Referenced by main().
VAR (menufps , 0 , 60 , 1000)
VARP (maxfps , 0 , 200 , 1000)
Variable Documentation
int fpshistory[MAXFPSHISTORY]
Referenced by getfps(), getfps_(), resetfpshistory(), and updatefpshistory().
int fpspos = 0
Referenced by getfps_(), resetfpshistory(), and updatefpshistory().
bool inbetweenframes = false
Referenced by commitchanges(), recorder::gettime(), main(), renderbackground(), renderprogress(), and resetgl().
bool renderedframe = true
Referenced by drawminimap(), genenvmaps(), main(), renderbackground(), renderprogress(), and restorebackground().