Inexor: inexor/network/legacy/game_types.hpp File Reference
game_types.hpp File Reference
#include <string.h>
Classes
struct demoheader
demos contain stored network messages of a game which can be replayed to review games
Macros
#define INEXOR_SERVINFO_PORT 31413
This file contains static protocol information for the (soon to be legacy) network code.
#define INEXOR_LANINFO_PORT 31414
#define INEXOR_SERVER_PORT 31415
#define INEXOR_MASTER_PORT 31416
#define INEXOR_DEFAULT_MASTER "master.inexor.org"
#define MAX_POSSIBLE_PORT 65535
#define PROTOCOL_VERSION 303
#define DEMO_VERSION 1
#define DEMO_MAGIC "INEXOR_DEMO"
Enumerations
enum { CHAN_POS = 0, CHAN_MSG, CHAN_FILE, NUM_ENET_CHANNELS }
enum {
N_CONNECT = 0, N_SERVINFO, N_WELCOME, N_INITCLIENT,
N_POS, N_TEXT, N_SOUND, N_CDIS,
N_SHOOT, N_EXPLODE, N_SUICIDE, N_DIED,
N_DAMAGE, N_HITPUSH, N_SHOTFX, N_EXPLODEFX,
N_TRYSPAWN, N_SPAWNSTATE, N_SPAWN, N_FORCEDEATH,
N_GUNSELECT, N_TAUNT, N_FOV, N_MAPCHANGE,
N_MAPVOTE, N_TEAMINFO, N_ITEMSPAWN, N_ITEMPICKUP,
N_ITEMACC, N_ITEMPUSH, N_TELEPORT, N_JUMPPAD,
N_PING, N_PONG, N_CLIENTPING, N_TIMEUP,
N_FORCEINTERMISSION, N_SERVMSG, N_ITEMLIST, N_RESUME,
N_EDITMODE, N_EDITENT, N_EDITF, N_EDITT,
N_EDITM, N_FLIP, N_COPY, N_PASTE,
N_ROTATE, N_REPLACE, N_DELCUBE, N_REMIP,
N_EDITVSLOT, N_UNDO, N_REDO, N_NEWMAP,
N_GETMAP, N_SENDMAP, N_CLIPBOARD, N_EDITVAR,
N_MASTERMODE, N_KICK, N_CLEARBANS, N_CURRENTMASTER,
N_SPECTATOR, N_SETMASTER, N_SETTEAM, N_BASES,
N_BASEINFO, N_BASESCORE, N_REPAMMO, N_BASEREGEN,
N_ANNOUNCE, N_LISTDEMOS, N_SENDDEMOLIST, N_GETDEMO,
N_SENDDEMO, N_DEMOPLAYBACK, N_RECORDDEMO, N_STOPDEMO,
N_CLEARDEMOS, N_TAKEFLAG, N_RETURNFLAG, N_RESETFLAG,
N_INVISFLAG, N_TRYDROPFLAG, N_DROPFLAG, N_SCOREFLAG,
N_INITFLAGS, N_SAYTEAM, N_PRIVMSG, N_HUDANNOUNCE,
N_CLIENT, N_PAUSEGAME, N_GAMESPEED, N_PERSISTTEAMS,
N_ADDBOT, N_DELBOT, N_INITAI, N_FROMAI,
N_BOTLIMIT, N_BOTBALANCE, N_MAPCRC, N_CHECKMAPS,
N_SWITCHNAME, N_SWITCHMODEL, N_SWITCHTEAM, N_INITTOKENS,
N_TAKETOKEN, N_EXPIRETOKENS, N_DROPTOKENS, N_DEPOSITTOKENS,
N_STEALTOKENS, N_SERVCMD, N_DEMOPACKET, N_SPAWNLOC,
NUMMSG
}
server message list
enum {
DISC_NONE = 0, DISC_EOP, DISC_KICK, DISC_MSGERR,
DISC_IPBAN, DISC_PRIVATE, DISC_MAXCLIENTS, DISC_TIMEOUT,
DISC_OVERFLOW, DISC_PASSWORD, DISC_NUM
}
Functions
int lan_info_port ()
int server_info_port (int servport)
int server_port (int infoport=-1)
int msgsizelookup (int msg)
const char * disconnectreason (int reason)
Variables
static const int msgsizes []
size incuding message token, 0 for variable or not-checked sizes
Class Documentation
struct demoheader
demos contain stored network messages of a game which can be replayed to review games
Class Members
char magic[16]
int protocol
int version
Macro Definition Documentation
#define DEMO_MAGIC "INEXOR_DEMO"
Referenced by server::setupdemoplayback(), and server::setupdemorecord().
#define DEMO_VERSION 1
Referenced by server::setupdemoplayback(), and server::setupdemorecord().
#define INEXOR_DEFAULT_MASTER "master.inexor.org"
#define INEXOR_LANINFO_PORT 31414
Referenced by lan_info_port().
#define INEXOR_MASTER_PORT 31416
#define INEXOR_SERVER_PORT 31415
Referenced by server_port().
#define INEXOR_SERVINFO_PORT 31413
This file contains static protocol information for the (soon to be legacy) network code.
constant protocol and version definitions
Referenced by server_info_port().
#define MAX_POSSIBLE_PORT 65535
#define PROTOCOL_VERSION 303
Referenced by game::parsemessages(), server::sendservinfo(), server::servercompatible(), server::serverinforeply(), server::setupdemoplayback(), and server::setupdemorecord().
Enumeration Type Documentation
anonymous enum
Enumerator
CHAN_POS
CHAN_MSG
CHAN_FILE
NUM_ENET_CHANNELS
anonymous enum
server message list
Warning
you will need to edit the msgsizes array as well.
you might get kicked from server because you modified the protocol!
Enumerator
N_CONNECT
N_SERVINFO
C2S send connection request to server.
N_WELCOME
S2C send connection attempt answer (can be denied in case of wrong protocol or server password protection)
N_INITCLIENT
S2C we are now connected. also close my GUI.
N_POS
S2C another client connected or existing client changed name, team, or player model.
N_TEXT
C2S|C2S send player position and rotation.
N_SOUND
C2S send chat message to global game chat.
N_CDIS
C2S send sound signal.
N_SHOOT
S2C a client disconnected.
N_EXPLODE
C2S a shot was fired.
N_SUICIDE
C2S an explosion was triggered (grenades, rockets..)
N_DIED
C2S I suicided (other clients receive N_DIED where actor = victim)
N_DAMAGE
S2C a player got killed (or suicided)
N_HITPUSH
S2C a player got damages.
N_SHOTFX
S2C a player got pushed back.
N_EXPLODEFX
S2C the EFFECT OF A SHOT (see N_SHOT)
N_TRYSPAWN
S2C the EFFECT OF AN EXPLOSION (see N_EXPLODE)
N_SPAWNSTATE
C2S a players tries to spawn.
N_SPAWN
S2C send clients spawn information.
N_FORCEDEATH
C2S|S2C a client is now spawning.
N_GUNSELECT
S2C force a client to die.
N_TAUNT
C2S a client selects a weapon.
N_FOV
C2S|S2C (?) a client sent "Im gonna kill you" animation.
N_MAPCHANGE
C2S|S2C a client has changed its field of view.
N_MAPVOTE
S2C server changed map.
N_TEAMINFO
C2S client suggests a map/mode.
N_ITEMSPAWN
S2C send information about teams and their frags.
N_ITEMPICKUP
S2C an item has spawned.
N_ITEMACC
C2S I just picked up this item.
N_ITEMPUSH
S2C item pickup was acknowledged for a client (item is occupied/despawned. wait for spawn)
N_TELEPORT
C2S lose items when killed (BOMBERMAN)
N_JUMPPAD
C2S|S2C a player in game has teleported to a teleport destination.
N_PING
C2S|S2C a player in game has used a jumppad.
N_PONG
C2S client sends ping packet to server.
N_CLIENTPING
S2C servers answers ping packet.
N_TIMEUP
C2S|S2C send client ping mesaure request / servers sends clients' pings.
N_FORCEINTERMISSION
S2C change remaining time.
N_SERVMSG
S2C server ended current game: set game time to 0 ("intermission")
N_ITEMLIST
S2C server messages can be colored and will be rendered in game console.
N_RESUME
C2S|S2C client request a list of items available in the current match / server answers with list.
N_EDITMODE
S2C resume transmission of new data from lagged client (NOT: RESUMING A PAUSED GAME!)
N_EDITENT
C2S|S2C a player toggled his edit mode on/off (requires editmode)
N_EDITF
S2C a player creates a new entity (requires editmode)
N_EDITT
C2S|S2C a player changed a FACE (requires editmode)
N_EDITM
C2S|S2C a player changed a TEXTURE (requires editmode)
N_FLIP
C2S|S2C a player edited MATERIAL (requires editmode)
N_COPY
C2S|S2C a player flipped the current selection (requires editmode)
N_PASTE
C2S|S2C (?) a player wants to copy a certain selection (requires editmode)
N_ROTATE
C2S|S2C (?) send clipboard to other palyers (requires editmode)
N_REPLACE
C2S|S2C a player rotated a selection (requires editmode)
N_DELCUBE
C2S|S2C a player wants to replace a selection (requires editmode)
N_REMIP
C2S|S2C a player wants to delete a selection (requires editmode)
N_EDITVSLOT
C2S|S2C a client forcedremip (requires editmode, no administrative levels required)
N_UNDO
C2S|S2C a client used a v.. command (vscale, vcolor..) to modify a texture.
N_REDO
C2S|S2C send undo edit message.
N_NEWMAP
C2S|S2C send redo edit message.
N_GETMAP
C2S|S2C a client started a new map (requires editmode)
N_SENDMAP
C2S a client downloaded the current map from server's map buffer (NOT ALWAYS UP TO DATE! MAP MUST BE SENT BEFORE DOWNLOADING!)
N_CLIPBOARD
S2C server sends map to client (requires coop mode. YOU CAN'T SEND MAPS IN INSTACTF e.g. (YET))
N_EDITVAR
C2S send copied data from your clipboard to server.
N_MASTERMODE
C2S|S2C set map var value (requires editmode)
N_KICK
C2S change master mode (requires permissions)
N_CLEARBANS
C2S kick a specific player.
N_CURRENTMASTER
C2S clear ban list.
N_SPECTATOR
S2C server sent information about who is the current game master.
N_SETMASTER
C2S|S2C toggle spectator status.
N_SETTEAM
C2S claim game master.
N_BASES
C2S|S2C team chat.
N_BASEINFO
S2C send a list of available bases in capture mode.
N_BASESCORE
S2C send extended information about bases.
N_REPAMMO
S2C send base score to client.
N_BASEREGEN
S2C replace ammo around bases in capture mode.
N_ANNOUNCE
S2C regen capture: refill health and ammo of players near captured bases.
N_LISTDEMOS
S2C announce spawn of quad damage or health boost (normal capture only)
N_SENDDEMOLIST
C2S request a list of demos available for download.
N_GETDEMO
S2C send a list of demos available for download.
N_SENDDEMO
C2S a client requests to download a demo.
N_DEMOPLAYBACK
S2C server sends a demo.
N_RECORDDEMO
S2C finish demo playback.
N_STOPDEMO
C2S advise the server to record demo.
N_CLEARDEMOS
C2S finish demo recording add add recorded material to demo list.
N_TAKEFLAG
C2S clear the last n / all demos.
N_RETURNFLAG
S2C a player took a flag.
N_RESETFLAG
S2C a player returned a flag.
N_INVISFLAG
S2C a flag has been reset.
N_TRYDROPFLAG
S2C send how long flag will stay transparent in hold mode ? (vistime)
N_DROPFLAG
C2S tell the server that you would like to drop your flag.
N_SCOREFLAG
S2C a client has dropped the flag.
N_INITFLAGS
S2C a client has scored the flag.
N_SAYTEAM
S2C send a list of flags available in game.
N_PRIVMSG
C2S|S2C team chat.
N_HUDANNOUNCE
C2S|S2C private/personal message.
N_CLIENT
S2C BOMBERMAN Announcement.
N_PAUSEGAME
S2C client synchronisation.
N_GAMESPEED
C2S|S2C server paused game. stop player movement and actions.
N_PERSISTTEAMS
C2S|S2C change game speed (and broadcast that change)
N_ADDBOT
C2S|S2C do not shuffle teams when enabled.
N_DELBOT
-S- add a bot to the current game
N_INITAI
-S- remove a bot from the current game
N_FROMAI
S2C commit AI settings to server. bots are still server side.
N_BOTLIMIT
C2S take client number from bot x?
N_BOTBALANCE
-S- set the bot limit
N_MAPCRC
-S- set bot balance
N_CHECKMAPS
C2S send map CRC32 hash value.
N_SWITCHNAME
C2S force server to check client maps manually (requires permissions)
N_SWITCHMODEL
C2S|S2C a player has changed his name.
N_SWITCHTEAM
C2S|S2C a player has changed his player model.
N_INITTOKENS
C2S|S2C a player has switched his team (some game modes have more than 2 teams!)
N_TAKETOKEN
N_EXPIRETOKENS
N_DROPTOKENS
N_DEPOSITTOKENS
N_STEALTOKENS
N_SERVCMD
N_DEMOPACKET
S2C servers could send advanced messages to clients. standard clients do not interpret this custom message.
N_SPAWNLOC
S2C send a requested demo packet.
NUMMSG
S2C BOMBERMAN spawn location?
anonymous enum
Enumerator
DISC_NONE
DISC_EOP
DISC_KICK
DISC_MSGERR
DISC_IPBAN
DISC_PRIVATE
DISC_MAXCLIENTS
DISC_TIMEOUT
DISC_OVERFLOW
DISC_PASSWORD
DISC_NUM
Function Documentation
const char* disconnectreason (int reason) inline
References DISC_EOP, DISC_IPBAN, DISC_KICK, DISC_MAXCLIENTS, DISC_MSGERR, DISC_OVERFLOW, DISC_PASSWORD, DISC_PRIVATE, and DISC_TIMEOUT.
Referenced by server::disconnect_client(), and gets2c().
int lan_info_port () inline
References INEXOR_LANINFO_PORT.
Referenced by server::setup_network_sockets().
int msgsizelookup (int msg) inline
References msgsizes, and NUMMSG.
Referenced by game::addmsg(), and server::parsepacket().
int server_info_port (int servport) inline
References INEXOR_SERVINFO_PORT.
Referenced by server::setup_network_sockets().
int server_port (int infoport = -1) inline
References INEXOR_SERVER_PORT.
Referenced by connectserv(), and server::setup_network_sockets().
Variable Documentation
const int msgsizes[] static
Initial value:
=
{
    N_CONNECT, 0, N_SERVINFO, 0, N_WELCOME, 1, N_INITCLIENT, 0, N_POS, 0, N_TEXT, 0, N_SOUND, 2, N_CDIS, 2,
    N_SHOOT, 0, N_EXPLODE, 0, N_SUICIDE, 1,
    N_DIED, 5, N_DAMAGE, 6, N_HITPUSH, 7, N_SHOTFX, 10, N_EXPLODEFX, 4,
    N_TRYSPAWN, 1, N_SPAWNSTATE, 14, N_SPAWN, 3, N_FORCEDEATH, 2,
    N_GUNSELECT, 2, N_TAUNT, 1, N_FOV, 2,
    N_MAPCHANGE, 0, N_MAPVOTE, 0, N_TEAMINFO, 0,
    N_ITEMSPAWN, 2, N_ITEMPICKUP, 2, N_ITEMACC, 3, N_ITEMPUSH, 6,
    N_PING, 2, N_PONG, 2, N_CLIENTPING, 2,
    N_TIMEUP, 2, N_FORCEINTERMISSION, 1,
    N_SERVMSG, 0, N_ITEMLIST, 0, N_RESUME, 0,
    N_EDITMODE, 2, N_EDITENT, 11, N_EDITF, 16, N_EDITT, 16, N_EDITM, 16, N_FLIP, 14, N_COPY, 14, N_PASTE, 14, N_ROTATE, 15, N_REPLACE, 17, N_DELCUBE, 14, N_REMIP, 1, N_EDITVSLOT, 16, N_UNDO, 0, N_REDO, 0, N_NEWMAP, 2, N_GETMAP, 1, N_SENDMAP, 0, N_EDITVAR, 0,
    N_MASTERMODE, 2, N_KICK, 0, N_CLEARBANS, 1, N_CURRENTMASTER, 0, N_SPECTATOR, 3, N_SETMASTER, 0, N_SETTEAM, 0,
    N_BASES, 0, N_BASEINFO, 0, N_BASESCORE, 0, N_REPAMMO, 1, N_BASEREGEN, 6, N_ANNOUNCE, 2,
    N_LISTDEMOS, 1, N_SENDDEMOLIST, 0, N_GETDEMO, 2, N_SENDDEMO, 0,
    N_DEMOPLAYBACK, 3, N_RECORDDEMO, 2, N_STOPDEMO, 1, N_CLEARDEMOS, 2,
    N_TAKEFLAG, 3, N_RETURNFLAG, 4, N_RESETFLAG, 6, N_INVISFLAG, 3, N_TRYDROPFLAG, 1, N_DROPFLAG, 7, N_SCOREFLAG, 11, N_INITFLAGS, 0,
    N_SAYTEAM, 0, N_PRIVMSG, 0, N_HUDANNOUNCE, 0,
    N_CLIENT, 0,
    N_PAUSEGAME, 0, N_GAMESPEED, 0, N_PERSISTTEAMS, 0,
    N_ADDBOT, 2, N_DELBOT, 1, N_INITAI, 0, N_FROMAI, 2, N_BOTLIMIT, 2, N_BOTBALANCE, 2,
    N_MAPCRC, 0, N_CHECKMAPS, 1,
    N_SWITCHNAME, 0, N_SWITCHMODEL, 2, N_SWITCHTEAM, 0,
    N_INITTOKENS, 0, N_TAKETOKEN, 2, N_EXPIRETOKENS, 0, N_DROPTOKENS, 0, N_DEPOSITTOKENS, 2, N_STEALTOKENS, 0,
    N_SERVCMD, 0,
    N_DEMOPACKET, 0,
    N_SPAWNLOC, 0,
    -1
}
size incuding message token, 0 for variable or not-checked sizes
Referenced by msgsizelookup().