Inexor: inexor/shared/geom.cpp File Reference
geom.cpp File Reference
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/geom.hpp"
Functions
static double det2x2 (double a, double b, double c, double d)
static double det3x3 (double a1, double a2, double a3, double b1, double b2, double b3, double c1, double c2, double c3)
bool raysphereintersect (const vec &center, float radius, const vec &o, const vec &ray, float &dist)
physics engine: collision (intersection) check functions
bool rayboxintersect (const vec &b, const vec &s, const vec &o, const vec &ray, float &dist, int &orient)
bool linecylinderintersect (const vec &from, const vec &to, const vec &start, const vec &end, float radius, float &dist)
Variables
const vec2 sincos360 [721]
Function Documentation
static double det2x2 (double a, double b, double c, double d) inline static
Referenced by det3x3().
static double det3x3 (double a1, double a2, double a3, double b1, double b2, double b3, double c1, double c2, double c3) inline static
References det2x2().
Referenced by matrix4::invert().
bool linecylinderintersect (const vec & from, const vec & to, const vec & start, const vec & end, float radius, float & dist)
References hmap::d, vec::dot(), f(), vec::squaredlen(), and vec::sub().
Referenced by game::intersect().
bool rayboxintersect (const vec & b, const vec & s, const vec & o, const vec & ray, float & dist, int & orient)
References vec::add(), C, hmap::d, hmap::dc, loop, vec::mul(), and R.
Referenced by disttoent(), disttooutsideent(), and rendereditcursor().
bool raysphereintersect (const vec & center, float radius, const vec & o, const vec & ray, float & dist)
physics engine: collision (intersection) check functions
References hmap::d, vec::dot(), vec::squaredlen(), and vec::sub().
Variable Documentation
const vec2 sincos360[721]
Referenced by brightestlight(), decodenormal(), generatelumel(), fogdome::init(), lightreaching(), regularshape(), renderellipse(), renderentring(), meterrenderer::renderpart(), and rotatebb().