Inexor: inexor/engine/grass.cpp File Reference
grass.cpp File Reference
#include <SDL_opengl.h>
#include <math.h>
#include <algorithm>
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct grasswedge
struct grassvert
struct grassgroup
Macros
#define NUMGRASSWEDGES 8
#define NUMGRASSOFFSETS 32
#define GRASSVERT(n, tcv, modify)
Functions
VARP (grass, 0, 0, 1)
VAR (dbggrass, 0, 0, 1)
VARP (grassdist, 0, 256, 10000)
FVARP (grasstaper, 0, 0.2, 1)
FVARP (grassstep, 0.5, 2, 8)
VARP (grassheight, 1, 4, 64)
VARR (grassanimmillis, 0, 3000, 60000)
FVARR (grassanimscale, 0, 0.03f, 1)
static void animategrass ()
VARR (grassscale, 1, 2, 64)
HVARFR (grasscolour, 0, 0xFFFFFF, 0xFFFFFF,{if(!grasscolour) grasscolour=0xFFFFFF;grasscolor=bvec((grasscolour >>16)&0xFF,(grasscolour >>8)&0xFF, grasscolour &0xFF);})
FVARR (grassalpha, 0, 1, 1)
static void gengrassquads (grassgroup *&group, const grasswedge &w, const grasstri &g, Texture *tex)
static void gengrassquads (vtxarray *va)
static bool comparegrassgroups (const grassgroup &x, const grassgroup &y)
void generategrass ()
void rendergrass ()
void cleanupgrass ()
Variables
static struct grasswedge grasswedges [NUMGRASSWEDGES] = { 0, 1, 2, 3, 4, 5, 6, 7 }
static vector< grassvert > grassverts
static GLuint grassvbo = 0
static int grassvbosize = 0
static vector< grassgroup > grassgroups
static float grassoffsets [NUMGRASSOFFSETS] = { -1 }
static float grassanimoffsets [NUMGRASSOFFSETS]
static int lastgrassanim = -1
bvec grasscolor (255, 255, 255)
Class Documentation
struct grassvert
Class Members
bvec4 color
vec2 lm
vec pos
vec2 tc
struct grassgroup
Class Members
float dist
int lmtex
int numquads
int offset
int tex
const grasstri * tri
Macro Definition Documentation
#define GRASSVERT (n, tcv, modify)
Value:
{ \
            grassvert &gv = grassverts.add(); \
            gv.pos = p##n; \
            gv.color = color; \
            gv.tc = vec2(tc##n, tcv); \
            gv.lm = lm##n; \
            modify; \
        }
Referenced by gengrassquads().
#define NUMGRASSOFFSETS 32
Referenced by animategrass(), generategrass(), and gengrassquads().
#define NUMGRASSWEDGES 8
Referenced by generategrass(), and gengrassquads().
Function Documentation
static void animategrass () static
References grassanimoffsets, grassoffsets, lastgrassanim, lastmillis, loopi(), and NUMGRASSOFFSETS.
Referenced by gengrassquads().
void cleanupgrass ()
References glDeleteBuffers_, grassvbo, and grassvbosize.
Referenced by cleanupva().
static bool comparegrassgroups (const grassgroup & x, const grassgroup & y) inline static
References grassgroup::dist.
Referenced by generategrass().
FVARP (grasstaper , 0 , 0. 2, 1)
FVARP (grassstep , 0. 5, 2 , 8)
FVARR (grassanimscale , 0 , 0. 03f, 1)
FVARR (grassalpha , 0 , 1 , 1)
void generategrass ()
References gle::bindvbo(), grasswedge::bound1, grasswedge::bound2, camera1, gle::clearvbo(), comparegrassgroups(), vec::dot(), vector< T, MINSIZE >::empty(), gengrassquads(), vector< T, MINSIZE >::getbuf(), glBufferData_, glBufferSubData_, glGenBuffers_, grassoffsets, grassvbo, grassvbosize, grasswedges, vector< T, MINSIZE >::length(), loopi(), inexor::rpc::max(), vtxarray::next, NUMGRASSOFFSETS, NUMGRASSWEDGES, physent::o, OCCLUDE_GEOM, plane::offset, reflecting, reflectz, refracting, rnd(), vector< T, MINSIZE >::setsize(), vector< T, MINSIZE >::sort(), and visibleva.
Referenced by gl_drawframe().
static void gengrassquads (grassgroup *& group, const grasswedge & w, const grasstri & g, Texture * tex) static
References grasswedge::across, vector< T, MINSIZE >::add(), vec::add(), animategrass(), grasswedge::bound1, grasswedge::bound2, brightengeom, camera1, gle::color(), vec::cross(), grasswedge::dir, plane::dist(), vec::dot(), vec4::dot(), editmode, grassanimoffsets, grasscolor, grassoffsets, GRASSVERT, Texture::id, lastgrassanim, lastmillis, vector< T, MINSIZE >::length(), lightmaptexs, grasstri::lmid, LMID_BRIGHT, LMID_RESERVED, grassgroup::lmtex, inexor::rpc::max(), inexor::rpc::min(), vec::mul(), notexture, NUMGRASSOFFSETS, grassgroup::numquads, grasstri::numv, physent::o, grassgroup::offset, vec::sub(), grasstri::surface, anonymous_namespace{utilTest.cpp}::t(), grasstri::tcu, grasstri::tcv, grassgroup::tex, texscale(), grassgroup::tri, grasstri::v, Texture::xs, Texture::ys, and plane::zdelta().
Referenced by generategrass(), and gengrassquads().
static void gengrassquads (vtxarray * va) static
References Slot::autograss, grasswedge::bound1, grasswedge::bound2, camera1, grasstri::center, grassgroup::dist, vec::dist(), plane::dist(), gengrassquads(), Slot::grasstex, vtxarray::grasstris, grasswedges, isfoggedsphere(), lookupvslot(), loopi(), loopv, NUMGRASSWEDGES, physent::o, grasstri::radius, VSlot::slot, grasstri::texture, and textureload().
HVARFR (grasscolour , 0 , 0xFFFFFF , 0xFFFFFF , {if(!grasscolour) grasscolour=0xFFFFFF;grasscolor=bvec((grasscolour >>16)&0xFF,(grasscolour >>8)&0xFF, grasscolour &0xFF);})
void rendergrass ()
References gle::bindvbo(), grasstri::center, gle::clearvbo(), grassvert::color, gle::disablequads(), gle::drawquads(), vector< T, MINSIZE >::empty(), gle::enablequads(), GL_ONE, glActiveTexture_, grassvbo, isfoggedsphere(), grassvert::lm, grassgroup::lmtex, loopv, grasstri::maxz, grassgroup::numquads, grassgroup::offset, grassvert::pos, grasstri::radius, reflecting, reflectz, refracting, SETSHADER, grassvert::tc, grassgroup::tex, grassgroup::tri, and xtravertsva.
Referenced by drawreflection(), and gl_drawframe().
VAR (dbggrass , 0 , 0 , 1)
VARP (grass , 0 , 0 , 1)
VARP (grassdist , 0 , 256 , 10000)
VARP (grassheight , 1 , 4 , 64)
VARR (grassanimmillis , 0 , 3000 , 60000)
VARR (grassscale , 1 , 2 , 64)
Variable Documentation
float grassanimoffsets[NUMGRASSOFFSETS] static
Referenced by animategrass(), and gengrassquads().
bvec grasscolor(255, 255, 255)
Referenced by gengrassquads().
vector<grassgroup> grassgroups static
float grassoffsets[NUMGRASSOFFSETS] = { -1 } static
Referenced by animategrass(), generategrass(), and gengrassquads().
GLuint grassvbo = 0 static
Referenced by cleanupgrass(), generategrass(), and rendergrass().
int grassvbosize = 0 static
Referenced by cleanupgrass(), and generategrass().
vector<grassvert> grassverts static
struct grasswedge grasswedges[NUMGRASSWEDGES] = { 0, 1, 2, 3, 4, 5, 6, 7 } static
Referenced by generategrass(), and gengrassquads().
int lastgrassanim = -1 static
Referenced by animategrass(), and gengrassquads().