Inexor: inexor/texture/image.cpp File Reference
image.cpp File Reference
Texture modifiers mainly applied on load.
#include <boost/algorithm/clamp.hpp>
#include <string.h>
#include <algorithm>
#include "SDL_opengl.h"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/cube_endian.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/texture/image.hpp"
#include "inexor/texture/macros.hpp"
#include "inexor/texture/texsettings.hpp"
Functions
template<int BPP>
static void halvetexture (uchar *src, uint sw, uint sh, uint stride, uchar *dst)
template<int BPP>
static void shifttexture (uchar *src, uint sw, uint sh, uint stride, uchar *dst, uint dw, uint dh)
template<int BPP>
static void scaletexture (uchar *src, uint sw, uint sh, uint stride, uchar *dst, uint dw, uint dh)
void scaletexture (uchar *src, uint sw, uint sh, uint bpp, uint pitch, uchar *dst, uint dw, uint dh)
void resizetexture (int w, int h, bool mipmap, bool canreduce, GLenum target, int compress, int &tw, int &th)
static void reorienttexture (uchar *src, int sw, int sh, int bpp, int stride, uchar *dst, bool flipx, bool flipy, bool swapxy, bool normals=false)
static void reorients3tc (GLenum format, int blocksize, int w, int h, uchar *src, uchar *dst, bool flipx, bool flipy, bool swapxy, bool normals=false)
void texreorient (ImageData &s, bool flipx, bool flipy, bool swapxy, bool isnormalmap)
void texrotate (ImageData &s, int numrots, bool isnormalmap)
void texoffset (ImageData &s, int xoffset, int yoffset)
void texmad (ImageData &s, const vec &mul, const vec &add)
void texcolorify (ImageData &s, const vec &color, vec weights)
void texcolormask (ImageData &s, const vec &color1, const vec &color2)
void texdup (ImageData &s, int srcchan, int dstchan)
void texmix (ImageData &s, int c1, int c2, int c3, int c4)
void texgrey (ImageData &s)
void texpremul (ImageData &s)
void texagrad (ImageData &s, float x2, float y2, float x1, float y1)
void texflip (ImageData &s)
void texnormal (ImageData &s, int emphasis)
template<int n, int bpp, bool normals>
static void blurtexture (int w, int h, uchar *dst, const uchar *src, int margin)
void blurtexture (int n, int bpp, int w, int h, uchar *dst, const uchar *src, int margin)
void blurnormals (int n, int w, int h, bvec *dst, const bvec *src, int margin)
void texblur (ImageData &s, int n, int r)
void forcergbimage (ImageData &s)
void scaleimage (ImageData &s, int w, int h)
Detailed Description
Texture modifiers mainly applied on load.
Function Documentation
void blurnormals (int n, int w, int h, bvec * dst, const bvec * src, int margin)
template<int n, int bpp, bool normals> static void blurtexture (int w, int h, uchar * dst, const uchar * src, int margin) static
References hmap::dr, vec::magnitude(), normals, and anonymous_namespace{utilTest.cpp}::t().
Referenced by finishlightmap(), genenvmap(), and texblur().
void blurtexture (int n, int bpp, int w, int h, uchar * dst, const uchar * src, int margin)
void forcergbimage (ImageData & s)
References ImageData::bpp, hmap::d, ImageData::h, readwritetex, and ImageData::w.
Referenced by Slot::loadthumbnail().
template<int BPP> static void halvetexture (uchar * src, uint sw, uint sh, uint stride, uchar * dst) static
References loopi().
static void reorients3tc (GLenum format, int blocksize, int w, int h, uchar * src, uchar * dst, bool flipx, bool flipy, bool swapxy, bool normals = false) static
References gle::end(), lilswap(), loopi(), inexor::rpc::min(), and normals.
Referenced by texreorient().
static void reorienttexture (uchar * src, int sw, int sh, int bpp, int stride, uchar * dst, bool flipx, bool flipy, bool swapxy, bool normals = false) inline static
References gle::end(), loopi(), loopk, and normals.
Referenced by texreorient().
void resizetexture (int w, int h, bool mipmap, bool canreduce, GLenum target, int compress, int & tw, int & th)
References hwcubetexsize, hwtexsize, inexor::rpc::max(), maxtexsize, inexor::rpc::min(), texreduce, usenp2, and usetexcompress.
Referenced by createtexture(), cubemaploadwildcard(), and newtexture().
void scaleimage (ImageData & s, int w, int h)
References ImageData::bpp, hmap::d, ImageData::data, ImageData::h, ImageData::pitch, ImageData::replace(), scaletexture(), and ImageData::w.
Referenced by Slot::combinetextures(), Slot::loadthumbnail(), and texturedata().
template<int BPP> static void scaletexture (uchar * src, uint sw, uint sh, uint stride, uchar * dst, uint dw, uint dh) static
References loopi(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by genenvmap(), scaleimage(), and uploadtexture().
void scaletexture (uchar * src, uint sw, uint sh, uint bpp, uint pitch, uchar * dst, uint dw, uint dh)
template<int BPP> static void shifttexture (uchar * src, uint sw, uint sh, uint stride, uchar * dst, uint dw, uint dh) static
References loopi(), and anonymous_namespace{utilTest.cpp}::t().
void texagrad (ImageData & s, float x2, float y2, float x1, float y1)
References ImageData::bpp, ImageData::data, gle::end(), f(), ImageData::h, inexor::rpc::max(), ImageData::pitch, and ImageData::w.
Referenced by texturedata().
void texblur (ImageData & s, int n, int r)
References blurtexture(), ImageData::bpp, hmap::d, ImageData::data, ImageData::h, loopi(), ImageData::replace(), and ImageData::w.
Referenced by texturedata().
void texcolorify (ImageData & s, const vec & color, vec weights)
References ImageData::bpp, f(), vec::iszero(), loopk, and writetex.
Referenced by texturedata().
void texcolormask (ImageData & s, const vec & color1, const vec & color2)
References ImageData::bpp, gle::color(), hmap::d, f(), ImageData::h, loopk, readwritetex, ImageData::replace(), and ImageData::w.
Referenced by texturedata().
void texdup (ImageData & s, int srcchan, int dstchan)
References ImageData::bpp, inexor::rpc::max(), and writetex.
Referenced by texturedata().
void texflip (ImageData & s)
References ImageData::bpp, hmap::d, ImageData::data, ImageData::h, loopi(), ImageData::pitch, ImageData::replace(), and ImageData::w.
Referenced by saveimage().
void texgrey (ImageData & s)
References ImageData::bpp, hmap::d, ImageData::h, readwritetex, ImageData::replace(), and ImageData::w.
Referenced by texturedata().
void texmad (ImageData & s, const vec & mul, const vec & add)
References ImageData::bpp, f(), loopk, inexor::rpc::min(), and writetex.
Referenced by Slot::loadthumbnail(), and texturedata().
void texmix (ImageData & s, int c1, int c2, int c3, int c4)
References hmap::d, ImageData::h, readwritetex, ImageData::replace(), and ImageData::w.
Referenced by texturedata().
void texnormal (ImageData & s, int emphasis)
References ImageData::bpp, hmap::d, ImageData::data, f(), ImageData::h, loop, gle::normal(), vec::normalize(), ImageData::pitch, ImageData::replace(), and ImageData::w.
Referenced by texturedata().
void texoffset (ImageData & s, int xoffset, int yoffset)
References ImageData::bpp, hmap::d, ImageData::data, ImageData::h, loop, inexor::rpc::max(), ImageData::pitch, ImageData::replace(), and ImageData::w.
Referenced by texturedata().
void texpremul (ImageData & s)
References ImageData::bpp, and writetex.
Referenced by texturedata().
void texreorient (ImageData & s, bool flipx, bool flipy, bool swapxy, bool isnormalmap = false)
Parameters
s The texture/image which you want to orientate
flipx Flip from x axis
flipy Flip from y axis
swapxy Swap on both x and y
isnormalmap specifies whether you pass in a normal map and hence need to shift the blue/red channels accordingly.
References ImageData::align, ImageData::bpp, ImageData::calclevelsize(), ImageData::compressed, hmap::d, ImageData::data, ImageData::h, ImageData::levels, loopi(), inexor::rpc::max(), ImageData::pitch, reorients3tc(), reorienttexture(), ImageData::replace(), and ImageData::w.
Referenced by cubemaploadwildcard(), texrotate(), and texturedata().
void texrotate (ImageData & s, int numrots, bool isnormalmap)
Parameters
isnormalmap specifies whether you pass in a normal map and hence need to shift the blue/red channels accordingly.
References texreorient().
Referenced by texturedata().