Inexor: inexor/io/input/InputRouter.cpp File Reference
InputRouter.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <string.h>
#include <memory>
#include "SDL_keyboard.h"
#include "SDL_keycode.h"
#include "SDL_mouse.h"
#include "SDL_stdinc.h"
#include "SDL_video.h"
#include "include/base/cef_ref_counted.h"
#include "include/cef_base.h"
#include "inexor/io/input/InputRouter.hpp"
#include "inexor/ui/InexorCefApp.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
#include "inexor/shared/cube_unicode.hpp"
Namespaces
inexor
Show stacktrace on unix, do not include directly.
inexor::io
Macros
#define keycodeshift 2*(event.button.button>=SDL_BUTTON_X1)
Functions
void quit ()
normal game quit
size_t decodeutf8 (unsigned char *dst, size_t dstlen, const unsigned char *src, size_t srclen, size_t *carry)
void processtextinput (const char *str, int len)
void processkey (int code, bool isdown)
bool g3d_movecursor (int dx, int dy)
void gl_resize ()
void mousemove (int dx, int dy)
Variables
InputRouter inexor::io::input_router
InputRouter singleton.
Macro Definition Documentation
#define keycodeshift 2*(event.button.button>=SDL_BUTTON_X1)
Referenced by inexor::io::InputRouter::checkinput().
Function Documentation
size_t decodeutf8 (unsigned char * dst, size_t dstlen, const unsigned char * src, size_t srclen, size_t * carry)
Referenced by inexor::io::InputRouter::checkinput(), loadfile(), pasteconsole(), and utf8stream::readbuf().
bool g3d_movecursor (int dx, int dy)
Referenced by inexor::io::InputRouter::checkinput().
void gl_resize ()
Referenced by inexor::io::InputRouter::checkinput().
void mousemove (int dx, int dy)
References game::allowmouselook(), camera1, curtime, detachedcamera, fixcamerarange(), physent::pitch, player, and physent::yaw.
Referenced by inexor::io::InputRouter::checkinput().
void processkey (int code, bool isdown)
References consolekey(), execbind(), g3d_key(), keyms, and keym::pressed.
Referenced by inexor::io::InputRouter::checkinput().
void processtextinput (const char * str, int len)
References consoleinput(), and g3d_input().
Referenced by inexor::io::InputRouter::checkinput().
void quit ()
normal game quit
See Also
fatal
cleanup
References abortconnect(), cleanup(), disconnect(), metapp, inexor::util::Metasystem::stop(), writecfg(), writehistory(), and writeinitcfg().
Referenced by inexor::io::InputRouter::checkinput().