Inexor: inexor/engine/lightning.hpp File Reference
lightning.hpp File Reference
Classes
struct lightningrenderer
Macros
#define MAXLIGHTNINGSTEPS 64
#define LIGHTNINGSTEP 8
Functions
static void calclightningjitter (int frame)
static void setuplightning ()
static void renderlightning (Texture *tex, const vec &o, const vec &d, float sz)
Variables
int lnjitterx [2][MAXLIGHTNINGSTEPS]
int lnjittery [2][MAXLIGHTNINGSTEPS]
int lnjitterframe = 0
int lastlnjitter = 0
static lightningrenderer lightnings
Macro Definition Documentation
#define LIGHTNINGSTEP 8
Referenced by renderlightning().
#define MAXLIGHTNINGSTEPS 64
Referenced by calclightningjitter(), and renderlightning().
Function Documentation
static void calclightningjitter (int frame) static
References lnjitterframe, lnjitterx, lnjittery, loopi(), MAXLIGHTNINGSTEPS, and rnd().
Referenced by setuplightning().
static void renderlightning (Texture * tex, const vec & o, const vec & d, float sz) static
References vec::add(), gle::begin(), camera1, vec::cross(), cur, hmap::d, detrnd(), vec::div(), gle::end(), f(), lastlnjitter, lastmillis, LIGHTNINGSTEP, lnjitterframe, lnjitterx, lnjittery, loopj, vec::magnitude(), MAXLIGHTNINGSTEPS, vec::mul(), vec::normalize(), physent::o, vec::orthogonal(), vec::sub(), Texture::xs, and Texture::ys.
Referenced by lightningrenderer::renderpart().
static void setuplightning () static
References calclightningjitter(), lastlnjitter, lastmillis, and lnjitterframe.
Referenced by lightningrenderer::update().
Variable Documentation
int lastlnjitter = 0
Referenced by renderlightning(), and setuplightning().
lightningrenderer lightnings static
int lnjitterframe = 0
Referenced by calclightningjitter(), renderlightning(), and setuplightning().
int lnjitterx[2][MAXLIGHTNINGSTEPS]
Referenced by calclightningjitter(), and renderlightning().
int lnjittery[2][MAXLIGHTNINGSTEPS]
Referenced by calclightningjitter(), and renderlightning().