Inexor: inexor/engine/material.hpp File Reference
material.hpp File Reference
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
Macros
#define isliquid(mat) ((mat)==MAT_WATER || (mat)==MAT_LAVA)
#define isclipped(mat) ((mat)==MAT_GLASS)
#define isdeadly(mat) ((mat)==MAT_LAVA)
Enumerations
enum {
MATF_INDEX_SHIFT = 0, MATF_VOLUME_SHIFT = 2, MATF_CLIP_SHIFT = 5, MATF_FLAG_SHIFT = 8,
MATF_INDEX = 3 << MATF_INDEX_SHIFT, MATF_VOLUME = 7 << MATF_VOLUME_SHIFT, MATF_CLIP = 7 << MATF_CLIP_SHIFT, MATF_FLAGS = 0xFF << MATF_FLAG_SHIFT
}
enum {
MAT_AIR = 0, MAT_WATER = 1 << MATF_VOLUME_SHIFT, MAT_LAVA = 2 << MATF_VOLUME_SHIFT, MAT_GLASS = 3 << MATF_VOLUME_SHIFT,
MAT_NOCLIP = 1 << MATF_CLIP_SHIFT, MAT_CLIP = 2 << MATF_CLIP_SHIFT, MAT_GAMECLIP = 3 << MATF_CLIP_SHIFT, MAT_DEATH = 1 << MATF_FLAG_SHIFT,
MAT_ALPHA = 4 << MATF_FLAG_SHIFT
}
Functions
int findmaterial (const char *name)
const char * findmaterialname (int mat)
const char * getmaterialdesc (int mat, const char *prefix="")
void genmatsurfs (const cube &c, const ivec &co, int size, vector< materialsurface > &matsurfs)
void rendermatgrid (materialsurface *matbuf, int matsurfs)
int optimizematsurfs (materialsurface *matbuf, int matsurfs)
void setupmaterials (int start=0, int len=0)
void rendermaterials ()
int visiblematerial (const cube &c, int orient, const ivec &co, int size, ushort matmask=MATF_VOLUME)
Variables
SharedVar< int > showmat
Macro Definition Documentation
#define isclipped (mat) ((mat)==MAT_GLASS)
Referenced by blobrenderer::findmaterials(), decalrenderer::findmaterials(), mpeditmat(), occludesface(), octacollide(), and raycube().
#define isdeadly (mat) ((mat)==MAT_LAVA)
Referenced by mpeditmat().
#define isliquid (mat) ((mat)==MAT_WATER || (mat)==MAT_LAVA)
Referenced by bounce(), findsurface(), ai::getweight(), gl_drawframe(), ragdolldata::move(), moveplayer(), occludesface(), optimizematsurfs(), setupmaterials(), and visibleface().
Enumeration Type Documentation
anonymous enum
Enumerator
MATF_INDEX_SHIFT
MATF_VOLUME_SHIFT
MATF_CLIP_SHIFT
MATF_FLAG_SHIFT
MATF_INDEX
MATF_VOLUME
MATF_CLIP
MATF_FLAGS
anonymous enum
Enumerator
MAT_AIR
MAT_WATER
MAT_LAVA
MAT_GLASS
MAT_NOCLIP
MAT_CLIP
MAT_GAMECLIP
MAT_DEATH
MAT_ALPHA
Function Documentation
int findmaterial (const char * name)
References material::id, loopi(), and materials.
Referenced by editmat(), and texture().
const char* findmaterialname (int mat)
References loopi(), materials, and material::name.
Referenced by getmaterialdesc().
void genmatsurfs (const cube & c, const ivec & co, int size, vector< materialsurface > & matsurfs)
References vector< T, MINSIZE >::add(), materialsurface::csize, dimcoord, dimension, loopi(), loopj, MAT_ALPHA, MAT_DEATH, materialsurface::material, cube::material, MATF_CLIP, MATF_INDEX, MATF_VOLUME, MATSURF_NOT_VISIBLE, materialsurface::o, materialsurface::orient, materialsurface::rsize, materialsurface::visible, and visiblematerial().
Referenced by rendercube().
const char* getmaterialdesc (int mat, const char * prefix = "")
References concatstring(), findmaterialname(), loopi(), MAT_ALPHA, MAT_DEATH, MATF_CLIP, MATF_INDEX, and MATF_VOLUME.
Referenced by gl_drawhud().
int optimizematsurfs (materialsurface * matbuf, int matsurfs)
References C, cur, dimension, gle::end(), QuadNode::genmatsurfs(), QuadNode::insert(), isliquid, loopi(), materialsurface::material, MATF_VOLUME, mergemats(), materialsurface::o, O_TOP, optmatcmp(), materialsurface::orient, quicksort(), R, recorder::start(), vertwater, materialsurface::visible, and worldsize.
Referenced by vacollect::optimize().
void rendermaterials ()
References modelpreview::camera, camera1, gle::color(), drawglass(), drawmaterial(), drawtex, editmode, EMID_NONE, vector< T, MINSIZE >::empty(), gle::end(), f(), foggednotextureshader, foggedshader, getglasscolor(), getwatercolor(), getwaterfallcolor(), getwaterfog(), GL_ONE, glActiveTexture_, glaring, GLOBALPARAM, Texture::id, bvec::iszero(), lastmillis, Slot::loaded, LOCALPARAMF, lookupenvmap(), lookupmaterialslot(), loopv, MAT_ALPHA, MAT_CLIP, MAT_DEATH, MAT_GAMECLIP, MAT_GLASS, MAT_LAVA, MAT_NOCLIP, MAT_WATER, materialsurface::material, MATF_INDEX, normals, notexture, physent::o, O_TOP, materialsurface::orient, reflecting, refracting, renderlava(), rendermatgrid(), renderwaterfall(), resetfogcolor(), VSlot::scale, Shader::set(), SETSHADER, setupwaterfallrefract(), showmat, sortmaterials(), Slot::sts, anonymous_namespace{utilTest.cpp}::t(), TEX_SCALE, vertwater, WATER_AMPLITUDE, WATER_OFFSET, waterfallrefract, wfscroll, wfwave, wfxscale, wfyscale, xtraverts, Texture::ys, and zerofogcolor().
Referenced by drawglare(), drawminimap(), drawreflection(), and gl_drawframe().
void rendermatgrid (materialsurface * matbuf, int matsurfs)
void setupmaterials (int start = 0, int len = 0)
References vector< T, MINSIZE >::add(), waterinfo::area, brightestlight(), C, closestenvmap(), materialsurface::csize, waterinfo::depth, dimcoord, dimension, unionfind::find(), isliquid, vector< T, MINSIZE >::length(), loadcaustics(), lookupcube(), lookupmaterialslot(), loopi(), loopj, loopv, loopvk, waterinfo::m, MAT_GLASS, MAT_LAVA, MAT_WATER, vtxarray::matbuf, materialsurface::material, cube::material, MATF_VOLUME, vtxarray::matsurfs, materialsurface::o, O_BOTTOM, O_TOP, materialsurface::orient, preloadwatershaders(), R, raycube(), materialsurface::rsize, materialsurface::skip, unionfind::unite(), useshaderbyname(), valist, visiblematerial(), and WATER_OFFSET.
Referenced by allchanged(), and commitchanges().
int visiblematerial (const cube & c, int orient, const ivec & co, int size, ushort matmask = MATF_VOLUME)
References MAT_AIR, MAT_GLASS, MAT_LAVA, MAT_WATER, cube::material, MATSURF_EDIT_ONLY, MATSURF_NOT_VISIBLE, MATSURF_VISIBLE, O_BOTTOM, and visibleface().
Referenced by genmatsurfs(), and setupmaterials().
Variable Documentation
SharedVar<int> showmat
Referenced by drawreflections(), gl_drawhud(), queryreflections(), rendereditcursor(), rendermaterials(), renderwater(), and sortmaterials().