Inexor: inexor/engine/material.cpp File Reference
material.cpp File Reference
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include "SDL_opengl.h"
#include "inexor/engine/glare.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_sort.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct QuadNode
struct material
struct waterinfo
struct unionfind
struct unionfind::ufval
Macros
#define GENFACEORIENT(orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERTX(orient, vert, mx, my, mz, sx, sy, sz)
#define GENFACEVERTY(orient, vert, mx, my, mz, sx, sy, sz)
#define GENFACENORMAL gle::attrib(n);
#define GENFACENORMAL
#define GENFACEVERTX(o, n, x, y, z, xv, yv, zv) GENFACEVERT(o,n, x,y,z, xv,yv,zv)
#define GENFACEVERTY(o, n, x, y, z, xv, yv, zv) GENFACEVERT(o,n, x,y,z, xv,yv,zv)
#define GENFACEORIENT(orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERT(orient, vert, mx, my, mz, sx, sy, sz) gle::attribf(mx sx, my sy, mz sz);
#define GLASSVARS(name)
#define GENFACEORIENT(orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERT(orient, vert, mx, my, mz, sx, sy, sz)
#define GENFACENORMAL gle::attrib(n);
#define GENFACENORMAL
Functions
static void renderwaterfall (const materialsurface &m, float offset, const vec *normal=nullptr)
static void drawmaterial (const materialsurface &m, float offset)
int findmaterial (const char *name)
const char * findmaterialname (int mat)
const char * getmaterialdesc (int mat, const char *prefix)
int visiblematerial (const cube &c, int orient, const ivec &co, int size, ushort matmask)
void genmatsurfs (const cube &c, const ivec &co, int size, vector< materialsurface > &matsurfs)
static bool mergematcmp (const materialsurface &x, const materialsurface &y)
static int mergematr (materialsurface *m, int sz, materialsurface &n)
static int mergematc (materialsurface &m, materialsurface &n)
static int mergemat (materialsurface *m, int sz, materialsurface &n)
static int mergemats (materialsurface *m, int sz)
static bool optmatcmp (const materialsurface &x, const materialsurface &y)
VARF (optmats, 0, 1, 1, allchanged())
int optimizematsurfs (materialsurface *matbuf, int matsurfs)
void setupmaterials (int start, int len)
VARP (showmat, 0, 1, 1)
static bool vismatcmp (const materialsurface *xm, const materialsurface *ym)
void sortmaterials (vector< materialsurface * > &vismats)
void rendermatgrid (vector< materialsurface * > &vismats)
VARP (glassenv, 0, 1, 1)
static void drawglass (const materialsurface &m, float offset, const vec *normal=nullptr)
VARFP (waterfallenv, 0, 1, 1, preloadwatershaders())
void rendermaterials ()
Variables
static float wfwave
static float wfscroll
static float wfxscale
static float wfyscale
const struct material materials []
static int sortdim [3]
static ivec sortorigin
static bool sortedit
Class Documentation
struct material
Class Members
ushort id
const char * name
struct waterinfo
Class Members
double area
double depth
materialsurface * m
Macro Definition Documentation
#define GENFACENORMAL gle::attrib(n);
#define GENFACENORMAL
#define GENFACENORMAL gle::attrib(n);
#define GENFACENORMAL
#define GENFACEORIENT (orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEORIENT (orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEORIENT (orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERT (orient, vert, mx, my, mz, sx, sy, sz) gle::attribf(mx sx, my sy, mz sz);
#define GENFACEVERT (orient, vert, mx, my, mz, sx, sy, sz)
Value:
{ \
            vec v(mx sx, my sy, mz sz); \
            vec reflect = vec(v).sub(camera1->o); \
            reflect[dimension(orient)] = -reflect[dimension(orient)]; \
            gle::attrib(v); \
            GENFACENORMAL \
            gle::attrib(reflect); \
        }
#define GENFACEVERTX (orient, vert, mx, my, mz, sx, sy, sz)
Value:
{ \
                vec v(mx sx, my sy, mz sz); \
                gle::attrib(v); \
                GENFACENORMAL \
                gle::attribf(wfxscale*v.y, wfyscale*(v.z+wfscroll)); \
            }
#define GENFACEVERTX (o, n, x, y, z, xv, yv, zv) GENFACEVERT(o,n, x,y,z, xv,yv,zv)
#define GENFACEVERTY (orient, vert, mx, my, mz, sx, sy, sz)
Value:
{ \
                vec v(mx sx, my sy, mz sz); \
                gle::attrib(v); \
                GENFACENORMAL \
                gle::attribf(wfxscale*v.x, wfyscale*(v.z+wfscroll)); \
            }
#define GENFACEVERTY (o, n, x, y, z, xv, yv, zv) GENFACEVERT(o,n, x,y,z, xv,yv,zv)
#define GLASSVARS (name)
Value:
bvec name##color(0x20, 0x80, 0xC0); \
    HVARFR(name##colour, 0, 0x2080C0, 0xFFFFFF, \
    { \
        if(!name##colour) name##colour = 0x2080C0; \
        name##color = bvec((name##colour>>16)&0xFF, (name##colour>>8)&0xFF, name##colour&0xFF); \
    });
Function Documentation
static void drawglass (const materialsurface & m, float offset, const vec * normal = nullptr) static
References gle::attribbuf, gle::begin(), GENFACEVERTS, and gle::normal().
Referenced by rendermaterials().
static void drawmaterial (const materialsurface & m, float offset) static
References gle::attribbuf, gle::begin(), materialsurface::csize, GENFACEVERTS, materialsurface::o, materialsurface::orient, and materialsurface::rsize.
Referenced by rendermaterials(), and rendermatgrid().
int findmaterial (const char * name)
References material::id, loopi(), and materials.
Referenced by editmat(), and texture().
const char* findmaterialname (int mat)
References loopi(), materials, and material::name.
Referenced by getmaterialdesc().
void genmatsurfs (const cube & c, const ivec & co, int size, vector< materialsurface > & matsurfs)
References vector< T, MINSIZE >::add(), materialsurface::csize, dimcoord, dimension, loopi(), loopj, MAT_ALPHA, MAT_DEATH, materialsurface::material, cube::material, MATF_CLIP, MATF_INDEX, MATF_VOLUME, MATSURF_NOT_VISIBLE, materialsurface::o, materialsurface::orient, materialsurface::rsize, materialsurface::visible, and visiblematerial().
Referenced by rendercube().
const char* getmaterialdesc (int mat, const char * prefix)
References concatstring(), findmaterialname(), loopi(), MAT_ALPHA, MAT_DEATH, MATF_CLIP, MATF_INDEX, and MATF_VOLUME.
Referenced by gl_drawhud().
static int mergemat (materialsurface * m, int sz, materialsurface & n) static
References mergematc(), and mergematr().
Referenced by mergemats().
static int mergematc (materialsurface & m, materialsurface & n) static
References C, materialsurface::csize, dimension, materialsurface::o, materialsurface::orient, R, and materialsurface::rsize.
Referenced by mergemat().
static bool mergematcmp (const materialsurface & x, const materialsurface & y) inline static
References C, dimension, materialsurface::o, materialsurface::orient, R, and materialsurface::rsize.
Referenced by mergemats().
static int mergematr (materialsurface * m, int sz, materialsurface & n) static
References C, materialsurface::csize, dimension, materialsurface::o, materialsurface::orient, R, and materialsurface::rsize.
Referenced by mergemat().
static int mergemats (materialsurface * m, int sz) static
References loopi(), mergemat(), mergematcmp(), and quicksort().
Referenced by optimizematsurfs().
int optimizematsurfs (materialsurface * matbuf, int matsurfs)
References C, cur, dimension, gle::end(), QuadNode::genmatsurfs(), QuadNode::insert(), isliquid, loopi(), materialsurface::material, MATF_VOLUME, mergemats(), materialsurface::o, O_TOP, optmatcmp(), materialsurface::orient, quicksort(), R, recorder::start(), vertwater, materialsurface::visible, and worldsize.
Referenced by vacollect::optimize().
static bool optmatcmp (const materialsurface & x, const materialsurface & y) inline static
References dimension, materialsurface::material, materialsurface::o, and materialsurface::orient.
Referenced by optimizematsurfs().
void rendermaterials ()
References modelpreview::camera, camera1, gle::color(), drawglass(), drawmaterial(), drawtex, editmode, EMID_NONE, vector< T, MINSIZE >::empty(), gle::end(), f(), foggednotextureshader, foggedshader, getglasscolor(), getwatercolor(), getwaterfallcolor(), getwaterfog(), GL_ONE, glActiveTexture_, glaring, GLOBALPARAM, Texture::id, bvec::iszero(), lastmillis, Slot::loaded, LOCALPARAMF, lookupenvmap(), lookupmaterialslot(), loopv, MAT_ALPHA, MAT_CLIP, MAT_DEATH, MAT_GAMECLIP, MAT_GLASS, MAT_LAVA, MAT_NOCLIP, MAT_WATER, materialsurface::material, MATF_INDEX, normals, notexture, physent::o, O_TOP, materialsurface::orient, reflecting, refracting, renderlava(), rendermatgrid(), renderwaterfall(), resetfogcolor(), VSlot::scale, Shader::set(), SETSHADER, setupwaterfallrefract(), showmat, sortmaterials(), Slot::sts, anonymous_namespace{utilTest.cpp}::t(), TEX_SCALE, vertwater, WATER_AMPLITUDE, WATER_OFFSET, waterfallrefract, wfscroll, wfwave, wfxscale, wfyscale, xtraverts, Texture::ys, and zerofogcolor().
Referenced by drawglare(), drawminimap(), drawreflection(), and gl_drawframe().
void rendermatgrid (vector< materialsurface * > & vismats)
References gle::color(), disablepolygonoffset(), drawmaterial(), enablepolygonoffset(), gle::end(), f(), loopvrev, MAT_ALPHA, MAT_CLIP, MAT_DEATH, MAT_GAMECLIP, MAT_GLASS, MAT_LAVA, MAT_NOCLIP, MAT_WATER, materialsurface::material, MATF_INDEX, and xtraverts.
Referenced by rendermaterials().
static void renderwaterfall (const materialsurface & m, float offset, const vec * normal = nullptr) static
References gle::attribbuf, gle::begin(), materialsurface::csize, GENFACEVERTSXY, gle::normal(), materialsurface::o, materialsurface::orient, materialsurface::rsize, WATER_AMPLITUDE, WATER_OFFSET, and wfwave.
Referenced by rendermaterials().
void setupmaterials (int start, int len)
References vector< T, MINSIZE >::add(), waterinfo::area, brightestlight(), C, closestenvmap(), materialsurface::csize, waterinfo::depth, dimcoord, dimension, unionfind::find(), isliquid, vector< T, MINSIZE >::length(), loadcaustics(), lookupcube(), lookupmaterialslot(), loopi(), loopj, loopv, loopvk, waterinfo::m, MAT_GLASS, MAT_LAVA, MAT_WATER, vtxarray::matbuf, materialsurface::material, cube::material, MATF_VOLUME, vtxarray::matsurfs, materialsurface::o, O_BOTTOM, O_TOP, materialsurface::orient, preloadwatershaders(), R, raycube(), materialsurface::rsize, materialsurface::skip, unionfind::unite(), useshaderbyname(), valist, visiblematerial(), and WATER_OFFSET.
Referenced by allchanged(), and commitchanges().
void sortmaterials (vector< materialsurface * > & vismats)
References vector< T, MINSIZE >::add(), camera1, dir, drawtex, editmode, glaring, loopi(), MAT_LAVA, MAT_WATER, materialsurface::material, MATF_VOLUME, MATSURF_EDIT_ONLY, physent::o, O_TOP, OCCLUDE_BB, materialsurface::orient, physent::pitch, reflectedva, reflecting, reflectz, refracting, showmat, materialsurface::skip, vector< T, MINSIZE >::sort(), vecfromyawpitch(), materialsurface::visible, visibleva, vismatcmp(), worldsize, and physent::yaw.
Referenced by rendermaterials().
VARF (optmats , 0 , 1 , 1 , allchanged())
VARFP (waterfallenv , 0 , 1 , 1 , preloadwatershaders())
VARP (showmat , 0 , 1 , 1)
VARP (glassenv , 0 , 1 , 1)
int visiblematerial (const cube & c, int orient, const ivec & co, int size, ushort matmask)
References MAT_AIR, MAT_GLASS, MAT_LAVA, MAT_WATER, cube::material, MATSURF_EDIT_ONLY, MATSURF_NOT_VISIBLE, MATSURF_VISIBLE, O_BOTTOM, and visibleface().
Referenced by genmatsurfs(), and setupmaterials().
static bool vismatcmp (const materialsurface * xm, const materialsurface * ym) inline static
References C, materialsurface::csize, dimension, loopi(), MAT_LAVA, materialsurface::material, MATF_VOLUME, inexor::rpc::max(), inexor::rpc::min(), materialsurface::o, materialsurface::orient, R, materialsurface::rsize, and sortedit.
Referenced by sortmaterials().
Variable Documentation
const struct material materials[]
Initial value:
=
{
    {"air", MAT_AIR},
    {"water", MAT_WATER}, {"water1", MAT_WATER}, {"water2", MAT_WATER+1}, {"water3", MAT_WATER+2}, {"water4", MAT_WATER+3},
    {"glass", MAT_GLASS}, {"glass1", MAT_GLASS}, {"glass2", MAT_GLASS+1}, {"glass3", MAT_GLASS+2}, {"glass4", MAT_GLASS+3},
    {"lava", MAT_LAVA}, {"lava1", MAT_LAVA}, {"lava2", MAT_LAVA+1}, {"lava3", MAT_LAVA+2}, {"lava4", MAT_LAVA+3},
    {"clip", MAT_CLIP},
    {"noclip", MAT_NOCLIP},
    {"gameclip", MAT_GAMECLIP},
    {"death", MAT_DEATH},
    {"alpha", MAT_ALPHA}
}
Referenced by findmaterial(), findmaterialname(), and smd::smdmeshgroup::readtriangles().
int sortdim[3] static
bool sortedit static
Referenced by vismatcmp().
ivec sortorigin static
float wfscroll static
Referenced by rendermaterials().
float wfwave static
Referenced by rendermaterials(), and renderwaterfall().
float wfxscale static
Referenced by rendermaterials().
float wfyscale static
Referenced by rendermaterials().