Inexor: inexor/ui/legacy/menus.hpp File Reference
menus.hpp File Reference
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/geom.hpp"
Enumerations
enum { NOT_INITING = 0, INIT_LOAD, INIT_RESET }
enum { CHANGE_GFX = 1<<0, CHANGE_SOUND = 1<<1 }
Functions
void clearmainmenu ()
void g3d_mainmenu ()
void menuprocess ()
void addchange (const char *desc, int type)
void clearchanges (int type)
vec menuinfrontofplayer ()
int cleargui (int n=0)
bool initwarning (const char *desc, int level=INIT_RESET, int type=CHANGE_GFX)
print initialisation (bug hints) warning in game console
Variables
SharedVar< int > mainmenu
int initing
Enumeration Type Documentation
anonymous enum
Enumerator
NOT_INITING
INIT_LOAD
INIT_RESET
anonymous enum
Enumerator
CHANGE_GFX
CHANGE_SOUND
Function Documentation
void addchange (const char * desc, int type)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::find(), vector< T, MINSIZE >::length(), loopv, inexor::rpc::max(), and pushgui().
Referenced by initwarning().
void clearchanges (int type)
References vector< T, MINSIZE >::empty(), loopv, vector< T, MINSIZE >::remove(), and removegui().
Referenced by resetgl(), and inexor::sound::resetsound().
int cleargui (int n = 0)
References vector< T, MINSIZE >::empty(), isconnected(), vector< T, MINSIZE >::length(), loopi(), mainmenu, inexor::rpc::min(), popgui(), and restoregui().
Referenced by clearguis(), clearmainmenu(), g3d_mainmenu(), and g3d_windowhit().
void clearmainmenu ()
References cleargui(), isconnected(), and mainmenu.
Referenced by emptymap(), and load_world().
void g3d_mainmenu ()
References camera1, cleargui(), vec::dist(), vector< T, MINSIZE >::empty(), g3d_addgui(), GUI_2D, GUI_FOLLOW, vector< T, MINSIZE >::last(), mainmenu, menuautoclose, menupos, and physent::o.
Referenced by g3d_render().
bool initwarning (const char * desc, int level, int type)
print initialisation (bug hints) warning in game console
See Also
addchange
References addchange(), and initing.
Referenced by inexor::rendering::screen::ScreenManager::screenres().
vec menuinfrontofplayer ()
References vec::add(), camera1, dir, physent::eyeheight, menudistance, vec::mul(), physent::o, player, vecfromyawpitch(), and physent::yaw.
Referenced by pushgui(), game::scoreboardgui::show(), and texturegui::showtextures().
void menuprocess ()
References clearguis(), clearlater, vector< T, MINSIZE >::empty(), isconnected(), vector< T, MINSIZE >::length(), loopv, mainmenu, showgui(), and vector< T, MINSIZE >::shrink().
Referenced by main().
Variable Documentation
int initing
Referenced by initwarning(), main(), and preloadmodelshaders().
SharedVar<int> mainmenu
Referenced by cleargui(), clearmainmenu(), disconnect(), drawcrosshair(), execbind(), g3d_addgui(), g3d_mainmenu(), g3d_render(), get_current_max_fps(), gl_drawhud(), main(), menuprocess(), renderbackground(), tryedit(), and inexor::sound::updatesounds().