Inexor: mpr Namespace Reference
mpr Namespace Reference
Classes
struct CubePlanes
struct SolidCube
struct Ent
struct EntOBB
struct EntFuzzy
struct EntCylinder
struct EntCapsule
struct EntEllipsoid
struct Model
struct ModelOBB
struct ModelEllipse
Functions
template<class T , class U >
bool collide (const T &p1, const U &p2)
template<class T , class U >
bool collide (const T &p1, const U &p2, vec *contactnormal, vec *contactpoint1, vec *contactpoint2)
Variables
const float boundarytolerance = 1e-3f
Function Documentation
template<class T , class U > bool mpr::collide (const T & p1, const U & p2)
References boundarytolerance, vec::cross(), vec::dot(), vec::iszero(), loopi(), vec::neg(), vec::normalize(), and vec::sub().
Referenced by partrenderer::calc(), ragdolldata::collidevert(), cubecollideplanes(), cubecollidesolid(), partrenderer::debuginfo(), finddynlights(), ai::jumpto(), mmcollide(), platformcollide(), plcollide(), regularshape(), and ai::avoidset::remap().
template<class T , class U > bool mpr::collide (const T & p1, const U & p2, vec * contactnormal, vec * contactpoint1, vec * contactpoint2)
References vec::add(), ASSERT, boundarytolerance, vec::cross(), vec::dot(), f(), game::hit(), vec::iszero(), loopi(), vec::mul(), vec::neg(), vec::normalize(), vec::scalartriple(), and vec::sub().
Variable Documentation
const float mpr::boundarytolerance = 1e-3f
Referenced by collide().