Inexor: ai Namespace Reference
ai Namespace Reference
Classes
struct waypoint
struct avoidset
struct interest
struct aistate
struct aiinfo
struct wpcache
struct wpcachestack
Enumerations
enum {
AI_S_WAIT = 0, AI_S_DEFEND, AI_S_PURSUE, AI_S_INTEREST,
AI_S_MAX
}
enum {
AI_T_NODE, AI_T_PLAYER, AI_T_AFFINITY, AI_T_ENTITY,
AI_T_MAX
}
enum { WPCACHE_STATIC = 0, WPCACHE_DYNAMIC, NUMWPCACHES }
Functions
VAR (aidebug, 0, 0, 6)
VAR (aiforcegun,-1,-1, NUMGUNS-1)
ICOMMAND (addbot,"s",(char *s), addmsg(N_ADDBOT,"ri",*s?clamp(parseint(s), 1, 101):-1))
ICOMMAND (botbalance,"i",(int *n), addmsg(N_BOTBALANCE,"ri",*n))
ICOMMAND (botlimit,"i",(int *n), addmsg(N_BOTLIMIT,"ri",*n))
ICOMMAND (delbot,"",(), addmsg(N_DELBOT,"r"))
float viewdist (int x)
float viewfieldx (int x)
float viewfieldy (int x)
bool canmove (fpsent *d)
float weapmindist (int weap)
float weapmaxdist (int weap)
bool weaprange (fpsent *d, int weap, float dist)
bool targetable (fpsent *d, fpsent *e)
bool getsight (vec &o, float yaw, float pitch, vec &q, vec &v, float mdist, float fovx, float fovy)
bool cansee (fpsent *d, vec &x, vec &y, vec &targ)
bool canshoot (fpsent *d, fpsent *e)
bool canshoot (fpsent *d)
bool hastarget (fpsent *d, aistate &b, fpsent *e, float yaw, float pitch, float dist)
vec getaimpos (fpsent *d, fpsent *e)
void create (fpsent *d)
void destroy (fpsent *d)
void init (fpsent *d, int at, int ocn, int sk, int bn, int pm, const char *name, const char *team, const char *tag)
void update ()
bool checkothers (vector< int > &targets, fpsent *d, int state, int targtype, int target, bool teams, int *members)
bool makeroute (fpsent *d, aistate &b, int node, bool changed, int retries)
bool makeroute (fpsent *d, aistate &b, const vec &pos, bool changed, int retries)
bool randomnode (fpsent *d, aistate &b, const vec &pos, float guard, float wander)
bool randomnode (fpsent *d, aistate &b, float guard, float wander)
bool badhealth (fpsent *d)
bool enemy (fpsent *d, aistate &b, const vec &pos, float guard=SIGHTMIN, int pursue=0)
bool patrol (fpsent *d, aistate &b, const vec &pos, float guard, float wander, int walk, bool retry)
bool defend (fpsent *d, aistate &b, const vec &pos, float guard, float wander, int walk)
bool violence (fpsent *d, aistate &b, fpsent *e, int pursue)
bool target (fpsent *d, aistate &b, int pursue=0, bool force=false, float mindist=0.f)
int isgoodammo (int gun)
bool hasgoodammo (fpsent *d)
void assist (fpsent *d, aistate &b, vector< interest > &interests, bool all, bool force)
static void tryitem (fpsent *d, extentity &e, int id, aistate &b, vector< interest > &interests, bool force=false)
void items (fpsent *d, aistate &b, vector< interest > &interests, bool force=false)
bool parseinterests (fpsent *d, aistate &b, vector< interest > &interests, bool override, bool ignore)
bool find (fpsent *d, aistate &b, bool override=false)
bool findassist (fpsent *d, aistate &b, bool override=false)
void damaged (fpsent *d, fpsent *e)
void findorientation (vec &o, float yaw, float pitch, vec &pos)
void setup (fpsent *d)
void spawned (fpsent *d)
void killed (fpsent *d, fpsent *e)
void itemspawned (int ent)
bool check (fpsent *d, aistate &b)
int dowait (fpsent *d, aistate &b)
int dodefend (fpsent *d, aistate &b)
int dointerest (fpsent *d, aistate &b)
int dopursue (fpsent *d, aistate &b)
int closenode (fpsent *d)
int wpspot (fpsent *d, int n, bool check=false)
int randomlink (fpsent *d, int n)
bool anynode (fpsent *d, aistate &b, int len=NUMPREVNODES)
bool checkroute (fpsent *d, int n)
bool hunt (fpsent *d, aistate &b)
void jumpto (fpsent *d, aistate &b, const vec &pos)
void fixfullrange (float &yaw, float &pitch, float &roll, bool full)
void fixrange (float &yaw, float &pitch)
void getyawpitch (const vec &from, const vec &pos, float &yaw, float &pitch)
void scaleyawpitch (float &yaw, float &pitch, float targyaw, float targpitch, float frame, float scale)
bool lockon (fpsent *d, fpsent *e, float maxdist)
int process (fpsent *d, aistate &b)
bool hasrange (fpsent *d, fpsent *e, int weap)
bool request (fpsent *d, aistate &b)
void timeouts (fpsent *d, aistate &b)
void logic (fpsent *d, aistate &b, bool run)
void avoid ()
void think (fpsent *d, bool run)
void drawroute (fpsent *d, float amt=1.f)
VAR (showwaypoints, 0, 0, 1)
VAR (showwaypointsradius, 0, 200, 10000)
void render ()
static bool iswaypoint (int n)
int closestwaypoint (const vec &pos, float mindist, bool links, fpsent *d=nullptr)
void findwaypointswithin (const vec &pos, float mindist, float maxdist, vector< int > &results)
void inferwaypoints (fpsent *d, const vec &o, const vec &v, float mindist=ai::CLOSEDIST)
bool route (fpsent *d, int node, int goal, vector< int > &route, const avoidset &obstacles, int retries=0)
void navigate ()
void clearwaypoints (bool full=false)
void seedwaypoints ()
void loadwaypoints (bool force=false, const char *mname=nullptr)
void savewaypoints (bool force=false, const char *mname=nullptr)
bool clipped (const vec &o)
int getweight (const vec &o)
static void invalidatewpcache (int wp)
void clearwpcache (bool full=true)
ICOMMAND (clearwpcache,"",(), clearwpcache())
void buildwpcache ()
static float heapscore (waypoint *q)
VARF (dropwaypoints, 0, 0, 1,{player1->lastnode=-1;})
int addwaypoint (const vec &o, int weight=-1)
void linkwaypoint (waypoint &a, int n)
static bool shouldnavigate ()
static bool shoulddrop (fpsent *d)
void navigate (fpsent *d)
ICOMMAND (clearwaypoints,"",(), clearwaypoints())
void remapwaypoints ()
bool cleanwaypoints ()
bool getwaypointfile (const char *mname, char *wptname)
ICOMMAND (loadwaypoints,"s",(char *mname), loadwaypoints(true, mname))
ICOMMAND (savewaypoints,"s",(char *mname), savewaypoints(true, mname))
void delselwaypoints ()
COMMAND (delselwaypoints,"")
void movewaypoints (const vec &d)
ICOMMAND (movewaypoints,"iii",(int *dx, int *dy, int *dz), movewaypoints(vec(*dx,*dy,*dz)))
Variables
avoidset obstacles
int updatemillis = 0
int iteration = 0
int itermillis = 0
int forcegun = -1
vec aitarget (0, 0, 0)
static vector< int > targets
const char * stnames [AI_S_MAX]
const char * sttypes [AI_T_MAX+1]
const int MAXWAYPOINTS = USHRT_MAX - 2
const int MAXWAYPOINTLINKS = 6
const int WAYPOINTRADIUS = 16
const float MINWPDIST = 4.f
const float CLOSEDIST = 32.f
const float FARDIST = 128.f
const float JUMPMIN = 4.f
const float JUMPMAX = 32.f
const float SIGHTMIN = 64.f
const float SIGHTMAX = 1024.f
const float VIEWMIN = 90.f
const float VIEWMAX = 180.f
vector< waypoint > waypoints
SharedVar< int > showwaypoints
SharedVar< int > dropwaypoints
const int NUMPREVNODES = 6
struct ai::wpcache wpcaches [NUMWPCACHES]
static int invalidatedwpcaches = 0
static int clearedwpcaches = (1<<NUMWPCACHES)-1
static int numinvalidatewpcaches = 0
static int lastwpcache = 0
avoidset wpavoid
vector< wpcache::node * > wpcachestack
string loadedwaypoints = ""
Class Documentation
struct ai::wpcachestack
Class Members
node * node
float tmax
float tmin
Enumeration Type Documentation
anonymous enum
Enumerator
AI_S_WAIT
AI_S_DEFEND
AI_S_PURSUE
AI_S_INTEREST
AI_S_MAX
anonymous enum
Enumerator
AI_T_NODE
AI_T_PLAYER
AI_T_AFFINITY
AI_T_ENTITY
AI_T_MAX
anonymous enum
Enumerator
WPCACHE_STATIC
WPCACHE_DYNAMIC
NUMWPCACHES
Function Documentation
int ai::addwaypoint (const vec & o, int weight = -1)
References getweight(), invalidatewpcache(), MAXWAYPOINTS, and waypoints.
Referenced by inferwaypoints(), navigate(), and seedwaypoints().
bool ai::anynode (fpsent * d, aistate & b, int len = NUMPREVNODES)
References vector< T, MINSIZE >::add(), fpsent::ai, ai::aiinfo::clear(), vector< T, MINSIZE >::insert(), iswaypoint(), fpsent::lastnode, loopi(), loopk, randomlink(), ai::aiinfo::route, and wpspot().
Referenced by hunt().
void ai::assist (fpsent * d, aistate & b, vector< interest > & interests, bool all, bool force)
References vector< T, MINSIZE >::add(), AI_NONE, AI_S_DEFEND, AI_T_PLAYER, fpsstate::aitype, fpsent::clientnum, hasgoodammo(), isteam, fpsent::lastnode, loopv, ai::interest::node, physent::o, game::players, ai::interest::score, vec::squaredist(), ai::interest::state, ai::interest::target, ai::interest::targtype, and fpsent::team.
Referenced by game::ctfclientmode::aihomerun(), find(), and findassist().
void ai::avoid ()
References physent::aboveeye, ai::avoidset::add(), ai::avoidset::avoidnear(), game::avoidweapons(), ai::avoidset::clear(), CS_ALIVE, hmap::d, physent::feetpos(), loopv, physent::o, obstacles, game::player1, game::players, physent::radius, physent::state, and wpavoid.
Referenced by update().
bool ai::badhealth (fpsent * d)
References fpsstate::health, and fpsstate::skill.
Referenced by game::collectclientmode::aicheck(), game::ctfclientmode::aicheck(), and itemspawned().
void ai::buildwpcache ()
References ai::avoidset::avoidnear(), ai::wpcache::build(), ai::avoidset::clear(), clearedwpcaches, lastwpcache, loopi(), loopv, NUMWPCACHES, WAYPOINTRADIUS, waypoints, wpavoid, and wpcaches.
Referenced by ai::avoidset::avoidnear(), closestwaypoint(), and findwaypointswithin().
bool ai::canmove (fpsent * d)
References CS_DEAD, game::intermission, and physent::state.
Referenced by cansee(), damaged(), logic(), and targetable().
bool ai::cansee (fpsent * d, vec & x, vec & y, vec & targ)
References fpsent::ai, AI_S_WAIT, canmove(), getsight(), ai::aiinfo::getstate(), physent::pitch, ai::aistate::type, ai::aiinfo::views, and physent::yaw.
Referenced by enemy(), process(), and target().
bool ai::canshoot (fpsent * d, fpsent * e)
References fpsstate::ammo, fpsstate::gunselect, fpsstate::gunwait, fpsent::lastaction, lastmillis, physent::o, vec::squaredist(), targetable(), and weaprange().
Referenced by process().
bool ai::canshoot (fpsent * d)
References fpsent::ai, fpsstate::ammo, ai::aiinfo::becareful, fpsstate::gunselect, fpsstate::gunwait, fpsent::lastaction, and lastmillis.
bool ai::check (fpsent * d, aistate & b)
References game::clientmode::aicheck(), and game::cmode.
Referenced by server::checkgban(), dodefend(), dointerest(), dopursue(), dowait(), and wpspot().
bool ai::checkothers (vector< int > & targets, fpsent * d, int state, int targtype, int target, bool teams, int * members)
References vector< T, MINSIZE >::add(), fpsent::ai, fpsent::clientnum, CS_ALIVE, vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::find(), ai::aiinfo::getstate(), isteam, loopv, game::players, vector< T, MINSIZE >::setsize(), physent::state, ai::aistate::target, ai::aistate::targtype, fpsent::team, and ai::aistate::type.
Referenced by game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), damaged(), findassist(), and parseinterests().
bool ai::checkroute (fpsent * d, int n)
References vector< T, MINSIZE >::add(), fpsent::ai, vector< T, MINSIZE >::empty(), ai::avoidset::find(), ai::aiinfo::hasprevnode(), vector< T, MINSIZE >::inrange(), iswaypoint(), ai::aiinfo::lastcheck, lastmillis, fpsent::lastnode, vector< T, MINSIZE >::length(), loopirev, loopj, loopvk, inexor::rpc::min(), NUMPREVNODES, obstacles, vector< T, MINSIZE >::pop(), route(), ai::aiinfo::route, vector< T, MINSIZE >::setsize(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by hunt().
bool ai::cleanwaypoints ()
References clearwpcache(), clipped(), fpsent::lastnode, ai::waypoint::links, loopv, ai::waypoint::o, game::player1, game::players, remapwaypoints(), and waypoints.
Referenced by loadwaypoints().
void ai::clearwaypoints (bool full = false)
References clearwpcache(), dropwaypoints, loadedwaypoints, and waypoints.
Referenced by movewaypoints(), and game::startmap().
void ai::clearwpcache (bool full = true)
References ai::wpcache::clear(), clearedwpcaches, invalidatedwpcaches, lastwpcache, loopi(), numinvalidatewpcaches, NUMWPCACHES, and wpcaches.
Referenced by cleanwaypoints(), clearwaypoints(), delselwaypoints(), loadwaypoints(), movewaypoints(), and navigate().
bool ai::clipped (const vec & o)
References lookupmaterial(), MAT_CLIP, MAT_DEATH, MAT_LAVA, MATF_CLIP, and MATF_VOLUME.
Referenced by cleanwaypoints(), and enablepolygonoffset().
int ai::closenode (fpsent * d)
References fpsent::ai, CLOSEDIST, FARDIST, physent::feetpos(), iswaypoint(), loopv, obstacles, ai::avoidset::remap(), ai::aiinfo::route, vec::squaredist(), and waypoints.
Referenced by hunt().
int ai::closestwaypoint (const vec & pos, float mindist, bool links, fpsent * d = nullptr)
References ai::wpcache::node::axis(), buildwpcache(), CHECKCLOSEST, ai::wpcache::node::childindex(), clearedwpcaches, ai::wpcache::node::isleaf(), lastwpcache, loop, NUMWPCACHES, ai::wpcache::node::split, waypoints, and wpcaches.
Referenced by game::captureclientmode::aifind(), game::collectclientmode::aifind(), game::ctfclientmode::aifind(), inferwaypoints(), makeroute(), navigate(), ai::avoidset::remap(), and tryitem().
ai::COMMAND (delselwaypoints , "")
void ai::create (fpsent * d)
References fpsent::ai.
Referenced by init().
void ai::damaged (fpsent * d, fpsent * e)
References fpsent::ai, AI_S_DEFEND, AI_T_PLAYER, canmove(), checkothers(), fpsent::clientnum, game::getclient(), ai::aiinfo::getstate(), GUN_FIST, fpsstate::gunselect, loopv, anonymous_namespace{utilTest.cpp}::t(), targetable(), targets, and violence().
Referenced by game::damaged(), and game::parsemessages().
bool ai::defend (fpsent * d, aistate & b, const vec & pos, float guard, float wander, int walk)
References enemy(), physent::feetpos(), GUN_FIST, fpsstate::gunselect, ai::aistate::idle, patrol(), and vec::squaredist().
Referenced by game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), dodefend(), and dopursue().
void ai::delselwaypoints ()
References vec::add(), clearwpcache(), f(), selinfo::grid, fpsent::lastnode, ai::waypoint::links, vec::mul(), noedit(), ai::waypoint::o, selinfo::o, game::player1, remapwaypoints(), selinfo::s, vec::sub(), and waypoints.
void ai::destroy (fpsent * d)
References fpsent::ai, and DELETEP.
Referenced by init().
int ai::dodefend (fpsent * d, aistate & b)
References AI_T_AFFINITY, AI_T_ENTITY, AI_T_NODE, AI_T_PLAYER, game::clientmode::aidefend(), check(), game::cmode, CS_ALIVE, defend(), entities::ents, physent::feetpos(), game::getclient(), iswaypoint(), physent::state, ai::aistate::target, ai::aistate::targtype, and waypoints.
Referenced by think().
int ai::dointerest (fpsent * d, aistate & b)
References AI_T_ENTITY, AI_T_NODE, check(), CLOSEDIST, CS_ALIVE, entities::ents, physent::feetpos(), find(), fpsstate::hasmaxammo(), I_CARTRIDGES, I_SHELLS, iswaypoint(), makeroute(), entity::o, extentity::spawned(), physent::state, vec::sub(), ai::aistate::target, target(), ai::aistate::targtype, entity::type, and waypoints.
Referenced by think().
int ai::dopursue (fpsent * d, aistate & b)
References AI_T_AFFINITY, AI_T_NODE, AI_T_PLAYER, game::clientmode::aipursue(), check(), game::cmode, CS_ALIVE, defend(), physent::feetpos(), game::getclient(), GUN_FIST, guns, fpsstate::gunselect, iswaypoint(), patrol(), guninfo::range, SIGHTMIN, physent::state, ai::aistate::target, ai::aistate::targtype, and waypoints.
Referenced by think().
int ai::dowait (fpsent * d, aistate & b)
References fpsent::ai, AI_S_INTEREST, AI_T_NODE, check(), ai::aiinfo::clear(), find(), randomnode(), ai::aiinfo::route, SIGHTMIN, ai::aiinfo::switchstate(), and target().
Referenced by think().
void ai::drawroute (fpsent * d, float amt = 1.f)
References fpsent::ai, hmap::dr, f(), physent::feetpos(), vector< T, MINSIZE >::inrange(), iswaypoint(), fpsent::lastnode, loopi(), loopvrev, NUMPREVNODES, ai::waypoint::o, PART_LIGHTNING, PART_STREAK, particle_flare(), ai::aiinfo::prevnodes, ai::aiinfo::route, ai::aiinfo::spot, ai::aiinfo::targnode, and waypoints.
Referenced by render().
bool ai::enemy (fpsent * d, aistate & b, const vec & pos, float guard = SIGHTMIN, int pursue = 0)
References cansee(), getaimpos(), physent::headpos(), loopv, game::players, vec::squaredist(), anonymous_namespace{utilTest.cpp}::t(), targetable(), and violence().
Referenced by defend(), and game::captureclientmode::parse_network_message().
bool ai::find (fpsent * d, aistate & b, bool override = false)
References game::clientmode::aifind(), assist(), fpsstate::canpickup(), game::cmode, entities::ents, physent::feetpos(), findents(), hasgoodammo(), fpsstate::health, I_QUAD, I_SHELLS, items(), loopv, m_noammo, m_noitems, m_teammode, inexor::rpc::min(), parseinterests(), vector< T, MINSIZE >::setsize(), fpsstate::skill, tryitem(), and entity::type.
Referenced by dointerest(), dowait(), genwatertex(), ai::avoidset::remap(), route(), and rendertarget::setup().
bool ai::findassist (fpsent * d, aistate & b, bool override = false)
References fpsent::ai, AI_S_DEFEND, assist(), checkothers(), vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::length(), loopi(), makeroute(), ai::interest::node, vector< T, MINSIZE >::removeunordered(), vector< T, MINSIZE >::setsize(), ai::interest::state, ai::aiinfo::switchstate(), ai::interest::target, targets, and ai::interest::targtype.
void ai::findorientation (vec & o, float yaw, float pitch, vec & pos)
References vec::add(), dir, getworldsize(), vec::mul(), RAY_CLIPMAT, RAY_SKIPFIRST, raycubepos(), and vecfromyawpitch().
Referenced by process(), and setup().
void ai::findwaypointswithin (const vec & pos, float mindist, float maxdist, vector< int > & results)
References ai::wpcache::node::axis(), buildwpcache(), CHECKWITHIN, ai::wpcache::node::childindex(), clearedwpcaches, ai::wpcache::node::isleaf(), lastwpcache, loop, NUMWPCACHES, ai::wpcache::node::split, waypoints, and wpcaches.
Referenced by randomnode(), and render().
void ai::fixfullrange (float & yaw, float & pitch, float & roll, bool full)
References f().
Referenced by fixrange().
void ai::fixrange (float & yaw, float & pitch)
References fixfullrange().
Referenced by process(), and scaleyawpitch().
vec ai::getaimpos (fpsent * d, fpsent * e)
References physent::aboveeye, fpsent::ai, ai::aiinfo::aimrnd, physent::eyeheight, f(), GUN_GL, GUN_RL, fpsstate::gunselect, ai::aiinfo::lastaimrnd, lastmillis, loopk, NUMGUNS, physent::o, physent::radius, rnd(), rndaioffset, and fpsstate::skill.
Referenced by enemy(), hasrange(), process(), and target().
bool ai::getsight (vec & o, float yaw, float pitch, vec & q, vec & v, float mdist, float fovx, float fovy)
References vec::dist(), inexor::rpc::min(), RAD, and raycubelos().
Referenced by cansee().
bool ai::getwaypointfile (const char * mname, char * wptname)
References game::getclientmap(), getmapfilename(), mapname(), MAXSTRLEN, and nformatstring().
Referenced by loadwaypoints(), and savewaypoints().
int ai::getweight (const vec & o)
References f(), getworldsize(), insideworld(), isliquid, JUMPMIN, lookupmaterial(), MAT_DEATH, MAT_LAVA, MATF_VOLUME, inexor::rpc::min(), RAY_CLIPMAT, and raycube().
Referenced by addwaypoint(), and loadwaypoints().
void ai::getyawpitch (const vec & from, const vec & pos, float & yaw, float & pitch)
References vec::dist(), and RAD.
Referenced by process().
bool ai::hasgoodammo (fpsent * d)
References fpsstate::ammo, GUN_BOMB, GUN_CG, GUN_GL, GUN_RIFLE, GUN_RL, GUN_SG, fpsstate::hasammo(), loopi(), and m_bomb.
Referenced by assist(), find(), and tryitem().
bool ai::hasrange (fpsent * d, fpsent * e, int weap)
References getaimpos(), physent::headpos(), vec::squaredist(), targetable(), and weaprange().
Referenced by request().
bool ai::hastarget (fpsent * d, aistate & b, fpsent * e, float yaw, float pitch, float dist)
References fpsent::ai, guninfo::attackdelay, ai::aiinfo::enemymillis, GUN_FIST, guns, fpsstate::gunselect, lastmillis, physent::pitch, guninfo::projspeed, rnd(), fpsstate::skill, ai::aiinfo::views, weaprange(), and physent::yaw.
Referenced by process().
static float ai::heapscore (waypoint * q) inline static
References ai::waypoint::score().
bool ai::hunt (fpsent * d, aistate & b)
References fpsent::ai, anynode(), checkroute(), ai::aiinfo::clear(), closenode(), vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::inrange(), vector< T, MINSIZE >::length(), ai::aistate::override, vector< T, MINSIZE >::pop(), ai::aiinfo::route, and wpspot().
Referenced by process().
ai::ICOMMAND (addbot , "s" , (char *s) , addmsg(N_ADDBOT,"ri",*s?clamp(parseint(s), 1, 101):-1))
ai::ICOMMAND (botbalance , "i" , (int *n) , addmsg(N_BOTBALANCE,"ri",*n))
ai::ICOMMAND (botlimit , "i" , (int *n) , addmsg(N_BOTLIMIT,"ri",*n))
ai::ICOMMAND (delbot , "" , () , addmsg(N_DELBOT,"r"))
ai::ICOMMAND (clearwpcache , "" , () , clearwpcache())
ai::ICOMMAND (clearwaypoints , "" , () , clearwaypoints())
ai::ICOMMAND (loadwaypoints , "s" , (char *mname) , loadwaypoints(true, mname))
ai::ICOMMAND (savewaypoints , "s" , (char *mname) , savewaypoints(true, mname))
ai::ICOMMAND (movewaypoints , "iii" , (int *dx, int *dy, int *dz) , movewaypoints(vec(*dx,*dy,*dz)))
void ai::inferwaypoints (fpsent * d, const vec & o, const vec & v, float mindist = ai::CLOSEDIST)
References addwaypoint(), closestwaypoint(), iswaypoint(), fpsent::lastnode, linkwaypoint(), seedwaypoints(), shoulddrop(), shouldnavigate(), WAYPOINTRADIUS, and waypoints.
Referenced by entities::teleport().
void ai::init (fpsent * d, int at, int ocn, int sk, int bn, int pm, const char * name, const char * team, const char * tag)
References fpsent::ai, fpsstate::aitype, at(), game::chooserandomplayermodel(), fpsent::clientnum, COL_GREEN, COL_WHITE, game::colorname(), copystring(), create(), destroy(), inexor::util::log_manager::game, loadwaypoints(), Log, MAXNAMELEN, MAXTAGLEN, MAXTEAMLEN, fpsent::name, game::newclient(), fpsent::ownernum, fpsent::plag, game::player1, fpsent::playermodel, game::removeweapons(), fpsstate::skill, fpsent::tag, fpsent::team, viewdist(), viewfieldx(), viewfieldy(), and ai::aiinfo::views.
Referenced by game::parsemessages().
static void ai::invalidatewpcache (int wp) inline static
References invalidatedwpcaches, loopi(), numinvalidatewpcaches, NUMWPCACHES, WPCACHE_DYNAMIC, and wpcaches.
Referenced by addwaypoint().
int ai::isgoodammo (int gun)
References GUN_GL, GUN_SG, and m_bomb.
Referenced by itemspawned(), request(), and tryitem().
static bool ai::iswaypoint (int n) inline static
References waypoints.
Referenced by anynode(), checkroute(), closenode(), dodefend(), dointerest(), dopursue(), drawroute(), inferwaypoints(), makeroute(), navigate(), randomlink(), ai::avoidset::remap(), render(), route(), and wpspot().
void ai::items (fpsent * d, aistate & b, vector< interest > & interests, bool force = false)
References fpsstate::canpickup(), entities::ents, loopv, extentity::spawned(), tryitem(), and entity::type.
Referenced by find(), and sortlist().
void ai::itemspawned (int ent)
References itemstat::add, fpsent::ai, AI_BOT, AI_S_INTEREST, AI_T_AFFINITY, AI_T_ENTITY, fpsstate::ammo, badhealth(), hmap::d, entities::ents, ai::aiinfo::getstate(), I_BOOST, I_GREENARMOUR, I_HEALTH, I_QUAD, I_SHELLS, I_YELLOWARMOUR, itemstat::info, isgoodammo(), itemstats, loopv, physent::o, game::players, vec::squaredist(), ai::aiinfo::switchstate(), ai::aistate::target, ai::aistate::targtype, ai::aistate::type, and ai::aiinfo::weappref.
Referenced by game::parsemessages().
void ai::jumpto (fpsent * d, aistate & b, const vec & pos)
References vec::add(), fpsent::ai, ai::aiinfo::blockseq, mpr::collide(), dir, entities::ents, physent::eyeheight, physent::feetpos(), ai::aistate::idle, physent::inwater, physent::jumping, JUMPMIN, JUMPPAD, ai::aiinfo::jumprand, ai::aiinfo::jumpseed, lastmillis, loopv, entity::o, physent::o, rnd(), fpsstate::skill, vec::squaredist(), vec::sub(), ai::aiinfo::targseq, and physent::timeinair.
Referenced by process().
void ai::killed (fpsent * d, fpsent * e)
References fpsent::ai, and ai::aiinfo::reset().
Referenced by game::killed(), and game::parsemessages().
void ai::linkwaypoint (waypoint & a, int n)
References ai::waypoint::links, loopi(), MAXWAYPOINTLINKS, and rnd().
Referenced by inferwaypoints(), and navigate().
void ai::loadwaypoints (bool force = false, const char * mname = nullptr)
References cleanwaypoints(), clearwpcache(), copystring(), stream::end(), f(), stream::getchar(), stream::getlil(), getwaypointfile(), getweight(), loadedwaypoints, Log, loopi(), MAXWAYPOINTLINKS, opengzfile(), stream::read(), waypoints, and inexor::util::log_manager::world.
Referenced by init().
bool ai::lockon (fpsent * d, fpsent * e, float maxdist)
References physent::blocked, dir, GUN_FIST, fpsstate::gunselect, physent::o, physent::radius, vec::sub(), and physent::timeinair.
Referenced by process().
void ai::logic (fpsent * d, aistate & b, bool run)
References fpsent::ai, AI_S_WAIT, game::allowmove(), fpsent::attacking, canmove(), game::clientmode::checkitems(), entities::checkitems(), entities::checkquad(), cleanragdoll(), game::cmode, CS_ALIVE, CS_DEAD, curtime, GUN_FIST, fpsstate::gunselect, ai::aistate::idle, game::intermission, physent::jumping, lastmillis, fpsent::lastpain, physent::move, moveplayer(), moveragdoll(), fpsstate::quadmillis, dynent::ragdoll, request(), game::shoot(), physent::state, dynent::stopmoving(), physent::strafe, ai::aiinfo::target, target(), timeouts(), and ai::aistate::type.
Referenced by think().
bool ai::makeroute (fpsent * d, aistate & b, int node, bool changed, int retries)
References fpsent::ai, iswaypoint(), fpsent::lastnode, vector< T, MINSIZE >::length(), obstacles, ai::aistate::override, route(), and ai::aiinfo::route.
Referenced by game::collectclientmode::aicheck(), game::ctfclientmode::aidefend(), game::ctfclientmode::aihomerun(), game::collectclientmode::aipursue(), game::ctfclientmode::aipursue(), dointerest(), findassist(), makeroute(), parseinterests(), patrol(), randomnode(), and violence().
bool ai::makeroute (fpsent * d, aistate & b, const vec & pos, bool changed, int retries)
References closestwaypoint(), makeroute(), and SIGHTMIN.
void ai::movewaypoints (const vec & d)
References vec::add(), clearwaypoints(), clearwpcache(), getworldsize(), insideworld(), fpsent::lastnode, ai::waypoint::links, noedit(), ai::waypoint::o, game::player1, remapwaypoints(), waypoints, and worldsize.
void ai::navigate ()
References clearwpcache(), invalidatedwpcaches, loopv, game::players, and shouldnavigate().
Referenced by game::updateworld().
void ai::navigate (fpsent * d)
References ai::aiinfo::addprevnode(), addwaypoint(), fpsent::ai, closestwaypoint(), CS_ALIVE, physent::feetpos(), iswaypoint(), fpsent::lastnode, linkwaypoint(), lookupmaterial(), MAT_CLIP, MAT_DEATH, MAT_LAVA, MATF_CLIP, MATF_VOLUME, seedwaypoints(), shoulddrop(), SIGHTMAX, SIGHTMIN, physent::state, physent::timeinair, WAYPOINTRADIUS, and waypoints.
bool ai::parseinterests (fpsent * d, aistate & b, vector< interest > & interests, bool override, bool ignore)
References fpsent::ai, AI_S_DEFEND, checkothers(), vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::length(), loopi(), makeroute(), ai::interest::node, vector< T, MINSIZE >::removeunordered(), ai::interest::state, ai::aiinfo::switchstate(), ai::interest::target, targets, and ai::interest::targtype.
Referenced by game::ctfclientmode::aihomerun(), and find().
bool ai::patrol (fpsent * d, aistate & b, const vec & pos, float guard, float wander, int walk, bool retry)
References fpsent::ai, vector< T, MINSIZE >::empty(), physent::feetpos(), makeroute(), ai::aistate::override, randomnode(), ai::aiinfo::route, and vec::squaredist().
Referenced by defend(), and dopursue().
int ai::process (fpsent * d, aistate & b)
References vec::add(), fpsent::ai, fpsent::attacking, ai::aiinfo::becareful, cansee(), canshoot(), ai::aiinfo::dontmove, ai::aiinfo::enemy, ai::aiinfo::enemymillis, ai::aiinfo::enemyseen, physent::eyeheight, f(), findorientation(), fixrange(), getaimpos(), game::getclient(), getyawpitch(), GUN_CG, GUN_FIST, fpsstate::gunselect, hastarget(), physent::headpos(), hunt(), ai::aistate::idle, game::intersectclosest(), jumpto(), ai::aiinfo::lastaction, ai::aiinfo::lasthunt, lastmillis, ai::aiinfo::lastrun, lockon(), inexor::rpc::max(), physent::move, move(), PHYS_FALL, physent::physstate, physent::pitch, result(), rnd(), scaleyawpitch(), SIGHTMIN, fpsstate::skill, ai::aiinfo::spot, vec::squaredist(), physent::strafe, ai::aiinfo::target, target(), targetable(), ai::aiinfo::targpitch, ai::aiinfo::targyaw, vectoyawpitch(), physent::vel, violence(), and physent::yaw.
int ai::randomlink (fpsent * d, int n)
References vector< T, MINSIZE >::add(), fpsent::ai, vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::find(), ai::aiinfo::hasprevnode(), iswaypoint(), vector< T, MINSIZE >::length(), ai::waypoint::links, loopi(), MAXWAYPOINTLINKS, rnd(), ai::aiinfo::route, vector< T, MINSIZE >::setsize(), and waypoints.
Referenced by anynode().
bool ai::randomnode (fpsent * d, aistate & b, const vec & pos, float guard, float wander)
References fpsent::ai, vector< T, MINSIZE >::empty(), ai::avoidset::find(), findwaypointswithin(), ai::aiinfo::hasprevnode(), fpsent::lastnode, vector< T, MINSIZE >::length(), makeroute(), obstacles, vector< T, MINSIZE >::removeunordered(), rnd(), and vector< T, MINSIZE >::setsize().
Referenced by game::ctfclientmode::aihomerun(), dowait(), patrol(), and randomnode().
bool ai::randomnode (fpsent * d, aistate & b, float guard, float wander)
References physent::feetpos(), and randomnode().
void ai::remapwaypoints ()
References vector< T, MINSIZE >::add(), ai::waypoint::links, loopi(), loopv, loopvj, MAXWAYPOINTLINKS, and waypoints.
Referenced by cleanwaypoints(), delselwaypoints(), and movewaypoints().
void ai::render ()
References physent::abovehead(), fpsent::ai, camera1, game::colorname(), CS_ALIVE, cur, hmap::d, defformatstring, drawroute(), vector< T, MINSIZE >::empty(), ai::aiinfo::enemy, f(), findwaypointswithin(), game::getclient(), guns, iswaypoint(), lastmillis, fpsent::lastnode, vector< T, MINSIZE >::length(), ai::waypoint::links, loopi(), loopj, loopv, loopvrev, MAXWAYPOINTLINKS, ai::aistate::millis, guninfo::name, NUMGUNS, ai::avoidset::obstacle::numwaypoints, ai::waypoint::o, physent::o, obstacles, ai::avoidset::obstacles, PART_EDIT, PART_STREAK, PART_TEXT, particle_flare(), particle_textcopy(), game::players, regular_particle_splash(), ai::aiinfo::route, showwaypoints, ai::aiinfo::state, recorder::state, stnames, sttypes, ai::aistate::target, ai::aistate::targtype, ai::aistate::type, waypoints, ai::avoidset::waypoints, and ai::aiinfo::weappref.
Referenced by findreflectedvas(), and game::rendergame().
bool ai::request (fpsent * d, aistate & b)
References fpsent::ai, ai::aiinfo::enemy, game::getclient(), GUN_BOMB, GUN_CG, GUN_FIST, GUN_GL, GUN_PISTOL, GUN_RIFLE, GUN_RL, GUN_SG, fpsstate::gunselect, game::gunselect(), fpsstate::hasammo(), hasrange(), isgoodammo(), loopi(), and ai::aiinfo::weappref.
Referenced by logic().
bool ai::route (fpsent * d, int node, int goal, vector< int > & route, const avoidset & obstacles, int retries = 0)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::addheap(), fpsent::ai, ai::waypoint::curscore, vec::dist(), vector< T, MINSIZE >::empty(), ai::waypoint::estscore, find(), iswaypoint(), ai::waypoint::links, loopavoid, loopi(), loopv, loopvj, inexor::rpc::max(), MAXWAYPOINTLINKS, NUMPREVNODES, ai::waypoint::o, ai::waypoint::prev, ai::aiinfo::prevnodes, vector< T, MINSIZE >::removeheap(), ai::waypoint::route, vector< T, MINSIZE >::setsize(), vector< T, MINSIZE >::upheap(), WAYPOINTRADIUS, waypoints, and ai::waypoint::weight.
Referenced by checkroute(), and makeroute().
void ai::savewaypoints (bool force = false, const char * mname = nullptr)
References dropwaypoints, f(), getwaypointfile(), ai::waypoint::links, Log, loopj, MAXWAYPOINTLINKS, ai::waypoint::o, opengzfile(), stream::putchar(), stream::putlil(), waypoints, inexor::util::log_manager::world, and stream::write().
Referenced by game::startmap().
void ai::scaleyawpitch (float & yaw, float & pitch, float targyaw, float targpitch, float frame, float scale)
References f(), and fixrange().
Referenced by process().
void ai::seedwaypoints ()
References addwaypoint(), BASE, entities::ents, FLAG, I_QUAD, I_SHELLS, JUMPPAD, loopv, entity::o, PLAYERSTART, TELEPORT, entity::type, and waypoints.
Referenced by inferwaypoints(), and navigate().
void ai::setup (fpsent * d)
References fpsent::ai, ai::aiinfo::clearsetup(), findorientation(), forcegun, GUN_BOMB, GUN_GL, GUN_RIFLE, GUN_SG, physent::headpos(), lastmillis, ai::aiinfo::lastrun, m_bomb, m_insta, m_noammo, NUMGUNS, physent::pitch, ai::aiinfo::reset(), rnd(), ai::aiinfo::target, ai::aiinfo::weappref, and physent::yaw.
Referenced by spawned().
static bool ai::shoulddrop (fpsent * d) inline static
References fpsent::ai, dropwaypoints, and loadedwaypoints.
Referenced by inferwaypoints(), and navigate().
static bool ai::shouldnavigate () inline static
References AI_NONE, dropwaypoints, loopvrev, and game::players.
Referenced by inferwaypoints(), and navigate().
void ai::spawned (fpsent * d)
References fpsent::ai, and setup().
Referenced by game::parsemessages(), server::parsepacket(), and server::welcomepacket().
bool ai::target (fpsent * d, aistate & b, int pursue = 0, bool force = false, float mindist = 0.f)
References vector< T, MINSIZE >::add(), cansee(), vector< T, MINSIZE >::find(), getaimpos(), physent::headpos(), loopv, game::players, vector< T, MINSIZE >::setsize(), vec::squaredist(), anonymous_namespace{utilTest.cpp}::t(), targetable(), and violence().
Referenced by createcompressedtexture(), createtexture(), dointerest(), dowait(), game::followingplayer(), generatelumel(), genvbo(), game::hudplayer(), lightent(), logic(), flarerenderer::newflare(), game::parsemessages(), process(), renderentarrow(), skelcommands< MDL >::setpitchcorrect(), and game::setupcamera().
bool ai::targetable (fpsent * d, fpsent * e)
References canmove(), CS_ALIVE, isteam, physent::state, and fpsent::team.
Referenced by canshoot(), damaged(), enemy(), hasrange(), process(), target(), and violence().
void ai::think (fpsent * d, bool run)
References game::addmsg(), ai::aiinfo::addstate(), fpsent::ai, AI_S_DEFEND, AI_S_INTEREST, AI_S_PURSUE, AI_S_WAIT, game::cmode, CS_ALIVE, CS_DEAD, dodefend(), dointerest(), dopursue(), dowait(), ai::aistate::idle, lastmillis, fpsent::lastpain, ai::aiinfo::lastrun, fpsent::lifesequence, logic(), loopvrev, ai::aistate::millis, N_TRYSPAWN, ai::aistate::override, ai::aiinfo::removestate(), fpsent::respawned, game::clientmode::respawnwait(), result(), physent::state, ai::aiinfo::state, ai::aiinfo::trywipe, ai::aistate::type, and ai::aiinfo::wipe().
Referenced by update().
void ai::timeouts (fpsent * d, aistate & b)
References ai::aiinfo::addprevnode(), fpsent::ai, physent::blocked, ai::aiinfo::blockseq, ai::aiinfo::blocktime, ai::aiinfo::clear(), entities::ents, ai::aiinfo::huntseq, ai::aiinfo::lasthunt, lastmillis, ai::aiinfo::lastrun, ai::aiinfo::reset(), game::suicide(), ai::aiinfo::targlast, ai::aiinfo::targnode, ai::aiinfo::targseq, ai::aiinfo::targtime, and ai::aiinfo::tryreset.
Referenced by logic().
static void ai::tryitem (fpsent * d, extentity & e, int id, aistate & b, vector< interest > & interests, bool force = false) static
References A_GREEN, A_YELLOW, vector< T, MINSIZE >::add(), fpsent::ai, AI_S_INTEREST, AI_T_ENTITY, fpsstate::armour, fpsstate::armourtype, closestwaypoint(), physent::feetpos(), GUN_BOMB, GUN_SG, hasgoodammo(), fpsstate::hasmaxammo(), fpsstate::health, I_BOMBDELAY, I_BOOST, I_GREENARMOUR, I_HEALTH, I_QUAD, I_SHELLS, I_YELLOWARMOUR, isgoodammo(), m_bomb, inexor::rpc::min(), ai::interest::node, entity::o, ai::interest::score, SIGHTMIN, fpsstate::skill, vec::squaredist(), ai::interest::state, ai::interest::target, ai::interest::targtype, entity::type, and ai::aiinfo::weappref.
Referenced by find(), and items().
void ai::update ()
References avoid(), forcegun, game::intermission, iteration, itermillis, loopv, multiplayer(), game::players, think(), totalmillis, and updatemillis.
Referenced by game::updateworld().
ai::VAR (aidebug , 0 , 0 , 6)
ai::VAR (aiforcegun , - 1, - 1, NUMGUNS- 1)
ai::VAR (showwaypoints , 0 , 0 , 1)
ai::VAR (showwaypointsradius , 0 , 200 , 10000)
ai::VARF (dropwaypoints , 0 , 0 , 1 , {player1->lastnode=-1;})
float ai::viewdist (int x)
References f(), SIGHTMAX, and SIGHTMIN.
Referenced by init().
float ai::viewfieldx (int x)
References f(), VIEWMAX, and VIEWMIN.
Referenced by init(), and viewfieldy().
float ai::viewfieldy (int x)
References viewfieldx().
Referenced by init().
bool ai::violence (fpsent * d, aistate & b, fpsent * e, int pursue)
References fpsent::ai, AI_S_PURSUE, AI_T_AFFINITY, AI_T_PLAYER, fpsent::clientnum, ai::aiinfo::enemy, ai::aiinfo::enemymillis, ai::aiinfo::enemyseen, lastmillis, fpsent::lastnode, makeroute(), ai::aiinfo::switchstate(), targetable(), and ai::aistate::targtype.
Referenced by game::ctfclientmode::aidefend(), game::ctfclientmode::aipursue(), damaged(), enemy(), process(), and target().
float ai::weapmaxdist (int weap)
References guns, and guninfo::range.
Referenced by weaprange().
float ai::weapmindist (int weap)
References guns, and inexor::rpc::max().
Referenced by weaprange().
bool ai::weaprange (fpsent * d, int weap, float dist)
References weapmaxdist(), and weapmindist().
Referenced by canshoot(), hasrange(), and hastarget().
int ai::wpspot (fpsent * d, int n, bool check = false)
References fpsent::ai, check(), physent::feetpos(), iswaypoint(), loopk, MINWPDIST, obstacles, ai::avoidset::remap(), ai::aiinfo::spot, vec::squaredist(), ai::aiinfo::targnode, and waypoints.
Referenced by anynode(), and hunt().
Variable Documentation
vec ai::aitarget
int ai::clearedwpcaches = (1<<NUMWPCACHES)-1 static
Referenced by ai::avoidset::avoidnear(), buildwpcache(), clearwpcache(), closestwaypoint(), and findwaypointswithin().
const float ai::CLOSEDIST = 32.f
Referenced by closenode(), and dointerest().
SharedVar<int> ai::dropwaypoints
Referenced by clearwaypoints(), savewaypoints(), shoulddrop(), and shouldnavigate().
const float ai::FARDIST = 128.f
Referenced by closenode().
int ai::forcegun = -1
Referenced by setup(), and update().
int ai::invalidatedwpcaches = 0 static
Referenced by clearwpcache(), invalidatewpcache(), and navigate().
int ai::iteration = 0
Referenced by update().
int ai::itermillis = 0
Referenced by update().
const float ai::JUMPMAX = 32.f
Referenced by ai::avoidset::remap().
const float ai::JUMPMIN = 4.f
Referenced by getweight(), and jumpto().
int ai::lastwpcache = 0 static
Referenced by ai::avoidset::avoidnear(), buildwpcache(), clearwpcache(), closestwaypoint(), and findwaypointswithin().
string ai::loadedwaypoints = ""
Referenced by clearwaypoints(), loadwaypoints(), and shoulddrop().
const int ai::MAXWAYPOINTLINKS = 6
Referenced by ai::waypoint::find(), linkwaypoint(), loadwaypoints(), randomlink(), remapwaypoints(), render(), route(), and savewaypoints().
const int ai::MAXWAYPOINTS = USHRT_MAX - 2
Referenced by addwaypoint().
const float ai::MINWPDIST = 4.f
Referenced by wpspot().
int ai::numinvalidatewpcaches = 0 static
Referenced by clearwpcache(), and invalidatewpcache().
const int ai::NUMPREVNODES = 6
Referenced by checkroute(), drawroute(), ai::aiinfo::hasprevnode(), and route().
avoidset ai::obstacles
Referenced by avoid(), checkroute(), closenode(), makeroute(), randomnode(), ai::avoidset::remap(), render(), and wpspot().
SharedVar<int> ai::showwaypoints
Referenced by render().
const float ai::SIGHTMAX = 1024.f
Referenced by navigate(), and viewdist().
const float ai::SIGHTMIN = 64.f
Referenced by game::captureclientmode::aifind(), game::collectclientmode::aifind(), game::ctfclientmode::aifind(), game::ctfclientmode::aihomerun(), dopursue(), dowait(), makeroute(), navigate(), process(), ai::avoidset::remap(), tryitem(), and viewdist().
const char* ai::stnames[AI_S_MAX]
Initial value:
= {
        "wait", "defend", "pursue", "interest"
    }
Referenced by render().
const char * ai::sttypes[AI_T_MAX+1]
Initial value:
= {
        "none", "node", "player", "affinity", "entity"
    }
Referenced by render().
vector<int> ai::targets static
Referenced by game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), damaged(), findassist(), and parseinterests().
int ai::updatemillis = 0
Referenced by update().
const float ai::VIEWMAX = 180.f
Referenced by viewfieldx().
const float ai::VIEWMIN = 90.f
Referenced by viewfieldx().
const int ai::WAYPOINTRADIUS = 16
Referenced by ai::wpcache::build(), buildwpcache(), inferwaypoints(), navigate(), and route().
vector< waypoint > ai::waypoints
Referenced by addwaypoint(), ai::avoidset::avoidnear(), ai::wpcache::build(), buildwpcache(), cleanwaypoints(), clearwaypoints(), closenode(), closestwaypoint(), delselwaypoints(), dodefend(), dointerest(), dopursue(), drawroute(), findwaypointswithin(), inferwaypoints(), iswaypoint(), loadwaypoints(), movewaypoints(), navigate(), randomlink(), ai::avoidset::remap(), remapwaypoints(), render(), route(), savewaypoints(), seedwaypoints(), and wpspot().
avoidset ai::wpavoid
Referenced by avoid(), and buildwpcache().
struct ai::wpcache ai::wpcaches[NUMWPCACHES]
Referenced by ai::avoidset::avoidnear(), buildwpcache(), clearwpcache(), closestwaypoint(), findwaypointswithin(), and invalidatewpcache().
vector<wpcache::node *> ai::wpcachestack