Inexor: aiman Namespace Reference
aiman Namespace Reference
Functions
VARN (serverbotlimit, botlimit, 0, 8, MAXBOTS)
VAR (serverbotbalance, 0, 1, 1)
void calcteams (vector< teamscore > &teams)
void balanceteams ()
const char * chooseteam ()
static bool validaiclient (clientinfo *ci)
clientinfo * findaiclient (clientinfo *exclude=nullptr)
bool addai (int skill, int limit)
void deleteai (clientinfo *ci)
bool deleteai ()
void reinitai (clientinfo *ci)
void shiftai (clientinfo *ci, clientinfo *owner=nullptr)
void removeai (clientinfo *ci)
bool reassignai ()
void checksetup ()
void clearai ()
void checkai ()
void reqadd (clientinfo *ci, int skill)
void reqdel (clientinfo *ci)
void setbotlimit (clientinfo *ci, int limit)
void setbotbalance (clientinfo *ci, bool balance)
void changemap ()
void addclient (clientinfo *ci)
void changeteam (clientinfo *ci)
Variables
bool dorefresh = false
bool botbalance = true
Function Documentation
bool aiman::addai (int skill, int limit)
References vector< T, MINSIZE >::add(), AI_BOT, server::bots, BOTTAG, chooseteam(), game::clients, copystring(), CS_DEAD, dorefresh, findaiclient(), lastmillis, loopv, m_teammode, MAXBOTS, MAXCLIENTS, MAXNAMELEN, MAXTAGLEN, MAXTEAMLEN, inexor::rpc::min(), rnd(), and physent::state.
Referenced by reqadd().
void aiman::addclient (clientinfo * ci)
References AI_NONE, and dorefresh.
void aiman::balanceteams ()
References vector< T, MINSIZE >::add(), server::bots, calcteams(), server::servmode::changeteam(), copystring(), CS_ALIVE, vector< T, MINSIZE >::last(), vector< T, MINSIZE >::length(), loopv, MAXTEAMLEN, N_SETTEAM, vector< T, MINSIZE >::remove(), vector< T, MINSIZE >::removeunordered(), teamscore::score, sendf(), server::smode, anonymous_namespace{utilTest.cpp}::t(), and teamscore::team.
Referenced by checksetup().
void aiman::calcteams (vector< teamscore > & teams)
References vector< T, MINSIZE >::add(), game::clients, teamscore::compare(), CS_SPECTATOR, vector< T, MINSIZE >::htfind(), vector< T, MINSIZE >::length(), loopi(), loopv, loopvj, teamscore::score, vector< T, MINSIZE >::sort(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by balanceteams(), and chooseteam().
void aiman::changemap ()
References botbalance, game::clients, dorefresh, loopv, and setbotbalance().
void aiman::changeteam (clientinfo * ci)
References AI_NONE, and dorefresh.
void aiman::checkai ()
References checksetup(), clearai(), dorefresh, m_botmode, server::numclients(), and reassignai().
void aiman::checksetup ()
References balanceteams(), botbalance, server::bots, loopvrev, m_teammode, and reinitai().
Referenced by checkai().
const char* aiman::chooseteam ()
References calcteams(), vector< T, MINSIZE >::last(), vector< T, MINSIZE >::length(), and teamscore::team.
Referenced by addai().
void aiman::clearai ()
References server::bots, deleteai(), and loopvrev.
Referenced by checkai().
void aiman::deleteai (clientinfo * ci)
References server::bots, game::clients, DELETEP, dorefresh, server::get_client_info(), server::servmode::leavegame(), MAXCLIENTS, N_CDIS, vector< T, MINSIZE >::removeobj(), sendf(), and server::smode.
Referenced by clearai(), deleteai(), reinitai(), and reqdel().
bool aiman::deleteai ()
References server::bots, deleteai(), and loopvrev.
clientinfo* aiman::findaiclient (clientinfo * exclude = nullptr)
References game::clients, loopv, and validaiclient().
Referenced by addai(), and removeai().
bool aiman::reassignai ()
References game::clients, loopv, loopvrev, shiftai(), and validaiclient().
Referenced by checkai().
void aiman::reinitai (clientinfo * ci)
References BOTTAG, CS_ALIVE, deleteai(), N_INITAI, sendf(), sendresume(), and server::sendspawn().
Referenced by checksetup().
void aiman::removeai (clientinfo * ci)
References findaiclient(), loopvrev, and shiftai().
void aiman::reqadd (clientinfo * ci, int skill)
References addai(), N_SERVMSG, PRIV_ADMIN, and sendf().
void aiman::reqdel (clientinfo * ci)
References deleteai(), N_SERVMSG, and sendf().
void aiman::setbotbalance (clientinfo * ci, bool balance)
References botbalance, defformatstring, dorefresh, and sendservmsg().
Referenced by changemap().
void aiman::setbotlimit (clientinfo * ci, int limit)
References defformatstring, dorefresh, MAXBOTS, PRIV_ADMIN, and sendservmsg().
void aiman::shiftai (clientinfo * ci, clientinfo * owner = nullptr)
References dorefresh, server::get_client_info(), server::servmode::leavegame(), and server::smode.
Referenced by reassignai(), and removeai().
static bool aiman::validaiclient (clientinfo * ci) inline static
References AI_NONE, and CS_SPECTATOR.
Referenced by findaiclient(), and reassignai().
aiman::VAR (serverbotbalance , 0 , 1 , 1)
aiman::VARN (serverbotlimit , botlimit , 0 , 8 , MAXBOTS)
Variable Documentation
bool aiman::botbalance = true
Referenced by changemap(), checksetup(), and setbotbalance().
bool aiman::dorefresh = false
Referenced by addai(), addclient(), changemap(), changeteam(), checkai(), deleteai(), setbotbalance(), setbotlimit(), and shiftai().