Inexor: server::aiman Namespace Reference
server::aiman Namespace Reference
Functions
VARN (serverbotlimit, botlimit, 0, 8, MAXBOTS)
VAR (serverbotbalance, 0, 1, 1)
void calcteams (vector< teamscore > &teams)
void balanceteams ()
const char * chooseteam ()
static bool validaiclient (clientinfo *ci)
clientinfo * findaiclient (clientinfo *exclude=nullptr)
bool addai (int skill, int limit)
void deleteai (clientinfo *ci)
bool deleteai ()
void reinitai (clientinfo *ci)
void shiftai (clientinfo *ci, clientinfo *owner=nullptr)
void removeai (clientinfo *ci)
bool reassignai ()
void checksetup ()
void clearai ()
void checkai ()
void reqadd (clientinfo *ci, int skill)
void reqdel (clientinfo *ci)
void setbotlimit (clientinfo *ci, int limit)
void setbotbalance (clientinfo *ci, bool balance)
void changemap ()
void addclient (clientinfo *ci)
void changeteam (clientinfo *ci)
Variables
bool dorefresh = false
bool botbalance = true
Function Documentation
bool server::aiman::addai (int skill, int limit)
void server::aiman::addclient (clientinfo * ci)
Referenced by server::player_connected(), and server::unspectate().
void server::aiman::balanceteams ()
References server::flushserver(), and server::getservermtu().
void server::aiman::calcteams (vector< teamscore > & teams)
void server::aiman::changemap ()
Referenced by server::changemap().
void server::aiman::changeteam (clientinfo * ci)
Referenced by server::parsepacket().
void server::aiman::checkai ()
References server::addban(), server::teamkillkick::ban, server::teamkillinfo::ip, and server::kickclients().
Referenced by server::serverupdate().
void server::aiman::checksetup ()
const char* server::aiman::chooseteam ()
void server::aiman::clearai ()
References server::teamkillkick::limit, and server::teamkillinfo::teamkills.
Referenced by server::changemap(), and server::noclients().
void server::aiman::deleteai (clientinfo * ci)
bool server::aiman::deleteai ()
clientinfo* server::aiman::findaiclient (clientinfo * exclude = nullptr)
bool server::aiman::reassignai ()
void server::aiman::reinitai (clientinfo * ci)
void server::aiman::removeai (clientinfo * ci)
Referenced by server::checkmaps(), server::disconnect_client(), server::forcespectator(), and server::revokemaster().
void server::aiman::reqadd (clientinfo * ci, int skill)
Referenced by server::parsepacket().
void server::aiman::reqdel (clientinfo * ci)
Referenced by server::parsepacket().
void server::aiman::setbotbalance (clientinfo * ci, bool balance)
Referenced by server::parsepacket().
void server::aiman::setbotlimit (clientinfo * ci, int limit)
Referenced by server::parsepacket().
void server::aiman::shiftai (clientinfo * ci, clientinfo * owner = nullptr)
static bool server::aiman::validaiclient (clientinfo * ci) inline static
server::aiman::VAR (serverbotbalance , 0 , 1 , 1)
server::aiman::VARN (serverbotlimit , botlimit , 0 , 8 , MAXBOTS)
Variable Documentation
bool server::aiman::botbalance = true
bool server::aiman::dorefresh = false