Inexor: fogdome Namespace Reference
fogdome Namespace Reference
Classes
struct vert
Functions
void subdivide (int depth, int face)
void genface (int depth, int i1, int i2, int i3)
int sortcap (GLushort x, GLushort y)
void init (const bvec &color, float minalpha=0.0f, float maxalpha=1.0f, float capsize=-1, float clipz=1, int hres=16, int depth=2)
void cleanup ()
void draw ()
Variables
struct fogdome::vert * verts = nullptr
GLushort * indices = nullptr
int numverts = 0
int numindices = 0
int capindices = 0
GLuint vbuf = 0
GLuint ebuf = 0
bvec lastcolor (0, 0, 0)
float lastminalpha = 0
float lastmaxalpha = 0
float lastcapsize = -1
float lastclipz = 1
Function Documentation
void fogdome::cleanup ()
References ebuf, glDeleteBuffers_, numindices, numverts, and vbuf.
Referenced by cleanupsky().
void fogdome::draw ()
References gle::bindebo(), gle::bindvbo(), capindices, gle::clearebo(), gle::clearvbo(), gle::color(), fogdome::vert::color, ebuf, fogcolor, fogdomecolor, glde, glDrawRangeElements_, indices, init(), lastcapsize, lastclipz, lastcolor, lastmaxalpha, lastminalpha, inexor::rpc::min(), numindices, numverts, fogdome::vert::pos, vbuf, verts, and xtraverts.
Referenced by drawfogdome().
void fogdome::genface (int depth, int i1, int i2, int i3)
References indices, numindices, and subdivide().
Referenced by init(), and subdivide().
void fogdome::init (const bvec & color, float minalpha = 0.0f, float maxalpha = 1.0f, float capsize = -1, float clipz = 1, int hres = 16, int depth = 2)
References gle::bindebo(), gle::bindvbo(), capindices, DELETEA, ebuf, f(), genface(), glBufferData_, glGenBuffers_, indices, loopi(), numindices, numverts, quicksort(), sincos360, sortcap(), vbuf, and verts.
Referenced by draw().
int fogdome::sortcap (GLushort x, GLushort y)
References fogdome::vert::pos, and verts.
Referenced by init().
void fogdome::subdivide (int depth, int face)
References genface(), indices, loopi(), numverts, and verts.
Referenced by genface().
Variable Documentation
int fogdome::capindices = 0
Referenced by draw(), and init().
GLuint fogdome::ebuf = 0
Referenced by cleanup(), draw(), and init().
GLushort* fogdome::indices = nullptr
Referenced by draw(), genface(), init(), and subdivide().
float fogdome::lastcapsize = -1
Referenced by draw().
float fogdome::lastclipz = 1
Referenced by draw().
bvec fogdome::lastcolor(0, 0, 0)
Referenced by draw().
float fogdome::lastmaxalpha = 0
Referenced by draw().
float fogdome::lastminalpha = 0
Referenced by draw().
int fogdome::numindices = 0
Referenced by cleanup(), draw(), genface(), and init().
int fogdome::numverts = 0
Referenced by cleanup(), draw(), init(), and subdivide().
GLuint fogdome::vbuf = 0
Referenced by cleanup(), draw(), and init().
struct fogdome::vert * fogdome::verts = nullptr
Referenced by draw(), init(), sortcap(), and subdivide().