Inexor: tiger Namespace Reference
tiger Namespace Reference
Classes
union hashval
Typedefs
typedef unsigned long long int chunk
Functions
void compress (const chunk *str, chunk state[3])
void gensboxes ()
void hash (const uchar *str, int length, hashval &val)
Variables
chunk sboxes [4 *256]
Class Documentation
union tiger::hashval
Class Members
uchar bytes[3 *8]
chunk chunks[3]
Typedef Documentation
typedef unsigned long long int tiger::chunk
Function Documentation
void tiger::compress (const chunk * str, chunk state[3])
References loop, round, and TIGER_PASSES.
Referenced by Slot::combinetextures(), cubemaploadwildcard(), gensboxes(), hash(), reloadtexture(), savepng(), texturedata(), and textureload().
void tiger::gensboxes ()
References compress(), islittleendian, loop, loopi(), loopj, sboxes, and recorder::state.
Referenced by hash().
void tiger::hash (const uchar * str, int length, hashval & val)
References tiger::hashval::bytes, tiger::hashval::chunks, compress(), gensboxes(), sphere::init(), islittleendian, loopj, loopk, and loopl.
Referenced by addvisibleva(), checkpassword(), game::hashpwd(), hashstring(), hthash(), blobrenderer::renderblob(), game::sendintro(), and game::setmaster().
Variable Documentation
chunk tiger::sboxes[4 *256]
Referenced by gensboxes().