Inexor: recorder Namespace Reference
recorder Namespace Reference
Classes
struct soundbuffer
struct videobuffer
Enumerations
enum { REC_OK = 0, REC_USERHALT, REC_TOOSLOW, REC_FILERROR }
enum { MAXSOUNDBUFFERS = 128 }
enum { MAXVIDEOBUFFERS = 2 }
Functions
bool isrecording ()
float calcquality ()
int gettime ()
int videoencoder (void *data)
void soundencoder (void *udata, Uint8 *stream, int len)
void start (const char *filename, int videofps, int videow, int videoh, bool sound)
void cleanup ()
void stop ()
void readbuffer (videobuffer &m, uint nextframe)
bool readbuffer ()
void drawhud ()
void capture (bool overlay)
Variables
static enum recorder:: { ... } state = REC_OK
static aviwriter * file = nullptr
static int starttime = 0
static int stats [1000]
static int statsindex = 0
static uint dps = 0
static queue< soundbuffer,
MAXSOUNDBUFFERS > soundbuffers
static SDL_mutex * soundlock = nullptr
static queue< videobuffer,
MAXVIDEOBUFFERS > videobuffers
static uint lastframe = ~0U
static GLuint scalefb = 0
static GLuint scaletex [2] = { 0, 0 }
static uint scalew = 0
static uint scaleh = 0
static GLuint encodefb = 0
static GLuint encoderb = 0
static SDL_Thread * thread = nullptr
static SDL_mutex * videolock = nullptr
static SDL_cond * shouldencode = nullptr
static SDL_cond * shouldread = nullptr
Enumeration Type Documentation
anonymous enum
Enumerator
REC_OK
REC_USERHALT
REC_TOOSLOW
REC_FILERROR
anonymous enum
Enumerator
MAXSOUNDBUFFERS
anonymous enum
Enumerator
MAXVIDEOBUFFERS
Function Documentation
float recorder::calcquality ()
References dps, file, and aviwriter::videofps.
Referenced by drawhud(), and videoencoder().
void recorder::capture (bool overlay)
References drawhud(), and readbuffer().
Referenced by inexor::rendering::screen::ScreenManager::swapbuffers().
void recorder::cleanup ()
References encodefb, encoderb, glDeleteFramebuffers_, glDeleteRenderbuffers_, scalefb, scaleh, scaletex, and scalew.
Referenced by resetgl().
void recorder::drawhud ()
References calcquality(), draw_textf(), f(), file, aviwriter::filespaceguess(), FONTH, forceaspect, gettextres(), hudmatrix, hudshader, matrix4::ortho(), resethudmatrix(), matrix4::scale(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, and Shader::set().
Referenced by capture().
int recorder::gettime ()
References inbetweenframes, time_since_program_start(), and totalmillis.
Referenced by readbuffer(), soundencoder(), and start().
bool recorder::isrecording ()
References file.
Referenced by movie().
void recorder::readbuffer (videobuffer & m, uint nextframe)
References createtexture(), encodefb, encoderb, f(), file, recorder::videobuffer::format, recorder::videobuffer::frame, GL_COLOR_ATTACHMENT0, GL_DRAW_FRAMEBUFFER, GL_FRAMEBUFFER, GL_READ_FRAMEBUFFER, GL_RENDERBUFFER, glBindFramebuffer_, glBindRenderbuffer_, glBlitFramebuffer_, glFramebufferRenderbuffer_, glFramebufferTexture2D_, glGenFramebuffers_, glGenRenderbuffers_, GLOBALPARAMF, glRenderbufferStorage_, recorder::videobuffer::h, hasFBB, recorder::videobuffer::init(), loopi(), inexor::rpc::max(), scalefb, scaleh, scaletex, scalew, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, screenquad(), screenquadflipped(), inexor::rendering::screen::ScreenManager::screenw, SETSHADER, texalign(), aviwriter::VID_RGB, aviwriter::VID_YUV, aviwriter::VID_YUV420, recorder::videobuffer::video, aviwriter::videoh, aviwriter::videow, and recorder::videobuffer::w.
bool recorder::readbuffer ()
References file, gettime(), lastframe, inexor::rpc::max(), REC_OK, shouldencode, shouldread, starttime, state, stop(), videobuffers, aviwriter::videofps, and videolock.
Referenced by capture().
void recorder::soundencoder (void * udata, Uint8 * stream, int len)
References file, gettime(), recorder::soundbuffer::load(), inexor::rpc::max(), REC_OK, REC_TOOSLOW, soundbuffers, soundlock, starttime, state, and aviwriter::videofps.
void recorder::start (const char * filename, int videofps, int videow, int videoh, bool sound)
References DELETEP, dps, file, aviwriter::filename, getfps(), gettime(), lastframe, Log, loopi(), MAXVIDEOBUFFERS, aviwriter::open(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenw, shouldencode, shouldread, soundbuffers, aviwriter::soundfrequency, soundlock, starttime, stats, statsindex, inexor::util::log_manager::std, thread, useshaderbyname(), videobuffers, videoencoder(), aviwriter::videofps, aviwriter::videoh, videolock, and aviwriter::videow.
Referenced by addtris(), at(), calclight(), compileblock(), compileblockstr(), compileblocksub(), compileval(), editline::del(), gle::end(), explodelist(), server::findmaprotation(), generatelightmap(), genpvs(), Shader::getvariant(), indexlist(), listdel(), listfilter(), listfind(), listincludes(), listsplice(), md5::md5mesh::load(), looplist(), looplistconc(), movie(), gle::multidraw(), optimizematsurfs(), parselist(), patchlight(), prettylist(), ipmask::print(), quicksort(), skelcommands< MDL >::setanim(), Shader::setvariant_(), sortlist(), sublist(), and unescapestring().
void recorder::stop ()
References cleanup(), DELETEP, file, Log, loopi(), MAXSOUNDBUFFERS, MAXVIDEOBUFFERS, REC_OK, REC_USERHALT, shouldencode, shouldread, soundbuffers, soundlock, state, inexor::util::log_manager::std, thread, videobuffers, aviwriter::videoframes, and videolock.
Referenced by cleanup(), movie(), and readbuffer().
int recorder::videoencoder (void * data)
References calcquality(), dps, file, recorder::videobuffer::format, recorder::soundbuffer::frame, recorder::videobuffer::frame, recorder::videobuffer::h, loopi(), REC_FILERROR, REC_OK, REC_TOOSLOW, shouldencode, shouldread, recorder::soundbuffer::size, recorder::soundbuffer::sound, soundbuffers, aviwriter::soundfrequency, soundlock, state, stats, statsindex, recorder::videobuffer::video, videobuffers, aviwriter::videofps, aviwriter::videoframes, videolock, recorder::videobuffer::w, aviwriter::writesound(), and aviwriter::writevideoframe().
Referenced by start().
Variable Documentation
uint recorder::dps = 0 static
Referenced by calcquality(), start(), and videoencoder().
GLuint recorder::encodefb = 0 static
Referenced by cleanup(), and readbuffer().
GLuint recorder::encoderb = 0 static
Referenced by cleanup(), and readbuffer().
aviwriter* recorder::file = nullptr static
Referenced by calcquality(), drawhud(), isrecording(), inexor::filesystem::list_files(), obj::objmeshgroup::load(), md2::md2meshgroup::load(), editor::load(), openrawfile(), opentempfile(), path(), game::preloadweapons(), readbuffer(), editor::save(), server::setupdemoplayback(), soundencoder(), start(), stop(), texturedata(), and videoencoder().
uint recorder::lastframe = ~0U static
Referenced by readbuffer(), and start().
GLuint recorder::scalefb = 0 static
Referenced by cleanup(), and readbuffer().
uint recorder::scaleh = 0 static
Referenced by cleanup(), and readbuffer().
GLuint recorder::scaletex[2] = { 0, 0 } static
Referenced by cleanup(), and readbuffer().
uint recorder::scalew = 0 static
Referenced by cleanup(), and readbuffer().
SDL_cond* recorder::shouldencode = nullptr static
Referenced by readbuffer(), start(), stop(), and videoencoder().
SDL_cond * recorder::shouldread = nullptr static
Referenced by readbuffer(), start(), stop(), and videoencoder().
queue<soundbuffer, MAXSOUNDBUFFERS> recorder::soundbuffers static
Referenced by soundencoder(), start(), stop(), and videoencoder().
SDL_mutex* recorder::soundlock = nullptr static
Referenced by soundencoder(), start(), stop(), and videoencoder().
int recorder::starttime = 0 static
Referenced by readbuffer(), resolverwait(), texturegui::showtextures(), soundencoder(), and start().
enum { ... } recorder::state
Referenced by game::abovegameplayhud(), bindkey(), server::checklms(), game::cycleweapon(), entities::doleveltrigger(), execbind(), server::bombservermode::gamerunning(), tiger::gensboxes(), server::collectservermode::initclient(), game::nextfollow(), server::captureservermode::parsebases(), readbuffer(), ai::render(), server::hideandseekservermode::setfreezedstate(), server::captureservermode::setup(), soundencoder(), stop(), game::updatepos(), and videoencoder().
int recorder::stats[1000] static
Referenced by start(), and videoencoder().
int recorder::statsindex = 0 static
Referenced by start(), and videoencoder().
SDL_Thread* recorder::thread = nullptr static
Referenced by genpvs(), resolverloop(), start(), stop(), and TEST().
queue<videobuffer, MAXVIDEOBUFFERS> recorder::videobuffers static
Referenced by readbuffer(), start(), stop(), and videoencoder().
SDL_mutex* recorder::videolock = nullptr static
Referenced by readbuffer(), start(), stop(), and videoencoder().