Inexor: server Namespace Reference
server Namespace Reference
Namespaces
aiman
Classes
struct maprotation
struct teamkillkick
struct teamkillinfo
struct teamrank
struct msgfilter
MSG filter works as a firewall it allowes only certain messages for certain things, see checktype -1 will become 1 in the switchcase below, its a hack to not misinterpretate the different cases as messages.
struct worldstate
struct votecount
struct crcinfo
struct ban
struct savedscore
Save scores if client disconnects to restore it when he reconnects.
struct client
server side version of "dynent" type
struct projectilestate
struct gamestate
server specialisation of the fpsstate (?)
struct gameevent
struct timedevent
struct hitinfo
struct shotevent
struct explodeevent
struct suicideevent
struct pickupevent
struct clientinfo
struct demofile
struct bombservermode
struct captureservermode
struct collectservermode
struct ctfservermode
struct servmode
struct hideandseekservermode
Functions
void flushserver (bool force)
int getservermtu ()
VAR (lockmaprotation, 0, 0, 2)
void maprotationreset ()
void nextmaprotation ()
int findmaprotation (int mode, const char *map)
bool addmaprotation (int modemask, const char *map)
void addmaprotations (tagval *args, int numargs)
COMMAND (maprotationreset,"")
COMMANDN (maprotation, addmaprotations,"ss2V")
VAR (restrictdemos, 0, 1, 1)
VAR (restrictpausegame, 0, 0, 1)
VAR (restrictgamespeed, 0, 1, 1)
VAR (restrictpersistteams, 0, 0, 1)
SVAR (serverdesc,"")
SVAR (servermotd,"")
VAR (spectatemodifiedmap, 0, 1, 1)
void teamkillkickreset ()
void addteamkillkick (char *modestr, int *limit, int *ban)
COMMAND (teamkillkickreset,"")
COMMANDN (teamkillkick, addteamkillkick,"sii")
void addteamkill (clientinfo *actor, clientinfo *victim, int n)
void checkteamkills ()
void resetitems ()
void serverinit ()
bool canspawnitem (int type)
int spawntime (int type)
bool pickup (int i, int sender)
void clearteaminfo ()
bool teamhasplayers (const char *team)
bool pruneteaminfo ()
teaminfo * addteaminfo (const char *team)
clientinfo * choosebestclient (float &bestrank)
void autoteam ()
const char * chooseworstteam (const char *suggest=nullptr, clientinfo *exclude=nullptr)
void assign_team (clientinfo *ci)
static void freegetmap (ENetPacket *packet)
void checkpausegame ()
If no player with a high enough privilege level is on the server, resume the game.
bool ispaused ()
void changegamespeed (int val, clientinfo *ci=nullptr)
void persistteams (bool val)
void checkpersistteams ()
static struct server::msgfilter msgfilter (-1, N_CONNECT, N_SERVINFO, N_INITCLIENT, N_WELCOME, N_MAPCHANGE, N_SERVMSG, N_DAMAGE, N_HITPUSH, N_SHOTFX, N_EXPLODEFX, N_DIED, N_SPAWNSTATE, N_FORCEDEATH, N_TEAMINFO, N_ITEMACC, N_ITEMSPAWN, N_TIMEUP, N_CDIS, N_CURRENTMASTER, N_PONG, N_RESUME, N_BASESCORE, N_BASEINFO, N_BASEREGEN, N_ANNOUNCE, N_SENDDEMOLIST, N_SENDDEMO, N_DEMOPLAYBACK, N_SENDMAP, N_DROPFLAG, N_SCOREFLAG, N_RETURNFLAG, N_RESETFLAG, N_INVISFLAG, N_CLIENT, N_INITAI, N_EXPIRETOKENS, N_DROPTOKENS, N_STEALTOKENS, N_DEMOPACKET,-2, N_REMIP, N_NEWMAP, N_GETMAP, N_SENDMAP, N_CLIPBOARD,-3, N_EDITENT, N_EDITF, N_EDITT, N_EDITM, N_FLIP, N_COPY, N_PASTE, N_ROTATE, N_REPLACE, N_DELCUBE, N_EDITVAR, N_EDITVSLOT, N_UNDO, N_REDO,-4, N_POS, NUMMSG)
int checktype (int type, clientinfo *ci)
void cleanworldstate (ENetPacket *packet)
void flushclientposition (clientinfo &ci)
static void sendpositions (worldstate &ws, ucharbuf &wsbuf)
static void addposition (worldstate &ws, ucharbuf &wsbuf, int mtu, clientinfo &bi, clientinfo &ci)
static void sendmessages (worldstate &ws, ucharbuf &wsbuf)
static void addmessages (worldstate &ws, ucharbuf &wsbuf, int mtu, clientinfo &bi, clientinfo &ci)
bool buildworldstate ()
bool sendpackets (bool force)
template<class T >
void sendstate (gamestate &gs, T &p)
void spawnstate (clientinfo *ci)
void sendspawn (clientinfo *ci)
int welcomepacket (packetbuf &p, clientinfo *ci)
void sendwelcome (clientinfo *ci)
void putinitclient (clientinfo *ci, packetbuf &p)
void welcomeinitclient (packetbuf &p, int exclude=-1)
void sendinitclient (clientinfo *ci)
void loaditems ()
void changemap (const char *s, int mode)
ICOMMAND (mapmode,"si",(char *name, int *mode), changemap(name,*mode))
void rotatemap (bool next)
bool hasmap (clientinfo *ci)
void choosemap (clientinfo *ci)
void checkvotes (bool force=false)
void vote (const char *map, int reqmode, int sender)
void checkintermission ()
void startintermission ()
void checklms ()
Checks if the game has ended because only one player is still alive.
void dodamage (clientinfo *target, clientinfo *actor, int damage, int gun, const vec &hitpush=vec(0, 0, 0))
void suicide (clientinfo *ci)
void clearevent (clientinfo *ci)
void flushevents (clientinfo *ci, int millis)
void processevents ()
void cleartimedevents (clientinfo *ci)
void serverupdate ()
void forcespectator (clientinfo *ci)
VAR (modifiedmapspectator, 0, 1, 2)
void checkmaps (int req=-1)
bool shouldspectate (clientinfo *ci)
void unspectate (clientinfo *ci)
void sendclipboard (clientinfo *ci)
bool allowbroadcast (int n)
void receivefile (int sender, uchar *data, int len)
void parsepacket (int sender, int chan, packetbuf &p)
void serverinforeply (ucharbuf &req, ucharbuf &p)
bool servercompatible (char *name, char *sdec, char *map, int ping, const vector< int > &attr, int np)
void sendresume (clientinfo *ci)
void clientdisconnect (int n)
int clientconnect (int n, uint ip)
VARF (maxclients, 0, DEFAULTCLIENTS, MAXCLIENTS,{if(!maxclients) maxclients=DEFAULTCLIENTS;})
VARF (maxdupclients, 0, 0, MAXCLIENTS,{if(serverhost) serverhost->duplicatePeers=maxdupclients?maxdupclients:MAXCLIENTS;})
Max clients from same peer.
int reserveclients ()
The amount of people who can connect more than the actual specified max clients limit.
SVAR (serverpass,"")
SVAR (adminpass,"")
VARF (publicserver, 0, 0, 2,{switch(*publicserver){case 0:default:mastermask=MM_PRIVSERV;break;case 1:mastermask=MM_PUBSERV;break;case 2:mastermask=MM_COOPSERV;break;}})
ENetPeer * getclientpeer (int i)
uint getclientip (int n)
bool has_clients ()
int get_num_clients ()
int numclients (int exclude=-1, bool nospec=true, bool noai=true, bool priv=false)
List all connected clients (game players)
clientinfo * get_client_info (int n, bool findbots)
bool duplicatename (clientinfo *ci, const char *name)
const char * colorname (clientinfo *ci, const char *name=nullptr)
colorful version of the clients name (if two people share the same name or ci is a bot)
void addban (uint ip, int expire)
void clearbans (clientinfo *actor)
void check_bans_expired ()
void kickclients (uint ip, clientinfo *actor=nullptr, int priv=PRIV_NONE)
Kick all clients with this IP (including bots and people in the same LAN)
bool trykick (clientinfo *ci, int victim, const char *reason, bool trial)
void cleargbans ()
bool checkgban (uint ip)
void addgban (const char *name)
int allowconnect (clientinfo *ci, const char *pwd="")
void change_mastermode (int mm, int sendernum, clientinfo *actor)
int get_mastermode_int ()
void revokemaster (clientinfo *ci)
bool setmaster (clientinfo *ci, bool val, const char *pass, bool force, bool trial)
savedscore * findscore (clientinfo *ci, bool insert)
void savescore (clientinfo *ci)
bool restorescore (clientinfo *ci)
void resetdisconnectedplayerscores ()
New map: we throw away the scores of disconnected players.
void sendservinfo (clientinfo *ci)
bool player_connected (clientinfo *ci, const char *password, const char *mapwish, int modewish)
void promote_if_local_client (client *c)
If client ci is from the same ip as this server -> make him priv_local.
client & add_client_connection (ENetPeer *peer)
void delete_client_connection (client *c)
void noclients ()
void disconnect_client (int n, int reason)
void check_clients_timed_out ()
After some period of time without response we disconnect a client.
VAR (maxdemos, 0, 5, 25)
VAR (maxdemosize, 0, 16, 31)
void prunedemos (int extra=0)
void adddemo ()
void enddemorecord ()
void writedemo (int chan, void *data, int len)
void recordpacket (int chan, void *data, int len)
void setupdemorecord ()
void listdemos (int cn)
Send a list of demos to that client.
void cleardemos (int n)
Remove all demos until demo number n or all if n = 0.
static void freegetdemo (ENetPacket *packet)
void senddemo (clientinfo *ci, int num)
Send a specific demo to the client.
void enddemoplayback ()
void setupdemoplayback ()
void readdemo ()
void stopdemo ()
Wrapper for either enddemoplayback or enddemorecord, depending on m_demo.
VAR (extinfoip, 0, 0, 1)
void extinfoplayer (ucharbuf &p, clientinfo *ci)
static void extinfoteamscore (ucharbuf &p, const char *team, int score)
void extinfoteams (ucharbuf &p)
void extserverinforeply (ucharbuf &req, ucharbuf &p)
void pausegame (bool val, clientinfo *ci)
VAR (ctftkpenalty, 0, 1, 1)
void cleanupserver ()
void process (ENetPacket *packet, int sender, int chan)
bool resolverwait (const char *name, ENetAddress *address)
int connectwithtimeout (ENetSocket sock, const char *hostname, const ENetAddress &remoteaddress)
void sendserverinforeply (ucharbuf &p)
void checkserversockets ()
Reply all server info requests.
VAR (serveruprate, 0, 0, INT_MAX)
SVAR (serverip,"")
VARF (serverport, 0, INEXOR_SERVER_PORT, MAX_POSSIBLE_PORT,{if(!serverport) serverport=server_port();})
void serverslice (uint timeout)
main server update
void run_server ()
bool servererror (const char *desc)
bool setup_network_sockets ()
Variables
int gamelimit = 0
int nextexceeded = 0
int gamespeed = 100
bool shouldstep = true
int interm = 0
bool teamspersisted
Whether team reshuffeling after map change is disabled.
enet_uint32 lastsend = 0
stream * mapdata = nullptr
string smapname = ""
bool notgotitems = true
vector< maprotation > maprotations
int curmaprotation = 0
vector< teamkillkick > teamkillkicks
vector< teamkillinfo > teamkills
bool shouldcheckteamkills = false
uint mcrc = 0
vector< entity > ments
vector< server_entity > sents
captureservermode capturemode
ctfservermode ctfmode
collectservermode collectmode
bombservermode bombmode
hideandseekservermode hideandseekmode
servmode * smode = nullptr
hashset< teaminfo > teaminfos
struct server::worldstate msgfilter
vector< worldstate > worldstates
bool reliablemessages = false
ENetHost * serverhost = nullptr
vector< client * > client_connections
TODO merge with clients or connects.
vector< clientinfo * > connects
vector< clientinfo * > clients
vector< clientinfo * > bots
int client_count = 0
Idk why client_connections.length isnt used here: we try to avoid resetting the vector completely (probably an optimisation), but just free the buffers from it and set the connection->connected to false and the next player joining fills the gap.
vector< uint > allowedips
allowed IPs: mastermode locked allows some players to be unspectated immediately?
vector< ban > bannedips
vector< ipmask > gbans
int mastermode = MM_OPEN
int mastermask = MM_PRIVSERV
vector< savedscore > scores
SharedVar< char * > serverdesc
SharedVar< char * > servermotd
SharedVar< int > maxclients
SharedVar< int > maxdupclients
static constexpr int DEATHMILLIS = 300
vector< demofile > demos
bool demonextmatch = false
Whether we want to record a demo next match.
stream * demotmp = nullptr
stream * demorecord = nullptr
The streams for demo playback or demo recording.
stream * demoplayback = nullptr
int nextplayback = 0
int demomillis = 0
SharedVar< int > maxdemos
SharedVar< int > maxdemosize
bool gamepaused = false
Whether this game is currently paused.
int laststatus = 0
ENetSocket pongsock = ENET_SOCKET_NULL
ENetSocket lansock = ENET_SOCKET_NULL
ENetAddress serveraddress = { ENET_HOST_ANY, ENET_PORT_ANY }
static ENetAddress pongaddr
Class Documentation
struct server::teamkillinfo
Class Members
uint ip
int teamkills
struct server::ban
Class Members
int expire
uint ip
int time
struct server::client
server side version of "dynent" type
Class Members
bool connected
string hostname
void * info
int num
ENetPeer * peer
struct server::hitinfo
Class Members
vec dir
float dist
int lifesequence
int rays
int target
struct server::demofile
Class Members
uchar * data
string info
int len
Function Documentation
client & server::add_client_connection (ENetPeer * peer)
References client_connections, client_count, server::client::connected, game::connected, server::client::info, loopv, server::client::num, server::client::peer, and promote_if_local_client().
Referenced by serverslice().
void server::addban (uint ip, int expire)
References allowedips, bannedips, server::ban::expire, server::ban::ip, loopv, server::ban::time, and totalmillis.
Referenced by server::aiman::checkai(), and trykick().
void server::adddemo ()
References hmap::d, server::demofile::data, DELETEP, demos, demotmp, f(), formatstring(), gamemode, server::demofile::info, iscubespace(), server::demofile::len, maxdemosize, inexor::rpc::min(), modename(), stream::read(), stream::seek(), sendservmsgf(), stream::size(), smapname, and anonymous_namespace{utilTest.cpp}::t().
Referenced by enddemorecord().
void server::addgban (const char * name)
References AI_NONE, fpsstate::aitype, checkgban(), server::clientinfo::clientnum, clients, DISC_IPBAN, disconnect_client(), gbans, getclientip(), loopvrev, ipmask::parse(), PRIV_ADMIN, server::clientinfo::privilege, and server::clientinfo::state.
bool server::addmaprotation (int modemask, const char * map)
References copystring(), server::maprotation::exclude, loopk, m_check, M_EDIT, server::maprotation::map, maprotations, server::maprotation::modes, and NUMGAMEMODES.
Referenced by addmaprotations().
void server::addmaprotations (tagval * args, int numargs)
References addmaprotation(), explodelist(), genmodemask(), getstr(), vector< T, MINSIZE >::length(), and loopvj.
static void server::addmessages (worldstate & ws, ucharbuf & wsbuf, int mtu, clientinfo & bi, clientinfo & ci) inline static
References databuf< T >::buf, server::clientinfo::clientnum, vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::getbuf(), databuf< T >::length(), vector< T, MINSIZE >::length(), server::clientinfo::messages, N_CLIENT, databuf< T >::put(), putint(), putuint(), sendmessages(), vector< T, MINSIZE >::setsize(), server::clientinfo::wsdata, and server::clientinfo::wslen.
Referenced by buildworldstate().
static void server::addposition (worldstate & ws, ucharbuf & wsbuf, int mtu, clientinfo & bi, clientinfo & ci) inline static
References databuf< T >::buf, vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::getbuf(), databuf< T >::length(), vector< T, MINSIZE >::length(), server::clientinfo::position, databuf< T >::put(), sendpositions(), vector< T, MINSIZE >::setsize(), server::clientinfo::wsdata, and server::clientinfo::wslen.
Referenced by buildworldstate().
teaminfo* server::addteaminfo (const char * team)
References copystring(), teaminfo::frags, MAXTEAMS, pruneteaminfo(), anonymous_namespace{utilTest.cpp}::t(), teaminfo::team, and teaminfos.
Referenced by autoteam(), and parsepacket().
void server::addteamkill (clientinfo * actor, clientinfo * victim, int n)
References AI_NONE, fpsstate::aitype, server::clientinfo::clientnum, getclientip(), loopv, m_timed, server::clientinfo::privilege, shouldcheckteamkills, server::clientinfo::state, and teamkills.
Referenced by dodamage().
void server::addteamkillkick (char * modestr, int * limit, int * ban)
References explodelist(), genmodemask(), game::kick(), server::teamkillkick::modes, and teamkillkicks.
bool server::allowbroadcast (int n)
References server::clientinfo::connected, and get_client_info().
Referenced by sendpacket().
int server::allowconnect (clientinfo * ci, const char * pwd = "")
References allowedips, bannedips, checkgban(), checkpassword(), server::clientinfo::clientnum, DISC_IPBAN, DISC_MAXCLIENTS, DISC_NONE, DISC_PASSWORD, DISC_PRIVATE, getclientip(), loopv, mastermode, maxclients, MM_PRIVATE, numclients(), and server::clientinfo::sessionid.
Referenced by player_connected().
void server::assign_team (clientinfo * ci)
References chooseworstteam(), copystring(), m_teammode, MAXTEAMLEN, and server::clientinfo::team.
Referenced by player_connected().
void server::autoteam ()
References vector< T, MINSIZE >::add(), addteaminfo(), choosebestclient(), server::clientinfo::clientnum, clients, copystring(), server::servmode::hidefrags(), loopi(), loopvj, MAXTEAMLEN, N_SETTEAM, round, sendf(), smode, server::clientinfo::state, server::clientinfo::team, and server::gamestate::timeplayed.
Referenced by changemap().
bool server::buildworldstate ()
References vector< T, MINSIZE >::add(), addmessages(), addposition(), AI_NONE, fpsstate::aitype, server::clientinfo::bots, server::worldstate::cleanup(), clients, server::worldstate::data, vector< T, MINSIZE >::drop(), getservermtu(), server::worldstate::len, vector< T, MINSIZE >::length(), loopv, loopvj, server::clientinfo::messages, server::clientinfo::overflow, server::clientinfo::position, sendmessages(), sendpositions(), server::worldstate::setup(), server::clientinfo::state, server::worldstate::uses, and server::clientinfo::wsdata.
Referenced by sendpackets().
bool server::canspawnitem (int type)
References I_BOMBDELAY, I_BOMBS, I_CARTRIDGES, I_SHELLS, m_bomb, and m_noitems.
Referenced by loaditems(), and parsepacket().
void server::change_mastermode (int mm, int sendernum, clientinfo * actor)
References allowedips, clients, defformatstring, getclientip(), loopv, mastermask, mastermode, MM_OPEN, MM_PRIVATE, N_MASTERMODE, N_SERVMSG, PRIV_ADMIN, server::clientinfo::privilege, and sendf().
Referenced by parsepacket().
void server::changegamespeed (int val, clientinfo * ci = nullptr)
References gamespeed, N_GAMESPEED, and sendf().
Referenced by changemap(), checkintermission(), and parsepacket().
void server::changemap (const char * s, int mode)
References autoteam(), bombmode, server::servmode::canspawn(), capturemode, changegamespeed(), server::aiman::changemap(), server::servmode::cleanup(), server::aiman::clearai(), clearteaminfo(), server::clientinfo::clientnum, clients, collectmode, copystring(), CS_DEAD, CS_SPECTATOR, ctfmode, demonextmatch, gamelimit, gamemillis, gamemode, GUN_BOMB, hideandseekmode, interm, lastmillis, server::gamestate::lasttimeplayed, loaditems(), loopv, m_bomb, m_capture, m_collect, m_ctf, m_demo, m_hideandseek, m_overtime, m_teammode, m_timed, server::clientinfo::mapchange(), inexor::rpc::max(), N_FORCEDEATH, N_MAPCHANGE, N_TIMEUP, nextexceeded, pausegame(), resetdisconnectedplayerscores(), sendf(), sendspawn(), server::gamestate::setbackupweapon(), server::servmode::setup(), setupdemoplayback(), setupdemorecord(), shouldcheckteamkills, smapname, smode, server::gamestate::state, server::clientinfo::state, stopdemo(), teamkills, teamspersisted, and server::gamestate::timeplayed.
Referenced by checkvotes(), player_connected(), rotatemap(), and vote().
void server::check_bans_expired ()
References bannedips, and totalmillis.
Referenced by serverupdate().
void server::check_clients_timed_out ()
After some period of time without response we disconnect a client.
References connects, DISC_TIMEOUT, disconnect_client(), loopv, and totalmillis.
Referenced by serverupdate().
bool server::checkgban (uint ip)
References ai::check(), gbans, and loopv.
Referenced by addgban(), and allowconnect().
void server::checkintermission ()
References changegamespeed(), gamelimit, gamemillis, interm, server::servmode::intermission(), m_timeforward, N_TIMEUP, sendf(), and smode.
Referenced by serverupdate(), and startintermission().
void server::checklms ()
Checks if the game has ended because only one player is still alive.
If yes it forces intermission.
Note
It does this by checking if less than 2 players have their state set to alive. This means, the game will also end if someone is Lagging.
References vector< T, MINSIZE >::add(), clients, CS_ALIVE, vector< T, MINSIZE >::length(), m_teammode, startintermission(), recorder::state, and anonymous_namespace{utilTest.cpp}::t().
Referenced by dodamage(), and suicide().
void server::checkmaps (int req = -1)
References vector< T, MINSIZE >::add(), AI_NONE, fpsstate::aitype, server::clientinfo::clientmap, server::clientinfo::clientnum, clients, colorname(), server::crcinfo::compare(), server::crcinfo::crc, CS_ALIVE, CS_SPECTATOR, forcespectator(), formatstring(), lastmillis, server::gamestate::lasttimeplayed, server::servmode::leavegame(), vector< T, MINSIZE >::length(), loopv, loopvj, m_edit, server::clientinfo::mapcrc, server::crcinfo::matches, mcrc, inexor::rpc::min(), N_SERVMSG, N_SPECTATOR, server::clientinfo::privilege, server::aiman::removeai(), sendf(), smapname, smode, vector< T, MINSIZE >::sort(), server::gamestate::state, server::clientinfo::state, suicide(), server::gamestate::timeplayed, and server::clientinfo::warned.
Referenced by parsepacket(), and unspectate().
void server::checkpausegame ()
If no player with a high enough privilege level is on the server, resume the game.
(Otherwise servers could get locked after an admin disconnected).
References clients, gamepaused, loopv, pausegame(), PRIV_ADMIN, and PRIV_MASTER.
Referenced by disconnect_client(), and setmaster().
void server::checkpersistteams ()
void server::checkserversockets ()
Reply all server info requests.
References lansock, databuf< T >::len, loopi(), inexor::rpc::max(), MAXPINGDATA, MAXTRANS, pongaddr, pongsock, and serverinforeply().
Referenced by serverslice().
void server::checkteamkills ()
Referenced by serverupdate().
int server::checktype (int type, clientinfo * ci)
References server::clientinfo::connected, m_edit, N_CONNECT, N_PING, and server::clientinfo::overflow.
Referenced by parsepacket().
void server::checkvotes (bool force = false)
References vector< T, MINSIZE >::add(), AI_NONE, fpsstate::aitype, changemap(), clients, server::votecount::count, CS_SPECTATOR, demorecord, enddemorecord(), loopv, loopvj, m_valid, server::votecount::map, server::clientinfo::mapvote, server::votecount::mode, server::clientinfo::modevote, server::clientinfo::privilege, rnd(), rotatemap(), sendservmsg(), server::gamestate::state, server::clientinfo::state, and vc.
Referenced by serverupdate(), and vote().
clientinfo* server::choosebestclient (float & bestrank)
References clients, CS_SPECTATOR, server::gamestate::effectiveness, loopv, inexor::rpc::max(), server::gamestate::state, server::clientinfo::state, and server::gamestate::timeplayed.
Referenced by autoteam().
void server::choosemap (clientinfo * ci)
References hasmap(), and rotatemap().
Referenced by player_connected().
const char* server::chooseworstteam (const char * suggest = nullptr, clientinfo * exclude = nullptr)
References AI_NONE, fpsstate::aitype, clients, server::teamrank::clients, CS_SPECTATOR, server::gamestate::effectiveness, server::servmode::hidefrags(), lastmillis, server::gamestate::lasttimeplayed, loopi(), loopj, loopv, inexor::rpc::max(), server::teamrank::name, server::teamrank::rank, smode, server::gamestate::state, server::clientinfo::state, server::clientinfo::team, and server::gamestate::timeplayed.
Referenced by assign_team().
void server::cleanupserver ()
References lansock, pongsock, serverhost, and inexor::util::Metasystem::stop().
Referenced by cleanup_application().
void server::cleanworldstate (ENetPacket * packet)
References server::worldstate::cleanup(), server::worldstate::contains(), loopv, vector< T, MINSIZE >::removeunordered(), and server::worldstate::uses.
Referenced by sendmessages(), and sendpositions().
void server::clearbans (clientinfo * actor)
References bannedips, server::clientinfo::privilege, and sendservmsg().
Referenced by parsepacket().
void server::cleardemos (int n)
Remove all demos until demo number n or all if n = 0.
References demos, loopv, sendservmsg(), and sendservmsgf().
Referenced by parsepacket().
void server::clearevent (clientinfo * ci)
References server::clientinfo::events.
Referenced by flushevents().
void server::cleargbans ()
References gbans.
void server::clearteaminfo ()
References teaminfos.
Referenced by changemap().
void server::cleartimedevents (clientinfo * ci)
References server::clientinfo::events, loopv, and server::clientinfo::timesync.
Referenced by parsepacket().
int server::clientconnect (int n, uint ip)
References server::clientinfo::clientnum, server::clientinfo::connectmillis, connects, DISC_NONE, get_client_info(), server::clientinfo::ownernum, rnd(), sendservinfo(), server::clientinfo::sessionid, and totalmillis.
Referenced by serverslice().
void server::clientdisconnect (int n)
const char * server::colorname (clientinfo * ci, const char * name)
colorful version of the clients name (if two people share the same name or ci is a bot)
References AI_NONE, fpsstate::aitype, server::clientinfo::clientnum, COL_MAGENTA, COL_WHITE, duplicatename(), formatstring(), server::clientinfo::name, and server::clientinfo::state.
Referenced by checkmaps(), parsepacket(), receivefile(), setmaster(), trykick(), and vote().
server::COMMAND (maprotationreset , "")
server::COMMAND (teamkillkickreset , "")
server::COMMANDN (maprotation , addmaprotations , "ss2V")
server::COMMANDN (teamkillkick , addteamkillkick , "sii")
int server::connectwithtimeout (ENetSocket sock, const char * hostname, const ENetAddress & remoteaddress)
void server::delete_client_connection (client * c)
References client_count, server::client::connected, server::client::info, and server::client::peer.
Referenced by disconnect_client().
void server::disconnect_client (int n, int reason)
References checkpausegame(), client_connections, clients, server::clientinfo::connected, connects, delete_client_connection(), disconnectreason(), formatstring(), get_client_info(), lastmillis, server::gamestate::lasttimeplayed, server::servmode::leavegame(), Log, N_CDIS, noclients(), numclients(), server::clientinfo::privilege, server::aiman::removeai(), savescore(), sendf(), sendservmsg(), setmaster(), smode, server::clientinfo::state, inexor::util::log_manager::std, and server::gamestate::timeplayed.
Referenced by addgban(), check_clients_timed_out(), kickclients(), server::bombservermode::parse_network_message(), parsepacket(), process(), serverslice(), and serverupdate().
void server::dodamage (clientinfo * target, clientinfo * actor, int damage, int gun, const vec & hitpush = vec(0, 0, 0))
References addteamkill(), fpsstate::armour, server::servmode::canhit(), checklms(), server::clientinfo::clientnum, clients, CS_DEAD, server::gamestate::damage, server::gamestate::deadflush, DEATHMILLIS, server::gamestate::deaths, server::servmode::died(), DNF, fpsstate::dodamage(), server::gamestate::effectiveness, teaminfo::frags, server::gamestate::frags, server::servmode::fragvalue(), gamemillis, fpsstate::health, game::hitpush(), isteam, server::gamestate::lastdeath, loopv, m_lms, m_teammode, inexor::rpc::max(), N_DAMAGE, N_DIED, N_HITPUSH, server::clientinfo::ownernum, server::clientinfo::position, server::gamestate::respawn(), sendf(), server::clientinfo::setpushed(), vector< T, MINSIZE >::setsize(), smode, server::gamestate::state, server::clientinfo::state, anonymous_namespace{utilTest.cpp}::t(), server::clientinfo::team, teaminfos, and server::gamestate::teamkills.
Referenced by server::shotevent::process(), and server::explodeevent::process().
bool server::duplicatename (clientinfo * ci, const char * name)
References clients, loopv, and server::clientinfo::name.
Referenced by colorname().
void server::enddemoplayback ()
References clients, DELETEP, demoplayback, gamemode, loopv, N_DEMOPLAYBACK, sendf(), sendservmsg(), and sendwelcome().
Referenced by player_connected(), readdemo(), setupdemoplayback(), and stopdemo().
void server::enddemorecord ()
References adddemo(), DELETEP, demorecord, demotmp, maxdemos, maxdemosize, and prunedemos().
Referenced by checkvotes(), serverupdate(), stopdemo(), vote(), and writedemo().
void server::extinfoplayer (ucharbuf & p, clientinfo * ci)
References fpsstate::armour, server::clientinfo::clientnum, server::gamestate::damage, server::gamestate::deaths, EXT_PLAYERSTATS_RESP_STATS, server::gamestate::flags, server::gamestate::frags, getclientip(), fpsstate::gunselect, fpsstate::health, inexor::rpc::max(), server::clientinfo::name, server::clientinfo::ping, server::clientinfo::privilege, databuf< T >::put(), putint(), sendserverinforeply(), sendstring(), server::gamestate::shotdamage, server::gamestate::state, server::clientinfo::state, server::clientinfo::team, and server::gamestate::teamkills.
Referenced by extserverinforeply().
void server::extinfoteams (ucharbuf & p)
References vector< T, MINSIZE >::add(), clients, CS_SPECTATOR, extinfoteamscore(), teaminfo::frags, gamelimit, gamemillis, gamemode, server::servmode::getteamscores(), server::servmode::hidefrags(), vector< T, MINSIZE >::htfind(), loopv, m_teammode, inexor::rpc::max(), putint(), scores, smode, server::gamestate::state, server::clientinfo::state, server::clientinfo::team, and teaminfos.
Referenced by extserverinforeply().
static void server::extinfoteamscore (ucharbuf & p, const char * team, int score) inline static
References server::servmode::extinfoteam(), putint(), sendstring(), and smode.
Referenced by extinfoteams().
void server::extserverinforeply (ucharbuf & req, ucharbuf & p)
References server::clientinfo::clientnum, clients, EXT_ACK, EXT_ERROR, EXT_NO_ERROR, EXT_PLAYERSTATS, EXT_PLAYERSTATS_RESP_IDS, EXT_TEAMSCORE, EXT_UPTIME, EXT_VERSION, extinfoplayer(), extinfoteams(), getint(), loopv, putint(), sendserverinforeply(), and totalsecs.
Referenced by serverinforeply().
int server::findmaprotation (int mode, const char * map)
References curmaprotation, loopv, maprotations, server::maprotation::match(), inexor::rpc::max(), server::maprotation::modes, and recorder::start().
Referenced by rotatemap(), and vote().
savedscore* server::findscore (clientinfo * ci, bool insert)
References server::clientinfo::clientnum, clients, copystring(), getclientip(), server::savedscore::ip, lastmillis, server::gamestate::lasttimeplayed, loopv, server::clientinfo::name, server::savedscore::name, server::savedscore::save(), scores, server::clientinfo::state, and server::gamestate::timeplayed.
Referenced by restorescore(), savescore(), and game::captureclientmode::setscore().
void server::flushclientposition (clientinfo & ci)
References demorecord, vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::getbuf(), has_clients(), vector< T, MINSIZE >::length(), server::clientinfo::ownernum, server::clientinfo::position, packetbuf::put(), sendpacket(), and vector< T, MINSIZE >::setsize().
Referenced by parsepacket().
void server::flushevents (clientinfo * ci, int millis)
References clearevent(), server::clientinfo::events, and server::gameevent::flush().
Referenced by parsepacket(), and processevents().
void server::flushserver (bool force)
References sendpackets(), and serverhost.
Referenced by server::aiman::balanceteams(), and sendclipboard().
void server::forcespectator (clientinfo * ci)
References server::clientinfo::clientnum, CS_ALIVE, CS_SPECTATOR, lastmillis, server::gamestate::lasttimeplayed, server::servmode::leavegame(), N_SPECTATOR, server::clientinfo::privilege, server::aiman::removeai(), sendf(), smode, server::gamestate::state, server::clientinfo::state, suicide(), server::gamestate::timeplayed, and server::clientinfo::warned.
Referenced by checkmaps(), and parsepacket().
static void server::freegetdemo (ENetPacket * packet) static
References clients, server::clientinfo::getdemo, and loopv.
Referenced by senddemo().
static void server::freegetmap (ENetPacket * packet) static
References clients, server::clientinfo::getmap, and loopv.
Referenced by parsepacket().
clientinfo * server::get_client_info (int n, bool findbots)
References bots, client_connections, and MAXCLIENTS.
Referenced by allowbroadcast(), clientconnect(), aiman::deleteai(), disconnect_client(), parsepacket(), pickup(), server::shotevent::process(), server::explodeevent::process(), receivefile(), aiman::shiftai(), trykick(), server::ctfservermode::update(), server::bombservermode::updatelimbo(), and vote().
int server::get_mastermode_int ()
References mastermask, mastermode, MM_AUTOAPPROVE, MM_PASSWORD, and MM_START.
Referenced by serverinforeply().
int server::get_num_clients ()
References client_count.
Referenced by player_connected(), and serverslice().
uint server::getclientip (int n)
References client_connections.
Referenced by addgban(), addteamkill(), allowconnect(), change_mastermode(), extinfoplayer(), findscore(), kickclients(), and trykick().
ENetPeer * server::getclientpeer (int i)
References client_connections.
Referenced by server::clientinfo::calcpushrange().
int server::getservermtu ()
References serverhost.
Referenced by server::aiman::balanceteams(), and buildworldstate().
bool server::has_clients ()
References client_count.
Referenced by flushclientposition(), sendpackets(), serverslice(), and vote().
bool server::hasmap (clientinfo * ci)
References server::clientinfo::clientnum, clients, CS_SPECTATOR, gamelimit, gamemillis, m_edit, m_timed, numclients(), server::clientinfo::privilege, smapname, server::gamestate::state, and server::clientinfo::state.
Referenced by choosemap(), and unspectate().
server::ICOMMAND (mapmode , "si" , (char *name, int *mode) , changemap(name,*mode))
bool server::ispaused ()
References gamepaused.
Referenced by serverslice().
void server::kickclients (uint ip, clientinfo * actor, int priv)
Kick all clients with this IP (including bots and people in the same LAN)
References AI_NONE, fpsstate::aitype, server::clientinfo::clientnum, clients, DISC_KICK, disconnect_client(), getclientip(), loopvrev, PRIV_ADMIN, server::clientinfo::privilege, and server::clientinfo::state.
Referenced by server::aiman::checkai(), and trykick().
void server::listdemos (int cn)
Send a list of demos to that client.
References demos, packetbuf::finalize(), loopv, MAXTRANS, N_SENDDEMOLIST, putint(), sendpacket(), and sendstring().
Referenced by parsepacket().
void server::loaditems ()
References canspawnitem(), entities::delayspawn(), loadents(), loopv, m_edit, mcrc, ments, notgotitems, NOTUSED, resetitems(), sents, smapname, and spawntime().
Referenced by changemap().
void server::maprotationreset ()
References curmaprotation, server::maprotation::exclude, and maprotations.
static struct server::msgfilter server::msgfilter (- 1, N_CONNECT , N_SERVINFO , N_INITCLIENT , N_WELCOME , N_MAPCHANGE , N_SERVMSG , N_DAMAGE , N_HITPUSH , N_SHOTFX , N_EXPLODEFX , N_DIED , N_SPAWNSTATE , N_FORCEDEATH , N_TEAMINFO , N_ITEMACC , N_ITEMSPAWN , N_TIMEUP , N_CDIS , N_CURRENTMASTER , N_PONG , N_RESUME , N_BASESCORE , N_BASEINFO , N_BASEREGEN , N_ANNOUNCE , N_SENDDEMOLIST , N_SENDDEMO , N_DEMOPLAYBACK , N_SENDMAP , N_DROPFLAG , N_SCOREFLAG , N_RETURNFLAG , N_RESETFLAG , N_INVISFLAG , N_CLIENT , N_INITAI , N_EXPIRETOKENS , N_DROPTOKENS , N_STEALTOKENS , N_DEMOPACKET , - 2, N_REMIP , N_NEWMAP , N_GETMAP , N_SENDMAP , N_CLIPBOARD , - 3, N_EDITENT , N_EDITF , N_EDITT , N_EDITM , N_FLIP , N_COPY , N_PASTE , N_ROTATE , N_REPLACE , N_DELCUBE , N_EDITVAR , N_EDITVSLOT , N_UNDO , N_REDO , - 4, N_POS , NUMMSG) static
void server::nextmaprotation ()
References curmaprotation.
Referenced by rotatemap().
void server::noclients ()
References bannedips, and server::aiman::clearai().
Referenced by disconnect_client().
int server::numclients (int exclude = -1, bool nospec = true, bool noai = true, bool priv = false)
List all connected clients (game players)
Parameters
exclude exclude the player with this client number from the counter.
nospec exclude spectators (expect they have priviledge leveles and parameter priv is true)
priv see nospec: count priviledges users (master, admin, local) even when they are in spectator mode.
noai exclude bots from the counter.
References AI_NONE, fpsstate::aitype, server::clientinfo::clientnum, clients, CS_SPECTATOR, loopv, server::clientinfo::privilege, server::gamestate::state, and server::clientinfo::state.
Referenced by allowconnect(), aiman::checkai(), disconnect_client(), hasmap(), game::listclients(), serverinforeply(), and setmaster().
void server::parsepacket (int sender, int chan, packetbuf & p)
References vector< T, MINSIZE >::add(), server::clientinfo::addevent(), addteaminfo(), AI_NONE, fpsstate::aitype, server::gamestate::bombs, server::clientinfo::bots, databuf< T >::buf, server::servmode::canchangeteam(), server::servmode::canspawn(), canspawnitem(), CHAN_FILE, change_mastermode(), changegamespeed(), server::aiman::changeteam(), checkmaps(), checktype(), server::clientinfo::cleanclipboard(), clearbans(), cleardemos(), cleartimedevents(), server::clientinfo::clientmap, server::clientinfo::clientnum, clients, server::clientinfo::clipboard, colorname(), server::clientinfo::connected, copystring(), CS_ALIVE, CS_DEAD, CS_EDITING, CS_SPECTATOR, server::gamestate::deadflush, server::gamestate::deaths, defformatstring, entities::delayspawn(), demonextmatch, server::hitinfo::dir, dir, DISC_MSGERR, DISC_OVERFLOW, disconnect_client(), server::hitinfo::dist, DMF, DNF, DVELF, server::gamestate::editstate, server::pickupevent::ent, server::servmode::entergame(), server::clientinfo::events, server::clientinfo::exceeded, filtertext(), packetbuf::finalize(), hmap::flags, flushclientposition(), flushevents(), forcespectator(), server::clientinfo::fov, freegetmap(), server::shotevent::from, server::clientinfo::gameclip, gamemillis, databuf< T >::get(), get_client_info(), server::clientinfo::geteventmillis(), getfloat(), getint(), server::clientinfo::getmap, getstring(), getuint(), server::gamestate::grenades, server::shotevent::gun, server::explodeevent::gun, GUN_BOMB, GUN_FIST, GUN_PISTOL, fpsstate::gunselect, game::gunselect(), game::hit(), game::hits, server::shotevent::hits, server::explodeevent::hits, server::shotevent::id, server::explodeevent::id, ID_FVAR, ID_SVAR, ID_VAR, server::clientinfo::lastclipboard, server::gamestate::lastspawn, server::servmode::leavegame(), databuf< T >::length(), server::gamestate::lifesequence, server::hitinfo::lifesequence, lilswap(), listdemos(), Log, loopi(), loopk, loopv, m_demo, m_edit, m_lms, m_teammode, vec::magnitude2(), server::clientinfo::mapcrc, mapdata, mastermode, inexor::rpc::max(), maxdemos, maxdemosize, MAXENTS, databuf< T >::maxlen, MAXNAMELEN, MAXTAGLEN, MAXTEAMLEN, MAXTRANS, server::clientinfo::messages, server::timedevent::millis, MM_LOCKED, server::servmode::moved(), msgsizelookup(), vec::mul(), N_ADDBOT, N_BOTBALANCE, N_BOTLIMIT, N_CHECKMAPS, N_CLEARBANS, N_CLEARDEMOS, N_CLIENTPING, N_CLIPBOARD, N_CONNECT, N_COPY, N_DELBOT, N_EDITENT, N_EDITMODE, N_EDITT, N_EDITVAR, N_EDITVSLOT, N_EXPLODE, N_FORCEINTERMISSION, N_FOV, N_FROMAI, N_GAMESPEED, N_GETDEMO, N_GETMAP, N_GUNSELECT, N_ITEMLIST, N_ITEMPICKUP, N_JUMPPAD, N_KICK, N_LISTDEMOS, N_MAPCRC, N_MAPVOTE, N_MASTERMODE, N_NEWMAP, N_PASTE, N_PAUSEGAME, N_PERSISTTEAMS, N_PING, N_PONG, N_POS, N_PRIVMSG, N_RECORDDEMO, N_REDO, N_REPLACE, N_SAYTEAM, N_SENDMAP, N_SERVCMD, N_SERVMSG, N_SETMASTER, N_SETTEAM, N_SHOOT, N_SPAWN, N_SPECTATOR, N_STOPDEMO, N_SUICIDE, N_SWITCHMODEL, N_SWITCHNAME, N_SWITCHTEAM, N_TELEPORT, N_TEXT, N_TRYSPAWN, N_UNDO, server::clientinfo::name, server::clientinfo::needclipboard, server::servmode::newmap(), notgotitems, NOTUSED, server::gamestate::o, databuf< T >::overread(), server::clientinfo::ownernum, packetbuf::packet, databuf< T >::pad(), server::servmode::parse_network_message(), pausegame(), persistteams(), pickup(), server::clientinfo::ping, player_connected(), server::clientinfo::playermodel, server::clientinfo::position, PRIV_ADMIN, PRIV_MASTER, server::clientinfo::privilege, putint(), QUEUE_AI, QUEUE_BUF, QUEUE_MSG, QUEUE_STR, RAD, server::hitinfo::rays, receivefile(), databuf< T >::remaining(), server::aiman::reqadd(), server::aiman::reqdel(), server::projectilestate< N >::reset(), resetitems(), server::gamestate::respawn(), server::gamestate::rockets, sendclipboard(), senddemo(), sendf(), sendfile(), sendpacket(), sendservmsgf(), sendspawn(), sendstate(), sents, server::aiman::setbotbalance(), server::aiman::setbotlimit(), server::clientinfo::setexceeded(), setmaster(), server::clientinfo::setpushed(), vector< T, MINSIZE >::setsize(), shouldstep, smapname, smode, server::servmode::spawned(), ai::spawned(), spawntime(), startintermission(), server::gamestate::state, server::clientinfo::state, inexor::util::log_manager::std, stopdemo(), packetbuf::subbuf(), suicide(), anonymous_namespace{utilTest.cpp}::t(), server::clientinfo::tag, server::hitinfo::target, server::clientinfo::team, entities::teleport(), server::shotevent::to, totalmillis, trykick(), unspectate(), and vote().
Referenced by process().
void server::pausegame (bool val, clientinfo * ci)
References server::clientinfo::clientnum, gamepaused, N_PAUSEGAME, and sendf().
Referenced by changemap(), checkpausegame(), parsepacket(), server::bombservermode::setup(), and server::bombservermode::updatelimbo().
void server::persistteams (bool val)
References N_PERSISTTEAMS, sendf(), and teamspersisted.
Referenced by parsepacket().
bool server::pickup (int i, int sender)
References fpsstate::canpickup(), gamelimit, gamemillis, get_client_info(), m_timed, N_ITEMACC, fpsstate::pickup(), sendf(), sents, spawntime(), and server::clientinfo::state.
Referenced by parsepacket(), and server::pickupevent::process().
bool server::player_connected (clientinfo * ci, const char * password, const char * mapwish, int modewish)
References server::aiman::addclient(), allowconnect(), assign_team(), changemap(), choosemap(), server::clientinfo::clientnum, clients, server::clientinfo::connected, connects, CS_SPECTATOR, DISC_NONE, enddemoplayback(), get_num_clients(), lastmillis, server::gamestate::lasttimeplayed, m_demo, mastermode, MM_LOCKED, N_SERVMSG, server::clientinfo::needclipboard, PRIV_LOCAL, server::clientinfo::privilege, restorescore(), sendf(), sendinitclient(), sendresume(), sendwelcome(), servermotd, setupdemoplayback(), server::gamestate::state, server::clientinfo::state, and totalmillis.
Referenced by parsepacket().
void server::process (ENetPacket * packet, int sender, int chan)
References DISC_EOP, disconnect_client(), databuf< T >::overread(), and parsepacket().
Referenced by serverslice().
void server::processevents ()
References clients, curtime, flushevents(), gamemillis, loopv, inexor::rpc::max(), fpsstate::quadmillis, and server::clientinfo::state.
Referenced by serverupdate().
void server::promote_if_local_client (client * c)
If client ci is from the same ip as this server -> make him priv_local.
References server::clientinfo::clientnum, server::client::info, IsLocalConnection(), Log, server::client::peer, PRIV_LOCAL, and server::clientinfo::privilege.
Referenced by add_client_connection().
void server::prunedemos (int extra = 0)
References demos, loopi(), and maxdemos.
Referenced by enddemorecord().
bool server::pruneteaminfo ()
References enumerate, teamhasplayers(), and teaminfos.
Referenced by addteaminfo().
void server::putinitclient (clientinfo * ci, packetbuf & p)
References AI_NONE, fpsstate::aitype, BOTTAG, server::clientinfo::clientnum, server::clientinfo::fov, N_INITAI, N_INITCLIENT, server::clientinfo::name, server::clientinfo::ownernum, server::clientinfo::playermodel, putint(), sendstring(), fpsstate::skill, server::clientinfo::state, server::clientinfo::tag, and server::clientinfo::team.
Referenced by sendinitclient(), and welcomeinitclient().
void server::readdemo ()
References curtime, demomillis, demoplayback, enddemoplayback(), lilswap(), N_DEMOPACKET, nextplayback, stream::read(), and sendpacket().
Referenced by serverupdate().
void server::receivefile (int sender, uchar * data, int len)
References colorname(), CS_SPECTATOR, DELETEP, get_client_info(), m_edit, mapdata, N_SERVMSG, opentempfile(), server::clientinfo::privilege, sendf(), sendservmsgf(), server::gamestate::state, server::clientinfo::state, and stream::write().
Referenced by parsepacket().
void server::recordpacket (int chan, void * data, int len)
References writedemo().
Referenced by sendmessages(), sendpacket(), and sendpositions().
int server::reserveclients ()
The amount of people who can connect more than the actual specified max clients limit.
E.g. for people connecting as admin or with the password.
Referenced by setup_network_sockets().
void server::resetdisconnectedplayerscores ()
New map: we throw away the scores of disconnected players.
References scores.
Referenced by changemap().
void server::resetitems ()
References mcrc, ments, and sents.
Referenced by loaditems(), and parsepacket().
bool server::resolverwait (const char * name, ENetAddress * address)
Referenced by connectserv().
bool server::restorescore (clientinfo * ci)
References findscore(), server::savedscore::restore(), and server::clientinfo::state.
Referenced by player_connected().
void server::revokemaster (clientinfo * ci)
References CS_SPECTATOR, PRIV_NONE, server::clientinfo::privilege, server::aiman::removeai(), server::gamestate::state, and server::clientinfo::state.
void server::rotatemap (bool next)
References changemap(), curmaprotation, findmaprotation(), server::maprotation::findmode(), gamemode, server::maprotation::map, maprotations, inexor::rpc::max(), nextmaprotation(), and smapname.
Referenced by checkvotes(), choosemap(), and unspectate().
void server::run_server ()
References Log, NULL, serverslice(), and inexor::util::log_manager::std.
Referenced by main().
void server::savescore (clientinfo * ci)
References findscore(), server::savedscore::save(), and server::clientinfo::state.
Referenced by disconnect_client().
void server::sendclipboard (clientinfo * ci)
References server::clientinfo::clientnum, clients, server::clientinfo::clipboard, flushserver(), server::clientinfo::lastclipboard, loopv, server::clientinfo::needclipboard, and sendpacket().
Referenced by parsepacket().
void server::senddemo (clientinfo * ci, int num)
Send a specific demo to the client.
If client ci is not receiving one yet and num is valid.
Parameters
ci info of connected clients on server side
num if 0 send the latest demo.
References server::clientinfo::clientnum, hmap::d, server::demofile::data, demos, freegetdemo(), server::clientinfo::getdemo, server::demofile::len, N_SENDDEMO, and sendf().
Referenced by parsepacket().
void server::sendinitclient (clientinfo * ci)
References server::clientinfo::clientnum, packetbuf::finalize(), MAXTRANS, putinitclient(), and sendpacket().
Referenced by player_connected().
static void server::sendmessages (worldstate & ws, ucharbuf & wsbuf) static
References AI_NONE, fpsstate::aitype, databuf< T >::buf, cleanworldstate(), server::clientinfo::clientnum, clients, databuf< T >::empty(), databuf< T >::length(), loopv, databuf< T >::offset(), databuf< T >::put(), recordpacket(), sendpacket(), server::clientinfo::state, server::worldstate::uses, server::clientinfo::wsdata, and server::clientinfo::wslen.
Referenced by addmessages(), and buildworldstate().
bool server::sendpackets (bool force)
References buildworldstate(), clients, curtime, demorecord, has_clients(), and lastsend.
Referenced by flushserver(), and serverslice().
static void server::sendpositions (worldstate & ws, ucharbuf & wsbuf) static
References AI_NONE, fpsstate::aitype, databuf< T >::buf, cleanworldstate(), server::clientinfo::clientnum, clients, databuf< T >::empty(), databuf< T >::length(), loopv, databuf< T >::offset(), databuf< T >::put(), recordpacket(), sendpacket(), server::clientinfo::state, server::worldstate::uses, server::clientinfo::wsdata, and server::clientinfo::wslen.
Referenced by addposition(), and buildworldstate().
void server::sendresume (clientinfo * ci)
References fpsstate::ammo, fpsstate::armour, fpsstate::armourtype, server::clientinfo::clientnum, server::gamestate::damage, server::gamestate::deaths, server::gamestate::flags, server::gamestate::frags, GUN_PISTOL, GUN_SG, fpsstate::gunselect, fpsstate::health, server::gamestate::lifesequence, fpsstate::maxhealth, N_RESUME, fpsstate::quadmillis, sendf(), server::gamestate::shotdamage, server::gamestate::state, server::clientinfo::state, and server::gamestate::teamkills.
Referenced by player_connected().
void server::sendserverinforeply (ucharbuf & p)
References databuf< T >::buf, databuf< T >::length(), pongaddr, and pongsock.
Referenced by extinfoplayer(), extserverinforeply(), and serverinforeply().
void server::sendservinfo (clientinfo * ci)
References server::clientinfo::clientnum, N_SERVINFO, PROTOCOL_VERSION, sendf(), serverdesc, and server::clientinfo::sessionid.
Referenced by clientconnect().
void server::sendspawn (clientinfo * ci)
References fpsstate::ammo, fpsstate::armour, fpsstate::armourtype, server::clientinfo::clientnum, gamemillis, GUN_PISTOL, GUN_SG, fpsstate::gunselect, fpsstate::health, server::gamestate::lastspawn, server::gamestate::lifesequence, fpsstate::maxhealth, N_SPAWNSTATE, server::clientinfo::ownernum, sendf(), spawnstate(), and server::clientinfo::state.
Referenced by changemap(), parsepacket(), aiman::reinitai(), and server::bombservermode::sendspawnlocs().
template<class T > void server::sendstate (gamestate & gs, T & p)
References fpsstate::ammo, fpsstate::armour, fpsstate::armourtype, GUN_PISTOL, GUN_SG, fpsstate::gunselect, fpsstate::health, server::gamestate::lifesequence, loopi(), fpsstate::maxhealth, and putint().
Referenced by parsepacket().
void server::sendwelcome (clientinfo * ci)
References server::clientinfo::clientnum, packetbuf::finalize(), MAXTRANS, sendpacket(), and welcomepacket().
Referenced by enddemoplayback(), and player_connected().
bool server::servercompatible (char * name, char * sdec, char * map, int ping, const vector< int > & attr, int np)
References vector< T, MINSIZE >::length(), and PROTOCOL_VERSION.
bool server::servererror (const char * desc)
References fatal().
Referenced by setup_network_sockets().
void server::serverinforeply (ucharbuf & req, ucharbuf & p)
References extserverinforeply(), gamelimit, gamemillis, gamemode, gamepaused, gamespeed, get_mastermode_int(), getint(), m_timed, inexor::rpc::max(), maxclients, numclients(), PROTOCOL_VERSION, putint(), databuf< T >::remaining(), sendserverinforeply(), sendstring(), serverdesc, and smapname.
Referenced by checkserversockets().
void server::serverinit ()
References smapname.
Referenced by main().
void server::serverslice (uint timeout)
main server update
References add_client_connection(), checkserversockets(), clientconnect(), copystring(), DISC_NONE, disconnect_client(), gamespeed, get_num_clients(), has_clients(), server::client::hostname, ispaused(), laststatus, Log, server::client::num, server::client::peer, process(), sendpackets(), serverhost, serverupdate(), inexor::util::log_manager::std, inexor::util::Metasystem::tick(), totalmillis, and updatetime().
Referenced by run_server().
void server::serverupdate ()
References AI_NONE, fpsstate::aitype, check_bans_expired(), check_clients_timed_out(), server::aiman::checkai(), server::clientinfo::checkexceeded(), checkintermission(), checkteamkills(), checkvotes(), server::clientinfo::clientnum, clients, curtime, demorecord, DISC_MSGERR, disconnect_client(), enddemorecord(), gamelimit, gamemillis, gamepaused, I_BOOST, I_QUAD, interm, loopv, loopvrev, m_demo, m_timed, N_ANNOUNCE, N_ITEMSPAWN, nextexceeded, processevents(), readdemo(), server::clientinfo::scheduleexceeded(), sendf(), sents, shouldcheckteamkills, shouldstep, smapname, smode, spawntime(), server::clientinfo::state, server::servmode::update(), and server::servmode::updatelimbo().
Referenced by serverslice().
bool server::setmaster (clientinfo * ci, bool val, const char * pass, bool force, bool trial)
References allowedips, checkpassword(), checkpausegame(), server::clientinfo::clientnum, clients, colorname(), CS_SPECTATOR, defformatstring, packetbuf::finalize(), loopv, mastermask, mastermode, MAXTRANS, MM_AUTOAPPROVE, MM_OPEN, N_CURRENTMASTER, N_SERVMSG, numclients(), PRIV_ADMIN, PRIV_MASTER, server::clientinfo::privilege, privname(), putint(), sendf(), sendpacket(), sendstring(), server::clientinfo::sessionid, server::gamestate::state, and server::clientinfo::state.
Referenced by disconnect_client(), and parsepacket().
bool server::setup_network_sockets ()
References lan_info_port(), lansock, Log, MAXCLIENTS, maxclients, maxdupclients, inexor::rpc::min(), NUM_ENET_CHANNELS, pongsock, reserveclients(), server_info_port(), server_port(), serveraddress, servererror(), serverhost, and inexor::util::log_manager::std.
Referenced by main().
void server::setupdemoplayback ()
References defformatstring, DELETEP, DEMO_MAGIC, DEMO_VERSION, demomillis, demoplayback, enddemoplayback(), recorder::file, formatstring(), lilswap(), demoheader::magic, N_DEMOPLAYBACK, nextplayback, opengzfile(), demoheader::protocol, PROTOCOL_VERSION, stream::read(), sendf(), sendservmsg(), sendservmsgf(), smapname, and demoheader::version.
Referenced by changemap(), and player_connected().
void server::setupdemorecord ()
References databuf< T >::buf, DELETEP, DEMO_MAGIC, DEMO_VERSION, demorecord, demotmp, f(), databuf< T >::len, lilswap(), m_edit, demoheader::magic, MAXTRANS, opengzfile(), opentempfile(), demoheader::protocol, PROTOCOL_VERSION, sendservmsg(), demoheader::version, welcomepacket(), stream::write(), and writedemo().
Referenced by changemap().
bool server::shouldspectate (clientinfo * ci)
References mcrc, and server::clientinfo::warned.
Referenced by unspectate().
void server::spawnstate (clientinfo * ci)
References gamemode, server::gamestate::lifesequence, fpsstate::spawnstate(), and server::clientinfo::state.
Referenced by sendspawn().
int server::spawntime (int type)
Referenced by loaditems(), parsepacket(), pickup(), and serverupdate().
void server::startintermission ()
References checkintermission(), gamelimit, gamemillis, and inexor::rpc::min().
Referenced by checklms(), server::collectservermode::deposittokens(), server::captureservermode::endcheck(), parsepacket(), server::ctfservermode::scoreflag(), and server::hideandseekservermode::update().
void server::stopdemo ()
Wrapper for either enddemoplayback or enddemorecord, depending on m_demo.
References enddemoplayback(), enddemorecord(), and m_demo.
Referenced by changemap(), and parsepacket().
void server::suicide (clientinfo * ci)
References checklms(), server::clientinfo::clientnum, CS_ALIVE, CS_DEAD, CS_EDITING, CS_SPECTATOR, server::gamestate::deaths, server::servmode::died(), teaminfo::frags, server::gamestate::frags, server::servmode::fragvalue(), gamemillis, server::gamestate::lastdeath, m_lms, m_teammode, N_DIED, server::clientinfo::position, server::gamestate::respawn(), sendf(), vector< T, MINSIZE >::setsize(), smode, server::gamestate::state, server::clientinfo::state, anonymous_namespace{utilTest.cpp}::t(), server::clientinfo::team, and teaminfos.
Referenced by checkmaps(), forcespectator(), parsepacket(), and server::suicideevent::process().
server::SVAR (serverpass , "")
server::SVAR (adminpass , "")
server::SVAR (serverip , "")
server::SVAR (serverdesc , "")
server::SVAR (servermotd , "")
bool server::teamhasplayers (const char * team)
References clients, and loopv.
Referenced by pruneteaminfo().
void server::teamkillkickreset ()
References teamkillkicks.
bool server::trykick (clientinfo * ci, int victim, const char * reason, bool trial)
References addban(), server::clientinfo::clientnum, colorname(), server::clientinfo::connected, copystring(), get_client_info(), getclientip(), kickclients(), PRIV_ADMIN, server::clientinfo::privilege, and sendservmsgf().
Referenced by parsepacket().
void server::unspectate (clientinfo * ci)
References server::aiman::addclient(), checkmaps(), server::clientinfo::clientmap, server::clientinfo::clientnum, CS_DEAD, hasmap(), lastmillis, server::gamestate::lasttimeplayed, server::clientinfo::mapcrc, N_SPECTATOR, server::gamestate::respawn(), rotatemap(), sendf(), shouldspectate(), server::gamestate::state, and server::clientinfo::state.
Referenced by parsepacket().
server::VAR (ctftkpenalty , 0 , 1 , 1)
server::VAR (maxdemos , 0 , 5 , 25)
server::VAR (maxdemosize , 0 , 16 , 31)
server::VAR (extinfoip , 0 , 0 , 1)
server::VAR (lockmaprotation , 0 , 0 , 2)
server::VAR (serveruprate , 0 , 0 , INT_MAX)
server::VAR (restrictdemos , 0 , 1 , 1)
server::VAR (restrictpausegame , 0 , 0 , 1)
server::VAR (restrictgamespeed , 0 , 1 , 1)
server::VAR (restrictpersistteams , 0 , 0 , 1)
server::VAR (spectatemodifiedmap , 0 , 1 , 1)
server::VAR (modifiedmapspectator , 0 , 1 , 2)
server::VARF (maxclients , 0 , DEFAULTCLIENTS , MAXCLIENTS , {if(!maxclients) maxclients=DEFAULTCLIENTS;})
server::VARF (maxdupclients , 0 , 0 , MAXCLIENTS , {if(serverhost) serverhost->duplicatePeers=maxdupclients?maxdupclients:MAXCLIENTS;})
Max clients from same peer.
server::VARF (publicserver , 0 , 0 , 2 , {switch(*publicserver){case 0:default:mastermask=MM_PRIVSERV;break;case 1:mastermask=MM_PUBSERV;break;case 2:mastermask=MM_COOPSERV;break;}})
server::VARF (serverport , 0 , INEXOR_SERVER_PORT , MAX_POSSIBLE_PORT , {if(!serverport) serverport=server_port();})
void server::vote (const char * map, int reqmode, int sender)
References changemap(), checkvotes(), colorname(), copystring(), CS_SPECTATOR, demorecord, enddemorecord(), findmaprotation(), get_client_info(), has_clients(), m_check, M_EDIT, m_valid, maprotations, server::clientinfo::mapvote, mastermode, MM_VETO, modename(), server::clientinfo::modevote, N_SERVMSG, PRIV_ADMIN, PRIV_MASTER, server::clientinfo::privilege, sendf(), sendservmsgf(), smapname, server::gamestate::state, and server::clientinfo::state.
Referenced by parsepacket().
void server::welcomeinitclient (packetbuf & p, int exclude = -1)
References server::clientinfo::clientnum, clients, server::clientinfo::connected, loopv, and putinitclient().
int server::welcomepacket (packetbuf & p, clientinfo * ci)
References clients, enumerate, gamelimit, gamemillis, gamemode, gamepaused, gamespeed, interm, loopv, m_teammode, m_timed, mastermode, inexor::rpc::max(), MM_OPEN, N_CURRENTMASTER, N_GAMESPEED, N_ITEMLIST, N_MAPCHANGE, N_PAUSEGAME, N_TEAMINFO, N_TIMEUP, N_WELCOME, notgotitems, PRIV_MASTER, putint(), sendstring(), sents, smapname, ai::spawned(), anonymous_namespace{utilTest.cpp}::t(), and teaminfos.
Referenced by sendwelcome(), and setupdemorecord().
void server::writedemo (int chan, void * data, int len)
References demorecord, enddemorecord(), gamemillis, lilswap(), maxdemosize, stream::rawtell(), and stream::write().
Referenced by recordpacket(), and setupdemorecord().
Variable Documentation
vector<uint> server::allowedips
allowed IPs: mastermode locked allows some players to be unspectated immediately?
Referenced by addban(), allowconnect(), change_mastermode(), and setmaster().
vector<ban> server::bannedips
Referenced by addban(), allowconnect(), check_bans_expired(), clearbans(), and noclients().
bombservermode server::bombmode
Referenced by changemap(), and game::setclientmode().
vector< clientinfo * > server::bots
Referenced by aiman::addai(), aiman::balanceteams(), aiman::checksetup(), aiman::clearai(), aiman::deleteai(), and get_client_info().
captureservermode server::capturemode
Referenced by changemap(), and game::setclientmode().
vector< client * > server::client_connections
TODO merge with clients or connects.
Referenced by add_client_connection(), disconnect_client(), get_client_info(), getclientip(), getclientpeer(), sendfile(), and sendpacket().
int server::client_count = 0
Idk why client_connections.length isnt used here: we try to avoid resetting the vector completely (probably an optimisation), but just free the buffers from it and set the connection->connected to false and the next player joining fills the gap.
. dunno, smells useless.
Referenced by add_client_connection(), delete_client_connection(), get_num_clients(), and has_clients().
vector< clientinfo * > server::clients
Referenced by addgban(), server::hideandseekservermode::announceseekers(), autoteam(), buildworldstate(), change_mastermode(), changemap(), server::hideandseekservermode::checkfinished(), checklms(), checkmaps(), checkpausegame(), checkvotes(), choosebestclient(), chooseworstteam(), disconnect_client(), dodamage(), duplicatename(), enddemoplayback(), extinfoteams(), extserverinforeply(), findscore(), freegetdemo(), freegetmap(), server::bombservermode::gamerunning(), server::hideandseekservermode::getactiveplayers(), server::hideandseekservermode::getremaininghiders(), hasmap(), server::collectservermode::initclient(), server::hideandseekservermode::initplayers(), kickclients(), numclients(), server::captureservermode::parsebases(), parsepacket(), player_connected(), processevents(), server::captureservermode::regenowners(), sendclipboard(), sendmessages(), sendpackets(), sendpositions(), server::bombservermode::sendspawnlocs(), serverupdate(), setmaster(), server::captureservermode::setup(), server::captureservermode::stealbase(), teamhasplayers(), welcomeinitclient(), and welcomepacket().
collectservermode server::collectmode
Referenced by changemap().
vector< clientinfo * > server::connects
Referenced by check_clients_timed_out(), clientconnect(), disconnect_client(), and player_connected().
ctfservermode server::ctfmode
Referenced by changemap(), and game::setclientmode().
int server::curmaprotation = 0
Referenced by findmaprotation(), maprotationreset(), nextmaprotation(), and rotatemap().
constexpr int server::DEATHMILLIS = 300 static
Referenced by dodamage(), and server::gamestate::isalive().
int server::demomillis = 0
Referenced by readdemo(), and setupdemoplayback().
bool server::demonextmatch = false
Whether we want to record a demo next match.
Referenced by changemap(), and parsepacket().
stream * server::demoplayback = nullptr
Referenced by enddemoplayback(), readdemo(), and setupdemoplayback().
stream * server::demorecord = nullptr
The streams for demo playback or demo recording.
set to nullptr if not recording/playing a demo.
Referenced by checkvotes(), enddemorecord(), flushclientposition(), sendpackets(), serverupdate(), setupdemorecord(), vote(), and writedemo().
vector< demofile > server::demos
Referenced by adddemo(), cleardemos(), listdemos(), game::parsemessages(), prunedemos(), and senddemo().
stream* server::demotmp = nullptr
Referenced by adddemo(), enddemorecord(), and setupdemorecord().
int server::gamelimit = 0
Referenced by changemap(), checkintermission(), extinfoteams(), hasmap(), server::captureservermode::movebases(), pickup(), serverinforeply(), serverupdate(), startintermission(), server::captureservermode::update(), server::collectservermode::update(), server::ctfservermode::update(), and welcomepacket().
bool server::gamepaused = false
Whether this game is currently paused.
Referenced by checkpausegame(), ispaused(), pausegame(), serverinforeply(), serverupdate(), and welcomepacket().
int server::gamespeed = 100
Referenced by changegamespeed(), serverinforeply(), serverslice(), and welcomepacket().
vector<ipmask> server::gbans
Referenced by addgban(), checkgban(), and cleargbans().
hideandseekservermode server::hideandseekmode
Referenced by changemap(), and game::setclientmode().
int server::interm = 0
Referenced by changemap(), server::hideandseekservermode::checkfinished(), checkintermission(), serverupdate(), and welcomepacket().
ENetSocket server::lansock = ENET_SOCKET_NULL
Referenced by checkserversockets(), cleanupserver(), and setup_network_sockets().
enet_uint32 server::lastsend = 0
Referenced by sendpackets().
int server::laststatus = 0
Referenced by serverslice().
stream* server::mapdata = nullptr
Referenced by parsepacket(), and receivefile().
vector<maprotation> server::maprotations
Referenced by addmaprotation(), findmaprotation(), maprotationreset(), rotatemap(), and vote().
int server::mastermask = MM_PRIVSERV
Referenced by change_mastermode(), get_mastermode_int(), and setmaster().
int server::mastermode = MM_OPEN
Referenced by allowconnect(), change_mastermode(), get_mastermode_int(), parsepacket(), player_connected(), setmaster(), vote(), and welcomepacket().
SharedVar<int> server::maxclients
Referenced by allowconnect(), serverinforeply(), and setup_network_sockets().
SharedVar<int> server::maxdemos
Referenced by enddemorecord(), parsepacket(), and prunedemos().
SharedVar<int> server::maxdemosize
Referenced by adddemo(), enddemorecord(), parsepacket(), and writedemo().
SharedVar<int> server::maxdupclients
Referenced by setup_network_sockets().
uint server::mcrc = 0
Referenced by checkmaps(), loaditems(), resetitems(), and shouldspectate().
vector< entity > server::ments
Referenced by loaditems(), server::bombservermode::pushentity(), resetitems(), server::bombservermode::setup(), server::captureservermode::setup(), server::collectservermode::setup(), and server::ctfservermode::setup().
struct server::worldstate server::msgfilter
int server::nextexceeded = 0
Referenced by changemap(), server::clientinfo::scheduleexceeded(), and serverupdate().
int server::nextplayback = 0
Referenced by readdemo(), and setupdemoplayback().
bool server::notgotitems = true
Referenced by loaditems(), parsepacket(), server::bombservermode::setup(), server::captureservermode::setup(), server::collectservermode::setup(), server::ctfservermode::setup(), and welcomepacket().
ENetAddress server::pongaddr static
Referenced by checkserversockets(), and sendserverinforeply().
ENetSocket server::pongsock = ENET_SOCKET_NULL
Referenced by checkserversockets(), cleanupserver(), sendserverinforeply(), and setup_network_sockets().
bool server::reliablemessages = false
vector<savedscore> server::scores
Referenced by extinfoteams(), findscore(), and resetdisconnectedplayerscores().
vector< server_entity > server::sents
Referenced by loaditems(), parsepacket(), pickup(), server::bombservermode::pushentity(), resetitems(), serverupdate(), and welcomepacket().
ENetAddress server::serveraddress = { ENET_HOST_ANY, ENET_PORT_ANY }
Referenced by setup_network_sockets().
SharedVar<char*> server::serverdesc
Referenced by sendservinfo(), and serverinforeply().
ENetHost * server::serverhost = nullptr
Referenced by cleanupserver(), flushserver(), getservermtu(), serverslice(), and setup_network_sockets().
SharedVar<char*> server::servermotd
Referenced by player_connected().
bool server::shouldcheckteamkills = false
Referenced by addteamkill(), changemap(), and serverupdate().
bool server::shouldstep = true
Referenced by parsepacket(), and serverupdate().
string server::smapname = ""
Referenced by adddemo(), changemap(), checkmaps(), hasmap(), loaditems(), server::bombservermode::parse_network_message(), server::collectservermode::parse_network_message(), server::ctfservermode::parse_network_message(), server::captureservermode::parse_network_message(), parsepacket(), rotatemap(), serverinforeply(), serverinit(), serverupdate(), setupdemoplayback(), vote(), and welcomepacket().
servmode * server::smode = nullptr
Referenced by autoteam(), aiman::balanceteams(), changemap(), checkintermission(), checkmaps(), chooseworstteam(), aiman::deleteai(), disconnect_client(), dodamage(), extinfoteams(), extinfoteamscore(), forcespectator(), parsepacket(), serverupdate(), aiman::shiftai(), and suicide().
hashset< teaminfo > server::teaminfos
Referenced by addteaminfo(), clearteaminfo(), dodamage(), extinfoteams(), pruneteaminfo(), suicide(), and welcomepacket().
vector<teamkillkick> server::teamkillkicks
Referenced by addteamkillkick(), and teamkillkickreset().
vector<teamkillinfo> server::teamkills
Referenced by addteamkill(), and changemap().
bool server::teamspersisted
Whether team reshuffeling after map change is disabled.
TODO move this to a better sourcefile.
Referenced by changemap(), and persistteams().
vector<worldstate> server::worldstates