Inexor: gle Namespace Reference
gle Namespace Reference
Classes
struct attribinfo
Enumerations
enum {
ATTRIB_VERTEX = 0, ATTRIB_COLOR = 1, ATTRIB_TEXCOORD0 = 2, ATTRIB_TEXCOORD1 = 3,
ATTRIB_NORMAL = 4, ATTRIB_TANGENT = 5, ATTRIB_BONEWEIGHT = 6, ATTRIB_BONEINDEX = 7,
MAXATTRIBS = 8
}
Functions
void enablequads ()
void disablequads ()
void drawquads (int offset, int count)
void defattrib (int type, int size, int format)
void defattribs (const char *fmt)
static void setattrib (const attribinfo &a, uchar *buf)
static void unsetattrib (const attribinfo &a)
static void setattribs (uchar *buf)
void begin (GLenum mode)
void begin (GLenum mode, int numverts)
void multidraw ()
int end ()
void forcedisable ()
void setup ()
void cleanup ()
static void disable ()
static void color (const bvec &v, uchar alpha=255)
static void color (const bvec4 &v)
static void normal (float x, float y, float z)
static void normal (const vec &v)
static void tangent (float x, float y, float z, float w=1.0f)
static void tangent (const vec &v, float w=1.0f)
static void tangent (const vec4 &v)
static void enableattrib (int index)
static void disableattrib (int index)
static void bindebo (GLuint ebo)
static void clearebo ()
static void bindvbo (GLuint vbo)
static void clearvbo ()
template<class T >
static void attrib (T x)
template<class T >
static void attrib (T x, T y)
template<class T >
static void attrib (T x, T y, T z)
template<class T >
static void attrib (T x, T y, T z, T w)
template<size_t N, class T >
static void attribv (const T *v)
static void attrib (const vec &v)
static void attrib (const vec &v, float w)
static void attrib (const vec2 &v)
static void attrib (const vec4 &v)
static void attrib (const ivec &v)
static void attrib (const ivec &v, int w)
static void attrib (const ivec2 &v)
static void attrib (const ivec4 &v)
static void attrib (const bvec &b)
static void attrib (const bvec &b, uchar w)
static void attrib (const bvec4 &b)
static void disable ()
Variables
const char *const attribnames [MAXATTRIBS] = { "vvertex", "vcolor", "vtexcoord0", "vtexcoord1", "vnormal", "vtangent", "vboneweight", "vboneindex" }
ucharbuf attribbuf
static uchar * attribdata
static attribinfo attribdefs [MAXATTRIBS]
static attribinfo lastattribs [MAXATTRIBS]
int enabled = 0
static int numattribs = 0
static int attribmask = 0
static int numlastattribs = 0
static int lastattribmask = 0
static int vertexsize = 0
static int lastvertexsize = 0
static GLenum primtype = GL_TRIANGLES
static uchar * lastbuf = nullptr
static bool changedattribs = false
static vector< GLint > multidrawstart
static vector< GLsizei > multidrawcount
static GLuint quadindexes = 0
static bool quadsenabled = false
static GLuint vbo = 0
static int vbooffset = MAXVBOSIZE
static GLuint defaultvao = 0
Enumeration Type Documentation
anonymous enum
Enumerator
ATTRIB_VERTEX
ATTRIB_COLOR
ATTRIB_TEXCOORD0
ATTRIB_TEXCOORD1
ATTRIB_NORMAL
ATTRIB_TANGENT
ATTRIB_BONEWEIGHT
ATTRIB_BONEINDEX
MAXATTRIBS
Function Documentation
template<class T > static void gle::attrib (T x) inline static
References attribbuf, databuf< T >::check(), and databuf< T >::pad().
Referenced by boxs(), boxsgrid(), draw_char(), drawdamagecompass(), drawenvoverlay(), obj::objmeshgroup::load(), gui::previewslot(), gui::rect_(), flarerenderer::render(), renderellipse(), renderentarrow(), renderentattachment(), renderentbox(), renderentcone(), renderentring(), meterrenderer::renderpart(), and rendertexturepanel().
template<class T > static void gle::attrib (T x, T y) inline static
References attribbuf, databuf< T >::check(), and databuf< T >::pad().
template<class T > static void gle::attrib (T x, T y, T z) inline static
References attribbuf, databuf< T >::check(), and databuf< T >::pad().
template<class T > static void gle::attrib (T x, T y, T z, T w) inline static
References attribbuf, databuf< T >::check(), and databuf< T >::pad().
static void gle::attrib (const vec & v) inline static
static void gle::attrib (const vec & v, float w) inline static
static void gle::attrib (const vec2 & v) inline static
static void gle::attrib (const vec4 & v) inline static
static void gle::attrib (const ivec & v) inline static
static void gle::attrib (const ivec & v, int w) inline static
static void gle::attrib (const ivec2 & v) inline static
static void gle::attrib (const ivec4 & v) inline static
static void gle::attrib (const bvec & b) inline static
static void gle::attrib (const bvec & b, uchar w) inline static
static void gle::attrib (const bvec4 & b) inline static
template<size_t N, class T > static void gle::attribv (const T * v) inline static
References attribbuf, and databuf< T >::put().
void gle::begin (GLenum mode)
References primtype.
Referenced by bgquad(), boxs(), boxsgrid(), rendertarget::debugblurtiles(), rendertarget::debugscissor(), editor::draw(), draw_text(), game::captureclientmode::drawblips(), drawdamagecompass(), drawenvboxface(), drawenvoverlay(), drawglass(), game::drawicon(), drawmaterial(), drawmaterialquery(), game::drawminimap(), game::drawradar(), gui::drawskin(), game::drawteammates(), forcecubemapload(), gui::previewslot(), gui::rect_(), flarerenderer::render(), render2dbox(), renderellipse(), renderentarrow(), renderentattachment(), renderentcone(), renderentring(), renderentselection(), renderlightning(), meterrenderer::renderpart(), renderprogress(), rendertexturepanel(), rendertarget::rendertiles(), and renderwaterfall().
void gle::begin (GLenum mode, int numverts)
References attribbuf, GL_MAP_INVALIDATE_RANGE_BIT, GL_MAP_UNSYNCHRONIZED_BIT, GL_MAP_WRITE_BIT, glBindBuffer_, glBufferData_, glGenBuffers_, glMapBufferRange_, lastvertexsize, MAXVBOSIZE, inexor::rpc::min(), primtype, databuf< T >::reset(), vbo, vbooffset, and vertexsize.
static void gle::bindebo (GLuint ebo) inline static
References disable(), and glBindBuffer_.
Referenced by animmodel::meshgroup::bindpos(), changevbuf(), fogdome::draw(), sphere::enable(), blobrenderer::flushblobs(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), sphere::init(), fogdome::init(), readva(), renderblendbrush(), renderdepthobstacles(), renderoutline(), renderprefab(), rendershadowmapreceivers(), renderskyva(), prefabmesh::setup(), setupbb(), and startbb().
static void gle::bindvbo (GLuint vbo) inline static
References disable(), and glBindBuffer_.
Referenced by animmodel::meshgroup::bindpos(), changevbuf(), fogdome::draw(), sphere::enable(), blobrenderer::flushblobs(), generategrass(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), sphere::init(), fogdome::init(), readva(), decalrenderer::render(), vertmodel::vertmeshgroup::render(), varenderer< T >::render(), skelmodel::skelmeshgroup::render(), renderblendbrush(), renderdepthobstacles(), rendergrass(), renderoutline(), renderprefab(), rendershadowmapreceivers(), renderskyva(), screenquad(), prefabmesh::setup(), setupbb(), setupscreenquad(), startbb(), and varenderer< T >::update().
void gle::cleanup ()
References defaultvao, disable(), glDeleteBuffers_, glDeleteVertexArrays_, MAXVBOSIZE, quadindexes, vbo, and vbooffset.
Referenced by cleanupgl().
static void gle::clearebo () inline static
References glBindBuffer_.
Referenced by blobrenderer::cleanuprenderstate(), sphere::disable(), animmodel::disablevbo(), disablevbuf(), fogdome::draw(), endbb(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), readva(), renderblendbrush(), renderdepthobstacles(), renderoutline(), renderprefab(), rendershadowmapreceivers(), rendersky(), prefabmesh::setup(), and setupbb().
static void gle::clearvbo () inline static
References glBindBuffer_.
Referenced by decalrenderer::cleanuprenderstate(), blobrenderer::cleanuprenderstate(), sphere::disable(), animmodel::disablevbo(), disablevbuf(), fogdome::draw(), endbb(), generategrass(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), readva(), varenderer< T >::render(), renderblendbrush(), renderdepthobstacles(), rendergrass(), renderoutline(), renderprefab(), rendershadowmapreceivers(), rendersky(), screenquad(), prefabmesh::setup(), setupbb(), setupscreenquad(), and varenderer< T >::update().
static void gle::color (const bvec & v, uchar alpha = 255) inline static
References glVertexAttrib4Nub_.
Referenced by decalrenderer::adddecal(), adddynlight(), game::collectclientmode::baseexplosion(), shaft::calcshaft(), fogdome::draw(), draw_crosshair(), draw_g3d_cursor(), draw_text(), drawenvoverlay(), drawfogoverlay(), game::drawhudmodel(), drawreflection(), gui::drawskin(), drawskybox(), decalrenderer::fadedecal(), game::ctfclientmode::flagexplosion(), game::gameplayhud(), gendynlightvariant(), gengrassquads(), hthash(), gui::icon_(), gui::line_(), makeparticles(), maskreflection(), gui::modelpreview(), gui::playerpreview(), gui::prefabpreview(), gui::previewslot(), flarerenderer::render(), animmodel::render(), renderblendbrush(), rendermaterials(), rendermatgrid(), renderoutline(), fireballrenderer::renderpart(), lightningrenderer::renderpart(), meterrenderer::renderpart(), renderprefab(), rendertexturepanel(), renderwater(), setnofog(), animmodel::skin::setshaderparams(), gui::tab(), texcolormask(), text_color(), game::updateprojectiles(), and fogdome::vert::vert().
static void gle::color (const bvec4 & v) inline static
References glVertexAttrib4Nubv_.
void gle::defattrib (int type, int size, int format)
References ATTRIB_VERTEX, attribdefs, attribmask, changedattribs, gle::attribinfo::format, format(), gle::attribinfo::formatsize, numattribs, gle::attribinfo::offset, gle::attribinfo::size, gle::attribinfo::type, and vertexsize.
Referenced by defattribs(), flarerenderer::render(), and lightningrenderer::startrender().
void gle::defattribs (const char * fmt)
References ATTRIB_BONEINDEX, ATTRIB_BONEWEIGHT, ATTRIB_COLOR, ATTRIB_NORMAL, ATTRIB_TANGENT, ATTRIB_TEXCOORD0, ATTRIB_TEXCOORD1, ATTRIB_VERTEX, defattrib(), format(), and GLenum().
static void gle::disable () inline static
References enabled, and forcedisable().
static void gle::disable () inline static
References enabled, and forcedisable().
Referenced by bindebo(), bindvbo(), cleanup(), enableattrib(), genvbo(), and inexor::rendering::screen::ScreenManager::swapbuffers().
static void gle::disableattrib (int index) inline static
References glDisableVertexAttribArray_.
void gle::disablequads ()
References glBindBuffer_, and quadsenabled.
Referenced by forcedisable(), varenderer< T >::render(), and rendergrass().
void gle::drawquads (int offset, int count)
References glDrawRangeElements_, and MAXQUADS.
Referenced by end(), varenderer< T >::render(), and rendergrass().
static void gle::enableattrib (int index) inline static
References disable(), and glEnableVertexAttribArray_.
void gle::enablequads ()
References glBindBuffer_, glBufferData_, glGenBuffers_, MAXQUADS, quadindexes, and quadsenabled.
Referenced by end(), varenderer< T >::render(), and rendergrass().
int gle::end ()
References attribbuf, attribdata, drawquads(), databuf< T >::empty(), enablequads(), databuf< T >::getbuf(), GL_MAP_INVALIDATE_RANGE_BIT, GL_MAP_UNSYNCHRONIZED_BIT, GL_MAP_WRITE_BIT, glBindBuffer_, glBufferData_, glBufferSubData_, glGenBuffers_, glMapBufferRange_, glMultiDrawArrays_, glUnmapBuffer_, lastbuf, lastvertexsize, databuf< T >::length(), loopv, MAXQUADS, MAXVBOSIZE, multidraw(), multidrawcount, multidrawstart, primtype, quadsenabled, databuf< T >::reset(), setattribs(), recorder::start(), vbo, vbooffset, and vertexsize.
Referenced by addblendbrush(), blobrenderer::addtris(), at(), bgquad(), boxs(), aviwriter::boxsample(), boxsgrid(), calclight(), decalrenderer::clearfadeddecals(), compilestatements(), compilestr(), complete(), cutstring(), rendertarget::debugblurtiles(), debugline(), rendertarget::debugscissor(), decodeutf8(), editor::draw(), draw_char(), draw_text(), game::captureclientmode::drawblips(), drawdamagecompass(), drawenvboxface(), drawenvoverlay(), game::drawicon(), game::drawminimap(), game::drawradar(), gui::drawskin(), game::drawteammates(), encodeutf8(), endianswap(), escapeid(), explodelist(), blobrenderer::fadeblob(), decalrenderer::fadedecal(), decalrenderer::fadeindecals(), decalrenderer::fadeoutdecals(), skelmodel::skeleton::findskelanim(), forcecubemapload(), generatelightmap(), gengenericvariant(), genpvs(), getbool(), Shader::getvariant(), indexlist(), insertionsort(), listdel(), listfilter(), listfind(), listincludes(), listsplice(), md5::md5mesh::load(), Slot::loadthumbnail(), looplist(), looplistconc(), makerelpath(), maskreflection(), newgui(), optimizeblendmap(), optimizematsurfs(), ipmask::parse(), parsefloat(), parselist(), game::parseplayer(), patchlight(), prettylist(), gui::previewslot(), queryreflection(), gui::rect_(), removelmalpha(), flarerenderer::render(), render2dbox(), renderellipse(), renderentarrow(), renderentattachment(), renderentcone(), renderentring(), renderentselection(), renderlightning(), rendermaterials(), rendermatgrid(), meterrenderer::renderpart(), renderprogress(), rendertexturepanel(), rendertarget::rendertiles(), renderwater(), reorients3tc(), reorienttexture(), varenderer< T >::seedemitter(), seedpos(), skelcommands< MDL >::setanim(), Shader::setvariant_(), sortlist(), sublist(), texagrad(), text_color(), and aviwriter::writesound().
void gle::forcedisable ()
References disablequads(), enabled, glBindBuffer_, glDisableVertexAttribArray_, lastattribmask, lastbuf, lastvertexsize, numlastattribs, and quadsenabled.
Referenced by disable().
void gle::multidraw ()
References attribbuf, databuf< T >::length(), multidrawcount, multidrawstart, recorder::start(), and vertexsize.
Referenced by end().
static void gle::normal (float x, float y, float z) inline static
References f(), and glVertexAttrib4f_.
Referenced by drawglass(), generatelightmap(), renderwaterfall(), and texnormal().
static void gle::normal (const vec & v) inline static
References glVertexAttrib4f_.
static void gle::setattrib (const attribinfo & a, uchar * buf) inline static
References ATTRIB_BONEINDEX, ATTRIB_BONEWEIGHT, ATTRIB_COLOR, ATTRIB_NORMAL, ATTRIB_TANGENT, ATTRIB_TEXCOORD0, ATTRIB_TEXCOORD1, ATTRIB_VERTEX, enabled, gle::attribinfo::format, glEnableVertexAttribArray_, glVertexAttribPointer_, gle::attribinfo::size, gle::attribinfo::type, and vertexsize.
Referenced by setattribs().
static void gle::setattribs (uchar * buf) inline static
References attribdefs, attribmask, changedattribs, enabled, gle::attribinfo::formatsize, lastattribmask, lastattribs, lastbuf, lastvertexsize, loopi(), numattribs, numlastattribs, setattrib(), gle::attribinfo::type, unsetattrib(), and vertexsize.
Referenced by end().
void gle::setup ()
References attribbuf, attribdata, defaultvao, glBindVertexArray_, glGenVertexArrays_, MAXVBOSIZE, and databuf< T >::reset().
Referenced by gl_init().
static void gle::tangent (float x, float y, float z, float w = 1.0f) inline static
References glVertexAttrib4f_.
Referenced by verthash::addvert(), animmodel::mesh::calctangents(), and vertmodel::vertmesh::interpverts().
static void gle::tangent (const vec & v, float w = 1.0f) inline static
References glVertexAttrib4f_.
static void gle::tangent (const vec4 & v) inline static
References glVertexAttrib4fv_.
static void gle::unsetattrib (const attribinfo & a) inline static
References enabled, glDisableVertexAttribArray_, and gle::attribinfo::type.
Referenced by setattribs().
Variable Documentation
ucharbuf gle::attribbuf
Referenced by attrib(), attribv(), begin(), drawglass(), drawmaterial(), drawmaterialquery(), end(), multidraw(), renderwaterfall(), and setup().
uchar* gle::attribdata static
Referenced by end(), and setup().
attribinfo gle::attribdefs[MAXATTRIBS] static
Referenced by defattrib(), and setattribs().
int gle::attribmask = 0 static
Referenced by defattrib(), and setattribs().
const char *const gle::attribnames = { "vvertex", "vcolor", "vtexcoord0", "vtexcoord1", "vnormal", "vtangent", "vboneweight", "vboneindex" }
Referenced by linkglslprogram().
bool gle::changedattribs = false static
Referenced by defattrib(), and setattribs().
GLuint gle::defaultvao = 0 static
Referenced by cleanup(), and setup().
int gle::enabled = 0
Referenced by disable(), forcedisable(), guibitfield(), guicheckbox(), guiradio(), setattrib(), setattribs(), and unsetattrib().
int gle::lastattribmask = 0 static
Referenced by forcedisable(), and setattribs().
attribinfo gle::lastattribs[MAXATTRIBS] static
Referenced by setattribs().
uchar* gle::lastbuf = nullptr static
Referenced by end(), forcedisable(), and setattribs().
int gle::lastvertexsize = 0 static
Referenced by begin(), end(), forcedisable(), and setattribs().
vector<GLsizei> gle::multidrawcount static
Referenced by end(), and multidraw().
vector<GLint> gle::multidrawstart static
Referenced by end(), and multidraw().
int gle::numattribs = 0 static
Referenced by defattrib(), and setattribs().
int gle::numlastattribs = 0 static
Referenced by forcedisable(), and setattribs().
GLenum gle::primtype = GL_TRIANGLES static
Referenced by begin(), and end().
GLuint gle::quadindexes = 0 static
Referenced by cleanup(), and enablequads().
bool gle::quadsenabled = false static
Referenced by disablequads(), enablequads(), end(), and forcedisable().
GLuint gle::vbo = 0 static
Referenced by begin(), cleanup(), varenderer< T >::cleanup(), prefab::cleanup(), end(), genvbo(), varenderer< T >::render(), and varenderer< T >::update().
int gle::vbooffset = MAXVBOSIZE static
Referenced by begin(), cleanup(), and end().
int gle::vertexsize = 0 static
Referenced by begin(), defattrib(), end(), multidraw(), setattrib(), and setattribs().