Inexor: inexor::sound Namespace Reference
inexor::sound Namespace Reference
Classes
struct soundsample
struct soundslot
struct soundconfig
struct soundchannel
struct soundtype
Functions
VARFP (mumble, 0, 0, 1,{if(mumble) initmumble();else closemumble();})
void initmumble ()
void closemumble ()
static vec mumblevec (const vec &v, bool pos=false)
void updatemumble ()
soundchannel & newchannel (int n, soundslot *slot, const vec *loc=nullptr, extentity *ent=nullptr, int flags=0, int radius=0)
void freechannel (int n)
void syncchannel (soundchannel &chan)
void stopchannels ()
VARFP (soundvol, 0, 255, 255, if(!soundvol){stopchannels();})
VARF (soundchans, 1, 32, 128, initwarning("sound configuration", INIT_RESET, CHANGE_SOUND))
VARF (soundfreq, 0, 44100, 44100, initwarning("sound configuration", INIT_RESET, CHANGE_SOUND))
VARF (soundbufferlen, 128, 1024, 4096, initwarning("sound configuration", INIT_RESET, CHANGE_SOUND))
void initsound ()
static void cleanupsamples ()
void registersound (char *name, int *vol)
COMMAND (registersound,"si")
void mapsound (char *name, int *vol, int *maxuses)
COMMAND (mapsound,"sii")
void altsound (char *name, int *vol)
COMMAND (altsound,"si")
void altmapsound (char *name, int *vol)
COMMAND (altmapsound,"si")
void soundreset ()
COMMAND (soundreset,"")
void mapsoundreset ()
COMMAND (mapsoundreset,"")
void resetchannels ()
void clear_sound ()
void stopmapsounds ()
void clearmapsounds ()
void stopmapsound (extentity *e)
void checkmapsounds ()
VAR (stereo, 0, 1, 1)
VARP (maxsoundradius, 0, 340, 10000)
bool updatechannel (soundchannel &chan)
void reclaimchannels ()
void syncchannels ()
void updatesounds ()
VARP (maxsoundsatonce, 0, 7, 100)
VAR (dbgsound, 0, 0, 1)
void preloadsound (int n)
void preloadmapsound (int n)
void preloadmapsounds ()
int playsound (int n, const vec *loc, extentity *ent, int flags, int loops, int fade, int chanid, int radius, int expire)
void stopsounds ()
bool stopsound (int n, int chanid, int fade)
int playsoundname (const char *s, const vec *loc, int vol, int flags, int loops, int fade, int chanid, int radius, int expire)
void sound (int *n)
COMMAND (sound,"i")
void resetsound ()
COMMAND (resetsound,"")
Variables
bool nosound = true
vector< soundchannel > channels
int maxchannels = 0
static hashnameset< soundsample > samples
static struct
inexor::sound::soundtype gamesounds
static struct
inexor::sound::soundtype mapsounds
SharedVar< int > soundchans
SharedVar< int > soundfreq
SharedVar< int > soundbufferlen
Class Documentation
struct inexor::sound::soundslot
Class Members
soundsample * sample
int volume
Function Documentation
void inexor::sound::altmapsound (char * name, int * vol)
References inexor::sound::soundtype::addalt(), and mapsounds.
void inexor::sound::altsound (char * name, int * vol)
References inexor::sound::soundtype::addalt(), and gamesounds.
void inexor::sound::checkmapsounds ()
References entity::attr1, entity::attr2, camera1, vec::dist(), EF_SOUND, entities::ents, ET_SOUND, extentity::flags, entities::getents(), loopv, entity::o, physent::o, playsound(), SND_MAP, stopmapsound(), and entity::type.
Referenced by updatesounds().
static void inexor::sound::cleanupsamples () static
References inexor::sound::soundsample::cleanup(), enumerate, and samples.
Referenced by clear_sound(), and resetsound().
void inexor::sound::clear_sound ()
References cleanupsamples(), inexor::sound::soundtype::clear(), closemumble(), gamesounds, mapsounds, nosound, resetchannels(), and samples.
Referenced by cleanup().
void inexor::sound::clearmapsounds ()
References inexor::sound::soundtype::clear(), mapsounds, and stopmapsounds().
Referenced by resetmap().
void inexor::sound::closemumble ()
References NULL.
Referenced by clear_sound(), and initmumble().
inexor::sound::COMMAND (registersound , "si")
inexor::sound::COMMAND (mapsound , "sii")
inexor::sound::COMMAND (altsound , "si")
inexor::sound::COMMAND (altmapsound , "si")
inexor::sound::COMMAND (soundreset , "")
inexor::sound::COMMAND (mapsoundreset , "")
inexor::sound::COMMAND (sound , "i")
inexor::sound::COMMAND (resetsound , "")
void inexor::sound::freechannel (int n)
References channels, EF_SOUND, inexor::sound::soundchannel::ent, extentity::flags, and inexor::sound::soundchannel::inuse.
Referenced by playsound(), inexor::sound::soundtype::reset(), resetchannels(), stopchannels(), stopmapsound(), stopmapsounds(), stopsound(), and stopsounds().
void inexor::sound::initmumble ()
References closemumble(), defformatstring, Log, and inexor::util::log_manager::std.
Referenced by main().
void inexor::sound::initsound ()
References maxchannels, nosound, and soundchans.
Referenced by main(), and resetsound().
void inexor::sound::mapsound (char * name, int * vol, int * maxuses)
References inexor::sound::soundtype::addsound(), intret(), mapsounds, and inexor::rpc::max().
void inexor::sound::mapsoundreset ()
References mapsounds, and inexor::sound::soundtype::reset().
static vec inexor::sound::mumblevec (const vec & v, bool pos = false) inline static
References vec::div().
Referenced by updatemumble().
soundchannel& inexor::sound::newchannel (int n, soundslot * slot, const vec * loc = nullptr, extentity * ent = nullptr, int flags = 0, int radius = 0)
References channels, EF_SOUND, inexor::sound::soundchannel::ent, inexor::sound::soundchannel::flags, inexor::sound::soundchannel::inuse, inexor::sound::soundchannel::loc, inexor::sound::soundchannel::radius, inexor::sound::soundchannel::reset(), and inexor::sound::soundchannel::slot.
Referenced by playsound().
int inexor::sound::playsound (int n, const vec * loc, extentity * ent, int flags, int loops, int fade, int chanid, int radius, int expire)
References camera1, channels, inexor::sound::soundconfig::chooseslot(), inexor::sound::soundchannel::clearloc(), inexor::sound::soundtype::configs, vec::dist(), freechannel(), gamesounds, inexor::sound::soundchannel::hasloc(), inexor::sound::soundchannel::loc, Log, loopv, mapsounds, maxchannels, inexor::sound::soundconfig::maxuses, inexor::rpc::min(), inexor::rendering::screen::ScreenManager::minimized, inexor::sound::soundsample::name, newchannel(), nosound, physent::o, inexor::sound::soundtype::playing(), inexor::sound::soundslot::sample, inexor::rendering::screen::screen_manager, inexor::sound::soundtype::slots, SND_MAP, inexor::util::log_manager::std, syncchannel(), totalmillis, and updatechannel().
Referenced by game::checkattacksound(), game::checkidlesound(), checkmapsounds(), entities::checkquad(), entities::checktriggers(), game::cycleweapon(), game::damaged(), game::deathstate(), game::collectclientmode::deposittokens(), game::ctfclientmode::dropflag(), game::collectclientmode::droptoken(), game::collectclientmode::expiretoken(), game::explode(), game::gunselect(), game::hit(), entities::jumppadeffects(), game::msgsound(), game::nextweapon(), game::parsemessages(), game::physicstrigger(), entities::pickupeffects(), playsoundname(), game::projsplash(), game::ctfclientmode::resetflag(), game::ctfclientmode::returnflag(), game::ctfclientmode::scoreflag(), game::setweapon(), game::shoteffects(), sound(), game::collectclientmode::stealtoken(), game::ctfclientmode::takeflag(), game::collectclientmode::taketoken(), entities::teleporteffects(), entities::trypickup(), entities::unlocktriggers(), and game::captureclientmode::updatebase().
int inexor::sound::playsoundname (const char * s, const vec * loc, int vol, int flags, int loops, int fade, int chanid, int radius, int expire)
References inexor::sound::soundtype::addsound(), inexor::sound::soundtype::findsound(), gamesounds, and playsound().
void inexor::sound::preloadmapsound (int n)
References mapsounds, and inexor::sound::soundtype::preloadsound().
Referenced by entities::preloadentities().
void inexor::sound::preloadmapsounds ()
References entity::attr1, entities::ents, ET_SOUND, entities::getents(), loopv, mapsounds, inexor::sound::soundtype::preloadsound(), and entity::type.
Referenced by load_world().
void inexor::sound::preloadsound (int n)
References gamesounds, and inexor::sound::soundtype::preloadsound().
Referenced by game::ctfclientmode::preload(), game::collectclientmode::preload(), game::captureclientmode::preload(), and game::preloadsounds().
void inexor::sound::reclaimchannels ()
References channels, and loopv.
Referenced by updatesounds().
void inexor::sound::registersound (char * name, int * vol)
References inexor::sound::soundtype::addsound(), gamesounds, and intret().
void inexor::sound::resetchannels ()
References channels, freechannel(), and loopv.
Referenced by clear_sound(), and resetsound().
void inexor::sound::resetsound ()
References CHANGE_SOUND, cleanupsamples(), clearchanges(), initsound(), nosound, and resetchannels().
void inexor::sound::sound (int * n)
References playsound().
Referenced by game::checkidlesound(), recorder::soundbuffer::cleanup(), recorder::soundbuffer::load(), entities::pickupeffects(), and game::shoteffects().
void inexor::sound::soundreset ()
References gamesounds, and inexor::sound::soundtype::reset().
void inexor::sound::stopchannels ()
References channels, freechannel(), inexor::sound::soundchannel::inuse, and loopv.
void inexor::sound::stopmapsound (extentity * e)
References channels, inexor::sound::soundchannel::ent, freechannel(), inexor::sound::soundchannel::inuse, and loopv.
Referenced by checkmapsounds().
void inexor::sound::stopmapsounds ()
References channels, freechannel(), and loopv.
Referenced by clearmapsounds(), and updatesounds().
bool inexor::sound::stopsound (int n, int chanid, int fade)
References channels, inexor::sound::soundtype::configs, freechannel(), gamesounds, Log, inexor::sound::soundtype::playing(), and inexor::util::log_manager::std.
Referenced by fpsent::stopattacksound(), fpsent::stopidlesound(), and fpsent::~fpsent().
void inexor::sound::stopsounds ()
References channels, freechannel(), and loopv.
Referenced by renderbackground(), and updatesounds().
void inexor::sound::syncchannel (soundchannel & chan)
References inexor::sound::soundchannel::dirty.
Referenced by playsound(), and syncchannels().
void inexor::sound::syncchannels ()
References channels, inexor::sound::soundchannel::hasloc(), inexor::sound::soundchannel::inuse, loopv, syncchannel(), and updatechannel().
Referenced by updatesounds().
bool inexor::sound::updatechannel (soundchannel & chan)
References entity::attr2, entity::attr3, camera1, inexor::sound::soundchannel::dirty, vec::dist(), inexor::sound::soundchannel::ent, f(), inexor::sound::soundchannel::hasloc(), inexor::sound::soundchannel::loc, vec::magnitude2(), MAXVOL, inexor::rpc::min(), physent::o, inexor::sound::soundchannel::pan, RAD, inexor::sound::soundchannel::radius, vec::rotate_around_z(), inexor::sound::soundchannel::slot, inexor::sound::soundslot::volume, inexor::sound::soundchannel::volume, and physent::yaw.
Referenced by playsound(), and syncchannels().
void inexor::sound::updatemumble ()
References mumblevec(), physent::o, physent::pitch, RAD, and physent::yaw.
Referenced by updatesounds().
void inexor::sound::updatesounds ()
References checkmapsounds(), mainmenu, inexor::rendering::screen::ScreenManager::minimized, nosound, reclaimchannels(), inexor::rendering::screen::screen_manager, stopmapsounds(), stopsounds(), syncchannels(), and updatemumble().
Referenced by main().
inexor::sound::VAR (stereo , 0 , 1 , 1)
inexor::sound::VAR (dbgsound , 0 , 0 , 1)
inexor::sound::VARF (soundchans , 1 , 32 , 128 , initwarning("sound configuration", INIT_RESET, CHANGE_SOUND))
inexor::sound::VARF (soundfreq , 0 , 44100 , 44100 , initwarning("sound configuration", INIT_RESET, CHANGE_SOUND))
inexor::sound::VARF (soundbufferlen , 128 , 1024 , 4096 , initwarning("sound configuration", INIT_RESET, CHANGE_SOUND))
inexor::sound::VARFP (mumble , 0 , 0 , 1 , {if(mumble) initmumble();else closemumble();})
inexor::sound::VARFP (soundvol , 0 , 255 , 255 , if(!soundvol){stopchannels();})
inexor::sound::VARP (maxsoundradius , 0 , 340 , 10000)
inexor::sound::VARP (maxsoundsatonce , 0 , 7 , 100)
Variable Documentation
vector<soundchannel> inexor::sound::channels
Referenced by inexor::sound::soundtype::addslot(), freechannel(), newchannel(), playsound(), reclaimchannels(), inexor::sound::soundtype::reset(), resetchannels(), stopchannels(), stopmapsound(), stopmapsounds(), stopsound(), stopsounds(), and syncchannels().
struct inexor::sound::soundtype inexor::sound::gamesounds static
Referenced by altsound(), clear_sound(), playsound(), playsoundname(), preloadsound(), registersound(), soundreset(), and stopsound().
struct inexor::sound::soundtype inexor::sound::mapsounds static
Referenced by altmapsound(), clear_sound(), clearmapsounds(), mapsound(), mapsoundreset(), playsound(), preloadmapsound(), and preloadmapsounds().
int inexor::sound::maxchannels = 0
Referenced by initsound(), and playsound().
bool inexor::sound::nosound = true
Referenced by clear_sound(), initsound(), playsound(), inexor::sound::soundtype::preloadsound(), resetsound(), and updatesounds().
hashnameset<soundsample> inexor::sound::samples static
Referenced by inexor::sound::soundtype::addslot(), cleanupsamples(), and clear_sound().
SharedVar<int> inexor::sound::soundbufferlen
Referenced by writeinitcfg().
SharedVar<int> inexor::sound::soundchans
Referenced by initsound(), and writeinitcfg().
SharedVar<int> inexor::sound::soundfreq
Referenced by writeinitcfg().