Inexor: inexor/engine/octaedit.hpp File Reference
octaedit.hpp File Reference
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
Enumerations
enum {
EDIT_FACE = 0, EDIT_TEX, EDIT_MAT, EDIT_FLIP,
EDIT_COPY, EDIT_PASTE, EDIT_ROTATE, EDIT_REPLACE,
EDIT_DELCUBE, EDIT_REMIP, EDIT_VSLOT, EDIT_UNDO,
EDIT_REDO
}
This file contains editing stuff.
Functions
int shouldpacktex (int index)
bool packeditinfo (editinfo *e, int &inlen, uchar *&outbuf, int &outlen)
bool unpackeditinfo (editinfo *&e, const uchar *inbuf, int inlen, int outlen)
void freeeditinfo (editinfo *&e)
void pruneundos (int maxremain=0)
bool packundo (int op, int &inlen, uchar *&outbuf, int &outlen)
bool unpackundo (const uchar *inbuf, int inlen, int outlen)
bool noedit (bool view=false, bool msg=true)
check if user is allowed to edit concerns may be a scene selection which is not in view or disbaled editing status
void toggleedit (bool force=true)
change editing status also cancel selection, blendmaps and more
void mpeditface (int dir, int mode, selinfo &sel, bool local)
void mpedittex (int tex, int allfaces, selinfo &sel, bool local)
bool mpedittex (int tex, int allfaces, selinfo &sel, ucharbuf &buf)
void mpeditmat (int matid, int filter, selinfo &sel, bool local)
void mpflip (selinfo &sel, bool local)
void mpcopy (editinfo *&e, selinfo &sel, bool local)
void mppaste (editinfo *&e, selinfo &sel, bool local)
void mprotate (int cw, selinfo &sel, bool local)
void mpreplacetex (int oldtex, int newtex, bool insel, selinfo &sel, bool local, bool update=true)
bool mpreplacetex (int oldtex, int newtex, bool insel, selinfo &sel, ucharbuf &buf)
void mpdelcube (selinfo &sel, bool local)
bool mpeditvslot (int delta, int allfaces, selinfo &sel, ucharbuf &buf)
void mpremip (bool local)
void cancelsel ()
reset the current selection called every time user changes grid size or editing status
void rendertexturepanel (int w, int h)
render quick selection preview for surface textures standard edit key binding: press Z
void addundo (undoblock *u)
void commitchanges (bool force=false)
commits changes in geometry
void rendereditcursor ()
render selection box to the cursor target also moves entities!
void tryedit ()
check if editing can be done
void previewprefab (const char *name, const vec &color)
Variables
editinfo * localedit
bool editmode
vector< ushort > texmru
Enumeration Type Documentation
anonymous enum
This file contains editing stuff.
Enumerator
EDIT_FACE
EDIT_TEX
EDIT_MAT
EDIT_FLIP
EDIT_COPY
EDIT_PASTE
EDIT_ROTATE
EDIT_REPLACE
EDIT_DELCUBE
EDIT_REMIP
EDIT_VSLOT
EDIT_UNDO
EDIT_REDO
Function Documentation
void addundo (undoblock * u)
References undolist::add(), pruneundos(), undoblock::size, undoblock::timestamp, totalmillis, totalundos, undos, and undosize().
Referenced by makeundo(), and makeundoent().
void cancelsel ()
reset the current selection called every time user changes grid size or editing status
See Also
cubecancel
entcancel
References cubecancel(), and entcancel().
Referenced by resetmap(), and toggleedit().
void commitchanges (bool force = false)
commits changes in geometry
References entitiesinoctanodes(), haschanged, inbetweenframes, invalidatepostfx(), vector< T, MINSIZE >::length(), octarender(), resetblobs(), resetclipplanes(), setupmaterials(), updatevabbs(), and valist.
Referenced by changed(), previewblends(), swapundo(), and unpackundo().
void freeeditinfo (editinfo *& e)
References editinfo::copy, editinfos, and freeblock().
Referenced by fpsent::~fpsent().
void mpcopy (editinfo *& e, selinfo & sel, bool local)
References blockcopy(), changed(), editinfo::copy, EDIT_COPY, editinfos, game::edittrigger(), freeblock(), selinfo::grid, and protectsel.
Referenced by copy(), and game::parsemessages().
void mpdelcube (selinfo & sel, bool local)
References discardchildren(), EDIT_DELCUBE, game::edittrigger(), emptyfaces, and loopselxyz.
Referenced by delcube(), and game::parsemessages().
void mpeditface (int dir, int mode, selinfo & sel, bool local)
References blockcube(), C, cube::children, selinfo::corner, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, hmap::d, hmap::dc, DEFAULT_GEOM, dimcoord, dimension, dir, discardchildren(), EDIT_FACE, game::edittrigger(), emptyfaces, getmaterial(), selinfo::grid, isvalidcube(), linkedpush(), loop, loopi(), loopk, loopselxyz, hmap::mx, hmap::my, selinfo::o, optiface(), selinfo::orient, R, selinfo::s, solidfaces, cube::texture, selinfo::us(), and worldsize.
Referenced by editface(), and game::parsemessages().
void mpeditmat (int matid, int filter, selinfo & sel, bool local)
References EDIT_MAT, game::edittrigger(), isclipped, isdeadly, loopselxyz, MAT_CLIP, MAT_DEATH, MATF_CLIP, MATF_INDEX, MATF_VOLUME, and setmat().
Referenced by editmat(), and game::parsemessages().
void mpedittex (int tex, int allfaces, selinfo & sel, bool local)
References EDIT_TEX, edittexcube(), game::edittrigger(), loopselxyz, selinfo::orient, repsel, reptex, and sel.
Referenced by edittex(), mpedittex(), and game::parsemessages().
bool mpedittex (int tex, int allfaces, selinfo & sel, ucharbuf & buf)
References mpedittex(), and unpacktex().
bool mpeditvslot (int delta, int allfaces, selinfo & sel, ucharbuf & buf)
References editingvslot, VSlot::layer, mpeditvslot(), and unpackvslot().
void mpflip (selinfo & sel, bool local)
References changed(), dimension, EDIT_FLIP, game::edittrigger(), flipcube(), loop, loopxy, makeundo(), selinfo::orient, selinfo::s, and selcube.
Referenced by flip(), and game::parsemessages().
void mppaste (editinfo *& e, selinfo & sel, bool local)
References editinfo::copy, EDIT_PASTE, game::edittrigger(), and pasteblock().
Referenced by game::parsemessages(), and paste().
void mpremip (bool local)
References allchanged(), allocnodes, calcmerges(), EDIT_REMIP, game::edittrigger(), loopi(), remip(), remipprogress, remiptotal, sel, and worldsize.
Referenced by calclight(), game::parsemessages(), and remip_().
void mpreplacetex (int oldtex, int newtex, bool insel, selinfo & sel, bool local, bool update = true)
References allchanged(), EDIT_REPLACE, game::edittrigger(), loopi(), loopselxyz, replacetexcube(), and worldroot.
Referenced by mpreplacetex(), game::parsemessages(), and replace().
bool mpreplacetex (int oldtex, int newtex, bool insel, selinfo & sel, ucharbuf & buf)
References editingvslot, mpreplacetex(), and unpacktex().
void mprotate (int cw, selinfo & sel, bool local)
References C, changed(), D, hmap::d, dimcoord, dimension, EDIT_ROTATE, game::edittrigger(), loop, loopi(), loopxy, makeundo(), inexor::rpc::max(), selinfo::orient, R, rotatecube(), rotatequad(), selinfo::s, and selcube.
Referenced by game::parsemessages(), and rotate().
bool noedit (bool view = false, bool msg = true)
check if user is allowed to edit concerns may be a scene selection which is not in view or disbaled editing status
References vec::add(), inexor::util::log_manager::edit, editmode, selinfo::grid, haveselent(), isvisiblesphere(), Log, inexor::rpc::max(), vec::mul(), selinfo::o, selinfo::s, sel, and VFC_NOT_VISIBLE.
Referenced by canpaintblendmap(), clearblendmapsel(), clearlightmaps(), copy(), delcube(), ai::delselwaypoints(), editface(), editmat(), edittex_(), flip(), getcurtex(), getseltex(), gettex(), gettexname(), invertblendmap(), invertblendmapsel(), ai::movewaypoints(), paste(), pasteprefab(), patchlight(), pushsel(), replace(), rotate(), saveprefab(), selextend(), showblendmap(), shrinkmap(), swapundo(), valpha(), vcolor(), vdelta(), vlayer(), voffset(), vreset(), vrotate(), vscale(), vscroll(), and vshaderparam().
bool packeditinfo (editinfo * e, int & inlen, uchar *& outbuf, int & outlen)
References compresseditinfo(), editinfo::copy, vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), packblock(), and packvslots().
Referenced by game::sendclipboard().
bool packundo (int op, int & inlen, uchar *& outbuf, int & outlen)
References EDIT_REDO, EDIT_UNDO, undolist::empty(), undolist::last, packundo(), redos, and undos.
void previewprefab (const char * name, const vec & color)
References calcmodelpreviewpos(), editinfo::copy, block3::grid, loadprefab(), vec::mul(), renderprefab(), and block3::s.
Referenced by gui::prefabpreview().
void pruneundos (int maxremain = 0)
References undolist::empty(), freeundo(), undolist::popfirst(), redos, undoblock::size, totalundos, and undos.
Referenced by addundo(), clearundos(), and resetmap().
void rendereditcursor ()
render selection box to the cursor target also moves entities!
References vec::add(), blendpaintmode, boxoutline, boxs(), boxs3D(), boxsgrid(), C, camdir, cor, selinfo::corner, countselchild(), cur, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, D, hmap::d, dimcoord, dimension, disablepolygonoffset(), editmode, editmoveplane(), enablepolygonoffset(), entdrag(), entediting, entmoving, entorient, f(), g3d_windowhit(), GL_ONE, selinfo::grid, gridsize, havesel, hmapsel, horient, hoveringonent(), insideworld(), isheightmap(), lastcor, lookupcube(), loopi(), lu, lusize, ivec::mask(), cube::material, inexor::rpc::max(), inexor::rpc::min(), moving, vec::mul(), normalizelookupcube(), notextureshader, physent::o, selinfo::o, orient, selinfo::orient, outline, player, R, RAY_EDITMAT, RAY_ENTS, RAY_PASS, RAY_SKIPFIRST, rayboxintersect(), rayent(), renderentselection(), selinfo::s, sel, selchildcount, selchildmat, Shader::set(), showmat, vec::sub(), anonymous_namespace{utilTest.cpp}::t(), updateselection(), worldroot, and worldsize.
Referenced by gl_drawhud().
void rendertexturepanel (int w, int h)
render quick selection preview for surface textures standard edit key binding: press Z
References gle::attrib(), gle::begin(), gle::color(), VSlot::colorscale, curtexindex, curtime, editmode, gle::end(), f(), flushhudmatrix(), GL_ONE, VSlot::glowcolor, hudmatrix, hudshader, Texture::id, vector< T, MINSIZE >::inrange(), VSlot::layer, lookupvslot(), loopi(), loopj, loopk, loopvj, inexor::rpc::min(), vec::mul(), notexture, VSlot::offset, pophudmatrix(), pushhudmatrix(), VSlot::rotation, matrix4::scale(), Shader::set(), SETSHADER, VSlot::slot, Slot::sts, TEX_GLOW, Slot::texmask, texmru, texpaneltimer, Texture::xs, xtraverts, and Texture::ys.
Referenced by gl_drawhud().
int shouldpacktex (int index)
References VSlot::changed, Slot::index, VSlot::slot, and vslots.
Referenced by game::edittrigger().
void toggleedit (bool force)
change editing status also cancel selection, blendmaps and more
Parameters
force represents if the user was forced by administrators
References game::allowedittoggle(), cancelsel(), CS_ALIVE, CS_DEAD, CS_EDITING, editmode, physent::editstate, game::edittoggled(), entediting, entinmap(), physent::eyeheight, initlights(), inexor::io::input_router, isconnected(), inexor::io::InputRouter::keyrepeat(), KR_EDITMODE, lightents(), physent::o, player, game::resetgamestate(), physent::state, and stoppaintblendmap().
Referenced by game::changemapserv(), game::gameconnect(), and game::parsemessages().
void tryedit ()
check if editing can be done
Warning
please note that editing is not allowed when the HUD (head up dispaly) is disabled!
References blendpaintmode, editmode, mainmenu, and trypaintblendmap().
Referenced by main().
bool unpackeditinfo (editinfo *& e, const uchar * inbuf, int inlen, int outlen)
References editinfo::copy, editinfos, freeblock(), uncompresseditinfo(), unpackblock(), and unpackvslots().
Referenced by game::parsemessages().
bool unpackundo (const uchar * inbuf, int inlen, int outlen)
References changed(), commitchanges(), freeblock(), block3::grid, lilswap(), loopi(), databuf< T >::pad(), pasteundoblock(), pasteundoent(), databuf< T >::remaining(), block3::size(), uncompresseditinfo(), unpackblock(), unpackvslots(), and worldsize.
Referenced by game::parsemessages().
Variable Documentation
bool editmode
Referenced by game::allowedittoggle(), calclight(), changebatchtmus(), game::changemapserv(), game::drawhudgun(), drawreflections(), drawskybox(), emptymap(), enlargemap(), execbind(), game::gameconnect(), gengrassquads(), gl_drawframe(), gl_drawhud(), initlights(), lightreaching(), limitsky(), flarerenderer::makelightflares(), makeparticles(), noedit(), noentedit(), game::parsemessages(), queryreflections(), rendereditcursor(), rendermaterials(), rendermodel(), rendertexturepanel(), renderwater(), game::selectcrosshair(), texturegui::show(), showtexgui(), sortmaterials(), game::spawnplayer(), toggleedit(), tryedit(), and updateparticles().
editinfo* localedit
Referenced by copy(), paste(), pastehilite(), and game::sendclipboard().
vector<ushort> texmru
Referenced by compactmruvslots(), edittex(), edittex_(), emptymap(), filltexlist(), getcurtex(), gettex(), load_world(), mpeditvslot(), rendertexturepanel(), save_world(), and tofronttex().