Inexor: inexor/engine/octa.hpp File Reference
octa.hpp File Reference
#include "inexor/engine/material.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/geom.hpp"
Functions
cube * newcubes (uint face=F_EMPTY, int mat=MAT_AIR)
cubeext * growcubeext (cubeext *ext, int maxverts)
void setcubeext (cube &c, cubeext *ext)
cubeext * newcubeext (cube &c, int maxverts=0, bool init=true)
void getcubevector (cube &c, int d, int x, int y, int z, ivec &p)
void setcubevector (cube &c, int d, int x, int y, int z, const ivec &p)
int familysize (const cube &c)
void freeocta (cube *c)
void discardchildren (cube &c, bool fixtex=false, int depth=0)
void optiface (uchar *p, cube &c)
void validatec (cube *c, int size=0)
bool isvalidcube (const cube &c)
cube & lookupcube (const ivec &to, int tsize=0, ivec &ro=lu, int &rsize=lusize)
const cube & neighbourcube (const cube &c, int orient, const ivec &co, int size, ivec &ro=lu, int &rsize=lusize)
void resetclipplanes ()
int getmippedtexture (const cube &p, int orient)
void forcemip (cube &c, bool fixtex=true)
bool subdividecube (cube &c, bool fullcheck=true, bool brighten=true)
void edgespan2vectorcube (cube &c)
int faceconvexity (const ivec v[4])
int faceconvexity (const ivec v[4], int &vis)
int faceconvexity (const vertinfo *verts, int numverts, int size)
int faceconvexity (const cube &c, int orient)
void calcvert (const cube &c, const ivec &co, int size, ivec &vert, int i, bool solid=false)
void calcvert (const cube &c, const ivec &co, int size, vec &vert, int i, bool solid=false)
uint faceedges (const cube &c, int orient)
bool collapsedface (const cube &c, int orient)
bool touchingface (const cube &c, int orient)
bool flataxisface (const cube &c, int orient)
bool collideface (const cube &c, int orient)
int genclipplane (const cube &c, int i, vec *v, plane *clip)
void genclipplanes (const cube &c, const ivec &co, int size, clipplanes &p, bool collide=true)
bool visibleface (const cube &c, int orient, const ivec &co, int size, ushort mat=MAT_AIR, ushort nmat=MAT_AIR, ushort matmask=MATF_VOLUME)
int classifyface (const cube &c, int orient, const ivec &co, int size)
int visibletris (const cube &c, int orient, const ivec &co, int size, ushort nmat=MAT_ALPHA, ushort matmask=MAT_ALPHA)
int visibleorient (const cube &c, int orient)
void genfaceverts (const cube &c, int orient, ivec v[4])
int calcmergedsize (int orient, const ivec &co, int size, const vertinfo *verts, int numverts)
void invalidatemerges (cube &c, const ivec &co, int size, bool msg)
void calcmerges ()
int mergefaces (int orient, facebounds *m, int sz)
void mincubeface (const cube &cu, int orient, const ivec &o, int size, const facebounds &orig, facebounds &cf, ushort nmat=MAT_AIR, ushort matmask=MATF_VOLUME)
static cubeext & ext (cube &c)
int lookupmaterial (const vec &o)
static bool insideworld (const vec &o)
static bool insideworld (const ivec &o)
Variables
ivec lu
lookup integer vector
int lusize
lookup size
const cube * neighbourstack [32]
int neighbourdepth
const ivec cubecoords [8]
const ivec facecoords [6][4]
const uchar fv [6][4]
const uchar fvmasks [64]
const uchar faceedgesidx [6][4]
Function Documentation
int calcmergedsize (int orient, const ivec & co, int size, const vertinfo * verts, int numverts)
References ivec::mask(), inexor::rpc::max(), inexor::rpc::min(), sphere::numverts, ivec::shl(), vertinfo::x, vertinfo::y, and vertinfo::z.
Referenced by genmergedfaces(), and setupsurfaces().
void calcmerges ()
References genmergeprogress, and genmerges().
Referenced by mpremip().
void calcvert (const cube & c, const ivec & co, int size, ivec & vert, int i, bool solid = false)
References ivec::add(), ivec::div(), gencubevert(), and ivec::mul().
Referenced by genclipplanes(), and isvalidcube().
void calcvert (const cube & c, const ivec & co, int size, vec & vert, int i, bool solid = false)
References vec::add(), f(), gencubevert(), and vec::mul().
int classifyface (const cube & c, int orient, const ivec & co, int size)
References cube::children, collapsedface(), F_SOLID, faceedges(), genfacevecs(), insideface(), isempty, isentirelysolid, ivec::mask(), MAT_AIR, MAT_ALPHA, MAT_NOCLIP, cube::material, MATF_CLIP, neighbourcube(), notouchingface(), occludesface(), opposite, and touchingface().
Referenced by setcubevisibility().
bool collapsedface (const cube & c, int orient)
References ivec::cross(), dimcoord, dimension, faceedgesidx, orient, and ivec::sub().
Referenced by classifyface(), and visibleface().
bool collideface (const cube & c, int orient)
References faceedgesidx, flataxisface(), and orient.
Referenced by setcubevisibility().
void discardchildren (cube & c, bool fixtex = false, int depth = 0)
References allocnodes, cube::children, DELETEA, destroyva(), discardchildren(), cube::ext, F_EMPTY, F_SOLID, freecubeext(), freeoctaentities(), getmippedtexture(), loopi(), MAT_AIR, cube::material, cube::merged, cube::texture, cubeext::tjoints, and cubeext::va.
Referenced by discardchildren(), freeblock(), freeocta(), hmap::getcube(), mpdelcube(), mpeditface(), pastecube(), readychanges(), remip(), and validatec().
void edgespan2vectorcube (cube & c)
References cubeedge, edgeset, genedgespanvert(), isempty, isentirelysolid, and loop.
Referenced by loadc().
static cubeext& ext (cube & c) inline static
References cube::ext, and newcubeext().
Referenced by addtjoint(), bboccluded(), clearsurfaces(), clearvas(), findents(), gencubeedges(), generatelightmaps(), blobrenderer::gentris(), decalrenderer::gentris(), growcubeext(), inexor::filesystem::list_files(), loadsky(), loadskyoverlay(), modifyoctaentity(), newcubeext(), octacollide(), previewblends(), readychanges(), savec(), setcubeext(), setsurface(), setupsurfaces(), setva(), filesval::update(), updateva(), and filesval::~filesval().
int faceconvexity (const ivec v[4])
References ivec::cross(), ivec::dot(), and ivec::sub().
Referenced by addnormals(), faceconvexity(), faceorder(), genclipplane(), genclipplanes(), gencubeedges(), gencubeverts(), genpoly(), genprefabmesh(), blobrenderer::gentris(), decalrenderer::gentris(), previewblends(), savec(), and setupsurfaces().
int faceconvexity (const ivec v[4], int & vis)
References ivec::cross(), ivec::dot(), and ivec::iszero().
int faceconvexity (const vertinfo * verts, int numverts, int size)
References ivec::cross(), ivec::dot(), vertinfo::getxyz(), ivec::shr(), and ivec::sub().
int faceconvexity (const cube & c, int orient)
References faceconvexity(), flataxisface(), and genfaceverts().
uint faceedges (const cube & c, int orient)
References faceedges().
int familysize (const cube & c)
References cube::children, familysize(), and loopi().
Referenced by familysize(), and undosize().
bool flataxisface (const cube & c, int orient)
References dimcoord, and dimension.
Referenced by addnormals(), collideface(), faceconvexity(), genclipplanes(), gencubeedges(), gencubeverts(), genpoly(), genprefabmesh(), blobrenderer::gentris(), decalrenderer::gentris(), previewblends(), and setupsurfaces().
void forcemip (cube & c, bool fixtex = true)
References cube::children, emptyfaces, getcubevector(), getmippedtexture(), isempty, loopi(), loopj, setcubevector(), and cube::texture.
Referenced by hmap::getcube(), and remip().
void freeocta (cube * c)
References allocnodes, discardchildren(), and loopi().
Referenced by cleanup(), emptymap(), genprefabmesh(), load_world(), remip(), and shrinkmap().
int genclipplane (const cube & c, int i, vec * v, plane * clip)
References faceconvexity(), fv, orient, and plane::toplane().
void genclipplanes (const cube & c, const ivec & co, int size, clipplanes & p, bool collide = true)
References vec::add(), calcvert(), f(), faceconvexity(), flataxisface(), fv, loopi(), MAT_NOCLIP, MATF_CLIP, vec::max(), vec::min(), vec::mul(), hmap::mx, clipplanes::o, clipplanes::p, clipplanes::r, clipplanes::side, clipplanes::size, vec::sub(), plane::toplane(), clipplanes::v, clipplanes::visible, and visibletris().
Referenced by getclipplanes(), isvalidcube(), and shadowray().
void genfaceverts (const cube & c, int orient, ivec v[4])
References GENFACEVERTS.
Referenced by addnormals(), convertoldsurfaces(), faceconvexity(), gencubeedges(), gencubeverts(), genfacevecs(), genpoly(), genprefabmesh(), blobrenderer::gentris(), decalrenderer::gentris(), loadc(), previewblends(), setupsurfaces(), and visibletris().
void getcubevector (cube & c, int d, int x, int y, int z, ivec & p)
References C, cubeedge, D, edgeget, loopi(), and R.
Referenced by forcemip(), linkedpush(), hmap::pushside(), and subdividecube().
int getmippedtexture (const cube & p, int orient)
References cube::children, hmap::d, hmap::dc, DEFAULT_GEOM, DEFAULT_SKY, dimcoord, dimension, isempty, loop, loopi(), loopirev, octaindex, oppositeocta, orient, and cube::texture.
Referenced by discardchildren(), forcemip(), and remip().
cubeext* growcubeext (cubeext * ext, int maxverts)
References cubeext::ents, ext(), cubeext::maxverts, cubeext::tjoints, and cubeext::va.
Referenced by newcubeext(), setsurface(), and setupsurfaces().
static bool insideworld (const vec & o) inline static
References worldsize.
Referenced by drawskybox(), droptofloor(), ai::getweight(), load_world(), lookupmaterial(), modifyoctaent(), moveplatform(), ai::movewaypoints(), and rendereditcursor().
static bool insideworld (const ivec & o) inline static
References worldsize.
void invalidatemerges (cube & c, const ivec & co, int size, bool msg)
References invalidatemerges(), renderprogress(), and totalmillis.
bool isvalidcube (const cube & c)
References calcvert(), genclipplanes(), loopi(), and pointincube().
Referenced by mpeditface(), and subdividecube().
cube& lookupcube (const ivec & to, int tsize = 0, ivec & ro = lu, int & rsize = lusize)
References cube::children, ivec::mask(), octastep, subdividecube(), worldscale, and worldsize.
Referenced by blockcube(), findsurface(), hmap::getcube(), getseltex(), printcube(), rendereditcursor(), and setupmaterials().
int lookupmaterial (const vec & o)
References cube::children, insideworld(), MAT_AIR, cube::material, octastep, and worldscale.
Referenced by bounce(), game::collectclientmode::checkitems(), game::ctfclientmode::checkitems(), ai::clipped(), drawcubemap(), ai::getweight(), gl_drawframe(), ragdolldata::move(), moveplayer(), ai::navigate(), game::captureclientmode::rendertether(), and game::sendposition().
int mergefaces (int orient, facebounds * m, int sz)
References loopi(), mergeface(), mergefacecmp(), and quicksort().
Referenced by addskyverts().
void mincubeface (const cube & cu, int orient, const ivec & o, int size, const facebounds & orig, facebounds & cf, ushort nmat = MAT_AIR, ushort matmask = MATF_VOLUME)
References C, cube::children, dimcoord, dimension, faceedgesidx, isempty, loopi(), MAT_AIR, cube::material, inexor::rpc::max(), inexor::rpc::min(), mincubeface(), octacoord, orient, R, touchingface(), facebounds::u1, facebounds::u2, facebounds::v1, and facebounds::v2.
Referenced by genpoly(), mincubeface(), and minskyface().
const cube& neighbourcube (const cube & c, int orient, const ivec & co, int size, ivec & ro = lu, int & rsize = lusize)
References cube::children, dimcoord, dimension, ivec::mask(), neighbourdepth, octastep, worldroot, worldscale, and worldsize.
Referenced by classifyface(), mincubeface(), visibleface(), and visibletris().
cubeext* newcubeext (cube & c, int maxverts = 0, bool init = true)
References ext(), cube::ext, growcubeext(), cubeext::maxverts, setcubeext(), cubeext::surfaces, and cubeext::verts().
Referenced by brightencube(), ext(), loadc(), setsurface(), and setsurfaces().
cube* newcubes (uint face = F_EMPTY, int mat = MAT_AIR)
References allocnodes, cube::children, DEFAULT_GEOM, cube::ext, loopi(), loopl, cube::material, cube::merged, setfaces, and cube::texture.
Referenced by copycube(), emptymap(), enlargemap(), genprefabmesh(), loadchildren(), splitocta(), subdividecube(), and unpackcube().
void optiface (uchar * p, cube & c)
References emptyfaces, and f().
Referenced by mpeditface().
void resetclipplanes ()
References clipcacheversion.
Referenced by allchanged(), and commitchanges().
void setcubeext (cube & c, cubeext * ext)
References ext(), and cube::ext.
Referenced by cleanupthreads(), newcubeext(), and setsurface().
void setcubevector (cube & c, int d, int x, int y, int z, const ivec & p)
References C, cubeedge, D, edgeset, loopi(), and R.
Referenced by forcemip(), and hmap::pushside().
bool subdividecube (cube & c, bool fullcheck = true, bool brighten = true)
References brightencube(), C, cube::children, crosscenter(), cubeedge, D, hmap::d, dimcoord, dimension, edgeset, emptyfaces, cube::ext, F_EMPTY, F_SOLID, getcubevector(), isempty, isentirelysolid, isvalidcube(), loopi(), loopj, loopl, cube::material, midedge(), ivec::mul(), newcubes(), octaindex, R, cubeext::surfaces, cube::texture, and validatec().
Referenced by lookupcube(), remip(), shrinkmap(), and validatec().
bool touchingface (const cube & c, int orient)
References dimcoord, and dimension.
Referenced by classifyface(), genmerges(), genpoly(), mincubeface(), occludesface(), skyoccluded(), visibleface(), visibleorient(), and visibletris().
void validatec (cube * c, int size = 0)
References discardchildren(), emptyfaces, f(), loopi(), loopj, solidfaces, subdividecube(), and validatec().
Referenced by load_world(), subdividecube(), and validatec().
bool visibleface (const cube & c, int orient, const ivec & co, int size, ushort mat = MAT_AIR, ushort nmat = MAT_AIR, ushort matmask = MATF_VOLUME)
References cube::children, collapsedface(), F_SOLID, faceedges(), genfacevecs(), insideface(), isempty, isentirelysolid, isliquid, ivec::mask(), MAT_AIR, MAT_GLASS, cube::material, MATF_VOLUME, neighbourcube(), notouchingface(), occludesface(), opposite, and touchingface().
Referenced by blobrenderer::gentris(), decalrenderer::gentris(), remip(), and visiblematerial().
int visibleorient (const cube & c, int orient)
References crushededge(), faceedgesidx, loopi(), loopj, orient, and touchingface().
Referenced by edittexcube(), and remapvslots().
int visibletris (const cube & c, int orient, const ivec & co, int size, ushort nmat = MAT_ALPHA, ushort matmask = MAT_ALPHA)
References cube::children, ivec::cross(), dimcoord, dimension, ivec::dot(), F_SOLID, faceedges(), genfacevecs(), genfaceverts(), insideface(), isempty, isentirelysolid, ivec::iszero(), loopi(), ivec::mask(), MAT_AIR, cube::material, neighbourcube(), notouchingface(), occludesface(), opposite, touchingface(), and sphere::verts.
Referenced by addnormals(), fixinsidefaces(), fixrotatedlightmaps(), genclipplanes(), gencubeedges(), gencubeverts(), generatelightmaps(), genmerges(), genprefabmesh(), previewblends(), and savec().
Variable Documentation
const ivec cubecoords[8]
const ivec facecoords[6][4]
Referenced by addskyverts(), and convertoldsurfaces().
const uchar faceedgesidx[6][4]
Referenced by collapsedface(), collideface(), faceedges(), mincubeface(), and visibleorient().
const uchar fv[6][4]
Referenced by clampcollide(), genclipplane(), genclipplanes(), and iqm::iqmmeshgroup::loadiqmmeshes().
const uchar fvmasks[64]
ivec lu
lookup integer vector
Referenced by normalizelookupcube(), printcube(), and rendereditcursor().
int lusize
lookup size
Referenced by normalizelookupcube(), printcube(), rendereditcursor(), and selgridmap().
int neighbourdepth
Referenced by gencubeedges(), genmerges(), genprefabmesh(), neighbourcube(), rendercube(), and updateva().
const cube* neighbourstack[32]
Referenced by gencubeedges(), genprefabmesh(), rendercube(), and updateva().