Inexor: inexor/physics/physics.hpp File Reference
physics.hpp File Reference
#include "inexor/shared/geom.hpp"
Enumerations
enum {
RAY_BB = 1, RAY_POLY = 3, RAY_ALPHAPOLY = 7, RAY_ENTS = 9,
RAY_CLIPMAT = 16, RAY_SKIPFIRST = 32, RAY_EDITMAT = 64, RAY_SHADOW = 128,
RAY_PASS = 256, RAY_SKIPSKY = 512
}
Functions
bool pointincube (const clipplanes &p, const vec &v)
bool overlapsdynent (const vec &o, float radius)
void rotatebb (vec &center, vec &radius, int yaw)
float shadowray (const vec &o, const vec &ray, float radius, int mode, extentity *t=nullptr)
ShadowRayCache * newshadowraycache ()
void freeshadowraycache (ShadowRayCache *&cache)
void resetshadowraycache (ShadowRayCache *cache)
float shadowray (ShadowRayCache *cache, const vec &o, const vec &ray, float radius, int mode, extentity *t=nullptr)
float raycube (const vec &o, const vec &ray, float radius=0, int mode=RAY_CLIPMAT, int size=0, extentity *t=nullptr)
float raycubepos (const vec &o, const vec &ray, vec &hit, float radius=0, int mode=RAY_CLIPMAT, int size=0)
float rayfloor (const vec &o, vec &floor, int mode=0, float radius=0)
bool raycubelos (const vec &o, const vec &dest, vec &hitpos)
void moveplayer (physent *pl, int moveres, bool local)
bool moveplayer (physent *pl, int moveres, bool local, int curtime)
bool ellipseboxcollide (physent *d, const vec &dir, const vec &o, const vec &center, float yaw, float xr, float yr, float hi, float lo)
bool ellipsecollide (physent *d, const vec &dir, const vec &o, const vec &center, float yaw, float xr, float yr, float hi, float lo)
bool collide (physent *d, const vec &dir=vec(0, 0, 0), float cutoff=0.0f, bool playercol=true)
bool bounce (physent *d, float secs, float elasticity, float waterfric, float grav)
bool bounce (physent *d, float elasticity, float waterfric, float grav)
void avoidcollision (physent *d, const vec &dir, physent *obstacle, float space)
bool movecamera (physent *pl, const vec &dir, float dist, float stepdist)
void physicsframe ()
void dropenttofloor (entity *e)
bool droptofloor (vec &o, float radius, float height)
void vecfromyawpitch (float yaw, float pitch, int move, int strafe, vec &m)
void vectoyawpitch (const vec &v, float &yaw, float &pitch)
bool moveplatform (physent *p, const vec &dir)
void updatephysstate (physent *d)
void cleardynentcache ()
void updatedynentcache (physent *d)
bool entinmap (dynent *d, bool avoidplayers=false)
void findplayerspawn (dynent *d, int forceent=-1, int tag=0)
Variables
vec collidewall
bool collideinside
physent * collideplayer
Enumeration Type Documentation
anonymous enum
Enumerator
RAY_BB
RAY_POLY
RAY_ALPHAPOLY
RAY_ENTS
RAY_CLIPMAT
RAY_SKIPFIRST
RAY_EDITMAT
RAY_SHADOW
RAY_PASS
RAY_SKIPSKY
Function Documentation
void avoidcollision (physent * d, const vec & dir, physent * obstacle, float space)
References physent::aboveeye, vec::add(), physent::eyeheight, f(), loopi(), inexor::rpc::min(), physent::o, physent::radius, and vec::sub().
Referenced by game::newbouncer().
bool bounce (physent * d, float secs, float elasticity, float waterfric, float grav)
References physent::aboveeye, vec::add(), game::bounced(), collide(), collideinside, collideplayer, dir, vec::dot(), physent::eyeheight, f(), GRAVITY, isliquid, lookupmaterial(), loopi(), vec::magnitude(), inexor::rpc::max(), vec::mul(), physent::o, PHYS_BOUNCE, physent::physstate, vec::sub(), and physent::vel.
Referenced by bounce(), and game::updatebouncers().
bool bounce (physent * d, float elasticity, float waterfric, float grav)
References bounce(), physent::deltapos, f(), interppos(), loopi(), physent::newpos, physent::o, physframetime, and vec::sub().
void cleardynentcache ()
References dynentcache, DYNENTCACHESIZE, dynentframe, dynentcacheentry::frame, and loopi().
Referenced by game::clearmovables(), game::clientdisconnected(), and physicsframe().
bool collide (physent * d, const vec & dir = vec(0, 0, 0), float cutoff = 0.0f, bool playercol = true)
References physent::aboveeye, ivec::add(), collideinside, physent::eyeheight, physent::o, octacollide(), plcollide(), and physent::radius.
Referenced by bounce(), entinmap(), findfloor(), getclipplanes(), move(), movecamera(), moveplatform(), trystepdown(), trystepup(), and updatephysstate().
void dropenttofloor (entity * e)
References dropheight(), droptofloor(), and entity::o.
Referenced by dropentity().
bool droptofloor (vec & o, float radius, float height)
References hmap::d, dropent(), ENT_BOUNCE, f(), insideworld(), movecamera(), vec::normalize(), raycube(), and worldsize.
Referenced by dropenttofloor(), game::ctfclientmode::dropflag(), game::collectclientmode::movetoken(), and game::ctfclientmode::parseflags().
bool ellipseboxcollide (physent * d, const vec & dir, const vec & o, const vec & center, float yaw, float xr, float yr, float hi, float lo)
References physent::aboveeye, collideinside, ENT_INANIMATE, physent::eyeheight, f(), vec::iszero(), physent::o, RAD, physent::radius, vec::rotate_around_z(), vec::sub(), physent::type, and physent::zmargin.
Referenced by mmcollide(), platformcollide(), and plcollide().
bool ellipsecollide (physent * d, const vec & dir, const vec & o, const vec & center, float yaw, float xr, float yr, float hi, float lo)
References physent::aboveeye, vec::add(), collideinside, ENT_INANIMATE, physent::eyeheight, f(), vec::iszero(), vec::normalize(), physent::o, RAD, vec::rotate_around_z(), physent::type, physent::xradius, physent::yaw, physent::yradius, and physent::zmargin.
Referenced by mmcollide(), platformcollide(), plcollide(), and game::weaponcollide().
bool entinmap (dynent * d, bool avoidplayers = false)
References collide(), collideinside, physent::eyeheight, Log, loopi(), physent::o, physent::resetinterp(), rnd(), and inexor::util::log_manager::std.
Referenced by game::clearmovables(), findplayerspawn(), game::ctfclientmode::pickholdspawn(), game::bombclientmode::pickspawn(), entities::teleport(), and toggleedit().
void findplayerspawn (dynent * d, int forceent = -1, int tag = 0)
References entinmap(), entities::ents, ET_PLAYERSTART, findentity(), entities::getents(), loopi(), physent::o, physent::pitch, rnd(), physent::roll, spawncycle, worldsize, and physent::yaw.
Referenced by game::parsemessages(), game::clientmode::pickspawn(), game::hideandseekclientmode::pickspawn(), game::captureclientmode::pickspawn(), game::collectclientmode::pickspawn(), game::ctfclientmode::pickspawn(), game::spawnplayer(), and game::startmap().
void freeshadowraycache (ShadowRayCache *& cache)
Referenced by lightmapworker::~lightmapworker().
bool movecamera (physent * pl, const vec & dir, float dist, float stepdist)
References vec::add(), collide(), hmap::d, loopi(), vec::mul(), and physent::o.
Referenced by droptofloor(), game::collectclientmode::movetoken(), and recomputecamera().
bool moveplatform (physent * p, const vec & dir)
References physent::aboveeye, vector< T, MINSIZE >::add(), vec::add(), platforment::chains, checkdynentcache(), collide(), hmap::d, platforment::d, entities::ents, physent::eyeheight, vector< T, MINSIZE >::find(), insideworld(), vector< T, MINSIZE >::length(), loopv, loopvj, inexor::rpc::max(), inexor::rpc::min(), physent::newpos, physent::o, platformcollide(), physent::radius, vec::reject(), vector< T, MINSIZE >::setsize(), platforment::stacks, updatedynentcache(), and worldsize.
Referenced by game::updatemovables().
void moveplayer (physent * pl, int moveres, bool local)
References physent::deltapos, interppos(), loopi(), moveplayer(), physent::newpos, physent::o, physframetime, and vec::sub().
bool moveplayer (physent * pl, int moveres, bool local, int curtime)
References physent::aboveeye, vec::add(), physent::blocked, CS_ALIVE, CS_EDITING, CS_SPECTATOR, hmap::d, ENT_PLAYER, physent::eyeheight, f(), physent::falling, physent::inwater, isliquid, lookupmaterial(), loopi(), MAT_AIR, MAT_DEATH, MATF_VOLUME, modifygravity(), modifyvelocity(), move(), vec::mul(), physent::o, PHYS_FLOAT, PHYSFRAMETIME, game::physicstrigger(), physent::physstate, physent::roll, physent::state, physent::strafe, game::suicide(), physent::timeinair, physent::type, updatedynentcache(), and physent::vel.
Referenced by ai::logic(), moveplayer(), game::otherplayers(), game::predictplayer(), game::updatemovables(), and game::updateworld().
ShadowRayCache* newshadowraycache ()
Referenced by lightmapworker::lightmapworker().
bool overlapsdynent (const vec & o, float radius)
References checkdynentcache(), hmap::d, vec::dist(), loopdynentcache, loopv, physent::o, and physent::radius.
Referenced by entities::checktriggers(), and entities::unlocktriggers().
void physicsframe ()
References cleardynentcache(), game::gamespeed, lastmillis, lastphysframe, PHYSFRAMETIME, physframetime, and scaletime().
Referenced by game::updateworld().
bool pointincube (const clipplanes & p, const vec & v)
References plane::dist(), f(), loopi(), clipplanes::o, clipplanes::p, pointinbox(), clipplanes::r, and clipplanes::size.
Referenced by isvalidcube().
float raycube (const vec & o, const vec & ray, float radius = 0, int mode = RAY_CLIPMAT, int size = 0, extentity * t = nullptr)
References CHECKINSIDEWORLD, disttoent(), DOWNOCTREE, f(), FINDCLOSEST, getclipplanes(), INITRAYCUBE, isclipped, isempty, isentirelysolid, vec::iszero(), MAT_AIR, cube::material, MATF_VOLUME, inexor::rpc::min(), RAY_CLIPMAT, RAY_EDITMAT, RAY_PASS, RAY_SHADOW, RAY_SKIPFIRST, raycubeintersect(), and UPOCTREE.
Referenced by droptofloor(), ai::getweight(), game::particletrack(), raycubepos(), rayent(), rayfloor(), regularshape(), game::renderbouncers(), setupmaterials(), game::shoot(), splash(), and game::weaponcollide().
bool raycubelos (const vec & o, const vec & dest, vec & hitpos)
References vec::magnitude(), vec::mul(), RAY_CLIPMAT, RAY_POLY, raycubepos(), and vec::sub().
Referenced by ai::getsight(), and flarerenderer::newflare().
float raycubepos (const vec & o, const vec & ray, vec & hit, float radius = 0, int mode = RAY_CLIPMAT, int size = 0)
References vec::add(), vec::mul(), and raycube().
Referenced by ai::findorientation(), game::offsetray(), raycubelos(), setcammatrix(), and game::updateprojectiles().
float rayfloor (const vec & o, vec & floor, int mode = 0, float radius = 0)
References hitsurface, and raycube().
Referenced by partrenderer::calc().
void resetshadowraycache (ShadowRayCache * cache)
References ShadowRayCache::clipcache, and ShadowRayCache::version.
Referenced by lightmapworker::reset().
void rotatebb (vec & center, vec & radius, int yaw)
References sincos360.
Referenced by getentboundingbox(), mmboundbox(), mmcollisionbox(), and rendermodel().
float shadowray (const vec & o, const vec & ray, float radius, int mode, extentity * t = nullptr)
References CHECKINSIDEWORLD, DEFAULT_SKY, DOWNOCTREE, f(), FINDCLOSEST, getclipplanes(), INITRAYCUBE, INTERSECTBOX, INTERSECTPLANES, isempty, isentirelysolid, MAT_ALPHA, cube::material, inexor::rpc::max(), O_BOTTOM, O_FRONT, O_RIGHT, O_TOP, RAY_SKIPSKY, shadowent(), clipplanes::side, cube::texture, and UPOCTREE.
Referenced by brightestlight(), calcocclusion(), calcskylight(), fastskylight(), generatelumel(), and lightreaching().
float shadowray (ShadowRayCache * cache, const vec & o, const vec & ray, float radius, int mode, extentity * t = nullptr)
References CHECKINSIDEWORLD, ShadowRayCache::clipcache, DEFAULT_SKY, DOWNOCTREE, f(), FINDCLOSEST, genclipplanes(), INITRAYCUBE, INTERSECTBOX, INTERSECTPLANES, isempty, isentirelysolid, MAT_ALPHA, cube::material, inexor::rpc::max(), MAXCLIPPLANES, O_BOTTOM, O_FRONT, O_RIGHT, O_TOP, clipplanes::owner, RAY_SKIPSKY, shadowent(), clipplanes::side, cube::texture, UPOCTREE, clipplanes::version, ShadowRayCache::version, and worldroot.
void updatedynentcache (physent * d)
References vector< T, MINSIZE >::add(), dynentcache, dynentframe, DYNENTHASH, dynentcacheentry::dynents, vector< T, MINSIZE >::find(), dynentcacheentry::frame, loopdynentcache, physent::o, physent::radius, dynentcacheentry::x, and dynentcacheentry::y.
Referenced by game::clearmovables(), moveplatform(), moveplayer(), and entities::teleport().
void updatephysstate (physent * d)
References collide(), collidewall, physent::floor, FLOORZ, physent::o, PHYS_FALL, PHYS_FLOOR, PHYS_SLIDE, PHYS_SLOPE, PHYS_STEP_DOWN, PHYS_STEP_UP, physent::physstate, SLOPEZ, STAIRHEIGHT, and physent::timeinair.
Referenced by game::parsepositions().
void vecfromyawpitch (float yaw, float pitch, int move, int strafe, vec & m)
References RAD.
Referenced by shadowmaptexture::dorender(), game::drawhudmodel(), game::drawminimap(), entities::entradius(), ai::findorientation(), game::gotoplayer(), game::gotosel(), game::hudgunorigin(), menuinfrontofplayer(), modifyvelocity(), game::movable::movable(), game::collectclientmode::movetoken(), game::parsepositions(), game::particletrack(), renderentradius(), sortmaterials(), entities::teleport(), and game::triggerplatform().
void vectoyawpitch (const vec & v, float & yaw, float & pitch)
References vec::iszero(), vec::magnitude(), and RAD.
Referenced by damagecompass(), game::ctfclientmode::interpflagpos(), ai::process(), game::renderbouncers(), game::bombclientmode::renderplayersposindicator(), game::renderprojectiles(), and game::sendposition().
Variable Documentation
bool collideinside
Referenced by bounce(), collide(), cubecollideplanes(), cubecollidesolid(), ellipseboxcollide(), ellipsecollide(), entinmap(), fuzzycollideplanes(), fuzzycollidesolid(), mmcollide(), and plcollide().
physent* collideplayer
Referenced by bounce().
vec collidewall
Referenced by findfloor(), ragdolldata::move(), move(), updatephysstate(), and ragdolldata::updatepos().