Inexor: inexor/fpsgame/player.hpp File Reference
player.hpp File Reference
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/ents.hpp"
Functions
bool isthirdperson ()
Variables
SharedVar< int > thirdperson
dynent * player
local player
Function Documentation
bool isthirdperson ()
References camera1, detachedcamera, player, and reflecting.
Referenced by drawreflection(), game::hudgunorigin(), game::newbouncer(), entities::pickupeffects(), renderavatar(), game::collectclientmode::rendergame(), and game::rendergame().
Variable Documentation
dynent* player
local player
SharedVar<int> thirdperson
Referenced by game::hudplayer(), and recomputecamera().