Inexor: inexor/engine/renderparticles.hpp File Reference
renderparticles.hpp File Reference
Functions
void particleinit ()
void clearparticles ()
void clearparticleemitters ()
void seedparticles ()
void updateparticles ()
void renderparticles (bool mainpass=false)
bool printparticles (extentity &e, char *buf, int len)
void regularshape (int type, int radius, int color, int dir, int num, int fade, const vec &p, float size, int gravity, int vel=200, const vec *modfrom=nullptr, const vec *modto=nullptr)
bool canaddparticles ()
void regular_particle_splash (int type, int num, int fade, const vec &p, int color=0xFFFFFF, float size=1.0f, int radius=150, int gravity=2, int delay=0)
void regular_particle_flame (int type, const vec &p, float radius, float height, int color, int density=3, float scale=2.0f, float speed=200.0f, float fade=600.0f, int gravity=-15)
void particle_splash (int type, int num, int fade, const vec &p, int color=0xFFFFFF, float size=1.0f, int radius=150, int gravity=2)
void particle_trail (int type, int fade, const vec &from, const vec &to, int color=0xFFFFFF, float size=1.0f, int gravity=20)
void particle_text (const vec &s, const char *t, int type, int fade=2000, int color=0xFFFFFF, float size=2.0f, int gravity=0)
void particle_textcopy (const vec &s, const char *t, int type, int fade=2000, int color=0xFFFFFF, float size=2.0f, int gravity=0)
void particle_icon (const vec &s, int ix, int iy, int type, int fade=2000, int color=0xFFFFFF, float size=2.0f, int gravity=0)
void particle_meter (const vec &s, float val, int type, int fade=1, int color=0xFFFFFF, int color2=0xFFFFF, float size=2.0f)
void particle_flare (const vec &p, const vec &dest, int fade, int type, int color=0xFFFFFF, float size=0.28f, physent *owner=nullptr)
void particle_fireball (const vec &dest, float max, int type, int fade=-1, int color=0xFFFFFF, float size=4.0f)
void removetrackedparticles (physent *owner=nullptr)
Function Documentation
bool canaddparticles ()
References inexor::rendering::screen::ScreenManager::minimized, renderedgame, inexor::rendering::screen::screen_manager, and shadowmapping.
Referenced by particle_fireball(), particle_flare(), particle_icon(), particle_meter(), particle_splash(), particle_text(), particle_textcopy(), particle_trail(), regular_particle_flame(), regular_particle_splash(), game::captureclientmode::rendergame(), and game::ctfclientmode::rendergame().
void clearparticleemitters ()
References emitters, and regenemitters.
Referenced by clearparticles(), and modifyoctaent().
void clearparticles ()
References clearparticleemitters(), loopi(), parts, and partrenderer::reset().
Referenced by resetmap().
void particle_fireball (const vec & dest, float max, int type, int fade = -1, int color = 0xFFFFFF, float size = 4.0f)
References canaddparticles(), and newparticle().
Referenced by game::collectclientmode::baseexplosion(), game::collectclientmode::droptoken(), game::explode(), game::ctfclientmode::flagexplosion(), game::ctfclientmode::rendergame(), and game::captureclientmode::rendertether().
void particle_flare (const vec & p, const vec & dest, int fade, int type, int color = 0xFFFFFF, float size = 0.28f, physent * owner = nullptr)
References canaddparticles(), and newparticle().
Referenced by game::collectclientmode::baseeffect(), ai::drawroute(), game::collectclientmode::droptoken(), game::ctfclientmode::flageffect(), ai::render(), game::ctfclientmode::rendergame(), game::captureclientmode::rendertether(), game::shoteffects(), and game::collectclientmode::stealtoken().
void particle_icon (const vec & s, int ix, int iy, int type, int fade = 2000, int color = 0xFFFFFF, float size = 2.0f, int gravity = 0)
References canaddparticles(), particle::flags, and newparticle().
Referenced by game::parsemessages(), entities::pickupeffects(), game::captureclientmode::receiveammo(), and game::captureclientmode::updatebase().
void particle_meter (const vec & s, float val, int type, int fade = 1, int color = 0xFFFFFF, int color2 = 0xFFFFF, float size = 2.0f)
References canaddparticles(), and newparticle().
Referenced by game::captureclientmode::rendergame().
void particle_splash (int type, int num, int fade, const vec & p, int color = 0xFFFFFF, float size = 1.0f, int radius = 150, int gravity = 2)
References canaddparticles(), and splash().
Referenced by game::collectclientmode::baseexplosion(), game::damageeffect(), game::collectclientmode::droptoken(), game::explode(), game::ctfclientmode::flagexplosion(), game::projsplash(), game::ctfclientmode::rendergame(), game::captureclientmode::rendertether(), game::shoteffects(), game::captureclientmode::updatebase(), game::updatebouncers(), and game::updateprojectiles().
void particle_text (const vec & s, const char * t, int type, int fade = 2000, int color = 0xFFFFFF, float size = 2.0f, int gravity = 0)
References camera1, canaddparticles(), vec::dist(), newparticle(), physent::o, and anonymous_namespace{utilTest.cpp}::t().
Referenced by game::parsemessages(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), and game::rendergame().
void particle_textcopy (const vec & s, const char * t, int type, int fade = 2000, int color = 0xFFFFFF, float size = 2.0f, int gravity = 0)
References camera1, canaddparticles(), vec::dist(), particle::flags, newparticle(), newstring(), and physent::o.
Referenced by game::damageeffect(), makeparticles(), game::parsemessages(), ai::render(), game::ctfclientmode::scoreflag(), game::captureclientmode::setscore(), and updateparticles().
void particle_trail (int type, int fade, const vec & from, const vec & to, int color = 0xFFFFFF, float size = 1.0f, int gravity = 20)
References vec::add(), canaddparticles(), hmap::d, vec::dist(), vec::div(), loopi(), newparticle(), and rnd().
Referenced by game::shoteffects().
void particleinit ()
References partrenderer::init(), lookupshaderbyname(), loopi(), inexor::rpc::min(), particlenotextureshader, particleshader, parts, and PT_FEW.
Referenced by main().
bool printparticles (extentity & e, char * buf, int len)
References entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, entities::entname(), nformatstring(), and entity::type.
Referenced by printent().
void regular_particle_flame (int type, const vec & p, float radius, float height, int color, int density = 3, float scale = 2.0f, float speed = 200.0f, float fade = 600.0f, int gravity = -15)
References canaddparticles(), and regularflame().
Referenced by game::captureclientmode::rendergame(), and game::collectclientmode::rendergame().
void regular_particle_splash (int type, int num, int fade, const vec & p, int color = 0xFFFFFF, float size = 1.0f, int radius = 150, int gravity = 2, int delay = 0)
References canaddparticles(), and regularsplash().
Referenced by ai::render(), game::updatebouncers(), updateparticles(), and game::updateprojectiles().
void regularshape (int type, int radius, int color, int dir, int num, int fade, const vec & p, float size, int gravity, int vel = 200, const vec * modfrom = nullptr, const vec * modto = nullptr)
References vec::add(), camera1, canemitparticles(), partrenderer::collide, mpr::collide(), COLLIDEERROR, COLLIDERADIUS, hmap::d, vec::dist2(), f(), loopi(), inexor::rpc::max(), vec::mul(), newparticle(), physent::o, parts, PI, PI2, PT_LIGHTNING, PT_TAPE, RAY_CLIPMAT, raycube(), vec::rescale(), rnd(), rndscale(), seedemitter, sincos360, vec::sub(), and partrenderer::type.
Referenced by makeparticles(), and game::renderbouncers().
void removetrackedparticles (physent * owner = nullptr)
References loopi(), parts, and partrenderer::resettracked().
Referenced by game::clientdisconnected().
void renderparticles (bool mainpass = false)
References binddepthfxparams(), binddepthfxtex(), canstep, partrenderer::debuginfo(), depthfxpartblend, depthfxtex, hmap::flags, GL_ONE, glaring, GLOBALPARAMF, partrenderer::haswork(), depthfxtexture::highprecision(), loopi(), particlenotextureshader, particleshader, parts, PT_GLARE, PT_LERP, PT_MOD, PT_NOTEX, PT_SHADER, PT_SOFT, partrenderer::render(), resetfogcolor(), Shader::set(), SETSHADER, partrenderer::type, partrenderer::update(), and zerofogcolor().
Referenced by drawglare(), drawreflection(), and gl_drawframe().
void seedparticles ()
References addparticleemitters(), canemit, emitters, particleemitter::ent, particleemitter::finalize(), particleemitter::lastemit, loopv, makeparticles(), inexor::rpc::min(), renderprogress(), and seedemitter.
Referenced by allchanged().
void updateparticles ()
References addedparticles, addparticleemitters(), camera1, canemit, particleemitter::center, particleemitter::cullmax, particleemitter::cullmin, vec::dist(), editmode, emitoffset, emitters, particleemitter::ent, entgroup, entname(), entities::ents, ET_EMPTY, f(), flares, entities::getents(), isfoggedsphere(), particleemitter::lastcull, particleemitter::lastemit, lastemitframe, lastmillis, Log, loopv, flarerenderer::makelightflares(), makeparticles(), inexor::rpc::max(), particleemitter::maxfade, inexor::rendering::screen::ScreenManager::minimized, entity::o, physent::o, PART_EDIT, PART_TEXT, particle_textcopy(), pvsoccluded(), particleemitter::radius, regenemitters, regular_particle_splash(), inexor::rendering::screen::screen_manager, inexor::util::log_manager::std, and entity::type.
Referenced by main().