Inexor: inexor/engine/renderva.cpp File Reference
renderva.cpp File Reference
#include <SDL_opengl.h>
#include <limits.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include <unordered_set>
#include "inexor/engine/dynlight.hpp"
#include "inexor/engine/glare.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/grass.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/pvs.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/shadowmap.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/model/model.hpp"
#include "inexor/model/rendermodel.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct queryframe
struct renderstate
struct geombatch
Macros
#define VASORTSIZE 64
#define MAXQUERY 2048
#define MAXQUERYFRAMES 2
#define GENFACEORIENT(orient, v0, v1, v2, v3)
#define GENFACEVERT(orient, vert, ox, oy, oz, rx, ry, rz) (ox | oy | oz)
#define startvaquery(va, flush)
#define endvaquery(va, flush)
#define NUMCAUSTICS 16
#define FIRSTVA (reflecting ? reflectedva : visibleva)
#define NEXTVA (reflecting ? va->rnext : va->next)
Enumerations
enum {
RENDERPASS_LIGHTMAP = 0, RENDERPASS_Z, RENDERPASS_CAUSTICS, RENDERPASS_FOG,
RENDERPASS_LIGHTMAP_BLEND
}
Functions
static void drawtris (GLsizei numindices, const GLvoid *indices, ushort minvert, ushort maxvert)
static void drawvatris (vtxarray *va, GLsizei numindices, const GLvoid *indices)
bool isfoggedsphere (float rad, const vec &cv)
int isvisiblesphere (float rad, const vec &cv)
static int ishiddencube (const ivec &o, int size)
static int isfoggedcube (const ivec &o, int size)
int isvisiblecube (const ivec &o, int size)
float vadist (vtxarray *va, const vec &p)
void addvisibleva (vtxarray *va)
void sortvisiblevas ()
void findvisiblevas (vector< vtxarray * > &vas, bool resetocclude=false)
void calcvfcD ()
void setvfcP (float z, const vec &bbmin, const vec &bbmax)
void savevfcP ()
void restorevfcP ()
void visiblecubes (bool cull)
static bool insideva (const vtxarray *va, const vec &v, int margin=2)
int getnumqueries ()
void flipqueries ()
occludequery * newquery (void *owner)
void resetqueries ()
void clearqueries ()
VAR (oqfrags, 0, 8, 64)
VAR (oqwait, 0, 1, 1)
bool checkquery (occludequery *query, bool nowait)
static void setupbb ()
static void cleanupbb ()
void startbb (bool mask)
void endbb (bool mask)
void drawbb (const ivec &bo, const ivec &br)
static bool insideoe (const octaentities *oe, const vec &v, int margin=1)
void findvisiblemms (const vector< extentity * > &ents)
VAR (oqmm, 0, 4, 8)
void rendermapmodel (extentity &e)
void renderreflectedmapmodels ()
void rendermapmodels ()
static bool bbinsideva (const ivec &bo, const ivec &br, vtxarray *va)
static bool bboccluded (const ivec &bo, const ivec &br, cube *c, const ivec &o, int size)
bool bboccluded (const ivec &bo, const ivec &br)
VAR (outline, 0, 0, 1)
HVARP (outlinecolour, 0, 0, 0xFFFFFF)
VAR (dtoutline, 0, 1, 1)
void renderoutline ()
HVAR (blendbrushcolor, 0, 0x0000C0, 0xFFFFFF)
void renderblendbrush (uint tex, float x, float y, float w, float h)
void rendershadowmapreceivers ()
void renderdepthobstacles (const vec &bbmin, const vec &bbmax, float scale, float *ranges, int numranges)
VAR (oqdist, 0, 256, 1024)
VAR (zpass, 0, 1, 1)
VAR (glowpass, 0, 1, 1)
VAR (envpass, 0, 1, 1)
static void disablevbuf (renderstate &cur)
static void enablevquery (renderstate &cur)
static void disablevquery (renderstate &cur)
static void renderquery (renderstate &cur, occludequery *query, vtxarray *va, bool full=true)
static void mergetexs (renderstate &cur, vtxarray *va, elementset *texs=nullptr, int numtexs=0, ushort *edata=nullptr)
static void enablevattribs (renderstate &cur, bool all=true)
static void disablevattribs (renderstate &cur, bool all=true)
static void changevbuf (renderstate &cur, int pass, vtxarray *va)
void resetinvalidtextslots ()
Resets the set of slots that an error has been reported for.
static void reportinvalidtextslot (Slot *slot)
Reports a slot with an invalid texture definition.
static void changebatchtmus (renderstate &cur, int pass, geombatch &b)
static void changeslottmus (renderstate &cur, int pass, Slot &slot, VSlot &vslot)
static void changeshader (renderstate &cur, Shader *s, Slot &slot, VSlot &vslot, bool shadowed)
static void changetexgen (renderstate &cur, int dim, Slot &slot, VSlot &vslot)
static void renderbatch (renderstate &cur, int pass, geombatch &b)
static void resetbatches ()
static void renderbatches (renderstate &cur, int pass)
void renderzpass (renderstate &cur, vtxarray *va)
void renderfoggedvas (renderstate &cur, bool doquery=false)
VAR (batchgeom, 0, 1, 1)
void renderva (renderstate &cur, vtxarray *va, int pass=RENDERPASS_LIGHTMAP, bool fogpass=false, bool doquery=false)
SVARP (causticdir,"texture/inexor/material/water/caustic")
void loadcaustics (bool force)
void cleanupva ()
VARR (causticscale, 0, 50, 10000)
VARR (causticmillis, 0, 75, 1000)
VARFP (caustics, 0, 1, 1, loadcaustics())
void setupcaustics (float blend)
void setupgeom (renderstate &cur)
void cleanupgeom (renderstate &cur)
static void rendergeommultipass (renderstate &cur, int pass, bool fogpass)
VAR (oqgeom, 0, 1, 1)
void rendergeom (float causticspass, bool fogpass)
void renderalphageom (bool fogpass)
void findreflectedvas (vector< vtxarray * > &vas, int prevvfc=VFC_PART_VISIBLE)
void renderreflectedgeom (bool causticspass, bool fogpass)
void renderskyva (vtxarray *va, bool explicitonly=false)
static void updateskystats (vtxarray *va)
void renderreflectedskyvas (vector< vtxarray * > &vas, int prevvfc=VFC_PART_VISIBLE)
bool rendersky (bool explicitonly)
Variables
plane vfcP [5]
float vfcDfog
float vfcDnear [5]
float vfcDfar [5]
vtxarray * visibleva
static vtxarray * vasort [VASORTSIZE]
plane oldvfcP [5]
static queryframe queryframes [MAXQUERYFRAMES]
static uint flipquery = 0
static GLuint bbvbo = 0
static GLuint bbebo = 0
SharedVar< int > octaentsize
static octaentities * visiblemms
static octaentities ** lastvisiblemms
vtxarray * reflectedva
static vector< geombatch > geombatches
static int firstbatch = -1
static int numbatches = 0
static std::unordered_set< int > reportedinvalidtextsloterrs
The slots that an error message has been shown for.
vector< vtxarray * > foggedvas
static Texture * caustictex [NUMCAUSTICS] = { nullptr }
static vtxarray * prevskyva = nullptr
int renderedsky = 0
int renderedexplicitsky = 0
int renderedskyfaces = 0
int renderedskyclip = INT_MAX
Macro Definition Documentation
#define endvaquery (va, flush)
Value:
do { \
        if(va->query) \
        { \
            flush; \
            endquery(va->query); \
        } \
    } while(0)
Referenced by renderfoggedvas(), and renderva().
#define FIRSTVA (reflecting ? reflectedva : visibleva)
Referenced by renderalphageom(), rendergeom(), and rendergeommultipass().
#define GENFACEORIENT (orient, v0, v1, v2, v3)
Value:
do { \
            int offset = orient*3*2; \
            tris[offset + 0] = v0; \
            tris[offset + 1] = v1; \
            tris[offset + 2] = v2; \
            tris[offset + 3] = v0; \
            tris[offset + 4] = v2; \
            tris[offset + 5] = v3; \
        } while(0);
#define GENFACEVERT (orient, vert, ox, oy, oz, rx, ry, rz) (ox | oy | oz)
#define MAXQUERY 2048
Referenced by queryframe::newquery().
#define MAXQUERYFRAMES 2
Referenced by clearqueries(), flipqueries(), and resetqueries().
#define NEXTVA (reflecting ? va->rnext : va->next)
Referenced by renderalphageom(), rendergeom(), and rendergeommultipass().
#define NUMCAUSTICS 16
Referenced by cleanupva(), loadcaustics(), and setupcaustics().
#define startvaquery (va, flush)
Value:
do { \
        if(va->query) \
        { \
            flush; \
            startquery(va->query); \
        } \
    } while(0)
Referenced by renderfoggedvas(), and renderva().
#define VASORTSIZE 64
Referenced by addvisibleva(), and sortvisiblevas().
Enumeration Type Documentation
anonymous enum
Enumerator
RENDERPASS_LIGHTMAP
RENDERPASS_Z
RENDERPASS_CAUSTICS
RENDERPASS_FOG
RENDERPASS_LIGHTMAP_BLEND
Function Documentation
void addvisibleva (vtxarray * va)
References camera1, cur, vtxarray::distance, tiger::hash(), inexor::rpc::min(), vtxarray::next, physent::o, vadist(), VASORTSIZE, and worldsize.
Referenced by findvisiblevas().
static bool bbinsideva (const ivec & bo, const ivec & br, vtxarray * va) inline static
References vtxarray::bbmax, and vtxarray::bbmin.
Referenced by bboccluded().
static bool bboccluded (const ivec & bo, const ivec & br, cube * c, const ivec & o, int size) inline static
References bbinsideva(), vtxarray::curvfc, ext(), cube::ext, loopoctabox, OCCLUDE_BB, vtxarray::occluded, cubeext::va, and VFC_FOGGED.
Referenced by bboccluded(), and modeloccluded().
bool bboccluded (const ivec & bo, const ivec & br)
References bbinsideva(), bboccluded(), cube::children, vtxarray::curvfc, cube::ext, OCCLUDE_BB, vtxarray::occluded, octastep, cubeext::va, VFC_FOGGED, worldroot, and worldscale.
void calcvfcD ()
References loopi(), loopk, vfcDfar, and vfcDnear.
Referenced by restorevfcP(), and setvfcP().
static void changebatchtmus (renderstate & cur, int pass, geombatch & b) static
References brightengeom, changed(), vtxarray::dynlightmask, renderstate::dynlightmask, editmode, EMID_CUSTOM, elementset::envmap, geombatch::es, glActiveTexture_, GLuint(), lightmaptexs, elementset::lmid, LMID_BRIGHT, LMID_RESERVED, lookupenvmap(), reportinvalidtextslot(), setdynlights(), Slot::shader, SHADER_ENVMAP, SHADER_NORMALSLMS, VSlot::slot, renderstate::textures, Shader::type, geombatch::va, renderstate::visibledynlights, and geombatch::vslot.
Referenced by renderbatches().
static void changeshader (renderstate & cur, Shader * s, Slot & slot, VSlot & vslot, bool shadowed) static
References renderstate::alphaing, renderstate::blending, fading, glaring, Shader::hasoption(), lookupshaderbyname(), Shader::set(), Shader::setvariant(), and renderstate::visibledynlights.
Referenced by renderbatch().
static void changeslottmus (renderstate & cur, int pass, Slot & slot, VSlot & vslot) static
References VSlot::alphaback, VSlot::alphafront, renderstate::alphaing, renderstate::alphascale, VSlot::colorscale, renderstate::colorscale, Slot::Tex::combined, curfogcolor, glActiveTexture_, GLOBALPARAMF, GLuint(), Texture::id, loopvj, notexture, RENDERPASS_LIGHTMAP, setfogcolor(), Slot::shader, SHADER_ENVMAP, SHADER_NORMALSLMS, renderstate::slot, Slot::sts, anonymous_namespace{utilTest.cpp}::t(), Slot::Tex::t, TEX_DIFFUSE, TEX_ENVMAP, renderstate::textures, Slot::Tex::type, Shader::type, and renderstate::vslot.
Referenced by renderbatches().
static void changetexgen (renderstate & cur, int dim, Slot & slot, VSlot & vslot) static
References GLOBALPARAM, lastmillis, notexture, VSlot::offset, VSlot::rotation, VSlot::scale, VSlot::scroll, Slot::sts, renderstate::texgendim, renderstate::texgenscroll, renderstate::texgenslot, renderstate::texgenvslot, Texture::xs, and Texture::ys.
Referenced by renderbatches().
static void changevbuf (renderstate & cur, int pass, vtxarray * va) static
References gle::bindebo(), gle::bindvbo(), vtxarray::ebuf, vertex::lm, vertex::norm, vertex::pos, RENDERPASS_LIGHTMAP, vertex::tangent, vertex::tc, vtxarray::vbuf, and renderstate::vbuf.
Referenced by renderbatches(), renderfoggedvas(), renderva(), and renderzpass().
bool checkquery (occludequery * query, bool nowait)
References occludequery::fragments, glGetQueryObjectiv_, glGetQueryObjectuiv_, GLuint(), occludequery::id, and oqfrags.
Referenced by cullmodel(), drawreflections(), findvisiblemms(), rendergeom(), and renderwater().
static void cleanupbb () static
References bbebo, bbvbo, and glDeleteBuffers_.
Referenced by cleanupva().
void cleanupgeom (renderstate & cur)
References disablevattribs(), disablevbuf(), renderstate::vattribs, and renderstate::vbuf.
Referenced by renderalphageom(), and rendergeom().
void cleanupva ()
References cleanupbb(), cleanupgrass(), clearqueries(), clearvas(), loopi(), NUMCAUSTICS, and worldroot.
Referenced by resetgl().
void clearqueries ()
References queryframe::cleanup(), loopi(), and MAXQUERYFRAMES.
Referenced by cleanupva().
static void disablevattribs (renderstate & cur, bool all = true) inline static
References renderstate::vattribs.
Referenced by cleanupgeom(), renderalphageom(), and rendergeom().
static void disablevbuf (renderstate & cur) inline static
References gle::clearebo(), gle::clearvbo(), and renderstate::vbuf.
Referenced by cleanupgeom(), renderalphageom(), rendergeom(), and rendergeommultipass().
static void disablevquery (renderstate & cur) inline static
References endbb(), and renderstate::vquery.
Referenced by renderbatches(), rendergeom(), and renderzpass().
void drawbb (const ivec & bo, const ivec & br)
References glDrawRangeElements_, LOCALPARAMF, and xtraverts.
Referenced by rendercullmodelquery(), rendermapmodels(), and renderquery().
static void drawtris (GLsizei numindices, const GLvoid * indices, ushort minvert, ushort maxvert) inline static
References glde, and glDrawRangeElements_.
Referenced by drawvatris(), and renderbatch().
static void drawvatris (vtxarray * va, GLsizei numindices, const GLvoid * indices) inline static
References drawtris(), vtxarray::maxvert, and vtxarray::minvert.
Referenced by renderblendbrush(), renderdepthobstacles(), renderfoggedvas(), renderoutline(), rendershadowmapreceivers(), renderskyva(), renderva(), and renderzpass().
static void enablevattribs (renderstate & cur, bool all = true) inline static
References renderstate::vattribs.
Referenced by renderbatches(), renderfoggedvas(), rendergeommultipass(), and renderzpass().
static void enablevquery (renderstate & cur) inline static
References renderstate::colormask, renderstate::depthmask, startbb(), and renderstate::vquery.
Referenced by renderquery().
void endbb (bool mask)
References gle::clearebo(), and gle::clearvbo().
Referenced by disablecullmodelquery(), disablevquery(), and rendermapmodels().
void findreflectedvas (vector< vtxarray * > & vas, int prevvfc = VFC_PART_VISIBLE)
References camera1, vtxarray::children, vtxarray::curvfc, vtxarray::distance, isfoggedcube(), vector< T, MINSIZE >::length(), loopv, physent::o, vtxarray::o, OCCLUDE_BB, OCCLUDE_GEOM, vtxarray::occluded, PVS_FOGGED, PVS_FULL_VISIBLE, reflectedva, reflectz, ai::render(), vtxarray::rnext, vtxarray::size, vadist(), VFC_FOGGED, VFC_FULL_VISIBLE, and VFC_NOT_VISIBLE.
Referenced by renderreflectedgeom().
void findvisiblemms (const vector< extentity * > & ents)
References octaentities::bbmax, octaentities::bbmin, camera1, checkquery(), cur, vec::dist_to_bb(), octaentities::distance, EF_NOVIS, EF_RENDER, extentity::flags, isfoggedcube(), loopv, octaentities::mapmodels, octaentities::next, vtxarray::next, octaentities::o, physent::o, OCCLUDE_BB, occludequery::owner, pvsoccluded(), octaentities::query, octaentities::size, VFC_FOGGED, and visiblemms.
Referenced by rendermapmodels().
void findvisiblevas (vector< vtxarray * > & vas, bool resetocclude = false)
References addvisibleva(), vtxarray::children, vtxarray::curvfc, isvisiblecube(), vector< T, MINSIZE >::length(), loopv, vtxarray::o, OCCLUDE_GEOM, OCCLUDE_NOTHING, vtxarray::occluded, PVS_FULL_VISIBLE, pvsoccluded(), vtxarray::query, vtxarray::size, vtxarray::texs, VFC_FULL_VISIBLE, and VFC_NOT_VISIBLE.
Referenced by visiblecubes().
void flipqueries ()
References queryframe::flip(), flipquery, and MAXQUERYFRAMES.
Referenced by rendergeom().
int getnumqueries ()
References queryframe::cur, and flipquery.
Referenced by gl_drawhud().
HVAR (blendbrushcolor , 0 , 0x0000C0 , 0xFFFFFF)
HVARP (outlinecolour , 0 , 0 , 0xFFFFFF)
static bool insideoe (const octaentities * oe, const vec & v, int margin = 1) inline static
References octaentities::bbmax, and octaentities::bbmin.
Referenced by rendermapmodels().
static bool insideva (const vtxarray * va, const vec & v, int margin = 2) inline static
References vtxarray::o, and vtxarray::size.
Referenced by rendergeom().
static int isfoggedcube (const ivec & o, int size) inline static
References ivec::dist(), loopi(), vfcDfar, vfcDfog, and vfcDnear.
Referenced by findreflectedvas(), findvisiblemms(), and renderreflectedmapmodels().
bool isfoggedsphere (float rad, const vec & cv)
References plane::dist(), loopi(), and vfcDfog.
Referenced by cullmodel(), fireballrenderer::finddepthfxranges(), finddynlights(), gengrassquads(), rendergrass(), fireballrenderer::renderpart(), and updateparticles().
static int ishiddencube (const ivec & o, int size) inline static
References ivec::dist(), loopi(), and vfcDfar.
Referenced by renderalphageom(), rendergeom(), rendergeommultipass(), and renderreflectedskyvas().
int isvisiblecube (const ivec & o, int size)
References ivec::dist(), loopi(), VFC_FOGGED, VFC_FULL_VISIBLE, VFC_NOT_VISIBLE, VFC_PART_VISIBLE, vfcDfar, vfcDfog, and vfcDnear.
Referenced by findvisiblevas().
int isvisiblesphere (float rad, const vec & cv)
References plane::dist(), loopi(), VFC_FOGGED, VFC_FULL_VISIBLE, VFC_NOT_VISIBLE, VFC_PART_VISIBLE, and vfcDfog.
Referenced by flarerenderer::addflare(), flarerenderer::makelightflares(), and noedit().
void loadcaustics (bool force)
References caustics, defformatstring, loopi(), NUMCAUSTICS, textureload(), and useshaderbyname().
Referenced by setupcaustics(), and setupmaterials().
static void mergetexs (renderstate & cur, vtxarray * va, elementset * texs = nullptr, int numtexs = 0, ushort * edata = nullptr) static
References vector< T, MINSIZE >::add(), vtxarray::alphaback, vtxarray::alphafront, renderstate::alphaing, geombatch::batch, vtxarray::blends, vtxarray::blendtris, geombatch::compare(), dir, vtxarray::edata, vtxarray::eslist, firstbatch, vector< T, MINSIZE >::length(), loopi(), geombatch::next, numbatches, vtxarray::texs, and vtxarray::tris.
Referenced by renderva().
occludequery* newquery (void * owner)
References flipquery, and queryframe::newquery().
Referenced by queryreflections(), rendercullmodelquery(), rendergeom(), rendermapmodels(), and rendermodel().
void renderalphageom (bool fogpass)
References vector< T, MINSIZE >::add(), renderstate::alphaing, renderstate::alphascale, cleanupgeom(), renderstate::colormask, renderstate::colorscale, cur, renderstate::depthmask, disablevattribs(), disablevbuf(), vector< T, MINSIZE >::empty(), fading, FIRSTVA, GL_ONE, ishiddencube(), vector< T, MINSIZE >::length(), loop, loopv, NEXTVA, OCCLUDE_BB, OCCLUDE_GEOM, pvsoccluded(), reflecting, reflectz, refractfog, refracting, renderbatches(), RENDERPASS_LIGHTMAP, RENDERPASS_Z, renderva(), resetbatches(), resetfogcolor(), vector< T, MINSIZE >::setsize(), setupgeom(), renderstate::texgendim, renderstate::vattribs, renderstate::vbuf, and VFC_FOGGED.
Referenced by drawcubemap(), drawglare(), drawminimap(), drawreflection(), and gl_drawframe().
static void renderbatch (renderstate & cur, int pass, geombatch & b) static
References changeshader(), drawtris(), geombatch::es, gbatches, elementset::length, inexor::rpc::max(), inexor::rpc::min(), Slot::shader, VSlot::slot, geombatch::vslot, and vtris.
Referenced by renderbatches().
static void renderbatches (renderstate & cur, int pass) static
References renderstate::alphaing, changebatchtmus(), changeslottmus(), changetexgen(), changevbuf(), renderstate::colormask, renderstate::depthmask, elementset::dim, disablevquery(), enablevattribs(), geombatch::es, firstbatch, geombatch::next, renderbatch(), RENDERPASS_LIGHTMAP, resetbatches(), VSlot::slot, renderstate::slot, renderstate::texgendim, renderstate::texgenvslot, geombatch::va, renderstate::vattribs, vtxarray::vbuf, renderstate::vbuf, renderstate::vquery, renderstate::vslot, and geombatch::vslot.
Referenced by renderalphageom(), rendergeom(), rendergeommultipass(), and renderva().
void renderblendbrush (uint tex, float x, float y, float w, float h)
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), gle::color(), drawvatris(), f(), GL_ONE, vec::hexcolor(), LOCALPARAMF, vtxarray::next, OCCLUDE_GEOM, vertex::pos, SETSHADER, vtxarray::vbuf, and xtravertsva.
void renderdepthobstacles (const vec & bbmin, const vec & bbmax, float scale, float * ranges, int numranges)
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), drawvatris(), LOCALPARAMF, loopi(), vtxarray::next, OCCLUDE_GEOM, vertex::pos, SETSHADER, vtxarray::vbuf, and xtravertsva.
Referenced by depthfxtexture::dorender().
void renderfoggedvas (renderstate & cur, bool doquery = false)
References changevbuf(), drawvatris(), vtxarray::edata, enablevattribs(), endvaquery, fading, lookupshaderbyname(), loopv, RENDERPASS_FOG, Shader::set(), vector< T, MINSIZE >::setsize(), Shader::setvariant(), startvaquery, vtxarray::tris, renderstate::vattribs, vtxarray::vbuf, renderstate::vbuf, and vtris.
Referenced by rendergeom().
void rendergeom (float causticspass, bool fogpass)
References renderstate::blending, camera1, checkquery(), cleanupgeom(), renderstate::colormask, cur, renderstate::depthmask, disablevattribs(), disablevbuf(), disablevquery(), drawtex, fading, finddynlights(), FIRSTVA, flipqueries(), glaring, insideva(), ishiddencube(), vector< T, MINSIZE >::length(), inexor::rpc::min(), newquery(), vtxarray::next, NEXTVA, physent::o, OCCLUDE_BB, OCCLUDE_GEOM, OCCLUDE_NOTHING, OCCLUDE_PARENT, oqfrags, popshadowmap(), pushshadowmap(), pvsoccluded(), reflecting, reflectz, refractfog, refracting, renderbatches(), renderfoggedvas(), rendergeommultipass(), RENDERPASS_CAUSTICS, RENDERPASS_LIGHTMAP, RENDERPASS_LIGHTMAP_BLEND, RENDERPASS_Z, renderquery(), rendershadowmap(), renderva(), resetbatches(), setupcaustics(), setupgeom(), shadowmap, renderstate::texgendim, renderstate::vattribs, renderstate::vbuf, VFC_FOGGED, renderstate::vquery, vtris, and vverts.
Referenced by drawcubemap(), drawglare(), drawminimap(), gl_drawframe(), and renderreflectedgeom().
static void rendergeommultipass (renderstate & cur, int pass, bool fogpass) static
References disablevbuf(), enablevattribs(), FIRSTVA, ishiddencube(), vector< T, MINSIZE >::length(), NEXTVA, OCCLUDE_GEOM, reflecting, reflectz, refractfog, refracting, renderbatches(), renderva(), renderstate::texgendim, renderstate::vattribs, renderstate::vbuf, and VFC_FOGGED.
Referenced by rendergeom().
void rendermapmodel (extentity & e)
References ANIM_LOOP, ANIM_MAPMODEL, entities::animatemapmodel(), entity::attr1, entity::attr2, EF_ANIM, extentity::flags, getmminfo(), extentity::light, MDL_CULL_DIST, MDL_CULL_VFC, MDL_DYNLIGHT, mapmodelinfo::name, entity::o, and rendermodel().
Referenced by rendermapmodels(), and renderreflectedmapmodels().
void rendermapmodels ()
References camera1, drawbb(), EF_RENDER, endbb(), endmodelbatches(), endmodelquery(), endquery, entities::ents, findvisiblemms(), extentity::flags, entities::getents(), insideoe(), loopv, newquery(), octaentities::next, physent::o, oqfrags, rendermapmodel(), startbb(), startmodelbatches(), startmodelquery(), startquery, ivec::sub(), and visiblemms.
Referenced by drawcubemap(), drawminimap(), and gl_drawframe().
void renderoutline ()
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), gle::color(), disablepolygonoffset(), drawvatris(), enablepolygonoffset(), vec::hexcolor(), vtxarray::next, notextureshader, OCCLUDE_BB, OCCLUDE_GEOM, outlinecolour, vertex::pos, Shader::set(), vtxarray::vbuf, and xtravertsva.
Referenced by gl_drawframe().
static void renderquery (renderstate & cur, occludequery * query, vtxarray * va, bool full = true) static
References ivec::add(), vtxarray::bbmax, vtxarray::bbmin, drawbb(), enablevquery(), endquery, vtxarray::geommax, vtxarray::geommin, startquery, ivec::sub(), and renderstate::vquery.
Referenced by rendergeom().
void renderreflectedgeom (bool causticspass, bool fogpass)
References findreflectedvas(), reflecting, rendergeom(), and varoot.
Referenced by drawreflection().
void renderreflectedmapmodels ()
References EF_NOVIS, EF_RENDER, endmodelbatches(), entities::ents, extentity::flags, entities::getents(), isfoggedcube(), loopv, octaentities::mapmodels, reflectdist, reflecting, reflectz, refracting, rendermapmodel(), octaentities::rnext, vtxarray::rnext, startmodelbatches(), and visiblemms.
Referenced by drawglare(), and drawreflection().
void renderreflectedskyvas (vector< vtxarray * > & vas, int prevvfc = VFC_PART_VISIBLE)
References vtxarray::children, vtxarray::curvfc, vtxarray::explicitsky, ishiddencube(), vector< T, MINSIZE >::length(), loopv, vtxarray::o, OCCLUDE_BB, vtxarray::occluded, PVS_FULL_VISIBLE, reflectz, renderskyva(), vtxarray::size, vtxarray::sky, updateskystats(), VFC_FULL_VISIBLE, and VFC_NOT_VISIBLE.
Referenced by rendersky().
void rendershadowmapreceivers ()
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), drawvatris(), GL_ONE, glBlendEquation_, isshadowmapreceiver(), vtxarray::next, vertex::pos, SETSHADER, vtxarray::vbuf, VFC_FOGGED, and xtravertsva.
Referenced by shadowmaptexture::dorender().
bool rendersky (bool explicitonly)
References gle::clearebo(), gle::clearvbo(), vtxarray::next, OCCLUDE_BB, reflecting, renderedexplicitsky, renderedskyclip, renderedskyfaces, renderreflectedskyvas(), renderskyva(), updateskystats(), and varoot.
Referenced by drawskylimits(), and drawskyoutline().
void renderskyva (vtxarray * va, bool explicitonly = false)
References gle::bindebo(), gle::bindvbo(), drawvatris(), vtxarray::explicitsky, vertex::pos, vtxarray::sky, vtxarray::skybuf, vtxarray::skydata, vtxarray::vbuf, and xtraverts.
Referenced by renderreflectedskyvas(), and rendersky().
void renderva (renderstate & cur, vtxarray * va, int pass = RENDERPASS_LIGHTMAP, bool fogpass = false, bool doquery = false)
References vector< T, MINSIZE >::add(), renderstate::alphaing, renderstate::blending, vtxarray::blends, calcdynlightmask(), changevbuf(), vtxarray::curvfc, drawtex, drawvatris(), vtxarray::dynlightmask, vtxarray::edata, endvaquery, vtxarray::eslist, vtxarray::geommax, glaring, isshadowmapreceiver(), vector< T, MINSIZE >::length(), mergetexs(), reflectz, refractfog, renderbatches(), RENDERPASS_CAUSTICS, RENDERPASS_FOG, RENDERPASS_LIGHTMAP, RENDERPASS_LIGHTMAP_BLEND, RENDERPASS_Z, renderzpass(), vtxarray::shadowed, startvaquery, vtxarray::texs, vtxarray::tris, vtxarray::vbuf, renderstate::vbuf, vtxarray::verts, VFC_FOGGED, vverts, and xtravertsva.
Referenced by renderalphageom(), rendergeom(), and rendergeommultipass().
void renderzpass (renderstate & cur, vtxarray * va)
References vtxarray::alphabacktris, vtxarray::alphafronttris, renderstate::alphaing, vtxarray::blends, vtxarray::blendtris, changevbuf(), renderstate::colormask, renderstate::depthmask, disablevquery(), drawvatris(), vtxarray::edata, enablevattribs(), nocolorshader, RENDERPASS_Z, Shader::set(), vtxarray::texs, vtxarray::tris, renderstate::vattribs, vtxarray::vbuf, renderstate::vbuf, vtxarray::verts, renderstate::vquery, and xtravertsva.
Referenced by renderva().
static void reportinvalidtextslot (Slot * slot) static
Reports a slot with an invalid texture definition.
Keeps track of what slots already have been reported in order to show an error only once.
References Slot::index, Log, loopv, Slot::Tex::name, inexor::util::log_manager::std, Slot::sts, anonymous_namespace{utilTest.cpp}::t(), TEX_DIFFUSE, and Slot::Tex::type.
Referenced by changebatchtmus().
static void resetbatches () static
References firstbatch, numbatches, and vector< T, MINSIZE >::setsize().
Referenced by renderalphageom(), renderbatches(), and rendergeom().
void resetinvalidtextslots ()
Resets the set of slots that an error has been reported for.
Referenced by clearslots().
void resetqueries ()
References loopi(), MAXQUERYFRAMES, and queryframe::reset().
Referenced by allchanged().
void restorevfcP ()
References calcvfcD().
Referenced by drawreflections().
void savevfcP ()
Referenced by drawreflections().
static void setupbb () static
References bbebo, bbvbo, gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), GENFACEVERTS, glBufferData_, glGenBuffers_, loopi(), and sphere::verts.
Referenced by startbb().
void setupcaustics (float blend)
References f(), glActiveTexture_, lastmillis, loadcaustics(), LOCALPARAM, LOCALPARAMF, loopi(), vec::mul(), NUMCAUSTICS, SETSHADER, and anonymous_namespace{utilTest.cpp}::t().
Referenced by rendergeom().
void setupgeom (renderstate & cur)
References ambientcolor, modelpreview::camera, camera1, f(), glActiveTexture_, GLOBALPARAM, GLOBALPARAMF, lastmillis, and physent::o.
Referenced by renderalphageom(), and rendergeom().
void setvfcP (float z, const vec & bbmin, const vec & bbmax)
References vec4::add(), calcvfcD(), camprojmatrix, fog, loopi(), plane::normalize(), plane::reflectz(), matrix4::roww(), matrix4::rowx(), matrix4::rowy(), matrix4::rowz(), vec4::sub(), and vfcDfog.
Referenced by drawreflections(), and visiblecubes().
void sortvisiblevas ()
References loopi(), vtxarray::next, VASORTSIZE, and visibleva.
Referenced by visiblecubes().
void startbb (bool mask)
References bbebo, bbvbo, gle::bindebo(), gle::bindvbo(), SETSHADER, and setupbb().
Referenced by enablecullmodelquery(), enablevquery(), and rendermapmodels().
SVARP (causticdir , "texture/inexor/material/water/caustic")
static void updateskystats (vtxarray * va) inline static
References camera1, vtxarray::explicitsky, inexor::rpc::min(), physent::o, renderedexplicitsky, renderedskyclip, renderedskyfaces, vtxarray::sky, vtxarray::skyclip, and vtxarray::skyfaces.
Referenced by renderreflectedskyvas(), and rendersky().
float vadist (vtxarray * va, const vec & p)
References vtxarray::bbmax, vtxarray::bbmin, and vec::dist_to_bb().
Referenced by addvisibleva(), and findreflectedvas().
VAR (oqfrags , 0 , 8 , 64)
VAR (oqwait , 0 , 1 , 1)
VAR (oqmm , 0 , 4 , 8)
VAR (outline , 0 , 0 , 1)
VAR (dtoutline , 0 , 1 , 1)
VAR (oqdist , 0 , 256 , 1024)
VAR (zpass , 0 , 1 , 1)
VAR (glowpass , 0 , 1 , 1)
VAR (envpass , 0 , 1 , 1)
VAR (batchgeom , 0 , 1 , 1)
VAR (oqgeom , 0 , 1 , 1)
VARFP (caustics , 0 , 1 , 1 , loadcaustics())
VARR (causticscale , 0 , 50 , 10000)
VARR (causticmillis , 0 , 75 , 1000)
void visiblecubes (bool cull)
References vtxarray::curvfc, vtxarray::distance, findvisiblevas(), loopv, vtxarray::next, OCCLUDE_GEOM, OCCLUDE_NOTHING, vtxarray::occluded, vtxarray::query, setvfcP(), sortvisiblevas(), vtxarray::texs, valist, varoot, VFC_FULL_VISIBLE, vfcDfar, vfcDfog, vfcDnear, and visibleva.
Referenced by drawcubemap(), drawminimap(), and gl_drawframe().
Variable Documentation
GLuint bbebo = 0 static
Referenced by cleanupbb(), setupbb(), and startbb().
GLuint bbvbo = 0 static
Referenced by cleanupbb(), setupbb(), and startbb().
Texture* caustictex[NUMCAUSTICS] = { nullptr } static
int firstbatch = -1 static
Referenced by mergetexs(), renderbatches(), and resetbatches().
uint flipquery = 0 static
Referenced by flipqueries(), getnumqueries(), and newquery().
vector<vtxarray *> foggedvas
vector<geombatch> geombatches static
octaentities ** lastvisiblemms static
int numbatches = 0 static
Referenced by mergetexs(), and resetbatches().
SharedVar<int> octaentsize
Referenced by findents(), and modifyoctaent().
plane oldvfcP[5]
vtxarray* prevskyva = nullptr static
queryframe queryframes[MAXQUERYFRAMES] static
vtxarray* reflectedva
Referenced by findreflectedvas(), and sortmaterials().
int renderedexplicitsky = 0
Referenced by rendersky(), and updateskystats().
int renderedsky = 0
int renderedskyclip = INT_MAX
Referenced by drawskybox(), rendersky(), and updateskystats().
int renderedskyfaces = 0
Referenced by drawskybox(), rendersky(), and updateskystats().
std::unordered_set<int> reportedinvalidtextsloterrs static
The slots that an error message has been shown for.
This is used to prevent repeating the same error over and over.
vtxarray* vasort[VASORTSIZE] static
float vfcDfar[5]
Referenced by calcvfcD(), isfoggedcube(), ishiddencube(), isvisiblecube(), and visiblecubes().
float vfcDfog
Referenced by isfoggedcube(), isfoggedsphere(), isvisiblecube(), isvisiblesphere(), setvfcP(), and visiblecubes().
float vfcDnear[5]
Referenced by calcvfcD(), isfoggedcube(), isvisiblecube(), and visiblecubes().
plane vfcP[5]
octaentities* visiblemms static
Referenced by findvisiblemms(), rendermapmodels(), and renderreflectedmapmodels().
vtxarray* visibleva
Referenced by drawskybox(), generategrass(), octarender(), queryreflections(), sortmaterials(), sortvisiblevas(), and visiblecubes().