Inexor: inexor/engine/renderbackground.hpp File Reference
renderbackground.hpp File Reference
#include "SDL_opengl.h"
Functions
void renderbackground (const char *caption=nullptr, Texture *mapshot=nullptr, const char *mapname=nullptr, const char *mapinfo=nullptr, bool restore=false, bool force=false)
render background texture for the mainmenu and the loading screen.
void renderprogress (float bar, const char *text, GLuint tex=0, bool background=false)
render progress bar and map screenshot
Variables
float loadprogress
Function Documentation
void renderbackground (const char * caption = nullptr, Texture * mapshot = nullptr, const char * mapname = nullptr, const char * mapinfo = nullptr, bool restore = false, bool force = false)
render background texture for the mainmenu and the loading screen.
References bgquad(), copystring(), hmap::d, decals, DELETEA, DIR_UI, draw_text(), f(), flushhudmatrix(), FONTH, forceaspect, getbackgroundres(), inexor::filesystem::getmediapath(), gettextres(), hudmatrix, hudshader, Texture::id, inbetweenframes, lastmillis, loopi(), mainmenu, inexor::rpc::max(), inexor::rpc::min(), newstring(), notexture, matrix4::ortho(), pophudmatrix(), pushhudmatrix(), renderedframe, resethudmatrix(), matrix4::scale(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, Shader::set(), inexor::sound::stopsounds(), inexor::rendering::screen::ScreenManager::swapbuffers(), text_bounds(), text_width(), textureload(), and matrix4::translate().
Referenced by calclight(), genpvs(), gl_drawmainmenu(), load_world(), main(), patchlight(), resetgl(), and restorebackground().
void renderprogress (float bar, const char * text, GLuint tex = 0, bool background = false)
render progress bar and map screenshot
make sure our connection doesn't time out while loading maps etc.
References gle::begin(), bgquad(), clientkeepalive(), DIR_UI, draw_text(), drawtex, gle::end(), f(), flushhudmatrix(), FONTH, forceaspect, getbackgroundres(), inexor::filesystem::getmediapath(), gettextres(), hudmatrix, hudshader, Texture::id, inbetweenframes, inexor::rpc::max(), inexor::rpc::min(), matrix4::ortho(), pophudmatrix(), pushhudmatrix(), renderedframe, resethudmatrix(), restorebackground(), matrix4::scale(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, Shader::set(), inexor::rendering::screen::ScreenManager::swapbuffers(), text_width(), textureload(), and matrix4::translate().
Referenced by allchanged(), clearlightmaps(), compactvslots(), drawminimap(), genenvmaps(), genmerges(), genpvs(), invalidatemerges(), inexor::sound::soundsample::load(), load_world(), loadmodel(), patchlight(), reloadshaders(), remip(), resolverwait(), save_world(), savec(), seedparticles(), shader(), show_addnormals_progress(), show_calclight_progress(), show_genpvs_progress(), and texturedata().
Variable Documentation
float loadprogress
Referenced by flushpreloadedmodels(), loadmodel(), octarender(), precachetextures(), preloadusedmapmodels(), reloadtextures(), shader(), texturedata(), and updateva().