Inexor: inexor/engine/rendergl.hpp File Reference
rendergl.hpp File Reference
#include "SDL_opengl.h"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/geom.hpp"
Namespaces
modelpreview
Enumerations
enum { DRAWTEX_NONE = 0, DRAWTEX_ENVMAP, DRAWTEX_MINIMAP, DRAWTEX_MODELPREVIEW }
Functions
void disablezoom ()
vec calcavatarpos (const vec &pos, float dist)
vec calcmodelpreviewpos (const vec &radius, float &yaw)
void damageblend (int n)
void damagecompass (int n, const vec &loc)
void bindminimap ()
void bind_items_texture ()
Binds the specific item icon map and returns true on success.
void bind_bomb_items_texture ()
void resethudmatrix ()
void pushhudmatrix ()
void flushhudmatrix (bool flushparams=true)
void pophudmatrix (bool flush=true, bool flushparams=true)
void pushhudscale (float sx, float sy=0)
void pushhudtranslate (float tx, float ty, float sx=0, float sy=0)
void gl_checkextensions ()
void gl_init (int depth, int fsaa)
void gl_resize ()
void cef_resize (int width, int height)
void cleangl ()
void rendergame (bool mainpass=false)
void invalidatepostfx ()
void gl_drawframe ()
void gl_drawmainmenu ()
void gl_drawhud ()
void drawminimap ()
void drawtextures ()
void enablepolygonoffset (GLenum type)
void disablepolygonoffset (GLenum type)
void calcspherescissor (const vec &center, float size, float &sx1, float &sy1, float &sx2, float &sy2)
int pushscissor (float sx1, float sy1, float sx2, float sy2)
void popscissor ()
void recomputecamera ()
void screenquad ()
void screenquad (float sw, float sh)
void screenquadflipped (float sw, float sh)
void screenquad (float sw, float sh, float sw2, float sh2)
void screenquadoffset (float x, float y, float w, float h)
void screenquadoffset (float x, float y, float w, float h, float x2, float y2, float w2, float h2)
void hudquad (float x, float y, float w, float h, float tx=0, float ty=0, float tw=1, float th=1)
void setfogcolor (const vec &v)
void zerofogcolor ()
void resetfogcolor ()
void setfogdist (float start, float end)
void clearfogdist ()
void resetfogdist ()
void writecrosshairs (stream *f)
void modelpreview::start (int x, int y, int w, int h, bool background)
void modelpreview::end ()
Variables
physent * camera1
special ent that acts as camera, same object as player1 in FPS mode
vec worldpos
vec camdir
vec camright
vec camup
int xtraverts
int xtravertsva
vec minimapcenter
vec minimapradius
vec minimapscale
matrix4 hudmatrix
bool hasVAO
bool hasFBO
bool hasAFBO
bool hasDS
bool hasTF
bool hasTRG
bool hasTSW
bool hasS3TC
bool hasFXT1
bool hasAF
bool hasFBB
bool hasUBO
bool hasMBR
int hasstencil
SharedVar< int > glversion
SharedVar< int > glslversion
SharedVar< float > forceaspect
float curfov
float fovy
float aspect
int drawtex
bool renderedgame
const matrix4 viewmatrix
matrix4 cammatrix
matrix4 projmatrix
matrix4 camprojmatrix
matrix4 invcammatrix
matrix4 invcamprojmatrix
bvec fogcolor
vec curfogcolor
SharedVar< int > fog
float curfogstart
float curfogend
Enumeration Type Documentation
anonymous enum
Enumerator
DRAWTEX_NONE
DRAWTEX_ENVMAP
DRAWTEX_MINIMAP
DRAWTEX_MODELPREVIEW
Function Documentation
void bind_bomb_items_texture ()
References DIR_UI, inexor::filesystem::getmediapath(), Texture::id, and textureload().
Referenced by game::bombclientmode::drawicon().
void bind_items_texture ()
Binds the specific item icon map and returns true on success.
References DIR_UI, inexor::filesystem::getmediapath(), Texture::id, and textureload().
Referenced by game::drawicon().
void bindminimap ()
References minimaptex.
Referenced by game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and game::captureclientmode::drawhud().
vec calcavatarpos (const vec & pos, float dist)
References vec::add(), aspect, camera1, cammatrix, curavatarfov, dir, farplane, invcamprojmatrix, physent::o, matrix4::perspectivetransform(), RAD, vec::rescale(), vec::sub(), matrix4::transform(), and worldpos.
Referenced by game::drawhudmodel().
vec calcmodelpreviewpos (const vec & radius, float & yaw)
References aspect, camera1, f(), fovy, lastmillis, vec::magnitude(), vec::magnitude2(), inexor::rpc::max(), physent::pitch, RAD, and vec::rotate_around_x().
Referenced by gui::modelpreview(), previewprefab(), and game::renderplayerpreview().
void calcspherescissor (const vec & center, float size, float & sx1, float & sy1, float & sx2, float & sy2)
References aspect, cammatrix, CHECKPLANE, f(), fovy, RAD, reflecting, reflectz, matrix4::transform(), and worldpos.
Referenced by depthfxtexture::addscissorbox().
void cef_resize (int width, int height)
void cleangl ()
void clearfogdist ()
References setfogdist().
Referenced by modelpreview::start().
void damageblend (int n)
References damageblendmillis, lastmillis, inexor::rendering::screen::ScreenManager::minimized, and inexor::rendering::screen::screen_manager.
Referenced by game::damaged(), and game::hit().
void damagecompass (int n, const vec & loc)
References camera1, damagedirs, dir, f(), vec::magnitude(), inexor::rpc::max(), inexor::rendering::screen::ScreenManager::minimized, physent::o, inexor::rendering::screen::screen_manager, vec::sub(), vectoyawpitch(), and physent::yaw.
Referenced by game::damaged(), and game::hit().
void disablepolygonoffset (GLenum type)
References nooffsetmatrix, projmatrix, and setcamprojmatrix().
Referenced by decalrenderer::cleanuprenderstate(), blobrenderer::cleanuprenderstate(), drawskyoutline(), animmodel::endrender(), rendereditcursor(), rendermatgrid(), renderoutline(), and renderprefab().
void disablezoom ()
References broadcastfov(), and zoomprogress.
Referenced by game::deathstate(), game::edittoggled(), game::parsemessages(), game::startgame(), and game::timeupdate().
void drawminimap ()
References matrix4::a, vec::add(), camera1, clearminimap(), clipminimap(), drawreflections(), drawtex, DRAWTEX_MINIMAP, ENT_CAMERA, f(), gbatches, vtxarray::geommax, vtxarray::geommin, glde, hwtexsize, loopi(), loopk, loopv, inexor::rpc::max(), inexor::rpc::min(), minimapcenter, minimapcolor, minimapradius, minimapscale, minimaptex, vec::mul(), vec4::mul(), game::needminimap(), physent::o, modelpreview::oldcamera, matrix4::ortho(), physent::pitch, player, projmatrix, queryreflections(), renderalphageom(), renderedframe, rendergeom(), rendermapmodels(), rendermaterials(), renderprogress(), renderwater(), physent::reset(), physent::roll, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, setcamprojmatrix(), setnofog(), setuptexparameters(), setviewcell(), vec::sub(), bvec::tocolor(), physent::type, valist, visiblecubes(), worldsize, xtraverts, xtravertsva, and physent::yaw.
Referenced by drawtextures().
void drawtextures ()
References deferdrawtextures, drawminimap(), genenvmaps(), inexor::rendering::screen::ScreenManager::minimized, and inexor::rendering::screen::screen_manager.
Referenced by allchanged(), and gl_drawframe().
void enablepolygonoffset (GLenum type)
References matrix4::c, ai::clipped(), matrix4::d, noclipmatrix, nooffsetmatrix, projmatrix, reflectz, and setcamprojmatrix().
Referenced by drawskyoutline(), animmodel::render(), rendereditcursor(), rendermatgrid(), renderoutline(), renderprefab(), decalrenderer::setuprenderstate(), and blobrenderer::setuprenderstate().
void flushhudmatrix (bool flushparams = true)
References Shader::flushparams(), GLOBALPARAM, hudmatrix, and Shader::lastshader.
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), game::drawhudicons(), game::gameplayhud(), gl_drawhud(), pophudmatrix(), pushhudscale(), pushhudtranslate(), renderbackground(), renderprogress(), and rendertexturepanel().
void gl_checkextensions ()
References blurdepthfx, depthfxsize, fatal(), getprocaddress(), glActiveTexture_, glAttachShader_, glBeginQuery_, glBindAttribLocation_, glBindBuffer_, glBindBufferBase_, glBindBufferRange_, glBindFramebuffer_, glBindRenderbuffer_, glBindVertexArray_, glBlendColor_, glBlendEquation_, glBlendEquationSeparate_, glBlendFuncSeparate_, glBlitFramebuffer_, glBufferData_, glBufferSubData_, glCheckFramebufferStatus_, glCompileShader_, glCompressedTexImage1D_, glCompressedTexImage2D_, glCompressedTexImage3D_, glCompressedTexSubImage1D_, glCompressedTexSubImage2D_, glCompressedTexSubImage3D_, glCopyTexSubImage3D_, glCreateProgram_, glCreateShader_, glDeleteBuffers_, glDeleteFramebuffers_, glDeleteProgram_, glDeleteQueries_, glDeleteRenderbuffers_, glDeleteShader_, glDeleteVertexArrays_, glDisableVertexAttribArray_, glDrawBuffers_, glDrawRangeElements_, glEnableVertexAttribArray_, glEndQuery_, glFlushMappedBufferRange_, glFramebufferRenderbuffer_, glFramebufferTexture2D_, glGenBuffers_, glGenerateMipmap_, glGenFramebuffers_, glGenQueries_, glGenRenderbuffers_, glGenVertexArrays_, glGetActiveUniform_, glGetActiveUniformBlockiv_, glGetActiveUniformsiv_, glGetBufferSubData_, glGetCompressedTexImage_, glGetProgramInfoLog_, glGetProgramiv_, glGetQueryiv_, glGetQueryObjectiv_, glGetQueryObjectuiv_, glGetShaderInfoLog_, glGetShaderiv_, glGetUniformBlockIndex_, glGetUniformIndices_, glGetUniformLocation_, glIsVertexArray_, glLinkProgram_, glMapBuffer_, glMapBufferRange_, glMultiDrawArrays_, glMultiDrawElements_, glRenderbufferStorage_, glShaderSource_, glslversion, glStencilFuncSeparate_, glStencilMaskSeparate_, glStencilOpSeparate_, glTexImage3D_, glTexSubImage3D_, glUniform1f_, glUniform1fv_, glUniform1i_, glUniform1iv_, glUniform2f_, glUniform2fv_, glUniform2i_, glUniform2iv_, glUniform3f_, glUniform3fv_, glUniform3i_, glUniform3iv_, glUniform4f_, glUniform4fv_, glUniform4i_, glUniform4iv_, glUniformBlockBinding_, glUniformMatrix2fv_, glUniformMatrix2x3fv_, glUniformMatrix2x4fv_, glUniformMatrix3fv_, glUniformMatrix3x2fv_, glUniformMatrix3x4fv_, glUniformMatrix4fv_, glUniformMatrix4x2fv_, glUniformMatrix4x3fv_, glUnmapBuffer_, glUseProgram_, glversion, glVertexAttrib1f_, glVertexAttrib1fv_, glVertexAttrib1s_, glVertexAttrib1sv_, glVertexAttrib2f_, glVertexAttrib2fv_, glVertexAttrib2s_, glVertexAttrib2sv_, glVertexAttrib3f_, glVertexAttrib3fv_, glVertexAttrib3s_, glVertexAttrib3sv_, glVertexAttrib4bv_, glVertexAttrib4f_, glVertexAttrib4fv_, glVertexAttrib4iv_, glVertexAttrib4Nbv_, glVertexAttrib4Niv_, glVertexAttrib4Nub_, glVertexAttrib4Nubv_, glVertexAttrib4Nuiv_, glVertexAttrib4Nusv_, glVertexAttrib4s_, glVertexAttrib4sv_, glVertexAttrib4ubv_, glVertexAttrib4uiv_, glVertexAttrib4usv_, glVertexAttribPointer_, hasAF, hasAFBO, hasDS, hasext(), hasFBB, hasFBO, hasFXT1, hasMBR, hasS3TC, hasTF, hasTRG, hasTSW, hasUBO, hasVAO, hwcubetexsize, hwmaxaniso, hwtexsize, intel_mapbufferrange_bug, Log, inexor::rpc::max(), MAXDYNLIGHTS, reservevpparams, rtsharefb, shadowmap, inexor::util::log_manager::std, usetexcompress, and waterfallrefract.
Referenced by main().
void gl_drawframe ()
References addglare(), addmotionblur(), aspect, camera1, caustics, curfov, deferdrawtextures, drawdepthfxtex(), drawfogoverlay(), drawglaretex(), drawreflections(), drawskybox(), drawtextures(), editmode, farplane, findsurface(), forceaspect, fovy, g3d_render(), gbatches, generategrass(), gl_drawhud(), gl_rendercef(), glde, hasstencil, hudshader, isliquid, lastmillis, limitsky(), lookupmaterial(), MAT_AIR, MAT_WATER, MATF_INDEX, MATF_VOLUME, inexor::rpc::min(), physent::o, outline, matrix4::perspective(), PI, projmatrix, queryreflections(), RAD, renderalphageom(), renderavatar(), renderdecals(), renderedgame, rendergame(), rendergeom(), rendergrass(), rendermapmodels(), rendermaterials(), renderoutline(), renderparticles(), renderpostfx(), renderwater(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, Shader::set(), setcamprojmatrix(), setfog(), updatedynlights(), visiblecubes(), WATER_OFFSET, worldsize, xtraverts, and xtravertsva.
Referenced by main().
void gl_drawhud ()
References game::abovegameplayhud(), allocnodes, allocva, debugparticles(), DELETEA, draw_text(), draw_textf(), drawcrosshair(), drawdamagecompass(), drawdamagescreen(), editmode, executestr(), flushhudmatrix(), FONTH, forceaspect, g3d_limitscale(), game::gameplayhud(), gbatches, getfps(), getmaterialdesc(), getnumqueries(), getnumviewcells(), gettextres(), gettimestr(), glde, hudmatrix, hudshader, identexists(), lightmaps, loopi(), mainmenu, inexor::rpc::max(), inexor::rpc::min(), matrix4::ortho(), pophudmatrix(), pushhudmatrix(), renderblendbrush(), rendercommand(), renderconsole(), rendereditcursor(), rendertexturepanel(), resethudmatrix(), rplanes, matrix4::scale(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, selchildcount, selchildmat, Shader::set(), showmat, text_bounds(), totalmillis, viewdepthfxtex(), viewglaretex(), viewshadowmap(), vtris, vverts, wtris, wverts, xtraverts, and xtravertsva.
void gl_drawmainmenu ()
References g3d_render(), gbatches, gl_drawhud(), gl_rendercef(), glde, renderbackground(), renderpostfx(), xtraverts, and xtravertsva.
Referenced by main().
void gl_init (int depth, int fsaa)
References gl_resize(), gle::setup(), setupshaders(), and setuptexcompress().
Referenced by main(), and resetgl().
void gl_resize ()
void hudquad (float x, float y, float w, float h, float tx = 0, float ty = 0, float tw = 1, float th = 1)
void invalidatepostfx ()
References dopostfx.
Referenced by allchanged(), and commitchanges().
void pophudmatrix (bool flush = true, bool flushparams = true)
References flushhudmatrix(), hudmatrix, hudmatrixpos, and hudmatrixstack.
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), game::drawhudicons(), game::gameplayhud(), gl_drawhud(), renderbackground(), renderprogress(), and rendertexturepanel().
void popscissor ()
References oldscissor, and scissoring.
void pushhudmatrix ()
References hudmatrix, hudmatrixpos, and hudmatrixstack.
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), game::drawhudicons(), game::gameplayhud(), gl_drawhud(), pushhudscale(), pushhudtranslate(), renderbackground(), renderprogress(), and rendertexturepanel().
void pushhudscale (float sx, float sy = 0)
References flushhudmatrix(), hudmatrix, pushhudmatrix(), and matrix4::scale().
void pushhudtranslate (float tx, float ty, float sx = 0, float sy = 0)
References flushhudmatrix(), hudmatrix, pushhudmatrix(), matrix4::scale(), and matrix4::translate().
int pushscissor (float sx1, float sy1, float sx2, float sy2)
References f(), inexor::rpc::max(), inexor::rpc::min(), oldscissor, and scissoring.
void recomputecamera ()
References matrix3::a, physent::aboveeye, vec::add(), matrix3::b, matrix3::c, camera1, Texture::clamp, game::collidecamera(), computezoom(), game::detachcamera(), detachedcamera, dir, vec::dist(), ENT_CAMERA, physent::eyeheight, f(), matrix3::identity(), physent::move, movecamera(), vec::neg(), physent::o, orient, physent::pitch, player, RAD, physent::radius, physent::reset(), physent::roll, matrix3::rotate_around_x(), matrix3::rotate_around_y(), matrix3::rotate_around_z(), game::setupcamera(), setviewcell(), thirdperson, physent::type, physent::xradius, physent::yaw, and physent::yradius.
Referenced by main().
void rendergame (bool mainpass = false)
References physent::abovehead(), game::bestplayers, game::bestteams, game::cmode, game::colorname(), concatstring(), copystring(), CS_DEAD, CS_SPAWNING, CS_SPECTATOR, hmap::d, defformatstring, endmodelbatches(), f(), game::followingplayer(), game::getbestplayers(), game::getbestteams(), game::getplayermodelinfo(), fpsent::info, game::intermission, game::clientmode::isinvisible(), isteam, isthirdperson(), lastmillis, fpsent::lastupdate, fpsent::lifesequence, loopv, m_teammode, inexor::rpc::max(), fpsstate::maxhealth, inexor::rpc::min(), PART_TEXT, particle_text(), game::player1, game::players, game::ragdolls, ai::render(), game::renderbouncers(), renderedgame, entities::renderentities(), game::clientmode::rendergame(), game::rendergame(), game::rendermovables(), game::renderplayer(), game::renderprojectiles(), shadowmapping, vector< T, MINSIZE >::shrink(), startmodelbatches(), physent::state, fpsent::team, and game::teamskins.
Referenced by shadowmaptexture::dorender(), drawglare(), drawreflection(), gl_drawframe(), and rendergame().
void resetfogcolor ()
References curfogcolor, and setfogcolor().
Referenced by modelpreview::end(), popfogcolor(), pushfogcolor(), decalrenderer::render(), renderalphageom(), rendermaterials(), renderparticles(), and resetfog().
void resetfogdist ()
References curfogend, curfogstart, and setfogdist().
Referenced by modelpreview::end(), popfogdist(), pushfogdist(), and resetfog().
void resethudmatrix ()
References GLOBALPARAM, hudmatrix, and hudmatrixpos.
Referenced by recorder::drawhud(), gl_drawhud(), gl_rendercef(), renderbackground(), renderprogress(), and gui::start().
void screenquad ()
References gle::bindvbo(), gle::clearvbo(), screenquadvbo, and setupscreenquad().
Referenced by addglare(), addmotionblur(), drawfogoverlay(), recorder::readbuffer(), renderpostfx(), screenquad(), screenquadflipped(), and screenquadoffset().
void screenquad (float sw, float sh)
void screenquad (float sw, float sh, float sw2, float sh2)
References screenquad(), and setscreentexcoord().
void screenquadflipped (float sw, float sh)
References screenquad(), and setscreentexcoord().
Referenced by recorder::readbuffer().
void screenquadoffset (float x, float y, float w, float h)
References screenquad(), and setscreentexcoord().
void screenquadoffset (float x, float y, float w, float h, float x2, float y2, float w2, float h2)
References screenquad(), and setscreentexcoord().
void setfogcolor (const vec & v)
References fogcolor, and GLOBALPARAM.
Referenced by changeslottmus(), resetfogcolor(), and zerofogcolor().
void setfogdist (float start, float end)
References GLOBALPARAMF.
Referenced by clearfogdist(), and resetfogdist().
void writecrosshairs (stream * f)
References crosshairs, escapestring(), loopi(), MAXCROSSHAIRS, Texture::name, notexture, path(), and stream::printf().
Referenced by writecfg().
void zerofogcolor ()
References setfogcolor().
Referenced by decalrenderer::render(), rendermaterials(), renderparticles(), and modelpreview::start().
Variable Documentation
float aspect
Referenced by gui::adjustscale(), calcavatarpos(), calcmodelpreviewpos(), calcspherescissor(), consolebox(), drawreflection(), modelpreview::end(), gl_drawframe(), matrix4::perspective(), renderavatar(), and modelpreview::start().
vec camdir
Referenced by flarerenderer::addflare(), gui::end(), g3d_key(), flarerenderer::makelightflares(), rendereditcursor(), meterrenderer::renderpart(), textrenderer::renderpart(), and setcammatrix().
physent* camera1
special ent that acts as camera, same object as player1 in FPS mode
Referenced by adddecal(), adddynlight(), flarerenderer::addflare(), addvisibleva(), calcavatarpos(), calcmodelpreviewpos(), calcshadowmapbb(), calcwatersubdiv(), inexor::sound::checkmapsounds(), cullmodel(), damagecompass(), shadowmaptexture::dorender(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), drawcubemap(), game::drawminimap(), drawminimap(), drawreflection(), drawreflections(), drawskybox(), game::drawteammate(), gui::end(), modelpreview::end(), endmodelbatches(), fireballrenderer::finddepthfxranges(), finddynlights(), findreflectedvas(), findvisiblemms(), fixcamerarange(), g3d_addgui(), g3d_key(), g3d_mainmenu(), generategrass(), gengrassquads(), genpos< PT_TAPE >(), gl_drawframe(), game::ctfclientmode::interpflagpos(), isthirdperson(), lockpvs_(), main(), flarerenderer::makelightflares(), menuinfrontofplayer(), mousemove(), newentity(), flarerenderer::newflare(), particle_text(), particle_textcopy(), phystest(), inexor::sound::playsound(), queryreflection(), recomputecamera(), regularshape(), animmodel::part::render(), ai::render(), rendercullmodelquery(), renderentselection(), rendergeom(), renderlightning(), rendermapmodels(), rendermaterials(), fireballrenderer::renderpart(), game::bombclientmode::renderplayersposindicator(), renderwater(), setcammatrix(), setupgeom(), texturegui::show(), sortmaterials(), splash(), gui::start(), modelpreview::start(), testpvs(), inexor::sound::updatechannel(), updateparticles(), and updateskystats().
matrix4 cammatrix
Referenced by calcavatarpos(), calcspherescissor(), drawfogdome(), drawreflection(), drawskybox(), depthfxtexture::eyedepth(), setcammatrix(), and setcamprojmatrix().
matrix4 camprojmatrix
Referenced by depthfxtexture::addscissorvert(), calcscissorbox(), animmodel::part::render(), fireballrenderer::renderpart(), renderprefab(), setcamprojmatrix(), setprojtexmatrix(), setvfcP(), and gui::start().
vec camright
Referenced by genpos(), genrotpos< PT_PART >(), game::hudgunorigin(), flarerenderer::render(), fireballrenderer::renderpart(), meterrenderer::renderpart(), textrenderer::renderpart(), and setcammatrix().
vec camup
Referenced by genpos(), genrotpos< PT_PART >(), game::hudgunorigin(), flarerenderer::render(), fireballrenderer::renderpart(), meterrenderer::renderpart(), textrenderer::renderpart(), and setcammatrix().
vec curfogcolor
Referenced by changeslottmus(), modelpreview::end(), popfogcolor(), pushfogcolor(), resetfog(), resetfogcolor(), setfog(), and setnofog().
float curfogend
Referenced by popfogdist(), pushfogdist(), resetfogdist(), setfog(), and setnofog().
float curfogstart
Referenced by popfogdist(), pushfogdist(), resetfogdist(), setfog(), and setnofog().
float curfov
Referenced by computezoom(), modelpreview::end(), gl_drawframe(), and modelpreview::start().
int drawtex
Referenced by addreflection(), drawcubemap(), drawminimap(), drawreflections(), drawskybox(), modelpreview::end(), queryreflections(), renderclient(), rendergeom(), rendermaterials(), renderprogress(), renderva(), renderwater(), setcammatrix(), sortmaterials(), and modelpreview::start().
SharedVar<int> fog
Referenced by blendfog(), and setvfcP().
bvec fogcolor
Referenced by blendfog(), fogdome::draw(), and setfogcolor().
SharedVar<float> forceaspect
Referenced by gui::adjustscale(), recorder::drawhud(), gl_drawframe(), gl_drawhud(), renderbackground(), and renderprogress().
float fovy
Referenced by calcmodelpreviewpos(), calcspherescissor(), modelpreview::end(), gl_drawframe(), renderentselection(), and modelpreview::start().
SharedVar<int> glslversion
Referenced by compileglslshader(), and gl_checkextensions().
SharedVar<int> glversion
bool hasAF
bool hasAFBO
bool hasDS
bool hasFBB
bool hasFBO
bool hasFXT1
bool hasMBR
bool hasS3TC
int hasstencil
bool hasTF
bool hasTRG
bool hasTSW
bool hasUBO
bool hasVAO
matrix4 hudmatrix
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), recorder::drawhud(), game::drawhudicons(), flushhudmatrix(), game::gameplayhud(), gl_drawhud(), gl_rendercef(), pophudmatrix(), pushhudmatrix(), pushhudscale(), pushhudtranslate(), renderbackground(), renderprogress(), rendertexturepanel(), resethudmatrix(), and gui::start().
matrix4 invcammatrix
Referenced by drawreflection(), and setcamprojmatrix().
matrix4 invcamprojmatrix
Referenced by calcavatarpos(), and setcamprojmatrix().
vec minimapcenter
Referenced by game::drawminimap(), and drawminimap().
vec minimapradius
Referenced by game::calcradarscale(), and drawminimap().
vec minimapscale
Referenced by game::drawminimap(), and drawminimap().
matrix4 projmatrix
Referenced by disablepolygonoffset(), drawcubemap(), drawfogdome(), drawminimap(), drawreflection(), drawskybox(), enablepolygonoffset(), gl_drawframe(), renderavatar(), setcamprojmatrix(), and modelpreview::start().
bool renderedgame
Referenced by canaddparticles(), gl_drawframe(), and rendergame().
const matrix4 viewmatrix
vec worldpos
Referenced by calcavatarpos(), calcspherescissor(), entautoview(), paintblendmap(), game::pointatplayer(), renderblendbrush(), game::selectcrosshair(), setcammatrix(), and game::updateweapons().
int xtraverts
Referenced by boxs(), boxsgrid(), sphere::draw(), fogdome::draw(), draw_char(), draw_text(), drawbb(), drawcubemap(), drawenvboxface(), drawenvoverlay(), drawminimap(), gui::drawskin(), gl_drawframe(), gl_drawhud(), gl_drawmainmenu(), maskreflection(), queryreflection(), gui::rect_(), render2dbox(), renderellipse(), renderentarrow(), renderentattachment(), renderentcone(), renderentring(), renderentselection(), rendermaterials(), rendermatgrid(), renderskyva(), rendertexturepanel(), renderwater(), and text_color().
int xtravertsva
Referenced by drawcubemap(), drawminimap(), gl_drawframe(), gl_drawhud(), gl_drawmainmenu(), vertmodel::vertmesh::render(), decalrenderer::render(), skelmodel::skelmesh::render(), renderblendbrush(), blobrenderer::renderblob(), renderdepthobstacles(), rendergrass(), renderoutline(), rendershadowmapreceivers(), renderva(), and renderzpass().