Inexor: inexor/engine/rendergl.cpp File Reference
rendergl.cpp File Reference
#include <SDL_opengl.h>
#include <boost/algorithm/clamp.hpp>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <list>
#include <memory>
#include <string>
#include "SDL_video.h"
#include "include/base/cef_ref_counted.h"
#include "include/cef_base.h"
#include "inexor/engine/blend.hpp"
#include "inexor/engine/console.hpp"
#include "inexor/engine/decal.hpp"
#include "inexor/engine/depthfx.hpp"
#include "inexor/engine/dynlight.hpp"
#include "inexor/engine/frame.hpp"
#include "inexor/engine/glare.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/grass.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/pvs.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderparticles.hpp"
#include "inexor/engine/rendersky.hpp"
#include "inexor/engine/rendertext.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/shadowmap.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/fpsgame/fps.hpp"
#include "inexor/fpsgame/player.hpp"
#include "inexor/fpsgame/render.hpp"
#include "inexor/io/Error.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/filesystem/mediadirs.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/texsettings.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/InexorCefApp.hpp"
#include "inexor/ui/InexorRenderHandler.hpp"
#include "inexor/ui/input/InexorMouseManager.hpp"
#include "inexor/ui/layer/InexorAppLayer.hpp"
#include "inexor/ui/layer/InexorConsoleLayer.hpp"
#include "inexor/ui/layer/InexorHudLayer.hpp"
#include "inexor/ui/layer/InexorLayer.hpp"
#include "inexor/ui/layer/InexorLayerManager.hpp"
#include "inexor/ui/legacy/3dgui.hpp"
#include "inexor/ui/legacy/menus.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
#include "inexor/util/legacy_time.hpp"
Namespaces
modelpreview
Macros
#define CHECKPLANE(c, dir, focaldist, low, high)
#define HUDQUAD(x1, y1, x2, y2, sx1, sy1, sx2, sy2)
#define MAXCROSSHAIRS 4
Functions
VAR (glversion, 1, 0, 0)
VAR (glslversion, 1, 0, 0)
void * getprocaddress (const char *name)
VARP (ati_skybox_bug, 0, 0, 1)
VAR (ati_minmax_bug, 0, 0, 1)
VAR (ati_cubemap_bug, 0, 0, 1)
VAR (intel_vertexarray_bug, 0, 0, 1)
VAR (intel_mapbufferrange_bug, 0, 0, 1)
VAR (minimizetcusage, 1, 0, 0)
VAR (useubo, 1, 0, 0)
VAR (usetexcompress, 1, 0, 0)
VAR (rtscissor, 0, 1, 1)
VAR (blurtile, 0, 1, 1)
VAR (rtsharefb, 0, 1, 1)
VAR (dbgexts, 0, 0, 1)
bool hasext (const char *exts, const char *ext)
void gl_checkextensions ()
void glext (char *ext)
COMMAND (glext,"s")
void cef_resize (int width, int height)
void gl_resize ()
void gl_init (int depth, int fsaa)
VAR (wireframe, 0, 0, 1)
ICOMMAND (getcampitch,"",(), floatret(camera1->pitch))
ICOMMAND (getcampos,"",(),{defformatstring(pos,"%s %s %s", floatstr(camera1->o.x), floatstr(camera1->o.y), floatstr(camera1->o.z));result(pos);})
ICOMMAND (getcamroll,"",(), floatret(camera1->roll))
ICOMMAND (getcamyaw,"",(), floatret(camera1->yaw))
void setcammatrix ()
void setcamprojmatrix (bool init=true, bool flush=false)
void resethudmatrix ()
void pushhudmatrix ()
void flushhudmatrix (bool flushparams)
void pophudmatrix (bool flush, bool flushparams)
void pushhudscale (float sx, float sy)
void pushhudtranslate (float tx, float ty, float sx, float sy)
void broadcastfov ()
Send your field of view to all other clients.
VARP (zoominvel, 0, 250, 5000)
VARP (zoomoutvel, 0, 100, 5000)
VARP (zoomfov, 10, 35, 150)
VARFP (fov, 10, 100, 150, broadcastfov())
VARP (followfov, 0, 1, 1)
VAR (avatarzoomfov, 10, 25, 60)
whether we adapt fov to the player we are currently spectating
VAR (avatarfov, 10, 65, 150)
FVAR (avatardepth, 0, 0.5f, 1)
FVARNP (aspect, forceaspect, 0, 0, 1e3f)
VARF (zoom,-1, 0, 1, broadcastfov())
void disablezoom ()
void computezoom ()
FVARP (zoomsens, 1e-3f, 1, 1000)
FVARP (zoomaccel, 0, 0, 1000)
VARP (zoomautosens, 0, 1, 1)
FVARP (sensitivity, 1e-3f, 3, 1000)
FVARP (sensitivityscale, 1e-3f, 1, 1000)
VARP (invmouse, 0, 0, 1)
FVARP (mouseaccel, 0, 0, 1000)
VAR (thirdperson, 0, 0, 2)
FVAR (thirdpersondistance, 0, 20, 50)
FVAR (thirdpersonup,-25, 0, 25)
FVAR (thirdpersonside,-25, 0, 25)
bool isthirdperson ()
void fixcamerarange ()
void mousemove (int dx, int dy)
void recomputecamera ()
FVAR (nearplane, 0.01f, 0.54f, 2.0f)
vec calcavatarpos (const vec &pos, float dist)
VAR (reflectclip, 0, 6, 64)
VAR (reflectclipavatar,-64, 0, 64)
void renderavatar ()
FVAR (polygonoffsetfactor,-1e4f,-3.0f, 1e4f)
FVAR (polygonoffsetunits,-1e4f,-3.0f, 1e4f)
FVAR (depthoffset,-1e4f, 0.01f, 1e4f)
void enablepolygonoffset (GLenum type)
void disablepolygonoffset (GLenum type)
void calcspherescissor (const vec &center, float size, float &sx1, float &sy1, float &sx2, float &sy2)
int pushscissor (float sx1, float sy1, float sx2, float sy2)
void popscissor ()
static void setupscreenquad ()
static void cleanupscreenquad ()
void screenquad ()
static void setscreentexcoord (int i, float w, float h, float x=0, float y=0)
void screenquad (float sw, float sh)
void screenquadflipped (float sw, float sh)
void screenquad (float sw, float sh, float sw2, float sh2)
void screenquadoffset (float x, float y, float w, float h)
void screenquadoffset (float x, float y, float w, float h, float x2, float y2, float w2, float h2)
void hudquad (float x, float y, float w, float h, float tx, float ty, float tw, float th)
VARR (fog, 16, 4000, 1000024)
HVARFR (fogcolour, 0, 0x8099B3, 0xFFFFFF,{fogcolor=bvec((fogcolour >>16)&0xFF,(fogcolour >>8)&0xFF, fogcolour &0xFF);})
static float findsurface (int fogmat, const vec &v, int &abovemat)
static void blendfog (int fogmat, float blend, float logblend, float &start, float &end, vec &fogc)
void setfogcolor (const vec &v)
void zerofogcolor ()
void resetfogcolor ()
void pushfogcolor (const vec &v)
void popfogcolor ()
void setfogdist (float start, float end)
void clearfogdist ()
void resetfogdist ()
void pushfogdist (float start, float end)
void popfogdist ()
static void resetfog ()
static void setfog (int fogmat, float below=1, int abovemat=MAT_AIR)
static void setnofog (const vec &color=vec(0, 0, 0))
static void blendfogoverlay (int fogmat, float blend, vec &overlay)
void drawfogoverlay (int fogmat, float fogblend, int abovemat)
void rendergame (bool mainpass)
VARP (skyboxglare, 0, 1, 1)
void drawglare ()
VARP (reflectmms, 0, 1, 1)
VARR (refractsky, 0, 0, 1)
void drawreflection (float z, bool refract, int fogdepth, const bvec &col)
void drawcubemap (int size, const vec &o, float yaw, float pitch, const cubemapside &side)
VAR (modelpreviewfov, 10, 20, 100)
VAR (modelpreviewpitch,-90,-15, 90)
void modelpreview::start (int x, int y, int w, int h, bool background)
void modelpreview::end ()
vec calcmodelpreviewpos (const vec &radius, float &yaw)
void clearminimap ()
VARR (minimapheight, 0, 0, 2<< 16)
HVARFR (minimapcolour, 0, 0, 0xFFFFFF,{minimapcolor=bvec((minimapcolour >>16)&0xFF,(minimapcolour >>8)&0xFF, minimapcolour &0xFF);})
VARR (minimapclip, 0, 0, 1)
VARFP (minimapsize, 7, 8, 10,{if(minimaptex) drawminimap();})
void bindminimap ()
void clipminimap (ivec &bbmin, ivec &bbmax, cube *c=worldroot, const ivec &co=ivec(0, 0, 0), int size=worldsize >>1)
void drawminimap ()
void drawtextures ()
void cleanupmotionblur ()
VARFP (motionblur, 0, 0, 1,{if(!motionblur) cleanupmotionblur();})
VARP (motionblurmillis, 1, 5, 1000)
FVARP (motionblurscale, 0, 0.5f, 1)
void addmotionblur ()
void invalidatepostfx ()
void gl_drawhud (int w, int h)
void gl_rendercefmouse (int view_x, int view_y, int view_width, int view_height)
void gl_rendercef ()
void gl_drawframe ()
VARP (new_ui, 0, 0, 1)
void gl_drawmainmenu ()
VARNP (damagecompass, usedamagecompass, 0, 1, 1)
VARP (damagecompassfade, 1, 1000, 10000)
VARP (damagecompasssize, 1, 30, 100)
VARP (damagecompassalpha, 1, 25, 100)
VARP (damagecompassmin, 1, 25, 1000)
VARP (damagecompassmax, 1, 200, 1000)
void damagecompass (int n, const vec &loc)
void drawdamagecompass (int w, int h)
VARFP (damagescreen, 0, 1, 1,{if(!damagescreen) damageblendmillis=0;})
VARP (damagescreenfactor, 1, 7, 100)
VARP (damagescreenalpha, 1, 45, 100)
VARP (damagescreenfade, 0, 125, 1000)
VARP (damagescreenmin, 1, 10, 1000)
VARP (damagescreenmax, 1, 100, 1000)
void damageblend (int n)
void bind_bomb_items_texture ()
void bind_items_texture ()
Binds the specific item icon map and returns true on success.
void drawdamagescreen (int w, int h)
VAR (hidestats, 0, 0, 1)
VAR (hidehud, 0, 0, 1)
VARP (crosshairsize, 0, 15, 50)
VARP (cursorsize, 0, 30, 50)
VARP (crosshairfx, 0, 1, 1)
VARP (crosshaircolors, 0, 1, 1)
SVARP (crosshairdir,"interface/crosshair")
void loadcrosshair (const char *name, int i)
void loadcrosshair_ (const char *name, int *i)
COMMANDN (loadcrosshair, loadcrosshair_,"si")
ICOMMAND (getcrosshair,"i",(int *i),{const char *name="";if(*i >=0 &&*i< MAXCROSSHAIRS){name=crosshairs[*i]?crosshairs[*i]->name:tempformatstring("%s/%s",*crosshairdir, game::defaultcrosshair(*i));}result(name);})
void writecrosshairs (stream *f)
SVARFP (cursor,"interface/cursor/default.png", cursortex=NULL)
void draw_g3d_cursor (int w, int h)
void draw_crosshair (int w, int h)
void drawcrosshair (int w, int h)
VARP (wallclock, 0, 0, 1)
VARP (wallclock24, 0, 0, 1)
VARP (wallclocksecs, 0, 0, 1)
VARP (showfps, 0, 1, 1)
VARP (showfpsrange, 0, 0, 1)
VAR (showeditstats, 0, 0, 1)
VAR (statrate, 1, 200, 1000)
FVARP (conscale, 1e-3f, 0.33f, 1e3f)
void gl_drawhud ()
void cleanupgl ()
Variables
bool hasVAO = false
bool hasFBO = false
bool hasAFBO = false
bool hasDS = false
bool hasTF = false
bool hasTRG = false
bool hasTSW = false
bool hasS3TC = false
bool hasFXT1 = false
bool hasAF = false
bool hasFBB = false
bool hasUBO = false
bool hasMBR = false
int hasstencil = 0
PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays_ = nullptr
PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements_ = nullptr
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate_ = nullptr
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate_ = nullptr
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate_ = nullptr
PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate_ = nullptr
PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate_ = nullptr
PFNGLGENBUFFERSPROC glGenBuffers_ = nullptr
PFNGLBINDBUFFERPROC glBindBuffer_ = nullptr
PFNGLMAPBUFFERPROC glMapBuffer_ = nullptr
PFNGLUNMAPBUFFERPROC glUnmapBuffer_ = nullptr
PFNGLBUFFERDATAPROC glBufferData_ = nullptr
PFNGLBUFFERSUBDATAPROC glBufferSubData_ = nullptr
PFNGLDELETEBUFFERSPROC glDeleteBuffers_ = nullptr
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData_ = nullptr
PFNGLGENQUERIESPROC glGenQueries_ = nullptr
PFNGLDELETEQUERIESPROC glDeleteQueries_ = nullptr
PFNGLBEGINQUERYPROC glBeginQuery_ = nullptr
PFNGLENDQUERYPROC glEndQuery_ = nullptr
PFNGLGETQUERYIVPROC glGetQueryiv_ = nullptr
PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv_ = nullptr
PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv_ = nullptr
PFNGLCREATEPROGRAMPROC glCreateProgram_ = nullptr
PFNGLDELETEPROGRAMPROC glDeleteProgram_ = nullptr
PFNGLUSEPROGRAMPROC glUseProgram_ = nullptr
PFNGLCREATESHADERPROC glCreateShader_ = nullptr
PFNGLDELETESHADERPROC glDeleteShader_ = nullptr
PFNGLSHADERSOURCEPROC glShaderSource_ = nullptr
PFNGLCOMPILESHADERPROC glCompileShader_ = nullptr
PFNGLGETSHADERIVPROC glGetShaderiv_ = nullptr
PFNGLGETPROGRAMIVPROC glGetProgramiv_ = nullptr
PFNGLATTACHSHADERPROC glAttachShader_ = nullptr
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog_ = nullptr
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog_ = nullptr
PFNGLLINKPROGRAMPROC glLinkProgram_ = nullptr
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation_ = nullptr
PFNGLUNIFORM1FPROC glUniform1f_ = nullptr
PFNGLUNIFORM2FPROC glUniform2f_ = nullptr
PFNGLUNIFORM3FPROC glUniform3f_ = nullptr
PFNGLUNIFORM4FPROC glUniform4f_ = nullptr
PFNGLUNIFORM1FVPROC glUniform1fv_ = nullptr
PFNGLUNIFORM2FVPROC glUniform2fv_ = nullptr
PFNGLUNIFORM3FVPROC glUniform3fv_ = nullptr
PFNGLUNIFORM4FVPROC glUniform4fv_ = nullptr
PFNGLUNIFORM1IPROC glUniform1i_ = nullptr
PFNGLUNIFORM2IPROC glUniform2i_ = nullptr
PFNGLUNIFORM3IPROC glUniform3i_ = nullptr
PFNGLUNIFORM4IPROC glUniform4i_ = nullptr
PFNGLUNIFORM1IVPROC glUniform1iv_ = nullptr
PFNGLUNIFORM2IVPROC glUniform2iv_ = nullptr
PFNGLUNIFORM3IVPROC glUniform3iv_ = nullptr
PFNGLUNIFORM4IVPROC glUniform4iv_ = nullptr
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv_ = nullptr
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv_ = nullptr
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv_ = nullptr
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation_ = nullptr
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform_ = nullptr
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray_ = nullptr
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray_ = nullptr
PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f_ = nullptr
PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv_ = nullptr
PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s_ = nullptr
PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv_ = nullptr
PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f_ = nullptr
PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv_ = nullptr
PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s_ = nullptr
PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv_ = nullptr
PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f_ = nullptr
PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv_ = nullptr
PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s_ = nullptr
PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv_ = nullptr
PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f_ = nullptr
PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv_ = nullptr
PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s_ = nullptr
PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv_ = nullptr
PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv_ = nullptr
PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv_ = nullptr
PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv_ = nullptr
PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv_ = nullptr
PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv_ = nullptr
PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv_ = nullptr
PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv_ = nullptr
PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub_ = nullptr
PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv_ = nullptr
PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv_ = nullptr
PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv_ = nullptr
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer_ = nullptr
PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv_ = nullptr
PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv_ = nullptr
PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv_ = nullptr
PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv_ = nullptr
PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv_ = nullptr
PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv_ = nullptr
PFNGLDRAWBUFFERSPROC glDrawBuffers_ = nullptr
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer_ = nullptr
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers_ = nullptr
PFNGLGENFRAMEBUFFERSPROC glGenRenderbuffers_ = nullptr
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage_ = nullptr
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus_ = nullptr
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer_ = nullptr
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers_ = nullptr
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers_ = nullptr
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D_ = nullptr
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer_ = nullptr
PFNGLGENERATEMIPMAPPROC glGenerateMipmap_ = nullptr
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer_ = nullptr
PFNGLGETUNIFORMINDICESPROC glGetUniformIndices_ = nullptr
PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv_ = nullptr
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex_ = nullptr
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv_ = nullptr
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding_ = nullptr
PFNGLBINDBUFFERBASEPROC glBindBufferBase_ = nullptr
PFNGLBINDBUFFERRANGEPROC glBindBufferRange_ = nullptr
PFNGLMAPBUFFERRANGEPROC glMapBufferRange_ = nullptr
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange_ = nullptr
PFNGLBINDVERTEXARRAYPROC glBindVertexArray_ = nullptr
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays_ = nullptr
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays_ = nullptr
PFNGLISVERTEXARRAYPROC glIsVertexArray_ = nullptr
vec worldpos
vec camdir
vec camright
vec camup
matrix4 hudmatrix
matrix4 hudmatrixstack [64]
int hudmatrixpos = 0
float curfov = 100
float curavatarfov = 65
float fovy
float aspect
int farplane
static float zoomprogress = 0
physent * camera1 = nullptr
special ent that acts as camera, same object as player1 in FPS mode
bool detachedcamera = false
const matrix4 viewmatrix (vec(-1, 0, 0), vec(0, 0, 1), vec(0,-1, 0))
matrix4 cammatrix
matrix4 projmatrix
matrix4 camprojmatrix
matrix4 invcammatrix
matrix4 invcamprojmatrix
matrix4 clipmatrix
matrix4 noclipmatrix
matrix4 nooffsetmatrix
static int scissoring = 0
static GLint oldscissor [4]
static GLuint screenquadvbo = 0
static LocalShaderParam screentexcoord [2] = { LocalShaderParam("screentexcoord0"), LocalShaderParam("screentexcoord1") }
bvec fogcolor (0x80, 0x99, 0xB3)
vec oldfogcolor (0, 0, 0)
vec curfogcolor (0, 0, 0)
float oldfogstart = 0
float oldfogend = 1000000
float curfogstart = 0
float curfogend = 1000000
bool renderedgame = false
matrix4 noreflectmatrix
int drawtex = 0
physent * modelpreview::oldcamera
physent modelpreview::camera
float modelpreview::oldaspect
float modelpreview::oldfovy
float modelpreview::oldfov
int modelpreview::oldfarplane
GLuint minimaptex = 0
vec minimapcenter (0, 0, 0)
vec minimapradius (0, 0, 0)
vec minimapscale (0, 0, 0)
bvec minimapcolor (0, 0, 0)
bool deferdrawtextures = false
GLuint motiontex = 0
int motionw = 0
int motionh = 0
int lastmotion = 0
bool dopostfx = false
int xtraverts
int xtravertsva
float damagedirs [8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
int damageblendmillis = 0
static Texture * crosshairs [MAXCROSSHAIRS] = { nullptr, nullptr, nullptr, nullptr }
static Texture * cursortex = nullptr
Macro Definition Documentation
#define CHECKPLANE (c, dir, focaldist, low, high)
Value:
do { \
        float nzc = (cz*cz + 1) / (cz dir drt) - cz, \
              pz = (d##c)/(nzc*e.c - e.z); \
        if(pz > 0) \
        { \
            float c = (focaldist)*nzc, \
                  pc = pz*nzc; \
            if(pc < e.c) low = c; \
            else if(pc > e.c) high = c; \
        } \
    } while(0)
Referenced by calcspherescissor().
#define HUDQUAD (x1, y1, x2, y2, sx1, sy1, sx2, sy2)
Value:
{ \
    gle::defvertex(2); \
    gle::deftexcoord0(); \
    gle::begin(GL_TRIANGLE_STRIP); \
    gle::attribf(x2, y1); gle::attribf(sx2, sy1); \
    gle::attribf(x1, y1); gle::attribf(sx1, sy1); \
    gle::attribf(x2, y2); gle::attribf(sx2, sy2); \
    gle::attribf(x1, y2); gle::attribf(sx1, sy2); \
    gle::end(); \
}
Referenced by hudquad().
#define MAXCROSSHAIRS 4
Referenced by loadcrosshair(), and writecrosshairs().
Function Documentation
void addmotionblur ()
References createtexture(), f(), hwtexsize, game::ispaused(), lastmillis, lastmotion, inexor::rpc::max(), motionh, motiontex, motionw, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, screenquad(), inexor::rendering::screen::ScreenManager::screenw, and SETSHADER.
Referenced by gl_drawframe().
void bind_bomb_items_texture ()
References DIR_UI, inexor::filesystem::getmediapath(), Texture::id, and textureload().
Referenced by game::bombclientmode::drawicon().
void bind_items_texture ()
Binds the specific item icon map and returns true on success.
References DIR_UI, inexor::filesystem::getmediapath(), Texture::id, and textureload().
Referenced by game::drawicon().
void bindminimap ()
References minimaptex.
Referenced by game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and game::captureclientmode::drawhud().
static void blendfog (int fogmat, float blend, float logblend, float & start, float & end, vec & fogc) static
References fog, fogcolor, getlavacolor(), getlavafog(), getwatercolor(), getwaterfog(), vec::madd(), MAT_LAVA, MAT_WATER, MATF_VOLUME, inexor::rpc::max(), inexor::rpc::min(), and bvec::tocolor().
Referenced by drawreflection(), and setfog().
static void blendfogoverlay (int fogmat, float blend, vec & overlay) static
References vec::add(), vec::div(), f(), getlavacolor(), getwatercolor(), vec::madd(), MAT_LAVA, MAT_WATER, MATF_VOLUME, vec::max(), inexor::rpc::max(), and inexor::rpc::min().
Referenced by drawfogoverlay().
void broadcastfov ()
Send your field of view to all other clients.
References game::broadcastfov().
Referenced by disablezoom().
vec calcavatarpos (const vec & pos, float dist)
References vec::add(), aspect, camera1, cammatrix, curavatarfov, dir, farplane, invcamprojmatrix, physent::o, matrix4::perspectivetransform(), RAD, vec::rescale(), vec::sub(), matrix4::transform(), and worldpos.
Referenced by game::drawhudmodel().
vec calcmodelpreviewpos (const vec & radius, float & yaw)
References aspect, camera1, f(), fovy, lastmillis, vec::magnitude(), vec::magnitude2(), inexor::rpc::max(), physent::pitch, RAD, and vec::rotate_around_x().
Referenced by gui::modelpreview(), previewprefab(), and game::renderplayerpreview().
void calcspherescissor (const vec & center, float size, float & sx1, float & sy1, float & sx2, float & sy2)
References aspect, cammatrix, CHECKPLANE, f(), fovy, RAD, reflecting, reflectz, matrix4::transform(), and worldpos.
Referenced by depthfxtexture::addscissorbox().
void cef_resize (int width, int height)
References inexor::ui::cef_app, Log, and inexor::util::log_manager::ui.
Referenced by gl_resize(), inexor::rendering::screen::ScreenManager::screenres(), and inexor::rendering::screen::ScreenManager::setfullscreen().
void cleanupgl ()
References gle::cleanup(), cleanupmotionblur(), cleanupscreenquad(), and clearminimap().
Referenced by resetgl().
void cleanupmotionblur ()
References lastmotion, motionh, motiontex, and motionw.
Referenced by cleanupgl().
static void cleanupscreenquad () static
References glDeleteBuffers_, and screenquadvbo.
Referenced by cleanupgl().
void clearfogdist ()
References setfogdist().
Referenced by modelpreview::start().
void clearminimap ()
References minimaptex.
Referenced by cleanupgl(), and drawminimap().
void clipminimap (ivec & bbmin, ivec & bbmax, cube * c = worldroot, const ivec & co = ivec(0, 0, 0), int size = worldsize>>1)
References isentirelysolid, loopi(), loopk, MAT_CLIP, MATF_CLIP, inexor::rpc::max(), and inexor::rpc::min().
Referenced by drawminimap().
COMMAND (glext , "s")
COMMANDN (loadcrosshair , loadcrosshair_ , "si")
void computezoom ()
References curavatarfov, curfov, elapsedtime, f(), game::getfollowingfov(), inexor::rpc::max(), inexor::rpc::min(), and zoomprogress.
Referenced by recomputecamera().
void damageblend (int n)
References damageblendmillis, lastmillis, inexor::rendering::screen::ScreenManager::minimized, and inexor::rendering::screen::screen_manager.
Referenced by game::damaged(), and game::hit().
void damagecompass (int n, const vec & loc)
References camera1, damagedirs, dir, f(), vec::magnitude(), inexor::rpc::max(), inexor::rendering::screen::ScreenManager::minimized, physent::o, inexor::rendering::screen::screen_manager, vec::sub(), vectoyawpitch(), and physent::yaw.
Referenced by game::damaged(), and game::hit().
void disablepolygonoffset (GLenum type)
References nooffsetmatrix, projmatrix, and setcamprojmatrix().
Referenced by decalrenderer::cleanuprenderstate(), blobrenderer::cleanuprenderstate(), drawskyoutline(), animmodel::endrender(), rendereditcursor(), rendermatgrid(), renderoutline(), and renderprefab().
void disablezoom ()
References broadcastfov(), and zoomprogress.
Referenced by game::deathstate(), game::edittoggled(), game::parsemessages(), game::startgame(), and game::timeupdate().
void draw_crosshair (int w, int h)
References Texture::ALPHA, gle::color(), crosshairs, GL_ONE, hudquad(), hudshader, Texture::id, loadcrosshair(), game::selectcrosshair(), Shader::set(), and Texture::type.
Referenced by drawcrosshair().
void draw_g3d_cursor (int w, int h)
References Texture::ALPHA, gle::color(), cursortex, g3d_cursorpos(), GL_ONE, hudquad(), hudshader, Texture::id, Shader::set(), textureload(), and Texture::type.
Referenced by drawcrosshair().
void drawcrosshair (int w, int h)
References draw_crosshair(), draw_g3d_cursor(), g3d_windowhit(), mainmenu, inexor::ui::layer::showapplayer, and windowhit.
Referenced by gl_drawhud().
void drawcubemap (int size, const vec & o, float yaw, float pitch, const cubemapside & side)
References matrix4::a, matrix4::b, matrix4::c, camera1, matrix4::d, drawskybox(), drawtex, DRAWTEX_ENVMAP, ENT_CAMERA, f(), farplane, cubemapside::flipx, cubemapside::flipy, gbatches, glde, limitsky(), lookupmaterial(), MATF_INDEX, MATF_VOLUME, physent::o, modelpreview::oldcamera, matrix4::perspective(), physent::pitch, player, projmatrix, renderalphageom(), rendergeom(), rendermapmodels(), physent::reset(), physent::roll, matrix4::scalexy(), setcamprojmatrix(), setfog(), setviewcell(), cubemapside::swapxy, physent::type, visiblecubes(), worldsize, xtraverts, xtravertsva, and physent::yaw.
Referenced by genenvmap().
void drawdamagecompass (int w, int h)
References gle::attrib(), gle::begin(), curtime, damagedirs, gle::end(), f(), hudnotextureshader, matrix4x3::identity(), loopi(), inexor::rpc::min(), RAD, matrix4x3::rotate_around_z(), matrix4x3::scale(), Shader::set(), matrix4x3::settranslation(), matrix4x3::transform(), and matrix4x3::translate().
Referenced by gl_drawhud().
void drawdamagescreen (int w, int h)
References damageblendmillis, DIR_UI, inexor::filesystem::getmediapath(), GL_ONE, hudquad(), hudshader, Texture::id, lastmillis, Shader::set(), and textureload().
Referenced by gl_drawhud().
void drawfogoverlay (int fogmat, float fogblend, int abovemat)
References blendfogoverlay(), gle::color(), screenquad(), and SETSHADER.
Referenced by gl_drawframe().
void drawglare ()
References drawskybox(), farplane, glaring, popfogcolor(), pushfogcolor(), refracting, renderalphageom(), renderavatar(), rendergame(), rendergeom(), rendermaterials(), renderparticles(), renderreflectedmapmodels(), and renderwater().
Referenced by glaretexture::dorender().
void drawminimap ()
References matrix4::a, vec::add(), camera1, clearminimap(), clipminimap(), drawreflections(), drawtex, DRAWTEX_MINIMAP, ENT_CAMERA, f(), gbatches, vtxarray::geommax, vtxarray::geommin, glde, hwtexsize, loopi(), loopk, loopv, inexor::rpc::max(), inexor::rpc::min(), minimapcenter, minimapcolor, minimapradius, minimapscale, minimaptex, vec::mul(), vec4::mul(), game::needminimap(), physent::o, modelpreview::oldcamera, matrix4::ortho(), physent::pitch, player, projmatrix, queryreflections(), renderalphageom(), renderedframe, rendergeom(), rendermapmodels(), rendermaterials(), renderprogress(), renderwater(), physent::reset(), physent::roll, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, setcamprojmatrix(), setnofog(), setuptexparameters(), setviewcell(), vec::sub(), bvec::tocolor(), physent::type, valist, visiblecubes(), worldsize, xtraverts, xtravertsva, and physent::yaw.
Referenced by drawtextures().
void drawreflection (float z, bool refract, int fogdepth, const bvec & col)
References physent::aboveeye, aspect, blendfog(), camera1, cammatrix, caustics, matrix4::clip(), clipmatrix, gle::color(), curavatarfov, drawskybox(), modelpreview::end(), physent::eyeheight, f(), fading, farplane, fogging, GLOBALPARAMF, invcammatrix, isthirdperson(), MAT_AIR, inexor::rpc::max(), noclipmatrix, noreflectmatrix, physent::o, matrix4::perspective(), player, popfogcolor(), popfogdist(), projmatrix, pushfogcolor(), pushfogdist(), reflecting, reflectz, matrix4::reflectz(), refractfog, refracting, renderalphageom(), game::renderavatar(), renderdecals(), rendergame(), rendergrass(), rendermaterials(), renderparticles(), renderreflectedgeom(), renderreflectedmapmodels(), setcamprojmatrix(), modelpreview::start(), bvec::tocolor(), matrix4::transposedtransform(), waterfade, and waterrefract.
Referenced by drawreflections().
void drawtextures ()
References deferdrawtextures, drawminimap(), genenvmaps(), inexor::rendering::screen::ScreenManager::minimized, and inexor::rendering::screen::screen_manager.
Referenced by allchanged(), and gl_drawframe().
void enablepolygonoffset (GLenum type)
References matrix4::c, ai::clipped(), matrix4::d, noclipmatrix, nooffsetmatrix, projmatrix, reflectz, and setcamprojmatrix().
Referenced by drawskyoutline(), animmodel::render(), rendereditcursor(), rendermatgrid(), renderoutline(), renderprefab(), decalrenderer::setuprenderstate(), and blobrenderer::setuprenderstate().
static float findsurface (int fogmat, const vec & v, int & abovemat) static
References isliquid, lookupcube(), MAT_AIR, cube::material, MATF_VOLUME, and worldsize.
Referenced by gl_drawframe().
void fixcamerarange ()
References camera1, physent::pitch, and physent::yaw.
Referenced by mousemove().
void flushhudmatrix (bool flushparams)
References Shader::flushparams(), GLOBALPARAM, hudmatrix, and Shader::lastshader.
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), game::drawhudicons(), game::gameplayhud(), gl_drawhud(), pophudmatrix(), pushhudscale(), pushhudtranslate(), renderbackground(), renderprogress(), and rendertexturepanel().
FVAR (avatardepth , 0 , 0. 5f, 1)
FVAR (thirdpersondistance , 0 , 20 , 50)
FVAR (thirdpersonup , - 25, 0 , 25)
FVAR (thirdpersonside , - 25, 0 , 25)
FVAR (nearplane , 0. 01f, 0. 54f, 2. 0f)
FVAR (polygonoffsetfactor , - 1e4f, -3. 0f, 1e4f)
FVAR (polygonoffsetunits , - 1e4f, -3. 0f, 1e4f)
FVAR (depthoffset , - 1e4f, 0. 01f, 1e4f)
FVARNP (aspect , forceaspect , 0 , 0 , 1e3f)
FVARP (zoomsens , 1e- 3f, 1 , 1000)
FVARP (zoomaccel , 0 , 0 , 1000)
FVARP (sensitivity , 1e- 3f, 3 , 1000)
FVARP (sensitivityscale , 1e- 3f, 1 , 1000)
FVARP (mouseaccel , 0 , 0 , 1000)
FVARP (motionblurscale , 0 , 0. 5f, 1)
FVARP (conscale , 1e- 3f, 0. 33f, 1e3f)
void* getprocaddress (const char * name)
Referenced by gl_checkextensions().
void gl_checkextensions ()
References blurdepthfx, depthfxsize, fatal(), getprocaddress(), glActiveTexture_, glAttachShader_, glBeginQuery_, glBindAttribLocation_, glBindBuffer_, glBindBufferBase_, glBindBufferRange_, glBindFramebuffer_, glBindRenderbuffer_, glBindVertexArray_, glBlendColor_, glBlendEquation_, glBlendEquationSeparate_, glBlendFuncSeparate_, glBlitFramebuffer_, glBufferData_, glBufferSubData_, glCheckFramebufferStatus_, glCompileShader_, glCompressedTexImage1D_, glCompressedTexImage2D_, glCompressedTexImage3D_, glCompressedTexSubImage1D_, glCompressedTexSubImage2D_, glCompressedTexSubImage3D_, glCopyTexSubImage3D_, glCreateProgram_, glCreateShader_, glDeleteBuffers_, glDeleteFramebuffers_, glDeleteProgram_, glDeleteQueries_, glDeleteRenderbuffers_, glDeleteShader_, glDeleteVertexArrays_, glDisableVertexAttribArray_, glDrawBuffers_, glDrawRangeElements_, glEnableVertexAttribArray_, glEndQuery_, glFlushMappedBufferRange_, glFramebufferRenderbuffer_, glFramebufferTexture2D_, glGenBuffers_, glGenerateMipmap_, glGenFramebuffers_, glGenQueries_, glGenRenderbuffers_, glGenVertexArrays_, glGetActiveUniform_, glGetActiveUniformBlockiv_, glGetActiveUniformsiv_, glGetBufferSubData_, glGetCompressedTexImage_, glGetProgramInfoLog_, glGetProgramiv_, glGetQueryiv_, glGetQueryObjectiv_, glGetQueryObjectuiv_, glGetShaderInfoLog_, glGetShaderiv_, glGetUniformBlockIndex_, glGetUniformIndices_, glGetUniformLocation_, glIsVertexArray_, glLinkProgram_, glMapBuffer_, glMapBufferRange_, glMultiDrawArrays_, glMultiDrawElements_, glRenderbufferStorage_, glShaderSource_, glslversion, glStencilFuncSeparate_, glStencilMaskSeparate_, glStencilOpSeparate_, glTexImage3D_, glTexSubImage3D_, glUniform1f_, glUniform1fv_, glUniform1i_, glUniform1iv_, glUniform2f_, glUniform2fv_, glUniform2i_, glUniform2iv_, glUniform3f_, glUniform3fv_, glUniform3i_, glUniform3iv_, glUniform4f_, glUniform4fv_, glUniform4i_, glUniform4iv_, glUniformBlockBinding_, glUniformMatrix2fv_, glUniformMatrix2x3fv_, glUniformMatrix2x4fv_, glUniformMatrix3fv_, glUniformMatrix3x2fv_, glUniformMatrix3x4fv_, glUniformMatrix4fv_, glUniformMatrix4x2fv_, glUniformMatrix4x3fv_, glUnmapBuffer_, glUseProgram_, glversion, glVertexAttrib1f_, glVertexAttrib1fv_, glVertexAttrib1s_, glVertexAttrib1sv_, glVertexAttrib2f_, glVertexAttrib2fv_, glVertexAttrib2s_, glVertexAttrib2sv_, glVertexAttrib3f_, glVertexAttrib3fv_, glVertexAttrib3s_, glVertexAttrib3sv_, glVertexAttrib4bv_, glVertexAttrib4f_, glVertexAttrib4fv_, glVertexAttrib4iv_, glVertexAttrib4Nbv_, glVertexAttrib4Niv_, glVertexAttrib4Nub_, glVertexAttrib4Nubv_, glVertexAttrib4Nuiv_, glVertexAttrib4Nusv_, glVertexAttrib4s_, glVertexAttrib4sv_, glVertexAttrib4ubv_, glVertexAttrib4uiv_, glVertexAttrib4usv_, glVertexAttribPointer_, hasAF, hasAFBO, hasDS, hasext(), hasFBB, hasFBO, hasFXT1, hasMBR, hasS3TC, hasTF, hasTRG, hasTSW, hasUBO, hasVAO, hwcubetexsize, hwmaxaniso, hwtexsize, intel_mapbufferrange_bug, Log, inexor::rpc::max(), MAXDYNLIGHTS, reservevpparams, rtsharefb, shadowmap, inexor::util::log_manager::std, usetexcompress, and waterfallrefract.
Referenced by main().
void gl_drawframe ()
References addglare(), addmotionblur(), aspect, camera1, caustics, curfov, deferdrawtextures, drawdepthfxtex(), drawfogoverlay(), drawglaretex(), drawreflections(), drawskybox(), drawtextures(), editmode, farplane, findsurface(), forceaspect, fovy, g3d_render(), gbatches, generategrass(), gl_drawhud(), gl_rendercef(), glde, hasstencil, hudshader, isliquid, lastmillis, limitsky(), lookupmaterial(), MAT_AIR, MAT_WATER, MATF_INDEX, MATF_VOLUME, inexor::rpc::min(), physent::o, outline, matrix4::perspective(), PI, projmatrix, queryreflections(), RAD, renderalphageom(), renderavatar(), renderdecals(), renderedgame, rendergame(), rendergeom(), rendergrass(), rendermapmodels(), rendermaterials(), renderoutline(), renderparticles(), renderpostfx(), renderwater(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, Shader::set(), setcamprojmatrix(), setfog(), updatedynlights(), visiblecubes(), WATER_OFFSET, worldsize, xtraverts, and xtravertsva.
Referenced by main().
void gl_drawhud (int w, int h)
Referenced by gl_drawframe(), and gl_drawmainmenu().
void gl_drawhud ()
References game::abovegameplayhud(), allocnodes, allocva, debugparticles(), DELETEA, draw_text(), draw_textf(), drawcrosshair(), drawdamagecompass(), drawdamagescreen(), editmode, executestr(), flushhudmatrix(), FONTH, forceaspect, g3d_limitscale(), game::gameplayhud(), gbatches, getfps(), getmaterialdesc(), getnumqueries(), getnumviewcells(), gettextres(), gettimestr(), glde, hudmatrix, hudshader, identexists(), lightmaps, loopi(), mainmenu, inexor::rpc::max(), inexor::rpc::min(), matrix4::ortho(), pophudmatrix(), pushhudmatrix(), renderblendbrush(), rendercommand(), renderconsole(), rendereditcursor(), rendertexturepanel(), resethudmatrix(), rplanes, matrix4::scale(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, selchildcount, selchildmat, Shader::set(), showmat, text_bounds(), totalmillis, viewdepthfxtex(), viewglaretex(), viewshadowmap(), vtris, vverts, wtris, wverts, xtraverts, and xtravertsva.
void gl_drawmainmenu ()
References g3d_render(), gbatches, gl_drawhud(), gl_rendercef(), glde, renderbackground(), renderpostfx(), xtraverts, and xtravertsva.
Referenced by main().
void gl_init (int depth, int fsaa)
References gl_resize(), gle::setup(), setupshaders(), and setuptexcompress().
Referenced by main(), and resetgl().
void gl_rendercef ()
References inexor::ui::cef_app, f(), GL_ONE, gl_rendercefmouse(), hudmatrix, hudquad(), hudshader, Log, matrix4::ortho(), resethudmatrix(), Shader::set(), and inexor::util::log_manager::std.
Referenced by gl_drawframe(), and gl_drawmainmenu().
void gl_rendercefmouse (int view_x, int view_y, int view_width, int view_height)
References inexor::ui::cef_app, f(), GL_ONE, hudquad(), hudshader, Shader::set(), and settexture().
Referenced by gl_rendercef().
void gl_resize ()
References cef_resize(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, and inexor::rendering::screen::ScreenManager::screenw.
Referenced by inexor::io::InputRouter::checkinput(), gl_init(), and inexor::rendering::screen::ScreenManager::screenres().
void glext (char * ext)
References hasext(), and intret().
bool hasext (const char * exts, const char * ext)
References cur.
Referenced by gl_checkextensions(), and glext().
void hudquad (float x, float y, float w, float h, float tx, float ty, float tw, float th)
References HUDQUAD.
Referenced by rendertarget::debug(), draw_crosshair(), draw_g3d_cursor(), drawdamagescreen(), gl_rendercef(), and gl_rendercefmouse().
HVARFR (fogcolour , 0 , 0x8099B3 , 0xFFFFFF , {fogcolor=bvec((fogcolour >>16)&0xFF,(fogcolour >>8)&0xFF, fogcolour &0xFF);})
HVARFR (minimapcolour , 0 , 0 , 0xFFFFFF , {minimapcolor=bvec((minimapcolour >>16)&0xFF,(minimapcolour >>8)&0xFF, minimapcolour &0xFF);})
ICOMMAND (getcampitch , "" , () , floatret(camera1->pitch))
ICOMMAND (getcampos , "" , () , {defformatstring(pos,"%s %s %s", floatstr(camera1->o.x), floatstr(camera1->o.y), floatstr(camera1->o.z));result(pos);})
ICOMMAND (getcamroll , "" , () , floatret(camera1->roll))
ICOMMAND (getcamyaw , "" , () , floatret(camera1->yaw))
ICOMMAND (getcrosshair , "i" , (int *i) , {const char *name="";if(*i >=0 &&*i< MAXCROSSHAIRS){name=crosshairs[*i]?crosshairs[*i]->name:tempformatstring("%s/%s",*crosshairdir, game::defaultcrosshair(*i));}result(name);})
void invalidatepostfx ()
References dopostfx.
Referenced by allchanged(), and commitchanges().
bool isthirdperson ()
References camera1, detachedcamera, player, and reflecting.
Referenced by drawreflection(), game::hudgunorigin(), game::newbouncer(), entities::pickupeffects(), renderavatar(), game::collectclientmode::rendergame(), and game::rendergame().
void loadcrosshair (const char * name, int i)
References crosshairs, game::defaultcrosshair(), MAXCROSSHAIRS, notexture, tempformatstring(), and textureload().
Referenced by draw_crosshair(), and loadcrosshair_().
void loadcrosshair_ (const char * name, int * i)
References loadcrosshair().
void mousemove (int dx, int dy)
References game::allowmouselook(), camera1, curtime, detachedcamera, fixcamerarange(), physent::pitch, player, and physent::yaw.
Referenced by inexor::io::InputRouter::checkinput().
void popfogcolor ()
References curfogcolor, oldfogcolor, and resetfogcolor().
Referenced by drawglare(), and drawreflection().
void popfogdist ()
References curfogend, curfogstart, oldfogend, oldfogstart, and resetfogdist().
Referenced by drawreflection().
void pophudmatrix (bool flush, bool flushparams)
References flushhudmatrix(), hudmatrix, hudmatrixpos, and hudmatrixstack.
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), game::drawhudicons(), game::gameplayhud(), gl_drawhud(), renderbackground(), renderprogress(), and rendertexturepanel().
void popscissor ()
References oldscissor, and scissoring.
void pushfogcolor (const vec & v)
References curfogcolor, oldfogcolor, and resetfogcolor().
Referenced by drawglare(), and drawreflection().
void pushfogdist (float start, float end)
References curfogend, curfogstart, modelpreview::end(), oldfogend, oldfogstart, resetfogdist(), and modelpreview::start().
Referenced by drawreflection().
void pushhudmatrix ()
References hudmatrix, hudmatrixpos, and hudmatrixstack.
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), game::drawhudicons(), game::gameplayhud(), gl_drawhud(), pushhudscale(), pushhudtranslate(), renderbackground(), renderprogress(), and rendertexturepanel().
void pushhudscale (float sx, float sy)
References flushhudmatrix(), hudmatrix, pushhudmatrix(), and matrix4::scale().
void pushhudtranslate (float tx, float ty, float sx, float sy)
References flushhudmatrix(), hudmatrix, pushhudmatrix(), matrix4::scale(), and matrix4::translate().
int pushscissor (float sx1, float sy1, float sx2, float sy2)
References f(), inexor::rpc::max(), inexor::rpc::min(), oldscissor, and scissoring.
void recomputecamera ()
References matrix3::a, physent::aboveeye, vec::add(), matrix3::b, matrix3::c, camera1, Texture::clamp, game::collidecamera(), computezoom(), game::detachcamera(), detachedcamera, dir, vec::dist(), ENT_CAMERA, physent::eyeheight, f(), matrix3::identity(), physent::move, movecamera(), vec::neg(), physent::o, orient, physent::pitch, player, RAD, physent::radius, physent::reset(), physent::roll, matrix3::rotate_around_x(), matrix3::rotate_around_y(), matrix3::rotate_around_z(), game::setupcamera(), setviewcell(), thirdperson, physent::type, physent::xradius, physent::yaw, and physent::yradius.
Referenced by main().
void renderavatar ()
References aspect, curavatarfov, farplane, isthirdperson(), matrix4::perspective(), projmatrix, game::renderavatar(), matrix4::scalez(), and setcamprojmatrix().
Referenced by drawglare(), and gl_drawframe().
void rendergame (bool mainpass)
Referenced by shadowmaptexture::dorender(), drawglare(), drawreflection(), and gl_drawframe().
static void resetfog () static
References curfogcolor, resetfogcolor(), and resetfogdist().
Referenced by setfog(), and setnofog().
void resetfogcolor ()
References curfogcolor, and setfogcolor().
Referenced by modelpreview::end(), popfogcolor(), pushfogcolor(), decalrenderer::render(), renderalphageom(), rendermaterials(), renderparticles(), and resetfog().
void resetfogdist ()
References curfogend, curfogstart, and setfogdist().
Referenced by modelpreview::end(), popfogdist(), pushfogdist(), and resetfog().
void resethudmatrix ()
References GLOBALPARAM, hudmatrix, and hudmatrixpos.
Referenced by recorder::drawhud(), gl_drawhud(), gl_rendercef(), renderbackground(), renderprogress(), and gui::start().
void screenquad ()
References gle::bindvbo(), gle::clearvbo(), screenquadvbo, and setupscreenquad().
Referenced by addglare(), addmotionblur(), drawfogoverlay(), recorder::readbuffer(), renderpostfx(), screenquad(), screenquadflipped(), and screenquadoffset().
void screenquad (float sw, float sh)
References screenquad(), and setscreentexcoord().
Referenced by rendertarget::rendertiles().
void screenquad (float sw, float sh, float sw2, float sh2)
References screenquad(), and setscreentexcoord().
void screenquadflipped (float sw, float sh)
References screenquad(), and setscreentexcoord().
Referenced by recorder::readbuffer().
void screenquadoffset (float x, float y, float w, float h)
References screenquad(), and setscreentexcoord().
void screenquadoffset (float x, float y, float w, float h, float x2, float y2, float w2, float h2)
References screenquad(), and setscreentexcoord().
void setcammatrix ()
References matrix4::a, vec::add(), matrix4::b, matrix4::c, camdir, camera1, cammatrix, camright, camup, drawtex, vec::mul(), vec::neg(), physent::o, physent::pitch, RAD, RAY_CLIPMAT, RAY_SKIPFIRST, raycubepos(), physent::roll, matrix4::rotate_around_x(), matrix4::rotate_around_y(), matrix4::rotate_around_z(), matrix4::translate(), matrix4::transposedtransformnormal(), viewmatrix, worldpos, worldsize, and physent::yaw.
Referenced by setcamprojmatrix().
void setcamprojmatrix (bool init = true, bool flush = false)
References matrix4::a, matrix4::b, matrix4::c, cammatrix, camprojmatrix, Shader::flushparams(), fogging, GLOBALPARAM, GLOBALPARAMF, sphere::init(), invcammatrix, invcamprojmatrix, matrix4::invert(), Shader::lastshader, matrix4::lineardepthscale(), matrix4::muld(), projmatrix, and setcammatrix().
Referenced by disablepolygonoffset(), drawcubemap(), drawminimap(), drawreflection(), enablepolygonoffset(), gl_drawframe(), renderavatar(), and modelpreview::start().
static void setfog (int fogmat, float below = 1, int abovemat = MAT_AIR) static
References blendfog(), curfogcolor, curfogend, curfogstart, and resetfog().
Referenced by drawcubemap(), and gl_drawframe().
void setfogcolor (const vec & v)
References fogcolor, and GLOBALPARAM.
Referenced by changeslottmus(), resetfogcolor(), and zerofogcolor().
void setfogdist (float start, float end)
References GLOBALPARAMF.
Referenced by clearfogdist(), and resetfogdist().
static void setnofog (const vec & color = vec(0, 0, 0)) static
References gle::color(), curfogcolor, curfogend, curfogstart, and resetfog().
Referenced by drawminimap().
static void setscreentexcoord (int i, float w, float h, float x = 0, float y = 0) inline static
References f(), screentexcoord, and LocalShaderParam::setf().
Referenced by screenquad(), screenquadflipped(), and screenquadoffset().
static void setupscreenquad () static
References gle::bindvbo(), gle::clearvbo(), glBufferData_, glGenBuffers_, screenquadvbo, and sphere::verts.
Referenced by screenquad().
SVARFP (cursor , "interface/cursor/default.png" , cursortex = NULL)
SVARP (crosshairdir , "interface/crosshair")
VAR (glversion , 1 , 0 , 0)
VAR (glslversion , 1 , 0 , 0)
VAR (ati_minmax_bug , 0 , 0 , 1)
VAR (ati_cubemap_bug , 0 , 0 , 1)
VAR (intel_vertexarray_bug , 0 , 0 , 1)
VAR (intel_mapbufferrange_bug , 0 , 0 , 1)
VAR (minimizetcusage , 1 , 0 , 0)
VAR (useubo , 1 , 0 , 0)
VAR (usetexcompress , 1 , 0 , 0)
VAR (rtscissor , 0 , 1 , 1)
VAR (blurtile , 0 , 1 , 1)
VAR (rtsharefb , 0 , 1 , 1)
VAR (dbgexts , 0 , 0 , 1)
VAR (wireframe , 0 , 0 , 1)
VAR (avatarzoomfov , 10 , 25 , 60)
whether we adapt fov to the player we are currently spectating
VAR (avatarfov , 10 , 65 , 150)
VAR (thirdperson , 0 , 0 , 2)
VAR (reflectclip , 0 , 6 , 64)
VAR (reflectclipavatar , - 64, 0 , 64)
VAR (modelpreviewfov , 10 , 20 , 100)
VAR (modelpreviewpitch , - 90, - 15, 90)
VAR (hidestats , 0 , 0 , 1)
VAR (hidehud , 0 , 0 , 1)
VAR (showeditstats , 0 , 0 , 1)
VAR (statrate , 1 , 200 , 1000)
VARF (zoom , - 1, 0 , 1 , broadcastfov())
VARFP (fov , 10 , 100 , 150 , broadcastfov())
VARFP (minimapsize , 7 , 8 , 10 , {if(minimaptex) drawminimap();})
VARFP (motionblur , 0 , 0 , 1 , {if(!motionblur) cleanupmotionblur();})
VARFP (damagescreen , 0 , 1 , 1 , {if(!damagescreen) damageblendmillis=0;})
VARNP (damagecompass , usedamagecompass , 0 , 1 , 1)
VARP (ati_skybox_bug , 0 , 0 , 1)
VARP (zoominvel , 0 , 250 , 5000)
VARP (zoomoutvel , 0 , 100 , 5000)
VARP (zoomfov , 10 , 35 , 150)
VARP (followfov , 0 , 1 , 1)
VARP (zoomautosens , 0 , 1 , 1)
VARP (invmouse , 0 , 0 , 1)
VARP (skyboxglare , 0 , 1 , 1)
VARP (reflectmms , 0 , 1 , 1)
VARP (motionblurmillis , 1 , 5 , 1000)
VARP (new_ui , 0 , 0 , 1)
VARP (damagecompassfade , 1 , 1000 , 10000)
VARP (damagecompasssize , 1 , 30 , 100)
VARP (damagecompassalpha , 1 , 25 , 100)
VARP (damagecompassmin , 1 , 25 , 1000)
VARP (damagecompassmax , 1 , 200 , 1000)
VARP (damagescreenfactor , 1 , 7 , 100)
VARP (damagescreenalpha , 1 , 45 , 100)
VARP (damagescreenfade , 0 , 125 , 1000)
VARP (damagescreenmin , 1 , 10 , 1000)
VARP (damagescreenmax , 1 , 100 , 1000)
VARP (crosshairsize , 0 , 15 , 50)
VARP (cursorsize , 0 , 30 , 50)
VARP (crosshairfx , 0 , 1 , 1)
VARP (crosshaircolors , 0 , 1 , 1)
VARP (wallclock , 0 , 0 , 1)
VARP (wallclock24 , 0 , 0 , 1)
VARP (wallclocksecs , 0 , 0 , 1)
VARP (showfps , 0 , 1 , 1)
VARP (showfpsrange , 0 , 0 , 1)
VARR (fog , 16 , 4000 , 1000024)
VARR (refractsky , 0 , 0 , 1)
VARR (minimapheight , 0 , 0 , 2<< 16)
VARR (minimapclip , 0 , 0 , 1)
void writecrosshairs (stream * f)
References crosshairs, escapestring(), loopi(), MAXCROSSHAIRS, Texture::name, notexture, path(), and stream::printf().
Referenced by writecfg().
void zerofogcolor ()
References setfogcolor().
Referenced by decalrenderer::render(), rendermaterials(), renderparticles(), and modelpreview::start().
Variable Documentation
float aspect
Referenced by gui::adjustscale(), calcavatarpos(), calcmodelpreviewpos(), calcspherescissor(), consolebox(), drawreflection(), modelpreview::end(), gl_drawframe(), matrix4::perspective(), renderavatar(), and modelpreview::start().
vec camdir
Referenced by flarerenderer::addflare(), gui::end(), g3d_key(), flarerenderer::makelightflares(), rendereditcursor(), meterrenderer::renderpart(), textrenderer::renderpart(), and setcammatrix().
physent* camera1 = nullptr
special ent that acts as camera, same object as player1 in FPS mode
Referenced by adddecal(), adddynlight(), flarerenderer::addflare(), addvisibleva(), calcavatarpos(), calcmodelpreviewpos(), calcshadowmapbb(), calcwatersubdiv(), inexor::sound::checkmapsounds(), cullmodel(), damagecompass(), shadowmaptexture::dorender(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), drawcubemap(), game::drawminimap(), drawminimap(), drawreflection(), drawreflections(), drawskybox(), game::drawteammate(), gui::end(), modelpreview::end(), endmodelbatches(), fireballrenderer::finddepthfxranges(), finddynlights(), findreflectedvas(), findvisiblemms(), fixcamerarange(), g3d_addgui(), g3d_key(), g3d_mainmenu(), generategrass(), gengrassquads(), genpos< PT_TAPE >(), gl_drawframe(), game::ctfclientmode::interpflagpos(), isthirdperson(), lockpvs_(), main(), flarerenderer::makelightflares(), menuinfrontofplayer(), mousemove(), newentity(), flarerenderer::newflare(), particle_text(), particle_textcopy(), phystest(), inexor::sound::playsound(), queryreflection(), recomputecamera(), regularshape(), animmodel::part::render(), ai::render(), rendercullmodelquery(), renderentselection(), rendergeom(), renderlightning(), rendermapmodels(), rendermaterials(), fireballrenderer::renderpart(), game::bombclientmode::renderplayersposindicator(), renderwater(), setcammatrix(), setupgeom(), texturegui::show(), sortmaterials(), splash(), gui::start(), modelpreview::start(), testpvs(), inexor::sound::updatechannel(), updateparticles(), and updateskystats().
matrix4 cammatrix
Referenced by calcavatarpos(), calcspherescissor(), drawfogdome(), drawreflection(), drawskybox(), depthfxtexture::eyedepth(), setcammatrix(), and setcamprojmatrix().
matrix4 camprojmatrix
Referenced by depthfxtexture::addscissorvert(), calcscissorbox(), animmodel::part::render(), fireballrenderer::renderpart(), renderprefab(), setcamprojmatrix(), setprojtexmatrix(), setvfcP(), and gui::start().
vec camright
Referenced by genpos(), genrotpos< PT_PART >(), game::hudgunorigin(), flarerenderer::render(), fireballrenderer::renderpart(), meterrenderer::renderpart(), textrenderer::renderpart(), and setcammatrix().
vec camup
Referenced by genpos(), genrotpos< PT_PART >(), game::hudgunorigin(), flarerenderer::render(), fireballrenderer::renderpart(), meterrenderer::renderpart(), textrenderer::renderpart(), and setcammatrix().
matrix4 clipmatrix
Referenced by drawreflection().
Texture* crosshairs[MAXCROSSHAIRS] = { nullptr, nullptr, nullptr, nullptr } static
Referenced by draw_crosshair(), loadcrosshair(), and writecrosshairs().
float curavatarfov = 65
Referenced by calcavatarpos(), computezoom(), drawreflection(), and renderavatar().
vec curfogcolor(0, 0, 0)
Referenced by changeslottmus(), modelpreview::end(), popfogcolor(), pushfogcolor(), resetfog(), resetfogcolor(), setfog(), and setnofog().
float curfogend = 1000000
Referenced by popfogdist(), pushfogdist(), resetfogdist(), setfog(), and setnofog().
float curfogstart = 0
Referenced by popfogdist(), pushfogdist(), resetfogdist(), setfog(), and setnofog().
float curfov = 100
Referenced by computezoom(), modelpreview::end(), gl_drawframe(), and modelpreview::start().
Texture* cursortex = nullptr static
Referenced by draw_g3d_cursor().
int damageblendmillis = 0
Referenced by damageblend(), and drawdamagescreen().
float damagedirs[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }
Referenced by damagecompass(), and drawdamagecompass().
bool deferdrawtextures = false
Referenced by drawtextures(), and gl_drawframe().
bool detachedcamera = false
Referenced by isthirdperson(), mousemove(), and recomputecamera().
bool dopostfx = false
Referenced by invalidatepostfx().
int drawtex = 0
Referenced by addreflection(), drawcubemap(), drawminimap(), drawreflections(), drawskybox(), modelpreview::end(), queryreflections(), renderclient(), rendergeom(), rendermaterials(), renderprogress(), renderva(), renderwater(), setcammatrix(), sortmaterials(), and modelpreview::start().
int farplane
Referenced by calcavatarpos(), drawcubemap(), drawglare(), drawreflection(), modelpreview::end(), gl_drawframe(), renderavatar(), and modelpreview::start().
bvec fogcolor(0x80, 0x99, 0xB3)
Referenced by blendfog(), fogdome::draw(), and setfogcolor().
float fovy
Referenced by calcmodelpreviewpos(), calcspherescissor(), modelpreview::end(), gl_drawframe(), renderentselection(), and modelpreview::start().
PFNGLATTACHSHADERPROC glAttachShader_ = nullptr
Referenced by gl_checkextensions(), and linkglslprogram().
PFNGLBEGINQUERYPROC glBeginQuery_ = nullptr
Referenced by gl_checkextensions().
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation_ = nullptr
Referenced by gl_checkextensions(), and linkglslprogram().
PFNGLBINDBUFFERPROC glBindBuffer_ = nullptr
Referenced by gle::begin(), gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), gle::disablequads(), gle::enablequads(), gle::end(), gle::forcedisable(), genvbo(), and gl_checkextensions().
PFNGLBINDBUFFERBASEPROC glBindBufferBase_ = nullptr
Referenced by gl_checkextensions().
PFNGLBINDBUFFERRANGEPROC glBindBufferRange_ = nullptr
Referenced by gl_checkextensions().
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer_ = nullptr
Referenced by rendertarget::blur(), drawreflections(), genwatertex(), gl_checkextensions(), recorder::readbuffer(), rendertarget::render(), renderpostfx(), rendertarget::setup(), and rendertarget::setupblur().
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer_ = nullptr
Referenced by genwatertex(), gl_checkextensions(), recorder::readbuffer(), rendertarget::setup(), and rendertarget::setupblur().
PFNGLBINDVERTEXARRAYPROC glBindVertexArray_ = nullptr
Referenced by gl_checkextensions(), and gle::setup().
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate_ = nullptr
Referenced by gl_checkextensions().
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate_ = nullptr
Referenced by gl_checkextensions().
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer_ = nullptr
Referenced by gl_checkextensions(), and recorder::readbuffer().
PFNGLBUFFERDATAPROC glBufferData_ = nullptr
Referenced by gle::begin(), gle::enablequads(), gle::end(), blobrenderer::flushblobs(), generategrass(), genvbo(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), gl_checkextensions(), sphere::init(), fogdome::init(), decalrenderer::render(), vertmodel::vertmeshgroup::render(), skelmodel::skelmeshgroup::render(), prefabmesh::setup(), setupbb(), setupscreenquad(), and varenderer< T >::update().
PFNGLBUFFERSUBDATAPROC glBufferSubData_ = nullptr
Referenced by gle::end(), blobrenderer::flushblobs(), generategrass(), gl_checkextensions(), decalrenderer::render(), and varenderer< T >::update().
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus_ = nullptr
Referenced by genwatertex(), gl_checkextensions(), and rendertarget::setup().
PFNGLCOMPILESHADERPROC glCompileShader_ = nullptr
Referenced by compileglslshader(), and gl_checkextensions().
PFNGLCREATEPROGRAMPROC glCreateProgram_ = nullptr
Referenced by gl_checkextensions(), and linkglslprogram().
PFNGLCREATESHADERPROC glCreateShader_ = nullptr
Referenced by compileglslshader(), and gl_checkextensions().
PFNGLDELETEBUFFERSPROC glDeleteBuffers_ = nullptr
Referenced by blobrenderer::cleanup(), decalrenderer::cleanup(), sphere::cleanup(), gle::cleanup(), fogdome::cleanup(), vertmodel::vertmeshgroup::cleanup(), varenderer< T >::cleanup(), prefab::cleanup(), skelmodel::skelmeshgroup::cleanup(), cleanupbb(), cleanupgrass(), cleanupscreenquad(), destroyvbo(), gl_checkextensions(), skelmodel::skelmeshgroup::~skelmeshgroup(), and vertmodel::vertmeshgroup::~vertmeshgroup().
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers_ = nullptr
Referenced by cleanreflections(), rendertarget::cleanup(), recorder::cleanup(), rendertarget::cleanupblur(), cleanuppostfx(), and gl_checkextensions().
PFNGLDELETEPROGRAMPROC glDeleteProgram_ = nullptr
Referenced by Shader::cleanup(), gl_checkextensions(), and linkglslprogram().
PFNGLDELETEQUERIESPROC glDeleteQueries_ = nullptr
Referenced by queryframe::cleanup(), and gl_checkextensions().
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers_ = nullptr
Referenced by cleanreflections(), rendertarget::cleanup(), recorder::cleanup(), rendertarget::cleanupblur(), and gl_checkextensions().
PFNGLDELETESHADERPROC glDeleteShader_ = nullptr
Referenced by Shader::cleanup(), compileglslshader(), and gl_checkextensions().
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays_ = nullptr
Referenced by gle::cleanup(), and gl_checkextensions().
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray_ = nullptr
Referenced by gle::disableattrib(), gle::forcedisable(), gl_checkextensions(), and gle::unsetattrib().
PFNGLDRAWBUFFERSPROC glDrawBuffers_ = nullptr
Referenced by gl_checkextensions().
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray_ = nullptr
Referenced by gle::enableattrib(), gl_checkextensions(), and gle::setattrib().
PFNGLENDQUERYPROC glEndQuery_ = nullptr
Referenced by gl_checkextensions().
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange_ = nullptr
Referenced by gl_checkextensions().
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer_ = nullptr
Referenced by genwatertex(), gl_checkextensions(), recorder::readbuffer(), rendertarget::setup(), and rendertarget::setupblur().
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D_ = nullptr
Referenced by rendertarget::blur(), drawreflections(), genwatertex(), gl_checkextensions(), recorder::readbuffer(), rendertarget::render(), renderpostfx(), rendertarget::setup(), and rendertarget::setupblur().
PFNGLGENBUFFERSPROC glGenBuffers_ = nullptr
Referenced by gle::begin(), gle::enablequads(), gle::end(), blobrenderer::flushblobs(), generategrass(), genvbo(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), gl_checkextensions(), sphere::init(), fogdome::init(), decalrenderer::render(), prefabmesh::setup(), setupbb(), setupscreenquad(), and varenderer< T >::update().
PFNGLGENERATEMIPMAPPROC glGenerateMipmap_ = nullptr
Referenced by gl_checkextensions().
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers_ = nullptr
Referenced by genwatertex(), gl_checkextensions(), recorder::readbuffer(), renderpostfx(), rendertarget::setup(), and rendertarget::setupblur().
PFNGLGENQUERIESPROC glGenQueries_ = nullptr
Referenced by gl_checkextensions(), and queryframe::newquery().
PFNGLGENFRAMEBUFFERSPROC glGenRenderbuffers_ = nullptr
Referenced by genwatertex(), gl_checkextensions(), recorder::readbuffer(), rendertarget::setup(), and rendertarget::setupblur().
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays_ = nullptr
Referenced by gl_checkextensions(), and gle::setup().
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform_ = nullptr
Referenced by allocglslactiveuniforms(), and gl_checkextensions().
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv_ = nullptr
Referenced by bindglsluniform(), and gl_checkextensions().
PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv_ = nullptr
Referenced by bindglsluniform(), and gl_checkextensions().
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData_ = nullptr
Referenced by gl_checkextensions(), and readva().
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog_ = nullptr
Referenced by gl_checkextensions(), and showglslinfo().
PFNGLGETPROGRAMIVPROC glGetProgramiv_ = nullptr
Referenced by allocglslactiveuniforms(), gl_checkextensions(), linkglslprogram(), and showglslinfo().
PFNGLGETQUERYIVPROC glGetQueryiv_ = nullptr
Referenced by gl_checkextensions().
PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv_ = nullptr
Referenced by checkquery(), and gl_checkextensions().
PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv_ = nullptr
Referenced by checkquery(), and gl_checkextensions().
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog_ = nullptr
Referenced by gl_checkextensions(), and showglslinfo().
PFNGLGETSHADERIVPROC glGetShaderiv_ = nullptr
Referenced by compileglslshader(), gl_checkextensions(), and showglslinfo().
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex_ = nullptr
Referenced by bindglsluniform(), and gl_checkextensions().
PFNGLGETUNIFORMINDICESPROC glGetUniformIndices_ = nullptr
Referenced by bindglsluniform(), and gl_checkextensions().
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation_ = nullptr
Referenced by bindglsluniform(), skelmodel::skeleton::getblendoffset(), gl_checkextensions(), linkglslprogram(), and setglsluniformformat().
PFNGLISVERTEXARRAYPROC glIsVertexArray_ = nullptr
Referenced by gl_checkextensions().
PFNGLLINKPROGRAMPROC glLinkProgram_ = nullptr
Referenced by gl_checkextensions(), and linkglslprogram().
PFNGLMAPBUFFERPROC glMapBuffer_ = nullptr
Referenced by gl_checkextensions().
PFNGLMAPBUFFERRANGEPROC glMapBufferRange_ = nullptr
Referenced by gle::begin(), gle::end(), blobrenderer::flushblobs(), and gl_checkextensions().
PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays_ = nullptr
Referenced by gle::end(), and gl_checkextensions().
PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements_ = nullptr
Referenced by gl_checkextensions().
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage_ = nullptr
Referenced by genwatertex(), gl_checkextensions(), recorder::readbuffer(), rendertarget::setup(), and rendertarget::setupblur().
PFNGLSHADERSOURCEPROC glShaderSource_ = nullptr
Referenced by compileglslshader(), and gl_checkextensions().
PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate_ = nullptr
Referenced by gl_checkextensions().
PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate_ = nullptr
Referenced by gl_checkextensions().
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate_ = nullptr
Referenced by gl_checkextensions().
PFNGLUNIFORM1FPROC glUniform1f_ = nullptr
Referenced by gl_checkextensions(), LocalShaderParam::setf(), and LocalShaderParam::sett().
PFNGLUNIFORM1FVPROC glUniform1fv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), setslotparam(), and LocalShaderParam::setv().
PFNGLUNIFORM1IPROC glUniform1i_ = nullptr
Referenced by gl_checkextensions(), linkglslprogram(), LocalShaderParam::setf(), setslotparam(), and LocalShaderParam::sett().
PFNGLUNIFORM1IVPROC glUniform1iv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), and LocalShaderParam::setv().
PFNGLUNIFORM2FPROC glUniform2f_ = nullptr
Referenced by gl_checkextensions(), LocalShaderParam::setf(), and LocalShaderParam::sett().
PFNGLUNIFORM2FVPROC glUniform2fv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), setslotparam(), and LocalShaderParam::setv().
PFNGLUNIFORM2IPROC glUniform2i_ = nullptr
Referenced by gl_checkextensions(), LocalShaderParam::setf(), setslotparam(), and LocalShaderParam::sett().
PFNGLUNIFORM2IVPROC glUniform2iv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), and LocalShaderParam::setv().
PFNGLUNIFORM3FPROC glUniform3f_ = nullptr
Referenced by gl_checkextensions(), LocalShaderParam::setf(), and LocalShaderParam::sett().
PFNGLUNIFORM3FVPROC glUniform3fv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), setslotparam(), and LocalShaderParam::setv().
PFNGLUNIFORM3IPROC glUniform3i_ = nullptr
Referenced by gl_checkextensions(), LocalShaderParam::setf(), setslotparam(), and LocalShaderParam::sett().
PFNGLUNIFORM3IVPROC glUniform3iv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), and LocalShaderParam::setv().
PFNGLUNIFORM4FPROC glUniform4f_ = nullptr
Referenced by gl_checkextensions(), LocalShaderParam::setf(), and LocalShaderParam::sett().
PFNGLUNIFORM4FVPROC glUniform4fv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), skelmodel::skeleton::setglslbones(), setslotparam(), and LocalShaderParam::setv().
PFNGLUNIFORM4IPROC glUniform4i_ = nullptr
Referenced by gl_checkextensions(), LocalShaderParam::setf(), setslotparam(), and LocalShaderParam::sett().
PFNGLUNIFORM4IVPROC glUniform4iv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), and LocalShaderParam::setv().
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding_ = nullptr
Referenced by bindglsluniform(), and gl_checkextensions().
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), and LocalShaderParam::setv().
PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), and LocalShaderParam::setv().
PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv_ = nullptr
Referenced by GlobalShaderParamUse::flush(), gl_checkextensions(), and LocalShaderParam::setv().
PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLUNMAPBUFFERPROC glUnmapBuffer_ = nullptr
Referenced by gle::end(), blobrenderer::flushblobs(), and gl_checkextensions().
PFNGLUSEPROGRAMPROC glUseProgram_ = nullptr
Referenced by Shader::bindprograms(), cleanupshaders(), gl_checkextensions(), linkglslprogram(), and newshader().
PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f_ = nullptr
Referenced by gl_checkextensions(), gle::normal(), and gle::tangent().
PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv_ = nullptr
Referenced by gl_checkextensions(), and gle::tangent().
PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub_ = nullptr
Referenced by gle::color(), and gl_checkextensions().
PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv_ = nullptr
Referenced by gle::color(), and gl_checkextensions().
PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv_ = nullptr
Referenced by gl_checkextensions().
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer_ = nullptr
Referenced by gl_checkextensions(), and gle::setattrib().
bool hasAF = false
Referenced by gl_checkextensions(), and setuptexparameters().
bool hasAFBO = false
Referenced by gl_checkextensions().
bool hasDS = false
Referenced by genwatertex(), gl_checkextensions(), and maskreflection().
bool hasFBB = false
Referenced by gl_checkextensions(), and recorder::readbuffer().
bool hasFBO = false
Referenced by gl_checkextensions().
bool hasFXT1 = false
Referenced by gl_checkextensions().
bool hasMBR = false
Referenced by gl_checkextensions().
bool hasS3TC = false
Referenced by gendds(), gl_checkextensions(), and loaddds().
int hasstencil = 0
Referenced by genwatertex(), gl_drawframe(), maskreflection(), and inexor::rendering::screen::ScreenManager::setupscreen().
bool hasTF = false
Referenced by depthfxtexture::colorformats(), shadowmaptexture::colorformats(), and gl_checkextensions().
bool hasTRG = false
Referenced by depthfxtexture::colorformats(), BlendBrush::gentex(), and gl_checkextensions().
bool hasTSW = false
Referenced by gl_checkextensions().
bool hasUBO = false
Referenced by bindglsluniform(), and gl_checkextensions().
bool hasVAO = false
Referenced by gl_checkextensions().
matrix4 hudmatrix
Referenced by consolebox(), debugparticles(), game::drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), recorder::drawhud(), game::drawhudicons(), flushhudmatrix(), game::gameplayhud(), gl_drawhud(), gl_rendercef(), pophudmatrix(), pushhudmatrix(), pushhudscale(), pushhudtranslate(), renderbackground(), renderprogress(), rendertexturepanel(), resethudmatrix(), and gui::start().
int hudmatrixpos = 0
Referenced by pophudmatrix(), pushhudmatrix(), and resethudmatrix().
matrix4 hudmatrixstack[64]
Referenced by pophudmatrix(), and pushhudmatrix().
matrix4 invcammatrix
Referenced by drawreflection(), and setcamprojmatrix().
matrix4 invcamprojmatrix
Referenced by calcavatarpos(), and setcamprojmatrix().
int lastmotion = 0
Referenced by addmotionblur(), and cleanupmotionblur().
vec minimapcenter(0, 0, 0)
Referenced by game::drawminimap(), and drawminimap().
bvec minimapcolor(0, 0, 0)
Referenced by drawminimap().
vec minimapradius(0, 0, 0)
Referenced by game::calcradarscale(), and drawminimap().
vec minimapscale(0, 0, 0)
Referenced by game::drawminimap(), and drawminimap().
GLuint minimaptex = 0
Referenced by bindminimap(), clearminimap(), and drawminimap().
int motionh = 0
Referenced by addmotionblur(), and cleanupmotionblur().
GLuint motiontex = 0
Referenced by addmotionblur(), and cleanupmotionblur().
int motionw = 0
Referenced by addmotionblur(), and cleanupmotionblur().
matrix4 noclipmatrix
Referenced by drawreflection(), and enablepolygonoffset().
matrix4 nooffsetmatrix
Referenced by disablepolygonoffset(), and enablepolygonoffset().
matrix4 noreflectmatrix
Referenced by drawreflection().
vec oldfogcolor(0, 0, 0)
Referenced by popfogcolor(), and pushfogcolor().
float oldfogend = 1000000
Referenced by popfogdist(), and pushfogdist().
float oldfogstart = 0
Referenced by popfogdist(), and pushfogdist().
GLint oldscissor[4] static
Referenced by popscissor(), and pushscissor().
matrix4 projmatrix
Referenced by disablepolygonoffset(), drawcubemap(), drawfogdome(), drawminimap(), drawreflection(), drawskybox(), enablepolygonoffset(), gl_drawframe(), renderavatar(), setcamprojmatrix(), and modelpreview::start().
bool renderedgame = false
Referenced by canaddparticles(), gl_drawframe(), and rendergame().
int scissoring = 0 static
Referenced by rendertarget::doblur(), shadowmaptexture::dorender(), popscissor(), pushscissor(), and rendertarget::render().
GLuint screenquadvbo = 0 static
Referenced by cleanupscreenquad(), screenquad(), and setupscreenquad().
LocalShaderParam screentexcoord[2] = { LocalShaderParam("screentexcoord0"), LocalShaderParam("screentexcoord1") } static
Referenced by setscreentexcoord().
const matrix4 viewmatrix(vec(-1, 0, 0), vec(0, 0, 1), vec(0,-1, 0))
Referenced by setcammatrix().
vec worldpos
Referenced by calcavatarpos(), calcspherescissor(), entautoview(), paintblendmap(), game::pointatplayer(), renderblendbrush(), game::selectcrosshair(), setcammatrix(), and game::updateweapons().
int xtraverts
Referenced by boxs(), boxsgrid(), sphere::draw(), fogdome::draw(), draw_char(), draw_text(), drawbb(), drawcubemap(), drawenvboxface(), drawenvoverlay(), drawminimap(), gui::drawskin(), gl_drawframe(), gl_drawhud(), gl_drawmainmenu(), maskreflection(), queryreflection(), gui::rect_(), render2dbox(), renderellipse(), renderentarrow(), renderentattachment(), renderentcone(), renderentring(), renderentselection(), rendermaterials(), rendermatgrid(), renderskyva(), rendertexturepanel(), renderwater(), and text_color().
int xtravertsva
Referenced by drawcubemap(), drawminimap(), gl_drawframe(), gl_drawhud(), gl_drawmainmenu(), vertmodel::vertmesh::render(), decalrenderer::render(), skelmodel::skelmesh::render(), renderblendbrush(), blobrenderer::renderblob(), renderdepthobstacles(), rendergrass(), renderoutline(), rendershadowmapreceivers(), renderva(), and renderzpass().
float zoomprogress = 0 static
Referenced by computezoom(), and disablezoom().