Inexor: inexor/model/rendermodel.hpp File Reference
rendermodel.hpp File Reference
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/model/model.hpp"
Classes
struct mapmodelinfo
Functions
void findanims (const char *pattern, vector< int > &anims)
mapmodelinfo * getmminfo (int i)
void startmodelquery (occludequery *query)
void endmodelquery ()
void preloadusedmapmodels (bool msg=false, bool bih=false)
static model * loadmapmodel (int n)
Class Documentation
struct mapmodelinfo
Class Members
model * m
string name
Function Documentation
void endmodelquery ()
References batchedmodel::attached, modelbatch::batched, vector< T, MINSIZE >::empty(), endquery, model::endrender(), occludequery::fragments, vector< T, MINSIZE >::last(), vector< T, MINSIZE >::length(), loopi(), modelbatch::m, inexor::rpc::min(), modelquery, vector< T, MINSIZE >::pop(), batchedmodel::query, renderbatchedmodel(), vector< T, MINSIZE >::setsize(), startquery, and model::startrender().
Referenced by rendermapmodels().
void findanims (const char * pattern, vector< int > & anims)
References vector< T, MINSIZE >::add(), animnames, loopi(), and matchanim().
Referenced by guimodelpreview(), vertcommands< MDL >::setanim(), and skelcommands< MDL >::setanim().
mapmodelinfo* getmminfo (int i)
References vector< T, MINSIZE >::inrange().
Referenced by preloadusedmapmodels(), and rendermapmodel().
static model* loadmapmodel (int n) inline static
References vector< T, MINSIZE >::inrange(), loadmodel(), and mapmodels.
Referenced by dropentity(), entselectionbox(), getentboundingbox(), mmcollide(), mmintersect(), and modifyoctaentity().
void preloadusedmapmodels (bool msg = false, bool bih = false)
References vector< T, MINSIZE >::add(), entity::attr2, entities::ents, ET_MAPMODEL, vector< T, MINSIZE >::find(), entities::getents(), getmminfo(), vector< T, MINSIZE >::length(), loadmodel(), loadprogress, Log, loopv, mapmodelinfo::m, mapmodels, mapmodelinfo::name, model::preloadBIH(), model::preloadmeshes(), inexor::util::log_manager::std, and entity::type.
Referenced by calclight(), load_world(), and patchlight().
void startmodelquery (occludequery * query)
Referenced by rendermapmodels().