Inexor: inexor/engine/serverbrowser.cpp File Reference
serverbrowser.cpp File Reference
#include <algorithm>
#include "SDL_keycode.h"
#include "SDL_mutex.h"
#include "SDL_thread.h"
#include "SDL_timer.h"
#include <enet/enet.h>
#include "inexor/engine/renderbackground.hpp"
#include "inexor/io/input/InputRouter.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct resolverthread
struct resolverresult
Macros
#define RESOLVERTHREADS 2
#define RESOLVERLIMIT 3000
Functions
int resolverloop (void *data)
void resolverinit ()
void resolverstop (resolverthread &rt)
void resolverclear ()
void resolverquery (const char *name)
bool resolvercheck (const char **name, ENetAddress *address)
bool resolverwait (const char *name, ENetAddress *address)
Variables
vector< resolverthread > resolverthreads
vector< const char * > resolverqueries
vector< resolverresult > resolverresults
SDL_mutex * resolvermutex
SDL_cond * querycond
SDL_cond * resultcond
Class Documentation
struct resolverthread
Class Members
const char * query
int starttime
SDL_Thread * thread
struct resolverresult
Class Members
ENetAddress address
const char * query
Macro Definition Documentation
#define RESOLVERLIMIT 3000
Referenced by resolvercheck(), and resolverwait().
#define RESOLVERTHREADS 2
Referenced by resolverinit().
Function Documentation
bool resolvercheck (const char ** name, ENetAddress * address)
References resolverresult::address, loopv, resolverthread::query, resolverresult::query, RESOLVERLIMIT, resolvermutex, resolverresults, resolverstop(), resolverthreads, resolverthread::starttime, and totalmillis.
void resolverclear ()
References loopv, resolvermutex, resolverqueries, resolverresults, resolverstop(), and resolverthreads.
void resolverinit ()
References loopi(), resolverthread::query, querycond, resolverloop(), resolvermutex, resolverthreads, RESOLVERTHREADS, resultcond, resolverthread::starttime, and resolverthread::thread.
Referenced by resolverquery(), and resolverwait().
int resolverloop (void * data)
References resolverresult::address, resolverthread::query, resolverresult::query, querycond, resolvermutex, resolverqueries, resolverresults, resultcond, resolverthread::starttime, resolverthread::thread, recorder::thread, and totalmillis.
Referenced by resolverinit(), and resolverstop().
void resolverquery (const char * name)
References querycond, resolverinit(), resolvermutex, resolverqueries, and resolverthreads.
void resolverstop (resolverthread & rt)
References resolverthread::query, resolverloop(), resolvermutex, resolverthread::starttime, and resolverthread::thread.
Referenced by resolvercheck(), resolverclear(), and resolverwait().
bool resolverwait (const char * name, ENetAddress * address)
References defformatstring, f(), inexor::io::input_router, inexor::io::InputRouter::interceptkey(), loopv, inexor::rpc::min(), resolverthread::query, querycond, renderprogress(), resolverinit(), RESOLVERLIMIT, resolvermutex, resolverqueries, resolverresults, resolverstop(), resolverthreads, resultcond, and recorder::starttime.
Variable Documentation
SDL_cond* querycond
Referenced by resolverinit(), resolverloop(), resolverquery(), and resolverwait().
SDL_mutex* resolvermutex
Referenced by resolvercheck(), resolverclear(), resolverinit(), resolverloop(), resolverquery(), resolverstop(), and resolverwait().
vector<const char *> resolverqueries
Referenced by resolverclear(), resolverloop(), resolverquery(), and resolverwait().
vector<resolverresult> resolverresults
Referenced by resolvercheck(), resolverclear(), resolverloop(), and resolverwait().
vector<resolverthread> resolverthreads
Referenced by resolvercheck(), resolverclear(), resolverinit(), resolverquery(), and resolverwait().
SDL_cond * resultcond
Referenced by resolverinit(), resolverloop(), and resolverwait().