Inexor: inexor/engine/shadowmap.cpp File Reference
shadowmap.cpp File Reference
#include <SDL_opengl.h>
#include <math.h>
#include <algorithm>
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/rendertarget.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/shadowmap.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
Classes
struct shadowmaptexture
Macros
#define SHADOWSKEW 0.7071068f
Functions
VARP (shadowmap, 0, 0, 1)
void cleanshadowmap ()
VARFP (shadowmapsize, 7, 9, 11, cleanshadowmap())
VARP (shadowmapradius, 64, 96, 256)
VAR (shadowmapheight, 0, 32, 128)
VARP (shadowmapdist, 128, 256, 512)
VARFP (fpshadowmap, 0, 0, 1, cleanshadowmap())
VARFP (shadowmapprecision, 0, 0, 1, cleanshadowmap())
HVARFR (shadowmapambient, 0, 0, 0xFFFFFF,{if(shadowmapambient<=255) shadowmapambient|=(shadowmapambient<< 8)|(shadowmapambient<< 16);shadowmapambientcolor=bvec((shadowmapambient >>16)&0xFF,(shadowmapambient >>8)&0xFF, shadowmapambient &0xFF);})
VARP (shadowmapintensity, 0, 40, 100)
VARP (blurshadowmap, 0, 1, 3)
VARP (blursmsigma, 1, 100, 200)
VAR_NOSYNC (shadowmapcasters, 1, 0, 0)
void setshadowdir (int angle)
VARFR (shadowmapangle, 0, 0, 360, setshadowdir(shadowmapangle))
void guessshadowdir ()
VARP (shadowmapbias, 0, 5, 1024)
VARP (shadowmappeelbias, 0, 20, 1024)
VAR (smdepthpeel, 0, 1, 1)
VAR (smoothshadowmappeel, 1, 0, 0)
void calcshadowmapbb (const vec &o, float xyrad, float zrad, float &x1, float &y1, float &x2, float &y2)
bool addshadowmapcaster (const vec &o, float xyrad, float zrad)
bool isshadowmapreceiver (vtxarray *va)
bool isshadowmapcaster (const vec &o, float rad)
void pushshadowmap ()
void popshadowmap ()
void rendershadowmap ()
VAR (debugsm, 0, 0, 1)
void viewshadowmap ()
Variables
bool hasVAO
bool hasFBO
bool hasAFBO
bool hasDS
bool hasTF
bool hasTRG
bool hasTSW
bool hasS3TC
bool hasFXT1
bool hasAF
bool hasFBB
bool hasUBO
bool hasMBR
bvec shadowmapambientcolor (0, 0, 0)
vec shadowoffset (0, 0, 0)
vec shadowfocus (0, 0, 0)
vec shadowdir (0, SHADOWSKEW, 1)
float shadowmapmaxz = 0
bool shadowmapping = false
matrix4 shadowmatrix
shadowmaptexture shadowmaptex
Macro Definition Documentation
#define SHADOWSKEW 0.7071068f
Referenced by guessshadowdir(), isshadowmapcaster(), isshadowmapreceiver(), and setshadowdir().
Function Documentation
bool addshadowmapcaster (const vec & o, float xyrad, float zrad)
References rendertarget::addblurtiles(), calcshadowmapbb(), inexor::rpc::max(), shadowfocus, shadowmapcasters, and shadowmaptex.
Referenced by cullmodel().
void calcshadowmapbb (const vec & o, float xyrad, float zrad, float & x1, float & y1, float & x2, float & y2)
References camera1, inexor::rpc::max(), inexor::rpc::min(), physent::o, physent::pitch, RAD, vec::rotate_around_z(), shadowdir, shadowoffset, vec::sub(), and physent::yaw.
Referenced by addshadowmapcaster(), and isshadowmapreceiver().
void cleanshadowmap ()
References rendertarget::cleanup(), and shadowmaptex.
Referenced by resetgl().
void guessshadowdir ()
References vec::add(), entity::attr1, dir, vec::div(), entities::ents, ET_GAMESPECIFIC, ET_LIGHT, ET_MAPMODEL, entities::getents(), vec::iszero(), loopv, vec::mul(), vec::normalize(), entity::o, shadowdir, SHADOWSKEW, vec::sub(), sunlightdir, and entity::type.
Referenced by allchanged().
HVARFR (shadowmapambient , 0 , 0 , 0xFFFFFF , {if(shadowmapambient<=255) shadowmapambient|=(shadowmapambient<< 8)|(shadowmapambient<< 16);shadowmapambientcolor=bvec((shadowmapambient >>16)&0xFF,(shadowmapambient >>8)&0xFF, shadowmapambient &0xFF);})
bool isshadowmapcaster (const vec & o, float rad)
References shadowdir, shadowfocus, and SHADOWSKEW.
Referenced by cullmodel().
bool isshadowmapreceiver (vtxarray * va)
References vec::add(), calcshadowmapbb(), rendertarget::checkblurtiles(), f(), inexor::rpc::max(), vec::mul(), vtxarray::o, shadowdir, shadowfocus, shadowmap, shadowmapcasters, vtxarray::shadowmapmax, vtxarray::shadowmapmin, shadowmaptex, SHADOWSKEW, vtxarray::size, and SQRT2.
Referenced by rendershadowmapreceivers(), and renderva().
void popshadowmap ()
References rendertarget::rendertex, shadowmap, and shadowmaptex.
Referenced by rendergeom().
void pushshadowmap ()
References ambientcolor, f(), glActiveTexture_, GLOBALPARAM, GLOBALPARAMF, inexor::rpc::max(), matrix4::projective(), rendertarget::rendertex, shadowmap, shadowmapambientcolor, shadowmaptex, shadowmatrix, and skylightcolor.
Referenced by rendergeom().
void rendershadowmap ()
References f(), rendertarget::render(), shadowmap, and shadowmaptex.
Referenced by rendergeom().
void setshadowdir (int angle)
References RAD, vec::rotate_around_z(), shadowdir, and SHADOWSKEW.
VAR (shadowmapheight , 0 , 32 , 128)
VAR (smdepthpeel , 0 , 1 , 1)
VAR (smoothshadowmappeel , 1 , 0 , 0)
VAR (debugsm , 0 , 0 , 1)
VAR_NOSYNC (shadowmapcasters , 1 , 0 , 0)
VARFP (shadowmapsize , 7 , 9 , 11 , cleanshadowmap())
VARFP (fpshadowmap , 0 , 0 , 1 , cleanshadowmap())
VARFP (shadowmapprecision , 0 , 0 , 1 , cleanshadowmap())
VARFR (shadowmapangle , 0 , 0 , 360 , setshadowdir(shadowmapangle))
VARP (shadowmap , 0 , 0 , 1)
VARP (shadowmapradius , 64 , 96 , 256)
VARP (shadowmapdist , 128 , 256 , 512)
VARP (shadowmapintensity , 0 , 40 , 100)
VARP (blurshadowmap , 0 , 1 , 3)
VARP (blursmsigma , 1 , 100 , 200)
VARP (shadowmapbias , 0 , 5 , 1024)
VARP (shadowmappeelbias , 0 , 20 , 1024)
void viewshadowmap ()
References rendertarget::debug(), shadowmap, and shadowmaptex.
Referenced by gl_drawhud().
Variable Documentation
bool hasAF
Referenced by gl_checkextensions(), and setuptexparameters().
bool hasAFBO
Referenced by gl_checkextensions().
bool hasDS
Referenced by genwatertex(), gl_checkextensions(), and maskreflection().
bool hasFBB
Referenced by gl_checkextensions(), and recorder::readbuffer().
bool hasFBO
Referenced by gl_checkextensions().
bool hasFXT1
Referenced by gl_checkextensions().
bool hasMBR
Referenced by gl_checkextensions().
bool hasS3TC
Referenced by gendds(), gl_checkextensions(), and loaddds().
bool hasTF
Referenced by depthfxtexture::colorformats(), shadowmaptexture::colorformats(), and gl_checkextensions().
bool hasTRG
Referenced by depthfxtexture::colorformats(), BlendBrush::gentex(), and gl_checkextensions().
bool hasTSW
Referenced by gl_checkextensions().
bool hasUBO
Referenced by bindglsluniform(), and gl_checkextensions().
bool hasVAO
Referenced by gl_checkextensions().
vec shadowdir(0, SHADOWSKEW, 1)
Referenced by calcshadowmapbb(), calcshadowmask(), shadowmaptexture::dorender(), guessshadowdir(), isshadowmapcaster(), isshadowmapreceiver(), and setshadowdir().
vec shadowfocus(0, 0, 0)
Referenced by addshadowmapcaster(), shadowmaptexture::dorender(), isshadowmapcaster(), and isshadowmapreceiver().
bvec shadowmapambientcolor(0, 0, 0)
Referenced by pushshadowmap().
float shadowmapmaxz = 0
bool shadowmapping = false
Referenced by animmodel::skin::bind(), canaddparticles(), cullmodel(), endmodelbatches(), animmodel::part::render(), renderbatchedmodel(), rendergame(), and rendermodel().
shadowmaptexture shadowmaptex static
Referenced by addshadowmapcaster(), cleanshadowmap(), isshadowmapreceiver(), popshadowmap(), pushshadowmap(), rendershadowmap(), and viewshadowmap().
matrix4 shadowmatrix
Referenced by pushshadowmap(), and animmodel::part::render().
vec shadowoffset(0, 0, 0)
Referenced by calcshadowmapbb(), and shadowmaptexture::dorender().