Inexor: inexor/engine/shader.cpp File Reference
shader.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <ctype.h>
#include <math.h>
#include <stdio.h>
#include <memory>
#include "SDL_opengl.h"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/rendertarget.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/io/Error.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_unicode.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/legacy/menus.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct postfxtex
struct postfxpass
Macros
#define UNIFORMTEX(name, tmu)
#define SETSLOTPARAM(l, mask, i, val)
#define SETSLOTPARAMS(slotparams)
#define SETDEFAULTPARAMS
#define GENSHADER(cond, body)
#define NUMPOSTFXBINDS 10
Functions
VAR (reservevpparams, 1, 16, 0)
VAR (maxvsuniforms, 1, 0, 0)
VAR (maxfsuniforms, 1, 0, 0)
VAR (maxvaryings, 1, 0, 0)
VAR (dbgshader, 0, 0, 2)
void loadshaders ()
Shader * lookupshaderbyname (const char *name)
Shader * generateshader (const char *name, const char *fmt,...)
static void showglslinfo (GLenum type, GLuint obj, const char *name, const char **parts=nullptr, int numparts=0)
static void compileglslshader (GLenum type, GLuint &obj, const char *def, const char *name, bool msg=true)
VAR (dbgubo, 0, 0, 1)
static void bindglsluniform (Shader &s, UniformLoc &u)
static void linkglslprogram (Shader &s, bool msg=true)
int getlocalparam (const char *name)
static int addlocalparam (Shader &s, const char *name, int loc, int size, GLenum format)
GlobalShaderParamState * getglobalparam (const char *name)
static GlobalShaderParamUse * addglobalparam (Shader &s, GlobalShaderParamState *param, int loc, int size, GLenum format)
static void setglsluniformformat (Shader &s, const char *name, GLenum format, int size)
static void allocglslactiveuniforms (Shader &s)
static float * findslotparam (Slot &s, const char *name, float *noval=nullptr)
static float * findslotparam (VSlot &s, const char *name, float *noval=nullptr)
static void setslotparam (SlotShaderParamState &l, const float *val)
VARF (shaderprecision, 0, 0, 2, initwarning("shader quality"))
static void genattriblocs (Shader &s, const char *vs, const char *ps, Shader *reusevs, Shader *reuseps)
static void genuniformlocs (Shader &s, const char *vs, const char *ps, Shader *reusevs, Shader *reuseps)
Shader * newshader (int type, const char *name, const char *vs, const char *ps, Shader *variant=nullptr, int row=0)
void setupshaders ()
static const char * findglslmain (const char *s)
static void gengenericvariant (Shader &s, const char *sname, const char *vs, const char *ps, int row=0)
static bool genwatervariant (Shader &s, const char *sname, const char *vs, const char *ps, int row=2)
bool minimizedynlighttcusage ()
static void gendynlightvariant (Shader &s, const char *sname, const char *vs, const char *ps, int row=0)
static void genshadowmapvariant (Shader &s, const char *sname, const char *vs, const char *ps, int row=1)
static void genfogshader (vector< char > &vsbuf, vector< char > &psbuf, const char *vs, const char *ps)
static void genuniformdefs (vector< char > &vsbuf, vector< char > &psbuf, const char *vs, const char *ps, Shader *variant=nullptr)
VAR (defershaders, 0, 1, 1)
void defershader (int *type, const char *name, const char *contents)
void fixshaderdetail ()
VARFP (shaderdetail, 0, MAXSHADERDETAIL, MAXSHADERDETAIL, fixshaderdetail())
Shader * useshaderbyname (const char *name)
void shader (int *type, char *name, char *vs, char *ps)
void variantshader (int *type, char *name, int *row, char *vs, char *ps)
void setshader (char *name)
void resetslotshader ()
void setslotshader (Slot &s)
static void linkslotshaderparams (vector< SlotShaderParam > &params, Shader *sh, bool load)
void linkslotshader (Slot &s, bool load)
void linkvslotshader (VSlot &s, bool load)
void altshader (char *origname, char *altname)
void fastshader (char *nice, char *fast, int *detail)
COMMAND (shader,"isss")
COMMAND (variantshader,"isiss")
COMMAND (setshader,"s")
COMMAND (altshader,"ss")
COMMAND (fastshader,"ssi")
COMMAND (defershader,"iss")
ICOMMAND (forceshader,"s",(const char *name), useshaderbyname(name))
ICOMMAND (isshaderdefined,"s",(char *name), intret(lookupshaderbyname(name)?1:0))
const char * getshaderparamname (const char *name, bool insert)
void addslotparam (const char *name, float x, float y, float z, float w)
ICOMMAND (defuniformparam,"sffff",(char *name, float *x, float *y, float *z, float *w), addslotparam(name,*x,*y,*z,*w))
ICOMMAND (setshaderparam,"sffff",(char *name, float *x, float *y, float *z, float *w), addslotparam(name,*x,*y,*z,*w))
ICOMMAND (setuniformparam,"sffff",(char *name, float *x, float *y, float *z, float *w), addslotparam(name,*x,*y,*z,*w))
static int allocatepostfxtex (int scale)
void cleanuppostfx (bool fullclean)
void renderpostfx ()
static bool addpostfx (const char *name, int outputbind, int outputscale, uint inputs, uint freeinputs, const vec4 &params)
void clearpostfx ()
COMMAND (clearpostfx,"")
ICOMMAND (addpostfx,"siisffff",(char *name, int *bind, int *scale, char *inputs, float *x, float *y, float *z, float *w),{int inputmask=inputs[0]?0:1;int freemask=inputs[0]?0:1;bool freeinputs=true;for(;*inputs;inputs++) if(isdigit(*inputs)){inputmask|=1<<(*inputs-'0');if(freeinputs) freemask|=1<<(*inputs-'0');}else if(*inputs=='+') freeinputs=false;else if(*inputs=='-') freeinputs=true;inputmask &=(1<< NUMPOSTFXBINDS)-1;freemask &=(1<< NUMPOSTFXBINDS)-1;addpostfx(name, clamp(*bind, 0, NUMPOSTFXBINDS-1), max(*scale, 0), inputmask, freemask, vec4(*x,*y,*z,*w));})
ICOMMAND (setpostfx,"sffff",(char *name, float *x, float *y, float *z, float *w),{clearpostfx();if(name[0]) addpostfx(name, 0, 0, 1, 1, vec4(*x,*y,*z,*w));})
void cleanupshaders ()
void reloadshaders ()
void setupblurkernel (int radius, float sigma, float *weights, float *offsets)
void setblurshader (int pass, int size, int radius, float *weights, float *offsets)
Variables
Shader * nullshader = nullptr
Shader * hudshader = nullptr
Shader * hudnotextureshader = nullptr
Shader * textureshader = nullptr
Shader * notextureshader = nullptr
Shader * nocolorshader = nullptr
Shader * foggedshader = nullptr
Shader * foggednotextureshader = nullptr
Shader * stdworldshader = nullptr
static hashnameset
< GlobalShaderParamState > globalparams (256)
static hashtable< const char
*, int > localparams (256)
static hashnameset< Shader > shaders (256)
static Shader * slotshader = nullptr
static vector< SlotShaderParam > slotparams
static bool standardshaders = false
static bool forceshaders = true
static bool loadedshaders = false
static hashset< const char * > shaderparamnames (256)
vector< postfxtex > postfxtexs
int postfxbinds [NUMPOSTFXBINDS]
GLuint postfxfb = 0
int postfxw = 0
int postfxh = 0
vector< postfxpass > postfxpasses
Macro Definition Documentation
#define GENSHADER (cond, body)
Value:
if(cond) \
    { \
        if(vsbuf.length()) { vsbak.setsize(0); vsbak.put(vs, strlen(vs)+1); vs = vsbak.getbuf(); vsbuf.setsize(0); } \
        if(psbuf.length()) { psbak.setsize(0); psbak.put(ps, strlen(ps)+1); ps = psbak.getbuf(); psbuf.setsize(0); } \
        body; \
        if(vsbuf.length()) vs = vsbuf.getbuf(); \
        if(psbuf.length()) ps = psbuf.getbuf(); \
    }
Referenced by shader(), and variantshader().
#define NUMPOSTFXBINDS 10
Referenced by renderpostfx().
#define SETDEFAULTPARAMS
Value:
loopv(defaultparams) \
    { \
        SlotShaderParamState &l = defaultparams[i]; \
        SETSLOTPARAM(l, unimask, i, l.val); \
    }
Referenced by Shader::setslotparams().
#define SETSLOTPARAM (l, mask, i, val)
Value:
do { \
    if(!(mask&(1<<i))) { \
        mask |= 1<<i; \
        setslotparam(l, val); \
    } \
} while(0)
#define SETSLOTPARAMS (slotparams)
Value:
loopv(slotparams) \
    { \
        SlotShaderParam &p = slotparams[i]; \
        if(!defaultparams.inrange(p.loc)) continue; \
        SlotShaderParamState &l = defaultparams[p.loc]; \
        SETSLOTPARAM(l, unimask, p.loc, p.val); \
    }
Referenced by Shader::setslotparams().
#define UNIFORMTEX (name, tmu)
Value:
{ \
            loc = glGetUniformLocation_(program, name); \
            int val = tmu; \
            if(loc != -1) glUniform1i_(loc, val); \
        }
Referenced by Shader::allocparams().
Function Documentation
static GlobalShaderParamUse* addglobalparam (Shader & s, GlobalShaderParamState * param, int loc, int size, GLenum format) static
References vector< T, MINSIZE >::add(), ShaderParamBinding::format, format(), Shader::globalparams, ShaderParamBinding::loc, GlobalShaderParamUse::param, ShaderParamBinding::size, and GlobalShaderParamUse::version.
Referenced by setglsluniformformat().
static int addlocalparam (Shader & s, const char * name, int loc, int size, GLenum format) static
References vector< T, MINSIZE >::add(), ShaderParamBinding::format, format(), getlocalparam(), vector< T, MINSIZE >::length(), ShaderParamBinding::loc, Shader::localparamremap, Shader::localparams, LocalShaderParamState::name, vector< T, MINSIZE >::pad(), and ShaderParamBinding::size.
Referenced by setglsluniformformat().
static bool addpostfx (const char * name, int outputbind, int outputscale, uint inputs, uint freeinputs, const vec4 & params) static
References postfxpass::freeinputs, postfxpass::inputs, Log, postfxpass::outputbind, postfxpass::outputscale, postfxpass::params, postfxpasses, postfxpass::shader, inexor::util::log_manager::std, and useshaderbyname().
void addslotparam (const char * name, float x, float y, float z, float w)
References vector< T, MINSIZE >::add(), getshaderparamname(), loopv, SlotShaderParam::name, slotparams, and SlotShaderParam::val.
static int allocatepostfxtex (int scale) static
References createtexture(), postfxtex::id, loopv, inexor::rpc::max(), postfxtexs, postfxtex::scale, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, anonymous_namespace{utilTest.cpp}::t(), and postfxtex::used.
Referenced by renderpostfx().
static void allocglslactiveuniforms (Shader & s) static
References format(), GLenum(), glGetActiveUniform_, glGetProgramiv_, loopi(), Shader::program, and setglsluniformformat().
Referenced by Shader::allocparams().
void altshader (char * origname, char * altname)
References Shader::altshader, Shader::fixdetailshader(), and shaders.
Referenced by Shader::cleanup().
static void bindglsluniform (Shader & s, UniformLoc & u) static
References UniformLoc::binding, UniformLoc::blockname, GL_INVALID_INDEX, GL_UNIFORM_ARRAY_STRIDE, GL_UNIFORM_BLOCK_DATA_SIZE, GL_UNIFORM_OFFSET, glGetActiveUniformBlockiv_, glGetActiveUniformsiv_, glGetUniformBlockIndex_, glGetUniformIndices_, glGetUniformLocation_, GLuint(), glUniformBlockBinding_, hasUBO, UniformLoc::loc, UniformLoc::name, UniformLoc::offset, Shader::program, UniformLoc::size, and UniformLoc::stride.
Referenced by linkglslprogram().
void cleanuppostfx (bool fullclean)
References glDeleteFramebuffers_, loopv, postfxfb, postfxh, postfxtexs, and postfxw.
Referenced by cleanupshaders(), clearpostfx(), and renderpostfx().
void cleanupshaders ()
References Shader::cleanup(), cleanuppostfx(), enumerate, foggednotextureshader, foggedshader, glUseProgram_, hudnotextureshader, hudshader, Shader::lastshader, nocolorshader, notextureshader, nullshader, shaders, stdworldshader, and textureshader.
Referenced by resetgl().
void clearpostfx ()
References cleanuppostfx(), and postfxpasses.
COMMAND (shader , "isss")
COMMAND (variantshader , "isiss")
COMMAND (setshader , "s")
COMMAND (altshader , "ss")
COMMAND (fastshader , "ssi")
COMMAND (defershader , "iss")
COMMAND (clearpostfx , "")
static void compileglslshader (GLenum type, GLuint & obj, const char * def, const char * name, bool msg = true) static
References glCompileShader_, glCreateShader_, glDeleteShader_, glGetShaderiv_, glShaderSource_, glslversion, loopi(), parts, and showglslinfo().
Referenced by Shader::compile().
void defershader (int * type, const char * name, const char * contents)
References Shader::defer, DELETEA, execute(), Shader::invalid(), Shader::name, newstring(), SHADER_DEFERRED, shaders, Shader::standard, standardshaders, and Shader::type.
void fastshader (char * nice, char * fast, int * detail)
References Shader::fastshader, Shader::fixdetailshader(), hmap::fs, loopi(), MAXSHADERDETAIL, inexor::rpc::min(), and shaders.
Referenced by Shader::cleanup().
static const char* findglslmain (const char * s) static
References main().
Referenced by gendynlightvariant(), genfogshader(), genshadowmapvariant(), genuniformdefs(), and genwatervariant().
static float* findslotparam (Slot & s, const char * name, float * noval = nullptr) static
References Shader::defaultparams, loopv, LocalShaderParamState::name, SlotShaderParam::name, Slot::params, Slot::shader, SlotShaderParam::val, and SlotShaderParamState::val.
Referenced by findslotparam(), and linkvslotshader().
static float* findslotparam (VSlot & s, const char * name, float * noval = nullptr) static
References findslotparam(), loopv, SlotShaderParam::name, VSlot::params, VSlot::slot, and SlotShaderParam::val.
void fixshaderdetail ()
References Shader::detailshader, enumerate, Shader::fixdetailshader(), linkslotshaders(), and shaders.
static void genattriblocs (Shader & s, const char * vs, const char * ps, Shader * reusevs, Shader * reuseps) static
References vector< T, MINSIZE >::add(), Shader::attriblocs, and getshaderparamname().
Referenced by newshader().
static void gendynlightvariant (Shader & s, const char * sname, const char * vs, const char * ps, int row = 0) static
References gle::color(), defformatstring, dir, findglslmain(), genwatervariant(), vector< T, MINSIZE >::getbuf(), loopi(), loopk, MAXDYNLIGHTS, inexor::rpc::min(), minimizedynlighttcusage(), newshader(), vector< T, MINSIZE >::put(), vector< T, MINSIZE >::setsize(), and Shader::type.
Referenced by genshadowmapvariant(), shader(), and variantshader().
Shader* generateshader (const char * name, const char * fmt, ...)
References defvformatstring, execute(), loadedshaders, lookupshaderbyname(), nullshader, and standardshaders.
Referenced by animmodel::skin::loadshader().
static void genfogshader (vector< char > & vsbuf, vector< char > & psbuf, const char * vs, const char * ps) static
References findglslmain(), iscubealpha(), iscubespace(), and vector< T, MINSIZE >::put().
Referenced by shader(), and variantshader().
static void gengenericvariant (Shader & s, const char * sname, const char * vs, const char * ps, int row = 0) static
References copystring(), defformatstring, gle::end(), formatstring(), vector< T, MINSIZE >::getbuf(), MAXVARIANTROWS, newshader(), Shader::numvariants(), vector< T, MINSIZE >::put(), and Shader::type.
Referenced by variantshader().
static void genshadowmapvariant (Shader & s, const char * sname, const char * vs, const char * ps, int row = 1) static
References defformatstring, findglslmain(), gendynlightvariant(), genwatervariant(), vector< T, MINSIZE >::getbuf(), newshader(), vector< T, MINSIZE >::put(), and Shader::type.
Referenced by shader().
static void genuniformdefs (vector< char > & vsbuf, vector< char > & psbuf, const char * vs, const char * ps, Shader * variant = nullptr) static
References defformatstring, vector< T, MINSIZE >::empty(), findglslmain(), loopv, vector< T, MINSIZE >::put(), and slotparams.
Referenced by shader(), and variantshader().
static void genuniformlocs (Shader & s, const char * vs, const char * ps, Shader * reusevs, Shader * reuseps) static
References vector< T, MINSIZE >::add(), getshaderparamname(), and Shader::uniformlocs.
Referenced by newshader().
static bool genwatervariant (Shader & s, const char * sname, const char * vs, const char * ps, int row = 2) static
References defformatstring, findglslmain(), vector< T, MINSIZE >::getbuf(), newshader(), vector< T, MINSIZE >::put(), and Shader::type.
Referenced by gendynlightvariant(), genshadowmapvariant(), and shader().
GlobalShaderParamState* getglobalparam (const char * name)
References globalparams, GlobalShaderParamState::name, and GlobalShaderParamState::version.
Referenced by GlobalShaderParam::resolve().
int getlocalparam (const char * name)
References localparams.
Referenced by addlocalparam(), and LocalShaderParam::resolve().
const char* getshaderparamname (const char * name, bool insert)
References newstring(), and shaderparamnames.
Referenced by addslotparam(), genattriblocs(), genuniformlocs(), linkvslotshader(), loadvslot(), setglsluniformformat(), unpackvslot(), and vshaderparam().
ICOMMAND (forceshader , "s" , (const char *name) , useshaderbyname(name))
ICOMMAND (isshaderdefined , "s" , (char *name) , intret(lookupshaderbyname(name)?1:0))
ICOMMAND (defuniformparam , "sffff" , (char *name, float *x, float *y, float *z, float *w) , addslotparam(name,*x,*y,*z,*w))
ICOMMAND (setshaderparam , "sffff" , (char *name, float *x, float *y, float *z, float *w) , addslotparam(name,*x,*y,*z,*w))
ICOMMAND (setuniformparam , "sffff" , (char *name, float *x, float *y, float *z, float *w) , addslotparam(name,*x,*y,*z,*w))
ICOMMAND (addpostfx , "siisffff" , (char *name, int *bind, int *scale, char *inputs, float *x, float *y, float *z, float *w) , {int inputmask=inputs[0]?0:1;int freemask=inputs[0]?0:1;bool freeinputs=true;for(;*inputs;inputs++) if(isdigit(*inputs)){inputmask|=1<<(*inputs-'0');if(freeinputs) freemask|=1<<(*inputs-'0');}else if(*inputs=='+') freeinputs=false;else if(*inputs=='-') freeinputs=true;inputmask &=(1<< NUMPOSTFXBINDS)-1;freemask &=(1<< NUMPOSTFXBINDS)-1;addpostfx(name, clamp(*bind, 0, NUMPOSTFXBINDS-1), max(*scale, 0), inputmask, freemask, vec4(*x,*y,*z,*w));})
ICOMMAND (setpostfx , "sffff" , (char *name, float *x, float *y, float *z, float *w) , {clearpostfx();if(name[0]) addpostfx(name, 0, 0, 1, 1, vec4(*x,*y,*z,*w));})
static void linkglslprogram (Shader & s, bool msg = true) static
References Shader::attriblocs, gle::attribnames, bindglsluniform(), Shader::defaultparams, glAttachShader_, glBindAttribLocation_, glCreateProgram_, glDeleteProgram_, glGetProgramiv_, glGetUniformLocation_, glLinkProgram_, glUniform1i_, glUseProgram_, ShaderParamBinding::loc, AttribLoc::loc, loopi(), loopv, gle::MAXATTRIBS, LocalShaderParamState::name, AttribLoc::name, Shader::name, Shader::program, Shader::psobj, showglslinfo(), Shader::uniformlocs, and Shader::vsobj.
Referenced by Shader::compile().
void linkslotshader (Slot & s, bool load)
References Shader::detailshader, Shader::fixdetailshader(), linkslotshaderparams(), Slot::params, and Slot::shader.
Referenced by linkslotshaders(), Slot::load(), and Slot::loadthumbnail().
static void linkslotshaderparams (vector< SlotShaderParam > & params, Shader * sh, bool load) static
References Shader::defaultparams, SlotShaderParam::loc, loopv, LocalShaderParamState::name, SlotShaderParam::name, SlotShaderParam::val, and SlotShaderParamState::val.
Referenced by linkslotshader(), and linkvslotshader().
void linkvslotshader (VSlot & s, bool load)
References vec::clamp(), Shader::detailshader, findslotparam(), getshaderparamname(), VSlot::glowcolor, linkslotshaderparams(), VSlot::params, Slot::shader, VSlot::slot, TEX_GLOW, and Slot::texmask.
Referenced by linkslotshaders(), Slot::loadthumbnail(), lookupmaterialslot(), and lookupvslot().
void loadshaders ()
References dummyslot, execfile(), fatal(), foggednotextureshader, foggedshader, hudnotextureshader, hudshader, loadedshaders, lookupshaderbyname(), nocolorshader, notextureshader, nullshader, Shader::set(), Slot::shader, standardshaders, stdworldshader, and textureshader.
Referenced by main(), and reloadshaders().
Shader* lookupshaderbyname (const char * name)
References Shader::loaded(), and shaders.
Referenced by changeshader(), generateshader(), loadshaders(), mdlshader(), particleinit(), renderfoggedvas(), setblurshader(), modelcommands< MDL, struct MDL::vertmesh >::setshader(), shader(), and variantshader().
bool minimizedynlighttcusage ()
Referenced by gendynlightvariant(), and setdynlights().
Shader* newshader (int type, const char * name, const char * vs, const char * ps, Shader * variant = nullptr, int row = 0)
References vector< T, MINSIZE >::add(), Shader::attriblocs, Shader::cleanup(), Shader::compile(), Shader::defaultparams, Shader::defer, DELETEA, Shader::fixdetailshader(), Shader::forced, forceshaders, genattriblocs(), genuniformlocs(), Shader::getvariant(), glUseProgram_, Shader::lastshader, loopv, Shader::name, newstring(), Shader::psstr, Shader::reuseps, Shader::reusevs, vector< T, MINSIZE >::setsize(), shaders, slotparams, Shader::standard, standardshaders, Shader::type, Shader::uniformlocs, Shader::variantshader, and Shader::vsstr.
Referenced by gendynlightvariant(), gengenericvariant(), genshadowmapvariant(), genwatervariant(), setupshaders(), shader(), and variantshader().
void reloadshaders ()
References Shader::cleanup(), Shader::compile(), defformatstring, enumerate, identflags, IDF_PERSIST, Shader::invalid(), linkslotshaders(), loadshaders(), loopv, renderprogress(), Shader::reuseps, Shader::reusevs, SHADER_DEFERRED, SHADER_INVALID, shaders, and Shader::variants.
Referenced by resetgl().
void renderpostfx ()
References allocatepostfxtex(), cleanuppostfx(), f(), postfxpass::freeinputs, GL_COLOR_ATTACHMENT0, GL_FRAMEBUFFER, glActiveTexture_, glBindFramebuffer_, glFramebufferTexture2D_, glGenFramebuffers_, GLOBALPARAMF, postfxpass::inputs, lastmillis, LOCALPARAM, LOCALPARAMF, loopi(), loopj, loopv, inexor::rpc::max(), NUMPOSTFXBINDS, postfxpass::outputbind, postfxpass::outputscale, postfxpass::params, postfxfb, postfxh, postfxpasses, postfxtexs, postfxw, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, screenquad(), inexor::rendering::screen::ScreenManager::screenw, Shader::set(), and postfxpass::shader.
Referenced by gl_drawframe(), and gl_drawmainmenu().
void resetslotshader ()
References vector< T, MINSIZE >::shrink(), slotparams, and slotshader.
Referenced by clearslots(), and texturereset().
void setblurshader (int pass, int size, int radius, float * weights, float * offsets)
References defformatstring, LOCALPARAMV, lookupshaderbyname(), loopk, MAXBLURRADIUS, and Shader::set().
Referenced by rendertarget::blur().
static void setglsluniformformat (Shader & s, const char * name, GLenum format, int size) static
References addglobalparam(), addlocalparam(), Shader::defaultparams, format(), getshaderparamname(), glGetUniformLocation_, globalparams, Shader::globalparams, Shader::localparams, loopvj, Shader::program, and Shader::uniformlocs.
Referenced by allocglslactiveuniforms().
void setshader (char * name)
References Log, shaders, vector< T, MINSIZE >::shrink(), slotparams, slotshader, and inexor::util::log_manager::std.
static void setslotparam (SlotShaderParamState & l, const float * val) inline static
References ShaderParamBinding::format, glUniform1fv_, glUniform1i_, glUniform2fv_, glUniform2i_, glUniform3fv_, glUniform3i_, glUniform4fv_, glUniform4i_, and ShaderParamBinding::loc.
void setslotshader (Slot & s)
References vector< T, MINSIZE >::add(), loopv, Slot::params, Slot::shader, slotparams, slotshader, and stdworldshader.
Referenced by texture().
void setupblurkernel (int radius, float sigma, float * weights, float * offsets)
References loopi(), and MAXBLURRADIUS.
Referenced by rendertarget::blur().
void setupshaders ()
References dummyslot, fatal(), hudnotextureshader, hudshader, maxfsuniforms, maxvsuniforms, newshader(), nullshader, Slot::shader, and standardshaders.
Referenced by gl_init().
void shader (int * type, char * name, char * vs, char * ps)
References defformatstring, gendynlightvariant(), genfogshader(), GENSHADER, genshadowmapvariant(), genuniformdefs(), genwatervariant(), vector< T, MINSIZE >::length(), loadprogress, lookupshaderbyname(), Shader::name, newshader(), renderprogress(), vector< T, MINSIZE >::shrink(), and slotparams.
Referenced by previewblends(), animmodel::setshader(), setupsurfaces(), and variantshader().
static void showglslinfo (GLenum type, GLuint obj, const char * name, const char ** parts = nullptr, int numparts = 0) static
References glGetProgramInfoLog_, glGetProgramiv_, glGetShaderInfoLog_, glGetShaderiv_, Log, parts, and inexor::util::log_manager::std.
Referenced by compileglslshader(), and linkglslprogram().
Shader* useshaderbyname (const char * name)
References Shader::detailshader, Shader::fixdetailshader(), Shader::forced, and shaders.
Referenced by addpostfx(), genprefabmesh(), loadcaustics(), preloadwatershaders(), vacollect::setupdata(), setupmaterials(), and recorder::start().
VAR (reservevpparams , 1 , 16 , 0)
VAR (maxvsuniforms , 1 , 0 , 0)
VAR (maxfsuniforms , 1 , 0 , 0)
VAR (maxvaryings , 1 , 0 , 0)
VAR (dbgshader , 0 , 0 , 2)
VAR (dbgubo , 0 , 0 , 1)
VAR (defershaders , 0 , 1 , 1)
VARF (shaderprecision , 0 , 0 , 2 , initwarning("shader quality"))
VARFP (shaderdetail , 0 , MAXSHADERDETAIL , MAXSHADERDETAIL , fixshaderdetail())
void variantshader (int * type, char * name, int * row, char * vs, char * ps)
References Shader::defaultparams, defformatstring, gendynlightvariant(), genfogshader(), gengenericvariant(), GENSHADER, genuniformdefs(), vector< T, MINSIZE >::length(), lookupshaderbyname(), MAXVARIANTROWS, newshader(), Shader::numvariants(), and shader().
Referenced by Shader::compile().
Variable Documentation
Shader * foggednotextureshader = nullptr
Referenced by cleanupshaders(), loadshaders(), and rendermaterials().
Shader * foggedshader = nullptr
Referenced by cleanupshaders(), loadshaders(), decalrenderer::render(), rendermaterials(), and blobrenderer::setuprenderstate().
bool forceshaders = true static
Referenced by Shader::force(), and newshader().
hashnameset<GlobalShaderParamState> globalparams(256) static
Referenced by Shader::cleanup(), getglobalparam(), GlobalShaderParamState::resetversions(), and setglsluniformformat().
Shader * hudnotextureshader = nullptr
Referenced by gui::background(), cleanupshaders(), rendertarget::debug(), editor::draw(), drawdamagecompass(), gui::field_(), loadshaders(), gui::modelpreview(), gui::playerpreview(), gui::prefabpreview(), gui::previewslot(), and setupshaders().
Shader * hudshader = nullptr
Referenced by gui::background(), cleanupshaders(), rendertarget::debug(), debugparticles(), editor::draw(), draw_crosshair(), draw_g3d_cursor(), drawdamagescreen(), recorder::drawhud(), gui::field_(), gl_drawframe(), gl_drawhud(), gl_rendercef(), gl_rendercefmouse(), texturegui::gui(), loadshaders(), gui::modelpreview(), gui::playerpreview(), gui::prefabpreview(), gui::previewslot(), renderbackground(), renderprogress(), rendertexturepanel(), setupshaders(), and gui::start().
bool loadedshaders = false static
Referenced by generateshader(), and loadshaders().
hashtable<const char *, int> localparams(256) static
Referenced by Shader::cleanup(), and getlocalparam().
Shader * nocolorshader = nullptr
Referenced by cleanupshaders(), drawskylimits(), loadshaders(), maskreflection(), queryreflection(), and renderzpass().
Shader * notextureshader = nullptr
Referenced by cleanupshaders(), drawskyoutline(), loadshaders(), maskreflection(), rendereditcursor(), rendermodel(), renderoutline(), and renderwater().
Shader* nullshader = nullptr
Referenced by cleanupshaders(), generateshader(), loadshaders(), and setupshaders().
int postfxbinds[NUMPOSTFXBINDS]
GLuint postfxfb = 0
Referenced by cleanuppostfx(), and renderpostfx().
int postfxh = 0
Referenced by cleanuppostfx(), and renderpostfx().
vector<postfxpass> postfxpasses
Referenced by addpostfx(), clearpostfx(), and renderpostfx().
vector<postfxtex> postfxtexs
Referenced by allocatepostfxtex(), cleanuppostfx(), and renderpostfx().
int postfxw = 0
Referenced by cleanuppostfx(), and renderpostfx().
hashset<const char *> shaderparamnames(256) static
Referenced by getshaderparamname().
hashnameset<Shader> shaders(256) static
Referenced by altshader(), cleanupshaders(), defershader(), fastshader(), fixshaderdetail(), lookupshaderbyname(), newshader(), reloadshaders(), GlobalShaderParamState::resetversions(), setshader(), Shader::uniformlocversion(), and useshaderbyname().
vector<SlotShaderParam> slotparams static
Referenced by addslotparam(), Shader::force(), genuniformdefs(), newshader(), resetslotshader(), setshader(), setslotshader(), and shader().
Shader* slotshader = nullptr static
Referenced by resetslotshader(), setshader(), and setslotshader().
bool standardshaders = false static
Referenced by defershader(), Shader::force(), generateshader(), loadshaders(), newshader(), and setupshaders().
Shader * stdworldshader = nullptr
Referenced by cleanupshaders(), loadshaders(), and setslotshader().
Shader * textureshader = nullptr
Referenced by cleanupshaders(), loadshaders(), and flarerenderer::render().