Inexor: inexor/io/legacy/stream.cpp File Reference
stream.cpp File Reference
#include <stdarg.h>
#include <algorithm>
#include <memory>
#include "inexor/io/Logging.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_unicode.hpp"
#include "inexor/shared/tools.hpp"
#include "zconf.h"
#include "zlib.h"
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>
Classes
struct packagedir
struct filestream
struct gzstream
struct utf8stream
Functions
char * makerelpath (const char *dir, const char *file, const char *prefix, const char *cmd)
Append a string together but add the prefix in the field.
char * path (char *s)
Modifies the input string to only contain slashes in the direction the platform allows.
char * path (const char *s, bool copy)
Returns a static string with adapted slashes according to the platforms prefered pathseperator.
const char * parentdir (const char *filename)
bool fileexists (const char *path, const char *mode)
Checks whether given file exists (and is available in the specific mode) Where Path is the filename and mode can optionally be set (but only effects posix systems) ATTENTION: DO NOT USE THIS METHOD DIRECTLY! It doesn't give a fuck about your homedir or any additional package dir, so use findfile instead! Available Modes are "w"/"a" for writeable files only and "d" for executeable files only ATTENTION2: if mode "w" or "a" are specified it checks for (parent) directory existence!
bool createdir (const char *path)
Creates a directory of given name.
size_t fixpackagedir (char *dir)
const char * addpackagedir (const char *dir)
Add an optional media directory.
const char * findfile (const char *filename, const char *mode)
Checks whether given file exists (and is available in the specific mode) Where Path is the filename and mode can optionally be set Available Modes are "e" (see.
bool listdir (const char *dirname, bool rel, const char *ext, vector< char * > &files)
Internal use only Use listfiles instead.
int listfiles (const char *dir, const char *ext, vector< char * > &files)
Lists all files in given directory and put it into vector files ext optionally filters for occurences with such extension only.
VAR (dbggz, 0, 0, 1)
stream * openrawfile (const char *filename, const char *mode)
stream * openfile (const char *filename, const char *mode)
stream * opentempfile (const char *name, const char *mode)
stream * opengzfile (const char *filename, const char *mode, stream *file, int level)
stream * openutf8file (const char *filename, const char *mode, stream *file)
char * loadfile (const char *fn, size_t *size, bool utf8)
Variables
string homedir = ""
vector< packagedir > packagedirs
Class Documentation
struct packagedir
Class Members
const char * dir
size_t dirlen
Function Documentation
const char* addpackagedir (const char * dir)
Add an optional media directory.
Inexor can have multiple directories for its content it will treat like the games root-folder.
References vector< T, MINSIZE >::add(), copystring(), packagedir::dir, packagedir::dirlen, fixpackagedir(), and newstring().
Referenced by main().
bool createdir (const char * path)
Creates a directory of given name.
Returns
Returns true on success
References copystring(), NULL, and PATHDIV.
Referenced by findfile(), and screenshot().
bool fileexists (const char * path, const char * mode)
Checks whether given file exists (and is available in the specific mode) Where Path is the filename and mode can optionally be set (but only effects posix systems) ATTENTION: DO NOT USE THIS METHOD DIRECTLY! It doesn't give a fuck about your homedir or any additional package dir, so use findfile instead! Available Modes are "w"/"a" for writeable files only and "d" for executeable files only ATTENTION2: if mode "w" or "a" are specified it checks for (parent) directory existence!
References parentdir().
Referenced by findfile(), findfile_(), and screenshot().
const char* findfile (const char * filename, const char * mode)
Checks whether given file exists (and is available in the specific mode) Where Path is the filename and mode can optionally be set Available Modes are "e" (see.
Returns
) "w"/"a" for writeable files only and "d" for executeable files only
Returns the filename of the found file (or the, if "e" is specified it returns NULL if nothing was found. Otherwise it returns the inital filename.
References copystring(), createdir(), packagedir::dir, dir, fileexists(), formatstring(), homedir, loopv, and PATHDIV.
Referenced by backup(), findfile_(), loadsurface(), main(), openrawfile(), opentempfile(), game::receivefile(), saveimage(), screenshot(), and game::sendmap().
size_t fixpackagedir (char * dir)
References path(), and PATHDIV.
Referenced by addpackagedir().
bool listdir (const char * dirname, bool rel, const char * ext, vector< char * > & files)
Internal use only Use listfiles instead.
Returns
false if dirname does not exists
References vector< T, MINSIZE >::add(), hmap::d, defformatstring, and newstring().
Referenced by listfiles().
int listfiles (const char * dir, const char * ext, vector< char * > & files)
Lists all files in given directory and put it into vector files ext optionally filters for occurences with such extension only.
References copystring(), packagedir::dir, formatstring(), homedir, listdir(), loopv, path(), and PATHDIV.
Referenced by filesval::update().
char* loadfile (const char * fn, size_t * size, bool utf8)
References decodeutf8(), f(), openfile(), stream::read(), and stream::size().
Referenced by execfile().
char* makerelpath (const char * dir, const char * file, const char * prefix, const char * cmd)
Append a string together but add the prefix in the field.
References concatstring(), copystring(), defformatstring, gle::end(), and inexor::rpc::min().
Referenced by autograss(), execfile(), fonttex(), md5::md5mesh::load(), newfont(), modelcommands< MDL, struct MDL::vertmesh >::setbumpmap(), modelcommands< MDL, struct MDL::vertmesh >::setskin(), and texlayer().
stream* openfile (const char * filename, const char * mode)
References openrawfile().
Referenced by canloadsurface(), gendds(), obj::objmeshgroup::load(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), md5::md5meshgroup::loadanim(), smd::smdmeshgroup::loadanim(), loaddds(), loadfile(), iqm::iqmmeshgroup::loadiqm(), md5::md5meshgroup::loadmesh(), smd::smdmeshgroup::loadmesh(), aviwriter::open(), opengzfile(), openutf8file(), savepng(), savetga(), and writeobj().
stream* opengzfile (const char * filename, const char * mode, stream * file, int level)
References hmap::gz, gzstream::open(), and openfile().
Referenced by load_world(), loadents(), loadprefab(), ai::loadwaypoints(), save_world(), saveprefab(), ai::savewaypoints(), server::setupdemoplayback(), and server::setupdemorecord().
stream* openrawfile (const char * filename, const char * mode)
References recorder::file, findfile(), and filestream::open().
Referenced by openfile(), game::receivefile(), and game::sendmap().
stream* opentempfile (const char * name, const char * mode)
References recorder::file, findfile(), and filestream::opentemp().
Referenced by server::receivefile(), and server::setupdemorecord().
stream* openutf8file (const char * filename, const char * mode, stream * file)
References utf8stream::open(), and openfile().
Referenced by editor::load(), loadhistory(), editor::save(), writecfg(), writehistory(), and writeinitcfg().
const char* parentdir (const char * filename)
Returns
the parent directory of a file path
Warning
Removes last slash: texture/lastly.dg becomes texture
References copystring().
Referenced by execfile(), fileexists(), md2::load(), md3::loaddefaultparts(), and obj::loaddefaultparts().
char* path (char * s)
Modifies the input string to only contain slashes in the direction the platform allows.
Which is \ on windows and / on any other platform.
References recorder::file, PATHDIV, and anonymous_namespace{utilTest.cpp}::t().
Referenced by aviwriter::aviwriter(), execfile(), inexor::filesystem::ExecutablePathFallback(), inexor::filesystem::ExecutablePathWithoutBinary(), findfile_(), fixpackagedir(), gendds(), gettexture(), listfiles(), md2::load(), md3::loaddefaultparts(), obj::loaddefaultparts(), iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), loadents(), loadhistory(), loadimage(), vertcommands< MDL >::loadpart(), skelcommands< MDL >::loadpart(), loadprefab(), mapcfgname(), path(), registertexture(), saveprefab(), screenshot(), skelcommands< MDL >::setanim(), setmapfilenames(), skelcommands< MDL >::setpitchtarget(), texlayer(), texturedata(), writecfg(), writecrosshairs(), writehistory(), and writeobj().
char* path (const char * s, bool copy)
Returns a static string with adapted slashes according to the platforms prefered pathseperator.
Warning
not threadsafe!
References copystring(), and path().
VAR (dbggz , 0 , 0 , 1)
Variable Documentation
string homedir = ""
Referenced by findfile(), and listfiles().
vector<packagedir> packagedirs