Inexor: databuf< T > Struct Template Reference
databuf< T > Struct Template Reference
template implementation of buffers (networking e.g.).
#include <buffer_types.hpp>
Public Types
enum { OVERREAD = 1<<0, OVERWROTE = 1<<1 }
buffer missuse flags.
Public Member Functions
databuf ()
template<class U >
databuf (T *buf, U maxlen)
void reset ()
void reset (T *buf_, int maxlen_)
const T & get ()
get one byte from the buffer and
databuf subbuf (int sz)
create a sub buffer copy from this buffer (from the current position)
T * pad (int numvals)
void put (const T &val)
put one element at the end of the buffer.
void put (const T *vals, int numvals)
put a given number of elements at the end of the buffer.
int get (T *vals, int numvals)
receive the given amount of elements from the buffer to given array.
void offset (int n)
skip the first n elemnts of the buffer.
T * getbuf () const
bool empty () const
int length () const
receive amount of values in buffer.
int remaining () const
receive remaining space in buffer.
bool overread () const
did we try to read too much?
bool overwrote () const
did we try to write too much into the buffer?
bool check (int n)
void forceoverread ()
force buffer to skip all free memory space
Public Attributes
T * buf
the pointer to the data.
int len
int maxlen
uchar flags
Detailed Description
template<class T>
struct databuf< T >
template implementation of buffers (networking e.g.).
work like streams: you put stuff at the end, you get stuff from the end
Member Enumeration Documentation
template<class T> anonymous enum
buffer missuse flags.
Enumerator
OVERREAD
OVERWROTE
Constructor & Destructor Documentation
template<class T> databuf< T >::databuf () inline
Referenced by databuf< T >::subbuf().
template<class T> template<class U > databuf< T >::databuf (T * buf, U maxlen) inline
Member Function Documentation
template<class T> bool databuf< T >::check (int n) inline
References databuf< T >::remaining().
Referenced by gle::attrib().
template<class T> bool databuf< T >::empty () const inline
References databuf< T >::len.
Referenced by gle::end(), server::sendmessages(), and server::sendpositions().
template<class T> void databuf< T >::forceoverread () inline
force buffer to skip all free memory space
References databuf< T >::flags, databuf< T >::len, databuf< T >::maxlen, and databuf< T >::OVERREAD.
template<class T> const T& databuf< T >::get () inline
get one byte from the buffer and
References databuf< T >::buf, databuf< T >::flags, databuf< T >::len, databuf< T >::maxlen, and databuf< T >::OVERREAD.
Referenced by getfloat(), getint(), getuint(), server::parsepacket(), game::parsepositions(), and unpackvslot().
template<class T> int databuf< T >::get (T * vals, int numvals) inline
receive the given amount of elements from the buffer to given array.
References databuf< T >::buf, databuf< T >::flags, databuf< T >::len, databuf< T >::maxlen, inexor::rpc::min(), and databuf< T >::OVERREAD.
template<class T> T* databuf< T >::getbuf () const inline
References databuf< T >::buf.
Referenced by gle::end().
template<class T> int databuf< T >::length () const inline
receive amount of values in buffer.
References databuf< T >::len.
Referenced by vector< facebounds >::addbuf(), server::addmessages(), game::addmsg(), server::addposition(), gle::end(), gle::multidraw(), server::parsepacket(), game::captureclientmode::senditems(), server::sendmessages(), server::sendpositions(), and server::sendserverinforeply().
template<class T> void databuf< T >::offset (int n) inline
skip the first n elemnts of the buffer.
References databuf< T >::buf, databuf< T >::len, inexor::rpc::max(), databuf< T >::maxlen, and inexor::rpc::min().
Referenced by server::sendmessages(), and server::sendpositions().
template<class T> bool databuf< T >::overread () const inline
did we try to read too much?
References databuf< T >::flags, and databuf< T >::OVERREAD.
Referenced by game::collectclientmode::parse_network_message(), server::collectservermode::parsebases(), server::captureservermode::parsebases(), game::ctfclientmode::parseflags(), server::ctfservermode::parseflags(), game::parsemessages(), server::parsepacket(), server::bombservermode::parsespawnloc(), game::collectclientmode::parsetokens(), server::process(), and unpackvslot().
template<class T> bool databuf< T >::overwrote () const inline
did we try to write too much into the buffer?
References databuf< T >::flags, and databuf< T >::OVERWROTE.
template<class T> T* databuf< T >::pad (int numvals) inline
References databuf< T >::buf, databuf< T >::len, databuf< T >::maxlen, and inexor::rpc::min().
Referenced by gle::attrib(), game::parsemessages(), server::parsepacket(), unpackundo(), and unpackvslots().
template<class T> void databuf< T >::put (const T & val) inline
put one element at the end of the buffer.
References databuf< T >::buf, databuf< T >::flags, databuf< T >::len, databuf< T >::maxlen, and databuf< T >::OVERWROTE.
Referenced by server::addmessages(), server::addposition(), gle::attribv(), server::extinfoplayer(), packetbuf::put(), vector< facebounds >::put(), smd::smdmeshgroup::readframes(), server::sendmessages(), and server::sendpositions().
template<class T> void databuf< T >::put (const T * vals, int numvals) inline
put a given number of elements at the end of the buffer.
References databuf< T >::buf, databuf< T >::flags, databuf< T >::len, databuf< T >::maxlen, inexor::rpc::min(), and databuf< T >::OVERWROTE.
template<class T> int databuf< T >::remaining () const inline
receive remaining space in buffer.
References databuf< T >::len, and databuf< T >::maxlen.
Referenced by databuf< T >::check(), getstring(), game::parsemessages(), server::parsepacket(), game::parsepositions(), game::receivefile(), server::serverinforeply(), unpackundo(), unpackvslot(), and unpackvslots().
template<class T> void databuf< T >::reset () inline
References databuf< T >::flags, and databuf< T >::len.
Referenced by gle::begin(), gle::end(), databuf< T >::reset(), and gle::setup().
template<class T> void databuf< T >::reset (T * buf_, int maxlen_) inline
References databuf< T >::buf, databuf< T >::maxlen, and databuf< T >::reset().
template<class T> databuf databuf< T >::subbuf (int sz) inline
create a sub buffer copy from this buffer (from the current position)
References databuf< T >::buf, databuf< T >::databuf(), databuf< T >::len, and databuf< T >::maxlen.
Referenced by game::parsemessages(), and packetbuf::subbuf().
Member Data Documentation
template<class T> T* databuf< T >::buf
the pointer to the data.
Referenced by server::addmessages(), server::addposition(), packetbuf::cleanup(), databuf< T >::get(), databuf< T >::getbuf(), make_file_packet(), databuf< T >::offset(), packetbuf::packetbuf(), databuf< T >::pad(), game::parsemessages(), server::parsepacket(), databuf< T >::put(), game::receivefile(), databuf< T >::reset(), packetbuf::resize(), server::sendmessages(), server::sendpositions(), server::sendserverinforeply(), server::setupdemorecord(), and databuf< T >::subbuf().
template<class T> uchar databuf< T >::flags
Referenced by databuf< T >::forceoverread(), databuf< T >::get(), databuf< T >::overread(), databuf< T >::overwrote(), databuf< T >::put(), and databuf< T >::reset().
template<class T> int databuf< T >::len
Referenced by server::checkserversockets(), packetbuf::checkspace(), packetbuf::cleanup(), databuf< T >::empty(), packetbuf::finalize(), databuf< T >::forceoverread(), databuf< T >::get(), databuf< T >::length(), databuf< T >::offset(), databuf< T >::pad(), databuf< T >::put(), databuf< T >::remaining(), databuf< T >::reset(), server::setupdemorecord(), and databuf< T >::subbuf().
template<class T> int databuf< T >::maxlen
Referenced by packetbuf::checkspace(), packetbuf::cleanup(), databuf< T >::forceoverread(), databuf< T >::get(), databuf< T >::offset(), packetbuf::packetbuf(), databuf< T >::pad(), game::parsemessages(), server::parsepacket(), databuf< T >::put(), game::receivefile(), databuf< T >::remaining(), databuf< T >::reset(), packetbuf::resize(), and databuf< T >::subbuf().
The documentation for this struct was generated from the following file:
inexor/network/legacy/buffer_types.hpp