Inexor: inexor::sound::soundsample Struct Reference
inexor::sound::soundsample Struct Reference
Public Member Functions
soundsample ()
~soundsample ()
void cleanup ()
bool load (bool msg=false)
Public Attributes
char * name
Constructor & Destructor Documentation
inexor::sound::soundsample::soundsample () inline
inexor::sound::soundsample::~soundsample () inline
References DELETEA.
Member Function Documentation
void inexor::sound::soundsample::cleanup () inline
Referenced by inexor::sound::cleanupsamples().
bool inexor::sound::soundsample::load (bool msg = false)
References DIR_SOUND, inexor::filesystem::getmediapath(), Log, loopi(), renderprogress(), and inexor::util::log_manager::std.
Member Data Documentation
char* inexor::sound::soundsample::name
Referenced by inexor::sound::soundtype::addslot(), inexor::sound::soundtype::findsound(), and inexor::sound::playsound().
The documentation for this struct was generated from the following file:
inexor/sound/sound.cpp