Inexor: game::hideandseekclientmode Struct Reference
game::hideandseekclientmode Struct Reference
#include <hideandseek_client.hpp>
Public Member Functions
void setup () override
void drawblip (fpsent *d, float x, float y, float s, const vec &pos, float size_factor)
void drawhud (fpsent *d, int w, int h) override
bool isinvisible (fpsent *d) override
void rendergame () override
void renderscoreboard (g3d_gui &g, scoregroup &sg, int fgcolor, int bgcolor) override
void killed (fpsent *d, fpsent *actor) override
void respawned (fpsent *d) override
void pickspawn (fpsent *d) override
bool hidefrags () override
bool parse_network_message (int type, ucharbuf &p) override
Parse game mode specific network messages.
virtual void preload ()
virtual int clipconsole (int w, int h)
virtual void checkitems (fpsent *d)
virtual int respawnwait (fpsent *d)
virtual void senditems (packetbuf &p)
virtual void addplayer (fpsent *d)
virtual void removeplayer (fpsent *d)
virtual void gameover ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual void aifind (fpsent *d, ai::aistate &b, vector< ai::interest > &interests)
virtual bool aicheck (fpsent *d, ai::aistate &b)
virtual bool aidefend (fpsent *d, ai::aistate &b)
virtual bool aipursue (fpsent *d, ai::aistate &b)
virtual void gameconnect (fpsent *d)
Static Public Attributes
static constexpr int STARTINVISIBLESECS = 30
Member Function Documentation
virtual void game::clientmode::addplayer (fpsent * d) inline virtual inherited
virtual bool game::clientmode::aicheck (fpsent * d, ai::aistate & b) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::check().
virtual bool game::clientmode::aidefend (fpsent * d, ai::aistate & b) inline virtual inherited
Reimplemented in game::ctfclientmode, and game::captureclientmode.
Referenced by ai::dodefend().
virtual void game::clientmode::aifind (fpsent * d, ai::aistate & b, vector< ai::interest > & interests) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::find().
virtual bool game::clientmode::aipursue (fpsent * d, ai::aistate & b) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::dopursue().
virtual void game::clientmode::checkitems (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::logic(), and game::updateworld().
virtual int game::clientmode::clipconsole (int w, int h) inline virtual inherited
Reimplemented in game::captureclientmode, game::collectclientmode, and game::ctfclientmode.
Referenced by game::clipconsole().
void game::hideandseekclientmode::drawblip (fpsent * d, float x, float y, float s, const vec & pos, float size_factor)
References game::calcradarscale(), camera1, dir, vec::div(), game::drawradar(), f(), vec::magnitude2(), vec::mul(), physent::o, RAD, vec::rotate_around_z(), vec::sub(), and physent::yaw.
Referenced by drawhud().
void game::hideandseekclientmode::drawhud (fpsent * d, int w, int h) override virtual
Reimplemented from game::clientmode.
References bindminimap(), CS_ALIVE, defformatstring, drawblip(), game::drawminimap(), game::drawradar(), ishider, game::isobstaclealive(), loopv, game::minimapalpha, game::movables, physent::o, game::players, radardir, game::setbliptex(), game::setradartex(), settexture(), game::showminimapobstacles, physent::state, and TEAM_OPPONENT.
virtual void game::clientmode::gameconnect (fpsent * d) inline virtual inherited
Reimplemented in game::bombclientmode.
virtual void game::clientmode::gameover () inline virtual inherited
Referenced by game::timeupdate().
virtual int game::clientmode::getteamscore (const char * team) inline virtual inherited
Referenced by game::groupplayers().
virtual void game::clientmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by game::getbestteams().
bool game::hideandseekclientmode::hidefrags () inline override virtual
Reimplemented from game::clientmode.
bool game::hideandseekclientmode::isinvisible (fpsent * d) override virtual
Reimplemented from game::clientmode.
References ishider, game::maptime, game::player1, STARTINVISIBLESECS, and totalmillis.
void game::hideandseekclientmode::killed (fpsent * d, fpsent * actor) inline override virtual
Reimplemented from game::clientmode.
bool game::hideandseekclientmode::parse_network_message (int type, ucharbuf & p) inline override virtual
Parse game mode specific network messages.
Returns
true if message got handled.
Implements game::clientmode.
void game::hideandseekclientmode::pickspawn (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
References findplayerspawn(), and game::player1.
virtual void game::clientmode::preload () inline virtual inherited
Reimplemented in game::captureclientmode, game::collectclientmode, and game::ctfclientmode.
Referenced by game::startgame().
virtual void game::clientmode::removeplayer (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode.
Referenced by game::clientdisconnected().
void game::hideandseekclientmode::rendergame () inline override virtual
Reimplemented from game::clientmode.
void game::hideandseekclientmode::renderscoreboard (g3d_gui & g, scoregroup & sg, int fgcolor, int bgcolor) inline override virtual
Reimplemented from game::clientmode.
void game::hideandseekclientmode::respawned (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
virtual int game::clientmode::respawnwait (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by game::respawn(), and ai::think().
virtual void game::clientmode::senditems (packetbuf & p) inline virtual inherited
Reimplemented in game::captureclientmode, game::ctfclientmode, game::collectclientmode, and game::bombclientmode.
Referenced by game::sendmessages().
void game::hideandseekclientmode::setup () inline override virtual
Reimplemented from game::clientmode.
Member Data Documentation
constexpr int game::hideandseekclientmode::STARTINVISIBLESECS = 30 static
Referenced by isinvisible().
The documentation for this struct was generated from the following files:
inexor/client/gamemode/hideandseek_client.hpp
inexor/client/gamemode/hideandseek_client.cpp