Inexor: smd Struct Reference
smd Struct Reference
#include <smd.hpp>
Classes
struct smdmesh
struct smdmeshgroup
Public Types
enum { LINK_TAG = 0, LINK_COOP, LINK_REUSE }
Public Member Functions
smd (const char *name)
int type () const override
meshgroup * loadmeshes (const char *name, va_list args) override
bool loaddefaultparts () override
bool load () override
int linktype (animmodel *m) const override
bool skeletal () const override
skelpart & addpart ()
meshgroup * sharemeshes (const char *name,...)
void render (int anim, int basetime, int basetime2, float pitch, const vec &axis, const vec &forward, dynent *d, modelattach *a)
void render (int anim, int basetime, int basetime2, const vec &o, float yaw, float pitch, dynent *d, modelattach *a, const vec &color, const vec &dir, float trans) override
void cleanup () override
void initmatrix (matrix4x3 &m)
void genBIH (vector< BIH::mesh > &bih)
void preloadBIH () override
BIH * setBIH () override
bool link (part *p, const char *tag, const vec &translate=vec(0, 0, 0), int anim=-1, int basetime=0, vec *pos=nullptr)
bool unlink (part *p)
bool envmapped () override
void preloadshaders (bool force) override
void preloadmeshes () override
void setshader (Shader *shader) override
void setenvmap (float envmapmin, float envmapmax, Texture *envmap) override
void setspec (float spec) override
void setambient (float ambient) override
void setglow (float glow, float delta, float pulse) override
void setglare (float specglare, float glowglare) override
void setalphatest (float alphatest) override
void setalphablend (bool alphablend) override
void setfullbright (float fullbright) override
void setcullface (bool cullface) override
void calcbb (vec &center, vec &radius) override
virtual void loaded ()
void startrender () override
void endrender () override
void boundbox (vec &center, vec &radius)
float collisionbox (vec &center, vec &radius)
float boundsphere (vec &center)
float above ()
Static Public Member Functions
static const char * formatname ()
static void disablebones ()
static void disabletangents ()
static void disabletc ()
static void disablenormals ()
static void disablevbo ()
static bool animated ()
static bool multiparted ()
static bool multimeshed ()
Public Attributes
vector< part * > parts
char * name
float spinyaw
float spinpitch
float offsetyaw
float offsetpitch
bool collide
bool ellipsecollide
bool shadow
bool alphadepth
bool depthoffset
float scale
vec translate
BIH * bih
vec bbcenter
vec bbradius
vec bbextend
vec collidecenter
vec collideradius
float rejectradius
float eyeheight
float collidexyradius
float collideheight
int batch
Static Public Attributes
static bool enabletc = false
static bool enablealphablend = false
static bool enablecullface = true
static bool enablenormals = false
static bool enabletangents = false
static bool enablebones = false
static bool enabledepthoffset = false
static vec lightdir
static vec lightcolor
static float transparent = 1
static float lastalphatest = -1
static GLuint lastvbuf = 0
static GLuint lasttcbuf = 0
static GLuint lastnbuf = 0
static GLuint lastxbuf = 0
static GLuint lastbbuf = 0
static GLuint lastebuf = 0
static GLuint lastenvmaptex = 0
static GLuint closestenvmaptex = 0
static Texture * lasttex = nullptr
static Texture * lastmasks = nullptr
static Texture * lastnormalmap = nullptr
static int matrixpos = 0
static matrix4 matrixstack [64]
static vector< skeladjustment > adjustments
static smd * loading
static string dir
Member Enumeration Documentation
anonymous enum inherited
Enumerator
LINK_TAG
LINK_COOP
LINK_REUSE
Constructor & Destructor Documentation
smd::smd (const char * name) inline
Member Function Documentation
float model::above () inline inherited
References model::boundbox().
Referenced by abovemodel(), and lightent().
skelpart& skelmodel::addpart () inline inherited
References animmodel::parts.
Referenced by iqm::loaddefaultparts(), md5::loaddefaultparts(), and loaddefaultparts().
static bool modelloader< smd >::animated () inline static inherited
void model::boundbox (vec & center, vec & radius) inline inherited
References vec::add(), model::bbcenter, model::bbextend, model::bbradius, and model::calcbb().
Referenced by model::above(), model::boundsphere(), model::collisionbox(), endmodelbatches(), getentboundingbox(), mmboundbox(), gui::modelpreview(), and rendermodel().
float model::boundsphere (vec & center) inline inherited
References model::boundbox(), and vec::magnitude().
void animmodel::calcbb (vec & center, vec & radius) inline override virtual inherited
Implements model.
References vec::add(), f(), animmodel::initmatrix(), vec::mul(), animmodel::parts, and vec::sub().
void animmodel::cleanup () inline override virtual inherited
Reimplemented from model.
References loopv, and animmodel::parts.
Referenced by vertmodel::vertmeshgroup::preload(), and vertmodel::vertmeshgroup::render().
float model::collisionbox (vec & center, vec & radius) inline inherited
References model::boundbox(), model::collidecenter, model::collideheight, model::collideradius, model::collidexyradius, vec::magnitude(), and model::rejectradius.
Referenced by entselectionbox(), mmcollide(), mmcollisionbox(), rendermodel(), and setbbfrommodel().
static void animmodel::disablebones () inline static inherited
References animmodel::enablebones.
Referenced by vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), and animmodel::disablevbo().
static void animmodel::disablenormals () inline static inherited
References animmodel::enablenormals.
Referenced by vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), and animmodel::disablevbo().
static void animmodel::disabletangents () inline static inherited
References animmodel::enabletangents.
Referenced by vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), and animmodel::disablevbo().
static void animmodel::disabletc () inline static inherited
References animmodel::enabletc.
Referenced by vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), and animmodel::disablevbo().
static void animmodel::disablevbo () inline static inherited
References gle::clearebo(), gle::clearvbo(), animmodel::disablebones(), animmodel::disablenormals(), animmodel::disabletangents(), animmodel::disabletc(), animmodel::enablebones, animmodel::enablenormals, animmodel::enabletangents, animmodel::enabletc, animmodel::lastbbuf, animmodel::lastebuf, animmodel::lastnbuf, animmodel::lasttcbuf, animmodel::lastvbuf, and animmodel::lastxbuf.
Referenced by animmodel::endrender(), vertmodel::vertmeshgroup::render(), and skelmodel::skelmeshgroup::render().
void animmodel::endrender () inline override virtual inherited
Reimplemented from model.
References disablepolygonoffset(), animmodel::disablevbo(), animmodel::enablealphablend, animmodel::enablecullface, animmodel::enabledepthoffset, animmodel::lastebuf, and animmodel::lastvbuf.
bool animmodel::envmapped () inline override virtual inherited
Reimplemented from model.
References loopv, and animmodel::parts.
Referenced by animmodel::render().
static const char* smd::formatname () inline static
void animmodel::genBIH (vector< BIH::mesh > & bih) inline inherited
References animmodel::initmatrix(), and animmodel::parts.
Referenced by animmodel::setBIH().
void animmodel::initmatrix (matrix4x3 & m) inline inherited
References matrix4x3::identity(), model::offsetpitch, model::offsetyaw, RAD, matrix4x3::rotate_around_y(), and matrix4x3::rotate_around_z().
Referenced by animmodel::calcbb(), and animmodel::genBIH().
bool animmodel::link (part * p, const char * tag, const vec & translate = vec(0, 0, 0), int anim = -1, int basetime = 0, vec * pos = nullptr) inline inherited
References animmodel::parts, and model::translate.
Referenced by animmodel::render().
int skelmodel::linktype (animmodel * m) const inline override virtual inherited
Reimplemented from animmodel.
References animmodel::LINK_REUSE, animmodel::LINK_TAG, animmodel::parts, and model::type().
bool smd::load () inline override virtual
Implements model.
References cfgname, defformatstring, modelloader< smd >::dir, execfile(), formatstring(), identflags, IDF_PERSIST, loaddefaultparts(), animmodel::loaded(), modelloader< smd >::loading, loopv, modeldir, model::name, and animmodel::parts.
bool smd::loaddefaultparts () inline override virtual
Reimplemented from animmodel.
References skelmodel::addpart(), skelloader< smd >::adjustments, defformatstring, skelmodel::skelpart::initanimparts(), animmodel::part::initskins(), animmodel::part::meshes, modeldir, model::name, NULL, path(), animmodel::part::pitchmax, animmodel::part::pitchmin, animmodel::part::pitchoffset, animmodel::part::pitchscale, vector< T, MINSIZE >::setsize(), and animmodel::sharemeshes().
Referenced by load().
virtual void animmodel::loaded () inline virtual inherited
References loopv, animmodel::parts, model::scale, and model::translate.
Referenced by md3::load(), obj::load(), md2::load(), iqm::load(), md5::load(), and load().
meshgroup* smd::loadmeshes (const char * name, va_list args) inline override virtual
Reimplemented from animmodel.
References smd::smdmeshgroup::load(), and skelmodel::skelmeshgroup::shareskeleton().
static bool modelloader< smd >::multimeshed () inline static inherited
static bool modelloader< smd >::multiparted () inline static inherited
void animmodel::preloadBIH () inline override virtual inherited
Reimplemented from model.
References model::bih, loopv, animmodel::parts, and model::preloadBIH().
void animmodel::preloadmeshes () inline override virtual inherited
Reimplemented from model.
References loopv, and animmodel::parts.
void animmodel::preloadshaders (bool force) inline override virtual inherited
Reimplemented from model.
References loopv, and animmodel::parts.
void animmodel::render (int anim, int basetime, int basetime2, float pitch, const vec & axis, const vec & forward, dynent * d, modelattach * a) inline inherited
References ANIM_REUSE, animmodel::part::index, animmodel::link(), animmodel::LINK_COOP, animmodel::LINK_REUSE, animmodel::LINK_TAG, animmodel::linktype(), MAXANIMPARTS, animmodel::part::numanimparts, animmodel::parts, animmodel::part::render(), modelattach::tag, and animmodel::unlink().
Referenced by animmodel::render().
void animmodel::render (int anim, int basetime, int basetime2, const vec & o, float yaw, float pitch, dynent * d, modelattach * a, const vec & color, const vec & dir, float trans) inline override virtual inherited
Implements model.
References model::alphadepth, ANIM_GHOST, ANIM_NORENDER, ANIM_NOSKIN, ANIM_RAGDOLL, closestenvmap(), animmodel::closestenvmaptex, gle::color(), model::depthoffset, dir, animmodel::enablealphablend, animmodel::enabledepthoffset, enablepolygonoffset(), animmodel::envmapped(), fading, GLOBALPARAM, matrix4::identity(), lastmillis, dynent::lastrendered, animmodel::lightcolor, animmodel::lightdir, lookupenvmap(), animmodel::matrixpos, animmodel::matrixstack, model::offsetpitch, model::offsetyaw, RAD, dynent::ragdoll, animmodel::render(), matrix4::rotate_around_z(), matrix4::settranslation(), model::spinpitch, model::spinyaw, modelattach::tag, matrix4::transformnormal(), and animmodel::transparent.
void animmodel::setalphablend (bool alphablend) inline override virtual inherited
Reimplemented from model.
References animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
void animmodel::setalphatest (float alphatest) inline override virtual inherited
Reimplemented from model.
References animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
void animmodel::setambient (float ambient) inline override virtual inherited
Reimplemented from model.
References animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
BIH* animmodel::setBIH () inline override virtual inherited
Reimplemented from model.
References model::bih, and animmodel::genBIH().
void animmodel::setcullface (bool cullface) inline override virtual inherited
Reimplemented from model.
References animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
void animmodel::setenvmap (float envmapmin, float envmapmax, Texture * envmap) inline override virtual inherited
Reimplemented from model.
References animmodel::skin::envmap, animmodel::shaderparams::envmapmax, animmodel::shaderparams::envmapmin, animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
void animmodel::setfullbright (float fullbright) inline override virtual inherited
Reimplemented from model.
References animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
void animmodel::setglare (float specglare, float glowglare) inline override virtual inherited
Reimplemented from model.
References animmodel::shaderparams::glowglare, animmodel::loaddefaultparts(), loopv, loopvj, animmodel::parts, and animmodel::shaderparams::specglare.
void animmodel::setglow (float glow, float delta, float pulse) inline override virtual inherited
Reimplemented from model.
References animmodel::shaderparams::glow, animmodel::shaderparams::glowdelta, animmodel::shaderparams::glowpulse, animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
void animmodel::setshader (Shader * shader) inline override virtual inherited
Reimplemented from model.
References animmodel::loaddefaultparts(), loopv, loopvj, animmodel::parts, and shader().
void animmodel::setspec (float spec) inline override virtual inherited
Reimplemented from model.
References animmodel::loaddefaultparts(), loopv, loopvj, and animmodel::parts.
meshgroup* animmodel::sharemeshes (const char * name, ...) inline inherited
References hashbase< hashnameset< T >, T, const char *, T >::access(), hashnameset< T >::add(), animmodel::loadmeshes(), and model::name.
Referenced by md2::load(), md3::loaddefaultparts(), obj::loaddefaultparts(), iqm::loaddefaultparts(), md5::loaddefaultparts(), and loaddefaultparts().
bool skelmodel::skeletal () const inline override virtual inherited
Reimplemented from model.
void animmodel::startrender () inline override virtual inherited
Reimplemented from model.
References animmodel::closestenvmaptex, animmodel::enablealphablend, animmodel::enablebones, animmodel::enablecullface, animmodel::enabledepthoffset, animmodel::enablenormals, animmodel::enabletangents, animmodel::enabletc, animmodel::shaderparamskey::invalidate(), animmodel::lastalphatest, animmodel::lastbbuf, animmodel::lastebuf, animmodel::lastenvmaptex, animmodel::lastmasks, animmodel::lastnbuf, animmodel::lastnormalmap, animmodel::lasttcbuf, animmodel::lasttex, animmodel::lastvbuf, animmodel::lastxbuf, and animmodel::transparent.
int smd::type () const inline override virtual
Implements model.
References MDL_SMD.
bool animmodel::unlink (part * p) inline inherited
References animmodel::parts.
Referenced by animmodel::render().
Member Data Documentation
vector<skeladjustment> skelloader< smd >::adjustments static inherited
Referenced by loaddefaultparts(), and smd::smdmeshgroup::readframes().
bool model::alphadepth inherited
Referenced by mdlalphadepth(), and animmodel::render().
int model::batch inherited
Referenced by addbatchedmodel().
vec model::bbcenter inherited
Referenced by model::boundbox().
vec model::bbextend inherited
Referenced by model::boundbox(), and mdlextendbb().
vec model::bbradius inherited
Referenced by model::boundbox().
BIH* model::bih inherited
Referenced by mmintersect(), model::preloadBIH(), animmodel::preloadBIH(), animmodel::setBIH(), and model::~model().
GLuint animmodel::closestenvmaptex = 0 static inherited
Referenced by animmodel::skin::bind(), animmodel::render(), and animmodel::startrender().
bool model::collide inherited
Referenced by mdlcollide(), mmcollide(), and mmintersect().
vec model::collidecenter inherited
Referenced by model::collisionbox().
float model::collideheight inherited
Referenced by model::collisionbox(), and mdlbb().
vec model::collideradius inherited
Referenced by model::collisionbox().
float model::collidexyradius inherited
Referenced by model::collisionbox(), and mdlbb().
bool model::depthoffset inherited
Referenced by mdldepthoffset(), and animmodel::render().
string modelloader< smd >::dir static inherited
Referenced by load().
bool model::ellipsecollide inherited
Referenced by mdlellipsecollide(), mmcollide(), and setbbfrommodel().
bool animmodel::enablealphablend = false static inherited
Referenced by animmodel::skin::bind(), animmodel::endrender(), animmodel::render(), and animmodel::startrender().
bool animmodel::enablebones = false static inherited
Referenced by animmodel::meshgroup::bindbones(), vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), animmodel::disablebones(), animmodel::disablevbo(), and animmodel::startrender().
bool animmodel::enablecullface = true static inherited
Referenced by animmodel::skin::bind(), animmodel::endrender(), and animmodel::startrender().
bool animmodel::enabledepthoffset = false static inherited
Referenced by animmodel::endrender(), animmodel::render(), and animmodel::startrender().
bool animmodel::enablenormals = false static inherited
Referenced by animmodel::meshgroup::bindnormals(), vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), animmodel::disablenormals(), animmodel::disablevbo(), and animmodel::startrender().
bool animmodel::enabletangents = false static inherited
Referenced by animmodel::meshgroup::bindtangents(), vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), animmodel::disabletangents(), animmodel::disablevbo(), and animmodel::startrender().
bool animmodel::enabletc = false static inherited
Referenced by animmodel::meshgroup::bindtc(), vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), animmodel::disabletc(), animmodel::disablevbo(), and animmodel::startrender().
float model::eyeheight inherited
Referenced by mdlbb(), and setbbfrommodel().
float animmodel::lastalphatest = -1 static inherited
Referenced by animmodel::startrender().
GLuint animmodel::lastbbuf = 0 static inherited
Referenced by animmodel::meshgroup::bindbones(), animmodel::disablevbo(), and animmodel::startrender().
GLuint animmodel::lastebuf = 0 static inherited
Referenced by animmodel::meshgroup::bindpos(), animmodel::disablevbo(), animmodel::endrender(), and animmodel::startrender().
GLuint animmodel::lastenvmaptex = 0 static inherited
Referenced by animmodel::skin::bind(), and animmodel::startrender().
Texture * animmodel::lastmasks = nullptr static inherited
Referenced by animmodel::skin::bind(), and animmodel::startrender().
GLuint animmodel::lastnbuf = 0 static inherited
Referenced by animmodel::meshgroup::bindnormals(), animmodel::disablevbo(), and animmodel::startrender().
Texture * animmodel::lastnormalmap = nullptr static inherited
Referenced by animmodel::skin::bind(), and animmodel::startrender().
GLuint animmodel::lasttcbuf = 0 static inherited
Referenced by animmodel::meshgroup::bindtc(), animmodel::disablevbo(), and animmodel::startrender().
Texture * animmodel::lasttex = nullptr static inherited
Referenced by animmodel::skin::bind(), and animmodel::startrender().
GLuint animmodel::lastvbuf = 0 static inherited
Referenced by animmodel::meshgroup::bindbones(), animmodel::meshgroup::bindnormals(), animmodel::meshgroup::bindpos(), animmodel::meshgroup::bindtangents(), animmodel::meshgroup::bindtc(), animmodel::disablevbo(), animmodel::endrender(), and animmodel::startrender().
GLuint animmodel::lastxbuf = 0 static inherited
Referenced by animmodel::meshgroup::bindtangents(), animmodel::disablevbo(), and animmodel::startrender().
vec animmodel::lightcolor static inherited
Referenced by animmodel::render(), and animmodel::skin::setshaderparams().
vec animmodel::lightdir static inherited
Referenced by animmodel::part::render(), and animmodel::render().
smd * modelloader< smd >::loading static inherited
Referenced by load().
int animmodel::matrixpos = 0 static inherited
Referenced by skelmodel::skeleton::initragdoll(), animmodel::part::render(), and animmodel::render().
matrix4 animmodel::matrixstack static inherited
Referenced by skelmodel::skeleton::initragdoll(), animmodel::part::render(), and animmodel::render().
char* model::name inherited
Referenced by obj::objmeshgroup::load(), md5::md5mesh::load(), md3::load(), obj::load(), md2::load(), md5::md5meshgroup::load(), iqm::load(), md5::load(), load(), md3::loaddefaultparts(), obj::loaddefaultparts(), iqm::loaddefaultparts(), md5::loaddefaultparts(), loaddefaultparts(), iqm::iqmmeshgroup::loadiqmanims(), md5::md5meshgroup::loadmesh(), iqm::iqmmeshgroup::loadmesh(), loadmodel(), animmodel::skin::loadshader(), mdlname(), animmodel::part::setanim(), animmodel::sharemeshes(), and model::~model().
float model::offsetpitch inherited
Referenced by animmodel::initmatrix(), mdlpitch(), and animmodel::render().
float model::offsetyaw inherited
Referenced by animmodel::initmatrix(), mdlyaw(), and animmodel::render().
vector<part *> animmodel::parts inherited
Referenced by md2::addpart(), animmodel::addpart(), skelmodel::addpart(), animmodel::calcbb(), animmodel::cleanup(), animmodel::envmapped(), animmodel::genBIH(), animmodel::link(), skelmodel::linktype(), md5::md5mesh::load(), md3::load(), obj::load(), iqm::load(), md5::load(), load(), animmodel::loaded(), animmodel::preloadBIH(), animmodel::preloadmeshes(), animmodel::preloadshaders(), animmodel::render(), animmodel::setalphablend(), animmodel::setalphatest(), animmodel::setambient(), vertcommands< MDL >::setanim(), animmodel::setcullface(), animmodel::setenvmap(), animmodel::setfullbright(), animmodel::setglare(), animmodel::setglow(), vertcommands< MDL >::setpitch(), animmodel::setshader(), animmodel::setspec(), animmodel::unlink(), and animmodel::~animmodel().
float model::rejectradius inherited
Referenced by model::collisionbox().
float model::scale inherited
Referenced by animmodel::part::calcbb(), vertmodel::vertmeshgroup::calctagmatrix(), skelmodel::skeleton::calctags(), vertmodel::vertmeshgroup::concattagtransform(), skelmodel::skeleton::concattagtransform(), animmodel::part::genBIH(), skelmodel::skeleton::genragdollbones(), skelmodel::skeleton::initragdoll(), animmodel::loaded(), mdlscale(), animmodel::part::render(), skelmodel::skelmeshgroup::render(), and animmodel::skin::setshaderparams().
bool model::shadow inherited
Referenced by mdlshadow(), and mmintersect().
float model::spinpitch inherited
Referenced by mdlspin(), and animmodel::render().
float model::spinyaw inherited
Referenced by mdlspin(), and animmodel::render().
vec model::translate inherited
Referenced by animmodel::link(), md3::load(), obj::load(), md2::load(), animmodel::loaded(), and mdltrans().
float animmodel::transparent = 1 static inherited
Referenced by animmodel::skin::bind(), animmodel::render(), animmodel::skin::setshaderparams(), and animmodel::startrender().
The documentation for this struct was generated from the following file:
inexor/model/smd.hpp