Inexor: menu Struct Reference
menu Struct Reference
Public Member Functions
menu ()
void gui (g3d_gui &g, bool firstpass) override
virtual void clear ()
int starttime ()
Public Attributes
char * name
char * header
uint * contents
uint * init
uint * onclear
bool showtab
Constructor & Destructor Documentation
menu::menu () inline
Member Function Documentation
virtual void menu::clear () inline virtual
Reimplemented in applymenu.
References freecode(), and onclear.
Referenced by applymenu::clear(), popgui(), and removegui().
void menu::gui (g3d_gui & g, bool firstpass) inline override virtual
Implements g3d_callback.
Reimplemented in applymenu.
References contents, g3d_gui::end(), execute(), f(), GUI_TITLE_COLOR, header, menustart, menutab, name, showtab, g3d_gui::start(), and g3d_gui::tab().
int g3d_callback::starttime () inherited
References totalmillis.
Referenced by game::scoreboardgui::show().
Member Data Documentation
uint* menu::contents
Referenced by gui(), and newgui().
char * menu::header
Referenced by gui(), and newgui().
uint * menu::init
Referenced by newgui(), and pushgui().
char* menu::name
Referenced by gui(), and newgui().
uint * menu::onclear
Referenced by clear(), clearguis(), and guionclear().
bool menu::showtab
Referenced by gui(), and newgui().
The documentation for this struct was generated from the following file:
inexor/ui/legacy/menus.cpp