Inexor: hline Struct Reference
hline Struct Reference
Public Member Functions
hline ()
~hline ()
void restore ()
bool shouldsave ()
void save ()
void run ()
Public Attributes
char * buf
char * action
char * prompt
int flags
Constructor & Destructor Documentation
hline::hline () inline
hline::~hline () inline
References DELETEA.
Member Function Documentation
void hline::restore () inline
References commandaction, commandbuf, commandflags, commandpos, commandprompt, copystring(), DELETEA, hmap::flags, and newstring().
void hline::run () inline
References alias(), CF_EXECUTE, execute(), hmap::flags, and game::toserver().
Referenced by consolekey().
void hline::save () inline
References commandaction, commandbuf, commandflags, commandprompt, hmap::flags, and newstring().
bool hline::shouldsave () inline
References commandaction, commandbuf, commandflags, commandprompt, and hmap::flags.
Member Data Documentation
char * hline::action
Referenced by loadhistory().
char* hline::buf
Referenced by loadhistory(), and writehistory().
int hline::flags
Referenced by loadhistory().
char * hline::prompt
Referenced by loadhistory().
The documentation for this struct was generated from the following file:
inexor/engine/console.cpp