Inexor: game::bombclientmode Struct Reference
game::bombclientmode Struct Reference
#include <bomb_client.hpp>
Public Member Functions
void setup () override
void senditems (packetbuf &p) override
void drawicon (int icon, float x, float y, float sz)
void drawblip (fpsent *d, float x, float y, float s, const vec &pos, float size_factor)
void drawhud (fpsent *d, int w, int h) override
void renderplayersposindicator ()
void rendergame () override
void renderscoreboard (g3d_gui &g, scoregroup &sg, int fgcolor, int bgcolor) override
void killed (fpsent *d, fpsent *actor) override
void gameconnect (fpsent *d) override
void pickspawn (fpsent *d) override
bool parse_network_message (int type, ucharbuf &p) override
Parse game mode specific network messages.
virtual void preload ()
virtual int clipconsole (int w, int h)
virtual bool isinvisible (fpsent *d)
virtual void respawned (fpsent *d)
virtual void checkitems (fpsent *d)
virtual int respawnwait (fpsent *d)
virtual void addplayer (fpsent *d)
virtual void removeplayer (fpsent *d)
virtual void gameover ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual void aifind (fpsent *d, ai::aistate &b, vector< ai::interest > &interests)
virtual bool aicheck (fpsent *d, ai::aistate &b)
virtual bool aidefend (fpsent *d, ai::aistate &b)
virtual bool aipursue (fpsent *d, ai::aistate &b)
Public Attributes
int myspawnloc
Member Function Documentation
virtual void game::clientmode::addplayer (fpsent * d) inline virtual inherited
virtual bool game::clientmode::aicheck (fpsent * d, ai::aistate & b) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::check().
virtual bool game::clientmode::aidefend (fpsent * d, ai::aistate & b) inline virtual inherited
Reimplemented in game::ctfclientmode, and game::captureclientmode.
Referenced by ai::dodefend().
virtual void game::clientmode::aifind (fpsent * d, ai::aistate & b, vector< ai::interest > & interests) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::find().
virtual bool game::clientmode::aipursue (fpsent * d, ai::aistate & b) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::dopursue().
virtual void game::clientmode::checkitems (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::logic(), and game::updateworld().
virtual int game::clientmode::clipconsole (int w, int h) inline virtual inherited
Reimplemented in game::captureclientmode, game::collectclientmode, and game::ctfclientmode.
Referenced by game::clipconsole().
void game::bombclientmode::drawblip (fpsent * d, float x, float y, float s, const vec & pos, float size_factor)
References game::calcradarscale(), camera1, dir, vec::div(), game::drawradar(), f(), vec::magnitude2(), vec::mul(), physent::o, RAD, vec::rotate_around_z(), vec::sub(), and physent::yaw.
Referenced by drawhud().
void game::bombclientmode::drawhud (fpsent * d, int w, int h) override virtual
Reimplemented from game::clientmode.
References bindminimap(), game::BNC_BOMB, fpsstate::bombdelay, fpsstate::bombradius, game::bouncers, game::bouncer::bouncetype, CS_ALIVE, fpsent::deaths, defformatstring, draw_text(), draw_textf(), drawblip(), drawicon(), game::drawminimap(), game::drawradar(), f(), formatstring(), HICON_BOMBDELAY, HICON_BOMBRADIUS, HICON_SIZE, HICON_SPACE, HICON_STEP, HICON_TEXTY, HICON_X, HICON_Y, game::intermission, game::isobstaclealive(), isteam, loopv, m_teammode, inexor::rpc::max(), game::minimapalpha, game::movables, physent::o, game::bouncer::owner, game::player1, game::players, fpsstate::quadmillis, radardir, game::setbliptex(), game::setradartex(), settexture(), game::showminimapobstacles, physent::state, fpsent::team, TEAM_OPPONENT, TEAM_OWN, and text_bounds().
void game::bombclientmode::drawicon (int icon, float x, float y, float sz)
References bind_bomb_items_texture(), and HICON_BOMBRADIUS.
Referenced by drawhud().
void game::bombclientmode::gameconnect (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
References CS_SPECTATOR, fpsent::deaths, and physent::state.
virtual void game::clientmode::gameover () inline virtual inherited
Referenced by game::timeupdate().
virtual int game::clientmode::getteamscore (const char * team) inline virtual inherited
Referenced by game::groupplayers().
virtual void game::clientmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by game::getbestteams().
virtual bool game::clientmode::hidefrags () inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::getbestteams(), game::groupplayers(), game::parsemessages(), and game::renderscoreboard().
virtual bool game::clientmode::isinvisible (fpsent * d) inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::rendergame().
void game::bombclientmode::killed (fpsent * d, fpsent * actor) override virtual
Reimplemented from game::clientmode.
References fpsent::clientnum, CS_SPECTATOR, game::following, physent::o, physent::pitch, game::player1, physent::resetinterp(), physent::state, and physent::yaw.
bool game::bombclientmode::parse_network_message (int type, ucharbuf & p) override virtual
Parse game mode specific network messages.
Returns
true if message got handled.
Implements game::clientmode.
References getint(), myspawnloc, and N_SPAWNLOC.
void game::bombclientmode::pickspawn (fpsent * d) override virtual
Reimplemented from game::clientmode.
References entity::attr1, entinmap(), entities::ents, myspawnloc, entity::o, physent::o, physent::pitch, physent::roll, and physent::yaw.
virtual void game::clientmode::preload () inline virtual inherited
Reimplemented in game::captureclientmode, game::collectclientmode, and game::ctfclientmode.
Referenced by game::startgame().
virtual void game::clientmode::removeplayer (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode.
Referenced by game::clientdisconnected().
void game::bombclientmode::rendergame () inline override virtual
Reimplemented from game::clientmode.
References renderplayersposindicator().
void game::bombclientmode::renderplayersposindicator ()
References ANIM_LOOP, ANIM_MAPMODEL, camera1, CS_ALIVE, f(), physent::feetpos(), lastmillis, loopv, m_teammode, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_GHOST, MDL_LIGHT, physent::o, game::player1, game::players, rendermodel(), physent::state, vec::sub(), fpsent::team, and vectoyawpitch().
Referenced by rendergame().
void game::bombclientmode::renderscoreboard (g3d_gui & g, scoregroup & sg, int fgcolor, int bgcolor) override virtual
Reimplemented from game::clientmode.
References fpsstate::ammo, fpsstate::bombdelay, fpsstate::bombradius, hmap::d, f(), GUN_BOMB, loopv, scoregroup::players, g3d_gui::poplist(), g3d_gui::pushlist(), g3d_gui::strut(), g3d_gui::text(), and g3d_gui::textf().
virtual void game::clientmode::respawned (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode, game::hideandseekclientmode, and game::captureclientmode.
Referenced by game::parsemessages().
virtual int game::clientmode::respawnwait (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by game::respawn(), and ai::think().
void game::bombclientmode::senditems (packetbuf & p) override virtual
Reimplemented from game::clientmode.
References vector< T, MINSIZE >::add(), entity::attr2, DMF, entities::ents, spawnloc::index, vector< T, MINSIZE >::length(), loopk, loopv, m_teammode, N_SPAWNLOC, spawnloc::o, entity::o, PLAYERSTART, putint(), spawnloc::team, and entity::type.
void game::bombclientmode::setup () inline override virtual
Reimplemented from game::clientmode.
References myspawnloc.
Member Data Documentation
int game::bombclientmode::myspawnloc
Referenced by parse_network_message(), pickspawn(), and setup().
The documentation for this struct was generated from the following files:
inexor/client/gamemode/bomb_client.hpp
inexor/client/gamemode/bomb_client.cpp