Inexor: md5::md5meshgroup Struct Reference
md5::md5meshgroup Struct Reference
#include <md5.hpp>
Public Member Functions
md5meshgroup ()
bool loadmesh (const char *filename, float smooth)
skelanimspec * loadanim (const char *filename) override
bool load (const char *meshfile, float smooth)
Constructor & Destructor Documentation
md5::md5meshgroup::md5meshgroup () inline
Member Function Documentation
bool md5::md5meshgroup::load (const char * meshfile, float smooth) inline
References loadmesh(), model::name, and newstring().
Referenced by md5::loadmeshes().
skelanimspec* md5::md5meshgroup::loadanim (const char * filename) inline override
References vector< T, MINSIZE >::add(), skelloader< md5 >::adjustments, f(), dualquat::fixantipodal(), md5hierarchy::flags, skelmodel::skelanimspec::frame, stream::getline(), vector< T, MINSIZE >::inrange(), vector< T, MINSIZE >::length(), loopv, dualquat::mul(), md5hierarchy::name, openfile(), md5joint::orient, md5hierarchy::parent, md5joint::pos, skelmodel::skelanimspec::range, quat::restorew(), and md5hierarchy::start.
bool md5::md5meshgroup::loadmesh (const char * filename, float smooth) inline
References vector< T, MINSIZE >::add(), skelmodel::boneinfo::base, skelmodel::skelmesh::buildnorms(), md5::md5mesh::buildverts(), md5::md5mesh::cleanup(), f(), stream::getline(), skelmodel::boneinfo::invbase, vector< T, MINSIZE >::length(), md5::md5mesh::load(), Log, loopv, model::name, newstring(), skelmodel::skelmesh::numtris, skelmodel::skelmesh::numverts, openfile(), md5joint::orient, orient, md5joint::pos, quat::restorew(), skelmodel::skelmesh::smoothnorms(), and inexor::util::log_manager::std.
Referenced by load().
The documentation for this struct was generated from the following file:
inexor/model/md5.hpp