Inexor: utf8stream Struct Reference
utf8stream Struct Reference
Public Types
enum { BUFSIZE = 4096 }
typedef off_t offset
Public Member Functions
utf8stream ()
~utf8stream () override
bool readbuf (size_t size=BUFSIZE)
bool checkheader ()
bool open (stream *f, const char *mode, bool needclose)
void finishreading ()
void stopreading ()
void stopwriting ()
void close () override
bool end () override
offset tell () override
bool seek (offset off, int whence) override
size_t read (void *dst, size_t len) override
bool getline (char *dst, size_t len) override
size_t write (const void *src, size_t len) override
bool flush () override
virtual offset rawtell ()
virtual offset size ()
virtual offset rawsize ()
virtual int getchar ()
virtual bool putchar (int n)
virtual bool putstring (const char *str)
virtual bool putline (const char *str)
virtual size_t printf (const char *fmt,...) PRINTFARGS(2
virtual size_t virtual uint getcrc ()
template<class T >
size_t put (const T *v, size_t n)
template<class T >
bool put (T n)
template<class T >
bool putlil (T n)
template<class T >
bool putbig (T n)
template<class T >
size_t get (T *v, size_t n)
template<class T >
T get ()
template<class T >
T getlil ()
template<class T >
T getbig ()
Public Attributes
stream * file
offset pos
size_t bufread
size_t bufcarry
size_t buflen
bool reading
bool writing
bool autoclose
uchar buf [BUFSIZE]
Member Typedef Documentation
typedef off_t stream::offset inherited
Member Enumeration Documentation
anonymous enum
Enumerator
BUFSIZE
Constructor & Destructor Documentation
utf8stream::utf8stream () inline
utf8stream::~utf8stream () inline override
References close().
Member Function Documentation
bool utf8stream::checkheader () inline
References buf, buflen, file, and stream::read().
Referenced by open(), and seek().
void utf8stream::close () inline override virtual
Implements stream.
References autoclose, DELETEP, file, stopreading(), and stopwriting().
Referenced by ~utf8stream().
bool utf8stream::end () inline override virtual
Implements stream.
References reading, and writing.
void utf8stream::finishreading () inline
References reading.
bool utf8stream::flush () inline override virtual
Reimplemented from stream.
References file, and stream::flush().
template<class T > size_t stream::get (T * v, size_t n) inline inherited
References stream::read().
Referenced by streambuf< T >::get().
template<class T > T stream::get () inline inherited
References stream::read().
template<class T > T stream::getbig () inline inherited
References bigswap().
virtual int stream::getchar () inline virtual inherited
Reimplemented in filestream.
References stream::read().
Referenced by load_world(), loadblendmap(), loadc(), loadents(), loadviewcells(), and ai::loadwaypoints().
virtual size_t virtual uint stream::getcrc () inline virtual inherited
Reimplemented in gzstream.
Referenced by load_world(), and loadents().
template<class T > T stream::getlil () inline inherited
References lilswap().
Referenced by load_world(), loadc(), loadents(), loadpvs(), loadviewcells(), loadvslot(), loadvslots(), ai::loadwaypoints(), and gzstream::size().
bool utf8stream::getline (char * dst, size_t len) inline override virtual
Reimplemented from stream.
References buf, bufcarry, bufread, BUFSIZE, inexor::rpc::min(), pos, readbuf(), reading, and stopreading().
bool utf8stream::open (stream * f, const char * mode, bool needclose) inline
References autoclose, checkheader(), f(), file, reading, and writing.
Referenced by openutf8file().
size_t stream::printf (const char * fmt, ...) virtual inherited
Reimplemented in filestream.
References _vsnprintf, and stream::write().
Referenced by writebinds(), writecfg(), game::writeclientinfo(), writecompletions(), writecrosshairs(), writeinitcfg(), and writeobj().
template<class T > size_t stream::put (const T * v, size_t n) inline inherited
References stream::write().
Referenced by streambuf< T >::put().
template<class T > bool stream::put (T n) inline inherited
References stream::write().
template<class T > bool stream::putbig (T n) inline inherited
References bigswap().
Referenced by savepng(), and writepngchunk().
virtual bool stream::putchar (int n) inline virtual inherited
Reimplemented in filestream.
References stream::write().
Referenced by stream::putline(), save_world(), saveblendmap(), savec(), savetga(), saveviewcells(), and ai::savewaypoints().
template<class T > bool stream::putlil (T n) inline inherited
References lilswap().
Referenced by save_world(), savec(), savepvs(), saveviewcells(), savevslot(), savevslots(), and ai::savewaypoints().
virtual bool stream::putline (const char * str) inline virtual inherited
References stream::putchar(), and stream::putstring().
Referenced by editor::save(), and writehistory().
virtual bool stream::putstring (const char * str) inline virtual inherited
Reimplemented in filestream.
References stream::write().
Referenced by stream::putline().
virtual offset stream::rawsize () inline virtual inherited
Reimplemented in gzstream.
References stream::size().
virtual offset stream::rawtell () inline virtual inherited
Reimplemented in gzstream.
References stream::tell().
Referenced by server::writedemo().
size_t utf8stream::read (void * dst, size_t len) inline override virtual
Reimplemented from stream.
References buf, bufcarry, bufread, BUFSIZE, inexor::rpc::min(), pos, readbuf(), reading, and stopreading().
Referenced by seek().
bool utf8stream::readbuf (size_t size = BUFSIZE) inline
References buf, bufcarry, buflen, bufread, BUFSIZE, decodeutf8(), file, inexor::rpc::min(), and stream::read().
Referenced by getline(), and read().
bool utf8stream::seek (offset off, int whence) inline override virtual
Reimplemented from stream.
References bufcarry, buflen, bufread, checkheader(), inexor::rpc::min(), pos, read(), reading, stopreading(), and writing.
stream::offset stream::size () virtual inherited
Reimplemented in gzstream.
References stream::seek(), and stream::tell().
Referenced by server::adddemo(), streambuf< T >::length(), loadfile(), make_file_packet(), stream::rawsize(), gzstream::rawsize(), and game::sendmap().
void utf8stream::stopreading () inline
References reading.
Referenced by close(), getline(), read(), and seek().
void utf8stream::stopwriting () inline
References writing.
Referenced by close(), and write().
offset utf8stream::tell () inline override virtual
Reimplemented from stream.
References pos, reading, and writing.
size_t utf8stream::write (const void * src, size_t len) inline override virtual
Reimplemented from stream.
References encodeutf8(), file, pos, stopwriting(), stream::write(), and writing.
Member Data Documentation
bool utf8stream::autoclose
Referenced by close(), and open().
uchar utf8stream::buf[BUFSIZE]
Referenced by checkheader(), getline(), read(), and readbuf().
size_t utf8stream::bufcarry
Referenced by getline(), read(), readbuf(), and seek().
size_t utf8stream::buflen
Referenced by checkheader(), readbuf(), and seek().
size_t utf8stream::bufread
Referenced by getline(), read(), readbuf(), and seek().
stream* utf8stream::file
Referenced by checkheader(), close(), flush(), open(), readbuf(), and write().
offset utf8stream::pos
Referenced by getline(), read(), seek(), tell(), and write().
bool utf8stream::reading
Referenced by end(), finishreading(), getline(), open(), read(), seek(), stopreading(), and tell().
bool utf8stream::writing
Referenced by end(), open(), seek(), stopwriting(), tell(), and write().
The documentation for this struct was generated from the following file:
inexor/io/legacy/stream.cpp