Inexor: shaft Struct Reference
shaft Struct Reference
Public Member Functions
shaft (const shaftbb &from, const shaftbb &to)
void calcshaft (const shaftbb &from, const shaftbb &to)
bool outside (const shaftbb &o) const
bool inside (const shaftbb &o) const
Public Attributes
shaftbb bounds
shaftplane planes [8]
int numplanes
Constructor & Destructor Documentation
shaft::shaft (const shaftbb & from, const shaftbb & to) inline
Member Function Documentation
void shaft::calcshaft (const shaftbb & from, const shaftbb & to) inline
References shaftplane::c, shaftplane::cfar, shaftplane::cnear, gle::color(), hmap::d, loopi(), shaftplane::offset, shaftplane::r, shaftplane::rfar, and shaftplane::rnear.
bool shaft::inside (const shaftbb & o) const inline
Referenced by pvsworker::shaftcullpvs().
bool shaft::outside (const shaftbb & o) const inline
Referenced by pvsworker::shaftcullpvs().
Member Data Documentation
shaftbb shaft::bounds
int shaft::numplanes
shaftplane shaft::planes[8]
The documentation for this struct was generated from the following file:
inexor/engine/pvs.cpp