Inexor: server::collectservermode Struct Reference
server::collectservermode Struct Reference
#include <collect_server.hpp>
Public Member Functions
token & droptoken (const vec &o, int yaw, int team, int droptime, int dropper)
void reset (bool empty)
void cleanup () override
void setup () override
void newmap () override
void droptokens (clientinfo *ci, bool penalty=false)
void leavegame (clientinfo *ci, bool disconnecting=false) override
void died (clientinfo *ci, clientinfo *actor) override
bool canspawn (clientinfo *ci, bool connecting) override
bool canchangeteam (clientinfo *ci, const char *oldteam, const char *newteam) override
void changeteam (clientinfo *ci, const char *oldteam, const char *newteam) override
void deposittokens (clientinfo *ci, int basenum)
void taketoken (clientinfo *ci, int id)
void update () override
void initclient (clientinfo *ci, packetbuf &p, bool connecting) override
void parsebases (ucharbuf &p, bool commit)
bool parse_network_message (int type, clientinfo *ci, clientinfo *cq, packetbuf &p) override
process gamemode specific network messages.
virtual void entergame (clientinfo *ci)
virtual void connected (clientinfo *ci)
virtual void moved (clientinfo *ci, const vec &oldpos, bool oldclip, const vec &newpos, bool newclip)
virtual void spawned (clientinfo *ci)
virtual int fragvalue (clientinfo *victim, clientinfo *actor)
virtual bool canhit (clientinfo *victim, clientinfo *actor)
virtual void updatelimbo ()
virtual void intermission ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual bool extinfoteam (const char *team, ucharbuf &p)
void resetbases ()
bool addbase (int i, const vec &o, int team)
token * findtoken (int id)
token & droptoken (const vec &o, int team, int droptime)
bool removetoken (int id)
int totalscore (int team)
int setscore (int team, int score)
int addscore (int team, int score)
bool hidefrags ()
int getteamscore (const char *team)
void getteamscores (vector< teamscore > &tscores)
bool insidebase (const base &b, const vec &o)
Public Attributes
bool notgotbases = false
vector< base > bases
int scores [2]
vector< token > tokens
int nexttoken
Static Public Attributes
static const int BASERADIUS = 16
static const int BASEHEIGHT = 16
static const int MAXBASES = 20
static const int TOKENRADIUS = 16
static const int TOKENLIMIT = 5
static const int UNOWNEDTOKENLIMIT = 15
static const int TOKENDIST = 16
static const int SCORELIMIT = 50
static const int RESPAWNSECS = 5
static const int EXPIRETOKENTIME = 10000
static const int STEALTOKENTIME = 5000
Member Function Documentation
bool collectmode_common::addbase (int i, const vec & o, int team) inline inherited
References collectmode_common::bases, collectmode_common::base::id, collectmode_common::MAXBASES, collectmode_common::base::o, collectmode_common::base::reset(), and collectmode_common::base::team.
Referenced by parsebases(), setup(), and game::collectclientmode::setup().
int collectmode_common::addscore (int team, int score) inline inherited
References collectmode_common::scores.
Referenced by deposittokens().
bool server::collectservermode::canchangeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline override virtual
Reimplemented from server::servmode.
References collectteambase.
virtual bool server::servmode::canhit (clientinfo * victim, clientinfo * actor) inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::dodamage().
bool server::collectservermode::canspawn (clientinfo * ci, bool connecting) inline override virtual
Reimplemented from server::servmode.
References curtime, gamemillis, server::gamestate::lastdeath, collectmode_common::RESPAWNSECS, and server::clientinfo::state.
void server::collectservermode::changeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline override virtual
Reimplemented from server::servmode.
void server::collectservermode::cleanup () inline override virtual
Reimplemented from server::servmode.
References reset().
virtual void server::servmode::connected (clientinfo * ci) inline virtual inherited
Reimplemented in server::hideandseekservermode.
void server::collectservermode::deposittokens (clientinfo * ci, int basenum)
References collectmode_common::addscore(), collectmode_common::bases, server::clientinfo::clientnum, collectbaseteam, collectteambase, CS_ALIVE, DMF, droptoken(), server::gamestate::flags, gamemillis, collectmode_common::token::id, lastmillis, collectmode_common::base::laststeal, loopv, N_DEPOSITTOKENS, N_STEALTOKENS, notgotbases, collectmode_common::base::o, collectmode_common::token::o, rnd(), collectmode_common::SCORELIMIT, sendf(), server::startintermission(), server::gamestate::state, server::clientinfo::state, collectmode_common::STEALTOKENTIME, anonymous_namespace{utilTest.cpp}::t(), collectmode_common::base::team, server::clientinfo::team, collectmode_common::TOKENLIMIT, collectmode_common::tokens, server::gamestate::tokens, collectmode_common::totalscore(), and collectmode_common::token::yaw.
Referenced by parse_network_message().
void server::collectservermode::died (clientinfo * ci, clientinfo * actor) inline override virtual
Reimplemented from server::servmode.
References droptokens(), isteam, and server::clientinfo::team.
collectmode_common::token & server::collectservermode::droptoken (const vec & o, int yaw, int team, int droptime, int dropper)
References collectmode_common::token::dropper, collectmode_common::droptoken(), collectmode_common::token::id, collectmode_common::nexttoken, anonymous_namespace{utilTest.cpp}::t(), and collectmode_common::token::yaw.
Referenced by deposittokens(), and droptokens().
token& collectmode_common::droptoken (const vec & o, int team, int droptime) inline inherited
References collectmode_common::token::droptime, collectmode_common::token::o, anonymous_namespace{utilTest.cpp}::t(), collectmode_common::token::team, and collectmode_common::tokens.
Referenced by droptoken(), and game::collectclientmode::droptoken().
void server::collectservermode::droptokens (clientinfo * ci, bool penalty = false)
References server::clientinfo::clientnum, collectteambase, DMF, collectmode_common::token::dropper, droptoken(), packetbuf::finalize(), collectmode_common::token::id, lastmillis, loopi(), loopvrev, N_DROPTOKENS, N_EXPIRETOKENS, notgotbases, server::gamestate::o, putint(), rnd(), sendpacket(), server::clientinfo::state, anonymous_namespace{utilTest.cpp}::t(), collectmode_common::token::team, server::clientinfo::team, collectmode_common::TOKENLIMIT, collectmode_common::tokens, server::gamestate::tokens, and collectmode_common::token::yaw.
Referenced by died().
virtual void server::servmode::entergame (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::extinfoteam (const char * team, ucharbuf & p) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::extinfoteamscore().
token* collectmode_common::findtoken (int id) inline inherited
References loopv, and collectmode_common::tokens.
Referenced by game::collectclientmode::aipursue(), game::collectclientmode::expiretoken(), game::collectclientmode::taketoken(), and taketoken().
virtual int server::servmode::fragvalue (clientinfo * victim, clientinfo * actor) inline virtual inherited
References isteam, and server::clientinfo::team.
Referenced by server::dodamage(), and server::suicide().
virtual int server::servmode::getteamscore (const char * team) inline virtual inherited
int collectmode_common::getteamscore (const char * team) inline inherited
References collectteambase, and collectmode_common::totalscore().
virtual void server::servmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by server::extinfoteams().
void collectmode_common::getteamscores (vector< teamscore > & tscores) inline inherited
References vector< T, MINSIZE >::add(), collectbaseteam, loopk, and collectmode_common::scores.
virtual bool server::servmode::hidefrags () inline virtual inherited
Referenced by server::autoteam(), server::chooseworstteam(), and server::extinfoteams().
bool collectmode_common::hidefrags () inline inherited
void server::collectservermode::initclient (clientinfo * ci, packetbuf & p, bool connecting) override virtual
Reimplemented from server::servmode.
References server::clients, CS_ALIVE, DMF, collectmode_common::token::id, loopk, loopv, N_INITTOKENS, collectmode_common::token::o, putint(), collectmode_common::scores, recorder::state, anonymous_namespace{utilTest.cpp}::t(), collectmode_common::token::team, collectmode_common::tokens, and collectmode_common::token::yaw.
bool collectmode_common::insidebase (const base & b, const vec & o) inline inherited
References collectmode_common::BASEHEIGHT, collectmode_common::BASERADIUS, and collectmode_common::base::o.
Referenced by game::collectclientmode::checkitems().
virtual void server::servmode::intermission () inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::checkintermission().
void server::collectservermode::leavegame (clientinfo * ci, bool disconnecting = false) override virtual
Reimplemented from server::servmode.
References server::clientinfo::clientnum, collectteambase, collectmode_common::token::dropper, packetbuf::finalize(), collectmode_common::token::id, loopvrev, N_EXPIRETOKENS, putint(), sendpacket(), server::clientinfo::state, anonymous_namespace{utilTest.cpp}::t(), collectmode_common::token::team, server::clientinfo::team, collectmode_common::tokens, server::gamestate::tokens, and collectmode_common::UNOWNEDTOKENLIMIT.
virtual void server::servmode::moved (clientinfo * ci, const vec & oldpos, bool oldclip, const vec & newpos, bool newclip) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
void server::collectservermode::newmap () inline override virtual
Reimplemented from server::servmode.
References reset().
bool server::collectservermode::parse_network_message (int type, clientinfo * ci, clientinfo * cq, packetbuf & p) override virtual
process gamemode specific network messages.
Parameters
type the N_ network message type
ci the sender.
cq the currently focused player (sender or bot from senders pc)
p the network packet containing the data
Returns
whether this messages got processed.
Implements server::servmode.
References server::clientinfo::clientmap, CS_SPECTATOR, deposittokens(), getint(), N_DEPOSITTOKENS, N_INITTOKENS, N_TAKETOKEN, parsebases(), server::clientinfo::privilege, server::smapname, server::gamestate::state, server::clientinfo::state, and taketoken().
void server::collectservermode::parsebases (ucharbuf & p, bool commit)
References collectmode_common::addbase(), DMF, f(), getint(), loopi(), loopk, inexor::rpc::max(), notgotbases, and databuf< T >::overread().
Referenced by parse_network_message().
bool collectmode_common::removetoken (int id) inline inherited
References loopv, and collectmode_common::tokens.
Referenced by game::collectclientmode::expiretoken(), and game::collectclientmode::taketoken().
void server::collectservermode::reset (bool empty) inline
References notgotbases, and collectmode_common::resetbases().
Referenced by cleanup(), newmap(), and setup().
void collectmode_common::resetbases () inline inherited
References collectmode_common::bases, loopk, collectmode_common::nexttoken, collectmode_common::scores, and collectmode_common::tokens.
Referenced by reset(), and game::collectclientmode::setup().
int collectmode_common::setscore (int team, int score) inline inherited
References collectmode_common::scores.
Referenced by game::collectclientmode::deposittokens(), and game::collectclientmode::stealtoken().
void server::collectservermode::setup () override virtual
Reimplemented from server::servmode.
References collectmode_common::addbase(), entity::attr2, collectmode_common::bases, FLAG, loopv, server::ments, notgotbases, server::notgotitems, entity::o, reset(), and entity::type.
virtual void server::servmode::spawned (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
void server::collectservermode::taketoken (clientinfo * ci, int id)
References server::clientinfo::clientnum, collectteambase, CS_ALIVE, collectmode_common::findtoken(), N_TAKETOKEN, notgotbases, sendf(), server::gamestate::state, server::clientinfo::state, anonymous_namespace{utilTest.cpp}::t(), collectmode_common::token::team, server::clientinfo::team, collectmode_common::TOKENLIMIT, and server::gamestate::tokens.
Referenced by parse_network_message().
int collectmode_common::totalscore (int team) inline inherited
References collectmode_common::scores.
Referenced by deposittokens(), collectmode_common::getteamscore(), and game::collectclientmode::rendergame().
void server::collectservermode::update () override virtual
Reimplemented from server::servmode.
References vector< T, MINSIZE >::add(), collectmode_common::token::droptime, collectmode_common::EXPIRETOKENTIME, server::gamelimit, gamemillis, vector< T, MINSIZE >::getbuf(), collectmode_common::token::id, lastmillis, vector< T, MINSIZE >::length(), loopvrev, N_EXPIRETOKENS, notgotbases, sendf(), anonymous_namespace{utilTest.cpp}::t(), and collectmode_common::tokens.
virtual void server::servmode::updatelimbo () inline virtual inherited
Reimplemented in server::bombservermode.
Referenced by server::serverupdate().
Member Data Documentation
const int collectmode_common::BASEHEIGHT = 16 static inherited
Referenced by collectmode_common::insidebase().
const int collectmode_common::BASERADIUS = 16 static inherited
Referenced by collectmode_common::insidebase().
vector<base> collectmode_common::bases inherited
Referenced by collectmode_common::addbase(), game::collectclientmode::aicheck(), game::collectclientmode::aifind(), game::collectclientmode::aipursue(), game::collectclientmode::checkitems(), game::collectclientmode::deposittokens(), deposittokens(), game::collectclientmode::drawbaseblip(), game::collectclientmode::drawhud(), game::collectclientmode::rendergame(), collectmode_common::resetbases(), game::collectclientmode::senditems(), setup(), game::collectclientmode::setup(), and game::collectclientmode::stealtoken().
const int collectmode_common::EXPIRETOKENTIME = 10000 static inherited
Referenced by update().
const int collectmode_common::MAXBASES = 20 static inherited
Referenced by collectmode_common::addbase().
int collectmode_common::nexttoken inherited
Referenced by droptoken(), and collectmode_common::resetbases().
bool server::collectservermode::notgotbases = false
Referenced by deposittokens(), droptokens(), parsebases(), reset(), setup(), taketoken(), and update().
const int collectmode_common::RESPAWNSECS = 5 static inherited
Referenced by canspawn(), and game::collectclientmode::respawnwait().
const int collectmode_common::SCORELIMIT = 50 static inherited
Referenced by game::collectclientmode::deposittokens(), and deposittokens().
int collectmode_common::scores[2] inherited
Referenced by collectmode_common::addscore(), collectmode_common::getteamscores(), initclient(), game::collectclientmode::parsetokens(), collectmode_common::resetbases(), collectmode_common::setscore(), and collectmode_common::totalscore().
const int collectmode_common::STEALTOKENTIME = 5000 static inherited
Referenced by deposittokens(), and game::collectclientmode::rendergame().
const int collectmode_common::TOKENDIST = 16 static inherited
Referenced by game::collectclientmode::movetoken().
const int collectmode_common::TOKENLIMIT = 5 static inherited
Referenced by game::collectclientmode::aifind(), game::collectclientmode::checkitems(), deposittokens(), droptokens(), and taketoken().
const int collectmode_common::TOKENRADIUS = 16 static inherited
Referenced by game::collectclientmode::checkitems().
vector<token> collectmode_common::tokens inherited
Referenced by game::collectclientmode::aicheck(), game::collectclientmode::aifind(), game::collectclientmode::checkitems(), deposittokens(), collectmode_common::droptoken(), droptokens(), collectmode_common::findtoken(), initclient(), leavegame(), game::collectclientmode::parsetokens(), collectmode_common::removetoken(), game::collectclientmode::rendergame(), collectmode_common::resetbases(), and update().
const int collectmode_common::UNOWNEDTOKENLIMIT = 15 static inherited
Referenced by leavegame().
The documentation for this struct was generated from the following files:
inexor/server/gamemode/collect_server.hpp
inexor/server/gamemode/collect_server.cpp