Inexor: ipmask Struct Reference
ipmask Struct Reference
structure to describe IPs
#include <cube_network.hpp>
Public Member Functions
void parse (const char *name)
int print (char *buf) const
bool check (enet_uint32 host) const
Public Attributes
enet_uint32 ip
enet_uint32 mask
Detailed Description
structure to describe IPs
Member Function Documentation
bool ipmask::check (enet_uint32 host) const inline
References ip.
void ipmask::parse (const char * name)
References gle::end(), ip, loopi(), and mask.
Referenced by server::addgban().
int ipmask::print (char * buf) const
References ip, loopi(), loopj, mask, and recorder::start().
Member Data Documentation
enet_uint32 ipmask::ip
Referenced by check(), parse(), and print().
enet_uint32 ipmask::mask
Referenced by parse(), and print().
The documentation for this struct was generated from the following files:
inexor/network/legacy/cube_network.hpp
inexor/network/legacy/cube_network.cpp