Inexor: delayedupdate Struct Reference
delayedupdate Struct Reference
Public Types
enum { INT, FLOAT, STRING, ACTION }
Public Member Functions
delayedupdate ()
~delayedupdate ()
void schedule (const char *s)
void schedule (ident *var, int i)
void schedule (ident *var, float f)
void schedule (ident *var, char *s)
int getint () const
float getfloat () const
const char * getstring () const
void run ()
Public Attributes
enum delayedupdate:: { ... } type
ident * id
union {
int i
float f
char * s
} val
Member Enumeration Documentation
anonymous enum
Enumerator
INT
FLOAT
STRING
ACTION
Constructor & Destructor Documentation
delayedupdate::delayedupdate () inline
References val.
delayedupdate::~delayedupdate () inline
References ACTION, DELETEA, STRING, type, and val.
Member Function Documentation
float delayedupdate::getfloat () const inline
References FLOAT, INT, parsefloat(), STRING, type, and val.
Referenced by run().
int delayedupdate::getint () const inline
References FLOAT, INT, STRING, type, and val.
Referenced by run().
const char* delayedupdate::getstring () const inline
References FLOAT, INT, intstr(), STRING, type, and val.
Referenced by run().
void delayedupdate::run () inline
References ACTION, alias(), execute(), getfloat(), getint(), getstring(), id, ID_ALIAS, ID_FVAR, ID_SVAR, ID_VAR, ident::name, setfvarchecked(), setsvarchecked(), setvarchecked(), type, ident::type, and val.
void delayedupdate::schedule (const char * s) inline
References ACTION, newstring(), type, and val.
Referenced by applymenu::gui(), guibutton(), guiimage(), guimodelpreview(), guiplayerpreview(), guiprefabpreview(), and updateval().
void delayedupdate::schedule (ident * var, int i) inline
References INT, type, and val.
void delayedupdate::schedule (ident * var, float f) inline
References f(), FLOAT, type, and val.
void delayedupdate::schedule (ident * var, char * s) inline
References newstring(), STRING, type, and val.
Member Data Documentation
ident* delayedupdate::id
Referenced by run().
enum { ... } delayedupdate::type
Referenced by getfloat(), getint(), getstring(), run(), schedule(), and ~delayedupdate().
union { ... } delayedupdate::val
Referenced by delayedupdate(), getfloat(), getint(), getstring(), run(), schedule(), and ~delayedupdate().
The documentation for this struct was generated from the following file:
inexor/ui/legacy/menus.cpp