Inexor: SharedList< T > Struct Template Reference
SharedList< T > Struct Template Reference
#include <SharedList.hpp>
Public Member Functions
SharedList ()
void push_back (T &&s)
void push_back (const T &s)
void erase (int i)
T & operator[] (size_t n)
size_t size ()
Public Attributes
int len = 0
std::function< void(int, T &)> element_pushed_back_func
std::function< void(int)> element_removed_func
std::vector< T > container
Constructor & Destructor Documentation
template<typename T > SharedList< T >::SharedList () inline
Member Function Documentation
template<typename T > void SharedList< T >::erase (int i) inline
References SharedList< T >::container, and SharedList< T >::element_removed_func.
template<typename T > T& SharedList< T >::operator[] (size_t n) inline
References SharedList< T >::container.
template<typename T > void SharedList< T >::push_back (T && s) inline
References SharedList< T >::container, SharedList< T >::element_pushed_back_func, SharedList< T >::len, and move().
template<typename T > void SharedList< T >::push_back (const T & s) inline
References SharedList< T >::container, SharedList< T >::element_pushed_back_func, and SharedList< T >::len.
template<typename T > size_t SharedList< T >::size () inline
References SharedList< T >::container.
Member Data Documentation
template<typename T > std::vector<T> SharedList< T >::container
Referenced by SharedList< T >::erase(), SharedList< T >::operator[](), SharedList< T >::push_back(), and SharedList< T >::size().
template<typename T > std::function<void(int, T &)> SharedList< T >::element_pushed_back_func
Referenced by SharedList< T >::push_back().
template<typename T > std::function<void(int)> SharedList< T >::element_removed_func
Referenced by SharedList< T >::erase().
template<typename T > int SharedList< T >::len = 0
Referenced by SharedList< T >::push_back().
The documentation for this struct was generated from the following file:
inexor/network/SharedList.hpp