Inexor: BlendMapRoot Struct Reference
BlendMapRoot Struct Reference
Public Member Functions
BlendMapRoot ()
BlendMapRoot (uchar type, const BlendMapNode &node)
void cleanup ()
void shrink (int quadrant)
void cleanup (int type)
void splitsolid (uchar &type, uchar val)
Public Attributes
uchar type
union {
BlendMapBranch * branch
BlendMapSolid * solid
BlendMapImage * image
};
Constructor & Destructor Documentation
BlendMapRoot::BlendMapRoot () inline
BlendMapRoot::BlendMapRoot (uchar type, const BlendMapNode & node) inline
Member Function Documentation
void BlendMapNode::cleanup (int type) inherited
References BM_BRANCH, and BM_IMAGE.
Referenced by cleanup(), fillblendmap(), optimizeblendmap(), BlendMapNode::splitsolid(), and BlendMapBranch::~BlendMapBranch().
void BlendMapRoot::cleanup () inline
References BlendMapNode::cleanup(), and type.
Referenced by moveblendmap(), resetblendmap(), and shrink().
void BlendMapRoot::shrink (int quadrant) inline
References BM_BRANCH, cleanup(), and type.
Referenced by shrinkblendmap().
void BlendMapNode::splitsolid (uchar & type, uchar val) inherited
References BM_BRANCH, BM_SOLID, BlendMapNode::cleanup(), and loopi().
Referenced by blitblendmap(), and fillblendmap().
Member Data Documentation
union { ... }
uchar BlendMapRoot::type
Referenced by blitblendmap(), cleanup(), enlargeblendmap(), fillblendmap(), invertblendmap(), loadblendmap(), lookupblendmap(), moveblendmap(), optimizeblendmap(), resetblendmap(), saveblendmap(), setblendmaporigin(), and shrink().
The documentation for this struct was generated from the following file:
inexor/engine/blend.cpp