Inexor: vertcommands< MDL > Struct Template Reference
vertcommands< MDL > Struct Template Reference
#include <vertmodel.hpp>
Public Types
typedef struct MDL::part part
typedef struct MDL::skin skin
Public Member Functions
vertcommands ()
void modelcommand (F *fun, const char *suffix, const char *args)
Static Public Member Functions
static void loadpart (char *model, float *smooth)
static void setpitch (float *pitchscale, float *pitchoffset, float *pitchmin, float *pitchmax)
static void setanim (char *anim, int *frame, int *range, float *speed, int *priority)
static void setdir (char *name)
static void setskin (char *meshname, char *tex, char *masks, float *envmapmax, float *envmapmin)
static void setspec (char *meshname, int *percent)
static void setambient (char *meshname, int *percent)
static void setglow (char *meshname, int *percent, int *delta, float *pulse)
static void setglare (char *meshname, float *specglare, float *glowglare)
static void setalphatest (char *meshname, float *cutoff)
static void setalphablend (char *meshname, int *blend)
static void setcullface (char *meshname, int *cullface)
static void setenvmap (char *meshname, char *envmap)
static void setbumpmap (char *meshname, char *normalmapfile)
static void setfullbright (char *meshname, float *fullbright)
static void setshader (char *meshname, char *shader)
static void setscroll (char *meshname, float *scrollu, float *scrollv)
static void setnoclip (char *meshname, int *noclip)
static void setlink (int *parent, int *child, char *tagname, float *x, float *y, float *z)
Member Typedef Documentation
template<class MDL> typedef struct MDL::part vertcommands< MDL >::part
template<class MDL> typedef struct MDL::skin vertcommands< MDL >::skin
Constructor & Destructor Documentation
template<class MDL> vertcommands< MDL >::vertcommands () inline
Member Function Documentation
template<class MDL> static void vertcommands< MDL >::loadpart (char * model, float * smooth) inline static
References defformatstring, dir, f(), Log, path(), RAD, and inexor::util::log_manager::std.
void modelcommands< MDL, struct MDL::vertmesh >::modelcommand (F * fun, const char * suffix, const char * args) inline inherited
References addcommand(), defformatstring, and newstring().
static void modelcommands< MDL, struct MDL::vertmesh >::setalphablend (char * meshname, int * blend) inline static inherited
References loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setalphatest (char * meshname, float * cutoff) inline static inherited
References f(), loopskins, inexor::rpc::max(), and inexor::rpc::min().
static void modelcommands< MDL, struct MDL::vertmesh >::setambient (char * meshname, int * percent) inline static inherited
References loopskins.
template<class MDL> static void vertcommands< MDL >::setanim (char * anim, int * frame, int * range, float * speed, int * priority) inline static
References vector< T, MINSIZE >::empty(), findanims(), Log, loopv, animmodel::parts, and inexor::util::log_manager::std.
static void modelcommands< MDL, struct MDL::vertmesh >::setbumpmap (char * meshname, char * normalmapfile) inline static inherited
References dir, loopskins, makerelpath(), and textureload().
static void modelcommands< MDL, struct MDL::vertmesh >::setcullface (char * meshname, int * cullface) inline static inherited
References loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setdir (char * name) inline static inherited
References dir, formatstring(), Log, modeldir, and inexor::util::log_manager::std.
static void modelcommands< MDL, struct MDL::vertmesh >::setenvmap (char * meshname, char * envmap) inline static inherited
References cubemapload(), and loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setfullbright (char * meshname, float * fullbright) inline static inherited
References loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setglare (char * meshname, float * specglare, float * glowglare) inline static inherited
References loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setglow (char * meshname, int * percent, int * delta, float * pulse) inline static inherited
References loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setlink (int * parent, int * child, char * tagname, float * x, float * y, float * z) inline static inherited
References Log, parts, and inexor::util::log_manager::std.
static void modelcommands< MDL, struct MDL::vertmesh >::setnoclip (char * meshname, int * noclip) inline static inherited
References loopmeshes.
template<class MDL> static void vertcommands< MDL >::setpitch (float * pitchscale, float * pitchoffset, float * pitchmin, float * pitchmax) inline static
References Log, animmodel::parts, and inexor::util::log_manager::std.
static void modelcommands< MDL, struct MDL::vertmesh >::setscroll (char * meshname, float * scrollu, float * scrollv) inline static inherited
References loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setshader (char * meshname, char * shader) inline static inherited
References lookupshaderbyname(), and loopskins.
static void modelcommands< MDL, struct MDL::vertmesh >::setskin (char * meshname, char * tex, char * masks, float * envmapmax, float * envmapmin) inline static inherited
References dir, loopskins, makerelpath(), and textureload().
static void modelcommands< MDL, struct MDL::vertmesh >::setspec (char * meshname, int * percent) inline static inherited
References loopskins.
The documentation for this struct was generated from the following file:
inexor/model/vertmodel.hpp