Inexor: ecjacobian Struct Reference
ecjacobian Struct Reference
Public Member Functions
ecjacobian ()
ecjacobian (const gfield &x, const gfield &y)
ecjacobian (const gfield &x, const gfield &y, const gfield &z)
void mul2 ()
void add (const ecjacobian &q)
template<int Q_DIGITS>
void mul (const ecjacobian &p, const bigint< Q_DIGITS > &q)
template<int Q_DIGITS>
void mul (const bigint< Q_DIGITS > &q)
void normalize ()
bool calcy (bool ybit)
void parse (const char *s)
Public Attributes
gfield x
gfield y
gfield z
Static Public Attributes
static const gfield B
static const ecjacobian base
static const ecjacobian origin
Constructor & Destructor Documentation
ecjacobian::ecjacobian () inline
ecjacobian::ecjacobian (const gfield & x, const gfield & y) inline
ecjacobian::ecjacobian (const gfield & x, const gfield & y, const gfield & z) inline
Member Function Documentation
void ecjacobian::add (const ecjacobian & q) inline
References gfield::add(), hmap::d, f(), bigint< BI_DIGITS >::isone(), bigint< BI_DIGITS >::iszero(), gfield::mul(), mul(), mul2(), origin, gfield::square(), gfield::sub(), x, y, and z.
Referenced by calcy(), and mul().
bool ecjacobian::calcy (bool ybit) inline
References gfield::add(), add(), B, bigint< BI_DIGITS >::hasbit(), gfield::mul(), gfield::neg(), gfield::sqrt(), gfield::square(), gfield::sub(), x, y, and bigint< BI_DIGITS >::zero().
Referenced by parse().
template<int Q_DIGITS> void ecjacobian::mul (const ecjacobian & p, const bigint< Q_DIGITS > & q) inline
References add(), bigint< BI_DIGITS >::hasbit(), loopirev, mul2(), bigint< BI_DIGITS >::numbits(), and origin.
Referenced by add().
template<int Q_DIGITS> void ecjacobian::mul (const bigint< Q_DIGITS > & q) inline
References mul().
Referenced by mul().
void ecjacobian::mul2 () inline
References gfield::add(), hmap::d, bigint< BI_DIGITS >::iszero(), gfield::mul(), gfield::mul2(), origin, gfield::square(), gfield::sub(), x, y, and z.
Referenced by add(), and mul().
void ecjacobian::normalize () inline
References gfield::invert(), bigint< BI_DIGITS >::isone(), bigint< BI_DIGITS >::iszero(), gfield::mul(), gfield::square(), x, y, and z.
void ecjacobian::parse (const char * s) inline
References calcy(), bigint< BI_DIGITS >::parse(), x, and z.
Member Data Documentation
const gfield ecjacobian::B static
Referenced by calcy().
const ecjacobian ecjacobian::base static
const ecjacobian ecjacobian::origin static
Referenced by add(), mul(), and mul2().
gfield ecjacobian::x
Referenced by add(), calcy(), mul2(), normalize(), and parse().
gfield ecjacobian::y
Referenced by add(), calcy(), mul2(), and normalize().
gfield ecjacobian::z
Referenced by add(), mul2(), normalize(), and parse().
The documentation for this struct was generated from the following file:
inexor/network/legacy/crypto.cpp