Inexor: varenderer< T > Struct Template Reference
varenderer< T > Struct Template Reference
Public Member Functions
varenderer (const char *texname, int type, int collide=0)
void cleanup () override
void init (int n) override
void reset () override
void resettracked (physent *owner) override
int count () override
bool haswork () override
particle * addpart (const vec &o, const vec &d, int fade, int color, float size, int gravity) override
void seedemitter (particleemitter &pe, const vec &o, const vec &d, int fade, float size, int gravity) override
void genverts (particle *p, partvert *vs, bool regen)
void genverts ()
void update () override
void render () override
virtual int adddepthfx (vec &bbmin, vec &bbmax)
void calc (particle *p, int &blend, int &ts, vec &o, vec &d, bool step=true)
const char * debuginfo ()
Public Attributes
partvert * verts
particle * parts
int maxparts
int numparts
int lastupdate
int rndmask
GLuint vbo
Texture * tex
const char * texname
int texclamp
uint type
int collide
string info
Constructor & Destructor Documentation
template<int T> varenderer< T >::varenderer (const char * texname, int type, int collide = 0) inline
References PT_HFLIP, PT_RND4, PT_ROT, and PT_VFLIP.
Member Function Documentation
virtual int partrenderer::adddepthfx (vec & bbmin, vec & bbmax) inline virtual inherited
Referenced by finddepthfxranges().
template<int T> particle* varenderer< T >::addpart (const vec & o, const vec & d, int fade, int color, float size, int gravity) inline override virtual
Implements partrenderer.
References particle::color, particle::d, hmap::d, emitoffset, particle::fade, particle::flags, particle::gravity, lastmillis, particle::millis, particle::o, parts, rnd(), and particle::size.
void partrenderer::calc (particle * p, int & blend, int & ts, vec & o, vec & d, bool step = true) inherited
References vec::add(), adddecal(), mpr::collide(), COLLIDEERROR, COLLIDERADIUS, particle::color, particle::d, f(), particle::fade, particle::flags, particle::gravity, lastmillis, inexor::rpc::max(), particle::millis, vec::normalize(), particle::o, game::particletrack(), PT_RND4, PT_TRACK, RAY_CLIPMAT, rayfloor(), particle::size, vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
template<int T> void varenderer< T >::cleanup () inline override virtual
Reimplemented from partrenderer.
References glDeleteBuffers_, and gle::vbo.
template<int T> int varenderer< T >::count () inline override virtual
Implements partrenderer.
const char * partrenderer::debuginfo () inherited
References mpr::collide(), concatstring(), concformatstring(), formatstring(), partnames, PT_FLIP, PT_GLARE, PT_LERP, PT_MOD, PT_RND4, and PT_SOFT.
Referenced by renderparticles().
template<int T> void varenderer< T >::genverts (particle * p, partvert * vs, bool regen) inline
References particle::color, partvert::color, hmap::d, f(), particle::fade, particle::flags, particle::gravity, loopi(), PT_ICON, PT_MOD, PT_RND4, PT_ROT, SETCOLOR, SETMODCOLOR, SETTEXCOORDS, and particle::size.
template<int T> void varenderer< T >::genverts () inline
References particle::fade, particle::flags, loopi(), parts, and sphere::verts.
template<int T> bool varenderer< T >::haswork () inline override virtual
Implements partrenderer.
template<int T> void varenderer< T >::init (int n) inline override virtual
Reimplemented from partrenderer.
References DELETEA, parts, and sphere::verts.
template<int T> void varenderer< T >::render () inline override virtual
Implements partrenderer.
References gle::bindvbo(), gle::clearvbo(), partvert::color, gle::disablequads(), gle::drawquads(), gle::enablequads(), partvert::pos, partvert::tc, textureload(), and gle::vbo.
template<int T> void varenderer< T >::reset () inline override virtual
Implements partrenderer.
template<int T> void varenderer< T >::resettracked (physent * owner) inline override virtual
Reimplemented from partrenderer.
References particle::fade, loopi(), parts, and PT_TRACK.
template<int T> void varenderer< T >::seedemitter (particleemitter & pe, const vec & o, const vec & d, int fade, float size, int gravity) inline override virtual
Reimplemented from partrenderer.
References vec::add(), hmap::d, gle::end(), particleemitter::extendbb(), f(), inexor::rpc::max(), particleemitter::maxfade, SQRT2, and anonymous_namespace{utilTest.cpp}::t().
template<int T> void varenderer< T >::update () inline override virtual
Reimplemented from partrenderer.
References gle::bindvbo(), gle::clearvbo(), glBufferData_, glBufferSubData_, glGenBuffers_, lastmillis, gle::vbo, and sphere::verts.
Member Data Documentation
int partrenderer::collide inherited
Referenced by fireballrenderer::finddepthfxranges(), regularshape(), and splash().
string partrenderer::info inherited
template<int T> int varenderer< T >::lastupdate
template<int T> int varenderer< T >::maxparts
template<int T> int varenderer< T >::numparts
template<int T> particle* varenderer< T >::parts
template<int T> int varenderer< T >::rndmask
Texture* partrenderer::tex inherited
Referenced by flarerenderer::render(), and lightningrenderer::renderpart().
int partrenderer::texclamp inherited
const char* partrenderer::texname inherited
Referenced by flarerenderer::render().
uint partrenderer::type inherited
Referenced by fireballrenderer::finddepthfxranges(), finddepthfxranges(), regularshape(), lightningrenderer::renderpart(), and renderparticles().
template<int T> GLuint varenderer< T >::vbo
template<int T> partvert* varenderer< T >::verts
The documentation for this struct was generated from the following file:
inexor/engine/renderparticles.cpp