Inexor: QuadNode Struct Reference
QuadNode Struct Reference
Public Member Functions
QuadNode (int x, int y, int size)
void clear ()
~QuadNode ()
void insert (int mx, int my, int msize)
void genmatsurf (ushort mat, uchar orient, uchar visible, int x, int y, int z, int size, materialsurface *&matbuf)
void genmatsurfs (ushort mat, uchar orient, uchar flags, int z, materialsurface *&matbuf)
Public Attributes
int x
int y
int size
uint filled
QuadNode * child [4]
Constructor & Destructor Documentation
QuadNode::QuadNode (int x, int y, int size) inline
References child, and loopi().
Referenced by insert().
QuadNode::~QuadNode () inline
References clear().
Member Function Documentation
void QuadNode::clear () inline
References child, DELETEP, and loopi().
Referenced by ~QuadNode().
void QuadNode::genmatsurf (ushort mat, uchar orient, uchar visible, int x, int y, int z, int size, materialsurface *& matbuf) inline
References C, materialsurface::csize, dimension, materialsurface::material, materialsurface::o, materialsurface::orient, orient, R, materialsurface::rsize, size, materialsurface::visible, x, and y.
Referenced by genmatsurfs().
void QuadNode::genmatsurfs (ushort mat, uchar orient, uchar flags, int z, materialsurface *& matbuf) inline
References child, filled, genmatsurf(), genmatsurfs(), loopi(), x, and y.
Referenced by genmatsurfs(), and optimizematsurfs().
void QuadNode::insert (int mx, int my, int msize) inline
References child, DELETEP, filled, insert(), loopj, QuadNode(), x, and y.
Referenced by insert(), and optimizematsurfs().
Member Data Documentation
QuadNode* QuadNode::child[4]
Referenced by clear(), genmatsurfs(), insert(), and QuadNode().
uint QuadNode::filled
Referenced by genmatsurfs(), and insert().
int QuadNode::size
Referenced by genmatsurf().
int QuadNode::x
Referenced by genmatsurf(), genmatsurfs(), and insert().
int QuadNode::y
Referenced by genmatsurf(), genmatsurfs(), and insert().
The documentation for this struct was generated from the following file:
inexor/engine/material.cpp