Inexor: recorder::soundbuffer Struct Reference
recorder::soundbuffer Struct Reference
Public Member Functions
soundbuffer ()
~soundbuffer ()
void load (uchar *stream, uint len, uint fnum)
void cleanup ()
Public Attributes
uchar * sound
uint size
uint maxsize
uint frame
Constructor & Destructor Documentation
recorder::soundbuffer::soundbuffer () inline
recorder::soundbuffer::~soundbuffer () inline
References cleanup().
Member Function Documentation
void recorder::soundbuffer::cleanup () inline
References DELETEA, and inexor::sound::sound().
void recorder::soundbuffer::load (uchar * stream, uint len, uint fnum) inline
References DELETEA, and inexor::sound::sound().
Referenced by recorder::soundencoder().
Member Data Documentation
uint recorder::soundbuffer::frame
Referenced by recorder::videoencoder().
uint recorder::soundbuffer::maxsize
uint recorder::soundbuffer::size
Referenced by recorder::videoencoder().
uchar* recorder::soundbuffer::sound
Referenced by recorder::videoencoder().
The documentation for this struct was generated from the following file:
inexor/engine/movie.cpp