Inexor: server::projectilestate< N > Struct Template Reference
server::projectilestate< N > Struct Template Reference
#include <client_management.hpp>
Public Member Functions
projectilestate ()
void reset ()
void add (int val)
bool remove (int val)
Public Attributes
int projs [N]
int numprojs
Constructor & Destructor Documentation
template<int N> server::projectilestate< N >::projectilestate () inline
Member Function Documentation
template<int N> void server::projectilestate< N >::add (int val) inline
Referenced by server::shotevent::process().
template<int N> bool server::projectilestate< N >::remove (int val) inline
Referenced by server::explodeevent::process().
template<int N> void server::projectilestate< N >::reset () inline
Referenced by server::parsepacket(), server::gamestate::reassign(), and server::gamestate::reset().
Member Data Documentation
template<int N> int server::projectilestate< N >::numprojs
Referenced by server::projectilestate< 8 >::add(), server::projectilestate< 8 >::remove(), and server::projectilestate< 8 >::reset().
template<int N> int server::projectilestate< N >::projs[N]
Referenced by server::projectilestate< 8 >::add(), and server::projectilestate< 8 >::remove().
The documentation for this struct was generated from the following file:
inexor/server/client_management.hpp