Inexor: server::hideandseekservermode Struct Reference
server::hideandseekservermode Struct Reference
#include <hideandseek_server.hpp>
Classes
struct seekersinfo
Public Member Functions
void setup () override
void initplayers ()
void initplayer (clientinfo *ci)
void initclient (clientinfo *ci, packetbuf &p, bool connecting) override
void connected (clientinfo *ci) override
void leavegame (clientinfo *ci, bool disconnecting) override
void cleanup () override
bool checkfinished ()
void update () override
void intermission () override
void spawned (fpsent *d)
bool canspawn (clientinfo *ci, bool connecting) override
bool canhit (clientinfo *target, clientinfo *actor) override
void died (clientinfo *target, clientinfo *actor) override
bool canchangeteam (clientinfo *ci, const char *oldteam, const char *newteam) override
void setseeker (clientinfo *ci)
void sethider (clientinfo *ci)
vector< clientinfo * > getactiveplayers ()
int getremaininghiders ()
bool isfreezed (clientinfo *ci)
void setfreezedstate (clientinfo *ci, bool state)
int getnonfreezedseekers ()
void announceseekers (char *msg)
bool parse_network_message (int type, clientinfo *ci, clientinfo *cq, packetbuf &p) override
process gamemode specific network messages.
virtual void entergame (clientinfo *ci)
virtual void moved (clientinfo *ci, const vec &oldpos, bool oldclip, const vec &newpos, bool newclip)
virtual void spawned (clientinfo *ci)
virtual int fragvalue (clientinfo *victim, clientinfo *actor)
virtual void changeteam (clientinfo *ci, const char *oldteam, const char *newteam)
virtual void updatelimbo ()
virtual void newmap ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual bool extinfoteam (const char *team, ucharbuf &p)
Public Attributes
vector< seekersinfo * > seekersinfos
int lastupdatecheck
Member Function Documentation
void server::hideandseekservermode::announceseekers (char * msg)
References server::clients, E_STATIC_TOP, isseeker, loopv, N_HUDANNOUNCE, and sendf().
bool server::hideandseekservermode::canchangeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline override virtual
Reimplemented from server::servmode.
bool server::hideandseekservermode::canhit (clientinfo * target, clientinfo * actor) override virtual
Reimplemented from server::servmode.
References ishider, isteam, and server::clientinfo::team.
bool server::hideandseekservermode::canspawn (clientinfo * ci, bool connecting) inline override virtual
Reimplemented from server::servmode.
virtual void server::servmode::changeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline virtual inherited
Reimplemented in server::captureservermode, server::ctfservermode, and server::collectservermode.
Referenced by aiman::balanceteams().
bool server::hideandseekservermode::checkfinished ()
References server::clients, getactiveplayers(), getnonfreezedseekers(), server::interm, ishider, and loopv.
Referenced by update().
void server::hideandseekservermode::cleanup () inline override virtual
Reimplemented from server::servmode.
References seekersinfos.
void server::hideandseekservermode::connected (clientinfo * ci) inline override virtual
Reimplemented from server::servmode.
References setseeker().
void server::hideandseekservermode::died (clientinfo * target, clientinfo * actor) override virtual
Reimplemented from server::servmode.
References defformatstring, E_ZOOM_OUT, getremaininghiders(), ishider, N_HUDANNOUNCE, server::clientinfo::name, sendf(), and setseeker().
virtual void server::servmode::entergame (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::extinfoteam (const char * team, ucharbuf & p) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::extinfoteamscore().
virtual int server::servmode::fragvalue (clientinfo * victim, clientinfo * actor) inline virtual inherited
References isteam, and server::clientinfo::team.
Referenced by server::dodamage(), and server::suicide().
vector< clientinfo * > server::hideandseekservermode::getactiveplayers ()
References vector< T, MINSIZE >::add(), server::clients, CS_SPECTATOR, loopv, server::gamestate::state, and server::clientinfo::state.
Referenced by checkfinished(), and initplayers().
int server::hideandseekservermode::getnonfreezedseekers ()
References loopv, and seekersinfos.
Referenced by checkfinished().
int server::hideandseekservermode::getremaininghiders ()
References server::clients, ishider, and loopv.
Referenced by died().
virtual int server::servmode::getteamscore (const char * team) inline virtual inherited
virtual void server::servmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by server::extinfoteams().
virtual bool server::servmode::hidefrags () inline virtual inherited
Referenced by server::autoteam(), server::chooseworstteam(), and server::extinfoteams().
void server::hideandseekservermode::initclient (clientinfo * ci, packetbuf & p, bool connecting) inline override virtual
Reimplemented from server::servmode.
References setseeker().
void server::hideandseekservermode::initplayer (clientinfo * ci) inline
References sethider().
Referenced by initplayers().
void server::hideandseekservermode::initplayers ()
References server::clients, getactiveplayers(), initplayer(), vector< T, MINSIZE >::length(), loopv, rnd(), and setseeker().
Referenced by setup().
void server::hideandseekservermode::intermission () inline override virtual
Reimplemented from server::servmode.
bool server::hideandseekservermode::isfreezed (clientinfo * ci)
References server::clientinfo::clientnum, loopv, and seekersinfos.
void server::hideandseekservermode::leavegame (clientinfo * ci, bool disconnecting) override virtual
Reimplemented from server::servmode.
References server::clientinfo::clientnum, loopv, and seekersinfos.
virtual void server::servmode::moved (clientinfo * ci, const vec & oldpos, bool oldclip, const vec & newpos, bool newclip) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual void server::servmode::newmap () inline virtual inherited
Reimplemented in server::ctfservermode, server::collectservermode, and server::captureservermode.
Referenced by server::parsepacket().
bool server::hideandseekservermode::parse_network_message (int type, clientinfo * ci, clientinfo * cq, packetbuf & p) inline override virtual
process gamemode specific network messages.
Parameters
type the N_ network message type
ci the sender.
cq the currently focused player (sender or bot from senders pc)
p the network packet containing the data
Returns
whether this messages got processed.
Implements server::servmode.
void server::hideandseekservermode::setfreezedstate (clientinfo * ci, bool state)
References server::clientinfo::clientnum, loopv, seekersinfos, and recorder::state.
void server::hideandseekservermode::sethider (clientinfo * ci)
References server::clientinfo::clientnum, copystring(), MAXTEAMLEN, N_SETTEAM, sendf(), server::clientinfo::team, and TEAM_HIDE.
Referenced by initplayer().
void server::hideandseekservermode::setseeker (clientinfo * ci)
References server::clientinfo::clientnum, copystring(), MAXTEAMLEN, N_SETTEAM, seekersinfos, sendf(), server::clientinfo::team, and TEAM_SEEK.
Referenced by connected(), died(), initclient(), and initplayers().
void server::hideandseekservermode::setup () override virtual
Reimplemented from server::servmode.
References initplayers(), lastupdatecheck, seekersinfos, and totalmillis.
virtual void server::servmode::spawned (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
void server::hideandseekservermode::spawned (fpsent * d) inline
void server::hideandseekservermode::update () override virtual
Reimplemented from server::servmode.
References checkfinished(), lastupdatecheck, server::startintermission(), and totalmillis.
virtual void server::servmode::updatelimbo () inline virtual inherited
Reimplemented in server::bombservermode.
Referenced by server::serverupdate().
Member Data Documentation
int server::hideandseekservermode::lastupdatecheck
Referenced by setup(), and update().
vector<seekersinfo*> server::hideandseekservermode::seekersinfos
Referenced by cleanup(), getnonfreezedseekers(), isfreezed(), leavegame(), setfreezedstate(), setseeker(), and setup().
The documentation for this struct was generated from the following files:
inexor/server/gamemode/hideandseek_server.hpp
inexor/server/gamemode/hideandseek_server.cpp