Inexor: streambuf< T > Struct Template Reference
streambuf< T > Struct Template Reference
#include <stream.hpp>
Public Member Functions
streambuf (stream *s)
T get ()
size_t get (T *vals, size_t numvals)
void put (const T &val)
void put (const T *vals, size_t numvals)
size_t length ()
Public Attributes
stream * s
Constructor & Destructor Documentation
template<class T> streambuf< T >::streambuf (stream * s) inline
Member Function Documentation
template<class T> T streambuf< T >::get () inline
References stream::get(), and streambuf< T >::s.
template<class T> size_t streambuf< T >::get (T * vals, size_t numvals) inline
References stream::get(), and streambuf< T >::s.
template<class T> size_t streambuf< T >::length () inline
References streambuf< T >::s, and stream::size().
template<class T> void streambuf< T >::put (const T & val) inline
References stream::put(), and streambuf< T >::s.
template<class T> void streambuf< T >::put (const T * vals, size_t numvals) inline
References stream::put(), and streambuf< T >::s.
Member Data Documentation
template<class T> stream* streambuf< T >::s
Referenced by streambuf< T >::get(), streambuf< T >::length(), and streambuf< T >::put().
The documentation for this struct was generated from the following file:
inexor/io/legacy/stream.hpp