Inexor: matrix4x3 Struct Reference
matrix4x3 Struct Reference
#include <geom.hpp>
Public Member Functions
matrix4x3 ()
matrix4x3 (const vec &a, const vec &b, const vec &c, const vec &d)
matrix4x3 (const matrix3 &rot, const vec &trans)
matrix4x3 (const dualquat &dq)
matrix4x3 (const matrix4 &m)
void mul (float k)
void setscale (float x, float y, float z)
void setscale (const vec &v)
void setscale (float n)
void scale (float x, float y, float z)
void scale (const vec &v)
void scale (float n)
void settranslation (const vec &p)
void settranslation (float x, float y, float z)
void translate (const vec &p)
void translate (float x, float y, float z)
void translate (const vec &p, float scale)
void accumulate (const matrix4x3 &m, float k)
void normalize ()
void lerp (const matrix4x3 &to, float t)
void lerp (const matrix4x3 &from, const matrix4x3 &to, float t)
void identity ()
void mul (const matrix4x3 &m, const matrix4x3 &n)
void mul (const matrix4x3 &n)
void mul (const matrix3 &m, const matrix4x3 &n)
void mul (const matrix3 &rot, const vec &trans, const matrix4x3 &n)
void transpose ()
void transpose (const matrix4x3 &o)
void transposemul (const matrix4x3 &m, const matrix4x3 &n)
void multranspose (const matrix4x3 &m, const matrix4x3 &n)
void invert (const matrix4x3 &o)
void invert ()
void rotate (float angle, const vec &d)
void rotate (float ck, float sk, const vec &axis)
void rotate_around_x (float ck, float sk)
void rotate_around_x (float angle)
void rotate_around_x (const vec2 &sc)
void rotate_around_y (float ck, float sk)
void rotate_around_y (float angle)
void rotate_around_y (const vec2 &sc)
void rotate_around_z (float ck, float sk)
void rotate_around_z (float angle)
void rotate_around_z (const vec2 &sc)
vec transform (const vec &o) const
vec transposedtransform (const vec &o) const
vec transformnormal (const vec &o) const
vec transposedtransformnormal (const vec &o) const
vec transform (const vec2 &o) const
vec4 rowx () const
vec4 rowy () const
vec4 rowz () const
Public Attributes
vec a
vec b
vec c
vec d
Constructor & Destructor Documentation
matrix4x3::matrix4x3 () inline
Referenced by invert(), mul(), and rotate().
matrix4x3::matrix4x3 (const vec & a, const vec & b, const vec & c, const vec & d) inline
matrix4x3::matrix4x3 (const matrix3 & rot, const vec & trans) inline
matrix4x3::matrix4x3 (const dualquat & dq) inline
References a, b, c, d, dualquat::dual, vec4::mul(), dualquat::real, and vec4::squaredlen().
matrix4x3::matrix4x3 (const matrix4 & m) inline explicit
Member Function Documentation
void matrix4x3::accumulate (const matrix4x3 & m, float k) inline
References a, b, c, d, and vec::madd().
void matrix4x3::identity () inline
References a, b, c, and d.
Referenced by drawdamagecompass(), and animmodel::initmatrix().
void matrix4x3::invert (const matrix4x3 & o) inline
References a, b, c, d, vec::mul(), vec::squaredlen(), and transpose().
Referenced by BIH::BIH().
void matrix4x3::invert () inline
References invert(), and matrix4x3().
Referenced by invert().
void matrix4x3::lerp (const matrix4x3 & to, float t) inline
References a, b, c, d, and vec::lerp().
Referenced by vertmodel::vertmeshgroup::calctagmatrix().
void matrix4x3::lerp (const matrix4x3 & from, const matrix4x3 & to, float t) inline
References a, b, c, d, and vec::lerp().
void matrix4x3::mul (float k) inline
References a, b, c, d, and vec::mul().
Referenced by skelmodel::skeleton::calctags(), vertmodel::vertmeshgroup::concattagtransform(), skelmodel::skeleton::concattagtransform(), skelmodel::skeleton::genragdollbones(), mul(), and translate().
void matrix4x3::mul (const matrix4x3 & m, const matrix4x3 & n) inline
References a, b, c, d, vec::madd(), and vec::mul().
void matrix4x3::mul (const matrix4x3 & n) inline
References matrix4x3(), and mul().
Referenced by mul().
void matrix4x3::mul (const matrix3 & m, const matrix4x3 & n) inline
References matrix3::a, a, matrix3::b, b, matrix3::c, c, d, vec::madd(), and vec::mul().
void matrix4x3::mul (const matrix3 & rot, const vec & trans, const matrix4x3 & n) inline
References vec::add(), d, and mul().
void matrix4x3::multranspose (const matrix4x3 & m, const matrix4x3 & n) inline
References a, b, c, d, vec::dot(), vec::madd(), vec::msub(), vec::mul(), and anonymous_namespace{utilTest.cpp}::t().
void matrix4x3::normalize () inline
References a, b, c, and vec::normalize().
void matrix4x3::rotate (float angle, const vec & d) inline
void matrix4x3::rotate (float ck, float sk, const vec & axis) inline
References matrix4x3(), and matrix3::rotate().
void matrix4x3::rotate_around_x (float ck, float sk) inline
References b, c, vec::madd(), vec::msub(), and vec::mul().
void matrix4x3::rotate_around_x (float angle) inline
References rotate_around_x().
Referenced by rotate_around_x().
void matrix4x3::rotate_around_x (const vec2 & sc) inline
References rotate_around_x().
Referenced by rotate_around_x().
void matrix4x3::rotate_around_y (float ck, float sk) inline
References a, c, vec::madd(), vec::msub(), and vec::mul().
Referenced by animmodel::initmatrix().
void matrix4x3::rotate_around_y (float angle) inline
References rotate_around_y().
Referenced by rotate_around_y().
void matrix4x3::rotate_around_y (const vec2 & sc) inline
References rotate_around_y().
Referenced by rotate_around_y().
void matrix4x3::rotate_around_z (float ck, float sk) inline
References a, b, vec::madd(), vec::msub(), and vec::mul().
Referenced by drawdamagecompass(), and animmodel::initmatrix().
void matrix4x3::rotate_around_z (float angle) inline
References rotate_around_z().
Referenced by rotate_around_z().
void matrix4x3::rotate_around_z (const vec2 & sc) inline
References rotate_around_z().
Referenced by rotate_around_z().
vec4 matrix4x3::rowx () const inline
References a, b, c, and d.
vec4 matrix4x3::rowy () const inline
References a, b, c, and d.
vec4 matrix4x3::rowz () const inline
References a, b, c, and d.
void matrix4x3::scale (float x, float y, float z) inline
References a, b, c, and vec::mul().
Referenced by animmodel::part::calcbb(), drawdamagecompass(), animmodel::part::genBIH(), meterrenderer::renderpart(), and textrenderer::renderpart().
void matrix4x3::scale (const vec & v) inline
References scale().
Referenced by scale().
void matrix4x3::scale (float n) inline
References scale().
Referenced by scale().
void matrix4x3::setscale (float x, float y, float z) inline
References a, b, and c.
void matrix4x3::setscale (const vec & v) inline
References setscale().
Referenced by setscale().
void matrix4x3::setscale (float n) inline
References setscale().
Referenced by setscale().
void matrix4x3::settranslation (const vec & p) inline
References d.
Referenced by drawdamagecompass().
void matrix4x3::settranslation (float x, float y, float z) inline
References d.
vec matrix4x3::transform (const vec & o) const inline
References a, b, c, d, and vec::madd().
Referenced by BIH::BIH(), vertmodel::vertmesh::calcbb(), skelmodel::skelmesh::calcbb(), vertmodel::vertmeshgroup::calctagmatrix(), draw_char(), drawdamagecompass(), meterrenderer::renderpart(), and BIH::traverse().
vec matrix4x3::transform (const vec2 & o) const inline
References a, b, d, and vec::madd().
vec matrix4x3::transformnormal (const vec & o) const inline
References a, b, c, vec::madd(), and vec::mul().
Referenced by vertmodel::vertmeshgroup::concattagtransform().
void matrix4x3::translate (const vec & p) inline
References a, b, c, d, and vec::madd().
Referenced by animmodel::part::calcbb(), vertmodel::vertmeshgroup::concattagtransform(), skelmodel::skeleton::concattagtransform(), drawdamagecompass(), animmodel::part::genBIH(), meterrenderer::renderpart(), and textrenderer::renderpart().
void matrix4x3::translate (float x, float y, float z) inline
References translate().
Referenced by translate().
void matrix4x3::translate (const vec & p, float scale) inline
References mul(), and translate().
Referenced by translate().
void matrix4x3::transpose () inline
References a, b, c, d, and vec::dot().
Referenced by invert(), and ragdollskel::setupjoints().
void matrix4x3::transpose (const matrix4x3 & o) inline
References a, b, c, d, and vec::dot().
vec matrix4x3::transposedtransform (const vec & o) const inline
References a, b, c, d, vec::dot(), and vec::sub().
vec matrix4x3::transposedtransformnormal (const vec & o) const inline
References a, b, c, and vec::dot().
void matrix4x3::transposemul (const matrix4x3 & m, const matrix4x3 & n) inline
References a, b, c, d, vec::dot(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by ragdolldata::calcanimjoint().
Member Data Documentation
vec matrix4x3::a
Referenced by accumulate(), BIH::BIH(), ragdolldata::calcanimjoint(), identity(), invert(), lerp(), md3::md3meshgroup::load(), matrix4x3(), mul(), multranspose(), normalize(), rotate_around_y(), rotate_around_z(), rowx(), rowy(), rowz(), scale(), setscale(), ragdollskel::setupjoints(), transform(), transformnormal(), translate(), transpose(), transposedtransform(), transposedtransformnormal(), and transposemul().
vec matrix4x3::b
Referenced by accumulate(), ragdolldata::calcanimjoint(), identity(), invert(), lerp(), md3::md3meshgroup::load(), matrix4x3(), mul(), multranspose(), normalize(), rotate_around_x(), rotate_around_z(), rowx(), rowy(), rowz(), scale(), setscale(), ragdollskel::setupjoints(), transform(), transformnormal(), translate(), transpose(), transposedtransform(), transposedtransformnormal(), and transposemul().
vec matrix4x3::c
Referenced by accumulate(), ragdolldata::calcanimjoint(), identity(), invert(), lerp(), md3::md3meshgroup::load(), matrix4x3(), mul(), multranspose(), normalize(), rotate_around_x(), rotate_around_y(), rowx(), rowy(), rowz(), scale(), setscale(), ragdollskel::setupjoints(), transform(), transformnormal(), translate(), transpose(), transposedtransform(), transposedtransformnormal(), and transposemul().
vec matrix4x3::d
Referenced by accumulate(), ragdolldata::calcanimjoint(), vertmodel::vertmeshgroup::calctagmatrix(), skelmodel::skeleton::calctags(), dualquat::dualquat(), identity(), invert(), lerp(), md3::md3meshgroup::load(), matrix4x3(), mul(), multranspose(), rowx(), rowy(), rowz(), settranslation(), ragdollskel::setupjoints(), transform(), translate(), transpose(), transposedtransform(), and transposemul().
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp