Inexor: quat Struct Reference
quat Struct Reference
quaternions are number systems that extend complex numbers complex numbers extend the number system of real numbers in a way so x²=-1 can be solved in this example x = i (imaginary).
#include <geom.hpp>
Public Member Functions
quat ()
quat (float x, float y, float z, float w)
quat (const vec &axis, float angle)
quat (const vec &v)
quat (const matrix3 &m)
quat (const matrix4x3 &m)
quat (const matrix4 &m)
void restorew ()
quat & add (const vec4 &o)
quat & sub (const vec4 &o)
quat & mul (float k)
quat & mul (const quat &p, const quat &o)
quat & mul (const quat &o)
quat & invert ()
void calcangleaxis (float &angle, vec &axis)
vec rotate (const vec &v) const
vec invertedrotate (const vec &v) const
template<class M >
void convertmatrix (const M &m)
float & operator[] (int i)
operators for XYZ coordinate access
float operator[] (int i) const
template<class T >
float dot3 (const T &o) const
dot products
float dot (const vec4 &o) const
float dot (const vec &o) const
float squaredlen () const
float magnitude () const
float magnitude3 () const
vec4 & normalize ()
vec4 & lerp (const vec4 &b, float t)
vec4 & lerp (const vec4 &a, const vec4 &b, float t)
vec4 & mul3 (float f)
basic algebraic methods
vec4 & mul (const vec4 &o)
vec4 & div3 (float f)
vec4 & div (float f)
vec4 & div (const vec4 &o)
vec4 & addw (float f)
vec4 & subw (float f)
vec4 & neg3 ()
vec4 & neg ()
template<class B >
vec4 & madd (const vec4 &a, const B &b)
template<class B >
vec4 & msub (const vec4 &a, const B &b)
void setxyz (const vec &v)
vec4 & rotate_around_z (float c, float s)
rotation members
vec4 & rotate_around_z (float angle)
vec4 & rotate_around_x (float c, float s)
vec4 & rotate_around_x (float angle)
vec4 & rotate_around_y (float c, float s)
vec4 & rotate_around_y (float angle)
Public Attributes
union {
struct {
float x
float y
float z
float w
}
struct {
float r
float g
float b
float a
}
float v [4]
};
Detailed Description
quaternions are number systems that extend complex numbers complex numbers extend the number system of real numbers in a way so x²=-1 can be solved in this example x = i (imaginary).
As you shoud know complex numbers have a real and an imaginary part. in quarterions, xy is NOT yx: xy != yx; but i² = k² = j² = ijk = -1 some calculations can be done much easier if you consider this extra condition/dimension
Constructor & Destructor Documentation
quat::quat () inline
Referenced by mul().
quat::quat (float x, float y, float z, float w) inline
quat::quat (const vec & axis, float angle) inline
quat::quat (const vec & v) inline explicit
References restorew().
quat::quat (const matrix3 & m) inline explicit
References convertmatrix().
quat::quat (const matrix4x3 & m) inline explicit
References convertmatrix().
quat::quat (const matrix4 & m) inline explicit
References convertmatrix().
Member Function Documentation
quat& quat::add (const vec4 & o) inline
References vec4::add().
Referenced by dualquat::accumulate(), dualquat::add(), dualquat::lerp(), dualquat::mul(), dualquat::mulorient(), and rotate().
vec4& vec4::addw (float f) inline inherited
References f().
void quat::calcangleaxis (float & angle, vec & axis) inline
References vec4::dot3(), and vec::mul().
template<class M > void quat::convertmatrix (const M & m) inline
Referenced by quat().
vec4& vec4::div (float f) inline inherited
References vec4::div3(), and f().
vec4& vec4::div (const vec4 & o) inline inherited
vec4& vec4::div3 (float f) inline inherited
References f().
Referenced by vec4::div().
float vec4::dot (const vec4 & o) const inline inherited
References vec4::dot3().
Referenced by dualquat::accumulate(), addcubeverts(), dualquat::fixantipodal(), gengrassquads(), dualquat::invert(), dualquat::lerp(), dualquat::mulorient(), and vec4::squaredlen().
float vec4::dot (const vec & o) const inline inherited
template<class T > float vec4::dot3 (const T & o) const inline inherited
dot products
Referenced by calcangleaxis(), plane::dist(), vec4::dot(), vec4::magnitude3(), matrix4::transposedtransform(), and matrix4::transposedtransformnormal().
quat& quat::invert () inline
References vec4::neg3().
Referenced by dualquat::invert(), and dualquat::mulorient().
vec quat::invertedrotate (const vec & v) const inline
References vec::add(), vec::cross(), vec::mul(), mul(), and sub().
Referenced by dualquat::transposedtransformnormal().
vec4& vec4::lerp (const vec4 & b, float t) inline inherited
Referenced by squat::lerp().
vec4& vec4::lerp (const vec4 & a, const vec4 & b, float t) inline inherited
template<class B > vec4& vec4::madd (const vec4 & a, const B & b) inline inherited
References vec4::add(), vec4::mul(), and vec4::vec4().
Referenced by matrix4::mul(), matrix4::mult(), matrix4::rotate_around_x(), matrix4::rotate_around_y(), matrix4::rotate_around_z(), matrix4::transform(), matrix4::transformnormal(), and matrix4::translate().
float vec4::magnitude () const inline inherited
References vec4::squaredlen().
Referenced by vec4::normalize(), and dualquat::normalize().
float vec4::magnitude3 () const inline inherited
References vec4::dot3().
template<class B > vec4& vec4::msub (const vec4 & a, const B & b) inline inherited
References vec4::mul(), vec4::sub(), and vec4::vec4().
Referenced by matrix4::rotate_around_x(), matrix4::rotate_around_y(), and matrix4::rotate_around_z().
vec4& vec4::mul (const vec4 & o) inline inherited
quat& quat::mul (float k) inline
References vec4::mul().
Referenced by invertedrotate(), dualquat::lerp(), dualquat::mul(), dualquat::mulorient(), dualquat::normalize(), rotate(), dualquat::scale(), and dualquat::transform().
quat& quat::mul (const quat & p, const quat & o) inline
quat& quat::mul (const quat & o) inline
References mul(), and quat().
Referenced by mul().
vec4& vec4::mul3 (float f) inline inherited
basic algebraic methods
References f().
Referenced by animmodel::mesh::fixqtangent(), and vec4::mul().
vec4& vec4::neg () inline inherited
References vec4::neg3().
Referenced by dualquat::fixantipodal(), animmodel::mesh::fixqtangent(), and matrix4::reflectz().
vec4& vec4::neg3 () inline inherited
Referenced by invert(), and vec4::neg().
vec4& vec4::normalize () inline inherited
References vec4::magnitude(), and vec4::mul().
Referenced by iqm::iqmmeshgroup::loadiqmanims(), and iqm::iqmmeshgroup::loadiqmmeshes().
float& vec4::operator[] (int i) inline inherited
operators for XYZ coordinate access
float vec4::operator[] (int i) const inline inherited
void quat::restorew () inline
Referenced by md5::md5meshgroup::loadanim(), md5::md5meshgroup::loadmesh(), and quat().
vec quat::rotate (const vec & v) const inline
References vec::add(), add(), vec::cross(), vec::mul(), and mul().
Referenced by md5::md5mesh::buildverts(), and dualquat::transformnormal().
vec4& vec4::rotate_around_x (float c, float s) inline inherited
vec4& vec4::rotate_around_x (float angle) inline inherited
References vec4::rotate_around_x().
Referenced by vec4::rotate_around_x().
vec4& vec4::rotate_around_y (float c, float s) inline inherited
vec4& vec4::rotate_around_y (float angle) inline inherited
References vec4::rotate_around_y().
Referenced by vec4::rotate_around_y().
vec4& vec4::rotate_around_z (float c, float s) inline inherited
rotation members
vec4& vec4::rotate_around_z (float angle) inline inherited
References vec4::rotate_around_z().
Referenced by vec4::rotate_around_z().
void vec4::setxyz (const vec & v) inline inherited
Referenced by matrix4::settranslation().
float vec4::squaredlen () const inline inherited
References vec4::dot().
Referenced by vec4::magnitude(), and matrix4x3::matrix4x3().
quat& quat::sub (const vec4 & o) inline
References vec4::sub().
Referenced by dualquat::invert(), invertedrotate(), and dualquat::mulorient().
vec4& vec4::subw (float f) inline inherited
References f().
Member Data Documentation
union { ... }
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp