Inexor: dualquat Struct Reference
dualquat Struct Reference
#include <geom.hpp>
Public Member Functions
dualquat ()
dualquat (const quat &q, const vec &p)
dualquat (const quat &q)
dualquat (const matrix4x3 &m)
dualquat & mul (float k)
dualquat & add (const dualquat &d)
dualquat & lerp (const dualquat &to, float t)
dualquat & lerp (const dualquat &from, const dualquat &to, float t)
dualquat & invert ()
void mul (const dualquat &p, const dualquat &o)
void mul (const dualquat &o)
void mulorient (const quat &q)
void mulorient (const quat &q, const dualquat &base)
void normalize ()
void translate (const vec &p)
void scale (float k)
void fixantipodal (const dualquat &d)
void accumulate (const dualquat &d, float k)
vec transform (const vec &v) const
quat transform (const quat &q) const
vec transposedtransform (const vec &v) const
vec transformnormal (const vec &v) const
vec transposedtransformnormal (const vec &v) const
vec gettranslation () const
Public Attributes
quat real
quat dual
Constructor & Destructor Documentation
dualquat::dualquat () inline
Referenced by mul(), and transposedtransform().
dualquat::dualquat (const quat & q, const vec & p) inline
dualquat::dualquat (const quat & q) inline explicit
dualquat::dualquat (const matrix4x3 & m) inline explicit
References matrix4x3::d, dual, and real.
Member Function Documentation
void dualquat::accumulate (const dualquat & d, float k) inline
References quat::add(), vec4::dot(), dual, vec4::mul(), and real.
Referenced by skelmodel::skelmeshgroup::blendbones().
dualquat& dualquat::add (const dualquat & d) inline
References quat::add(), dual, and real.
Referenced by lerp(), mulorient(), and transform().
void dualquat::fixantipodal (const dualquat & d) inline
References vec4::dot(), dual, vec4::neg(), and real.
Referenced by skelmodel::skeleton::genragdollbones(), skelmodel::skeleton::interpbones(), md5::md5meshgroup::loadanim(), iqm::iqmmeshgroup::loadiqmanims(), and smd::smdmeshgroup::readframes().
vec dualquat::gettranslation () const inline
References vec::add(), vec::cross(), dual, vec::mul(), mul(), real, and vec::sub().
dualquat& dualquat::invert () inline
References vec4::dot(), dual, quat::invert(), mul(), real, and quat::sub().
Referenced by skelmodel::skeleton::initragdoll(), and mulorient().
dualquat& dualquat::lerp (const dualquat & to, float t) inline
References quat::add(), vec4::dot(), dual, vec4::mul(), quat::mul(), real, and anonymous_namespace{utilTest.cpp}::t().
dualquat& dualquat::lerp (const dualquat & from, const dualquat & to, float t) inline
References add(), vec4::dot(), dual, vec4::mul(), mul(), real, and anonymous_namespace{utilTest.cpp}::t().
dualquat& dualquat::mul (float k) inline
References dual, quat::mul(), and real.
Referenced by skelmodel::skelmeshgroup::blendbones(), skelmodel::skeleton::calctags(), skelmodel::skeleton::genragdollbones(), gettranslation(), skelmodel::skeleton::initpitchdeps(), skelmodel::skeleton::initragdoll(), skelmodel::skeleton::interpbones(), invert(), lerp(), md5::md5meshgroup::loadanim(), iqm::iqmmeshgroup::loadiqmanims(), iqm::iqmmeshgroup::loadiqmmeshes(), mul(), mulorient(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readskeleton(), and transform().
void dualquat::mul (const dualquat & p, const dualquat & o) inline
References quat::add(), dual, quat::mul(), mul(), and real.
void dualquat::mul (const dualquat & o) inline
References dualquat(), and mul().
Referenced by mul().
void dualquat::mulorient (const quat & q) inline
References dual, invert(), quat::mul(), and real.
Referenced by skeladjustment::adjust(), and skelmodel::skeleton::interpbones().
void dualquat::mulorient (const quat & q, const dualquat & base) inline
References quat::add(), add(), vec4::dot(), dual, quat::invert(), invert(), quat::mul(), mul(), real, and quat::sub().
void dualquat::normalize () inline
References dual, vec4::magnitude(), quat::mul(), and real.
Referenced by skelmodel::skelmeshgroup::blendbones().
void dualquat::scale (float k) inline
References dual, and quat::mul().
vec dualquat::transform (const vec & v) const inline
References add(), vec::cross(), dual, vec::mul(), mul(), and real.
Referenced by skelmodel::skeleton::initragdoll().
quat dualquat::transform (const quat & q) const inline
References quat::mul(), and real.
vec dualquat::transformnormal (const vec & v) const inline
References real, and quat::rotate().
Referenced by skelmodel::skeleton::calcdeviation().
void dualquat::translate (const vec & p) inline
References dual, and real.
Referenced by skeladjustment::adjust().
vec dualquat::transposedtransform (const vec & v) const inline
References dualquat().
vec dualquat::transposedtransformnormal (const vec & v) const inline
References quat::invertedrotate(), and real.
Member Data Documentation
quat dualquat::dual
Referenced by accumulate(), add(), dualquat(), fixantipodal(), gettranslation(), invert(), lerp(), matrix4x3::matrix4x3(), mul(), mulorient(), normalize(), scale(), transform(), and translate().
quat dualquat::real
Referenced by accumulate(), add(), dualquat(), fixantipodal(), gettranslation(), invert(), lerp(), matrix4x3::matrix4x3(), mul(), mulorient(), normalize(), skelmodel::skeleton::setglslbones(), transform(), transformnormal(), translate(), and transposedtransformnormal().
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp