Inexor: ai::avoidset Struct Reference
ai::avoidset Struct Reference
#include <ai.hpp>
Classes
struct obstacle
Public Member Functions
void clear ()
void add (void *owner, float above)
void add (void *owner, float above, int wp)
void add (avoidset &avoid)
void avoidnear (void *owner, float above, const vec &pos, float limit)
bool find (int n, fpsent *d) const
int remap (fpsent *d, int n, vec &pos, bool retry=false)
Public Attributes
vector< obstacle > obstacles
vector< int > waypoints
Member Function Documentation
void ai::avoidset::add (void * owner, float above) inline
References obstacles.
Referenced by add(), and ai::avoid().
void ai::avoidset::add (void * owner, float above, int wp) inline
References vector< T, MINSIZE >::add(), add(), obstacles, and waypoints.
void ai::avoidset::add (avoidset & avoid) inline
References ai::avoidset::obstacle::above, add(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), loopv, ai::avoidset::obstacle::numwaypoints, obstacles, ai::avoidset::obstacle::owner, vector< T, MINSIZE >::put(), and waypoints.
void ai::avoidset::avoidnear (void * owner, float above, const vec & pos, float limit)
References ai::wpcache::node::axis(), ai::buildwpcache(), CHECKNEAR, ai::wpcache::node::childindex(), ai::clearedwpcaches, ai::wpcache::node::isleaf(), ai::lastwpcache, loop, ai::NUMWPCACHES, ai::wpcache::node::split, ai::waypoints, and ai::wpcaches.
Referenced by ai::avoid(), game::avoidweapons(), and ai::buildwpcache().
void ai::avoidset::clear () inline
References obstacles, vector< T, MINSIZE >::setsize(), and waypoints.
Referenced by ai::avoid(), and ai::buildwpcache().
bool ai::avoidset::find (int n, fpsent * d) const inline
References loopavoid.
Referenced by ai::checkroute(), and ai::randomnode().
int ai::avoidset::remap (fpsent * d, int n, vec & pos, bool retry = false)
References ai::avoidset::obstacle::above, vec::add(), ai::closestwaypoint(), mpr::collide(), cur, physent::eyeheight, ai::find(), ai::iswaypoint(), ai::JUMPMAX, loopv, ai::avoidset::obstacle::numwaypoints, physent::o, ai::obstacles, ai::avoidset::obstacle::owner, ai::SIGHTMIN, and ai::waypoints.
Referenced by ai::closenode(), and ai::wpspot().
Member Data Documentation
vector<obstacle> ai::avoidset::obstacles
Referenced by add(), clear(), and ai::render().
vector<int> ai::avoidset::waypoints
Referenced by add(), clear(), and ai::render().
The documentation for this struct was generated from the following files:
inexor/fpsgame/ai.hpp
inexor/fpsgame/waypoint.cpp