Inexor: stream Struct Reference
stream Struct Reference abstract
Legacy file system streams.
#include <stream.hpp>
Public Types
typedef off_t offset
Public Member Functions
virtual ~stream ()
virtual void close ()=0
virtual bool end ()=0
virtual offset tell ()
virtual offset rawtell ()
virtual bool seek (offset pos, int whence=SEEK_SET)
virtual offset size ()
virtual offset rawsize ()
virtual size_t read (void *buf, size_t len)
virtual size_t write (const void *buf, size_t len)
virtual bool flush ()
virtual int getchar ()
virtual bool putchar (int n)
virtual bool getline (char *str, size_t len)
virtual bool putstring (const char *str)
virtual bool putline (const char *str)
virtual size_t printf (const char *fmt,...) PRINTFARGS(2
virtual size_t virtual uint getcrc ()
template<class T >
size_t put (const T *v, size_t n)
template<class T >
bool put (T n)
template<class T >
bool putlil (T n)
template<class T >
bool putbig (T n)
template<class T >
size_t get (T *v, size_t n)
template<class T >
T get ()
template<class T >
T getlil ()
template<class T >
T getbig ()
Detailed Description
Legacy file system streams.
Use the filesystem module for new code.
Member Typedef Documentation
typedef off_t stream::offset
Constructor & Destructor Documentation
virtual stream::~stream () inline virtual
Member Function Documentation
virtual void stream::close () pure virtual
Implemented in utf8stream, gzstream, and filestream.
virtual bool stream::end () pure virtual
Implemented in utf8stream, gzstream, and filestream.
Referenced by gzstream::checkheader(), and ai::loadwaypoints().
virtual bool stream::flush () inline virtual
Reimplemented in utf8stream, gzstream, and filestream.
Referenced by utf8stream::flush(), and gzstream::flushbuf().
template<class T > size_t stream::get (T * v, size_t n) inline
References read().
Referenced by streambuf< T >::get().
template<class T > T stream::get () inline
References read().
template<class T > T stream::getbig () inline
References bigswap().
virtual int stream::getchar () inline virtual
Reimplemented in filestream.
References read().
Referenced by load_world(), loadblendmap(), loadc(), loadents(), loadviewcells(), and ai::loadwaypoints().
virtual size_t virtual uint stream::getcrc () inline virtual
Reimplemented in gzstream.
Referenced by load_world(), and loadents().
template<class T > T stream::getlil () inline
References lilswap().
Referenced by load_world(), loadc(), loadents(), loadpvs(), loadviewcells(), loadvslot(), loadvslots(), ai::loadwaypoints(), and gzstream::size().
bool stream::getline (char * str, size_t len) virtual
Reimplemented in utf8stream, and filestream.
References loopi(), and read().
Referenced by obj::objmeshgroup::load(), md5::md5mesh::load(), md5::md5meshgroup::loadanim(), smd::smdmeshgroup::loadanim(), loadhistory(), md5::md5meshgroup::loadmesh(), smd::smdmeshgroup::loadmesh(), editline::read(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readnodes(), smd::smdmeshgroup::readskeleton(), smd::smdmeshgroup::readtriangles(), and smd::smdmeshgroup::skipsection().
size_t stream::printf (const char * fmt, ...) virtual
Reimplemented in filestream.
References _vsnprintf, and write().
Referenced by writebinds(), writecfg(), game::writeclientinfo(), writecompletions(), writecrosshairs(), writeinitcfg(), and writeobj().
template<class T > size_t stream::put (const T * v, size_t n) inline
References write().
Referenced by streambuf< T >::put().
template<class T > bool stream::put (T n) inline
References write().
template<class T > bool stream::putbig (T n) inline
References bigswap().
Referenced by savepng(), and writepngchunk().
virtual bool stream::putchar (int n) inline virtual
Reimplemented in filestream.
References write().
Referenced by putline(), save_world(), saveblendmap(), savec(), savetga(), saveviewcells(), and ai::savewaypoints().
template<class T > bool stream::putlil (T n) inline
References lilswap().
Referenced by save_world(), savec(), savepvs(), saveviewcells(), savevslot(), savevslots(), and ai::savewaypoints().
virtual bool stream::putline (const char * str) inline virtual
References putchar(), and putstring().
Referenced by editor::save(), and writehistory().
virtual bool stream::putstring (const char * str) inline virtual
Reimplemented in filestream.
References write().
Referenced by putline().
virtual offset stream::rawsize () inline virtual
Reimplemented in gzstream.
References size().
virtual offset stream::rawtell () inline virtual
Reimplemented in gzstream.
References tell().
Referenced by server::writedemo().
virtual size_t stream::read (void * buf, size_t len) inline virtual
Reimplemented in utf8stream, gzstream, and filestream.
Referenced by server::adddemo(), utf8stream::checkheader(), get(), getchar(), getline(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), load_world(), loadblendmap(), loadc(), loaddds(), loadents(), loadfile(), iqm::iqmmeshgroup::loadiqm(), loadprefab(), loadpvs(), loadvslot(), ai::loadwaypoints(), make_file_packet(), gzstream::readbuf(), utf8stream::readbuf(), server::readdemo(), and server::setupdemoplayback().
virtual bool stream::seek (offset pos, int whence = SEEK_SET) inline virtual
Reimplemented in utf8stream, gzstream, and filestream.
Referenced by server::adddemo(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), load_world(), loadc(), loadents(), loadvslot(), make_file_packet(), savepng(), size(), gzstream::size(), and gzstream::skipbytes().
stream::offset stream::size () virtual
Reimplemented in gzstream.
References seek(), and tell().
Referenced by server::adddemo(), streambuf< T >::length(), loadfile(), make_file_packet(), rawsize(), gzstream::rawsize(), and game::sendmap().
virtual offset stream::tell () inline virtual
Reimplemented in utf8stream, gzstream, and filestream.
Referenced by gzstream::checkheader(), rawtell(), gzstream::rawtell(), savepng(), and size().
virtual size_t stream::write (const void * buf, size_t len) inline virtual
Reimplemented in utf8stream, gzstream, and filestream.
Referenced by gzstream::finishwriting(), gzstream::flushbuf(), gendds(), printf(), put(), putchar(), putstring(), server::receivefile(), game::receivefile(), save_world(), saveblendmap(), savec(), savepng(), saveprefab(), savepvs(), savetga(), savevslot(), ai::savewaypoints(), server::setupdemorecord(), utf8stream::write(), server::writedemo(), gzstream::writeheader(), and writepngchunk().
The documentation for this struct was generated from the following files:
inexor/io/legacy/stream.hpp
inexor/io/legacy/stream.cpp