Inexor: filestream Struct Reference
filestream Struct Reference
Public Types
typedef off_t offset
Public Member Functions
filestream ()
~filestream () override
bool open (const char *name, const char *mode)
bool opentemp (const char *name, const char *mode)
void close () override
bool end () override
offset tell () override
bool seek (offset pos, int whence) override
size_t read (void *buf, size_t len) override
size_t write (const void *buf, size_t len) override
bool flush () override
int getchar () override
bool putchar (int c) override
bool getline (char *str, size_t len) override
bool putstring (const char *str) override
size_t printf (const char *fmt,...) override
virtual offset rawtell ()
virtual offset size ()
virtual offset rawsize ()
virtual bool putline (const char *str)
virtual size_t virtual uint getcrc ()
template<class T >
size_t put (const T *v, size_t n)
template<class T >
bool put (T n)
template<class T >
bool putlil (T n)
template<class T >
bool putbig (T n)
template<class T >
size_t get (T *v, size_t n)
template<class T >
T get ()
template<class T >
T getlil ()
template<class T >
T getbig ()
Public Attributes
FILE * file
Member Typedef Documentation
typedef off_t stream::offset inherited
Constructor & Destructor Documentation
filestream::filestream () inline
filestream::~filestream () inline override
References close().
Member Function Documentation
void filestream::close () inline override virtual
Implements stream.
References file.
Referenced by ~filestream().
bool filestream::end () inline override virtual
Implements stream.
References file.
bool filestream::flush () inline override virtual
Reimplemented from stream.
References file.
template<class T > size_t stream::get (T * v, size_t n) inline inherited
References stream::read().
Referenced by streambuf< T >::get().
template<class T > T stream::get () inline inherited
References stream::read().
template<class T > T stream::getbig () inline inherited
References bigswap().
int filestream::getchar () inline override virtual
Reimplemented from stream.
References file.
virtual size_t virtual uint stream::getcrc () inline virtual inherited
Reimplemented in gzstream.
Referenced by load_world(), and loadents().
template<class T > T stream::getlil () inline inherited
References lilswap().
Referenced by load_world(), loadc(), loadents(), loadpvs(), loadviewcells(), loadvslot(), loadvslots(), ai::loadwaypoints(), and gzstream::size().
bool filestream::getline (char * str, size_t len) inline override virtual
Reimplemented from stream.
References file.
bool filestream::open (const char * name, const char * mode) inline
References file.
Referenced by openrawfile().
bool filestream::opentemp (const char * name, const char * mode) inline
References file.
Referenced by opentempfile().
size_t filestream::printf (const char * fmt, ...) inline override virtual
Reimplemented from stream.
References file, inexor::rpc::max(), and result().
template<class T > size_t stream::put (const T * v, size_t n) inline inherited
References stream::write().
Referenced by streambuf< T >::put().
template<class T > bool stream::put (T n) inline inherited
References stream::write().
template<class T > bool stream::putbig (T n) inline inherited
References bigswap().
Referenced by savepng(), and writepngchunk().
bool filestream::putchar (int c) inline override virtual
Reimplemented from stream.
References file.
template<class T > bool stream::putlil (T n) inline inherited
References lilswap().
Referenced by save_world(), savec(), savepvs(), saveviewcells(), savevslot(), savevslots(), and ai::savewaypoints().
virtual bool stream::putline (const char * str) inline virtual inherited
References stream::putchar(), and stream::putstring().
Referenced by editor::save(), and writehistory().
bool filestream::putstring (const char * str) inline override virtual
Reimplemented from stream.
References file.
virtual offset stream::rawsize () inline virtual inherited
Reimplemented in gzstream.
References stream::size().
virtual offset stream::rawtell () inline virtual inherited
Reimplemented in gzstream.
References stream::tell().
Referenced by server::writedemo().
size_t filestream::read (void * buf, size_t len) inline override virtual
Reimplemented from stream.
References file.
bool filestream::seek (offset pos, int whence) inline override virtual
Reimplemented from stream.
References file.
stream::offset stream::size () virtual inherited
Reimplemented in gzstream.
References stream::seek(), and stream::tell().
Referenced by server::adddemo(), streambuf< T >::length(), loadfile(), make_file_packet(), stream::rawsize(), gzstream::rawsize(), and game::sendmap().
offset filestream::tell () inline override virtual
Reimplemented from stream.
References file.
size_t filestream::write (const void * buf, size_t len) inline override virtual
Reimplemented from stream.
References file.
Member Data Documentation
FILE* filestream::file
Referenced by close(), end(), flush(), getchar(), getline(), open(), opentemp(), printf(), putchar(), putstring(), read(), seek(), tell(), and write().
The documentation for this struct was generated from the following file:
inexor/io/legacy/stream.cpp