Inexor: skelmodel::blendcombo Struct Reference
skelmodel::blendcombo Struct Reference
#include <skelmodel.hpp>
Public Member Functions
blendcombo ()
bool operator== (const blendcombo &c) const
int size () const
int addweight (int sorted, float weight, int bone)
void finalize (int sorted)
void serialize (vvertw &v)
Static Public Member Functions
static bool sortcmp (const blendcombo &x, const blendcombo &y)
Public Attributes
int uses
int interpindex
float weights [4]
uchar bones [4]
uchar interpbones [4]
Constructor & Destructor Documentation
skelmodel::blendcombo::blendcombo () inline
Member Function Documentation
int skelmodel::blendcombo::addweight (int sorted, float weight, int bone) inline
References bones, f(), loopk, inexor::rpc::min(), and weights.
Referenced by md5::md5mesh::buildverts(), iqm::iqmmeshgroup::loadiqmmeshes(), and smd::smdmeshgroup::readtriangles().
void skelmodel::blendcombo::finalize (int sorted) inline
References bones, loopj, and weights.
Referenced by md5::md5mesh::buildverts(), iqm::iqmmeshgroup::loadiqmmeshes(), and smd::smdmeshgroup::readtriangles().
bool skelmodel::blendcombo::operator== (const blendcombo & c) const inline
References bones, loopk, and weights.
void skelmodel::blendcombo::serialize (vvertw & v) inline
References skelmodel::vvertw::bones, f(), interpbones, interpindex, loopk, skelmodel::vvertw::weights, and weights.
Referenced by skelmodel::skelmesh::assignvert().
int skelmodel::blendcombo::size () const inline
References weights.
Referenced by skelmodel::skelmesh::addblendcombo(), skelmodel::skelmeshgroup::addblendcombo(), and skelmodel::skelmeshgroup::genvbo().
static bool skelmodel::blendcombo::sortcmp (const blendcombo & x, const blendcombo & y) inline static
References loopi(), and weights.
Referenced by skelmodel::skelmeshgroup::sortblendcombos().
Member Data Documentation
uchar skelmodel::blendcombo::bones[4]
Referenced by addweight(), finalize(), operator==(), and skelmodel::skeleton::remapbones().
uchar skelmodel::blendcombo::interpbones[4]
Referenced by skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::remapblend(), skelmodel::skeleton::remapbones(), and serialize().
int skelmodel::blendcombo::interpindex
Referenced by skelmodel::skelmeshgroup::addblendcombo(), skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::genvbo(), skelmodel::skelmeshgroup::remapblend(), and serialize().
int skelmodel::blendcombo::uses
Referenced by skelmodel::skelmeshgroup::addblendcombo().
float skelmodel::blendcombo::weights[4]
Referenced by addweight(), skelmodel::skelmeshgroup::blendbones(), finalize(), skelmodel::skelmeshgroup::genvbo(), operator==(), skelmodel::skelmeshgroup::remapblend(), skelmodel::skeleton::remapbones(), serialize(), size(), and sortcmp().
The documentation for this struct was generated from the following file:
inexor/model/skelmodel.hpp