Inexor: vec Struct Reference
vec Struct Reference
vector with 3 floats and some useful methods.
#include <geom.hpp>
Public Member Functions
vec ()
a variety of constructor calls is supported
vec (int a)
vec (float a)
vec (float a, float b, float c)
vec (int v[3])
vec (const float *v)
vec (const vec2 &v, float z=0)
vec (const vec4 &v)
vec (const ivec &v)
vec (float yaw, float pitch)
vector constructor which converts yaw and pitch angles to XYZ coordinates
float & operator[] (int i)
operators for accessing XYZ vector coordinates
float operator[] (int i) const
vec & set (int i, float f)
bool operator== (const vec &o) const
operators for vector comparisn
bool operator!= (const vec &o) const
vec & abs ()
Receive the absolute values of this vec.
bool iszero () const
"do all cartesian coordinates (XYZ) of this vector have the value zero?"
float squaredlen () const
calculate the squared length of this vector (pythagoras)
template<class T >
float dot2 (const T &o) const
dot product (line by line) of 2 dimensions
float dot (const vec &o) const
dot product (line by line) of all 3 dimensions
float absdot (const vec &o) const
dot product with absolute values.
vec & mul (const vec &o)
scalar multiplication
vec & mul (float f)
vec & div (const vec &o)
scalar division
vec & div (float f)
vec & add (const vec &o)
scalar sum
vec & add (float f)
vec & sub (const vec &o)
scalar subtraction
vec & sub (float f)
vec & neg2 ()
turn XY coordinates into its negative values
vec & neg ()
turn all 3 (XYZ) coordinates into its negative values
vec & min (const vec &o)
vector min/max-comparison and clamp methods
vec & max (const vec &o)
vec & min (float f)
vec & max (float f)
vec & clamp (float f, float h)
float magnitude2 () const
vector's magnitude in XY dimension
float magnitude () const
vector's magnitude in all 3 (XYZ) dimensions
vec & normalize ()
normalize vector: divide it by its length (magnitude)
bool isnormalized () const
"is this vector normalized?"
float squaredist (const vec &e) const
distance calculation methods
float dist (const vec &e) const
float dist (const vec &e, vec &t) const
float dist2 (const vec &o) const
bool reject (const vec &o, float r)
template<class A , class B >
vec & cross (const A &a, const B &b)
template based vector cross product
vec & cross (const vec &o, const vec &a, const vec &b)
float scalartriple (const vec &a, const vec &b) const
scalar triple product can be used to calculate the volume of a 3 dimensional parallelogram
vec & reflectz (float rz)
vector reflection (around angle or other vectors)
vec & reflect (const vec &n)
vec & project (const vec &n)
vector projection
vec & projectxydir (const vec &n)
vec & projectxy (const vec &n)
vec & projectxy (const vec &n, float threshold)
vec & lerp (const vec &b, float t)
interpolation between two vectors
vec & lerp (const vec &a, const vec &b, float t)
template<class B >
vec & madd (const vec &a, const B &b)
template<class B >
vec & msub (const vec &a, const B &b)
vec & rescale (float k)
scale a vector to a certain length
vec & rotate_around_z (float c, float s)
vector rotation methods
vec & rotate_around_x (float c, float s)
vec & rotate_around_y (float c, float s)
vec & rotate_around_z (float angle)
vec & rotate_around_x (float angle)
vec & rotate_around_y (float angle)
vec & rotate_around_z (const vec2 &sc)
vec & rotate_around_x (const vec2 &sc)
vec & rotate_around_y (const vec2 &sc)
vec & rotate (float c, float s, const vec &d)
vec & rotate (float angle, const vec &d)
vec & rotate (const vec2 &sc, const vec &d)
void orthogonal (const vec &d)
orthogonal projection
void orthonormalize (vec &s, vec &t) const
template<class T >
bool insidebb (const T &bbmin, const T &bbmax) const
is vector inside bounding box bounding boxes have a minimal vector and a maximal vector
template<class T , class U >
bool insidebb (const T &o, U size) const
template<class T >
float dist_to_bb (const T &min, const T &max) const
calculate vector's distance to a bounding box
template<class T , class S >
float dist_to_bb (const T &o, S size) const
Static Public Member Functions
static vec hexcolor (int color)
Public Attributes
union {
struct {
float x
float y
float z
}
struct {
float r
float g
float b
}
float v [3]
};
memory union which contains position, color or 3 float values please note that only one of these members can be accessed!
Friends
std::ostream & operator<< (std::ostream &os, const vec &v)
Output operator, used for simple << vec << functionality: output of form"(x, y, z)" You may want to set the precision beforehand with std::setprecision()
Detailed Description
vector with 3 floats and some useful methods.
Constructor & Destructor Documentation
vec::vec () inline
a variety of constructor calls is supported
Referenced by cross(), hexcolor(), madd(), msub(), orthogonal(), orthonormalize(), rotate(), squaredist(), and plane::toplane().
vec::vec (int a) inline explicit
vec::vec (float a) inline explicit
vec::vec (float a, float b, float c) inline
vec::vec (int v[3]) inline explicit
vec::vec (const float * v) inline explicit
vec::vec (const vec2 & v, float z = 0) inline explicit
vec::vec (const vec4 & v) inline explicit
vec::vec (const ivec & v) inline explicit
vec::vec (float yaw, float pitch) inline
vector constructor which converts yaw and pitch angles to XYZ coordinates
Member Function Documentation
vec& vec::abs () inline
Receive the absolute values of this vec.
Referenced by matrix3::abstransform().
float vec::absdot (const vec & o) const inline
dot product with absolute values.
Referenced by matrix3::abstransposedtransform().
vec& vec::add (const vec & o) inline
scalar sum
Referenced by physent::abovehead(), matrix3::abstransform(), triangle::add(), game::adddynlights(), addgrasstri(), addmergedverts(), addnormals(), addtris(), ragdolldata::applyrotlimit(), avoidcollision(), BIH::BIH(), blendfogoverlay(), bounce(), model::boundbox(), boxs(), ai::wpcache::build(), animmodel::mesh::buildnorms(), md5::md5mesh::buildverts(), partrenderer::calc(), ragdolldata::calcanimjoint(), calcavatarpos(), animmodel::calcbb(), ragdolldata::calcboundsphere(), calcgeombb(), vertmodel::vertmeshgroup::calctagmatrix(), skelmodel::skeleton::calctags(), animmodel::mesh::calctangents(), calcvert(), mpr::SolidCube::center(), blobrenderer::clip(), decalrenderer::clip(), mpr::collide(), ragdolldata::constraindist(), ai::delselwaypoints(), dist_to_bb(), shadowmaptexture::dorender(), game::drawhudmodel(), game::drawminimap(), drawminimap(), game::collectclientmode::droptoken(), dynlightreaching(), game::dynlighttrack(), editmoveplane(), ellipsecollide(), gui::end(), entautoview(), entpaste(), entselectionbox(), game::explode(), game::explodeeffects(), physent::feetpos(), particleemitter::finalize(), fireballrenderer::finddepthfxranges(), findnormal(), ai::findorientation(), g3d_key(), genclipplanes(), gencubeverts(), generatelightmap(), generatelumel(), gengrassquads(), genpos(), genpos< PT_TRAIL >(), genprefabmesh(), skelmodel::skeleton::genragdollbones(), blobrenderer::gentris(), decalrenderer::gentris(), getentboundingbox(), dualquat::gettranslation(), game::gotoplayer(), game::gotosel(), guessnormals(), guessshadowdir(), physent::headpos(), fpsent::hitpush(), game::movable::hitpush(), game::hudgunorigin(), ragdolldata::init(), skelmodel::skeleton::initragdoll(), interppos(), quat::invertedrotate(), isshadowmapreceiver(), ai::jumpto(), lerpnormal(), lightreaching(), madd(), menuinfrontofplayer(), mmcollide(), mpr::Model::Model(), modifygravity(), ragdolldata::move(), move(), movecamera(), moveplatform(), moveplayer(), moveragdoll(), ai::movewaypoints(), matrix4x3::mul(), game::newbouncer(), noedit(), game::offsetray(), particle_trail(), game::particletrack(), game::predictplayer(), previewblends(), previewlightmapalpha(), ai::process(), rayboxintersect(), raycubepos(), recalcdir(), recomputecamera(), regularshape(), ai::avoidset::remap(), flarerenderer::render(), render3dbox(), game::renderbouncers(), rendereditcursor(), renderellipse(), renderentarrow(), renderentbox(), renderentcone(), game::collectclientmode::rendergame(), renderlightning(), rendermodel(), game::renderplayerpreview(), game::renderprojectiles(), quat::rotate(), varenderer< T >::seedemitter(), seedpos(), seedpos< PT_TRAIL >(), setcammatrix(), setlerpstep(), ragdollskel::setupjoints(), setupsunlight(), setupsurface(), setupsurfaces(), setva(), game::shoot(), game::shorten(), game::shoteffects(), slideagainst(), animmodel::mesh::smoothnorms(), game::spawnbouncer(), game::spawnnextsplinter(), game::spawnsplinters(), blobrenderer::split(), mpr::EntOBB::supportpoint(), mpr::EntCapsule::supportpoint(), mpr::ModelOBB::supportpoint(), mpr::ModelEllipse::supportpoint(), game::swayhudgun(), switchfloor(), threeplaneintersect(), matrix4::transform(), matrix4::transformnormal(), trystepdown(), trystepup(), ragdolldata::tryunstick(), game::updatebouncers(), game::updateprojectiles(), and writeobj().
vec& vec::add (float f) inline
References f().
vec& vec::clamp (float f, float h) inline
Referenced by linkvslotshader().
template<class A , class B > vec& vec::cross (const A & a, const B & b) inline
template based vector cross product
Referenced by decalrenderer::adddecal(), addgrasstri(), addnormals(), ragdolldata::applyrotlimit(), animmodel::mesh::buildnorms(), ragdolldata::calcanimjoint(), skelmodel::skeleton::calcdeviation(), animmodel::mesh::calctangent(), animmodel::mesh::calctangents(), ragdolldata::calctris(), mpr::collide(), gengrassquads(), genpos< PT_TAPE >(), decalrenderer::gentris(), dualquat::gettranslation(), guessnormals(), quat::invertedrotate(), renderlightning(), quat::rotate(), matrix3::rotationalign(), ragdollskel::setupjoints(), setupsurface(), animmodel::mesh::smoothnorms(), threeplaneintersect(), plane::toplane(), dualquat::transform(), and BIH::triintersect().
vec& vec::cross (const vec & o, const vec & a, const vec & b) inline
References cross(), sub(), and vec().
Referenced by cross().
float vec::dist (const vec & e) const inline
References dist(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by adddecal(), adddynlight(), addgrasstri(), game::collectclientmode::aicheck(), attachentity(), calcwatersubdiv(), game::captureclientmode::checkitems(), game::collectclientmode::checkitems(), game::ctfclientmode::checkitems(), entities::checkitems(), inexor::sound::checkmapsounds(), entities::checktriggers(), closestenvmap(), cullmodel(), dist(), capturemode_common::disttoenemy(), endmodelbatches(), entities::entradius(), particleemitter::finalize(), finddynlights(), g3d_addgui(), g3d_key(), g3d_mainmenu(), gengrassquads(), ai::getsight(), ai::getyawpitch(), game::hitpush(), nearestent(), game::offsetray(), overlapsdynent(), game::parsepositions(), particle_text(), particle_textcopy(), particle_trail(), game::particletrack(), game::ctfclientmode::pickholdspawn(), game::captureclientmode::pickteamspawn(), inexor::sound::playsound(), server::shotevent::process(), game::projdist(), game::radialbombeffect(), recomputecamera(), renderentradius(), renderentselection(), game::ctfclientmode::respawned(), game::ctfclientmode::returnflag(), ai::route(), game::ctfclientmode::scoreflag(), game::shoot(), game::shoteffects(), texturegui::show(), splash(), inexor::sound::updatechannel(), updateparticles(), and game::updateprojectiles().
float vec::dist (const vec & e, vec & t) const inline
References magnitude(), and sub().
float vec::dist2 (const vec & o) const inline
Referenced by regularshape().
template<class T > float vec::dist_to_bb (const T & min, const T & max) const inline
calculate vector's distance to a bounding box
References loopi().
Referenced by calcdynlightmask(), dist_to_bb(), findvisiblemms(), and vadist().
template<class T , class S > float vec::dist_to_bb (const T & o, S size) const inline
References add(), and dist_to_bb().
vec& vec::div (const vec & o) inline
scalar division
Referenced by addgrasstri(), ragdolldata::applyrotfriction(), ragdolldata::applyrotlimit(), blendfogoverlay(), brightestlight(), ragdolldata::calcboundsphere(), mpr::EntOBB::contactface(), mpr::ModelOBB::contactface(), mpr::ModelEllipse::contactface(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), game::drawteammate(), dynlightreaching(), generatelightmap(), genpos< PT_TRAIL >(), grasswedge::grasswedge(), guessshadowdir(), lerpnormal(), lightreaching(), modifyvelocity(), inexor::sound::mumblevec(), normalize(), plane::normalize(), particle_trail(), matrix4::perspectivetransform(), game::projdist(), game::radialbombeffect(), animmodel::part::render(), renderlightning(), seedpos< PT_TRAIL >(), setlerpstep(), game::shoot(), threeplaneintersect(), plane::toplane(), ragdolldata::tryunstick(), and ragdolldata::updatepos().
vec& vec::div (float f) inline
References f().
float vec::dot (const vec & o) const inline
dot product (line by line) of all 3 dimensions
Referenced by decalrenderer::adddecal(), flarerenderer::addflare(), addlight(), bounce(), brightestlight(), skelmodel::skeleton::calcdeviation(), calcskylight(), animmodel::mesh::calctangents(), decalrenderer::clip(), mpr::collide(), cubecollideplanes(), plane::dist(), shadowmaptexture::dorender(), gui::end(), falling(), findnormal(), fuzzycollideplanes(), generategrass(), generatelumel(), gengrassquads(), decalrenderer::gentris(), grasswedge::grasswedge(), lightreaching(), linecylinderintersect(), flarerenderer::makelightflares(), mmintersect(), move(), matrix4x3::multranspose(), orthonormalize(), project(), projectxy(), plane::rayintersect(), raysphereintersect(), reflect(), matrix3::rotationalign(), setupsurface(), gui::start(), mpr::EntOBB::supportcoord(), mpr::EntOBB::supportcoordneg(), mpr::CubePlanes::supportpoint(), switchfloor(), plane::toplane(), plane::translate(), matrix4x3::transpose(), matrix3::transposedtransform(), matrix4x3::transposedtransform(), matrix4x3::transposedtransformnormal(), matrix3::transposemul(), matrix4x3::transposemul(), BIH::triintersect(), and ragdolldata::updatepos().
template<class T > float vec::dot2 (const T & o) const inline
dot product (line by line) of 2 dimensions
Referenced by mpr::EntCylinder::contactface(), mpr::ModelEllipse::contactface(), magnitude2(), and matrix3::transposedtransform().
static vec vec::hexcolor (int color) inline static
References f(), and vec().
Referenced by drawenvoverlay(), drawskybox(), guiprefabpreview(), renderblendbrush(), renderoutline(), and renderprefab().
template<class T > bool vec::insidebb (const T & bbmin, const T & bbmax) const inline
is vector inside bounding box bounding boxes have a minimal vector and a maximal vector
template<class T , class U > bool vec::insidebb (const T & o, U size) const inline
bool vec::isnormalized () const inline
"is this vector normalized?"
References f(), and squaredlen().
Referenced by calcocclusion().
bool vec::iszero () const inline
"do all cartesian coordinates (XYZ) of this vector have the value zero?"
Referenced by skeladjustment::adjust(), calcocclusion(), mpr::collide(), cubecollideplanes(), cubecollidesolid(), dynlightreaching(), ellipseboxcollide(), ellipsecollide(), encodenormal(), fuzzycollideplanes(), fuzzycollidesolid(), generatelumel(), guessnormals(), guessshadowdir(), lightreaching(), mmcollide(), platformcollide(), plcollide(), raycube(), animmodel::part::render(), slideagainst(), game::spawnbouncer(), texcolorify(), game::updatemovables(), and vectoyawpitch().
vec& vec::lerp (const vec & b, float t) inline
interpolation between two vectors
Referenced by dynlight::calccolor(), findtnormal(), game::ctfclientmode::interpflagpos(), matrix4x3::lerp(), and modifyvelocity().
vec& vec::lerp (const vec & a, const vec & b, float t) inline
template<class B > vec& vec::madd (const vec & a, const B & b) inline
References add(), mul(), and vec().
Referenced by matrix4x3::accumulate(), blendfog(), blendfogoverlay(), matrix3::mul(), matrix4x3::mul(), matrix3::multranspose(), matrix4x3::multranspose(), matrix3::rotate_around_x(), matrix4x3::rotate_around_x(), matrix3::rotate_around_y(), matrix4x3::rotate_around_y(), matrix3::rotate_around_z(), matrix4x3::rotate_around_z(), matrix3::transform(), matrix4x3::transform(), matrix4x3::transformnormal(), and matrix4x3::translate().
float vec::magnitude () const inline
vector's magnitude in all 3 (XYZ) dimensions
References squaredlen().
Referenced by flarerenderer::addflare(), BIH::BIH(), blurtexture(), bounce(), model::boundsphere(), brightestlight(), calcmodelpreviewpos(), model::collisionbox(), ragdolldata::constraindist(), cubecollideplanes(), damagecompass(), dist(), shadowmaptexture::dorender(), dynlightreaching(), falling(), fireballrenderer::finddepthfxranges(), fuzzycollideplanes(), generatelumel(), lightreaching(), flarerenderer::makelightflares(), normalize(), plane::normalize(), bvec::normalize(), raycubelos(), recalcdir(), game::renderbouncers(), renderlightning(), rendermodel(), fireballrenderer::renderpart(), rescale(), game::sendposition(), animmodel::mesh::smoothnorms(), mpr::EntCapsule::supportpoint(), game::swayhudgun(), switchfloor(), plane::toplane(), trystepdown(), trystepup(), game::updatebouncers(), and vectoyawpitch().
float vec::magnitude2 () const inline
vector's magnitude in XY dimension
References dot2().
Referenced by calcmodelpreviewpos(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), game::drawteammate(), server::parsepacket(), fireballrenderer::renderpart(), mpr::EntCylinder::supportpoint(), mpr::ModelEllipse::supportpoint(), entities::teleport(), trystepdown(), and inexor::sound::updatechannel().
vec& vec::max (const vec & o) inline
References inexor::rpc::max().
Referenced by BIH::BIH(), blendfogoverlay(), ai::wpcache::build(), calcgeombb(), calcshadowmask(), entselectionbox(), genclipplanes(), blobrenderer::gentris(), and getentboundingbox().
vec& vec::max (float f) inline
References inexor::rpc::max().
vec& vec::min (const vec & o) inline
vector min/max-comparison and clamp methods
References inexor::rpc::min().
Referenced by BIH::BIH(), calcshadowmask(), genclipplanes(), and blobrenderer::gentris().
vec& vec::min (float f) inline
References inexor::rpc::min().
template<class B > vec& vec::msub (const vec & a, const B & b) inline
References mul(), sub(), and vec().
Referenced by matrix4x3::multranspose(), matrix3::rotate_around_x(), matrix4x3::rotate_around_x(), matrix3::rotate_around_y(), matrix4x3::rotate_around_y(), matrix3::rotate_around_z(), and matrix4x3::rotate_around_z().
vec& vec::mul (const vec & o) inline
scalar multiplication
Referenced by matrix3::abstransform(), game::adddynlights(), flarerenderer::addflare(), addmergedverts(), addnormals(), addtris(), ragdolldata::applyrotlimit(), BIH::BIH(), bounce(), boxs3D(), md5::md5mesh::buildverts(), quat::calcangleaxis(), matrix3::calcangleaxis(), ragdolldata::calcanimjoint(), animmodel::calcbb(), dynlight::calccolor(), calcgeombb(), vertmodel::vertmeshgroup::calctagmatrix(), skelmodel::skeleton::calctags(), animmodel::mesh::calctangents(), calcvert(), blobrenderer::clip(), decalrenderer::clip(), mpr::collide(), vertmodel::vertmeshgroup::concattagtransform(), skelmodel::skeleton::concattagtransform(), ragdolldata::constraindist(), ai::delselwaypoints(), shadowmaptexture::dorender(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), drawfogdome(), game::drawhudmodel(), game::drawminimap(), drawminimap(), game::drawteammate(), server::ctfservermode::dropflag(), dynlightreaching(), editmoveplane(), gui::end(), entautoview(), entpaste(), entselectionbox(), game::explodeeffects(), particleemitter::finalize(), fireballrenderer::finddepthfxranges(), findents(), ai::findorientation(), genclipplanes(), gencubeverts(), generatelightmap(), generatelumel(), gengrassquads(), genpos(), genpos< PT_TAPE >(), genprefabmesh(), skelmodel::skeleton::genragdollbones(), genrotpos< PT_PART >(), blobrenderer::gentris(), decalrenderer::gentris(), dualquat::gettranslation(), game::gotoplayer(), game::gotosel(), guessshadowdir(), fpsent::hitpush(), game::movable::hitpush(), game::hudgunorigin(), ragdolldata::init(), skelmodel::skeleton::initragdoll(), interppos(), matrix3::invert(), matrix4x3::invert(), quat::invertedrotate(), isshadowmapreceiver(), lerpnormal(), lightreaching(), madd(), flarerenderer::makelightflares(), menuinfrontofplayer(), mergevslot(), modifygravity(), modifyvelocity(), game::movable::movable(), ragdolldata::move(), movecamera(), moveplayer(), moveragdoll(), game::collectclientmode::movetoken(), msub(), matrix3::mul(), matrix4x3::mul(), matrix3::multranspose(), matrix4x3::multranspose(), game::newbouncer(), noedit(), game::offsetray(), server::parsepacket(), game::parsepositions(), game::particletrack(), game::predictplayer(), previewblends(), previewlightmapalpha(), previewprefab(), server::bombservermode::pushentity(), rayboxintersect(), raycubelos(), raycubepos(), recalcdir(), regularshape(), flarerenderer::render(), game::renderbouncers(), rendereditcursor(), renderentarrow(), renderentcone(), renderlightning(), renderprefab(), game::renderprojectiles(), rendertexturepanel(), renderwater(), rescale(), quat::rotate(), matrix3::rotate_around_x(), matrix4x3::rotate_around_x(), matrix3::rotate_around_y(), matrix4x3::rotate_around_y(), matrix3::rotate_around_z(), matrix4x3::rotate_around_z(), matrix3::scale(), matrix4x3::scale(), plane::scale(), game::selectcrosshair(), game::sendposition(), setcammatrix(), setdynlights(), setlerpstep(), setupcaustics(), ragdollskel::setupjoints(), setupsunlight(), setupsurface(), setupsurfaces(), setva(), game::shoot(), game::shorten(), blobrenderer::split(), game::swayhudgun(), threeplaneintersect(), dualquat::transform(), matrix3::transform(), matrix4::transform(), matrix4x3::transformnormal(), matrix4::transformnormal(), game::triggerplatform(), trystepdown(), trystepup(), game::updatebouncers(), game::updatemovables(), and game::updateprojectiles().
vec& vec::mul (float f) inline
References f().
vec& vec::neg () inline
turn all 3 (XYZ) coordinates into its negative values
Referenced by animmodel::mesh::calctangents(), mpr::collide(), shadowmaptexture::dorender(), game::explodeeffects(), findfloor(), plane::invert(), mmcollide(), platformcollide(), plcollide(), game::projsplash(), recomputecamera(), setcammatrix(), game::triggerplatform(), and game::updatemovables().
vec& vec::neg2 () inline
turn XY coordinates into its negative values
vec& vec::normalize () inline
normalize vector: divide it by its length (magnitude)
References div(), and magnitude().
Referenced by decalrenderer::adddecal(), addnormals(), brightestlight(), animmodel::mesh::buildnorms(), partrenderer::calc(), ragdolldata::calcanimjoint(), skelmodel::skeleton::calcdeviation(), animmodel::mesh::calctangents(), ragdolldata::calctris(), mpr::collide(), mpr::EntCylinder::contactface(), mpr::ModelEllipse::contactface(), droptofloor(), dynlightreaching(), ellipsecollide(), gui::end(), entautoview(), entities::entradius(), findnormal(), findtnormal(), generatelightmap(), generatelumel(), genpos< PT_TAPE >(), decalrenderer::gentris(), guessnormals(), guessshadowdir(), lerpnormal(), lightreaching(), gui::modelpreview(), modifygravity(), modifyvelocity(), game::newbouncer(), game::newprojectile(), matrix3::normalize(), matrix4x3::normalize(), game::offsetray(), previewblends(), renderentradius(), renderlightning(), game::renderplayerpreview(), game::renderprojectiles(), setlerpstep(), setsunlightdir(), ragdollskel::setupjoints(), setupsurface(), setupsurfaces(), slideagainst(), animmodel::mesh::smoothnorms(), game::spawnbouncer(), mpr::EntEllipsoid::supportpoint(), texnormal(), and trystepdown().
bool vec::operator!= (const vec & o) const inline
bool vec::operator== (const vec & o) const inline
operators for vector comparisn
float& vec::operator[] (int i) inline
operators for accessing XYZ vector coordinates
float vec::operator[] (int i) const inline
void vec::orthogonal (const vec & d) inline
orthogonal projection
References vec().
Referenced by decalrenderer::adddecal(), decalrenderer::gentris(), renderentarrow(), renderentcone(), and renderlightning().
void vec::orthonormalize (vec & s, vec & t) const inline
References dot(), sub(), and vec().
Referenced by generatelumel().
vec& vec::project (const vec & n) inline
vector projection
References dot().
Referenced by skelmodel::skeleton::calcdeviation(), modifygravity(), slideagainst(), and switchfloor().
vec& vec::projectxy (const vec & n) inline
References dot(), f(), inexor::rpc::max(), projectxydir(), rescale(), and squaredlen().
Referenced by switchfloor().
vec& vec::projectxy (const vec & n, float threshold) inline
References dot(), f(), inexor::rpc::max(), inexor::rpc::min(), projectxydir(), rescale(), and squaredlen().
vec& vec::projectxydir (const vec & n) inline
Referenced by projectxy().
vec& vec::reflect (const vec & n) inline
References dot().
Referenced by ragdolldata::move(), and ragdolldata::updatepos().
vec& vec::reflectz (float rz) inline
vector reflection (around angle or other vectors)
bool vec::reject (const vec & o, float r) inline
Referenced by game::explode(), mmcollide(), moveplatform(), plcollide(), and game::updateprojectiles().
vec& vec::rescale (float k) inline
scale a vector to a certain length
References f(), magnitude(), and mul().
Referenced by calcavatarpos(), game::newbouncer(), projectxy(), regularshape(), and ragdolldata::tryunstick().
vec& vec::rotate (float c, float s, const vec & d) inline
References vec().
Referenced by decalrenderer::adddecal().
vec& vec::rotate (float angle, const vec & d) inline
References rotate().
Referenced by rotate().
vec& vec::rotate (const vec2 & sc, const vec & d) inline
References rotate().
Referenced by rotate().
vec& vec::rotate_around_x (float c, float s) inline
Referenced by calcmodelpreviewpos().
vec& vec::rotate_around_x (float angle) inline
References rotate_around_x().
Referenced by rotate_around_x().
vec& vec::rotate_around_x (const vec2 & sc) inline
References rotate_around_x().
Referenced by rotate_around_x().
vec& vec::rotate_around_y (float c, float s) inline
vec& vec::rotate_around_y (float angle) inline
References rotate_around_y().
Referenced by rotate_around_y().
vec& vec::rotate_around_y (const vec2 & sc) inline
References rotate_around_y().
Referenced by rotate_around_y().
vec& vec::rotate_around_z (float c, float s) inline
vector rotation methods
Referenced by calcshadowmapbb(), shadowmaptexture::dorender(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), drawenvoverlay(), game::drawminimap(), game::drawteammate(), ellipseboxcollide(), ellipsecollide(), mmintersect(), renderellipse(), rendermodel(), setshadowdir(), and inexor::sound::updatechannel().
vec& vec::rotate_around_z (float angle) inline
References rotate_around_z().
Referenced by rotate_around_z().
vec& vec::rotate_around_z (const vec2 & sc) inline
References rotate_around_z().
Referenced by rotate_around_z().
float vec::scalartriple (const vec & a, const vec & b) const inline
scalar triple product can be used to calculate the volume of a 3 dimensional parallelogram
Referenced by addcubeverts(), and mpr::collide().
vec& vec::set (int i, float f) inline
References f().
Referenced by gui::end().
float vec::squaredist (const vec & e) const inline
distance calculation methods
References vec().
Referenced by game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::collectclientmode::aifind(), game::ctfclientmode::aifind(), game::ctfclientmode::aihomerun(), ai::assist(), ai::canshoot(), clampcollide(), ai::closenode(), ai::defend(), ai::enemy(), ai::hasrange(), ai::itemspawned(), ai::jumpto(), ai::patrol(), ai::process(), ai::target(), ai::tryitem(), and ai::wpspot().
float vec::squaredlen () const inline
calculate the squared length of this vector (pythagoras)
Referenced by flarerenderer::addflare(), BIH::BIH(), matrix3::calcangleaxis(), clampcollide(), dynlightreaching(), findents(), matrix3::invert(), matrix4x3::invert(), isnormalized(), linecylinderintersect(), magnitude(), physent::maymove(), mmintersect(), game::offsetray(), projectxy(), and raysphereintersect().
vec& vec::sub (const vec & o) inline
scalar subtraction
Referenced by decalrenderer::adddecal(), flarerenderer::addflare(), addgrasstri(), addlight(), addnormals(), addtris(), ragdolldata::applyrotlimit(), avoidcollision(), BIH::BIH(), bounce(), game::bounced(), brightestlight(), ai::wpcache::build(), animmodel::mesh::buildnorms(), partrenderer::calc(), ragdolldata::calcanimjoint(), calcavatarpos(), animmodel::calcbb(), calcshadowmapbb(), calcshadowmask(), animmodel::mesh::calctangents(), ragdolldata::calctris(), blobrenderer::clip(), decalrenderer::clip(), mpr::collide(), ragdolldata::constraindist(), cross(), damagecompass(), ai::delselwaypoints(), dist(), ai::dointerest(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), game::drawminimap(), drawminimap(), game::drawteammate(), dynlightreaching(), editmoveplane(), ellipseboxcollide(), gui::end(), entautoview(), entselectionbox(), fireballrenderer::finddepthfxranges(), findents(), g3d_key(), genclipplanes(), generatelightmap(), generatelumel(), gengrassquads(), genpos(), genpos< PT_TAPE >(), skelmodel::skeleton::genragdollbones(), decalrenderer::gentris(), getentboundingbox(), dualquat::gettranslation(), guessshadowdir(), game::hudgunorigin(), ragdolldata::init(), ai::jumpto(), lerpnormal(), lightreaching(), linecylinderintersect(), ai::lockon(), flarerenderer::makelightflares(), mmcollide(), mmintersect(), gui::modelpreview(), ragdolldata::move(), moveplayer(), msub(), game::newbouncer(), game::newprojectile(), game::offsetray(), orthonormalize(), platformcollide(), plcollide(), flag::pos(), raycubelos(), raysphereintersect(), regularshape(), flarerenderer::render(), animmodel::part::render(), render3dbox(), rendereditcursor(), renderentradius(), renderlightning(), fireballrenderer::renderpart(), game::renderplayer(), game::bombclientmode::renderplayersposindicator(), game::renderprojectiles(), setdynlights(), setlerpstep(), ragdollskel::setupjoints(), setupsurface(), game::shorten(), animmodel::mesh::smoothnorms(), blobrenderer::split(), triangle::sub(), plane::toplane(), matrix4x3::transposedtransform(), matrix4::transposedtransform(), BIH::triintersect(), trystepup(), game::updatebouncers(), and ragdolldata::updatepos().
vec& vec::sub (float f) inline
References f().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const vec & v) friend
Output operator, used for simple << vec << functionality: output of form"(x, y, z)" You may want to set the precision beforehand with std::setprecision()
Member Data Documentation
union { ... }
memory union which contains position, color or 3 float values please note that only one of these members can be accessed!
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp