Inexor: GlobalShaderParamState Struct Reference
GlobalShaderParamState Struct Reference
#include <shader.hpp>
Public Member Functions
void resetversions ()
void changed ()
Public Attributes
const char * name
union {
float fval [32]
int ival [32]
uint uval [32]
uchar buf [32 *sizeof(float)]
};
int version
Static Public Attributes
static int nextversion = 0
Member Function Documentation
void GlobalShaderParamState::changed () inline
References nextversion, resetversions(), and version.
Referenced by GlobalShaderParam::resolve().
void GlobalShaderParamState::resetversions ()
References enumerate, globalparams, loopv, GlobalShaderParamUse::param, shaders, version, and GlobalShaderParamUse::version.
Referenced by changed().
Member Data Documentation
union { ... }
const char* GlobalShaderParamState::name
Referenced by getglobalparam().
int GlobalShaderParamState::nextversion = 0 static
Referenced by changed().
int GlobalShaderParamState::version
Referenced by changed(), GlobalShaderParamUse::flush(), getglobalparam(), and resetversions().
The documentation for this struct was generated from the following files:
inexor/engine/shader.hpp
inexor/engine/shader.cpp