Inexor: md2::md2meshgroup Struct Reference
md2::md2meshgroup Struct Reference
#include <md2.hpp>
Public Member Functions
void genverts (int *glcommands, vector< tcvert > &tcverts, vector< ushort > &vindexes, vector< tri > &tris)
bool load (const char *filename)
int findtag (const char *name) override
int totalframes () const override
void concattagtransform (part *p, int i, const matrix4x3 &m, matrix4x3 &n) override
void calctagmatrix (part *p, int i, const animstate &as, matrix4 &matrix)
void genvbo (bool tangents, vbocacheentry &vc)
void bindvbo (const animstate *as, vbocacheentry &vc)
void cleanup () override
void preload (part *p) override
void render (const animstate *as, float pitch, const vec &axis, const vec &forward, dynent *d, part *p) override
void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m)
void genBIH (vector< skin > &skins, vector< BIH::mesh > &bih, const matrix4x3 &t)
virtual void * animkey ()
bool hasframe (int i) const
bool hasframes (int i, int n) const
int clipframes (int i, int n) const
void bindpos (GLuint ebuf, GLuint vbuf, void *v, int stride)
void bindtc (void *v, int stride)
void bindnormals (void *v, int stride)
void bindtangents (void *v, int stride)
void bindbones (void *wv, void *bv, int stride)
Public Attributes
int numframes
tag * tags
int numtags
vbocacheentry vbocache [MAXVBOCACHE]
ushort * edata
GLuint ebuf
bool vtangents
int vlen
int vertsize
uchar * vdata
meshgroup * next
int shared
char * name
vector< mesh * > meshes
Static Public Attributes
static const int MAXVBOCACHE = 16
Member Function Documentation
virtual void* animmodel::meshgroup::animkey () inline virtual inherited
Reimplemented in skelmodel::skelmeshgroup.
Referenced by animmodel::part::calcanim().
void animmodel::meshgroup::bindbones (void * wv, void * bv, int stride) inline inherited
References animmodel::enablebones, animmodel::lastbbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindnormals (void * v, int stride) inline inherited
References animmodel::enablenormals, animmodel::lastnbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindpos (GLuint ebuf, GLuint vbuf, void * v, int stride) inline inherited
References gle::bindebo(), gle::bindvbo(), sphere::ebuf, animmodel::lastebuf, animmodel::lastvbuf, and sphere::vbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindtangents (void * v, int stride) inline inherited
References animmodel::enabletangents, animmodel::lastvbuf, and animmodel::lastxbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindtc (void * v, int stride) inline inherited
References animmodel::enabletc, animmodel::lasttcbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void vertmodel::vertmeshgroup::bindvbo (const animstate * as, vbocacheentry & vc) inline inherited
References animmodel::animpos::anim, ANIM_NOSKIN, animmodel::animstate::cur, animmodel::disablebones(), animmodel::disablenormals(), animmodel::disabletangents(), animmodel::disabletc(), sphere::ebuf, animmodel::enablebones, animmodel::enablenormals, animmodel::enabletangents, animmodel::enabletc, vertmodel::vvertn::norm, vertmodel::vvert::pos, vertmodel::vvertbump::tangent, vertmodel::vvert::tc, vertmodel::vbocacheentry::vbuf, and vverts.
void animmodel::meshgroup::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline inherited
References loopv, and animmodel::meshgroup::meshes.
Referenced by animmodel::part::calcbb().
void vertmodel::vertmeshgroup::calctagmatrix (part * p, int i, const animstate & as, matrix4 & matrix) inline inherited
References vec::add(), animmodel::animstate::cur, matrix4x3::d, animmodel::animpos::fr1, animmodel::animpos::fr2, animmodel::animstate::interp, matrix4x3::lerp(), animmodel::part::model, vec::mul(), animmodel::animstate::prev, model::scale, animmodel::animpos::t, matrix4x3::transform(), and animmodel::part::translate.
void vertmodel::vertmeshgroup::cleanup () inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References vertmodel::vbocacheentry::as, animmodel::animstate::cur, sphere::ebuf, animmodel::animpos::fr1, glDeleteBuffers_, loopi(), and vertmodel::vbocacheentry::vbuf.
int animmodel::meshgroup::clipframes (int i, int n) const inline inherited
References inexor::rpc::min(), and animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
void vertmodel::vertmeshgroup::concattagtransform (part * p, int i, const matrix4x3 & m, matrix4x3 & n) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References animmodel::part::model, vec::mul(), matrix4x3::mul(), model::scale, matrix4x3::transformnormal(), animmodel::part::translate, and matrix4x3::translate().
int vertmodel::vertmeshgroup::findtag (const char * name) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References loopi().
void animmodel::meshgroup::genBIH (vector< skin > & skins, vector< BIH::mesh > & bih, const matrix4x3 & t) inline inherited
References loopv, and animmodel::meshgroup::meshes.
Referenced by animmodel::part::genBIH().
void vertmodel::vertmeshgroup::genvbo (bool tangents, vbocacheentry & vc) inline inherited
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), DELETEA, sphere::ebuf, FILLVDATA, GENVBO, vector< T, MINSIZE >::getbuf(), glBufferData_, glGenBuffers_, vector< T, MINSIZE >::length(), loopv, vertmodel::vertmesh::numverts, and vertmodel::vbocacheentry::vbuf.
void md2::md2meshgroup::genverts (int * glcommands, vector< tcvert > & tcverts, vector< ushort > & vindexes, vector< tri > & tris) inline
References hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::access(), vector< T, MINSIZE >::add(), f(), vector< T, MINSIZE >::length(), loopi(), loopk, vector< T, MINSIZE >::setsize(), anonymous_namespace{utilTest.cpp}::t(), vertmodel::tcvert::tc, and vertmodel::tri::vert.
Referenced by load().
bool animmodel::meshgroup::hasframe (int i) const inline inherited
References animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
bool animmodel::meshgroup::hasframes (int i, int n) const inline inherited
References animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
bool md2::md2meshgroup::load (const char * filename) inline
References recorder::file, md2::md2_header::framesize, genverts(), vector< T, MINSIZE >::getbuf(), animmodel::mesh::group, vector< T, MINSIZE >::length(), lilswap(), loopi(), loopj, md2::md2_header::magic, md2normaltable, animmodel::meshgroup::meshes, animmodel::meshgroup::name, newstring(), vertmodel::vert::norm, md2::md2_vertex::normalindex, md2::md2_header::numframes, vertmodel::vertmeshgroup::numframes, md2::md2_header::numglcommands, vertmodel::vertmesh::numtris, md2::md2_header::numvertices, vertmodel::vertmesh::numverts, md2::md2_header::offsetframes, md2::md2_header::offsetglcommands, openfile(), vertmodel::vert::pos, stream::read(), md2::md2_frame::scale, stream::seek(), vertmodel::vertmesh::tcverts, md2::md2_frame::translate, vertmodel::vertmesh::tris, md2::md2_header::version, md2::md2_vertex::vertex, and vertmodel::vertmesh::verts.
Referenced by md2::loadmeshes().
void vertmodel::vertmeshgroup::preload (part * p) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References animmodel::cleanup(), vertmodel::vertmesh::genvbo(), and animmodel::part::tangents().
void vertmodel::vertmeshgroup::render (const animstate * as, float pitch, const vec & axis, const vec & forward, dynent * d, part * p) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References animmodel::animpos::anim, ANIM_NORENDER, vertmodel::vbocacheentry::as, gle::bindvbo(), animmodel::cleanup(), animmodel::animstate::cur, animmodel::disablevbo(), vertmodel::vertmesh::genvbo(), glBufferData_, vertmodel::vertmesh::interpverts(), lastmillis, animmodel::part::links, loopi(), loopv, vertmodel::vbocacheentry::millis, vertmodel::vertmesh::render(), animmodel::part::skins, animmodel::part::tangents(), vertmodel::vbocacheentry::vbuf, vc, and vertmodel::vertmesh::voffset.
int vertmodel::vertmeshgroup::totalframes () const inline override virtual inherited
Reimplemented from animmodel::meshgroup.
Member Data Documentation
GLuint vertmodel::vertmeshgroup::ebuf inherited
ushort* vertmodel::vertmeshgroup::edata inherited
const int vertmodel::vertmeshgroup::MAXVBOCACHE = 16 static inherited
vector<mesh *> animmodel::meshgroup::meshes inherited
Referenced by animmodel::meshgroup::calcbb(), animmodel::meshgroup::genBIH(), skelmodel::skelmeshgroup::genvbo(), animmodel::part::initskins(), md3::md3meshgroup::load(), load(), smd::smdmeshgroup::readtriangles(), skelmodel::skelmeshgroup::render(), skelmodel::skelmeshgroup::sortblendcombos(), and animmodel::meshgroup::~meshgroup().
char* animmodel::meshgroup::name inherited
Referenced by md3::md3meshgroup::load(), load(), smd::smdmeshgroup::load(), smd::smdmeshgroup::readmaterial(), smd::smdmeshgroup::readname(), smd::smdmeshgroup::readnodes(), and animmodel::meshgroup::~meshgroup().
meshgroup* animmodel::meshgroup::next inherited
Referenced by animmodel::meshgroup::~meshgroup().
int vertmodel::vertmeshgroup::numframes inherited
Referenced by md3::md3meshgroup::load(), and load().
int vertmodel::vertmeshgroup::numtags inherited
Referenced by md3::md3meshgroup::load().
int animmodel::meshgroup::shared inherited
Referenced by animmodel::part::loaded().
tag* vertmodel::vertmeshgroup::tags inherited
Referenced by md3::md3meshgroup::load().
vbocacheentry vertmodel::vertmeshgroup::vbocache[MAXVBOCACHE] inherited
uchar* vertmodel::vertmeshgroup::vdata inherited
int vertmodel::vertmeshgroup::vertsize inherited
int vertmodel::vertmeshgroup::vlen inherited
bool vertmodel::vertmeshgroup::vtangents inherited
The documentation for this struct was generated from the following file:
inexor/model/md2.hpp