Inexor: particleemitter Struct Reference
particleemitter Struct Reference
#include <particles.hpp>
Public Member Functions
particleemitter (extentity *ent)
void finalize ()
void extendbb (const vec &o, float size=0)
void extendbb (float z, float size=0)
Public Attributes
extentity * ent
vec bbmin
vec bbmax
vec center
float radius
ivec cullmin
ivec cullmax
int maxfade
int lastemit
int lastcull
Constructor & Destructor Documentation
particleemitter::particleemitter (extentity * ent) inline
Member Function Documentation
void particleemitter::extendbb (const vec & o, float size = 0)
References inexor::rpc::max(), and inexor::rpc::min().
Referenced by fireballrenderer::seedemitter(), lightningrenderer::seedemitter(), varenderer< T >::seedemitter(), and seedpos().
void particleemitter::extendbb (float z, float size = 0)
References inexor::rpc::max(), and inexor::rpc::min().
void particleemitter::finalize ()
References vec::add(), vec::dist(), f(), Log, vec::mul(), and inexor::util::log_manager::std.
Referenced by seedparticles().
Member Data Documentation
vec particleemitter::bbmax
vec particleemitter::bbmin
vec particleemitter::center
Referenced by updateparticles().
ivec particleemitter::cullmax
Referenced by updateparticles().
ivec particleemitter::cullmin
Referenced by updateparticles().
extentity* particleemitter::ent
Referenced by fireballrenderer::seedemitter(), seedparticles(), and updateparticles().
int particleemitter::lastcull
Referenced by updateparticles().
int particleemitter::lastemit
Referenced by seedparticles(), and updateparticles().
int particleemitter::maxfade
Referenced by fireballrenderer::seedemitter(), lightningrenderer::seedemitter(), varenderer< T >::seedemitter(), and updateparticles().
float particleemitter::radius
Referenced by updateparticles().
The documentation for this struct was generated from the following files:
inexor/engine/particles.hpp
inexor/engine/renderparticles.cpp