Inexor: hashtable< K, T > Struct Template Reference
hashtable< K, T > Struct Template Reference
#include <cube_hash.hpp>
Public Types
typedef hashbase< hashtable< K,
T >, hashtableentry< K, T >, K,
T > basetype
typedef basetype::elemtype elemtype
enum
enum
typedef K keytype
typedef T datatype
Public Member Functions
hashtable (int size=basetype::DEFAULTSIZE)
chain * insert (uint h)
T & insert (uint h, const U &key)
T * access (const U &key)
T & access (const U &key, const V &elem)
T & operator[] (const U &key)
T & find (const U &key, T &notfound)
const T & find (const U &key, const T &notfound)
bool remove (const U &key)
void deletechunks ()
void clear ()
Static Public Member Functions
static K & getkey (elemtype &elem)
static T & getdata (elemtype &elem)
template<class U >
static void setkey (elemtype &elem, const U &key)
static chain * enumnext (void *i)
static K & enumkey (void *i)
static T & enumdata (void *i)
Public Attributes
int size
int numelems
chain ** chains
chainchunk * chunks
chain * unused
Member Typedef Documentation
template<class K, class T> typedef hashbase<hashtable<K, T>, hashtableentry<K, T>, K, T> hashtable< K, T >::basetype
typedef T hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::datatype inherited
template<class K, class T> typedef basetype::elemtype hashtable< K, T >::elemtype
typedef K hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::keytype inherited
Member Enumeration Documentation
anonymous enum inherited
anonymous enum inherited
Constructor & Destructor Documentation
template<class K, class T> hashtable< K, T >::hashtable (int size = basetype::DEFAULTSIZE) inline
Member Function Documentation
T* hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::access (const U & key) inline inherited
Referenced by destroyvbo(), md2::md2meshgroup::genverts(), obj::objmeshgroup::load(), smd::smdmeshgroup::readtriangles(), animmodel::mesh::smoothnorms(), and writeobj().
T& hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::access (const U & key, const V & elem) inline inherited
void hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::clear () inline inherited
Referenced by genmerges().
void hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::deletechunks () inline inherited
static T& hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::enumdata (void * i) inline static inherited
static K& hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::enumkey (void * i) inline static inherited
static chain* hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::enumnext (void * i) inline static inherited
T& hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::find (const U & key, T & notfound) inline inherited
const T& hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::find (const U & key, const T & notfound) inline inherited
template<class K, class T> static T& hashtable< K, T >::getdata (elemtype & elem) inline static
template<class K, class T> static K& hashtable< K, T >::getkey (elemtype & elem) inline static
chain* hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::insert (uint h) inline inherited
T& hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::insert (uint h, const U & key) inline inherited
T& hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::operator[] (const U & key) inline inherited
bool hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::remove (const U & key) inline inherited
Referenced by destroyvbo().
template<class K, class T> template<class U > static void hashtable< K, T >::setkey (elemtype & elem, const U & key) inline static
Member Data Documentation
chain** hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::chains inherited
chainchunk* hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::chunks inherited
int hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::numelems inherited
Referenced by genmerges().
int hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::size inherited
chain* hashbase< hashtable< K, T > , hashtableentry< K, T > , K, T >::unused inherited
The documentation for this struct was generated from the following file:
inexor/shared/cube_hash.hpp