Inexor: mpr::EntOBB Struct Reference
mpr::EntOBB Struct Reference
#include <mpr.hpp>
Public Member Functions
EntOBB (physent *ent, float zmargin=0)
vec center () const
vec contactface (const vec &wn, const vec &wdir) const
vec localsupportpoint (const vec &ln) const
vec supportpoint (const vec &n) const
float supportcoordneg (float a, float b, float c) const
float supportcoord (float a, float b, float c) const
float left () const
float right () const
float back () const
float front () const
float bottom () const
float top () const
Public Attributes
matrix3 orient
float zmargin
physent * ent
Constructor & Destructor Documentation
mpr::EntOBB::EntOBB (physent * ent, float zmargin = 0) inline
References orient, RAD, matrix3::setyaw(), and physent::yaw.
Member Function Documentation
float mpr::EntOBB::back () const inline
References matrix3::a, matrix3::b, matrix3::c, mpr::Ent::ent, physent::o, orient, and supportcoordneg().
float mpr::EntOBB::bottom () const inline
References mpr::Ent::ent, physent::eyeheight, physent::o, and zmargin.
vec mpr::EntOBB::center () const inline
References physent::aboveeye, mpr::Ent::ent, physent::eyeheight, physent::o, and zmargin.
vec mpr::EntOBB::contactface (const vec & wn, const vec & wdir) const inline
References physent::aboveeye, dir, vec::div(), mpr::Ent::ent, physent::eyeheight, orient, matrix3::transform(), matrix3::transposedtransform(), physent::xradius, physent::yradius, and zmargin.
float mpr::EntOBB::front () const inline
References matrix3::a, matrix3::b, matrix3::c, mpr::Ent::ent, physent::o, orient, and supportcoord().
float mpr::EntOBB::left () const inline
References matrix3::a, matrix3::b, matrix3::c, mpr::Ent::ent, physent::o, orient, and supportcoordneg().
vec mpr::EntOBB::localsupportpoint (const vec & ln) const inline
References physent::aboveeye, mpr::Ent::ent, physent::eyeheight, physent::xradius, physent::yradius, and zmargin.
Referenced by supportcoord(), supportcoordneg(), and supportpoint().
float mpr::EntOBB::right () const inline
References matrix3::a, matrix3::b, matrix3::c, mpr::Ent::ent, physent::o, orient, and supportcoord().
float mpr::EntOBB::supportcoord (float a, float b, float c) const inline
References vec::dot(), and localsupportpoint().
Referenced by front(), and right().
float mpr::EntOBB::supportcoordneg (float a, float b, float c) const inline
References vec::dot(), and localsupportpoint().
Referenced by back(), and left().
vec mpr::EntOBB::supportpoint (const vec & n) const inline
References vec::add(), mpr::Ent::ent, localsupportpoint(), physent::o, orient, matrix3::transform(), and matrix3::transposedtransform().
float mpr::EntOBB::top () const inline
References physent::aboveeye, mpr::Ent::ent, and physent::o.
Member Data Documentation
physent* mpr::Ent::ent inherited
Referenced by back(), mpr::EntFuzzy::back(), bottom(), mpr::EntFuzzy::bottom(), mpr::EntCylinder::bottom(), mpr::Ent::center(), center(), mpr::EntCylinder::center(), contactface(), mpr::EntCylinder::contactface(), front(), mpr::EntFuzzy::front(), left(), mpr::EntFuzzy::left(), localsupportpoint(), right(), mpr::EntFuzzy::right(), supportpoint(), mpr::EntCylinder::supportpoint(), mpr::EntCapsule::supportpoint(), mpr::EntEllipsoid::supportpoint(), top(), and mpr::EntFuzzy::top().
matrix3 mpr::EntOBB::orient
Referenced by back(), contactface(), EntOBB(), front(), left(), right(), and supportpoint().
float mpr::EntOBB::zmargin
Referenced by bottom(), center(), contactface(), and localsupportpoint().
The documentation for this struct was generated from the following file:
inexor/physics/mpr.hpp