Inexor: Shader Struct Reference
Shader Struct Reference
#include <shader.hpp>
Public Member Functions
Shader ()
~Shader ()
void fixdetailshader (bool force=true, bool recurse=true)
void allocparams (Slot *slot=nullptr)
void setslotparams (Slot &slot)
void setslotparams (Slot &slot, VSlot &vslot)
void bindprograms ()
void flushparams (Slot *slot=nullptr)
void force ()
bool invalid () const
bool deferred () const
bool loaded () const
bool isnull () const
int numvariants (int row) const
Shader * getvariant (int col, int row) const
bool hasoption (int row)
void addvariant (int row, Shader *s)
void setvariant_ (int col, int row, Shader *fallbackshader)
void setvariant (int col, int row, Shader *fallbackshader)
void setvariant (int col, int row)
void setvariant (int col, int row, Slot &slot, VSlot &vslot, Shader *fallbackshader)
void setvariant (int col, int row, Slot &slot, VSlot &vslot)
void set_ ()
void set ()
void set (Slot &slot, VSlot &vslot)
bool compile ()
void cleanup (bool invalid=false)
Static Public Member Functions
static bool isnull (const Shader *s)
static int uniformlocversion ()
Public Attributes
char * name
char * vsstr
char * psstr
char * defer
int type
GLuint program
GLuint vsobj
GLuint psobj
vector< SlotShaderParamState > defaultparams
vector< GlobalShaderParamUse > globalparams
vector< LocalShaderParamState > localparams
vector< uchar > localparamremap
Shader * detailshader
Shader * variantshader
Shader * altshader
Shader * fastshader [MAXSHADERDETAIL]
vector< Shader * > variants
ushort * variantrows
bool standard
bool forced
bool used
Shader * reusevs
Shader * reuseps
vector< UniformLoc > uniformlocs
vector< AttribLoc > attriblocs
const void * owner
Static Public Attributes
static Shader * lastshader = nullptr
Constructor & Destructor Documentation
Shader::Shader () inline
References fastshader, loopi(), and MAXSHADERDETAIL.
Shader::~Shader () inline
References defer, DELETEA, name, psstr, variantrows, and vsstr.
Member Function Documentation
void Shader::addvariant (int row, Shader * s) inline
References vector< T, MINSIZE >::insert(), vector< T, MINSIZE >::length(), MAXVARIANTROWS, variantrows, and variants.
void Shader::allocparams (Slot * slot = nullptr)
References allocglslactiveuniforms(), Slot::Tex::combined, defformatstring, loopv, SHADER_ENVMAP, SHADER_NORMALSLMS, Slot::sts, anonymous_namespace{utilTest.cpp}::t(), TEX_DECAL, TEX_DEPTH, TEX_DIFFUSE, TEX_GLOW, TEX_NORMAL, TEX_SPEC, TEX_UNKNOWN, Slot::Tex::type, and UNIFORMTEX.
Referenced by flushparams().
void Shader::bindprograms ()
References glUseProgram_, SHADER_DEFERRED, and SHADER_INVALID.
Referenced by set_(), and setvariant_().
void Shader::cleanup (bool invalid = false)
References altshader(), DELETEA, fastshader(), glDeleteProgram_, glDeleteShader_, globalparams, localparams, loopi(), loopv, MAXSHADERDETAIL, and SHADER_INVALID.
Referenced by cleanupshaders(), newshader(), and reloadshaders().
bool Shader::compile ()
References compileglslshader(), linkglslprogram(), and variantshader().
Referenced by newshader(), and reloadshaders().
bool Shader::deferred () const inline
References SHADER_DEFERRED, and type.
Referenced by fixdetailshader().
void Shader::fixdetailshader (bool force = true, bool recurse = true)
References altshader, cur, deferred(), fastshader, force(), invalid(), loopv, MAXSHADERDETAIL, and shaderdetail.
Referenced by altshader(), fastshader(), fixshaderdetail(), linkslotshader(), newshader(), and useshaderbyname().
void Shader::flushparams (Slot * slot = nullptr) inline
References allocparams(), globalparams, loopv, and used.
Referenced by flushhudmatrix(), set(), setcamprojmatrix(), and setvariant().
void Shader::force ()
References DELETEA, execute(), forceshaders, identflags, IDF_PERSIST, SHADER_INVALID, vector< T, MINSIZE >::shrink(), slotparams, and standardshaders.
Referenced by fixdetailshader().
Shader* Shader::getvariant (int col, int row) const inline
References gle::end(), MAXVARIANTROWS, recorder::start(), variantrows, and variants.
Referenced by hasoption(), and newshader().
bool Shader::hasoption (int row) inline
References detailshader, getvariant(), SHADER_OPTION, and type.
Referenced by changeshader().
bool Shader::invalid () const inline
References SHADER_INVALID, and type.
Referenced by defershader(), fixdetailshader(), and reloadshaders().
static bool Shader::isnull (const Shader * s) inline static
bool Shader::isnull () const inline
References isnull().
Referenced by isnull(), set(), and setvariant().
bool Shader::loaded () const inline
References detailshader.
Referenced by lookupshaderbyname(), set(), and setvariant().
int Shader::numvariants (int row) const inline
References MAXVARIANTROWS, and variantrows.
Referenced by gengenericvariant(), and variantshader().
void Shader::set () inline
References flushparams(), isnull(), lastshader, loaded(), and set_().
Referenced by gui::background(), changeshader(), rendertarget::debug(), debugparticles(), editor::draw(), draw_crosshair(), draw_g3d_cursor(), drawdamagecompass(), drawdamagescreen(), recorder::drawhud(), drawskylimits(), drawskyoutline(), gui::field_(), gl_drawframe(), gl_drawhud(), gl_rendercef(), gl_rendercefmouse(), texturegui::gui(), loadshaders(), maskreflection(), gui::modelpreview(), gui::playerpreview(), gui::prefabpreview(), gui::previewslot(), queryreflection(), flarerenderer::render(), decalrenderer::render(), renderbackground(), rendereditcursor(), renderfoggedvas(), rendermaterials(), rendermodel(), renderoutline(), renderparticles(), renderpostfx(), renderprogress(), rendertexturepanel(), renderwater(), renderzpass(), setblurshader(), animmodel::mesh::setshader(), skelmodel::skelmesh::setshader(), blobrenderer::setuprenderstate(), and gui::start().
void Shader::set (Slot & slot, VSlot & vslot) inline
References flushparams(), isnull(), lastshader, loaded(), set_(), and setslotparams().
void Shader::set_ () inline
References bindprograms(), detailshader, and lastshader.
Referenced by set().
void Shader::setslotparams (Slot & slot)
References Slot::params, SETDEFAULTPARAMS, and SETSLOTPARAMS.
Referenced by set(), and setvariant().
void Shader::setslotparams (Slot & slot, VSlot & vslot)
References VSlot::params, Slot::params, SETDEFAULTPARAMS, SETSLOTPARAMS, and VSlot::slot.
void Shader::setvariant (int col, int row, Shader * fallbackshader) inline
References flushparams(), isnull(), lastshader, loaded(), and setvariant_().
Referenced by changeshader(), renderfoggedvas(), animmodel::mesh::setshader(), and skelmodel::skelmesh::setshader().
void Shader::setvariant (int col, int row) inline
References detailshader, flushparams(), isnull(), lastshader, loaded(), and setvariant_().
void Shader::setvariant (int col, int row, Slot & slot, VSlot & vslot, Shader * fallbackshader) inline
References flushparams(), isnull(), lastshader, loaded(), setslotparams(), and setvariant_().
void Shader::setvariant (int col, int row, Slot & slot, VSlot & vslot) inline
References detailshader, flushparams(), isnull(), lastshader, loaded(), setslotparams(), and setvariant_().
void Shader::setvariant_ (int col, int row, Shader * fallbackshader) inline
References bindprograms(), detailshader, gle::end(), lastshader, inexor::rpc::min(), recorder::start(), variantrows, and variants.
Referenced by setvariant().
int Shader::uniformlocversion () static
References enumerate, loopvj, and shaders.
Referenced by skelmodel::skelcacheentry::nextversion().
Member Data Documentation
Shader * Shader::altshader
Referenced by altshader(), and fixdetailshader().
vector<AttribLoc> Shader::attriblocs
Referenced by genattriblocs(), linkglslprogram(), and newshader().
vector<SlotShaderParamState> Shader::defaultparams
Referenced by findslotparam(), linkglslprogram(), linkslotshaderparams(), newshader(), setglsluniformformat(), and variantshader().
char * Shader::defer
Referenced by defershader(), newshader(), and ~Shader().
Shader* Shader::detailshader
Referenced by fixshaderdetail(), hasoption(), linkslotshader(), linkvslotshader(), loaded(), set_(), setvariant(), setvariant_(), and useshaderbyname().
Shader * Shader::fastshader[MAXSHADERDETAIL]
Referenced by fastshader(), fixdetailshader(), and Shader().
bool Shader::forced
Referenced by newshader(), and useshaderbyname().
vector<GlobalShaderParamUse> Shader::globalparams
Referenced by addglobalparam(), flushparams(), and setglsluniformformat().
Shader * Shader::lastshader = nullptr static
Referenced by cleanupshaders(), flushhudmatrix(), skelmodel::skeleton::getblendoffset(), newshader(), LocalShaderParam::resolve(), set(), set_(), setcamprojmatrix(), skelmodel::skeleton::setgpubones(), animmodel::skin::setshaderparams(), setvariant(), and setvariant_().
vector<uchar> Shader::localparamremap
Referenced by addlocalparam(), and LocalShaderParam::resolve().
vector<LocalShaderParamState> Shader::localparams
Referenced by addlocalparam(), LocalShaderParam::resolve(), and setglsluniformformat().
char* Shader::name
Referenced by defershader(), linkglslprogram(), newshader(), shader(), and ~Shader().
const void* Shader::owner
Referenced by animmodel::skin::setshaderparams().
GLuint Shader::program
Referenced by allocglslactiveuniforms(), bindglsluniform(), linkglslprogram(), and setglsluniformformat().
GLuint Shader::psobj
Referenced by linkglslprogram().
char * Shader::psstr
Referenced by newshader(), and ~Shader().
Shader * Shader::reuseps
Referenced by newshader(), and reloadshaders().
Shader* Shader::reusevs
Referenced by newshader(), and reloadshaders().
bool Shader::standard
Referenced by animmodel::skin::cleanup(), defershader(), and newshader().
int Shader::type
Referenced by changebatchtmus(), changeslottmus(), deferred(), defershader(), gencubeverts(), gendynlightvariant(), gengenericvariant(), genmergedfaces(), genshadowmapvariant(), genwatervariant(), hasoption(), invalid(), newshader(), previewblends(), vacollect::remapunlit(), vacollect::setupdata(), and setupsurfaces().
vector<UniformLoc> Shader::uniformlocs
Referenced by genuniformlocs(), linkglslprogram(), newshader(), setglsluniformformat(), and skelmodel::skeleton::setgpubones().
bool Shader::used
Referenced by flushparams().
ushort* Shader::variantrows
Referenced by addvariant(), getvariant(), numvariants(), setvariant_(), and ~Shader().
vector<Shader *> Shader::variants
Referenced by addvariant(), getvariant(), reloadshaders(), and setvariant_().
Shader * Shader::variantshader
Referenced by newshader().
GLuint Shader::vsobj
Referenced by linkglslprogram().
char * Shader::vsstr
Referenced by newshader(), and ~Shader().
The documentation for this struct was generated from the following files:
inexor/engine/shader.hpp
inexor/engine/shader.cpp