Inexor: game::clientmode Struct Reference
game::clientmode Struct Reference abstract
#include <gamemode_client.hpp>
Public Member Functions
virtual ~clientmode ()
virtual void preload ()
virtual int clipconsole (int w, int h)
virtual void drawhud (fpsent *d, int w, int h)
virtual bool isinvisible (fpsent *d)
virtual void rendergame ()
virtual void respawned (fpsent *d)
virtual void setup ()
virtual void checkitems (fpsent *d)
virtual int respawnwait (fpsent *d)
virtual void pickspawn (fpsent *d)
virtual void senditems (packetbuf &p)
virtual void addplayer (fpsent *d)
virtual void removeplayer (fpsent *d)
virtual void gameover ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual void aifind (fpsent *d, ai::aistate &b, vector< ai::interest > &interests)
virtual bool aicheck (fpsent *d, ai::aistate &b)
virtual bool aidefend (fpsent *d, ai::aistate &b)
virtual bool aipursue (fpsent *d, ai::aistate &b)
virtual void killed (fpsent *d, fpsent *actor)
virtual void gameconnect (fpsent *d)
virtual void renderscoreboard (g3d_gui &g, scoregroup &sg, int fgcolor, int bgcolor)
virtual bool parse_network_message (int type, ucharbuf &p)=0
Parse game mode specific network messages.
Constructor & Destructor Documentation
virtual game::clientmode::~clientmode () inline virtual
Member Function Documentation
virtual void game::clientmode::addplayer (fpsent * d) inline virtual
virtual bool game::clientmode::aicheck (fpsent * d, ai::aistate & b) inline virtual
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::check().
virtual bool game::clientmode::aidefend (fpsent * d, ai::aistate & b) inline virtual
Reimplemented in game::ctfclientmode, and game::captureclientmode.
Referenced by ai::dodefend().
virtual void game::clientmode::aifind (fpsent * d, ai::aistate & b, vector< ai::interest > & interests) inline virtual
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::find().
virtual bool game::clientmode::aipursue (fpsent * d, ai::aistate & b) inline virtual
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::dopursue().
virtual void game::clientmode::checkitems (fpsent * d) inline virtual
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by ai::logic(), and game::updateworld().
virtual int game::clientmode::clipconsole (int w, int h) inline virtual
Reimplemented in game::captureclientmode, game::collectclientmode, and game::ctfclientmode.
Referenced by game::clipconsole().
virtual void game::clientmode::drawhud (fpsent * d, int w, int h) inline virtual
Reimplemented in game::captureclientmode, game::collectclientmode, game::ctfclientmode, game::bombclientmode, and game::hideandseekclientmode.
Referenced by game::gameplayhud().
virtual void game::clientmode::gameconnect (fpsent * d) inline virtual
Reimplemented in game::bombclientmode.
virtual void game::clientmode::gameover () inline virtual
Referenced by game::timeupdate().
virtual int game::clientmode::getteamscore (const char * team) inline virtual
Referenced by game::groupplayers().
virtual void game::clientmode::getteamscores (vector< teamscore > & scores) inline virtual
Referenced by game::getbestteams().
virtual bool game::clientmode::hidefrags () inline virtual
Reimplemented in game::hideandseekclientmode.
Referenced by game::getbestteams(), game::groupplayers(), game::parsemessages(), and game::renderscoreboard().
virtual bool game::clientmode::isinvisible (fpsent * d) inline virtual
Reimplemented in game::hideandseekclientmode.
Referenced by game::rendergame().
virtual void game::clientmode::killed (fpsent * d, fpsent * actor) inline virtual
Reimplemented in game::hideandseekclientmode, and game::bombclientmode.
Referenced by game::killed().
virtual bool game::clientmode::parse_network_message (int type, ucharbuf & p) pure virtual
Parse game mode specific network messages.
Returns
true if message got handled.
Implemented in game::ctfclientmode, game::captureclientmode, game::collectclientmode, game::hideandseekclientmode, and game::bombclientmode.
Referenced by game::parsemessages().
virtual void game::clientmode::pickspawn (fpsent * d) inline virtual
Reimplemented in game::ctfclientmode, game::collectclientmode, game::captureclientmode, game::hideandseekclientmode, and game::bombclientmode.
References findplayerspawn().
Referenced by game::parsemessages(), and game::spawnplayer().
virtual void game::clientmode::preload () inline virtual
Reimplemented in game::captureclientmode, game::collectclientmode, and game::ctfclientmode.
Referenced by game::startgame().
virtual void game::clientmode::removeplayer (fpsent * d) inline virtual
Reimplemented in game::ctfclientmode.
Referenced by game::clientdisconnected().
virtual void game::clientmode::rendergame () inline virtual
Reimplemented in game::ctfclientmode, game::collectclientmode, game::captureclientmode, game::bombclientmode, and game::hideandseekclientmode.
Referenced by game::rendergame().
virtual void game::clientmode::renderscoreboard (g3d_gui & g, scoregroup & sg, int fgcolor, int bgcolor) inline virtual
Reimplemented in game::bombclientmode, and game::hideandseekclientmode.
Referenced by game::renderscoreboard().
virtual void game::clientmode::respawned (fpsent * d) inline virtual
Reimplemented in game::ctfclientmode, game::hideandseekclientmode, and game::captureclientmode.
Referenced by game::parsemessages().
virtual int game::clientmode::respawnwait (fpsent * d) inline virtual
Reimplemented in game::ctfclientmode, game::collectclientmode, and game::captureclientmode.
Referenced by game::respawn(), and ai::think().
virtual void game::clientmode::senditems (packetbuf & p) inline virtual
Reimplemented in game::captureclientmode, game::ctfclientmode, game::collectclientmode, and game::bombclientmode.
Referenced by game::sendmessages().
virtual void game::clientmode::setup () inline virtual
Reimplemented in game::captureclientmode, game::ctfclientmode, game::collectclientmode, game::hideandseekclientmode, and game::bombclientmode.
Referenced by game::startgame().
The documentation for this struct was generated from the following file:
inexor/client/gamemode/gamemode_client.hpp