Inexor: server::captureservermode Struct Reference
server::captureservermode Struct Reference
#include <capture_server.hpp>
Public Member Functions
void reset (bool empty)
void cleanup () override
void setup () override
void newmap () override
void stealbase (int n, const char *team)
void replenishammo (clientinfo *ci)
void movebases (const char *team, const vec &oldpos, bool oldclip, const vec &newpos, bool newclip)
void leavebases (const char *team, const vec &o)
void enterbases (const char *team, const vec &o)
void addscore (int base, const char *team, int n)
void regenowners (baseinfo &b, int ticks)
void update () override
void sendbaseinfo (int i)
void sendbases ()
void initclient (clientinfo *ci, packetbuf &p, bool connecting) override
void endcheck ()
void entergame (clientinfo *ci) override
void spawned (clientinfo *ci) override
void leavegame (clientinfo *ci, bool disconnecting=false) override
void died (clientinfo *ci, clientinfo *actor) override
bool canspawn (clientinfo *ci, bool connecting) override
void moved (clientinfo *ci, const vec &oldpos, bool oldclip, const vec &newpos, bool newclip) override
void changeteam (clientinfo *ci, const char *oldteam, const char *newteam) override
void parsebases (ucharbuf &p, bool commit)
bool extinfoteam (const char *team, ucharbuf &p) override
bool parse_network_message (int type, clientinfo *ci, clientinfo *cq, packetbuf &p) override
process gamemode specific network messages.
virtual void connected (clientinfo *ci)
virtual int fragvalue (clientinfo *victim, clientinfo *actor)
virtual bool canhit (clientinfo *victim, clientinfo *actor)
virtual bool canchangeteam (clientinfo *ci, const char *oldteam, const char *newteam)
virtual void updatelimbo ()
virtual void intermission ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
void resetbases ()
bool hidefrags ()
int getteamscore (const char *team)
void getteamscores (vector< teamscore > &teamscores)
score & findscore (const char *team)
void addbase (int ammotype, const vec &o)
void initbase (int i, int ammotype, const char *owner, const char *enemy, int converted, int ammo)
bool hasbases (const char *team)
float disttoenemy (baseinfo &b)
bool insidebase (const baseinfo &b, const vec &o)
Public Attributes
bool notgotbases = false
vector< baseinfo > bases
vector< score > scores
int captures = 0
Static Public Attributes
static const int CAPTURERADIUS = 64
static const int CAPTUREHEIGHT = 24
static const int OCCUPYBONUS = 1
static const int OCCUPYPOINTS = 1
static const int OCCUPYENEMYLIMIT = 28
static const int OCCUPYNEUTRALLIMIT = 14
static const int SCORESECS = 10
static const int AMMOSECS = 15
static const int REGENSECS = 1
static const int REGENHEALTH = 10
static const int REGENARMOUR = 10
static const int REGENAMMO = 20
static const int MAXAMMO = 5
static const int REPAMMODIST = 32
static const int RESPAWNSECS = 10
static const int REGENRESPAWNSECS = 0
static const int MAXBASES = 100
Member Function Documentation
void capturemode_common::addbase (int ammotype, const vec & o) inline inherited
References capturemode_common::baseinfo::ammogroup, capturemode_common::baseinfo::ammotype, capturemode_common::bases, I_GRENADES, I_SHELLS, loopi(), loopj, capturemode_common::MAXBASES, inexor::rpc::min(), capturemode_common::baseinfo::o, and rnd().
Referenced by parsebases(), and setup().
void server::captureservermode::addscore (int base, const char * team, int n)
References capturemode_common::findscore(), N_BASESCORE, sendf(), and capturemode_common::score::total.
Referenced by update().
virtual bool server::servmode::canchangeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline virtual inherited
Reimplemented in server::hideandseekservermode, server::ctfservermode, server::collectservermode, and server::bombservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::canhit (clientinfo * victim, clientinfo * actor) inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::dodamage().
bool server::captureservermode::canspawn (clientinfo * ci, bool connecting) inline override virtual
Reimplemented from server::servmode.
References curtime, gamemillis, server::gamestate::lastdeath, m_regencapture, capturemode_common::REGENRESPAWNSECS, capturemode_common::RESPAWNSECS, and server::clientinfo::state.
void server::captureservermode::changeteam (clientinfo * ci, const char * oldteam, const char * newteam) override virtual
Reimplemented from server::servmode.
References enterbases(), server::clientinfo::gameclip, leavebases(), notgotbases, server::gamestate::o, and server::clientinfo::state.
void server::captureservermode::cleanup () inline override virtual
Reimplemented from server::servmode.
References reset().
virtual void server::servmode::connected (clientinfo * ci) inline virtual inherited
Reimplemented in server::hideandseekservermode.
void server::captureservermode::died (clientinfo * ci, clientinfo * actor) inline override virtual
Reimplemented from server::servmode.
References server::clientinfo::gameclip, leavebases(), notgotbases, server::gamestate::o, server::clientinfo::state, and server::clientinfo::team.
float capturemode_common::disttoenemy (baseinfo & b) inline inherited
References capturemode_common::bases, vec::dist(), loopv, inexor::rpc::min(), capturemode_common::baseinfo::o, and capturemode_common::baseinfo::owner.
void server::captureservermode::endcheck ()
References capturemode_common::bases, capturemode_common::findscore(), loopv, N_BASESCORE, capturemode_common::baseinfo::owner, sendf(), server::startintermission(), capturemode_common::score::total, and capturemode_common::baseinfo::valid().
Referenced by update().
void server::captureservermode::enterbases (const char * team, const vec & o) inline
References movebases().
Referenced by changeteam(), entergame(), and spawned().
void server::captureservermode::entergame (clientinfo * ci) inline override virtual
Reimplemented from server::servmode.
References CS_ALIVE, enterbases(), server::clientinfo::gameclip, notgotbases, server::gamestate::o, server::gamestate::state, server::clientinfo::state, and server::clientinfo::team.
Referenced by parsebases(), and setup().
bool server::captureservermode::extinfoteam (const char * team, ucharbuf & p) override virtual
Reimplemented from server::servmode.
References capturemode_common::bases, loopvj, and putint().
score& capturemode_common::findscore (const char * team) inline inherited
References copystring(), loopv, capturemode_common::scores, capturemode_common::score::team, and capturemode_common::score::total.
Referenced by addscore(), and endcheck().
virtual int server::servmode::fragvalue (clientinfo * victim, clientinfo * actor) inline virtual inherited
References isteam, and server::clientinfo::team.
Referenced by server::dodamage(), and server::suicide().
virtual int server::servmode::getteamscore (const char * team) inline virtual inherited
int capturemode_common::getteamscore (const char * team) inline inherited
References loopv, capturemode_common::scores, capturemode_common::score::team, and capturemode_common::score::total.
virtual void server::servmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by server::extinfoteams().
void capturemode_common::getteamscores (vector< teamscore > & teamscores) inline inherited
References vector< T, MINSIZE >::add(), loopv, and capturemode_common::scores.
bool capturemode_common::hasbases (const char * team) inline inherited
References capturemode_common::bases, loopv, and capturemode_common::baseinfo::owner.
virtual bool server::servmode::hidefrags () inline virtual inherited
Referenced by server::autoteam(), server::chooseworstteam(), and server::extinfoteams().
bool capturemode_common::hidefrags () inline inherited
void capturemode_common::initbase (int i, int ammotype, const char * owner, const char * enemy, int converted, int ammo) inline inherited
References capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammotype, capturemode_common::bases, capturemode_common::baseinfo::converted, copystring(), capturemode_common::baseinfo::enemy, and capturemode_common::baseinfo::owner.
void server::captureservermode::initclient (clientinfo * ci, packetbuf & p, bool connecting) override virtual
Reimplemented from server::servmode.
References capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammotype, capturemode_common::bases, capturemode_common::baseinfo::converted, capturemode_common::baseinfo::enemy, loopv, N_BASES, N_BASESCORE, capturemode_common::baseinfo::owner, putint(), capturemode_common::scores, sendstring(), capturemode_common::score::team, and capturemode_common::score::total.
Referenced by sendbases().
bool capturemode_common::insidebase (const baseinfo & b, const vec & o) inline inherited
References capturemode_common::CAPTUREHEIGHT, capturemode_common::CAPTURERADIUS, and capturemode_common::baseinfo::o.
Referenced by movebases(), regenowners(), replenishammo(), and stealbase().
virtual void server::servmode::intermission () inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::checkintermission().
void server::captureservermode::leavebases (const char * team, const vec & o) inline
References movebases().
Referenced by changeteam(), died(), and leavegame().
void server::captureservermode::leavegame (clientinfo * ci, bool disconnecting = false) inline override virtual
Reimplemented from server::servmode.
References CS_ALIVE, server::clientinfo::gameclip, leavebases(), notgotbases, server::gamestate::o, server::gamestate::state, server::clientinfo::state, and server::clientinfo::team.
void server::captureservermode::movebases (const char * team, const vec & oldpos, bool oldclip, const vec & newpos, bool newclip)
References capturemode_common::bases, capturemode_common::baseinfo::enter(), server::gamelimit, gamemillis, capturemode_common::insidebase(), capturemode_common::baseinfo::leave(), loopv, sendbaseinfo(), capturemode_common::baseinfo::steal(), stealbase(), and capturemode_common::baseinfo::valid().
Referenced by enterbases(), leavebases(), and moved().
void server::captureservermode::moved (clientinfo * ci, const vec & oldpos, bool oldclip, const vec & newpos, bool newclip) inline override virtual
Reimplemented from server::servmode.
References movebases(), notgotbases, and server::clientinfo::team.
void server::captureservermode::newmap () inline override virtual
Reimplemented from server::servmode.
References reset().
bool server::captureservermode::parse_network_message (int type, clientinfo * ci, clientinfo * cq, packetbuf & p) override virtual
process gamemode specific network messages.
Parameters
type the N_ network message type
ci the sender.
cq the currently focused player (sender or bot from senders pc)
p the network packet containing the data
Returns
whether this messages got processed.
Implements server::servmode.
References server::clientinfo::clientmap, CS_SPECTATOR, N_BASES, N_REPAMMO, parsebases(), server::clientinfo::privilege, replenishammo(), server::smapname, server::gamestate::state, and server::clientinfo::state.
void server::captureservermode::parsebases (ucharbuf & p, bool commit)
References capturemode_common::addbase(), server::clients, CS_ALIVE, DMF, entergame(), f(), getint(), GUN_PISTOL, GUN_SG, loopi(), loopk, loopv, inexor::rpc::max(), inexor::rpc::min(), notgotbases, databuf< T >::overread(), sendbases(), and recorder::state.
Referenced by parse_network_message().
void server::captureservermode::regenowners (capturemode_common::baseinfo & b, int ticks)
References A_GREEN, fpsstate::addammo(), fpsstate::ammo, capturemode_common::baseinfo::ammotype, fpsstate::armour, fpsstate::armourtype, server::clientinfo::clientnum, server::clients, CS_ALIVE, fpsstate::hasmaxammo(), fpsstate::health, I_GREENARMOUR, I_SHELLS, capturemode_common::insidebase(), itemstats, loopv, itemstat::max, fpsstate::maxhealth, inexor::rpc::min(), N_BASEREGEN, server::gamestate::o, capturemode_common::baseinfo::owner, capturemode_common::REGENAMMO, capturemode_common::REGENARMOUR, capturemode_common::REGENHEALTH, sendf(), server::gamestate::state, server::clientinfo::state, server::clientinfo::team, and capturemode_common::baseinfo::valid().
Referenced by update().
void server::captureservermode::replenishammo (clientinfo * ci)
References fpsstate::addammo(), capturemode_common::baseinfo::ammotype, capturemode_common::bases, server::clientinfo::clientnum, CS_ALIVE, fpsstate::hasmaxammo(), I_SHELLS, capturemode_common::insidebase(), loopv, m_noitems, N_REPAMMO, notgotbases, server::gamestate::o, sendbaseinfo(), sendf(), server::gamestate::state, server::clientinfo::state, capturemode_common::baseinfo::takeammo(), server::clientinfo::team, and capturemode_common::baseinfo::valid().
Referenced by parse_network_message().
void server::captureservermode::reset (bool empty) inline
References notgotbases, and capturemode_common::resetbases().
Referenced by cleanup(), newmap(), and setup().
void capturemode_common::resetbases () inline inherited
References capturemode_common::bases, capturemode_common::captures, and capturemode_common::scores.
Referenced by reset().
void server::captureservermode::sendbaseinfo (int i)
References capturemode_common::baseinfo::ammo, capturemode_common::bases, capturemode_common::baseinfo::converted, capturemode_common::baseinfo::enemy, N_BASEINFO, capturemode_common::baseinfo::owner, and sendf().
Referenced by movebases(), replenishammo(), stealbase(), and update().
void server::captureservermode::sendbases ()
References packetbuf::finalize(), initclient(), MAXTRANS, and sendpacket().
Referenced by parsebases(), and setup().
void server::captureservermode::setup () override virtual
Reimplemented from server::servmode.
References capturemode_common::addbase(), entity::attr1, BASE, server::clients, CS_ALIVE, entergame(), loopv, server::ments, notgotbases, server::notgotitems, entity::o, reset(), sendbases(), recorder::state, and entity::type.
void server::captureservermode::spawned (clientinfo * ci) inline override virtual
Reimplemented from server::servmode.
References enterbases(), server::clientinfo::gameclip, notgotbases, server::gamestate::o, server::clientinfo::state, and server::clientinfo::team.
void server::captureservermode::stealbase (int n, const char * team)
References capturemode_common::bases, server::clients, CS_ALIVE, capturemode_common::baseinfo::enter(), capturemode_common::insidebase(), loopv, server::gamestate::o, sendbaseinfo(), server::gamestate::state, server::clientinfo::state, and server::clientinfo::team.
Referenced by movebases().
void server::captureservermode::update () override virtual
Reimplemented from server::servmode.
References capturemode_common::baseinfo::addammo(), addscore(), capturemode_common::AMMOSECS, capturemode_common::bases, capturemode_common::baseinfo::capturetime, curtime, endcheck(), capturemode_common::baseinfo::enemies, capturemode_common::baseinfo::enemy, server::gamelimit, gamemillis, loopv, m_regencapture, capturemode_common::baseinfo::occupy(), capturemode_common::OCCUPYBONUS, capturemode_common::OCCUPYPOINTS, capturemode_common::baseinfo::owner, capturemode_common::baseinfo::owners, regenowners(), capturemode_common::REGENSECS, capturemode_common::SCORESECS, sendbaseinfo(), anonymous_namespace{utilTest.cpp}::t(), and capturemode_common::baseinfo::valid().
virtual void server::servmode::updatelimbo () inline virtual inherited
Reimplemented in server::bombservermode.
Referenced by server::serverupdate().
Member Data Documentation
const int capturemode_common::AMMOSECS = 15 static inherited
Referenced by update().
vector<baseinfo> capturemode_common::bases inherited
Referenced by capturemode_common::addbase(), capturemode_common::disttoenemy(), endcheck(), extinfoteam(), capturemode_common::hasbases(), capturemode_common::initbase(), initclient(), movebases(), replenishammo(), capturemode_common::resetbases(), sendbaseinfo(), stealbase(), and update().
const int capturemode_common::CAPTUREHEIGHT = 24 static inherited
Referenced by capturemode_common::insidebase().
const int capturemode_common::CAPTURERADIUS = 64 static inherited
Referenced by capturemode_common::insidebase().
int capturemode_common::captures = 0 inherited
Referenced by capturemode_common::resetbases().
const int capturemode_common::MAXAMMO = 5 static inherited
Referenced by capturemode_common::baseinfo::addammo().
const int capturemode_common::MAXBASES = 100 static inherited
Referenced by capturemode_common::addbase().
bool server::captureservermode::notgotbases = false
Referenced by changeteam(), died(), entergame(), leavegame(), moved(), parsebases(), replenishammo(), reset(), setup(), and spawned().
const int capturemode_common::OCCUPYBONUS = 1 static inherited
Referenced by update().
const int capturemode_common::OCCUPYENEMYLIMIT = 28 static inherited
Referenced by capturemode_common::baseinfo::occupy().
const int capturemode_common::OCCUPYNEUTRALLIMIT = 14 static inherited
Referenced by capturemode_common::baseinfo::occupy().
const int capturemode_common::OCCUPYPOINTS = 1 static inherited
Referenced by update().
const int capturemode_common::REGENAMMO = 20 static inherited
Referenced by regenowners().
const int capturemode_common::REGENARMOUR = 10 static inherited
Referenced by regenowners().
const int capturemode_common::REGENHEALTH = 10 static inherited
Referenced by regenowners().
const int capturemode_common::REGENRESPAWNSECS = 0 static inherited
Referenced by canspawn(), and game::captureclientmode::respawnwait().
const int capturemode_common::REGENSECS = 1 static inherited
Referenced by update().
const int capturemode_common::REPAMMODIST = 32 static inherited
const int capturemode_common::RESPAWNSECS = 10 static inherited
Referenced by canspawn(), and game::captureclientmode::respawnwait().
vector<score> capturemode_common::scores inherited
Referenced by capturemode_common::findscore(), capturemode_common::getteamscore(), capturemode_common::getteamscores(), initclient(), and capturemode_common::resetbases().
const int capturemode_common::SCORESECS = 10 static inherited
Referenced by update().
The documentation for this struct was generated from the following files:
inexor/server/gamemode/capture_server.hpp
inexor/server/gamemode/capture_server.cpp