Inexor: ai::wpcache::node Struct Reference
ai::wpcache::node Struct Reference
Public Member Functions
int axis () const
int childindex (int which) const
bool isleaf (int which) const
Public Attributes
float split [2]
uint child [2]
Member Function Documentation
int ai::wpcache::node::axis () const inline
Referenced by ai::avoidset::avoidnear(), ai::closestwaypoint(), and ai::findwaypointswithin().
int ai::wpcache::node::childindex (int which) const inline
Referenced by ai::avoidset::avoidnear(), ai::closestwaypoint(), and ai::findwaypointswithin().
bool ai::wpcache::node::isleaf (int which) const inline
Referenced by ai::avoidset::avoidnear(), ai::closestwaypoint(), and ai::findwaypointswithin().
Member Data Documentation
uint ai::wpcache::node::child[2]
Referenced by ai::wpcache::build().
float ai::wpcache::node::split[2]
Referenced by ai::avoidset::avoidnear(), ai::wpcache::build(), ai::closestwaypoint(), and ai::findwaypointswithin().
The documentation for this struct was generated from the following file:
inexor/fpsgame/waypoint.cpp