Inexor: gzstream Struct Reference
gzstream Struct Reference
Public Types
enum { MAGIC1 = 0x1F, MAGIC2 = 0x8B, BUFSIZE = 16384, OS_UNIX = 0x03 }
enum {
F_ASCII = 0x01, F_CRC = 0x02, F_EXTRA = 0x04, F_NAME = 0x08,
F_COMMENT = 0x10, F_RESERVED = 0xE0
}
typedef off_t offset
Public Member Functions
gzstream ()
~gzstream () override
void writeheader ()
void readbuf (size_t size=BUFSIZE)
uchar readbyte (size_t size=BUFSIZE)
void skipbytes (size_t n)
bool checkheader ()
bool open (stream *f, const char *mode, bool needclose, int level)
uint getcrc () override
void finishreading ()
void stopreading ()
void finishwriting ()
void stopwriting ()
void close () override
bool end () override
offset tell () override
offset rawtell () override
offset size () override
offset rawsize () override
bool seek (offset pos, int whence) override
size_t read (void *buf, size_t len) override
bool flushbuf (bool full=false)
bool flush () override
size_t write (const void *buf, size_t len) override
virtual int getchar ()
virtual bool putchar (int n)
virtual bool getline (char *str, size_t len)
virtual bool putstring (const char *str)
virtual bool putline (const char *str)
virtual size_t printf (const char *fmt,...) PRINTFARGS(2
template<class T >
size_t put (const T *v, size_t n)
template<class T >
bool put (T n)
template<class T >
bool putlil (T n)
template<class T >
bool putbig (T n)
template<class T >
size_t get (T *v, size_t n)
template<class T >
T get ()
template<class T >
T getlil ()
template<class T >
T getbig ()
Public Attributes
stream * file
z_stream zfile
uchar * buf
bool reading
bool writing
bool autoclose
uint crc
size_t headersize
Member Typedef Documentation
typedef off_t stream::offset inherited
Member Enumeration Documentation
anonymous enum
Enumerator
MAGIC1
MAGIC2
BUFSIZE
OS_UNIX
anonymous enum
Enumerator
F_ASCII
F_CRC
F_EXTRA
F_NAME
F_COMMENT
F_RESERVED
Constructor & Destructor Documentation
gzstream::gzstream () inline
References zfile.
gzstream::~gzstream () inline override
References close().
Member Function Documentation
bool gzstream::checkheader () inline
References stream::end(), F_COMMENT, F_CRC, F_EXTRA, F_NAME, F_RESERVED, file, hmap::flags, headersize, MAGIC1, MAGIC2, readbuf(), readbyte(), skipbytes(), stream::tell(), and zfile.
Referenced by open().
void gzstream::close () inline override virtual
Implements stream.
References autoclose, buf, DELETEA, DELETEP, file, finishreading(), finishwriting(), reading, stopreading(), stopwriting(), and writing.
Referenced by ~gzstream().
bool gzstream::end () inline override virtual
Implements stream.
References reading, and writing.
void gzstream::finishreading () inline
References crc, inexor::util::log_manager::io, Log, loopi(), readbyte(), reading, and zfile.
Referenced by close(), and read().
void gzstream::finishwriting () inline
References crc, file, flushbuf(), stream::write(), writing, and zfile.
Referenced by close().
bool gzstream::flush () inline override virtual
Reimplemented from stream.
References flushbuf().
bool gzstream::flushbuf (bool full = false) inline
References buf, BUFSIZE, file, stream::flush(), stream::write(), and zfile.
Referenced by finishwriting(), flush(), and write().
template<class T > size_t stream::get (T * v, size_t n) inline inherited
References stream::read().
Referenced by streambuf< T >::get().
template<class T > T stream::get () inline inherited
References stream::read().
template<class T > T stream::getbig () inline inherited
References bigswap().
virtual int stream::getchar () inline virtual inherited
Reimplemented in filestream.
References stream::read().
Referenced by load_world(), loadblendmap(), loadc(), loadents(), loadviewcells(), and ai::loadwaypoints().
uint gzstream::getcrc () inline override virtual
Reimplemented from stream.
References crc.
template<class T > T stream::getlil () inline inherited
References lilswap().
Referenced by load_world(), loadc(), loadents(), loadpvs(), loadviewcells(), loadvslot(), loadvslots(), ai::loadwaypoints(), and size().
bool stream::getline (char * str, size_t len) virtual inherited
Reimplemented in utf8stream, and filestream.
References loopi(), and stream::read().
Referenced by obj::objmeshgroup::load(), md5::md5mesh::load(), md5::md5meshgroup::loadanim(), smd::smdmeshgroup::loadanim(), loadhistory(), md5::md5meshgroup::loadmesh(), smd::smdmeshgroup::loadmesh(), editline::read(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readnodes(), smd::smdmeshgroup::readskeleton(), smd::smdmeshgroup::readtriangles(), and smd::smdmeshgroup::skipsection().
bool gzstream::open (stream * f, const char * mode, bool needclose, int level) inline
References autoclose, buf, BUFSIZE, checkheader(), crc, f(), file, inexor::rpc::min(), reading, stopreading(), writeheader(), writing, and zfile.
Referenced by opengzfile().
size_t stream::printf (const char * fmt, ...) virtual inherited
Reimplemented in filestream.
References _vsnprintf, and stream::write().
Referenced by writebinds(), writecfg(), game::writeclientinfo(), writecompletions(), writecrosshairs(), writeinitcfg(), and writeobj().
template<class T > size_t stream::put (const T * v, size_t n) inline inherited
References stream::write().
Referenced by streambuf< T >::put().
template<class T > bool stream::put (T n) inline inherited
References stream::write().
template<class T > bool stream::putbig (T n) inline inherited
References bigswap().
Referenced by savepng(), and writepngchunk().
virtual bool stream::putchar (int n) inline virtual inherited
Reimplemented in filestream.
References stream::write().
Referenced by stream::putline(), save_world(), saveblendmap(), savec(), savetga(), saveviewcells(), and ai::savewaypoints().
template<class T > bool stream::putlil (T n) inline inherited
References lilswap().
Referenced by save_world(), savec(), savepvs(), saveviewcells(), savevslot(), savevslots(), and ai::savewaypoints().
virtual bool stream::putline (const char * str) inline virtual inherited
References stream::putchar(), and stream::putstring().
Referenced by editor::save(), and writehistory().
virtual bool stream::putstring (const char * str) inline virtual inherited
Reimplemented in filestream.
References stream::write().
Referenced by stream::putline().
offset gzstream::rawsize () inline override virtual
Reimplemented from stream.
References file, and stream::size().
offset gzstream::rawtell () inline override virtual
Reimplemented from stream.
References file, and stream::tell().
size_t gzstream::read (void * buf, size_t len) inline override virtual
Reimplemented from stream.
References BUFSIZE, crc, finishreading(), readbuf(), reading, stopreading(), and zfile.
Referenced by seek().
void gzstream::readbuf (size_t size = BUFSIZE) inline
References buf, BUFSIZE, file, inexor::rpc::min(), stream::read(), and zfile.
Referenced by checkheader(), read(), and readbyte().
uchar gzstream::readbyte (size_t size = BUFSIZE) inline
References readbuf(), and zfile.
Referenced by checkheader(), and finishreading().
bool gzstream::seek (offset pos, int whence) inline override virtual
Reimplemented from stream.
References buf, crc, headersize, inexor::rpc::min(), read(), reading, stopreading(), writing, and zfile.
offset gzstream::size () inline override virtual
Reimplemented from stream.
References file, stream::getlil(), stream::seek(), and tell().
void gzstream::skipbytes (size_t n) inline
References file, inexor::rpc::min(), stream::seek(), and zfile.
Referenced by checkheader().
void gzstream::stopreading () inline
References reading, and zfile.
Referenced by close(), open(), read(), and seek().
void gzstream::stopwriting () inline
References writing, and zfile.
Referenced by close(), and write().
offset gzstream::tell () inline override virtual
Reimplemented from stream.
References reading, writing, and zfile.
Referenced by size().
size_t gzstream::write (const void * buf, size_t len) inline override virtual
Reimplemented from stream.
References crc, flushbuf(), stopwriting(), writing, and zfile.
void gzstream::writeheader () inline
References file, MAGIC1, MAGIC2, OS_UNIX, and stream::write().
Referenced by open().
Member Data Documentation
bool gzstream::autoclose
Referenced by close(), and open().
uchar* gzstream::buf
Referenced by close(), flushbuf(), open(), readbuf(), and seek().
uint gzstream::crc
Referenced by finishreading(), finishwriting(), getcrc(), open(), read(), seek(), and write().
stream* gzstream::file
Referenced by checkheader(), close(), finishwriting(), flushbuf(), open(), rawsize(), rawtell(), readbuf(), size(), skipbytes(), and writeheader().
size_t gzstream::headersize
Referenced by checkheader(), and seek().
bool gzstream::reading
Referenced by close(), end(), finishreading(), open(), read(), seek(), stopreading(), and tell().
bool gzstream::writing
Referenced by close(), end(), finishwriting(), open(), seek(), stopwriting(), tell(), and write().
z_stream gzstream::zfile
Referenced by checkheader(), finishreading(), finishwriting(), flushbuf(), gzstream(), open(), read(), readbuf(), readbyte(), seek(), skipbytes(), stopreading(), stopwriting(), tell(), and write().
The documentation for this struct was generated from the following file:
inexor/io/legacy/stream.cpp