Inexor: lightningrenderer Struct Reference
lightningrenderer Struct Reference
#include <lightning.hpp>
Public Member Functions
lightningrenderer ()
void startrender () override
void endrender () override
void update () override
void seedemitter (particleemitter &pe, const vec &o, const vec &d, int fade, float size, int gravity) override
void renderpart (listparticle *p, const vec &o, const vec &d, int blend, int ts) override
virtual void killpart (listparticle *p)
void reset () override
void resettracked (physent *owner) override
particle * addpart (const vec &o, const vec &d, int fade, int color, float size, int gravity) override
int count () override
bool haswork () override
void render () override
virtual void init (int n)
virtual int adddepthfx (vec &bbmin, vec &bbmax)
virtual void cleanup ()
void calc (particle *p, int &blend, int &ts, vec &o, vec &d, bool step=true)
const char * debuginfo ()
Public Attributes
listparticle * list
Texture * tex
const char * texname
int texclamp
uint type
int collide
string info
Static Public Attributes
static listparticle * parempty = nullptr
Constructor & Destructor Documentation
lightningrenderer::lightningrenderer () inline
Member Function Documentation
virtual int partrenderer::adddepthfx (vec & bbmin, vec & bbmax) inline virtual inherited
Referenced by finddepthfxranges().
particle * listrenderer::addpart (const vec & o, const vec & d, int fade, int color, float size, int gravity) override virtual inherited
Implements partrenderer.
References particle::color, particle::d, hmap::d, emitoffset, particle::fade, particle::flags, particle::gravity, lastmillis, loopi(), particle::millis, listparticle::next, particle::o, and particle::size.
void partrenderer::calc (particle * p, int & blend, int & ts, vec & o, vec & d, bool step = true) inherited
References vec::add(), adddecal(), mpr::collide(), COLLIDEERROR, COLLIDERADIUS, particle::color, particle::d, f(), particle::fade, particle::flags, particle::gravity, lastmillis, inexor::rpc::max(), particle::millis, vec::normalize(), particle::o, game::particletrack(), PT_RND4, PT_TRACK, RAY_CLIPMAT, rayfloor(), particle::size, vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
virtual void partrenderer::cleanup () inline virtual inherited
Reimplemented in varenderer< T >, and fireballrenderer.
Referenced by cleanupparticles().
int listrenderer::count () override virtual inherited
Implements partrenderer.
References listparticle::next.
const char * partrenderer::debuginfo () inherited
References mpr::collide(), concatstring(), concformatstring(), formatstring(), partnames, PT_FLIP, PT_GLARE, PT_LERP, PT_MOD, PT_RND4, and PT_SOFT.
Referenced by renderparticles().
void lightningrenderer::endrender () inline override virtual
Implements listrenderer.
bool listrenderer::haswork () override virtual inherited
Implements partrenderer.
virtual void partrenderer::init (int n) inline virtual inherited
Reimplemented in varenderer< T >.
Referenced by particleinit().
virtual void listrenderer::killpart (listparticle * p) inline virtual inherited
Reimplemented in textrenderer.
void listrenderer::render () override virtual inherited
Implements partrenderer.
References canstep, hmap::d, and textureload().
void lightningrenderer::renderpart (listparticle * p, const vec & o, const vec & d, int blend, int ts) inline override virtual
Implements listrenderer.
References gle::color(), particle::color, inexor::rpc::min(), PT_MOD, renderlightning(), particle::size, partrenderer::tex, and partrenderer::type.
void listrenderer::reset () override virtual inherited
Implements partrenderer.
References listparticle::next.
void listrenderer::resettracked (physent * owner) override virtual inherited
Reimplemented from partrenderer.
References cur, and PT_TRACK.
void lightningrenderer::seedemitter (particleemitter & pe, const vec & o, const vec & d, int fade, float size, int gravity) inline override virtual
Reimplemented from partrenderer.
References particleemitter::extendbb(), inexor::rpc::max(), and particleemitter::maxfade.
void lightningrenderer::startrender () inline override virtual
Implements listrenderer.
References gle::ATTRIB_TEXCOORD0, gle::ATTRIB_VERTEX, and gle::defattrib().
void lightningrenderer::update () inline override virtual
Reimplemented from partrenderer.
References setuplightning().
Member Data Documentation
int partrenderer::collide inherited
Referenced by fireballrenderer::finddepthfxranges(), regularshape(), and splash().
string partrenderer::info inherited
listparticle* listrenderer::list inherited
Referenced by fireballrenderer::finddepthfxranges().
listparticle * listrenderer::parempty = nullptr static inherited
Texture* partrenderer::tex inherited
Referenced by flarerenderer::render(), and renderpart().
int partrenderer::texclamp inherited
const char* partrenderer::texname inherited
Referenced by flarerenderer::render().
uint partrenderer::type inherited
Referenced by fireballrenderer::finddepthfxranges(), finddepthfxranges(), regularshape(), renderpart(), and renderparticles().
The documentation for this struct was generated from the following file:
inexor/engine/lightning.hpp