Inexor: LocalShaderParam Struct Reference
LocalShaderParam Struct Reference
#include <shader.hpp>
Public Member Functions
LocalShaderParam (const char *name)
LocalShaderParamState * resolve ()
void setf (float x=0, float y=0, float z=0, float w=0)
void set (const vec &v, float w=0)
void set (const vec2 &v, float z=0, float w=0)
void set (const vec4 &v)
void set (const plane &p)
void setv (const float *f, int n=1)
void setv (const vec *v, int n=1)
void setv (const vec2 *v, int n=1)
void setv (const vec4 *v, int n=1)
void setv (const plane *p, int n=1)
void setv (const matrix2 *m, int n=1)
void setv (const matrix3 *m, int n=1)
void setv (const matrix4 *m, int n=1)
void set (const matrix2 &m)
void set (const matrix3 &m)
void set (const matrix4 &m)
template<class T >
void sett (T x, T y, T z, T w)
void seti (int x=0, int y=0, int z=0, int w=0)
void set (const ivec &v, int w=0)
void set (const ivec2 &v, int z=0, int w=0)
void set (const ivec4 &v)
void setv (const int *i, int n=1)
void setv (const ivec *v, int n=1)
void setv (const ivec2 *v, int n=1)
void setv (const ivec4 *v, int n=1)
Public Attributes
const char * name
int loc
Constructor & Destructor Documentation
LocalShaderParam::LocalShaderParam (const char * name) inline
Member Function Documentation
LocalShaderParamState* LocalShaderParam::resolve () inline
References getlocalparam(), vector< T, MINSIZE >::inrange(), Shader::lastshader, loc, Shader::localparamremap, Shader::localparams, and name.
Referenced by setf(), sett(), and setv().
void LocalShaderParam::set (const vec & v, float w = 0) inline
References setf().
void LocalShaderParam::set (const vec2 & v, float z = 0, float w = 0) inline
References setf().
void LocalShaderParam::set (const vec4 & v) inline
References setf().
void LocalShaderParam::set (const plane & p) inline
References plane::offset, and setf().
void LocalShaderParam::set (const matrix2 & m) inline
References setv().
void LocalShaderParam::set (const matrix3 & m) inline
References setv().
void LocalShaderParam::set (const matrix4 & m) inline
References setv().
void LocalShaderParam::set (const ivec & v, int w = 0) inline
References seti().
void LocalShaderParam::set (const ivec2 & v, int z = 0, int w = 0) inline
References seti().
void LocalShaderParam::set (const ivec4 & v) inline
References seti().
void LocalShaderParam::setf (float x = 0, float y = 0, float z = 0, float w = 0) inline
References ShaderParamBinding::format, glUniform1f_, glUniform1i_, glUniform2f_, glUniform2i_, glUniform3f_, glUniform3i_, glUniform4f_, glUniform4i_, ShaderParamBinding::loc, and resolve().
Referenced by set(), and setscreentexcoord().
void LocalShaderParam::seti (int x = 0, int y = 0, int z = 0, int w = 0) inline
Referenced by set().
template<class T > void LocalShaderParam::sett (T x, T y, T z, T w) inline
References ShaderParamBinding::format, glUniform1f_, glUniform1i_, glUniform2f_, glUniform2i_, glUniform3f_, glUniform3i_, glUniform4f_, glUniform4i_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const float * f, int n = 1) inline
References glUniform1fv_, ShaderParamBinding::loc, and resolve().
Referenced by set().
void LocalShaderParam::setv (const vec * v, int n = 1) inline
References glUniform3fv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const vec2 * v, int n = 1) inline
References glUniform2fv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const vec4 * v, int n = 1) inline
References glUniform4fv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const plane * p, int n = 1) inline
References glUniform4fv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const matrix2 * m, int n = 1) inline
References matrix2::a, glUniformMatrix2fv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const matrix3 * m, int n = 1) inline
References matrix3::a, glUniformMatrix3fv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const matrix4 * m, int n = 1) inline
References matrix4::a, glUniformMatrix4fv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const int * i, int n = 1) inline
References glUniform1iv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const ivec * v, int n = 1) inline
References glUniform3iv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const ivec2 * v, int n = 1) inline
References glUniform2iv_, ShaderParamBinding::loc, and resolve().
void LocalShaderParam::setv (const ivec4 * v, int n = 1) inline
References glUniform4iv_, ShaderParamBinding::loc, and resolve().
Member Data Documentation
int LocalShaderParam::loc
Referenced by resolve().
const char* LocalShaderParam::name
Referenced by resolve().
The documentation for this struct was generated from the following file:
inexor/engine/shader.hpp