Inexor: queryframe Struct Reference
queryframe Struct Reference
Public Member Functions
queryframe ()
void flip ()
occludequery * newquery (void *owner)
void reset ()
void cleanup ()
Public Attributes
int cur
int max
occludequery queries [MAXQUERY]
Constructor & Destructor Documentation
queryframe::queryframe () inline
Member Function Documentation
void queryframe::cleanup () inline
References cur, glDeleteQueries_, loopi(), max, occludequery::owner, and queries.
Referenced by clearqueries().
void queryframe::flip () inline
References cur, loopi(), occludequery::owner, and queries.
Referenced by flipqueries().
occludequery* queryframe::newquery (void * owner) inline
References cur, occludequery::fragments, glGenQueries_, max, MAXQUERY, occludequery::owner, and queries.
Referenced by newquery().
void queryframe::reset () inline
References loopi(), max, occludequery::owner, and queries.
Referenced by resetqueries().
Member Data Documentation
int queryframe::cur
Referenced by cleanup(), flip(), getnumqueries(), and newquery().
int queryframe::max
Referenced by cleanup(), newquery(), and reset().
occludequery queryframe::queries[MAXQUERY]
Referenced by cleanup(), flip(), newquery(), and reset().
The documentation for this struct was generated from the following file:
inexor/engine/renderva.cpp