Inexor: undoblock Struct Reference
undoblock Struct Reference
#include <octree.hpp>
Public Member Functions
block3 * block ()
uchar * gridmap ()
undoent * ents ()
Public Attributes
undoblock * prev
undoblock * next
int size
int timestamp
int numents
Member Function Documentation
block3* undoblock::block () inline
Referenced by freeundo(), gridmap(), packundo(), pasteundo(), swapundo(), and undosize().
undoent* undoblock::ents () inline
Referenced by copyundoents(), packundo(), and pasteundoents().
uchar* undoblock::gridmap () inline
References block(), block3::c(), and block3::size().
Referenced by newundocube(), packundo(), and pasteundo().
Member Data Documentation
undoblock * undoblock::next
Referenced by undolist::add(), compacteditvslots(), undolist::popfirst(), and undolist::poplast().
int undoblock::numents
Referenced by copyundoents(), freeundo(), newundocube(), newundoent(), packundo(), pasteundo(), pasteundoents(), swapundo(), and undosize().
undoblock* undoblock::prev
Referenced by undolist::add(), undolist::popfirst(), and undolist::poplast().
int undoblock::size
Referenced by addundo(), pruneundos(), and swapundo().
int undoblock::timestamp
Referenced by addundo(), and swapundo().
The documentation for this struct was generated from the following file:
inexor/engine/octree.hpp