Inexor: hashbase< H, E, K, T > Struct Template Reference
hashbase< H, E, K, T > Struct Template Reference
#include <cube_hash.hpp>
Classes
struct chain
struct chainchunk
Public Types
enum { CHUNKSIZE = 64 }
enum { DEFAULTSIZE = 1<<10 }
typedef E elemtype
typedef K keytype
typedef T datatype
Public Member Functions
hashbase (int size=DEFAULTSIZE)
~hashbase ()
chain * insert (uint h)
template<class U >
T & insert (uint h, const U &key)
template<class U >
T * access (const U &key)
template<class U , class V >
T & access (const U &key, const V &elem)
template<class U >
T & operator[] (const U &key)
template<class U >
T & find (const U &key, T &notfound)
template<class U >
const T & find (const U &key, const T &notfound)
template<class U >
bool remove (const U &key)
void deletechunks ()
void clear ()
Static Public Member Functions
static chain * enumnext (void *i)
static K & enumkey (void *i)
static T & enumdata (void *i)
Public Attributes
int size
int numelems
chain ** chains
chainchunk * chunks
chain * unused
Class Documentation
struct hashbase::chain
template<class H, class E, class K, class T>
struct hashbase< H, E, K, T >::chain
Class Members
E elem
chain * next
struct hashbase::chainchunk
template<class H, class E, class K, class T>
struct hashbase< H, E, K, T >::chainchunk
Class Members
chain chains[CHUNKSIZE]
chainchunk * next
Member Typedef Documentation
template<class H, class E, class K, class T> typedef T hashbase< H, E, K, T >::datatype
template<class H, class E, class K, class T> typedef E hashbase< H, E, K, T >::elemtype
template<class H, class E, class K, class T> typedef K hashbase< H, E, K, T >::keytype
Member Enumeration Documentation
template<class H, class E, class K, class T> anonymous enum
Enumerator
CHUNKSIZE
template<class H, class E, class K, class T> anonymous enum
Enumerator
DEFAULTSIZE
Constructor & Destructor Documentation
template<class H, class E, class K, class T> hashbase< H, E, K, T >::hashbase (int size = DEFAULTSIZE) inline
template<class H, class E, class K, class T> hashbase< H, E, K, T >::~hashbase () inline
Member Function Documentation
template<class H, class E, class K, class T> template<class U > T* hashbase< H, E, K, T >::access (const U & key) inline
Referenced by skelmodel::skeleton::getblendoffset(), vacollect::optimize(), and vacollect::remapunlit().
template<class H, class E, class K, class T> template<class U , class V > T& hashbase< H, E, K, T >::access (const U & key, const V & elem) inline
template<class H, class E, class K, class T> void hashbase< H, E, K, T >::clear () inline
Referenced by skelmodel::skeleton::cleanup(), and vacollect::clear().
template<class H, class E, class K, class T> void hashbase< H, E, K, T >::deletechunks () inline
Referenced by hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::clear(), and hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::~hashbase().
template<class H, class E, class K, class T> static T& hashbase< H, E, K, T >::enumdata (void * i) inline static
template<class H, class E, class K, class T> static K& hashbase< H, E, K, T >::enumkey (void * i) inline static
template<class H, class E, class K, class T> static chain* hashbase< H, E, K, T >::enumnext (void * i) inline static
template<class H, class E, class K, class T> template<class U > T& hashbase< H, E, K, T >::find (const U & key, T & notfound) inline
template<class H, class E, class K, class T> template<class U > const T& hashbase< H, E, K, T >::find (const U & key, const T & notfound) inline
template<class H, class E, class K, class T> chain* hashbase< H, E, K, T >::insert (uint h) inline
Referenced by hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::access(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::insert(), and hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::operator[]().
template<class H, class E, class K, class T> template<class U > T& hashbase< H, E, K, T >::insert (uint h, const U & key) inline
template<class H, class E, class K, class T> template<class U > T& hashbase< H, E, K, T >::operator[] (const U & key) inline
template<class H, class E, class K, class T> template<class U > bool hashbase< H, E, K, T >::remove (const U & key) inline
Member Data Documentation
template<class H, class E, class K, class T> chain** hashbase< H, E, K, T >::chains
Referenced by hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::clear(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::hashbase(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::insert(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::remove(), and hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::~hashbase().
template<class H, class E, class K, class T> chainchunk* hashbase< H, E, K, T >::chunks
Referenced by hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::deletechunks(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::hashbase(), and hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::insert().
template<class H, class E, class K, class T> int hashbase< H, E, K, T >::numelems
Referenced by hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::clear(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::hashbase(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::insert(), and hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::remove().
template<class H, class E, class K, class T> int hashbase< H, E, K, T >::size
Referenced by hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::hashbase().
template<class H, class E, class K, class T> chain* hashbase< H, E, K, T >::unused
Referenced by hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::clear(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::hashbase(), hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::insert(), and hashbase< hashtable< animmodel::shaderparams, animmodel::shaderparamskey >, hashtableentry< animmodel::shaderparams, animmodel::shaderparamskey >, animmodel::shaderparams, animmodel::shaderparamskey >::remove().
The documentation for this struct was generated from the following file:
inexor/shared/cube_hash.hpp