Inexor: dvec4 Struct Reference
dvec4 Struct Reference
#include <geom.hpp>
Public Member Functions
dvec4 ()
dvec4 (double x, double y, double z, double w)
dvec4 (const vec4 &v)
template<class B >
dvec4 & madd (const dvec4 &a, const B &b)
dvec4 & mul (double f)
dvec4 & mul (const dvec4 &o)
dvec4 & add (double f)
dvec4 & add (const dvec4 &o)
operator vec4 () const
Public Attributes
double x
double y
double z
double w
Constructor & Destructor Documentation
dvec4::dvec4 () inline
Referenced by madd().
dvec4::dvec4 (double x, double y, double z, double w) inline
dvec4::dvec4 (const vec4 & v) inline
Member Function Documentation
dvec4& dvec4::add (double f) inline
References f(), w, x, y, and z.
Referenced by madd().
dvec4& dvec4::add (const dvec4 & o) inline
References w, x, y, and z.
template<class B > dvec4& dvec4::madd (const dvec4 & a, const B & b) inline
References add(), dvec4(), and mul().
dvec4& dvec4::mul (double f) inline
References f(), w, x, y, and z.
Referenced by madd().
dvec4& dvec4::mul (const dvec4 & o) inline
References w, x, y, and z.
dvec4::operator vec4 () const inline
References w, x, y, and z.
Member Data Documentation
double dvec4::w
Referenced by add(), mul(), and operator vec4().
double dvec4::x
Referenced by add(), mul(), and operator vec4().
double dvec4::y
Referenced by add(), mul(), and operator vec4().
double dvec4::z
Referenced by add(), mul(), and operator vec4().
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp