Inexor: filesval Struct Reference
filesval Struct Reference
Public Member Functions
filesval (int type, const char *dir, const char *ext)
~filesval ()
void update ()
Public Attributes
int type
char * dir
char * ext
vector< char * > files
int millis
Constructor & Destructor Documentation
filesval::filesval (int type, const char * dir, const char * ext) inline
filesval::~filesval () inline
References DELETEA, dir, and ext().
Member Function Documentation
void filesval::update () inline
References commandmillis, dir, ext(), FILES_DIR, listfiles(), loopv, and totalmillis.
Referenced by complete().
Member Data Documentation
char* filesval::dir
Referenced by addcomplete(), and writecompletions().
char * filesval::ext
Referenced by addcomplete(), and writecompletions().
vector<char *> filesval::files
Referenced by addcomplete(), and complete().
int filesval::millis
int filesval::type
Referenced by writecompletions().
The documentation for this struct was generated from the following file:
inexor/engine/console.cpp