Inexor: fireballrenderer Struct Reference
fireballrenderer Struct Reference
#include <explosion.hpp>
Public Member Functions
fireballrenderer (const char *texname)
void startrender () override
void endrender () override
void cleanup () override
int finddepthfxranges (void **owners, float *ranges, int numranges, int maxranges, vec &bbmin, vec &bbmax)
void seedemitter (particleemitter &pe, const vec &o, const vec &d, int fade, float size, int gravity) override
void renderpart (listparticle *p, const vec &o, const vec &d, int blend, int ts) override
virtual void killpart (listparticle *p)
void reset () override
void resettracked (physent *owner) override
particle * addpart (const vec &o, const vec &d, int fade, int color, float size, int gravity) override
int count () override
bool haswork () override
void render () override
virtual void init (int n)
virtual int adddepthfx (vec &bbmin, vec &bbmax)
virtual void update ()
void calc (particle *p, int &blend, int &ts, vec &o, vec &d, bool step=true)
const char * debuginfo ()
Public Attributes
listparticle * list
Texture * tex
const char * texname
int texclamp
uint type
int collide
string info
Static Public Attributes
static listparticle * parempty = nullptr
Constructor & Destructor Documentation
fireballrenderer::fireballrenderer (const char * texname) inline
Member Function Documentation
virtual int partrenderer::adddepthfx (vec & bbmin, vec & bbmax) inline virtual inherited
Referenced by finddepthfxranges().
particle * listrenderer::addpart (const vec & o, const vec & d, int fade, int color, float size, int gravity) override virtual inherited
Implements partrenderer.
References particle::color, particle::d, hmap::d, emitoffset, particle::fade, particle::flags, particle::gravity, lastmillis, loopi(), particle::millis, listparticle::next, particle::o, and particle::size.
void partrenderer::calc (particle * p, int & blend, int & ts, vec & o, vec & d, bool step = true) inherited
References vec::add(), adddecal(), mpr::collide(), COLLIDEERROR, COLLIDERADIUS, particle::color, particle::d, f(), particle::fade, particle::flags, particle::gravity, lastmillis, inexor::rpc::max(), particle::millis, vec::normalize(), particle::o, game::particletrack(), PT_RND4, PT_TRACK, RAY_CLIPMAT, rayfloor(), particle::size, vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
void fireballrenderer::cleanup () override virtual
Reimplemented from partrenderer.
References sphere::cleanup().
int listrenderer::count () override virtual inherited
Implements partrenderer.
References listparticle::next.
const char * partrenderer::debuginfo () inherited
References mpr::collide(), concatstring(), concformatstring(), formatstring(), partnames, PT_FLIP, PT_GLARE, PT_LERP, PT_MOD, PT_RND4, and PT_SOFT.
Referenced by renderparticles().
void fireballrenderer::endrender () override virtual
Implements listrenderer.
References sphere::disable().
int fireballrenderer::finddepthfxranges (void ** owners, float * ranges, int numranges, int maxranges, vec & bbmin, vec & bbmax)
References vec::add(), depthfxtexture::addscissorbox(), camera1, partrenderer::collide, depthfxbias, depthfxblend, depthfxscale, depthfxscissor, depthfxtex, dir, depthfxtexture::emulatehighprecision(), ENT_CAMERA, depthfxtexture::eyedepth(), depthfxtexture::highprecision(), isfoggedsphere(), lastmillis, listrenderer::list, loopi(), loopk, vec::magnitude(), inexor::rpc::max(), inexor::rpc::min(), vec::mul(), listparticle::next, physent::o, vec::sub(), partrenderer::type, and WOBBLE.
Referenced by finddepthfxranges().
bool listrenderer::haswork () override virtual inherited
Implements partrenderer.
virtual void partrenderer::init (int n) inline virtual inherited
Reimplemented in varenderer< T >.
Referenced by particleinit().
virtual void listrenderer::killpart (listparticle * p) inline virtual inherited
Reimplemented in textrenderer.
void listrenderer::render () override virtual inherited
Implements partrenderer.
References canstep, hmap::d, and textureload().
void fireballrenderer::renderpart (listparticle * p, const vec & o, const vec & d, int blend, int ts) override virtual
Implements listrenderer.
References binddepthfxparams(), camera1, camprojmatrix, camright, camup, gle::color(), particle::color, depthfxblend, dir, sphere::draw(), f(), particle::fade, isfoggedsphere(), lastmillis, LOCALPARAM, LOCALPARAMF, loopi(), vec::magnitude(), vec::magnitude2(), particle::o, physent::o, RAD, reflecting, reflectz, refracting, particle::size, SQRT3, vec::sub(), anonymous_namespace{utilTest.cpp}::t(), matrix3::transposedtransform(), and WOBBLE.
void listrenderer::reset () override virtual inherited
Implements partrenderer.
References listparticle::next.
void listrenderer::resettracked (physent * owner) override virtual inherited
Reimplemented from partrenderer.
References cur, and PT_TRACK.
void fireballrenderer::seedemitter (particleemitter & pe, const vec & o, const vec & d, int fade, float size, int gravity) override virtual
Reimplemented from partrenderer.
References entity::attr2, particleemitter::ent, particleemitter::extendbb(), inexor::rpc::max(), particleemitter::maxfade, and WOBBLE.
void fireballrenderer::startrender () override virtual
Implements listrenderer.
References depthfx, depthfxtex, sphere::enable(), glaring, depthfxtexture::highprecision(), numdepthfxranges, reflecting, refracting, rendertarget::rendertex, and SETSHADER.
virtual void partrenderer::update () inline virtual inherited
Reimplemented in varenderer< T >, and lightningrenderer.
Referenced by renderparticles().
Member Data Documentation
int partrenderer::collide inherited
Referenced by finddepthfxranges(), regularshape(), and splash().
string partrenderer::info inherited
listparticle* listrenderer::list inherited
Referenced by finddepthfxranges().
listparticle * listrenderer::parempty = nullptr static inherited
Texture* partrenderer::tex inherited
Referenced by flarerenderer::render(), and lightningrenderer::renderpart().
int partrenderer::texclamp inherited
const char* partrenderer::texname inherited
Referenced by flarerenderer::render().
uint partrenderer::type inherited
Referenced by finddepthfxranges(), finddepthfxranges(), regularshape(), lightningrenderer::renderpart(), and renderparticles().
The documentation for this struct was generated from the following files:
inexor/engine/explosion.hpp
inexor/engine/explosion.cpp