Inexor: gfield Struct Reference
gfield Struct Reference
Public Types
typedef ushort digit
typedef uint dbldigit
Public Member Functions
gfield ()
gfield (digit n)
gfield (const char *s)
template<int Y_DIGITS>
gfield (const bigint< Y_DIGITS > &y)
template<int Y_DIGITS>
gfield & operator= (const bigint< Y_DIGITS > &y)
template<int X_DIGITS, int Y_DIGITS>
gfield & add (const bigint< X_DIGITS > &x, const bigint< Y_DIGITS > &y)
template<int Y_DIGITS>
gfield & add (const bigint< Y_DIGITS > &y)
template<int X_DIGITS>
gfield & mul2 (const bigint< X_DIGITS > &x)
gfield & mul2 ()
gfield & div2 ()
template<int X_DIGITS, int Y_DIGITS>
gfield & sub (const bigint< X_DIGITS > &x, const bigint< Y_DIGITS > &y)
template<int Y_DIGITS>
gfield & sub (const bigint< Y_DIGITS > &y)
template<int X_DIGITS>
gfield & neg (const bigint< X_DIGITS > &x)
gfield & neg ()
template<int X_DIGITS>
gfield & square (const bigint< X_DIGITS > &x)
gfield & square ()
template<int X_DIGITS, int Y_DIGITS>
gfield & mul (const bigint< X_DIGITS > &x, const bigint< Y_DIGITS > &y)
template<int Y_DIGITS>
gfield & mul (const bigint< Y_DIGITS > &y)
template<int RESULT_DIGITS>
void reduce (const bigint< RESULT_DIGITS > &result)
template<int X_DIGITS, int Y_DIGITS>
gfield & pow (const bigint< X_DIGITS > &x, const bigint< Y_DIGITS > &y)
template<int Y_DIGITS>
gfield & pow (const bigint< Y_DIGITS > &y)
bool invert (const gfield &x)
void invert ()
int legendre () const
bool sqrt (const gfield &x)
bool sqrt ()
void parse (const char *s)
void zero ()
bool iszero () const
bool isone () const
int numbits () const
bool hasbit (int n) const
bool morebits (int n) const
void shrink ()
void shrinkdigits (int n)
void shrinkbits (int n)
template<int Y_DIGITS>
void copyshrinkdigits (const bigint< Y_DIGITS > &y, int n)
template<int Y_DIGITS>
void copyshrinkbits (const bigint< Y_DIGITS > &y, int n)
bigint & rshift (int n)
bigint & lshift (int n)
void zerodigits (int i, int n)
void zerobits (int i, int n)
template<int Y_DIGITS>
void copydigits (int to, const bigint< Y_DIGITS > &y, int from, int n)
template<int Y_DIGITS>
void copybits (int to, const bigint< Y_DIGITS > &y, int from, int n)
void dupdigits (int to, int from, int n)
void dupbits (int to, int from, int n)
template<int Y_DIGITS>
bool operator== (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator!= (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator< (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator> (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator<= (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator>= (const bigint< Y_DIGITS > &y) const
Static Public Member Functions
template<int X_DIGITS>
static int legendre (const bigint< X_DIGITS > &x)
static int parsedigits (ushort *digits, int maxlen, const char *s)
Public Attributes
int len
digit digits [BI_DIGITS]
Static Public Attributes
static const gfield P
Member Typedef Documentation
template<int BI_DIGITS> typedef uint bigint< BI_DIGITS >::dbldigit inherited
template<int BI_DIGITS> typedef ushort bigint< BI_DIGITS >::digit inherited
Constructor & Destructor Documentation
gfield::gfield () inline
gfield::gfield (digit n) inline
gfield::gfield (const char * s) inline
template<int Y_DIGITS> gfield::gfield (const bigint< Y_DIGITS > & y) inline
Member Function Documentation
template<int X_DIGITS, int Y_DIGITS> gfield& gfield::add (const bigint< X_DIGITS > & x, const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::add(), P, and bigint< BI_DIGITS >::sub().
Referenced by ecjacobian::add(), ecjacobian::calcy(), mul2(), ecjacobian::mul2(), reduce(), and sqrt().
template<int Y_DIGITS> gfield& gfield::add (const bigint< Y_DIGITS > & y) inline
References add().
Referenced by add().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copybits (int to, const bigint< Y_DIGITS > & y, int from, int n) inline inherited
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::copydigits().
Referenced by reduce().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copydigits (int to, const bigint< Y_DIGITS > & y, int from, int n) inline inherited
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and inexor::rpc::min().
Referenced by bigint< BI_DIGITS >::copybits().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copyshrinkbits (const bigint< Y_DIGITS > & y, int n) inline inherited
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::copyshrinkdigits().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copyshrinkdigits (const bigint< Y_DIGITS > & y, int n) inline inherited
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, inexor::rpc::min(), and bigint< BI_DIGITS >::shrink().
Referenced by bigint< BI_DIGITS >::copyshrinkbits(), and reduce().
gfield& gfield::div2 () inline
References bigint< BI_DIGITS >::add(), bigint< BI_DIGITS >::hasbit(), P, and bigint< BI_DIGITS >::rshift().
template<int BI_DIGITS> void bigint< BI_DIGITS >::dupbits (int to, int from, int n) inline inherited
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::dupdigits().
Referenced by reduce().
template<int BI_DIGITS> void bigint< BI_DIGITS >::dupdigits (int to, int from, int n) inline inherited
References bigint< BI_DIGITS >::digits.
Referenced by bigint< BI_DIGITS >::dupbits().
template<int BI_DIGITS> bool bigint< BI_DIGITS >::hasbit (int n) const inline inherited
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by ecjacobian::calcy(), div2(), invert(), ecjacobian::mul(), and pow().
bool gfield::invert (const gfield & x) inline
References bigint< BI_DIGITS >::add(), ASSERT, C, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::hasbit(), bigint< BI_DIGITS >::len, P, bigint< BI_DIGITS >::rshift(), and bigint< BI_DIGITS >::sub().
Referenced by ecjacobian::normalize().
void gfield::invert () inline
References invert().
Referenced by invert().
template<int BI_DIGITS> bool bigint< BI_DIGITS >::isone () const inline inherited
References bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by ecjacobian::add(), and ecjacobian::normalize().
template<int BI_DIGITS> bool bigint< BI_DIGITS >::iszero () const inline inherited
References bigint< BI_DIGITS >::len.
Referenced by ecjacobian::add(), ecjacobian::mul2(), and ecjacobian::normalize().
template<int X_DIGITS> static int gfield::legendre (const bigint< X_DIGITS > & x) inline static
References bigint< BI_DIGITS >::len, P, pow(), bigint< BI_DIGITS >::rshift(), and sub().
int gfield::legendre () const inline
References legendre().
Referenced by legendre(), and sqrt().
template<int BI_DIGITS> bigint& bigint< BI_DIGITS >::lshift (int n) inline inherited
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and loopirev.
template<int BI_DIGITS> bool bigint< BI_DIGITS >::morebits (int n) const inline inherited
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::len.
Referenced by reduce().
template<int X_DIGITS, int Y_DIGITS> gfield& gfield::mul (const bigint< X_DIGITS > & x, const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::mul(), reduce(), and result().
Referenced by ecjacobian::add(), ecjacobian::calcy(), ecjacobian::mul2(), ecjacobian::normalize(), pow(), and square().
template<int Y_DIGITS> gfield& gfield::mul (const bigint< Y_DIGITS > & y) inline
References mul().
Referenced by mul().
template<int X_DIGITS> gfield& gfield::mul2 (const bigint< X_DIGITS > & x) inline
References add().
Referenced by ecjacobian::mul2().
gfield& gfield::mul2 () inline
References mul2().
Referenced by mul2().
template<int X_DIGITS> gfield& gfield::neg (const bigint< X_DIGITS > & x) inline
References P, and bigint< BI_DIGITS >::sub().
Referenced by ecjacobian::calcy().
gfield& gfield::neg () inline
References neg().
Referenced by neg().
template<int BI_DIGITS> int bigint< BI_DIGITS >::numbits () const inline inherited
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by ecjacobian::mul(), and pow().
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator!= (const bigint< Y_DIGITS > & y) const inline inherited
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator< (const bigint< Y_DIGITS > & y) const inline inherited
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and loopirev.
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator<= (const bigint< Y_DIGITS > & y) const inline inherited
template<int Y_DIGITS> gfield& gfield::operator= (const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::operator=().
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator== (const bigint< Y_DIGITS > & y) const inline inherited
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and loopirev.
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator> (const bigint< Y_DIGITS > & y) const inline inherited
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator>= (const bigint< Y_DIGITS > & y) const inline inherited
template<int BI_DIGITS> void bigint< BI_DIGITS >::parse (const char * s) inline inherited
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, bigint< BI_DIGITS >::parsedigits(), and bigint< BI_DIGITS >::shrink().
Referenced by bigint< BI_DIGITS >::bigint(), and ecjacobian::parse().
template<int BI_DIGITS> static int bigint< BI_DIGITS >::parsedigits (ushort * digits, int maxlen, const char * s) inline static inherited
References bigint< BI_DIGITS >::len, and loopi().
Referenced by bigint< BI_DIGITS >::parse().
template<int X_DIGITS, int Y_DIGITS> gfield& gfield::pow (const bigint< X_DIGITS > & x, const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::hasbit(), bigint< BI_DIGITS >::len, mul(), bigint< BI_DIGITS >::numbits(), and square().
Referenced by legendre(), and sqrt().
template<int Y_DIGITS> gfield& gfield::pow (const bigint< Y_DIGITS > & y) inline
References pow().
Referenced by pow().
template<int RESULT_DIGITS> void gfield::reduce (const bigint< RESULT_DIGITS > & result) inline
References add(), bigint< BI_DIGITS >::copybits(), bigint< BI_DIGITS >::copyshrinkdigits(), bigint< BI_DIGITS >::dupbits(), GF_DIGITS, bigint< BI_DIGITS >::morebits(), P, bigint< BI_DIGITS >::shrinkbits(), bigint< BI_DIGITS >::shrinkdigits(), bigint< BI_DIGITS >::sub(), sub(), and bigint< BI_DIGITS >::zerobits().
Referenced by mul().
template<int BI_DIGITS> bigint& bigint< BI_DIGITS >::rshift (int n) inline inherited
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and bigint< BI_DIGITS >::shrink().
Referenced by div2(), invert(), legendre(), and sqrt().
template<int BI_DIGITS> void bigint< BI_DIGITS >::shrink () inline inherited
References bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by bigint< BI_DIGITS >::copyshrinkdigits(), bigint< BI_DIGITS >::mul(), bigint< BI_DIGITS >::parse(), bigint< BI_DIGITS >::rshift(), bigint< BI_DIGITS >::shrinkdigits(), and bigint< BI_DIGITS >::sub().
template<int BI_DIGITS> void bigint< BI_DIGITS >::shrinkbits (int n) inline inherited
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::shrinkdigits().
Referenced by reduce().
template<int BI_DIGITS> void bigint< BI_DIGITS >::shrinkdigits (int n) inline inherited
References bigint< BI_DIGITS >::len, and bigint< BI_DIGITS >::shrink().
Referenced by reduce(), and bigint< BI_DIGITS >::shrinkbits().
bool gfield::sqrt (const gfield & x) inline
References add(), ASSERT, bigint< BI_DIGITS >::digits, legendre(), bigint< BI_DIGITS >::len, P, pow(), and bigint< BI_DIGITS >::rshift().
Referenced by ecjacobian::calcy().
bool gfield::sqrt () inline
References sqrt().
Referenced by sqrt().
template<int X_DIGITS> gfield& gfield::square (const bigint< X_DIGITS > & x) inline
References mul().
Referenced by ecjacobian::add(), ecjacobian::calcy(), ecjacobian::mul2(), ecjacobian::normalize(), and pow().
gfield& gfield::square () inline
References square().
Referenced by square().
template<int X_DIGITS, int Y_DIGITS> gfield& gfield::sub (const bigint< X_DIGITS > & x, const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::add(), P, and bigint< BI_DIGITS >::sub().
Referenced by ecjacobian::add(), ecjacobian::calcy(), legendre(), ecjacobian::mul2(), and reduce().
template<int Y_DIGITS> gfield& gfield::sub (const bigint< Y_DIGITS > & y) inline
References sub().
Referenced by sub().
template<int BI_DIGITS> void bigint< BI_DIGITS >::zero () inline inherited
References bigint< BI_DIGITS >::len.
Referenced by ecjacobian::calcy().
template<int BI_DIGITS> void bigint< BI_DIGITS >::zerobits (int i, int n) inline inherited
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::zerodigits().
Referenced by reduce().
template<int BI_DIGITS> void bigint< BI_DIGITS >::zerodigits (int i, int n) inline inherited
References bigint< BI_DIGITS >::digits.
Referenced by bigint< BI_DIGITS >::zerobits().
Member Data Documentation
template<int BI_DIGITS> digit bigint< BI_DIGITS >::digits[BI_DIGITS] inherited
Referenced by bigint< BI_DIGITS >::add(), bigint< BI_DIGITS >::bigint(), bigint< BI_DIGITS >::copydigits(), bigint< BI_DIGITS >::copyshrinkdigits(), bigint< BI_DIGITS >::dupdigits(), bigint< BI_DIGITS >::hasbit(), invert(), bigint< BI_DIGITS >::isone(), bigint< BI_DIGITS >::lshift(), bigint< BI_DIGITS >::mul(), bigint< BI_DIGITS >::numbits(), bigint< BI_DIGITS >::operator<(), bigint< BI_DIGITS >::operator=(), bigint< BI_DIGITS >::operator==(), bigint< BI_DIGITS >::parse(), pow(), bigint< BI_DIGITS >::rshift(), bigint< BI_DIGITS >::shrink(), sqrt(), bigint< BI_DIGITS >::sub(), and bigint< BI_DIGITS >::zerodigits().
template<int BI_DIGITS> int bigint< BI_DIGITS >::len inherited
Referenced by bigint< BI_DIGITS >::add(), bigint< BI_DIGITS >::bigint(), bigint< BI_DIGITS >::copydigits(), bigint< BI_DIGITS >::copyshrinkdigits(), bigint< BI_DIGITS >::hasbit(), invert(), bigint< BI_DIGITS >::isone(), bigint< BI_DIGITS >::iszero(), legendre(), bigint< BI_DIGITS >::lshift(), bigint< BI_DIGITS >::morebits(), bigint< BI_DIGITS >::mul(), bigint< BI_DIGITS >::numbits(), bigint< BI_DIGITS >::operator<(), bigint< BI_DIGITS >::operator=(), bigint< BI_DIGITS >::operator==(), bigint< BI_DIGITS >::parse(), bigint< BI_DIGITS >::parsedigits(), pow(), bigint< BI_DIGITS >::rshift(), bigint< BI_DIGITS >::shrink(), bigint< BI_DIGITS >::shrinkdigits(), sqrt(), bigint< BI_DIGITS >::sub(), and bigint< BI_DIGITS >::zero().
const gfield gfield::P static
Referenced by add(), div2(), invert(), legendre(), neg(), reduce(), sqrt(), and sub().
The documentation for this struct was generated from the following file:
inexor/network/legacy/crypto.cpp