Inexor: tagval Struct Reference
tagval Struct Reference
#include <command.hpp>
Public Member Functions
void setint (int val)
void setfloat (float val)
void setstr (char *val)
void setnull ()
void setcode (const uint *val)
void setmacro (const uint *val)
void setident (ident *val)
const char * getstr () const
int getint () const
float getfloat () const
bool getbool () const
void cleanup ()
Public Attributes
int type
union {
int i
float f
char * s
const uint * code
ident * id
};
Member Function Documentation
void tagval::cleanup ()
References freearg().
bool tagval::getbool () const
float tagval::getfloat () const inline
References getfloat(), and type.
int tagval::getint () const inline
References getint(), and type.
Referenced by at(), and execute().
const char * tagval::getstr () const inline
References getstr(), and type.
Referenced by at(), format(), loopconc(), and looplistconc().
void tagval::setcode (const uint * val) inline
References type, and VAL_CODE.
Referenced by callcommand(), and runcode().
void tagval::setfloat (float val) inline
References f(), type, and VAL_FLOAT.
Referenced by callcommand(), floatret(), forcefloat(), ident::getval(), loopiter(), and runcode().
void tagval::setident (ident * val) inline
References type, and VAL_IDENT.
Referenced by callcommand(), forceident(), and runcode().
void tagval::setint (int val) inline
References type, and VAL_INT.
Referenced by callcommand(), forceint(), ident::getval(), intret(), loopiter(), runcode(), and setiter().
void tagval::setmacro (const uint * val) inline
References type, and VAL_MACRO.
Referenced by runcode().
void tagval::setnull () inline
References type, and VAL_NULL.
Referenced by callcommand(), forcenull(), ident::getval(), and runcode().
void tagval::setstr (char * val) inline
References type, and VAL_STR.
Referenced by alias(), at(), callcommand(), concat(), concatword(), forcestr(), ident::getval(), listfilter(), listsplice(), loopiter(), looplistconc(), result(), runcode(), setiter(), sortlist(), stringret(), strsplice(), sublist(), and substr().
Member Data Documentation
union { ... }
int tagval::type
Referenced by executestr(), forcearg(), forcefloat(), forceident(), forceint(), forcenull(), forcestr(), freearg(), getbool(), getfloat(), getint(), getstr(), result(), runcode(), setcode(), setfloat(), setident(), setint(), setmacro(), setnull(), setstr(), and ident::setval().
The documentation for this struct was generated from the following files:
inexor/shared/command.hpp
inexor/engine/command.cpp