Inexor: skelmodel::skeleton Struct Reference
skelmodel::skeleton Struct Reference
#include <skelmodel.hpp>
Public Member Functions
skeleton ()
~skeleton ()
skelanimspec * findskelanim (const char *name, char sep= '\0')
skelanimspec & addskelanim (const char *name)
int findbone (const char *name)
int findtag (const char *name)
bool addtag (const char *name, int bone, const matrix4x3 &matrix)
void calcantipodes ()
void remapbones ()
void addpitchdep (int bone, int frame)
int findpitchdep (int bone)
int findpitchcorrect (int bone)
void initpitchdeps ()
void optimize ()
void expandbonemask (uchar *expansion, int bone, int val)
void applybonemask (ushort *mask, uchar *partmask, int partindex)
void linkchildren ()
int availgpubones () const
bool gpuaccelerate () const
float calcdeviation (const vec &axis, const vec &forward, const dualquat &pose1, const dualquat &pose2)
void calcpitchcorrects (float pitch, const vec &axis, const vec &forward)
void interpbones (const animstate *as, float pitch, const vec &axis, const vec &forward, int numanimparts, const uchar *partmask, skelcacheentry &sc)
void initragdoll (ragdolldata &d, skelcacheentry &sc, part *p)
void genragdollbones (ragdolldata &d, skelcacheentry &sc, part *p)
void concattagtransform (part *p, int i, const matrix4x3 &m, matrix4x3 &n)
void calctags (part *p, skelcacheentry *sc=nullptr)
void cleanup (bool full=true)
bool canpreload ()
void preload ()
skelcacheentry & checkskelcache (part *p, const animstate *as, float pitch, const vec &axis, const vec &forward, ragdolldata *rdata)
int getblendoffset (UniformLoc &u)
void setglslbones (UniformLoc &u, skelcacheentry &sc, skelcacheentry &bc, int count)
void setgpubones (skelcacheentry &sc, blendcacheentry *bc, int count)
bool shouldcleanup () const
Public Attributes
char * name
int shared
vector< skelmeshgroup * > users
boneinfo * bones
int numbones
int numinterpbones
int numgpubones
int numframes
dualquat * framebones
vector< skelanimspec > skelanims
vector< tag > tags
vector< antipode > antipodes
ragdollskel * ragdoll
vector< pitchdep > pitchdeps
vector< pitchtarget > pitchtargets
vector< pitchcorrect > pitchcorrects
bool usegpuskel
vector< skelcacheentry > skelcache
hashtable< GLuint, int > blendoffsets
Constructor & Destructor Documentation
skelmodel::skeleton::skeleton () inline
skelmodel::skeleton::~skeleton () inline
References bones, DELETEA, DELETEP, framebones, loopv, name, ragdoll, and skelcache.
Member Function Documentation
void skelmodel::skeleton::addpitchdep (int bone, int frame) inline
References skelmodel::pitchdep::bone, bones, hmap::d, framebones, loopvj, numbones, skelmodel::boneinfo::parent, skelmodel::pitchdep::parent, pitchdeps, and skelmodel::pitchdep::pose.
Referenced by initpitchdeps().
skelanimspec& skelmodel::skeleton::addskelanim (const char * name) inline
References skelmodel::skelanimspec::name, newstring(), and skelanims.
Referenced by smd::smdmeshgroup::loadanim().
bool skelmodel::skeleton::addtag (const char * name, int bone, const matrix4x3 & matrix) inline
References skelmodel::tag::bone, findtag(), skelmodel::tag::matrix, skelmodel::tag::name, newstring(), anonymous_namespace{utilTest.cpp}::t(), and tags.
void skelmodel::skeleton::applybonemask (ushort * mask, uchar * partmask, int partindex) inline
References BONEMASK_BONE, BONEMASK_END, BONEMASK_NOT, expandbonemask(), loopi(), and numbones.
int skelmodel::skeleton::availgpubones () const inline
References maxvsuniforms, inexor::rpc::min(), and reservevpparams.
Referenced by skelmodel::skelmeshgroup::genvbo(), and gpuaccelerate().
void skelmodel::skeleton::calcantipodes () inline
References vector< T, MINSIZE >::add(), antipodes, bones, skelmodel::boneinfo::interpindex, vector< T, MINSIZE >::length(), loopi(), loopj, loopv, inexor::rpc::min(), numbones, and skelmodel::boneinfo::scheduled.
Referenced by remapbones().
float skelmodel::skeleton::calcdeviation (const vec & axis, const vec & forward, const dualquat & pose1, const dualquat & pose2) inline
References vec::cross(), vec::dot(), vec::normalize(), vec::project(), RAD, and dualquat::transformnormal().
Referenced by calcpitchcorrects().
void skelmodel::skeleton::calcpitchcorrects (float pitch, const vec & axis, const vec & forward) inline
References calcdeviation(), skelmodel::pitchtarget::corrects, skelmodel::pitchtarget::deps, skelmodel::pitchtarget::deviated, f(), loopv, loopvj, skelmodel::pitchcorrect::parent, skelmodel::pitchcorrect::pitchangle, pitchcorrects, pitchdeps, skelmodel::pitchtarget::pitchmax, skelmodel::pitchcorrect::pitchmax, skelmodel::pitchtarget::pitchmin, skelmodel::pitchcorrect::pitchmin, skelmodel::pitchcorrect::pitchscale, pitchtargets, skelmodel::pitchcorrect::pitchtotal, skelmodel::pitchtarget::pose, anonymous_namespace{utilTest.cpp}::t(), and skelmodel::pitchcorrect::target.
Referenced by interpbones().
void skelmodel::skeleton::calctags (part * p, skelcacheentry * sc = nullptr) inline
References vec::add(), skelmodel::boneinfo::base, skelmodel::tag::bone, bones, matrix4x3::d, skelmodel::boneinfo::interpindex, animmodel::part::links, loopv, skelmodel::tag::matrix, animmodel::linkedpart::matrix, animmodel::part::model, vec::mul(), dualquat::mul(), matrix4x3::mul(), model::scale, anonymous_namespace{utilTest.cpp}::t(), animmodel::linkedpart::tag, tags, and animmodel::part::translate.
Referenced by skelmodel::skelmeshgroup::render().
bool skelmodel::skeleton::canpreload () inline
References gpuaccelerate(), and numframes.
Referenced by skelmodel::skelmeshgroup::preload().
skelcacheentry& skelmodel::skeleton::checkskelcache (part * p, const animstate * as, float pitch, const vec & axis, const vec & forward, ragdolldata * rdata) inline
References skelmodel::animcacheentry::as, genragdollbones(), gpuaccelerate(), interpbones(), lastmillis, ragdolldata::lastmove, loopi(), loopj, loopv, skelmodel::animcacheentry::millis, animmodel::animstate::owner, skelmodel::animcacheentry::partmask, skelmodel::animcacheentry::pitch, skelmodel::animcacheentry::ragdoll, skelcache, and usegpuskel.
Referenced by skelmodel::skelmeshgroup::render().
void skelmodel::skeleton::cleanup (bool full = true) inline
References skelmodel::animcacheentry::as, skelmodel::skelcacheentry::bdata, blendoffsets, hashbase< H, E, K, T >::clear(), DELETEA, loopj, loopv, MAXANIMPARTS, skelcache, and users.
Referenced by skelmodel::skelmeshgroup::cleanup(), optimize(), skelmodel::skelmeshgroup::preload(), and skelmodel::skelmeshgroup::render().
void skelmodel::skeleton::concattagtransform (part * p, int i, const matrix4x3 & m, matrix4x3 & n) inline
References bones, animmodel::part::model, vec::mul(), matrix4x3::mul(), model::scale, anonymous_namespace{utilTest.cpp}::t(), tags, animmodel::part::translate, and matrix4x3::translate().
Referenced by skelmodel::skelmeshgroup::concattagtransform().
void skelmodel::skeleton::expandbonemask (uchar * expansion, int bone, int val) inline
References bones, skelmodel::boneinfo::children, and skelmodel::boneinfo::next.
Referenced by applybonemask().
int skelmodel::skeleton::findbone (const char * name) inline
References bones, loopi(), and numbones.
int skelmodel::skeleton::findpitchcorrect (int bone) inline
References loopv, and pitchcorrects.
Referenced by initpitchdeps().
int skelmodel::skeleton::findpitchdep (int bone) inline
References loopv, and pitchdeps.
Referenced by initpitchdeps().
skelanimspec* skelmodel::skeleton::findskelanim (const char * name, char sep = '\0') inline
References gle::end(), loopv, and skelanims.
Referenced by smd::smdmeshgroup::loadanim().
int skelmodel::skeleton::findtag (const char * name) inline
References loopv, and tags.
Referenced by addtag(), and skelmodel::skelmeshgroup::findtag().
void skelmodel::skeleton::genragdollbones (ragdolldata & d, skelcacheentry & sc, part * p) inline
References vec::add(), ragdolldata::animjoints, antipodes, skelmodel::skelcacheentry::bdata, ragdollskel::joint::bone, ragdollskel::reljoint::bone, bones, hmap::br, dualquat::fixantipodal(), skelmodel::boneinfo::interpindex, ragdollskel::joints, loopk, loopv, animmodel::part::model, vec::mul(), dualquat::mul(), matrix4x3::mul(), skelmodel::skelcacheentry::nextversion(), numinterpbones, ragdollskel::joint::orient, ragdollskel::reljoint::parent, ragdolldata::vert::pos, ragdoll, ragdollskel::reljoints, ragdolldata::reljoints, model::scale, vec::sub(), animmodel::part::translate, ragdollskel::joint::tri, ragdolldata::tris, ragdollskel::joint::vert, ragdolldata::verts, and ragdollskel::joint::weight.
Referenced by checkskelcache().
int skelmodel::skeleton::getblendoffset (UniformLoc & u) inline
References hashbase< H, E, K, T >::access(), blendoffsets, defformatstring, glGetUniformLocation_, Shader::lastshader, UniformLoc::name, and numgpubones.
Referenced by setglslbones().
bool skelmodel::skeleton::gpuaccelerate () const inline
References availgpubones(), numframes, and numgpubones.
Referenced by canpreload(), checkskelcache(), preload(), and shouldcleanup().
void skelmodel::skeleton::initpitchdeps () inline
References addpitchdep(), skelmodel::pitchdep::bone, skelmodel::pitchtarget::bone, skelmodel::pitchcorrect::bone, bones, skelmodel::boneinfo::correctindex, skelmodel::pitchtarget::corrects, hmap::d, skelmodel::pitchtarget::deps, findpitchcorrect(), findpitchdep(), skelmodel::pitchtarget::frame, loopv, dualquat::mul(), skelmodel::boneinfo::parent, skelmodel::pitchdep::parent, skelmodel::pitchcorrect::parent, pitchcorrects, pitchdeps, pitchtargets, skelmodel::pitchdep::pose, skelmodel::pitchtarget::pose, and anonymous_namespace{utilTest.cpp}::t().
Referenced by optimize().
void skelmodel::skeleton::initragdoll (ragdolldata & d, skelcacheentry & sc, part * p) inline
References vec::add(), ragdollskel::animjoints, skelmodel::skelcacheentry::bdata, ragdollskel::joint::bone, ragdollskel::reljoint::bone, bones, hmap::br, ragdolldata::calcanimjoint(), skelmodel::boneinfo::interpindex, dualquat::invert(), ragdollskel::joints, loopk, loopv, animmodel::matrixpos, animmodel::matrixstack, animmodel::part::model, vec::mul(), dualquat::mul(), ragdollskel::reljoint::parent, ragdollskel::vert::pos, ragdolldata::vert::pos, ragdoll, ragdollskel::reljoints, ragdolldata::reljoints, model::scale, dualquat::transform(), matrix4::transform(), animmodel::part::translate, ragdollskel::joint::vert, ragdollskel::verts, ragdolldata::verts, and ragdollskel::vert::weight.
Referenced by skelmodel::skelmeshgroup::render().
void skelmodel::skeleton::interpbones (const animstate * as, float pitch, const vec & axis, const vec & forward, int numanimparts, const uchar * partmask, skelcacheentry & sc) inline
References animmodel::animpos::anim, ANIM_NOPITCH, antipodes, skelmodel::boneinfo::base, skelmodel::skelcacheentry::bdata, skelmodel::pitchdep::bone, bones, calcpitchcorrects(), skelmodel::boneinfo::correctindex, animmodel::animstate::cur, hmap::d, dualquat::fixantipodal(), animmodel::animpos::fr1, framebones, animmodel::animstate::interp, INTERPBONE, skelmodel::boneinfo::interpindex, skelmodel::boneinfo::interpparent, loopi(), loopv, MAXANIMPARTS, dualquat::mul(), dualquat::mulorient(), skelmodel::skelcacheentry::nextversion(), numbones, numinterpbones, skelmodel::pitchdep::parent, pitchcorrects, pitchdeps, skelmodel::boneinfo::pitchmax, skelmodel::boneinfo::pitchmin, skelmodel::boneinfo::pitchoffset, skelmodel::boneinfo::pitchscale, skelmodel::pitchdep::pose, animmodel::animstate::prev, and RAD.
Referenced by checkskelcache().
void skelmodel::skeleton::linkchildren () inline
References bones, skelmodel::boneinfo::children, loopi(), skelmodel::boneinfo::next, numbones, and skelmodel::boneinfo::parent.
Referenced by smd::smdmeshgroup::loadmesh().
void skelmodel::skeleton::optimize () inline
References cleanup(), initpitchdeps(), ragdoll, remapbones(), and ragdollskel::setup().
void skelmodel::skeleton::preload () inline
References gpuaccelerate(), numframes, skelcache, and usegpuskel.
Referenced by skelmodel::skelmeshgroup::preload().
void skelmodel::skeleton::remapbones () inline
References ragdollskel::addreljoint(), skelmodel::skelmeshgroup::blendcombos, skelmodel::blendcombo::bones, bones, calcantipodes(), skelmodel::boneinfo::group, skelmodel::blendcombo::interpbones, skelmodel::boneinfo::interpindex, skelmodel::boneinfo::interpparent, ragdollskel::joints, loopi(), loopk, loopl, loopv, loopvj, numbones, numgpubones, numinterpbones, skelmodel::boneinfo::parent, ragdoll, skelmodel::boneinfo::ragdollindex, tags, users, and skelmodel::blendcombo::weights.
Referenced by optimize().
void skelmodel::skeleton::setglslbones (UniformLoc & u, skelcacheentry & sc, skelcacheentry & bc, int count) inline
References skelmodel::skelcacheentry::bdata, UniformLoc::data, getblendoffset(), glUniform4fv_, UniformLoc::loc, numgpubones, dualquat::real, UniformLoc::version, and skelmodel::skelcacheentry::version.
Referenced by setgpubones().
void skelmodel::skeleton::setgpubones (skelcacheentry & sc, blendcacheentry * bc, int count) inline
References Shader::lastshader, setglslbones(), and Shader::uniformlocs.
Referenced by skelmodel::skelmeshgroup::render().
bool skelmodel::skeleton::shouldcleanup () const inline
References gpuaccelerate(), numframes, skelcache, and usegpuskel.
Referenced by skelmodel::skelmeshgroup::preload(), and skelmodel::skelmeshgroup::render().
Member Data Documentation
vector<antipode> skelmodel::skeleton::antipodes
Referenced by calcantipodes(), genragdollbones(), and interpbones().
hashtable<GLuint, int> skelmodel::skeleton::blendoffsets
Referenced by cleanup(), and getblendoffset().
boneinfo* skelmodel::skeleton::bones
Referenced by addpitchdep(), calcantipodes(), calctags(), concattagtransform(), expandbonemask(), findbone(), genragdollbones(), initpitchdeps(), initragdoll(), interpbones(), linkchildren(), smd::smdmeshgroup::loadmesh(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readskeleton(), remapbones(), and ~skeleton().
dualquat* skelmodel::skeleton::framebones
Referenced by addpitchdep(), interpbones(), smd::smdmeshgroup::loadanim(), smd::smdmeshgroup::readframes(), and ~skeleton().
char* skelmodel::skeleton::name
Referenced by skelmodel::skelmeshgroup::shareskeleton(), and ~skeleton().
int skelmodel::skeleton::numbones
Referenced by addpitchdep(), applybonemask(), calcantipodes(), findbone(), interpbones(), linkchildren(), smd::smdmeshgroup::loadanim(), smd::smdmeshgroup::loadmesh(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readskeleton(), and remapbones().
int skelmodel::skeleton::numframes
Referenced by canpreload(), skelmodel::skelmeshgroup::genvbo(), gpuaccelerate(), smd::smdmeshgroup::loadanim(), preload(), smd::smdmeshgroup::readframes(), skelmodel::skelmeshgroup::render(), shouldcleanup(), and skelmodel::skelmeshgroup::totalframes().
int skelmodel::skeleton::numgpubones
Referenced by skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::genvbo(), getblendoffset(), gpuaccelerate(), remapbones(), and setglslbones().
int skelmodel::skeleton::numinterpbones
Referenced by genragdollbones(), interpbones(), and remapbones().
vector<pitchcorrect> skelmodel::skeleton::pitchcorrects
Referenced by calcpitchcorrects(), findpitchcorrect(), initpitchdeps(), and interpbones().
vector<pitchdep> skelmodel::skeleton::pitchdeps
Referenced by addpitchdep(), calcpitchcorrects(), findpitchdep(), initpitchdeps(), and interpbones().
vector<pitchtarget> skelmodel::skeleton::pitchtargets
Referenced by calcpitchcorrects(), and initpitchdeps().
ragdollskel* skelmodel::skeleton::ragdoll
Referenced by genragdollbones(), initragdoll(), optimize(), remapbones(), skelmodel::skelmeshgroup::render(), and ~skeleton().
int skelmodel::skeleton::shared
Referenced by smd::smdmeshgroup::loadmesh(), skelmodel::skelmeshgroup::shareskeleton(), and skelmodel::skelmeshgroup::~skelmeshgroup().
vector<skelanimspec> skelmodel::skeleton::skelanims
Referenced by addskelanim(), and findskelanim().
vector<skelcacheentry> skelmodel::skeleton::skelcache
Referenced by checkskelcache(), cleanup(), preload(), skelmodel::skelmeshgroup::render(), shouldcleanup(), and ~skeleton().
vector<tag> skelmodel::skeleton::tags
Referenced by addtag(), calctags(), concattagtransform(), findtag(), and remapbones().
bool skelmodel::skeleton::usegpuskel
Referenced by skelmodel::skelmeshgroup::bindvbo(), skelmodel::skelmeshgroup::blendbones(), checkskelcache(), skelmodel::skelmeshgroup::genvbo(), preload(), skelmodel::skelmeshgroup::render(), skelmodel::skelmesh::setshader(), and shouldcleanup().
vector<skelmeshgroup *> skelmodel::skeleton::users
Referenced by cleanup(), remapbones(), skelmodel::skelmeshgroup::shareskeleton(), and skelmodel::skelmeshgroup::~skelmeshgroup().
The documentation for this struct was generated from the following file:
inexor/model/skelmodel.hpp