Inexor: vertmodel::vertmesh Struct Reference
vertmodel::vertmesh Struct Reference
#include <vertmodel.hpp>
Public Member Functions
vertmesh ()
~vertmesh () override
void smoothnorms (float limit=0, bool areaweight=true)
void buildnorms (bool areaweight=true)
void calctangents (bool areaweight=true)
void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m) override
void genBIH (BIH::mesh &m) override
void assignvert (vvertbump &vv, int j, tcvert &tc, vert &v)
template<class T >
int genvbo (vector< ushort > &idxs, int offset, vector< T > &vverts, int *htdata, int htlen)
int genvbo (vector< ushort > &idxs, int offset)
template<class T >
void fillverts (T *vdata)
void interpverts (const animstate &as, bool tangents, void *RESTRICT vdata, skin &s)
void render (const animstate *as, skin &s, vbocacheentry &vc)
void genBIH (skin &s, vector< BIH::mesh > &bih, const matrix4x3 &t)
virtual void setshader (Shader *s)
template<class V , class T >
void smoothnorms (V *verts, int numverts, T *tris, int numtris, float limit, bool areaweight)
template<class V , class T >
void buildnorms (V *verts, int numverts, T *tris, int numtris, bool areaweight)
template<class V , class T >
void buildnorms (V *verts, int numverts, T *tris, int numtris, bool areaweight, int numframes)
template<class B , class V , class TC , class T >
void calctangents (B *bumpverts, V *verts, TC *tcverts, int numverts, T *tris, int numtris, bool areaweight)
template<class B , class V , class TC , class T >
void calctangents (B *bumpverts, V *verts, TC *tcverts, int numverts, T *tris, int numtris, bool areaweight, int numframes)
Static Public Member Functions
static void assignvert (vvertn &vv, int j, tcvert &tc, vert &v)
template<class T >
static void fillvert (T &vv, int j, tcvert &tc, vert &v)
static void fixqtangent (quat &q, float bt)
template<class V >
static void calctangent (V &v, const vec &n, const vec &t, float bt)
Public Attributes
vert * verts
tcvert * tcverts
bumpvert * bumpverts
tri * tris
int numverts
int numtris
int voffset
int eoffset
int elen
ushort minvert
ushort maxvert
meshgroup * group
char * name
bool noclip
Constructor & Destructor Documentation
vertmodel::vertmesh::vertmesh () inline
vertmodel::vertmesh::~vertmesh () inline override
References bumpverts, DELETEA, tcverts, tris, and verts.
Member Function Documentation
static void vertmodel::vertmesh::assignvert (vvertn & vv, int j, tcvert & tc, vert & v) inline static
References vertmodel::vert::norm, vertmodel::vvertn::norm, vertmodel::vert::pos, vertmodel::vvert::pos, vertmodel::vvert::tc, and vertmodel::tcvert::tc.
Referenced by genvbo().
void vertmodel::vertmesh::assignvert (vvertbump & vv, int j, tcvert & tc, vert & v) inline
References bumpverts, vertmodel::vert::pos, vertmodel::vvert::pos, vertmodel::vvertbump::tangent, vertmodel::bumpvert::tangent, vertmodel::vvert::tc, and vertmodel::tcvert::tc.
void vertmodel::vertmesh::buildnorms (bool areaweight = true) inline
References animmodel::mesh::buildnorms(), animmodel::mesh::group, numtris, numverts, tris, and verts.
Referenced by smoothnorms().
template<class V , class T > void animmodel::mesh::buildnorms (V * verts, int numverts, T * tris, int numtris, bool areaweight) inline inherited
References vec::add(), vec::cross(), loopi(), vec::normalize(), vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by buildnorms(), skelmodel::skelmesh::buildnorms(), and animmodel::mesh::buildnorms().
template<class V , class T > void animmodel::mesh::buildnorms (V * verts, int numverts, T * tris, int numtris, bool areaweight, int numframes) inline inherited
References animmodel::mesh::buildnorms(), and loopi().
void vertmodel::vertmesh::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline override virtual
Reimplemented from animmodel::mesh.
References loopi(), loopj, inexor::rpc::max(), inexor::rpc::min(), numverts, matrix4x3::transform(), and verts.
template<class V > static void animmodel::mesh::calctangent (V & v, const vec & n, const vec & t, float bt) inline static inherited
References matrix3::a, matrix3::b, matrix3::c, vec::cross(), animmodel::mesh::fixqtangent(), and anonymous_namespace{utilTest.cpp}::t().
void vertmodel::vertmesh::calctangents (bool areaweight = true) inline
References bumpverts, animmodel::mesh::calctangents(), animmodel::mesh::group, numtris, numverts, tcverts, tris, and verts.
template<class B , class V , class TC , class T > void animmodel::mesh::calctangents (B * bumpverts, V * verts, TC * tcverts, int numverts, T * tris, int numtris, bool areaweight) inline inherited
References matrix3::a, vec::add(), matrix3::b, matrix3::c, vec::cross(), vec::dot(), animmodel::mesh::fixqtangent(), loopi(), loopj, vec::mul(), vec::neg(), vec::normalize(), sphere::numverts, vec::sub(), anonymous_namespace{utilTest.cpp}::t(), and gle::tangent().
Referenced by calctangents(), skelmodel::skelmesh::calctangents(), and animmodel::mesh::calctangents().
template<class B , class V , class TC , class T > void animmodel::mesh::calctangents (B * bumpverts, V * verts, TC * tcverts, int numverts, T * tris, int numtris, bool areaweight, int numframes) inline inherited
References animmodel::mesh::calctangents(), and loopi().
template<class T > static void vertmodel::vertmesh::fillvert (T & vv, int j, tcvert & tc, vert & v) inline static
References vertmodel::tcvert::tc.
Referenced by fillverts().
template<class T > void vertmodel::vertmesh::fillverts (T * vdata) inline
References fillvert(), loopi(), numverts, tcverts, verts, and voffset.
static void animmodel::mesh::fixqtangent (quat & q, float bt) inline static inherited
References vec4::mul3(), and vec4::neg().
Referenced by animmodel::mesh::calctangent(), and animmodel::mesh::calctangents().
void vertmodel::vertmesh::genBIH (BIH::mesh & m) inline override virtual
Reimplemented from animmodel::mesh.
References numtris, BIH::mesh::numtris, vertmodel::vert::pos, BIH::mesh::pos, BIH::mesh::posstride, vertmodel::tcvert::tc, BIH::mesh::tc, BIH::mesh::tcstride, tcverts, tris, BIH::mesh::tris, and verts.
void animmodel::mesh::genBIH (skin & s, vector< BIH::mesh > & bih, const matrix4x3 & t) inline inherited
References vector< T, MINSIZE >::add(), Texture::ALPHA, animmodel::skin::cullface, BIH::mesh::flags, animmodel::mesh::genBIH(), BIH::MESH_ALPHA, BIH::MESH_CULLFACE, BIH::MESH_NOCLIP, animmodel::mesh::noclip, anonymous_namespace{utilTest.cpp}::t(), BIH::mesh::tex, animmodel::skin::tex, Texture::type, and BIH::mesh::xform.
template<class T > int vertmodel::vertmesh::genvbo (vector< ushort > & idxs, int offset, vector< T > & vverts, int * htdata, int htlen) inline
References vector< T, MINSIZE >::add(), assignvert(), elen, eoffset, hthash(), vector< T, MINSIZE >::length(), loopi(), loopj, loopk, inexor::rpc::max(), maxvert, inexor::rpc::min(), minvert, numtris, vertmodel::vert::pos, anonymous_namespace{utilTest.cpp}::t(), tcverts, tris, vertmodel::tri::vert, verts, and voffset.
Referenced by vertmodel::vertmeshgroup::preload(), and vertmodel::vertmeshgroup::render().
int vertmodel::vertmesh::genvbo (vector< ushort > & idxs, int offset) inline
References vector< T, MINSIZE >::add(), elen, eoffset, vector< T, MINSIZE >::length(), loopi(), loopj, maxvert, minvert, numtris, numverts, anonymous_namespace{utilTest.cpp}::t(), tris, vertmodel::tri::vert, and voffset.
void vertmodel::vertmesh::interpverts (const animstate & as, bool tangents, void *RESTRICT vdata, skin & s) inline
References bumpverts, animmodel::animstate::cur, animmodel::animpos::fr1, animmodel::animpos::fr2, animmodel::animstate::interp, ipbvert, ipbvertp, iploop, ipvert, ipvertp, numverts, animmodel::animstate::prev, RESTRICT, gle::tangent(), and verts.
Referenced by vertmodel::vertmeshgroup::render().
void vertmodel::vertmesh::render (const animstate * as, skin & s, vbocacheentry & vc) inline
References elen, eoffset, glde, glDrawRangeElements_, animmodel::mesh::group, maxvert, minvert, numverts, and xtravertsva.
Referenced by vertmodel::vertmeshgroup::render().
virtual void animmodel::mesh::setshader (Shader * s) inline virtual inherited
References glaring, Shader::set(), and Shader::setvariant().
Referenced by animmodel::skin::setshader().
void vertmodel::vertmesh::smoothnorms (float limit = 0, bool areaweight = true) inline
References buildnorms(), animmodel::mesh::group, numtris, numverts, animmodel::mesh::smoothnorms(), tris, and verts.
template<class V , class T > void animmodel::mesh::smoothnorms (V * verts, int numverts, T * tris, int numtris, float limit, bool areaweight) inline inherited
References hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::access(), vec::add(), vec::cross(), loopi(), vec::magnitude(), vec::normalize(), sphere::numverts, vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by smoothnorms(), and skelmodel::skelmesh::smoothnorms().
Member Data Documentation
bumpvert* vertmodel::vertmesh::bumpverts
Referenced by assignvert(), calctangents(), interpverts(), and ~vertmesh().
int vertmodel::vertmesh::elen
Referenced by genvbo(), and render().
int vertmodel::vertmesh::eoffset
Referenced by genvbo(), and render().
meshgroup* animmodel::mesh::group inherited
Referenced by buildnorms(), calctangents(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), render(), and smoothnorms().
ushort vertmodel::vertmesh::maxvert
Referenced by genvbo(), and render().
ushort vertmodel::vertmesh::minvert
Referenced by genvbo(), and render().
char* animmodel::mesh::name inherited
Referenced by md3::md3meshgroup::load(), animmodel::mesh::~mesh(), and vertmodel::tag::~tag().
bool animmodel::mesh::noclip inherited
Referenced by animmodel::mesh::genBIH().
int vertmodel::vertmesh::numtris
Referenced by buildnorms(), calctangents(), genBIH(), genvbo(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), and smoothnorms().
int vertmodel::vertmesh::numverts
Referenced by buildnorms(), calcbb(), calctangents(), fillverts(), genvbo(), vertmodel::vertmeshgroup::genvbo(), interpverts(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), render(), and smoothnorms().
tcvert* vertmodel::vertmesh::tcverts
Referenced by calctangents(), fillverts(), genBIH(), genvbo(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), and ~vertmesh().
tri* vertmodel::vertmesh::tris
Referenced by buildnorms(), calctangents(), genBIH(), genvbo(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), smoothnorms(), and ~vertmesh().
vert* vertmodel::vertmesh::verts
Referenced by buildnorms(), calcbb(), calctangents(), fillverts(), genBIH(), genvbo(), interpverts(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), smoothnorms(), and ~vertmesh().
int vertmodel::vertmesh::voffset
Referenced by fillverts(), genvbo(), and vertmodel::vertmeshgroup::render().
The documentation for this struct was generated from the following file:
inexor/model/vertmodel.hpp