Inexor: inexor/texture/texture.cpp File Reference
texture.cpp File Reference
Main texture loading and organizing routines.
#include <SDL_opengl.h>
#include <boost/algorithm/clamp.hpp>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <map>
#include <memory>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include "SDL_pixels.h"
#include "SDL_surface.h"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/SDL_loading.hpp"
#include "inexor/texture/additionaltools.hpp"
#include "inexor/texture/compressedtex.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/format.hpp"
#include "inexor/texture/image.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texsettings.hpp"
#include "inexor/texture/texture.hpp"
Macros
#define PARSETEXCOMMANDS(cmds)
Functions
COMMAND (gendds,"ss")
COMMAND (flipnormalmapy,"ss")
COMMAND (mergenormalmaps,"ss")
void setuptexcompress ()
void uploadtexture (GLenum target, GLenum internal, int tw, int th, GLenum format, GLenum type, void *pixels, int pw, int ph, int pitch, bool mipmap)
void uploadcompressedtexture (GLenum target, GLenum subtarget, GLenum format, int w, int h, uchar *data, int align, int blocksize, int levels, bool mipmap)
void setuptexparameters (int tnum, void *pixels, int clamp, int filter, GLenum format, GLenum target)
void createtexture (int tnum, int w, int h, void *pixels, int clamp, int filter, GLenum component, GLenum subtarget, int pw, int ph, int pitch, bool resize, GLenum format)
void createcompressedtexture (int tnum, int w, int h, uchar *data, int align, int blocksize, int levels, int clamp, int filter, GLenum format, GLenum subtarget)
Texture * registertexture (const char *name)
Registers a texture to the texture registry, so it wont be loaded twice (but looked up the other time).
Texture * gettexture (const char *name)
Receives a texture from the hashtable of all loaded textures if name is equal.
int texalign (void *data, int w, int bpp)
Texture * newtexture (Texture *t, const char *rname, ImageData &s, int clamp, bool mipit, bool canreduce, bool transient, int compress)
static vec parsevec (const char *arg)
VAR (usedds, 0, 1, 1)
VAR (scaledds, 0, 2, 4)
bool texturedata (ImageData &d, const char *tname, Slot::Tex *tex, bool msg, int *compress)
uchar * loadalphamask (Texture *t)
Texture * textureload (const char *name, int clamp, bool mipit, bool msg, bool threadsafe)
bool settexture (const char *name, int clamp)
void cleanuptexture (Texture *t)
Clean up texture t: delete texture from gpu, only remove from registry if transient.
void cleanuptextures ()
bool reloadtexture (const char *name)
bool reloadtexture (Texture &tex)
void reloadtex (char *name)
COMMAND (reloadtex,"s")
void reloadtextures ()
bool loadimage (const char *filename, ImageData &image)
Variables
std::unordered_map
< std::string, Texture > textures
Texture * notexture = nullptr
Global used to specify this texture has not be found.
Detailed Description
Main texture loading and organizing routines.
Macro Definition Documentation
#define PARSETEXCOMMANDS (cmds)
Value:
const char *cmd = NULL, *end = NULL, *arg[4] = { NULL, NULL, NULL, NULL }; \
            cmd = &cmds[1]; \
            end = strchr(cmd, '>'); \
            if(!end) break; \
            cmds = strchr(cmd, '<'); \
            size_t len = strcspn(cmd, ":,><"); \
            loopi(4) \
            { \
                arg[i] = strchr(i ? arg[i-1] : cmd, i ? ',' : ':'); \
                if(!arg[i] || arg[i] >= end) arg[i] = ""; \
                else arg[i]++; \
            }
Referenced by texturedata().
Function Documentation
void cleanuptexture (Texture * t)
Clean up texture t: delete texture from gpu, only remove from registry if transient.
References Texture::alphamask, DELETEA, Texture::id, Texture::name, Texture::TRANSIENT, and Texture::type.
Referenced by cleanuptextures(), and clearenvmaps().
void cleanuptextures ()
References cleanupmaterialslots(), cleanupslots(), cleanuptexture(), cleanupvslots(), and clearenvmaps().
Referenced by resetgl().
COMMAND (gendds , "ss")
COMMAND (flipnormalmapy , "ss")
COMMAND (mergenormalmaps , "ss")
COMMAND (reloadtex , "s")
void createcompressedtexture (int tnum, int w, int h, uchar * data, int align, int blocksize, int levels, int clamp, int filter, GLenum format, GLenum subtarget)
References GLenum(), setuptexparameters(), ai::target(), and uploadcompressedtexture().
Referenced by cubemaploadwildcard(), and newtexture().
void createtexture (int tnum, int w, int h, void * pixels, int clamp, int filter, GLenum component, GLenum subtarget, int pw, int ph, int pitch, bool resize, GLenum format)
References compressedformat(), GL_DEPTH24_STENCIL8, GL_DEPTH_STENCIL, GL_R16, GL_R16F, GL_R32F, GL_R8, GL_RG, GL_RG16, GL_RG16F, GL_RG32F, GL_RG8, GL_RGB16F, GL_RGB32F, GL_RGBA16F, GL_RGBA32F, GL_UNSIGNED_INT_24_8, GLenum(), resizetexture(), setuptexparameters(), ai::target(), and uploadtexture().
Referenced by addmotionblur(), allocatepostfxtex(), cubemaploadwildcard(), genenvmap(), genlightmaptexs(), genreservedlightmaptexs(), BlendBrush::gentex(), genwatertex(), newtexture(), recorder::readbuffer(), setfullbrightlevel(), rendertarget::setup(), rendertarget::setupblur(), show_calclight_progress(), and updatelightmap().
Texture* gettexture (const char * name)
Receives a texture from the hashtable of all loaded textures if name is equal.
Warning
not threadsafe.
References copystring(), and path().
Referenced by Slot::combinetextures(), cubemaploadwildcard(), gendds(), Slot::loadthumbnail(), reloadtex(), reloadtexture(), and textureload().
uchar* loadalphamask (Texture * t)
References Texture::ALPHA, Texture::alphamask, ImageData::bpp, ImageData::compressed, ImageData::data, ImageData::h, loop, Texture::name, ImageData::pitch, texturedata(), Texture::type, and ImageData::w.
Referenced by animmodel::skin::preloadBIH(), and BIH::triintersect().
bool loadimage (const char * filename, ImageData & image)
References loadsurface(), path(), and ImageData::wrap().
Referenced by addblendbrush(), flipnormalmapy(), and mergenormalmaps().
Texture* newtexture (Texture * t, const char * rname, ImageData & s, int clamp, bool mipit, bool canreduce, bool transient, int compress)
References ImageData::align, Texture::ALPHA, alphaformat(), ImageData::bpp, Texture::bpp, ImageData::calclevelsize(), Texture::clamp, ImageData::compressed, Texture::COMPRESSED, compressedformat(), createcompressedtexture(), createtexture(), ImageData::data, format(), formatsize(), GLenum(), ImageData::h, Texture::h, hwtexsize, Texture::id, Texture::IMAGE, ImageData::levels, loopi(), maxtexsize, inexor::rpc::min(), Texture::mipmap, ImageData::pitch, reducefilter, registertexture(), resizetexture(), Texture::STUB, anonymous_namespace{utilTest.cpp}::t(), texformat(), texreduce, Texture::TRANSIENT, Texture::type, uncompressedformat(), ImageData::w, Texture::w, Texture::xs, and Texture::ys.
Referenced by Slot::combinetextures(), Slot::loadthumbnail(), reloadtexture(), and textureload().
static vec parsevec (const char * arg) static
Referenced by texturedata().
Texture* registertexture (const char * name)
Registers a texture to the texture registry, so it wont be loaded twice (but looked up the other time).
References copystring(), Texture::name, newstring(), path(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by cubemaploadwildcard(), and newtexture().
void reloadtex (char * name)
References Texture::alphamask, DELETEA, gettexture(), Texture::id, Log, reloadtexture(), inexor::util::log_manager::std, anonymous_namespace{utilTest.cpp}::t(), Texture::TRANSIENT, and Texture::type.
Referenced by gendds().
bool reloadtexture (const char * name)
References gettexture(), reloadtexture(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by reloadfonts(), reloadtex(), reloadtexture(), reloadtextures(), and resetgl().
bool reloadtexture (Texture & tex)
References Texture::clamp, tiger::compress(), Texture::CUBEMAP, cubemaploadwildcard(), Texture::id, Texture::IMAGE, Texture::mipmap, Texture::name, newtexture(), texturedata(), Texture::TYPE, and Texture::type.
void reloadtextures ()
References loadprogress, and reloadtexture().
Referenced by resetgl().
bool settexture (const char * name, int clamp)
References Texture::id, notexture, anonymous_namespace{utilTest.cpp}::t(), and textureload().
Referenced by game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), gl_rendercefmouse(), game::setbliptex(), and game::setradartex().
void setuptexcompress ()
References GLenum(), texcompressquality, and usetexcompress.
Referenced by gendds(), and gl_init().
void setuptexparameters (int tnum, void * pixels, int clamp, int filter, GLenum format, GLenum target)
References aniso, bilinear, hasAF, hwmaxaniso, inexor::rpc::min(), and trilinear.
Referenced by createcompressedtexture(), createtexture(), and drawminimap().
int texalign (void * data, int w, int bpp)
Referenced by genenvmap(), recorder::readbuffer(), screenshot(), show_calclight_progress(), and uploadtexture().
bool texturedata (ImageData & d, const char * tname, Slot::Tex * tex, bool msg, int * compress)
References canloadsurface(), tiger::compress(), ImageData::compressed, copystring(), ImageData::data, recorder::file, formatstring(), ImageData::h, loaddds(), loadprogress, loadsurface(), Log, matchstring(), inexor::rpc::max(), Slot::Tex::name, PARSETEXCOMMANDS, parsevec(), path(), renderprogress(), scaleimage(), inexor::util::log_manager::std, TEX_NORMAL, texagrad(), texblur(), texcolorify(), texcolormask(), texdup(), texformat(), texgrey(), texmad(), texmix(), texnormal(), texoffset(), texpremul(), texreorient(), texrotate(), Slot::Tex::type, ImageData::w, and ImageData::wrap().
Referenced by Slot::combinetextures(), cubemaploadwildcard(), loadalphamask(), Slot::loadlayermask(), Slot::loadthumbnail(), reloadtexture(), and textureload().
Texture* textureload (const char * name, int clamp = 0, bool mipit = true, bool msg = true, bool threadsafe = false)
Parameters
name Name of texture
clamp the last pixel of texture image will be stretched to infinity
mipit specifies whether mipmap (lower quality versions; usually used when far away or small) textures should be created.
msg specifies whether a renderprogress bar should be displayed while loading. Always off if threadsafe = true.
threadsafe if true, the texture wont be automatically registerd to the global texture registry, you need to check whether it is loaded via gettexture beforehand in a nonthreaded environment and register it afterwards with registertexture.
References tiger::compress(), copystring(), gettexture(), newtexture(), notexture, anonymous_namespace{utilTest.cpp}::t(), and texturedata().
Referenced by bind_bomb_items_texture(), bind_items_texture(), gui::button_(), draw_g3d_cursor(), drawdamagescreen(), gui::drawskin(), fonttex(), gendds(), gengrassquads(), guiimage(), gui::icon_(), decalrenderer::init(), blobrenderer::init(), gui::line_(), md5::md5mesh::load(), load_world(), loadcaustics(), loadcrosshair(), loadsky(), loadskyoverlay(), main(), gui::modelpreview(), newfont(), gui::playerpreview(), gui::prefabpreview(), gui::previewslot(), flarerenderer::render(), listrenderer::render(), varenderer< T >::render(), renderbackground(), renderprogress(), modelcommands< MDL, struct MDL::vertmesh >::setbumpmap(), modelcommands< MDL, struct MDL::vertmesh >::setskin(), and settexture().
void uploadcompressedtexture (GLenum target, GLenum subtarget, GLenum format, int w, int h, uchar * data, int align, int blocksize, int levels, bool mipmap)
References glCompressedTexImage1D_, glCompressedTexImage2D_, hwcubetexsize, hwtexsize, loopi(), inexor::rpc::max(), maxtexsize, and inexor::rpc::min().
Referenced by createcompressedtexture().
void uploadtexture (GLenum target, GLenum internal, int tw, int th, GLenum format, GLenum type, void * pixels, int pw, int ph, int pitch, bool mipmap)
References formatsize(), loopi(), inexor::rpc::max(), scaletexture(), and texalign().
Referenced by createtexture().
VAR (usedds , 0 , 1 , 1)
VAR (scaledds , 0 , 2 , 4)
Variable Documentation
Texture* notexture = nullptr
Global used to specify this texture has not be found.
Referenced by calctexgen(), changeslottmus(), changetexgen(), Slot::combinetextures(), drawenvboxface(), drawenvoverlay(), fonttex(), gendds(), gengrassquads(), getwaterfalltex(), texturegui::gui(), guiimage(), md5::md5mesh::load(), md2::load(), loadcrosshair(), md3::loaddefaultparts(), obj::loaddefaultparts(), loadskin(), loadsky(), loadskyoverlay(), Slot::loadthumbnail(), main(), animmodel::skin::masked(), newfont(), gui::previewslot(), renderbackground(), rendermaterials(), rendertexturepanel(), renderwater(), resetgl(), settexture(), setupwaterfallrefract(), textureload(), writecrosshairs(), and writeobj().
std::unordered_map<std::string, Texture> textures