Inexor: inexor/shared/tools.hpp File Reference
tools.hpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <algorithm>
#include <cstddef>
#include <map>
#include <new>
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedTree.hpp"
#include "inexor/network/legacy/cube_network.hpp"
#include "inexor/shared/cube_endian.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_unicode.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/util/random.hpp"
Functions
static int bitscan (uint mask)
Search the mask data from least significant bit(LSB) to the most significant bit(MSB) for a set bit(1).
int rnd (int Rmax)
Function alias. Should be replaced inline actually!
float rndscale (float Rmax)
float detrnd (int seed, int Rmax)
Function Documentation
static int bitscan (uint mask) inline static
Search the mask data from least significant bit(LSB) to the most significant bit(MSB) for a set bit(1).
Returns
the position of first set bit (1) found.
Referenced by selgridmap().
float detrnd (int seed, int Rmax) inline
Referenced by renderlightning(), and textrenderer::renderpart().
int rnd (int Rmax) inline
Function alias. Should be replaced inline actually!
Referenced by aiman::addai(), capturemode_common::addbase(), decalrenderer::adddecal(), varenderer< T >::addpart(), game::ctfclientmode::aicheck(), game::bounced(), calclightningjitter(), server::checkvotes(), inexor::sound::soundconfig::chooseslot(), ai::aiinfo::clean(), server::clientconnect(), game::damaged(), game::deathstate(), server::collectservermode::deposittokens(), server::collectservermode::droptokens(), entinmap(), game::explode(), findplayerspawn(), generategrass(), ai::getaimpos(), ai::hastarget(), game::hit(), server::hideandseekservermode::initplayers(), ai::jumpto(), ai::linkwaypoint(), makeparticles(), game::newbouncer(), particle_trail(), game::ctfclientmode::pickholdspawn(), game::captureclientmode::pickteamspawn(), ai::process(), server::bombservermode::pushentity(), ai::randomlink(), ai::randomnode(), regularflame(), regularshape(), regularsplash(), game::renderbouncers(), ai::setup(), game::shoot(), game::spawnbouncer(), server::ctfservermode::spawnflag(), game::spawnnextsplinter(), splash(), and TEST().
float rndscale (float Rmax) inline
Referenced by game::offsetray(), regularflame(), and regularshape().