Inexor: inexor/engine/water.hpp File Reference
water.hpp File Reference
#include "inexor/engine/material.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/geom.hpp"
Macros
#define GETMATIDXVAR(name, var, type)
Functions
const bvec & getwatercolor (int mat)
const bvec & getwaterfallcolor (int mat)
int getwaterfog (int mat)
const bvec & getlavacolor (int mat)
int getlavafog (int mat)
const bvec & getglasscolor (int mat)
void cleanreflections ()
void queryreflections ()
void drawreflections ()
void renderwater ()
void renderlava (const materialsurface &m, Texture *tex, float scale)
void loadcaustics (bool force=false)
void preloadwatershaders (bool force=false)
Variables
int refracting
int refractfog
bool reflecting
bool fading
bool fogging
float reflectz
SharedVar< int > reflectdist
SharedVar< int > vertwater
SharedVar< int > waterrefract
SharedVar< int > waterreflect
SharedVar< int > waterfade
SharedVar< int > caustics
SharedVar< int > waterfallrefract
Macro Definition Documentation
#define GETMATIDXVAR (name, var, type)
Value:
type get##name##var(int mat) \
    { \
        switch(mat&MATF_INDEX) \
        { \
            default: case 0: return name##var; \
            case 1: return name##2##var; \
            case 2: return name##3##var; \
            case 3: return name##4##var; \
        } \
    }
Function Documentation
void cleanreflections ()
References cleanreflection(), glDeleteFramebuffers_, glDeleteRenderbuffers_, loopi(), MAXREFLECTIONS, reflectiondb, reflectionfb, reflections, and waterfallrefraction.
Referenced by queryreflections(), resetgl(), and resetmap().
void drawreflections ()
References Reflection::age, calcscissorbox(), camera1, checkquery(), Reflection::depth, drawreflection(), drawtex, DRAWTEX_MINIMAP, editmode, vector< T, MINSIZE >::empty(), f(), getwatercolor(), getwaterfog(), GL_COLOR_ATTACHMENT0, GL_FRAMEBUFFER, glBindFramebuffer_, glFramebufferTexture2D_, Reflection::height, hwtexsize, Reflection::init, loopi(), maskreflection(), Reflection::material, Reflection::matsurfs, MAXREFLECTIONS, physent::o, oqfrags, occludequery::owner, Reflection::prevquery, Reflection::query, reflectionfb, reflections, Reflection::refracttex, restorevfcP(), savevfcP(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, setvfcP(), showmat, Reflection::tex, WATER_OFFSET, waterfade, waterfallrefract, waterfallrefraction, waterreflect, and waterrefract.
Referenced by drawminimap(), and gl_drawframe().
const bvec& getglasscolor (int mat)
Referenced by rendermaterials().
const bvec& getlavacolor (int mat)
Referenced by blendfog(), and blendfogoverlay().
int getlavafog (int mat)
Referenced by blendfog().
const bvec& getwatercolor (int mat)
Referenced by blendfog(), blendfogoverlay(), drawreflections(), makeparticles(), maskreflection(), rendermaterials(), and renderwater().
const bvec& getwaterfallcolor (int mat)
Referenced by makeparticles(), and rendermaterials().
int getwaterfog (int mat)
Referenced by blendfog(), drawreflections(), queryreflections(), rendermaterials(), and renderwater().
void loadcaustics (bool force = false)
References caustics, defformatstring, loopi(), NUMCAUSTICS, textureload(), and useshaderbyname().
Referenced by setupcaustics(), and setupmaterials().
void preloadwatershaders (bool force = false)
References useshaderbyname(), waterfade, waterfallrefract, waterreflect, and waterrefract.
Referenced by setupmaterials().
void queryreflections ()
References addreflection(), addwaterfallrefraction(), Reflection::age, cleanreflections(), drawtex, DRAWTEX_MINIMAP, editmode, getwaterfog(), Reflection::height, hwtexsize, vector< T, MINSIZE >::length(), loopi(), MAT_WATER, materialsurface::material, MATF_VOLUME, Reflection::matsurfs, MAXREFLECTIONS, newquery(), vtxarray::next, O_BOTTOM, O_TOP, OCCLUDE_BB, oqfrags, materialsurface::orient, Reflection::prevquery, Reflection::query, queryreflection(), reflections, rplanes, vector< T, MINSIZE >::setsize(), showmat, materialsurface::skip, VFC_FOGGED, visibleva, waterfallrefract, waterfallrefraction, waterpvsoccluded(), waterreflect, and waterrefract.
Referenced by drawminimap(), and gl_drawframe().
void renderlava (const materialsurface & m, Texture * tex, float scale)
References lastmillis, lavascroll, lavaxk, lavayk, MAT_LAVA, renderwater(), Texture::xs, and Texture::ys.
Referenced by rendermaterials().
void renderwater ()
References Reflection::age, ambientcolor, entity::attr1, entity::attr2, entity::attr3, entity::attr4, modelpreview::camera, camera1, checkquery(), gle::color(), drawtex, DRAWTEX_MINIMAP, editmode, vector< T, MINSIZE >::empty(), gle::end(), ET_LIGHT, f(), getwatercolor(), getwaterfog(), GL_ONE, glActiveTexture_, glaring, GLOBALPARAM, GLOBALPARAMF, Reflection::height, Texture::id, lastmillis, LOCALPARAM, LOCALPARAMF, lookupenvmap(), lookupmaterialslot(), loopi(), loopvj, Reflection::material, Reflection::matsurfs, inexor::rpc::max(), MAXREFLECTIONS, inexor::rpc::min(), vec::mul(), notexture, notextureshader, entity::o, physent::o, oqfrags, occludequery::owner, Reflection::prevquery, Reflection::query, reflections, Reflection::refracttex, renderwater(), rplanes, Shader::set(), setprojtexmatrix(), SETWATERSHADER, showmat, skylightcolor, Slot::sts, Reflection::tex, WATER_OFFSET, waterfade, waterreflect, waterrefract, worldsize, and xtraverts.
Variable Documentation
SharedVar<int> caustics
Referenced by drawreflection(), gl_drawframe(), and loadcaustics().
bool fading
Referenced by dynlight::calccolor(), changeshader(), drawreflection(), drawskybox(), animmodel::render(), renderalphageom(), renderfoggedvas(), and rendergeom().
bool fogging
Referenced by cullmodel(), drawreflection(), and setcamprojmatrix().
SharedVar<int> reflectdist
Referenced by cullmodel(), and renderreflectedmapmodels().
bool reflecting
Referenced by animmodel::skin::bind(), binddepthfxparams(), binddepthfxtex(), calcspherescissor(), canemitparticles(), cullmodel(), drawreflection(), drawskybox(), finddynlights(), generategrass(), flarerenderer::haswork(), isthirdperson(), renderalphageom(), rendergeom(), rendergeommultipass(), rendergrass(), rendermaterials(), rendermodel(), fireballrenderer::renderpart(), renderreflectedgeom(), renderreflectedmapmodels(), rendersky(), sortmaterials(), and fireballrenderer::startrender().
float reflectz
Referenced by calcspherescissor(), cullmodel(), drawreflection(), drawskybox(), enablepolygonoffset(), finddynlights(), findreflectedvas(), generategrass(), renderalphageom(), renderblob(), rendergeom(), rendergeommultipass(), rendergrass(), rendermodel(), fireballrenderer::renderpart(), renderreflectedmapmodels(), renderreflectedskyvas(), renderva(), and sortmaterials().
int refractfog
Referenced by cullmodel(), drawreflection(), renderalphageom(), rendergeom(), rendergeommultipass(), and renderva().
int refracting
Referenced by animmodel::skin::bind(), binddepthfxparams(), binddepthfxtex(), canemitparticles(), cullmodel(), depthfxtexture::dorender(), drawglare(), drawreflection(), drawskybox(), finddynlights(), generategrass(), flarerenderer::haswork(), renderalphageom(), rendergeom(), rendergeommultipass(), rendergrass(), rendermaterials(), rendermodel(), fireballrenderer::renderpart(), renderreflectedmapmodels(), sortmaterials(), and fireballrenderer::startrender().
SharedVar<int> vertwater
Referenced by optimizematsurfs(), queryreflection(), rendermaterials(), and renderwater().
SharedVar<int> waterfade
Referenced by drawreflection(), drawreflections(), genwatertex(), preloadwatershaders(), and renderwater().
SharedVar<int> waterfallrefract
Referenced by drawreflections(), gl_checkextensions(), preloadwatershaders(), queryreflections(), and rendermaterials().
SharedVar<int> waterreflect
Referenced by addreflection(), drawreflections(), preloadwatershaders(), queryreflections(), and renderwater().
SharedVar<int> waterrefract
Referenced by addreflection(), drawreflection(), drawreflections(), genwatertex(), preloadwatershaders(), queryreflections(), and renderwater().