Inexor: inexor/engine/water.cpp File Reference
water.cpp File Reference
#include <SDL_opengl.h>
#include <boost/algorithm/clamp.hpp>
#include <limits.h>
#include <math.h>
#include <string.h>
#include <algorithm>
#include "inexor/engine/glare.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/pvs.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texsettings.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct Reflection
Macros
#define VERTW(vertw, defbody, body)
#define VERTWN(vertw, defbody, body)
#define renderwaterstrips(vertw, z)
#define renderwaterquad(vertwn, z)
#define MAXREFLECTIONS 16
#define WATERVARS(name)
#define LAVAVARS(name)
#define SETWATERSHADER(which, name)
#define GENFACEORIENT(orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERT(orient, vert, mx, my, mz, sx, sy, sz) gle::attribf(mx sx, my sy, mz sz);
Functions
VARFP (waterreflect, 0, 1, 1,{cleanreflections();preloadwatershaders();})
VARFP (waterrefract, 0, 1, 1,{cleanreflections();preloadwatershaders();})
VARFP (waterenvmap, 0, 1, 1,{cleanreflections();preloadwatershaders();})
VARFP (waterfallrefract, 0, 0, 1,{cleanreflections();preloadwatershaders();})
VARP (watersubdiv, 0, 2, 3)
VARP (waterlod, 0, 1, 3)
VERTW (vertwt,{gle::deftexcoord0();},{gle::attribf(v1/8.0f, v2/8.0f);}) VERTWN(vertwtn
VERTW (vertl,{gle::deftexcoord0();},{gle::attribf(lavaxk *(v1+lavascroll), lavayk *(v2+lavascroll));}) VERTWN(vertln
void rendervertwater (int subdiv, int xo, int yo, int z, int size, int mat)
int calcwatersubdiv (int x, int y, int z, int size)
int renderwaterlod (int x, int y, int z, int size, int mat)
void renderflatwater (int x, int y, int z, int rsize, int csize, int mat)
VARFP (vertwater, 0, 1, 1, allchanged())
static void renderwater (const materialsurface &m, int mat=MAT_WATER)
void renderlava (const materialsurface &m, Texture *tex, float scale)
VARP (reflectdist, 0, 2000, 10000)
void setprojtexmatrix (Reflection &ref)
GLuint getwaterfalltex ()
VAR (oqwater, 0, 2, 2)
VARFP (waterfade, 0, 1, 1,{cleanreflections();preloadwatershaders();})
void preloadwatershaders (bool force)
void renderwater ()
void setupwaterfallrefract ()
void cleanreflection (Reflection &ref)
void cleanreflections ()
VARFP (reflectsize, 6, 8, 10, cleanreflections())
void genwatertex (GLuint &tex, GLuint &fb, GLuint &db, bool refract=false)
void addwaterfallrefraction (materialsurface &m)
void addreflection (materialsurface &m)
static void drawmaterialquery (const materialsurface &m, float offset, float border=0, float reflect=-1)
void drawreflection (float z, bool refract, int fogdepth=-1, const bvec &col=bvec(0, 0, 0))
void queryreflection (Reflection &ref, bool init)
void queryreflections ()
VARP (maxreflect, 1, 2, 8)
VAR (maskreflect, 0, 2, 16)
void maskreflection (Reflection &ref, float offset, bool reflect, bool clear=false)
VAR (reflectscissor, 0, 1, 1)
VAR (reflectvfc, 0, 1, 1)
static bool calcscissorbox (Reflection &ref, int size, vec &clipmin, vec &clipmax, int &sx, int &sy, int &sw, int &sh)
VARR (refractclear, 0, 0, 1)
void drawreflections ()
Variables
static int wx1
static int wy1
static int wx2
static int wy2
static int wsize
static float whscale
static float whoffset
static float lavaxk = 1.0f
static float lavayk = 1.0f
static float lavascroll = 0.0f
Reflection reflections [MAXREFLECTIONS]
Reflection waterfallrefraction
GLuint reflectionfb = 0
GLuint reflectiondb = 0
int rplanes = 0
int refracting = 0
int refractfog = 0
bvec refractcolor (0, 0, 0)
bool reflecting = false
bool fading = false
bool fogging = false
float reflectz = 1e16f
Macro Definition Documentation
#define GENFACEORIENT (orient, v0, v1, v2, v3) case orient: v0 v1 v2 v3 break;
#define GENFACEVERT (orient, vert, mx, my, mz, sx, sy, sz) gle::attribf(mx sx, my sy, mz sz);
#define LAVAVARS (name)
Value:
bvec name##color(0xFF, 0x40, 0x00); \
    HVARFR(name##colour, 0, 0xFF4000, 0xFFFFFF, \
    { \
        if(!name##colour) name##colour = 0xFF4000; \
        name##color = bvec((name##colour>>16)&0xFF, (name##colour>>8)&0xFF, name##colour&0xFF); \
    }); \
    VARR(name##fog, 0, 50, 10000);
#define MAXREFLECTIONS 16
Referenced by addreflection(), cleanreflections(), drawreflections(), queryreflections(), and renderwater().
#define renderwaterquad (vertwn, z)
Value:
{ \
        if(gle::attribbuf.empty()) { def##vertwn(); gle::begin(GL_QUADS); } \
        vertwn(x, y, z); \
        vertwn(x+rsize, y, z); \
        vertwn(x+rsize, y+csize, z); \
        vertwn(x, y+csize, z); \
        xtraverts += 4; \
    }
Referenced by renderflatwater().
#define renderwaterstrips (vertw, z)
Value:
{ \
    def##vertw(); \
    gle::begin(GL_TRIANGLE_STRIP, 2*(wy2-wy1 + 1)*(wx2-wx1)/subdiv); \
    for(int x = wx1; x<wx2; x += subdiv) \
    { \
        vertw(x,        wy1, z); \
        vertw(x+subdiv, wy1, z); \
        for(int y = wy1; y<wy2; y += subdiv) \
        { \
            vertw(x,        y+subdiv, z); \
            vertw(x+subdiv, y+subdiv, z); \
        } \
        gle::multidraw(); \
    } \
    xtraverts += gle::end(); \
}
Referenced by rendervertwater().
#define SETWATERSHADER (which, name)
Value:
do { \
        static Shader *name##shader = NULL; \
        if(!name##shader) name##shader = lookupshaderbyname(#name); \
        which##shader = name##shader; \
    } while(0)
Referenced by renderwater().
#define VERTW (vertw, defbody, body)
Value:
static inline void def##vertw() \
    { \
        gle::defvertex(); \
        defbody; \
    } \
    static inline void vertw(float v1, float v2, float v3) \
    { \
        float angle = (v1-wx1)*(v2-wy1)*(v1-wx2)*(v2-wy2)*whscale+whoffset; \
        float s = angle - int(angle) - 0.5f; \
        s *= 8 - fabs(s)*16; \
        float h = WATER_AMPLITUDE*s-WATER_OFFSET; \
        gle::attribf(v1, v2, v3+h); \
        body; \
    }
#define VERTWN (vertw, defbody, body)
Value:
static inline void def##vertw() \
    { \
        gle::defvertex(); \
        defbody; \
    } \
    static inline void vertw(float v1, float v2, float v3) \
    { \
        float h = -WATER_OFFSET; \
        gle::attribf(v1, v2, v3+h); \
        body; \
    }
#define WATERVARS (name)
Value:
bvec name##color(0x14, 0x46, 0x50), name##fallcolor(0, 0, 0); \
    HVARFR(name##colour, 0, 0x144650, 0xFFFFFF, \
    { \
        if(!name##colour) name##colour = 0x144650; \
        name##color = bvec((name##colour>>16)&0xFF, (name##colour>>8)&0xFF, name##colour&0xFF); \
    }); \
    VARR(name##fog, 0, 150, 10000); \
    VARR(name##spec, 0, 150, 1000); \
    HVARFR(name##fallcolour, 0, 0, 0xFFFFFF, \
    { \
        name##fallcolor = bvec((name##fallcolour>>16)&0xFF, (name##fallcolour>>8)&0xFF, name##fallcolour&0xFF); \
    });
Function Documentation
void addreflection (materialsurface & m)
References vector< T, MINSIZE >::add(), Reflection::age, Reflection::depth, drawtex, DRAWTEX_MINIMAP, genwatertex(), Reflection::height, Reflection::init, loopi(), materialsurface::material, Reflection::material, Reflection::matsurfs, inexor::rpc::max(), MAXREFLECTIONS, materialsurface::o, Reflection::prevquery, reflectiondb, reflectionfb, reflections, Reflection::refracttex, rplanes, vector< T, MINSIZE >::setsize(), Reflection::tex, waterreflect, and waterrefract.
Referenced by queryreflections().
void addwaterfallrefraction (materialsurface & m)
References vector< T, MINSIZE >::add(), Reflection::age, genwatertex(), Reflection::height, Reflection::init, MAT_WATER, Reflection::material, Reflection::matsurfs, reflectiondb, reflectionfb, Reflection::refracttex, vector< T, MINSIZE >::setsize(), and waterfallrefraction.
Referenced by queryreflections().
static bool calcscissorbox (Reflection & ref, int size, vec & clipmin, vec & clipmax, int & sx, int & sy, int & sw, int & sh) static
References C, camprojmatrix, materialsurface::csize, dimension, f(), loopi(), loopj, loopvj, Reflection::matsurfs, inexor::rpc::max(), inexor::rpc::min(), materialsurface::o, materialsurface::orient, R, materialsurface::rsize, anonymous_namespace{utilTest.cpp}::t(), matrix4::transform(), WATER_AMPLITUDE, and WATER_OFFSET.
Referenced by drawreflections().
int calcwatersubdiv (int x, int y, int z, int size)
References camera1, vec::dist(), and physent::o.
Referenced by renderwaterlod().
void cleanreflection (Reflection & ref)
References Reflection::height, Reflection::init, Reflection::material, Reflection::matsurfs, Reflection::prevquery, Reflection::query, Reflection::refracttex, vector< T, MINSIZE >::setsize(), and Reflection::tex.
Referenced by cleanreflections().
void cleanreflections ()
References cleanreflection(), glDeleteFramebuffers_, glDeleteRenderbuffers_, loopi(), MAXREFLECTIONS, reflectiondb, reflectionfb, reflections, and waterfallrefraction.
Referenced by queryreflections(), resetgl(), and resetmap().
static void drawmaterialquery (const materialsurface & m, float offset, float border = 0, float reflect = -1) static
References gle::attribbuf, gle::begin(), materialsurface::csize, GENFACEVERTS, materialsurface::o, materialsurface::orient, and materialsurface::rsize.
Referenced by maskreflection(), and queryreflection().
void drawreflection (float z, bool refract, int fogdepth = -1, const bvec & col = bvec(0, 0, 0))
References physent::aboveeye, aspect, blendfog(), camera1, cammatrix, caustics, matrix4::clip(), clipmatrix, gle::color(), curavatarfov, drawskybox(), modelpreview::end(), physent::eyeheight, f(), fading, farplane, fogging, GLOBALPARAMF, invcammatrix, isthirdperson(), MAT_AIR, inexor::rpc::max(), noclipmatrix, noreflectmatrix, physent::o, matrix4::perspective(), player, popfogcolor(), popfogdist(), projmatrix, pushfogcolor(), pushfogdist(), reflecting, reflectz, matrix4::reflectz(), refractfog, refracting, renderalphageom(), game::renderavatar(), renderdecals(), rendergame(), rendergrass(), rendermaterials(), renderparticles(), renderreflectedgeom(), renderreflectedmapmodels(), setcamprojmatrix(), modelpreview::start(), bvec::tocolor(), matrix4::transposedtransform(), waterfade, and waterrefract.
Referenced by drawreflections().
void drawreflections ()
References Reflection::age, calcscissorbox(), camera1, checkquery(), Reflection::depth, drawreflection(), drawtex, DRAWTEX_MINIMAP, editmode, vector< T, MINSIZE >::empty(), f(), getwatercolor(), getwaterfog(), GL_COLOR_ATTACHMENT0, GL_FRAMEBUFFER, glBindFramebuffer_, glFramebufferTexture2D_, Reflection::height, hwtexsize, Reflection::init, loopi(), maskreflection(), Reflection::material, Reflection::matsurfs, MAXREFLECTIONS, physent::o, oqfrags, occludequery::owner, Reflection::prevquery, Reflection::query, reflectionfb, reflections, Reflection::refracttex, restorevfcP(), savevfcP(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, setvfcP(), showmat, Reflection::tex, WATER_OFFSET, waterfade, waterfallrefract, waterfallrefraction, waterreflect, and waterrefract.
Referenced by drawminimap(), and gl_drawframe().
void genwatertex (GLuint & tex, GLuint & fb, GLuint & db, bool refract = false)
References createtexture(), ai::find(), GL_COLOR_ATTACHMENT0, GL_DEPTH24_STENCIL8, GL_DEPTH_ATTACHMENT, GL_DEPTH_STENCIL, GL_FRAMEBUFFER, GL_FRAMEBUFFER_COMPLETE, GL_RENDERBUFFER, GL_STENCIL_ATTACHMENT, glBindFramebuffer_, glBindRenderbuffer_, glCheckFramebufferStatus_, GLenum(), glFramebufferRenderbuffer_, glFramebufferTexture2D_, glGenFramebuffers_, glGenRenderbuffers_, glRenderbufferStorage_, hasDS, hasstencil, hwtexsize, waterfade, and waterrefract.
Referenced by addreflection(), and addwaterfallrefraction().
GLuint getwaterfalltex ()
References Texture::id, notexture, Reflection::refracttex, and waterfallrefraction.
void maskreflection (Reflection & ref, float offset, bool reflect, bool clear = false)
References gle::color(), drawmaterialquery(), gle::end(), getwatercolor(), hasDS, hasstencil, Reflection::height, loopv, Reflection::material, Reflection::matsurfs, nocolorshader, notextureshader, Shader::set(), bvec::tocolor(), and xtraverts.
Referenced by drawreflections().
void preloadwatershaders (bool force)
References useshaderbyname(), waterfade, waterfallrefract, waterreflect, and waterrefract.
Referenced by setupmaterials().
void queryreflection (Reflection & ref, bool init)
References camera1, drawmaterialquery(), gle::end(), endquery, loopvj, Reflection::matsurfs, nocolorshader, materialsurface::o, physent::o, O_TOP, materialsurface::orient, physent::pitch, Reflection::query, Shader::set(), startquery, vertwater, WATER_AMPLITUDE, WATER_OFFSET, and xtraverts.
Referenced by queryreflections().
void queryreflections ()
References addreflection(), addwaterfallrefraction(), Reflection::age, cleanreflections(), drawtex, DRAWTEX_MINIMAP, editmode, getwaterfog(), Reflection::height, hwtexsize, vector< T, MINSIZE >::length(), loopi(), MAT_WATER, materialsurface::material, MATF_VOLUME, Reflection::matsurfs, MAXREFLECTIONS, newquery(), vtxarray::next, O_BOTTOM, O_TOP, OCCLUDE_BB, oqfrags, materialsurface::orient, Reflection::prevquery, Reflection::query, queryreflection(), reflections, rplanes, vector< T, MINSIZE >::setsize(), showmat, materialsurface::skip, VFC_FOGGED, visibleva, waterfallrefract, waterfallrefraction, waterpvsoccluded(), waterreflect, and waterrefract.
Referenced by drawminimap(), and gl_drawframe().
void renderflatwater (int x, int y, int z, int rsize, int csize, int mat)
References MAT_LAVA, MAT_WATER, and renderwaterquad.
Referenced by renderwater().
void renderlava (const materialsurface & m, Texture * tex, float scale)
References lastmillis, lavascroll, lavaxk, lavayk, MAT_LAVA, renderwater(), Texture::xs, and Texture::ys.
Referenced by rendermaterials().
void rendervertwater (int subdiv, int xo, int yo, int z, int size, int mat)
References ASSERT, f(), lastmillis, MAT_LAVA, MAT_WATER, renderwaterstrips, whoffset, whscale, wsize, wx1, wx2, wy1, and wy2.
Referenced by renderwater(), and renderwaterlod().
static void renderwater (const materialsurface & m, int mat = MAT_WATER) inline static
References materialsurface::csize, drawtex, DRAWTEX_MINIMAP, materialsurface::o, renderflatwater(), rendervertwater(), renderwaterlod(), materialsurface::rsize, and vertwater.
Referenced by drawglare(), drawminimap(), gl_drawframe(), renderlava(), and renderwater().
void renderwater ()
References Reflection::age, ambientcolor, entity::attr1, entity::attr2, entity::attr3, entity::attr4, modelpreview::camera, camera1, checkquery(), gle::color(), drawtex, DRAWTEX_MINIMAP, editmode, vector< T, MINSIZE >::empty(), gle::end(), ET_LIGHT, f(), getwatercolor(), getwaterfog(), GL_ONE, glActiveTexture_, glaring, GLOBALPARAM, GLOBALPARAMF, Reflection::height, Texture::id, lastmillis, LOCALPARAM, LOCALPARAMF, lookupenvmap(), lookupmaterialslot(), loopi(), loopvj, Reflection::material, Reflection::matsurfs, inexor::rpc::max(), MAXREFLECTIONS, inexor::rpc::min(), vec::mul(), notexture, notextureshader, entity::o, physent::o, oqfrags, occludequery::owner, Reflection::prevquery, Reflection::query, reflections, Reflection::refracttex, renderwater(), rplanes, Shader::set(), setprojtexmatrix(), SETWATERSHADER, showmat, skylightcolor, Slot::sts, Reflection::tex, WATER_OFFSET, waterfade, waterreflect, waterrefract, worldsize, and xtraverts.
int renderwaterlod (int x, int y, int z, int size, int mat)
References calcwatersubdiv(), inexor::rpc::min(), and rendervertwater().
Referenced by renderwater().
void setprojtexmatrix (Reflection & ref)
References camprojmatrix, and LOCALPARAM.
Referenced by renderwater(), and setupwaterfallrefract().
void setupwaterfallrefract ()
References Texture::id, notexture, Reflection::refracttex, setprojtexmatrix(), and waterfallrefraction.
Referenced by rendermaterials().
VAR (oqwater , 0 , 2 , 2)
VAR (maskreflect , 0 , 2 , 16)
VAR (reflectscissor , 0 , 1 , 1)
VAR (reflectvfc , 0 , 1 , 1)
VARFP (waterreflect , 0 , 1 , 1 , {cleanreflections();preloadwatershaders();})
VARFP (waterrefract , 0 , 1 , 1 , {cleanreflections();preloadwatershaders();})
VARFP (waterenvmap , 0 , 1 , 1 , {cleanreflections();preloadwatershaders();})
VARFP (waterfallrefract , 0 , 0 , 1 , {cleanreflections();preloadwatershaders();})
VARFP (vertwater , 0 , 1 , 1 , allchanged())
VARFP (waterfade , 0 , 1 , 1 , {cleanreflections();preloadwatershaders();})
VARFP (reflectsize , 6 , 8 , 10 , cleanreflections())
VARP (watersubdiv , 0 , 2 , 3)
VARP (waterlod , 0 , 1 , 3)
VARP (reflectdist , 0 , 2000 , 10000)
VARP (maxreflect , 1 , 2 , 8)
VARR (refractclear , 0 , 0 , 1)
VERTW (vertwt , {gle::deftexcoord0();} , {gle::attribf(v1/8.0f, v2/8.0f);})
VERTW (vertl , {gle::deftexcoord0();} , {gle::attribf(lavaxk *(v1+lavascroll), lavayk *(v2+lavascroll));})
Variable Documentation
bool fading = false
Referenced by dynlight::calccolor(), changeshader(), drawreflection(), drawskybox(), animmodel::render(), renderalphageom(), renderfoggedvas(), and rendergeom().
bool fogging = false
Referenced by cullmodel(), drawreflection(), and setcamprojmatrix().
float lavascroll = 0.0f static
Referenced by renderlava().
float lavaxk = 1.0f static
Referenced by renderlava().
float lavayk = 1.0f static
Referenced by renderlava().
bool reflecting = false
Referenced by animmodel::skin::bind(), binddepthfxparams(), binddepthfxtex(), calcspherescissor(), canemitparticles(), cullmodel(), drawreflection(), drawskybox(), finddynlights(), generategrass(), flarerenderer::haswork(), isthirdperson(), renderalphageom(), rendergeom(), rendergeommultipass(), rendergrass(), rendermaterials(), rendermodel(), fireballrenderer::renderpart(), renderreflectedgeom(), renderreflectedmapmodels(), rendersky(), sortmaterials(), and fireballrenderer::startrender().
GLuint reflectiondb = 0
Referenced by addreflection(), addwaterfallrefraction(), and cleanreflections().
GLuint reflectionfb = 0
Referenced by addreflection(), addwaterfallrefraction(), cleanreflections(), and drawreflections().
Reflection reflections[MAXREFLECTIONS]
Referenced by addreflection(), cleanreflections(), drawreflections(), queryreflections(), and renderwater().
float reflectz = 1e16f
Referenced by calcspherescissor(), cullmodel(), drawreflection(), drawskybox(), enablepolygonoffset(), finddynlights(), findreflectedvas(), generategrass(), renderalphageom(), renderblob(), rendergeom(), rendergeommultipass(), rendergrass(), rendermodel(), fireballrenderer::renderpart(), renderreflectedmapmodels(), renderreflectedskyvas(), renderva(), and sortmaterials().
bvec refractcolor(0, 0, 0)
int refractfog = 0
Referenced by cullmodel(), drawreflection(), renderalphageom(), rendergeom(), rendergeommultipass(), and renderva().
int refracting = 0
Referenced by animmodel::skin::bind(), binddepthfxparams(), binddepthfxtex(), canemitparticles(), cullmodel(), depthfxtexture::dorender(), drawglare(), drawreflection(), drawskybox(), finddynlights(), generategrass(), flarerenderer::haswork(), renderalphageom(), rendergeom(), rendergeommultipass(), rendergrass(), rendermaterials(), rendermodel(), fireballrenderer::renderpart(), renderreflectedmapmodels(), sortmaterials(), and fireballrenderer::startrender().
int rplanes = 0
Referenced by addreflection(), gl_drawhud(), queryreflections(), and renderwater().
Reflection waterfallrefraction
Referenced by addwaterfallrefraction(), cleanreflections(), drawreflections(), getwaterfalltex(), queryreflections(), and setupwaterfallrefract().
float whoffset static
Referenced by rendervertwater().
float whscale static
Referenced by rendervertwater().
int wsize static
Referenced by rendervertwater().
int wx1 static
Referenced by rendervertwater().
int wx2 static
Referenced by rendervertwater().
int wy1 static
Referenced by rendervertwater().
int wy2 static
Referenced by rendervertwater().