Inexor: inexor/engine/world.hpp File Reference
world.hpp File Reference
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
Classes
struct octaheader
octree header structure as its found in the ogz files.
struct compatheader
more intense map file header used when loading.
struct vertex
Macros
#define MAPVERSION 40
#define WATER_AMPLITUDE 0.4f
#define WATER_OFFSET 1.1f
#define TEX_SCALE 8.0f
Enumerations
enum { DEFAULT_SKY = 0, DEFAULT_GEOM }
enum { MATSURF_NOT_VISIBLE = 0, MATSURF_VISIBLE, MATSURF_EDIT_ONLY }
Functions
void entcancel ()
cancel (remove) entity selection
void entitiesinoctanodes ()
void attachentities ()
void freeoctaentities (cube &c)
bool pointinsel (const selinfo &sel, const vec &o)
void resetmap ()
void startmap (const char *name)
called just after a map load send CRC32 to server
char * entname (entity &e)
bool haveselent ()
undoblock * copyundoents (undoblock *u)
void pasteundoent (int idx, const entity &ue)
void pasteundoents (undoblock *u)
bool emptymap (int factor, bool force, const char *mname="", bool usecfg=true)
bool enlargemap (bool force)
int findentity (int type, int index=0, int attr1=-1, int attr2=-1)
void findents (int low, int high, bool notspawned, const vec &pos, const vec &radius, vector< int > &found)
extentity * newentity (bool local, const vec &o, int type, int v1, int v2, int v3, int v4, int v5, int &idx)
void attachentity (extentity &e)
bool modifyoctaent (int flags, int id)
void mpeditent (int i, const vec &o, int type, int attr1, int attr2, int attr3, int attr4, int attr5, bool local)
vec getselpos ()
int getworldsize ()
int getmapversion ()
void renderentcone (const extentity &e, const vec &dir, float radius, float angle)
void renderentarrow (const extentity &e, const vec &dir, float radius)
void renderentattachment (const extentity &e)
void renderentsphere (const extentity &e, float radius)
void renderentring (const extentity &e, float radius, int axis=0)
Variables
SharedVar< char * > maptitle
vector< int > outsideents
vector< int > entgroup
SharedVar< int > worldscale
SharedVar< int > worldsize
SharedVar< int > mapversion
Class Documentation
struct octaheader
octree header structure as its found in the ogz files.
ogz files are gz-compressed as the name suggests.
Class Members
int blendmap
int headersize
int lightmaps
char magic[4]
int numents
int numpvs
int numvars
int numvslots
int version
int worldsize
struct compatheader
more intense map file header used when loading.
Class Members
uchar ambient
uchar blendmap
uchar bumperror
int headersize
uchar lavacolour[3]
uchar lerpangle
uchar lerpsubdiv
uchar lerpsubdivsize
int lighterror
int lightlod
int lightmaps
int lightprecision
char magic[4]
char maptitle[128]
int numents
int numpvs
uchar reserved[10]
uchar skylight[3]
int version
uchar watercolour[3]
uchar waterfallcolour[3]
int worldsize
struct vertex
Class Members
svec2 lm
bvec4 norm
vec pos
bvec4 tangent
vec2 tc
Macro Definition Documentation
#define MAPVERSION 40
Referenced by load_world(), loadents(), and save_world().
#define TEX_SCALE 8.0f
Referenced by calctexgen(), and rendermaterials().
#define WATER_AMPLITUDE 0.4f
Referenced by calcscissorbox(), queryreflection(), rendermaterials(), and renderwaterfall().
#define WATER_OFFSET 1.1f
Referenced by calcscissorbox(), drawreflections(), gl_drawframe(), queryreflection(), rendermaterials(), renderwater(), renderwaterfall(), and setupmaterials().
Enumeration Type Documentation
anonymous enum
Enumerator
DEFAULT_SKY
DEFAULT_GEOM
anonymous enum
Enumerator
MATSURF_NOT_VISIBLE
MATSURF_VISIBLE
MATSURF_EDIT_ONLY
Function Documentation
void attachentities ()
References attachentity(), entities::ents, entities::getents(), and loopv.
Referenced by load_world().
void attachentity (extentity & e)
References extentity::attached, entities::attachent(), detachentity(), vec::dist(), entities::ents, ET_GAMESPECIFIC, ET_LIGHT, ET_SPOTLIGHT, entities::getents(), loopv, entities::mayattach(), entity::o, and entity::type.
Referenced by attachent(), attachentities(), mpeditent(), and game::parsemessages().
undoblock* copyundoents (undoblock * u)
References entadd(), entcancel(), entgroup, undoblock::ents(), ET_EMPTY, loopi(), newundoent(), undoblock::numents, and vector< T, MINSIZE >::removeobj().
Referenced by swapundo().
bool emptymap (int factor, bool force, const char * mname = "", bool usecfg = true)
References allchanged(), clearmainmenu(), inexor::util::log_manager::edit, editmode, execfile(), F_EMPTY, freeocta(), identflags, IDF_OVERRIDDEN, initlights(), Log, loopi(), newcubes(), resetmap(), setvar(), vector< T, MINSIZE >::shrink(), solidfaces, splitocta(), startmap(), texmru, worldroot, worldscale, and worldsize.
Referenced by game::changemapserv(), main(), newmap(), and game::parsemessages().
bool enlargemap (bool force)
References allchanged(), cube::children, inexor::util::log_manager::edit, editmode, enlargeblendmap(), F_EMPTY, vector< T, MINSIZE >::length(), Log, loopi(), newcubes(), outsideents, vector< T, MINSIZE >::pop(), removeentity(), solidfaces, splitocta(), worldroot, worldscale, and worldsize.
Referenced by mapenlarge(), and game::parsemessages().
void entcancel ()
cancel (remove) entity selection
References entgroup, and vector< T, MINSIZE >::shrink().
Referenced by cancelsel(), copyundoents(), delent(), and entpaste().
void entitiesinoctanodes ()
References entities::ents, entities::getents(), loopv, modifyoctaent(), and MODOE_ADD.
Referenced by allchanged(), commitchanges(), and load_world().
char* entname (entity & e)
References concatstring(), copystring(), entities::entname(), entities::entnameinfo(), and entity::type.
Referenced by updateparticles().
int findentity (int type, int index = 0, int attr1 = -1, int attr2 = -1)
References entity::attr1, entity::attr2, entities::ents, entities::getents(), vector< T, MINSIZE >::length(), loopj, and entity::type.
Referenced by findplayerspawn(), and entities::teleport().
void findents (int low, int high, bool notspawned, const vec & pos, const vec & radius, vector< int > & found)
References hmap::br, cube::children, cubeext::ents, cube::ext, findents(), octaentsize, octastep, worldroot, worldscale, and worldsize.
void freeoctaentities (cube & c)
References vector< T, MINSIZE >::empty(), cubeext::ents, cube::ext, entities::getents(), octaentities::mapmodels, octaentities::other, vector< T, MINSIZE >::pop(), and removeentity().
Referenced by discardchildren(), modifyoctaentity(), and readychanges().
int getmapversion ()
References mapversion.
vec getselpos ()
References entgroup, enthover, entities::ents, entities::getents(), vector< T, MINSIZE >::inrange(), vector< T, MINSIZE >::length(), materialsurface::o, selinfo::o, and sel.
Referenced by game::gotosel().
int getworldsize ()
References worldsize.
Referenced by ai::findorientation(), ai::getweight(), ai::movewaypoints(), and game::parsemessages().
bool haveselent ()
References entgroup, and vector< T, MINSIZE >::length().
Referenced by entautoview(), entdrag(), and noedit().
bool modifyoctaent (int flags, int id)
References entities::ents, entities::getents(), vector< T, MINSIZE >::inrange(), and modifyoctaent().
void mpeditent (int i, const vec & o, int type, int attr1, int attr2, int attr3, int attr4, int attr5, bool local)
References addentity(), attachentity(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, detachentity(), entities::editent(), entities::ents, entities::getents(), vector< T, MINSIZE >::length(), MAXENTS, newentity(), materialsurface::o, entity::o, removeentity(), and entity::type.
Referenced by game::parsemessages().
extentity* newentity (bool local, const vec & o, int type, int v1, int v2, int v3, int v4, int v5, int & idx)
References vector< T, MINSIZE >::add(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, camera1, entitylight::color, entities::deleteentity(), entitylight::dir, inexor::util::log_manager::edit, entities::ents, ET_EMPTY, ET_MAPMODEL, ET_PLAYERSTART, entities::fixentity(), entities::getents(), vector< T, MINSIZE >::inrange(), keepents, vector< T, MINSIZE >::length(), extentity::light, Log, MAXENTS, entities::newentity(), materialsurface::o, entity::o, entity::reserved, entity::type, and physent::yaw.
Referenced by entpaste(), mpeditent(), newent(), newentity(), and game::parsemessages().
void pasteundoent (int idx, const entity & ue)
References vector< T, MINSIZE >::add(), efocus, entedit, entities::ents, ET_EMPTY, entities::getents(), vector< T, MINSIZE >::length(), MAXENTS, entities::newentity(), and entity::type.
Referenced by unpackundo().
void pasteundoents (undoblock * u)
References entedit, undoblock::ents(), loopi(), and undoblock::numents.
Referenced by pasteundo().
bool pointinsel (const selinfo & sel, const vec & o)
References selinfo::grid, selinfo::o, and selinfo::s.
void renderentarrow (const extentity & e, const vec & dir, float radius)
References vec::add(), gle::attrib(), gle::begin(), gle::end(), f(), loopi(), inexor::rpc::min(), vec::mul(), entity::o, vec::orthogonal(), rotate(), ai::target(), and xtraverts.
Referenced by entities::entradius(), and renderentradius().
void renderentattachment (const extentity & e)
References extentity::attached, gle::attrib(), gle::begin(), gle::end(), entity::o, and xtraverts.
Referenced by renderentradius().
void renderentcone (const extentity & e, const vec & dir, float radius, float angle)
References vec::add(), gle::attrib(), gle::begin(), gle::end(), f(), loopi(), vec::mul(), entity::o, vec::orthogonal(), RAD, rotate(), and xtraverts.
Referenced by renderentradius().
void renderentring (const extentity & e, float radius, int axis = 0)
References gle::attrib(), gle::begin(), gle::end(), loopi(), entity::o, sincos360, and xtraverts.
Referenced by entities::entradius(), and renderentsphere().
void renderentsphere (const extentity & e, float radius)
References loopk, and renderentring().
Referenced by renderentradius().
void resetmap ()
References cancelsel(), cleanreflections(), cleardecals(), entities::clearents(), clearmapcrc(), inexor::sound::clearmapsounds(), clearoverrides(), clearparticles(), clearpvs(), clearsleep(), clearslots(), outsideents, pruneundos(), resetblendmap(), resetlightmaps(), and vector< T, MINSIZE >::setsize().
Referenced by emptymap(), and load_world().
void startmap (const char * name)
called just after a map load send CRC32 to server
See Also
sendmapinfo
send CRC32 checksum of my current map yeah if you would like to cheat this is the code passage you must modify you little ****** *
References ai::clearwaypoints(), game::clientmap, copystring(), findplayerspawn(), game::player1, entities::resetspawns(), game::respawnent, ai::savewaypoints(), game::sendmapinfo(), and game::startmap().
Referenced by emptymap(), load_world(), and startmap().
Variable Documentation
vector<int> entgroup
Referenced by copyundoents(), entadd(), entautoview(), entcancel(), entcopy(), entdrag(), enttoggle(), getselpos(), haveselent(), hoveringonent(), newundoent(), renderentselection(), and updateparticles().
SharedVar<char*> maptitle
Referenced by load_world().
SharedVar<int> mapversion
Referenced by getmapversion(), load_world(), and loadc().
vector<int> outsideents
Referenced by disttooutsideent(), enlargemap(), modifyoctaent(), resetmap(), and shrinkmap().
SharedVar<int> worldscale
Referenced by bboccluded(), emptymap(), enlargemap(), findents(), genprefabmesh(), load_world(), lookupcube(), lookupmaterial(), lookupviewcell(), neighbourcube(), octacollide(), pasteundoblock(), pvsoccluded(), pvsworker::resetlevels(), setblendmaporigin(), and shrinkmap().
SharedVar<int> worldsize