Inexor: inexor/engine/world.cpp File Reference
world.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "SDL_opengl.h"
#include "inexor/client/network.hpp"
#include "inexor/engine/blend.hpp"
#include "inexor/engine/decal.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/pvs.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderparticles.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/engine/worldio.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/fpsgame/fps.hpp"
#include "inexor/fpsgame/player.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/model/model.hpp"
#include "inexor/model/rendermodel.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/sound/sound.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/ui/legacy/menus.hpp"
Macros
#define addimplicit(f) { if(entgroup.empty() && enthover>=0) { entadd(enthover); undonext = (enthover != oldhover); f; entgroup.drop(); } else f; }
#define entfocusv(i, f, v) { int n = efocus = (i); if(n>=0) { extentity &e = *v[n]; f; } }
#define entfocus(i, f) entfocusv(i, f, entities::getents())
#define enteditv(i, f, v)
#define entedit(i, f) enteditv(i, f, entities::getents())
#define addgroup(exp) { vector<extentity *> &ents = entities::getents(); loopv(ents) entfocusv(i, if(exp) entadd(n), ents); }
#define setgroup(exp) { entcancel(); addgroup(exp); }
#define groupeditloop(f) { vector<extentity *> &ents = entities::getents(); entlooplevel++; int _ = efocus; loopv(entgroup) enteditv(entgroup[i], f, ents); efocus = _; entlooplevel--; }
#define groupeditpure(f) { if(entlooplevel>0) { entedit(efocus, f); } else groupeditloop(f); }
#define groupeditundo(f) { makeundoent(); groupeditpure(f); }
#define groupedit(f) { addimplicit(groupeditundo(f)); }
Enumerations
enum { MODOE_ADD = 1<<0, MODOE_UPDATEBB = 1<<1, MODOE_LIGHTENT = 1<<2 }
Functions
VARR (mapversion, 1, MAPVERSION, 0)
VARNR (mapscale, worldscale, 1, 0, 0)
VARNR (mapsize, worldsize, 1, 0, 0)
SVARR (maptitle,"Untitled Map by Unknown")
VAR (octaentsize, 0, 64, 1024)
VAR (entselradius, 0, 2, 10)
VARF (entediting, 0, 0, 1,{if(!entediting){entcancel();efocus=enthover=-1;}})
static void mmboundbox (const entity &e, model *m, vec &center, vec &radius)
static void mmcollisionbox (const entity &e, model *m, vec &center, vec &radius)
bool getentboundingbox (const extentity &e, ivec &o, ivec &r)
void modifyoctaentity (int flags, int id, extentity &e, cube *c, const ivec &cor, int size, const ivec &bo, const ivec &br, int leafsize, vtxarray *lastva=nullptr)
static bool modifyoctaent (int flags, int id, extentity &e)
bool modifyoctaent (int flags, int id)
static void addentity (int id)
static void removeentity (int id)
void freeoctaentities (cube &c)
void entitiesinoctanodes ()
static void findents (octaentities &oe, int low, int high, bool notspawned, const vec &pos, const vec &invradius, vector< int > &found)
static void findents (cube *c, const ivec &o, int size, const ivec &bo, const ivec &br, int low, int high, bool notspawned, const vec &pos, const vec &invradius, vector< int > &found)
void findents (int low, int high, bool notspawned, const vec &pos, const vec &radius, vector< int > &found)
char * entname (entity &e)
bool noentedit ()
bool pointinsel (const selinfo &sel, const vec &o)
bool haveselent ()
void entcancel ()
cancel (remove) entity selection
void entadd (int id)
undoblock * newundoent ()
void makeundoent ()
void detachentity (extentity &e)
VAR (attachradius, 1, 100, 1000)
void attachentity (extentity &e)
void attachentities ()
vec getselpos ()
undoblock * copyundoents (undoblock *u)
void pasteundoent (int idx, const entity &ue)
void pasteundoents (undoblock *u)
void entflip ()
void entrotate (int *cw)
void entselectionbox (const entity &e, vec &eo, vec &es)
VAR (entselsnap, 0, 0, 1)
VAR (entmovingshadow, 0, 1, 1)
void boxs (int orient, vec o, const vec &s, float size)
renders a rectangular box to the target location with faked thick lines
void boxs (int orient, vec o, const vec &s)
renders a rectangular box to the target location
void boxs3D (const vec &o, vec s, int g)
render cube (6 boxes) to target location
bool editmoveplane (const vec &o, const vec &ray, int d, float off, vec &handle, vec &dest, bool first)
move the selection grid (the "plane") along the selection has an origin and can only be moved in 2 dimensions simultaneously
void entdrag (const vec &ray)
VAR (showentradius, 0, 1, 1)
void renderentring (const extentity &e, float radius, int axis)
void renderentsphere (const extentity &e, float radius)
void renderentattachment (const extentity &e)
void renderentarrow (const extentity &e, const vec &dir, float radius)
void renderentcone (const extentity &e, const vec &dir, float radius, float angle)
void renderentradius (extentity &e, bool color)
static void renderentbox (const vec &eo, vec es)
void renderentselection (const vec &o, const vec &ray, bool entmoving)
bool enttoggle (int id)
bool hoveringonent (int ent, int orient)
VAR (entitysurf, 0, 0, 1)
ICOMMAND (entadd,"",(),{if(enthover >=0 &&!noentedit()){if(entgroup.find(enthover)< 0) entadd(enthover);if(entmoving > 1) entmoving=1;}})
ICOMMAND (enttoggle,"",(),{if(enthover< 0||noentedit()||!enttoggle(enthover)){entmoving=0;intret(0);}else{if(entmoving > 1) entmoving=1;intret(1);}})
ICOMMAND (entmoving,"b",(int *n),{if(*n >=0){if(!*n||enthover< 0||noentedit()) entmoving=0;else{if(entgroup.find(enthover)< 0){entadd(enthover);entmoving=1;}else if(!entmoving) entmoving=1;}}intret(entmoving);})
void entpush (int *dir)
VAR (entautoviewdist, 0, 25, 100)
void entautoview (int *dir)
COMMAND (entautoview,"i")
COMMAND (entflip,"")
COMMAND (entrotate,"i")
COMMAND (entpush,"i")
void delent ()
int findtype (char *what)
VAR (entdrop, 0, 2, 3)
bool dropentity (entity &e, int drop=-1)
void dropent ()
void attachent ()
COMMAND (attachent,"")
extentity * newentity (bool local, const vec &o, int type, int v1, int v2, int v3, int v4, int v5, int &idx)
void newentity (int type, int a1, int a2, int a3, int a4, int a5)
void newent (char *what, int *a1, int *a2, int *a3, int *a4, int *a5)
void entcopy ()
void entpaste ()
COMMAND (newent,"siiiii")
COMMAND (delent,"")
COMMAND (dropent,"")
COMMAND (entcopy,"")
COMMAND (entpaste,"")
void entset (char *what, int *a1, int *a2, int *a3, int *a4, int *a5)
void printent (extentity &e, char *buf, int len)
void nearestent ()
ICOMMAND (entget,"",(), entfocus(efocus, string s;printent(e, s, sizeof(s));result(s)))
ICOMMAND (enthavesel,"",(), addimplicit(intret(entgroup.length())))
ICOMMAND (entindex,"",(), intret(efocus))
ICOMMAND (entloop,"e",(uint *body), if(!noentedit()) addimplicit(groupeditloop(((void) e, execute(body)))))
ICOMMAND (entselect,"e",(uint *body), if(!noentedit()) addgroup(e.type!=ET_EMPTY &&entgroup.find(n)< 0 &&executebool(body)))
ICOMMAND (insel,"",(), entfocus(efocus, intret(pointinsel(sel, e.o))))
COMMAND (entset,"siiiii")
COMMAND (nearestent,"")
void enttype (char *type, int *numargs)
void entattr (int *attr, int *val, int *numargs)
COMMAND (enttype,"sN")
COMMAND (entattr,"iiN")
int findentity (int type, int index, int attr1, int attr2)
void findplayerspawn (dynent *d, int forceent, int tag)
void splitocta (cube *c, int size)
void resetmap ()
void startmap (const char *name)
bool emptymap (int scale, bool force, const char *mname, bool usecfg)
bool enlargemap (bool force)
static bool isallempty (cube &c)
void shrinkmap ()
void newmap (int *i)
void mapenlarge ()
COMMAND (newmap,"i")
COMMAND (mapenlarge,"")
COMMAND (shrinkmap,"")
void mapname ()
COMMAND (mapname,"")
void mpeditent (int i, const vec &o, int type, int attr1, int attr2, int attr3, int attr4, int attr5, bool local)
int getworldsize ()
int getmapversion ()
Variables
int efocus = -1
int enthover = -1
int entorient = -1
int oldhover = -1
vector< int > outsideents
selinfo sel
bool havesel
int entlooplevel = 0
bool undonext = true
vector< int > entgroup
int entmoving = 0
static int keepents = 0
int entcopygrid
vector< entity > entcopybuf
int spawncycle = -1
Macro Definition Documentation
#define addgroup (exp) { vector<extentity *> &ents = entities::getents(); loopv(ents) entfocusv(i, if(exp) entadd(n), ents); }
#define addimplicit (f) { if(entgroup.empty() && enthover>=0) { entadd(enthover); undonext = (enthover != oldhover); f; entgroup.drop(); } else f; }
#define entedit (i, f) enteditv(i, f, entities::getents())
Referenced by newentity(), pasteundoent(), and pasteundoents().
#define enteditv (i, f, v)
Value:
{ \
    entfocusv(i, \
    { \
        int oldtype = e.type; \
        removeentity(n);  \
        f; \
        if(oldtype!=e.type) detachentity(e); \
        if(e.type!=ET_EMPTY) { addentity(n); if(oldtype!=e.type) attachentity(e); } \
        entities::editent(n, true); \
    }, v); \
}
#define entfocus (i, f) entfocusv(i, f, entities::getents())
Referenced by entattr(), entautoview(), entcopy(), entdrag(), enttype(), and renderentselection().
#define entfocusv (i, f, v) { int n = efocus = (i); if(n>=0) { extentity &e = *v[n]; f; } }
#define groupedit (f) { addimplicit(groupeditundo(f)); }
Referenced by attachent(), delent(), dropent(), entattr(), entpush(), entset(), and enttype().
#define groupeditloop (f) { vector<extentity *> &ents = entities::getents(); entlooplevel++; int _ = efocus; loopv(entgroup) enteditv(entgroup[i], f, ents); efocus = _; entlooplevel--; }
#define groupeditpure (f) { if(entlooplevel>0) { entedit(efocus, f); } else groupeditloop(f); }
Referenced by entdrag(), and entpush().
#define groupeditundo (f) { makeundoent(); groupeditpure(f); }
Referenced by entflip(), entpaste(), and entrotate().
#define setgroup (exp) { entcancel(); addgroup(exp); }
Enumeration Type Documentation
anonymous enum
Enumerator
MODOE_ADD
MODOE_UPDATEBB
MODOE_LIGHTENT
Function Documentation
static void addentity (int id) inline static
References modifyoctaent(), MODOE_ADD, MODOE_LIGHTENT, and MODOE_UPDATEBB.
Referenced by mpeditent().
void attachent ()
References attachentity(), groupedit, and noentedit().
void attachentities ()
References attachentity(), entities::ents, entities::getents(), and loopv.
Referenced by load_world().
void attachentity (extentity & e)
References extentity::attached, entities::attachent(), detachentity(), vec::dist(), entities::ents, ET_GAMESPECIFIC, ET_LIGHT, ET_SPOTLIGHT, entities::getents(), loopv, entities::mayattach(), entity::o, and entity::type.
Referenced by attachent(), attachentities(), mpeditent(), and game::parsemessages().
void boxs (int orient, vec o, const vec & s, float size)
renders a rectangular box to the target location with faked thick lines
References vec::add(), gle::attrib(), gle::begin(), boxoutline, C, D, hmap::d, hmap::dc, dimcoord, dimension, gle::end(), f(), R, and xtraverts.
Referenced by boxs3D(), rendereditcursor(), and renderentselection().
void boxs (int orient, vec o, const vec & s)
renders a rectangular box to the target location
Parameters
orient cube face orientation index (3 dimensions x 2 directions = 6 possible orientation indices)
o target rendering position
s a constant scalar vector
References gle::attrib(), gle::begin(), boxoutline, C, D, hmap::d, hmap::dc, dimcoord, dimension, gle::end(), f(), R, and xtraverts.
void boxs3D (const vec & o, vec s, int g)
render cube (6 boxes) to target location
Parameters
o selection start vector
s selection end vector
g gridsize
References boxs(), loopi(), and vec::mul().
Referenced by rendereditcursor(), and renderentselection().
COMMAND (entautoview , "i")
COMMAND (entflip , "")
COMMAND (entrotate , "i")
COMMAND (entpush , "i")
COMMAND (attachent , "")
COMMAND (newent , "siiiii")
COMMAND (delent , "")
COMMAND (dropent , "")
COMMAND (entcopy , "")
COMMAND (entpaste , "")
COMMAND (entset , "siiiii")
COMMAND (nearestent , "")
COMMAND (enttype , "sN")
COMMAND (entattr , "iiN")
COMMAND (newmap , "i")
COMMAND (mapenlarge , "")
COMMAND (shrinkmap , "")
COMMAND (mapname , "")
undoblock* copyundoents (undoblock * u)
References entadd(), entcancel(), entgroup, undoblock::ents(), ET_EMPTY, loopi(), newundoent(), undoblock::numents, and vector< T, MINSIZE >::removeobj().
Referenced by swapundo().
void delent ()
References entcancel(), ET_EMPTY, groupedit, and noentedit().
void detachentity (extentity & e)
References extentity::attached.
Referenced by attachentity(), and mpeditent().
void dropent ()
References dropentity(), groupedit, and noentedit().
Referenced by droptofloor(), and game::collectclientmode::movetoken().
bool dropentity (entity & e, int drop = -1)
References entity::attr2, C, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, D, hmap::d, hmap::dc, dimcoord, dimension, dropenttofloor(), ET_LIGHT, ET_MAPMODEL, ET_SPOTLIGHT, f(), selinfo::grid, loadmapmodel(), mmboundbox(), entity::o, selinfo::o, selinfo::orient, R, sel, and entity::type.
Referenced by dropent(), and newentity().
bool editmoveplane (const vec & o, const vec & ray, int d, float off, vec & handle, vec & dest, bool first)
move the selection grid (the "plane") along the selection has an origin and can only be moved in 2 dimensions simultaneously
References vec::add(), vec::mul(), physent::o, player, plane::rayintersect(), and vec::sub().
Referenced by entdrag(), and rendereditcursor().
bool emptymap (int scale, bool force, const char * mname, bool usecfg)
References allchanged(), clearmainmenu(), inexor::util::log_manager::edit, editmode, execfile(), F_EMPTY, freeocta(), identflags, IDF_OVERRIDDEN, initlights(), Log, loopi(), newcubes(), resetmap(), setvar(), vector< T, MINSIZE >::shrink(), solidfaces, splitocta(), startmap(), texmru, worldroot, worldscale, and worldsize.
Referenced by game::changemapserv(), main(), newmap(), and game::parsemessages().
bool enlargemap (bool force)
References allchanged(), cube::children, inexor::util::log_manager::edit, editmode, enlargeblendmap(), F_EMPTY, vector< T, MINSIZE >::length(), Log, loopi(), newcubes(), outsideents, vector< T, MINSIZE >::pop(), removeentity(), solidfaces, splitocta(), worldroot, worldscale, and worldsize.
Referenced by mapenlarge(), and game::parsemessages().
void entadd (int id)
References vector< T, MINSIZE >::add(), entgroup, and undonext.
Referenced by copyundoents(), entpaste(), enttoggle(), and nearestent().
void entattr (int * attr, int * val, int * numargs)
References efocus, entfocus, groupedit, and intret().
void entautoview (int * dir)
References vec::add(), dir, entfocus, entgroup, haveselent(), vector< T, MINSIZE >::length(), vec::mul(), vec::normalize(), physent::o, player, physent::resetinterp(), vec::sub(), anonymous_namespace{utilTest.cpp}::t(), and worldpos.
void entcancel ()
cancel (remove) entity selection
References entgroup, and vector< T, MINSIZE >::shrink().
Referenced by cancelsel(), copyundoents(), delent(), and entpaste().
void entcopy ()
References entcopybuf, entcopygrid, entfocus, entgroup, selinfo::grid, loopv, noentedit(), selinfo::o, and sel.
void entdrag (const vec & ray)
References ivec::add(), C, hmap::d, hmap::dc, dimcoord, dimension, editmoveplane(), entfocus, entgroup, entmoving, entorient, entselectionbox(), selinfo::grid, groupeditpure, haveselent(), vector< T, MINSIZE >::last(), makeundoent(), ivec::mask(), noentedit(), R, and sel.
Referenced by rendereditcursor().
void entflip ()
References hmap::d, dimension, selinfo::grid, groupeditundo, noentedit(), selinfo::o, selinfo::orient, selinfo::s, and sel.
void entitiesinoctanodes ()
References entities::ents, entities::getents(), loopv, modifyoctaent(), and MODOE_ADD.
Referenced by allchanged(), commitchanges(), and load_world().
char* entname (entity & e)
References concatstring(), copystring(), entities::entname(), entities::entnameinfo(), and entity::type.
Referenced by updateparticles().
void entpaste ()
References vec::add(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, entadd(), entcancel(), entcopybuf, entcopygrid, ET_EMPTY, selinfo::grid, groupeditundo, keepents, loopv, inexor::rpc::max(), vec::mul(), newentity(), noentedit(), materialsurface::o, entity::o, selinfo::o, and sel.
void entpush (int * dir)
References hmap::d, dimcoord, dimension, dir, entmoving, entorient, selinfo::grid, groupedit, groupeditpure, noentedit(), physent::o, player, physent::resetinterp(), and sel.
void entrotate (int * cw)
References C, hmap::d, dimcoord, dimension, selinfo::grid, groupeditundo, noentedit(), selinfo::o, selinfo::orient, R, selinfo::s, and sel.
void entselectionbox (const entity & e, vec & eo, vec & es)
References vec::add(), entity::attr2, model::collisionbox(), entities::entmodel(), ET_MAPMODEL, loadmapmodel(), loadmodel(), vec::max(), mmcollisionbox(), vec::mul(), entity::o, vec::sub(), and entity::type.
Referenced by disttoent(), disttooutsideent(), entdrag(), and renderentselection().
void entset (char * what, int * a1, int * a2, int * a3, int * a4, int * a5)
References ET_EMPTY, findtype(), groupedit, and noentedit().
bool enttoggle (int id)
References entadd(), entgroup, vector< T, MINSIZE >::find(), vector< T, MINSIZE >::remove(), and undonext.
Referenced by newentity().
void enttype (char * type, int * numargs)
References efocus, entfocus, entities::entname(), ET_EMPTY, findtype(), groupedit, and result().
int findentity (int type, int index, int attr1, int attr2)
References entity::attr1, entity::attr2, entities::ents, entities::getents(), vector< T, MINSIZE >::length(), loopj, and entity::type.
Referenced by findplayerspawn(), and entities::teleport().
static void findents (octaentities & oe, int low, int high, bool notspawned, const vec & pos, const vec & invradius, vector< int > & found) inline static
References vector< T, MINSIZE >::add(), entities::ents, entities::getents(), loopv, vec::mul(), entity::o, octaentities::other, extentity::spawned(), vec::squaredlen(), vec::sub(), and entity::type.
Referenced by ai::find(), and findents().
static void findents (cube * c, const ivec & o, int size, const ivec & bo, const ivec & br, int low, int high, bool notspawned, const vec & pos, const vec & invradius, vector< int > & found) inline static
References cubeext::ents, ext(), findents(), loopoctabox, and octaentsize.
void findents (int low, int high, bool notspawned, const vec & pos, const vec & radius, vector< int > & found)
References hmap::br, cube::children, cubeext::ents, cube::ext, findents(), octaentsize, octastep, worldroot, worldscale, and worldsize.
void findplayerspawn (dynent * d, int forceent, int tag)
References entinmap(), entities::ents, ET_PLAYERSTART, findentity(), entities::getents(), loopi(), physent::o, physent::pitch, rnd(), physent::roll, spawncycle, worldsize, and physent::yaw.
Referenced by game::parsemessages(), game::clientmode::pickspawn(), game::hideandseekclientmode::pickspawn(), game::captureclientmode::pickspawn(), game::collectclientmode::pickspawn(), game::ctfclientmode::pickspawn(), game::spawnplayer(), and game::startmap().
int findtype (char * what)
References inexor::util::log_manager::edit, entities::entname(), ET_EMPTY, and Log.
Referenced by entset(), enttype(), and newent().
void freeoctaentities (cube & c)
References vector< T, MINSIZE >::empty(), cubeext::ents, cube::ext, entities::getents(), octaentities::mapmodels, octaentities::other, vector< T, MINSIZE >::pop(), and removeentity().
Referenced by discardchildren(), modifyoctaentity(), and readychanges().
bool getentboundingbox (const extentity & e, ivec & o, ivec & r)
References vec::add(), entity::attr1, entity::attr2, model::boundbox(), entediting, ET_EMPTY, ET_MAPMODEL, ET_OBSTACLE, entities::hasmapmodel(), loadmapmodel(), loadmodel(), vec::max(), mmboundbox(), ivec::mul(), entity::o, rotatebb(), vec::sub(), ivec::sub(), and entity::type.
Referenced by modifyoctaent(), and modifyoctaentity().
int getmapversion ()
References mapversion.
vec getselpos ()
References entgroup, enthover, entities::ents, entities::getents(), vector< T, MINSIZE >::inrange(), vector< T, MINSIZE >::length(), materialsurface::o, selinfo::o, and sel.
Referenced by game::gotosel().
int getworldsize ()
References worldsize.
Referenced by ai::findorientation(), ai::getweight(), ai::movewaypoints(), and game::parsemessages().
bool haveselent ()
References entgroup, and vector< T, MINSIZE >::length().
Referenced by entautoview(), entdrag(), and noedit().
bool hoveringonent (int ent, int orient)
References efocus, vector< T, MINSIZE >::empty(), entgroup, enthover, entorient, vector< T, MINSIZE >::last(), noentedit(), and orient.
Referenced by rendereditcursor().
ICOMMAND (entadd , "" , () , {if(enthover >=0 &&!noentedit()){if(entgroup.find(enthover)< 0) entadd(enthover);if(entmoving > 1) entmoving=1;}})
ICOMMAND (enttoggle , "" , () , {if(enthover< 0||noentedit()||!enttoggle(enthover)){entmoving=0;intret(0);}else{if(entmoving > 1) entmoving=1;intret(1);}})
ICOMMAND (entmoving , "b" , (int *n) , {if(*n >=0){if(!*n||enthover< 0||noentedit()) entmoving=0;else{if(entgroup.find(enthover)< 0){entadd(enthover);entmoving=1;}else if(!entmoving) entmoving=1;}}intret(entmoving);})
ICOMMAND (entget , "" , () , entfocus(efocus, string s;printent(e, s, sizeof(s));result(s)))
ICOMMAND (enthavesel , "" , () , addimplicit(intret(entgroup.length())))
ICOMMAND (entindex , "" , () , intret(efocus))
ICOMMAND (entloop , "e" , (uint *body) , if(!noentedit()) addimplicit(groupeditloop(((void) e, execute(body)))))
ICOMMAND (entselect , "e" , (uint *body) , if(!noentedit()) addgroup(e.type!=ET_EMPTY &&entgroup.find(n)< 0 &&executebool(body)))
ICOMMAND (insel , "" , () , entfocus(efocus, intret(pointinsel(sel, e.o))))
static bool isallempty (cube & c) static
References cube::children, isempty, and loopi().
Referenced by shrinkmap().
void makeundoent ()
References addundo(), enthover, newundoent(), oldhover, and undonext.
Referenced by entdrag(), and newentity().
void mapenlarge ()
References enlargemap(), and game::newmap().
void mapname ()
References game::getclientmap(), and result().
Referenced by ai::getwaypointfile(), loadents(), mapcfgname(), and setmapfilenames().
static void mmboundbox (const entity & e, model * m, vec & center, vec & radius) inline static
References entity::attr1, model::boundbox(), and rotatebb().
Referenced by dropentity(), and getentboundingbox().
static void mmcollisionbox (const entity & e, model * m, vec & center, vec & radius) inline static
References entity::attr1, model::collisionbox(), and rotatebb().
Referenced by entselectionbox().
static bool modifyoctaent (int flags, int id, extentity & e) static
References vector< T, MINSIZE >::add(), clearlightcache(), clearparticleemitters(), EF_OCTA, ET_LIGHT, ET_PARTICLES, vector< T, MINSIZE >::find(), extentity::flags, getentboundingbox(), insideworld(), lightent(), inexor::rpc::max(), modifyoctaentity(), MODOE_ADD, MODOE_LIGHTENT, materialsurface::o, entity::o, octaentsize, outsideents, vector< T, MINSIZE >::removeunordered(), entity::type, worldroot, and worldsize.
Referenced by addentity(), entitiesinoctanodes(), modifyoctaent(), game::parsemessages(), and removeentity().
bool modifyoctaent (int flags, int id)
References entities::ents, entities::getents(), vector< T, MINSIZE >::inrange(), and modifyoctaent().
void modifyoctaentity (int flags, int id, extentity & e, cube * c, const ivec & cor, int size, const ivec & bo, const ivec & br, int leafsize, vtxarray * lastva = nullptr)
References vector< T, MINSIZE >::add(), ivec::add(), entity::attr2, octaentities::bbmax, octaentities::bbmin, vtxarray::bbmin, vector< T, MINSIZE >::empty(), entediting, cubeext::ents, ET_MAPMODEL, ET_OBSTACLE, ext(), cube::ext, freeoctaentities(), getentboundingbox(), entities::getents(), entities::hasmapmodel(), loadmapmodel(), loopoctabox, loopvj, octaentities::mapmodels, vtxarray::mapmodels, ivec::max(), ivec::min(), MODOE_ADD, MODOE_UPDATEBB, materialsurface::o, octaentities::o, octaentities::other, octaentities::query, vector< T, MINSIZE >::removeobj(), octaentities::size, entity::type, updatevabb(), and cubeext::va.
Referenced by modifyoctaent().
void mpeditent (int i, const vec & o, int type, int attr1, int attr2, int attr3, int attr4, int attr5, bool local)
References addentity(), attachentity(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, detachentity(), entities::editent(), entities::ents, entities::getents(), vector< T, MINSIZE >::length(), MAXENTS, newentity(), materialsurface::o, entity::o, removeentity(), and entity::type.
Referenced by game::parsemessages().
void nearestent ()
References vec::dist(), entadd(), entities::ents, ET_EMPTY, entities::getents(), loopv, noentedit(), entity::o, physent::o, player, and entity::type.
void newent (char * what, int * a1, int * a2, int * a3, int * a4, int * a5)
References ET_EMPTY, findtype(), newentity(), and noentedit().
extentity* newentity (bool local, const vec & o, int type, int v1, int v2, int v3, int v4, int v5, int & idx)
References vector< T, MINSIZE >::add(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, camera1, entitylight::color, entities::deleteentity(), entitylight::dir, inexor::util::log_manager::edit, entities::ents, ET_EMPTY, ET_MAPMODEL, ET_PLAYERSTART, entities::fixentity(), entities::getents(), vector< T, MINSIZE >::inrange(), keepents, vector< T, MINSIZE >::length(), extentity::light, Log, MAXENTS, entities::newentity(), materialsurface::o, entity::o, entity::reserved, entity::type, and physent::yaw.
Referenced by entpaste(), mpeditent(), newent(), newentity(), and game::parsemessages().
void newentity (int type, int a1, int a2, int a3, int a4, int a5)
References dropentity(), entedit, enttoggle(), ET_EMPTY, makeundoent(), newentity(), physent::o, player, anonymous_namespace{utilTest.cpp}::t(), and entity::type.
void newmap (int * i)
References emptymap(), game::forceedit(), isconnected(), inexor::rpc::max(), and game::newmap().
undoblock* newundoent ()
References undoent::e, entgroup, entities::getents(), undoent::i, vector< T, MINSIZE >::length(), loopv, and undoblock::numents.
Referenced by copyundoents(), and makeundoent().
bool noentedit ()
References inexor::util::log_manager::edit, editmode, entediting, and Log.
Referenced by attachent(), delent(), dropent(), entcopy(), entdrag(), entflip(), entpaste(), entpush(), entrotate(), entset(), hoveringonent(), nearestent(), newent(), and renderentselection().
void pasteundoent (int idx, const entity & ue)
References vector< T, MINSIZE >::add(), efocus, entedit, entities::ents, ET_EMPTY, entities::getents(), vector< T, MINSIZE >::length(), MAXENTS, entities::newentity(), and entity::type.
Referenced by unpackundo().
void pasteundoents (undoblock * u)
References entedit, undoblock::ents(), loopi(), and undoblock::numents.
Referenced by pasteundo().
bool pointinsel (const selinfo & sel, const vec & o)
References selinfo::grid, selinfo::o, and selinfo::s.
void printent (extentity & e, char * buf, int len)
References entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, entities::entname(), ET_GAMESPECIFIC, ET_PARTICLES, nformatstring(), entities::printent(), printparticles(), and entity::type.
static void removeentity (int id) inline static
References modifyoctaent(), and MODOE_UPDATEBB.
Referenced by enlargemap(), freeoctaentities(), mpeditent(), and shrinkmap().
void renderentarrow (const extentity & e, const vec & dir, float radius)
References vec::add(), gle::attrib(), gle::begin(), gle::end(), f(), loopi(), inexor::rpc::min(), vec::mul(), entity::o, vec::orthogonal(), rotate(), ai::target(), and xtraverts.
Referenced by entities::entradius(), and renderentradius().
void renderentattachment (const extentity & e)
References extentity::attached, gle::attrib(), gle::begin(), gle::end(), entity::o, and xtraverts.
Referenced by renderentradius().
static void renderentbox (const vec & eo, vec es) static
References vec::add(), and gle::attrib().
Referenced by renderentselection().
void renderentcone (const extentity & e, const vec & dir, float radius, float angle)
References vec::add(), gle::attrib(), gle::begin(), gle::end(), f(), loopi(), vec::mul(), entity::o, vec::orthogonal(), RAD, rotate(), and xtraverts.
Referenced by renderentradius().
void renderentradius (extentity & e, bool color)
References extentity::attached, entity::attr1, entity::attr2, entity::attr3, entity::attr4, dir, vec::dist(), entities::entradius(), ET_ENVMAP, ET_GAMESPECIFIC, ET_LIGHT, ET_MAPMODEL, ET_PLAYERSTART, ET_SOUND, ET_SPOTLIGHT, inexor::rpc::max(), inexor::rpc::min(), vec::normalize(), entity::o, renderentarrow(), renderentattachment(), renderentcone(), renderentsphere(), vec::sub(), entity::type, and vecfromyawpitch().
Referenced by renderentselection().
void renderentring (const extentity & e, float radius, int axis)
References gle::attrib(), gle::begin(), gle::end(), loopi(), entity::o, sincos360, and xtraverts.
Referenced by entities::entradius(), and renderentsphere().
void renderentselection (const vec & o, const vec & ray, bool entmoving)
References gle::begin(), boxs(), boxs3D(), camera1, vec::dist(), gle::end(), entfocus, entgroup, enthover, entorient, entselectionbox(), f(), fovy, vector< T, MINSIZE >::length(), loopv, noentedit(), physent::o, RAD, renderentbox(), renderentradius(), worldsize, and xtraverts.
Referenced by rendereditcursor().
void renderentsphere (const extentity & e, float radius)
References loopk, and renderentring().
Referenced by renderentradius().
void resetmap ()
References cancelsel(), cleanreflections(), cleardecals(), entities::clearents(), clearmapcrc(), inexor::sound::clearmapsounds(), clearoverrides(), clearparticles(), clearpvs(), clearsleep(), clearslots(), outsideents, pruneundos(), resetblendmap(), resetlightmaps(), and vector< T, MINSIZE >::setsize().
Referenced by emptymap(), and load_world().
void shrinkmap ()
References allchanged(), cube::children, entities::ents, freeocta(), entities::getents(), isallempty(), vector< T, MINSIZE >::length(), Log, loopi(), loopv, multiplayer(), noedit(), nompedit, outsideents, vector< T, MINSIZE >::pop(), removeentity(), shrinkblendmap(), inexor::util::log_manager::std, subdividecube(), worldroot, worldscale, and worldsize.
void splitocta (cube * c, int size)
References cube::children, F_EMPTY, F_SOLID, isempty, loopi(), and newcubes().
Referenced by emptymap(), and enlargemap().
void startmap (const char * name)
Referenced by emptymap(), and load_world().
SVARR (maptitle , "Untitled Map by Unknown")
VAR (octaentsize , 0 , 64 , 1024)
VAR (entselradius , 0 , 2 , 10)
VAR (attachradius , 1 , 100 , 1000)
VAR (entselsnap , 0 , 0 , 1)
VAR (entmovingshadow , 0 , 1 , 1)
VAR (showentradius , 0 , 1 , 1)
VAR (entitysurf , 0 , 0 , 1)
VAR (entautoviewdist , 0 , 25 , 100)
VAR (entdrop , 0 , 2 , 3)
VARF (entediting , 0 , 0 , 1 , {if(!entediting){entcancel();efocus=enthover=-1;}})
VARNR (mapscale , worldscale , 1 , 0 , 0)
VARNR (mapsize , worldsize , 1 , 0 , 0)
VARR (mapversion , 1 , MAPVERSION , 0)
Variable Documentation
int efocus = -1
Referenced by entattr(), enttype(), hoveringonent(), and pasteundoent().
vector<entity> entcopybuf
Referenced by entcopy(), and entpaste().
int entcopygrid
Referenced by entcopy(), and entpaste().
vector<int> entgroup
Referenced by copyundoents(), entadd(), entautoview(), entcancel(), entcopy(), entdrag(), enttoggle(), getselpos(), haveselent(), hoveringonent(), newundoent(), renderentselection(), and updateparticles().
int enthover = -1
Referenced by getselpos(), hoveringonent(), makeundoent(), and renderentselection().
int entlooplevel = 0
int entmoving = 0
Referenced by entdrag(), entpush(), and rendereditcursor().
int entorient = -1
Referenced by entdrag(), entpush(), hoveringonent(), rendereditcursor(), and renderentselection().
bool havesel
Referenced by cubecancel(), isheightmap(), pastehilite(), rendereditcursor(), and hmap::run().
int keepents = 0 static
Referenced by entpaste(), and newentity().
int oldhover = -1
Referenced by makeundoent().
vector<int> outsideents
Referenced by disttooutsideent(), enlargemap(), modifyoctaent(), resetmap(), and shrinkmap().
selinfo sel
See Also
selinfo
Referenced by dropentity(), entcopy(), entdrag(), entflip(), entpaste(), entpush(), entrotate(), and getselpos().
int spawncycle = -1
Referenced by findplayerspawn().
bool undonext = true
Referenced by entadd(), enttoggle(), and makeundoent().