Inexor: inexor/ui/legacy/3dgui.hpp File Reference
3dgui.hpp File Reference
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/texture/slot.hpp"
Classes
struct g3d_gui
struct g3d_callback
Enumerations
enum {
HICON_BLUE_ARMOUR = 0, HICON_GREEN_ARMOUR, HICON_YELLOW_ARMOUR, HICON_HEALTH,
HICON_FIST, HICON_SG, HICON_CG, HICON_RL,
HICON_RIFLE, HICON_GL, HICON_PISTOL, HICON_BOMB,
HICON_QUAD, HICON_RED_FLAG, HICON_BLUE_FLAG, HICON_NEUTRAL_FLAG,
HICON_TOKEN, HICON_BOMBRADIUS, HICON_BOMBDELAY, HICON_X = 20,
HICON_Y = 1650, HICON_TEXTY = 1644, HICON_STEP = 490, HICON_SIZE = 120,
HICON_SPACE = 40
}
enumeration for icons
enum {
G3D_DOWN = 1, G3D_UP = 2, G3D_PRESSED = 4, G3D_ROLLOVER = 8,
G3D_DRAGGED = 16
}
enum { EDITORFOCUSED = 1, EDITORUSED, EDITORFOREVER }
enum { GUI_2D = 1<<0, GUI_FOLLOW = 1<<1, GUI_FORCE_2D = 1<<2, GUI_BOTTOM = 1<<3 }
enum hudannounceeffects {
E_STATIC_CENTER = 0, E_STATIC_LEFT, E_STATIC_RIGHT, E_STATIC_TOP,
E_STATIC_BOTTOM, E_FADE_LEFT_RIGHT, E_FADE_RIGHT_LEFT, E_FADE_TOP_BOTTOM,
E_FADE_BOTTOM_TOP, E_ZOOM_IN, E_ZOOM_OUT, E_BLINK_CENTER
}
Bomberman: HUD announce effects.
Functions
void g3d_addgui (g3d_callback *cb, vec &origin, int flags=0)
bool g3d_movecursor (int dx, int dy)
void g3d_cursorpos (float &x, float &y)
void g3d_resetcursor ()
void g3d_limitscale (float scale)
void g3d_render ()
bool g3d_windowhit (bool on, bool act)
bool g3d_key (int code, bool isdown)
bool g3d_input (const char *str, int len)
Variables
int hudannounce_begin
Bomberman HUD.
int hudannounce_timeout
int hudannounce_effect
char * hudannounce_text
Enumeration Type Documentation
anonymous enum
enumeration for icons
Enumerator
HICON_BLUE_ARMOUR
HICON_GREEN_ARMOUR
HICON_YELLOW_ARMOUR
HICON_HEALTH
HICON_FIST
HICON_SG
HICON_CG
HICON_RL
HICON_RIFLE
HICON_GL
HICON_PISTOL
HICON_BOMB
HICON_QUAD
HICON_RED_FLAG
HICON_BLUE_FLAG
HICON_NEUTRAL_FLAG
HICON_TOKEN
HICON_BOMBRADIUS
HICON_BOMBDELAY
HICON_X
HICON_Y
HICON_TEXTY
HICON_STEP
HICON_SIZE
HICON_SPACE
anonymous enum
Enumerator
G3D_DOWN
G3D_UP
G3D_PRESSED
G3D_ROLLOVER
G3D_DRAGGED
anonymous enum
Enumerator
EDITORFOCUSED
EDITORUSED
EDITORFOREVER
anonymous enum
Enumerator
GUI_2D
GUI_FOLLOW
GUI_FORCE_2D
GUI_BOTTOM
enum hudannounceeffects
Bomberman: HUD announce effects.
Enumerator
E_STATIC_CENTER
E_STATIC_LEFT
E_STATIC_RIGHT
E_STATIC_TOP
E_STATIC_BOTTOM
E_FADE_LEFT_RIGHT
E_FADE_RIGHT_LEFT
E_FADE_TOP_BOTTOM
E_FADE_BOTTOM_TOP
E_ZOOM_IN
E_ZOOM_OUT
E_BLINK_CENTER
Function Documentation
void g3d_addgui (g3d_callback * cb, vec & origin, int flags = 0)
References camera1, gui::cb, vec::dist(), gui::dist, physent::eyeheight, gui::gui2d, GUI_2D, GUI_BOTTOM, GUI_FOLLOW, GUI_FORCE_2D, guis2d, guis3d, mainmenu, physent::o, gui::origin, player, and gui::savedorigin.
Referenced by g3d_mainmenu(), game::scoreboardgui::render(), and texturegui::show().
void g3d_cursorpos (float & x, float & y)
References cursorx, cursory, and guis2d.
Referenced by draw_g3d_cursor().
bool g3d_input (const char * str, int len)
References currentfocus(), FIELDKEY, fieldmode, FIELDSHOW, and editor::input().
Referenced by processtextinput().
bool g3d_key (int code, bool isdown)
References vec::add(), camdir, camera1, currentfocus(), vec::dist(), vector< T, MINSIZE >::empty(), FIELDABORT, FIELDCOMMIT, FIELDKEY, fieldmode, FIELDSHOW, g3d_windowhit(), getkeyname(), gui::gui2d, guis2d, editor::insert(), editor::key(), vector< T, MINSIZE >::length(), editor::lines, loopj, editor::maxy, physent::o, gui::savedorigin, vec::sub(), and windowhit.
Referenced by processkey().
void g3d_limitscale (float scale)
References gui::maxscale.
Referenced by gl_drawhud().
bool g3d_movecursor (int dx, int dy)
References cursorx, cursory, guis2d, hascursor, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, and inexor::rendering::screen::ScreenManager::screenw.
void g3d_render ()
References actionon, fieldmode, fieldsactive, FIELDSHOW, flusheditors(), game::g3d_gamemenus(), g3d_mainmenu(), G3D_PRESSED, g3d_sort(), g3d_texturemenu(), guis2d, guis3d, hascursor, inexor::io::input_router, inexor::io::InputRouter::keyrepeat(), KR_GUI, layoutpass, loopv, loopvrev, mainmenu, mousebuttons, readyeditors(), gui::reset(), and windowhit.
Referenced by gl_drawframe(), and gl_drawmainmenu().
void g3d_resetcursor ()
References cursorx, and cursory.
Referenced by pushgui().
bool g3d_windowhit (bool on, bool act)
References actionon, cleargui(), firstx, firsty, G3D_DOWN, G3D_UP, gui::gui2d, guis2d, hascursor, gui::hitx, gui::hity, mousebuttons, and windowhit.
Referenced by drawcrosshair(), g3d_key(), and rendereditcursor().
Variable Documentation
int hudannounce_begin
Bomberman HUD.
Referenced by game::drawhudannounce(), and game::parsemessages().
int hudannounce_effect
Referenced by game::drawhudannounce(), and game::parsemessages().
char* hudannounce_text
Referenced by game::drawhudannounce(), and game::parsemessages().
int hudannounce_timeout
Referenced by game::drawhudannounce(), and game::parsemessages().