Inexor: inexor/texture/additionaltools.hpp File Reference
additionaltools.hpp File Reference
Functions
void flipnormalmapy (char *destfile, char *normalfile)
void mergenormalmaps (char *heightfile, char *normalfile)
void gendds (char *infile, char *outfile)
Function Documentation
void flipnormalmapy (char * destfile, char * normalfile)
References hmap::d, guessimageformat(), ImageData::h, IMG_TGA, loadimage(), readwritetex, saveimage(), and ImageData::w.
void gendds (char * infile, char * outfile)
References compressed, concatstring(), copystring(), hmap::d, DDPF_ALPHAPIXELS, DDPF_FOURCC, DDSURFACEDESC2::ddsCaps, DDSCAPS_COMPLEX, DDSCAPS_MIPMAP, DDSCAPS_TEXTURE, DDSD_CAPS, DDSD_HEIGHT, DDSD_LINEARSIZE, DDSD_MIPMAPCOUNT, DDSD_PIXELFORMAT, DDSD_WIDTH, defformatstring, DDSCAPS2::dwCaps, DDSURFACEDESC2::dwFlags, DDSURFACEDESC2::dwHeight, DDSURFACEDESC2::dwSize, DDSURFACEDESC2::dwWidth, f(), format(), FOURCC_DXT1, FOURCC_DXT3, FOURCC_DXT5, gettexture(), glGetCompressedTexImage_, hasS3TC, Texture::id, lilswap(), Log, inexor::rpc::max(), notexture, openfile(), path(), reloadtex(), setuptexcompress(), inexor::util::log_manager::std, anonymous_namespace{utilTest.cpp}::t(), textureload(), usetexcompress, and stream::write().
void mergenormalmaps (char * heightfile, char * normalfile)
References hmap::d, guessimageformat(), ImageData::h, IMG_TGA, loadimage(), read2writetex, saveimage(), and ImageData::w.