Inexor: inexor/physics/bih.hpp File Reference
bih.hpp File Reference
#include <stdlib.h>
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
Classes
struct BIH
struct BIH::node
struct BIH::tri
struct BIH::tribb
struct BIH::mesh
Functions
bool mmintersect (const extentity &e, const vec &o, const vec &ray, float maxdist, int mode, float &dist)
Class Documentation
struct BIH::tri
Class Members
ushort vert[3]
Function Documentation
bool mmintersect (const extentity & e, const vec & o, const vec & ray, float maxdist, int mode, float & dist)
References entity::attr1, entity::attr2, model::bih, model::collide, vec::dot(), EF_NOCOLLIDE, EF_NOSHADOW, BIH::entradius, extentity::flags, lightmapping, loadmapmodel(), entity::o, RAY_ENTS, RAY_SHADOW, vec::rotate_around_z(), model::setBIH(), model::shadow, sincosmod360(), vec::squaredlen(), vec::sub(), and BIH::traverse().
Referenced by disttoent(), and shadowent().