Inexor: inexor/engine/blend.hpp File Reference
blend.hpp File Reference
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/cube_types.hpp"
Functions
BlendMapCache * newblendmapcache ()
void freeblendmapcache (BlendMapCache *&cache)
bool setblendmaporigin (BlendMapCache *cache, const ivec &o, int size)
bool hasblendmap (BlendMapCache *cache)
uchar lookupblendmap (BlendMapCache *cache, const vec &pos)
void resetblendmap ()
void enlargeblendmap ()
void shrinkblendmap (int octant)
void optimizeblendmap ()
void stoppaintblendmap ()
void trypaintblendmap ()
void renderblendbrush (uint tex, float x, float y, float w, float h)
void renderblendbrush ()
bool loadblendmap (stream *f, int info)
void saveblendmap (stream *f)
uchar shouldsaveblendmap ()
Variables
SharedVar< int > blendpaintmode
Function Documentation
void enlargeblendmap ()
References blendmap, BM_BRANCH, BM_SOLID, BlendMapBranch::children, loopi(), BlendMapBranch::type, and BlendMapRoot::type.
Referenced by enlargemap().
void freeblendmapcache (BlendMapCache *& cache)
Referenced by lightmapworker::~lightmapworker().
bool hasblendmap (BlendMapCache * cache)
References BlendMapCache::node.
bool loadblendmap (stream * f, int info)
References loadblendmap(), resetblendmap(), and BlendMapRoot::type.
uchar lookupblendmap (BlendMapCache * cache, const vec & pos)
References BM_IMAGE, BM_IMAGE_SIZE, BM_SCALE, BM_SOLID, f(), lookupblendmap(), loop, BlendMapCache::node, BlendMapCache::origin, BlendMapCache::scale, and BlendMapRoot::type.
BlendMapCache* newblendmapcache ()
Referenced by lightmapworker::lightmapworker().
void optimizeblendmap ()
References optimizeblendmap(), and BlendMapRoot::type.
void renderblendbrush (uint tex, float x, float y, float w, float h)
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), gle::color(), drawvatris(), f(), GL_ONE, vec::hexcolor(), LOCALPARAMF, vtxarray::next, OCCLUDE_GEOM, vertex::pos, SETSHADER, vtxarray::vbuf, and xtravertsva.
void renderblendbrush ()
References blendpaintmode, BM_SCALE, brush, curbrush, BlendBrush::gentex(), BlendBrush::h, vector< T, MINSIZE >::inrange(), inexor::rpc::max(), inexor::rpc::min(), renderblendbrush(), BlendBrush::tex, BlendBrush::w, worldpos, and worldsize.
Referenced by gl_drawhud(), and renderblendbrush().
void resetblendmap ()
References BM_SOLID, BlendMapRoot::cleanup(), and BlendMapRoot::type.
Referenced by loadblendmap(), and resetmap().
void saveblendmap (stream * f)
References saveblendmap(), and BlendMapRoot::type.
bool setblendmaporigin (BlendMapCache * cache, const ivec & o, int size)
References blendmap, BM_BRANCH, BM_SCALE, BlendMapBranch::children, inexor::rpc::max(), inexor::rpc::min(), BlendMapCache::node, BlendMapCache::origin, BlendMapCache::scale, BlendMapBranch::type, BlendMapRoot::type, and worldscale.
Referenced by findlights(), and previewblends().
uchar shouldsaveblendmap ()
Referenced by save_world().
void shrinkblendmap (int octant)
References BlendMapRoot::shrink().
Referenced by shrinkmap().
void stoppaintblendmap ()
References lastpaintblendmap.
Referenced by toggleedit().
void trypaintblendmap ()
References lastpaintblendmap, paintblendmap(), and totalmillis.
Referenced by tryedit().
Variable Documentation
SharedVar<int> blendpaintmode
Referenced by canpaintblendmap(), paintblendmap(), renderblendbrush(), rendereditcursor(), and tryedit().