Inexor: inexor::ui::layer::InexorLayerManager Class Reference
inexor::ui::layer::InexorLayerManager Class Reference
#include <InexorLayerManager.hpp>
Public Member Functions
InexorLayerManager (int width, int height)
void SetScreenSize (int width, int height)
int GetScreenWidth ()
int GetScreenHeight ()
void InitializeLayers ()
void InitializeLayer (CefRefPtr< InexorLayerProvider > layer_provider)
void DestroyLayers ()
void AddLayerProvider (CefRefPtr< InexorLayerProvider > layer_provider)
CefRefPtr< InexorLayer > CreateLayer (std::string name, std::string url)
CefRefPtr< InexorLayer > CreateLayer (std::string name, int x, int y, int width, int height, std::string url)
CefRefPtr< InexorLayer > GetLayer (std::string name)
std::list< std::string > GetLayers ()
std::list< CefRefPtr
< InexorLayer > > GetLayerList ()
bool LayerExists (std::string name)
void ShowLayer (std::string name)
void HideLayer (std::string name)
void BringToFront (std::string name)
void SendToBack (std::string name)
void BringForward (std::string name)
void SendBackward (std::string name)
void SendKeyEvent (CefKeyEvent event)
void SendMouseClickEvent (const CefMouseEvent &event, CefBrowserHost::MouseButtonType type, bool mouseUp, int clickCount)
void SendMouseMoveEvent (const CefMouseEvent &event, bool mouseLeave)
void SendMouseWheelEvent (const CefMouseEvent &event, int deltaX, int deltaY)
void InitializeContext () override
bool Execute (const CefString &name, CefRefPtr< CefV8Value > object, const CefV8ValueList &arguments, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Get (const CefString &name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Set (const CefString &name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString &exception) override
std::string GetContextName () override
CefRefPtr< CefV8Value > GetContext ()
void InitializeSubContexts ()
void AddSubContext (InexorContextProvider *sub_context)
Protected Member Functions
void CreateFunction (const CefString &name)
void CreateFunction (const CefString &name, CefRefPtr< CefV8Handler > handler)
void CreateVariable (const CefString &name, bool readonly=false)
void CreateSubContext (CefRefPtr< InexorContextProvider > sub_context)
Protected Attributes
std::list
< InexorContextProvider * > sub_contexts
CefRefPtr< CefV8Value > context
Private Member Functions
std::list< CefRefPtr
< InexorLayer > >::iterator GetIterator (std::string name)
Returns an iterator instance pointing to the layer element with the given name.
void _CreateLayer (std::string name, std::string url)
IMPLEMENT_REFCOUNTING (InexorLayerManager)
Private Attributes
std::list< CefRefPtr
< InexorLayer > > layers
std::list< CefRefPtr
< InexorLayerProvider > > layer_providers
int width
int height
Constructor & Destructor Documentation
inexor::ui::layer::InexorLayerManager::InexorLayerManager (int width, int height)
References SetScreenSize().
Member Function Documentation
void inexor::ui::layer::InexorLayerManager::_CreateLayer (std::string name, std::string url) private
References CreateLayer().
void inexor::ui::layer::InexorLayerManager::AddLayerProvider (CefRefPtr< InexorLayerProvider > layer_provider)
References layer_providers.
void inexor::ui::context::InexorContextProvider::AddSubContext (InexorContextProvider * sub_context) inherited
References inexor::ui::context::InexorContextProvider::sub_contexts.
void inexor::ui::layer::InexorLayerManager::BringForward (std::string name)
References GetIterator(), and layers.
void inexor::ui::layer::InexorLayerManager::BringToFront (std::string name)
References GetIterator(), and layers.
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name, CefRefPtr< CefV8Handler > handler) protected inherited
References inexor::ui::context::InexorContextProvider::context.
CefRefPtr< InexorLayer > inexor::ui::layer::InexorLayerManager::CreateLayer (std::string name, std::string url)
Referenced by _CreateLayer(), and InitializeLayer().
CefRefPtr< InexorLayer > inexor::ui::layer::InexorLayerManager::CreateLayer (std::string name, int x, int y, int width, int height, std::string url)
References layers.
void inexor::ui::context::InexorContextProvider::CreateSubContext (CefRefPtr< InexorContextProvider > sub_context) protected inherited
References inexor::ui::context::InexorContextProvider::context.
Referenced by inexor::ui::context::InexorContextProvider::InitializeSubContexts().
void inexor::ui::context::InexorContextProvider::CreateVariable (const CefString & name, bool readonly = false) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::layer::InexorLayerManager::DestroyLayers ()
References layers.
bool inexor::ui::layer::InexorLayerManager::Execute (const CefString & name, CefRefPtr< CefV8Value > object, const CefV8ValueList & arguments, CefRefPtr< CefV8Value > & retval, CefString & exception) override
bool inexor::ui::layer::InexorLayerManager::Get (const CefString & name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > & retval, CefString & exception) override
CefRefPtr< CefV8Value > inexor::ui::context::InexorContextProvider::GetContext () inherited
References inexor::ui::context::InexorContextProvider::context, inexor::ui::context::InexorContextProvider::GetContextName(), inexor::ui::context::InexorContextProvider::InitializeContext(), inexor::ui::context::InexorContextProvider::InitializeSubContexts(), Log, and inexor::util::log_manager::ui.
std::string inexor::ui::layer::InexorLayerManager::GetContextName () inline override virtual
Implements inexor::ui::context::InexorContextProvider.
std::list< CefRefPtr< InexorLayer > >::iterator inexor::ui::layer::InexorLayerManager::GetIterator (std::string name) private
Returns an iterator instance pointing to the layer element with the given name.
If no element was found, the iterator points to end() which means there is no layer with the given name.
References layers.
Referenced by BringForward(), BringToFront(), LayerExists(), SendBackward(), and SendToBack().
CefRefPtr< InexorLayer > inexor::ui::layer::InexorLayerManager::GetLayer (std::string name)
References layers.
Referenced by HideLayer(), and ShowLayer().
std::list<CefRefPtr<InexorLayer> > inexor::ui::layer::InexorLayerManager::GetLayerList () inline
References layers.
std::list< std::string > inexor::ui::layer::InexorLayerManager::GetLayers ()
References layers.
int inexor::ui::layer::InexorLayerManager::GetScreenHeight () inline
References height.
int inexor::ui::layer::InexorLayerManager::GetScreenWidth () inline
References width.
void inexor::ui::layer::InexorLayerManager::HideLayer (std::string name)
References GetLayer(), Log, and inexor::util::log_manager::std.
inexor::ui::layer::InexorLayerManager::IMPLEMENT_REFCOUNTING (InexorLayerManager) private
void inexor::ui::layer::InexorLayerManager::InitializeContext () override virtual
Implements inexor::ui::context::InexorContextProvider.
void inexor::ui::layer::InexorLayerManager::InitializeLayer (CefRefPtr< InexorLayerProvider > layer_provider)
References CreateLayer(), Log, and inexor::util::log_manager::std.
Referenced by InitializeLayers().
void inexor::ui::layer::InexorLayerManager::InitializeLayers ()
References InitializeLayer(), and layer_providers.
void inexor::ui::context::InexorContextProvider::InitializeSubContexts () inherited
References inexor::ui::context::InexorContextProvider::CreateSubContext(), and inexor::ui::context::InexorContextProvider::sub_contexts.
Referenced by inexor::ui::context::InexorContextProvider::GetContext().
bool inexor::ui::layer::InexorLayerManager::LayerExists (std::string name)
References GetIterator(), and layers.
void inexor::ui::layer::InexorLayerManager::SendBackward (std::string name)
References GetIterator(), and layers.
void inexor::ui::layer::InexorLayerManager::SendKeyEvent (CefKeyEvent event)
References layers.
void inexor::ui::layer::InexorLayerManager::SendMouseClickEvent (const CefMouseEvent & event, CefBrowserHost::MouseButtonType type, bool mouseUp, int clickCount)
References layers.
void inexor::ui::layer::InexorLayerManager::SendMouseMoveEvent (const CefMouseEvent & event, bool mouseLeave)
References layers.
void inexor::ui::layer::InexorLayerManager::SendMouseWheelEvent (const CefMouseEvent & event, int deltaX, int deltaY)
References layers.
void inexor::ui::layer::InexorLayerManager::SendToBack (std::string name)
References GetIterator(), and layers.
bool inexor::ui::layer::InexorLayerManager::Set (const CefString & name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString & exception) override
void inexor::ui::layer::InexorLayerManager::SetScreenSize (int width, int height)
References height, and width.
Referenced by InexorLayerManager().
void inexor::ui::layer::InexorLayerManager::ShowLayer (std::string name)
References GetLayer(), Log, and inexor::util::log_manager::std.
Member Data Documentation
CefRefPtr<CefV8Value> inexor::ui::context::InexorContextProvider::context protected inherited
Referenced by inexor::ui::context::InexorContextProvider::CreateFunction(), inexor::ui::context::InexorContextProvider::CreateSubContext(), inexor::ui::context::InexorContextProvider::CreateVariable(), and inexor::ui::context::InexorContextProvider::GetContext().
int inexor::ui::layer::InexorLayerManager::height private
Referenced by GetScreenHeight(), and SetScreenSize().
std::list<CefRefPtr<InexorLayerProvider> > inexor::ui::layer::InexorLayerManager::layer_providers private
Referenced by AddLayerProvider(), and InitializeLayers().
std::list<CefRefPtr<InexorLayer> > inexor::ui::layer::InexorLayerManager::layers private
Referenced by BringForward(), BringToFront(), CreateLayer(), DestroyLayers(), GetIterator(), GetLayer(), GetLayerList(), GetLayers(), LayerExists(), SendBackward(), SendKeyEvent(), SendMouseClickEvent(), SendMouseMoveEvent(), SendMouseWheelEvent(), and SendToBack().
std::list<InexorContextProvider*> inexor::ui::context::InexorContextProvider::sub_contexts protected inherited
Referenced by inexor::ui::context::InexorContextProvider::AddSubContext(), and inexor::ui::context::InexorContextProvider::InitializeSubContexts().
int inexor::ui::layer::InexorLayerManager::width private
Referenced by GetScreenWidth(), and SetScreenSize().
The documentation for this class was generated from the following files:
inexor/ui/layer/InexorLayerManager.hpp
inexor/ui/layer/InexorLayerManager.cpp