Inexor: inexor::ui::layer::InexorAppLayer Class Reference
inexor::ui::layer::InexorAppLayer Class Reference
The application layer of the inexor user interface.
#include <InexorAppLayer.hpp>
Public Member Functions
InexorAppLayer (std::string &name, std::string &url)
void InitializeContext () override
bool Execute (const CefString &name, CefRefPtr< CefV8Value > object, const CefV8ValueList &arguments, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Get (const CefString &name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Set (const CefString &name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString &exception) override
std::string GetContextName () override
void Reload ()
void Resize (int x, int y, int width, int height)
void AutoResize (int width, int height)
void SetVisibility (bool _is_visible) override
void SetAcceptingKeyInput (bool _is_accepting_key_input) override
void SetAcceptingMouseInput (bool _is_accepting_mouse_input) override
void FireUiEvent (std::string name, bool value)
void FireUiEvent (std::string name, std::string value)
CefRefPtr< CefV8Value > GetContext ()
void InitializeSubContexts ()
void AddSubContext (InexorContextProvider *sub_context)
std::string GetLayerName () override
void SetLayerName (std::string &_name) override
std::string GetUrl () override
void SetUrl (std::string &_url) override
bool GetVisibility () override
bool GetAcceptingKeyInput () override
bool GetAcceptingMouseInput () override
void Show ()
void Hide ()
void ToggleVisibility ()
void SetLayer (CefRefPtr< InexorLayer > layer)
Protected Member Functions
void CreateFunction (const CefString &name)
void CreateFunction (const CefString &name, CefRefPtr< CefV8Handler > handler)
void CreateVariable (const CefString &name, bool readonly=false)
void CreateSubContext (CefRefPtr< InexorContextProvider > sub_context)
std::string GetLocalUrl (std::string relpath)
Protected Attributes
std::list
< InexorContextProvider * > sub_contexts
CefRefPtr< CefV8Value > context
bool is_visible
bool is_accepting_key_input
bool is_accepting_mouse_input
std::string name
std::string url
CefRefPtr< InexorLayer > layer
Private Member Functions
IMPLEMENT_REFCOUNTING (InexorAppLayer)
Private Attributes
std::string _name
std::string _url
Detailed Description
The application layer of the inexor user interface.
Constructor & Destructor Documentation
inexor::ui::layer::InexorAppLayer::InexorAppLayer (std::string & name, std::string & url) inline
Member Function Documentation
void inexor::ui::context::InexorContextProvider::AddSubContext (InexorContextProvider * sub_context) inherited
References inexor::ui::context::InexorContextProvider::sub_contexts.
void inexor::ui::layer::InexorAppLayer::AutoResize (int width, int height)
References inexor::ui::layer::InexorLayerProvider::layer, and Resize().
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name, CefRefPtr< CefV8Handler > handler) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::context::InexorContextProvider::CreateSubContext (CefRefPtr< InexorContextProvider > sub_context) protected inherited
References inexor::ui::context::InexorContextProvider::context.
Referenced by inexor::ui::context::InexorContextProvider::InitializeSubContexts().
void inexor::ui::context::InexorContextProvider::CreateVariable (const CefString & name, bool readonly = false) protected inherited
References inexor::ui::context::InexorContextProvider::context.
bool inexor::ui::layer::InexorAppLayer::Execute (const CefString & name, CefRefPtr< CefV8Value > object, const CefV8ValueList & arguments, CefRefPtr< CefV8Value > & retval, CefString & exception) override
void inexor::ui::layer::InexorAppLayer::FireUiEvent (std::string name, bool value)
References inexor::ui::layer::InexorLayerProvider::layer.
Referenced by SetAcceptingKeyInput(), SetAcceptingMouseInput(), and SetVisibility().
void inexor::ui::layer::InexorAppLayer::FireUiEvent (std::string name, std::string value)
References inexor::ui::layer::InexorLayerProvider::layer.
bool inexor::ui::layer::InexorAppLayer::Get (const CefString & name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > & retval, CefString & exception) override
bool inexor::ui::layer::AbstractInexorLayerProvider::GetAcceptingKeyInput () inline override virtual inherited
Implements inexor::ui::layer::InexorLayerProvider.
References inexor::ui::layer::AbstractInexorLayerProvider::is_accepting_key_input.
Referenced by inexor::ui::layer::InexorHudLayer::SetAcceptingKeyInput(), inexor::ui::layer::InexorConsoleLayer::SetAcceptingKeyInput(), and SetAcceptingKeyInput().
bool inexor::ui::layer::AbstractInexorLayerProvider::GetAcceptingMouseInput () inline override virtual inherited
Implements inexor::ui::layer::InexorLayerProvider.
References inexor::ui::layer::AbstractInexorLayerProvider::is_accepting_mouse_input.
Referenced by inexor::ui::layer::InexorHudLayer::SetAcceptingMouseInput(), inexor::ui::layer::InexorConsoleLayer::SetAcceptingMouseInput(), and SetAcceptingMouseInput().
CefRefPtr< CefV8Value > inexor::ui::context::InexorContextProvider::GetContext () inherited
References inexor::ui::context::InexorContextProvider::context, inexor::ui::context::InexorContextProvider::GetContextName(), inexor::ui::context::InexorContextProvider::InitializeContext(), inexor::ui::context::InexorContextProvider::InitializeSubContexts(), Log, and inexor::util::log_manager::ui.
std::string inexor::ui::layer::InexorAppLayer::GetContextName () inline override virtual
Implements inexor::ui::context::InexorContextProvider.
References _name.
std::string inexor::ui::layer::AbstractInexorLayerProvider::GetLayerName () inline override virtual inherited
Implements inexor::ui::layer::InexorLayerProvider.
References inexor::ui::layer::AbstractInexorLayerProvider::name.
std::string inexor::ui::layer::InexorLayerProvider::GetLocalUrl (std::string relpath) inline protected inherited
References GetCurrentDir.
std::string inexor::ui::layer::AbstractInexorLayerProvider::GetUrl () inline override virtual inherited
Implements inexor::ui::layer::InexorLayerProvider.
References inexor::ui::layer::AbstractInexorLayerProvider::url.
Referenced by inexor::ui::layer::InexorHudLayer::Reload(), inexor::ui::layer::InexorConsoleLayer::Reload(), and Reload().
bool inexor::ui::layer::AbstractInexorLayerProvider::GetVisibility () inline override virtual inherited
Implements inexor::ui::layer::InexorLayerProvider.
References inexor::ui::layer::AbstractInexorLayerProvider::is_visible.
Referenced by inexor::ui::layer::InexorHudLayer::SetVisibility(), inexor::ui::layer::InexorConsoleLayer::SetVisibility(), and SetVisibility().
void inexor::ui::layer::AbstractInexorLayerProvider::Hide () inline inherited
References inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingKeyInput(), inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingMouseInput(), and inexor::ui::layer::AbstractInexorLayerProvider::SetVisibility().
inexor::ui::layer::InexorAppLayer::IMPLEMENT_REFCOUNTING (InexorAppLayer) private
void inexor::ui::layer::InexorAppLayer::InitializeContext () override virtual
Implements inexor::ui::context::InexorContextProvider.
void inexor::ui::context::InexorContextProvider::InitializeSubContexts () inherited
References inexor::ui::context::InexorContextProvider::CreateSubContext(), and inexor::ui::context::InexorContextProvider::sub_contexts.
Referenced by inexor::ui::context::InexorContextProvider::GetContext().
void inexor::ui::layer::InexorAppLayer::Reload ()
References inexor::ui::layer::AbstractInexorLayerProvider::GetUrl(), inexor::ui::layer::AbstractInexorLayerProvider::SetUrl(), and inexor::ui::layer::AbstractInexorLayerProvider::url.
void inexor::ui::layer::InexorAppLayer::Resize (int x, int y, int width, int height)
References inexor::ui::layer::AbstractInexorLayerProvider::is_visible, inexor::ui::layer::InexorLayerProvider::layer, Log, and inexor::util::log_manager::ui.
Referenced by AutoResize().
bool inexor::ui::layer::InexorAppLayer::Set (const CefString & name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString & exception) override
void inexor::ui::layer::InexorAppLayer::SetAcceptingKeyInput (bool _is_accepting_key_input) override virtual
Implements inexor::ui::layer::InexorLayerProvider.
References FireUiEvent(), inexor::ui::layer::AbstractInexorLayerProvider::GetAcceptingKeyInput(), and inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingKeyInput().
void inexor::ui::layer::InexorAppLayer::SetAcceptingMouseInput (bool _is_accepting_mouse_input) override virtual
Implements inexor::ui::layer::InexorLayerProvider.
References FireUiEvent(), inexor::ui::layer::AbstractInexorLayerProvider::GetAcceptingMouseInput(), and inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingMouseInput().
void inexor::ui::layer::InexorLayerProvider::SetLayer (CefRefPtr< InexorLayer > layer) inline inherited
References inexor::ui::layer::InexorLayerProvider::layer.
void inexor::ui::layer::AbstractInexorLayerProvider::SetLayerName (std::string & _name) inline override virtual inherited
Implements inexor::ui::layer::InexorLayerProvider.
References inexor::ui::layer::AbstractInexorLayerProvider::name.
void inexor::ui::layer::AbstractInexorLayerProvider::SetUrl (std::string & _url) inline override virtual inherited
Implements inexor::ui::layer::InexorLayerProvider.
References inexor::ui::layer::AbstractInexorLayerProvider::url.
Referenced by inexor::ui::layer::InexorHudLayer::Reload(), inexor::ui::layer::InexorConsoleLayer::Reload(), and Reload().
void inexor::ui::layer::InexorAppLayer::SetVisibility (bool _is_visible) override virtual
Implements inexor::ui::layer::InexorLayerProvider.
References FireUiEvent(), inexor::ui::layer::AbstractInexorLayerProvider::GetVisibility(), and inexor::ui::layer::AbstractInexorLayerProvider::SetVisibility().
void inexor::ui::layer::AbstractInexorLayerProvider::Show () inline inherited
References inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingKeyInput(), inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingMouseInput(), and inexor::ui::layer::AbstractInexorLayerProvider::SetVisibility().
void inexor::ui::layer::AbstractInexorLayerProvider::ToggleVisibility () inline inherited
References inexor::ui::layer::AbstractInexorLayerProvider::is_visible, and inexor::ui::layer::AbstractInexorLayerProvider::SetVisibility().
Member Data Documentation
std::string inexor::ui::layer::InexorAppLayer::_name private
Referenced by GetContextName().
std::string inexor::ui::layer::InexorAppLayer::_url private
CefRefPtr<CefV8Value> inexor::ui::context::InexorContextProvider::context protected inherited
Referenced by inexor::ui::context::InexorContextProvider::CreateFunction(), inexor::ui::context::InexorContextProvider::CreateSubContext(), inexor::ui::context::InexorContextProvider::CreateVariable(), and inexor::ui::context::InexorContextProvider::GetContext().
bool inexor::ui::layer::AbstractInexorLayerProvider::is_accepting_key_input protected inherited
Referenced by inexor::ui::layer::AbstractInexorLayerProvider::GetAcceptingKeyInput(), and inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingKeyInput().
bool inexor::ui::layer::AbstractInexorLayerProvider::is_accepting_mouse_input protected inherited
Referenced by inexor::ui::layer::AbstractInexorLayerProvider::GetAcceptingMouseInput(), and inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingMouseInput().
bool inexor::ui::layer::AbstractInexorLayerProvider::is_visible protected inherited
Referenced by inexor::ui::layer::AbstractInexorLayerProvider::GetVisibility(), inexor::ui::layer::InexorHudLayer::Resize(), inexor::ui::layer::InexorConsoleLayer::Resize(), Resize(), inexor::ui::layer::AbstractInexorLayerProvider::SetVisibility(), and inexor::ui::layer::AbstractInexorLayerProvider::ToggleVisibility().
CefRefPtr<InexorLayer> inexor::ui::layer::InexorLayerProvider::layer protected inherited
Referenced by inexor::ui::layer::InexorHudLayer::AutoResize(), inexor::ui::layer::InexorConsoleLayer::AutoResize(), AutoResize(), FireUiEvent(), inexor::ui::layer::InexorHudLayer::Resize(), inexor::ui::layer::InexorConsoleLayer::Resize(), Resize(), inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingKeyInput(), inexor::ui::layer::AbstractInexorLayerProvider::SetAcceptingMouseInput(), inexor::ui::layer::InexorLayerProvider::SetLayer(), and inexor::ui::layer::AbstractInexorLayerProvider::SetVisibility().
std::string inexor::ui::layer::AbstractInexorLayerProvider::name protected inherited
Referenced by inexor::ui::layer::AbstractInexorLayerProvider::GetLayerName(), and inexor::ui::layer::AbstractInexorLayerProvider::SetLayerName().
std::list<InexorContextProvider*> inexor::ui::context::InexorContextProvider::sub_contexts protected inherited
Referenced by inexor::ui::context::InexorContextProvider::AddSubContext(), and inexor::ui::context::InexorContextProvider::InitializeSubContexts().
std::string inexor::ui::layer::AbstractInexorLayerProvider::url protected inherited
Referenced by inexor::ui::layer::AbstractInexorLayerProvider::GetUrl(), inexor::ui::layer::InexorHudLayer::Reload(), inexor::ui::layer::InexorConsoleLayer::Reload(), Reload(), and inexor::ui::layer::AbstractInexorLayerProvider::SetUrl().
The documentation for this class was generated from the following files:
inexor/ui/layer/InexorAppLayer.hpp
inexor/ui/layer/InexorAppLayer.cpp