Inexor: inexor::ui::context::InexorContextManager Class Reference
inexor::ui::context::InexorContextManager Class Reference
#include <InexorContextManager.hpp>
Public Member Functions
InexorContextManager ()
void InitializeContext () override
bool Execute (const CefString &name, CefRefPtr< CefV8Value > object, const CefV8ValueList &arguments, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Get (const CefString &name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > &retval, CefString &exception) override
bool Set (const CefString &name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString &exception) override
std::string GetContextName () override
CefRefPtr< CefV8Value > GetContext ()
void InitializeSubContexts ()
void AddSubContext (InexorContextProvider *sub_context)
Protected Member Functions
void CreateFunction (const CefString &name)
void CreateFunction (const CefString &name, CefRefPtr< CefV8Handler > handler)
void CreateVariable (const CefString &name, bool readonly=false)
void CreateSubContext (CefRefPtr< InexorContextProvider > sub_context)
Protected Attributes
std::list
< InexorContextProvider * > sub_contexts
CefRefPtr< CefV8Value > context
Private Member Functions
IMPLEMENT_REFCOUNTING (InexorContextManager)
Constructor & Destructor Documentation
inexor::ui::context::InexorContextManager::InexorContextManager () inline
Member Function Documentation
void inexor::ui::context::InexorContextProvider::AddSubContext (InexorContextProvider * sub_context) inherited
References inexor::ui::context::InexorContextProvider::sub_contexts.
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::context::InexorContextProvider::CreateFunction (const CefString & name, CefRefPtr< CefV8Handler > handler) protected inherited
References inexor::ui::context::InexorContextProvider::context.
void inexor::ui::context::InexorContextProvider::CreateSubContext (CefRefPtr< InexorContextProvider > sub_context) protected inherited
References inexor::ui::context::InexorContextProvider::context.
Referenced by inexor::ui::context::InexorContextProvider::InitializeSubContexts().
void inexor::ui::context::InexorContextProvider::CreateVariable (const CefString & name, bool readonly = false) protected inherited
References inexor::ui::context::InexorContextProvider::context.
bool inexor::ui::context::InexorContextManager::Execute (const CefString & name, CefRefPtr< CefV8Value > object, const CefV8ValueList & arguments, CefRefPtr< CefV8Value > & retval, CefString & exception) override
bool inexor::ui::context::InexorContextManager::Get (const CefString & name, const CefRefPtr< CefV8Value > object, CefRefPtr< CefV8Value > & retval, CefString & exception) override
CefRefPtr< CefV8Value > inexor::ui::context::InexorContextProvider::GetContext () inherited
References inexor::ui::context::InexorContextProvider::context, inexor::ui::context::InexorContextProvider::GetContextName(), inexor::ui::context::InexorContextProvider::InitializeContext(), inexor::ui::context::InexorContextProvider::InitializeSubContexts(), Log, and inexor::util::log_manager::ui.
std::string inexor::ui::context::InexorContextManager::GetContextName () inline override virtual
Implements inexor::ui::context::InexorContextProvider.
inexor::ui::context::InexorContextManager::IMPLEMENT_REFCOUNTING (InexorContextManager) private
void inexor::ui::context::InexorContextManager::InitializeContext () override virtual
Implements inexor::ui::context::InexorContextProvider.
void inexor::ui::context::InexorContextProvider::InitializeSubContexts () inherited
References inexor::ui::context::InexorContextProvider::CreateSubContext(), and inexor::ui::context::InexorContextProvider::sub_contexts.
Referenced by inexor::ui::context::InexorContextProvider::GetContext().
bool inexor::ui::context::InexorContextManager::Set (const CefString & name, const CefRefPtr< CefV8Value > object, const CefRefPtr< CefV8Value > value, CefString & exception) override
Member Data Documentation
CefRefPtr<CefV8Value> inexor::ui::context::InexorContextProvider::context protected inherited
Referenced by inexor::ui::context::InexorContextProvider::CreateFunction(), inexor::ui::context::InexorContextProvider::CreateSubContext(), inexor::ui::context::InexorContextProvider::CreateVariable(), and inexor::ui::context::InexorContextProvider::GetContext().
std::list<InexorContextProvider*> inexor::ui::context::InexorContextProvider::sub_contexts protected inherited
Referenced by inexor::ui::context::InexorContextProvider::AddSubContext(), and inexor::ui::context::InexorContextProvider::InitializeSubContexts().
The documentation for this class was generated from the following files:
inexor/ui/context/InexorContextManager.hpp
inexor/ui/context/InexorContextManager.cpp