Inexor: inexor/client/network.hpp File Reference
network.hpp File Reference
#include <enet/enet.h>
Functions
void sendclientpacket (ENetPacket *packet, int chan)
void flushclient ()
void disconnect (bool async=false, bool cleanup=true)
bool isconnected (bool attempt=false, bool local=true)
const ENetAddress * connectedpeer ()
bool multiplayer (bool msg=true)
void neterr (const char *s, bool disc=true)
void gets2c ()
void notifywelcome ()
This function gets executed as we get connected.
ENetPacket * send_file (stream *file, const char *format="",...)
Send a file to all other clients.
void connectserv (const char *servername, int port, const char *serverpassword, const char *mapwish=nullptr, int modewish=-1)
void abortconnect ()
void clientkeepalive ()
bool resolverwait (const char *name, ENetAddress *address)
Function Documentation
void abortconnect ()
References clienthost, game::connectfail(), connpeer, and curpeer.
Referenced by connectserv(), gets2c(), quit(), and trydisconnect().
void clientkeepalive ()
References clienthost.
Referenced by genenvmap(), and renderprogress().
const ENetAddress* connectedpeer ()
References curpeer.
Referenced by game::renderscoreboard().
void connectserv (const char * servername, int port, const char * serverpassword, const char * mapwish = nullptr, int modewish = -1)
References abortconnect(), clienthost, connattempts, game::connectattempt(), connmillis, connpeer, Log, NUM_ENET_CHANNELS, resolverwait(), server_port(), setsvar(), setvar(), inexor::util::log_manager::std, and totalmillis.
Referenced by game::changemap(), and reconnect().
void disconnect (bool async = false, bool cleanup = true)
References clienthost, connpeer, curpeer, DISC_NONE, discmillis, game::gamedisconnect(), Log, mainmenu, inexor::util::log_manager::std, and totalmillis.
Referenced by gets2c(), neterr(), game::parsemessages(), quit(), and trydisconnect().
void flushclient ()
References clienthost.
Referenced by game::c2sinfo(), entities::jumppadeffects(), and entities::teleporteffects().
void gets2c ()
References abortconnect(), clienthost, connattempts, connmillis, connpeer, curpeer, DISC_NONE, DISC_NUM, discmillis, disconnect(), disconnectreason(), game::gameconnect(), Log, game::parsepacketclient(), setrate(), inexor::util::log_manager::std, throttle(), and totalmillis.
Referenced by game::updateworld().
bool isconnected (bool attempt = false, bool local = true)
References connpeer, and curpeer.
Referenced by game::allowedittoggle(), game::changemap(), cleargui(), clearmainmenu(), menuprocess(), newmap(), game::pausegame(), game::persistteams(), and toggleedit().
bool multiplayer (bool msg = true)
References curpeer, Log, and inexor::util::log_manager::std.
Referenced by game::allowedittoggle(), canpaintblendmap(), clearblendmapsel(), edithmap(), invertblendmap(), invertblendmapsel(), pasteprefab(), game::preloadplayermodel(), game::renderscoreboard(), save_world(), saveprefab(), showblendmap(), shrinkmap(), swapundo(), ai::update(), and vlayer().
void neterr (const char * s, bool disc = true)
References disconnect(), Log, and inexor::util::log_manager::std.
Referenced by game::newclient(), game::parsemessages(), and game::parsepositions().
void notifywelcome ()
This function gets executed as we get connected.
Referenced by game::parsemessages().
bool resolverwait (const char * name, ENetAddress * address)
References defformatstring, f(), inexor::io::input_router, inexor::io::InputRouter::interceptkey(), loopv, inexor::rpc::min(), resolverthread::query, querycond, renderprogress(), resolverinit(), RESOLVERLIMIT, resolvermutex, resolverqueries, resolverresults, resolverstop(), resolverthreads, resultcond, and recorder::starttime.
Referenced by connectserv().
ENetPacket* send_file (stream * file, const char * format = "", ...)
Send a file to all other clients.
References CHAN_FILE, make_file_packet(), and sendclientpacket().
Referenced by game::sendmap().
void sendclientpacket (ENetPacket * packet, int chan)
References curpeer.
Referenced by entities::jumppadeffects(), game::parsemessages(), send_file(), game::sendclipboard(), game::sendintro(), game::sendmessages(), game::sendposition(), game::sendpositions(), and entities::teleporteffects().