Inexor: inexor/texture/compressedtex.hpp File Reference
compressedtex.hpp File Reference
compressed texture (mostly dds) loading.
#include "inexor/shared/cube_types.hpp"
Classes
struct DDCOLORKEY
struct DDPIXELFORMAT
struct DDSCAPS2
struct DDSURFACEDESC2
union DDPIXELFORMAT.__unnamed__
union DDPIXELFORMAT.__unnamed__
union DDPIXELFORMAT.__unnamed__
struct DDPIXELFORMAT.__unnamed__.MultiSampleCaps
union DDPIXELFORMAT.__unnamed__
union DDPIXELFORMAT.__unnamed__
union DDSURFACEDESC2.__unnamed__
union DDSURFACEDESC2.__unnamed__
union DDSURFACEDESC2.__unnamed__
union DDSURFACEDESC2.__unnamed__
Enumerations
enum {
DDSD_CAPS = 0x00000001, DDSD_HEIGHT = 0x00000002, DDSD_WIDTH = 0x00000004, DDSD_PITCH = 0x00000008,
DDSD_PIXELFORMAT = 0x00001000, DDSD_MIPMAPCOUNT = 0x00020000, DDSD_LINEARSIZE = 0x00080000, DDSD_BACKBUFFERCOUNT = 0x00800000,
DDPF_ALPHAPIXELS = 0x00000001, DDPF_FOURCC = 0x00000004, DDPF_INDEXED = 0x00000020, DDPF_ALPHA = 0x00000002,
DDPF_RGB = 0x00000040, DDPF_COMPRESSED = 0x00000080, DDPF_LUMINANCE = 0x00020000, DDSCAPS_COMPLEX = 0x00000008,
DDSCAPS_TEXTURE = 0x00001000, DDSCAPS_MIPMAP = 0x00400000, DDSCAPS2_CUBEMAP = 0x00000200, DDSCAPS2_CUBEMAP_POSITIVEX = 0x00000400,
DDSCAPS2_CUBEMAP_NEGATIVEX = 0x00000800, DDSCAPS2_CUBEMAP_POSITIVEY = 0x00001000, DDSCAPS2_CUBEMAP_NEGATIVEY = 0x00002000, DDSCAPS2_CUBEMAP_POSITIVEZ = 0x00004000,
DDSCAPS2_CUBEMAP_NEGATIVEZ = 0x00008000, DDSCAPS2_VOLUME = 0x00200000, FOURCC_DXT1 = 0x31545844, FOURCC_DXT2 = 0x32545844,
FOURCC_DXT3 = 0x33545844, FOURCC_DXT4 = 0x34545844, FOURCC_DXT5 = 0x35545844
}
Functions
bool loaddds (const char *filename, ImageData &image, int force=0)
Detailed Description
compressed texture (mostly dds) loading.
Class Documentation
struct DDCOLORKEY
Class Members
uint dwColorSpaceHighValue
uint dwColorSpaceLowValue
struct DDPIXELFORMAT
Class Members
union DDPIXELFORMAT __unnamed__
union DDPIXELFORMAT __unnamed__
union DDPIXELFORMAT __unnamed__
union DDPIXELFORMAT __unnamed__
union DDPIXELFORMAT __unnamed__
uint dwFlags
uint dwFourCC
uint dwSize
struct DDSCAPS2
Class Members
uint dwCaps
uint dwCaps2
uint dwCaps3
uint dwCaps4
struct DDSURFACEDESC2
Class Members
union DDSURFACEDESC2 __unnamed__
union DDSURFACEDESC2 __unnamed__
union DDSURFACEDESC2 __unnamed__
union DDSURFACEDESC2 __unnamed__
DDCOLORKEY ddckCKDestBlt
DDCOLORKEY ddckCKSrcBlt
DDCOLORKEY ddckCKSrcOverlay
DDSCAPS2 ddsCaps
uint dwAlphaBitDepth
uint dwBackBufferCount
uint dwFlags
uint dwHeight
uint dwReserved
uint dwSize
uint dwTextureStage
uint dwWidth
uint lpSurface
union DDPIXELFORMAT.__unnamed__
Class Members
uint dwAlphaBitDepth
uint dwBumpBitCount
uint dwLuminanceBitCount
uint dwPrivateFormatBitCount
uint dwRGBBitCount
uint dwYUVBitCount
uint dwZBufferBitDepth
union DDPIXELFORMAT.__unnamed__
Class Members
uint dwBumpDuBitMask
uint dwLuminanceBitMask
uint dwOperations
uint dwRBitMask
uint dwStencilBitDepth
uint dwYBitMask
union DDPIXELFORMAT.__unnamed__
Class Members
uint dwBumpDvBitMask
uint dwGBitMask
uint dwUBitMask
uint dwZBitMask
__unnamed__ MultiSampleCaps
struct DDPIXELFORMAT.__unnamed__.MultiSampleCaps
Class Members
ushort wBltMSTypes
ushort wFlipMSTypes
union DDPIXELFORMAT.__unnamed__
Class Members
uint dwBBitMask
uint dwBumpLuminanceBitMask
uint dwStencilBitMask
uint dwVBitMask
union DDPIXELFORMAT.__unnamed__
Class Members
uint dwLuminanceAlphaBitMask
uint dwRGBAlphaBitMask
uint dwRGBZBitMask
uint dwYUVAlphaBitMask
uint dwYUVZBitMask
union DDSURFACEDESC2.__unnamed__
Class Members
uint dwLinearSize
int lPitch
union DDSURFACEDESC2.__unnamed__
Class Members
uint dwMipMapCount
uint dwRefreshRate
uint dwSrcVBHandle
union DDSURFACEDESC2.__unnamed__
Class Members
DDCOLORKEY ddckCKDestOverlay
uint dwEmptyFaceColor
union DDSURFACEDESC2.__unnamed__
Class Members
DDPIXELFORMAT ddpfPixelFormat
uint dwFVF
Enumeration Type Documentation
anonymous enum
Enumerator
DDSD_CAPS
DDSD_HEIGHT
DDSD_WIDTH
DDSD_PITCH
DDSD_PIXELFORMAT
DDSD_MIPMAPCOUNT
DDSD_LINEARSIZE
DDSD_BACKBUFFERCOUNT
DDPF_ALPHAPIXELS
DDPF_FOURCC
DDPF_INDEXED
DDPF_ALPHA
DDPF_RGB
DDPF_COMPRESSED
DDPF_LUMINANCE
DDSCAPS_COMPLEX
DDSCAPS_TEXTURE
DDSCAPS_MIPMAP
DDSCAPS2_CUBEMAP
DDSCAPS2_CUBEMAP_POSITIVEX
DDSCAPS2_CUBEMAP_NEGATIVEX
DDSCAPS2_CUBEMAP_POSITIVEY
DDSCAPS2_CUBEMAP_NEGATIVEY
DDSCAPS2_CUBEMAP_POSITIVEZ
DDSCAPS2_CUBEMAP_NEGATIVEZ
DDSCAPS2_VOLUME
FOURCC_DXT1
FOURCC_DXT2
FOURCC_DXT3
FOURCC_DXT4
FOURCC_DXT5
Function Documentation
bool loaddds (const char * filename, ImageData & image, int force = 0)
References ImageData::calcsize(), ImageData::cleanup(), hmap::d, ImageData::data, DDPF_ALPHAPIXELS, DDPF_FOURCC, DDSURFACEDESC2::dwFlags, DDSURFACEDESC2::dwHeight, DDSURFACEDESC2::dwSize, DDSURFACEDESC2::dwWidth, f(), format(), FOURCC_DXT1, FOURCC_DXT2, FOURCC_DXT3, FOURCC_DXT4, FOURCC_DXT5, GLenum(), hasS3TC, lilswap(), Log, openfile(), stream::read(), ImageData::setdata(), and inexor::util::log_manager::std.
Referenced by texturedata().