Inexor: inexor/engine/console.hpp File Reference
console.hpp File Reference
Functions
void processkey (int code, bool isdown)
void processtextinput (const char *str, int len)
int rendercommand (int x, int y, int w)
int renderconsole (int w, int h, int abovehud)
void resetcomplete ()
void complete (char *s, int maxlen, const char *cmdprefix, bool backwards)
const char * getkeyname (int code)
const char * addreleaseaction (char *s)
void writebinds (stream *f)
void writecompletions (stream *f)
Function Documentation
const char* addreleaseaction (char * s)
References releaseaction::action, releaseaction::key, keypressed, keym::name, and releaseactions.
Referenced by callcommand(), onrelease(), and runcode().
void complete (char * s, int maxlen, const char * cmdprefix, bool backwards)
References completesize, completions, copystring(), DELETEA, gle::end(), enumerate, f(), filesval::files, idents, lastcomplete, loopv, inexor::rpc::min(), newstring(), prependstring(), and filesval::update().
Referenced by consolekey().
const char* getkeyname (int code)
References keyms, and keym::name.
Referenced by g3d_key().
void processkey (int code, bool isdown)
void processtextinput (const char * str, int len)
int rendercommand (int x, int y, int w)
References commandbuf, commandmillis, commandpos, commandprompt, defformatstring, draw_text(), and text_bounds().
Referenced by gl_drawhud().
int renderconsole (int w, int h, int abovehud)
References game::clipconsole(), conskip, consolebox(), drawconlines(), FONTH, inexor::rpc::min(), and miniconskip.
Referenced by gl_drawhud().
void resetcomplete ()
References completesize.
Referenced by consoleinput(), and consolekey().
void writebinds (stream * f)
References keym::actions, vector< T, MINSIZE >::add(), enumerate, escapestring(), keyms, loopj, loopv, keym::name, stream::printf(), vector< T, MINSIZE >::sortname(), and validateblock().
Referenced by writecfg().
void writecompletions (stream * f)
References vector< T, MINSIZE >::add(), completions, filesval::dir, enumeratekt, escapeid(), escapestring(), filesval::ext, FILES_LIST, loopv, stream::printf(), vector< T, MINSIZE >::sort(), filesval::type, and validateblock().
Referenced by writecfg().