Inexor: inexor/shared/cube_endian.hpp File Reference
cube_endian.hpp File Reference
#include <SDL2/SDL.h>
#include "inexor/shared/cube_types.hpp"
Functions
ushort endianswap16 (ushort n)
uint endianswap32 (uint n)
ullong endianswap64 (ullong n)
template<class T >
T endianswap (T n)
template<>
ushort endianswap< ushort > (ushort n)
template<>
short endianswap< short > (short n)
template<>
uint endianswap< uint > (uint n)
template<>
int endianswap< int > (int n)
template<>
ullong endianswap< ullong > (ullong n)
template<>
llong endianswap< llong > (llong n)
template<>
double endianswap< double > (double n)
template<class T >
void endianswap (T *buf, size_t len)
template<class T >
T endiansame (T n)
template<class T >
void endiansame (T *buf, size_t len)
template<class T >
T lilswap (T n)
template<class T >
void lilswap (T *buf, size_t len)
template<class T >
T bigswap (T n)
template<class T >
void bigswap (T *buf, size_t len)
Variables
const int islittleendian = 1
Legacy manual byte order swapping for serialisation.
Function Documentation
template<class T > T bigswap (T n) inline
References endianswap(), and islittleendian.
Referenced by stream::getbig(), and stream::putbig().
template<class T > void bigswap (T * buf, size_t len) inline
References endianswap(), and islittleendian.
template<class T > T endiansame (T n) inline
template<class T > void endiansame (T * buf, size_t len) inline
template<class T > T endianswap (T n) inline
References endianswap32(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by bigswap(), endianswap(), lilswap(), and aviwriter::writesound().
template<class T > void endianswap (T * buf, size_t len) inline
References gle::end(), and endianswap().
ushort endianswap16 (ushort n) inline
Referenced by endianswap< short >(), and endianswap< ushort >().
uint endianswap32 (uint n) inline
Referenced by endianswap(), endianswap64(), endianswap< int >(), and endianswap< uint >().
ullong endianswap64 (ullong n) inline
References endianswap32().
Referenced by endianswap< double >(), endianswap< llong >(), and endianswap< ullong >().
template<> double endianswap< double > (double n) inline
References endianswap64(), and anonymous_namespace{utilTest.cpp}::t().
template<> int endianswap< int > (int n) inline
References endianswap32().
template<> llong endianswap< llong > (llong n) inline
References endianswap64().
template<> short endianswap< short > (short n) inline
References endianswap16().
template<> uint endianswap< uint > (uint n) inline
References endianswap32().
template<> ullong endianswap< ullong > (ullong n) inline
References endianswap64().
template<> ushort endianswap< ushort > (ushort n) inline
References endianswap16().
template<class T > T lilswap (T n) inline
References endianswap(), and islittleendian.
Referenced by game::edittrigger(), gendds(), getfloat(), stream::getlil(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), load_world(), loadc(), loaddds(), loadents(), iqm::iqmmeshgroup::loadiqm(), iqm::iqmmeshgroup::loadiqmanims(), iqm::iqmmeshgroup::loadiqmmeshes(), loadprefab(), packblock(), packcube(), packundo(), packvslots(), game::parsemessages(), server::parsepacket(), putfloat_(), stream::putlil(), server::readdemo(), reorients3tc(), save_world(), saveprefab(), server::setupdemoplayback(), server::setupdemorecord(), unpackblock(), unpackcube(), unpackundo(), unpackvslots(), and server::writedemo().
template<class T > void lilswap (T * buf, size_t len) inline
References endianswap(), and islittleendian.
Variable Documentation
const int islittleendian = 1
Legacy manual byte order swapping for serialisation.
Define mainly two macros: lilswap and bigswap
Avoid this: use libraries which abstract endianess away for saved/transmitted data.
Referenced by bigswap(), tiger::gensboxes(), tiger::hash(), and lilswap().