Inexor: inexor/network/legacy/cube_network.hpp File Reference
cube_network.hpp File Reference
#include <enet/enet.h>
#include <stdarg.h>
#include <stddef.h>
#include <algorithm>
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
Classes
struct ipmask
structure to describe IPs
Macros
#define MAXCLIENTS 128
#define MAXTRANS 5000
#define DMF 16.0f
network quantization scale
#define DNF 100.0f
#define DVELF 1.0f
Functions
void putint (ucharbuf &p, int n)
void putint (packetbuf &p, int n)
void putint (vector< uchar > &p, int n)
int getint (ucharbuf &p)
void putuint (ucharbuf &p, int n)
void putuint (packetbuf &p, int n)
void putuint (vector< uchar > &p, int n)
int getuint (ucharbuf &p)
void putfloat (ucharbuf &p, float f)
void putfloat (packetbuf &p, float f)
void putfloat (vector< uchar > &p, float f)
float getfloat (ucharbuf &p)
void sendstring (const char *t, ucharbuf &p)
void sendstring (const char *t, packetbuf &p)
void sendstring (const char *t, vector< uchar > &p)
void getstring (char *t, ucharbuf &p, size_t len)
template<size_t N>
static void getstring (char(&t)[N], ucharbuf &p)
void filtertext (char *dst, const char *src, bool whitespace, bool forcespace, size_t len)
template<size_t N>
static void filtertext (char(&dst)[N], const char *src, bool whitespace=true, bool forcespace=false)
ENetPacket * make_file_packet (stream *file, const char *format, va_list args)
Puts a file into a ENet packet.
Macro Definition Documentation
#define DMF 16.0f
network quantization scale
Referenced by server::collectservermode::deposittokens(), server::ctfservermode::dropflag(), server::collectservermode::droptokens(), entities::editent(), game::hit(), server::collectservermode::initclient(), server::ctfservermode::initclient(), game::collectclientmode::parse_network_message(), game::ctfclientmode::parse_network_message(), server::collectservermode::parsebases(), server::captureservermode::parsebases(), game::ctfclientmode::parseflags(), server::ctfservermode::parseflags(), game::parsemessages(), server::parsepacket(), game::parsepositions(), server::bombservermode::parsespawnloc(), game::collectclientmode::parsetokens(), server::shotevent::process(), server::bombservermode::pushentity(), game::bombclientmode::senditems(), game::collectclientmode::senditems(), game::ctfclientmode::senditems(), game::captureclientmode::senditems(), game::sendposition(), and game::shoot().
#define DNF 100.0f
Referenced by server::dodamage(), game::hit(), game::parsemessages(), and server::parsepacket().
#define DVELF 1.0f
Referenced by server::parsepacket(), game::parsepositions(), and game::sendposition().
#define MAXCLIENTS 128
Referenced by aiman::addai(), aiman::deleteai(), server::get_client_info(), game::newclient(), and server::setup_network_sockets().
#define MAXTRANS 5000
Referenced by game::addmsg(), server::checkserversockets(), server::listdemos(), make_file_packet(), game::captureclientmode::parse_network_message(), game::parsemessages(), server::parsepacket(), server::captureservermode::sendbases(), sendf(), server::sendinitclient(), game::sendintro(), game::sendmessages(), server::sendwelcome(), server::setmaster(), and server::setupdemorecord().
Function Documentation
void filtertext (char * dst, const char * src, bool whitespace, bool forcespace, size_t len)
References iscubeprint(), and iscubespace().
Referenced by filtertext(), game::initclient(), loadhistory(), game::parsemessages(), server::parsepacket(), game::switchname(), and game::switchteam().
template<size_t N> static void filtertext (char(&) dst[N], const char * src, bool whitespace = true, bool forcespace = false) inline static
References filtertext().
float getfloat (ucharbuf & p)
References f(), databuf< T >::get(), and lilswap().
Referenced by game::parsemessages(), server::parsepacket(), and unpackvslot().
int getint (ucharbuf & p)
References databuf< T >::get().
Referenced by server::extserverinforeply(), getstring(), game::bombclientmode::parse_network_message(), server::collectservermode::parse_network_message(), game::collectclientmode::parse_network_message(), game::captureclientmode::parse_network_message(), server::ctfservermode::parse_network_message(), game::ctfclientmode::parse_network_message(), server::collectservermode::parsebases(), server::captureservermode::parsebases(), game::ctfclientmode::parseflags(), server::ctfservermode::parseflags(), game::parsemessages(), server::parsepacket(), game::parsepositions(), server::bombservermode::parsespawnloc(), game::parsestate(), game::collectclientmode::parsetokens(), game::receivefile(), server::serverinforeply(), and unpackvslot().
void getstring (char * t, ucharbuf & p, size_t len)
References getint(), databuf< T >::remaining(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by getstring(), game::captureclientmode::parse_network_message(), game::parsemessages(), server::parsepacket(), and unpackvslot().
template<size_t N> static void getstring (char(&) t[N], ucharbuf & p) inline static
References getstring(), and anonymous_namespace{utilTest.cpp}::t().
int getuint (ucharbuf & p)
References databuf< T >::get().
Referenced by game::parsemessages(), server::parsepacket(), game::parsepositions(), and unpackvslot().
ENetPacket* make_file_packet (stream * file, const char * format, va_list args)
Puts a file into a ENet packet.
args is just a forward of "...", see C argument forwarding.
args is just a forward of "...", meaning this function should be used like
References databuf< T >::buf, packetbuf::finalize(), loopi(), MAXTRANS, inexor::rpc::min(), putint(), stream::read(), stream::seek(), sendstring(), stream::size(), and packetbuf::subbuf().
Referenced by send_file(), and sendfile().
void putfloat (ucharbuf & p, float f)
References putfloat_().
Referenced by game::addmsg(), packvslot(), and sendf().
void putfloat (packetbuf & p, float f)
References putfloat_().
void putfloat (vector< uchar > & p, float f)
References putfloat_().
void putint (ucharbuf & p, int n)
References putint_().
Referenced by server::addmessages(), game::addmsg(), server::collectservermode::droptokens(), server::extinfoplayer(), server::captureservermode::extinfoteam(), server::extinfoteams(), server::extinfoteamscore(), server::extserverinforeply(), server::captureservermode::initclient(), server::collectservermode::initclient(), server::ctfservermode::initclient(), entities::jumppadeffects(), server::collectservermode::leavegame(), server::listdemos(), make_file_packet(), packvslot(), game::parsemessages(), server::parsepacket(), server::putinitclient(), entities::putitems(), game::sendclipboard(), sendf(), game::sendintro(), game::bombclientmode::senditems(), game::collectclientmode::senditems(), game::ctfclientmode::senditems(), game::captureclientmode::senditems(), game::sendmessages(), game::sendposition(), server::sendstate(), sendstring_(), server::serverinforeply(), server::setmaster(), entities::teleporteffects(), and server::welcomepacket().
void putint (packetbuf & p, int n)
References putint_().
void putint (vector< uchar > & p, int n)
References putint_().
void putuint (ucharbuf & p, int n)
References putuint_().
Referenced by server::addmessages(), packvslot(), and game::sendposition().
void putuint (packetbuf & p, int n)
References putuint_().
void putuint (vector< uchar > & p, int n)
References putuint_().
void sendstring (const char * t, ucharbuf & p)
References sendstring_().
Referenced by game::addmsg(), server::extinfoplayer(), server::extinfoteamscore(), server::captureservermode::initclient(), server::listdemos(), make_file_packet(), packvslot(), server::putinitclient(), sendf(), game::sendintro(), game::sendmessages(), server::serverinforeply(), server::setmaster(), and server::welcomepacket().
void sendstring (const char * t, packetbuf & p)
References sendstring_().
void sendstring (const char * t, vector< uchar > & p)
References sendstring_().