Inexor: inexor/shared/cube_formatting.hpp File Reference
cube_formatting.hpp File Reference
#include "inexor/shared/cube_tools.hpp"
#include <cstdarg>
#include <cstdio>
#include <stdarg.h>
Macros
#define PRINTFARGS(fmt, args)
#define defformatstring(d,...) char d[260]; formatstring(d, __VA_ARGS__)
#define defvformatstring(d, last, fmt) char d[260]; { va_list ap; va_start(ap, last); vformatstring(d, fmt, ap); va_end(ap); }
Functions
void vformatstring (char *d, const char *fmt, va_list v, int len)
Internal: format string using variable parameter lists (va_list)
template<size_t N>
void vformatstring (char(&d)[N], const char *fmt, va_list v)
char * concatstring (char *d, const char *s, size_t len)
template<size_t N>
char * concatstring (char(&d)[N], const char *s)
char * prependstring (char *d, const char *s, size_t len)
template<size_t N>
char * prependstring (char(&d)[N], const char *s)
void nformatstring (char *d, int len, const char *fmt,...) PRINTFARGS(3
char * tempformatstring (const char *fmt,...) PRINTFARGS(1
formatstring using some static globals, faster but less safe.
template<size_t N>
char void formatstring (char(&d)[N], const char *fmt,...) PRINTFARGS(2
template<size_t N>
char void void formatstring (char(&d)[N], const char *fmt,...)
template<size_t N>
void concformatstring (char(&d)[N], const char *fmt,...) PRINTFARGS(2
template<size_t N>
void void concformatstring (char(&d)[N], const char *fmt,...)
Macro Definition Documentation
#define defformatstring (d, ...) char d[260]; formatstring(d, __VA_ARGS__)
Referenced by Shader::allocparams(), server::change_mastermode(), cubemapload(), game::damageeffect(), server::bombservermode::died(), server::hideandseekservermode::died(), entities::doleveltrigger(), game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::drawhudmodel(), dumplms(), gendds(), gendynlightvariant(), gengenericvariant(), genshadowmapvariant(), genuniformdefs(), genwatervariant(), skelmodel::skeleton::getblendoffset(), guicolor(), initidents(), inexor::sound::initmumble(), listdir(), md3::load(), obj::load(), md2::load(), iqm::load(), md5::load(), smd::load(), loadcaustics(), md3::loaddefaultparts(), obj::loaddefaultparts(), iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), loadmodel(), vertcommands< MDL >::loadpart(), skelcommands< MDL >::loadpart(), loadprefab(), animmodel::skin::loadshader(), loadskin(), loadsky(), Slot::loadthumbnail(), makeparticles(), makerelpath(), mapcfgname(), modelcommands< MDL, struct MDL::vertmesh >::modelcommand(), game::parsemessages(), server::parsepacket(), game::receivefile(), reloadshaders(), ai::render(), rendercommand(), game::rendergame(), resolverwait(), saveprefab(), game::ctfclientmode::scoreflag(), game::sendmap(), skelcommands< MDL >::setanim(), setblurshader(), aiman::setbotbalance(), aiman::setbotlimit(), server::setmaster(), skelcommands< MDL >::setpitchtarget(), game::setradartex(), game::captureclientmode::setscore(), game::captureclientmode::setup(), server::setupdemoplayback(), shader(), show_calclight_progress(), show_genpvs_progress(), entities::trypickup(), server::bombservermode::updatelimbo(), variantshader(), and writeobj().
#define defvformatstring (d, last, fmt) char d[260]; { va_list ap; va_start(ap, last); vformatstring(d, fmt, ap); va_end(ap); }
Referenced by debugcode(), debugcodeline(), draw_textf(), fatal(), generateshader(), and sendservmsgf().
#define PRINTFARGS (fmt, args)
Function Documentation
char* concatstring (char * d, const char * s, size_t len) inline
References copystring(), and hmap::d.
Referenced by aviwriter::aviwriter(), concatstring(), cubemaploadwildcard(), partrenderer::debuginfo(), game::drawhudmodel(), entname(), gendds(), getmaterialdesc(), hashpassword(), iqm::iqmmeshgroup::loadiqmanims(), loadsky(), loadskyoverlay(), makerelpath(), game::rendergame(), and screenshot().
template<size_t N> char* concatstring (char(&) d[N], const char * s) inline
References concatstring(), and hmap::d.
template<size_t N> void concformatstring (char(&) d[N], const char * fmt, ...) inline
Referenced by partrenderer::debuginfo().
template<size_t N> void void concformatstring (char(&) d[N], const char * fmt, ...) inline
References hmap::d, and vformatstring().
template<size_t N> char void formatstring (char(&) d[N], const char * fmt, ...) inline
Referenced by server::adddemo(), server::checkmaps(), server::colorname(), partrenderer::debuginfo(), debugline(), server::disconnect_client(), game::captureclientmode::drawblips(), drawconlines(), game::bombclientmode::drawhud(), findfile(), gengenericvariant(), hashpassword(), game::listclients(), listfiles(), md3::load(), obj::load(), md2::load(), iqm::load(), md5::load(), smd::load(), loadents(), game::preloadweapons(), game::printvar(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), modelcommands< MDL, struct MDL::vertmesh >::setdir(), setmapfilenames(), server::setupdemoplayback(), and texturedata().
template<size_t N> char void void formatstring (char(&) d[N], const char * fmt, ...) inline
References hmap::d, and vformatstring().
void void nformatstring (char * d, int len, const char * fmt, ...) inline
References vformatstring().
Referenced by floatformat(), ai::getwaypointfile(), intformat(), printent(), and printparticles().
char* prependstring (char * d, const char * s, size_t len) inline
References hmap::d, and inexor::rpc::min().
Referenced by complete(), and prependstring().
template<size_t N> char* prependstring (char(&) d[N], const char * s) inline
References hmap::d, and prependstring().
char * tempformatstring (const char * fmt, ...)
formatstring using some static globals, faster but less safe.
Referenced by game::colorname(), loadcrosshair(), game::setbliptex(), and game::teamcolor().
void vformatstring (char * d, const char * fmt, va_list v, int len) inline
Internal: format string using variable parameter lists (va_list)
References _vsnprintf.
Referenced by concformatstring(), formatstring(), editline::if(), nformatstring(), tempformatstring(), and vformatstring().
template<size_t N> void vformatstring (char(&) d[N], const char * fmt, va_list v) inline
References hmap::d, and vformatstring().