Inexor: inexor/texture/cubemap.cpp File Reference
cubemap.cpp File Reference
environment map loading routine.
#include <boost/algorithm/clamp.hpp>
#include <string.h>
#include <algorithm>
#include <memory>
#include "SDL_timer.h"
#include "inexor/client/network.hpp"
#include "inexor/engine/frame.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/filesystem/mediadirs.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/format.hpp"
#include "inexor/texture/image.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texsettings.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
Classes
struct envmap
Functions
void forcecubemapload (GLuint tex)
VARFP (envmapsize, 4, 7, 10, setupmaterials())
Texture * cubemaploadwildcard (Texture *t, const char *name, bool mipit, bool msg, bool transient)
Texture * cubemapload (const char *name, bool mipit, bool msg, bool transient)
VAR (envmapradius, 0, 128, 10000)
void clearenvmaps ()
VAR (aaenvmap, 0, 2, 4)
GLuint genenvmap (const vec &o, int envmapsize, int blur)
void initenvmaps ()
void genenvmaps ()
ushort closestenvmap (const vec &o)
ushort closestenvmap (int orient, const ivec &co, int size)
GLuint lookupenvmap (Slot &slot)
GLuint lookupenvmap (ushort emid)
Variables
cubemapside cubemapsides [6]
static vector< envmap > envmaps
static Texture * skyenvmap = nullptr
Detailed Description
environment map loading routine.
Class Documentation
struct envmap
Class Members
int blur
vec o
int radius
int size
GLuint tex
Function Documentation
void clearenvmaps ()
References cleanuptexture(), envmaps, loopv, skyenvmap, Texture::TRANSIENT, and Texture::type.
Referenced by cleanuptextures(), and initenvmaps().
ushort closestenvmap (const vec & o)
References vec::dist(), EMID_RESERVED, EMID_SKY, envmaps, loopv, envmap::o, and envmap::radius.
Referenced by closestenvmap(), gencubeverts(), genmergedfaces(), animmodel::render(), and setupmaterials().
ushort closestenvmap (int orient, const ivec & co, int size)
References C, closestenvmap(), dimcoord, dimension, and R.
Texture* cubemapload (const char * name, bool mipit, bool msg, bool transient)
References cubemaploadwildcard(), defformatstring, DIR_SKYBOX, inexor::filesystem::getmediapath(), Log, MAXSTRLEN, inexor::util::log_manager::std, and anonymous_namespace{utilTest.cpp}::t().
Referenced by initenvmaps(), Slot::load(), mdlenvmap(), and modelcommands< MDL, struct MDL::vertmesh >::setenvmap().
Texture* cubemaploadwildcard (Texture * t, const char * name, bool mipit, bool msg, bool transient)
References ImageData::align, Texture::ALPHA, alphaformat(), ImageData::bpp, Texture::bpp, ImageData::calclevelsize(), Texture::clamp, tiger::compress(), ImageData::compressed, Texture::COMPRESSED, compressed, compressedformat(), concatstring(), copystring(), createcompressedtexture(), createtexture(), Texture::CUBEMAP, cubemapsides, ImageData::data, cubemapside::flipx, cubemapside::flipy, forcecubemapload(), format(), formatsize(), gettexture(), GLenum(), ImageData::h, Texture::h, Texture::id, ImageData::levels, Log, loopi(), inexor::rpc::max(), inexor::rpc::min(), Texture::mipmap, Texture::name, ImageData::pitch, registertexture(), resizetexture(), inexor::util::log_manager::std, cubemapside::swapxy, anonymous_namespace{utilTest.cpp}::t(), cubemapside::target, texformat(), texreorient(), texturedata(), Texture::TRANSIENT, Texture::type, uncompressedformat(), ImageData::w, Texture::w, Texture::xs, and Texture::ys.
Referenced by cubemapload(), and reloadtexture().
void forcecubemapload (GLuint tex)
References gle::begin(), gle::end(), f(), GLenum(), loopi(), and SETSHADER.
Referenced by cubemaploadwildcard(), and genenvmap().
GLuint genenvmap (const vec & o, int envmapsize, int blur)
References blurtexture(), clientkeepalive(), createtexture(), cubemapsides, drawcubemap(), cubemapside::flipx, cubemapside::flipy, forcecubemapload(), GLuint(), hwcubetexsize, loopi(), maxtexsize, inexor::rpc::min(), scaletexture(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, cubemapside::swapxy, cubemapside::target, and texalign().
Referenced by genenvmaps().
void genenvmaps ()
References envmap::blur, envmaps, genenvmap(), loopv, inexor::rpc::min(), envmap::o, renderedframe, renderprogress(), envmap::size, and envmap::tex.
Referenced by drawtextures().
void initenvmaps ()
References entity::attr1, entity::attr2, entity::attr3, envmap::blur, clearenvmaps(), cubemapload(), entities::ents, envmaps, ET_ENVMAP, entities::getents(), loopv, entity::o, envmap::o, envmap::radius, envmap::size, skyenvmap, envmap::tex, and entity::type.
Referenced by allchanged().
GLuint lookupenvmap (Slot & slot)
References Texture::id, loopv, skyenvmap, Slot::sts, and TEX_ENVMAP.
Referenced by changebatchtmus(), animmodel::render(), rendermaterials(), and renderwater().
GLuint lookupenvmap (ushort emid)
References EMID_CUSTOM, EMID_NONE, EMID_RESERVED, EMID_SKY, envmaps, GLuint(), Texture::id, and skyenvmap.
VAR (envmapradius , 0 , 128 , 10000)
VAR (aaenvmap , 0 , 2 , 4)
VARFP (envmapsize , 4 , 7 , 10 , setupmaterials())
Variable Documentation
cubemapside cubemapsides[6]
Initial value:
=
{
    { GL_TEXTURE_CUBE_MAP_NEGATIVE_X, "lf", true,  true,  true },
    { GL_TEXTURE_CUBE_MAP_POSITIVE_X, "rt", false, false, true },
    { GL_TEXTURE_CUBE_MAP_NEGATIVE_Y, "ft", true,  false, false },
    { GL_TEXTURE_CUBE_MAP_POSITIVE_Y, "bk", false, true,  false },
    { GL_TEXTURE_CUBE_MAP_NEGATIVE_Z, "dn", false, false, true },
    { GL_TEXTURE_CUBE_MAP_POSITIVE_Z, "up", false, false, true },
}
Referenced by cubemaploadwildcard(), genenvmap(), and loadsky().
vector<envmap> envmaps static
Referenced by clearenvmaps(), closestenvmap(), genenvmaps(), initenvmaps(), and lookupenvmap().
Texture* skyenvmap = nullptr static
Referenced by clearenvmaps(), initenvmaps(), and lookupenvmap().