Inexor: inexor/shared/cube_sort.hpp File Reference
cube_sort.hpp File Reference
#include <string.h>
#include <algorithm>
Classes
struct sortless
Legacy Sorting algorithms.
struct sortnameless
Functions
template<class T , class F >
static void insertionsort (T *start, T *end, F fun)
template<class T , class F >
static void insertionsort (T *buf, int n, F fun)
template<class T >
static void insertionsort (T *buf, int n)
template<class T , class F >
static void quicksort (T *start, T *end, F fun)
template<class T , class F >
static void quicksort (T *buf, int n, F fun)
template<class T >
static void quicksort (T *buf, int n)
Function Documentation
template<class T , class F > static void insertionsort (T * start, T * end, F fun) inline static
References gle::end().
Referenced by insertionsort(), and quicksort().
template<class T , class F > static void insertionsort (T * buf, int n, F fun) inline static
References insertionsort().
template<class T > static void insertionsort (T * buf, int n) inline static
References insertionsort().
template<class T , class F > static void quicksort (T * start, T * end, F fun) inline static
References insertionsort(), and recorder::start().
Referenced by fogdome::init(), mergefaces(), mergemats(), optimizematsurfs(), quicksort(), and vector< facebounds >::sort().
template<class T , class F > static void quicksort (T * buf, int n, F fun) inline static
References quicksort().
template<class T > static void quicksort (T * buf, int n) inline static
References quicksort().