Inexor: inexor/engine/decal.hpp File Reference
decal.hpp File Reference
#include "inexor/shared/geom.hpp"
Enumerations
enum { DECAL_SCORCH = 0, DECAL_BLOOD, DECAL_BULLET }
Functions
void initdecals ()
void cleardecals ()
void renderdecals (bool mainpass=false)
void adddecal (int type, const vec &center, const vec &surface, float radius, const bvec &color=bvec(0xFF, 0xFF, 0xFF), int info=0)
Enumeration Type Documentation
anonymous enum
Enumerator
DECAL_SCORCH
DECAL_BLOOD
DECAL_BULLET
Function Documentation
void adddecal (int type, const vec & center, const vec & surface, float radius, const bvec & color = bvec(0xFF, 0xFF, 0xFF), int info = 0)
References decalrenderer::adddecal(), camera1, hmap::d, vec::dist(), and physent::o.
Referenced by game::bounced(), partrenderer::calc(), game::explodeeffects(), game::projsplash(), game::raydamage(), game::shoteffects(), game::updatebouncers(), and game::updatemovables().
void cleardecals ()
References decalrenderer::cleardecals(), and loopi().
Referenced by resetmap().
void initdecals ()
References decalrenderer::init(), and loopi().
Referenced by main().
void renderdecals (bool mainpass = false)
References decalrenderer::cleanuprenderstate(), decalrenderer::clearfadeddecals(), hmap::d, decalrenderer::fadeindecals(), decalrenderer::fadeoutdecals(), decalrenderer::hasdecals(), loopi(), decalrenderer::render(), and decalrenderer::setuprenderstate().
Referenced by drawreflection(), and gl_drawframe().