Inexor: inexor/engine/frame.hpp File Reference
frame.hpp File Reference
Functions
void resetfpshistory ()
clear fps history array
int get_current_max_fps ()
The current fps limit.
void updatefpshistory (int millis)
add current frames per seconds score to fps history array
void getfps (int &fps, int &bestdiff, int &worstdiff)
get average fps, best fps and worst fps (see command fpsrange)
Variables
bool inbetweenframes
bool renderedframe
Function Documentation
int get_current_max_fps ()
The current fps limit.
References mainmenu, inexor::rpc::min(), inexor::rendering::screen::ScreenManager::minimized, and inexor::rendering::screen::screen_manager.
Referenced by main().
void getfps (int & fps, int & bestdiff, int & worstdiff)
get average fps, best fps and worst fps (see command fpsrange)
References fpshistory, loopi(), and MAXFPSHISTORY.
Referenced by getfps_(), gl_drawhud(), and recorder::start().
void resetfpshistory ()
clear fps history array
References fpshistory, fpspos, loopi(), and MAXFPSHISTORY.
Referenced by main().
void updatefpshistory (int millis)
add current frames per seconds score to fps history array
References fpshistory, fpspos, inexor::rpc::max(), MAXFPSHISTORY, and inexor::rpc::min().
Referenced by main().
Variable Documentation
bool inbetweenframes
Referenced by commitchanges(), recorder::gettime(), main(), renderbackground(), renderprogress(), and resetgl().
bool renderedframe
Referenced by drawminimap(), genenvmaps(), main(), renderbackground(), renderprogress(), and restorebackground().