Inexor: inexor/engine/grass.hpp File Reference
grass.hpp File Reference
Functions
void generategrass ()
void rendergrass ()
void cleanupgrass ()
Function Documentation
void cleanupgrass ()
References glDeleteBuffers_, grassvbo, and grassvbosize.
Referenced by cleanupva().
void generategrass ()
References gle::bindvbo(), grasswedge::bound1, grasswedge::bound2, camera1, gle::clearvbo(), comparegrassgroups(), vec::dot(), vector< T, MINSIZE >::empty(), gengrassquads(), vector< T, MINSIZE >::getbuf(), glBufferData_, glBufferSubData_, glGenBuffers_, grassoffsets, grassvbo, grassvbosize, grasswedges, vector< T, MINSIZE >::length(), loopi(), inexor::rpc::max(), vtxarray::next, NUMGRASSOFFSETS, NUMGRASSWEDGES, physent::o, OCCLUDE_GEOM, plane::offset, reflecting, reflectz, refracting, rnd(), vector< T, MINSIZE >::setsize(), vector< T, MINSIZE >::sort(), and visibleva.
Referenced by gl_drawframe().
void rendergrass ()
References gle::bindvbo(), grasstri::center, gle::clearvbo(), grassvert::color, gle::disablequads(), gle::drawquads(), vector< T, MINSIZE >::empty(), gle::enablequads(), GL_ONE, glActiveTexture_, grassvbo, isfoggedsphere(), grassvert::lm, grassgroup::lmtex, loopv, grasstri::maxz, grassgroup::numquads, grassgroup::offset, grassvert::pos, grasstri::radius, reflecting, reflectz, refracting, SETSHADER, grassvert::tc, grassgroup::tex, grassgroup::tri, and xtravertsva.
Referenced by drawreflection(), and gl_drawframe().