Inexor: inexor/engine/lightmap.cpp File Reference
lightmap.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <limits.h>
#include <math.h>
#include <string.h>
#include <algorithm>
#include <array>
#include <memory>
#include "SDL_keycode.h"
#include "SDL_mutex.h"
#include "SDL_opengl.h"
#include "SDL_stdinc.h"
#include "SDL_thread.h"
#include "SDL_timer.h"
#include "inexor/engine/blend.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/fpsgame/fps.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/input/InputRouter.hpp"
#include "inexor/model/model.hpp"
#include "inexor/model/rendermodel.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/image.hpp"
#include "inexor/texture/savetexture.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texsettings.hpp"
#include "inexor/texture/texture.hpp"
Classes
struct lightmapworker
Structure containing anything to calculate while calclighting, which gets passed to the lightmap threads.
struct lightmapinfo
struct lightmaptask
struct lightmapext
struct layoutinfo
struct lightcacheentry
Macros
#define MAXLIGHTMAPTASKS 4096
#define LIGHTMAPBUFSIZE (2*1024*1024)
#define CHECK_PROGRESS_LOCKED(exit, before, after) CHECK_CALCLIGHT_PROGRESS_LOCKED(exit, show_calclight_progress, before, after)
#define CHECK_PROGRESS(exit) CHECK_PROGRESS_LOCKED(exit, ,)
#define NCHECK(n)
#define SURFACE_AMBIENT SURFACE_AMBIENT_BOTTOM
#define SURFACE_LIGHTMAP SURFACE_LIGHTMAP_BOTTOM
#define EDGE_TOLERANCE(x, y)
#define AA_EDGE_TOLERANCE(x, y, i) EDGE_TOLERANCE(x + aacoords[i][0], y + aacoords[i][1])
#define LIGHTCACHESIZE 1024
#define LIGHTCACHEHASH(x, y) (((((x)^(y))<<5) + (((x)^(y))>>5)) & (LIGHTCACHESIZE - 1))
#define ALLOCLOCK(name, init) { if(lightmapping > 1) name = init(); if(!name) lightmapping = 1; }
#define FREELOCK(name, destroy) { if(name) { destroy(name); name = NULL; } }
Enumerations
enum {
NO_SURFACE = 0, SURFACE_AMBIENT_BOTTOM, SURFACE_AMBIENT_TOP, SURFACE_LIGHTMAP_BOTTOM,
SURFACE_LIGHTMAP_TOP, SURFACE_LIGHTMAP_BLEND
}
Functions
VARR (lightprecision, 1, 32, 1024)
VARR (lighterror, 1, 8, 16)
VARR (bumperror, 1, 3, 16)
VARR (lightlod, 0, 0, 10)
HVARFR (ambient, 1, 0x191919, 0xFFFFFF,{if(ambient<=255) ambient|=(ambient<< 8)|(ambient<< 16);ambientcolor=bvec((ambient >>16)&0xFF,(ambient >>8)&0xFF, ambient &0xFF);})
HVARFR (skylight, 0, 0, 0xFFFFFF,{if(skylight<=255) skylight|=(skylight<< 8)|(skylight<< 16);skylightcolor=bvec((skylight >>16)&0xFF,(skylight >>8)&0xFF, skylight &0xFF);})
void setupsunlight ()
HVARFR (sunlight, 0, 0, 0xFFFFFF,{if(sunlight<=255) sunlight|=(sunlight<< 8)|(sunlight<< 16);sunlightcolor=bvec((sunlight >>16)&0xFF,(sunlight >>8)&0xFF, sunlight &0xFF);setupsunlight();})
FVARFR (sunlightscale, 0, 1, 16, setupsunlight())
void setsunlightdir ()
VARFR (sunlightyaw, 0, 0, 360, setsunlightdir())
VARFR (sunlightpitch,-90, 90, 90, setsunlightdir())
VARR (skytexturelight, 0, 1, 1)
void brightencube (cube &c)
void setsurfaces (cube &c, const surfaceinfo *surfs, const vertinfo *verts, int numverts)
void setsurface (cube &c, int orient, const surfaceinfo &src, const vertinfo *srcverts, int numsrcverts)
VARN (lmshadows, lmshadows_, 0, 2, 2)
VARN (lmaa, lmaa_, 0, 3, 3)
VARN (lerptjoints, lerptjoints_, 0, 1, 1)
VARN (lmao, lmao_, 0, 1, 1)
void check_calclight_canceled ()
void show_calclight_progress ()
static void insertunlit (int i)
static void insertlightmap (lightmapinfo &li, layoutinfo &si)
static void copylightmap (lightmapinfo &li, layoutinfo &si)
static bool htcmp (const lightmapinfo &k, const layoutinfo &v)
static uint hthash (const lightmapinfo &k)
VAR (lightcompress, 0, 3, 6)
static bool packlightmap (lightmapinfo &l, layoutinfo &surface)
static void updatelightmap (const layoutinfo &surface)
VARR (ambientocclusion, 0, 0, 255)
FVARR (ambientocclusionradius, 1.0, 2.0, 200.0)
VAR (debugao, 0, 0, 1)
static float calcocclusion (ShadowRayCache *cache, const vec &o, const vec &normal, float tolerance)
Calculates a value between 0 and 1 representing the occulation of a pixel.
static uint generatelumel (lightmapworker *w, const float tolerance, uint lightmask, const vector< const extentity * > &lights, const vec &target, const vec &normal, vec &sample, uchar &occlusionsample, int x, int y)
Generate Lumels (Pixel) of a specific sample, calculating its color.
static bool lumelsample (const vec &sample, int aasample, int stride)
Returns whether sample does need to be saved (whether lumels/pixels need to be generated).
static void calcskylight (lightmapworker *w, const vec &o, const vec &normal, float tolerance, uchar *skylight, int flags=RAY_ALPHAPOLY, extentity *t=nullptr)
static bool hasskylight ()
VARR (blurlms, 0, 0, 2)
VARR (blurskylight, 0, 0, 2)
static void generatealpha (lightmapworker *w, float tolerance, const vec &pos, uchar &alpha)
VAR (edgetolerance, 1, 4, 64)
VAR (adaptivesample, 0, 2, 2)
static bool generatelightmap (lightmapworker *w, float lpu, const lerpvert *lv, int numv, vec origin1, const vec &xstep1, const vec &ystep1, vec origin2, const vec &xstep2, const vec &ystep2, float side0, float sidestep)
static int finishlightmap (lightmapworker *w)
static int previewlightmapalpha (lightmapworker *w, float lpu, const vec &origin1, const vec &xstep1, const vec &ystep1, const vec &origin2, const vec &xstep2, const vec &ystep2, float side0, float sidestep)
static void clearsurfaces (cube *c)
VARF (lightcachesize, 4, 6, 12, clearlightcache())
void clearlightcache (int id)
const vector< int > & checklightcache (int x, int y)
static void addlight (lightmapworker *w, const extentity &light, int cx, int cy, int cz, int size, const vec *v, const vec *n, int numv)
static bool findlights (lightmapworker *w, int cx, int cy, int cz, int size, const vec *v, const vec *n, int numv, const Slot &slot, const VSlot &vslot)
static int packlightmaps (lightmapworker *w=nullptr)
static lightmapinfo * alloclightmap (lightmapworker *w)
static void freelightmap (lightmapworker *w)
static int setupsurface (lightmapworker *w, plane planes[2], int numplanes, const vec *p, const vec *n, int numverts, vertinfo *litverts, bool preview=false)
static void removelmalpha (lightmapworker *w)
static lightmapinfo * setupsurfaces (lightmapworker *w, lightmaptask &task)
static bool processtasks (bool finish=false)
static void generatelightmaps (cube *c, const ivec &co, int size)
static bool previewblends (lightmapworker *w, cube &c, const ivec &co, int size)
static bool previewblends (lightmapworker *w, cube *c, const ivec &co, int size, const ivec &bo, const ivec &bs)
void previewblends (const ivec &bo, const ivec &bs)
void cleanuplightmaps ()
void resetlightmaps (bool fullclean)
static Uint32 calclighttimer (Uint32 interval, void *param)
bool setlightmapquality (int quality)
VARP (lightthreads, 0, 0, 16)
static void cleanuplocks ()
static void setupthreads (int numthreads)
static void cleanupthreads ()
void calclight (int *quality)
COMMAND (calclight,"i")
VAR (patchnormals, 0, 0, 1)
void patchlight (int *quality)
COMMAND (patchlight,"i")
void clearlightmaps ()
COMMAND (clearlightmaps,"")
void setfullbrightlevel (int fullbrightlevel)
VARF (fullbright, 0, 0, 1, if(lightmaptexs.length()){initlights();lightents();})
VARF (fullbrightlevel, 0, 128, 255, setfullbrightlevel(fullbrightlevel))
static void rotatenormals (LightMap &lmlv, int x, int y, int w, int h, int rotate)
static void rotatenormals (cube *c)
void fixlightmapnormals ()
void fixrotatedlightmaps (cube &c, const ivec &co, int size)
void fixrotatedlightmaps ()
static void copylightmap (LightMap &lm, uchar *dst, size_t stride)
void genreservedlightmaptexs ()
static void findunlit (int i)
VARF (roundlightmaptex, 0, 4, 16,{cleanuplightmaps();initlights();allchanged();})
VARF (batchlightmaps, 0, 4, 256,{cleanuplightmaps();initlights();allchanged();})
void genlightmaptexs (int flagmask, int flagval)
void clearlights ()
void lightent (extentity &e, float height)
void lightents (bool force)
void initlights ()
static void fastskylight (const vec &o, float tolerance, uchar *skylight, int flags=RAY_ALPHAPOLY, extentity *t=nullptr, bool fast=false)
void lightreaching (const vec &target, vec &color, vec &dir, bool fast, extentity *t, float ambient)
entity * brightestlight (const vec &target, const vec &dir)
void dumplms ()
COMMAND (dumplms,"")
Variables
static vector< lightmapworker * > lightmapworkers
static vector< lightmaptask > lightmaptasks [2]
static vector< lightmapext > lightmapexts
static int packidx = 0
static int allocidx = 0
static SDL_mutex * lightlock = nullptr
static SDL_mutex * tasklock = nullptr
static SDL_cond * fullcond = nullptr
static SDL_cond * emptycond = nullptr
int lightmapping = 0
vector< LightMap > lightmaps
bvec ambientcolor (0x19, 0x19, 0x19)
bvec skylightcolor (0, 0, 0)
bvec sunlightcolor (0, 0, 0)
vec sunlightdir (0, 0, 1)
entity sunlightent
static const surfaceinfo brightsurfaces [6]
static int lmshadows = 2
static int lmaa = 3
static int lerptjoints = 1
static int lmao = 1
static uint progress = 0
static uint taskprogress = 0
static GLuint progresstex = 0
static int progresstexticks = 0
static int progresslightmap = -1
bool calclight_canceled = false
volatile bool check_calclight_progress = false
static hashset< layoutinfo > compressed
static struct lightcacheentry lightcache [LIGHTCACHESIZE]
vector< LightMapTexture > lightmaptexs
bool brightengeom = false
bool shouldlightents = false
Class Documentation
struct lightmapinfo
Class Members
int bpp
int bufsize
cube * c
uchar * colorbuf
int h
int layers
lightmapinfo * next
bool packed
bvec * raybuf
int surface
int type
int w
struct lightmaptask
Class Members
cube * c
cubeext * ext
lightmapinfo * lightmaps
ivec o
int progress
int size
int usefaces
lightmapworker * worker
struct lightmapext
Class Members
cube * c
cubeext * ext
struct layoutinfo
Class Members
uchar h
ushort lmid
uchar w
ushort x
ushort y
struct lightcacheentry
Class Members
vector< int > lights
int x
int y
Macro Definition Documentation
#define AA_EDGE_TOLERANCE (x, y, i) EDGE_TOLERANCE(x + aacoords[i][0], y + aacoords[i][1])
Referenced by generatelightmap().
#define ALLOCLOCK (name, init) { if(lightmapping > 1) name = init(); if(!name) lightmapping = 1; }
Referenced by setupthreads().
#define CHECK_PROGRESS (exit) CHECK_PROGRESS_LOCKED(exit, ,)
Referenced by generatelightmaps(), and processtasks().
#define CHECK_PROGRESS_LOCKED (exit, before, after) CHECK_CALCLIGHT_PROGRESS_LOCKED(exit, show_calclight_progress, before, after)
Referenced by processtasks().
#define EDGE_TOLERANCE (x, y)
Value:
(x < blurlms \
     || x+1 > w->w - blurlms \
     || y < blurlms \
     || y+1 > w->h - blurlms \
     ? edgetolerance : 1)
Referenced by generatelightmap().
#define FREELOCK (name, destroy) { if(name) { destroy(name); name = NULL; } }
Referenced by cleanuplocks().
#define LIGHTCACHEHASH (x, y) (((((x)^(y))<<5) + (((x)^(y))>>5)) & (LIGHTCACHESIZE - 1))
Referenced by checklightcache(), and clearlightcache().
#define LIGHTCACHESIZE 1024
Referenced by clearlightcache().
#define LIGHTMAPBUFSIZE (2*1024*1024)
Referenced by alloclightmap(), lightmapworker::lightmapworker(), and packlightmaps().
#define MAXLIGHTMAPTASKS 4096
Referenced by generatelightmaps().
#define NCHECK (n)
Value:
if((n).x >= int(ambientcolor[0])+1 || (n).y >= int(ambientcolor[1])+1 || (n).z >= int(ambientcolor[2])+1) \
        return true;
Referenced by lumelsample().
#define SURFACE_AMBIENT SURFACE_AMBIENT_BOTTOM
#define SURFACE_LIGHTMAP SURFACE_LIGHTMAP_BOTTOM
Referenced by setupsurface().
Enumeration Type Documentation
anonymous enum
Enumerator
NO_SURFACE
SURFACE_AMBIENT_BOTTOM
SURFACE_AMBIENT_TOP
SURFACE_LIGHTMAP_BOTTOM
SURFACE_LIGHTMAP_TOP
SURFACE_LIGHTMAP_BLEND
Function Documentation
static void addlight (lightmapworker * w, const extentity & light, int cx, int cy, int cz, int size, const vec * v, const vec * n, int numv) inline static
References vector< T, MINSIZE >::add(), entity::attr1, vec::dot(), lightmapworker::lights, loopi(), entity::o, and vec::sub().
Referenced by findlights().
static lightmapinfo* alloclightmap (lightmapworker * w) static
References lightmapworker::bpp, lightmapworker::buf, lightmapinfo::bufsize, lightmapworker::bufstart, lightmapworker::bufused, lightmapworker::colorbuf, lightmapworker::doneworking, lightmapworker::firstlightmap, lightmapworker::h, lightmapworker::lastlightmap, LIGHTMAPBUFSIZE, LM_BUMPMAP0, LM_TYPE, inexor::rpc::max(), inexor::rpc::min(), lightmapworker::needspace, lightmapinfo::next, lightmapinfo::packed, packlightmaps(), lightmapworker::raybuf, lightmapworker::spacecond, tasklock, lightmapworker::type, and lightmapworker::w.
Referenced by setupsurface().
void brightencube (cube & c)
References brightsurfaces, cube::ext, newcubeext(), and cubeext::surfaces.
Referenced by invalidatemerges(), readychanges(), remip(), and subdividecube().
entity* brightestlight (const vec & target, const vec & dir)
References extentity::attached, entity::attr1, checklightcache(), vec::div(), vec::dot(), entities::ents, ET_LIGHT, ET_SPOTLIGHT, entities::getents(), loopv, vec::magnitude(), vec::normalize(), entity::o, RAY_POLY, RAY_SHADOW, RAY_SKIPSKY, shadowray(), sincos360, vec::sub(), sunlightdir, sunlightent, and entity::type.
Referenced by setupmaterials().
void calclight (int * quality)
References allchanged(), calclight_canceled, calclighttimer(), calcnormals(), check_calclight_progress, cleanupthreads(), clearnormals(), clearsurfaces(), compressed, inexor::util::log_manager::edit, editmode, gle::end(), f(), generatelightmaps(), initlights(), insertunlit(), lerptjoints, lightmaps, LM_PACKH, LM_PACKW, loadlayermasks(), Log, loopv, mpremip(), optimizeblendmap(), preloadusedmapmodels(), progress, progresslightmap, progresstexticks, renderbackground(), resetlightmaps(), setlightmapquality(), setupthreads(), show_calclight_progress(), recorder::start(), inexor::util::log_manager::std, taskprogress, worldroot, and worldsize.
static Uint32 calclighttimer (Uint32 interval, void * param) static
References check_calclight_progress.
Referenced by calclight(), and patchlight().
static float calcocclusion (ShadowRayCache * cache, const vec & o, const vec & normal, float tolerance) static
Calculates a value between 0 and 1 representing the occulation of a pixel.
Attention
crashes if a normal vector of length zero occurs
References ASSERT, vec::isnormalized(), vec::iszero(), RAD, RAY_ALPHAPOLY, RAY_SHADOW, RAY_SKIPSKY, game::rays, and shadowray().
Referenced by generatelumel().
static void calcskylight (lightmapworker * w, const vec & o, const vec & normal, float tolerance, uchar * skylight, int flags = RAY_ALPHAPOLY, extentity * t = nullptr) static
References ambientcolor, vec::dot(), f(), hmap::flags, game::hit(), loopi(), loopk, inexor::rpc::max(), RAD, RAY_SHADOW, RAY_SKIPSKY, game::rays, shadowray(), lightmapworker::shadowraycache, skylightcolor, and anonymous_namespace{utilTest.cpp}::t().
Referenced by generatelightmap(), and lightreaching().
void check_calclight_canceled ()
References calclight_canceled, check_calclight_progress, inexor::io::input_router, inexor::io::InputRouter::interceptkey(), lightmapworkers, and loopv.
const vector<int>& checklightcache (int x, int y)
References vector< T, MINSIZE >::add(), entity::attr1, entities::ents, ET_LIGHT, entities::getents(), lightcache, LIGHTCACHEHASH, lightcacheentry::lights, loopv, entity::o, vector< T, MINSIZE >::setsize(), entity::type, lightcacheentry::x, and lightcacheentry::y.
Referenced by brightestlight(), findlights(), lightreaching(), and flarerenderer::makelightflares().
void cleanuplightmaps ()
References lightmaps, lightmaptexs, loopv, LightMap::offsetx, LightMap::offsety, progresstex, and LightMap::tex.
Referenced by patchlight(), resetgl(), and resetlightmaps().
static void cleanuplocks () static
References emptycond, FREELOCK, fullcond, lightlock, and tasklock.
Referenced by cleanupthreads(), and setupthreads().
static void cleanupthreads () static
References lightmapext::c, cleanuplocks(), lightmapext::ext, fullcond, lightmapexts, lightmapping, lightmapworkers, loopv, lightmapworker::needspace, processtasks(), setcubeext(), lightmapworker::spacecond, tasklock, and lightmapworker::thread.
Referenced by calclight(), and patchlight().
void clearlightcache (int id)
References entity::attr1, entities::getents(), lightcache, LIGHTCACHEHASH, LIGHTCACHESIZE, lightcacheentry::lights, inexor::rpc::max(), inexor::rpc::min(), entity::o, vector< T, MINSIZE >::setsize(), worldsize, lightcacheentry::x, and lightcacheentry::y.
Referenced by clearlights(), initlights(), modifyoctaent(), and resetlightmaps().
void clearlightmaps ()
References allchanged(), clearsurfaces(), initlights(), noedit(), renderprogress(), resetlightmaps(), and worldroot.
void clearlights ()
References clearlightcache(), entitylight::color, entitylight::dir, entities::ents, genlightmaptexs(), entities::getents(), extentity::light, LM_ALPHA, loopv, and shouldlightents.
Referenced by initlights().
static void clearsurfaces (cube * c) static
References surfaceinfo::clear(), ext(), cube::ext, loopi(), loopj, loopk, MAXFACEVERTS, vertinfo::norm, sphere::numverts, surfaceinfo::numverts, cubeext::surfaces, vertinfo::u, surfaceinfo::used(), vertinfo::v, sphere::verts, surfaceinfo::verts, and cubeext::verts().
Referenced by calclight(), and clearlightmaps().
COMMAND (calclight , "i")
COMMAND (patchlight , "i")
COMMAND (clearlightmaps , "")
COMMAND (dumplms , "")
static void copylightmap (lightmapinfo & li, layoutinfo & si) static
References lightmapinfo::colorbuf, layoutinfo::h, lightmaps, LM_BUMPMAP0, LM_TYPE, layoutinfo::lmid, LMID_RESERVED, lightmapinfo::raybuf, lightmapinfo::type, layoutinfo::w, layoutinfo::x, and layoutinfo::y.
Referenced by genlightmaptexs(), and previewblends().
static void copylightmap (LightMap & lm, uchar * dst, size_t stride) static
References LightMap::bpp, LightMap::data, LM_PACKH, LM_PACKW, and loopi().
void dumplms ()
References defformatstring, game::getclientmap(), lightmaps, LM_PACKH, LM_PACKW, loopv, hmap::map, and savepng().
static void fastskylight (const vec & o, float tolerance, uchar * skylight, int flags = RAY_ALPHAPOLY, extentity * t = nullptr, bool fast = false) inline static
References ambientcolor, f(), hmap::flags, game::hit(), loopi(), loopk, inexor::rpc::max(), RAD, RAY_SHADOW, RAY_SKIPSKY, game::rays, shadowray(), skylightcolor, and anonymous_namespace{utilTest.cpp}::t().
Referenced by lightreaching().
static bool findlights (lightmapworker * w, int cx, int cy, int cz, int size, const vec * v, const vec * n, int numv, const Slot & slot, const VSlot & vslot) static
References addlight(), lightmapworker::blendmapcache, checklightcache(), entities::ents, ET_LIGHT, entities::getents(), hasskylight(), VSlot::layer, Slot::layermask, vector< T, MINSIZE >::length(), lightlock, lightmapworker::lights, loopv, setblendmaporigin(), vector< T, MINSIZE >::setsize(), and entity::type.
Referenced by setupsurfaces().
static void findunlit (int i) static
References ambientcolor, LightMap::bpp, LightMap::data, lightmaps, LM_BUMPMAP0, LM_BUMPMAP1, LM_DIFFUSE, LM_PACKW, LM_TYPE, loop, LightMap::type, LightMap::unlitx, and LightMap::unlity.
Referenced by genlightmaptexs().
static int finishlightmap (lightmapworker * w) static
References lightmapworker::ambient, lightmapworker::blur, blurtexture(), lightmapworker::bpp, lightmapworker::colorbuf, lightmapworker::colordata, f(), lightmapworker::h, hasskylight(), lmaa, inexor::rpc::min(), lightmapworker::occlusiondata, lightmapworker::raydata, and lightmapworker::w.
Referenced by setupsurface().
void fixlightmapnormals ()
References rotatenormals(), and worldroot.
Referenced by load_world().
void fixrotatedlightmaps (cube & c, const ivec & co, int size)
References cube::children, cube::ext, LAYER_DUP, surfaceinfo::lmid, LMID_RESERVED, loopi(), loopk, MAXFACEVERTS, cube::merged, sphere::numverts, surfaceinfo::numverts, cubeext::surfaces, sphere::verts, surfaceinfo::verts, cubeext::verts(), visibletris(), vertinfo::x, vertinfo::y, and vertinfo::z.
Referenced by fixrotatedlightmaps(), and load_world().
void fixrotatedlightmaps ()
References fixrotatedlightmaps(), loopi(), worldroot, and worldsize.
static void freelightmap (lightmapworker * w) static
References lightmapinfo::bufsize, lightmapworker::bufstart, lightmapworker::bufused, lightmapworker::curlightmaps, lightmapworker::firstlightmap, lightmapworker::lastlightmap, lightmapinfo::packed, and lightmapinfo::surface.
Referenced by setupsurfaces().
FVARFR (sunlightscale , 0 , 1 , 16 , setupsunlight())
FVARR (ambientocclusionradius , 1. 0, 2. 0, 200. 0)
static void generatealpha (lightmapworker * w, float tolerance, const vec & pos, uchar & alpha) inline static
References lightmapworker::blendmapcache, ImageData::bpp, ImageData::data, dimension, ImageData::h, Slot::layermask, Slot::layermaskmode, Slot::layermaskscale, lookupblendmap(), inexor::rpc::max(), inexor::rpc::min(), hmap::mx, hmap::my, VSlot::offset, lightmapworker::orient, ImageData::pitch, lightmapworker::rotate, VSlot::scale, lightmapworker::slot, anonymous_namespace{utilTest.cpp}::t(), lightmapworker::vslot, and ImageData::w.
Referenced by generatelightmap(), and previewlightmapalpha().
static bool generatelightmap (lightmapworker * w, float lpu, const lerpvert * lv, int numv, vec origin1, const vec & xstep1, const vec & ystep1, vec origin2, const vec & xstep2, const vec & ystep2, float side0, float sidestep) static
References AA_EDGE_TOLERANCE, vec::add(), lightmapworker::ambient, ambientcolor, lightmapworker::bpp, calcskylight(), lightmapworker::colordata, vec::div(), EDGE_TOLERANCE, gle::end(), generatealpha(), generatelumel(), lightmapworker::h, hasskylight(), initlerpbounds(), lerpnormal(), lightmapworker::lights, LM_ALPHA, LM_BUMPMAP0, LM_MAXH, LM_MAXW, LM_TYPE, lmaa, lmshadows, loopi(), loopk, lumelsample(), inexor::rpc::max(), inexor::rpc::min(), vec::mul(), gle::normal(), vec::normalize(), lightmapworker::occlusiondata, RAY_ALPHAPOLY, lightmapworker::raydata, skylightcolor, recorder::start(), vec::sub(), anonymous_namespace{utilTest.cpp}::t(), lightmapworker::type, and lightmapworker::w.
Referenced by setupsurface().
static void generatelightmaps (cube * c, const ivec & co, int size) static
References lightmaptask::c, CHECK_PROGRESS, surfaceinfo::clear(), DEFAULT_SKY, ext(), lightmaptask::ext, cube::ext, isempty, lightmaptask::lightmaps, lightmaptasks, surfaceinfo::lmid, LMID_RESERVED, loopi(), loopj, MAXFACEVERTS, MAXLIGHTMAPTASKS, lightmaptask::o, processtasks(), lightmaptask::progress, lightmaptask::size, cubeext::surfaces, anonymous_namespace{utilTest.cpp}::t(), taskprogress, lightmaptask::usefaces, and visibletris().
Referenced by calclight(), and patchlight().
static uint generatelumel (lightmapworker * w, const float tolerance, uint lightmask, const vector< const extentity * > & lights, const vec & target, const vec & normal, vec & sample, uchar & occlusionsample, int x, int y) static
Generate Lumels (Pixel) of a specific sample, calculating its color.
References vec::add(), ambientcolor, extentity::attached, entity::attr1, entity::attr2, entity::attr3, entity::attr4, calcocclusion(), dimension, vec::dot(), ET_SPOTLIGHT, f(), vec::iszero(), LM_BUMPMAP0, LM_TYPE, lmao, lmshadows, loopv, vec::magnitude(), vec::mul(), vec::normalize(), entity::o, lightmapworker::orient, orientation_bitangent, orientation_tangent, vec::orthonormalize(), RAY_ALPHAPOLY, RAY_SHADOW, RAY_SKIPSKY, lightmapworker::raydata, lightmapworker::rotate, shadowray(), lightmapworker::shadowraycache, sincos360, vec::sub(), sunlightcolor, sunlightdir, ai::target(), entity::type, lightmapworker::type, and lightmapworker::w.
Referenced by generatelightmap().
void genlightmaptexs (int flagmask, int flagval)
References vector< T, MINSIZE >::add(), LightMap::bpp, copylightmap(), createtexture(), LightMap::data, findunlit(), genreservedlightmaptexs(), LightMapTexture::h, hwtexsize, LightMapTexture::id, vector< T, MINSIZE >::length(), lightmaps, LM_DIFFUSE, LM_PACKH, LM_PACKW, LM_TYPE, LMID_RESERVED, loopv, inexor::rpc::max(), maxtexsize, inexor::rpc::min(), LightMap::offsetx, LightMap::offsety, LightMap::tex, LightMap::type, LightMapTexture::type, LightMap::unlitx, LightMapTexture::unlitx, LightMap::unlity, LightMapTexture::unlity, and LightMapTexture::w.
Referenced by clearlights(), and initlights().
void genreservedlightmaptexs ()
References vector< T, MINSIZE >::add(), ambientcolor, createtexture(), LightMapTexture::id, vector< T, MINSIZE >::length(), LM_BUMPMAP1, LM_DIFFUSE, LMID_AMBIENT, LMID_AMBIENT1, LMID_BRIGHT, LMID_BRIGHT1, LMID_DARK, LMID_DARK1, LMID_RESERVED, and LightMapTexture::type.
Referenced by genlightmaptexs().
static bool hasskylight () inline static
References ambientcolor, and skylightcolor.
Referenced by findlights(), finishlightmap(), generatelightmap(), and lightreaching().
static bool htcmp (const lightmapinfo & k, const layoutinfo & v) inline static
References lightmapinfo::bpp, lightmapinfo::colorbuf, LightMap::data, lightmapinfo::h, layoutinfo::h, lightmaps, LM_BUMPMAP0, LM_PACKW, LM_TYPE, layoutinfo::lmid, LMID_RESERVED, loopi(), lightmapinfo::raybuf, LightMap::type, lightmapinfo::type, vcolor(), lightmapinfo::w, layoutinfo::w, layoutinfo::x, and layoutinfo::y.
static uint hthash (const lightmapinfo & k) inline static
References lightmapinfo::bpp, gle::color(), lightmapinfo::colorbuf, lightmapinfo::h, tiger::hash(), loopi(), and lightmapinfo::w.
HVARFR (ambient , 1 , 0x191919 , 0xFFFFFF , {if(ambient<=255) ambient|=(ambient<< 8)|(ambient<< 16);ambientcolor=bvec((ambient >>16)&0xFF,(ambient >>8)&0xFF, ambient &0xFF);})
HVARFR (skylight , 0 , 0 , 0xFFFFFF , {if(skylight<=255) skylight|=(skylight<< 8)|(skylight<< 16);skylightcolor=bvec((skylight >>16)&0xFF,(skylight >>8)&0xFF, skylight &0xFF);})
HVARFR (sunlight , 0 , 0 , 0xFFFFFF , {if(sunlight<=255) sunlight|=(sunlight<< 8)|(sunlight<< 16);sunlightcolor=bvec((sunlight >>16)&0xFF,(sunlight >>8)&0xFF, sunlight &0xFF);setupsunlight();})
void initlights ()
References clearlightcache(), clearlights(), editmode, genlightmaptexs(), lightmaps, LM_ALPHA, and shouldlightents.
Referenced by calclight(), clearlightmaps(), emptymap(), load_world(), patchlight(), resetgl(), setfullbrightlevel(), and toggleedit().
static void insertlightmap (lightmapinfo & li, layoutinfo & si) static
References ASSERT, LightMap::bpp, lightmapinfo::bpp, lightmapinfo::colorbuf, LightMap::data, layoutinfo::h, LightMap::insert(), lightmaps, LM_BUMPMAP0, LM_BUMPMAP1, LM_PACKH, LM_PACKW, LM_TYPE, layoutinfo::lmid, LMID_RESERVED, loopv, progresslightmap, lightmapinfo::raybuf, LightMap::type, lightmapinfo::type, layoutinfo::w, layoutinfo::x, and layoutinfo::y.
Referenced by packlightmap().
static void insertunlit (int i) static
References ambientcolor, ASSERT, LightMap::insert(), lightmaps, LM_BUMPMAP0, LM_BUMPMAP1, LM_TYPE, LightMap::type, LightMap::unlitx, and LightMap::unlity.
Referenced by calclight().
void lightent (extentity & e, float height)
References model::above(), entity::attr2, entitylight::color, entitylight::dir, ET_GAMESPECIFIC, ET_LIGHT, ET_MAPMODEL, extentity::light, lightreaching(), loadmodel(), entity::o, ai::target(), and entity::type.
Referenced by lightents(), and modifyoctaent().
void lightents (bool force)
References entities::ents, entities::getents(), lightent(), loopv, and shouldlightents.
Referenced by allchanged(), and toggleedit().
void lightreaching (const vec & target, vec & color, vec & dir, bool fast, extentity * t, float ambient)
References vec::add(), ambientcolor, extentity::attached, entity::attr1, entity::attr2, entity::attr3, entity::attr4, calcskylight(), checklightcache(), vec::div(), vec::dot(), editmode, entities::ents, ET_LIGHT, ET_SPOTLIGHT, f(), fastskylight(), entities::getents(), hasskylight(), vec::iszero(), lightmaps, loopk, loopv, vec::magnitude(), inexor::rpc::max(), inexor::rpc::min(), vec::mul(), vec::normalize(), entity::o, RAY_POLY, RAY_SHADOW, RAY_SKIPSKY, shadowray(), sincos360, vec::sub(), sunlightcolor, sunlightdir, and entity::type.
Referenced by game::collectclientmode::droptoken(), game::explode(), lightent(), game::collectclientmode::rendergame(), rendermodel(), and gui::start().
static bool lumelsample (const vec & sample, int aasample, int stride) static
Returns whether sample does need to be saved (whether lumels/pixels need to be generated).
true if sample colour is not darker than the ambient light (hence saveworthy).
References ambientcolor, and NCHECK.
Referenced by generatelightmap().
static bool packlightmap (lightmapinfo & l, layoutinfo & surface) static
References compressed, lightmapinfo::h, layoutinfo::h, insertlightmap(), layoutinfo::lmid, lightmapinfo::w, layoutinfo::w, layoutinfo::x, and layoutinfo::y.
Referenced by packlightmaps(), and previewblends().
static int packlightmaps (lightmapworker * w = nullptr) static
References lightmapinfo::bufsize, lightmapinfo::c, lightmaptask::c, lightmapext::c, lightmaptask::ext, lightmapext::ext, cube::ext, LAYER_BOTTOM, LAYER_DUP, LAYER_TOP, lightmapinfo::layers, LIGHTMAPBUFSIZE, lightmapexts, lightmaptask::lightmaps, lightmaptasks, LM_ALPHA, LM_PACKH, LM_PACKW, surfaceinfo::lmid, layoutinfo::lmid, loopk, MAXFACEVERTS, lightmapworker::needspace, lightmapinfo::next, sphere::numverts, surfaceinfo::numverts, lightmapinfo::packed, packidx, packlightmap(), lightmaptask::progress, progress, lightmapworker::spacecond, lightmapinfo::surface, cubeext::surfaces, anonymous_namespace{utilTest.cpp}::t(), lightmapinfo::type, vertinfo::u, vertinfo::v, sphere::verts, surfaceinfo::verts, cubeext::verts(), lightmaptask::worker, layoutinfo::x, and layoutinfo::y.
Referenced by alloclightmap(), processtasks(), and lightmapworker::work().
void patchlight (int * quality)
References allchanged(), calclight_canceled, calclighttimer(), calcnormals(), check_calclight_progress, cleanuplightmaps(), cleanupthreads(), clearnormals(), inexor::util::log_manager::edit, gle::end(), f(), generatelightmaps(), initlights(), lerptjoints, lightmaps, LM_BUMPMAP1, LM_PACKH, LM_PACKW, LM_TYPE, loadlayermasks(), Log, loopv, noedit(), preloadusedmapmodels(), progress, progresslightmap, progresstexticks, renderbackground(), renderprogress(), setlightmapquality(), setupthreads(), show_calclight_progress(), recorder::start(), inexor::util::log_manager::std, taskprogress, worldroot, and worldsize.
static bool previewblends (lightmapworker * w, cube & c, const ivec & co, int size) static
References vec::add(), lightmapworker::blendmapcache, lightmapworker::bpp, brightbottomsurface, surfaceinfo::brighten(), brightsurface, brightsurfaces, lightmapworker::bufstart, lightmapworker::bufused, lightmapworker::c, copylightmap(), lightmapworker::curlightmaps, DEFAULT_SKY, cube::ext, f(), faceconvexity(), lightmapworker::firstlightmap, flataxisface(), genfaceverts(), lightmapworker::h, layoutinfo::h, isempty, lightmapworker::lastlightmap, VSlot::layer, LAYER_BLEND, LAYER_BOTTOM, lightmaps, LM_ALPHA, LM_BUMPMAP0, LM_DIFFUSE, LM_PACKH, LM_PACKW, surfaceinfo::lmid, layoutinfo::lmid, LMID_RESERVED, lookupvslot(), loopi(), loopj, loopk, ivec::mask(), MAT_ALPHA, cube::material, MAXFACEVERTS, vec::mul(), vec::normalize(), sphere::numverts, surfaceinfo::numverts, lightmapworker::orient, packlightmap(), lightmapworker::rotate, VSlot::rotation, vertinfo::set(), setblendmaporigin(), setsurfaces(), setupsurface(), Slot::shader, shader(), SHADER_NORMALSLMS, ivec::shl(), VSlot::slot, lightmapworker::slot, SURFACE_AMBIENT_TOP, SURFACE_LIGHTMAP_BLEND, cubeext::surfaces, cube::texture, plane::toplane(), surfaceinfo::totalverts(), lightmapworker::type, Shader::type, vertinfo::u, updatelightmap(), vertinfo::v, surfaceinfo::verts, cubeext::verts(), visibletris(), lightmapworker::vslot, lightmapworker::w, layoutinfo::w, vertinfo::x, layoutinfo::x, vertinfo::y, and layoutinfo::y.
Referenced by clearblendmapsel(), invertblendmap(), invertblendmapsel(), paintblendmap(), previewblends(), and showblendmap().
static bool previewblends (lightmapworker * w, cube * c, const ivec & co, int size, const ivec & bo, const ivec & bs) static
References changed(), destroyva(), ext(), cube::ext, vtxarray::hasmerges, invalidatemerges(), loopoctabox, previewblends(), and cubeext::va.
void previewblends (const ivec & bo, const ivec & bs)
References commitchanges(), lightmapworkers, loadlayermasks(), previewblends(), worldroot, and worldsize.
static int previewlightmapalpha (lightmapworker * w, float lpu, const vec & origin1, const vec & xstep1, const vec & ystep1, const vec & origin2, const vec & xstep2, const vec & ystep2, float side0, float sidestep) static
References vec::add(), lightmapworker::colorbuf, generatealpha(), lightmapworker::h, LM_BUMPMAP0, LM_TYPE, loopi(), loopk, inexor::rpc::max(), inexor::rpc::min(), vec::mul(), lightmapworker::raybuf, SURFACE_AMBIENT_BOTTOM, SURFACE_AMBIENT_TOP, SURFACE_LIGHTMAP_BLEND, lightmapworker::type, and lightmapworker::w.
Referenced by setupsurface().
static bool processtasks (bool finish = false) static
References allocidx, CHECK_PROGRESS, CHECK_PROGRESS_LOCKED, emptycond, fullcond, lightmapping, lightmaptask::lightmaps, lightmaptasks, lightmapworkers, packidx, packlightmaps(), setupsurfaces(), anonymous_namespace{utilTest.cpp}::t(), tasklock, and lightmaptask::worker.
Referenced by cleanupthreads(), and generatelightmaps().
static void removelmalpha (lightmapworker * w) static
References lightmapworker::bpp, lightmapinfo::bpp, lightmapworker::colorbuf, gle::end(), lightmapworker::h, lightmapworker::lastlightmap, LM_ALPHA, lightmapworker::type, lightmapinfo::type, and lightmapworker::w.
Referenced by setupsurfaces().
void resetlightmaps (bool fullclean)
References cleanuplightmaps(), clearlightcache(), compressed, lightmaps, and lightmapworkers.
Referenced by calclight(), clearlightmaps(), and resetmap().
static void rotatenormals (LightMap & lmlv, int x, int y, int w, int h, int rotate) static
References LightMap::data, LM_PACKW, loopi(), and loopj.
Referenced by fixlightmapnormals(), and rotatenormals().
static void rotatenormals (cube * c) static
References cube::children, cube::ext, lightmaps, LM_BUMPMAP1, LM_PACKH, LM_PACKW, LM_TYPE, surfaceinfo::lmid, LMID_RESERVED, lookupvslot(), loopi(), loopj, loopk, inexor::rpc::max(), MAXFACEVERTS, inexor::rpc::min(), sphere::numverts, surfaceinfo::numverts, rotatenormals(), VSlot::rotation, cubeext::surfaces, cube::texture, LightMap::type, vertinfo::u, vertinfo::v, sphere::verts, surfaceinfo::verts, and cubeext::verts().
void setfullbrightlevel (int fullbrightlevel)
References createtexture(), initlights(), lightmaptexs, and LMID_BRIGHT.
bool setlightmapquality (int quality)
References lerptjoints, lmaa, lmao, and lmshadows.
Referenced by calclight(), and patchlight().
void setsunlightdir ()
References f(), loopk, vec::normalize(), RAD, setupsunlight(), and sunlightdir.
void setsurface (cube & c, int orient, const surfaceinfo & src, const vertinfo * srcverts, int numsrcverts)
References ext(), cube::ext, growcubeext(), loopi(), cubeext::maxverts, newcubeext(), sphere::numverts, orient, setcubeext(), cubeext::surfaces, surfaceinfo::totalverts(), surfaceinfo::verts, and cubeext::verts().
Referenced by addmerge().
void setsurfaces (cube & c, const surfaceinfo * surfs, const vertinfo * verts, int numverts)
References cube::ext, cubeext::maxverts, newcubeext(), cubeext::surfaces, sphere::verts, and cubeext::verts().
Referenced by convertoldsurfaces(), and previewblends().
void setupsunlight ()
References vec::add(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, ET_LIGHT, inexor::rpc::min(), vec::mul(), entity::o, sunlightcolor, sunlightdir, sunlightent, entity::type, and worldsize.
Referenced by setsunlightdir().
static int setupsurface (lightmapworker * w, plane planes[2], int numplanes, const vec * p, const vec * n, int numverts, vertinfo * litverts, bool preview = false) static
References vec2::add(), vec::add(), alloclightmap(), calclerpverts(), vec::cross(), vec2::div(), vec2::dot(), vec::dot(), finishlightmap(), generatelightmap(), lightmapworker::h, LM_MAXH, LM_MAXW, LM_MINH, LM_MINW, LM_PACKH, LM_PACKW, loopi(), loopj, loopk, inexor::rpc::max(), MAXFACEVERTS, inexor::rpc::min(), vec2::mul(), vec::mul(), vec2::neg(), NO_SURFACE, vec::normalize(), sphere::numverts, previewlightmapalpha(), vec2::squaredlen(), vec2::sub(), vec::sub(), SURFACE_LIGHTMAP, anonymous_namespace{utilTest.cpp}::t(), texscale(), vertinfo::u, vertinfo::v, and lightmapworker::w.
Referenced by previewblends(), and setupsurfaces().
static lightmapinfo* setupsurfaces (lightmapworker * w, lightmaptask & task) static
References vec::add(), lightmapworker::bpp, lightmapworker::c, lightmaptask::c, calcmergedsize(), lightmapworker::curlightmaps, encodenormal(), ext(), lightmaptask::ext, cube::ext, f(), faceconvexity(), findlights(), findnormal(), flataxisface(), freelightmap(), genfaceverts(), vertinfo::getxyz(), growcubeext(), lightmapworker::lastlightmap, VSlot::layer, LAYER_BLEND, LAYER_BOTTOM, LAYER_DUP, LAYER_TOP, lightmapinfo::layers, LM_ALPHA, LM_BUMPMAP0, LM_DIFFUSE, lookupvslot(), loopi(), loopj, loopk, ivec::mask(), MAT_ALPHA, cube::material, MAXFACEVERTS, cubeext::maxverts, cube::merged, vec::mul(), vertinfo::norm, vec::normalize(), sphere::numverts, surfaceinfo::numverts, lightmaptask::o, lightmapworker::orient, removelmalpha(), lightmapworker::rotate, VSlot::rotation, vertinfo::set(), setupsurface(), vertinfo::setxyz(), Slot::shader, shader(), SHADER_ENVMAP, SHADER_NORMALSLMS, ivec::shl(), lightmaptask::size, VSlot::slot, lightmapworker::slot, lightmapinfo::surface, SURFACE_AMBIENT_TOP, SURFACE_LIGHTMAP_BLEND, SURFACE_LIGHTMAP_BOTTOM, SURFACE_LIGHTMAP_TOP, cubeext::surfaces, cube::texture, plane::toplane(), surfaceinfo::totalverts(), lightmapworker::type, Shader::type, surfaceinfo::used(), lightmaptask::usefaces, sphere::verts, surfaceinfo::verts, cubeext::verts(), and lightmapworker::vslot.
Referenced by processtasks(), and lightmapworker::work().
static void setupthreads (int numthreads) static
References allocidx, ALLOCLOCK, cleanuplocks(), lightmapworker::cleanupthread(), emptycond, fullcond, lightlock, lightmapexts, lightmapping, lightmaptasks, lightmapworkers, loopi(), inexor::rpc::max(), packidx, lightmapworker::reset(), and tasklock.
Referenced by calclight(), and patchlight().
void show_calclight_progress ()
References allocnodes, LightMap::bpp, calclight_canceled, createtexture(), LightMap::data, defformatstring, hwtexsize, lightmaps, LM_PACKH, LM_PACKW, progress, progresslightmap, progresstex, progresstexticks, renderprogress(), tasklock, and texalign().
Referenced by calclight(), and patchlight().
static void updatelightmap (const layoutinfo & surface) static
References LightMap::bpp, createtexture(), LightMap::data, LightMapTexture::h, layoutinfo::h, hwtexsize, LightMapTexture::id, lightmaps, lightmaptexs, LM_ALPHA, LM_BUMPMAP0, LM_PACKH, LM_PACKW, LM_TYPE, layoutinfo::lmid, LMID_RESERVED, inexor::rpc::max(), LightMap::offsetx, LightMap::offsety, LightMap::tex, LightMap::type, LightMapTexture::type, LightMap::unlitx, LightMapTexture::unlitx, LightMap::unlity, LightMapTexture::unlity, LightMapTexture::w, layoutinfo::w, layoutinfo::x, and layoutinfo::y.
Referenced by previewblends().
VAR (lightcompress , 0 , 3 , 6)
VAR (debugao , 0 , 0 , 1)
VAR (edgetolerance , 1 , 4 , 64)
VAR (adaptivesample , 0 , 2 , 2)
VAR (patchnormals , 0 , 0 , 1)
VARF (lightcachesize , 4 , 6 , 12 , clearlightcache())
VARF (fullbright , 0 , 0 , 1 , if(lightmaptexs.length()){initlights();lightents();})
VARF (fullbrightlevel , 0 , 128 , 255 , setfullbrightlevel(fullbrightlevel))
VARF (roundlightmaptex , 0 , 4 , 16 , {cleanuplightmaps();initlights();allchanged();})
VARF (batchlightmaps , 0 , 4 , 256 , {cleanuplightmaps();initlights();allchanged();})
VARFR (sunlightyaw , 0 , 0 , 360 , setsunlightdir())
VARFR (sunlightpitch , - 90, 90 , 90 , setsunlightdir())
VARN (lmshadows , lmshadows_ , 0 , 2 , 2)
VARN (lmaa , lmaa_ , 0 , 3 , 3)
VARN (lerptjoints , lerptjoints_ , 0 , 1 , 1)
VARN (lmao , lmao_ , 0 , 1 , 1)
VARP (lightthreads , 0 , 0 , 16)
VARR (lightprecision , 1 , 32 , 1024)
VARR (lighterror , 1 , 8 , 16)
VARR (bumperror , 1 , 3 , 16)
VARR (lightlod , 0 , 0 , 10)
VARR (skytexturelight , 0 , 1 , 1)
VARR (ambientocclusion , 0 , 0 , 255)
VARR (blurlms , 0 , 0 , 2)
VARR (blurskylight , 0 , 0 , 2)
Variable Documentation
int allocidx = 0 static
Referenced by processtasks(), setupthreads(), and lightmapworker::work().
bvec ambientcolor(0x19, 0x19, 0x19)
Referenced by calcskylight(), fastskylight(), findunlit(), generatelightmap(), generatelumel(), genreservedlightmaptexs(), hasskylight(), insertunlit(), lightreaching(), lumelsample(), pushshadowmap(), renderwater(), and setupgeom().
bool brightengeom = false
Referenced by changebatchtmus(), and gengrassquads().
const surfaceinfo brightsurfaces[6] static
Initial value:
=
{
    brightsurface,
    brightsurface,
    brightsurface,
    brightsurface,
    brightsurface,
    brightsurface
}
Referenced by brightencube(), and previewblends().
bool calclight_canceled = false
Referenced by calclight(), check_calclight_canceled(), patchlight(), and show_calclight_progress().
volatile bool check_calclight_progress = false
Referenced by calclight(), calclighttimer(), check_calclight_canceled(), and patchlight().
hashset<layoutinfo> compressed static
Referenced by calclight(), cubemaploadwildcard(), gendds(), packlightmap(), and resetlightmaps().
SDL_cond * emptycond = nullptr static
Referenced by cleanuplocks(), processtasks(), setupthreads(), and lightmapworker::work().
SDL_cond* fullcond = nullptr static
Referenced by cleanuplocks(), cleanupthreads(), processtasks(), setupthreads(), and lightmapworker::work().
int lerptjoints = 1 static
Referenced by calclight(), calcnormals(), patchlight(), and setlightmapquality().
struct lightcacheentry lightcache[LIGHTCACHESIZE] static
Referenced by checklightcache(), and clearlightcache().
SDL_mutex* lightlock = nullptr static
Referenced by cleanuplocks(), findlights(), and setupthreads().
vector<lightmapext> lightmapexts static
Referenced by cleanupthreads(), packlightmaps(), and setupthreads().
int lightmapping = 0
Referenced by cleanupthreads(), loadmodel(), mmintersect(), processtasks(), setupthreads(), and BIH::triintersect().
vector<LightMap> lightmaps
Referenced by addcubeverts(), calclight(), cleanuplightmaps(), copylightmap(), dumplms(), findunlit(), genlightmaptexs(), gl_drawhud(), htcmp(), initlights(), insertlightmap(), insertunlit(), lightreaching(), load_world(), patchlight(), previewblends(), resetlightmaps(), rotatenormals(), save_world(), show_calclight_progress(), and updatelightmap().
vector<lightmaptask> lightmaptasks[2] static
Referenced by generatelightmaps(), packlightmaps(), processtasks(), setupthreads(), and lightmapworker::work().
vector<LightMapTexture> lightmaptexs
Referenced by addcubeverts(), changebatchtmus(), cleanuplightmaps(), gengrassquads(), vacollect::optimize(), vacollect::remapunlit(), setfullbrightlevel(), and updatelightmap().
vector<lightmapworker *> lightmapworkers static
Referenced by check_calclight_canceled(), cleanupthreads(), previewblends(), processtasks(), resetlightmaps(), and setupthreads().
int lmaa = 3 static
Referenced by finishlightmap(), generatelightmap(), and setlightmapquality().
int lmao = 1 static
Referenced by generatelumel(), and setlightmapquality().
int lmshadows = 2 static
Referenced by generatelightmap(), generatelumel(), and setlightmapquality().
int packidx = 0 static
Referenced by packlightmaps(), processtasks(), setupthreads(), and lightmapworker::work().
uint progress = 0 static
Referenced by calclight(), packlightmaps(), patchlight(), and show_calclight_progress().
int progresslightmap = -1 static
Referenced by calclight(), insertlightmap(), patchlight(), and show_calclight_progress().
GLuint progresstex = 0 static
Referenced by cleanuplightmaps(), and show_calclight_progress().
int progresstexticks = 0 static
Referenced by calclight(), patchlight(), and show_calclight_progress().
bool shouldlightents = false
Referenced by clearlights(), initlights(), and lightents().
bvec skylightcolor(0, 0, 0)
Referenced by calcskylight(), fastskylight(), generatelightmap(), hasskylight(), pushshadowmap(), and renderwater().
bvec sunlightcolor(0, 0, 0)
Referenced by generatelumel(), lightreaching(), and setupsunlight().
vec sunlightdir(0, 0, 1)
Referenced by brightestlight(), generatelumel(), guessshadowdir(), lightreaching(), setsunlightdir(), and setupsunlight().
entity sunlightent
Referenced by brightestlight(), and setupsunlight().
SDL_mutex * tasklock = nullptr static
Referenced by alloclightmap(), cleanuplocks(), cleanupthreads(), processtasks(), setupthreads(), show_calclight_progress(), and lightmapworker::work().
uint taskprogress = 0 static
Referenced by calclight(), generatelightmaps(), and patchlight().