Inexor: inexor/engine/lightmap.hpp File Reference
lightmap.hpp File Reference
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
Classes
struct PackNode
struct LightMap
struct LightMapTexture
struct lerpvert
struct lerpbounds
Macros
#define LM_MINW 2
#define LM_MINH 2
#define LM_MAXW 128
#define LM_MAXH 128
#define LM_PACKW 512
#define LM_PACKH 512
#define CHECK_CALCLIGHT_PROGRESS_LOCKED(exit, show_calclight_progress, before, after)
#define CHECK_CALCLIGHT_PROGRESS(exit, show_calclight_progress) CHECK_CALCLIGHT_PROGRESS_LOCKED(exit, show_calclight_progress, ,)
Enumerations
enum {
LM_DIFFUSE = 0, LM_BUMPMAP0, LM_BUMPMAP1, LM_TYPE = 0x0F,
LM_ALPHA = 1<<4, LM_FLAGS = 0xF0
}
Functions
void clearlights ()
void initlights ()
void lightents (bool force=false)
void clearlightcache (int id=-1)
void resetlightmaps (bool fullclean=true)
void brightencube (cube &c)
void setsurfaces (cube &c, const surfaceinfo *surfs, const vertinfo *verts, int numverts)
void setsurface (cube &c, int orient, const surfaceinfo &surf, const vertinfo *verts, int numverts)
void previewblends (const ivec &bo, const ivec &bs)
void calcnormals (bool lerptjoints=false)
void clearnormals ()
void findnormal (const vec &key, const vec &surface, vec &v)
void calclerpverts (const vec2 *c, const vec *n, lerpvert *lv, int &numv)
void initlerpbounds (float u, float v, const lerpvert *lv, int numv, lerpbounds &start, lerpbounds &end)
void lerpnormal (float u, float v, const lerpvert *lv, int numv, lerpbounds &start, lerpbounds &end, vec &normal, vec &nstep)
void check_calclight_canceled ()
void lightent (extentity &e, float height=8.0f)
void lightreaching (const vec &target, vec &color, vec &dir, bool fast=false, extentity *e=nullptr, float ambient=0.4f)
entity * brightestlight (const vec &target, const vec &dir)
Variables
vector< LightMap > lightmaps
vector< LightMapTexture > lightmaptexs
bvec ambientcolor
bvec skylightcolor
bool calclight_canceled
volatile bool check_calclight_progress
int lightmapping
Class Documentation
struct lerpbounds
Class Members
const lerpvert * max
const lerpvert * min
vec normal
vec nstep
float u
float ustep
int winding
Macro Definition Documentation
#define CHECK_CALCLIGHT_PROGRESS (exit, show_calclight_progress) CHECK_CALCLIGHT_PROGRESS_LOCKED(exit, show_calclight_progress, ,)
Referenced by addnormals().
#define CHECK_CALCLIGHT_PROGRESS_LOCKED (exit, show_calclight_progress, before, after)
Value:
if(check_calclight_progress) \
    { \
        if(!calclight_canceled) \
        { \
            before; \
            show_calclight_progress(); \
            check_calclight_canceled(); \
            after; \
        } \
        if(calclight_canceled) { exit; } \
    }
#define LM_MAXH 128
Referenced by generatelightmap(), lightmapworker::lightmapworker(), and setupsurface().
#define LM_MAXW 128
Referenced by generatelightmap(), lightmapworker::lightmapworker(), and setupsurface().
#define LM_MINH 2
Referenced by setupsurface().
#define LM_MINW 2
Referenced by setupsurface().
#define LM_PACKH 512
Referenced by addcubeverts(), calclight(), convertoldsurfaces(), copylightmap(), dumplms(), genlightmaptexs(), insertlightmap(), load_world(), packlightmaps(), patchlight(), previewblends(), rotatenormals(), save_world(), setupsurface(), show_calclight_progress(), and updatelightmap().
#define LM_PACKW 512
Referenced by addcubeverts(), calclight(), convertoldsurfaces(), LightMap::copy(), copylightmap(), dumplms(), findunlit(), genlightmaptexs(), htcmp(), insertlightmap(), load_world(), packlightmaps(), patchlight(), previewblends(), rotatenormals(), save_world(), setupsurface(), show_calclight_progress(), and updatelightmap().
Enumeration Type Documentation
anonymous enum
Enumerator
LM_DIFFUSE
LM_BUMPMAP0
LM_BUMPMAP1
LM_TYPE
LM_ALPHA
LM_FLAGS
Function Documentation
void brightencube (cube & c)
References brightsurfaces, cube::ext, newcubeext(), and cubeext::surfaces.
Referenced by invalidatemerges(), readychanges(), remip(), and subdividecube().
entity* brightestlight (const vec & target, const vec & dir)
References extentity::attached, entity::attr1, checklightcache(), vec::div(), vec::dot(), entities::ents, ET_LIGHT, ET_SPOTLIGHT, entities::getents(), loopv, vec::magnitude(), vec::normalize(), entity::o, RAY_POLY, RAY_SHADOW, RAY_SKIPSKY, shadowray(), sincos360, vec::sub(), sunlightdir, sunlightent, and entity::type.
Referenced by setupmaterials().
void calclerpverts (const vec2 * c, const vec * n, lerpvert * lv, int & numv)
References loopj, lerpvert::normal, and lerpvert::tc.
Referenced by setupsurface().
void calcnormals (bool lerptjoints = false)
References addnormals(), f(), findtjoints(), lerpthreshold, lerptjoints, loopi(), progress, RAD, usetnormals, worldroot, and worldsize.
Referenced by calclight(), and patchlight().
void check_calclight_canceled ()
References calclight_canceled, check_calclight_progress, inexor::io::input_router, inexor::io::InputRouter::interceptkey(), lightmapworkers, and loopv.
void clearlightcache (int id = -1)
References entity::attr1, entities::getents(), lightcache, LIGHTCACHEHASH, LIGHTCACHESIZE, lightcacheentry::lights, inexor::rpc::max(), inexor::rpc::min(), entity::o, vector< T, MINSIZE >::setsize(), worldsize, lightcacheentry::x, and lightcacheentry::y.
Referenced by clearlights(), initlights(), modifyoctaent(), and resetlightmaps().
void clearlights ()
References clearlightcache(), entitylight::color, entitylight::dir, entities::ents, genlightmaptexs(), entities::getents(), extentity::light, LM_ALPHA, loopv, and shouldlightents.
Referenced by initlights().
void clearnormals ()
References normalgroups, and vector< T, MINSIZE >::setsize().
Referenced by calclight(), and patchlight().
void findnormal (const vec & key, const vec & surface, vec & v)
References findnormal(), findtnormal(), normalgroups, and normalgroup::tnormals.
Referenced by setupsurfaces().
void initlerpbounds (float u, float v, const lerpvert * lv, int numv, lerpbounds & start, lerpbounds & end)
References loopi(), lerpbounds::max, lerpbounds::min, setlerpstep(), lerpvert::tc, and lerpbounds::winding.
Referenced by generatelightmap().
void initlights ()
References clearlightcache(), clearlights(), editmode, genlightmaptexs(), lightmaps, LM_ALPHA, and shouldlightents.
Referenced by calclight(), clearlightmaps(), emptymap(), load_world(), patchlight(), resetgl(), setfullbrightlevel(), and toggleedit().
void lerpnormal (float u, float v, const lerpvert * lv, int numv, lerpbounds & start, lerpbounds & end, vec & normal, vec & nstep)
References vec::add(), vec::div(), vec::mul(), lerpbounds::normal, vec::normalize(), lerpbounds::nstep, vec::sub(), lerpbounds::u, updatelerpbounds(), and lerpbounds::ustep.
Referenced by generatelightmap().
void lightent (extentity & e, float height = 8.0f)
References model::above(), entity::attr2, entitylight::color, entitylight::dir, ET_GAMESPECIFIC, ET_LIGHT, ET_MAPMODEL, extentity::light, lightreaching(), loadmodel(), entity::o, ai::target(), and entity::type.
Referenced by lightents(), and modifyoctaent().
void lightents (bool force = false)
References entities::ents, entities::getents(), lightent(), loopv, and shouldlightents.
Referenced by allchanged(), and toggleedit().
void lightreaching (const vec & target, vec & color, vec & dir, bool fast = false, extentity * e = nullptr, float ambient = 0.4f)
References vec::add(), ambientcolor, extentity::attached, entity::attr1, entity::attr2, entity::attr3, entity::attr4, calcskylight(), checklightcache(), vec::div(), vec::dot(), editmode, entities::ents, ET_LIGHT, ET_SPOTLIGHT, f(), fastskylight(), entities::getents(), hasskylight(), vec::iszero(), lightmaps, loopk, loopv, vec::magnitude(), inexor::rpc::max(), inexor::rpc::min(), vec::mul(), vec::normalize(), entity::o, RAY_POLY, RAY_SHADOW, RAY_SKIPSKY, shadowray(), sincos360, vec::sub(), sunlightcolor, sunlightdir, and entity::type.
Referenced by game::collectclientmode::droptoken(), game::explode(), lightent(), game::collectclientmode::rendergame(), rendermodel(), and gui::start().
void previewblends (const ivec & bo, const ivec & bs)
References commitchanges(), lightmapworkers, loadlayermasks(), previewblends(), worldroot, and worldsize.
void resetlightmaps (bool fullclean = true)
References cleanuplightmaps(), clearlightcache(), compressed, lightmaps, and lightmapworkers.
Referenced by calclight(), clearlightmaps(), and resetmap().
void setsurface (cube & c, int orient, const surfaceinfo & surf, const vertinfo * verts, int numverts)
References ext(), cube::ext, growcubeext(), loopi(), cubeext::maxverts, newcubeext(), sphere::numverts, orient, setcubeext(), cubeext::surfaces, surfaceinfo::totalverts(), surfaceinfo::verts, and cubeext::verts().
Referenced by addmerge().
void setsurfaces (cube & c, const surfaceinfo * surfs, const vertinfo * verts, int numverts)
References cube::ext, cubeext::maxverts, newcubeext(), cubeext::surfaces, sphere::verts, and cubeext::verts().
Referenced by convertoldsurfaces(), and previewblends().
Variable Documentation
bvec ambientcolor
Referenced by calcskylight(), fastskylight(), findunlit(), generatelightmap(), generatelumel(), genreservedlightmaptexs(), hasskylight(), insertunlit(), lightreaching(), lumelsample(), pushshadowmap(), renderwater(), and setupgeom().
bool calclight_canceled
Referenced by calclight(), check_calclight_canceled(), patchlight(), and show_calclight_progress().
volatile bool check_calclight_progress
Referenced by calclight(), calclighttimer(), check_calclight_canceled(), and patchlight().
int lightmapping
Referenced by cleanupthreads(), loadmodel(), mmintersect(), processtasks(), setupthreads(), and BIH::triintersect().
vector<LightMap> lightmaps
Referenced by addcubeverts(), calclight(), cleanuplightmaps(), copylightmap(), dumplms(), findunlit(), genlightmaptexs(), gl_drawhud(), htcmp(), initlights(), insertlightmap(), insertunlit(), lightreaching(), load_world(), patchlight(), previewblends(), resetlightmaps(), rotatenormals(), save_world(), show_calclight_progress(), and updatelightmap().
vector<LightMapTexture> lightmaptexs
Referenced by addcubeverts(), changebatchtmus(), cleanuplightmaps(), gengrassquads(), vacollect::optimize(), vacollect::remapunlit(), setfullbrightlevel(), and updatelightmap().
bvec skylightcolor
Referenced by calcskylight(), fastskylight(), generatelightmap(), hasskylight(), pushshadowmap(), and renderwater().