Inexor: inexor/ui/legacy/menus.cpp File Reference
menus.cpp File Reference
#include <ctype.h>
#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include "inexor/client/network.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/fpsgame/player.hpp"
#include "inexor/model/rendermodel.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/legacy/3dgui.hpp"
#include "inexor/ui/legacy/menus.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct menu
struct delayedupdate
struct change
struct applymenu
union delayedupdate.val
Macros
#define GUI_TITLE_COLOR 0xFFDD88
#define GUI_BUTTON_COLOR 0xFFFFFF
#define GUI_TEXT_COLOR 0xDDFFDD
Functions
VARP (menudistance, 16, 40, 256)
VARP (menuautoclose, 32, 120, 4096)
vec menuinfrontofplayer ()
void popgui ()
void removegui (menu *m)
void pushgui (menu *m, int pos=-1)
void restoregui (int pos)
void showgui (const char *name)
void hidegui (const char *name)
int cleargui (int n)
void clearguis (int level=-1)
void guionclear (char *action)
void guistayopen (uint *contents)
void guinoautotab (uint *contents)
void guimerge (uint *contents)
void guibutton (char *name, char *action, char *icon)
void guiimage (char *path, char *action, float *scale, int *overlaid, char *alt)
void guicolor (int *color)
void guitextbox (char *text, int *width, int *height, int *color)
void guitext (char *name, char *icon)
void guititle (char *name)
void guitab (char *name)
void guibar ()
void guistrut (float *strut, int *alt)
void guispring (int *weight)
void guicolumn (int *col)
template<class T >
static void updateval (char *var, T val, char *onchange)
static int getval (char *var)
static float getfval (char *var)
static const char * getsval (char *var)
void guislider (char *var, int *min, int *max, char *onchange)
void guilistslider (char *var, char *list, char *onchange)
void guinameslider (char *var, char *names, char *list, char *onchange)
void guicheckbox (char *name, char *var, float *on, float *off, char *onchange)
void guiradio (char *name, char *var, float *n, char *onchange)
void guibitfield (char *name, char *var, int *mask, char *onchange)
void guifield (char *var, int *maxlength, char *onchange)
void guieditor (char *name, int *maxlength, int *height, int *mode)
void guikeyfield (char *var, int *maxlength, char *onchange)
void guilist (uint *contents)
void guialign (int *align, uint *contents)
void newgui (char *name, char *contents, char *header, char *init)
void notifywelcome ()
This function gets executed as we get connected.
COMMAND (newgui,"ssss")
COMMAND (guibutton,"sss")
COMMAND (guitext,"ss")
ICOMMAND (cleargui,"i",(int *n), intret(cleargui(*n)))
COMMAND (showgui,"s")
COMMAND (hidegui,"s")
COMMAND (guionclear,"s")
COMMAND (guistayopen,"e")
COMMAND (guinoautotab,"e")
COMMAND (guimerge,"e")
COMMAND (guilist,"e")
COMMAND (guialign,"ie")
COMMAND (guititle,"s")
COMMAND (guibar,"")
COMMAND (guistrut,"fi")
COMMAND (guispring,"i")
COMMAND (guicolumn,"i")
COMMAND (guiimage,"ssfis")
COMMAND (guislider,"sbbs")
COMMAND (guilistslider,"sss")
COMMAND (guinameslider,"ssss")
COMMAND (guiradio,"ssfs")
COMMAND (guibitfield,"ssis")
COMMAND (guicheckbox,"ssffs")
COMMAND (guitab,"s")
COMMAND (guifield,"sis")
COMMAND (guikeyfield,"sis")
COMMAND (guieditor,"siii")
COMMAND (guicolor,"i")
COMMAND (guitextbox,"siii")
void guiplayerpreview (int *model, int *team, int *weap, char *action, float *scale, int *overlaid)
COMMAND (guiplayerpreview,"iiisfi")
void guimodelpreview (char *model, char *animspec, char *action, float *scale, int *overlaid)
COMMAND (guimodelpreview,"sssfi")
void guiprefabpreview (char *prefab, int *color, char *action, float *scale, int *overlaid)
COMMAND (guiprefabpreview,"sisfi")
VARP (applydialog, 0, 1, 1)
void addchange (const char *desc, int type)
void clearchanges (int type)
void menuprocess ()
VAR (mainmenu, 1, 1, 0)
void clearmainmenu ()
void g3d_mainmenu ()
bool initwarning (const char *desc, int level, int type)
print initialisation (bug hints) warning in game console
Variables
static vec menupos
static int menustart = 0
static int menutab = 1
static g3d_gui * cgui = nullptr
static hashnameset< menu > guis
static vector< menu * > guistack
static vector< delayedupdate > updatelater
static bool shouldclearmenu = true
static bool clearlater = false
static vector< change > needsapply
applymenu applymenu
static bool processingmenu = false
Class Documentation
union delayedupdate.val
Class Members
float f
int i
char * s
Macro Definition Documentation
#define GUI_BUTTON_COLOR 0xFFFFFF
Referenced by applymenu::gui(), guibitfield(), guibutton(), guicheckbox(), guieditor(), guifield(), guikeyfield(), guiradio(), and guitext().
#define GUI_TEXT_COLOR 0xDDFFDD
Referenced by applymenu::gui(), and guitext().
#define GUI_TITLE_COLOR 0xFFDD88
Referenced by menu::gui(), guilistslider(), guinameslider(), guislider(), guitab(), and guititle().
Function Documentation
void addchange (const char * desc, int type)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::find(), vector< T, MINSIZE >::length(), loopv, inexor::rpc::max(), and pushgui().
Referenced by initwarning().
void clearchanges (int type)
References vector< T, MINSIZE >::empty(), loopv, vector< T, MINSIZE >::remove(), and removegui().
Referenced by resetgl(), and inexor::sound::resetsound().
int cleargui (int n)
References vector< T, MINSIZE >::empty(), isconnected(), vector< T, MINSIZE >::length(), loopi(), mainmenu, inexor::rpc::min(), popgui(), and restoregui().
Referenced by clearguis(), clearmainmenu(), g3d_mainmenu(), and g3d_windowhit().
void clearguis (int level = -1)
References cleargui(), execute(), freecode(), vector< T, MINSIZE >::length(), loopvrev, and menu::onclear.
Referenced by menuprocess().
void clearmainmenu ()
References cleargui(), isconnected(), and mainmenu.
Referenced by emptymap(), and load_world().
COMMAND (newgui , "ssss")
COMMAND (guibutton , "sss")
COMMAND (guitext , "ss")
COMMAND (showgui , "s")
COMMAND (hidegui , "s")
COMMAND (guionclear , "s")
COMMAND (guistayopen , "e")
COMMAND (guinoautotab , "e")
COMMAND (guimerge , "e")
COMMAND (guilist , "e")
COMMAND (guialign , "ie")
COMMAND (guititle , "s")
COMMAND (guibar , "")
COMMAND (guistrut , "fi")
COMMAND (guispring , "i")
COMMAND (guicolumn , "i")
COMMAND (guiimage , "ssfis")
COMMAND (guislider , "sbbs")
COMMAND (guilistslider , "sss")
COMMAND (guinameslider , "ssss")
COMMAND (guiradio , "ssfs")
COMMAND (guibitfield , "ssis")
COMMAND (guicheckbox , "ssffs")
COMMAND (guitab , "s")
COMMAND (guifield , "sis")
COMMAND (guikeyfield , "sis")
COMMAND (guieditor , "siii")
COMMAND (guicolor , "i")
COMMAND (guitextbox , "siii")
COMMAND (guiplayerpreview , "iiisfi")
COMMAND (guimodelpreview , "sssfi")
COMMAND (guiprefabpreview , "sisfi")
void g3d_mainmenu ()
References camera1, cleargui(), vec::dist(), vector< T, MINSIZE >::empty(), g3d_addgui(), GUI_2D, GUI_FOLLOW, vector< T, MINSIZE >::last(), mainmenu, menuautoclose, menupos, and physent::o.
Referenced by g3d_render().
static float getfval (char * var) static
References ID_ALIAS, ID_FVAR, ID_SVAR, ID_VAR, parsefloat(), readident(), and ident::type.
Referenced by guicheckbox(), and guiradio().
static const char* getsval (char * var) static
References floatstr(), ID_ALIAS, ID_FVAR, ID_SVAR, ID_VAR, intstr(), readident(), and ident::type.
Referenced by guifield(), and guikeyfield().
static int getval (char * var) static
References ID_ALIAS, ID_FVAR, ID_SVAR, ID_VAR, parseint(), readident(), and ident::type.
Referenced by guibitfield(), guilistslider(), guinameslider(), and guislider().
void guialign (int * align, uint * contents)
References execute(), g3d_gui::poplist(), g3d_gui::pushlist(), and g3d_gui::spring().
void guibar ()
References g3d_gui::separator().
void guibitfield (char * name, char * var, int * mask, char * onchange)
References g3d_gui::button(), gle::enabled, G3D_UP, getval(), GUI_BUTTON_COLOR, and updateval().
void guibutton (char * name, char * action, char * icon)
References vector< T, MINSIZE >::add(), alias(), g3d_gui::button(), clearlater, G3D_ROLLOVER, G3D_UP, GUI_BUTTON_COLOR, delayedupdate::schedule(), and shouldclearmenu.
void guicheckbox (char * name, char * var, float * on, float * off, char * onchange)
References g3d_gui::button(), gle::enabled, f(), G3D_UP, getfval(), GUI_BUTTON_COLOR, and updateval().
void guicolor (int * color)
References defformatstring, and g3d_gui::text().
void guicolumn (int * col)
References g3d_gui::column().
void guieditor (char * name, int * maxlength, int * height, int * mode)
References EDITORFOREVER, g3d_gui::field(), and GUI_BUTTON_COLOR.
void guifield (char * var, int * maxlength, char * onchange)
References g3d_gui::field(), getsval(), GUI_BUTTON_COLOR, result(), and updateval().
void guiimage (char * path, char * action, float * scale, int * overlaid, char * alt)
References vector< T, MINSIZE >::add(), alias(), clearlater, G3D_ROLLOVER, G3D_UP, g3d_gui::image(), notexture, delayedupdate::schedule(), shouldclearmenu, anonymous_namespace{utilTest.cpp}::t(), and textureload().
void guikeyfield (char * var, int * maxlength, char * onchange)
References getsval(), GUI_BUTTON_COLOR, g3d_gui::keyfield(), result(), and updateval().
void guilist (uint * contents)
References execute(), g3d_gui::poplist(), and g3d_gui::pushlist().
void guilistslider (char * var, char * list, char * onchange)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::empty(), getval(), GUI_TITLE_COLOR, intstr(), vector< T, MINSIZE >::length(), loopv, parseint(), g3d_gui::slider(), and updateval().
void guimerge (uint * contents)
References execute(), and g3d_gui::mergehits().
void guimodelpreview (char * model, char * animspec, char * action, float * scale, int * overlaid)
References vector< T, MINSIZE >::add(), ANIM_ALL, ANIM_INDEX, ANIM_LOOP, clearlater, findanims(), G3D_UP, vector< T, MINSIZE >::length(), g3d_gui::modelpreview(), parseint(), delayedupdate::schedule(), and shouldclearmenu.
void guinameslider (char * var, char * names, char * list, char * onchange)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::empty(), getval(), GUI_TITLE_COLOR, indexlist(), vector< T, MINSIZE >::length(), loopv, parseint(), g3d_gui::slider(), and updateval().
void guinoautotab (uint * contents)
References g3d_gui::allowautotab(), and execute().
void guionclear (char * action)
References compilecode(), vector< T, MINSIZE >::empty(), freecode(), vector< T, MINSIZE >::last(), and menu::onclear.
void guiplayerpreview (int * model, int * team, int * weap, char * action, float * scale, int * overlaid)
References vector< T, MINSIZE >::add(), clearlater, G3D_UP, g3d_gui::playerpreview(), delayedupdate::schedule(), and shouldclearmenu.
void guiprefabpreview (char * prefab, int * color, char * action, float * scale, int * overlaid)
References vector< T, MINSIZE >::add(), clearlater, G3D_UP, vec::hexcolor(), g3d_gui::prefabpreview(), delayedupdate::schedule(), and shouldclearmenu.
void guiradio (char * name, char * var, float * n, char * onchange)
References g3d_gui::button(), gle::enabled, G3D_UP, getfval(), GUI_BUTTON_COLOR, and updateval().
void guislider (char * var, int * min, int * max, char * onchange)
References getval(), getvarmax(), getvarmin(), GUI_TITLE_COLOR, g3d_gui::slider(), and updateval().
void guispring (int * weight)
References inexor::rpc::max(), and g3d_gui::spring().
void guistayopen (uint * contents)
References execute(), and shouldclearmenu.
void guistrut (float * strut, int * alt)
References g3d_gui::space(), and g3d_gui::strut().
void guitab (char * name)
References GUI_TITLE_COLOR, and g3d_gui::tab().
void guitext (char * name, char * icon)
References GUI_BUTTON_COLOR, GUI_TEXT_COLOR, and g3d_gui::text().
void guitextbox (char * text, int * width, int * height, int * color)
References g3d_gui::textbox().
void guititle (char * name)
References GUI_TITLE_COLOR, and g3d_gui::title().
void hidegui (const char * name)
References hashbase< hashnameset< T >, T, const char *, T >::access(), and removegui().
ICOMMAND (cleargui , "i" , (int *n) , intret(cleargui(*n)))
bool initwarning (const char * desc, int level, int type)
print initialisation (bug hints) warning in game console
See Also
addchange
References addchange(), and initing.
Referenced by inexor::rendering::screen::ScreenManager::screenres().
vec menuinfrontofplayer ()
References vec::add(), camera1, dir, physent::eyeheight, menudistance, vec::mul(), physent::o, player, vecfromyawpitch(), and physent::yaw.
Referenced by pushgui(), game::scoreboardgui::show(), and texturegui::showtextures().
void menuprocess ()
References clearguis(), clearlater, vector< T, MINSIZE >::empty(), isconnected(), vector< T, MINSIZE >::length(), loopv, mainmenu, showgui(), and vector< T, MINSIZE >::shrink().
Referenced by main().
void newgui (char * name, char * contents, char * header, char * init)
References hashbase< hashnameset< T >, T, const char *, T >::access(), compilecode(), menu::contents, DELETEA, gle::end(), freecode(), menu::header, menu::init, menu::name, newstring(), and menu::showtab.
void notifywelcome ()
This function gets executed as we get connected.
Referenced by game::parsemessages().
void popgui ()
References menu::clear(), and vector< T, MINSIZE >::pop().
Referenced by cleargui(), and restoregui().
void pushgui (menu * m, int pos = -1)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::empty(), execute(), g3d_resetcursor(), menu::init, vector< T, MINSIZE >::insert(), vector< T, MINSIZE >::length(), menuinfrontofplayer(), menustart, menutab, and totalmillis.
Referenced by addchange(), and showgui().
void removegui (menu * m)
References menu::clear(), loopv, and vector< T, MINSIZE >::remove().
Referenced by clearchanges(), and hidegui().
void restoregui (int pos)
References vector< T, MINSIZE >::length(), loopi(), menustart, menutab, popgui(), and totalmillis.
Referenced by cleargui(), and showgui().
void showgui (const char * name)
References hashbase< hashnameset< T >, T, const char *, T >::access(), vector< T, MINSIZE >::find(), pushgui(), and restoregui().
Referenced by menuprocess().
template<class T > static void updateval (char * var, T val, char * onchange) static
References vector< T, MINSIZE >::add(), delayedupdate::schedule(), and writeident().
Referenced by guibitfield(), guicheckbox(), guifield(), guikeyfield(), guilistslider(), guinameslider(), guiradio(), and guislider().
VAR (mainmenu , 1 , 1 , 0)
VARP (menudistance , 16 , 40 , 256)
VARP (menuautoclose , 32 , 120 , 4096)
VARP (applydialog , 0 , 1 , 1)
Variable Documentation
applymenu applymenu static
g3d_gui* cgui = nullptr static
bool clearlater = false static
Referenced by applymenu::gui(), guibutton(), guiimage(), guimodelpreview(), guiplayerpreview(), guiprefabpreview(), and menuprocess().
hashnameset<menu> guis static
vector<menu *> guistack static
vec menupos static
Referenced by g3d_mainmenu(), texturegui::show(), and texturegui::showtextures().
int menustart = 0 static
Referenced by menu::gui(), applymenu::gui(), texturegui::gui(), pushgui(), restoregui(), and texturegui::showtextures().
int menutab = 1 static
Referenced by menu::gui(), texturegui::gui(), pushgui(), restoregui(), and texturegui::showtextures().
vector<change> needsapply static
bool processingmenu = false static
bool shouldclearmenu = true static
Referenced by guibutton(), guiimage(), guimodelpreview(), guiplayerpreview(), guiprefabpreview(), and guistayopen().
vector<delayedupdate> updatelater static