Inexor: inexor/model/model.hpp File Reference
model.hpp File Reference
#include "inexor/physics/bih.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/engine/shader.hpp"
Classes
struct modelattach
struct model
Enumerations
enum {
MDL_MD2 = 0, MDL_MD3, MDL_MD5, MDL_OBJ,
MDL_SMD, MDL_IQM, NUMMODELTYPES
}
enum {
MDL_CULL_VFC = 1<<0, MDL_CULL_DIST = 1<<1, MDL_CULL_OCCLUDED = 1<<2, MDL_CULL_QUERY = 1<<3,
MDL_SHADOW = 1<<4, MDL_DYNSHADOW = 1<<5, MDL_LIGHT = 1<<6, MDL_DYNLIGHT = 1<<7,
MDL_FULLBRIGHT = 1<<8, MDL_NORENDER = 1<<9, MDL_LIGHT_FAST = 1<<10, MDL_HUD = 1<<11,
MDL_GHOST = 1<<12
}
Functions
void startmodelbatches ()
void endmodelbatches ()
void rendermodel (entitylight *light, const char *mdl, int anim, const vec &o, float yaw=0, float pitch=0, int cull=MDL_CULL_VFC|MDL_CULL_DIST|MDL_CULL_OCCLUDED|MDL_LIGHT, dynent *d=nullptr, modelattach *a=nullptr, int basetime=0, int basetime2=0, float trans=1)
void abovemodel (vec &o, const char *mdl)
void rendershadow (dynent *d)
void renderclient (dynent *d, const char *mdlname, modelattach *attachments, int hold, int attack, int attackdelay, int lastaction, int lastpain, float fade=1, bool ragdoll=false)
void interpolateorientation (dynent *d, float &interpyaw, float &interppitch)
void setbbfrommodel (dynent *d, const char *mdl)
const char * mapmodelname (int i)
model * loadmodel (const char *name, int i=-1, bool msg=false)
void preloadmodel (const char *name)
void flushpreloadedmodels (bool msg=true)
Enumeration Type Documentation
anonymous enum
Enumerator
MDL_MD2
MDL_MD3
MDL_MD5
MDL_OBJ
MDL_SMD
MDL_IQM
NUMMODELTYPES
anonymous enum
Enumerator
MDL_CULL_VFC
MDL_CULL_DIST
MDL_CULL_OCCLUDED
MDL_CULL_QUERY
MDL_SHADOW
MDL_DYNSHADOW
MDL_LIGHT
MDL_DYNLIGHT
MDL_FULLBRIGHT
MDL_NORENDER
MDL_LIGHT_FAST
MDL_HUD
MDL_GHOST
Function Documentation
void abovemodel (vec & o, const char * mdl)
References model::above(), and loadmodel().
Referenced by game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), game::collectclientmode::setup(), and game::captureclientmode::setup().
void endmodelbatches ()
References vector< T, MINSIZE >::add(), modelbatch::batched, transparentmodel::batched, BLOB_DYNAMIC, BLOB_STATIC, model::boundbox(), camera1, ragdolldata::center, batchedmodel::d, vec::dist(), transparentmodel::dist, vector< T, MINSIZE >::empty(), endquery, model::endrender(), batchedmodel::flags, modelbatch::flags, flushblobs(), vector< T, MINSIZE >::length(), loopi(), loopv, loopvj, modelbatch::m, transparentmodel::m, inexor::rpc::max(), MDL_CULL_VFC, MDL_DYNSHADOW, MDL_GHOST, MDL_SHADOW, physent::o, occludequery::owner, batchedmodel::pos, batchedmodel::query, physent::radius, dynent::ragdoll, renderbatchedmodel(), renderblob(), shadowmapping, vector< T, MINSIZE >::sort(), sorttransparentmodels(), startquery, model::startrender(), and batchedmodel::transparent.
Referenced by game::rendergame(), rendermapmodels(), and renderreflectedmapmodels().
void flushpreloadedmodels (bool msg = true)
References vector< T, MINSIZE >::deletearrays(), vector< T, MINSIZE >::length(), loadmodel(), loadprogress, Log, loopv, model::preloadmeshes(), and inexor::util::log_manager::std.
Referenced by load_world().
void interpolateorientation (dynent * d, float & interpyaw, float & interppitch)
model* loadmodel (const char * name, int i = -1, bool msg = false)
References hashbase< hashnameset< T >, T, const char *, T >::access(), vector< T, MINSIZE >::add(), defformatstring, DELETEP, vector< T, MINSIZE >::find(), vector< T, MINSIZE >::inrange(), lightmapping, model::load(), loadprogress, loopi(), mapmodelinfo::m, modeldir, modeltypes(), mapmodelinfo::name, model::name, NUMMODELTYPES, model::preloadshaders(), and renderprogress().
Referenced by abovemodel(), entselectionbox(), flushpreloadedmodels(), getentboundingbox(), lightent(), loadmapmodel(), gui::modelpreview(), preloadusedmapmodels(), rendermodel(), and setbbfrommodel().
const char* mapmodelname (int i)
References vector< T, MINSIZE >::inrange().
Referenced by entities::entmodel(), game::movable::movable(), entities::preloadentities(), and game::rendermovables().
void preloadmodel (const char * name)
References hashbase< hashnameset< T >, T, const char *, T >::access(), vector< T, MINSIZE >::add(), and newstring().
Referenced by game::ctfclientmode::preload(), game::collectclientmode::preload(), game::captureclientmode::preload(), game::preloadbouncers(), entities::preloadentities(), game::preloadplayermodel(), and game::preloadweapons().
void renderclient (dynent * d, const char * mdlname, modelattach * attachments, int hold, int attack, int attackdelay, int lastaction, int lastpain, float fade = 1, bool ragdoll = false)
References game::allowmove(), ANIM_ALL, ANIM_BACKWARD, ANIM_DEAD, ANIM_DYING, ANIM_EDIT, ANIM_END, ANIM_FORWARD, ANIM_IDLE, ANIM_INDEX, ANIM_JUMP, ANIM_LAG, ANIM_LEFT, ANIM_LOOP, ANIM_NOPITCH, ANIM_PAIN, ANIM_RAGDOLL, ANIM_RIGHT, ANIM_SECONDARY, ANIM_SINK, ANIM_SWIM, CS_DEAD, CS_EDITING, CS_LAGGED, CS_SPECTATOR, DELETEP, drawtex, DRAWTEX_MODELPREVIEW, ENT_AI, ENT_PLAYER, f(), hmap::flags, lastmillis, MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_QUERY, MDL_CULL_VFC, MDL_DYNSHADOW, MDL_FULLBRIGHT, MDL_LIGHT, inexor::rpc::min(), PHYS_FALL, physent::pitch, player, rendermodel(), and physent::yaw.
Referenced by game::renderplayer().
void rendermodel (entitylight * light, const char * mdl, int anim, const vec & o, float yaw = 0, float pitch = 0, int cull = MDL_CULL_VFC|MDL_CULL_DIST|MDL_CULL_OCCLUDED|MDL_LIGHT, dynent * d = nullptr, modelattach * a = nullptr, int basetime = 0, int basetime2 = 0, float trans = 1)
References physent::aboveeye, vector< T, MINSIZE >::add(), vec::add(), addbatchedmodel(), batchedmodel::anim, ANIM_FULLBRIGHT, ANIM_GHOST, ANIM_NORENDER, ANIM_NOSKIN, batchedmodel::attached, batchedmodel::basetime, batchedmodel::basetime2, modelbatch::batched, BLOB_DYNAMIC, BLOB_STATIC, model::boundbox(), ragdolldata::center, model::collisionbox(), entitylight::color, batchedmodel::color, cullmodel(), batchedmodel::d, hmap::d, entitylight::dir, batchedmodel::dir, disablecullmodelquery(), dynlightreaching(), editmode, enablecullmodelquery(), endquery, model::endrender(), ENT_CAMERA, physent::eyeheight, batchedmodel::flags, modelbatch::flags, flushblobs(), glaring, GLOBALPARAMF, lastmillis, vector< T, MINSIZE >::length(), dynent::light, game::lighteffects(), lightreaching(), loadmodel(), modelattach::m, vec::magnitude(), inexor::rpc::max(), MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_QUERY, MDL_CULL_VFC, MDL_DYNLIGHT, MDL_DYNSHADOW, MDL_FULLBRIGHT, MDL_GHOST, MDL_HUD, MDL_LIGHT, MDL_LIGHT_FAST, MDL_NORENDER, MDL_SHADOW, entitylight::millis, modelquery, newquery(), notextureshader, physent::o, OCCLUDE_NOTHING, dynent::occluded, oqfrags, batchedmodel::pitch, batchedmodel::pos, dynent::query, batchedmodel::query, RAD, physent::radius, ragdolldata::radius, dynent::ragdoll, reflecting, reflectz, refracting, model::render(), render3dbox(), renderblob(), rendercullmodelquery(), renderellipse(), vec::rotate_around_z(), rotatebb(), Shader::set(), shadowmap, shadowmapping, showblobs, startquery, model::startrender(), modelattach::tag, batchedmodel::transparent, physent::type, physent::xradius, physent::yaw, batchedmodel::yaw, and physent::yradius.
Referenced by game::drawhudmodel(), gui::modelpreview(), game::renderbouncers(), renderclient(), entities::renderentities(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), game::ctfclientmode::rendergame(), rendermapmodel(), game::rendermovables(), game::renderplayer(), game::bombclientmode::renderplayersposindicator(), and game::renderprojectiles().
void rendershadow (dynent * d)
void setbbfrommodel (dynent * d, const char * mdl)
References physent::aboveeye, COLLIDE_OBB, physent::collidetype, model::collisionbox(), model::ellipsecollide, ENT_INANIMATE, model::eyeheight, physent::eyeheight, loadmodel(), inexor::rpc::max(), physent::radius, physent::type, physent::xradius, and physent::yradius.
Referenced by game::movable::movable().
void startmodelbatches ()
References vector< T, MINSIZE >::setsize().
Referenced by game::rendergame(), rendermapmodels(), and renderreflectedmapmodels().