Inexor: anonymous_namespace{utilTest.cpp} Namespace Reference
anonymous_namespace{utilTest.cpp} Namespace Reference
Typedefs
typedef const char * cstr
Functions
template<typename T >
void ttype (cstr s, T sep, cstr exp)
void tstr (cstr s, cstr sep, cstr exp)
void tchar (cstr s, cstr sep, cstr exp)
test (split_find_last, Splits)
template<typename T >
void t (T x, const char *cmp)
test (to_string, works)
Typedef Documentation
typedef const char* anonymous_namespace{utilTest.cpp}::cstr
Function Documentation
template<typename T > void anonymous_namespace{utilTest.cpp}::t (T x, const char * cmp)
References expectEq, and inexor::util::to_string().
Referenced by queue< shaftbb, 32 >::add(), addcubeverts(), server::adddemo(), addnormals(), skelmodel::skeleton::addtag(), server::addteaminfo(), addtris(), game::collectclientmode::aicheck(), game::collectclientmode::aifind(), game::ctfclientmode::aifind(), game::collectclientmode::aipursue(), allocatepostfxtex(), Shader::allocparams(), aiman::balanceteams(), blurtexture(), animmodel::mesh::buildnorms(), partrenderer::calc(), ragdolldata::calcanimjoint(), animmodel::part::calcbb(), skelmodel::skeleton::calcpitchcorrects(), calcscissorbox(), calcskylight(), skelmodel::skeleton::calctags(), animmodel::mesh::calctangent(), animmodel::mesh::calctangents(), aiman::calcteams(), ragdolldata::calctris(), changeslottmus(), game::collectclientmode::checkitems(), server::checklms(), ai::checkroute(), Slot::cleanup(), clipfacevecx(), clipfacevecy(), skelmodel::skeleton::concattagtransform(), cubemapload(), cubemaploadwildcard(), ai::damaged(), server::collectservermode::deposittokens(), vec::dist(), server::dodamage(), game::drawhudmodel(), server::collectservermode::droptoken(), game::collectclientmode::droptoken(), collectmode_common::droptoken(), server::collectservermode::droptokens(), endianswap(), endianswap< double >(), ai::enemy(), entautoview(), game::collectclientmode::expiretoken(), fastskylight(), fonttex(), animmodel::mesh::genBIH(), animmodel::part::genBIH(), gendds(), generatealpha(), generatelightmap(), generatelightmaps(), gengrassquads(), vertmodel::vertmesh::genvbo(), skelmodel::skelmesh::genvbo(), md2::md2meshgroup::genverts(), game::getbestteams(), getstring(), guiimage(), sphere::init(), server::collectservermode::initclient(), skelmodel::skeleton::initpitchdeps(), game::ctfclientmode::interpflagpos(), entities::itemicon(), entities::itemname(), server::collectservermode::leavegame(), dualquat::lerp(), game::lighteffects(), obj::objmeshgroup::load(), md5::md5mesh::load(), Slot::load(), loadc(), iqm::iqmmeshgroup::loadiqmmeshes(), loadskyoverlay(), Slot::loadthumbnail(), inexor::rpc::TestRpcClient< DATA_TYPE, SERVICE_TYPE >::make_test_msg(), matrix4x3::multranspose(), newentity(), newtexture(), vacollect::optimize(), packlightmaps(), game::parsemessages(), server::parsepacket(), particle_text(), path(), gui::previewslot(), processtasks(), rdjoint(), rdtri(), registertexture(), reloadtex(), reloadtexture(), vacollect::remapunlit(), queue< shaftbb, 32 >::remove(), rendereditcursor(), game::collectclientmode::rendergame(), rendermaterials(), fireballrenderer::renderpart(), reportinvalidtextslot(), rotatequad(), scaletexture(), varenderer< T >::seedemitter(), seedpos(), hmap::select(), vertinfo::set(), setiter(), skelcommands< MDL >::setpitchtarget(), game::setteaminfo(), settexture(), setupcaustics(), vacollect::setupdata(), ragdollskel::setupjoints(), setupsurface(), shifttexture(), animmodel::mesh::smoothnorms(), game::collectclientmode::stealtoken(), server::suicide(), game::collectclientmode::taketoken(), server::collectservermode::taketoken(), ai::target(), test(), TEST(), textureload(), matrix4x3::transposemul(), BIH::triintersect(), server::captureservermode::update(), server::collectservermode::update(), server::welcomepacket(), and lightmapworker::work().
void anonymous_namespace{utilTest.cpp}::tchar (cstr s, cstr sep, cstr exp)
References tstr().
Referenced by test().
anonymous_namespace{utilTest.cpp}::test (split_find_last , Splits)
References tchar(), and tstr().
anonymous_namespace{utilTest.cpp}::test (to_string , works)
References t().
void anonymous_namespace{utilTest.cpp}::tstr (cstr s, cstr sep, cstr exp)
Referenced by tabify(), tchar(), and test().
template<typename T > void anonymous_namespace{utilTest.cpp}::ttype (cstr s, T sep, cstr exp)
References expectEq.