Inexor: inexor::crashreporter Namespace Reference
inexor::crashreporter Namespace Reference
Classes
class CrashReporter
Functions
void abortHandler (int signum)
This function serves as callback for the signals function.
static void demanglesymbol (std::vector< std::string > &output, char *symbol)
static void printStackTrace (std::vector< std::string > &output)
Function Documentation
void inexor::crashreporter::abortHandler (int signum)
This function serves as callback for the signals function.
It gets executed when an instance of the crashreporter class exists in your code and it receives a signal by the OS to terminate the program.
References fatal(), inexor::util::fmt, move(), and printStackTrace().
Referenced by inexor::crashreporter::CrashReporter::CrashReporter().
static void inexor::crashreporter::demanglesymbol (std::vector< std::string > & output, char * symbol) inline static
References inexor::util::fmt, and move().
Referenced by printStackTrace().
static void inexor::crashreporter::printStackTrace (std::vector< std::string > & output) inline static
References demanglesymbol(), and MAX_FRAMES.
Referenced by abortHandler().