Inexor: inexor::filesystem Namespace Reference
inexor::filesystem Namespace Reference
Typedefs
using Path = boost::filesystem::path
Functions
std::string ExecutablePathWithoutBinary (const char *argv0)
std::string ExecutablePath (const char *argv0)
std::string ExecutablePathFallback (const char *argv0)
const char * getmediadir (int type)
Returns the specific media dir according to type.
Path getmediapath (const std::string &basename, int type)
Append the media directory specified by type to the basename.
std::string & getmediapath (std::string &output, const std::string basename, int type)
const char * getmediapath (char *output, int outputlen, const std::string &basename, int type)
const std::string filecontents (const std::string &filename)
Retrieve the contents of a text file.
const std::string filecontents_partly (const std::string &filename, size_t start_line, size_t end_line)
Load the contents of a file in a specific section.
std::vector< Path > & list_files (Path folder, std::vector< Path > &file_list, Path ext)
Retrieve a list of all files inside a folder (non recursively!).
Typedef Documentation
using inexor::filesystem::Path = typedef boost::filesystem::path
See Also
boost::filesystem::path We need to rename this class bc otherwise we get clashes with legacy code.
Function Documentation
std::string inexor::filesystem::ExecutablePath (const char * argv0)
References ExecutablePathFallback().
Referenced by ExecutablePathWithoutBinary().
std::string inexor::filesystem::ExecutablePathFallback (const char * argv0)
References path().
Referenced by ExecutablePath().
std::string inexor::filesystem::ExecutablePathWithoutBinary (const char * argv0)
References ExecutablePath(), and path().
Referenced by inexor::ui::CefSubsystem::initialize().
const std::string inexor::filesystem::filecontents (const std::string & filename)
Retrieve the contents of a text file.
const std::string inexor::filesystem::filecontents_partly (const std::string & filename, size_t start_line, size_t end_line)
Load the contents of a file in a specific section.
Parameters
filename the name of the file to load contents from
start_line the first line we copy.
end_line the last line we copy to the output string.
Note
we count from 1 upwards (as you see it in your text-editor)
const char * inexor::filesystem::getmediadir (int type)
Returns the specific media dir according to type.
Returns the media-dir string of specific type.
References DIR_ICON, DIR_MAP, DIR_MUSIC, DIR_RADAR, DIR_SKYBOX, DIR_SOUND, DIR_TEXTURE, DIR_UI, icondir, interfacedir, mapdir, musicdir, radardir, skyboxdir, sounddir, and texturedir.
Referenced by getmediapath().
Path inexor::filesystem::getmediapath (const std::string & basename, int type)
Append the media directory specified by type to the basename.
Slashes get corrected as well and will be in the platforms prefered form.
References dir, inexor::util::fmt, getmediadir(), and move().
Referenced by Slot::addtexture(), bind_bomb_items_texture(), bind_items_texture(), gui::button_(), cubemapload(), drawdamagescreen(), gui::drawskin(), getmapfilename(), gui::icon_(), gui::line_(), inexor::sound::soundsample::load(), loadsky(), loadskyoverlay(), gui::modelpreview(), gui::playerpreview(), gui::previewslot(), game::receivefile(), renderbackground(), renderprogress(), and game::sendmap().
std::string & inexor::filesystem::getmediapath (std::string & output, const std::string basename, int type)
References getmediapath().
const char * inexor::filesystem::getmediapath (char * output, int outputlen, const std::string & basename, int type)
Referenced by getmediapath().
std::vector< Path > & inexor::filesystem::list_files (Path folder, std::vector< Path > & file_list, Path ext)
Retrieve a list of all files inside a folder (non recursively!).
Parameters
folder The folder which contains the contents you want to retrieve a list from
file_list which will store and return all the file paths as a list
ext needs to be either empty or an extension to filter for (only those files get accepted) DOT needed! ".jpg"
References ext(), and recorder::file.