Inexor: inexor::rpc Namespace Reference
inexor::rpc Namespace Reference
Classes
struct callback_event
class RpcServer
class RpcSubsystem
class TestRpcClient
Temporary test client.
class SharedVar
SharedVar wrapper for primitive/immutable objects.
Enumerations
enum cpp_type_t { t_cstring = 0, t_float, t_int }
Known C++ SharedVar types.
enum EVENT_TYPE {
E_WRITE, E_READ, E_CONNECT, E_DISCONNECT,
E_NUM
}
The events we request GRPC to do.
Functions
void set_on_change_functions ()
void send_all_vars ()
template<typename MSG_TYPE >
bool handle_index (int index, const MSG_TYPE &tree_event)
const void * encode_signal (const int event_type, int clientid)
template<typename T >
std::ostream & operator<< (std::ostream &os, const SharedVar< T > &x)
template<typename T >
const T & min (const inexor::rpc::SharedVar< T > &a, const T &b)
template<typename T >
const T & min (const T &a, const inexor::rpc::SharedVar< T > &b)
template<typename T >
const T & min (const inexor::rpc::SharedVar< T > &a, const inexor::rpc::SharedVar< T > &b)
template<typename T >
const T & max (const inexor::rpc::SharedVar< T > &a, const T &b)
template<typename T >
const T & max (const T &a, const inexor::rpc::SharedVar< T > &b)
template<typename T >
const T & max (const inexor::rpc::SharedVar< T > &a, const inexor::rpc::SharedVar< T > &b)
Variables
const std::unordered_map
< int64, void * > cppvar_pointer_map
const std::unordered_map
< int64, int > index_to_type_map
Enumeration Type Documentation
enum inexor::rpc::cpp_type_t
Known C++ SharedVar types.
Enumerator
t_cstring
t_float
t_int
enum inexor::rpc::EVENT_TYPE
The events we request GRPC to do.
Enumerator
E_WRITE
E_READ
E_CONNECT
E_DISCONNECT
E_NUM
Function Documentation
const void* inexor::rpc::encode_signal (const int event_type, int clientid) inline
Referenced by inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::open_connect_slot(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::clienthandler::request_disconnect(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::clienthandler::request_read(), and inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::clienthandler::request_send_one().
template<typename MSG_TYPE > bool inexor::rpc::handle_index (int index, const MSG_TYPE & tree_event)
template<typename T > const T& inexor::rpc::max (const inexor::rpc::SharedVar< T > & a, const T & b)
References max().
Referenced by bigint< BI_DIGITS >::add(), addblendbrush(), skelmodel::skelmesh::addblendcombo(), rendertarget::addblurtiles(), addchange(), addgrasstri(), addmotionblur(), addreflection(), depthfxtexture::addscissorvert(), addshadowmapcaster(), addsleep(), gui::adjustcolumns(), gui::adjusthorizontalcolumn(), gui::adjustverticalcolumn(), allocatepostfxtex(), alloclightmap(), BIH::BIH(), blendfog(), blendfogoverlay(), blitblendmap(), bounce(), brushvert(), BIH::build(), ai::wpcache::build(), partrenderer::calc(), vertmodel::vertmesh::calcbb(), skelmodel::skelmesh::calcbb(), ragdolldata::calcboundsphere(), ImageData::calclevelsize(), calcmatbb(), calcmergedsize(), calcmodelpreviewpos(), calcpvsbounds(), game::calcradarscale(), calcscissorbox(), calcshadowmapbb(), calcskylight(), callcommand(), server::changemap(), rendertarget::checkblurtiles(), server::checkserversockets(), packetbuf::checkspace(), server::choosebestclient(), server::chooseworstteam(), clearlightcache(), clipminimap(), compressedformat(), computezoom(), conc(), shaftbb::contains(), cubemaploadwildcard(), pvsworker::cullpvs(), damagecompass(), game::deathstate(), server::dodamage(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), drawminimap(), drawreflection(), drawskybox(), gui::end(), endmodelbatches(), entpaste(), game::explode(), particleemitter::extendbb(), server::extinfoplayer(), server::extinfoteams(), depthfxtexture::eyedepth(), fastskylight(), gui::field_(), fillblendmap(), fireballrenderer::finddepthfxranges(), server::findmaprotation(), blobrenderer::findmaterials(), decalrenderer::findmaterials(), findmergedfaces(), fontskip(), game::gameplayhud(), gendds(), genedgespanvert(), generatealpha(), generategrass(), generatelightmap(), gengrassquads(), genlightmaptexs(), genmergedfaces(), genpoly(), genprefabmesh(), genpvs(), genpvsnodes(), vertmodel::vertmesh::genvbo(), skelmodel::skelmesh::genvbo(), getbackgroundres(), game::getbestteams(), gl_checkextensions(), gl_drawhud(), vector< facebounds >::growbuf(), texturegui::gui(), guispring(), gui::icon_(), PackNode::insert(), editor::insertallfrom(), invertblendmap(), isshadowmapreceiver(), gui::layout(), lightreaching(), listsplice(), md5::md5mesh::load(), makeparticles(), inexor::sound::mapsound(), vec2::max(), vec::max(), ivec::max(), ivec2::max(), mdlalphatest(), midedge(), mincubeface(), minskyface(), modifyoctaent(), modifyvelocity(), moveplatform(), mprotate(), game::newclient(), newmap(), noedit(), shaftbb::notinside(), databuf< T >::offset(), shaftbb::outside(), server::collectservermode::parsebases(), server::captureservermode::parsebases(), server::ctfservermode::parseflags(), game::parsemessages(), server::parsepacket(), server::bombservermode::parsespawnloc(), gui::poplist(), previewlightmapalpha(), filestream::printf(), ai::process(), server::processevents(), vec::projectxy(), pushscissor(), pushshadowmap(), pvsstats(), raycubeintersect(), rdlimitdist(), recorder::readbuffer(), regularflame(), regularshape(), vacollect::remapunlit(), renderbackground(), renderbatch(), renderblendbrush(), rendercube(), rendereditcursor(), renderentradius(), game::rendergame(), rendermodel(), renderpostfx(), renderprogress(), game::renderscoreboard(), renderwater(), resizetexture(), game::captureclientmode::respawnwait(), game::collectclientmode::respawnwait(), game::ctfclientmode::respawnwait(), inexor::util::random::rnd_raw(), server::rotatemap(), rotatenormals(), ai::route(), hmap::run(), game::saveragdoll(), shadowmaptexture::scissorblur(), rendertarget::scissorblur(), rendertarget::scissorrender(), fireballrenderer::seedemitter(), lightningrenderer::seedemitter(), varenderer< T >::seedemitter(), server::serverinforeply(), modelcommands< MDL, struct MDL::vertmesh >::setalphatest(), skelcommands< MDL >::setanim(), setbbfrommodel(), setblendmaporigin(), server::clientinfo::setpushed(), animmodel::skin::setshaderparams(), vacollect::setupdata(), setupsurface(), setupthreads(), shadowray(), shaftbb::shaftbb(), sortlist(), recorder::soundencoder(), gui::start(), sublist(), game::swayhudgun(), gui::tab(), tabify(), texagrad(), texdup(), texlayer(), texoffset(), texreorient(), texturedata(), game::timeupdate(), skelmodel::skelmeshgroup::totalframes(), BIH::traverse(), game::triggerplatform(), unionfind::unite(), game::updatebouncers(), updatefpshistory(), updatelightmap(), updateparticles(), game::updateprojectiles(), updateva(), uploadcompressedtexture(), uploadtexture(), vismatcmp(), ai::weapmindist(), server::welcomepacket(), and writeobj().
template<typename T > const T& inexor::rpc::max (const T & a, const inexor::rpc::SharedVar< T > & b)
References max().
template<typename T > const T& inexor::rpc::max (const inexor::rpc::SharedVar< T > & a, const inexor::rpc::SharedVar< T > & b)
Referenced by max().
template<typename T > const T& inexor::rpc::min (const inexor::rpc::SharedVar< T > & a, const T & b)
References min().
Referenced by aiman::addai(), fpsstate::addammo(), capturemode_common::baseinfo::addammo(), capturemode_common::addbase(), rendertarget::addblurtiles(), addcubeverts(), server::adddemo(), addgrasstri(), addnormals(), depthfxtexture::addscissorvert(), addskyverts(), blobrenderer::addtris(), addtris(), addvisibleva(), skelmodel::blendcombo::addweight(), alloclightmap(), skelmodel::skeleton::availgpubones(), avoidcollision(), gle::begin(), blendfog(), blendfogoverlay(), blitblendmap(), brushvert(), BIH::build(), ai::wpcache::build(), animmodel::part::calcanim(), skelmodel::skeleton::calcantipodes(), vertmodel::vertmesh::calcbb(), skelmodel::skelmesh::calcbb(), calcmatbb(), calcmergedsize(), calcpvsbounds(), calcscissorbox(), calcshadowmapbb(), rendertarget::checkblurtiles(), server::checkmaps(), ai::checkroute(), cleargui(), clearlightcache(), animmodel::meshgroup::clipframes(), clipminimap(), compactvslots(), complete(), computezoom(), consoleinput(), shaftbb::contains(), bigint< BI_DIGITS >::copydigits(), bigint< BI_DIGITS >::copyshrinkdigits(), copystring(), cubemaploadwildcard(), pvsworker::cullpvs(), rendertarget::debug(), decodeutf8(), capturemode_common::disttoenemy(), shadowmaptexture::dorender(), fogdome::draw(), drawconlines(), drawdamagecompass(), drawminimap(), drawskybox(), encodeutf8(), gui::end(), endmodelquery(), particleemitter::extendbb(), fastshader(), fillblendmap(), ai::find(), fireballrenderer::finddepthfxranges(), finishlightmap(), fixsurfaceformat(), gendynlightvariant(), genedgespanvert(), genenvmap(), genenvmaps(), generatealpha(), generatelightmap(), gengrassquads(), genlightmaptexs(), genpoly(), genpvsnodes(), vertmodel::vertmesh::genvbo(), skelmodel::skelmesh::genvbo(), databuf< T >::get(), get_current_max_fps(), utf8stream::getline(), ai::getsight(), ai::getweight(), game::gibeffect(), gl_drawframe(), gl_drawhud(), blobrenderer::init(), editor::insert(), game::ctfclientmode::interpflagpos(), interppos(), invertblendmap(), lightreaching(), obj::objmeshgroup::load(), load_world(), loadents(), Slot::loadthumbnail(), loadvslot(), make_file_packet(), makeparticles(), makerelpath(), mdlalphatest(), midedge(), vec2::min(), vec::min(), ivec::min(), ivec2::min(), mincubeface(), minskyface(), modifyblend(), ragdolldata::move(), moveplatform(), moveragdoll(), newtexture(), shaftbb::notinside(), databuf< T >::offset(), gzstream::open(), skelmodel::animcacheentry::operator==(), shaftbb::outside(), databuf< T >::pad(), server::captureservermode::parsebases(), particleinit(), game::particletrack(), pasteundoblock(), fpsstate::pickup(), inexor::sound::playsound(), prependstring(), previewlightmapalpha(), gui::previewslot(), vec::projectxy(), pushscissor(), databuf< T >::put(), raycube(), editline::read(), utf8stream::read(), gzstream::readbuf(), utf8stream::readbuf(), server::captureservermode::regenowners(), regularflame(), rendertarget::render(), renderbackground(), renderbatch(), renderblendbrush(), renderclient(), renderconsole(), rendereditcursor(), renderentarrow(), renderentradius(), game::ctfclientmode::rendergame(), game::rendergame(), rendergeom(), lightningrenderer::renderpart(), renderprogress(), rendertexturepanel(), renderwater(), renderwaterlod(), reorients3tc(), resizetexture(), resolverwait(), hmap::ripple(), inexor::util::random::rnd_raw(), rotatenormals(), hmap::run(), savetga(), shadowmaptexture::scissorblur(), rendertarget::scissorblur(), rendertarget::scissorrender(), inexor::rendering::screen::ScreenManager::screenres(), seedparticles(), gzstream::seek(), utf8stream::seek(), game::sendposition(), modelcommands< MDL, struct MDL::vertmesh >::setalphatest(), skelcommands< MDL >::setanim(), setblendmaporigin(), animmodel::animpos::setframes(), skelmodel::skelmesh::setshader(), server::setup_network_sockets(), vacollect::setupdata(), inexor::rendering::screen::ScreenManager::setupscreen(), setupsunlight(), setupsurface(), setuptexparameters(), setva(), Shader::setvariant_(), shaftbb::shaftbb(), game::shorten(), gzstream::skipbytes(), gui::spring(), gui::start(), server::startintermission(), game::swayhudgun(), texmad(), BIH::traverse(), game::triggerplatform(), ai::tryitem(), game::updatebouncers(), inexor::sound::updatechannel(), updatefpshistory(), game::updatemovables(), updateselection(), updateskystats(), updateva(), uploadcompressedtexture(), vismatcmp(), and writeobj().
template<typename T > const T& inexor::rpc::min (const T & a, const inexor::rpc::SharedVar< T > & b)
References min().
template<typename T > const T& inexor::rpc::min (const inexor::rpc::SharedVar< T > & a, const inexor::rpc::SharedVar< T > & b)
Referenced by min().
template<typename T > std::ostream& inexor::rpc::operator<< (std::ostream & os, const SharedVar< T > & x)
void inexor::rpc::send_all_vars ()
void inexor::rpc::set_on_change_functions ()
Referenced by inexor::rpc::RpcSubsystem< MSG_TYPE, ASYNC_SERVICE_TYPE >::initialize().
Variable Documentation
const std::unordered_map<int64, void *> inexor::rpc::cppvar_pointer_map
const std::unordered_map<int64, int> inexor::rpc::index_to_type_map