Inexor: game Namespace Reference
game Namespace Reference
implementation of basic game functionsand cubescript bindings
Classes
struct bombclientmode
struct captureclientmode
struct collectclientmode
struct ctfclientmode
struct clientmode
struct hideandseekclientmode
struct movable
struct projectile
struct bouncer
struct hudent
struct playermodelinfo
struct scoreboardgui
struct hitmsg
Enumerations
enum {
BOXWEIGHT = 25, BARRELHEALTH = 50, BARRELWEIGHT = 25, OBSTACLEHEALTH = 1,
PLATFORMWEIGHT = 1000, PLATFORMSPEED = 8, EXPLODEDELAY = 200
}
enum {
BNC_GRENADE, BNC_BOMB, BNC_SPLINTER, BNC_GIBS,
BNC_DEBRIS, BNC_BARRELDEBRIS
}
Functions
VARP (showbombs, 0, 1, 1)
VARP (showbombradius, 0, 1, 1)
VARP (showbombdelay, 0, 1, 1)
VARP (showminimapobstacles, 0, 1, 1)
VARP (capturetether, 0, 1, 1)
VARP (autorepammo, 0, 1, 1)
VARP (basenumbers, 0, 0, 1)
ICOMMAND (insidebases,"",(),{vector< char > buf;if(m_capture &&player1->state==CS_ALIVE) loopv(capturemode.bases){captureclientmode::baseinfo &b=capturemode.bases[i];if(b.valid()&&capturemode.insidebase(b, player1->feetpos())){if(buf.length()) buf.add(' ');defformatstring(basenum,"%d", i+1);buf.put(basenum, strlen(basenum));}}buf.add('\0');result(buf.getbuf());})
ICOMMAND (repammo,"",(), capturemode.replenishammo())
ICOMMAND (dropflag,"",(),{ctfmode.trydropflag();})
float calcradarscale ()
calculate required radar scale
void drawminimap (fpsent *d, float x, float y, float s)
draw rotated minimap
void setradartex ()
bind the minimap frame's texture
void drawradar (float x, float y, float s)
draw radar (a trangle square with matching texture coordinates to be precise) to target coordinates
void drawteammates (fpsent *d, float x, float y, float s)
draw all teamate arrow icons in minimap
void setbliptex (int team, const char *type)
set specific textures for teammates, skulls... on the minimap
void setclientmode ()
set game mode pointer
VARP (minradarscale, 0, 384, 10000)
minimap and radar
VARP (maxradarscale, 1, 1024, 10000)
VARP (radarteammates, 0, 1, 1)
FVARP (minimapalpha, 0, 1, 1)
void drawteammate (fpsent *d, float x, float y, float s, fpsent *o, float scale)
draw a specific teamate's icon arrow in minimap
VARP (deadpush, 1, 2, 20)
push dead bodies (?)
void switchname (const char *name, const char *tag)
team, name and playermodel settings
void printname ()
print my own nick name to the game console
ICOMMAND (name,"sN",(char *s, int *numargs),{if(*numargs > 0) switchname(s, nullptr);else if(!*numargs) printname();else result(colorname(player1));})
ICOMMAND (getname,"",(), result(player1->name))
ICOMMAND (tag,"sN",(char *s, int *numargs),{if(*numargs > 0) switchname("", s);else if(!*numargs) Log.std->info("your tag is: {0}", player1->tag);else result(player1->tag);})
ICOMMAND (gettag,"",(), result(player1->tag))
void switchteam (const char *team)
switch own team
void printteam ()
print own team name to the game console
ICOMMAND (team,"sN",(char *s, int *numargs),{if(*numargs > 0) switchteam(s);else if(!*numargs) printteam();else result(player1->team);})
switch team or print team name
ICOMMAND (getteam,"",(), result(player1->team))
cubescript implementation of getteam
void switchplayermodel (int playermodel)
switch my player model (inky, ogro..)
void sendmapinfo ()
set booleans sendcrc and senditemstoserver if connected.
void writeclientinfo (stream *f)
write my player name to a stream
bool allowedittoggle ()
check if editing is available
void edittoggled (bool on)
send edit toggle to server
const char * getclientname (int cn)
get nick name from cn
ICOMMAND (getclientname,"i",(int *cn), result(getclientname(*cn)))
const char * getclientteam (int cn)
get team name from cn
ICOMMAND (getclientteam,"i",(int *cn), result(getclientteam(*cn)))
int getclientmodel (int cn)
get client player model ID from cn
ICOMMAND (getclientmodel,"i",(int *cn), intret(getclientmodel(*cn)))
const char * getclienticon (int cn)
get client icon from cn depends on player model and spectator mode
ICOMMAND (getclienticon,"i",(int *cn), result(getclienticon(*cn)))
bool ismaster (int cn)
check if this client is a game master or administrator
ICOMMAND (ismaster,"i",(int *cn), intret(ismaster(*cn)?1:0))
bool isadmin (int cn)
check if this client is an administrator
ICOMMAND (isadmin,"i",(int *cn), intret(isadmin(*cn)?1:0))
ICOMMAND (getmastermode,"",(), intret(mastermode))
ICOMMAND (mastermodename,"i",(int *mm), result(mastermodename(*mm,"")))
bool isspectator (int cn)
ICOMMAND (isspectator,"i",(int *cn), intret(isspectator(*cn)?1:0))
bool isai (int cn, int type)
check if this cn is a bot (computer controlled player)
ICOMMAND (isai,"ii",(int *cn, int *type), intret(isai(*cn,*type)?1:0))
int parseplayer (const char *arg)
all functions can be called using client number or full name name should be case sensitive but the engine checks is both ways
ICOMMAND (getclientnum,"s",(char *name), intret(name[0]?parseplayer(name):player1->clientnum))
void listclients (bool local, bool bots)
return a list of players
ICOMMAND (listclients,"bb",(int *local, int *bots), listclients(*local >0,*bots!=0))
void clearbans ()
server administration
COMMAND (clearbans,"")
void setteam (const char *arg1, const char *arg2)
change a players team
COMMAND (setteam,"ss")
void kick (const char *victim, const char *reason)
request to kickban a player
COMMAND (kick,"ss")
void ignore (int cn)
ignore all chat messags from a certain client number
void unignore (int cn)
stop ignoring all chat messages from a certain client number
bool isignored (int cn)
cubescript: check if this person is ignored by you
ICOMMAND (ignore,"s",(char *arg), ignore(parseplayer(arg)))
ICOMMAND (unignore,"s",(char *arg), unignore(parseplayer(arg)))
ICOMMAND (isignored,"s",(char *arg), intret(isignored(parseplayer(arg))?1:0))
void hashpwd (const char *pwd)
hash setmaster password cn and sessionid are used to hash: servers do to store the hash value.
COMMAND (hashpwd,"s")
void setmaster (const char *arg, const char *who)
acquire game master or give game master to players
COMMAND (setmaster,"ss")
ICOMMAND (mastermode,"i",(int *val), addmsg(N_MASTERMODE,"ri",*val))
request to change server master mode (permissions requires)
void togglespectator (int val, const char *who)
toggle own spectator or put player into spectator (permissions requred)
ICOMMAND (spectator,"is",(int *val, char *who), togglespectator(*val, who))
ICOMMAND (checkmaps,"",(), addmsg(N_CHECKMAPS,"r"))
ask the server to acquire CRC32 checksum of all player's maps (permissions requred)
void changemapserv (const char *name, int mode)
force server to change map (permissions required)
void setmode (int mode)
force server to change game mode (permissions required)
ICOMMAND (mode,"i",(int *val), setmode(*val))
set game mode
ICOMMAND (getmode,"",(), intret(gamemode))
get game mode in cubescript
ICOMMAND (timeremaining,"i",(int *formatted),{int val=max(maplimit-lastmillis, 0)/1000;if(*formatted){defformatstring(str,"%d:%02d", val/60, val%60);result(str);}else intret(val);})
return remaining time
ICOMMANDS ("m_noitems","i",(int *mode),{int gamemode=*mode;intret(m_noitems);})
ICOMMANDS ("m_noammo","i",(int *mode),{int gamemode=*mode;intret(m_noammo);})
ICOMMANDS ("m_insta","i",(int *mode),{int gamemode=*mode;intret(m_insta);})
ICOMMANDS ("m_tactics","i",(int *mode),{int gamemode=*mode;intret(m_tactics);})
ICOMMANDS ("m_efficiency","i",(int *mode),{int gamemode=*mode;intret(m_efficiency);})
ICOMMANDS ("m_capture","i",(int *mode),{int gamemode=*mode;intret(m_capture);})
ICOMMANDS ("m_regencapture","i",(int *mode),{int gamemode=*mode;intret(m_regencapture);})
ICOMMANDS ("m_ctf","i",(int *mode),{int gamemode=*mode;intret(m_ctf);})
ICOMMANDS ("m_protect","i",(int *mode),{int gamemode=*mode;intret(m_protect);})
ICOMMANDS ("m_hold","i",(int *mode),{int gamemode=*mode;intret(m_hold);})
ICOMMANDS ("m_collect","i",(int *mode),{int gamemode=*mode;intret(m_collect);})
ICOMMANDS ("m_teammode","i",(int *mode),{int gamemode=*mode;intret(m_teammode);})
ICOMMANDS ("m_demo","i",(int *mode),{int gamemode=*mode;intret(m_demo);})
ICOMMANDS ("m_edit","i",(int *mode),{int gamemode=*mode;intret(m_edit);})
ICOMMANDS ("m_lobby","i",(int *mode),{int gamemode=*mode;intret(m_lobby);})
ICOMMANDS ("m_lms","i",(int *mode),{int gamemode=*mode;intret(m_lms);})
ICOMMANDS ("m_bomb","i",(int *mode),{int gamemode=*mode;intret(m_bomb);})
ICOMMANDS ("m_timeforward","i",(int *mode),{int gamemode=*mode;intret(m_timeforward);})
ICOMMANDS ("m_obstacles","i",(int *mode),{int gamemode=*mode;intret(m_obstacles);})
void changemap (const char *name, int mode)
request map change, server may ignore
void changemap (const char *name)
validates game mode name and calls changemap above
ICOMMAND (map,"s",(char *name), changemap(name))
void forceintermission ()
void forceedit (const char *name)
force edit mode
void newmap (int size)
request server to start new map (requires editmode)
void sendclipboard ()
send copied data from your clipboard to server
void edittrigger (const selinfo &sel, int op, int arg1, int arg2, int arg3, const VSlot *vs)
send edit messages to servers
void printvar (fpsent *d, ident *id)
print map var change commited by other players in edit mode
void vartrigger (ident *id)
change map vars in edit mode in multiplayer
void broadcastfov (int fov)
void pausegame (bool val)
pause game
ICOMMAND (pausegame,"i",(int *val), pausegame(*val > 0))
ICOMMAND (paused,"iN$",(int *val, int *numargs, ident *id),{if(*numargs > 0) pausegame(clampvar(id,*val, 0, 1) > 0);else if(*numargs< 0) intret(gamepaused?1:0);else printvar(id, gamepaused?1:0);})
cubescript: check if game is paused
bool ispaused ()
check if game is paused
void persistteams (bool val)
Set reshuffeling behaviour on mapchange according to bool val (true activates persistent teams)
ICOMMAND (persistteams,"i",(int *val), persistteams(*val > 0))
bool ispersisted ()
bool allowmouselook ()
check if looking around with the mouse is allowed.
void changegamespeed (int val)
change game speed (requires permissions)
ICOMMAND (gamespeed,"iN$",(int *val, int *numargs, ident *id),{if(*numargs > 0) changegamespeed(clampvar(id,*val, 10, 1000));else if(*numargs< 0) intret(gamespeed);else printvar(id, gamespeed);})
bool addmsg (int type, const char *fmt,...)
add network message
void connectattempt (const char *mapwish, int modewish, const char *password)
copy connection password (?)
void connectfail ()
reset connection password after connection failed
void gameconnect ()
?
void gamedisconnect (bool cleanup)
clean up local storage/vars after disconnect from server
void toserver (char *text)
send chat messages to server
COMMANDN (say, toserver,"C")
void sayteam (char *text)
send team messages to server
COMMAND (sayteam,"C")
void sayprivate (int i, char *text)
ICOMMAND (pm,"is",(int *i, char *text), sayprivate(*i, text))
ICOMMAND (servcmd,"C",(char *cmd), addmsg(N_SERVCMD,"rs", cmd))
send custom server messages to servers this feature is not used on most servers (?)
static void sendposition (fpsent *d, packetbuf &q)
network message parser
void sendposition (fpsent *d, bool reliable)
send my own player position to server (call function above)
void sendpositions ()
?
void sendmessages ()
?
void c2sinfo (bool force)
send update to the server
void sendintro ()
send N_CONNECT (with own name, serverpassword, playermodel and fov)
void updatepos (fpsent *d)
void parsepositions (ucharbuf &p)
void parsestate (fpsent *d, ucharbuf &p, bool resume=false)
void parsemessages (int cn, fpsent *d, ucharbuf &p)
void receivefile (packetbuf &p)
void parsepacketclient (int chan, packetbuf &p)
void getmap ()
COMMAND (getmap,"")
void stopdemo ()
COMMAND (stopdemo,"")
void recorddemo (int val)
ICOMMAND (recorddemo,"i",(int *val), recorddemo(*val))
void cleardemos (int val)
ICOMMAND (cleardemos,"i",(int *val), cleardemos(*val))
void getdemo (int i)
ICOMMAND (getdemo,"i",(int *val), getdemo(*val))
void listdemos ()
COMMAND (listdemos,"")
void sendmap ()
COMMAND (sendmap,"")
void gotoplayer (const char *arg)
COMMANDN (goto, gotoplayer,"s")
void gotosel ()
COMMAND (gotosel,"")
const char * savedconfig ()
const char * restoreconfig ()
const char * defaultconfig ()
const char * autoexec ()
const char * savedservers ()
void taunt ()
send taunt network animation message to server taunt animation is this "im gonna kill you" gesture that can be seen by other players
COMMAND (taunt,"")
ICOMMAND (getfollow,"",(),{fpsent *f=followingplayer();intret(f?f->clientnum:-1);})
cubescript: get the player I am following
void follow (char *arg)
follow a specific player if you are in spectator mode
COMMAND (follow,"s")
void nextfollow (int dir)
follow previous/next client number
ICOMMAND (nextfollow,"i",(int *dir), nextfollow(*dir< 0?-1:1))
const char * getclientmap ()
get client map name
void resetgamestate ()
reset game state in singleplayer reset all monsters, triggers, bouncers, movables, and projectiles
fpsent * spawnstate (fpsent *d)
reset player state not persistent accross spawns
void respawnself ()
Send "I would like to spawn" to server.
fpsent * pointatplayer ()
Give me the player I am aiming at.
void stopfollowing ()
stop spectating a specific player and start free camery fly
fpsent * followingplayer ()
Give me the fpsent instance of the player you are currently spectating.
int getfollowingfov ()
Receive the fov the currently followed player got or -1 on failure.
ICOMMAND (getfollowingfov,"",(), intret(getfollowingfov()))
fpsent * hudplayer ()
Give me the fpsent instance of the player whose coordinates will be used to calculate my camera's position.
void setupcamera ()
initialise camera when entering spectator mode
bool detachcamera ()
check if it is neccesary to detach the camera from first person view to third person view.
bool collidecamera ()
check if camera collision detection is neccesary
VARP (smoothmove, 0, 75, 100)
interpolation factor for player positions low smoothmove means jumpily player movement
VARP (smoothdist, 0, 32, 64)
distance in which interpolation will be applied (?)
void predictplayer (fpsent *d, bool move)
use latency and assume player movement to predict a player's new position.
void otherplayers (int curtime)
parse player state, move players, predict their position, handle ragdoll, check for lag
void updateworld ()
called in game loop to the update game world
void spawnplayer (fpsent *d)
spawn yourself im the game world, also called for monsters/AI in singleplayer of course not used for other players in multiplayer because everyone determins his spawn point for himself.
VARP (spawnwait, 0, 0, 1000)
void respawn (int gamemode=0)
spawn myself in SP and DMSP game mode (singleplayer only)
void doattack (bool on)
filter attack attempts not possible in intermission or if player's state is CS_DEAD
bool canjump ()
check if I am allowed to jump at the moment called every time before jump command is executed
bool allowmove (physent *d)
check if I am allowed to move
VARP (hitsound, 0, 0, 1)
void damaged (int damage, fpsent *d, fpsent *actor, bool local)
an fpsent (player/monster/bot) took damage
VARP (deathscore, 0, 1, 1)
void deathstate (fpsent *d, bool restore)
mark players as dead and update their state data
VARP (teamcolorfrags, 0, 1, 1)
highlight frags in team colors
void killed (fpsent *d, fpsent *actor)
this callback is called when player actor kills d prints death messages to all kind of consoles
void timeupdate (int secs)
update game session time display intermission statistics in console
ICOMMAND (getaccuracy,"",(), intret((player1->totaldamage *100)/max(player1->totalshots, 1)))
ICOMMAND (getdeaths,"",(), intret(player1->deaths))
ICOMMAND (getflags,"",(), intret(player1->flags))
ICOMMAND (getfrags,"",(), intret(player1->frags))
return a player's statistics to cubescript
ICOMMAND (getteamkills,"",(), intret(player1->teamkills))
ICOMMAND (gettotaldamage,"",(), intret(player1->totaldamage))
ICOMMAND (gettotalshots,"",(), intret(player1->totalshots))
fpsent * newclient (int cn)
ensure new client is a valid entity
fpsent * getclient (int cn)
access fpsent object safely using index
void clientdisconnected (int cn, bool notify)
notify my client to change data when another clients disconnect
void clearclients (bool notify)
delete all clients
void initclient ()
VARP (showmodeinfo, 0, 1, 1)
show game mode description text during map load
void startgame ()
clear all game data to start a new game
void startmap (const char *name)
called just after a map load send CRC32 to server
const char * getclientmode ()
void physicstrigger (physent *d, bool local, int floorlevel, int waterlevel, int material)
trigger sound effects depending on the material you enter
void dynentcollide (physent *d, physent *o, const vec &dir)
push monsters (or objects) together when they hit walls or other objects
void msgsound (int n, physent *d)
play sound and send sound notification to server
int numdynents ()
return the sum of dynamic entities currently in scene
dynent * iterdynents (int i)
iterate through all dynamic entities and return entity with index [i] You put the list in and get it through to return back The caller has to hand in a list which will get filled
VARP (teamcolortext, 0, 1, 1)
color team names in frag notifications in game console in red/blue, depending on my team
bool duplicatename (fpsent *d, const char *name=nullptr, const char *alt=nullptr)
are there any duplicate names in our client list? in case this is true, their client numbers will be displayed behind both nicknames
const char * colorname (fpsent *d, const char *name, const char *prefix, const char *alt)
add colored client number in [] brackets behind the name in case another player has the same name (duplicated name)
const char * teamcolorname (fpsent *d, const char *alt)
color name depending on my team in red or blue
const char * teamcolor (const char *name, bool sameteam, const char *alt)
color player name blue if you have the same team f1 otherwise red f3
const char * teamcolor (const char *name, const char *team, const char *alt)
this function calls the function above but also validates that team is a valid char pointer it is not possible to return memory to an invalid char* pointer!7
void suicide (physent *d)
suicide your player
ICOMMAND (suicide,"",(), suicide(player1))
bool needminimap ()
checks if minimap is required for this game mode
void drawicon (int icon, float x, float y, float sz)
draw (blit) item texture (weapon, flags, armours, quad) on screen at x,y
float abovegameplayhud (int w, int h)
calculate distance of hud from bottom of my screen depending on player state referenced only in gl_drawhud in render.cpp
ICOMMAND (ammohudup,"V",(tagval *args, int numargs),{loopi(3) ammohudup[i]=i< numargs?getweapon(args[i].getstr()):-1;})
those 3 functions are used to rotate in circles through your weapons so you see different preview images of the other weapons in your holsters
ICOMMAND (ammohuddown,"V",(tagval *args, int numargs),{loopi(3) ammohuddown[i]=i< numargs?getweapon(args[i].getstr()):-1;})
ICOMMAND (ammohudcycle,"V",(tagval *args, int numargs),{loopi(8) ammohudcycle[i]=i< numargs?getweapon(args[i].getstr()):-1;})
VARP (ammohud, 0, 1, 1)
decide if you want to display the little icons of your other weapons in the slot
void drawammohud (fpsent *d)
draw other weapons in weapon slots beside the icon of the currently selected weapon
void drawhudicons (fpsent *d)
draw health icon, armour icon and icon of selected gun other gun's preview icons are not included here
void drawhudannounce (int w, int h)
draw announcement for upcoming pickup entities in BOMBERMAN mode
void gameplayhud (int w, int h)
render game hud depending on hudplayer's state and "SPECTATOR" in spectator mode
int clipconsole (int w, int h)
VARP (teamcrosshair, 0, 1, 1)
use blue blocking crosshair when pointing at a teamate
VARP (hitcrosshair, 0, 425, 1000)
displaying a hit crosshair increases the players hit impression ('feel')
const char * defaultcrosshair (int index)
int selectcrosshair (vec &color)
switch crosshair depending on player state and player health
void lighteffects (dynent *e, vec &color, vec &dir)
void writegamedata (vector< char > &extras)
void readgamedata (vector< char > &extras)
bool clientoption (const char *arg)
void clearmovables ()
void triggerplatform (int tag, int newdir)
ICOMMAND (platform,"ii",(int *tag, int *newdir), triggerplatform(*tag,*newdir))
void stackmovable (movable *d, physent *o)
void updatemovables (int curtime)
void rendermovables ()
void suicidemovable (movable *m)
void hitmovable (int damage, movable *m, fpsent *at, const vec &vel, int gun)
bool isobstaclealive (movable *m)
void clearprojectiles ()
void renderprojectiles ()
void clearbouncers ()
void renderbouncers ()
void preloadbouncers ()
VARP (ragdoll, 0, 1, 1)
VARP (ragdollmillis, 0, 10000, 300000)
VARP (ragdollfade, 0, 1000, 300000)
VARFP (playermodel, 0, 0, 4, changedplayermodel())
VARP (forceplayermodels, 0, 0, 1)
VARP (hidedead, 0, 0, 1)
void saveragdoll (fpsent *d)
void clearragdolls ()
void moveragdolls ()
int chooserandomplayermodel (int seed)
const playermodelinfo * getplayermodelinfo (int n)
const playermodelinfo & getplayermodelinfo (fpsent *d)
void changedplayermodel ()
void preloadplayermodel ()
VAR (testquad, 0, 0, 1)
VAR (testarmour, 0, 0, 1)
VAR (testteam, 0, 0, 3)
void renderplayer (fpsent *d, const playermodelinfo &mdl, int team, float fade, bool mainpass)
VARP (teamskins, 0, 0, 1)
void rendergame (bool mainpass)
VARP (hudgun, 0, 1, 1)
VARP (hudgunsway, 0, 1, 1)
VARP (teamhudguns, 0, 1, 1)
VARP (chainsawhudgun, 0, 1, 1)
VAR (testhudgun, 0, 0, 1)
FVAR (swaystep, 1, 35.0f, 100)
FVAR (swayside, 0, 0.04f, 1)
FVAR (swayup,-1, 0.05f, 1)
void swayhudgun (int curtime)
SVARP (hudgunsdir,"")
void drawhudmodel (fpsent *d, int anim, float speed=0, int base=0)
void drawhudgun ()
void renderavatar ()
void renderplayerpreview (int model, int team, int weap)
vec hudgunorigin (int gun, const vec &from, const vec &to, fpsent *d)
void preloadweapons ()
void preloadsounds ()
void preload ()
VARP (scoreboard2d, 0, 1, 1)
VARP (showservinfo, 0, 1, 1)
VARP (showclientnum, 0, 0, 1)
VARP (showpj, 0, 0, 1)
VARP (showping, 0, 1, 1)
VARP (showspectators, 0, 1, 1)
VARP (showflags, 0, 0, 1)
VARP (showfrags, 0, 1, 1)
VARP (showaccuracy, 0, 1, 1)
VARP (highlightscore, 0, 1, 1)
VARP (showconnecting, 0, 0, 1)
void clearteaminfo ()
void setteaminfo (const char *team, int frags)
static bool playersort (const fpsent *a, const fpsent *b)
void getbestplayers (vector< fpsent * > &best)
void getbestteams (vector< const char * > &best)
static bool scoregroupcmp (const scoregroup *x, const scoregroup *y)
static int groupplayers ()
void renderscoreboard (g3d_gui &g, bool firstpass)
void g3d_gamemenus ()
VARFN (scoreboard, showscoreboard, 0, 0, 1, scoreboard.show(showscoreboard!=0))
void showscores (bool on)
ICOMMAND (showscores,"D",(int *down), showscores(*down!=0))
VARP (maxdebris, 10, 25, 1000)
VARP (maxbarreldebris, 5, 10, 1000)
ICOMMAND (getweapon,"",(), intret(player1->gunselect))
void gunselect (int gun, fpsent *d)
void nextweapon (int dir, bool force=false)
ICOMMAND (nextweapon,"ii",(int *dir, int *force), nextweapon(*dir,*force!=0))
int getweapon (const char *name)
void setweapon (const char *name, bool force=false)
ICOMMAND (setweapon,"si",(char *name, int *force), setweapon(name,*force!=0))
void cycleweapon (int numguns, int *guns, bool force=false)
ICOMMAND (cycleweapon,"V",(tagval *args, int numargs),{int numguns=min(numargs, 8);int guns[8];loopi(numguns) guns[i]=getweapon(args[i].getstr());cycleweapon(numguns, guns);})
void weaponswitch (fpsent *d)
ICOMMAND (weapon,"V",(tagval *args, int numargs),{if(player1->state!=CS_ALIVE) return;loopi(8){const char *name=i< numargs?args[i].getstr():"";if(name[0]){int gun=getweapon(name);if(gun >=GUN_FIST &&gun<=GUN_BOMB &&gun!=player1->gunselect &&player1->ammo[gun]){gunselect(gun, player1);return;}}else{weaponswitch(player1);return;}}playsound(S_NOAMMO);})
void offsetray (const vec &from, const vec &to, int spread, float range, vec &dest)
void createrays (int gun, const vec &from, const vec &to)
void newbouncer (const vec &from, const vec &to, bool local, int id, fpsent *owner, int type, int lifetime, int speed, entitylight *light=nullptr, int generation=0)
void bounced (physent *d, const vec &surface)
void spawnnextsplinter (const vec &p, const vec &vel, fpsent *d, int generation)
void spawnsplinters (const vec &p, fpsent *d)
void updatebouncers (int time)
void removebouncers (fpsent *owner)
void newprojectile (const vec &from, const vec &to, float speed, bool local, int id, fpsent *owner, int gun)
void removeprojectiles (fpsent *owner)
VARP (blood, 0, 1, 1)
void damageeffect (int damage, fpsent *d, bool thirdperson)
void spawnbouncer (const vec &p, const vec &vel, fpsent *d, int type, entitylight *light=nullptr)
void gibeffect (int damage, const vec &vel, fpsent *d)
void hit (int damage, dynent *d, fpsent *at, const vec &vel, int gun, float info1, int info2=1)
void hitpush (int damage, dynent *d, fpsent *at, vec &from, vec &to, int gun, int rays)
float projdist (dynent *o, vec &dir, const vec &v)
void radialeffect (dynent *o, const vec &v, int qdam, fpsent *at, int gun)
void radialbombeffect (bouncer *b, const vec &v)
void explode (bool local, fpsent *owner, const vec &v, dynent *safe, int damage, int gun)
void projsplash (projectile &p, vec &v, dynent *safe, int damage)
void explodeeffects (int gun, fpsent *d, bool local, int id)
bool projdamage (dynent *o, projectile &p, vec &v, int qdam)
void updateprojectiles (int time)
VARP (muzzleflash, 0, 1, 1)
VARP (muzzlelight, 0, 1, 1)
void shoteffects (int gun, const vec &from, const vec &to, fpsent *d, bool local, int id, int prevaction)
void particletrack (physent *owner, vec &o, vec &d)
void dynlighttrack (physent *owner, vec &o, vec &hud)
bool intersect (dynent *d, const vec &from, const vec &to, float &dist)
dynent * intersectclosest (const vec &from, const vec &to, fpsent *at, float &bestdist)
void shorten (vec &from, vec &target, float dist)
void raydamage (vec &from, vec &to, fpsent *d)
void shoot (fpsent *d, const vec &targ)
void adddynlights ()
VARP (bombcolliderad, 0, 16, 1000)
VARP (bombbarrier, 0, 1, 1)
void checkattacksound (fpsent *d, bool local)
void checkidlesound (fpsent *d, bool local)
void removeweapons (fpsent *d)
void updateweapons (int curtime)
bool weaponcollide (physent *d, const vec &dir)
void avoidweapons (ai::avoidset &obstacles, float radius)
Variables
bombclientmode bombmode
captureclientmode capturemode
ctfclientmode ctfmode
SharedVar< float > minimapalpha
clientmode * cmode = nullptr
gamemodes
SharedVar< int > showminimapobstacles
hideandseekclientmode hideandseekmode
collectclientmode collectmode
bool senditemstoserver = false
after a map change, since server doesn't have map data
bool sendcrc = false
int lastping = 0
bool connected = false
bool demoplayback = false
bool gamepaused = false
bool teamspersisted = false
int sessionid = 0
int mastermode = MM_OPEN
int gamespeed = 100
string servinfo = ""
string connectpass = ""
string connectmapwish = ""
int connectmodewish = -1
vector< int > ignores
a vector of ignored client numbers (cns)
int nextmode = INT_MAX
string clientmap = ""
int needclipboard = -1
?
vector< uchar > messages
collect client to server messages conveniently
int messagecn = -1
int messagereliable = false
SharedVar< int > deathscore
int paused
fpsent * player1 = nullptr
vector< fpsent * > players
our client
bool intermission = false
other clients
int maptime = 0
int maprealtime = 0
int maplimit = -1
int respawnent = -1
int lasthit = 0
int lastspawnattempt = 0
int following = -1
int followdir = 0
int savedammo [NUMGUNS]
vector< fpsent * > clients
other clients connected to this server
int ammohudup [3] = { GUN_CG, GUN_RL, GUN_GL }
this static data is used to describe the sorting of the 3 next weapons in your holster preview.
int ammohuddown [3] = { GUN_RIFLE, GUN_SG, GUN_PISTOL }
int ammohudcycle [8] = { -1, -1, -1, -1, -1, -1, -1, -1 }
SharedVar< int > smoothmove
SharedVar< int > smoothdist
vector< movable * > movables
vector< projectile > projs
vector< bouncer * > bouncers
vector< fpsent * > bestplayers
vector< const char * > bestteams
vector< fpsent * > ragdolls
static const playermodelinfo playermodels [2]
float swayfade = 0
float swayspeed = 0
float swaydist = 0
vec swaydir (0, 0, 0)
game::hudent guninterp
SharedVar< int > playermodel
SharedVar< int > teamskins
SharedVar< int > testteam
static hashset< teaminfo > teaminfos
static vector< scoregroup * > groups
static vector< fpsent * > spectators
game::scoreboardgui scoreboard
static const int MONSTERDAMAGEFACTOR = 4
static const int OFFSETMILLIS = 500
vec rays [MAXRAYS]
vector< hitmsg > hits
SharedVar< int > chainsawhudgun
float intersectdist = 1e16f
static const char *const projnames [3] = { "projectile/grenade", "projectile/rocket", "projectile/bomb" }
static const char *const gibnames [3] = { "particle/gibs/gib01", "particle/gibs/gib02", "particle/gibs/gib03" }
static const char *const debrisnames [4] = { "particle/debris/debris01", "particle/debris/debris02", "particle/debris/debris03", "particle/debris/debris04" }
Detailed Description
implementation of basic game functionsand cubescript bindings
Class Documentation
struct game::projectile
Class Members
vec dir
int gun
int id
entitylight light
bool local
vec o
vec offset
int offsetmillis
fpsent * owner
float speed
vec to
struct game::playermodelinfo
Class Members
const char * armour[3]
const char * blueicon
const char * blueteam
const char * ffa
const char * ffaicon
const char * hudguns
const char * quad
bool ragdoll
const char * redicon
const char * redteam
const char * vwep
struct game::hitmsg
Class Members
ivec dir
int info1
int info2
int lifesequence
int target
Enumeration Type Documentation
anonymous enum
Enumerator
BOXWEIGHT
BARRELHEALTH
BARRELWEIGHT
OBSTACLEHEALTH
PLATFORMWEIGHT
PLATFORMSPEED
EXPLODEDELAY
anonymous enum
Enumerator
BNC_GRENADE
BNC_BOMB
BNC_SPLINTER
BNC_GIBS
BNC_DEBRIS
BNC_BARRELDEBRIS
Function Documentation
float game::abovegameplayhud (int w, int h)
calculate distance of hud from bottom of my screen depending on player state referenced only in gl_drawhud in render.cpp
References CS_EDITING, CS_SPECTATOR, hudplayer(), and recorder::state.
Referenced by gl_drawhud().
void game::adddynlights ()
References vec::add(), adddynlight(), BNC_BOMB, BNC_GRENADE, bouncers, game::bouncer::bouncetype, f(), game::projectile::gun, GUN_RL, loopv, vec::mul(), game::projectile::o, physent::o, game::projectile::offset, game::bouncer::offset, game::projectile::offsetmillis, game::bouncer::offsetmillis, and OFFSETMILLIS.
Referenced by updatedynlights().
bool game::addmsg (int type, const char * fmt, ...)
add network message
References fpsent::clientnum, connected, hmap::d, fatal(), databuf< T >::length(), loopi(), MAXTRANS, messagecn, messagereliable, messages, msgsizelookup(), N_FROMAI, player1, vector< T, MINSIZE >::put(), putfloat(), putint(), and sendstring().
Referenced by broadcastfov(), changegamespeed(), changemap(), game::captureclientmode::checkitems(), game::collectclientmode::checkitems(), game::ctfclientmode::checkitems(), clearbans(), cleardemos(), entities::editent(), edittoggled(), edittrigger(), forceintermission(), getdemo(), getmap(), gunselect(), kick(), listdemos(), msgsound(), newmap(), parsemessages(), pausegame(), persistteams(), recorddemo(), game::captureclientmode::replenishammo(), respawnself(), sayprivate(), sayteam(), setmaster(), setteam(), shoot(), stopdemo(), suicide(), switchname(), switchplayermodel(), switchteam(), taunt(), ai::think(), togglespectator(), toserver(), game::ctfclientmode::trydropflag(), entities::trypickup(), updatebouncers(), updateprojectiles(), and vartrigger().
bool game::allowedittoggle ()
check if editing is available
References inexor::util::log_manager::edit, editmode, execute(), identexists(), isconnected(), Log, m_edit, and multiplayer().
Referenced by mapmodelreset(), materialreset(), setfvarchecked(), setsvarchecked(), setvarchecked(), texturereset(), and toggleedit().
bool game::allowmouselook ()
check if looking around with the mouse is allowed.
References gamepaused, and m_edit.
Referenced by mousemove().
bool game::allowmove (physent * d)
check if I am allowed to move
References ENT_PLAYER, lastmillis, and physent::type.
Referenced by ai::logic(), modifygravity(), modifyvelocity(), renderclient(), and trystepdown().
const char* game::autoexec () inline
Referenced by main(), and writecfg().
void game::avoidweapons (ai::avoidset & obstacles, float radius)
References ai::avoidset::avoidnear(), BNC_GRENADE, bouncers, game::bouncer::bouncetype, game::projectile::gun, GUN_GL, loopv, game::projectile::o, physent::o, and projs.
Referenced by ai::avoid().
void game::bounced (physent * d, const vec & surface)
References adddecal(), BNC_GIBS, game::bouncer::bounces, game::bouncer::bouncetype, DECAL_BLOOD, ENT_BOUNCE, physent::o, physent::radius, rnd(), vec::sub(), and physent::type.
Referenced by bounce().
void game::broadcastfov (int fov)
References addmsg(), fpsent::fov, N_FOV, and player1.
Referenced by broadcastfov().
void game::c2sinfo (bool force)
send update to the server
References flushclient(), sendmessages(), sendpositions(), and totalmillis.
Referenced by edittrigger(), and updateworld().
float game::calcradarscale ()
calculate required radar scale
References inexor::rpc::max(), and minimapradius.
Referenced by game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), drawminimap(), and drawteammates().
bool game::canjump ()
check if I am allowed to jump at the moment called every time before jump command is executed
See Also
respawn
References connected, CS_DEAD, gamemode, intermission, player1, respawn(), and physent::state.
void game::changedplayermodel ()
References cleanragdoll(), fpsent::clientnum, hmap::d, getplayermodelinfo(), loopv, player1, playermodel, fpsent::playermodel, players, dynent::ragdoll, and ragdolls.
void game::changegamespeed (int val)
change game speed (requires permissions)
References addmsg(), connected, and N_GAMESPEED.
void game::changemap (const char * name, int mode)
request map change, server may ignore
References addmsg(), connectserv(), isconnected(), and N_MAPVOTE.
void game::changemap (const char * name)
validates game mode name and calls changemap above
References m_valid, and nextmode.
Referenced by forceedit().
void game::changemapserv (const char * name, int mode)
force server to change map (permissions required)
See Also
startgame
References editmode, emptymap(), gamemode, load_world(), m_demo, m_edit, nextmode, entities::resetspawns(), senditemstoserver, startgame(), and toggleedit().
Referenced by parsemessages().
void game::checkattacksound (fpsent * d, bool local)
References fpsent::attackchan, fpsent::attacksound, chainsawhudgun, fpsent::clientnum, CS_ALIVE, GUN_FIST, fpsent::lastaction, fpsent::lastattackgun, lastmillis, NUMGUNS, physent::o, inexor::sound::playsound(), S_CHAINSAW_ATTACK, physent::state, and fpsent::stopattacksound().
Referenced by updateweapons().
void game::checkidlesound (fpsent * d, bool local)
References fpsent::attacksound, chainsawhudgun, fpsent::clientnum, CS_ALIVE, GUN_FIST, fpsstate::gunselect, fpsent::idlechan, fpsent::idlesound, physent::o, inexor::sound::playsound(), S_CHAINSAW_IDLE, inexor::sound::sound(), physent::state, and fpsent::stopidlesound().
Referenced by updateweapons().
int game::chooserandomplayermodel (int seed)
References playermodels.
Referenced by ai::init().
void game::clearbans ()
server administration
many server commands require administrative permissions clears server ban lists
See Also
addmsg
References addmsg(), and N_CLEARBANS.
void game::clearbouncers ()
References bouncers.
Referenced by resetgamestate(), and startgame().
void game::clearclients (bool notify)
delete all clients
See Also
disconnect
References clientdisconnected(), clients, and loopv.
Referenced by gamedisconnect(), and parsemessages().
void game::cleardemos (int val)
References addmsg(), N_CLEARDEMOS, player1, PRIV_MASTER, and fpsent::privilege.
void game::clearmovables ()
References BARREL, BOX, cleardynentcache(), ELEVATOR, entinmap(), entities::ents, physent::eyeheight, loopv, m_obstacles, movables, entity::o, physent::o, OBSTACLE, PHYS_FLOOR, physent::physstate, PLATFORM, physent::resetinterp(), entity::type, and updatedynentcache().
Referenced by resetgamestate(), and startgame().
void game::clearprojectiles ()
References vector< T, MINSIZE >::shrink().
Referenced by resetgamestate(), and startgame().
void game::clearragdolls ()
References vector< T, MINSIZE >::deletecontents(), and ragdolls.
Referenced by startgame().
void game::clearteaminfo ()
References teaminfos.
Referenced by startgame().
void game::clientdisconnected (int cn, bool notify)
notify my client to change data when another clients disconnect
remove client number from ingore list
References cleardynentcache(), clients, cmode, COL_GREY, COL_WHITE, colorname(), hmap::d, DELETEP, followdir, following, inexor::util::log_manager::game, vector< T, MINSIZE >::inrange(), Log, fpsent::name, nextfollow(), players, vector< T, MINSIZE >::removeobj(), game::clientmode::removeplayer(), removetrackeddynlights(), removetrackedparticles(), removeweapons(), stopfollowing(), and unignore().
Referenced by clearclients(), and parsemessages().
bool game::clientoption (const char * arg)
int game::clipconsole (int w, int h)
References game::clientmode::clipconsole(), and cmode.
Referenced by renderconsole().
bool game::collidecamera ()
check if camera collision detection is neccesary
See Also
followingplayer
References CS_EDITING, CS_SPECTATOR, followingplayer(), player1, and physent::state.
Referenced by recomputecamera().
const char * game::colorname (fpsent * d, const char * name, const char * prefix, const char * alt)
add colored client number in [] brackets behind the name in case another player has the same name (duplicated name)
Warning
not safe.
resets color to white afterwards!
See Also
duplicatename
References AI_NONE, COL_MAGENTA, COL_WHITE, duplicatename(), fpsent::name, player1, and tempformatstring().
Referenced by clientdisconnected(), gameplayhud(), ai::init(), killed(), parsemessages(), printname(), printvar(), ai::render(), rendergame(), renderscoreboard(), sayprivate(), sayteam(), teamcolorname(), and toserver().
game::COMMAND (taunt , "")
game::COMMAND (follow , "s")
game::COMMAND (clearbans , "")
game::COMMAND (setteam , "ss")
game::COMMAND (kick , "ss")
game::COMMAND (hashpwd , "s")
game::COMMAND (setmaster , "ss")
game::COMMAND (sayteam , "C")
game::COMMAND (getmap , "")
game::COMMAND (stopdemo , "")
game::COMMAND (listdemos , "")
game::COMMAND (sendmap , "")
game::COMMAND (gotosel , "")
game::COMMANDN (say , toserver , "C")
game::COMMANDN (goto , gotoplayer , "s")
void game::connectattempt (const char * mapwish, int modewish, const char * password)
copy connection password (?)
References connectmapwish, connectmodewish, connectpass, and copystring().
Referenced by connectserv().
void game::connectfail ()
reset connection password after connection failed
References connectmapwish, connectmodewish, connectpass, m_valid, and nextmode.
Referenced by abortconnect().
void game::createrays (int gun, const vec & from, const vec & to)
References loopi(), offsetray(), and rays.
Referenced by shoot(), and shoteffects().
void game::cycleweapon (int numguns, int * guns, bool force = false)
References fpsstate::ammo, CS_ALIVE, fpsstate::gunselect, gunselect(), loopi(), NUMGUNS, player1, inexor::sound::playsound(), S_NOAMMO, and recorder::state.
void game::damaged (int damage, fpsent * d, fpsent * actor, bool local)
an fpsent (player/monster/bot) took damage
See Also
damageeffect
References CS_ALIVE, CS_LAGGED, CS_SPAWNING, damageblend(), damagecompass(), ai::damaged(), damageeffect(), fpsstate::dodamage(), fpsstate::health, hudplayer(), intermission, killed(), lasthit, lastmillis, physent::o, player1, inexor::sound::playsound(), rnd(), S_HIT, S_PAIN1, S_PAIN6, and physent::state.
void game::damageeffect (int damage, fpsent * d, bool thirdperson)
References physent::aboveeye, physent::abovehead(), defformatstring, physent::eyeheight, f(), physent::o, PART_BLOOD, PART_TEXT, particle_splash(), and particle_textcopy().
Referenced by damaged(), and hit().
void game::deathstate (fpsent * d, bool restore)
mark players as dead and update their state data
play a random death sound
play a random death sound
References fpsstate::ammo, fpsent::attacking, CS_DEAD, fpsent::deaths, deathscore, disablezoom(), gibeffect(), fpsstate::health, lastmillis, fpsent::lastpain, loopi(), inexor::rpc::max(), physent::move, NUMGUNS, physent::o, player1, inexor::sound::playsound(), physent::resetinterp(), rnd(), physent::roll, S_DIE1, savedammo, showscores(), fpsent::smoothmillis, physent::state, physent::strafe, and physent::vel.
Referenced by edittoggled(), killed(), and parsemessages().
const char* game::defaultconfig () inline
Referenced by main(), and writecfg().
const char * game::defaultcrosshair (int index)
Referenced by loadcrosshair().
bool game::detachcamera ()
check if it is neccesary to detach the camera from first person view to third person view.
this is mostly triggered by player death
See Also
hudplayer
References CS_DEAD, hmap::d, hudplayer(), and physent::state.
Referenced by recomputecamera().
void game::doattack (bool on)
filter attack attempts not possible in intermission or if player's state is CS_DEAD
References fpsent::attacking, connected, gamemode, intermission, player1, and respawn().
void game::drawammohud (fpsent * d)
draw other weapons in weapon slots beside the icon of the currently selected weapon
References ammohudup, drawicon(), f(), flushhudmatrix(), GUN_BOMB, HICON_FIST, HICON_SIZE, HICON_STEP, HICON_X, HICON_Y, hudmatrix, loopi(), pophudmatrix(), pushhudmatrix(), and matrix4::scale().
Referenced by drawhudicons().
void game::drawhudannounce (int w, int h)
draw announcement for upcoming pickup entities in BOMBERMAN mode
References draw_text(), E_STATIC_BOTTOM, E_STATIC_CENTER, E_STATIC_LEFT, E_STATIC_RIGHT, E_STATIC_TOP, E_ZOOM_IN, E_ZOOM_OUT, hudannounce_begin, hudannounce_effect, hudannounce_text, hudannounce_timeout, text_bounds(), and totalmillis.
Referenced by gameplayhud().
void game::drawhudgun ()
References ANIM_GUN_IDLE, ANIM_GUN_SHOOT, ANIM_LOOP, ANIM_SETSPEED, guninfo::attackdelay, CS_EDITING, CS_SPECTATOR, hmap::d, drawhudmodel(), editmode, f(), guns, fpsstate::gunselect, hudplayer(), fpsent::lastaction, fpsent::lastattackgun, lastmillis, fpsent::muzzle, player1, and physent::state.
Referenced by renderavatar().
void game::drawhudicons (fpsent * d)
draw health icon, armour icon and icon of selected gun other gun's preview icons are not included here
References fpsstate::ammo, fpsstate::armour, fpsstate::armourtype, CS_DEAD, draw_textf(), drawammohud(), drawicon(), flushhudmatrix(), fpsstate::gunselect, fpsstate::health, HICON_BLUE_ARMOUR, HICON_FIST, HICON_HEALTH, HICON_QUAD, HICON_SIZE, HICON_SPACE, HICON_STEP, HICON_TEXTY, HICON_X, HICON_Y, hudmatrix, pophudmatrix(), pushhudmatrix(), fpsstate::quadmillis, matrix4::scale(), and physent::state.
Referenced by gameplayhud().
void game::drawhudmodel (fpsent * d, int anim, float speed = 0, int base = 0)
References vec::add(), ANIM_LOOP, calcavatarpos(), chainsawhudgun, gle::color(), concatstring(), CS_DEAD, defformatstring, f(), guninfo::file, getplayermodelinfo(), GUN_BOMB, GUN_FIST, guninterp, guns, fpsstate::gunselect, game::playermodelinfo::hudguns, isteam, lastmillis, m_teammode, MDL_HUD, MDL_LIGHT, vec::mul(), fpsent::muzzle, physent::o, physent::pitch, player1, fpsstate::quadmillis, rendermodel(), physent::state, swaydir, swaydist, anonymous_namespace{utilTest.cpp}::t(), fpsent::team, teamskins, testteam, vecfromyawpitch(), and physent::yaw.
Referenced by drawhudgun().
void game::drawicon (int icon, float x, float y, float sz)
draw (blit) item texture (weapon, flags, armours, quad) on screen at x,y
References gle::begin(), bind_items_texture(), and gle::end().
Referenced by drawammohud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and drawhudicons().
void game::drawminimap (fpsent * d, float x, float y, float s)
draw rotated minimap
See Also
calcradarscale
References vec::add(), gle::begin(), calcradarscale(), camera1, dir, gle::end(), f(), loopi(), minimapcenter, minimapscale, vec::mul(), physent::o, vec::rotate_around_z(), vec::sub(), vecfromyawpitch(), and physent::yaw.
Referenced by game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and game::captureclientmode::drawhud().
void game::drawradar (float x, float y, float s)
draw radar (a trangle square with matching texture coordinates to be precise) to target coordinates
References gle::begin(), and gle::end().
Referenced by game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and game::captureclientmode::drawhud().
void game::drawteammate (fpsent * d, float x, float y, float s, fpsent * o, float scale)
draw a specific teamate's icon arrow in minimap
References camera1, dir, vec::div(), f(), vec::magnitude2(), vec::mul(), physent::o, RAD, vec::rotate_around_z(), vec::sub(), and physent::yaw.
Referenced by drawteammates().
void game::drawteammates (fpsent * d, float x, float y, float s)
draw all teamate arrow icons in minimap
References gle::begin(), calcradarscale(), CS_ALIVE, CS_DEAD, drawteammate(), gle::end(), isteam, loopv, players, setbliptex(), physent::state, fpsent::team, and TEAM_OWN.
Referenced by game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and game::captureclientmode::drawhud().
bool game::duplicatename (fpsent * d, const char * name = nullptr, const char * alt = nullptr)
are there any duplicate names in our client list? in case this is true, their client numbers will be displayed behind both nicknames
References loopv, fpsent::name, player1, and players.
Referenced by colorname().
void game::dynentcollide (physent * d, physent * o, const vec & dir)
push monsters (or objects) together when they hit walls or other objects
References ENT_INANIMATE, stackmovable(), and physent::type.
Referenced by plcollide().
void game::dynlighttrack (physent * owner, vec & o, vec & hud)
References vec::add(), ENT_AI, ENT_PLAYER, fpsstate::gunselect, hudplayer(), fpsent::lastattackgun, fpsent::muzzle, physent::o, and physent::type.
Referenced by updatedynlights().
void game::edittoggled (bool on)
send edit toggle to server
See Also
addmsg
deathstate
References addmsg(), CS_DEAD, CS_EDITING, deathstate(), disablezoom(), physent::editstate, N_EDITMODE, player1, fpsent::respawned, showscores(), physent::state, and fpsent::suicided.
Referenced by toggleedit().
void game::edittrigger (const selinfo & sel, int op, int arg1, int arg2, int arg3, const VSlot * vs)
send edit messages to servers
References addmsg(), c2sinfo(), selinfo::corner, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, EDIT_COPY, EDIT_DELCUBE, EDIT_FACE, EDIT_FLIP, EDIT_MAT, EDIT_PASTE, EDIT_REDO, EDIT_REMIP, EDIT_REPLACE, EDIT_ROTATE, EDIT_TEX, EDIT_UNDO, EDIT_VSLOT, selinfo::grid, vector< T, MINSIZE >::length(), lilswap(), m_edit, messages, N_EDITF, needclipboard, selinfo::o, selinfo::orient, packundo(), packvslot(), vector< T, MINSIZE >::pad(), vector< T, MINSIZE >::put(), selinfo::s, sendclipboard(), and shouldpacktex().
Referenced by mpcopy(), mpdelcube(), mpeditface(), mpeditmat(), mpedittex(), mpeditvslot(), mpflip(), mppaste(), mpremip(), mpreplacetex(), mprotate(), and swapundo().
void game::explode (bool local, fpsent * owner, const vec & v, dynent * safe, int damage, int gun)
References vec::add(), adddynlight(), fpsstate::ammo, BNC_BARRELDEBRIS, BNC_DEBRIS, bouncers, entitylight::color, entitylight::dir, f(), GUN_BARREL, GUN_BOMB, GUN_GL, GUN_RL, GUN_SPLINTER, itemstats, iterdynents(), lightreaching(), loopi(), m_bomb, m_obstacles, itemstat::max, inexor::rpc::max(), numdynents(), physent::o, PART_EXPLOSION, PART_EXPLOSION_BLUE, PART_SPARK, particle_fireball(), particle_splash(), inexor::sound::playsound(), radialbombeffect(), radialeffect(), physent::radius, vec::reject(), rnd(), S_FEXPLODE, S_RLHIT, and spawnbouncer().
Referenced by game::movable::explode(), explodeeffects(), projsplash(), and updatebouncers().
void game::explodeeffects (int gun, fpsent * d, bool local, int id)
References vec::add(), adddecal(), BNC_BOMB, BNC_GRENADE, BNC_SPLINTER, bouncers, game::bouncer::bouncetype, DECAL_SCORCH, game::projectile::dir, explode(), game::bouncer::generation, game::projectile::gun, GUN_BOMB, GUN_GL, GUN_RL, GUN_SPLINTER, game::projectile::id, game::bouncer::id, game::projectile::local, game::bouncer::local, loopv, vec::mul(), vec::neg(), game::projectile::o, physent::o, game::projectile::offset, game::bouncer::offset, game::projectile::offsetmillis, game::bouncer::offsetmillis, OFFSETMILLIS, game::projectile::owner, game::bouncer::owner, vector< T, MINSIZE >::remove(), spawnnextsplinter(), spawnsplinters(), and physent::vel.
Referenced by parsemessages().
void game::follow (char * arg)
follow a specific player if you are in spectator mode
Parameters
arg either the player's name or his client number
See Also
parseplayer
References fpsent::clientnum, CS_SPECTATOR, followdir, following, Log, parseplayer(), player1, physent::state, and inexor::util::log_manager::std.
fpsent * game::followingplayer ()
Give me the fpsent instance of the player you are currently spectating.
References CS_SPECTATOR, following, getclient(), player1, physent::state, and ai::target().
Referenced by collidecamera(), gameplayhud(), getfollowingfov(), hudplayer(), killed(), rendergame(), setupcamera(), and updateweapons().
void game::forceedit (const char * name)
force edit mode
References changemap().
Referenced by newmap().
void game::forceintermission ()
References addmsg(), and N_FORCEINTERMISSION.
game::FVAR (swaystep , 1 , 35. 0f, 100)
game::FVAR (swayside , 0 , 0. 04f, 1)
game::FVAR (swayup , - 1, 0. 05f, 1)
game::FVARP (minimapalpha , 0 , 1 , 1)
void game::g3d_gamemenus ()
References game::scoreboardgui::render(), and scoreboard.
Referenced by g3d_render().
void game::gameconnect ()
?
References editmode, and toggleedit().
Referenced by gets2c().
void game::gamedisconnect (bool cleanup)
clean up local storage/vars after disconnect from server
References clearclients(), clientmap, fpsent::clientnum, connected, CS_ALIVE, demoplayback, gamemode, gamepaused, gamespeed, ignores, fpsent::lifesequence, mastermode, messagecn, messagereliable, messages, MM_OPEN, nextmode, player1, PRIV_NONE, fpsent::privilege, fpsent::respawn(), sendcrc, senditemstoserver, sessionid, vector< T, MINSIZE >::setsize(), physent::state, and stopfollowing().
Referenced by disconnect().
void game::gameplayhud (int w, int h)
render game hud depending on hudplayer's state and "SPECTATOR" in spectator mode
References cmode, gle::color(), colorname(), CS_DEAD, CS_EDITING, CS_SPECTATOR, hmap::d, draw_text(), game::clientmode::drawhud(), drawhudannounce(), drawhudicons(), f(), flushhudmatrix(), followingplayer(), hudmatrix, hudplayer(), inexor::rpc::max(), player1, pophudmatrix(), PRIV_ADMIN, fpsent::privilege, pushhudmatrix(), matrix4::scale(), physent::state, and text_bounds().
Referenced by gl_drawhud().
void game::getbestplayers (vector< fpsent * > & best)
References vector< T, MINSIZE >::add(), CS_SPECTATOR, vector< T, MINSIZE >::drop(), fpsent::frags, vector< T, MINSIZE >::last(), vector< T, MINSIZE >::length(), loopv, players, playersort(), vector< T, MINSIZE >::sort(), and physent::state.
Referenced by rendergame().
void game::getbestteams (vector< const char * > & best)
References vector< T, MINSIZE >::add(), cmode, teamscore::compare(), CS_SPECTATOR, vector< T, MINSIZE >::drop(), enumerate, game::clientmode::getteamscores(), game::clientmode::hidefrags(), vector< T, MINSIZE >::htfind(), vector< T, MINSIZE >::last(), vector< T, MINSIZE >::length(), loopv, inexor::rpc::max(), players, teamscore::score, vector< T, MINSIZE >::sort(), physent::state, anonymous_namespace{utilTest.cpp}::t(), fpsent::team, and teaminfos.
Referenced by rendergame().
fpsent * game::getclient (int cn)
access fpsent object safely using index
Returns
NULL if index is invalid
References fpsent::clientnum, clients, vector< T, MINSIZE >::inrange(), and player1.
Referenced by game::ctfclientmode::aifind(), ai::damaged(), ai::dodefend(), ai::dopursue(), followingplayer(), getclienticon(), getclientmodel(), getclientname(), getclientteam(), gotoplayer(), ignore(), isadmin(), isai(), ismaster(), isspectator(), game::captureclientmode::parse_network_message(), parsemessages(), parsepositions(), ai::process(), ai::render(), renderscoreboard(), ai::request(), and unignore().
const char* game::getclienticon (int cn)
get client icon from cn depends on player model and spectator mode
See Also
getplayermodelinfo
References game::playermodelinfo::blueicon, CS_SPECTATOR, hmap::d, game::playermodelinfo::ffaicon, getclient(), getplayermodelinfo(), isteam, m_teammode, player1, game::playermodelinfo::redicon, physent::state, and fpsent::team.
const char * game::getclientmap ()
get client map name
References clientmap.
Referenced by dumplms(), ai::getwaypointfile(), mapcfgname(), mapname(), receivefile(), renderscoreboard(), save_world(), savecurrentmap(), screenshot(), and sendmessages().
const char * game::getclientmode ()
References gamemode, and modename().
Referenced by screenshot().
int game::getclientmodel (int cn)
get client player model ID from cn
References hmap::d, getclient(), and fpsent::playermodel.
const char* game::getclientname (int cn)
get nick name from cn
Parameters
cn client number
References hmap::d, getclient(), and fpsent::name.
const char* game::getclientteam (int cn)
get team name from cn
References hmap::d, getclient(), and fpsent::team.
void game::getdemo (int i)
References addmsg(), Log, N_GETDEMO, and inexor::util::log_manager::std.
int game::getfollowingfov ()
Receive the fov the currently followed player got or -1 on failure.
References hmap::d, followingplayer(), and fpsent::fov.
Referenced by computezoom().
void game::getmap ()
References addmsg(), inexor::util::log_manager::edit, Log, m_edit, and N_GETMAP.
const playermodelinfo* game::getplayermodelinfo (int n)
References playermodels.
Referenced by getclienticon(), and renderscoreboard().
const playermodelinfo & game::getplayermodelinfo (fpsent * d)
References player1, playermodel, and fpsent::playermodel.
Referenced by changedplayermodel(), drawhudmodel(), preloadplayermodel(), preloadweapons(), rendergame(), and renderplayerpreview().
int game::getweapon (const char * name)
References loopi(), and parseint().
Referenced by setweapon().
void game::gibeffect (int damage, const vec & vel, fpsent * d)
References physent::abovehead(), BNC_GIBS, loopi(), inexor::rpc::min(), and spawnbouncer().
Referenced by deathstate().
void game::gotoplayer (const char * arg)
References vec::add(), CS_EDITING, CS_SPECTATOR, hmap::d, dir, getclient(), vec::mul(), physent::o, parseplayer(), physent::pitch, player1, physent::resetinterp(), physent::state, vecfromyawpitch(), and physent::yaw.
void game::gotosel ()
References vec::add(), CS_EDITING, dir, getselpos(), vec::mul(), physent::o, physent::pitch, player1, physent::resetinterp(), physent::state, vecfromyawpitch(), and physent::yaw.
static int game::groupplayers () static
References vector< T, MINSIZE >::add(), cmode, CS_SPECTATOR, teaminfo::frags, game::clientmode::getteamscore(), groups, game::clientmode::hidefrags(), loopi(), loopj, loopv, m_teammode, fpsent::name, players, scoregroup::players, playersort(), teamscore::score, scoregroupcmp(), vector< T, MINSIZE >::setsize(), vector< T, MINSIZE >::sort(), spectators, physent::state, fpsent::team, teamscore::team, and teaminfos.
Referenced by renderscoreboard().
void game::gunselect (int gun, fpsent * d)
References addmsg(), fpsstate::gunselect, N_GUNSELECT, physent::o, inexor::sound::playsound(), and S_WEAPLOAD.
Referenced by cycleweapon(), nextweapon(), server::parsepacket(), ai::request(), setweapon(), and weaponswitch().
void game::hashpwd (const char * pwd)
hash setmaster password cn and sessionid are used to hash: servers do to store the hash value.
References fpsent::clientnum, tiger::hash(), hashpassword(), player1, result(), and sessionid.
void game::hit (int damage, dynent * d, fpsent * at, const vec & vel, int gun, float info1, int info2 = 1)
References fpsent::clientnum, damageblend(), damagecompass(), damageeffect(), game::hitmsg::dir, DMF, DNF, ENT_AI, ENT_INANIMATE, ENT_PLAYER, f(), hitmovable(), fpsent::hitpush(), hits, game::hitmsg::info1, game::hitmsg::info2, isteam, lasthit, lastmillis, fpsent::lastpain, fpsent::lifesequence, game::hitmsg::lifesequence, physent::o, player1, inexor::sound::playsound(), rnd(), S_HIT, S_PAIN1, S_PAIN6, game::hitmsg::target, fpsent::team, fpsent::totaldamage, and physent::type.
Referenced by gui::button_(), calcskylight(), mpr::collide(), fastskylight(), gui::field_(), hitpush(), gui::layout(), gui::modelpreview(), server::parsepacket(), gui::playerpreview(), gui::prefabpreview(), projdamage(), radialeffect(), gui::slider(), and gui::tab().
void game::hitmovable (int damage, movable * m, fpsent * at, const vec & vel, int gun)
References game::movable::damaged(), and game::movable::hitpush().
Referenced by hit().
void game::hitpush (int damage, dynent * d, fpsent * at, vec & from, vec & to, int gun, int rays)
References vec::dist(), hit(), and rays.
Referenced by server::dodamage(), and raydamage().
vec game::hudgunorigin (int gun, const vec & from, const vec & to, fpsent * d)
References physent::aboveeye, vec::add(), camright, camup, ENT_AI, physent::eyeheight, f(), hudplayer(), isthirdperson(), vec::mul(), fpsent::muzzle, physent::pitch, physent::radius, vec::sub(), physent::type, vecfromyawpitch(), and physent::yaw.
Referenced by newbouncer(), newprojectile(), and shoteffects().
fpsent * game::hudplayer ()
Give me the fpsent instance of the player whose coordinates will be used to calculate my camera's position.
See Also
followingplayer
References followingplayer(), player1, ai::target(), and thirdperson.
Referenced by abovegameplayhud(), damaged(), detachcamera(), drawhudgun(), dynlighttrack(), gameplayhud(), hudgunorigin(), newbouncer(), game::collectclientmode::rendergame(), selectcrosshair(), shoteffects(), and swayhudgun().
game::ICOMMAND (insidebases , "" , () , {vector< char > buf;if(m_capture &&player1->state==CS_ALIVE) loopv(capturemode.bases){captureclientmode::baseinfo &b=capturemode.bases[i];if(b.valid()&&capturemode.insidebase(b, player1->feetpos())){if(buf.length()) buf.add(' ');defformatstring(basenum,"%d", i+1);buf.put(basenum, strlen(basenum));}}buf.add('\0');result(buf.getbuf());})
game::ICOMMAND (repammo , "" , () , capturemode. replenishammo())
game::ICOMMAND (getweapon , "" , () , intret(player1->gunselect))
game::ICOMMAND (getfollow , "" , () , {fpsent *f=followingplayer();intret(f?f->clientnum:-1);})
cubescript: get the player I am following
game::ICOMMAND (nextweapon , "ii" , (int *dir, int *force) , nextweapon *,*!= 0force)
game::ICOMMAND (setweapon , "si" , (char *name, int *force) , setweapon(name,*force!=0))
game::ICOMMAND (cycleweapon , "V" , (tagval *args, int numargs) , {int numguns=min(numargs, 8);int guns[8];loopi(numguns) guns[i]=getweapon(args[i].getstr());cycleweapon(numguns, guns);})
game::ICOMMAND (nextfollow , "i" , (int *dir) , nextfollow *< 0?-1:1dir)
game::ICOMMAND (weapon , "V" , (tagval *args, int numargs) , {if(player1->state!=CS_ALIVE) return;loopi(8){const char *name=i< numargs?args[i].getstr():"";if(name[0]){int gun=getweapon(name);if(gun >=GUN_FIST &&gun<=GUN_BOMB &&gun!=player1->gunselect &&player1->ammo[gun]){gunselect(gun, player1);return;}}else{weaponswitch(player1);return;}}playsound(S_NOAMMO);})
game::ICOMMAND (platform , "ii" , (int *tag, int *newdir) , triggerplatform *,* newdir)
game::ICOMMAND (getfollowingfov , "" , () , intret(getfollowingfov()))
game::ICOMMAND (name , "sN" , (char *s, int *numargs) , {if(*numargs > 0) switchname(s, nullptr);else if(!*numargs) printname();else result(colorname(player1));})
game::ICOMMAND (getname , "" , () , result(player1->name))
game::ICOMMAND (tag , "sN" , (char *s, int *numargs) , {if(*numargs > 0) switchname("", s);else if(!*numargs) Log.std->info("your tag is: {0}", player1->tag);else result(player1->tag);})
game::ICOMMAND (gettag , "" , () , result(player1->tag))
game::ICOMMAND (team , "sN" , (char *s, int *numargs) , {if(*numargs > 0) switchteam(s);else if(!*numargs) printteam();else result(player1->team);})
switch team or print team name
game::ICOMMAND (getteam , "" , () , result(player1->team))
cubescript implementation of getteam
game::ICOMMAND (getclientname , "i" , (int *cn) , result(getclientname(*cn)))
game::ICOMMAND (getclientteam , "i" , (int *cn) , result(getclientteam(*cn)))
game::ICOMMAND (getclientmodel , "i" , (int *cn) , intret(getclientmodel(*cn)))
game::ICOMMAND (getclienticon , "i" , (int *cn) , result(getclienticon(*cn)))
game::ICOMMAND (ismaster , "i" , (int *cn) , intret(ismaster(*cn)?1:0))
game::ICOMMAND (isadmin , "i" , (int *cn) , intret(isadmin(*cn)?1:0))
game::ICOMMAND (getmastermode , "" , () , intret(mastermode))
game::ICOMMAND (mastermodename , "i" , (int *mm) , result(mastermodename(*mm,"")))
game::ICOMMAND (isspectator , "i" , (int *cn) , intret(isspectator(*cn)?1:0))
game::ICOMMAND (isai , "ii" , (int *cn, int *type) , intret(isai(*cn,*type)?1:0))
game::ICOMMAND (getclientnum , "s" , (char *name) , intret(name[0]?parseplayer(name):player1->clientnum))
game::ICOMMAND (showscores , "D" , (int *down) , showscores *!= 0down)
game::ICOMMAND (listclients , "bb" , (int *local, int *bots) , listclients * >0,*!= 0bots)
game::ICOMMAND (ignore , "s" , (char *arg) , ignore(parseplayer(arg)))
game::ICOMMAND (unignore , "s" , (char *arg) , unignore(parseplayer(arg)))
game::ICOMMAND (isignored , "s" , (char *arg) , intret(isignored(parseplayer(arg))?1:0))
game::ICOMMAND (mastermode , "i" , (int *val) , addmsg(N_MASTERMODE,"ri",*val))
request to change server master mode (permissions requires)
game::ICOMMAND (getaccuracy , "" , () , intret((player1->totaldamage *100)/max(player1->totalshots, 1)))
game::ICOMMAND (getdeaths , "" , () , intret(player1->deaths))
game::ICOMMAND (getflags , "" , () , intret(player1->flags))
game::ICOMMAND (spectator , "is" , (int *val, char *who) , togglespectator *, who)
game::ICOMMAND (getfrags , "" , () , intret(player1->frags))
return a player's statistics to cubescript
game::ICOMMAND (getteamkills , "" , () , intret(player1->teamkills))
game::ICOMMAND (gettotaldamage , "" , () , intret(player1->totaldamage))
game::ICOMMAND (checkmaps , "" , () , addmsg(N_CHECKMAPS,"r"))
ask the server to acquire CRC32 checksum of all player's maps (permissions requred)
game::ICOMMAND (gettotalshots , "" , () , intret(player1->totalshots))
game::ICOMMAND (mode , "i" , (int *val) , setmode * val)
set game mode
game::ICOMMAND (getmode , "" , () , intret(gamemode))
get game mode in cubescript
game::ICOMMAND (timeremaining , "i" , (int *formatted) , {int val=max(maplimit-lastmillis, 0)/1000;if(*formatted){defformatstring(str,"%d:%02d", val/60, val%60);result(str);}else intret(val);})
return remaining time
game::ICOMMAND (map , "s" , (char *name) , changemap(name))
game::ICOMMAND (dropflag , "" , () , {ctfmode.trydropflag();})
game::ICOMMAND (suicide , "" , () , suicide(player1))
game::ICOMMAND (pausegame , "i" , (int *val) , pausegame * > 0val)
game::ICOMMAND (paused , "iN$" , (int *val, int *numargs, ident *id) , {if(*numargs > 0) pausegame(clampvar(id,*val, 0, 1) > 0);else if(*numargs< 0) intret(gamepaused?1:0);else printvar(id, gamepaused?1:0);})
cubescript: check if game is paused
game::ICOMMAND (persistteams , "i" , (int *val) , persistteams * > 0val)
game::ICOMMAND (ammohudup , "V" , (tagval *args, int numargs) , {loopi(3) ammohudup[i]=i< numargs?getweapon(args[i].getstr()):-1;})
those 3 functions are used to rotate in circles through your weapons so you see different preview images of the other weapons in your holsters
game::ICOMMAND (ammohuddown , "V" , (tagval *args, int numargs) , {loopi(3) ammohuddown[i]=i< numargs?getweapon(args[i].getstr()):-1;})
game::ICOMMAND (ammohudcycle , "V" , (tagval *args, int numargs) , {loopi(8) ammohudcycle[i]=i< numargs?getweapon(args[i].getstr()):-1;})
game::ICOMMAND (gamespeed , "iN$" , (int *val, int *numargs, ident *id) , {if(*numargs > 0) changegamespeed(clampvar(id,*val, 10, 1000));else if(*numargs< 0) intret(gamespeed);else printvar(id, gamespeed);})
game::ICOMMAND (pm , "is" , (int *i, char *text) , sayprivate *, text)
game::ICOMMAND (servcmd , "C" , (char *cmd) , addmsg(N_SERVCMD,"rs", cmd))
send custom server messages to servers this feature is not used on most servers (?)
game::ICOMMAND (recorddemo , "i" , (int *val) , recorddemo * val)
game::ICOMMAND (cleardemos , "i" , (int *val) , cleardemos * val)
game::ICOMMAND (getdemo , "i" , (int *val) , getdemo * val)
game::ICOMMANDS ("m_noitems" , "i" , (int *mode) , {int gamemode=*mode;intret(m_noitems);})
game::ICOMMANDS ("m_noammo" , "i" , (int *mode) , {int gamemode=*mode;intret(m_noammo);})
game::ICOMMANDS ("m_insta" , "i" , (int *mode) , {int gamemode=*mode;intret(m_insta);})
game::ICOMMANDS ("m_tactics" , "i" , (int *mode) , {int gamemode=*mode;intret(m_tactics);})
game::ICOMMANDS ("m_efficiency" , "i" , (int *mode) , {int gamemode=*mode;intret(m_efficiency);})
game::ICOMMANDS ("m_capture" , "i" , (int *mode) , {int gamemode=*mode;intret(m_capture);})
game::ICOMMANDS ("m_regencapture" , "i" , (int *mode) , {int gamemode=*mode;intret(m_regencapture);})
game::ICOMMANDS ("m_ctf" , "i" , (int *mode) , {int gamemode=*mode;intret(m_ctf);})
game::ICOMMANDS ("m_protect" , "i" , (int *mode) , {int gamemode=*mode;intret(m_protect);})
game::ICOMMANDS ("m_hold" , "i" , (int *mode) , {int gamemode=*mode;intret(m_hold);})
game::ICOMMANDS ("m_collect" , "i" , (int *mode) , {int gamemode=*mode;intret(m_collect);})
game::ICOMMANDS ("m_teammode" , "i" , (int *mode) , {int gamemode=*mode;intret(m_teammode);})
game::ICOMMANDS ("m_demo" , "i" , (int *mode) , {int gamemode=*mode;intret(m_demo);})
game::ICOMMANDS ("m_edit" , "i" , (int *mode) , {int gamemode=*mode;intret(m_edit);})
game::ICOMMANDS ("m_lobby" , "i" , (int *mode) , {int gamemode=*mode;intret(m_lobby);})
game::ICOMMANDS ("m_lms" , "i" , (int *mode) , {int gamemode=*mode;intret(m_lms);})
game::ICOMMANDS ("m_bomb" , "i" , (int *mode) , {int gamemode=*mode;intret(m_bomb);})
game::ICOMMANDS ("m_timeforward" , "i" , (int *mode) , {int gamemode=*mode;intret(m_timeforward);})
game::ICOMMANDS ("m_obstacles" , "i" , (int *mode) , {int gamemode=*mode;intret(m_obstacles);})
void game::ignore (int cn)
ignore all chat messags from a certain client number
References vector< T, MINSIZE >::add(), hmap::d, vector< T, MINSIZE >::find(), inexor::util::log_manager::game, getclient(), ignores, Log, fpsent::name, and player1.
void game::initclient ()
References vector< T, MINSIZE >::add(), filtertext(), MAXNAMELEN, fpsent::name, player1, players, and spawnstate().
Referenced by main().
bool game::intersect (dynent * d, const vec & from, const vec & to, float & dist)
References physent::aboveeye, physent::eyeheight, linecylinderintersect(), physent::o, and physent::radius.
Referenced by intersectclosest(), pointatplayer(), and projdamage().
dynent * game::intersectclosest (const vec & from, const vec & to, fpsent * at, float & bestdist)
References CS_ALIVE, intersect(), iterdynents(), loopi(), numdynents(), and physent::state.
Referenced by ai::process(), raydamage(), and selectcrosshair().
bool game::isadmin (int cn)
check if this client is an administrator
References hmap::d, getclient(), PRIV_ADMIN, and fpsent::privilege.
bool game::isai (int cn, int type)
check if this cn is a bot (computer controlled player)
References AI_BOT, AI_MAX, fpsstate::aitype, hmap::d, and getclient().
bool game::isignored (int cn)
cubescript: check if this person is ignored by you
References vector< T, MINSIZE >::find(), and ignores.
Referenced by parsemessages().
bool game::ismaster (int cn)
check if this client is a game master or administrator
References hmap::d, getclient(), PRIV_MASTER, and fpsent::privilege.
bool game::isobstaclealive (movable * m)
References CS_ALIVE, game::movable::etype, OBSTACLE, and physent::state.
Referenced by game::hideandseekclientmode::drawhud(), and game::bombclientmode::drawhud().
bool game::ispaused ()
check if game is paused
References gamepaused.
Referenced by addmotionblur(), main(), renderscoreboard(), and respawnself().
bool game::ispersisted ()
References teamspersisted.
bool game::isspectator (int cn)
References CS_SPECTATOR, hmap::d, getclient(), and physent::state.
dynent * game::iterdynents (int i)
iterate through all dynamic entities and return entity with index [i] You put the list in and get it through to return back The caller has to hand in a list which will get filled
Returns
a player, monster or movable (all dynamic entities)
References vector< T, MINSIZE >::length(), movables, and players.
Referenced by game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), checkdynentcache(), explode(), intersectclosest(), main(), and updateprojectiles().
void game::kick (const char * victim, const char * reason)
request to kickban a player
References addmsg(), fpsent::clientnum, N_KICK, parseplayer(), and player1.
Referenced by server::addteamkillkick().
void game::killed (fpsent * d, fpsent * actor)
this callback is called when player actor kills d prints death messages to all kind of consoles
References cmode, colorname(), CS_ALIVE, CS_DEAD, CS_EDITING, CS_LAGGED, CS_SPAWNING, fpsent::deaths, deathstate(), physent::editstate, ENT_AI, ENT_INANIMATE, followingplayer(), inexor::util::log_manager::frag_involved, inexor::util::log_manager::frag_not_involved, intermission, isteam, game::clientmode::killed(), ai::killed(), Log, m_teammode, player1, physent::resetinterp(), physent::state, fpsent::team, teamcolorname(), fpsent::teamkills, and physent::type.
Referenced by damaged().
void game::lighteffects (dynent * e, vec & color, vec & dir)
if 0 is another way to comment out like this: /*
References CS_DEAD, hmap::d, f(), lastmillis, fpsstate::quadmillis, physent::state, and anonymous_namespace{utilTest.cpp}::t().
Referenced by rendermodel().
void game::listclients (bool local, bool bots)
return a list of players
References vector< T, MINSIZE >::add(), AI_NONE, fpsent::clientnum, clients, connected, formatstring(), vector< T, MINSIZE >::getbuf(), loopv, server::numclients(), player1, vector< T, MINSIZE >::put(), and result().
void game::listdemos ()
References addmsg(), Log, N_LISTDEMOS, and inexor::util::log_manager::std.
void game::moveragdolls ()
References hmap::d, lastmillis, fpsent::lastupdate, loopv, moveragdoll(), ragdolls, and vector< T, MINSIZE >::remove().
Referenced by updateworld().
void game::msgsound (int n, physent * d)
play sound and send sound notification to server
See Also
playsound
References addmsg(), ENT_PLAYER, N_SOUND, physent::o, player1, inexor::sound::playsound(), and physent::type.
Referenced by entities::addammo(), physicstrigger(), and shoot().
bool game::needminimap ()
checks if minimap is required for this game mode
References m_bomb, m_capture, m_collect, m_ctf, m_hold, and m_protect.
Referenced by drawminimap().
void game::newbouncer (const vec & from, const vec & to, bool local, int id, fpsent * owner, int type, int lifetime, int speed, entitylight * light = nullptr, int generation = 0)
References physent::aboveeye, vec::add(), avoidcollision(), BNC_BARRELDEBRIS, BNC_BOMB, BNC_DEBRIS, BNC_GIBS, BNC_GRENADE, BNC_SPLINTER, bouncers, game::bouncer::bouncetype, COLLIDE_ELLIPSE_PRECISE, physent::collidetype, dir, physent::eyeheight, f(), game::bouncer::generation, GUN_BOMB, GUN_GL, hudgunorigin(), hudplayer(), game::bouncer::id, isthirdperson(), lastmillis, game::bouncer::lifetime, game::bouncer::light, game::bouncer::local, vec::mul(), vec::normalize(), physent::o, game::bouncer::offset, game::bouncer::offsetmillis, OFFSETMILLIS, game::bouncer::owner, physent::radius, vec::rescale(), physent::resetinterp(), rnd(), vec::sub(), game::bouncer::variant, physent::vel, physent::xradius, and physent::yradius.
Referenced by shoteffects(), spawnbouncer(), spawnnextsplinter(), and spawnsplinters().
fpsent * game::newclient (int cn)
ensure new client is a valid entity
References vector< T, MINSIZE >::add(), fpsent::clientnum, clients, hmap::d, vector< T, MINSIZE >::length(), inexor::rpc::max(), MAXBOTS, MAXCLIENTS, neterr(), player1, and players.
Referenced by ai::init(), game::collectclientmode::parse_network_message(), game::ctfclientmode::parse_network_message(), game::ctfclientmode::parseflags(), parsemessages(), and game::collectclientmode::parsetokens().
void game::newmap (int size)
request server to start new map (requires editmode)
References addmsg(), and N_NEWMAP.
Referenced by mapenlarge(), and newmap().
void game::newprojectile (const vec & from, const vec & to, float speed, bool local, int id, fpsent * owner, int gun)
References vector< T, MINSIZE >::add(), game::projectile::dir, game::projectile::gun, hudgunorigin(), game::projectile::id, lastmillis, game::projectile::local, vec::normalize(), game::projectile::o, game::projectile::offset, game::projectile::offsetmillis, OFFSETMILLIS, game::projectile::owner, game::projectile::speed, vec::sub(), and game::projectile::to.
Referenced by shoteffects().
void game::nextfollow (int dir)
follow previous/next client number
Parameters
dir either forwards (1) or backwards (-1)
References clients, CS_SPECTATOR, cur, dir, vector< T, MINSIZE >::empty(), followdir, following, vector< T, MINSIZE >::length(), Log, loopv, player1, physent::state, recorder::state, inexor::util::log_manager::std, and stopfollowing().
Referenced by clientdisconnected().
void game::nextweapon (int dir, bool force = false)
References fpsstate::ammo, CS_ALIVE, dir, fpsstate::gunselect, gunselect(), loopi(), NUMGUNS, player1, inexor::sound::playsound(), S_NOAMMO, and physent::state.
int game::numdynents ()
return the sum of dynamic entities currently in scene
References vector< T, MINSIZE >::length(), movables, and players.
Referenced by game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), checkdynentcache(), explode(), intersectclosest(), and updateprojectiles().
void game::offsetray (const vec & from, const vec & to, int spread, float range, vec & dest)
References vec::add(), vec::dist(), f(), vec::mul(), vec::normalize(), RAY_ALPHAPOLY, RAY_CLIPMAT, raycubepos(), rndscale(), vec::squaredlen(), and vec::sub().
Referenced by createrays(), and shoot().
void game::otherplayers (int curtime)
parse player state, move players, predict their position, handle ragdoll, check for lag
See Also
updateworld
moveragdoll
predictplayer
References fpsent::ai, entities::checkquad(), CS_ALIVE, CS_DEAD, CS_EDITING, CS_LAGGED, hmap::d, fpsstate::gunwait, intermission, fpsent::lastaction, lastmillis, fpsent::lastpain, fpsent::lastupdate, loopv, moveplayer(), moveragdoll(), player1, players, predictplayer(), fpsstate::quadmillis, dynent::ragdoll, fpsent::smoothmillis, smoothmove, physent::state, and totalmillis.
Referenced by updateworld().
void game::parsemessages (int cn, fpsent * d, ucharbuf & p)
References physent::abovehead(), addmsg(), alias(), fpsstate::ammo, fpsstate::armour, at(), attachentity(), guninfo::attackdelay, fpsent::attacking, databuf< T >::buf, changemapserv(), inexor::util::log_manager::chat, cleanragdoll(), clearclients(), clientdisconnected(), fpsent::clientnum, cmode, COL_BLUE, COL_GREEN, COL_GREY, COL_WHITE, colorname(), connected, copystring(), selinfo::corner, CS_ALIVE, CS_DEAD, CS_EDITING, CS_SPAWNING, CS_SPECTATOR, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, guninfo::damage, ai::damaged(), deathscore, deathstate(), defformatstring, demoplayback, server::demos, dir, disablezoom(), disconnect(), DMF, DNF, sphere::ebuf, fpsent::edit, inexor::util::log_manager::edit, editmode, physent::editstate, emptymap(), enlargemap(), entities::ents, ET_EMPTY, execute(), explodeeffects(), f(), filtertext(), packetbuf::finalize(), findplayerspawn(), ident::flags, following, fpsent::fov, inexor::util::log_manager::game, gamepaused, gamespeed, getclient(), entities::getents(), getfloat(), getident(), getint(), getstring(), getuint(), getworldsize(), selinfo::grid, GUN_BOMB, GUN_FIST, guns, fpsstate::gunselect, fpsstate::gunwait, fpsstate::health, game::clientmode::hidefrags(), fpsent::hitpush(), hudannounce_begin, hudannounce_effect, hudannounce_text, hudannounce_timeout, I_BOOST, I_QUAD, ID_FVAR, ID_SVAR, ID_VAR, identexists(), IDF_OVERRIDE, IDF_READONLY, ai::init(), isignored(), isteam, entities::itemicon(), entities::itemname(), ai::itemspawned(), ai::killed(), fpsent::lastaction, fpsent::lastattackgun, lasthit, lastmillis, fpsent::lastpain, fpsent::lasttaunt, fpsent::lifesequence, lilswap(), Log, loopi(), loopk, loopv, m_teammode, mastermode, mastermodename(), inexor::rpc::max(), databuf< T >::maxlen, MAXNAMELEN, MAXTAGLEN, MAXTEAMLEN, MAXTEAMS, MAXTRANS, modifyoctaent(), mpcopy(), mpdelcube(), mpeditent(), mpeditface(), mpeditmat(), mpedittex(), mpeditvslot(), mpflip(), mppaste(), mpremip(), mpreplacetex(), mprotate(), N_ANNOUNCE, N_CDIS, N_CLIENT, N_CLIENTPING, N_CLIPBOARD, N_COPY, N_CURRENTMASTER, N_DAMAGE, N_DELCUBE, N_DEMOPACKET, N_DEMOPLAYBACK, N_DIED, N_EDITENT, N_EDITF, N_EDITM, N_EDITMODE, N_EDITT, N_EDITVAR, N_EDITVSLOT, N_EXPLODEFX, N_FLIP, N_FORCEDEATH, N_FOV, N_GAMESPEED, N_GUNSELECT, N_HITPUSH, N_HUDANNOUNCE, N_INITAI, N_INITCLIENT, N_ITEMACC, N_ITEMLIST, N_ITEMPUSH, N_ITEMSPAWN, N_MAPCHANGE, N_MASTERMODE, N_NEWMAP, N_PASTE, N_PAUSEGAME, N_PERSISTTEAMS, N_PONG, N_PRIVMSG, N_REDO, N_REMIP, N_REPLACE, N_RESUME, N_ROTATE, N_SAYTEAM, N_SENDDEMOLIST, N_SERVCMD, N_SERVINFO, N_SERVMSG, N_SETTEAM, N_SHOTFX, N_SOUND, N_SPAWN, N_SPAWNSTATE, N_SPECTATOR, N_SWITCHMODEL, N_SWITCHNAME, N_TAUNT, N_TEAMINFO, N_TEXT, N_TIMEUP, N_UNDO, N_WELCOME, fpsent::name, needclipboard, neterr(), newclient(), entities::newentity(), newentity(), notifywelcome(), physent::o, selinfo::o, selinfo::orient, databuf< T >::overread(), databuf< T >::pad(), game::clientmode::parse_network_message(), parsestate(), PART_HUD_ICON, PART_TEXT, particle_icon(), particle_text(), particle_textcopy(), game::clientmode::pickspawn(), entities::pickupeffects(), fpsent::ping, player1, fpsent::playermodel, players, inexor::sound::playsound(), printvar(), PRIV_NONE, fpsent::privilege, PROTOCOL_VERSION, putint(), fpsstate::quadmillis, dynent::ragdoll, guninfo::rays, databuf< T >::remaining(), physent::resetinterp(), fpsent::respawn(), game::clientmode::respawned(), selinfo::s, S_ITEMSPAWN, S_V_BOOST10, S_V_QUAD10, S_WEAPLOAD, saveragdoll(), sel, sendclientpacket(), sendintro(), senditemstoserver, servinfo, sessionid, setfvar(), entities::setspawn(), setsvar(), setteaminfo(), setvar(), shoteffects(), showscores(), ai::spawned(), entities::spawnitems(), physent::state, inexor::util::log_manager::std, stopfollowing(), databuf< T >::subbuf(), anonymous_namespace{utilTest.cpp}::t(), fpsent::tag, ai::target(), fpsent::team, inexor::util::log_manager::team_chat, teamspersisted, timeupdate(), toggleedit(), totalmillis, fpsent::totalshots, unpackeditinfo(), unpackundo(), and selinfo::validate().
Referenced by parsepacketclient().
void game::parsepacketclient (int chan, packetbuf & p)
References packetbuf::packet, parsemessages(), parsepositions(), and receivefile().
Referenced by gets2c().
int game::parseplayer (const char * arg)
all functions can be called using client number or full name name should be case sensitive but the engine checks is both ways
try to parse it as cn
try case sensitive first
nothing found, try case insensitive
no match found!
References fpsent::clientnum, clients, gle::end(), vector< T, MINSIZE >::inrange(), loopv, fpsent::name, player1, and players.
Referenced by follow(), gotoplayer(), kick(), setmaster(), setteam(), and togglespectator().
void game::parsepositions (ucharbuf & p)
References CS_ALIVE, CS_DEAD, CS_LAGGED, CS_SPAWNING, hmap::d, fpsent::deltapitch, physent::deltapos, fpsent::deltaroll, fpsent::deltayaw, dir, vec::dist(), DMF, DVELF, physent::eyeheight, physent::falling, falling(), hmap::flags, databuf< T >::get(), getclient(), getint(), getuint(), entities::jumppadeffects(), lastmillis, fpsent::lifesequence, loopk, physent::move, vec::mul(), N_DEMOPACKET, N_JUMPPAD, N_POS, N_TELEPORT, neterr(), fpsent::newpitch, physent::newpos, fpsent::newroll, fpsent::newyaw, physent::o, physent::physstate, physent::pitch, databuf< T >::remaining(), physent::roll, smoothdist, fpsent::smoothmillis, smoothmove, physent::state, physent::strafe, entities::teleporteffects(), updatephysstate(), updatepos(), vecfromyawpitch(), physent::vel, and physent::yaw.
Referenced by parsepacketclient().
void game::parsestate (fpsent * d, ucharbuf & p, bool resume = false)
References fpsstate::ammo, fpsstate::armour, fpsstate::armourtype, fpsent::deaths, fpsent::flags, fpsent::frags, getint(), GUN_BOMB, GUN_FIST, GUN_PISTOL, GUN_SG, fpsstate::gunselect, fpsstate::health, fpsent::lifesequence, loopi(), fpsstate::maxhealth, player1, fpsstate::quadmillis, physent::state, fpsent::teamkills, fpsent::totaldamage, and fpsent::totalshots.
Referenced by parsemessages().
void game::particletrack (physent * owner, vec & o, vec & d)
References vec::add(), vec::dist(), ENT_AI, ENT_PLAYER, fpsstate::gunselect, fpsent::lastattackgun, inexor::rpc::min(), vec::mul(), fpsent::muzzle, physent::o, physent::pitch, RAY_ALPHAPOLY, RAY_CLIPMAT, raycube(), physent::type, vecfromyawpitch(), and physent::yaw.
Referenced by partrenderer::calc().
void game::pausegame (bool val)
pause game
References addmsg(), inexor::util::log_manager::game, isconnected(), Log, and N_PAUSEGAME.
void game::persistteams (bool val)
Set reshuffeling behaviour on mapchange according to bool val (true activates persistent teams)
References addmsg(), inexor::util::log_manager::game, isconnected(), Log, and N_PERSISTTEAMS.
void game::physicstrigger (physent * d, bool local, int floorlevel, int waterlevel, int material)
trigger sound effects depending on the material you enter
as long as you do not enter lava play a splash sound
only send server message if I entered the water and fpsent d is not a bot
References ENT_INANIMATE, ENT_PLAYER, MAT_LAVA, msgsound(), physent::o, player1, inexor::sound::playsound(), S_BURN, S_JUMP, S_LAND, S_SPLASH1, S_SPLASH2, and physent::type.
Referenced by modifyvelocity(), ragdolldata::move(), and moveplayer().
static bool game::playersort (const fpsent * a, const fpsent * b) inline static
References CS_SPECTATOR, fpsent::flags, fpsent::frags, m_collect, m_ctf, fpsent::name, and physent::state.
Referenced by getbestplayers(), and groupplayers().
fpsent * game::pointatplayer ()
Give me the player I am aiming at.
References intersect(), loopv, physent::o, player1, players, and worldpos.
void game::predictplayer (fpsent * d, bool move)
use latency and assume player movement to predict a player's new position.
Improves visual appearance of his movement tremendous - even under lag
See Also
moveplayer
References vec::add(), fpsent::deltapitch, physent::deltapos, fpsent::deltaroll, fpsent::deltayaw, lastmillis, moveplayer(), vec::mul(), fpsent::newpitch, physent::newpos, fpsent::newroll, fpsent::newyaw, physent::o, physent::pitch, physent::roll, fpsent::smoothmillis, smoothmove, and physent::yaw.
Referenced by otherplayers().
void game::preload ()
References preloadbouncers(), entities::preloadentities(), preloadplayermodel(), preloadsounds(), and preloadweapons().
Referenced by load_world().
void game::preloadbouncers ()
References loopi(), and preloadmodel().
Referenced by preload().
void game::preloadplayermodel ()
References game::playermodelinfo::armour, game::playermodelinfo::blueteam, game::playermodelinfo::ffa, getplayermodelinfo(), loopi(), loopj, m_teammode, multiplayer(), playermodel, playermodels, preloadmodel(), game::playermodelinfo::quad, game::playermodelinfo::redteam, and game::playermodelinfo::vwep.
Referenced by preload().
void game::preloadsounds ()
References inexor::sound::preloadsound(), S_BURN, S_HIT, S_JUMP, S_JUMPPAD, S_PISTOL, S_SPLASH2, S_V_BOOST, and S_V_QUAD10.
Referenced by preload().
void game::preloadweapons ()
References guninfo::file, recorder::file, formatstring(), getplayermodelinfo(), guns, game::playermodelinfo::hudguns, loopi(), m_teammode, NUMGUNS, player1, preloadmodel(), and teamskins.
Referenced by preload().
void game::printname ()
print my own nick name to the game console
References colorname(), Log, player1, and inexor::util::log_manager::std.
void game::printteam ()
print own team name to the game console
References Log, player1, inexor::util::log_manager::std, and fpsent::team.
void game::printvar (fpsent * d, ident * id)
print map var change commited by other players in edit mode
References colorname(), inexor::util::log_manager::edit, ident::flags, formatstring(), ID_FVAR, ID_SVAR, ID_VAR, IDF_HEX, Log, ident::name, and ident::type.
Referenced by parsemessages(), and vartrigger().
bool game::projdamage (dynent * o, projectile & p, vec & v, int qdam)
References CS_ALIVE, dir, game::projectile::gun, hit(), intersect(), game::projectile::o, game::projectile::owner, projdist(), projsplash(), and physent::state.
Referenced by updateprojectiles().
float game::projdist (dynent * o, vec & dir, const vec & v)
References physent::aboveeye, vec::dist(), vec::div(), physent::eyeheight, and physent::o.
Referenced by projdamage(), and radialeffect().
void game::projsplash (projectile & p, vec & v, dynent * safe, int damage)
References adddecal(), DECAL_SCORCH, game::projectile::dir, explode(), f(), game::projectile::gun, GUN_RL, game::projectile::local, vec::neg(), game::projectile::owner, PART_SPARK, particle_splash(), inexor::sound::playsound(), and S_FEXPLODE.
Referenced by projdamage(), and updateprojectiles().
void game::radialbombeffect (bouncer * b, const vec & v)
References BNC_BOMB, game::bouncer::bouncetype, dir, vec::dist(), vec::div(), GUN_BOMB, game::bouncer::lifetime, and physent::o.
Referenced by explode().
void game::radialeffect (dynent * o, const vec & v, int qdam, fpsent * at, int gun)
References CS_ALIVE, dir, EXP_DISTSCALE, EXP_SELFDAMDIV, hit(), projdist(), and physent::state.
Referenced by explode().
void game::raydamage (vec & from, vec & to, fpsent * d)
References adddecal(), DECAL_BULLET, ENT_AI, f(), GUN_BITE, GUN_FIST, GUN_RIFLE, fpsstate::gunselect, hitpush(), hits, intersectclosest(), loopi(), MAXRAYS, MONSTERDAMAGEFACTOR, fpsstate::quadmillis, rays, shorten(), and physent::type.
Referenced by shoot().
void game::readgamedata (vector< char > & extras)
Referenced by load_world().
void game::receivefile (packetbuf & p)
References databuf< T >::buf, copystring(), defformatstring, DIR_MAP, inexor::util::log_manager::edit, findfile(), getclientmap(), getint(), inexor::filesystem::getmediapath(), lastmillis, load_world(), Log, m_edit, hmap::map, databuf< T >::maxlen, N_DEMOPACKET, N_SENDDEMO, N_SENDMAP, openrawfile(), databuf< T >::remaining(), entities::spawnitems(), inexor::util::log_manager::std, packetbuf::subbuf(), and stream::write().
Referenced by parsepacketclient().
void game::recorddemo (int val)
References addmsg(), N_RECORDDEMO, player1, PRIV_MASTER, and fpsent::privilege.
void game::removebouncers (fpsent * owner)
References bouncers, and loopv.
Referenced by removeweapons().
void game::removeprojectiles (fpsent * owner)
References vector< T, MINSIZE >::length(), loopi(), and vector< T, MINSIZE >::remove().
Referenced by removeweapons().
void game::removeweapons (fpsent * d)
References removebouncers(), and removeprojectiles().
Referenced by clientdisconnected(), and ai::init().
void game::renderavatar ()
References drawhudgun().
Referenced by drawreflection(), and renderavatar().
void game::renderbouncers ()
References vec::add(), ANIM_LOOP, ANIM_MAPMODEL, bbarr_color, bbarr_dir, bbarr_fade, bbarr_gravity, bbarr_height, bbarr_num, bbarr_overlap, bbarr_size, bbarr_tremblepeak, bbarr_type, BNC_BARRELDEBRIS, BNC_BOMB, BNC_DEBRIS, BNC_GIBS, BNC_GRENADE, bouncers, f(), game::bouncer::lastyaw, loopv, vec::magnitude(), MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_DYNSHADOW, MDL_LIGHT, MDL_LIGHT_FAST, vec::mul(), physent::o, game::bouncer::offset, game::bouncer::offsetmillis, OFFSETMILLIS, RAY_CLIPMAT, raycube(), regularshape(), rendermodel(), rnd(), vectoyawpitch(), and physent::vel.
Referenced by rendergame().
void game::rendergame (bool mainpass)
References physent::abovehead(), bestplayers, bestteams, cmode, colorname(), concatstring(), copystring(), CS_DEAD, CS_SPAWNING, CS_SPECTATOR, hmap::d, defformatstring, endmodelbatches(), f(), followingplayer(), getbestplayers(), getbestteams(), getplayermodelinfo(), fpsent::info, intermission, game::clientmode::isinvisible(), isteam, isthirdperson(), lastmillis, fpsent::lastupdate, fpsent::lifesequence, loopv, m_teammode, inexor::rpc::max(), fpsstate::maxhealth, inexor::rpc::min(), PART_TEXT, particle_text(), player1, players, ragdolls, ai::render(), renderbouncers(), renderedgame, entities::renderentities(), game::clientmode::rendergame(), rendergame(), rendermovables(), renderplayer(), renderprojectiles(), shadowmapping, vector< T, MINSIZE >::shrink(), startmodelbatches(), physent::state, fpsent::team, and teamskins.
Referenced by rendergame().
void game::rendermovables ()
References ANIM_LOOP, ANIM_MAPMODEL, CS_ALIVE, physent::feetpos(), loopv, game::movable::mapmodel, mapmodelname(), MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_LIGHT, MDL_SHADOW, mdlname(), movables, rendermodel(), physent::state, and physent::yaw.
Referenced by rendergame().
void game::renderplayer (fpsent * d, const playermodelinfo & mdl, int team, float fade, bool mainpass)
References A_BLUE, A_YELLOW, ANIM_ATTACK1, ANIM_HOLD1, ANIM_LOOP, ANIM_LOSE, ANIM_MAPMODEL, ANIM_POWERUP, ANIM_SHIELD, ANIM_TAUNT, ANIM_VWEP_IDLE, ANIM_VWEP_SHOOT, ANIM_WIN, game::playermodelinfo::armour, fpsstate::armour, fpsstate::armourtype, guninfo::attackdelay, bestplayers, bestteams, game::playermodelinfo::blueteam, CS_ALIVE, CS_DEAD, physent::eyeheight, game::playermodelinfo::ffa, vector< T, MINSIZE >::find(), GUN_BOMB, GUN_FIST, GUN_PISTOL, guns, fpsstate::gunselect, intermission, fpsent::lastaction, fpsent::lastattackgun, lastmillis, fpsent::lastpain, fpsent::lasttaunt, m_teammode, MDL_CULL_DIST, MDL_CULL_VFC, MDL_DYNSHADOW, mdlname(), fpsent::muzzle, physent::o, game::playermodelinfo::quad, fpsstate::quadmillis, game::playermodelinfo::ragdoll, game::playermodelinfo::redteam, renderclient(), rendermodel(), physent::state, vec::sub(), fpsent::team, testteam, and game::playermodelinfo::vwep.
Referenced by rendergame(), and renderplayerpreview().
void game::renderplayerpreview (int model, int team, int weap)
References physent::aboveeye, vec::add(), fpsstate::ammo, calcmodelpreviewpos(), entitylight::color, entitylight::dir, physent::eyeheight, getplayermodelinfo(), GUN_FIST, GUN_PISTOL, fpsstate::gunselect, dynent::light, loopi(), vec2::max(), entitylight::millis, vec::normalize(), physent::o, renderplayer(), physent::xradius, physent::yaw, and physent::yradius.
Referenced by gui::playerpreview().
void game::renderprojectiles ()
References vec::add(), ANIM_LOOP, ANIM_MAPMODEL, game::projectile::gun, GUN_RL, game::projectile::light, loopv, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_LIGHT, MDL_LIGHT_FAST, vec::mul(), vec::normalize(), game::projectile::o, game::projectile::offset, game::projectile::offsetmillis, OFFSETMILLIS, projs, rendermodel(), vec::sub(), game::projectile::to, and vectoyawpitch().
Referenced by rendergame().
void game::renderscoreboard (g3d_gui & g, bool firstpass)
References g3d_gui::background(), game::playermodelinfo::blueicon, cmode, colorname(), connectedpeer(), CS_DEAD, CS_LAGGED, demoplayback, f(), game::playermodelinfo::ffaicon, gamemode, gamespeed, getclient(), getclientmap(), getplayermodelinfo(), groupplayers(), groups, game::clientmode::hidefrags(), intermission, ispaused(), isteam, lastmillis, vector< T, MINSIZE >::length(), loopk, loopscoregroup, m_ctf, m_teammode, m_timed, m_timeforward, maplimit, maptime, inexor::rpc::max(), modename(), multiplayer(), fpsent::ownernum, fpsent::ping, player1, players, g3d_gui::poplist(), PRIV_ADMIN, PRIV_MASTER, fpsent::privilege, g3d_gui::pushlist(), game::playermodelinfo::redicon, game::clientmode::renderscoreboard(), scoregroup::sametag(), teamscore::score, g3d_gui::separator(), servinfo, g3d_gui::space(), g3d_gui::spring(), physent::state, g3d_gui::strut(), fpsent::team, teamscore::team, g3d_gui::text(), g3d_gui::textf(), and g3d_gui::titlef().
Referenced by game::scoreboardgui::gui().
void game::resetgamestate ()
reset game state in singleplayer reset all monsters, triggers, bouncers, movables, and projectiles
References clearbouncers(), clearmovables(), clearprojectiles(), and m_obstacles.
Referenced by toggleedit().
void game::respawn (int gamemode = 0)
spawn myself in SP and DMSP game mode (singleplayer only)
See Also
changemap
References fpsent::attacking, cmode, CS_DEAD, lastmillis, lastspawnattempt, player1, respawnself(), game::clientmode::respawnwait(), and physent::state.
Referenced by canjump(), and doattack().
void game::respawnself ()
Send "I would like to spawn" to server.
References addmsg(), ispaused(), lastmillis, fpsent::lifesequence, N_TRYSPAWN, player1, and fpsent::respawned.
Referenced by respawn().
const char* game::restoreconfig () inline
Referenced by main().
const char* game::savedconfig () inline
Referenced by main(), and writecfg().
const char* game::savedservers () inline
Referenced by main().
void game::saveragdoll (fpsent * d)
References vector< T, MINSIZE >::add(), fpsent::ai, fpsent::attackchan, fpsent::edit, fpsent::idlechan, lastmillis, fpsent::lastpain, fpsent::lastupdate, inexor::rpc::max(), player1, playermodel, fpsent::playermodel, dynent::ragdoll, and ragdolls.
Referenced by parsemessages().
void game::sayprivate (int i, char * text)
References addmsg(), clients, COL_BLUE, COL_GREY, colorname(), inexor::util::log_manager::game, vector< T, MINSIZE >::inrange(), Log, N_PRIVMSG, player1, and inexor::util::log_manager::team_chat.
void game::sayteam (char * text)
send team messages to server
References addmsg(), COL_BLUE, colorname(), Log, N_SAYTEAM, player1, and inexor::util::log_manager::team_chat.
static bool game::scoregroupcmp (const scoregroup * x, const scoregroup * y) inline static
References vector< T, MINSIZE >::length(), scoregroup::players, teamscore::score, and teamscore::team.
Referenced by groupplayers().
int game::selectcrosshair (vec & color)
switch crosshair depending on player state and player health
References CS_ALIVE, CS_DEAD, CS_SPECTATOR, hmap::d, editmode, ENT_PLAYER, f(), fpsstate::gunwait, fpsstate::health, hudplayer(), intersectclosest(), isteam, lasthit, lastmillis, m_insta, vec::mul(), physent::o, physent::state, fpsent::team, physent::type, and worldpos.
Referenced by draw_crosshair().
void game::sendclipboard ()
send copied data from your clipboard to server
References packetbuf::finalize(), localedit, N_CLIPBOARD, needclipboard, packeditinfo(), packetbuf::put(), putint(), and sendclientpacket().
Referenced by edittrigger().
void game::sendintro ()
send N_CONNECT (with own name, serverpassword, playermodel and fov)
References fpsent::clientnum, connectmapwish, connectmodewish, connectpass, packetbuf::finalize(), fpsent::fov, tiger::hash(), hashpassword(), m_valid, MAXTRANS, N_CONNECT, fpsent::name, nextmode, player1, fpsent::playermodel, putint(), sendclientpacket(), sendstring(), and sessionid.
Referenced by parsemessages().
void game::sendmap ()
References CS_SPECTATOR, defformatstring, DIR_MAP, inexor::util::log_manager::edit, findfile(), inexor::filesystem::getmediapath(), lastmillis, Log, m_edit, hmap::map, needclipboard, openrawfile(), player1, fpsent::privilege, save_world(), send_file(), stream::size(), and physent::state.
void game::sendmapinfo ()
set booleans sendcrc and senditemstoserver if connected.
References connected, CS_SPECTATOR, player1, fpsent::privilege, sendcrc, senditemstoserver, and physent::state.
Referenced by startmap().
void game::sendmessages ()
?
References cmode, packetbuf::finalize(), vector< T, MINSIZE >::getbuf(), getclientmap(), getmapcrc(), lastping, vector< T, MINSIZE >::length(), m_noitems, MAXTRANS, messagecn, messagereliable, messages, N_MAPCRC, N_PING, packetbuf::put(), putint(), entities::putitems(), packetbuf::reliable(), sendclientpacket(), sendcrc, game::clientmode::senditems(), senditemstoserver, sendstring(), vector< T, MINSIZE >::setsize(), and totalmillis.
Referenced by c2sinfo().
static void game::sendposition (fpsent * d, packetbuf & q) static
network message parser
format position in network packet
References fpsent::clientnum, dir, DMF, DVELF, physent::eyeheight, physent::falling, physent::feetpos(), hmap::flags, fpsent::lifesequence, lookupmaterial(), loopk, vec::magnitude(), MAT_GAMECLIP, MATF_CLIP, inexor::rpc::min(), physent::move, vec::mul(), N_POS, physent::o, physent::physstate, physent::pitch, packetbuf::put(), putint(), putuint(), physent::roll, physent::strafe, vectoyawpitch(), physent::vel, and physent::yaw.
Referenced by entities::jumppadeffects(), and entities::teleporteffects().
void game::sendposition (fpsent * d, bool reliable)
send my own player position to server (call function above)
References CS_ALIVE, CS_EDITING, packetbuf::finalize(), sendclientpacket(), and physent::state.
Referenced by sendpositions().
void game::sendpositions ()
?
References fpsent::ai, CS_ALIVE, CS_EDITING, hmap::d, packetbuf::finalize(), vector< T, MINSIZE >::length(), loopv, player1, players, sendclientpacket(), sendposition(), and physent::state.
Referenced by c2sinfo().
void game::setbliptex (int team, const char * type = "")
set specific textures for teammates, skulls... on the minimap
References radardir, settexture(), teamblipcolor, and tempformatstring().
Referenced by game::collectclientmode::drawbaseblip(), game::ctfclientmode::drawblip(), game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), and drawteammates().
void game::setclientmode ()
set game mode pointer
References bombmode, capturemode, cmode, collectmode, ctfmode, hideandseekmode, m_bomb, m_capture, m_collect, m_ctf, and m_hideandseek.
Referenced by startgame().
void game::setmaster (const char * arg, const char * who)
acquire game master or give game master to players
References addmsg(), fpsent::clientnum, tiger::hash(), hashpassword(), N_SETMASTER, parseint(), parseplayer(), player1, and sessionid.
void game::setmode (int mode)
force server to change game mode (permissions required)
References intret(), and nextmode.
void game::setradartex ()
bind the minimap frame's texture
See Also
settexture
References defformatstring, radardir, and settexture().
Referenced by game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and game::captureclientmode::drawhud().
void game::setteam (const char * arg1, const char * arg2)
change a players team
See Also
addmsg
References addmsg(), N_SETTEAM, and parseplayer().
void game::setteaminfo (const char * team, int frags)
References copystring(), teaminfo::frags, anonymous_namespace{utilTest.cpp}::t(), teaminfo::team, and teaminfos.
Referenced by parsemessages().
void game::setupcamera ()
initialise camera when entering spectator mode
See Also
followingplayer
References CS_DEAD, followingplayer(), physent::o, physent::pitch, player1, physent::resetinterp(), physent::state, ai::target(), and physent::yaw.
Referenced by recomputecamera().
void game::setweapon (const char * name, bool force = false)
References fpsstate::ammo, CS_ALIVE, getweapon(), GUN_BOMB, gunselect(), player1, inexor::sound::playsound(), S_NOAMMO, and physent::state.
void game::shoot (fpsent * d, const vec & targ)
References vec::add(), addmsg(), fpsent::ai, fpsstate::ammo, fpsent::attacking, createrays(), vec::dist(), vec::div(), DMF, GUN_BOMB, GUN_PISTOL, fpsstate::gunselect, fpsstate::gunwait, hits, fpsent::lastaction, fpsent::lastattackgun, lastmillis, maptime, msgsound(), vec::mul(), N_SHOOT, physent::o, offsetray(), player1, fpsstate::quadmillis, RAY_ALPHAPOLY, RAY_CLIPMAT, raycube(), raydamage(), rnd(), S_NOAMMO, shorten(), shoteffects(), fpsstate::skill, fpsent::totalshots, physent::vel, and weaponswitch().
Referenced by ai::logic(), and updateweapons().
void game::shorten (vec & from, vec & target, float dist)
References vec::add(), f(), inexor::rpc::min(), vec::mul(), and vec::sub().
Referenced by raydamage(), and shoot().
void game::shoteffects (int gun, const vec & from, const vec & to, fpsent * d, bool local, int id, int prevaction)
References vec::add(), adddecal(), adddynlight(), fpsent::attackchan, fpsent::attacksound, BNC_BOMB, BNC_GRENADE, fpsstate::bombdelay, createrays(), DECAL_BULLET, vec::dist(), DL_FLASH, ENT_AI, ENT_PLAYER, f(), GUN_BOMB, GUN_CG, GUN_FIREBALL, GUN_FIST, GUN_GL, GUN_ICEBALL, GUN_PISTOL, GUN_RIFLE, GUN_RL, GUN_SG, GUN_SLIMEBALL, hudgunorigin(), hudplayer(), fpsent::idlesound, lastmillis, loopi(), fpsent::muzzle, newbouncer(), newprojectile(), physent::o, PART_MUZZLE_FLASH1, PART_MUZZLE_FLASH2, PART_MUZZLE_FLASH3, PART_SMOKE, PART_SPARK, PART_STREAK, particle_flare(), particle_splash(), particle_trail(), inexor::sound::playsound(), fpsstate::quadmillis, rays, S_CHAINSAW_ATTACK, S_ITEMPUP, inexor::sound::sound(), fpsent::stopattacksound(), fpsent::stopidlesound(), and physent::type.
Referenced by parsemessages(), and shoot().
void game::showscores (bool on)
References scoreboard, and game::scoreboardgui::show().
Referenced by deathstate(), edittoggled(), parsemessages(), startgame(), and timeupdate().
void game::spawnbouncer (const vec & p, const vec & vel, fpsent * d, int type, entitylight * light = nullptr)
References vec::add(), vec::iszero(), newbouncer(), vec::normalize(), and rnd().
Referenced by explode(), and gibeffect().
void game::spawnnextsplinter (const vec & p, const vec & vel, fpsent * d, int generation)
References vec::add(), BNC_SPLINTER, BOMB_DAMRAD, fpsstate::bombradius, f(), newbouncer(), and rnd().
Referenced by explodeeffects(), and updatebouncers().
void game::spawnplayer (fpsent * d)
spawn yourself im the game world, also called for monsters/AI in singleplayer of course not used for other players in multiplayer because everyone determins his spawn point for himself.
See Also
spawnstate
References cmode, CS_ALIVE, CS_EDITING, CS_SPECTATOR, editmode, findplayerspawn(), game::clientmode::pickspawn(), player1, respawnent, spawnstate(), and physent::state.
void game::spawnsplinters (const vec & p, fpsent * d)
References vec::add(), BNC_SPLINTER, BOMB_DAMRAD, fpsstate::bombradius, f(), and newbouncer().
Referenced by explodeeffects(), and updatebouncers().
fpsent* game::spawnstate (fpsent * d)
reset player state not persistent accross spawns
Parameters
d the affected fpsent ("player"/"monster"/"bot")
References hmap::d, gamemode, fpsent::respawn(), and fpsstate::spawnstate().
Referenced by initclient(), and spawnplayer().
void game::stackmovable (movable * d, physent * o)
References physent::o, game::movable::stacked, and game::movable::stackpos.
Referenced by dynentcollide().
void game::startgame ()
clear all game data to start a new game
execute cube script map start macro
References clearbouncers(), clearmovables(), clearprojectiles(), clearragdolls(), clearteaminfo(), cmode, hmap::d, fpsent::deaths, disablezoom(), execute(), fpsent::flags, fpsent::frags, inexor::util::log_manager::game, gamemode, identexists(), intermission, lasthit, fpsent::lifesequence, Log, loopv, maplimit, maprealtime, maptime, fpsstate::maxhealth, modename(), player1, playermodel, fpsent::playermodel, players, game::clientmode::preload(), fpsent::respawned, setclientmode(), game::clientmode::setup(), showscores(), fpsent::suicided, switchplayermodel(), fpsent::totaldamage, and fpsent::totalshots.
Referenced by changemapserv().
void game::startmap (const char * name)
called just after a map load send CRC32 to server
See Also
sendmapinfo
send CRC32 checksum of my current map yeah if you would like to cheat this is the code passage you must modify you little ****** *
References ai::clearwaypoints(), clientmap, copystring(), findplayerspawn(), player1, entities::resetspawns(), respawnent, ai::savewaypoints(), sendmapinfo(), and startmap().
Referenced by startmap().
void game::stopdemo ()
References addmsg(), N_STOPDEMO, player1, PRIV_MASTER, and fpsent::privilege.
void game::stopfollowing ()
stop spectating a specific player and start free camery fly
References followdir, following, Log, and inexor::util::log_manager::std.
Referenced by clientdisconnected(), gamedisconnect(), nextfollow(), and parsemessages().
void game::suicide (physent * d)
suicide your player
References addmsg(), CS_ALIVE, ENT_INANIMATE, ENT_PLAYER, lastmillis, fpsent::lifesequence, N_SUICIDE, player1, physent::state, fpsent::suicided, suicidemovable(), and physent::type.
Referenced by moveplayer(), and ai::timeouts().
void game::suicidemovable (movable * m)
References game::movable::suicide().
Referenced by suicide().
game::SVARP (hudgunsdir , "")
void game::swayhudgun (int curtime)
References vec::add(), CS_SPECTATOR, hmap::d, f(), physent::falling, hudplayer(), vec::magnitude(), inexor::rpc::max(), physent::maxspeed, inexor::rpc::min(), vec::mul(), PHYS_SLOPE, physent::physstate, physent::state, swaydir, swaydist, swayfade, swayspeed, and physent::vel.
Referenced by updateworld().
void game::switchname (const char * name, const char * tag)
team, name and playermodel settings
change own nick name
Parameters
name my new nickname
tag is clantag of the player
See Also
filtertext
References addmsg(), copystring(), filtertext(), MAXNAMELEN, MAXTAGLEN, N_SWITCHNAME, fpsent::name, player1, and fpsent::tag.
void game::switchplayermodel (int playermodel)
switch my player model (inky, ogro..)
See Also
addmsg
References addmsg(), N_SWITCHMODEL, player1, playermodel, and fpsent::playermodel.
Referenced by startgame().
void game::switchteam (const char * team)
switch own team
See Also
filtertext
References addmsg(), fpsent::clientnum, filtertext(), MAXTEAMLEN, N_SWITCHTEAM, player1, and fpsent::team.
void game::taunt ()
send taunt network animation message to server taunt animation is this "im gonna kill you" gesture that can be seen by other players
References addmsg(), CS_ALIVE, lastmillis, fpsent::lasttaunt, N_TAUNT, PHYS_SLOPE, physent::physstate, player1, and physent::state.
const char * game::teamcolor (const char * name, bool sameteam, const char * alt)
color player name blue if you have the same team f1 otherwise red f3
Warning
not safe.
References m_teammode, and tempformatstring().
Referenced by game::collectclientmode::deposittokens(), game::ctfclientmode::scoreflag(), game::captureclientmode::setscore(), game::collectclientmode::stealtoken(), game::ctfclientmode::takeflag(), game::ctfclientmode::teamcolorflag(), and game::captureclientmode::updatebase().
const char * game::teamcolor (const char * name, const char * team, const char * alt)
this function calls the function above but also validates that team is a valid char pointer it is not possible to return memory to an invalid char* pointer!7
See Also
teamcolor
References isteam, player1, and fpsent::team.
const char * game::teamcolorname (fpsent * d, const char * alt)
color name depending on my team in red or blue
References COL_BLUE, COL_RED, colorname(), isteam, m_teammode, player1, and fpsent::team.
Referenced by game::collectclientmode::deposittokens(), game::ctfclientmode::dropflag(), killed(), game::ctfclientmode::returnflag(), game::ctfclientmode::scoreflag(), game::collectclientmode::stealtoken(), and game::ctfclientmode::takeflag().
void game::timeupdate (int secs)
update game session time display intermission statistics in console
References fpsent::attacking, cmode, fpsent::deaths, disablezoom(), execute(), fpsent::flags, fpsent::frags, inexor::util::log_manager::game, game::clientmode::gameover(), identexists(), intermission, lastmillis, Log, m_collect, m_ctf, maplimit, inexor::rpc::max(), player1, showscores(), fpsent::totaldamage, and fpsent::totalshots.
Referenced by parsemessages().
void game::togglespectator (int val, const char * who)
toggle own spectator or put player into spectator (permissions requred)
References addmsg(), fpsent::clientnum, N_SPECTATOR, parseplayer(), and player1.
void game::toserver (char * text)
send chat messages to server
References addmsg(), inexor::util::log_manager::chat, COL_GREEN, colorname(), Log, N_TEXT, and player1.
Referenced by hline::run().
void game::triggerplatform (int tag, int newdir)
References CS_ALIVE, game::movable::dir, ELEVATOR, game::movable::etype, loopv, inexor::rpc::max(), physent::maxspeed, inexor::rpc::min(), movables, vec::mul(), vec::neg(), PLATFORM, physent::state, game::movable::tag, vecfromyawpitch(), physent::vel, and physent::yaw.
void game::unignore (int cn)
stop ignoring all chat messages from a certain client number
References hmap::d, vector< T, MINSIZE >::find(), inexor::util::log_manager::game, getclient(), ignores, Log, fpsent::name, and vector< T, MINSIZE >::removeobj().
Referenced by clientdisconnected().
void game::updatebouncers (int time)
References vec::add(), adddecal(), addmsg(), BNC_BOMB, BNC_GRENADE, BNC_SPLINTER, fpsstate::bombradius, bounce(), bouncers, game::bouncer::bouncetype, DECAL_SCORCH, explode(), f(), game::bouncer::generation, GUN_BOMB, GUN_GL, GUN_SPLINTER, hits, game::bouncer::id, lastmillis, game::bouncer::lifetime, game::bouncer::local, loopv, vec::magnitude(), maptime, inexor::rpc::max(), inexor::rpc::min(), vec::mul(), N_EXPLODE, physent::o, game::bouncer::offset, game::bouncer::offsetmillis, OFFSETMILLIS, game::bouncer::owner, PART_SMOKE, PART_SPARK, particle_splash(), fpsstate::quadmillis, RAD, regular_particle_splash(), game::bouncer::roll, spawnnextsplinter(), spawnsplinters(), vec::sub(), and physent::vel.
Referenced by updateweapons().
void game::updatemovables (int curtime)
References adddecal(), CS_ALIVE, DECAL_SCORCH, ELEVATOR, game::movable::etype, game::movable::explode(), game::movable::exploding, GUN_BARREL, guns, vec::iszero(), lastmillis, loopv, physent::maymove(), inexor::rpc::min(), movables, moveplatform(), moveplayer(), vec::mul(), vec::neg(), physent::o, physsteps, PLATFORM, game::movable::stacked, game::movable::stackpos, physent::state, game::movable::tag, and physent::vel.
Referenced by updateworld().
void game::updatepos (fpsent * d)
References physent::aboveeye, CS_DEAD, CS_SPAWNING, CS_SPECTATOR, physent::eyeheight, fpsent::lastupdate, physent::o, fpsent::plag, player1, physent::radius, physent::state, recorder::state, and totalmillis.
Referenced by parsepositions().
void game::updateprojectiles (int time)
References vec::add(), addmsg(), hmap::br, gle::color(), game::projectile::dir, vec::dist(), ENT_AI, f(), game::projectile::gun, hits, game::projectile::id, iterdynents(), lastmillis, game::projectile::local, loopj, loopv, maptime, inexor::rpc::max(), MONSTERDAMAGEFACTOR, vec::mul(), N_EXPLODE, numdynents(), game::projectile::o, physent::o, game::projectile::offset, game::projectile::offsetmillis, OFFSETMILLIS, game::projectile::owner, PART_FIREBALL1, PART_SMOKE, particle_splash(), projdamage(), projsplash(), fpsstate::quadmillis, physent::radius, RAY_ALPHAPOLY, RAY_CLIPMAT, raycubepos(), regular_particle_splash(), vec::reject(), vector< T, MINSIZE >::remove(), game::projectile::speed, game::projectile::to, and physent::type.
Referenced by updateweapons().
void game::updateweapons (int curtime)
References checkattacksound(), checkidlesound(), fpsent::clientnum, CS_ALIVE, hmap::d, following, followingplayer(), loopv, player1, players, shoot(), physent::state, updatebouncers(), updateprojectiles(), and worldpos.
Referenced by updateworld().
void game::updateworld ()
called in game loop to the update game world
References c2sinfo(), game::clientmode::checkitems(), entities::checkitems(), entities::checkquad(), cleanragdoll(), fpsent::clientnum, cmode, connected, CS_DEAD, CS_SPECTATOR, curtime, gets2c(), intermission, lastmillis, fpsent::lastpain, maprealtime, maptime, physent::move, moveplayer(), moveragdoll(), moveragdolls(), ai::navigate(), otherplayers(), physicsframe(), player1, fpsstate::quadmillis, dynent::ragdoll, physent::state, physent::strafe, swayhudgun(), totalmillis, ai::update(), updatemovables(), and updateweapons().
Referenced by main().
game::VAR (testquad , 0 , 0 , 1)
game::VAR (testarmour , 0 , 0 , 1)
game::VAR (testteam , 0 , 0 , 3)
game::VAR (testhudgun , 0 , 0 , 1)
game::VARFN (scoreboard , showscoreboard , 0 , 0 , 1 , scoreboard. showshowscoreboard!=0)
game::VARFP (playermodel , 0 , 0 , 4 , changedplayermodel())
game::VARP (scoreboard2d , 0 , 1 , 1)
game::VARP (showservinfo , 0 , 1 , 1)
game::VARP (showclientnum , 0 , 0 , 1)
game::VARP (showpj , 0 , 0 , 1)
game::VARP (capturetether , 0 , 1 , 1)
game::VARP (autorepammo , 0 , 1 , 1)
game::VARP (showping , 0 , 1 , 1)
game::VARP (showbombs , 0 , 1 , 1)
game::VARP (showspectators , 0 , 1 , 1)
game::VARP (basenumbers , 0 , 0 , 1)
game::VARP (showflags , 0 , 0 , 1)
game::VARP (showbombradius , 0 , 1 , 1)
game::VARP (showbombdelay , 0 , 1 , 1)
game::VARP (showfrags , 0 , 1 , 1)
game::VARP (showminimapobstacles , 0 , 1 , 1)
game::VARP (showaccuracy , 0 , 1 , 1)
game::VARP (highlightscore , 0 , 1 , 1)
game::VARP (showconnecting , 0 , 0 , 1)
game::VARP (ragdoll , 0 , 1 , 1)
game::VARP (ragdollmillis , 0 , 10000 , 300000)
game::VARP (ragdollfade , 0 , 1000 , 300000)
game::VARP (forceplayermodels , 0 , 0 , 1)
game::VARP (hidedead , 0 , 0 , 1)
game::VARP (maxdebris , 10 , 25 , 1000)
game::VARP (maxbarreldebris , 5 , 10 , 1000)
game::VARP (minradarscale , 0 , 384 , 10000)
minimap and radar
radar and minimap settings
game::VARP (maxradarscale , 1 , 1024 , 10000)
game::VARP (radarteammates , 0 , 1 , 1)
game::VARP (teamskins , 0 , 0 , 1)
game::VARP (deadpush , 1 , 2 , 20)
push dead bodies (?)
game::VARP (smoothmove , 0 , 75 , 100)
interpolation factor for player positions low smoothmove means jumpily player movement
game::VARP (smoothdist , 0 , 32 , 64)
distance in which interpolation will be applied (?)
game::VARP (hudgun , 0 , 1 , 1)
game::VARP (hudgunsway , 0 , 1 , 1)
game::VARP (teamhudguns , 0 , 1 , 1)
game::VARP (chainsawhudgun , 0 , 1 , 1)
game::VARP (spawnwait , 0 , 0 , 1000)
game::VARP (blood , 0 , 1 , 1)
game::VARP (hitsound , 0 , 0 , 1)
game::VARP (deathscore , 0 , 1 , 1)
game::VARP (teamcolorfrags , 0 , 1 , 1)
highlight frags in team colors
game::VARP (showmodeinfo , 0 , 1 , 1)
show game mode description text during map load
game::VARP (muzzleflash , 0 , 1 , 1)
game::VARP (muzzlelight , 0 , 1 , 1)
game::VARP (teamcolortext , 0 , 1 , 1)
color team names in frag notifications in game console in red/blue, depending on my team
game::VARP (ammohud , 0 , 1 , 1)
decide if you want to display the little icons of your other weapons in the slot
game::VARP (bombcolliderad , 0 , 16 , 1000)
game::VARP (bombbarrier , 0 , 1 , 1)
game::VARP (teamcrosshair , 0 , 1 , 1)
use blue blocking crosshair when pointing at a teamate
game::VARP (hitcrosshair , 0 , 425 , 1000)
displaying a hit crosshair increases the players hit impression ('feel')
void game::vartrigger (ident * id)
change map vars in edit mode in multiplayer
access memory storage union depending on var type
print my own change as well
References addmsg(), ID_FVAR, ID_SVAR, ID_VAR, m_edit, N_EDITVAR, ident::name, player1, printvar(), and ident::type.
Referenced by setfvarchecked(), setsvarchecked(), and setvarchecked().
bool game::weaponcollide (physent * d, const vec & dir)
References physent::aboveeye, BNC_BOMB, bouncers, game::bouncer::bouncetype, ellipsecollide(), f(), loopv, physent::o, RAY_CLIPMAT, raycube(), and physent::yaw.
Referenced by mmcollide().
void game::weaponswitch (fpsent * d)
References CS_ALIVE, GUN_BOMB, GUN_CG, GUN_GL, GUN_PISTOL, GUN_RIFLE, GUN_RL, GUN_SG, and gunselect().
Referenced by shoot().
void game::writeclientinfo (stream * f)
write my player name to a stream
See Also
escapestring
References escapestring(), fpsent::name, player1, and stream::printf().
Referenced by writecfg().
void game::writegamedata (vector< char > & extras)
Referenced by save_world().
Variable Documentation
int game::ammohudcycle[8] = { -1, -1, -1, -1, -1, -1, -1, -1 }
int game::ammohuddown[3] = { GUN_RIFLE, GUN_SG, GUN_PISTOL }
int game::ammohudup[3] = { GUN_CG, GUN_RL, GUN_GL }
this static data is used to describe the sorting of the 3 next weapons in your holster preview.
Referenced by drawammohud().
vector<fpsent *> game::bestplayers
Referenced by rendergame(), and renderplayer().
vector<const char *> game::bestteams
Referenced by rendergame(), and renderplayer().
bombclientmode game::bombmode
Referenced by server::changemap(), and setclientmode().
vector< bouncer * > game::bouncers
Referenced by adddynlights(), avoidweapons(), clearbouncers(), game::bombclientmode::drawhud(), explode(), explodeeffects(), newbouncer(), removebouncers(), renderbouncers(), updatebouncers(), and weaponcollide().
captureclientmode game::capturemode
Referenced by server::changemap(), and setclientmode().
SharedVar<int> game::chainsawhudgun
Referenced by checkattacksound(), checkidlesound(), and drawhudmodel().
string game::clientmap = ""
Referenced by gamedisconnect(), getclientmap(), and startmap().
vector< fpsent * > game::clients
other clients connected to this server
Referenced by aiman::addai(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::any_writes_outstanding(), aiman::calcteams(), aiman::changemap(), clearclients(), clientdisconnected(), aiman::deleteai(), aiman::findaiclient(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::finish_disconnect_client(), getclient(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::handle_new_connection(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::kickoff_writes(), listclients(), newclient(), nextfollow(), parseplayer(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::pick_unused_id(), aiman::reassignai(), sayprivate(), and inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::~RpcServer().
clientmode * game::cmode = nullptr
gamemodes
Referenced by ai::check(), clientdisconnected(), clipconsole(), ai::dodefend(), ai::dopursue(), ai::find(), gameplayhud(), getbestteams(), groupplayers(), killed(), ai::logic(), parsemessages(), rendergame(), renderscoreboard(), respawn(), sendmessages(), setclientmode(), spawnplayer(), startgame(), ai::think(), timeupdate(), and updateworld().
collectclientmode game::collectmode
Referenced by setclientmode().
bool game::connected = false
Referenced by server::add_client_connection(), addmsg(), canjump(), changegamespeed(), doattack(), gamedisconnect(), listclients(), parsemessages(), sendmapinfo(), sendpacket(), and updateworld().
string game::connectmapwish = ""
Referenced by connectattempt(), connectfail(), and sendintro().
int game::connectmodewish = -1
Referenced by connectattempt(), connectfail(), and sendintro().
string game::connectpass = ""
Referenced by connectattempt(), connectfail(), and sendintro().
ctfclientmode game::ctfmode
Referenced by server::changemap(), and setclientmode().
SharedVar<int> game::deathscore
Referenced by deathstate(), and parsemessages().
const char* const game::debrisnames[4] = { "particle/debris/debris01", "particle/debris/debris02", "particle/debris/debris03", "particle/debris/debris04" } static
bool game::demoplayback = false
Referenced by gamedisconnect(), parsemessages(), and renderscoreboard().
int game::followdir = 0
Referenced by clientdisconnected(), follow(), nextfollow(), and stopfollowing().
int game::following = -1
Referenced by clientdisconnected(), follow(), followingplayer(), game::bombclientmode::killed(), nextfollow(), parsemessages(), stopfollowing(), and updateweapons().
bool game::gamepaused = false
Referenced by allowmouselook(), gamedisconnect(), ispaused(), and parsemessages().
int game::gamespeed = 100
Referenced by gamedisconnect(), main(), parsemessages(), physicsframe(), renderscoreboard(), and scaletime().
const char* const game::gibnames[3] = { "particle/gibs/gib01", "particle/gibs/gib02", "particle/gibs/gib03" } static
vector<scoregroup *> game::groups static
Referenced by groupplayers(), and renderscoreboard().
game::hudent game::guninterp
Referenced by drawhudmodel().
hideandseekclientmode game::hideandseekmode
Referenced by server::changemap(), and setclientmode().
vector<hitmsg> game::hits
Referenced by hit(), server::parsepacket(), raydamage(), shoot(), updatebouncers(), and updateprojectiles().
vector<int> game::ignores
a vector of ignored client numbers (cns)
Referenced by gamedisconnect(), ignore(), isignored(), and unignore().
bool game::intermission = false
other clients
Referenced by canjump(), ai::canmove(), damaged(), doattack(), game::bombclientmode::drawhud(), killed(), ai::logic(), otherplayers(), rendergame(), renderplayer(), renderscoreboard(), startgame(), timeupdate(), ai::update(), and updateworld().
float game::intersectdist = 1e16f
int game::lasthit = 0
Referenced by damaged(), hit(), parsemessages(), selectcrosshair(), and startgame().
int game::lastping = 0
Referenced by sendmessages().
int game::lastspawnattempt = 0
Referenced by game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), and respawn().
int game::maplimit = -1
Referenced by renderscoreboard(), startgame(), and timeupdate().
int game::maprealtime = 0
Referenced by startgame(), and updateworld().
int game::maptime = 0
Referenced by game::hideandseekclientmode::isinvisible(), renderscoreboard(), shoot(), startgame(), updatebouncers(), updateprojectiles(), and updateworld().
int game::mastermode = MM_OPEN
Referenced by gamedisconnect(), and parsemessages().
int game::messagecn = -1
Referenced by addmsg(), gamedisconnect(), and sendmessages().
int game::messagereliable = false
Referenced by addmsg(), gamedisconnect(), and sendmessages().
vector< uchar > game::messages
collect client to server messages conveniently
Referenced by addmsg(), edittrigger(), gamedisconnect(), and sendmessages().
SharedVar<float> game::minimapalpha
Referenced by game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), and game::captureclientmode::drawhud().
const int game::MONSTERDAMAGEFACTOR = 4 static
Referenced by raydamage(), and updateprojectiles().
vector< movable * > game::movables
Referenced by clearmovables(), game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), iterdynents(), numdynents(), rendermovables(), triggerplatform(), and updatemovables().
int game::needclipboard = -1
?
Referenced by edittrigger(), parsemessages(), sendclipboard(), and sendmap().
int game::nextmode = INT_MAX
Referenced by changemap(), changemapserv(), connectfail(), gamedisconnect(), sendintro(), and setmode().
const int game::OFFSETMILLIS = 500 static
Referenced by adddynlights(), explodeeffects(), newbouncer(), newprojectile(), renderbouncers(), renderprojectiles(), updatebouncers(), and updateprojectiles().
int game::paused
fpsent * game::player1 = nullptr
Referenced by addmsg(), ai::avoid(), game::collectclientmode::baseeffect(), game::collectclientmode::baseexplosion(), broadcastfov(), canjump(), changedplayermodel(), game::captureclientmode::checkitems(), entities::checkquad(), entities::checktriggers(), ai::cleanwaypoints(), cleardemos(), collidecamera(), colorname(), cycleweapon(), damaged(), deathstate(), ai::delselwaypoints(), game::collectclientmode::deposittokens(), doattack(), game::collectclientmode::drawbaseblip(), game::ctfclientmode::drawblip(), game::captureclientmode::drawblips(), game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), drawhudgun(), drawhudmodel(), game::collectclientmode::droptoken(), duplicatename(), edittoggled(), entities::fixentity(), game::ctfclientmode::flageffect(), game::ctfclientmode::flagexplosion(), follow(), followingplayer(), gamedisconnect(), gameplayhud(), getclient(), getclienticon(), getplayermodelinfo(), gotoplayer(), gotosel(), hashpwd(), hit(), hudplayer(), ignore(), ai::init(), initclient(), game::hideandseekclientmode::isinvisible(), entities::jumppadeffects(), kick(), game::bombclientmode::killed(), killed(), listclients(), ai::movewaypoints(), msgsound(), newclient(), nextfollow(), nextweapon(), otherplayers(), game::collectclientmode::parse_network_message(), game::captureclientmode::parse_network_message(), game::ctfclientmode::parse_network_message(), game::ctfclientmode::parseflags(), parsemessages(), parseplayer(), parsestate(), game::collectclientmode::parsetokens(), physicstrigger(), game::hideandseekclientmode::pickspawn(), entities::pickupeffects(), pointatplayer(), preloadweapons(), printname(), printteam(), game::captureclientmode::receiveammo(), recorddemo(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), game::ctfclientmode::rendergame(), rendergame(), game::bombclientmode::renderplayersposindicator(), renderscoreboard(), game::captureclientmode::rendertether(), game::captureclientmode::replenishammo(), respawn(), respawnself(), saveragdoll(), sayprivate(), sayteam(), game::ctfclientmode::scoreflag(), sendintro(), sendmap(), sendmapinfo(), sendpositions(), setmaster(), game::captureclientmode::setscore(), setupcamera(), setweapon(), shoot(), spawnplayer(), startgame(), startmap(), game::collectclientmode::stealtoken(), stopdemo(), game::movable::suicide(), suicide(), switchname(), switchplayermodel(), switchteam(), game::collectclientmode::taketoken(), taunt(), teamcolor(), teamcolorname(), entities::teleporteffects(), timeupdate(), togglespectator(), toserver(), game::ctfclientmode::trydropflag(), entities::trypickup(), game::captureclientmode::updatebase(), updatepos(), updateweapons(), updateworld(), vartrigger(), and writeclientinfo().
SharedVar<int> game::playermodel
Referenced by changedplayermodel(), getplayermodelinfo(), preloadplayermodel(), saveragdoll(), startgame(), and switchplayermodel().
const playermodelinfo game::playermodels[2] static
Initial value:
=
    {
        { "player/mrfixit2", "player/mrfixit2/blue", "player/mrfixit2/red", "player/mrfixit2/hudgun", nullptr, "player/mrfixit2/horns", { "player/mrfixit2/armor/blue", "player/mrfixit2/armor/green", "player/mrfixit2/armor/yellow" }, "mrfixit2", "mrfixit2_blue", "mrfixit2_red", true },
        { "player/ironsnoutx10k", "player/ironsnoutx10k/blue", "player/ironsnoutx10k/red", "player/ironsnoutx10k/hudgun", nullptr, "player/ironsnoutx10k/wings", { "player/ironsnoutx10k/armor/blue", "player/ironsnoutx10k/armor/green", "player/ironsnoutx10k/armor/yellow" }, "ironsnoutx10k", "ironsnoutx10k_blue", "ironsnoutx10k_red", true },
    }
Referenced by chooserandomplayermodel(), getplayermodelinfo(), and preloadplayermodel().
vector< fpsent * > game::players
our client
Referenced by game::ctfclientmode::addflag(), ai::assist(), ai::avoid(), changedplayermodel(), ai::checkothers(), ai::cleanwaypoints(), clientdisconnected(), game::hideandseekclientmode::drawhud(), game::bombclientmode::drawhud(), game::collectclientmode::drawhud(), drawteammates(), game::ctfclientmode::dropflag(), duplicatename(), ai::enemy(), getbestplayers(), getbestteams(), groupplayers(), initclient(), ai::itemspawned(), iterdynents(), ai::navigate(), newclient(), numdynents(), otherplayers(), game::ctfclientmode::ownflag(), parsemessages(), parseplayer(), pointatplayer(), ai::render(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), game::ctfclientmode::rendergame(), rendergame(), game::bombclientmode::renderplayersposindicator(), renderscoreboard(), game::ctfclientmode::returnflag(), sendpositions(), ai::shouldnavigate(), startgame(), ai::target(), ai::update(), and updateweapons().
const char* const game::projnames[3] = { "projectile/grenade", "projectile/rocket", "projectile/bomb" } static
vector< projectile > game::projs
Referenced by avoidweapons(), and renderprojectiles().
vector<fpsent *> game::ragdolls
Referenced by changedplayermodel(), clearragdolls(), moveragdolls(), rendergame(), and saveragdoll().
vec game::rays[MAXRAYS]
Referenced by calcocclusion(), calcskylight(), createrays(), fastskylight(), hitpush(), server::shotevent::process(), raydamage(), and shoteffects().
int game::respawnent = -1
Referenced by spawnplayer(), startmap(), and entities::trypickup().
int game::savedammo[NUMGUNS]
Referenced by deathstate().
game::scoreboardgui game::scoreboard
Referenced by g3d_gamemenus(), and showscores().
bool game::sendcrc = false
Referenced by gamedisconnect(), sendmapinfo(), and sendmessages().
bool game::senditemstoserver = false
after a map change, since server doesn't have map data
Referenced by changemapserv(), gamedisconnect(), parsemessages(), sendmapinfo(), and sendmessages().
string game::servinfo = ""
Referenced by parsemessages(), and renderscoreboard().
int game::sessionid = 0
Referenced by gamedisconnect(), hashpwd(), parsemessages(), sendintro(), and setmaster().
SharedVar<int> game::showminimapobstacles
Referenced by game::hideandseekclientmode::drawhud(), and game::bombclientmode::drawhud().
SharedVar<int> game::smoothdist
Referenced by parsepositions().
SharedVar<int> game::smoothmove
Referenced by otherplayers(), parsepositions(), and predictplayer().
vector<fpsent *> game::spectators static
Referenced by groupplayers().
vec game::swaydir(0, 0, 0)
Referenced by drawhudmodel(), and swayhudgun().
float game::swaydist = 0
Referenced by drawhudmodel(), and swayhudgun().
float game::swayfade = 0
Referenced by swayhudgun().
float game::swayspeed = 0
Referenced by swayhudgun().
hashset<teaminfo> game::teaminfos static
Referenced by clearteaminfo(), getbestteams(), groupplayers(), and setteaminfo().
SharedVar<int> game::teamskins
Referenced by drawhudmodel(), preloadweapons(), and rendergame().
bool game::teamspersisted = false
Referenced by ispersisted(), and parsemessages().
SharedVar<int> game::testteam
Referenced by drawhudmodel(), and renderplayer().