Inexor: modelpreview Namespace Reference
modelpreview Namespace Reference
Functions
void start (int x, int y, int w, int h, bool background)
void end ()
Variables
physent * oldcamera
physent camera
float oldaspect
float oldfovy
float oldfov
int oldfarplane
Function Documentation
void modelpreview::end ()
References aspect, camera1, curfogcolor, curfov, drawtex, farplane, fovy, oldaspect, oldcamera, oldfarplane, oldfov, oldfovy, resetfogcolor(), resetfogdist(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, and inexor::rendering::screen::ScreenManager::screenw.
Referenced by drawreflection(), gui::modelpreview(), gui::playerpreview(), gui::prefabpreview(), and pushfogdist().
void modelpreview::start (int x, int y, int w, int h, bool background)
References aspect, camera, camera1, clearfogdist(), curfov, drawtex, DRAWTEX_MODELPREVIEW, ENT_CAMERA, farplane, fovy, physent::o, oldaspect, oldcamera, oldfarplane, oldfov, oldfovy, matrix4::perspective(), physent::pitch, projmatrix, RAD, physent::reset(), physent::roll, setcamprojmatrix(), physent::type, physent::yaw, and zerofogcolor().
Referenced by drawreflection(), gui::modelpreview(), gui::playerpreview(), gui::prefabpreview(), and pushfogdist().
Variable Documentation
physent modelpreview::camera
Referenced by rendermaterials(), renderwater(), setupgeom(), and start().
float modelpreview::oldaspect
Referenced by end(), and start().
physent* modelpreview::oldcamera
Referenced by drawcubemap(), drawminimap(), end(), and start().
int modelpreview::oldfarplane
Referenced by end(), and start().
float modelpreview::oldfov
Referenced by end(), and start().
float modelpreview::oldfovy
Referenced by end(), and start().