Inexor: entities Namespace Reference
entities Namespace Reference
Enumerations
enum {
TRIG_COLLIDE = 1<<0, TRIG_TOGGLE = 1<<1, TRIG_ONCE = 0<<2, TRIG_MANY = 1<<2,
TRIG_DISAPPEAR = 1<<3, TRIG_AUTO_RESET = 1<<4, TRIG_RUMBLE = 1<<5, TRIG_LOCKED = 1<<6,
TRIG_ENDSP = 1<<7
}
Functions
int extraentinfosize ()
void writeent (entity &e, char *buf)
void readent (entity &e, char *buf, int ver)
vector< extentity * > & getents ()
bool mayattach (extentity &e)
bool attachent (extentity &e, extentity &a)
const char * itemname (int i)
int itemicon (int i)
const char * entmdlname (int type)
const char * entmodel (const entity &e)
void preloadentities ()
void renderentities ()
void addammo (int type, int &v, bool local)
void repammo (fpsent *d, int type, bool local)
void pickupeffects (int n, fpsent *d)
void teleporteffects (fpsent *d, int tp, int td, bool local)
void jumppadeffects (fpsent *d, int jp, bool local)
void teleport (int n, fpsent *d)
void trypickup (int n, fpsent *d)
void checkitems (fpsent *d)
void checkquad (int time, fpsent *d)
void putitems (packetbuf &p)
void resetspawns ()
void spawnitems (bool force)
void setspawn (int i, bool on)
extentity * newentity ()
void deleteentity (extentity *e)
void clearents ()
static void cleartriggerflags (extentity &e)
static void setuptriggerflags (fpsentity &e)
void resettriggers ()
void unlocktriggers (int tag, int oldstate=TRIGGER_RESET, int newstate=TRIGGERING)
ICOMMAND (trigger,"ii",(int *tag, int *state),{if(*state) unlocktriggers(*tag);else unlocktriggers(*tag, TRIGGERED, TRIGGER_RESETTING);})
VAR (triggerstate,-1, 0, 1)
void doleveltrigger (int trigger, int state)
void checktriggers ()
void animatemapmodel (const extentity &e, int &anim, int &basetime)
void fixentity (extentity &e)
void entradius (extentity &e, bool color)
bool printent (extentity &e, char *buf, int len)
const char * entnameinfo (entity &e)
const char * entname (int i)
void editent (int i, bool local)
float dropheight (entity &e)
bool hasmapmodel (const extentity &e)
bool delayspawn (int type)
Returns whether the ammo entity gets spawned at mapstart.
Variables
vector< extentity * > ents
static const int NUMTRIGGERTYPES = 32
static const int triggertypes [NUMTRIGGERTYPES]
Enumeration Type Documentation
anonymous enum
Enumerator
TRIG_COLLIDE
TRIG_TOGGLE
TRIG_ONCE
TRIG_MANY
TRIG_DISAPPEAR
TRIG_AUTO_RESET
TRIG_RUMBLE
TRIG_LOCKED
TRIG_ENDSP
Function Documentation
void entities::addammo (int type, int & v, bool local)
References itemstat::add, I_SHELLS, itemstats, itemstat::max, game::msgsound(), and itemstat::sound.
Referenced by repammo().
void entities::animatemapmodel (const extentity & e, int & anim, int & basetime)
References ANIM_END, ANIM_REVERSE, ANIM_START, ANIM_TRIGGER, entity::attr3, f(), fpsentity::lasttrigger, TRIGGER_RESET, TRIGGER_RESETTING, TRIGGERED, TRIGGERING, fpsentity::triggerstate, and validtrigger.
Referenced by rendermapmodel().
bool entities::attachent (extentity & e, extentity & a)
Referenced by attachentity().
void entities::checkitems (fpsent * d)
References CS_ALIVE, vec::dist(), ents, physent::feetpos(), JUMPPAD, loopv, NOTUSED, entity::o, RESPAWNPOINT, extentity::spawned(), physent::state, TELEPORT, trypickup(), and entity::type.
Referenced by ai::logic(), and game::updateworld().
void entities::checkquad (int time, fpsent * d)
References inexor::util::log_manager::game, Log, physent::o, game::player1, inexor::sound::playsound(), fpsstate::quadmillis, and S_PUPOUT.
Referenced by ai::logic(), game::otherplayers(), and game::updateworld().
void entities::checktriggers ()
References entity::attr3, entity::attr4, checktriggertype, CS_ALIVE, vec::dist(), doleveltrigger(), ents, ET_MAPMODEL, physent::feetpos(), lastmillis, fpsentity::lasttrigger, loopv, entity::o, overlapsdynent(), game::player1, inexor::sound::playsound(), physent::radius, S_RUMBLE, setuptriggerflags(), physent::state, TRIG_AUTO_RESET, TRIG_COLLIDE, TRIG_DISAPPEAR, TRIG_ENDSP, TRIG_LOCKED, TRIG_MANY, TRIG_RUMBLE, TRIG_TOGGLE, TRIGGER_DISAPPEARED, TRIGGER_RESET, TRIGGER_RESETTING, TRIGGERED, TRIGGERING, fpsentity::triggerstate, entity::type, unlocktriggers(), and validtrigger.
void entities::clearents ()
References deleteentity(), and ents.
Referenced by resetmap().
static void entities::cleartriggerflags (extentity & e) inline static
References EF_ANIM, EF_NOCOLLIDE, EF_NOSHADOW, EF_NOVIS, and extentity::flags.
Referenced by editent(), and setuptriggerflags().
bool entities::delayspawn (int type) inline
Returns whether the ammo entity gets spawned at mapstart.
References I_BOOST, I_GREENARMOUR, I_QUAD, and I_YELLOWARMOUR.
Referenced by server::loaditems(), server::parsepacket(), and spawnitems().
void entities::deleteentity (extentity * e)
Referenced by clearents(), load_world(), and newentity().
void entities::doleveltrigger (int trigger, int state)
References defformatstring, execute(), identexists(), and recorder::state.
Referenced by checktriggers().
float entities::dropheight (entity & e)
References BASE, FLAG, and entity::type.
Referenced by dropheight().
void entities::editent (int i, bool local)
References game::addmsg(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, cleartriggerflags(), DMF, ents, ET_MAPMODEL, f(), fpsentity::lasttrigger, N_EDITENT, entity::o, setuptriggerflags(), TRIGGER_RESET, fpsentity::triggerstate, entity::type, and validtrigger.
Referenced by mpeditent().
const char * entities::entmdlname (int type)
Referenced by entmodel(), preloadentities(), and game::captureclientmode::rendergame().
const char * entities::entmodel (const entity & e)
References entity::attr2, entmdlname(), mapmodelname(), MAXENTTYPES, TELEPORT, and entity::type.
Referenced by entselectionbox(), and renderentities().
const char * entities::entname (int i)
Referenced by entname(), enttype(), findtype(), load_world(), printent(), and printparticles().
const char * entities::entnameinfo (entity & e)
Referenced by entname().
void entities::entradius (extentity & e, bool color)
References entity::attr1, entity::attr2, entity::attr3, BARREL, BOX, checktriggertype, dir, vec::dist(), ELEVATOR, ents, FLAG, JUMPPAD, loopv, MAPMODEL, MONSTER, vec::normalize(), entity::o, OBSTACLE, PLATFORM, renderentarrow(), renderentring(), RESPAWNPOINT, TELEDEST, TELEPORT, TRIG_COLLIDE, entity::type, validtrigger, and vecfromyawpitch().
Referenced by renderentradius().
int entities::extraentinfosize ()
Referenced by load_world(), and save_world().
void entities::fixentity (extentity & e)
References entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, BARREL, BOX, ELEVATOR, FLAG, MONSTER, OBSTACLE, PLATFORM, game::player1, RESPAWNPOINT, TELEDEST, entity::type, and physent::yaw.
Referenced by newentity().
vector< extentity * > & entities::getents ()
References ents.
Referenced by addparticleemitters(), attachentities(), attachentity(), brightestlight(), checklightcache(), inexor::sound::checkmapsounds(), clearlightcache(), clearlights(), disttoent(), disttooutsideent(), entitiesinoctanodes(), findentity(), findents(), findlights(), findplayerspawn(), freeoctaentities(), getselpos(), guessshadowdir(), initenvmaps(), lightents(), lightreaching(), load_world(), flarerenderer::makelightflares(), mmcollide(), modifyoctaent(), modifyoctaentity(), mpeditent(), nearestent(), newentity(), newundoent(), game::parsemessages(), pasteundoent(), inexor::sound::preloadmapsounds(), preloadusedmapmodels(), rendermapmodels(), renderreflectedmapmodels(), save_world(), shadowent(), shrinkmap(), and updateparticles().
bool entities::hasmapmodel (const extentity & e)
References BARREL, BOX, MAPMODEL, OBSTACLE, and entity::type.
Referenced by getentboundingbox(), and modifyoctaentity().
entities::ICOMMAND (trigger , "ii" , (int *tag, int *state) , {if(*state) unlocktriggers(*tag);else unlocktriggers(*tag, TRIGGERED, TRIGGER_RESETTING);})
int entities::itemicon (int i)
References ents, I_QUAD, I_SHELLS, itemstat::icon, itemstats, and anonymous_namespace{utilTest.cpp}::t().
Referenced by game::parsemessages().
const char * entities::itemname (int i)
References ents, I_QUAD, I_SHELLS, itemstats, itemstat::name, and anonymous_namespace{utilTest.cpp}::t().
Referenced by game::parsemessages().
void entities::jumppadeffects (fpsent * d, int jp, bool local)
References entity::attr4, fpsent::clientnum, ents, packetbuf::finalize(), hmap::flags, flushclient(), JUMPPAD, N_JUMPPAD, entity::o, game::player1, inexor::sound::playsound(), putint(), S_JUMPPAD, sendclientpacket(), game::sendposition(), and SND_MAP.
Referenced by game::parsepositions(), and trypickup().
bool entities::mayattach (extentity & e)
Referenced by attachentity().
extentity * entities::newentity ()
Referenced by load_world(), newentity(), game::parsemessages(), and pasteundoent().
void entities::pickupeffects (int n, fpsent * d)
References physent::abovehead(), ents, inexor::util::log_manager::game, I_BOMBDELAY, I_BOMBRADIUS, I_BOOST, I_QUAD, I_SHELLS, itemstat::icon, isthirdperson(), itemstats, Log, fpsstate::maxhealth, physent::o, PART_HUD_ICON_GREY, particle_icon(), fpsstate::pickup(), game::player1, inexor::sound::playsound(), S_ITEMHEALTH, S_V_BOOST, S_V_QUAD, and inexor::sound::sound().
Referenced by game::parsemessages().
void entities::preloadentities ()
References entity::attr2, entity::attr4, entmdlname(), ents, I_BOMBDELAY, I_BOMBRADIUS, I_BOMBS, I_BOOST, I_BULLETS, I_CARTRIDGES, I_GREENARMOUR, I_GRENADES, I_HEALTH, I_QUAD, I_ROCKETS, I_ROUNDS, I_SHELLS, I_YELLOWARMOUR, JUMPPAD, loopi(), loopv, m_bomb, m_noammo, m_noitems, mapmodelname(), MAXENTTYPES, inexor::sound::preloadmapsound(), preloadmodel(), TELEPORT, and entity::type.
Referenced by game::preload().
bool entities::printent (extentity & e, char * buf, int len)
Referenced by printent().
void entities::putitems (packetbuf & p)
References ents, I_BOMBDELAY, I_BOMBS, I_HEALTH, I_QUAD, I_SHELLS, loopv, m_bomb, m_noammo, N_ITEMLIST, and putint().
Referenced by game::sendmessages().
void entities::readent (entity & e, char * buf, int ver)
References entity::attr1, BARREL, BOX, ELEVATOR, FLAG, MONSTER, OBSTACLE, PLATFORM, RESPAWNPOINT, TELEDEST, and entity::type.
Referenced by load_world(), and loadents().
void entities::renderentities ()
References ANIM_LOOP, ANIM_MAPMODEL, entity::attr2, CARROT, entmodel(), ents, I_QUAD, I_SHELLS, lastmillis, extentity::light, loopv, MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_SHADOW, mdlname(), entity::o, rendermodel(), RESPAWNPOINT, extentity::spawned(), TELEPORT, and entity::type.
Referenced by game::rendergame().
void entities::repammo (fpsent * d, int type, bool local)
References addammo(), fpsstate::ammo, GUN_SG, and I_SHELLS.
Referenced by game::captureclientmode::receiveammo().
void entities::resetspawns ()
References ents, and loopv.
Referenced by game::changemapserv(), and game::startmap().
void entities::resettriggers ()
References entity::attr3, ents, ET_MAPMODEL, fpsentity::lasttrigger, loopv, setuptriggerflags(), TRIGGER_RESET, fpsentity::triggerstate, entity::type, and validtrigger.
void entities::setspawn (int i, bool on)
References ents.
Referenced by game::parsemessages().
static void entities::setuptriggerflags (fpsentity & e) inline static
References entity::attr3, checktriggertype, cleartriggerflags(), EF_ANIM, EF_NOCOLLIDE, EF_NOSHADOW, EF_NOVIS, extentity::flags, lastmillis, fpsentity::lasttrigger, TRIG_COLLIDE, TRIG_DISAPPEAR, TRIGGER_DISAPPEARED, TRIGGERED, TRIGGERING, and fpsentity::triggerstate.
Referenced by checktriggers(), editent(), and resettriggers().
void entities::spawnitems (bool force)
References delayspawn(), ents, I_BOMBDELAY, I_BOMBS, I_HEALTH, I_QUAD, I_SHELLS, loopv, m_bomb, m_noammo, and m_noitems.
Referenced by game::parsemessages(), and game::receivefile().
void entities::teleport (int n, fpsent * d)
References dir, entinmap(), ents, f(), findentity(), ai::inferwaypoints(), Log, vec::magnitude2(), physent::o, inexor::util::log_manager::std, TELEDEST, teleporteffects(), updatedynentcache(), vecfromyawpitch(), physent::vel, and physent::yaw.
Referenced by server::parsepacket(), and trypickup().
void entities::teleporteffects (fpsent * d, int tp, int td, bool local)
References entity::attr4, fpsent::clientnum, ents, packetbuf::finalize(), hmap::flags, flushclient(), N_TELEPORT, entity::o, game::player1, inexor::sound::playsound(), putint(), S_TELEPORT, sendclientpacket(), game::sendposition(), SND_MAP, TELEDEST, and TELEPORT.
Referenced by game::parsepositions(), and teleport().
void entities::trypickup (int n, fpsent * d)
References game::addmsg(), fpsent::ai, ai::aiinfo::becareful, fpsstate::canpickup(), defformatstring, ents, execute(), f(), physent::falling, inexor::util::log_manager::game, identexists(), JUMPPAD, jumppadeffects(), lastmillis, fpsent::lastpickup, fpsent::lastpickupmillis, Log, N_ITEMPICKUP, PHYS_FALL, physent::physstate, game::player1, inexor::sound::playsound(), game::respawnent, RESPAWNPOINT, S_V_RESPAWNPOINT, TELEPORT, teleport(), physent::timeinair, and physent::vel.
Referenced by checkitems().
void entities::unlocktriggers (int tag, int oldstate = TRIGGER_RESET, int newstate = TRIGGERING)
References entity::attr3, entity::attr4, checktriggertype, ents, ET_MAPMODEL, lastmillis, fpsentity::lasttrigger, loopv, entity::o, overlapsdynent(), inexor::sound::playsound(), S_RUMBLE, TRIG_COLLIDE, TRIG_LOCKED, TRIG_RUMBLE, TRIGGER_RESETTING, fpsentity::triggerstate, entity::type, and validtrigger.
Referenced by checktriggers().
entities::VAR (triggerstate , - 1, 0 , 1)
void entities::writeent (entity & e, char * buf)
Referenced by save_world().
Variable Documentation
vector< extentity * > entities::ents
Referenced by addparticleemitters(), attachentities(), attachentity(), brightestlight(), checkitems(), checklightcache(), inexor::sound::checkmapsounds(), checktriggers(), clearents(), clearlights(), game::clearmovables(), disttoent(), disttooutsideent(), ai::dodefend(), ai::dointerest(), editent(), entitiesinoctanodes(), entradius(), ai::find(), findentity(), findents(), findlights(), findplayerspawn(), getents(), getselpos(), guessshadowdir(), initenvmaps(), itemicon(), itemname(), ai::items(), ai::itemspawned(), jumppadeffects(), ai::jumpto(), lightents(), lightreaching(), load_world(), flarerenderer::makelightflares(), mmcollide(), modifyoctaent(), moveplatform(), mpeditent(), nearestent(), newentity(), game::parsemessages(), pasteundoent(), game::ctfclientmode::pickholdspawn(), game::bombclientmode::pickspawn(), game::captureclientmode::pickteamspawn(), pickupeffects(), preloadentities(), inexor::sound::preloadmapsounds(), preloadusedmapmodels(), putitems(), renderentities(), rendermapmodels(), renderreflectedmapmodels(), resetspawns(), resettriggers(), save_world(), ai::seedwaypoints(), game::bombclientmode::senditems(), setspawn(), game::collectclientmode::setup(), game::ctfclientmode::setup(), game::captureclientmode::setup(), shadowent(), shrinkmap(), spawnitems(), teleport(), teleporteffects(), ai::timeouts(), trypickup(), unlocktriggers(), and updateparticles().
const int entities::NUMTRIGGERTYPES = 32 static
const int entities::triggertypes[NUMTRIGGERTYPES] static