Inexor: inexor/server/network_send.cpp File Reference
network_send.cpp File Reference
#include <ctype.h>
#include <stdarg.h>
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/network/legacy/cube_network.hpp"
#include "inexor/network/legacy/game_types.hpp"
#include "inexor/server/client_management.hpp"
#include "inexor/server/demos.hpp"
#include "inexor/server/network_send.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/fpsgame/server.hpp"
Functions
void sendpacket (int n, int chan, ENetPacket *packet, int exclude)
ENetPacket * sendf (int cn, int chan, const char *format,...)
void sendservmsg (const char *s)
void sendservmsgf (const char *fmt,...)
ENetPacket * sendfile (int cn, int chan, stream *file, const char *format,...)
Function Documentation
ENetPacket* sendf (int cn, int chan, const char * format, ...)
References packetbuf::finalize(), format(), loopi(), MAXTRANS, packetbuf::put(), putfloat(), putint(), sendpacket(), and sendstring().
Referenced by server::captureservermode::addscore(), server::hideandseekservermode::announceseekers(), server::autoteam(), aiman::balanceteams(), server::bombservermode::canspawn(), server::change_mastermode(), server::changegamespeed(), server::changemap(), server::checkintermission(), server::checkmaps(), aiman::deleteai(), server::collectservermode::deposittokens(), server::bombservermode::died(), server::hideandseekservermode::died(), server::disconnect_client(), server::dodamage(), server::ctfservermode::dropflag(), server::captureservermode::endcheck(), server::enddemoplayback(), server::forcespectator(), server::parsepacket(), server::pausegame(), server::persistteams(), server::pickup(), server::player_connected(), server::shotevent::process(), server::explodeevent::process(), server::bombservermode::pushentity(), server::receivefile(), server::captureservermode::regenowners(), aiman::reinitai(), server::captureservermode::replenishammo(), aiman::reqadd(), aiman::reqdel(), server::ctfservermode::scoreflag(), server::captureservermode::sendbaseinfo(), server::senddemo(), server::sendresume(), server::sendservinfo(), sendservmsg(), sendservmsgf(), server::sendspawn(), server::bombservermode::sendspawnlocs(), server::serverupdate(), server::hideandseekservermode::sethider(), server::setmaster(), server::hideandseekservermode::setseeker(), server::setupdemoplayback(), server::ctfservermode::setupholdspawns(), server::suicide(), server::ctfservermode::takeflag(), server::collectservermode::taketoken(), server::unspectate(), server::collectservermode::update(), server::ctfservermode::update(), server::bombservermode::updatelimbo(), and server::vote().
ENetPacket* sendfile (int cn, int chan, stream * file, const char * format, ...)
References server::client_connections, make_file_packet(), and sendpacket().
Referenced by server::parsepacket().
void sendpacket (int n, int chan, ENetPacket * packet, int exclude)
References server::allowbroadcast(), server::client_connections, game::connected, loopv, server::recordpacket(), and sendpacket().
Referenced by server::collectservermode::droptokens(), server::flushclientposition(), server::collectservermode::leavegame(), server::listdemos(), server::parsepacket(), server::readdemo(), server::captureservermode::sendbases(), server::sendclipboard(), sendf(), sendfile(), server::sendinitclient(), server::sendmessages(), sendpacket(), server::sendpositions(), server::sendwelcome(), and server::setmaster().
void sendservmsg (const char * s)
References N_SERVMSG, and sendf().
Referenced by server::checkvotes(), server::clearbans(), server::cleardemos(), server::disconnect_client(), server::enddemoplayback(), aiman::setbotbalance(), aiman::setbotlimit(), server::setupdemoplayback(), and server::setupdemorecord().
void sendservmsgf (const char * fmt, ...)
References defvformatstring, N_SERVMSG, and sendf().
Referenced by server::adddemo(), server::cleardemos(), server::parsepacket(), server::receivefile(), server::setupdemoplayback(), server::trykick(), and server::vote().