Inexor: inexor/engine/normal.cpp File Reference
normal.cpp File Reference
#include <math.h>
#include <stdlib.h>
#include <algorithm>
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
Classes
struct normalgroup
struct normal
struct tnormal
Functions
static bool htcmp (const vec &v, const normalgroup &n)
VARR (lerpangle, 0, 44, 180)
static int addnormal (const vec &key, const vec &surface)
static void addtnormal (const vec &key, float offset, int normal1, int normal2, normalgroup *group1, normalgroup *group2)
static int addnormal (const vec &key, int axis)
static void findnormal (const normalgroup &g, const vec &surface, vec &v)
static bool findtnormal (const normalgroup &g, const vec &surface, vec &v)
void findnormal (const vec &key, const vec &surface, vec &v)
VARR (lerpsubdiv, 0, 2, 4)
VARR (lerpsubdivsize, 4, 4, 128)
void show_addnormals_progress ()
void addnormals (cube &c, const ivec &o, int size)
void calcnormals (bool lerptjoints)
void clearnormals ()
void calclerpverts (const vec2 *c, const vec *n, lerpvert *lv, int &numv)
void setlerpstep (float v, lerpbounds &bounds)
void initlerpbounds (float u, float v, const lerpvert *lv, int numv, lerpbounds &start, lerpbounds &end)
void updatelerpbounds (float v, const lerpvert *lv, int numv, lerpbounds &start, lerpbounds &end)
void lerpnormal (float u, float v, const lerpvert *lv, int numv, lerpbounds &start, lerpbounds &end, vec &normal, vec &nstep)
Variables
hashset< normalgroup > normalgroups (1<< 16)
vector< normal > normals
vector< tnormal > tnormals
static float lerpthreshold = 0
static bool usetnormals = true
static uint progress = 0
Class Documentation
struct normal
Class Members
int next
vec surface
struct tnormal
Class Members
normalgroup * groups[2]
int next
int normals[2]
float offset
Function Documentation
static int addnormal (const vec & key, const vec & surface) static
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::length(), normal::next, normalgroups, normalgroup::normals, and normal::surface.
Referenced by addnormals().
static int addnormal (const vec & key, int axis) static
References normalgroup::flat, and normalgroups.
void addnormals (cube & c, const ivec & o, int size)
References vec::add(), addnormal(), addtnormal(), CHECK_CALCLIGHT_PROGRESS, cube::children, vec::cross(), hmap::d, DEFAULT_SKY, tjoint::edge, cube::ext, f(), faceconvexity(), flataxisface(), genfaceverts(), isempty, loopi(), loopj, loopk, MAXFACEVERTS, cube::merged, inexor::rpc::min(), vec::mul(), ivec::neg(), tjoint::next, normalgroups, vec::normalize(), sphere::numverts, surfaceinfo::numverts, tjoint::offset, progress, reduceslope(), show_addnormals_progress(), vec::sub(), cubeext::surfaces, anonymous_namespace{utilTest.cpp}::t(), cube::texture, cubeext::tjoints, tjoints, usetnormals, sphere::verts, surfaceinfo::verts, cubeext::verts(), visibletris(), vertinfo::x, vertinfo::y, and vertinfo::z.
Referenced by calcnormals().
static void addtnormal (const vec & key, float offset, int normal1, int normal2, normalgroup * group1, normalgroup * group2) static
References vector< T, MINSIZE >::add(), tnormal::groups, vector< T, MINSIZE >::length(), tnormal::next, normalgroups, tnormal::normals, tnormal::offset, and normalgroup::tnormals.
Referenced by addnormals().
void calclerpverts (const vec2 * c, const vec * n, lerpvert * lv, int & numv)
References loopj, lerpvert::normal, and lerpvert::tc.
Referenced by setupsurface().
void calcnormals (bool lerptjoints)
References addnormals(), f(), findtjoints(), lerpthreshold, lerptjoints, loopi(), progress, RAD, usetnormals, worldroot, and worldsize.
Referenced by calclight(), and patchlight().
void clearnormals ()
References normalgroups, and vector< T, MINSIZE >::setsize().
Referenced by calclight(), and patchlight().
static void findnormal (const normalgroup & g, const vec & surface, vec & v) inline static
References vec::add(), cur, vec::dot(), normalgroup::flat, lerpthreshold, normal::next, vec::normalize(), normalgroup::normals, and normal::surface.
Referenced by findnormal(), and findtnormal().
void findnormal (const vec & key, const vec & surface, vec & v)
References findnormal(), findtnormal(), normalgroups, and normalgroup::tnormals.
Referenced by setupsurfaces().
static bool findtnormal (const normalgroup & g, const vec & surface, vec & v) inline static
References cur, findnormal(), tnormal::groups, vec::lerp(), lerpthreshold, tnormal::next, vec::normalize(), tnormal::normals, tnormal::offset, and normalgroup::tnormals.
Referenced by findnormal().
static bool htcmp (const vec & v, const normalgroup & n) inline static
References normalgroup::pos.
void initlerpbounds (float u, float v, const lerpvert * lv, int numv, lerpbounds & start, lerpbounds & end)
References loopi(), lerpbounds::max, lerpbounds::min, setlerpstep(), lerpvert::tc, and lerpbounds::winding.
Referenced by generatelightmap().
void lerpnormal (float u, float v, const lerpvert * lv, int numv, lerpbounds & start, lerpbounds & end, vec & normal, vec & nstep)
References vec::add(), vec::div(), vec::mul(), lerpbounds::normal, vec::normalize(), lerpbounds::nstep, vec::sub(), lerpbounds::u, updatelerpbounds(), and lerpbounds::ustep.
Referenced by generatelightmap().
void setlerpstep (float v, lerpbounds & bounds)
References vec::add(), vec::div(), lerpbounds::max, lerpbounds::min, vec::mul(), lerpvert::normal, lerpbounds::normal, vec::normalize(), lerpbounds::nstep, vec::sub(), lerpvert::tc, lerpbounds::u, and lerpbounds::ustep.
Referenced by initlerpbounds(), and updatelerpbounds().
void show_addnormals_progress ()
References allocnodes, progress, and renderprogress().
Referenced by addnormals().
void updatelerpbounds (float v, const lerpvert * lv, int numv, lerpbounds & start, lerpbounds & end)
References lerpbounds::max, lerpbounds::min, setlerpstep(), lerpvert::tc, and lerpbounds::winding.
Referenced by lerpnormal().
VARR (lerpangle , 0 , 44 , 180)
VARR (lerpsubdiv , 0 , 2 , 4)
VARR (lerpsubdivsize , 4 , 4 , 128)
Variable Documentation
float lerpthreshold = 0 static
Referenced by calcnormals(), findnormal(), and findtnormal().
hashset<normalgroup> normalgroups(1<< 16)
Referenced by addnormal(), addnormals(), addtnormal(), clearnormals(), and findnormal().
vector<normal> normals
Referenced by blurtexture(), loadc(), rendermaterials(), reorients3tc(), and reorienttexture().
uint progress = 0 static
Referenced by addnormals(), calcnormals(), and show_addnormals_progress().
vector<tnormal> tnormals
bool usetnormals = true static
Referenced by addnormals(), and calcnormals().