Inexor: inexor/engine/octarender.cpp File Reference
octarender.cpp File Reference
#include "inexor/engine/octarender.hpp"
#include <SDL_opengl.h>
#include <boost/algorithm/clamp.hpp>
#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "inexor/engine/blob.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderparticles.hpp"
#include "inexor/engine/rendersky.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/shadowmap.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texture.hpp"
Classes
struct vboinfo
struct verthash
struct sortkey
struct sortval
struct vacollect
struct edgegroup
struct cubeedge
struct mergedface
Macros
#define GENVERTS(type, ptr, body)
#define progress(s) if((recalcprogress++&0xFFF)==0) renderprogress(recalcprogress/(float)allocnodes, s);
#define MAXMERGELEVEL 12
Enumerations
enum { VBO_VBUF = 0, VBO_EBUF, VBO_SKYBUF, NUMVBO }
enum { NO_ALPHA = 0, ALPHA_BACK, ALPHA_FRONT }
enum { CE_START = 1<<0, CE_END = 1<<1, CE_FLIP = 1<<2, CE_DUP = 1<<3 }
Functions
VAR (debugvbo, 0, 0, 1)
VARFN (vbosize, maxvbosize, 0, 16384, 65536, allchanged())
void destroyvbo (GLuint vbo)
void genvbo (int type, void *buf, int len, vtxarray **vas, int numva)
bool readva (vtxarray *va, ushort *&edata, vertex *&vdata)
void flushvbo (int type=-1)
uchar * addvbo (vtxarray *va, int type, int numelems, int elemsize)
static bool htcmp (const sortkey &x, const sortkey &y)
static uint hthash (const sortkey &k)
int calcshadowmask (vec *pos, int numpos)
VARFP (filltjoints, 0, 1, 1, allchanged())
void reduceslope (ivec &n)
void addtris (const sortkey &key, int orient, vertex *verts, int *index, int numverts, int convex, int shadowmask, int tj)
void addgrasstri (int face, vertex *verts, int numv, ushort texture, ushort lmid)
static void calctexgen (VSlot &vslot, int dim, vec4 &sgen, vec4 &tgen)
ushort encodenormal (const vec &n)
vec decodenormal (ushort norm)
void guessnormals (const vec *pos, int numverts, vec *normals)
void addcubeverts (VSlot &vslot, int orient, int size, vec *pos, int convex, ushort texture, ushort lmid, vertinfo *vinfo, int numverts, int tj=-1, ushort envmap=EMID_NONE, int grassy=0, bool alpha=false, int layer=LAYER_TOP)
static uint hthash (const edgegroup &g)
static bool htcmp (const edgegroup &x, const edgegroup &y)
void gencubeedges (cube &c, const ivec &co, int size)
void gencubeedges (cube *c=worldroot, const ivec &co=ivec(0, 0, 0), int size=worldsize >>1)
void gencubeverts (cube &c, const ivec &co, int size, int csi)
static bool skyoccluded (cube &c, int orient)
static int hasskyfaces (cube &c, const ivec &co, int size, int faces[6]=dummyskyfaces)
void minskyface (cube &cu, int orient, const ivec &co, int size, facebounds &orig)
void genskyfaces (cube &c, const ivec &o, int size)
void addskyverts (const ivec &o, int size)
vtxarray * newva (const ivec &co, int size)
void destroyva (vtxarray *va, bool reparent)
void clearvas (cube *c)
void updatevabb (vtxarray *va, bool force)
void updatevabbs (bool force)
int genmergedfaces (cube &c, const ivec &co, int size, int minlevel=-1)
int findmergedfaces (cube &c, const ivec &co, int size, int csi, int minlevel)
void addmergedverts (int level, const ivec &o)
void rendercube (cube &c, const ivec &co, int size, int csi, int &maxlevel)
void calcgeombb (const ivec &co, int size, ivec &bbmin, ivec &bbmax)
void calcmatbb (const ivec &co, int size, ivec &bbmin, ivec &bbmax)
void setva (cube &c, const ivec &co, int size, int csi)
static int setcubevisibility (cube &c, const ivec &co, int size)
VARF (vafacemax, 64, 384, 256 *256, allchanged())
VARF (vafacemin, 0, 96, 256 *256, allchanged())
VARF (vacubesize, 32, 128, 0x1000, allchanged())
int updateva (cube *c, const ivec &co, int size, int csi)
void addtjoint (const edgegroup &g, const cubeedge &e, int offset)
void findtjoints (int cur, const edgegroup &g)
void findtjoints ()
void octarender ()
void precachetextures ()
void allchanged (bool load)
void recalc ()
COMMAND (recalc,"")
Variables
hashtable< GLuint, vboinfo > vbos
static vector< uchar > vbodata [NUMVBO]
static vector< vtxarray * > vbovas [NUMVBO]
static int vbosize [NUMVBO]
vacollect vc
int recalcprogress = 0
vector< tjoint > tjoints
vec shadowmapmin
vec shadowmapmax
vec orientation_tangent [6][3]
vec orientation_bitangent [6][3]
vector< cubeedge > cubeedges
hashtable< edgegroup, int > edgegroups (1<< 13)
static int dummyskyfaces [6]
int allocva = 0
int wtris = 0
int wverts = 0
int vtris = 0
int vverts = 0
int glde = 0
int gbatches = 0
vector< vtxarray * > valist
vector< vtxarray * > varoot
static int vahasmerges = 0
static int vamergemax = 0
static vector< mergedface > vamerges [MAXMERGELEVEL+1]
Class Documentation
struct vboinfo
Class Members
int uses
struct edgegroup
Class Members
int axis
ivec origin
ivec slope
struct cubeedge
Class Members
cube * c
uchar flags
uchar index
int next
int offset
ushort size
struct mergedface
Class Members
ushort envmap
uchar lmid
ushort mat
uchar numverts
uchar orient
ushort tex
int tjoints
vertinfo * verts
Macro Definition Documentation
#define GENVERTS (type, ptr, body)
Value:
do \
    { \
        type *f = (type *)ptr; \
        loopv(verts) \
        { \
            const vertex &v = verts[i]; \
            body; \
            f++; \
        } \
    } while(0)
Referenced by vacollect::genverts().
#define MAXMERGELEVEL 12
Referenced by rendercube(), setva(), and updateva().
#define progress (s) if((recalcprogress++&0xFFF)==0) renderprogress(recalcprogress/(float)allocnodes, s);
Referenced by gencubeedges(), and updateva().
Enumeration Type Documentation
anonymous enum
Enumerator
VBO_VBUF
VBO_EBUF
VBO_SKYBUF
NUMVBO
anonymous enum
Enumerator
NO_ALPHA
ALPHA_BACK
ALPHA_FRONT
anonymous enum
Enumerator
CE_START
CE_END
CE_FLIP
CE_DUP
Function Documentation
void addcubeverts (VSlot & vslot, int orient, int size, vec * pos, int convex, ushort texture, ushort lmid, vertinfo * vinfo, int numverts, int tj = -1, ushort envmap = EMID_NONE, int grassy = 0, bool alpha = false, int layer = LAYER_TOP)
References addgrasstri(), addtris(), verthash::addvert(), ALPHA_BACK, ALPHA_FRONT, VSlot::alphaback, VSlot::alphafront, calcshadowmask(), calctexgen(), decodenormal(), DEFAULT_SKY, dimension, vec4::dot(), EMID_NONE, LightMapTexture::h, vec2::iszero(), LAYER_BLEND, LAYER_TOP, lightmaps, lightmaptexs, vertex::lm, LM_BUMPMAP0, LM_BUMPMAP1, LM_DIFFUSE, LM_PACKH, LM_PACKW, LM_TYPE, LMID_AMBIENT, LMID_RESERVED, loopk, MAXFACEVERTS, inexor::rpc::min(), NO_ALPHA, vertinfo::norm, vertex::norm, LightMap::offsetx, LightMap::offsety, orient, vertex::pos, VSlot::rotation, vec::scalartriple(), VSlot::scroll, vacollect::skyclip, vacollect::skymask, anonymous_namespace{utilTest.cpp}::t(), vertex::tangent, vertex::tc, LightMap::tex, LightMap::type, vertinfo::u, vertinfo::v, vc, sphere::verts, and LightMapTexture::w.
Referenced by addmergedverts(), and gencubeverts().
void addgrasstri (int face, vertex * verts, int numv, ushort texture, ushort lmid)
References vector< T, MINSIZE >::add(), vec::add(), grasstri::center, vec::cross(), vec::dist(), vec::div(), vacollect::grasstris, vertex::lm, grasstri::lmid, loopk, inexor::rpc::max(), grasstri::maxz, inexor::rpc::min(), grasstri::minz, grasstri::numv, vector< T, MINSIZE >::pop(), vertex::pos, grasstri::radius, vec::sub(), grasstri::surface, grasstri::tcu, grasstri::tcv, grasstri::texture, plane::toplane(), grasstri::v, and vc.
Referenced by addcubeverts().
void addmergedverts (int level, const ivec & o)
References vec::add(), addcubeverts(), Slot::autograss, vector< T, MINSIZE >::empty(), mergedface::envmap, f(), LAYER_BLEND, LAYER_TOP, mergedface::lmid, lookupvslot(), loopi(), loopv, mergedface::mat, MAT_ALPHA, MAXFACEVERTS, MERGE_USE, vec::mul(), sphere::numverts, mergedface::numverts, O_BOTTOM, mergedface::orient, vector< T, MINSIZE >::setsize(), VSlot::slot, mergedface::tex, mergedface::tjoints, mergedface::verts, vertinfo::x, vertinfo::y, and vertinfo::z.
Referenced by rendercube().
void addskyverts (const ivec & o, int size)
References vector< T, MINSIZE >::add(), verthash::addvert(), C, dimension, vector< T, MINSIZE >::empty(), facecoords, vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), loopi(), loopk, loopvj, mergefaces(), inexor::rpc::min(), opposite, R, vector< T, MINSIZE >::setsize(), vacollect::skyclip, vacollect::skyfaces, vacollect::skyindices, vacollect::skymask, vacollect::skytris, facebounds::u1, facebounds::u2, facebounds::v1, facebounds::v2, and vc.
Referenced by setva().
void addtjoint (const edgegroup & g, const cubeedge & e, int offset)
References vector< T, MINSIZE >::add(), edgegroup::axis, cubeedge::c, CE_FLIP, cur, tjoint::edge, ext(), cube::ext, cubeedge::flags, cubeedge::index, vector< T, MINSIZE >::length(), tjoint::next, tjoint::offset, edgegroup::origin, edgegroup::slope, and cubeext::tjoints.
Referenced by findtjoints().
void addtris (const sortkey & key, int orient, vertex * verts, int * index, int numverts, int convex, int shadowmask, int tj)
References vector< T, MINSIZE >::add(), vec::add(), verthash::addvert(), hmap::d, DEFAULT_SKY, tjoint::edge, vacollect::explicitskyindices, f(), vacollect::indices, vec2::lerp(), bvec4::lerp(), vertex::lm, loopi(), loopk, MAXFACEVERTS, inexor::rpc::min(), vec::mul(), tjoint::next, vertex::norm, sphere::numverts, tjoint::offset, vertex::pos, reduceslope(), vacollect::skytris, recorder::start(), vec::sub(), anonymous_namespace{utilTest.cpp}::t(), vertex::tangent, vertex::tc, sortkey::tex, vc, and vacollect::worldtris.
Referenced by addcubeverts().
uchar* addvbo (vtxarray * va, int type, int numelems, int elemsize)
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::advance(), and vector< T, MINSIZE >::reserve().
Referenced by vacollect::setupdata().
void allchanged (bool load)
References clearvas(), drawtextures(), entitiesinoctanodes(), findtjoints(), guessshadowdir(), initenvmaps(), invalidatepostfx(), lightents(), octarender(), precachetextures(), renderprogress(), resetblobs(), resetclipplanes(), resetqueries(), seedparticles(), vector< T, MINSIZE >::setsize(), setupmaterials(), updatevabbs(), and worldroot.
Referenced by calclight(), clearlightmaps(), editvslot(), emptymap(), enlargemap(), load_world(), mpremip(), mpreplacetex(), patchlight(), recalc(), remip_(), resetgl(), save_world(), and shrinkmap().
void calcgeombb (const ivec & co, int size, ivec & bbmin, ivec & bbmax)
References vec::add(), loopv, vec::max(), vec::mul(), ivec::shr(), vc, and verthash::verts.
Referenced by setva().
void calcmatbb (const ivec & co, int size, ivec & bbmin, ivec & bbmax)
References C, materialsurface::csize, dimension, loopv, MAT_GLASS, MAT_LAVA, MAT_WATER, materialsurface::material, MATF_VOLUME, vacollect::matsurfs, inexor::rpc::max(), inexor::rpc::min(), materialsurface::o, materialsurface::orient, R, materialsurface::rsize, and vc.
Referenced by setva().
int calcshadowmask (vec * pos, int numpos)
References loopk, vec::max(), vec::min(), shadowdir, and vec::sub().
Referenced by addcubeverts().
static void calctexgen (VSlot & vslot, int dim, vec4 & sgen, vec4 & tgen) inline static
References notexture, VSlot::offset, VSlot::rotation, VSlot::scale, VSlot::slot, Slot::sts, TEX_SCALE, Texture::xs, and Texture::ys.
Referenced by addcubeverts().
void clearvas (cube * c)
References clearvas(), destroyva(), ext(), cube::ext, loopi(), cubeext::tjoints, and cubeext::va.
Referenced by allchanged(), cleanupva(), and clearvas().
COMMAND (recalc , "")
vec decodenormal (ushort norm)
References sincos360.
Referenced by addcubeverts().
void destroyva (vtxarray * va, bool reparent)
References vector< T, MINSIZE >::add(), vtxarray::alphabacktris, vtxarray::alphafronttris, vtxarray::blends, vtxarray::children, destroyvbo(), vtxarray::ebuf, vtxarray::eslist, loopv, vtxarray::matbuf, vtxarray::parent, vector< T, MINSIZE >::removeobj(), vtxarray::skybuf, vtxarray::tris, vtxarray::vbuf, vtxarray::verts, and wverts.
Referenced by clearvas(), discardchildren(), invalidatemerges(), previewblends(), and readychanges().
void destroyvbo (GLuint vbo)
References hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::access(), glDeleteBuffers_, hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::remove(), and vboinfo::uses.
Referenced by destroyva().
ushort encodenormal (const vec & n)
References vec::iszero(), and RAD.
Referenced by convertoldsurfaces(), and setupsurfaces().
int findmergedfaces (cube & c, const ivec & co, int size, int csi, int minlevel)
References cube::children, cube::ext, genmergedfaces(), vtxarray::hasmerges, loopi(), inexor::rpc::max(), MERGE_ORIGIN, cube::merged, vtxarray::mergelevel, and cubeext::va.
Referenced by updateva().
void findtjoints (int cur, const edgegroup & g)
References addtjoint(), CE_DUP, CE_END, CE_START, cur, cubeedge::flags, cubeedge::next, cubeedge::offset, and cubeedge::size.
Referenced by allchanged(), calcnormals(), and findtjoints().
void findtjoints ()
References edgegroups, enumeratekt, findtjoints(), gencubeedges(), and vector< T, MINSIZE >::setsize().
void flushvbo (int type = -1)
References vector< T, MINSIZE >::empty(), genvbo(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), loopi(), NUMVBO, and vector< T, MINSIZE >::setsize().
Referenced by octarender(), and vacollect::setupdata().
void gencubeedges (cube & c, const ivec & co, int size)
References vector< T, MINSIZE >::add(), ivec::add(), edgegroup::axis, cubeedge::c, CE_DUP, CE_END, CE_FLIP, CE_START, cur, hmap::d, edgegroups, cube::ext, faceconvexity(), cubeedge::flags, flataxisface(), genfaceverts(), cubeedge::index, ivec::iszero(), vector< T, MINSIZE >::length(), loopi(), loopj, ivec::mask(), MAXFACEVERTS, cube::merged, ivec::mul(), ivec::neg(), cubeedge::next, sphere::numverts, surfaceinfo::numverts, cubeedge::offset, edgegroup::origin, reduceslope(), ivec::shl(), cubeedge::size, edgegroup::slope, ivec::sub(), cubeext::surfaces, sphere::verts, surfaceinfo::verts, cubeext::verts(), visibletris(), vertinfo::x, vertinfo::y, and vertinfo::z.
Referenced by findtjoints(), and gencubeedges().
void gencubeedges (cube * c = worldroot, const ivec & co = ivec(0, 0, 0), int size = worldsize>>1)
References ext(), gencubeedges(), isempty, loopi(), neighbourdepth, neighbourstack, and progress.
void gencubeverts (cube & c, const ivec & co, int size, int csi)
References vec::add(), addcubeverts(), Slot::autograss, closestenvmap(), EMID_CUSTOM, EMID_NONE, cube::ext, f(), faceconvexity(), flataxisface(), genfaceverts(), VSlot::layer, LAYER_BLEND, LAYER_BOTTOM, LAYER_DUP, LAYER_TOP, surfaceinfo::lmid, LMID_AMBIENT, lookupvslot(), loopi(), loopj, MAT_ALPHA, cube::material, MAXFACEVERTS, cube::merged, vec::mul(), sphere::numverts, surfaceinfo::numverts, O_BOTTOM, Slot::shader, SHADER_ENVMAP, VSlot::slot, cubeext::surfaces, TEX_ENVMAP, Slot::texmask, cube::texture, cubeext::tjoints, Shader::type, sphere::verts, surfaceinfo::verts, cubeext::verts(), and visibletris().
Referenced by rendercube().
int genmergedfaces (cube & c, const ivec & co, int size, int minlevel = -1)
References vector< T, MINSIZE >::add(), calcmergedsize(), closestenvmap(), EMID_CUSTOM, EMID_NONE, mergedface::envmap, cube::ext, isempty, VSlot::layer, LAYER_BOTTOM, LAYER_DUP, LAYER_TOP, surfaceinfo::lmid, mergedface::lmid, lookupvslot(), loopi(), mergedface::mat, MAT_ALPHA, cube::material, inexor::rpc::max(), MAXFACEVERTS, MERGE_ORIGIN, MERGE_PART, cube::merged, sphere::numverts, surfaceinfo::numverts, mergedface::numverts, mergedface::orient, Slot::shader, SHADER_ENVMAP, VSlot::slot, cubeext::surfaces, mergedface::tex, TEX_ENVMAP, Slot::texmask, cube::texture, cubeext::tjoints, mergedface::tjoints, Shader::type, vamergemax, surfaceinfo::verts, cubeext::verts(), and mergedface::verts.
Referenced by findmergedfaces(), and rendercube().
void genskyfaces (cube & c, const ivec & o, int size)
References vector< T, MINSIZE >::add(), C, dimension, hasskyfaces(), loopi(), minskyface(), orient, R, vacollect::skyarea, vacollect::skyfaces, facebounds::u1, facebounds::u2, facebounds::v1, facebounds::v2, and vc.
Referenced by rendercube().
void genvbo (int type, void * buf, int len, vtxarray ** vas, int numva)
References gle::disable(), vtxarray::ebuf, glBindBuffer_, glBufferData_, GLenum(), glGenBuffers_, GLuint(), Log, loopi(), vtxarray::skybuf, inexor::util::log_manager::std, ai::target(), vboinfo::uses, gle::vbo, VBO_EBUF, VBO_SKYBUF, VBO_VBUF, and vtxarray::vbuf.
Referenced by flushvbo().
void guessnormals (const vec * pos, int numverts, vec * normals)
References vec::add(), vec::cross(), vec::iszero(), loopk, and vec::normalize().
Referenced by genprefabmesh().
static int hasskyfaces (cube & c, const ivec & co, int size, int faces[6] = dummyskyfaces) inline static
References isempty, isentirelysolid, MAT_ALPHA, cube::material, O_BACK, O_BOTTOM, O_FRONT, O_LEFT, O_RIGHT, O_TOP, skyoccluded(), and worldsize.
Referenced by genskyfaces(), and updateva().
static bool htcmp (const sortkey & x, const sortkey & y) inline static
static bool htcmp (const edgegroup & x, const edgegroup & y) static
References edgegroup::origin, and edgegroup::slope.
static uint hthash (const sortkey & k) inline static
References sortkey::lmid, and sortkey::tex.
Referenced by verthash::addvert().
static uint hthash (const edgegroup & g) static
References edgegroup::origin, and edgegroup::slope.
void minskyface (cube & cu, int orient, const ivec & co, int size, facebounds & orig)
References MAT_ALPHA, inexor::rpc::max(), inexor::rpc::min(), mincubeface(), facebounds::u1, facebounds::u2, facebounds::v1, and facebounds::v2.
Referenced by genskyfaces().
vtxarray* newva (const ivec & co, int size)
References vector< T, MINSIZE >::add(), vtxarray::alphabacktris, vtxarray::alphafronttris, vtxarray::bbmax, vtxarray::bbmin, vtxarray::blends, vtxarray::curvfc, vtxarray::hasmerges, vtxarray::mergelevel, vtxarray::o, OCCLUDE_NOTHING, vtxarray::occluded, vacollect::optimize(), vtxarray::parent, vtxarray::query, vacollect::setupdata(), vtxarray::size, vtxarray::skyarea, vacollect::skyarea, vtxarray::skyclip, vacollect::skyclip, vtxarray::skyfaces, vacollect::skymask, vtxarray::tris, vc, vtxarray::verts, VFC_NOT_VISIBLE, and wverts.
Referenced by setva().
void octarender ()
References vtxarray::explicitsky, explicitsky, flushvbo(), loadprogress, loopv, vector< T, MINSIZE >::setsize(), vtxarray::skyarea, skyarea, updateva(), visibleva, worldroot, and worldsize.
Referenced by allchanged(), and commitchanges().
void precachetextures ()
References vector< T, MINSIZE >::add(), vtxarray::blends, vtxarray::eslist, vector< T, MINSIZE >::find(), vector< T, MINSIZE >::length(), loadprogress, lookupvslot(), loopj, loopv, vtxarray::texs, and elementset::texture.
Referenced by allchanged().
bool readva (vtxarray * va, ushort *& edata, vertex *& vdata)
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), vtxarray::ebuf, vtxarray::edata, glGetBufferSubData_, vtxarray::tris, vtxarray::vbuf, vtxarray::verts, and vtxarray::voffset.
Referenced by writeobj().
void recalc ()
References allchanged().
void reduceslope (ivec & n)
References C, ivec::div(), loopi(), R, and ivec::shr().
Referenced by addnormals(), addtris(), gencubeedges(), and genpoly().
void rendercube (cube & c, const ivec & co, int size, int csi, int & maxlevel)
References vector< T, MINSIZE >::add(), addmergedverts(), cube::children, cubeext::ents, cube::ext, gencubeverts(), genmatsurfs(), genmergedfaces(), genskyfaces(), isempty, vector< T, MINSIZE >::length(), loopi(), octaentities::mapmodels, vacollect::mapmodels, MAT_AIR, cube::material, vacollect::matsurfs, inexor::rpc::max(), MAXMERGELEVEL, cube::merged, vtxarray::mergelevel, neighbourdepth, neighbourstack, cubeext::va, and vc.
Referenced by setva().
static int setcubevisibility (cube & c, const ivec & co, int size) inline static
References classifyface(), collideface(), DEFAULT_SKY, cube::ext, loopi(), MAXFACEVERTS, cube::merged, surfaceinfo::numverts, cubeext::surfaces, and cube::texture.
Referenced by updateva().
void setva (cube & c, const ivec & co, int size, int csi)
References vec::add(), addskyverts(), ASSERT, calcgeombb(), calcmatbb(), vacollect::clear(), vacollect::emptyva(), ext(), vtxarray::geommax, vtxarray::geommin, vtxarray::hasmerges, vector< T, MINSIZE >::length(), loopi(), vtxarray::matmax, vtxarray::matmin, MAXMERGELEVEL, vtxarray::mergelevel, inexor::rpc::min(), vec::mul(), newva(), vacollect::origin, rendercube(), vector< T, MINSIZE >::setsize(), vtxarray::shadowmapmax, vtxarray::shadowmapmin, ivec::shr(), vacollect::size, cubeext::va, vahasmerges, vamergemax, vc, and worldsize.
Referenced by updateva().
static bool skyoccluded (cube & c, int orient) inline static
References F_SOLID, faceedges(), and touchingface().
Referenced by hasskyfaces().
int updateva (cube * c, const ivec & co, int size, int csi)
References vector< T, MINSIZE >::add(), allocnodes, vtxarray::children, ext(), cube::ext, f(), findmergedfaces(), vtxarray::hasmerges, hasskyfaces(), isempty, vector< T, MINSIZE >::length(), loadprogress, loopi(), inexor::rpc::max(), MAXMERGELEVEL, MERGE_ORIGIN, MERGE_USE, inexor::rpc::min(), vector< T, MINSIZE >::move(), neighbourdepth, neighbourstack, vtxarray::parent, vector< T, MINSIZE >::pop(), progress, setcubevisibility(), setva(), cubeext::va, vahasmerges, vamergemax, and worldsize.
Referenced by octarender().
void updatevabb (vtxarray * va, bool force)
References ivec::add(), octaentities::bbmax, vtxarray::bbmax, octaentities::bbmin, vtxarray::bbmin, C, vtxarray::children, vtxarray::geommax, vtxarray::geommin, loop, loopv, vtxarray::mapmodels, vtxarray::matmax, vtxarray::matmin, ivec::max(), ivec::min(), vtxarray::o, R, vtxarray::size, vtxarray::sky, vtxarray::skyfaces, and updatevabb().
Referenced by modifyoctaentity(), updatevabb(), and updatevabbs().
void updatevabbs (bool force)
References loopv, and updatevabb().
Referenced by allchanged(), and commitchanges().
VAR (debugvbo , 0 , 0 , 1)
VARF (vafacemax , 64 , 384 , 256 * 256, allchanged())
VARF (vafacemin , 0 , 96 , 256 * 256, allchanged())
VARF (vacubesize , 32 , 128 , 0x1000 , allchanged())
VARFN (vbosize , maxvbosize , 0 , 16384 , 65536 , allchanged())
VARFP (filltjoints , 0 , 1 , 1 , allchanged())
Variable Documentation
int allocva = 0
Referenced by gl_drawhud().
vector<cubeedge> cubeedges
int dummyskyfaces[6] static
hashtable<edgegroup, int> edgegroups(1<< 13)
Referenced by findtjoints(), and gencubeedges().
int gbatches = 0
Referenced by drawcubemap(), drawminimap(), gl_drawframe(), gl_drawhud(), gl_drawmainmenu(), and renderbatch().
int glde = 0
Referenced by sphere::draw(), fogdome::draw(), drawcubemap(), drawminimap(), drawtris(), gl_drawframe(), gl_drawhud(), gl_drawmainmenu(), vertmodel::vertmesh::render(), and skelmodel::skelmesh::render().
vec orientation_bitangent[6][3]
Initial value:
=
{
    { vec(0,  0, -1), vec( 0, 0, -1), vec( 0,  1, 0) },
    { vec(0, -1,  0), vec(-1, 0,  0), vec(-1,  0, 0) },
    { vec(0,  0,  1), vec( 0, 0,  1), vec( 0, -1, 0) },
    { vec(0,  1,  0), vec( 1, 0,  0), vec( 1,  0, 0) },
    { vec(0,  0, -1), vec( 0, 0, -1), vec( 0,  1, 0) },
    { vec(0,  0,  1), vec( 0, 0,  1), vec( 0, -1, 0) },
}
Referenced by generatelumel().
vec orientation_tangent[6][3]
Initial value:
=
{
    { vec(0,  1,  0), vec( 1, 0,  0), vec( 1,  0, 0) },
    { vec(0,  0, -1), vec( 0, 0, -1), vec( 0,  1, 0) },
    { vec(0, -1,  0), vec(-1, 0,  0), vec(-1,  0, 0) },
    { vec(0,  0,  1), vec( 0, 0,  1), vec( 0, -1, 0) },
    { vec(0, -1,  0), vec(-1, 0,  0), vec(-1,  0, 0) },
    { vec(0,  1,  0), vec( 1, 0,  0), vec( 1,  0, 0) },
}
Referenced by generatelumel().
int recalcprogress = 0
vec shadowmapmax
vec shadowmapmin
vector<tjoint> tjoints
Referenced by addnormals().
int vahasmerges = 0 static
Referenced by setva(), and updateva().
vector<vtxarray *> valist
Referenced by calcpvsbounds(), commitchanges(), drawminimap(), findwaterplanes(), setupmaterials(), visiblecubes(), and writeobj().
int vamergemax = 0 static
Referenced by genmergedfaces(), setva(), and updateva().
vector<mergedface> vamerges[MAXMERGELEVEL+1] static
vector<vtxarray *> varoot
Referenced by renderreflectedgeom(), rendersky(), and visiblecubes().
vector<uchar> vbodata[NUMVBO] static
hashtable<GLuint, vboinfo> vbos
int vbosize[NUMVBO] static
vector<vtxarray *> vbovas[NUMVBO] static
vacollect vc
Referenced by addcubeverts(), addgrasstri(), addskyverts(), addtris(), calcgeombb(), calcmatbb(), server::checkvotes(), convertoldsurfaces(), genskyfaces(), loadc(), lookupviewcell(), newva(), vertmodel::vertmeshgroup::render(), skelmodel::skelmeshgroup::render(), rendercube(), savec(), and setva().
int vtris = 0
Referenced by gl_drawhud(), renderbatch(), renderfoggedvas(), and rendergeom().
int vverts = 0
Referenced by vertmodel::vertmeshgroup::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), gl_drawhud(), rendergeom(), and renderva().
int wtris = 0
Referenced by gl_drawhud().
int wverts = 0
Referenced by destroyva(), gl_drawhud(), and newva().