Inexor: inexor/engine/octaedit.cpp File Reference
octaedit.cpp File Reference
#include <SDL_opengl.h>
#include <boost/algorithm/clamp.hpp>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "inexor/client/network.hpp"
#include "inexor/engine/blend.hpp"
#include "inexor/engine/blob.hpp"
#include "inexor/engine/frame.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/fpsgame/fps.hpp"
#include "inexor/fpsgame/player.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/input/InputRouter.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_endian.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/legacy/3dgui.hpp"
#include "inexor/ui/legacy/menus.hpp"
#include "inexor/util/legacy_time.hpp"
#include "zconf.h"
#include "zlib.h"
Classes
struct undolist
struct vslothdr
struct vslotmap
struct prefabheader
struct prefab
struct prefabmesh
struct prefabmesh::vertex
struct vslotref
struct texturegui
Namespaces
hmap
Macros
#define loopxy(b) loop(y,(b).s[C[dimension((b).orient)]]) loop(x,(b).s[R[dimension((b).orient)]])
#define loopxyz(b, r, f) { loop(z,(b).s[D[dimension((b).orient)]]) loopxy((b)) { cube &c = blockcube(x,y,z,b,r); f; } }
#define loopselxyz(f) { if(local) makeundo(); loopxyz(sel, sel.grid, f); changed(sel); }
#define selcube(x, y, z) blockcube(x, y, z, sel, sel.grid)
#define protectsel(f) { undoblock *_u = newundocube(sel); f; if(_u) { pasteundo(_u); freeundo(_u); } }
#define editingvslot(...) vslotref vslotrefs[] = { __VA_ARGS__ }; (void)vslotrefs;
#define MAXBRUSH 64
#define MAXBRUSHC 63
#define MAXBRUSH2 32
#define PAINTED 1
#define NOTHMAP 2
#define MAPPED 16
#define pullhmap(I, LT, GT, M, N, A)
#define DIAGONAL_RIPPLE(a, b, exp)
#define loopbrush(i) for(int x=bmx; x<=bnx+i; x++) for(int y=bmy; y<=bny+i; y++)
Enumerations
enum { EDITMATF_EMPTY = 0x10000, EDITMATF_NOTEMPTY = 0x20000, EDITMATF_SOLID = 0x30000, EDITMATF_NOTSOLID = 0x40000 }
Functions
void boxs (int orient, vec o, const vec &s, float size)
renders a rectangular box to the target location with faked thick lines
void boxs (int orient, vec o, const vec &s)
renders a rectangular box to the target location
void boxs3D (const vec &o, vec s, int g)
render cube (6 boxes) to target location
void boxsgrid (int orient, vec o, vec s, int g)
renders box grid on the face of the selected volume/area
VARF (dragging, 0, 0, 1, if(!dragging||cor[0]< 0) return;lastcur=cur;lastcor=cor;sel.grid=gridsize;sel.orient=orient;)
dragging is enabled (1) once a grid start cube is selected once you select a cube the selection box will be drawn a little brighter
ICOMMAND (moving,"b",(int *n),{if(*n >=0){if(!*n||(moving<=1 &&!pointinsel(sel, vec(cur).add(1)))) moving=0;else if(!moving) moving=1;}intret(moving);})
VARF (gridpower, 0, 3, 12,{if(dragging) return;gridsize=1<< gridpower;if(gridsize >=worldsize) gridsize=worldsize/2;cancelsel();})
will be called every time the gridpower (gridsize) changes
VAR (passthroughsel, 0, 0, 1)
allow the editor to select new areas/volumes through the current selection otherwise select cubes ON the current selection
VAR (editing, 1, 0, 0)
represent the user's editing status (is he editing or not?)
VAR (selectcorners, 0, 0, 1)
when intruding (pushing towards the inside) a selected cube/face keep the corners rounded
VARF (hmapedit, 0, 0, 1, horient=sel.orient)
start/stop heightmap editing
void forcenextundo ()
reset orientation of the last selection this is called every time the user changes grid size or editing status
void hmapcancel ()
void cubecancel ()
aborts heightsmap editing and resets selection data
void cancelsel ()
reset the current selection called every time user changes grid size or editing status
void toggleedit (bool force)
change editing status also cancel selection, blendmaps and more
bool noedit (bool view, bool msg)
check if user is allowed to edit concerns may be a scene selection which is not in view or disbaled editing status
void reorient ()
change the selection orientation according to the cursor's position
void selextend ()
extend the selection according to the cursor's position
ICOMMAND (edittoggle,"",(), toggleedit(false))
cubescript command hook: toggle editing
COMMAND (entcancel,"")
cubescript command hook: remove entity selection
COMMAND (cubecancel,"")
cubescript command hook: remove cube selection
COMMAND (cancelsel,"")
cubescript command hook: remove both cube and entity selection
COMMAND (reorient,"")
cubescript command hook: change orientation of selected cubes according to the cursor
COMMAND (selextend,"")
cubescript command hook: extend selection of cubes according to the cursor
ICOMMAND (selmoved,"",(),{if(noedit(true)) return;intret(sel.o!=savedsel.o?1:0);})
ICOMMAND (selrestore,"",(),{if(noedit(true)) return;sel=savedsel;})
ICOMMAND (selsave,"",(),{if(noedit(true)) return;savedsel=sel;})
ICOMMAND (selswap,"",(),{if(noedit(true)) return;swap(sel, savedsel);})
cube & blockcube (int x, int y, int z, const block3 &b, int rgrid)
looks up a world cube, based on coordinates mapped by the block
ICOMMAND (havesel,"",(), intret(havesel?selchildcount:0))
cubescript: return number of selected cubes
void countselchild (cube *c, const ivec &cor, int size)
count the number of selected child cubes and materials in your selection
void normalizelookupcube (const ivec &o)
get the selected cube's position from the origin vector (0,0,0)
void updateselection ()
validate the coordinates of the selected face/volume make sure the selected grid is not outside of the map
bool editmoveplane (const vec &o, const vec &ray, int d, float off, vec &handle, vec &dest, bool first)
move the selection grid (the "plane") along the selection has an origin and can only be moved in 2 dimensions simultaneously
bool isheightmap (int orient, int d, bool empty, cube *c)
void entdrag (const vec &ray)
bool hoveringonent (int ent, int orient)
void renderentselection (const vec &o, const vec &ray, bool entmoving)
float rayent (const vec &o, const vec &ray, float radius, int mode, int size, int &orient, int &ent)
VAR (gridlookup, 0, 0, 1)
automaticly select the grid size of the selected face
VAR (passthroughcube, 0, 1, 1)
ignore the first cube when view ray intersects it and select the second ("select through cubes")
void rendereditcursor ()
render selection box to the cursor target also moves entities!
void tryedit ()
check if editing can be done
void readychanges (const ivec &bbmin, const ivec &bbmax, cube *c, const ivec &cor, int size)
checks and validates changes in the octree system
void commitchanges (bool force)
commits changes in geometry
void changed (const block3 &sel, bool commit=true)
validates editing changes using readychanges() and calls commitchanges()
static void copycube (const cube &src, cube &dst)
static void pastecube (const cube &src, cube &dst)
void blockcopy (const block3 &s, int rgrid, block3 *b)
block3 * blockcopy (const block3 &s, int rgrid)
void freeblock (block3 *b, bool alloced=true)
void selgridmap (selinfo &sel, uchar *g)
void freeundo (undoblock *u)
void pasteundoblock (block3 *b, uchar *g)
void pasteundo (undoblock *u)
static int undosize (undoblock *u)
VARP (undomegs, 0, 5, 100)
void pruneundos (int maxremain)
void clearundos ()
COMMAND (clearundos,"")
undoblock * newundocube (selinfo &s)
void addundo (undoblock *u)
VARP (nompedit, 0, 1, 1)
void makeundo (selinfo &s)
void makeundo ()
static int countblock (cube *c, int n=8)
static int countblock (block3 *b)
void swapundo (undolist &a, undolist &b, int op)
void editundo ()
void editredo ()
template<class B >
static void packcube (cube &c, B &buf)
template<class B >
static bool packblock (block3 &b, B &buf)
static void packvslots (cube &c, vector< uchar > &buf, vector< ushort > &used)
static void packvslots (block3 &b, vector< uchar > &buf)
template<class B >
static void unpackcube (cube &c, B &buf)
template<class B >
static bool unpackblock (block3 *&b, B &buf)
static void unpackvslots (cube &c, ucharbuf &buf)
static void unpackvslots (block3 &b, ucharbuf &buf)
static bool compresseditinfo (const uchar *inbuf, int inlen, uchar *&outbuf, int &outlen)
static bool uncompresseditinfo (const uchar *inbuf, int inlen, uchar *&outbuf, int &outlen)
bool packeditinfo (editinfo *e, int &inlen, uchar *&outbuf, int &outlen)
bool unpackeditinfo (editinfo *&e, const uchar *inbuf, int inlen, int outlen)
void freeeditinfo (editinfo *&e)
bool packundo (undoblock *u, int &inlen, uchar *&outbuf, int &outlen)
bool unpackundo (const uchar *inbuf, int inlen, int outlen)
bool packundo (int op, int &inlen, uchar *&outbuf, int &outlen)
SVARP (prefabdir,"prefab")
void cleanupprefabs ()
void delprefab (char *name)
COMMAND (delprefab,"s")
void saveprefab (char *name)
COMMAND (saveprefab,"s")
void pasteblock (block3 &b, selinfo &sel, bool local)
prefab * loadprefab (const char *name, bool msg=true)
void pasteprefab (char *name)
COMMAND (pasteprefab,"s")
static void genprefabmesh (prefabmesh &r, cube &c, const ivec &co, int size)
void genprefabmesh (prefab &p)
static void renderprefab (prefab &p, const vec &o, float yaw, float pitch, float roll, float size, const vec &color)
void renderprefab (const char *name, const vec &o, float yaw, float pitch, float roll, float size, const vec &color)
void previewprefab (const char *name, const vec &color)
void mpcopy (editinfo *&e, selinfo &sel, bool local)
void mppaste (editinfo *&e, selinfo &sel, bool local)
void copy ()
void pastehilite ()
void paste ()
COMMAND (copy,"")
COMMAND (pastehilite,"")
COMMAND (paste,"")
COMMANDN (undo, editundo,"")
COMMANDN (redo, editredo,"")
void compacteditvslots ()
VAR (brushx, 0, MAXBRUSH2, MAXBRUSH)
VAR (brushy, 0, MAXBRUSH2, MAXBRUSH)
void clearbrush ()
void brushvert (int *x, int *y, int *v)
COMMAND (clearbrush,"")
COMMAND (brushvert,"iii")
COMMAND (hmapcancel,"")
ICOMMAND (hmapselect,"",(), int t=lookupcube(cur).texture[orient];int i=htextures.find(t);if(i< 0) htextures.add(t);else htextures.remove(i);)
cube * hmap::getcube (ivec t, int f)
uint hmap::getface (cube *c, int d)
void hmap::pushside (cube &c, int d, int x, int y, int z)
void hmap::addpoint (int x, int y, int z, int v)
void hmap::select (int x, int y, int z)
void hmap::ripple (int x, int y, int z, bool force)
void hmap::paint ()
void hmap::smooth ()
void hmap::rippleandset ()
void hmap::run (int dir, int mode)
void edithmap (int dir, int mode)
int bounded (int n)
void pushedge (uchar &edge, int dir, int dc)
void linkedpush (cube &c, int d, int x, int y, int dc, int dir)
static ushort getmaterial (cube &c)
VAR (invalidcubeguard, 0, 1, 1)
void mpeditface (int dir, int mode, selinfo &sel, bool local)
void editface (int *dir, int *mode)
VAR (selectionsurf, 0, 0, 1)
void pushsel (int *dir)
void mpdelcube (selinfo &sel, bool local)
void delcube ()
COMMAND (pushsel,"i")
COMMAND (editface,"ii")
COMMAND (delcube,"")
void tofronttex ()
VAR (usevdelta, 1, 0, 0)
static VSlot * remapvslot (int index, bool delta, const VSlot &ds)
static void remapvslots (cube &c, bool delta, const VSlot &ds, int orient, bool &findrep, VSlot *&findedit)
void edittexcube (cube &c, int tex, int orient, bool &findrep)
VAR (allfaces, 0, 0, 1)
void mpeditvslot (int delta, VSlot &ds, int allfaces, selinfo &sel, bool local)
bool mpeditvslot (int delta, int allfaces, selinfo &sel, ucharbuf &buf)
void vdelta (char *body)
COMMAND (vdelta,"s")
void vrotate (int *n)
COMMAND (vrotate,"i")
void voffset (int *x, int *y)
COMMAND (voffset,"ii")
void vscroll (float *s, float *t)
COMMAND (vscroll,"ff")
void vscale (float *scale)
COMMAND (vscale,"f")
void vlayer (int *n)
COMMAND (vlayer,"i")
void valpha (float *front, float *back)
COMMAND (valpha,"ff")
void vcolor (float *r, float *g, float *b)
COMMAND (vcolor,"fff")
void vreset ()
COMMAND (vreset,"")
void vshaderparam (const char *name, float *x, float *y, float *z, float *w)
COMMAND (vshaderparam,"sffff")
void mpedittex (int tex, int allfaces, selinfo &sel, bool local)
static int unpacktex (int &tex, ucharbuf &buf, bool insert=true)
int shouldpacktex (int index)
bool mpedittex (int tex, int allfaces, selinfo &sel, ucharbuf &buf)
void filltexlist ()
void compactmruvslots ()
void edittex (int i, bool save=true)
void edittex_ (int *dir)
void gettex ()
void getcurtex ()
void getseltex ()
void gettexname (int *tex, int *subslot)
COMMANDN (edittex, edittex_,"i")
COMMAND (gettex,"")
COMMAND (getcurtex,"")
COMMAND (getseltex,"")
ICOMMAND (getreptex,"",(),{if(!noedit()) intret(vslots.inrange(reptex)?reptex:-1);})
COMMAND (gettexname,"ii")
void replacetexcube (cube &c, int oldtex, int newtex)
bool hastexcube (cube &c, int tex)
void mpreplacetex (int oldtex, int newtex, bool insel, selinfo &sel, bool local, bool update)
bool mpreplacetex (int oldtex, int newtex, bool insel, selinfo &sel, ucharbuf &buf)
void replace (bool insel)
ICOMMAND (replace,"",(), replace(false))
ICOMMAND (replacesel,"",(), replace(true))
uint dflip (uint face)
uint cflip (uint face)
uint rflip (uint face)
uint mflip (uint face)
void flipcube (cube &c, int d)
void rotatequad (cube &a, cube &b, cube &c, cube &d)
void rotatecube (cube &c, int d)
void mpflip (selinfo &sel, bool local)
void flip ()
void mprotate (int cw, selinfo &sel, bool local)
void rotate (int *cw)
COMMAND (flip,"")
COMMAND (rotate,"i")
void setmat (cube &c, ushort mat, ushort matmask, ushort filtermat, ushort filtermask, int filtergeom)
void mpeditmat (int matid, int filter, selinfo &sel, bool local)
void editmat (char *name, char *filtername)
COMMAND (editmat,"ss")
VARP (texguiwidth, 1, 12, 1000)
VARP (texguiheight, 1, 8, 1000)
VARP (texguitime, 0, 25, 1000)
VARP (texgui2d, 0, 1, 1)
void g3d_texturemenu ()
void showtexgui (int *n)
show texture
COMMAND (showtexgui,"i")
void rendertexturepanel (int w, int h)
render quick selection preview for surface textures standard edit key binding: press Z
Variables
SharedVar< int > outline
bool boxoutline = false
selinfo sel
Bot Movement, according to waypoints (saved within the map in an excluded file).
selinfo lastsel
selinfo savedsel
int orient = 0
int gridsize = 8
ivec cor
ivec lastcor
ivec cur
ivec lastcur
SharedVar< int > entediting
bool editmode = false
bool havesel = false
bool hmapsel = false
int horient = 0
int entmoving
int moving = 0
moving will be set to 1 as soon as you right-click a selected area/volume to move it once you release the key, moving(0) will be called
int selchildcount = 0
the amount of selected child cubes they will be displayed in the bottom left of you screen in coopedit mode
int selchildmat = -1
static bool haschanged = false
undolist undos
undolist redos
int totalundos = 0
vector< editinfo * > editinfos
editinfo * localedit = nullptr
static vector< vslotmap > unpackingvslots
static hashnameset< prefab > prefabs
SharedVar< int > outlinecolour
static vector< int * > editingvslots
int brush [MAXBRUSH][MAXBRUSH]
bool paintbrush = 0
int brushmaxx = 0
int brushminx = MAXBRUSH
int brushmaxy = 0
int brushminy = MAXBRUSH
vector< int > htextures
uchar hmap::flags [MAXBRUSH][MAXBRUSH]
cube * hmap::cmap [MAXBRUSHC][MAXBRUSHC][4]
int hmap::mapz [MAXBRUSHC][MAXBRUSHC]
int hmap::map [MAXBRUSH][MAXBRUSH]
selinfo hmap::changes
bool hmap::selecting
int hmap::d
int hmap::dc
int hmap::dr
int hmap::dcr
int hmap::biasup
int hmap::br
int hmap::hws
int hmap::fg
int hmap::gx
int hmap::gy
int hmap::gz
int hmap::mx
int hmap::my
int hmap::mz
int hmap::nx
int hmap::ny
int hmap::nz
int hmap::bmx
int hmap::bmy
int hmap::bnx
int hmap::bny
uint hmap::fs
selinfo hmap::hundo
int curtexindex = -1
int lasttex = 0
int lasttexmillis = -1
int texpaneltimer = 0
vector< ushort > texmru
selinfo repsel
int reptex = -1
static vector< vslotmap > remappedvslots
struct {
const char * name
int filter
} editmatfilters []
SharedVar< int > menudistance
SharedVar< int > menuautoclose
static int lastthumbnail = 0
texturegui gui
Class Documentation
struct vslothdr
Class Members
ushort index
ushort slot
struct prefabheader
Class Members
char magic[4]
int version
struct prefabmesh::vertex
Class Members
bvec4 norm
vec pos
Macro Definition Documentation
#define DIAGONAL_RIPPLE (a, b, exp)
Value:
if(exp) { \
            if(flags[x a][ y] & PAINTED) \
                ripple(x a, y b, mapz[x a][y], true); \
            else if(flags[x][y b] & PAINTED) \
                ripple(x a, y b, mapz[x][y b], true); \
        }
Referenced by hmap::ripple().
#define editingvslot (...) vslotref vslotrefs[] = { __VA_ARGS__ }; (void)vslotrefs;
Referenced by mpeditvslot(), mpreplacetex(), and vlayer().
#define loopbrush (i) for(int x=bmx; x<=bnx+i; x++) for(int y=bmy; y<=bny+i; y++)
Referenced by hmap::paint(), hmap::rippleandset(), and hmap::smooth().
#define loopselxyz (f) { if(local) makeundo(); loopxyz(sel, sel.grid, f); changed(sel); }
Referenced by mpdelcube(), mpeditface(), mpeditmat(), mpedittex(), mpeditvslot(), mpreplacetex(), and pasteblock().
#define loopxy (b) loop(y,(b).s[C[dimension((b).orient)]]) loop(x,(b).s[R[dimension((b).orient)]])
Referenced by mpflip(), and mprotate().
#define loopxyz (b, r, f) { loop(z,(b).s[D[dimension((b).orient)]]) loopxy((b)) { cube &c = blockcube(x,y,z,b,r); f; } }
Referenced by blockcopy(), genprefabmesh(), gettex(), pasteundoblock(), and selgridmap().
#define MAPPED 16
Referenced by hmap::addpoint(), and hmap::smooth().
#define MAXBRUSH 64
Referenced by brushvert(), clearbrush(), and hmap::run().
#define MAXBRUSH2 32
Referenced by brushvert(), and hmap::run().
#define MAXBRUSHC 63
#define NOTHMAP 2
Referenced by hmap::ripple(), and hmap::select().
#define PAINTED 1
Referenced by hmap::ripple(), and hmap::select().
#define protectsel (f) { undoblock *_u = newundocube(sel); f; if(_u) { pasteundo(_u); freeundo(_u); } }
Referenced by mpcopy(), and saveprefab().
#define pullhmap (I, LT, GT, M, N, A)
Value:
do { \
            best = I; \
            loopi(4) if(*o[i] LT best) best = *o[q = i] - M; \
            par = (best&(~7)) + N; \
            /* dual layer for extra smoothness */ \
            if(*o[q^3] GT par && !(*o[q^1] LT par || *o[q^2] LT par)) { \
                if(*o[q^3] GT par A 8 || *o[q^1] != par || *o[q^2] != par) { \
                    *o[q^3] = (*o[q^3] GT par A 8 ? par A 8 : *o[q^3]); \
                    *o[q^1] = *o[q^2] = par; \
                    changed = true; \
                } \
            /* single layer */ \
            } else { \
                loopj(4) if(*o[j] GT par) { \
                    *o[j] = par; \
                    changed = true; \
                } \
            } \
        } while(0)
Referenced by hmap::ripple().
#define selcube (x, y, z) blockcube(x, y, z, sel, sel.grid)
Referenced by mpflip(), and mprotate().
Enumeration Type Documentation
anonymous enum
Enumerator
EDITMATF_EMPTY
EDITMATF_NOTEMPTY
EDITMATF_SOLID
EDITMATF_NOTSOLID
Function Documentation
void addundo (undoblock * u)
References undolist::add(), pruneundos(), undoblock::size, undoblock::timestamp, totalmillis, totalundos, undos, and undosize().
Referenced by makeundo(), and makeundoent().
void blockcopy (const block3 & s, int rgrid, block3 * b)
References block3::c(), copycube(), and loopxyz.
Referenced by blockcopy(), mpcopy(), newundocube(), and saveprefab().
block3* blockcopy (const block3 & s, int rgrid)
References blockcopy(), and block3::size().
cube& blockcube (int x, int y, int z, const block3 & b, int rgrid)
looks up a world cube, based on coordinates mapped by the block
References ivec::add(), hmap::dc, dimcoord, dimension, block3::grid, lookupcube(), block3::o, block3::orient, and block3::s.
Referenced by mpeditface().
int bounded (int n)
Referenced by pushedge().
void boxs (int orient, vec o, const vec & s, float size)
renders a rectangular box to the target location with faked thick lines
References vec::add(), gle::attrib(), gle::begin(), boxoutline, C, D, hmap::d, hmap::dc, dimcoord, dimension, gle::end(), f(), R, and xtraverts.
Referenced by boxs3D(), rendereditcursor(), and renderentselection().
void boxs (int orient, vec o, const vec & s)
renders a rectangular box to the target location
Parameters
orient cube face orientation index (3 dimensions x 2 directions = 6 possible orientation indices)
o target rendering position
s a constant scalar vector
References gle::attrib(), gle::begin(), boxoutline, C, D, hmap::d, hmap::dc, dimcoord, dimension, gle::end(), f(), R, and xtraverts.
void boxs3D (const vec & o, vec s, int g)
render cube (6 boxes) to target location
Parameters
o selection start vector
s selection end vector
g gridsize
References boxs(), loopi(), and vec::mul().
Referenced by rendereditcursor(), and renderentselection().
void boxsgrid (int orient, vec o, vec s, int g)
renders box grid on the face of the selected volume/area
Parameters
orient orientation
o origin vector (start)
s end vector
g grid size
References gle::attrib(), gle::begin(), boxoutline, C, D, hmap::d, hmap::dc, dimcoord, dimension, gle::end(), f(), loop, R, and xtraverts.
Referenced by rendereditcursor().
void brushvert (int * x, int * y, int * v)
References brush, brushmaxx, brushmaxy, brushminx, brushminy, inexor::rpc::max(), MAXBRUSH, MAXBRUSH2, inexor::rpc::min(), and paintbrush.
void cancelsel ()
reset the current selection called every time user changes grid size or editing status
See Also
cubecancel
entcancel
References cubecancel(), and entcancel().
Referenced by resetmap(), and toggleedit().
uint cflip (uint face)
Referenced by flipcube(), and rotatecube().
void changed (const block3 & sel, bool commit = true)
validates editing changes using readychanges() and calls commitchanges()
See Also
readychanges
commitchanges
References ivec::add(), commitchanges(), block3::grid, haschanged, ivec::iszero(), ivec::mul(), block3::o, readychanges(), block3::s, ivec::sub(), worldroot, and worldsize.
Referenced by changebatchtmus(), emptyvslot(), loadvslot(), loadvslots(), mpcopy(), mpflip(), mprotate(), previewblends(), hmap::ripple(), hmap::run(), saveprefab(), swapundo(), unpackundo(), and unpackvslot().
void cleanupprefabs ()
References prefab::cleanup(), enumerate, and prefabs.
Referenced by resetgl().
void clearbrush ()
References brush, brushmaxx, brushmaxy, brushminx, brushminy, MAXBRUSH, and paintbrush.
void clearundos ()
References pruneundos().
COMMAND (entcancel , "")
cubescript command hook: remove entity selection
COMMAND (cubecancel , "")
cubescript command hook: remove cube selection
COMMAND (cancelsel , "")
cubescript command hook: remove both cube and entity selection
COMMAND (reorient , "")
cubescript command hook: change orientation of selected cubes according to the cursor
COMMAND (selextend , "")
cubescript command hook: extend selection of cubes according to the cursor
COMMAND (clearundos , "")
COMMAND (delprefab , "s")
COMMAND (saveprefab , "s")
COMMAND (pasteprefab , "s")
COMMAND (copy , "")
COMMAND (pastehilite , "")
COMMAND (paste , "")
COMMAND (clearbrush , "")
COMMAND (brushvert , "iii")
COMMAND (hmapcancel , "")
COMMAND (pushsel , "i")
COMMAND (editface , "ii")
COMMAND (delcube , "")
COMMAND (vdelta , "s")
COMMAND (vrotate , "i")
COMMAND (voffset , "ii")
COMMAND (vscroll , "ff")
COMMAND (vscale , "f")
COMMAND (vlayer , "i")
COMMAND (valpha , "ff")
COMMAND (vcolor , "fff")
COMMAND (vreset , "")
COMMAND (vshaderparam , "sffff")
COMMAND (gettex , "")
COMMAND (getcurtex , "")
COMMAND (getseltex , "")
COMMAND (gettexname , "ii")
COMMAND (flip , "")
COMMAND (rotate , "i")
COMMAND (editmat , "ss")
COMMAND (showtexgui , "i")
COMMANDN (undo , editundo , "")
COMMANDN (redo , editredo , "")
COMMANDN (edittex , edittex_ , "i")
void commitchanges (bool force)
commits changes in geometry
References entitiesinoctanodes(), haschanged, inbetweenframes, invalidatepostfx(), vector< T, MINSIZE >::length(), octarender(), resetblobs(), resetclipplanes(), setupmaterials(), updatevabbs(), and valist.
Referenced by changed(), previewblends(), swapundo(), and unpackundo().
void compacteditvslots ()
References block3::c(), compactvslot(), compactvslots(), editinfo::copy, editinfos, editingvslots, undolist::first, loopv, undoblock::next, redos, block3::size(), undos, and unpackingvslots.
Referenced by compactvslots().
void compactmruvslots ()
References curtexindex, VSlot::index, lasttex, loopvrev, remappedvslots, vector< T, MINSIZE >::remove(), reptex, texmru, and vslots.
Referenced by compactvslots().
static bool compresseditinfo (const uchar * inbuf, int inlen, uchar *& outbuf, int & outlen) static
Referenced by packeditinfo(), and packundo().
void copy ()
References localedit, mpcopy(), noedit(), and sel.
Referenced by loadprefab(), and prefab::~prefab().
static void copycube (const cube & src, cube & dst) inline static
References cube::children, cube::ext, F_EMPTY, loopi(), cube::merged, and newcubes().
Referenced by blockcopy(), and pastecube().
static int countblock (cube * c, int n = 8) inline static
References loopi().
Referenced by countblock(), and swapundo().
static int countblock (block3 * b) static
References block3::c(), countblock(), and block3::size().
void countselchild (cube * c, const ivec & cor, int size)
count the number of selected child cubes and materials in your selection
See Also
gl_drawhud
selchildcount
selected volume * grid = list of child cubes
References selinfo::grid, loopoctaboxsize, MAT_AIR, cube::material, ivec::mul(), selinfo::o, selinfo::s, sel, selchildcount, and selchildmat.
Referenced by rendereditcursor().
void cubecancel ()
aborts heightsmap editing and resets selection data
See Also
forcenextundo
forcenextundo
References forcenextundo(), havesel, hmapcancel(), and moving.
Referenced by cancelsel().
void delcube ()
References mpdelcube(), noedit(), and sel.
void delprefab (char * name)
References prefab::cleanup(), inexor::util::log_manager::edit, Log, and prefabs.
uint dflip (uint face)
References F_EMPTY.
Referenced by flipcube(), and rotatecube().
void editface (int * dir, int * mode)
References edithmap(), moving, mpeditface(), noedit(), and sel.
void edithmap (int dir, int mode)
References hmapsel, multiplayer(), nompedit, and hmap::run().
Referenced by editface().
void editmat (char * name, char * filtername)
References editmatfilters, findmaterial(), Log, loopi(), mpeditmat(), noedit(), sel, and inexor::util::log_manager::std.
bool editmoveplane (const vec & o, const vec & ray, int d, float off, vec & handle, vec & dest, bool first)
move the selection grid (the "plane") along the selection has an origin and can only be moved in 2 dimensions simultaneously
References vec::add(), vec::mul(), physent::o, player, plane::rayintersect(), and vec::sub().
Referenced by entdrag(), and rendereditcursor().
void editredo ()
References EDIT_REDO, redos, swapundo(), and undos.
void edittex (int i, bool save = true)
References curtexindex, lasttex, lasttexmillis, loopvj, mpedittex(), save(), sel, texmru, and totalmillis.
Referenced by edittex_(), and texturegui::gui().
void edittex_ (int * dir)
References curtexindex, edittex(), vector< T, MINSIZE >::empty(), filltexlist(), lastsel, vector< T, MINSIZE >::length(), noedit(), sel, texmru, texpaneltimer, and tofronttex().
void edittexcube (cube & c, int tex, int orient, bool & findrep)
References cube::children, loopi(), reptex, cube::texture, and visibleorient().
Referenced by mpedittex().
void editundo ()
References EDIT_UNDO, redos, swapundo(), and undos.
void entdrag (const vec & ray)
References ivec::add(), C, hmap::d, hmap::dc, dimcoord, dimension, editmoveplane(), entfocus, entgroup, entmoving, entorient, entselectionbox(), selinfo::grid, groupeditpure, haveselent(), vector< T, MINSIZE >::last(), makeundoent(), ivec::mask(), noentedit(), R, and sel.
Referenced by rendereditcursor().
void filltexlist ()
References vector< T, MINSIZE >::add(), curtexindex, vector< T, MINSIZE >::find(), vector< T, MINSIZE >::length(), loopv, loopvrev, vector< T, MINSIZE >::remove(), texmru, and vslots.
Referenced by edittex_(), getcurtex(), gettex(), and texturegui::show().
void flip ()
References mpflip(), noedit(), and sel.
Referenced by aviwriter::compressyuv(), aviwriter::encodeyuv(), and aviwriter::scaleyuv().
void flipcube (cube & c, int d)
References C, cflip(), cube::children, D, hmap::d, dflip(), loopi(), octadim, R, rflip(), and cube::texture.
Referenced by mpflip().
void forcenextundo ()
reset orientation of the last selection this is called every time the user changes grid size or editing status
References lastsel, and selinfo::orient.
Referenced by cubecancel(), hmap::run(), and swapundo().
void freeblock (block3 * b, bool alloced = true)
References block3::c(), discardchildren(), loopi(), and block3::size().
Referenced by freeeditinfo(), freeundo(), mpcopy(), saveprefab(), unpackblock(), unpackeditinfo(), unpackundo(), and prefab::~prefab().
void freeeditinfo (editinfo *& e)
References editinfo::copy, editinfos, and freeblock().
Referenced by fpsent::~fpsent().
void freeundo (undoblock * u)
References undoblock::block(), freeblock(), and undoblock::numents.
Referenced by pruneundos(), and swapundo().
void g3d_texturemenu ()
Referenced by g3d_render().
static void genprefabmesh (prefabmesh & r, cube & c, const ivec & co, int size) static
References vector< T, MINSIZE >::add(), vec::add(), prefabmesh::addvert(), cube::children, f(), faceconvexity(), flataxisface(), genfaceverts(), guessnormals(), isempty, loopi(), loopj, vec::mul(), neighbourdepth, neighbourstack, sphere::numverts, prefabmesh::tris, and visibletris().
Referenced by genprefabmesh(), and renderprefab().
void genprefabmesh (prefab & p)
References block3::c(), cube::children, editinfo::copy, freeocta(), genprefabmesh(), block3::grid, isempty, loopi(), loopxyz, inexor::rpc::max(), neighbourdepth, neighbourstack, newcubes(), block3::o, pastecube(), block3::s, useshaderbyname(), worldroot, worldscale, and worldsize.
void getcurtex ()
References curtexindex, filltexlist(), vector< T, MINSIZE >::inrange(), intret(), noedit(), and texmru.
static ushort getmaterial (cube & c) static
References cube::children, loopi(), MAT_AIR, and cube::material.
Referenced by mpeditface().
void getseltex ()
References cube::children, selinfo::grid, intret(), isempty, lookupcube(), noedit(), selinfo::o, selinfo::orient, sel, and cube::texture.
void gettex ()
References curtexindex, filltexlist(), selinfo::grid, loopv, loopxyz, noedit(), selinfo::orient, sel, texmru, and tofronttex().
void gettexname (int * tex, int * subslot)
References lookupvslot(), noedit(), result(), VSlot::slot, and Slot::sts.
bool hastexcube (cube & c, int tex)
References cube::children, loopi(), and cube::texture.
void hmapcancel ()
References htextures, and vector< T, MINSIZE >::setsize().
Referenced by cubecancel().
bool hoveringonent (int ent, int orient)
References efocus, vector< T, MINSIZE >::empty(), entgroup, enthover, entorient, vector< T, MINSIZE >::last(), noentedit(), and orient.
Referenced by rendereditcursor().
ICOMMAND (moving , "b" , (int *n) , {if(*n >=0){if(!*n||(moving<=1 &&!pointinsel(sel, vec(cur).add(1)))) moving=0;else if(!moving) moving=1;}intret(moving);})
ICOMMAND (edittoggle , "" , () , toggleedit(false))
cubescript command hook: toggle editing
ICOMMAND (selmoved , "" , () , {if(noedit(true)) return;intret(sel.o!=savedsel.o?1:0);})
ICOMMAND (selrestore , "" , () , {if(noedit(true)) return;sel=savedsel;})
ICOMMAND (selsave , "" , () , {if(noedit(true)) return;savedsel=sel;})
ICOMMAND (selswap , "" , () , {if(noedit(true)) return;swap(sel, savedsel);})
ICOMMAND (havesel , "" , () , intret(havesel?selchildcount:0))
cubescript: return number of selected cubes
See Also
selchildcount
ICOMMAND (hmapselect , "" , () , int t = lookupcube(cur).texture[orient];int i=htextures.find(t);if(i< 0) htextures.add(t);else htextures.remove(i);)
ICOMMAND (getreptex , "" , () , {if(!noedit()) intret(vslots.inrange(reptex)?reptex:-1);})
ICOMMAND (replace , "" , () , replace(false))
ICOMMAND (replacesel , "" , () , replace(true))
bool isheightmap (int orient, int d, bool empty, cube * c) inline
References vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::find(), havesel, htextures, isempty, and cube::texture.
Referenced by hmap::getcube(), and rendereditcursor().
void linkedpush (cube & c, int d, int x, int y, int dc, int dir)
References cubeedge, getcubevector(), loopi(), loopj, and pushedge().
Referenced by mpeditface().
prefab* loadprefab (const char * name, bool msg = true)
References editinfo::copy, copy(), defformatstring, f(), lilswap(), Log, prefabheader::magic, prefab::name, newstring(), opengzfile(), path(), prefabs, stream::read(), inexor::util::log_manager::std, unpackblock(), and prefabheader::version.
Referenced by pasteprefab(), previewprefab(), and renderprefab().
void makeundo (selinfo & s)
References addundo(), and newundocube().
Referenced by makeundo(), mpflip(), mprotate(), and hmap::select().
void makeundo ()
References ivec::iszero(), lastsel, makeundo(), selinfo::s, and sel.
uint mflip (uint face)
Referenced by rotatecube().
void mpcopy (editinfo *& e, selinfo & sel, bool local)
References blockcopy(), changed(), editinfo::copy, EDIT_COPY, editinfos, game::edittrigger(), freeblock(), selinfo::grid, and protectsel.
Referenced by copy(), and game::parsemessages().
void mpdelcube (selinfo & sel, bool local)
References discardchildren(), EDIT_DELCUBE, game::edittrigger(), emptyfaces, and loopselxyz.
Referenced by delcube(), and game::parsemessages().
void mpeditface (int dir, int mode, selinfo & sel, bool local)
References blockcube(), C, cube::children, selinfo::corner, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, hmap::d, hmap::dc, DEFAULT_GEOM, dimcoord, dimension, dir, discardchildren(), EDIT_FACE, game::edittrigger(), emptyfaces, getmaterial(), selinfo::grid, isvalidcube(), linkedpush(), loop, loopi(), loopk, loopselxyz, hmap::mx, hmap::my, selinfo::o, optiface(), selinfo::orient, R, selinfo::s, solidfaces, cube::texture, selinfo::us(), and worldsize.
Referenced by editface(), and game::parsemessages().
void mpeditmat (int matid, int filter, selinfo & sel, bool local)
References EDIT_MAT, game::edittrigger(), isclipped, isdeadly, loopselxyz, MAT_CLIP, MAT_DEATH, MATF_CLIP, MATF_INDEX, MATF_VOLUME, and setmat().
Referenced by editmat(), and game::parsemessages().
void mpedittex (int tex, int allfaces, selinfo & sel, bool local)
References EDIT_TEX, edittexcube(), game::edittrigger(), loopselxyz, selinfo::orient, repsel, reptex, and sel.
Referenced by edittex(), mpedittex(), and game::parsemessages().
bool mpedittex (int tex, int allfaces, selinfo & sel, ucharbuf & buf)
References mpedittex(), and unpacktex().
void mpeditvslot (int delta, VSlot & ds, int allfaces, selinfo & sel, bool local)
References vector< T, MINSIZE >::add(), curtexindex, EDIT_VSLOT, game::edittrigger(), vector< T, MINSIZE >::find(), VSlot::index, lastsel, lasttex, lasttexmillis, vector< T, MINSIZE >::length(), loopselxyz, selinfo::orient, remappedvslots, remapvslots(), repsel, reptex, sel, texmru, tofronttex(), and totalmillis.
Referenced by mpeditvslot(), game::parsemessages(), valpha(), vcolor(), vlayer(), voffset(), vreset(), vrotate(), vscale(), vscroll(), and vshaderparam().
bool mpeditvslot (int delta, int allfaces, selinfo & sel, ucharbuf & buf)
References editingvslot, VSlot::layer, mpeditvslot(), and unpackvslot().
void mpflip (selinfo & sel, bool local)
References changed(), dimension, EDIT_FLIP, game::edittrigger(), flipcube(), loop, loopxy, makeundo(), selinfo::orient, selinfo::s, and selcube.
Referenced by flip(), and game::parsemessages().
void mppaste (editinfo *& e, selinfo & sel, bool local)
References editinfo::copy, EDIT_PASTE, game::edittrigger(), and pasteblock().
Referenced by game::parsemessages(), and paste().
void mpreplacetex (int oldtex, int newtex, bool insel, selinfo & sel, bool local, bool update)
References allchanged(), EDIT_REPLACE, game::edittrigger(), loopi(), loopselxyz, replacetexcube(), and worldroot.
Referenced by mpreplacetex(), game::parsemessages(), and replace().
bool mpreplacetex (int oldtex, int newtex, bool insel, selinfo & sel, ucharbuf & buf)
References editingvslot, mpreplacetex(), and unpacktex().
void mprotate (int cw, selinfo & sel, bool local)
References C, changed(), D, hmap::d, dimcoord, dimension, EDIT_ROTATE, game::edittrigger(), loop, loopi(), loopxy, makeundo(), inexor::rpc::max(), selinfo::orient, R, rotatecube(), rotatequad(), selinfo::s, and selcube.
Referenced by game::parsemessages(), and rotate().
undoblock* newundocube (selinfo & s)
References blockcopy(), selinfo::grid, undoblock::gridmap(), undoblock::numents, selgridmap(), and selinfo::size().
Referenced by makeundo(), and swapundo().
bool noedit (bool view, bool msg)
check if user is allowed to edit concerns may be a scene selection which is not in view or disbaled editing status
References vec::add(), inexor::util::log_manager::edit, editmode, selinfo::grid, haveselent(), isvisiblesphere(), Log, inexor::rpc::max(), vec::mul(), selinfo::o, selinfo::s, sel, and VFC_NOT_VISIBLE.
Referenced by canpaintblendmap(), clearblendmapsel(), clearlightmaps(), copy(), delcube(), ai::delselwaypoints(), editface(), editmat(), edittex_(), flip(), getcurtex(), getseltex(), gettex(), gettexname(), invertblendmap(), invertblendmapsel(), ai::movewaypoints(), paste(), pasteprefab(), patchlight(), pushsel(), replace(), rotate(), saveprefab(), selextend(), showblendmap(), shrinkmap(), swapundo(), valpha(), vcolor(), vdelta(), vlayer(), voffset(), vreset(), vrotate(), vscale(), vscroll(), and vshaderparam().
void normalizelookupcube (const ivec & o)
get the selected cube's position from the origin vector (0,0,0)
References gridsize, lu, and lusize.
Referenced by rendereditcursor().
template<class B > static bool packblock (block3 & b, B & buf) static
References block3::c(), block3::grid, lilswap(), loopi(), block3::o, block3::orient, packcube(), block3::s, and block3::size().
Referenced by packeditinfo(), packundo(), and saveprefab().
template<class B > static void packcube (cube & c, B & buf) static
References cube::children, lilswap(), loopi(), cube::material, and cube::texture.
Referenced by packblock().
bool packeditinfo (editinfo * e, int & inlen, uchar *& outbuf, int & outlen)
References compresseditinfo(), editinfo::copy, vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), packblock(), and packvslots().
Referenced by game::sendclipboard().
bool packundo (undoblock * u, int & inlen, uchar *& outbuf, int & outlen)
References entity::attr1, undoblock::block(), compresseditinfo(), undoent::e, undoblock::ents(), vector< T, MINSIZE >::getbuf(), undoblock::gridmap(), vector< T, MINSIZE >::length(), lilswap(), loopi(), undoblock::numents, entity::o, packblock(), packvslots(), vector< T, MINSIZE >::pad(), vector< T, MINSIZE >::put(), vector< T, MINSIZE >::reserve(), and block3::size().
Referenced by game::edittrigger(), and packundo().
bool packundo (int op, int & inlen, uchar *& outbuf, int & outlen)
References EDIT_REDO, EDIT_UNDO, undolist::empty(), undolist::last, packundo(), redos, and undos.
static void packvslots (cube & c, vector< uchar > & buf, vector< ushort > & used) static
References vector< T, MINSIZE >::add(), cube::children, vector< T, MINSIZE >::find(), Slot::index, vslothdr::index, lilswap(), loopi(), packvslot(), vector< T, MINSIZE >::pad(), VSlot::slot, vslothdr::slot, cube::texture, and vslots.
Referenced by packeditinfo(), packundo(), and packvslots().
static void packvslots (block3 & b, vector< uchar > & buf) static
References block3::c(), loopi(), packvslots(), vector< T, MINSIZE >::pad(), and block3::size().
void paste ()
References localedit, mppaste(), noedit(), and sel.
void pasteblock (block3 & b, selinfo & sel, bool local)
References block3::c(), cube::children, isempty, loopselxyz, MAT_AIR, cube::material, selinfo::orient, block3::orient, pastecube(), selinfo::s, and block3::s.
Referenced by mppaste(), and pasteprefab().
static void pastecube (const cube & src, cube & dst) inline static
References copycube(), and discardchildren().
Referenced by genprefabmesh(), pasteblock(), and pasteundoblock().
void pastehilite ()
References editinfo::copy, havesel, localedit, reorient(), selinfo::s, block3::s, and sel.
void pasteprefab (char * name)
References editinfo::copy, loadprefab(), multiplayer(), noedit(), nompedit, pasteblock(), and sel.
void pasteundo (undoblock * u)
References undoblock::block(), undoblock::gridmap(), undoblock::numents, pasteundoblock(), and pasteundoents().
Referenced by swapundo().
void pasteundoblock (block3 * b, uchar * g)
References block3::c(), loopxyz, inexor::rpc::min(), pastecube(), and worldscale.
Referenced by pasteundo(), and unpackundo().
void previewprefab (const char * name, const vec & color)
References calcmodelpreviewpos(), editinfo::copy, block3::grid, loadprefab(), vec::mul(), renderprefab(), and block3::s.
Referenced by gui::prefabpreview().
void pruneundos (int maxremain)
References undolist::empty(), freeundo(), undolist::popfirst(), redos, undoblock::size, totalundos, and undos.
Referenced by addundo(), clearundos(), and resetmap().
void pushedge (uchar & edge, int dir, int dc)
References bounded(), edgeget, and edgeset.
Referenced by linkedpush().
void pushsel (int * dir)
References hmap::d, dimcoord, dimension, dir, selinfo::grid, moving, noedit(), physent::o, selinfo::o, orient, player, physent::resetinterp(), and sel.
float rayent (const vec & o, const vec & ray, float radius, int mode, int size, int & orient, int & ent)
References disttooutsideent(), hitent, hitentdist, hitorient, RAY_ENTS, and raycube().
Referenced by rendereditcursor().
void readychanges (const ivec & bbmin, const ivec & bbmax, cube * c, const ivec & cor, int size)
checks and validates changes in the octree system
References brightencube(), destroyva(), discardchildren(), ext(), cube::ext, freeoctaentities(), vtxarray::hasmerges, invalidatemerges(), loopoctabox, solidfaces, cubeext::tjoints, and cubeext::va.
Referenced by changed().
static VSlot* remapvslot (int index, bool delta, const VSlot & ds) static
References VSlot::changed, DEFAULT_SKY, editvslot(), VSlot::index, lookupvslot(), loopv, mergevslot(), remappedvslots, VSlot::slot, and Slot::variants.
Referenced by remapvslots().
static void remapvslots (cube & c, bool delta, const VSlot & ds, int orient, bool & findrep, VSlot *& findedit) static
References cube::children, VSlot::index, loopi(), remapvslot(), reptex, cube::texture, and visibleorient().
Referenced by mpeditvslot().
void rendereditcursor ()
render selection box to the cursor target also moves entities!
References vec::add(), blendpaintmode, boxoutline, boxs(), boxs3D(), boxsgrid(), C, camdir, cor, selinfo::corner, countselchild(), cur, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, D, hmap::d, dimcoord, dimension, disablepolygonoffset(), editmode, editmoveplane(), enablepolygonoffset(), entdrag(), entediting, entmoving, entorient, f(), g3d_windowhit(), GL_ONE, selinfo::grid, gridsize, havesel, hmapsel, horient, hoveringonent(), insideworld(), isheightmap(), lastcor, lookupcube(), loopi(), lu, lusize, ivec::mask(), cube::material, inexor::rpc::max(), inexor::rpc::min(), moving, vec::mul(), normalizelookupcube(), notextureshader, physent::o, selinfo::o, orient, selinfo::orient, outline, player, R, RAY_EDITMAT, RAY_ENTS, RAY_PASS, RAY_SKIPFIRST, rayboxintersect(), rayent(), renderentselection(), selinfo::s, sel, selchildcount, selchildmat, Shader::set(), showmat, vec::sub(), anonymous_namespace{utilTest.cpp}::t(), updateselection(), worldroot, and worldsize.
Referenced by gl_drawhud().
void renderentselection (const vec & o, const vec & ray, bool entmoving)
References gle::begin(), boxs(), boxs3D(), camera1, vec::dist(), gle::end(), entfocus, entgroup, enthover, entorient, entselectionbox(), f(), fovy, vector< T, MINSIZE >::length(), loopv, noentedit(), physent::o, RAD, renderentbox(), renderentradius(), worldsize, and xtraverts.
Referenced by rendereditcursor().
static void renderprefab (prefab & p, const vec & o, float yaw, float pitch, float roll, float size, const vec & color) static
References gle::bindebo(), gle::bindvbo(), camprojmatrix, gle::clearebo(), gle::clearvbo(), gle::color(), editinfo::copy, disablepolygonoffset(), prefab::ebo, enablepolygonoffset(), genprefabmesh(), glDrawRangeElements_, GLOBALPARAM, block3::grid, vec::hexcolor(), matrix4::identity(), vec::mul(), matrix4::mul(), prefabmesh::vertex::norm, prefab::numtris, prefab::numverts, outlinecolour, prefabmesh::vertex::pos, RAD, matrix4::rotate_around_x(), matrix4::rotate_around_y(), matrix4::rotate_around_z(), block3::s, matrix4::scale(), SETSHADER, matrix4::settranslation(), matrix4::translate(), and prefab::vbo.
Referenced by previewprefab(), and renderprefab().
void renderprefab (const char * name, const vec & o, float yaw, float pitch, float roll, float size, const vec & color)
References loadprefab(), and renderprefab().
void rendertexturepanel (int w, int h)
render quick selection preview for surface textures standard edit key binding: press Z
References gle::attrib(), gle::begin(), gle::color(), VSlot::colorscale, curtexindex, curtime, editmode, gle::end(), f(), flushhudmatrix(), GL_ONE, VSlot::glowcolor, hudmatrix, hudshader, Texture::id, vector< T, MINSIZE >::inrange(), VSlot::layer, lookupvslot(), loopi(), loopj, loopk, loopvj, inexor::rpc::min(), vec::mul(), notexture, VSlot::offset, pophudmatrix(), pushhudmatrix(), VSlot::rotation, matrix4::scale(), Shader::set(), SETSHADER, VSlot::slot, Slot::sts, TEX_GLOW, Slot::texmask, texmru, texpaneltimer, Texture::xs, xtraverts, and Texture::ys.
Referenced by gl_drawhud().
void reorient ()
change the selection orientation according to the cursor's position
References C, selinfo::cx, selinfo::cxs, selinfo::cy, selinfo::cys, dimension, orient, selinfo::orient, R, selinfo::s, and sel.
Referenced by pastehilite(), and swapundo().
void replace (bool insel)
References lasttex, Log, mpreplacetex(), noedit(), reptex, sel, and inexor::util::log_manager::std.
void replacetexcube (cube & c, int oldtex, int newtex)
References cube::children, loopi(), and cube::texture.
Referenced by mpreplacetex().
uint rflip (uint face)
Referenced by flipcube(), and rotatecube().
void rotate (int * cw)
References mprotate(), noedit(), and sel.
Referenced by renderentarrow(), and renderentcone().
void rotatecube (cube & c, int d)
References C, cflip(), cube::children, D, hmap::d, dflip(), loopi(), mflip(), octadim, R, rflip(), rotatequad(), and cube::texture.
Referenced by mprotate().
void rotatequad (cube & a, cube & b, cube & c, cube & d)
References hmap::d, and anonymous_namespace{utilTest.cpp}::t().
Referenced by mprotate(), and rotatecube().
void saveprefab (char * name)
References blockcopy(), changed(), editinfo::copy, defformatstring, inexor::util::log_manager::edit, f(), freeblock(), selinfo::grid, lilswap(), Log, prefabheader::magic, multiplayer(), prefab::name, newstring(), noedit(), nompedit, opengzfile(), packblock(), path(), prefabs, protectsel, sel, inexor::util::log_manager::std, prefabheader::version, and stream::write().
void selextend ()
extend the selection according to the cursor's position
References cur, selinfo::grid, loopi(), noedit(), selinfo::o, selinfo::s, and sel.
void selgridmap (selinfo & sel, uchar * g)
References bitscan(), selinfo::grid, loopxyz, and lusize.
Referenced by newundocube().
void setmat (cube & c, ushort mat, ushort matmask, ushort filtermat, ushort filtermask, int filtergeom)
References cube::children, EDITMATF_EMPTY, EDITMATF_NOTEMPTY, EDITMATF_NOTSOLID, EDITMATF_SOLID, isempty, isentirelysolid, loopi(), MAT_AIR, and cube::material.
Referenced by mpeditmat().
int shouldpacktex (int index)
References VSlot::changed, Slot::index, VSlot::slot, and vslots.
Referenced by game::edittrigger().
void showtexgui (int * n)
show texture
References inexor::util::log_manager::edit, editmode, and Log.
SVARP (prefabdir , "prefab")
void swapundo (undolist & a, undolist & b, int op)
References undolist::add(), undoblock::block(), changed(), commitchanges(), copyundoents(), countblock(), EDIT_REDO, game::edittrigger(), undolist::empty(), forcenextundo(), freeundo(), selinfo::grid, block3::grid, hmapsel, undolist::last, Log, multiplayer(), newundocube(), noedit(), nompedit, undoblock::numents, selinfo::o, block3::o, selinfo::orient, block3::orient, pasteundo(), undolist::poplast(), reorient(), selinfo::s, block3::s, sel, undoblock::size, inexor::util::log_manager::std, undoblock::timestamp, and totalmillis.
Referenced by editredo(), and editundo().
void tofronttex ()
References curtexindex, vector< T, MINSIZE >::inrange(), vector< T, MINSIZE >::insert(), vector< T, MINSIZE >::remove(), and texmru.
Referenced by edittex_(), gettex(), and mpeditvslot().
void toggleedit (bool force)
change editing status also cancel selection, blendmaps and more
Parameters
force represents if the user was forced by administrators
References game::allowedittoggle(), cancelsel(), CS_ALIVE, CS_DEAD, CS_EDITING, editmode, physent::editstate, game::edittoggled(), entediting, entinmap(), physent::eyeheight, initlights(), inexor::io::input_router, isconnected(), inexor::io::InputRouter::keyrepeat(), KR_EDITMODE, lightents(), physent::o, player, game::resetgamestate(), physent::state, and stoppaintblendmap().
Referenced by game::changemapserv(), game::gameconnect(), and game::parsemessages().
void tryedit ()
check if editing can be done
Warning
please note that editing is not allowed when the HUD (head up dispaly) is disabled!
References blendpaintmode, editmode, mainmenu, and trypaintblendmap().
Referenced by main().
static bool uncompresseditinfo (const uchar * inbuf, int inlen, uchar *& outbuf, int & outlen) static
Referenced by unpackeditinfo(), and unpackundo().
static int undosize (undoblock * u) inline static
References undoblock::block(), block3::c(), familysize(), loopj, undoblock::numents, and block3::size().
Referenced by addundo().
template<class B > static bool unpackblock (block3 *& b, B & buf) static
References block3::c(), freeblock(), block3::grid, lilswap(), loopi(), block3::o, block3::orient, block3::s, block3::size(), and unpackcube().
Referenced by loadprefab(), unpackeditinfo(), and unpackundo().
template<class B > static void unpackcube (cube & c, B & buf) static
References cube::children, F_EMPTY, lilswap(), loopi(), cube::material, newcubes(), and cube::texture.
Referenced by unpackblock().
bool unpackeditinfo (editinfo *& e, const uchar * inbuf, int inlen, int outlen)
References editinfo::copy, editinfos, freeblock(), uncompresseditinfo(), unpackblock(), and unpackvslots().
Referenced by game::parsemessages().
static int unpacktex (int & tex, ucharbuf & buf, bool insert = true) static
References DEFAULT_SKY, editvslot(), Slot::findvariant(), VSlot::index, lookupslot(), VSlot::slot, unpackvslot(), and Slot::variants.
Referenced by mpedittex(), and mpreplacetex().
bool unpackundo (const uchar * inbuf, int inlen, int outlen)
References changed(), commitchanges(), freeblock(), block3::grid, lilswap(), loopi(), databuf< T >::pad(), pasteundoblock(), pasteundoent(), databuf< T >::remaining(), block3::size(), uncompresseditinfo(), unpackblock(), unpackvslots(), and worldsize.
Referenced by game::parsemessages().
static void unpackvslots (cube & c, ucharbuf & buf) static
References cube::children, loopi(), loopvj, cube::texture, and unpackingvslots.
Referenced by unpackeditinfo(), unpackundo(), and unpackvslots().
static void unpackvslots (block3 & b, ucharbuf & buf) static
References block3::c(), DEFAULT_SKY, editvslot(), VSlot::index, vslothdr::index, lilswap(), lookupslot(), loopi(), databuf< T >::pad(), databuf< T >::remaining(), block3::size(), vslothdr::slot, unpackingvslots, unpackvslot(), unpackvslots(), and Slot::variants.
void updateselection ()
validate the coordinates of the selected face/volume make sure the selected grid is not outside of the map
See Also
sel
References cur, selinfo::grid, lastcur, inexor::rpc::min(), selinfo::o, selinfo::s, and sel.
Referenced by rendereditcursor().
void valpha (float * front, float * back)
References VSlot::alphaback, VSlot::alphafront, VSlot::changed, f(), mpeditvslot(), noedit(), sel, and VSLOT_ALPHA.
VAR (passthroughsel , 0 , 0 , 1)
allow the editor to select new areas/volumes through the current selection otherwise select cubes ON the current selection
VAR (editing , 1 , 0 , 0)
represent the user's editing status (is he editing or not?)
VAR (selectcorners , 0 , 0 , 1)
when intruding (pushing towards the inside) a selected cube/face keep the corners rounded
VAR (gridlookup , 0 , 0 , 1)
automaticly select the grid size of the selected face
VAR (passthroughcube , 0 , 1 , 1)
ignore the first cube when view ray intersects it and select the second ("select through cubes")
VAR (brushx , 0 , MAXBRUSH2 , MAXBRUSH)
VAR (brushy , 0 , MAXBRUSH2 , MAXBRUSH)
VAR (invalidcubeguard , 0 , 1 , 1)
VAR (selectionsurf , 0 , 0 , 1)
VAR (usevdelta , 1 , 0 , 0)
VAR (allfaces , 0 , 0 , 1)
VARF (dragging , 0 , 0 , 1 , if(!dragging||cor[0]< 0) return; lastcur = cur;lastcor=cor;sel.grid=gridsize;sel.orient=orient;)
dragging is enabled (1) once a grid start cube is selected once you select a cube the selection box will be drawn a little brighter
Warning
this has nothing to do with particles, pickups or entities!
VARF (gridpower , 0 , 3 , 12 , {if(dragging) return;gridsize=1<< gridpower;if(gridsize >=worldsize) gridsize=worldsize/2;cancelsel();})
will be called every time the gridpower (gridsize) changes
VARF (hmapedit , 0 , 0 , 1 , horient = sel.orient)
start/stop heightmap editing
VARP (undomegs , 0 , 5 , 100)
VARP (nompedit , 0 , 1 , 1)
VARP (texguiwidth , 1 , 12 , 1000)
VARP (texguiheight , 1 , 8 , 1000)
VARP (texguitime , 0 , 25 , 1000)
VARP (texgui2d , 0 , 1 , 1)
void vcolor (float * r, float * g, float * b)
References VSlot::changed, VSlot::colorscale, f(), mpeditvslot(), noedit(), sel, and VSLOT_COLOR.
Referenced by htcmp().
void vdelta (char * body)
References execute(), and noedit().
void vlayer (int * n)
References VSlot::changed, editingvslot, VSlot::layer, mpeditvslot(), multiplayer(), noedit(), nompedit, sel, VSLOT_LAYER, and vslots.
void voffset (int * x, int * y)
References VSlot::changed, mpeditvslot(), noedit(), VSlot::offset, sel, and VSLOT_OFFSET.
void vreset ()
References mpeditvslot(), noedit(), and sel.
void vrotate (int * n)
References VSlot::changed, mpeditvslot(), noedit(), VSlot::rotation, sel, and VSLOT_ROTATION.
void vscale (float * scale)
References VSlot::changed, f(), mpeditvslot(), noedit(), VSlot::scale, sel, and VSLOT_SCALE.
void vscroll (float * s, float * t)
References VSlot::changed, vec2::div(), mpeditvslot(), noedit(), VSlot::scroll, sel, and VSLOT_SCROLL.
void vshaderparam (const char * name, float * x, float * y, float * z, float * w)
References vector< T, MINSIZE >::add(), VSlot::changed, getshaderparamname(), mpeditvslot(), noedit(), VSlot::params, sel, and VSLOT_SHPARAM.
Variable Documentation
bool boxoutline = false
Referenced by boxs(), boxsgrid(), and rendereditcursor().
int brush[MAXBRUSH][MAXBRUSH]
Referenced by addblendbrush(), brushvert(), canpaintblendmap(), clearbrush(), hmap::paint(), paintblendmap(), renderblendbrush(), and rotateblendbrush().
int brushmaxx = 0
Referenced by brushvert(), clearbrush(), and hmap::run().
int brushmaxy = 0
Referenced by brushvert(), clearbrush(), and hmap::run().
int brushminx = MAXBRUSH
Referenced by brushvert(), clearbrush(), and hmap::run().
int brushminy = MAXBRUSH
Referenced by brushvert(), clearbrush(), and hmap::run().
ivec cor
Referenced by rendereditcursor().
ivec cur
Referenced by addtjoint(), blobrenderer::addtris(), addvisibleva(), aviwriter::boxsample(), clipfacevecs(), findnormal(), findtjoints(), findtnormal(), findvisiblemms(), Shader::fixdetailshader(), fvariable(), gencubeedges(), hasext(), pvsworker::hasvoxel(), insideface(), game::nextfollow(), optimizematsurfs(), ai::avoidset::remap(), ai::render(), renderalphageom(), rendereditcursor(), rendergeom(), renderlightning(), listrenderer::resettracked(), hmap::run(), savevslots(), selextend(), updateselection(), and variable().
int curtexindex = -1
Referenced by compactmruvslots(), edittex(), edittex_(), filltexlist(), getcurtex(), gettex(), mpeditvslot(), rendertexturepanel(), and tofronttex().
vector<editinfo *> editinfos
Referenced by compacteditvslots(), freeeditinfo(), mpcopy(), and unpackeditinfo().
vector<int *> editingvslots static
Referenced by compacteditvslots(), vslotref::vslotref(), and vslotref::~vslotref().
const { ... } editmatfilters[]
Initial value:
=
{
    { "empty", EDITMATF_EMPTY },
    { "notempty", EDITMATF_NOTEMPTY },
    { "solid", EDITMATF_SOLID },
    { "notsolid", EDITMATF_NOTSOLID }
}
Referenced by editmat().
bool editmode = false
Referenced by game::allowedittoggle(), calclight(), changebatchtmus(), game::changemapserv(), game::drawhudgun(), drawreflections(), drawskybox(), emptymap(), enlargemap(), execbind(), game::gameconnect(), gengrassquads(), gl_drawframe(), gl_drawhud(), initlights(), lightreaching(), limitsky(), flarerenderer::makelightflares(), makeparticles(), noedit(), noentedit(), game::parsemessages(), queryreflections(), rendereditcursor(), rendermaterials(), rendermodel(), rendertexturepanel(), renderwater(), game::selectcrosshair(), texturegui::show(), showtexgui(), sortmaterials(), game::spawnplayer(), toggleedit(), tryedit(), and updateparticles().
SharedVar<int> entediting
Referenced by getentboundingbox(), modifyoctaentity(), noentedit(), rendereditcursor(), and toggleedit().
int entmoving
Referenced by entdrag(), entpush(), and rendereditcursor().
int gridsize = 8
Referenced by hmap::getcube(), normalizelookupcube(), rendereditcursor(), hmap::run(), and hmap::select().
texturegui gui
bool haschanged = false static
Referenced by changed(), and commitchanges().
bool havesel = false
Referenced by cubecancel(), isheightmap(), pastehilite(), rendereditcursor(), and hmap::run().
bool hmapsel = false
Referenced by edithmap(), rendereditcursor(), and swapundo().
int horient = 0
Referenced by rendereditcursor().
vector<int> htextures
Referenced by hmapcancel(), and isheightmap().
ivec lastcor
Referenced by rendereditcursor().
ivec lastcur
Referenced by updateselection().
selinfo lastsel
Referenced by edittex_(), forcenextundo(), makeundo(), and mpeditvslot().
int lasttex = 0
Referenced by compactmruvslots(), edittex(), mpeditvslot(), replace(), and texturegui::showtextures().
int lasttexmillis = -1
Referenced by edittex(), mpeditvslot(), and texturegui::showtextures().
int lastthumbnail = 0 static
Referenced by texturegui::gui().
editinfo* localedit = nullptr
Referenced by copy(), paste(), pastehilite(), and game::sendclipboard().
SharedVar<int> menuautoclose
Referenced by g3d_mainmenu(), and texturegui::show().
SharedVar<int> menudistance
Referenced by menuinfrontofplayer().
int moving = 0
moving will be set to 1 as soon as you right-click a selected area/volume to move it once you release the key, moving(0) will be called
Warning
this has nothing to do with particles, pickups or entities!
Referenced by cubecancel(), editface(), pushsel(), and rendereditcursor().
int orient = 0
Referenced by addcubeverts(), addmerge(), clearmerge(), collapsedface(), collideface(), disttoent(), disttooutsideent(), faceedges(), genclipplane(), QuadNode::genmatsurf(), genskyfaces(), blobrenderer::gentris(), decalrenderer::gentris(), getmippedtexture(), hoveringonent(), iqm::iqmmeshgroup::loadiqmanims(), md5::md5meshgroup::loadmesh(), mincubeface(), pushsel(), recomputecamera(), remip(), rendereditcursor(), reorient(), setsurface(), and visibleorient().
SharedVar<int> outline
Referenced by gl_drawframe(), and rendereditcursor().
SharedVar<int> outlinecolour
Referenced by renderoutline(), and renderprefab().
bool paintbrush = 0
Referenced by brushvert(), clearbrush(), and hmap::run().
hashnameset<prefab> prefabs static
Referenced by cleanupprefabs(), delprefab(), loadprefab(), and saveprefab().
undolist redos
Referenced by compacteditvslots(), editredo(), editundo(), packundo(), and pruneundos().
vector<vslotmap> remappedvslots static
Referenced by compactmruvslots(), mpeditvslot(), and remapvslot().
selinfo repsel
Referenced by mpedittex(), and mpeditvslot().
int reptex = -1
Referenced by compactmruvslots(), edittexcube(), mpedittex(), mpeditvslot(), remapvslots(), and replace().
selinfo savedsel
selinfo sel
Bot Movement, according to waypoints (saved within the map in an excluded file).
See Also
selinfo
Referenced by canpaintblendmap(), clearblendmapsel(), copy(), countselchild(), delcube(), dropentity(), editface(), editmat(), edittex(), edittex_(), entcopy(), entdrag(), entflip(), entpaste(), entpush(), entrotate(), flip(), hmap::getcube(), getselpos(), getseltex(), gettex(), invertblendmapsel(), makeundo(), mpedittex(), mpeditvslot(), mpremip(), noedit(), game::parsemessages(), paste(), pastehilite(), pasteprefab(), pushsel(), rendereditcursor(), reorient(), replace(), hmap::ripple(), rotate(), hmap::run(), saveprefab(), selextend(), swapundo(), updateselection(), valpha(), vcolor(), vlayer(), voffset(), vreset(), vrotate(), vscale(), vscroll(), and vshaderparam().
int selchildcount = 0
the amount of selected child cubes they will be displayed in the bottom left of you screen in coopedit mode
Referenced by countselchild(), gl_drawhud(), and rendereditcursor().
int selchildmat = -1
Referenced by countselchild(), gl_drawhud(), and rendereditcursor().
vector<ushort> texmru
Referenced by compactmruvslots(), edittex(), edittex_(), emptymap(), filltexlist(), getcurtex(), gettex(), load_world(), mpeditvslot(), rendertexturepanel(), save_world(), and tofronttex().
int texpaneltimer = 0
Referenced by edittex_(), and rendertexturepanel().
int totalundos = 0
Referenced by addundo(), and pruneundos().
undolist undos
Referenced by addundo(), compacteditvslots(), editredo(), editundo(), packundo(), and pruneundos().
vector<vslotmap> unpackingvslots static
Referenced by compacteditvslots(), and unpackvslots().