Inexor: inexor/engine/octa.cpp File Reference
octa.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_sort.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct cfkey
struct pvert
struct pedge
struct poly
struct plink
struct cfpolys
Macros
#define GENCUBEVERT(n, x, y, z) ivec(x, y, z),
#define GENCUBEVERT(n, x, y, z)
#define GENFACEORIENT(o, v0, v1, v2, v3) case o: v0 v1 v2 v3 break;
#define GENFACEVERT(o, n, x, y, z, xv, yv, zv)
#define GENFACEORIENT(o, v0, v1, v2, v3) { v0, v1, v2, v3 },
#define GENFACEVERT(o, n, x, y, z, xv, yv, zv) ivec(x,y,z)
#define GENFACEORIENT(orient, v0, v1, v2, v3)
#define GENFACEVERT(orient, vert, xv, yv, zv, x, y, z) { ivec2 &f = fvecs[i]; x ((xv)<<3); y ((yv)<<3); z ((zv)<<3); i++; }
#define GENFACEVERT(orient, vert, sx, sy, sz, dx, dy, dz)
Functions
cubeext * growcubeext (cubeext *old, int maxverts)
void setcubeext (cube &c, cubeext *ext)
cubeext * newcubeext (cube &c, int maxverts, bool init)
cube * newcubes (uint face, int mat)
int familysize (const cube &c)
void freeocta (cube *c)
void freecubeext (cube &c)
void discardchildren (cube &c, bool fixtex, int depth)
void getcubevector (cube &c, int d, int x, int y, int z, ivec &p)
void setcubevector (cube &c, int d, int x, int y, int z, const ivec &p)
static void getcubevector (cube &c, int i, ivec &p)
static void setcubevector (cube &c, int i, const ivec &p)
void optiface (uchar *p, cube &c)
void printcube ()
COMMAND (printcube,"")
bool isvalidcube (const cube &c)
void validatec (cube *c, int size)
cube & lookupcube (const ivec &to, int tsize, ivec &ro, int &rsize)
int lookupmaterial (const vec &v)
const cube & neighbourcube (const cube &c, int orient, const ivec &co, int size, ivec &ro, int &rsize)
int getmippedtexture (const cube &p, int orient)
void forcemip (cube &c, bool fixtex)
static int midedge (const ivec &a, const ivec &b, int xd, int yd, bool &perfect)
static bool crosscenter (const ivec &a, const ivec &b, int xd, int yd)
bool subdividecube (cube &c, bool fullcheck, bool brighten)
bool crushededge (uchar e, int dc)
int visibleorient (const cube &c, int orient)
VAR (mipvis, 0, 0, 1)
bool remip (cube &c, const ivec &co, int size)
void mpremip (bool local)
void remip_ ()
COMMANDN (remip, remip_,"")
static int edgeval (cube &c, const ivec &p, int dim, int coord)
void genvertp (cube &c, ivec &p1, ivec &p2, ivec &p3, plane &pl, bool solid=false)
static bool threeplaneintersect (plane &pl1, plane &pl2, plane &pl3, vec &dest)
static void genedgespanvert (ivec &p, cube &c, vec &v)
void edgespan2vectorcube (cube &c)
template<class T >
static void gencubevert (const cube &c, int i, T &v)
void genfaceverts (const cube &c, int orient, ivec v[4])
bool flataxisface (const cube &c, int orient)
bool collideface (const cube &c, int orient)
bool touchingface (const cube &c, int orient)
bool notouchingface (const cube &c, int orient)
int faceconvexity (const ivec v[4])
int faceconvexity (const vertinfo *verts, int numverts, int size)
int faceconvexity (const ivec v[4], int &vis)
int faceconvexity (const cube &c, int orient)
int faceorder (const cube &c, int orient)
static void faceedges (const cube &c, int orient, uchar edges[4])
uint faceedges (const cube &c, int orient)
static int genfacevecs (const cube &cu, int orient, const ivec &pos, int size, bool solid, ivec2 *fvecs, const ivec *v=nullptr)
static int clipfacevecy (const ivec2 &o, const ivec2 &dir, int cx, int cy, int size, ivec2 &r)
static int clipfacevecx (const ivec2 &o, const ivec2 &dir, int cx, int cy, int size, ivec2 &r)
static int clipfacevec (const ivec2 &o, const ivec2 &dir, int cx, int cy, int size, ivec2 *rvecs)
static bool insideface (const ivec2 *p, int nump, const ivec2 *o, int numo)
static int clipfacevecs (const ivec2 *o, int numo, int cx, int cy, int size, ivec2 *rvecs)
bool collapsedface (const cube &c, int orient)
static bool occludesface (const cube &c, int orient, const ivec &o, int size, const ivec &vo, int vsize, ushort vmat, ushort nmat, ushort matmask, const ivec2 *vf, int numv)
bool visibleface (const cube &c, int orient, const ivec &co, int size, ushort mat, ushort nmat, ushort matmask)
int classifyface (const cube &c, int orient, const ivec &co, int size)
int visibletris (const cube &c, int orient, const ivec &co, int size, ushort nmat, ushort matmask)
void calcvert (const cube &c, const ivec &co, int size, ivec &v, int i, bool solid)
void calcvert (const cube &c, const ivec &co, int size, vec &v, int i, bool solid)
int genclipplane (const cube &c, int orient, vec *v, plane *clip)
void genclipplanes (const cube &c, const ivec &co, int size, clipplanes &p, bool collide)
static bool mergefacecmp (const facebounds &x, const facebounds &y)
static int mergefacev (int orient, facebounds *m, int sz, facebounds &n)
static int mergefaceu (int orient, facebounds &m, facebounds &n)
static int mergeface (int orient, facebounds *m, int sz, facebounds &n)
int mergefaces (int orient, facebounds *m, int sz)
static bool htcmp (const cfkey &x, const cfkey &y)
static uint hthash (const cfkey &k)
void mincubeface (const cube &cu, int orient, const ivec &o, int size, const facebounds &orig, facebounds &cf, ushort nmat, ushort matmask)
bool mincubeface (const cube &cu, int orient, const ivec &co, int size, facebounds &orig)
VAR (maxmerge, 0, 6, 12)
VAR (minface, 0, 4, 12)
static uint hthash (const pedge &x)
static bool htcmp (const pedge &x, const pedge &y)
bool clippoly (poly &p, const facebounds &b)
bool genpoly (cube &cu, int orient, const ivec &o, int size, int vis, ivec &n, int &offset, poly &p)
bool mergepolys (int orient, hashset< plink > &links, vector< plink * > &queue, int owner, poly &p, poly &q, const pedge &e)
void addmerge (cube &cu, int orient, const ivec &co, const ivec &n, int offset, poly &p)
static void clearmerge (cube &c, int orient)
void addmerges (int orient, const ivec &co, const ivec &n, int offset, vector< poly > &polys)
void mergepolys (int orient, const ivec &co, const ivec &n, int offset, vector< poly > &polys)
void genmerges (cube *c=worldroot, const ivec &o=ivec(0, 0, 0), int size=worldsize >>1)
int calcmergedsize (int orient, const ivec &co, int size, const vertinfo *verts, int numverts)
static void invalidatemerges (cube &c)
void invalidatemerges (cube &c, const ivec &co, int size, bool msg)
void calcmerges ()
Variables
cube * worldroot = newcubes(F_SOLID)
int allocnodes = 0
ivec lu
lookup integer vector
int lusize
lookup size
const cube * neighbourstack [32]
int neighbourdepth = -1
static int remipprogress = 0
static int remiptotal = 0
const ivec cubecoords [8]
const ivec facecoords [6][4]
const uchar fv [6][4]
const uchar fvmasks [64]
const uchar faceedgesidx [6][4]
static int genmergeprogress = 0
static hashtable< cfkey, cfpolys > cpolys
static int invalidatedmerges = 0
Class Documentation
struct cfkey
Class Members
ushort material
ivec n
int offset
uchar orient
ushort tex
struct poly
Class Members
cube * c
bool merged
int numverts
pvert verts[MAXFACEVERTS]
struct cfpolys
Class Members
vector< poly > polys
Macro Definition Documentation
#define GENCUBEVERT (n, x, y, z) ivec(x, y, z),
#define GENCUBEVERT (n, x, y, z)
Value:
case n: \
            v = T(edgeget(cubeedge(c, 0, y, z), x), \
                  edgeget(cubeedge(c, 1, z, x), y), \
                  edgeget(cubeedge(c, 2, x, y), z)); \
            break;
#define GENFACEORIENT (o, v0, v1, v2, v3) case o: v0 v1 v2 v3 break;
#define GENFACEORIENT (o, v0, v1, v2, v3) { v0, v1, v2, v3 },
#define GENFACEORIENT (orient, v0, v1, v2, v3)
Value:
case orient: \
            { \
                if(dimcoord(orient)) { v0 v1 v2 v3 } else { v3 v2 v1 v0 } \
                break; \
            }
#define GENFACEVERT (o, n, x, y, z, xv, yv, zv)
Value:
v[n] = ivec(edgeget(cubeedge(c, 0, y, z), x), \
                        edgeget(cubeedge(c, 1, z, x), y), \
                        edgeget(cubeedge(c, 2, x, y), z));
#define GENFACEVERT (o, n, x, y, z, xv, yv, zv) ivec(x,y,z)
#define GENFACEVERT (orient, vert, xv, yv, zv, x, y, z) { ivec2 &f = fvecs[i]; x ((xv)<<3); y ((yv)<<3); z ((zv)<<3); i++; }
#define GENFACEVERT (orient, vert, sx, sy, sz, dx, dy, dz)
Value:
{ \
            const ivec &e = v[vert]; \
            ivec ef; \
            ef.dx = e.sx; ef.dy = e.sy; ef.dz = e.sz; \
            if(ef.z == dimcoord(orient)*8) \
            { \
                ivec2 &f = fvecs[i]; \
                ivec pf; \
                pf.dx = pos.sx; pf.dy = pos.sy; pf.dz = pos.sz; \
                f = ivec2(ef.x*size + (pf.x<<3), ef.y*size + (pf.y<<3)); \
                if(f != prev) { prev = f; i++; } \
            } \
        }
Function Documentation
void addmerge (cube & cu, int orient, const ivec & co, const ivec & n, int offset, poly & p)
References ambientsurface, brightsurface, C, dimcoord, dimension, cube::ext, vertinfo::getxyz(), loopj, loopk, MAXFACEVERTS, cube::merged, sphere::numverts, surfaceinfo::numverts, poly::numverts, orient, R, vertinfo::set(), setsurface(), cubeext::surfaces, sphere::verts, surfaceinfo::verts, cubeext::verts(), poly::verts, pvert::x, and pvert::y.
Referenced by addmerges(), and genmerges().
void addmerges (int orient, const ivec & co, const ivec & n, int offset, vector< poly > & polys)
References addmerge(), poly::c, clearmerge(), loopv, and poly::merged.
Referenced by mergepolys().
int calcmergedsize (int orient, const ivec & co, int size, const vertinfo * verts, int numverts)
References ivec::mask(), inexor::rpc::max(), inexor::rpc::min(), sphere::numverts, ivec::shl(), vertinfo::x, vertinfo::y, and vertinfo::z.
Referenced by genmergedfaces(), and setupsurfaces().
void calcmerges ()
References genmergeprogress, and genmerges().
Referenced by mpremip().
void calcvert (const cube & c, const ivec & co, int size, ivec & v, int i, bool solid)
References ivec::add(), ivec::div(), gencubevert(), and ivec::mul().
Referenced by genclipplanes(), and isvalidcube().
void calcvert (const cube & c, const ivec & co, int size, vec & v, int i, bool solid)
References vec::add(), f(), gencubevert(), and vec::mul().
int classifyface (const cube & c, int orient, const ivec & co, int size)
References cube::children, collapsedface(), F_SOLID, faceedges(), genfacevecs(), insideface(), isempty, isentirelysolid, ivec::mask(), MAT_AIR, MAT_ALPHA, MAT_NOCLIP, cube::material, MATF_CLIP, neighbourcube(), notouchingface(), occludesface(), opposite, and touchingface().
Referenced by setcubevisibility().
static void clearmerge (cube & c, int orient) inline static
References brightsurface, cube::ext, cube::merged, orient, and cubeext::surfaces.
Referenced by addmerges(), and genmerges().
static int clipfacevec (const ivec2 & o, const ivec2 & dir, int cx, int cy, int size, ivec2 * rvecs) inline static
References ASSERT, clipfacevecx(), and clipfacevecy().
Referenced by clipfacevecs().
static int clipfacevecs (const ivec2 * o, int numo, int cx, int cy, int size, ivec2 * rvecs) inline static
References ASSERT, clipfacevec(), cur, insideface(), and loopi().
Referenced by occludesface().
static int clipfacevecx (const ivec2 & o, const ivec2 & dir, int cx, int cy, int size, ivec2 & r) inline static
References anonymous_namespace{utilTest.cpp}::t().
Referenced by clipfacevec().
static int clipfacevecy (const ivec2 & o, const ivec2 & dir, int cx, int cy, int size, ivec2 & r) inline static
References anonymous_namespace{utilTest.cpp}::t().
Referenced by clipfacevec().
bool clippoly (poly & p, const facebounds & b)
References loopi(), MAXFACEVERTS, poly::numverts, facebounds::u1, facebounds::u2, facebounds::v1, facebounds::v2, poly::verts, pvert::x, and pvert::y.
Referenced by genpoly().
bool collapsedface (const cube & c, int orient)
References ivec::cross(), dimcoord, dimension, faceedgesidx, orient, and ivec::sub().
Referenced by classifyface(), and visibleface().
bool collideface (const cube & c, int orient)
References faceedgesidx, flataxisface(), and orient.
Referenced by setcubevisibility().
COMMAND (printcube , "")
COMMANDN (remip , remip_ , "")
static bool crosscenter (const ivec & a, const ivec & b, int xd, int yd) inline static
Referenced by subdividecube().
bool crushededge (uchar e, int dc)
Referenced by visibleorient().
void discardchildren (cube & c, bool fixtex, int depth)
References allocnodes, cube::children, DELETEA, destroyva(), discardchildren(), cube::ext, F_EMPTY, F_SOLID, freecubeext(), freeoctaentities(), getmippedtexture(), loopi(), MAT_AIR, cube::material, cube::merged, cube::texture, cubeext::tjoints, and cubeext::va.
Referenced by discardchildren(), freeblock(), freeocta(), hmap::getcube(), mpdelcube(), mpeditface(), pastecube(), readychanges(), remip(), and validatec().
void edgespan2vectorcube (cube & c)
References cubeedge, edgeset, genedgespanvert(), isempty, isentirelysolid, and loop.
Referenced by loadc().
static int edgeval (cube & c, const ivec & p, int dim, int coord) inline static
References C, cubeedge, edgeget, and R.
Referenced by genvertp().
int faceconvexity (const ivec v[4])
References ivec::cross(), ivec::dot(), and ivec::sub().
Referenced by addnormals(), faceconvexity(), faceorder(), genclipplane(), genclipplanes(), gencubeedges(), gencubeverts(), genpoly(), genprefabmesh(), blobrenderer::gentris(), decalrenderer::gentris(), previewblends(), savec(), and setupsurfaces().
int faceconvexity (const vertinfo * verts, int numverts, int size)
References ivec::cross(), ivec::dot(), vertinfo::getxyz(), ivec::shr(), and ivec::sub().
int faceconvexity (const ivec v[4], int & vis)
References ivec::cross(), ivec::dot(), and ivec::iszero().
int faceconvexity (const cube & c, int orient)
References faceconvexity(), flataxisface(), and genfaceverts().
static void faceedges (const cube & c, int orient, uchar edges[4]) inline static
References faceedgesidx, loopk, and orient.
Referenced by classifyface(), faceedges(), genpoly(), occludesface(), skyoccluded(), visibleface(), and visibletris().
uint faceedges (const cube & c, int orient)
References faceedges().
int faceorder (const cube & c, int orient)
References faceconvexity().
int familysize (const cube & c)
References cube::children, familysize(), and loopi().
Referenced by familysize(), and undosize().
bool flataxisface (const cube & c, int orient)
References dimcoord, and dimension.
Referenced by addnormals(), collideface(), faceconvexity(), genclipplanes(), gencubeedges(), gencubeverts(), genpoly(), genprefabmesh(), blobrenderer::gentris(), decalrenderer::gentris(), previewblends(), and setupsurfaces().
void forcemip (cube & c, bool fixtex)
References cube::children, emptyfaces, getcubevector(), getmippedtexture(), isempty, loopi(), loopj, setcubevector(), and cube::texture.
Referenced by hmap::getcube(), and remip().
void freecubeext (cube & c)
References cube::ext.
Referenced by discardchildren().
void freeocta (cube * c)
References allocnodes, discardchildren(), and loopi().
Referenced by cleanup(), emptymap(), genprefabmesh(), load_world(), remip(), and shrinkmap().
int genclipplane (const cube & c, int orient, vec * v, plane * clip)
References faceconvexity(), fv, orient, and plane::toplane().
void genclipplanes (const cube & c, const ivec & co, int size, clipplanes & p, bool collide)
References vec::add(), calcvert(), f(), faceconvexity(), flataxisface(), fv, loopi(), MAT_NOCLIP, MATF_CLIP, vec::max(), vec::min(), vec::mul(), hmap::mx, clipplanes::o, clipplanes::p, clipplanes::r, clipplanes::side, clipplanes::size, vec::sub(), plane::toplane(), clipplanes::v, clipplanes::visible, and visibletris().
Referenced by getclipplanes(), isvalidcube(), and shadowray().
template<class T > static void gencubevert (const cube & c, int i, T & v) inline static
References GENCUBEVERTS.
Referenced by calcvert().
static void genedgespanvert (ivec & p, cube & c, vec & v) static
References ASSERT, f(), genvertp(), inexor::rpc::max(), inexor::rpc::min(), and threeplaneintersect().
Referenced by edgespan2vectorcube().
static int genfacevecs (const cube & cu, int orient, const ivec & pos, int size, bool solid, ivec2 * fvecs, const ivec * v = nullptr) inline static
References f(), GENFACEVERTS, and genfaceverts().
Referenced by classifyface(), occludesface(), visibleface(), and visibletris().
void genfaceverts (const cube & c, int orient, ivec v[4])
References GENFACEVERTS.
Referenced by addnormals(), convertoldsurfaces(), faceconvexity(), gencubeedges(), gencubeverts(), genfacevecs(), genpoly(), genprefabmesh(), blobrenderer::gentris(), decalrenderer::gentris(), loadc(), previewblends(), setupsurfaces(), and visibletris().
void genmerges (cube * c = worldroot, const ivec & o = ivec(0, 0, 0), int size = worldsize>>1)
References addmerge(), allocnodes, hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::clear(), clearmerge(), enumeratekt, genmergeprogress, genpoly(), isempty, loopi(), loopj, MAT_ALPHA, cfkey::material, poly::merged, mergepolys(), cfkey::n, neighbourdepth, hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::numelems, cfkey::offset, cfkey::orient, renderprogress(), cfkey::tex, touchingface(), and visibletris().
Referenced by calcmerges().
bool genpoly (cube & cu, int orient, const ivec & o, int size, int vis, ivec & n, int & offset, poly & p)
References ivec::add(), C, poly::c, clippoly(), ivec::cross(), dimcoord, dimension, dir, ivec::dot(), F_SOLID, faceconvexity(), faceedges(), flataxisface(), genfaceverts(), ivec::iszero(), loopk, ivec::mask(), inexor::rpc::max(), poly::merged, inexor::rpc::min(), mincubeface(), ivec::mul(), poly::numverts, R, reduceslope(), ivec::shl(), touchingface(), facebounds::u1, facebounds::u2, facebounds::v1, facebounds::v2, poly::verts, pvert::x, and pvert::y.
Referenced by genmerges().
void genvertp (cube & c, ivec & p1, ivec & p2, ivec & p3, plane & pl, bool solid = false)
References edgeval(), and plane::toplane().
Referenced by genedgespanvert().
void getcubevector (cube & c, int d, int x, int y, int z, ivec & p)
References C, cubeedge, D, edgeget, loopi(), and R.
Referenced by forcemip(), linkedpush(), hmap::pushside(), and subdividecube().
static void getcubevector (cube & c, int i, ivec & p) inline static
References C, cubeedge, D, edgeget, and R.
int getmippedtexture (const cube & p, int orient)
References cube::children, hmap::d, hmap::dc, DEFAULT_GEOM, DEFAULT_SKY, dimcoord, dimension, isempty, loop, loopi(), loopirev, octaindex, oppositeocta, orient, and cube::texture.
Referenced by discardchildren(), forcemip(), and remip().
cubeext* growcubeext (cubeext * old, int maxverts)
References cubeext::ents, ext(), cubeext::maxverts, cubeext::tjoints, and cubeext::va.
Referenced by newcubeext(), setsurface(), and setupsurfaces().
static bool htcmp (const cfkey & x, const cfkey & y) inline static
References cfkey::material, cfkey::n, cfkey::offset, cfkey::orient, and cfkey::tex.
static bool htcmp (const pedge & x, const pedge & y) inline static
static uint hthash (const cfkey & k) inline static
References cfkey::material, cfkey::n, cfkey::offset, cfkey::orient, and cfkey::tex.
static uint hthash (const pedge & x) inline static
References pedge::from, pvert::x, and pvert::y.
static bool insideface (const ivec2 * p, int nump, const ivec2 * o, int numo) inline static
References cur, dir, loopi(), and loopj.
Referenced by classifyface(), clipfacevecs(), occludesface(), visibleface(), and visibletris().
static void invalidatemerges (cube & c) static
References brightencube(), cube::children, destroyva(), cube::ext, vtxarray::hasmerges, loopi(), MERGE_ORIGIN, MERGE_PART, cube::merged, cubeext::tjoints, and cubeext::va.
Referenced by invalidatemerges(), previewblends(), and readychanges().
void invalidatemerges (cube & c, const ivec & co, int size, bool msg)
References invalidatemerges(), renderprogress(), and totalmillis.
bool isvalidcube (const cube & c)
References calcvert(), genclipplanes(), loopi(), and pointincube().
Referenced by mpeditface(), and subdividecube().
cube& lookupcube (const ivec & to, int tsize, ivec & ro, int & rsize)
References cube::children, ivec::mask(), octastep, subdividecube(), worldscale, and worldsize.
Referenced by blockcube(), findsurface(), hmap::getcube(), getseltex(), printcube(), rendereditcursor(), and setupmaterials().
int lookupmaterial (const vec & v)
References cube::children, insideworld(), MAT_AIR, cube::material, octastep, and worldscale.
Referenced by bounce(), game::collectclientmode::checkitems(), game::ctfclientmode::checkitems(), ai::clipped(), drawcubemap(), ai::getweight(), gl_drawframe(), ragdolldata::move(), moveplayer(), ai::navigate(), game::captureclientmode::rendertether(), and game::sendposition().
static int mergeface (int orient, facebounds * m, int sz, facebounds & n) static
References mergefaceu(), and mergefacev().
Referenced by mergefaces().
static bool mergefacecmp (const facebounds & x, const facebounds & y) inline static
References facebounds::u1, and facebounds::v2.
Referenced by mergefaces().
int mergefaces (int orient, facebounds * m, int sz)
References loopi(), mergeface(), mergefacecmp(), and quicksort().
Referenced by addskyverts().
static int mergefaceu (int orient, facebounds & m, facebounds & n) static
References facebounds::u1, facebounds::u2, facebounds::v1, and facebounds::v2.
Referenced by mergeface().
static int mergefacev (int orient, facebounds * m, int sz, facebounds & n) static
References facebounds::u1, facebounds::u2, and facebounds::v1.
Referenced by mergeface().
bool mergepolys (int orient, hashset< plink > & links, vector< plink * > & queue, int owner, poly & p, poly & q, const pedge & e)
References hashbase< hashset< T >, T, T, T >::access(), vector< T, MINSIZE >::add(), dir, pedge::from, loopi(), loopj, MAXFACEVERTS, poly::merged, sphere::numverts, poly::numverts, plink::polys, pedge::to, sphere::verts, poly::verts, pvert::x, and pvert::y.
Referenced by genmerges(), and mergepolys().
void mergepolys (int orient, const ivec & co, const ivec & n, int offset, vector< poly > & polys)
References hashset< T >::add(), addmerges(), pedge::from, vector< T, MINSIZE >::length(), loopj, loopv, mergepolys(), poly::numverts, plink::polys, pedge::to, poly::verts, pvert::x, and pvert::y.
static int midedge (const ivec & a, const ivec & b, int xd, int yd, bool & perfect) static
References inexor::rpc::max(), and inexor::rpc::min().
Referenced by subdividecube().
void mincubeface (const cube & cu, int orient, const ivec & o, int size, const facebounds & orig, facebounds & cf, ushort nmat, ushort matmask)
References C, cube::children, dimcoord, dimension, faceedgesidx, isempty, loopi(), MAT_AIR, cube::material, inexor::rpc::max(), inexor::rpc::min(), mincubeface(), octacoord, orient, R, touchingface(), facebounds::u1, facebounds::u2, facebounds::v1, and facebounds::v2.
Referenced by genpoly(), mincubeface(), and minskyface().
bool mincubeface (const cube & cu, int orient, const ivec & co, int size, facebounds & orig)
References MAT_AIR, MAT_ALPHA, cube::material, mincubeface(), neighbourcube(), opposite, facebounds::u1, facebounds::u2, facebounds::v1, and facebounds::v2.
void mpremip (bool local)
References allchanged(), allocnodes, calcmerges(), EDIT_REMIP, game::edittrigger(), loopi(), remip(), remipprogress, remiptotal, sel, and worldsize.
Referenced by calclight(), game::parsemessages(), and remip_().
const cube& neighbourcube (const cube & c, int orient, const ivec & co, int size, ivec & ro, int & rsize)
References cube::children, dimcoord, dimension, ivec::mask(), neighbourdepth, octastep, worldroot, worldscale, and worldsize.
Referenced by classifyface(), mincubeface(), visibleface(), and visibletris().
cubeext* newcubeext (cube & c, int maxverts, bool init)
References ext(), cube::ext, growcubeext(), cubeext::maxverts, setcubeext(), cubeext::surfaces, and cubeext::verts().
Referenced by brightencube(), ext(), loadc(), setsurface(), and setsurfaces().
cube* newcubes (uint face, int mat)
References allocnodes, cube::children, DEFAULT_GEOM, cube::ext, loopi(), loopl, cube::material, cube::merged, setfaces, and cube::texture.
Referenced by copycube(), emptymap(), enlargemap(), genprefabmesh(), loadchildren(), splitocta(), subdividecube(), and unpackcube().
bool notouchingface (const cube & c, int orient)
References dimcoord, and dimension.
Referenced by classifyface(), occludesface(), visibleface(), and visibletris().
static bool occludesface (const cube & c, int orient, const ivec & o, int size, const ivec & vo, int vsize, ushort vmat, ushort nmat, ushort matmask, const ivec2 * vf, int numv) inline static
References C, cube::children, clipfacevecs(), dimcoord, dimension, F_SOLID, faceedges(), genfacevecs(), insideface(), isclipped, isempty, isentirelysolid, isliquid, loopi(), MAT_AIR, cube::material, MATF_VOLUME, notouchingface(), octacoord, R, and touchingface().
Referenced by classifyface(), visibleface(), and visibletris().
void optiface (uchar * p, cube & c)
References emptyfaces, and f().
Referenced by mpeditface().
void printcube ()
References Log, lookupcube(), lu, lusize, and inexor::util::log_manager::std.
bool remip (cube & c, const ivec & co, int size)
References brightencube(), cube::children, dimcoord, dimension, discardchildren(), cube::ext, forcemip(), freeocta(), getmippedtexture(), isempty, isentirelysolid, loop, loopi(), loopj, MAT_AIR, MAT_ALPHA, MAT_NOCLIP, cube::material, MATF_CLIP, octaindex, orient, remipprogress, remiptotal, renderprogress(), solidfaces, subdividecube(), cube::texture, and visibleface().
Referenced by mpremip().
void remip_ ()
References allchanged(), and mpremip().
void setcubeext (cube & c, cubeext * ext)
References ext(), and cube::ext.
Referenced by cleanupthreads(), newcubeext(), and setsurface().
void setcubevector (cube & c, int d, int x, int y, int z, const ivec & p)
References C, cubeedge, D, edgeset, loopi(), and R.
Referenced by forcemip(), and hmap::pushside().
static void setcubevector (cube & c, int i, const ivec & p) inline static
References C, cubeedge, D, edgeset, and R.
bool subdividecube (cube & c, bool fullcheck, bool brighten)
References brightencube(), C, cube::children, crosscenter(), cubeedge, D, hmap::d, dimcoord, dimension, edgeset, emptyfaces, cube::ext, F_EMPTY, F_SOLID, getcubevector(), isempty, isentirelysolid, isvalidcube(), loopi(), loopj, loopl, cube::material, midedge(), ivec::mul(), newcubes(), octaindex, R, cubeext::surfaces, cube::texture, and validatec().
Referenced by lookupcube(), remip(), shrinkmap(), and validatec().
static bool threeplaneintersect (plane & pl1, plane & pl2, plane & pl3, vec & dest) static
References vec::add(), vec::cross(), hmap::d, vec::div(), vec::mul(), and plane::offset.
Referenced by genedgespanvert().
bool touchingface (const cube & c, int orient)
References dimcoord, and dimension.
Referenced by classifyface(), genmerges(), genpoly(), mincubeface(), occludesface(), skyoccluded(), visibleface(), visibleorient(), and visibletris().
void validatec (cube * c, int size)
References discardchildren(), emptyfaces, f(), loopi(), loopj, solidfaces, subdividecube(), and validatec().
Referenced by load_world(), subdividecube(), and validatec().
VAR (mipvis , 0 , 0 , 1)
VAR (maxmerge , 0 , 6 , 12)
VAR (minface , 0 , 4 , 12)
bool visibleface (const cube & c, int orient, const ivec & co, int size, ushort mat, ushort nmat, ushort matmask)
References cube::children, collapsedface(), F_SOLID, faceedges(), genfacevecs(), insideface(), isempty, isentirelysolid, isliquid, ivec::mask(), MAT_AIR, MAT_GLASS, cube::material, MATF_VOLUME, neighbourcube(), notouchingface(), occludesface(), opposite, and touchingface().
Referenced by blobrenderer::gentris(), decalrenderer::gentris(), remip(), and visiblematerial().
int visibleorient (const cube & c, int orient)
References crushededge(), faceedgesidx, loopi(), loopj, orient, and touchingface().
Referenced by edittexcube(), and remapvslots().
int visibletris (const cube & c, int orient, const ivec & co, int size, ushort nmat, ushort matmask)
References cube::children, ivec::cross(), dimcoord, dimension, ivec::dot(), F_SOLID, faceedges(), genfacevecs(), genfaceverts(), insideface(), isempty, isentirelysolid, ivec::iszero(), loopi(), ivec::mask(), MAT_AIR, cube::material, neighbourcube(), notouchingface(), occludesface(), opposite, touchingface(), and sphere::verts.
Referenced by addnormals(), fixinsidefaces(), fixrotatedlightmaps(), genclipplanes(), gencubeedges(), gencubeverts(), generatelightmaps(), genmerges(), genprefabmesh(), previewblends(), and savec().
Variable Documentation
int allocnodes = 0
Referenced by compactvslots(), discardchildren(), freeocta(), genmerges(), gl_drawhud(), mpremip(), newcubes(), savec(), show_addnormals_progress(), show_calclight_progress(), and updateva().
hashtable<cfkey, cfpolys> cpolys static
const ivec cubecoords[8]
Initial value:
=
{
#define GENCUBEVERT(n, x, y, z)
}
const ivec facecoords[6][4]
Initial value:
=
{
#define GENFACEORIENT(o, v0, v1, v2, v3)
#define GENFACEVERT(o, n, x,y,z, xv,yv,zv)
}
Referenced by addskyverts(), and convertoldsurfaces().
const uchar faceedgesidx[6][4]
Initial value:
=
{
    { 4,  5,  8, 10 },
    { 6,  7,  9, 11 },
    { 8,  9,  0, 2 },
    { 10, 11, 1, 3 },
    { 0,  1,  4, 6 },
    { 2,  3,  5, 7 },
}
Referenced by collapsedface(), collideface(), faceedges(), mincubeface(), and visibleorient().
const uchar fv[6][4]
Initial value:
=
{
    { 2, 1, 6, 5 },
    { 3, 4, 7, 0 },
    { 4, 5, 6, 7 },
    { 1, 2, 3, 0 },
    { 6, 1, 0, 7 },
    { 5, 4, 3, 2 },
}
Referenced by clampcollide(), genclipplane(), genclipplanes(), and iqm::iqmmeshgroup::loadiqmmeshes().
const uchar fvmasks[64]
Initial value:
=
{
    0x00, 0x66, 0x99, 0xFF, 0xF0, 0xF6, 0xF9, 0xFF,
    0x0F, 0x6F, 0x9F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xC3, 0xE7, 0xDB, 0xFF, 0xF3, 0xF7, 0xFB, 0xFF,
    0xCF, 0xEF, 0xDF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x3C, 0x7E, 0xBD, 0xFF, 0xFC, 0xFE, 0xFD, 0xFF,
    0x3F, 0x7F, 0xBF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
}
int genmergeprogress = 0 static
Referenced by calcmerges(), and genmerges().
int invalidatedmerges = 0 static
ivec lu
lookup integer vector
Referenced by normalizelookupcube(), printcube(), and rendereditcursor().
int lusize
lookup size
Referenced by normalizelookupcube(), printcube(), rendereditcursor(), and selgridmap().
int neighbourdepth = -1
Referenced by gencubeedges(), genmerges(), genprefabmesh(), neighbourcube(), rendercube(), and updateva().
const cube* neighbourstack[32]
Referenced by gencubeedges(), genprefabmesh(), rendercube(), and updateva().
int remipprogress = 0 static
Referenced by mpremip(), and remip().
int remiptotal = 0 static
Referenced by mpremip(), and remip().
cube* worldroot = newcubes(F_SOLID)
Referenced by blobrenderer::addblob(), decalrenderer::adddecal(), allchanged(), bboccluded(), calclight(), calcnormals(), changed(), cleanup(), cleanupva(), clearlightmaps(), compactvslots(), emptymap(), enlargemap(), findents(), fixlightmapnormals(), fixrotatedlightmaps(), genprefabmesh(), genpvs(), getclipplanes(), load_world(), modifyoctaent(), mpreplacetex(), neighbourcube(), octacollide(), octarender(), patchlight(), previewblends(), rendereditcursor(), save_world(), shadowray(), shrinkmap(), and testpvs().