Inexor: inexor/engine/octarender.hpp File Reference
octarender.hpp File Reference
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
Functions
ushort encodenormal (const vec &n)
void guessnormals (const vec *pos, int numverts, vec *normals)
void reduceslope (ivec &n)
void findtjoints ()
void octarender ()
void allchanged (bool load=false)
void clearvas (cube *c)
void destroyva (vtxarray *va, bool reparent=true)
bool readva (vtxarray *va, ushort *&edata, vertex *&vdata)
void updatevabb (vtxarray *va, bool force=false)
void updatevabbs (bool force=false)
Variables
vector< tjoint > tjoints
vector< vtxarray * > varoot
vector< vtxarray * > valist
Function Documentation
void allchanged (bool load = false)
References clearvas(), drawtextures(), entitiesinoctanodes(), findtjoints(), guessshadowdir(), initenvmaps(), invalidatepostfx(), lightents(), octarender(), precachetextures(), renderprogress(), resetblobs(), resetclipplanes(), resetqueries(), seedparticles(), vector< T, MINSIZE >::setsize(), setupmaterials(), updatevabbs(), and worldroot.
Referenced by calclight(), clearlightmaps(), editvslot(), emptymap(), enlargemap(), load_world(), mpremip(), mpreplacetex(), patchlight(), recalc(), remip_(), resetgl(), save_world(), and shrinkmap().
void clearvas (cube * c)
References clearvas(), destroyva(), ext(), cube::ext, loopi(), cubeext::tjoints, and cubeext::va.
Referenced by allchanged(), cleanupva(), and clearvas().
void destroyva (vtxarray * va, bool reparent = true)
References vector< T, MINSIZE >::add(), vtxarray::alphabacktris, vtxarray::alphafronttris, vtxarray::blends, vtxarray::children, destroyvbo(), vtxarray::ebuf, vtxarray::eslist, loopv, vtxarray::matbuf, vtxarray::parent, vector< T, MINSIZE >::removeobj(), vtxarray::skybuf, vtxarray::tris, vtxarray::vbuf, vtxarray::verts, and wverts.
Referenced by clearvas(), discardchildren(), invalidatemerges(), previewblends(), and readychanges().
ushort encodenormal (const vec & n)
References vec::iszero(), and RAD.
Referenced by convertoldsurfaces(), and setupsurfaces().
void findtjoints ()
References edgegroups, enumeratekt, findtjoints(), gencubeedges(), and vector< T, MINSIZE >::setsize().
void guessnormals (const vec * pos, int numverts, vec * normals)
References vec::add(), vec::cross(), vec::iszero(), loopk, and vec::normalize().
Referenced by genprefabmesh().
void octarender ()
References vtxarray::explicitsky, explicitsky, flushvbo(), loadprogress, loopv, vector< T, MINSIZE >::setsize(), vtxarray::skyarea, skyarea, updateva(), visibleva, worldroot, and worldsize.
Referenced by allchanged(), and commitchanges().
bool readva (vtxarray * va, ushort *& edata, vertex *& vdata)
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), vtxarray::ebuf, vtxarray::edata, glGetBufferSubData_, vtxarray::tris, vtxarray::vbuf, vtxarray::verts, and vtxarray::voffset.
Referenced by writeobj().
void reduceslope (ivec & n)
References C, ivec::div(), loopi(), R, and ivec::shr().
Referenced by addnormals(), addtris(), gencubeedges(), and genpoly().
void updatevabb (vtxarray * va, bool force = false)
References ivec::add(), octaentities::bbmax, vtxarray::bbmax, octaentities::bbmin, vtxarray::bbmin, C, vtxarray::children, vtxarray::geommax, vtxarray::geommin, loop, loopv, vtxarray::mapmodels, vtxarray::matmax, vtxarray::matmin, ivec::max(), ivec::min(), vtxarray::o, R, vtxarray::size, vtxarray::sky, vtxarray::skyfaces, and updatevabb().
Referenced by modifyoctaentity(), updatevabb(), and updatevabbs().
void updatevabbs (bool force = false)
References loopv, and updatevabb().
Referenced by allchanged(), and commitchanges().
Variable Documentation
vector<tjoint> tjoints
Referenced by addnormals().
vector<vtxarray *> valist
Referenced by calcpvsbounds(), commitchanges(), drawminimap(), findwaterplanes(), setupmaterials(), visiblecubes(), and writeobj().
vector<vtxarray *> varoot
Referenced by renderreflectedgeom(), rendersky(), and visiblecubes().