Inexor: inexor/physics/physics.cpp File Reference
physics.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/fpsgame/fps.hpp"
#include "inexor/fpsgame/player.hpp"
#include "inexor/fpsgame/weapon.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/model/model.hpp"
#include "inexor/model/rendermodel.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/bih.hpp"
#include "inexor/physics/mpr.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/util/legacy_time.hpp"
Classes
struct ShadowRayCache
struct dynentcacheentry
struct platforment
struct platformcollision
Macros
#define INTERSECTPLANES(setentry, exit)
#define INTERSECTBOX(setentry, exit)
#define entintersect(mask, type, func)
#define INITRAYCUBE
#define CHECKINSIDEWORLD
#define DOWNOCTREE(disttoent, earlyexit)
#define FINDCLOSEST(xclosest, yclosest, zclosest)
#define UPOCTREE(exitworld)
#define DYNENTCACHESIZE 1024
#define DYNENTHASH(x, y) (((((x)^(y))<<5) + (((x)^(y))>>5)) & (DYNENTCACHESIZE - 1))
#define loopdynentcache(curx, cury, o, radius)
#define CHECKSIDE(side, distval, dotval, margin, normal)
#define PHYSFRAMETIME 5
#define dir(name, v, d, s, os) ICOMMAND(name, "D", (int *down), { player->s = *down!=0; player->v = player->s ? d : (player->os ? -(d) : 0); });
Functions
static clipplanes & getclipplanes (const cube &c, const ivec &o, int size, bool collide=true, int offset=0)
void resetclipplanes ()
static bool pointinbox (const vec &v, const vec &bo, const vec &br)
bool pointincube (const clipplanes &p, const vec &v)
static bool raycubeintersect (const clipplanes &p, const cube &c, const vec &v, const vec &ray, const vec &invray, float &dist)
void entselectionbox (const entity &e, vec &eo, vec &es)
static float disttoent (octaentities *oc, const vec &o, const vec &ray, float radius, int mode, extentity *t)
static float disttooutsideent (const vec &o, const vec &ray, float radius, int mode, extentity *t)
static float shadowent (octaentities *oc, const vec &o, const vec &ray, float radius, int mode, extentity *t)
float raycube (const vec &o, const vec &ray, float radius, int mode, int size, extentity *t)
float shadowray (const vec &o, const vec &ray, float radius, int mode, extentity *t)
ShadowRayCache * newshadowraycache ()
void freeshadowraycache (ShadowRayCache *&cache)
void resetshadowraycache (ShadowRayCache *cache)
float shadowray (ShadowRayCache *cache, const vec &o, const vec &ray, float radius, int mode, extentity *t)
float rayent (const vec &o, const vec &ray, float radius, int mode, int size, int &orient, int &ent)
float raycubepos (const vec &o, const vec &ray, vec &hitpos, float radius, int mode, int size)
bool raycubelos (const vec &o, const vec &dest, vec &hitpos)
float rayfloor (const vec &o, vec &floor, int mode, float radius)
bool ellipseboxcollide (physent *d, const vec &dir, const vec &o, const vec &center, float yaw, float xr, float yr, float hi, float lo)
bool ellipsecollide (physent *d, const vec &dir, const vec &o, const vec &center, float yaw, float xr, float yr, float hi, float lo)
void cleardynentcache ()
VARF (dynentsize, 4, 7, 12, cleardynentcache())
const vector< physent * > & checkdynentcache (int x, int y)
void updatedynentcache (physent *d)
bool overlapsdynent (const vec &o, float radius)
template<class E , class O >
static bool plcollide (physent *d, const vec &dir, physent *o)
bool plcollide (physent *d, const vec &dir)
void rotatebb (vec &center, vec &radius, int yaw)
template<class E , class M >
static bool mmcollide (physent *d, const vec &dir, const extentity &e, const vec &center, const vec &radius, float yaw)
bool mmcollide (physent *d, const vec &dir, octaentities &oc)
template<class E >
static bool fuzzycollidesolid (physent *d, const vec &dir, float cutoff, const cube &c, const ivec &co, int size)
template<class E >
static bool clampcollide (const clipplanes &p, const E &entvol, const plane &w, const vec &pw)
template<class E >
static bool fuzzycollideplanes (physent *d, const vec &dir, float cutoff, const cube &c, const ivec &co, int size)
template<class E >
static bool cubecollidesolid (physent *d, const vec &dir, float cutoff, const cube &c, const ivec &co, int size)
template<class E >
static bool cubecollideplanes (physent *d, const vec &dir, float cutoff, const cube &c, const ivec &co, int size)
static bool cubecollide (physent *d, const vec &dir, float cutoff, const cube &c, const ivec &co, int size, bool solid)
static bool octacollide (physent *d, const vec &dir, float cutoff, const ivec &bo, const ivec &bs, const cube *c, const ivec &cor, int size)
static bool octacollide (physent *d, const vec &dir, float cutoff, const ivec &bo, const ivec &bs)
bool collide (physent *d, const vec &dir, float cutoff, bool playercol)
void recalcdir (physent *d, const vec &oldvel, vec &dir)
void slideagainst (physent *d, vec &dir, const vec &obstacle, bool foundfloor, bool slidecollide)
void switchfloor (physent *d, vec &dir, const vec &floor)
bool trystepup (physent *d, vec &dir, const vec &obstacle, float maxstep, const vec &floor)
bool trystepdown (physent *d, vec &dir, float step, float xy, float z, bool init=false)
bool trystepdown (physent *d, vec &dir, bool init=false)
void falling (physent *d, vec &dir, const vec &floor)
void landing (physent *d, vec &dir, const vec &floor, bool collided)
bool findfloor (physent *d, bool collided, const vec &obstacle, bool &slide, vec &floor)
bool move (physent *d, vec &dir)
bool bounce (physent *d, float secs, float elasticity, float waterfric, float grav)
void avoidcollision (physent *d, const vec &dir, physent *obstacle, float space)
bool movecamera (physent *pl, const vec &dir, float dist, float stepdist)
bool droptofloor (vec &o, float radius, float height)
float dropheight (entity &e)
void dropenttofloor (entity *e)
void phystest ()
COMMAND (phystest,"")
void vecfromyawpitch (float yaw, float pitch, int move, int strafe, vec &m)
void vectoyawpitch (const vec &v, float &yaw, float &pitch)
VARP (maxroll, 0, 0, 20)
FVAR (straferoll, 0, 0.033f, 90)
FVAR (faderoll, 0, 0.95f, 1)
VAR (floatspeed, 1, 100, 10000)
void modifyvelocity (physent *pl, bool local, bool water, bool floating, int curtime)
void modifygravity (physent *pl, bool water, int curtime)
bool moveplayer (physent *pl, int moveres, bool local, int curtime)
void physicsframe ()
VAR (physinterp, 0, 1, 1)
void interppos (physent *pl)
void moveplayer (physent *pl, int moveres, bool local)
bool bounce (physent *d, float elasticity, float waterfric, float grav)
void updatephysstate (physent *d)
template<class E , class O >
static bool platformcollide (physent *d, const vec &dir, physent *o, float margin)
bool platformcollide (physent *d, physent *o, const vec &dir, float margin=0)
bool moveplatform (physent *p, const vec &dir)
ICOMMAND (attack,"D",(int *down),{game::doattack(*down!=0);})
ICOMMAND (jump,"D",(int *down),{if(!*down||game::canjump()) player->jumping=*down!=0;})
dir (backward, move,-1, k_down, k_up)
dir (forward, move, 1, k_up, k_down)
dir (left, strafe, 1, k_left, k_right)
dir (right, strafe,-1, k_right, k_left)
bool entinmap (dynent *d, bool avoidplayers)
Variables
const int MAXCLIPPLANES = 1024
static clipplanes clipcache [MAXCLIPPLANES]
static int clipcacheversion = -2
vec hitsurface
float hitentdist
int hitent
int hitorient
bool collideinside
physent * collideplayer
vec collidewall
const float STAIRHEIGHT = 4.1f
const float FLOORZ = 0.867f
const float SLOPEZ = 0.5f
const float WALLZ = 0.2f
const float JUMPVEL = 125.0f
const float GRAVITY = 200.0f
static uint dynentframe = 0
static struct dynentcacheentry dynentcache [DYNENTCACHESIZE]
int physsteps = 0
int physframetime = PHYSFRAMETIME
int lastphysframe = 0
const float PLATFORMMARGIN = 0.2f
const float PLATFORMBORDER = 10.0f
Class Documentation
struct dynentcacheentry
Class Members
vector< physent * > dynents
uint frame
int x
int y
Macro Definition Documentation
#define CHECKINSIDEWORLD
Value:
if(!insideworld(o)) \
    { \
        float disttoworld = 0, exitworld = 1e16f; \
        loopi(3) \
        { \
            float c = v[i]; \
            if(c<0 || c>=worldsize) \
            { \
                float d = ((invray[i]>0?0:worldsize)-c)*invray[i]; \
                if(d<0) return (radius>0?radius:-1); \
                disttoworld = max(disttoworld, 0.1f + d); \
            } \
            float e = ((invray[i]>0?worldsize:0)-c)*invray[i]; \
            exitworld = min(exitworld, e); \
        } \
        if(disttoworld > exitworld) return (radius>0?radius:-1); \
        v.add(vec(ray).mul(disttoworld)); \
        dist += disttoworld; \
    }
Referenced by raycube(), and shadowray().
#define CHECKSIDE (side, distval, dotval, margin, normal)
Value:
if(visible&(1<<side)) do \
    { \
        float dist = distval; \
        if(dist > 0) return false; \
        if(dist <= bestdist) continue; \
        if(!dir.iszero()) \
        { \
            if(dotval >= -cutoff*dir.magnitude()) continue; \
            if(d->type<ENT_CAMERA && dotval < 0 && dist < margin) continue; \
        } \
        collidewall = normal; \
        bestdist = dist; \
    } while(0)
Referenced by cubecollideplanes(), cubecollidesolid(), fuzzycollideplanes(), and fuzzycollidesolid().
#define dir (name, v, d, s, os) ICOMMAND(name, "D", (int *down), { player->s = *down!=0; player->v = player->s ? d : (player->os ? -(d) : 0); });
Referenced by decalrenderer::adddecal(), bounce(), calcavatarpos(), ragdolldata::constraindist(), mpr::EntOBB::contactface(), mpr::ModelOBB::contactface(), mpr::ModelEllipse::contactface(), cubecollide(), pvsworker::cullpvs(), damagecompass(), shadowmaptexture::dorender(), game::hideandseekclientmode::drawblip(), game::ctfclientmode::drawblip(), game::bombclientmode::drawblip(), game::collectclientmode::drawblip(), game::captureclientmode::drawblips(), drawconlines(), game::drawminimap(), game::drawteammate(), entautoview(), entpush(), entities::entradius(), fireballrenderer::finddepthfxranges(), findfile(), ai::findorientation(), gendynlightvariant(), genpoly(), inexor::filesystem::getmediapath(), game::gotoplayer(), game::gotosel(), guessshadowdir(), insideface(), ai::jumpto(), vertcommands< MDL >::loadpart(), skelcommands< MDL >::loadpart(), ai::lockon(), main(), menuinfrontofplayer(), mergepolys(), mergetexs(), mmcollide(), ragdolldata::move(), mpeditface(), game::newbouncer(), game::nextfollow(), game::nextweapon(), offsetvec(), game::parsemessages(), server::parsepacket(), game::parsepositions(), platformcollide(), plcollide(), game::projdamage(), pushsel(), game::radialbombeffect(), game::radialeffect(), recomputecamera(), animmodel::render(), renderentradius(), fireballrenderer::renderpart(), screenshot(), game::sendposition(), skelcommands< MDL >::setanim(), modelcommands< MDL, struct MDL::vertmesh >::setbumpmap(), setconskip(), modelcommands< MDL, struct MDL::vertmesh >::setdir(), skelcommands< MDL >::setpitchtarget(), modelcommands< MDL, struct MDL::vertmesh >::setskin(), sortmaterials(), gui::start(), entities::teleport(), filesval::update(), ragdolldata::updatepos(), and filesval::~filesval().
#define DOWNOCTREE (disttoent, earlyexit)
Value:
cube *lc = levels[lshift]; \
        for(;;) \
        { \
            lshift--; \
            lc += octastep(x, y, z, lshift); \
            if(lc->ext && lc->ext->ents && lshift < elvl) \
            { \
                float edist = disttoent(lc->ext->ents, o, ray, dent, mode, t); \
                if(edist < dent) \
                { \
                    earlyexit return min(edist, dist); \
                    elvl = lshift; \
                    dent = min(dent, edist); \
                } \
            } \
            if(lc->children==NULL) break; \
            lc = lc->children; \
            levels[lshift] = lc; \
        }
Referenced by raycube(), and shadowray().
#define DYNENTCACHESIZE 1024
Referenced by cleardynentcache().
#define DYNENTHASH (x, y) (((((x)^(y))<<5) + (((x)^(y))>>5)) & (DYNENTCACHESIZE - 1))
Referenced by checkdynentcache(), and updatedynentcache().
#define entintersect (mask, type, func)
Value:
{\
        if((mode&(mask))==(mask)) loopv(oc->type) \
        { \
            extentity &e = *ents[oc->type[i]]; \
            if(!(e.flags&EF_OCTA) || &e==t) continue; \
            func; \
            if(f<dist && f>0 && vec(ray).mul(f).add(o).insidebb(oc->o, oc->size)) \
            { \
                hitentdist = dist = f; \
                hitent = oc->type[i]; \
                hitorient = orient; \
            } \
        } \
    }
Referenced by disttoent().
#define FINDCLOSEST (xclosest, yclosest, zclosest)
Value:
float dx = (lo.x+(lsizemask.x<<lshift)-v.x)*invray.x, \
              dy = (lo.y+(lsizemask.y<<lshift)-v.y)*invray.y, \
              dz = (lo.z+(lsizemask.z<<lshift)-v.z)*invray.z; \
        float disttonext = dx; \
        xclosest; \
        if(dy < disttonext) { disttonext = dy; yclosest; } \
        if(dz < disttonext) { disttonext = dz; zclosest; } \
        disttonext += 0.1f; \
        v.add(vec(ray).mul(disttonext)); \
        dist += disttonext;
Referenced by raycube(), and shadowray().
#define INITRAYCUBE
Value:
float dist = 0, dent = radius > 0 ? radius : 1e16f; \
    vec v(o), invray(ray.x ? 1/ray.x : 1e16f, ray.y ? 1/ray.y : 1e16f, ray.z ? 1/ray.z : 1e16f); \
    cube *levels[20]; \
    levels[worldscale] = worldroot; \
    int lshift = worldscale, elvl = mode&RAY_BB ? worldscale : 0; \
    ivec lsizemask(invray.x>0 ? 1 : 0, invray.y>0 ? 1 : 0, invray.z>0 ? 1 : 0); \
Referenced by raycube(), and shadowray().
#define INTERSECTBOX (setentry, exit)
Value:
loop(i, 3) \
    { \
        if(ray[i]) \
        { \
            float prad = fabs(p.r[i] * invray[i]), pdist = (p.o[i] - v[i]) * invray[i], pmin = pdist - prad, pmax = pdist + prad; \
            if(pmin > enterdist) \
            { \
                if(pmin > exitdist) exit; \
                enterdist = pmin; \
                setentry; \
            } \
            if(pmax < exitdist) \
            { \
                if(pmax < enterdist) exit; \
                exitdist = pmax; \
            } \
         } \
         else if(v[i] < p.o[i]-p.r[i] || v[i] > p.o[i]+p.r[i]) exit; \
    }
Referenced by raycubeintersect(), and shadowray().
#define INTERSECTPLANES (setentry, exit)
Value:
float enterdist = -1e16f, exitdist = 1e16f; \
    loopi(p.size) \
    { \
        float pdist = p.p[i].dist(v), facing = ray.dot(p.p[i]); \
        if(facing < 0) \
        { \
            pdist /= -facing; \
            if(pdist > enterdist) \
            { \
                if(pdist > exitdist) exit; \
                enterdist = pdist; \
                setentry; \
            } \
        } \
        else if(facing > 0) \
        { \
            pdist /= -facing; \
            if(pdist < exitdist) \
            { \
                if(pdist < enterdist) exit; \
                exitdist = pdist; \
            } \
        } \
        else if(pdist > 0) exit; \
    }
Referenced by raycubeintersect(), and shadowray().
#define loopdynentcache (curx, cury, o, radius)
Value:
for(int curx = max(int(o.x-radius), 0)>>dynentsize, endx = min(int(o.x+radius), worldsize-1)>>dynentsize; curx <= endx; curx++) \
    for(int cury = max(int(o.y-radius), 0)>>dynentsize, endy = min(int(o.y+radius), worldsize-1)>>dynentsize; cury <= endy; cury++)
Referenced by overlapsdynent(), plcollide(), and updatedynentcache().
#define PHYSFRAMETIME 5
Referenced by moveplayer(), and physicsframe().
#define UPOCTREE (exitworld)
Value:
x = int(v.x); \
        y = int(v.y); \
        z = int(v.z); \
        uint diff = uint(lo.x^x)|uint(lo.y^y)|uint(lo.z^z); \
        if(diff >= uint(worldsize)) exitworld; \
        diff >>= lshift; \
        if(!diff) exitworld; \
        do \
        { \
            lshift++; \
            diff >>= 1; \
        } while(diff);
Referenced by raycube(), and shadowray().
Function Documentation
void avoidcollision (physent * d, const vec & dir, physent * obstacle, float space)
References physent::aboveeye, vec::add(), physent::eyeheight, f(), loopi(), inexor::rpc::min(), physent::o, physent::radius, and vec::sub().
Referenced by game::newbouncer().
bool bounce (physent * d, float secs, float elasticity, float waterfric, float grav)
References physent::aboveeye, vec::add(), game::bounced(), collide(), collideinside, collideplayer, dir, vec::dot(), physent::eyeheight, f(), GRAVITY, isliquid, lookupmaterial(), loopi(), vec::magnitude(), inexor::rpc::max(), vec::mul(), physent::o, PHYS_BOUNCE, physent::physstate, vec::sub(), and physent::vel.
Referenced by bounce(), and game::updatebouncers().
bool bounce (physent * d, float elasticity, float waterfric, float grav)
References bounce(), physent::deltapos, f(), interppos(), loopi(), physent::newpos, physent::o, physframetime, and vec::sub().
const vector<physent *>& checkdynentcache (int x, int y)
References vector< T, MINSIZE >::add(), CS_ALIVE, hmap::d, dynentcache, dynentframe, DYNENTHASH, dynentcacheentry::dynents, dynentcacheentry::frame, game::iterdynents(), loopi(), game::numdynents(), physent::o, physent::radius, vector< T, MINSIZE >::shrink(), physent::state, dynentcacheentry::x, and dynentcacheentry::y.
Referenced by moveplatform(), overlapsdynent(), and plcollide().
template<class E > static bool clampcollide (const clipplanes & p, const E & entvol, const plane & w, const vec & pw) inline static
References fv, clipplanes::o, plane::offset, clipplanes::r, vec::squaredist(), and vec::squaredlen().
Referenced by cubecollideplanes(), and fuzzycollideplanes().
void cleardynentcache ()
References dynentcache, DYNENTCACHESIZE, dynentframe, dynentcacheentry::frame, and loopi().
Referenced by game::clearmovables(), game::clientdisconnected(), and physicsframe().
bool collide (physent * d, const vec & dir, float cutoff, bool playercol)
References physent::aboveeye, ivec::add(), collideinside, physent::eyeheight, physent::o, octacollide(), plcollide(), and physent::radius.
Referenced by bounce(), entinmap(), findfloor(), getclipplanes(), move(), movecamera(), moveplatform(), trystepdown(), trystepup(), and updatephysstate().
COMMAND (phystest , "")
static bool cubecollide (physent * d, const vec & dir, float cutoff, const cube & c, const ivec & co, int size, bool solid) inline static
References COLLIDE_ELLIPSE, COLLIDE_ELLIPSE_PRECISE, COLLIDE_OBB, physent::collidetype, hmap::d, dir, and isentirelysolid.
Referenced by octacollide().
template<class E > static bool cubecollideplanes (physent * d, const vec & dir, float cutoff, const cube & c, const ivec & co, int size) static
References physent::aboveeye, CHECKSIDE, clampcollide(), mpr::collide(), collideinside, plane::dist(), vec::dot(), ENT_CAMERA, physent::eyeheight, f(), getclipplanes(), vec::iszero(), loopi(), vec::magnitude(), physent::o, clipplanes::o, O_BACK, O_BOTTOM, O_FRONT, O_LEFT, O_RIGHT, O_TOP, clipplanes::p, clipplanes::r, physent::radius, clipplanes::size, physent::type, clipplanes::visible, and physent::zmargin.
template<class E > static bool cubecollidesolid (physent * d, const vec & dir, float cutoff, const cube & c, const ivec & co, int size) static
References physent::aboveeye, CHECKSIDE, mpr::collide(), collideinside, physent::eyeheight, f(), isentirelysolid, vec::iszero(), physent::o, O_BACK, O_BOTTOM, O_FRONT, O_LEFT, O_RIGHT, O_TOP, physent::radius, and physent::zmargin.
dir (backward , move , - 1, k_down , k_up)
dir (forward , move , 1 , k_up , k_down)
dir (left , strafe , 1 , k_left , k_right)
dir (right , strafe , - 1, k_right , k_left)
static float disttoent (octaentities * oc, const vec & o, const vec & ray, float radius, int mode, extentity * t) static
References entintersect, entities::ents, entselectionbox(), f(), entities::getents(), mapmodels, mmintersect(), orient, RAY_ENTS, RAY_POLY, and rayboxintersect().
Referenced by raycube().
static float disttooutsideent (const vec & o, const vec & ray, float radius, int mode, extentity * t) static
References EF_OCTA, entities::ents, entselectionbox(), f(), extentity::flags, entities::getents(), hitent, hitentdist, hitorient, loopv, orient, outsideents, and rayboxintersect().
Referenced by rayent().
void dropenttofloor (entity * e)
References dropheight(), droptofloor(), and entity::o.
Referenced by dropentity().
float dropheight (entity & e)
References entities::dropheight(), ET_GAMESPECIFIC, ET_MAPMODEL, ET_PARTICLES, and entity::type.
Referenced by dropenttofloor().
bool droptofloor (vec & o, float radius, float height)
References hmap::d, dropent(), ENT_BOUNCE, f(), insideworld(), movecamera(), vec::normalize(), raycube(), and worldsize.
Referenced by dropenttofloor(), game::ctfclientmode::dropflag(), game::collectclientmode::movetoken(), and game::ctfclientmode::parseflags().
bool ellipseboxcollide (physent * d, const vec & dir, const vec & o, const vec & center, float yaw, float xr, float yr, float hi, float lo)
References physent::aboveeye, collideinside, ENT_INANIMATE, physent::eyeheight, f(), vec::iszero(), physent::o, RAD, physent::radius, vec::rotate_around_z(), vec::sub(), physent::type, and physent::zmargin.
Referenced by mmcollide(), platformcollide(), and plcollide().
bool ellipsecollide (physent * d, const vec & dir, const vec & o, const vec & center, float yaw, float xr, float yr, float hi, float lo)
References physent::aboveeye, vec::add(), collideinside, ENT_INANIMATE, physent::eyeheight, f(), vec::iszero(), vec::normalize(), physent::o, RAD, vec::rotate_around_z(), physent::type, physent::xradius, physent::yaw, physent::yradius, and physent::zmargin.
Referenced by mmcollide(), platformcollide(), plcollide(), and game::weaponcollide().
bool entinmap (dynent * d, bool avoidplayers)
References collide(), collideinside, physent::eyeheight, Log, loopi(), physent::o, physent::resetinterp(), rnd(), and inexor::util::log_manager::std.
Referenced by game::clearmovables(), findplayerspawn(), game::ctfclientmode::pickholdspawn(), game::bombclientmode::pickspawn(), entities::teleport(), and toggleedit().
void entselectionbox (const entity & e, vec & eo, vec & es)
References vec::add(), entity::attr2, model::collisionbox(), entities::entmodel(), ET_MAPMODEL, loadmapmodel(), loadmodel(), vec::max(), mmcollisionbox(), vec::mul(), entity::o, vec::sub(), and entity::type.
Referenced by disttoent(), disttooutsideent(), entdrag(), and renderentselection().
void falling (physent * d, vec & dir, const vec & floor)
References vec::dot(), physent::floor, vec::magnitude(), PHYS_FALL, PHYS_SLIDE, PHYS_SLOPE, physent::physstate, SLOPEZ, switchfloor(), physent::timeinair, trystepdown(), and WALLZ.
Referenced by move(), and game::parsepositions().
bool findfloor (physent * d, bool collided, const vec & obstacle, bool & slide, vec & floor)
References collide(), collidewall, physent::floor, FLOORZ, vec::neg(), physent::o, PHYS_SLIDE, PHYS_SLOPE, PHYS_STEP_DOWN, PHYS_STEP_UP, physent::physstate, SLOPEZ, and WALLZ.
Referenced by move().
void freeshadowraycache (ShadowRayCache *& cache)
Referenced by lightmapworker::~lightmapworker().
template<class E > static bool fuzzycollideplanes (physent * d, const vec & dir, float cutoff, const cube & c, const ivec & co, int size) static
References physent::aboveeye, CHECKSIDE, clampcollide(), collideinside, plane::dist(), vec::dot(), ENT_CAMERA, physent::eyeheight, getclipplanes(), vec::iszero(), loopi(), vec::magnitude(), physent::o, clipplanes::o, O_BACK, O_BOTTOM, O_FRONT, O_LEFT, O_RIGHT, O_TOP, clipplanes::p, clipplanes::r, physent::radius, clipplanes::size, physent::type, clipplanes::visible, and physent::zmargin.
template<class E > static bool fuzzycollidesolid (physent * d, const vec & dir, float cutoff, const cube & c, const ivec & co, int size) static
References physent::aboveeye, CHECKSIDE, collideinside, physent::eyeheight, isentirelysolid, vec::iszero(), physent::o, O_BACK, O_BOTTOM, O_FRONT, O_LEFT, O_RIGHT, O_TOP, physent::radius, and physent::zmargin.
FVAR (straferoll , 0 , 0. 033f, 90)
FVAR (faderoll , 0 , 0. 95f, 1)
static clipplanes& getclipplanes (const cube & c, const ivec & o, int size, bool collide = true, int offset = 0) inline static
References clipcacheversion, collide(), genclipplanes(), MAXCLIPPLANES, clipplanes::owner, clipplanes::version, and worldroot.
Referenced by cubecollideplanes(), fuzzycollideplanes(), raycube(), and shadowray().
ICOMMAND (attack , "D" , (int *down) , {game::doattack(*down!=0);})
ICOMMAND (jump , "D" , (int *down) , {if(!*down||game::canjump()) player->jumping=*down!=0;})
void interppos (physent * pl)
References vec::add(), physent::deltapos, lastmillis, inexor::rpc::min(), vec::mul(), physent::newpos, physent::o, and physframetime.
Referenced by bounce(), and moveplayer().
void landing (physent * d, vec & dir, const vec & floor, bool collided)
References physent::floor, FLOORZ, PHYS_FALL, PHYS_FLOOR, PHYS_SLOPE, PHYS_STEP_DOWN, PHYS_STEP_UP, physent::physstate, switchfloor(), physent::timeinair, and physent::vel.
Referenced by move().
template<class E , class M > static bool mmcollide (physent * d, const vec & dir, const extentity & e, const vec & center, const vec & radius, float yaw) inline static
References mpr::collide(), collideinside, dir, vec::iszero(), vec::neg(), entity::o, and vec::sub().
Referenced by octacollide().
bool mmcollide (physent * d, const vec & dir, octaentities & oc)
References vec::add(), entity::attr1, entity::attr2, model::collide, COLLIDE_ELLIPSE, COLLIDE_ELLIPSE_PRECISE, COLLIDE_OBB, physent::collidetype, model::collisionbox(), EF_NOCOLLIDE, ellipseboxcollide(), model::ellipsecollide, ellipsecollide(), entities::ents, extentity::flags, entities::getents(), loadmapmodel(), loopv, octaentities::mapmodels, entity::o, physent::o, physent::radius, vec::reject(), and game::weaponcollide().
void modifygravity (physent * pl, bool water, int curtime)
References vec::add(), game::allowmove(), f(), physent::falling, physent::floor, FLOORZ, GRAVITY, physent::move, vec::mul(), vec::normalize(), PHYS_FALL, PHYS_SLOPE, physent::physstate, vec::project(), SLOPEZ, and physent::strafe.
Referenced by moveplayer().
void modifyvelocity (physent * pl, bool local, bool water, bool floating, int curtime)
References game::allowmove(), curtime, hmap::d, vec::div(), ENT_CAMERA, ENT_PLAYER, f(), physent::floor, physent::inwater, physent::jumping, JUMPVEL, vec::lerp(), inexor::rpc::max(), physent::maxspeed, physent::move, vec::mul(), vec::normalize(), PHYS_FALL, PHYS_SLOPE, game::physicstrigger(), physent::physstate, physent::pitch, player, physent::strafe, physent::timeinair, physent::type, vecfromyawpitch(), physent::vel, and physent::yaw.
Referenced by moveplayer().
bool move (physent * d, vec & dir)
References vec::add(), physent::blocked, collide(), collidewall, vec::dot(), ENT_AI, ENT_INANIMATE, ENT_PLAYER, f(), falling(), findfloor(), physent::floor, FLOORZ, landing(), physent::o, PHYS_FLOOR, PHYS_SLOPE, PHYS_STEP_DOWN, PHYS_STEP_UP, physent::physstate, slideagainst(), SLOPEZ, STAIRHEIGHT, trystepdown(), trystepup(), physent::type, WALLZ, and physent::zmargin.
Referenced by inexor::crashreporter::abortHandler(), inexor::crashreporter::demanglesymbol(), inexor::filesystem::getmediapath(), inexor::rpc::RpcServer< MSG_TYPE, ASYNC_SERVICE_TYPE >::handle_new_connection(), moveplayer(), inexor::rpc::SharedVar< char * >::operator=(), ai::process(), SharedList< T >::push_back(), inexor::rpc::SharedVar< char * >::setnosync(), and anonymous_namespace{Observe.cpp}::test_primitive().
bool movecamera (physent * pl, const vec & dir, float dist, float stepdist)
References vec::add(), collide(), hmap::d, loopi(), vec::mul(), and physent::o.
Referenced by droptofloor(), game::collectclientmode::movetoken(), and recomputecamera().
bool moveplatform (physent * p, const vec & dir)
References physent::aboveeye, vector< T, MINSIZE >::add(), vec::add(), platforment::chains, checkdynentcache(), collide(), hmap::d, platforment::d, entities::ents, physent::eyeheight, vector< T, MINSIZE >::find(), insideworld(), vector< T, MINSIZE >::length(), loopv, loopvj, inexor::rpc::max(), inexor::rpc::min(), physent::newpos, physent::o, platformcollide(), physent::radius, vec::reject(), vector< T, MINSIZE >::setsize(), platforment::stacks, updatedynentcache(), and worldsize.
Referenced by game::updatemovables().
bool moveplayer (physent * pl, int moveres, bool local, int curtime)
References physent::aboveeye, vec::add(), physent::blocked, CS_ALIVE, CS_EDITING, CS_SPECTATOR, hmap::d, ENT_PLAYER, physent::eyeheight, f(), physent::falling, physent::inwater, isliquid, lookupmaterial(), loopi(), MAT_AIR, MAT_DEATH, MATF_VOLUME, modifygravity(), modifyvelocity(), move(), vec::mul(), physent::o, PHYS_FLOAT, PHYSFRAMETIME, game::physicstrigger(), physent::physstate, physent::roll, physent::state, physent::strafe, game::suicide(), physent::timeinair, physent::type, updatedynentcache(), and physent::vel.
Referenced by ai::logic(), moveplayer(), game::otherplayers(), game::predictplayer(), game::updatemovables(), and game::updateworld().
void moveplayer (physent * pl, int moveres, bool local)
References physent::deltapos, interppos(), loopi(), moveplayer(), physent::newpos, physent::o, physframetime, and vec::sub().
ShadowRayCache* newshadowraycache ()
Referenced by lightmapworker::lightmapworker().
static bool octacollide (physent * d, const vec & dir, float cutoff, const ivec & bo, const ivec & bs, const cube * c, const ivec & cor, int size) inline static
References cubecollide(), ENT_AI, ENT_CAMERA, cubeext::ents, ext(), isclipped, isempty, loopoctabox, MAT_CLIP, MAT_GAMECLIP, MAT_NOCLIP, MATF_CLIP, MATF_VOLUME, mmcollide(), and physent::type.
Referenced by collide(), and octacollide().
static bool octacollide (physent * d, const vec & dir, float cutoff, const ivec & bo, const ivec & bs) inline static
References cube::children, cubecollide(), ENT_AI, ENT_CAMERA, cubeext::ents, cube::ext, isclipped, isempty, MAT_CLIP, MAT_GAMECLIP, MAT_NOCLIP, cube::material, MATF_CLIP, MATF_VOLUME, mmcollide(), octacollide(), octastep, physent::type, worldroot, worldscale, and worldsize.
bool overlapsdynent (const vec & o, float radius)
References checkdynentcache(), hmap::d, vec::dist(), loopdynentcache, loopv, physent::o, and physent::radius.
Referenced by entities::checktriggers(), and entities::unlocktriggers().
void physicsframe ()
References cleardynentcache(), game::gamespeed, lastmillis, lastphysframe, PHYSFRAMETIME, physframetime, and scaletime().
Referenced by game::updateworld().
void phystest ()
References camera1, physent::falling, physent::floor, physent::physstate, player, physent::timeinair, and physent::vel.
template<class E , class O > static bool platformcollide (physent * d, const vec & dir, physent * o, float margin) inline static
References mpr::collide(), dir, vec::iszero(), vec::neg(), and vec::sub().
Referenced by moveplatform().
bool platformcollide (physent * d, physent * o, const vec & dir, float margin = 0)
References physent::aboveeye, COLLIDE_OBB, physent::collidetype, hmap::d, dir, ellipseboxcollide(), ellipsecollide(), physent::eyeheight, physent::o, physent::xradius, physent::yaw, and physent::yradius.
template<class E , class O > static bool plcollide (physent * d, const vec & dir, physent * o) inline static
References mpr::collide(), collideinside, dir, vec::iszero(), vec::neg(), and vec::sub().
Referenced by collide().
bool plcollide (physent * d, const vec & dir)
References physent::aboveeye, checkdynentcache(), COLLIDE_ELLIPSE, COLLIDE_ELLIPSE_PRECISE, COLLIDE_OBB, physent::collidetype, CS_ALIVE, game::dynentcollide(), ellipseboxcollide(), ellipsecollide(), ENT_CAMERA, physent::eyeheight, loopdynentcache, loopv, physent::o, physent::radius, vec::reject(), physent::state, physent::type, physent::xradius, physent::yaw, and physent::yradius.
static bool pointinbox (const vec & v, const vec & bo, const vec & br) inline static
Referenced by pointincube().
bool pointincube (const clipplanes & p, const vec & v)
References plane::dist(), f(), loopi(), clipplanes::o, clipplanes::p, pointinbox(), clipplanes::r, and clipplanes::size.
Referenced by isvalidcube().
float raycube (const vec & o, const vec & ray, float radius, int mode, int size, extentity * t)
References CHECKINSIDEWORLD, disttoent(), DOWNOCTREE, f(), FINDCLOSEST, getclipplanes(), INITRAYCUBE, isclipped, isempty, isentirelysolid, vec::iszero(), MAT_AIR, cube::material, MATF_VOLUME, inexor::rpc::min(), RAY_CLIPMAT, RAY_EDITMAT, RAY_PASS, RAY_SHADOW, RAY_SKIPFIRST, raycubeintersect(), and UPOCTREE.
Referenced by droptofloor(), ai::getweight(), game::particletrack(), raycubepos(), rayent(), rayfloor(), regularshape(), game::renderbouncers(), setupmaterials(), game::shoot(), splash(), and game::weaponcollide().
static bool raycubeintersect (const clipplanes & p, const cube & c, const vec & v, const vec & ray, const vec & invray, float & dist) inline static
References f(), INTERSECTBOX, INTERSECTPLANES, inexor::rpc::max(), and clipplanes::p.
Referenced by raycube().
bool raycubelos (const vec & o, const vec & dest, vec & hitpos)
References vec::magnitude(), vec::mul(), RAY_CLIPMAT, RAY_POLY, raycubepos(), and vec::sub().
Referenced by ai::getsight(), and flarerenderer::newflare().
float raycubepos (const vec & o, const vec & ray, vec & hitpos, float radius, int mode, int size)
References vec::add(), vec::mul(), and raycube().
Referenced by ai::findorientation(), game::offsetray(), raycubelos(), setcammatrix(), and game::updateprojectiles().
float rayent (const vec & o, const vec & ray, float radius, int mode, int size, int & orient, int & ent)
References disttooutsideent(), hitent, hitentdist, hitorient, RAY_ENTS, and raycube().
Referenced by rendereditcursor().
float rayfloor (const vec & o, vec & floor, int mode, float radius)
References hitsurface, and raycube().
Referenced by partrenderer::calc().
void recalcdir (physent * d, const vec & oldvel, vec & dir)
References vec::add(), f(), physent::falling, vec::magnitude(), vec::mul(), and physent::vel.
Referenced by slideagainst(), and switchfloor().
void resetclipplanes ()
References clipcacheversion.
Referenced by allchanged(), and commitchanges().
void resetshadowraycache (ShadowRayCache * cache)
References ShadowRayCache::clipcache, and ShadowRayCache::version.
Referenced by lightmapworker::reset().
void rotatebb (vec & center, vec & radius, int yaw)
References sincos360.
Referenced by getentboundingbox(), mmboundbox(), mmcollisionbox(), and rendermodel().
static float shadowent (octaentities * oc, const vec & o, const vec & ray, float radius, int mode, extentity * t) static
References EF_OCTA, entities::ents, f(), extentity::flags, entities::getents(), loopv, octaentities::mapmodels, and mmintersect().
Referenced by shadowray().
float shadowray (const vec & o, const vec & ray, float radius, int mode, extentity * t)
References CHECKINSIDEWORLD, DEFAULT_SKY, DOWNOCTREE, f(), FINDCLOSEST, getclipplanes(), INITRAYCUBE, INTERSECTBOX, INTERSECTPLANES, isempty, isentirelysolid, MAT_ALPHA, cube::material, inexor::rpc::max(), O_BOTTOM, O_FRONT, O_RIGHT, O_TOP, RAY_SKIPSKY, shadowent(), clipplanes::side, cube::texture, and UPOCTREE.
Referenced by brightestlight(), calcocclusion(), calcskylight(), fastskylight(), generatelumel(), and lightreaching().
float shadowray (ShadowRayCache * cache, const vec & o, const vec & ray, float radius, int mode, extentity * t)
References CHECKINSIDEWORLD, ShadowRayCache::clipcache, DEFAULT_SKY, DOWNOCTREE, f(), FINDCLOSEST, genclipplanes(), INITRAYCUBE, INTERSECTBOX, INTERSECTPLANES, isempty, isentirelysolid, MAT_ALPHA, cube::material, inexor::rpc::max(), MAXCLIPPLANES, O_BOTTOM, O_FRONT, O_RIGHT, O_TOP, clipplanes::owner, RAY_SKIPSKY, shadowent(), clipplanes::side, cube::texture, UPOCTREE, clipplanes::version, ShadowRayCache::version, and worldroot.
void slideagainst (physent * d, vec & dir, const vec & obstacle, bool foundfloor, bool slidecollide)
References vec::add(), physent::falling, vec::iszero(), vec::normalize(), vec::project(), recalcdir(), and physent::vel.
Referenced by move().
void switchfloor (physent * d, vec & dir, const vec & floor)
References vec::add(), vec::dot(), f(), physent::falling, physent::floor, FLOORZ, vec::magnitude(), PHYS_SLIDE, physent::physstate, vec::project(), vec::projectxy(), recalcdir(), and physent::vel.
Referenced by falling(), landing(), trystepdown(), and trystepup().
bool trystepdown (physent * d, vec & dir, float step, float xy, float z, bool init = false)
References vec::add(), collide(), physent::floor, sphere::init(), vec::magnitude2(), vec::mul(), vec::normalize(), physent::o, PHYS_SLOPE, PHYS_STEP_DOWN, physent::physstate, SLOPEZ, STAIRHEIGHT, switchfloor(), physent::timeinair, and physent::zmargin.
Referenced by falling(), move(), and trystepdown().
bool trystepdown (physent * d, vec & dir, bool init = false)
References game::allowmove(), collide(), sphere::init(), vec::magnitude(), physent::move, physent::o, SLOPEZ, STAIRHEIGHT, physent::strafe, trystepdown(), and physent::zmargin.
bool trystepup (physent * d, vec & dir, const vec & obstacle, float maxstep, const vec & floor)
References vec::add(), collide(), f(), physent::floor, vec::magnitude(), vec::mul(), physent::o, PHYS_FALL, PHYS_STEP_UP, physent::physstate, SLOPEZ, vec::sub(), switchfloor(), and physent::timeinair.
Referenced by move().
void updatedynentcache (physent * d)
References vector< T, MINSIZE >::add(), dynentcache, dynentframe, DYNENTHASH, dynentcacheentry::dynents, vector< T, MINSIZE >::find(), dynentcacheentry::frame, loopdynentcache, physent::o, physent::radius, dynentcacheentry::x, and dynentcacheentry::y.
Referenced by game::clearmovables(), moveplatform(), moveplayer(), and entities::teleport().
void updatephysstate (physent * d)
References collide(), collidewall, physent::floor, FLOORZ, physent::o, PHYS_FALL, PHYS_FLOOR, PHYS_SLIDE, PHYS_SLOPE, PHYS_STEP_DOWN, PHYS_STEP_UP, physent::physstate, SLOPEZ, STAIRHEIGHT, and physent::timeinair.
Referenced by game::parsepositions().
VAR (floatspeed , 1 , 100 , 10000)
VAR (physinterp , 0 , 1 , 1)
VARF (dynentsize , 4 , 7 , 12 , cleardynentcache())
VARP (maxroll , 0 , 0 , 20)
void vecfromyawpitch (float yaw, float pitch, int move, int strafe, vec & m)
References RAD.
Referenced by shadowmaptexture::dorender(), game::drawhudmodel(), game::drawminimap(), entities::entradius(), ai::findorientation(), game::gotoplayer(), game::gotosel(), game::hudgunorigin(), menuinfrontofplayer(), modifyvelocity(), game::movable::movable(), game::collectclientmode::movetoken(), game::parsepositions(), game::particletrack(), renderentradius(), sortmaterials(), entities::teleport(), and game::triggerplatform().
void vectoyawpitch (const vec & v, float & yaw, float & pitch)
References vec::iszero(), vec::magnitude(), and RAD.
Referenced by damagecompass(), game::ctfclientmode::interpflagpos(), ai::process(), game::renderbouncers(), game::bombclientmode::renderplayersposindicator(), game::renderprojectiles(), and game::sendposition().
Variable Documentation
clipplanes clipcache[MAXCLIPPLANES] static
int clipcacheversion = -2 static
Referenced by getclipplanes(), and resetclipplanes().
bool collideinside
Referenced by bounce(), collide(), cubecollideplanes(), cubecollidesolid(), ellipseboxcollide(), ellipsecollide(), entinmap(), fuzzycollideplanes(), fuzzycollidesolid(), mmcollide(), and plcollide().
physent* collideplayer
Referenced by bounce().
vec collidewall
Referenced by findfloor(), ragdolldata::move(), move(), updatephysstate(), and ragdolldata::updatepos().
struct dynentcacheentry dynentcache[DYNENTCACHESIZE] static
Referenced by checkdynentcache(), cleardynentcache(), and updatedynentcache().
uint dynentframe = 0 static
Referenced by checkdynentcache(), cleardynentcache(), and updatedynentcache().
const float FLOORZ = 0.867f
Referenced by findfloor(), landing(), modifygravity(), move(), switchfloor(), and updatephysstate().
const float GRAVITY = 200.0f
Referenced by bounce(), modifygravity(), and ragdolldata::move().
int hitent
Referenced by disttooutsideent(), and rayent().
float hitentdist
Referenced by disttooutsideent(), and rayent().
int hitorient
Referenced by disttooutsideent(), and rayent().
vec hitsurface
Referenced by rayfloor().
const float JUMPVEL = 125.0f
Referenced by modifyvelocity().
int lastphysframe = 0
Referenced by physicsframe().
const int MAXCLIPPLANES = 1024
Referenced by getclipplanes(), and shadowray().
int physframetime = PHYSFRAMETIME
Referenced by bounce(), interppos(), moveplayer(), and physicsframe().
int physsteps = 0
Referenced by game::updatemovables().
const float PLATFORMBORDER = 10.0f
const float PLATFORMMARGIN = 0.2f
const float SLOPEZ = 0.5f
Referenced by falling(), findfloor(), modifygravity(), move(), trystepdown(), trystepup(), and updatephysstate().
const float STAIRHEIGHT = 4.1f
Referenced by move(), trystepdown(), and updatephysstate().
const float WALLZ = 0.2f
Referenced by falling(), findfloor(), and move().