Inexor: inexor/engine/pvs.cpp File Reference
pvs.cpp File Reference
#include <limits.h>
#include <math.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "SDL_keycode.h"
#include "SDL_mutex.h"
#include "SDL_stdinc.h"
#include "SDL_thread.h"
#include "SDL_timer.h"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/pvs.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/input/InputRouter.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_queue.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/tools.hpp"
Classes
struct pvsnode
struct shaftplane
struct shaftbb
struct shaft
struct pvsdata
struct viewcellrequest
struct pvsworker
struct pvsworker::cullorder
struct viewcellnode
union viewcellnode::viewcellchild
union shaftbb.__unnamed__
struct shaftbb.__unnamed__.__unnamed__
Macros
#define MERGEBBS(res, coord, row, col)
#define MAXWATERPVS 32
Enumerations
enum { PVS_HIDE_GEOM = 1<<0, PVS_HIDE_BB = 1<<1 }
Functions
static bool mergepvsnodes (pvsnode &p, pvsnode *children)
static void genpvsnodes (cube *c, int parent=0, const ivec &co=ivec(0, 0, 0), int size=worldsize/2)
static uint hthash (const pvsdata &k)
static bool htcmp (const pvsdata &x, const pvsdata &y)
VAR (maxpvsblocker, 1, 512, 1<< 16)
VAR (pvsleafsize, 1, 64, 1024)
VARP (pvsthreads, 0, 0, 16)
static Uint32 genpvs_timer (Uint32 interval, void *param)
static void show_genpvs_progress (int unique=pvs.length(), int processed=numviewcells)
static void calcpvsbounds ()
static bool isallclip (cube *c)
static int countviewcells (cube *c, const ivec &co, int size, int threshold)
static void genviewcells (viewcellnode &p, cube *c, const ivec &co, int size, int threshold)
static pvsdata * lookupviewcell (const vec &p)
static void lockpvs_ (bool lock)
VARF (lockpvs, 0, 0, 1, lockpvs_(lockpvs!=0))
VARN (pvs, usepvs, 0, 1, 1)
VARN (waterpvs, usewaterpvs, 0, 1, 1)
void setviewcell (const vec &p)
void clearpvs ()
COMMAND (clearpvs,"")
static void findwaterplanes ()
void testpvs (int *vcsize)
COMMAND (testpvs,"i")
void genpvs (int *viewcellsize)
COMMAND (genpvs,"i")
void pvsstats ()
COMMAND (pvsstats,"")
static bool pvsoccluded (uchar *buf, const ivec &co, int size, const ivec &bbmin, const ivec &bbmax)
static bool pvsoccluded (uchar *buf, const ivec &bbmin, const ivec &bbmax)
bool pvsoccluded (const ivec &bbmin, const ivec &bbmax)
bool pvsoccludedsphere (const vec &center, float radius)
bool waterpvsoccluded (int height)
void saveviewcells (stream *f, viewcellnode &p)
void savepvs (stream *f)
viewcellnode * loadviewcells (stream *f)
void loadpvs (stream *f, int numpvs)
int getnumviewcells ()
Variables
static vector< pvsnode > origpvsnodes
static vector< uchar > pvsbuf
static SDL_mutex * pvsmutex = nullptr
static hashtable< pvsdata, int > pvscompress
static vector< pvsdata > pvs
static SDL_mutex * viewcellmutex = nullptr
static vector< viewcellrequest > viewcellrequests
static bool genpvs_canceled = false
static int numviewcells = 0
struct {
int height
vector< materialsurface * > matsurfs
} waterplanes [MAXWATERPVS]
static vector< materialsurface * > waterfalls
uint numwaterplanes = 0
static vector< pvsworker * > pvsworkers
static volatile bool check_genpvs_progress = false
static int totalviewcells = 0
static shaftbb pvsbounds
static viewcellnode * viewcells = nullptr
static int lockedwaterplanes [MAXWATERPVS]
static uchar * curpvs = nullptr
static uchar * lockedpvs = nullptr
static int curwaterpvs = 0
static int lockedwaterpvs = 0
Class Documentation
struct pvsnode
Class Members
uint children
bvec edges
uchar flags
struct shaftplane
Class Members
float c
uchar cfar
uchar cnear
float offset
float r
uchar rfar
uchar rnear
struct viewcellrequest
Class Members
ivec o
int * result
int size
union viewcellnode::viewcellchild
Class Members
viewcellnode * node
int pvs
union shaftbb.__unnamed__
Class Members
__unnamed__ __unnamed__
ushort v[6]
struct shaftbb.__unnamed__.__unnamed__
Class Members
usvec max
usvec min
Macro Definition Documentation
#define MAXWATERPVS 32
Referenced by findwaterplanes(), lockpvs_(), testpvs(), and waterpvsoccluded().
#define MERGEBBS (res, coord, row, col)
Value:
if(lo.coord==0xFF) \
        { \
            if(hi.coord!=0xFF) \
            { \
                res.coord = ((hi.coord&~0x11)>>1) + 0x44; \
                res.row = hi.row; \
                res.col = hi.col; \
            } \
        } \
        else if(hi.coord==0xFF) \
        { \
            res.coord = (lo.coord&0xEE)>>1; \
            res.row = lo.row; \
            res.col = lo.col; \
        } \
        else if(lo.row!=hi.row || lo.col!=hi.col || (lo.coord&0xF0)!=0x80 || (hi.coord&0xF)!=0) return false; \
        else \
        { \
            res.coord = ((lo.coord&~0xF1)>>1) | (((hi.coord&~0x1F)>>1) + 0x40); \
            res.row = lo.row; \
            res.col = lo.col; \
        }
Referenced by mergepvsnodes().
Enumeration Type Documentation
anonymous enum
Enumerator
PVS_HIDE_GEOM
PVS_HIDE_BB
Function Documentation
static void calcpvsbounds () static
References vtxarray::geommax, vtxarray::geommin, loopk, loopv, inexor::rpc::max(), inexor::rpc::min(), pvsbounds, and valist.
Referenced by genpvs().
void clearpvs ()
References curpvs, DELETEP, lockpvs_(), numwaterplanes, pvs, pvsbuf, vector< T, MINSIZE >::setsize(), and viewcells.
Referenced by genpvs(), and resetmap().
COMMAND (clearpvs , "")
COMMAND (testpvs , "i")
COMMAND (genpvs , "i")
COMMAND (pvsstats , "")
static int countviewcells (cube * c, const ivec & co, int size, int threshold) static
References cube::children, isallclip(), isentirelysolid, loopi(), MAT_CLIP, cube::material, MATF_CLIP, shaftbb::outside(), and pvsbounds.
Referenced by genpvs().
static void findwaterplanes () static
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::length(), loopi(), loopj, loopk, loopv, MAT_WATER, vtxarray::matbuf, materialsurface::material, MATF_VOLUME, vtxarray::matsurfs, MAXWATERPVS, numwaterplanes, materialsurface::o, O_BOTTOM, O_TOP, materialsurface::orient, vector< T, MINSIZE >::setsize(), materialsurface::skip, valist, waterfalls, and waterplanes.
Referenced by genpvs(), and testpvs().
void genpvs (int * viewcellsize)
References calcpvsbounds(), check_genpvs_progress, pvsnode::children, clearpvs(), countviewcells(), pvsnode::edges, inexor::util::log_manager::edit, gle::end(), f(), findwaterplanes(), pvsnode::flags, genpvs_canceled, genpvs_timer(), genpvsnodes(), genviewcells(), vector< T, MINSIZE >::length(), Log, loopi(), loopv, inexor::rpc::max(), numviewcells, origpvsnodes, pvs, pvsbuf, pvscompress, pvsmutex, pvsworkers, renderbackground(), renderprogress(), pvsworker::run(), show_genpvs_progress(), recorder::start(), pvsworker::thread, recorder::thread, totalviewcells, viewcellmutex, viewcellrequests, viewcells, worldroot, and worldsize.
static Uint32 genpvs_timer (Uint32 interval, void * param) static
References check_genpvs_progress.
Referenced by genpvs().
static void genpvsnodes (cube * c, int parent = 0, const ivec & co = ivec(0, 0, 0), int size = worldsize/2) static
References pvsnode::children, pvsnode::edges, F_SOLID, pvsnode::flags, isempty, loopi(), loopk, MAT_ALPHA, inexor::rpc::max(), mergepvsnodes(), inexor::rpc::min(), and origpvsnodes.
Referenced by genpvs(), and testpvs().
static void genviewcells (viewcellnode & p, cube * c, const ivec & co, int size, int threshold) static
References check_genpvs_progress, cube::children, viewcellnode::children, genpvs_canceled, isallclip(), isentirelysolid, viewcellnode::leafmask, loopi(), MAT_CLIP, cube::material, MATF_CLIP, viewcellnode::viewcellchild::node, viewcellrequest::o, shaftbb::outside(), viewcellnode::viewcellchild::pvs, pvsbounds, pvsworkers, viewcellrequest::result, show_genpvs_progress(), viewcellrequest::size, and viewcellrequests.
Referenced by genpvs().
int getnumviewcells ()
References pvs.
Referenced by gl_drawhud(), and save_world().
static bool htcmp (const pvsdata & x, const pvsdata & y) inline static
References pvsdata::len, pvsdata::offset, and pvsbuf.
static uint hthash (const pvsdata & k) inline static
References pvsdata::len, loopi(), pvsdata::offset, and pvsbuf.
static bool isallclip (cube * c) inline static
References cube::children, isentirelysolid, loopi(), MAT_CLIP, cube::material, and MATF_CLIP.
Referenced by countviewcells(), and genviewcells().
void loadpvs (stream * f, int numpvs)
References vector< T, MINSIZE >::advance(), stream::getlil(), loadviewcells(), loopi(), numwaterplanes, pvs, pvsbuf, stream::read(), vector< T, MINSIZE >::reserve(), viewcells, and waterplanes.
Referenced by load_world().
viewcellnode* loadviewcells (stream * f)
References viewcellnode::children, stream::getchar(), stream::getlil(), viewcellnode::leafmask, loopi(), viewcellnode::viewcellchild::node, and viewcellnode::viewcellchild::pvs.
Referenced by loadpvs().
static void lockpvs_ (bool lock) static
References camera1, hmap::d, DELETEA, pvsdata::len, lockedpvs, lockedwaterplanes, lockedwaterpvs, Log, lookupviewcell(), loopi(), MAXWATERPVS, physent::o, pvsdata::offset, pvsbuf, inexor::util::log_manager::std, and waterplanes.
Referenced by clearpvs(), and testpvs().
static pvsdata* lookupviewcell (const vec & p) inline static
References viewcellnode::children, viewcellnode::leafmask, viewcellnode::viewcellchild::node, octastep, pvs, viewcellnode::viewcellchild::pvs, vc, viewcells, worldscale, and worldsize.
Referenced by lockpvs_(), and setviewcell().
static bool mergepvsnodes (pvsnode & p, pvsnode * children) static
References pvsnode::edges, hmap::flags, loop, loopi(), MERGEBBS, and octaindex.
Referenced by genpvsnodes().
static bool pvsoccluded (uchar * buf, const ivec & co, int size, const ivec & bbmin, const ivec & bbmax) inline static
References loopoctabox, and octaboxoverlap().
Referenced by findvisiblemms(), findvisiblevas(), modeloccluded(), pvsoccluded(), pvsoccludedsphere(), renderalphageom(), rendergeom(), and updateparticles().
static bool pvsoccluded (uchar * buf, const ivec & bbmin, const ivec & bbmax) inline static
References octaboxoverlap(), octastep, pvsoccluded(), and worldscale.
bool pvsoccluded (const ivec & bbmin, const ivec & bbmax)
References curpvs, and pvsoccluded().
Referenced by pvsoccluded().
bool pvsoccludedsphere (const vec & center, float radius)
References curpvs, and pvsoccluded().
Referenced by finddynlights().
void pvsstats ()
References inexor::util::log_manager::edit, vector< T, MINSIZE >::length(), Log, inexor::rpc::max(), pvs, and pvsbuf.
void savepvs (stream * f)
References vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), loopi(), loopv, numwaterplanes, stream::putlil(), pvs, pvsbuf, saveviewcells(), viewcells, waterplanes, and stream::write().
Referenced by save_world().
void saveviewcells (stream * f, viewcellnode & p)
References viewcellnode::children, viewcellnode::leafmask, loopi(), viewcellnode::viewcellchild::node, stream::putchar(), stream::putlil(), and viewcellnode::viewcellchild::pvs.
Referenced by savepvs().
void setviewcell (const vec & p)
References curpvs, curwaterpvs, hmap::d, pvsdata::len, lockedpvs, lockedwaterpvs, lookupviewcell(), loopi(), pvsdata::offset, and pvsbuf.
Referenced by drawcubemap(), drawminimap(), and recomputecamera().
static void show_genpvs_progress (int unique = pvs.length(), int processed = numviewcells) static
References check_genpvs_progress, defformatstring, genpvs_canceled, inexor::io::input_router, inexor::io::InputRouter::interceptkey(), renderprogress(), and totalviewcells.
Referenced by genpvs(), and genviewcells().
void testpvs (int * vcsize)
References camera1, check_genpvs_progress, pvsnode::children, pvsnode::edges, inexor::util::log_manager::edit, findwaterplanes(), pvsnode::flags, genpvs_canceled, genpvsnodes(), lockedpvs, lockedwaterplanes, lockedwaterpvs, lockpvs_(), Log, loopi(), ivec::mask(), MAXWATERPVS, numwaterplanes, physent::o, origpvsnodes, pvsworker::testviewcell(), waterplanes, and worldroot.
VAR (maxpvsblocker , 1 , 512 , 1<< 16)
VAR (pvsleafsize , 1 , 64 , 1024)
VARF (lockpvs , 0 , 0 , 1 , lockpvs_(lockpvs!=0))
VARN (pvs , usepvs , 0 , 1 , 1)
VARN (waterpvs , usewaterpvs , 0 , 1 , 1)
VARP (pvsthreads , 0 , 0 , 16)
bool waterpvsoccluded (int height)
References curwaterpvs, lockedpvs, lockedwaterplanes, loopi(), MAXWATERPVS, numwaterplanes, and waterplanes.
Referenced by queryreflections().
Variable Documentation
volatile bool check_genpvs_progress = false static
Referenced by genpvs(), genpvs_timer(), genviewcells(), show_genpvs_progress(), and testpvs().
uchar* curpvs = nullptr static
Referenced by clearpvs(), pvsoccluded(), pvsoccludedsphere(), and setviewcell().
int curwaterpvs = 0 static
Referenced by setviewcell(), and waterpvsoccluded().
bool genpvs_canceled = false static
Referenced by pvsworker::cullpvs(), genpvs(), genviewcells(), show_genpvs_progress(), and testpvs().
uchar * lockedpvs = nullptr static
Referenced by lockpvs_(), setviewcell(), testpvs(), and waterpvsoccluded().
int lockedwaterplanes[MAXWATERPVS] static
Referenced by lockpvs_(), testpvs(), and waterpvsoccluded().
int lockedwaterpvs = 0 static
Referenced by lockpvs_(), setviewcell(), and testpvs().
int numviewcells = 0 static
Referenced by genpvs(), and pvsworker::genviewcell().
uint numwaterplanes = 0
Referenced by pvsworker::calcpvs(), clearpvs(), findwaterplanes(), loadpvs(), savepvs(), testpvs(), and waterpvsoccluded().
vector<pvsnode> origpvsnodes static
Referenced by pvsworker::calcpvs(), genpvs(), genpvsnodes(), and testpvs().
vector<pvsdata> pvs static
Referenced by clearpvs(), genpvs(), pvsworker::genviewcell(), getnumviewcells(), loadpvs(), lookupviewcell(), pvsstats(), and savepvs().
shaftbb pvsbounds static
Referenced by calcpvsbounds(), countviewcells(), and genviewcells().
vector<uchar> pvsbuf static
Referenced by clearpvs(), genpvs(), pvsworker::genviewcell(), htcmp(), hthash(), loadpvs(), lockpvs_(), pvsstats(), savepvs(), and setviewcell().
hashtable<pvsdata, int> pvscompress static
Referenced by genpvs(), and pvsworker::genviewcell().
SDL_mutex* pvsmutex = nullptr static
Referenced by genpvs(), and pvsworker::genviewcell().
vector<pvsworker *> pvsworkers static
Referenced by genpvs(), and genviewcells().
int totalviewcells = 0 static
Referenced by genpvs(), and show_genpvs_progress().
SDL_mutex* viewcellmutex = nullptr static
Referenced by genpvs(), and pvsworker::run().
vector<viewcellrequest> viewcellrequests static
Referenced by genpvs(), genviewcells(), and pvsworker::run().
viewcellnode* viewcells = nullptr static
Referenced by clearpvs(), genpvs(), loadpvs(), lookupviewcell(), and savepvs().
vector<materialsurface *> waterfalls static
Referenced by pvsworker::calcpvs(), and findwaterplanes().
struct { ... } waterplanes[MAXWATERPVS]
Referenced by pvsworker::calcpvs(), findwaterplanes(), loadpvs(), lockpvs_(), savepvs(), testpvs(), and waterpvsoccluded().