Inexor: inexor/engine/pvs.hpp File Reference
pvs.hpp File Reference
#include "inexor/shared/geom.hpp"
Functions
void clearpvs ()
bool pvsoccluded (const ivec &bbmin, const ivec &bbmax)
bool pvsoccludedsphere (const vec &center, float radius)
bool waterpvsoccluded (int height)
void setviewcell (const vec &p)
void savepvs (stream *f)
void loadpvs (stream *f, int numpvs)
int getnumviewcells ()
static bool pvsoccluded (const ivec &bborigin, int size)
Function Documentation
void clearpvs ()
References curpvs, DELETEP, lockpvs_(), numwaterplanes, pvs, pvsbuf, vector< T, MINSIZE >::setsize(), and viewcells.
Referenced by genpvs(), and resetmap().
int getnumviewcells ()
References pvs.
Referenced by gl_drawhud(), and save_world().
void loadpvs (stream * f, int numpvs)
References vector< T, MINSIZE >::advance(), stream::getlil(), loadviewcells(), loopi(), numwaterplanes, pvs, pvsbuf, stream::read(), vector< T, MINSIZE >::reserve(), viewcells, and waterplanes.
Referenced by load_world().
bool pvsoccluded (const ivec & bbmin, const ivec & bbmax)
References curpvs, and pvsoccluded().
Referenced by pvsoccluded().
static bool pvsoccluded (const ivec & bborigin, int size) inline static
References pvsoccluded().
bool pvsoccludedsphere (const vec & center, float radius)
References curpvs, and pvsoccluded().
Referenced by finddynlights().
void savepvs (stream * f)
References vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), loopi(), loopv, numwaterplanes, stream::putlil(), pvs, pvsbuf, saveviewcells(), viewcells, waterplanes, and stream::write().
Referenced by save_world().
void setviewcell (const vec & p)
References curpvs, curwaterpvs, hmap::d, pvsdata::len, lockedpvs, lockedwaterpvs, lookupviewcell(), loopi(), pvsdata::offset, and pvsbuf.
Referenced by drawcubemap(), drawminimap(), and recomputecamera().
bool waterpvsoccluded (int height)
References curwaterpvs, lockedpvs, lockedwaterplanes, loopi(), MAXWATERPVS, numwaterplanes, and waterplanes.
Referenced by queryreflections().