Inexor: inexor/model/ragdoll.cpp File Reference
ragdoll.cpp File Reference
#include <limits.h>
#include <math.h>
#include <stddef.h>
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/fpsgame/fps.hpp"
#include "inexor/model/ragdoll.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/util/legacy_time.hpp"
#include "inexor/util/random.hpp"
Functions
VAR (ragdollconstrain, 1, 5, 100)
FVAR (ragdollbodyfric, 0, 0.95f, 1)
FVAR (ragdollbodyfricscale, 0, 2, 10)
FVAR (ragdollwaterfric, 0, 0.85f, 1)
FVAR (ragdollgroundfric, 0, 0.8f, 1)
FVAR (ragdollairfric, 0, 0.996f, 1)
FVAR (ragdollunstick, 0, 10, 1e3f)
VAR (ragdollexpireoffset, 0, 1500, 30000)
VAR (ragdollwaterexpireoffset, 0, 3000, 30000)
VAR (ragdolltimestepmin, 1, 5, 50)
VAR (ragdolltimestepmax, 1, 10, 50)
FVAR (ragdollrotfric, 0, 0.85f, 1)
FVAR (ragdollrotfricstop, 0, 0.1f, 1)
FVAR (ragdolleyesmooth, 0, 0.5f, 1)
VAR (ragdolleyesmoothmillis, 1, 250, 10000)
void moveragdoll (dynent *d)
void cleanragdoll (dynent *d)
Function Documentation
void cleanragdoll (dynent * d)
References DELETEP, and dynent::ragdoll.
Referenced by game::changedplayermodel(), ai::logic(), game::parsemessages(), game::updateworld(), and dynent::~dynent().
FVAR (ragdollbodyfric , 0 , 0. 95f, 1)
FVAR (ragdollbodyfricscale , 0 , 2 , 10)
FVAR (ragdollwaterfric , 0 , 0. 85f, 1)
FVAR (ragdollgroundfric , 0 , 0. 8f, 1)
FVAR (ragdollairfric , 0 , 0. 996f, 1)
FVAR (ragdollunstick , 0 , 10 , 1e3f)
FVAR (ragdollrotfric , 0 , 0. 85f, 1)
FVAR (ragdollrotfricstop , 0 , 0. 1f, 1)
FVAR (ragdolleyesmooth , 0 , 0. 5f, 1)
void moveragdoll (dynent * d)
References vec::add(), ragdolldata::center, ragdolldata::collidemillis, curtime, ragdollskel::eye, f(), lastmillis, ragdolldata::lastmove, inexor::rpc::min(), ragdolldata::move(), vec::mul(), physent::o, ragdolldata::offset, ragdolldata::vert::pos, dynent::ragdoll, ragdolldata::skel, and ragdolldata::verts.
Referenced by ai::logic(), game::moveragdolls(), game::otherplayers(), and game::updateworld().
VAR (ragdollconstrain , 1 , 5 , 100)
VAR (ragdollexpireoffset , 0 , 1500 , 30000)
VAR (ragdollwaterexpireoffset , 0 , 3000 , 30000)
VAR (ragdolltimestepmin , 1 , 5 , 50)
VAR (ragdolltimestepmax , 1 , 10 , 50)
VAR (ragdolleyesmoothmillis , 1 , 250 , 10000)