Inexor: inexor/model/ragdoll.hpp File Reference
ragdoll.hpp File Reference
#include <algorithm>
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
Classes
struct ragdollskel
struct ragdollskel::vert
struct ragdollskel::tri
struct ragdollskel::distlimit
struct ragdollskel::rotlimit
struct ragdollskel::rotfriction
struct ragdollskel::joint
struct ragdollskel::reljoint
struct ragdolldata
struct ragdolldata::vert
Functions
void moveragdoll (dynent *d)
void cleanragdoll (dynent *d)
Class Documentation
struct ragdollskel::vert
Class Members
vec pos
float radius
float weight
struct ragdollskel::distlimit
Class Members
float maxdist
float mindist
int vert[2]
struct ragdollskel::rotlimit
Class Members
float maxangle
matrix3 middle
int tri[2]
struct ragdollskel::rotfriction
Class Members
matrix3 middle
int tri[2]
struct ragdollskel::joint
Class Members
int bone
matrix4x3 orient
int tri
int vert[3]
float weight
struct ragdollskel::reljoint
Class Members
int bone
int parent
Function Documentation
void cleanragdoll (dynent * d)
References DELETEP, and dynent::ragdoll.
Referenced by game::changedplayermodel(), ai::logic(), game::parsemessages(), game::updateworld(), and dynent::~dynent().
void moveragdoll (dynent * d)
References vec::add(), ragdolldata::center, ragdolldata::collidemillis, curtime, ragdollskel::eye, f(), lastmillis, ragdolldata::lastmove, inexor::rpc::min(), ragdolldata::move(), vec::mul(), physent::o, ragdolldata::offset, ragdolldata::vert::pos, dynent::ragdoll, ragdolldata::skel, and ragdolldata::verts.
Referenced by ai::logic(), game::moveragdolls(), game::otherplayers(), and game::updateworld().