Inexor: inexor/engine/rendertext.hpp File Reference
rendertext.hpp File Reference
#include <math.h>
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_vector.hpp"
Classes
struct font
struct font::charinfo
Macros
#define FONTH (curfont->scale)
#define FONTW (FONTH/2)
#define MINRESW 640
#define MINRESH 480
Functions
bool setfont (const char *name)
void pushfont ()
bool popfont ()
void gettextres (int &w, int &h)
void draw_text (const char *str, int left, int top, int r=255, int g=255, int b=255, int a=255, int cursor=-1, int maxwidth=-1)
void draw_textf (const char *fstr, int left, int top,...) PRINTFARGS(1
void float text_widthf (const char *str)
void text_boundsf (const char *str, float &width, float &height, int maxwidth=-1)
int text_visible (const char *str, float hitx, float hity, int maxwidth)
void text_posf (const char *str, int cursor, float &cx, float &cy, int maxwidth)
static int text_width (const char *str)
static void text_bounds (const char *str, int &width, int &height, int maxwidth=-1)
static void text_pos (const char *str, int cursor, int &cx, int &cy, int maxwidth)
Variables
font * curfont
const matrix4x3 * textmatrix
Class Documentation
struct font::charinfo
Class Members
short advance
short h
short offsetx
short offsety
short tex
short w
short x
short y
Macro Definition Documentation
#define FONTH (curfont->scale)
Referenced by gui::adjustscale(), gui::autotab(), gui::button_(), consolebox(), debugparticles(), editor::draw(), draw_text(), recorder::drawhud(), gui::end(), gui::field_(), gl_drawhud(), gui::image(), editor::key(), gui::line_(), gui::modelpreview(), gui::playerpreview(), gui::prefabpreview(), gui::progress(), renderbackground(), renderconsole(), meterrenderer::renderpart(), renderprogress(), gui::separator(), gui::shouldtab(), gui::slider(), gui::space(), gui::strut(), gui::tab(), text_boundsf(), gui::textbox(), and gui::texture().
#define FONTW (FONTH/2)
Referenced by editor::draw(), draw_text(), gui::field_(), gui::space(), gui::strut(), and gui::textbox().
#define MINRESH 480
Referenced by gettextres().
#define MINRESW 640
Referenced by gettextres().
Function Documentation
void draw_text (const char * str, int left, int top, int r = 255, int g = 255, int b = 255, int a = 255, int cursor = -1, int maxwidth = -1)
References gle::begin(), gle::color(), draw_char(), gle::end(), FONTH, FONTW, Texture::id, font::texs, TEXTEND, TEXTSKELETON, totalmillis, and xtraverts.
Referenced by debugparticles(), editor::draw(), draw_textf(), game::captureclientmode::drawblips(), drawconlines(), game::bombclientmode::drawhud(), game::drawhudannounce(), game::gameplayhud(), gl_drawhud(), renderbackground(), rendercommand(), textrenderer::renderpart(), renderprogress(), gui::text_(), and gui::textbox().
void draw_textf (const char * fstr, int left, int top, ...)
void gettextres (int & w, int & h)
References MINRESH, and MINRESW.
Referenced by recorder::drawhud(), gl_drawhud(), renderbackground(), and renderprogress().
bool popfont ()
References vector< T, MINSIZE >::empty(), and vector< T, MINSIZE >::pop().
Referenced by game::captureclientmode::drawhud().
void pushfont ()
References vector< T, MINSIZE >::add().
Referenced by game::captureclientmode::drawhud().
bool setfont (const char * name)
References hashbase< hashnameset< T >, T, const char *, T >::access(), and f().
Referenced by game::captureclientmode::drawhud(), and main().
static void text_bounds (const char * str, int & width, int & height, int maxwidth = -1) inline static
References text_boundsf().
Referenced by editor::draw(), game::captureclientmode::drawblips(), drawconlines(), game::bombclientmode::drawhud(), game::captureclientmode::drawhud(), game::drawhudannounce(), gui::field_(), game::gameplayhud(), gl_drawhud(), editor::hit(), editor::key(), editor::limitscrolly(), renderbackground(), rendercommand(), and gui::textbox().
void text_boundsf (const char * str, float & width, float & height, int maxwidth = -1)
References FONTH, TEXTLINE, and TEXTSKELETON.
Referenced by text_bounds(), and text_widthf().
static void text_pos (const char * str, int cursor, int & cx, int & cy, int maxwidth) inline static
References text_posf().
Referenced by editor::draw(), and editor::key().
void text_posf (const char * str, int cursor, float & cx, float & cy, int maxwidth)
References TEXTEND, and TEXTSKELETON.
Referenced by text_pos().
int text_visible (const char * str, float hitx, float hity, int maxwidth)
References TEXTSKELETON.
Referenced by editor::hit(), and editor::key().
static int text_width (const char * str) inline static
References text_widthf().
Referenced by gui::button_(), renderbackground(), textrenderer::renderpart(), renderprogress(), gui::slider(), and gui::tab().
void float text_widthf (const char * str)
References text_boundsf().
Referenced by tabify(), and text_width().
Variable Documentation
font* curfont
const matrix4x3* textmatrix
Referenced by textrenderer::renderpart().