Inexor: inexor/engine/rendersky.hpp File Reference
rendersky.hpp File Reference
Functions
void drawskybox (int farplane, bool limited)
bool limitsky ()
Variables
int explicitsky
double skyarea
Function Documentation
void drawskybox (int farplane, bool limited)
References camera1, cammatrix, cloudoverlay, clouds, gle::color(), drawenvbox(), drawenvoverlay(), drawfogdome(), drawskylimits(), drawskyoutline(), drawtex, editmode, f(), fading, glaring, vec::hexcolor(), insideworld(), lastmillis, LOCALPARAM, inexor::rpc::max(), inexor::rpc::min(), vtxarray::next, physent::o, OCCLUDE_BB, projmatrix, RAD, reflecting, reflectz, refracting, renderedskyclip, renderedskyfaces, matrix4::rotate_around_z(), SETSHADER, matrix4::settranslation(), sky, visibleva, worldsize, and yawskyfaces().
Referenced by drawcubemap(), drawglare(), drawreflection(), and gl_drawframe().
bool limitsky ()
References editmode, explicitsky, skyarea, and worldsize.
Referenced by drawcubemap(), and gl_drawframe().
Variable Documentation
int explicitsky
Referenced by limitsky(), and octarender().
double skyarea
Referenced by limitsky(), and octarender().