Inexor: inexor/engine/rendertarget.hpp File Reference
rendertarget.hpp File Reference
#include <SDL_opengl.h>
#include <math.h>
#include <string.h>
#include <algorithm>
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/texture/texsettings.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
#include "inexor/network/SharedVar.hpp"
Classes
struct rendertarget
Macros
#define BLURTILES 32
#define BLURTILEMASK (0xFFFFFFFFU>>(32-BLURTILES))
Functions
void screenquad (float sw, float sh)
void hudquad (float x, float y, float w, float h, float tx, float ty, float tw, float th)
Variables
SharedVar< int > rtsharefb
SharedVar< int > rtscissor
SharedVar< int > blurtile
Macro Definition Documentation
#define BLURTILEMASK (0xFFFFFFFFU>>(32-BLURTILES))
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::debugblurtiles(), and rendertarget::rendertiles().
#define BLURTILES 32
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::debugblurtiles(), and rendertarget::rendertiles().
Function Documentation
void hudquad (float x, float y, float w, float h, float tx, float ty, float tw, float th)
References HUDQUAD.
Referenced by rendertarget::debug(), draw_crosshair(), draw_g3d_cursor(), drawdamagescreen(), gl_rendercef(), and gl_rendercefmouse().
void screenquad (float sw, float sh)
References screenquad(), and setscreentexcoord().
Referenced by rendertarget::rendertiles().
Variable Documentation
SharedVar<int> blurtile
SharedVar<int> rtscissor
Referenced by shadowmaptexture::dorender().
SharedVar<int> rtsharefb
Referenced by gl_checkextensions().