Inexor: inexor/engine/rendertext.cpp File Reference
rendertext.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <algorithm>
#include "SDL_opengl.h"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/rendertext.hpp"
#include "inexor/io/Error.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/util/legacy_time.hpp"
Macros
#define FONTTAB (4*FONTW)
#define TEXTTAB(x) ((int((x)/FONTTAB)+1.0f)*FONTTAB)
#define TEXTSKELETON
#define TEXTWORDSKELETON
#define TEXTEND(cursor) if(cursor >= i) { do { TEXTINDEX(cursor); } while(0); }
#define TEXTINDEX(idx)
#define TEXTWHITE(idx) if(y+FONTH > hity && x >= hitx) return idx;
#define TEXTLINE(idx) if(y+FONTH > hity) return idx;
#define TEXTCOLOR(idx)
#define TEXTCHAR(idx) x += cw; TEXTWHITE(idx)
#define TEXTWORD TEXTWORDSKELETON
#define TEXTINDEX(idx) if(idx == cursor) { cx = x; cy = y; break; }
#define TEXTWHITE(idx)
#define TEXTLINE(idx)
#define TEXTCOLOR(idx)
#define TEXTCHAR(idx) x += cw;
#define TEXTWORD TEXTWORDSKELETON if(i >= cursor) break;
#define TEXTINDEX(idx)
#define TEXTWHITE(idx)
#define TEXTLINE(idx) if(x > width) width = x;
#define TEXTCOLOR(idx)
#define TEXTCHAR(idx) x += cw;
#define TEXTWORD x += w;
#define TEXTINDEX(idx) if(idx == cursor) { cx = x; cy = y; }
#define TEXTWHITE(idx)
#define TEXTLINE(idx)
#define TEXTCOLOR(idx) if(usecolor) { int nextpos = 0; text_color(&str[idx], a, nextpos); idx += nextpos;}
#define TEXTCHAR(idx) draw_char(tex, c, left+x, top+y, scale); x += cw;
#define TEXTWORD TEXTWORDSKELETON
Functions
void newfont (char *name, char *tex, int *defaultw, int *defaulth)
void fontoffset (char *c)
void fontscale (int *scale)
void fonttex (char *s)
void fontchar (int *x, int *y, int *w, int *h, int *offsetx, int *offsety, int *advance)
void fontskip (int *n)
COMMANDN (font, newfont,"ssii")
COMMAND (fontoffset,"s")
COMMAND (fontscale,"i")
COMMAND (fonttex,"s")
COMMAND (fontchar,"iiiiiii")
COMMAND (fontskip,"i")
void fontalias (const char *dst, const char *src)
COMMAND (fontalias,"ss")
bool setfont (const char *name)
void pushfont ()
bool popfont ()
void gettextres (int &w, int &h)
float text_widthf (const char *str)
void tabify (const char *str, int *numtabs)
COMMAND (tabify,"si")
void draw_textf (const char *fstr, int left, int top,...)
static float draw_char (Texture *&tex, int c, float x, float y, float scale)
static void text_color (const char *curstring, int a, int &skipamount)
int text_visible (const char *str, float hitx, float hity, int maxwidth)
void text_posf (const char *str, int cursor, float &cx, float &cy, int maxwidth)
void text_boundsf (const char *str, float &width, float &height, int maxwidth)
void draw_text (const char *str, int left, int top, int r, int g, int b, int a, int cursor, int maxwidth)
void reloadfonts ()
Variables
static hashnameset< font > fonts
static font * fontdef = nullptr
static int fontdeftex = 0
font * curfont = nullptr
int curfonttex = 0
static vector< font * > fontstack
const matrix4x3 * textmatrix = nullptr
Macro Definition Documentation
#define FONTTAB (4*FONTW)
Referenced by tabify().
#define TEXTCHAR (idx) x += cw; TEXTWHITE(idx)
#define TEXTCHAR (idx) x += cw;
#define TEXTCHAR (idx) x += cw;
#define TEXTCHAR (idx) draw_char(tex, c, left+x, top+y, scale); x += cw;
#define TEXTCOLOR (idx)
#define TEXTCOLOR (idx)
#define TEXTCOLOR (idx)
#define TEXTCOLOR (idx) if(usecolor) { int nextpos = 0; text_color(&str[idx], a, nextpos); idx += nextpos;}
#define TEXTEND (cursor) if(cursor >= i) { do { TEXTINDEX(cursor); } while(0); }
Referenced by draw_text(), and text_posf().
#define TEXTINDEX (idx)
#define TEXTINDEX (idx) if(idx == cursor) { cx = x; cy = y; break; }
#define TEXTINDEX (idx)
#define TEXTINDEX (idx) if(idx == cursor) { cx = x; cy = y; }
#define TEXTLINE (idx) if(y+FONTH > hity) return idx;
Referenced by text_boundsf().
#define TEXTLINE (idx)
#define TEXTLINE (idx) if(x > width) width = x;
#define TEXTLINE (idx)
#define TEXTSKELETON
Referenced by draw_text(), text_boundsf(), text_posf(), and text_visible().
#define TEXTTAB (x) ((int((x)/FONTTAB)+1.0f)*FONTTAB)
Referenced by tabify().
#define TEXTWHITE (idx) if(y+FONTH > hity && x >= hitx) return idx;
#define TEXTWHITE (idx)
#define TEXTWHITE (idx)
#define TEXTWHITE (idx)
#define TEXTWORD TEXTWORDSKELETON
#define TEXTWORD TEXTWORDSKELETON if(i >= cursor) break;
#define TEXTWORD x += w;
#define TEXTWORD TEXTWORDSKELETON
#define TEXTWORDSKELETON
Value:
for(; j <= i; j++)\
                {\
                    TEXTINDEX(j)\
                    int c = uchar(str[j]);\
                    if(c=='\x1b') { if(str[j+1]) { j++; TEXTCOLOR(j) }}\
                    else { float cw = scale*curfont->chars[c-curfont->charoffset].advance; TEXTCHAR(j) }\
                }
Function Documentation
COMMAND (fontoffset , "s")
COMMAND (fontscale , "i")
COMMAND (fonttex , "s")
COMMAND (fontchar , "iiiiiii")
COMMAND (fontskip , "i")
COMMAND (fontalias , "ss")
COMMAND (tabify , "si")
COMMANDN (font , newfont , "ssii")
static float draw_char (Texture *& tex, int c, float x, float y, float scale) static
References font::charinfo::advance, gle::attrib(), font::charoffset, font::chars, gle::end(), font::charinfo::h, Texture::id, font::charinfo::offsetx, font::charinfo::offsety, font::charinfo::tex, font::texs, matrix4x3::transform(), font::charinfo::w, font::charinfo::x, Texture::xs, xtraverts, font::charinfo::y, and Texture::ys.
Referenced by draw_text().
void draw_text (const char * str, int left, int top, int r, int g, int b, int a, int cursor, int maxwidth)
References gle::begin(), gle::color(), draw_char(), gle::end(), FONTH, FONTW, Texture::id, font::texs, TEXTEND, TEXTSKELETON, totalmillis, and xtraverts.
Referenced by debugparticles(), editor::draw(), draw_textf(), game::captureclientmode::drawblips(), drawconlines(), game::bombclientmode::drawhud(), game::drawhudannounce(), game::gameplayhud(), gl_drawhud(), renderbackground(), rendercommand(), textrenderer::renderpart(), renderprogress(), gui::text_(), and gui::textbox().
void draw_textf (const char * fstr, int left, int top, ...)
References defvformatstring, and draw_text().
Referenced by game::bombclientmode::drawhud(), game::ctfclientmode::drawhud(), game::collectclientmode::drawhud(), game::captureclientmode::drawhud(), recorder::drawhud(), game::drawhudicons(), and gl_drawhud().
void fontalias (const char * dst, const char * src)
References hashbase< hashnameset< T >, T, const char *, T >::access(), font::charoffset, font::chars, hmap::d, font::defaulth, font::defaultw, fontdeftex, vector< T, MINSIZE >::length(), font::name, newstring(), font::scale, and font::texs.
void fontchar (int * x, int * y, int * w, int * h, int * offsetx, int * offsety, int * advance)
References font::charinfo::advance, font::chars, font::defaulth, font::defaultw, fontdeftex, font::charinfo::h, font::charinfo::offsetx, font::charinfo::offsety, font::charinfo::tex, font::charinfo::w, font::charinfo::x, and font::charinfo::y.
void fontoffset (char * c)
References font::charoffset.
void fontscale (int * scale)
References font::defaulth, and font::scale.
void fontskip (int * n)
References font::charinfo::advance, font::chars, font::charinfo::h, loopi(), inexor::rpc::max(), font::charinfo::offsetx, font::charinfo::offsety, font::charinfo::tex, font::charinfo::w, font::charinfo::x, and font::charinfo::y.
void fonttex (char * s)
References vector< T, MINSIZE >::add(), fontdeftex, getcurexecdir(), vector< T, MINSIZE >::length(), loopv, makerelpath(), notexture, anonymous_namespace{utilTest.cpp}::t(), font::texs, and textureload().
void gettextres (int & w, int & h)
References MINRESH, and MINRESW.
Referenced by recorder::drawhud(), gl_drawhud(), renderbackground(), and renderprogress().
void newfont (char * name, char * tex, int * defaultw, int * defaulth)
References vector< T, MINSIZE >::add(), font::charoffset, font::chars, font::defaulth, font::defaultw, f(), fontdeftex, getcurexecdir(), vector< T, MINSIZE >::last(), makerelpath(), font::name, newstring(), notexture, font::scale, vector< T, MINSIZE >::shrink(), font::texs, and textureload().
bool popfont ()
References vector< T, MINSIZE >::empty(), and vector< T, MINSIZE >::pop().
Referenced by game::captureclientmode::drawhud().
void pushfont ()
References vector< T, MINSIZE >::add().
Referenced by game::captureclientmode::drawhud().
void reloadfonts ()
References enumerate, f(), fatal(), loopv, and reloadtexture().
Referenced by resetgl().
bool setfont (const char * name)
References hashbase< hashnameset< T >, T, const char *, T >::access(), and f().
Referenced by game::captureclientmode::drawhud(), and main().
void tabify (const char * str, int * numtabs)
References FONTTAB, inexor::rpc::max(), newstring(), stringret(), text_widthf(), TEXTTAB, and anonymous_namespace{utilTest.cpp}::tstr().
void text_boundsf (const char * str, float & width, float & height, int maxwidth)
References FONTH, TEXTLINE, and TEXTSKELETON.
Referenced by text_bounds(), and text_widthf().
static void text_color (const char * curstring, int a, int & skipamount) static
References gle::color(), gle::end(), and xtraverts.
void text_posf (const char * str, int cursor, float & cx, float & cy, int maxwidth)
References TEXTEND, and TEXTSKELETON.
Referenced by text_pos().
int text_visible (const char * str, float hitx, float hity, int maxwidth)
References TEXTSKELETON.
Referenced by editor::hit(), and editor::key().
float text_widthf (const char * str)
References text_boundsf().
Referenced by tabify(), and text_width().
Variable Documentation
font* curfont = nullptr
int curfonttex = 0
font* fontdef = nullptr static
int fontdeftex = 0 static
Referenced by fontalias(), fontchar(), fonttex(), and newfont().
hashnameset<font> fonts static
vector<font *> fontstack static
const matrix4x3* textmatrix = nullptr
Referenced by textrenderer::renderpart().