Inexor: inexor/model/rendermodel.cpp File Reference
rendermodel.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <math.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include <string>
#include "SDL_opengl.h"
#include "inexor/engine/blob.hpp"
#include "inexor/engine/dynlight.hpp"
#include "inexor/engine/glare.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/lightmap.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/pvs.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/shadowmap.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/fpsgame/fps.hpp"
#include "inexor/fpsgame/player.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/filesystem/mediadirs.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/model/model.hpp"
#include "inexor/model/rendermodel.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_hash.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_unicode.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/legacy/menus.hpp"
#include "inexor/util/legacy_time.hpp"
#include "inexor/model/animmodel.hpp"
#include "inexor/model/ragdoll.hpp"
#include "inexor/model/skelmodel.hpp"
#include "inexor/model/iqm.hpp"
#include "inexor/model/md2.hpp"
#include "inexor/model/md3.hpp"
#include "inexor/model/md5.hpp"
#include "inexor/model/obj.hpp"
#include "inexor/model/smd.hpp"
Classes
struct batchedmodel
struct modelbatch
struct transparentmodel
Macros
#define MODELTYPE(modeltype, modelclass)
#define checkmdl if(!loadingmodel) { Log.std->error("not loading a model"); return; }
#define checkragdoll
#define ifnoload(tex, path) if((tex = textureload(path, 0, true, false))==notexture)
#define tryload(tex, prefix, cmd, name)
Functions
void loadskin (const char *dir, const char *altdir, Texture *&skin, Texture *&masks)
void preloadmodelshaders (bool force)
VAR (oqdynent, 0, 1, 1)
VAR (animationinterpolationtime, 0, 150, 1000)
VARFP (envmapmodels, 0, 1, 1, preloadmodelshaders(true))
VARFP (bumpmodels, 0, 1, 1, preloadmodelshaders(true))
VARP (fullbrightmodels, 0, 0, 200)
VARP (gpuskel, 0, 1, 1)
VAR (maxskelanimdata, 1, 192, 0)
VAR (testtags, 0, 0, 1)
static model *__cdecl * modeltypes (const char *)
static int addmodeltype (int type, model *(__cdecl *loader)(const char *))
MODELTYPE (MDL_MD2, md2)
MODELTYPE (MDL_MD3, md3)
MODELTYPE (MDL_MD5, md5)
MODELTYPE (MDL_OBJ, obj)
MODELTYPE (MDL_SMD, smd)
MODELTYPE (MDL_IQM, iqm)
void mdlcullface (int *cullface)
COMMAND (mdlcullface,"i")
void mdlcollide (int *collide)
COMMAND (mdlcollide,"i")
void mdlellipsecollide (int *collide)
COMMAND (mdlellipsecollide,"i")
void mdlspec (int *percent)
COMMAND (mdlspec,"i")
void mdlambient (int *percent)
COMMAND (mdlambient,"i")
void mdlalphatest (float *cutoff)
COMMAND (mdlalphatest,"f")
void mdlalphablend (int *blend)
COMMAND (mdlalphablend,"i")
void mdlalphadepth (int *depth)
COMMAND (mdlalphadepth,"i")
void mdldepthoffset (int *offset)
COMMAND (mdldepthoffset,"i")
void mdlglow (int *percent, int *delta, float *pulse)
COMMAND (mdlglow,"iif")
void mdlglare (float *specglare, float *glowglare)
COMMAND (mdlglare,"ff")
void mdlenvmap (float *envmapmax, float *envmapmin, char *envmap)
COMMAND (mdlenvmap,"ffs")
void mdlfullbright (float *fullbright)
COMMAND (mdlfullbright,"f")
void mdlshader (char *shader)
COMMAND (mdlshader,"s")
void mdlspin (float *yaw, float *pitch)
COMMAND (mdlspin,"ff")
void mdlscale (int *percent)
COMMAND (mdlscale,"i")
void mdltrans (float *x, float *y, float *z)
COMMAND (mdltrans,"fff")
void mdlyaw (float *angle)
COMMAND (mdlyaw,"f")
void mdlpitch (float *angle)
COMMAND (mdlpitch,"f")
void mdlshadow (int *shadow)
COMMAND (mdlshadow,"i")
void mdlbb (float *rad, float *h, float *eyeheight)
COMMAND (mdlbb,"fff")
void mdlextendbb (float *x, float *y, float *z)
COMMAND (mdlextendbb,"fff")
void mdlname ()
COMMAND (mdlname,"")
void rdvert (float *x, float *y, float *z, float *radius)
COMMAND (rdvert,"ffff")
void rdeye (int *v)
COMMAND (rdeye,"i")
void rdtri (int *v1, int *v2, int *v3)
COMMAND (rdtri,"iii")
void rdjoint (int *n, int *t, int *v1, int *v2, int *v3)
COMMAND (rdjoint,"iibbb")
void rdlimitdist (int *v1, int *v2, float *mindist, float *maxdist)
COMMAND (rdlimitdist,"iiff")
void rdlimitrot (int *t1, int *t2, float *maxangle, float *qx, float *qy, float *qz, float *qw)
COMMAND (rdlimitrot,"iifffff")
void rdanimjoints (int *on)
COMMAND (rdanimjoints,"i")
void mmodel (char *name)
void mapmodelcompat (int *rad, int *h, int *tex, char *name, char *shadow)
void mapmodelreset (int *n)
mapmodelinfo * getmminfo (int i)
const char * mapmodelname (int i)
COMMAND (mmodel,"s")
COMMANDN (mapmodel, mapmodelcompat,"iiiss")
COMMAND (mapmodelreset,"i")
ICOMMAND (mapmodelname,"i",(int *index),{result(mapmodels.inrange(*index)?mapmodels[*index].name:"");})
ICOMMAND (nummapmodels,"",(),{intret(mapmodels.length());})
void preloadmodel (const char *name)
void flushpreloadedmodels (bool msg)
void preloadusedmapmodels (bool msg, bool bih)
model * loadmodel (const char *name, int i, bool msg)
void clear_mdls ()
void cleanupmodels ()
void clearmodel (char *name)
COMMAND (clearmodel,"s")
bool modeloccluded (const vec &center, float radius)
VAR (showboundingbox, 0, 0, 2)
void render2dbox (vec &o, float x, float y, float z)
void render3dbox (vec &o, float tofloor, float toceil, float xradius, float yradius=0)
void renderellipse (vec &o, float xradius, float yradius, float yaw)
void startmodelbatches ()
modelbatch & addbatchedmodel (model *m)
void renderbatchedmodel (model *m, batchedmodel &b)
static bool sorttransparentmodels (const transparentmodel &x, const transparentmodel &y)
void endmodelbatches ()
void startmodelquery (occludequery *query)
void endmodelquery ()
VAR (maxmodelradiusdistance, 10, 200, 1000)
static void enablecullmodelquery ()
static void rendercullmodelquery (model *m, dynent *d, const vec &center, float radius)
static void disablecullmodelquery ()
static int cullmodel (model *m, const vec &center, float radius, int flags, dynent *d=nullptr, bool shadow=false)
void rendermodel (entitylight *light, const char *mdl, int anim, const vec &o, float yaw, float pitch, int flags, dynent *d, modelattach *a, int basetime, int basetime2, float trans)
void abovemodel (vec &o, const char *mdl)
bool matchanim (const char *name, const char *pattern)
void findanims (const char *pattern, vector< int > &anims)
ICOMMAND (findanims,"s",(char *name),{vector< int > anims;findanims(name, anims);vector< char > buf;string num;loopv(anims){formatstring(num,"%d", anims[i]);if(i > 0) buf.add(' ');buf.put(num, strlen(num));}buf.add('\0');result(buf.getbuf());})
VAR (animoverride,-1, 0, NUMANIMS-1)
VAR (testanims, 0, 0, 1)
VAR (testpitch,-90, 0, 90)
void renderclient (dynent *d, const char *mdlname, modelattach *attachments, int hold, int attack, int attackdelay, int lastaction, int lastpain, float fade, bool ragdoll)
void setbbfrommodel (dynent *d, const char *mdl)
Variables
model * loadingmodel = nullptr
vector< mapmodelinfo > mapmodels
hashnameset< model * > models
vector< const char * > preloadmodels
vector< std::string > missingmodels
static vector< modelbatch * > batches
static vector< modelattach > modelattached
static int numbatches = -1
static occludequery * modelquery = nullptr
Class Documentation
struct batchedmodel
Class Members
int anim
int attached
int basetime
int basetime2
vec color
dynent * d
vec dir
int flags
float pitch
vec pos
occludequery * query
float transparent
float yaw
struct modelbatch
Class Members
vector< batchedmodel > batched
int flags
model * m
struct transparentmodel
Class Members
batchedmodel * batched
float dist
model * m
Macro Definition Documentation
#define checkmdl if(!loadingmodel) { Log.std->error("not loading a model"); return; }
Referenced by mdlalphablend(), mdlalphadepth(), mdlalphatest(), mdlambient(), mdlbb(), mdlcollide(), mdlcullface(), mdldepthoffset(), mdlellipsecollide(), mdlenvmap(), mdlextendbb(), mdlfullbright(), mdlglare(), mdlglow(), mdlname(), mdlpitch(), mdlscale(), mdlshader(), mdlshadow(), mdlspec(), mdlspin(), mdltrans(), and mdlyaw().
#define checkragdoll
Value:
if(!loadingmodel->skeletal()) { Log.std->error("not loading a skeletal model"); return; } \
    skelmodel *m = (skelmodel *)loadingmodel; \
    if(m->parts.empty()) return; \
    skelmodel::skelmeshgroup *meshes = (skelmodel::skelmeshgroup *)m->parts.last()->meshes; \
    if(!meshes) return; \
    skelmodel::skeleton *skel = meshes->skel; \
    if(!skel->ragdoll) skel->ragdoll = new ragdollskel; \
    ragdollskel *ragdoll = skel->ragdoll; \
    if(ragdoll->loaded) return;
Referenced by rdanimjoints(), rdeye(), rdjoint(), rdlimitdist(), rdlimitrot(), rdtri(), and rdvert().
#define ifnoload (tex, path) if((tex = textureload(path, 0, true, false))==notexture)
#define MODELTYPE (modeltype, modelclass)
Value:
static model *__loadmodel__##modelclass(const char *filename) \
{ \
    return new modelclass(filename); \
} \
UNUSED static int __dummy__##modelclass = addmodeltype((modeltype), __loadmodel__##modelclass);
#define tryload (tex, prefix, cmd, name)
Value:
ifnoload(tex, makerelpath(mdir, name ".jpg", prefix, cmd)) \
    { \
        ifnoload(tex, makerelpath(mdir, name ".png", prefix, cmd)) \
        { \
            ifnoload(tex, makerelpath(maltdir, name ".jpg", prefix, cmd)) \
            { \
                ifnoload(tex, makerelpath(maltdir, name ".png", prefix, cmd)) return; \
            } \
        } \
    }
Referenced by loadskin().
Function Documentation
void abovemodel (vec & o, const char * mdl)
References model::above(), and loadmodel().
Referenced by game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), game::collectclientmode::setup(), and game::captureclientmode::setup().
modelbatch& addbatchedmodel (model * m)
References vector< T, MINSIZE >::add(), model::batch, modelbatch::batched, modelbatch::flags, vector< T, MINSIZE >::length(), modelbatch::m, numbatches, and vector< T, MINSIZE >::setsize().
Referenced by rendermodel().
static int addmodeltype (int type, model * __cdecl *loader)(const char *) static
References modeltypes().
void cleanupmodels ()
References model::cleanup(), and enumerate.
Referenced by resetgl().
void clear_mdls ()
References enumerate.
Referenced by cleanup().
void clearmodel (char * name)
References hashbase< hashnameset< T >, T, const char *, T >::access(), Log, loopv, hashbase< hashnameset< T >, T, const char *, T >::remove(), and inexor::util::log_manager::std.
COMMAND (mdlcullface , "i")
COMMAND (mdlcollide , "i")
COMMAND (mdlellipsecollide , "i")
COMMAND (mdlspec , "i")
COMMAND (mdlambient , "i")
COMMAND (mdlalphatest , "f")
COMMAND (mdlalphablend , "i")
COMMAND (mdlalphadepth , "i")
COMMAND (mdldepthoffset , "i")
COMMAND (mdlglow , "iif")
COMMAND (mdlglare , "ff")
COMMAND (mdlenvmap , "ffs")
COMMAND (mdlfullbright , "f")
COMMAND (mdlshader , "s")
COMMAND (mdlspin , "ff")
COMMAND (mdlscale , "i")
COMMAND (mdltrans , "fff")
COMMAND (mdlyaw , "f")
COMMAND (mdlpitch , "f")
COMMAND (mdlshadow , "i")
COMMAND (mdlbb , "fff")
COMMAND (mdlextendbb , "fff")
COMMAND (mdlname , "")
COMMAND (rdvert , "ffff")
COMMAND (rdeye , "i")
COMMAND (rdtri , "iii")
COMMAND (rdjoint , "iibbb")
COMMAND (rdlimitdist , "iiff")
COMMAND (rdlimitrot , "iifffff")
COMMAND (rdanimjoints , "i")
COMMAND (mmodel , "s")
COMMAND (mapmodelreset , "i")
COMMAND (clearmodel , "s")
COMMANDN (mapmodel , mapmodelcompat , "iiiss")
static int cullmodel (model * m, const vec & center, float radius, int flags, dynent * d = nullptr, bool shadow = false) inline static
References addshadowmapcaster(), camera1, checkquery(), hmap::d, vec::dist(), fogging, isfoggedsphere(), isshadowmapcaster(), MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_QUERY, MDL_CULL_VFC, modeloccluded(), physent::o, OCCLUDE_BB, OCCLUDE_PARENT, reflectdist, reflecting, reflectz, refractfog, refracting, and shadowmapping.
Referenced by rendermodel().
static void disablecullmodelquery () inline static
References endbb().
Referenced by rendermodel().
static void enablecullmodelquery () inline static
References startbb().
Referenced by rendermodel().
void endmodelbatches ()
References vector< T, MINSIZE >::add(), modelbatch::batched, transparentmodel::batched, BLOB_DYNAMIC, BLOB_STATIC, model::boundbox(), camera1, ragdolldata::center, batchedmodel::d, vec::dist(), transparentmodel::dist, vector< T, MINSIZE >::empty(), endquery, model::endrender(), batchedmodel::flags, modelbatch::flags, flushblobs(), vector< T, MINSIZE >::length(), loopi(), loopv, loopvj, modelbatch::m, transparentmodel::m, inexor::rpc::max(), MDL_CULL_VFC, MDL_DYNSHADOW, MDL_GHOST, MDL_SHADOW, physent::o, occludequery::owner, batchedmodel::pos, batchedmodel::query, physent::radius, dynent::ragdoll, renderbatchedmodel(), renderblob(), shadowmapping, vector< T, MINSIZE >::sort(), sorttransparentmodels(), startquery, model::startrender(), and batchedmodel::transparent.
Referenced by game::rendergame(), rendermapmodels(), and renderreflectedmapmodels().
void endmodelquery ()
References batchedmodel::attached, modelbatch::batched, vector< T, MINSIZE >::empty(), endquery, model::endrender(), occludequery::fragments, vector< T, MINSIZE >::last(), vector< T, MINSIZE >::length(), loopi(), modelbatch::m, inexor::rpc::min(), modelquery, vector< T, MINSIZE >::pop(), batchedmodel::query, renderbatchedmodel(), vector< T, MINSIZE >::setsize(), startquery, and model::startrender().
Referenced by rendermapmodels().
void findanims (const char * pattern, vector< int > & anims)
References vector< T, MINSIZE >::add(), animnames, loopi(), and matchanim().
Referenced by guimodelpreview(), vertcommands< MDL >::setanim(), and skelcommands< MDL >::setanim().
void flushpreloadedmodels (bool msg)
References vector< T, MINSIZE >::deletearrays(), vector< T, MINSIZE >::length(), loadmodel(), loadprogress, Log, loopv, model::preloadmeshes(), and inexor::util::log_manager::std.
Referenced by load_world().
mapmodelinfo* getmminfo (int i)
References vector< T, MINSIZE >::inrange().
Referenced by preloadusedmapmodels(), and rendermapmodel().
ICOMMAND (mapmodelname , "i" , (int *index) , {result(mapmodels.inrange(*index)?mapmodels[*index].name:"");})
ICOMMAND (nummapmodels , "" , () , {intret(mapmodels.length());})
ICOMMAND (findanims , "s" , (char *name) , {vector< int > anims;findanims(name, anims);vector< char > buf;string num;loopv(anims){formatstring(num,"%d", anims[i]);if(i > 0) buf.add(' ');buf.put(num, strlen(num));}buf.add('\0');result(buf.getbuf());})
model* loadmodel (const char * name, int i, bool msg)
References hashbase< hashnameset< T >, T, const char *, T >::access(), vector< T, MINSIZE >::add(), defformatstring, DELETEP, vector< T, MINSIZE >::find(), vector< T, MINSIZE >::inrange(), lightmapping, model::load(), loadprogress, loopi(), mapmodelinfo::m, modeldir, modeltypes(), mapmodelinfo::name, model::name, NUMMODELTYPES, model::preloadshaders(), and renderprogress().
Referenced by abovemodel(), entselectionbox(), flushpreloadedmodels(), getentboundingbox(), lightent(), loadmapmodel(), gui::modelpreview(), preloadusedmapmodels(), rendermodel(), and setbbfrommodel().
void loadskin (const char * dir, const char * altdir, Texture *& skin, Texture *& masks)
References defformatstring, modeldir, notexture, and tryload.
Referenced by md2::load(), md3::loaddefaultparts(), and obj::loaddefaultparts().
void mapmodelcompat (int * rad, int * h, int * tex, char * name, char * shadow)
References mmodel().
const char* mapmodelname (int i)
References vector< T, MINSIZE >::inrange().
Referenced by entities::entmodel(), game::movable::movable(), entities::preloadentities(), and game::rendermovables().
void mapmodelreset (int * n)
References game::allowedittoggle(), identflags, IDF_OVERRIDDEN, vector< T, MINSIZE >::length(), and vector< T, MINSIZE >::shrink().
bool matchanim (const char * name, const char * pattern)
References iscubespace().
Referenced by findanims().
void mdlalphablend (int * blend)
References checkmdl, and model::setalphablend().
void mdlalphadepth (int * depth)
References model::alphadepth, and checkmdl.
void mdlalphatest (float * cutoff)
References checkmdl, f(), inexor::rpc::max(), inexor::rpc::min(), and model::setalphatest().
void mdlambient (int * percent)
References checkmdl, and model::setambient().
void mdlbb (float * rad, float * h, float * eyeheight)
References checkmdl, model::collideheight, model::collidexyradius, and model::eyeheight.
void mdlcollide (int * collide)
References checkmdl, and model::collide.
void mdlcullface (int * cullface)
References checkmdl, and model::setcullface().
void mdldepthoffset (int * offset)
References checkmdl, and model::depthoffset.
void mdlellipsecollide (int * collide)
References checkmdl, and model::ellipsecollide.
void mdlenvmap (float * envmapmax, float * envmapmin, char * envmap)
References checkmdl, cubemapload(), and model::setenvmap().
void mdlextendbb (float * x, float * y, float * z)
References model::bbextend, and checkmdl.
void mdlfullbright (float * fullbright)
References checkmdl, and model::setfullbright().
void mdlglare (float * specglare, float * glowglare)
References checkmdl, and model::setglare().
void mdlglow (int * percent, int * delta, float * pulse)
References checkmdl, and model::setglow().
void mdlname ()
References checkmdl, model::name, and result().
Referenced by game::movable::movable(), entities::renderentities(), game::rendermovables(), and game::renderplayer().
void mdlpitch (float * angle)
References checkmdl, and model::offsetpitch.
void mdlscale (int * percent)
References checkmdl, and model::scale.
void mdlshader (char * shader)
References checkmdl, lookupshaderbyname(), and model::setshader().
void mdlshadow (int * shadow)
References checkmdl, and model::shadow.
void mdlspec (int * percent)
References checkmdl, and model::setspec().
void mdlspin (float * yaw, float * pitch)
References checkmdl, model::spinpitch, and model::spinyaw.
void mdltrans (float * x, float * y, float * z)
References checkmdl, and model::translate.
void mdlyaw (float * angle)
References checkmdl, and model::offsetyaw.
void mmodel (char * name)
References vector< T, MINSIZE >::add(), copystring(), mapmodelinfo::m, and mapmodelinfo::name.
Referenced by mapmodelcompat().
bool modeloccluded (const vec & center, float radius)
References bboccluded(), and pvsoccluded().
Referenced by cullmodel().
MODELTYPE (MDL_MD2 , md2)
MODELTYPE (MDL_MD3 , md3)
MODELTYPE (MDL_MD5 , md5)
MODELTYPE (MDL_OBJ , obj)
MODELTYPE (MDL_SMD , smd)
MODELTYPE (MDL_IQM , iqm)
static model* __cdecl* modeltypes (const char *) static
Referenced by addmodeltype(), and loadmodel().
void preloadmodel (const char * name)
References hashbase< hashnameset< T >, T, const char *, T >::access(), vector< T, MINSIZE >::add(), and newstring().
Referenced by game::ctfclientmode::preload(), game::collectclientmode::preload(), game::captureclientmode::preload(), game::preloadbouncers(), entities::preloadentities(), game::preloadplayermodel(), and game::preloadweapons().
void preloadmodelshaders (bool force)
References enumerate, initing, and model::preloadshaders().
void preloadusedmapmodels (bool msg, bool bih)
References vector< T, MINSIZE >::add(), entity::attr2, entities::ents, ET_MAPMODEL, vector< T, MINSIZE >::find(), entities::getents(), getmminfo(), vector< T, MINSIZE >::length(), loadmodel(), loadprogress, Log, loopv, mapmodelinfo::m, mapmodels, mapmodelinfo::name, model::preloadBIH(), model::preloadmeshes(), inexor::util::log_manager::std, and entity::type.
Referenced by calclight(), load_world(), and patchlight().
void rdanimjoints (int * on)
References checkragdoll.
void rdeye (int * v)
References checkragdoll.
void rdjoint (int * n, int * t, int * v1, int * v2, int * v3)
References ragdollskel::joint::bone, checkragdoll, anonymous_namespace{utilTest.cpp}::t(), ragdollskel::joint::tri, and ragdollskel::joint::vert.
void rdlimitdist (int * v1, int * v2, float * mindist, float * maxdist)
References checkragdoll, hmap::d, inexor::rpc::max(), ragdollskel::distlimit::maxdist, ragdollskel::distlimit::mindist, and ragdollskel::distlimit::vert.
void rdlimitrot (int * t1, int * t2, float * maxangle, float * qx, float * qy, float * qz, float * qw)
References checkragdoll, ragdollskel::rotlimit::maxangle, ragdollskel::rotlimit::middle, RAD, and ragdollskel::rotlimit::tri.
void rdtri (int * v1, int * v2, int * v3)
References checkragdoll, anonymous_namespace{utilTest.cpp}::t(), and ragdollskel::tri::vert.
void rdvert (float * x, float * y, float * z, float * radius)
References checkragdoll, ragdollskel::vert::pos, and ragdollskel::vert::radius.
void render2dbox (vec & o, float x, float y, float z)
References gle::begin(), gle::end(), and xtraverts.
Referenced by render3dbox().
void render3dbox (vec & o, float tofloor, float toceil, float xradius, float yradius = 0)
References vec::add(), render2dbox(), and vec::sub().
Referenced by rendermodel().
void renderbatchedmodel (model * m, batchedmodel & b)
References batchedmodel::anim, ANIM_FULLBRIGHT, ANIM_GHOST, ANIM_NOSKIN, batchedmodel::attached, batchedmodel::basetime, batchedmodel::basetime2, batchedmodel::color, batchedmodel::d, batchedmodel::dir, batchedmodel::flags, GLOBALPARAMF, MDL_FULLBRIGHT, MDL_GHOST, batchedmodel::pitch, batchedmodel::pos, model::render(), shadowmapping, batchedmodel::transparent, and batchedmodel::yaw.
Referenced by endmodelbatches(), and endmodelquery().
void renderclient (dynent * d, const char * mdlname, modelattach * attachments, int hold, int attack, int attackdelay, int lastaction, int lastpain, float fade, bool ragdoll)
References game::allowmove(), ANIM_ALL, ANIM_BACKWARD, ANIM_DEAD, ANIM_DYING, ANIM_EDIT, ANIM_END, ANIM_FORWARD, ANIM_IDLE, ANIM_INDEX, ANIM_JUMP, ANIM_LAG, ANIM_LEFT, ANIM_LOOP, ANIM_NOPITCH, ANIM_PAIN, ANIM_RAGDOLL, ANIM_RIGHT, ANIM_SECONDARY, ANIM_SINK, ANIM_SWIM, CS_DEAD, CS_EDITING, CS_LAGGED, CS_SPECTATOR, DELETEP, drawtex, DRAWTEX_MODELPREVIEW, ENT_AI, ENT_PLAYER, f(), hmap::flags, lastmillis, MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_QUERY, MDL_CULL_VFC, MDL_DYNSHADOW, MDL_FULLBRIGHT, MDL_LIGHT, inexor::rpc::min(), PHYS_FALL, physent::pitch, player, rendermodel(), and physent::yaw.
Referenced by game::renderplayer().
static void rendercullmodelquery (model * m, dynent * d, const vec & center, float radius) inline static
References hmap::br, camera1, drawbb(), endquery, newquery(), physent::o, dynent::query, and startquery.
Referenced by rendermodel().
void renderellipse (vec & o, float xradius, float yradius, float yaw)
References vec::add(), gle::attrib(), gle::begin(), gle::end(), f(), loopi(), RAD, vec::rotate_around_z(), sincos360, and xtraverts.
Referenced by rendermodel().
void rendermodel (entitylight * light, const char * mdl, int anim, const vec & o, float yaw, float pitch, int flags, dynent * d, modelattach * a, int basetime, int basetime2, float trans)
References physent::aboveeye, vector< T, MINSIZE >::add(), vec::add(), addbatchedmodel(), batchedmodel::anim, ANIM_FULLBRIGHT, ANIM_GHOST, ANIM_NORENDER, ANIM_NOSKIN, batchedmodel::attached, batchedmodel::basetime, batchedmodel::basetime2, modelbatch::batched, BLOB_DYNAMIC, BLOB_STATIC, model::boundbox(), ragdolldata::center, model::collisionbox(), entitylight::color, batchedmodel::color, cullmodel(), batchedmodel::d, hmap::d, entitylight::dir, batchedmodel::dir, disablecullmodelquery(), dynlightreaching(), editmode, enablecullmodelquery(), endquery, model::endrender(), ENT_CAMERA, physent::eyeheight, batchedmodel::flags, modelbatch::flags, flushblobs(), glaring, GLOBALPARAMF, lastmillis, vector< T, MINSIZE >::length(), dynent::light, game::lighteffects(), lightreaching(), loadmodel(), modelattach::m, vec::magnitude(), inexor::rpc::max(), MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_QUERY, MDL_CULL_VFC, MDL_DYNLIGHT, MDL_DYNSHADOW, MDL_FULLBRIGHT, MDL_GHOST, MDL_HUD, MDL_LIGHT, MDL_LIGHT_FAST, MDL_NORENDER, MDL_SHADOW, entitylight::millis, modelquery, newquery(), notextureshader, physent::o, OCCLUDE_NOTHING, dynent::occluded, oqfrags, batchedmodel::pitch, batchedmodel::pos, dynent::query, batchedmodel::query, RAD, physent::radius, ragdolldata::radius, dynent::ragdoll, reflecting, reflectz, refracting, model::render(), render3dbox(), renderblob(), rendercullmodelquery(), renderellipse(), vec::rotate_around_z(), rotatebb(), Shader::set(), shadowmap, shadowmapping, showblobs, startquery, model::startrender(), modelattach::tag, batchedmodel::transparent, physent::type, physent::xradius, physent::yaw, batchedmodel::yaw, and physent::yradius.
Referenced by game::drawhudmodel(), gui::modelpreview(), game::renderbouncers(), renderclient(), entities::renderentities(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), game::ctfclientmode::rendergame(), rendermapmodel(), game::rendermovables(), game::renderplayer(), game::bombclientmode::renderplayersposindicator(), and game::renderprojectiles().
void setbbfrommodel (dynent * d, const char * mdl)
References physent::aboveeye, COLLIDE_OBB, physent::collidetype, model::collisionbox(), model::ellipsecollide, ENT_INANIMATE, model::eyeheight, physent::eyeheight, loadmodel(), inexor::rpc::max(), physent::radius, physent::type, physent::xradius, and physent::yradius.
Referenced by game::movable::movable().
static bool sorttransparentmodels (const transparentmodel & x, const transparentmodel & y) inline static
References transparentmodel::dist.
Referenced by endmodelbatches().
void startmodelbatches ()
References vector< T, MINSIZE >::setsize().
Referenced by game::rendergame(), rendermapmodels(), and renderreflectedmapmodels().
void startmodelquery (occludequery * query)
Referenced by rendermapmodels().
VAR (oqdynent , 0 , 1 , 1)
VAR (animationinterpolationtime , 0 , 150 , 1000)
VAR (maxskelanimdata , 1 , 192 , 0)
VAR (testtags , 0 , 0 , 1)
VAR (showboundingbox , 0 , 0 , 2)
VAR (maxmodelradiusdistance , 10 , 200 , 1000)
VAR (animoverride , - 1, 0 , NUMANIMS- 1)
VAR (testanims , 0 , 0 , 1)
VAR (testpitch , - 90, 0 , 90)
VARFP (envmapmodels , 0 , 1 , 1 , preloadmodelshaders(true))
VARFP (bumpmodels , 0 , 1 , 1 , preloadmodelshaders(true))
VARP (fullbrightmodels , 0 , 0 , 200)
VARP (gpuskel , 0 , 1 , 1)
Variable Documentation
vector<modelbatch *> batches static
model* loadingmodel = nullptr
vector<mapmodelinfo> mapmodels
Referenced by disttoent(), loadmapmodel(), and preloadusedmapmodels().
vector<std::string> missingmodels
vector<modelattach> modelattached static
occludequery* modelquery = nullptr static
Referenced by endmodelquery(), and rendermodel().
hashnameset<model *> models
int numbatches = -1 static
Referenced by addbatchedmodel().
vector<const char *> preloadmodels