Inexor: inexor/engine/renderparticles.cpp File Reference
renderparticles.cpp File Reference
#include "inexor/engine/renderparticles.hpp"
#include <SDL_opengl.h>
#include <boost/algorithm/clamp.hpp>
#include <math.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "inexor/engine/decal.hpp"
#include "inexor/engine/depthfx.hpp"
#include "inexor/engine/glare.hpp"
#include "inexor/engine/glemu.hpp"
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/particles.hpp"
#include "inexor/engine/pvs.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/rendergl.hpp"
#include "inexor/engine/rendertext.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/shader.hpp"
#include "inexor/engine/shadowmap.hpp"
#include "inexor/engine/water.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/entities.hpp"
#include "inexor/fpsgame/weapon.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/physics/physics.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/ents.hpp"
#include "inexor/shared/geom.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/texture.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
#include "inexor/util/legacy_time.hpp"
#include "inexor/engine/explosion.hpp"
#include "inexor/engine/lensflare.hpp"
#include "inexor/engine/lightning.hpp"
Classes
struct meterrenderer
struct textrenderer
struct varenderer< T >
Macros
#define ROTCOEFFS(n)
#define SETTEXCOORDS(u1c, u2c, v1c, v2c, body)
#define SETCOLOR(r, g, b, a)
#define SETMODCOLOR SETCOLOR((p->color.r*blend)>>8, (p->color.g*blend)>>8, (p->color.b*blend)>>8, 255)
Typedefs
typedef varenderer< PT_PART > quadrenderer
typedef varenderer< PT_TAPE > taperenderer
typedef varenderer< PT_TRAIL > trailrenderer
Functions
VARP (particlesize, 20, 100, 500)
VARP (emitmillis, 1, 17, 1000)
static bool canemitparticles ()
VARP (showparticles, 0, 1, 1)
VAR (cullparticles, 0, 1, 1)
VAR (replayparticles, 0, 1, 1)
VARN (seedparticles, seedmillis, 0, 3000, 10000)
VAR (dbgpcull, 0, 0, 1)
VAR (dbgpseed, 0, 0, 1)
void clearparticleemitters ()
void addparticleemitters ()
VARP (outlinemeters, 0, 0, 1)
static textrenderer texts (PT_TEXT|PT_LERP)
template<int T>
static void modifyblend (const vec &o, int &blend)
template<>
void modifyblend< PT_TAPE > (const vec &o, int &blend)
template<int T>
static void genpos (const vec &o, const vec &d, float size, int grav, int ts, partvert *vs)
template<>
void genpos< PT_TAPE > (const vec &o, const vec &d, float size, int ts, int grav, partvert *vs)
template<>
void genpos< PT_TRAIL > (const vec &o, const vec &d, float size, int ts, int grav, partvert *vs)
template<int T>
static void genrotpos (const vec &o, const vec &d, float size, int grav, int ts, partvert *vs, int rot)
template<>
void genrotpos< PT_PART > (const vec &o, const vec &d, float size, int grav, int ts, partvert *vs, int rot)
template<int T>
static void seedpos (particleemitter &pe, const vec &o, const vec &d, int fade, float size, int grav)
template<>
void seedpos< PT_TAPE > (particleemitter &pe, const vec &o, const vec &d, int fade, float size, int grav)
template<>
void seedpos< PT_TRAIL > (particleemitter &pe, const vec &o, const vec &d, int fade, float size, int grav)
VAR (flarelights, 0, 0, 1)
VARP (flarecutoff, 0, 1000, 10000)
VARP (flaresize, 20, 100, 500)
VAR (lnjittermillis, 0, 100, 1000)
VAR (lnjitterradius, 0, 4, 100)
FVAR (lnjitterscale, 0, 0.5f, 10)
VAR (lnscrollmillis, 1, 300, 5000)
FVAR (lnscrollscale, 0, 0.125f, 10)
FVAR (lnblendpower, 0, 0.25f, 1000)
VARFP (maxparticles, 10, 4000, 40000, particleinit())
VARFP (fewparticles, 10, 100, 40000, particleinit())
void particleinit ()
void clearparticles ()
void cleanupparticles ()
void removetrackedparticles (physent *owner)
VARP (particleglare, 0, 2, 100)
VARN (debugparticles, dbgparts, 0, 0, 1)
void debugparticles ()
void renderparticles (bool mainpass)
static particle * newparticle (const vec &o, const vec &d, int fade, int type, int color, float size, int gravity=0)
VARP (maxparticledistance, 256, 1024, 4096)
static void splash (int type, int color, int radius, int num, int fade, const vec &p, float size, int gravity)
static void regularsplash (int type, int color, int radius, int num, int fade, const vec &p, float size, int gravity, int delay=0)
bool canaddparticles ()
void regular_particle_splash (int type, int num, int fade, const vec &p, int color, float size, int radius, int gravity, int delay)
void particle_splash (int type, int num, int fade, const vec &p, int color, float size, int radius, int gravity)
VARP (maxtrail, 1, 500, 10000)
void particle_trail (int type, int fade, const vec &s, const vec &e, int color, float size, int gravity)
VARP (particletext, 0, 1, 1)
VARP (maxparticletextdistance, 0, 128, 10000)
void particle_text (const vec &s, const char *t, int type, int fade, int color, float size, int gravity)
void particle_textcopy (const vec &s, const char *t, int type, int fade, int color, float size, int gravity)
void particle_icon (const vec &s, int ix, int iy, int type, int fade, int color, float size, int gravity)
void particle_meter (const vec &s, float val, int type, int fade, int color, int color2, float size)
void particle_flare (const vec &p, const vec &dest, int fade, int type, int color, float size, physent *owner)
void particle_fireball (const vec &dest, float maxsize, int type, int fade, int color, float size)
static vec offsetvec (vec o, int dir, int dist)
static int colorfromattr (int attr)
void regularshape (int type, int radius, int color, int dir, int num, int fade, const vec &p, float size, int gravity, int vel, const vec *modfrom, const vec *modto)
static void regularflame (int type, const vec &p, float radius, float height, int color, int density=3, float scale=2.0f, float speed=200.0f, float fade=600.0f, int gravity=-15)
void regular_particle_flame (int type, const vec &p, float radius, float height, int color, int density, float scale, float speed, float fade, int gravity)
static void makeparticles (entity &e)
bool printparticles (extentity &e, char *buf, int len)
void seedparticles ()
void updateparticles ()
Variables
Shader * particleshader = nullptr
Shader * particlenotextureshader = nullptr
static int lastemitframe = 0
static int emitoffset = 0
static bool canemit = false
static bool regenemitters = false
static bool canstep = false
static vector< particleemitter > emitters
static particleemitter * seedemitter = nullptr
static const char * partnames [] = { "part", "tape", "trail", "text", "textup", "meter", "metervs", "fireball", "lightning", "flare" }
static meterrenderer meters (PT_METER)
static meterrenderer metervs (PT_METERVS)
static const vec rotcoeffs [32][4]
partrenderer * parts []
static int addedparticles = 0
Macro Definition Documentation
#define ROTCOEFFS (n)
Value:
{ \
    vec(-1,  1, 0).rotate_around_z(n*2*M_PI/32.0f), \
    vec( 1,  1, 0).rotate_around_z(n*2*M_PI/32.0f), \
    vec( 1, -1, 0).rotate_around_z(n*2*M_PI/32.0f), \
    vec(-1, -1, 0).rotate_around_z(n*2*M_PI/32.0f) \
}
#define SETCOLOR (r, g, b, a)
Value:
do { \
                bvec4 col(r, g, b, a); \
                loopi(4) vs[i].color = col; \
            } while(0)
Referenced by varenderer< T >::genverts().
#define SETMODCOLOR SETCOLOR((p->color.r*blend)>>8, (p->color.g*blend)>>8, (p->color.b*blend)>>8, 255)
Referenced by varenderer< T >::genverts().
#define SETTEXCOORDS (u1c, u2c, v1c, v2c, body)
Value:
{ \
                float u1 = u1c, u2 = u2c, v1 = v1c, v2 = v2c; \
                body; \
                vs[0].tc = vec2(u1, v1); \
                vs[1].tc = vec2(u2, v1); \
                vs[2].tc = vec2(u2, v2); \
                vs[3].tc = vec2(u1, v2); \
            }
Referenced by varenderer< T >::genverts().
Typedef Documentation
typedef varenderer<PT_PART> quadrenderer
typedef varenderer<PT_TAPE> taperenderer
typedef varenderer<PT_TRAIL> trailrenderer
Function Documentation
void addparticleemitters ()
References emitters, entities::ents, ET_PARTICLES, entities::getents(), loopv, regenemitters, and entity::type.
Referenced by seedparticles(), and updateparticles().
bool canaddparticles ()
References inexor::rendering::screen::ScreenManager::minimized, renderedgame, inexor::rendering::screen::screen_manager, and shadowmapping.
Referenced by particle_fireball(), particle_flare(), particle_icon(), particle_meter(), particle_splash(), particle_text(), particle_textcopy(), particle_trail(), regular_particle_flame(), regular_particle_splash(), game::captureclientmode::rendergame(), and game::ctfclientmode::rendergame().
static bool canemitparticles () static
References canemit, emitoffset, reflecting, and refracting.
Referenced by regularflame(), regularshape(), and regularsplash().
void cleanupparticles ()
References partrenderer::cleanup(), loopi(), and parts.
Referenced by resetgl().
void clearparticleemitters ()
References emitters, and regenemitters.
Referenced by clearparticles(), and modifyoctaent().
void clearparticles ()
References clearparticleemitters(), loopi(), parts, and partrenderer::reset().
Referenced by resetmap().
static int colorfromattr (int attr) inline static
Referenced by makeparticles().
void debugparticles ()
References draw_text(), flushhudmatrix(), FONTH, hudmatrix, hudshader, loopi(), matrix4::ortho(), parts, pophudmatrix(), pushhudmatrix(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::ScreenManager::screenw, and Shader::set().
Referenced by gl_drawhud().
FVAR (lnjitterscale , 0 , 0. 5f, 10)
FVAR (lnscrollscale , 0 , 0. 125f, 10)
FVAR (lnblendpower , 0 , 0. 25f, 1000)
template<int T> static void genpos (const vec & o, const vec & d, float size, int grav, int ts, partvert * vs) inline static
References vec::add(), camright, camup, vec::mul(), partvert::pos, and vec::sub().
template<> void genpos< PT_TAPE > (const vec & o, const vec & d, float size, int ts, int grav, partvert * vs) inline
References camera1, vec::cross(), hmap::d, vec::mul(), vec::normalize(), physent::o, and vec::sub().
Referenced by genpos< PT_TRAIL >().
template<> void genpos< PT_TRAIL > (const vec & o, const vec & d, float size, int ts, int grav, partvert * vs) inline
References vec::add(), hmap::d, vec::div(), f(), and genpos< PT_TAPE >().
template<int T> static void genrotpos (const vec & o, const vec & d, float size, int grav, int ts, partvert * vs, int rot) inline static
References hmap::d.
template<> void genrotpos< PT_PART > (const vec & o, const vec & d, float size, int grav, int ts, partvert * vs, int rot) inline
References camright, camup, vec::mul(), and rotcoeffs.
static void makeparticles (entity & e) static
References flarerenderer::addflare(), entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, gle::color(), colorfromattr(), defformatstring, editmode, f(), flares, getwatercolor(), getwaterfallcolor(), MAT_WATER, inexor::rpc::max(), inexor::rpc::min(), newparticle(), entity::o, offsetvec(), PART_EXPLOSION, PART_FLAME, PART_LIGHTNING, PART_METER, PART_METER_VS, PART_SMOKE, PART_SNOW, PART_STEAM, PART_STREAK, PART_TEXT, PART_WATER, particle_textcopy(), regularflame(), regularshape(), regularsplash(), and rnd().
Referenced by seedparticles(), and updateparticles().
template<int T> static void modifyblend (const vec & o, int & blend) inline static
References inexor::rpc::min().
template<> void modifyblend< PT_TAPE > (const vec & o, int & blend) inline
static particle* newparticle (const vec & o, const vec & d, int fade, int type, int color, float size, int gravity = 0) inline static
References addedparticles, partrenderer::addpart(), emitoffset, parts, seedemitter, and partrenderer::seedemitter().
Referenced by makeparticles(), particle_fireball(), particle_flare(), particle_icon(), particle_meter(), particle_text(), particle_textcopy(), particle_trail(), regularflame(), regularshape(), and splash().
static vec offsetvec (vec o, int dir, int dist) inline static
References dir.
Referenced by makeparticles().
void particle_fireball (const vec & dest, float maxsize, int type, int fade, int color, float size)
References canaddparticles(), and newparticle().
Referenced by game::collectclientmode::baseexplosion(), game::collectclientmode::droptoken(), game::explode(), game::ctfclientmode::flagexplosion(), game::ctfclientmode::rendergame(), and game::captureclientmode::rendertether().
void particle_flare (const vec & p, const vec & dest, int fade, int type, int color, float size, physent * owner)
References canaddparticles(), and newparticle().
Referenced by game::collectclientmode::baseeffect(), ai::drawroute(), game::collectclientmode::droptoken(), game::ctfclientmode::flageffect(), ai::render(), game::ctfclientmode::rendergame(), game::captureclientmode::rendertether(), game::shoteffects(), and game::collectclientmode::stealtoken().
void particle_icon (const vec & s, int ix, int iy, int type, int fade, int color, float size, int gravity)
References canaddparticles(), particle::flags, and newparticle().
Referenced by game::parsemessages(), entities::pickupeffects(), game::captureclientmode::receiveammo(), and game::captureclientmode::updatebase().
void particle_meter (const vec & s, float val, int type, int fade, int color, int color2, float size)
References canaddparticles(), and newparticle().
Referenced by game::captureclientmode::rendergame().
void particle_splash (int type, int num, int fade, const vec & p, int color, float size, int radius, int gravity)
References canaddparticles(), and splash().
Referenced by game::collectclientmode::baseexplosion(), game::damageeffect(), game::collectclientmode::droptoken(), game::explode(), game::ctfclientmode::flagexplosion(), game::projsplash(), game::ctfclientmode::rendergame(), game::captureclientmode::rendertether(), game::shoteffects(), game::captureclientmode::updatebase(), game::updatebouncers(), and game::updateprojectiles().
void particle_text (const vec & s, const char * t, int type, int fade, int color, float size, int gravity)
References camera1, canaddparticles(), vec::dist(), newparticle(), physent::o, and anonymous_namespace{utilTest.cpp}::t().
Referenced by game::parsemessages(), game::captureclientmode::rendergame(), game::collectclientmode::rendergame(), and game::rendergame().
void particle_textcopy (const vec & s, const char * t, int type, int fade, int color, float size, int gravity)
References camera1, canaddparticles(), vec::dist(), particle::flags, newparticle(), newstring(), and physent::o.
Referenced by game::damageeffect(), makeparticles(), game::parsemessages(), ai::render(), game::ctfclientmode::scoreflag(), game::captureclientmode::setscore(), and updateparticles().
void particle_trail (int type, int fade, const vec & s, const vec & e, int color, float size, int gravity)
References vec::add(), canaddparticles(), hmap::d, vec::dist(), vec::div(), loopi(), newparticle(), and rnd().
Referenced by game::shoteffects().
void particleinit ()
References partrenderer::init(), lookupshaderbyname(), loopi(), inexor::rpc::min(), particlenotextureshader, particleshader, parts, and PT_FEW.
Referenced by main().
bool printparticles (extentity & e, char * buf, int len)
References entity::attr1, entity::attr2, entity::attr3, entity::attr4, entity::attr5, entities::entname(), nformatstring(), and entity::type.
Referenced by printent().
void regular_particle_flame (int type, const vec & p, float radius, float height, int color, int density, float scale, float speed, float fade, int gravity)
References canaddparticles(), and regularflame().
Referenced by game::captureclientmode::rendergame(), and game::collectclientmode::rendergame().
void regular_particle_splash (int type, int num, int fade, const vec & p, int color, float size, int radius, int gravity, int delay)
References canaddparticles(), and regularsplash().
Referenced by ai::render(), game::updatebouncers(), updateparticles(), and game::updateprojectiles().
static void regularflame (int type, const vec & p, float radius, float height, int color, int density = 3, float scale = 2.0f, float speed = 200.0f, float fade = 600.0f, int gravity = -15) static
References canemitparticles(), f(), loopi(), inexor::rpc::max(), inexor::rpc::min(), newparticle(), rnd(), and rndscale().
Referenced by makeparticles(), and regular_particle_flame().
void regularshape (int type, int radius, int color, int dir, int num, int fade, const vec & p, float size, int gravity, int vel, const vec * modfrom, const vec * modto)
References vec::add(), camera1, canemitparticles(), partrenderer::collide, mpr::collide(), COLLIDEERROR, COLLIDERADIUS, hmap::d, vec::dist2(), f(), loopi(), inexor::rpc::max(), vec::mul(), newparticle(), physent::o, parts, PI, PI2, PT_LIGHTNING, PT_TAPE, RAY_CLIPMAT, raycube(), vec::rescale(), rnd(), rndscale(), seedemitter, sincos360, vec::sub(), and partrenderer::type.
Referenced by makeparticles(), and game::renderbouncers().
static void regularsplash (int type, int color, int radius, int num, int fade, const vec & p, float size, int gravity, int delay = 0) static
References canemitparticles(), rnd(), and splash().
Referenced by makeparticles(), and regular_particle_splash().
void removetrackedparticles (physent * owner)
References loopi(), parts, and partrenderer::resettracked().
Referenced by game::clientdisconnected().
void renderparticles (bool mainpass)
References binddepthfxparams(), binddepthfxtex(), canstep, partrenderer::debuginfo(), depthfxpartblend, depthfxtex, hmap::flags, GL_ONE, glaring, GLOBALPARAMF, partrenderer::haswork(), depthfxtexture::highprecision(), loopi(), particlenotextureshader, particleshader, parts, PT_GLARE, PT_LERP, PT_MOD, PT_NOTEX, PT_SHADER, PT_SOFT, partrenderer::render(), resetfogcolor(), Shader::set(), SETSHADER, partrenderer::type, partrenderer::update(), and zerofogcolor().
Referenced by drawglare(), drawreflection(), and gl_drawframe().
void seedparticles ()
References addparticleemitters(), canemit, emitters, particleemitter::ent, particleemitter::finalize(), particleemitter::lastemit, loopv, makeparticles(), inexor::rpc::min(), renderprogress(), and seedemitter.
Referenced by allchanged().
template<int T> static void seedpos (particleemitter & pe, const vec & o, const vec & d, int fade, float size, int grav) inline static
References vec::add(), gle::end(), particleemitter::extendbb(), f(), and anonymous_namespace{utilTest.cpp}::t().
template<> void seedpos< PT_TAPE > (particleemitter & pe, const vec & o, const vec & d, int fade, float size, int grav) inline
References hmap::d.
template<> void seedpos< PT_TRAIL > (particleemitter & pe, const vec & o, const vec & d, int fade, float size, int grav) inline
References vec::add(), hmap::d, vec::div(), and f().
static void splash (int type, int color, int radius, int num, int fade, const vec & p, float size, int gravity) static
References camera1, partrenderer::collide, COLLIDEERROR, COLLIDERADIUS, vec::dist(), f(), loopi(), newparticle(), physent::o, parts, RAY_CLIPMAT, raycube(), rnd(), and seedemitter.
Referenced by particle_splash(), and regularsplash().
static textrenderer texts (PT_TEXT| PT_LERP) static
void updateparticles ()
References addedparticles, addparticleemitters(), camera1, canemit, particleemitter::center, particleemitter::cullmax, particleemitter::cullmin, vec::dist(), editmode, emitoffset, emitters, particleemitter::ent, entgroup, entname(), entities::ents, ET_EMPTY, f(), flares, entities::getents(), isfoggedsphere(), particleemitter::lastcull, particleemitter::lastemit, lastemitframe, lastmillis, Log, loopv, flarerenderer::makelightflares(), makeparticles(), inexor::rpc::max(), particleemitter::maxfade, inexor::rendering::screen::ScreenManager::minimized, entity::o, physent::o, PART_EDIT, PART_TEXT, particle_textcopy(), pvsoccluded(), particleemitter::radius, regenemitters, regular_particle_splash(), inexor::rendering::screen::screen_manager, inexor::util::log_manager::std, and entity::type.
Referenced by main().
VAR (cullparticles , 0 , 1 , 1)
VAR (replayparticles , 0 , 1 , 1)
VAR (dbgpcull , 0 , 0 , 1)
VAR (dbgpseed , 0 , 0 , 1)
VAR (flarelights , 0 , 0 , 1)
VAR (lnjittermillis , 0 , 100 , 1000)
VAR (lnjitterradius , 0 , 4 , 100)
VAR (lnscrollmillis , 1 , 300 , 5000)
VARFP (maxparticles , 10 , 4000 , 40000 , particleinit())
VARFP (fewparticles , 10 , 100 , 40000 , particleinit())
VARN (seedparticles , seedmillis , 0 , 3000 , 10000)
VARN (debugparticles , dbgparts , 0 , 0 , 1)
VARP (particlesize , 20 , 100 , 500)
VARP (emitmillis , 1 , 17 , 1000)
VARP (showparticles , 0 , 1 , 1)
VARP (outlinemeters , 0 , 0 , 1)
VARP (flarecutoff , 0 , 1000 , 10000)
VARP (flaresize , 20 , 100 , 500)
VARP (particleglare , 0 , 2 , 100)
VARP (maxparticledistance , 256 , 1024 , 4096)
VARP (maxtrail , 1 , 500 , 10000)
VARP (particletext , 0 , 1 , 1)
VARP (maxparticletextdistance , 0 , 128 , 10000)
Variable Documentation
int addedparticles = 0 static
Referenced by newparticle(), and updateparticles().
bool canemit = false static
Referenced by canemitparticles(), seedparticles(), and updateparticles().
bool canstep = false static
Referenced by listrenderer::render(), and renderparticles().
int emitoffset = 0 static
Referenced by listrenderer::addpart(), varenderer< T >::addpart(), canemitparticles(), newparticle(), and updateparticles().
vector<particleemitter> emitters static
Referenced by addparticleemitters(), clearparticleemitters(), seedparticles(), and updateparticles().
int lastemitframe = 0 static
Referenced by updateparticles().
meterrenderer meters(PT_METER) static
meterrenderer metervs(PT_METERVS)
Shader * particlenotextureshader = nullptr
Referenced by particleinit(), and renderparticles().
Shader* particleshader = nullptr
Referenced by particleinit(), and renderparticles().
const char* partnames[] = { "part", "tape", "trail", "text", "textup", "meter", "metervs", "fireball", "lightning", "flare" } static
Referenced by partrenderer::debuginfo().
partrenderer* parts[]
Initial value:
=
{
    new quadrenderer("<grey>particle/blood.png", PT_PART|PT_FLIP|PT_MOD|PT_RND4, DECAL_BLOOD),
    new trailrenderer("particle/base.png", PT_TRAIL|PT_LERP),
    new quadrenderer("<grey>particle/smoke.png", PT_PART|PT_FLIP|PT_LERP),
    new quadrenderer("<grey>particle/steam.png", PT_PART|PT_FLIP),
    new quadrenderer("<grey>particle/flames.png", PT_PART|PT_HFLIP|PT_RND4|PT_GLARE),
    new quadrenderer("particle/ball1.png", PT_PART|PT_FEW|PT_GLARE),
    new quadrenderer("particle/ball2.png", PT_PART|PT_FEW|PT_GLARE),
    new quadrenderer("particle/ball3.png", PT_PART|PT_FEW|PT_GLARE),
    new taperenderer("particle/flare.jpg", PT_TAPE|PT_GLARE),
    &lightnings,
    &fireballs,
    &bluefireballs,
    new quadrenderer("particle/spark.png", PT_PART|PT_FLIP|PT_GLARE),
    new quadrenderer("particle/base.png",  PT_PART|PT_FLIP|PT_GLARE),
    new quadrenderer("<grey>particle/snow.png", PT_PART|PT_FLIP|PT_RND4, -1),
    new quadrenderer("particle/muzzleflash1.jpg", PT_PART|PT_FEW|PT_FLIP|PT_GLARE|PT_TRACK),
    new quadrenderer("particle/muzzleflash2.jpg", PT_PART|PT_FEW|PT_FLIP|PT_GLARE|PT_TRACK),
    new quadrenderer("particle/muzzleflash3.jpg", PT_PART|PT_FEW|PT_FLIP|PT_GLARE|PT_TRACK),
    new quadrenderer("interface/hud/items.png", PT_PART|PT_FEW|PT_ICON),
    new quadrenderer("<colorify:1/1/1>interface/hud/items.png", PT_PART|PT_FEW|PT_ICON),
    &texts,
    &meters,
    &metervs,
    &flares
}
Referenced by varenderer< T >::addpart(), cleanupparticles(), clearparticles(), compileglslshader(), debugparticles(), finddepthfxranges(), varenderer< T >::genverts(), varenderer< T >::init(), newparticle(), particleinit(), regularshape(), removetrackedparticles(), renderparticles(), varenderer< T >::resettracked(), skelcommands< MDL >::setadjust(), skelcommands< MDL >::setanim(), skelcommands< MDL >::setanimpart(), modelcommands< MDL, struct MDL::vertmesh >::setlink(), skelcommands< MDL >::setpitch(), skelcommands< MDL >::setpitchcorrect(), skelcommands< MDL >::setpitchtarget(), skelcommands< MDL >::settag(), showglslinfo(), and splash().
bool regenemitters = false static
Referenced by addparticleemitters(), clearparticleemitters(), and updateparticles().
const vec rotcoeffs[32][4] static
Initial value:
=
{
    ROTCOEFFS(0),  ROTCOEFFS(1),  ROTCOEFFS(2),  ROTCOEFFS(3),  ROTCOEFFS(4),  ROTCOEFFS(5),  ROTCOEFFS(6),  ROTCOEFFS(7),
    ROTCOEFFS(8),  ROTCOEFFS(9),  ROTCOEFFS(10), ROTCOEFFS(11), ROTCOEFFS(12), ROTCOEFFS(13), ROTCOEFFS(14), ROTCOEFFS(15),
    ROTCOEFFS(16), ROTCOEFFS(17), ROTCOEFFS(18), ROTCOEFFS(19), ROTCOEFFS(20), ROTCOEFFS(21), ROTCOEFFS(22), ROTCOEFFS(7),
    ROTCOEFFS(24), ROTCOEFFS(25), ROTCOEFFS(26), ROTCOEFFS(27), ROTCOEFFS(28), ROTCOEFFS(29), ROTCOEFFS(30), ROTCOEFFS(31),
}
Referenced by genrotpos< PT_PART >().
particleemitter* seedemitter = nullptr static
Referenced by newparticle(), regularshape(), seedparticles(), and splash().