Inexor: inexor/engine/renderva.hpp File Reference
renderva.hpp File Reference
#include <SDL_opengl.h>
#include "inexor/engine/glexts.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/geom.hpp"
Macros
#define startquery(query) do { glBeginQuery_(GL_SAMPLES_PASSED, ((occludequery *)(query))->id); } while(0)
#define endquery(query) do { glEndQuery_(GL_SAMPLES_PASSED); } while(0)
Functions
void visiblecubes (bool cull=true)
void setvfcP (float z=-1, const vec &bbmin=vec(-1,-1,-1), const vec &bbmax=vec(1, 1, 1))
void savevfcP ()
void restorevfcP ()
void rendergeom (float causticspass=0, bool fogpass=false)
void renderalphageom (bool fogpass=false)
void rendermapmodels ()
void renderreflectedgeom (bool causticspass=false, bool fogpass=false)
void renderreflectedmapmodels ()
void renderoutline ()
bool rendersky (bool explicitonly=false)
void resetinvalidtextslots ()
Resets the set of slots that an error has been reported for.
bool isfoggedsphere (float rad, const vec &cv)
int isvisiblesphere (float rad, const vec &cv)
bool bboccluded (const ivec &bo, const ivec &br)
occludequery * newquery (void *owner)
bool checkquery (occludequery *query, bool nowait=false)
void resetqueries ()
int getnumqueries ()
void startbb (bool mask=true)
void endbb (bool mask=true)
void drawbb (const ivec &bo, const ivec &br)
Variables
vtxarray * visibleva
vtxarray * reflectedva
SharedVar< int > oqfrags
Macro Definition Documentation
#define endquery (query) do { glEndQuery_(GL_SAMPLES_PASSED); } while(0)
Referenced by endmodelbatches(), endmodelquery(), queryreflection(), rendercullmodelquery(), rendermapmodels(), rendermodel(), and renderquery().
#define startquery (query) do { glBeginQuery_(GL_SAMPLES_PASSED, ((occludequery *)(query))->id); } while(0)
Referenced by endmodelbatches(), endmodelquery(), queryreflection(), rendercullmodelquery(), rendermapmodels(), rendermodel(), and renderquery().
Function Documentation
bool bboccluded (const ivec & bo, const ivec & br)
References bbinsideva(), bboccluded(), cube::children, vtxarray::curvfc, cube::ext, OCCLUDE_BB, vtxarray::occluded, octastep, cubeext::va, VFC_FOGGED, worldroot, and worldscale.
bool checkquery (occludequery * query, bool nowait = false)
References occludequery::fragments, glGetQueryObjectiv_, glGetQueryObjectuiv_, GLuint(), occludequery::id, and oqfrags.
Referenced by cullmodel(), drawreflections(), findvisiblemms(), rendergeom(), and renderwater().
void drawbb (const ivec & bo, const ivec & br)
References glDrawRangeElements_, LOCALPARAMF, and xtraverts.
Referenced by rendercullmodelquery(), rendermapmodels(), and renderquery().
void endbb (bool mask = true)
References gle::clearebo(), and gle::clearvbo().
Referenced by disablecullmodelquery(), disablevquery(), and rendermapmodels().
int getnumqueries ()
References queryframe::cur, and flipquery.
Referenced by gl_drawhud().
bool isfoggedsphere (float rad, const vec & cv)
References plane::dist(), loopi(), and vfcDfog.
Referenced by cullmodel(), fireballrenderer::finddepthfxranges(), finddynlights(), gengrassquads(), rendergrass(), fireballrenderer::renderpart(), and updateparticles().
int isvisiblesphere (float rad, const vec & cv)
References plane::dist(), loopi(), VFC_FOGGED, VFC_FULL_VISIBLE, VFC_NOT_VISIBLE, VFC_PART_VISIBLE, and vfcDfog.
Referenced by flarerenderer::addflare(), flarerenderer::makelightflares(), and noedit().
occludequery* newquery (void * owner)
References flipquery, and queryframe::newquery().
Referenced by queryreflections(), rendercullmodelquery(), rendergeom(), rendermapmodels(), and rendermodel().
void renderalphageom (bool fogpass = false)
References vector< T, MINSIZE >::add(), renderstate::alphaing, renderstate::alphascale, cleanupgeom(), renderstate::colormask, renderstate::colorscale, cur, renderstate::depthmask, disablevattribs(), disablevbuf(), vector< T, MINSIZE >::empty(), fading, FIRSTVA, GL_ONE, ishiddencube(), vector< T, MINSIZE >::length(), loop, loopv, NEXTVA, OCCLUDE_BB, OCCLUDE_GEOM, pvsoccluded(), reflecting, reflectz, refractfog, refracting, renderbatches(), RENDERPASS_LIGHTMAP, RENDERPASS_Z, renderva(), resetbatches(), resetfogcolor(), vector< T, MINSIZE >::setsize(), setupgeom(), renderstate::texgendim, renderstate::vattribs, renderstate::vbuf, and VFC_FOGGED.
Referenced by drawcubemap(), drawglare(), drawminimap(), drawreflection(), and gl_drawframe().
void rendergeom (float causticspass = 0, bool fogpass = false)
References renderstate::blending, camera1, checkquery(), cleanupgeom(), renderstate::colormask, cur, renderstate::depthmask, disablevattribs(), disablevbuf(), disablevquery(), drawtex, fading, finddynlights(), FIRSTVA, flipqueries(), glaring, insideva(), ishiddencube(), vector< T, MINSIZE >::length(), inexor::rpc::min(), newquery(), vtxarray::next, NEXTVA, physent::o, OCCLUDE_BB, OCCLUDE_GEOM, OCCLUDE_NOTHING, OCCLUDE_PARENT, oqfrags, popshadowmap(), pushshadowmap(), pvsoccluded(), reflecting, reflectz, refractfog, refracting, renderbatches(), renderfoggedvas(), rendergeommultipass(), RENDERPASS_CAUSTICS, RENDERPASS_LIGHTMAP, RENDERPASS_LIGHTMAP_BLEND, RENDERPASS_Z, renderquery(), rendershadowmap(), renderva(), resetbatches(), setupcaustics(), setupgeom(), shadowmap, renderstate::texgendim, renderstate::vattribs, renderstate::vbuf, VFC_FOGGED, renderstate::vquery, vtris, and vverts.
Referenced by drawcubemap(), drawglare(), drawminimap(), gl_drawframe(), and renderreflectedgeom().
void rendermapmodels ()
References camera1, drawbb(), EF_RENDER, endbb(), endmodelbatches(), endmodelquery(), endquery, entities::ents, findvisiblemms(), extentity::flags, entities::getents(), insideoe(), loopv, newquery(), octaentities::next, physent::o, oqfrags, rendermapmodel(), startbb(), startmodelbatches(), startmodelquery(), startquery, ivec::sub(), and visiblemms.
Referenced by drawcubemap(), drawminimap(), and gl_drawframe().
void renderoutline ()
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), gle::color(), disablepolygonoffset(), drawvatris(), enablepolygonoffset(), vec::hexcolor(), vtxarray::next, notextureshader, OCCLUDE_BB, OCCLUDE_GEOM, outlinecolour, vertex::pos, Shader::set(), vtxarray::vbuf, and xtravertsva.
Referenced by gl_drawframe().
void renderreflectedgeom (bool causticspass = false, bool fogpass = false)
References findreflectedvas(), reflecting, rendergeom(), and varoot.
Referenced by drawreflection().
void renderreflectedmapmodels ()
References EF_NOVIS, EF_RENDER, endmodelbatches(), entities::ents, extentity::flags, entities::getents(), isfoggedcube(), loopv, octaentities::mapmodels, reflectdist, reflecting, reflectz, refracting, rendermapmodel(), octaentities::rnext, vtxarray::rnext, startmodelbatches(), and visiblemms.
Referenced by drawglare(), and drawreflection().
bool rendersky (bool explicitonly = false)
References gle::clearebo(), gle::clearvbo(), vtxarray::next, OCCLUDE_BB, reflecting, renderedexplicitsky, renderedskyclip, renderedskyfaces, renderreflectedskyvas(), renderskyva(), updateskystats(), and varoot.
Referenced by drawskylimits(), and drawskyoutline().
void resetinvalidtextslots ()
Resets the set of slots that an error has been reported for.
Referenced by clearslots().
void resetqueries ()
References loopi(), MAXQUERYFRAMES, and queryframe::reset().
Referenced by allchanged().
void restorevfcP ()
References calcvfcD().
Referenced by drawreflections().
void savevfcP ()
Referenced by drawreflections().
void setvfcP (float z = -1, const vec & bbmin = vec(-1,-1,-1), const vec & bbmax = vec(1, 1, 1))
References vec4::add(), calcvfcD(), camprojmatrix, fog, loopi(), plane::normalize(), plane::reflectz(), matrix4::roww(), matrix4::rowx(), matrix4::rowy(), matrix4::rowz(), vec4::sub(), and vfcDfog.
Referenced by drawreflections(), and visiblecubes().
void startbb (bool mask = true)
References bbebo, bbvbo, gle::bindebo(), gle::bindvbo(), SETSHADER, and setupbb().
Referenced by enablecullmodelquery(), enablevquery(), and rendermapmodels().
void visiblecubes (bool cull = true)
References vtxarray::curvfc, vtxarray::distance, findvisiblevas(), loopv, vtxarray::next, OCCLUDE_GEOM, OCCLUDE_NOTHING, vtxarray::occluded, vtxarray::query, setvfcP(), sortvisiblevas(), vtxarray::texs, valist, varoot, VFC_FULL_VISIBLE, vfcDfar, vfcDfog, vfcDnear, and visibleva.
Referenced by drawcubemap(), drawminimap(), and gl_drawframe().
Variable Documentation
SharedVar<int> oqfrags
Referenced by checkquery(), drawreflections(), queryreflections(), rendergeom(), rendermapmodels(), rendermodel(), and renderwater().
vtxarray * reflectedva
Referenced by findreflectedvas(), and sortmaterials().
vtxarray* visibleva
Referenced by drawskybox(), generategrass(), octarender(), queryreflections(), sortmaterials(), sortvisiblevas(), and visiblecubes().