Inexor: inexor/texture/savetexture.hpp File Reference
savetexture.hpp File Reference
everything to save images of various formats.
Enumerations
enum { IMG_BMP = 0, IMG_TGA = 1, IMG_PNG = 2, NUMIMG }
Functions
void saveimage (const char *filename, int format, ImageData &image, bool flip=false)
int guessimageformat (const char *filename, int format=IMG_PNG)
void savepng (const char *filename, ImageData &image, bool flip=false)
void savetga (const char *filename, ImageData &image, bool flip=false)
Detailed Description
everything to save images of various formats.
Enumeration Type Documentation
anonymous enum
Enumerator
IMG_BMP
IMG_TGA
IMG_PNG
NUMIMG
Function Documentation
int guessimageformat (const char * filename, int format = IMG_PNG)
References format(), imageexts, loopi(), and NUMIMG.
Referenced by flipnormalmapy(), mergenormalmaps(), and screenshot().
void saveimage (const char * filename, int format, ImageData & image, bool flip = false)
References ImageData::bpp, ImageData::data, findfile(), ImageData::h, IMG_PNG, IMG_TGA, savepng(), savetga(), texflip(), ImageData::w, and wrapsurface().
Referenced by flipnormalmapy(), mergenormalmaps(), and screenshot().
void savepng (const char * filename, ImageData & image, bool flip = false)
References ImageData::bpp, tiger::compress(), ImageData::data, f(), FLUSHZ, ImageData::h, Log, loopi(), loopj, openfile(), ImageData::pitch, stream::putbig(), stream::seek(), inexor::util::log_manager::std, stream::tell(), ImageData::w, stream::write(), and writepngchunk().
Referenced by dumplms(), and saveimage().
void savetga (const char * filename, ImageData & image, bool flip = false)
References ImageData::bpp, ImageData::data, f(), ImageData::h, tgaheader::height, tgaheader::imagetype, Log, loopi(), loopj, inexor::rpc::min(), openfile(), ImageData::pitch, tgaheader::pixelsize, stream::putchar(), hmap::run(), inexor::util::log_manager::std, ImageData::w, tgaheader::width, and stream::write().
Referenced by saveimage().