Inexor: inexor/ui/screen/ScreenManager.cpp File Reference
ScreenManager.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <memory>
#include "SDL.h"
#include "SDL_error.h"
#include "SDL_mouse.h"
#include "SDL_stdinc.h"
#include "inexor/engine/movie.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/ui/legacy/menus.hpp"
#include "inexor/ui/screen/ScreenManager.hpp"
Namespaces
gle
inexor
Show stacktrace on unix, do not include directly.
inexor::rendering
inexor::rendering::screen
Functions
void cef_resize (int width, int height)
void gl_resize ()
void fatal (const char *s,...)
Fatal crash: log/display crash message and clean up SDL.
void gle::forcedisable ()
static void gle::disable ()
Variables
int hasstencil
ScreenManager inexor::rendering::screen::screen_manager
Singleton instnace of the screenmanager.
Function Documentation
void cef_resize (int width, int height)
References inexor::ui::cef_app, Log, and inexor::util::log_manager::ui.
Referenced by gl_resize(), inexor::rendering::screen::ScreenManager::screenres(), and inexor::rendering::screen::ScreenManager::setfullscreen().
void fatal (const char * s, ...)
Fatal crash: log/display crash message and clean up SDL.
References cleanup_application(), defvformatstring, Log, NULL, and inexor::util::log_manager::std.
Referenced by inexor::crashreporter::abortHandler(), addcommand(), game::addmsg(), gl_checkextensions(), loadshaders(), main(), reloadfonts(), resetgl(), server::servererror(), inexor::rendering::screen::ScreenManager::setupscreen(), and setupshaders().
void gl_resize ()
References cef_resize(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, and inexor::rendering::screen::ScreenManager::screenw.
Referenced by gl_init(), and inexor::rendering::screen::ScreenManager::screenres().
Variable Documentation
int hasstencil
Referenced by genwatertex(), gl_drawframe(), maskreflection(), and inexor::rendering::screen::ScreenManager::setupscreen().