Inexor: inexor/io/input/SDL2Keyboard.cpp File Reference
SDL2Keyboard.cpp File Reference
#include "SDL_keyboard.h"
#include "include/cef_base.h"
#include "inexor/io/input/SDL2Keyboard.hpp"
Functions
int getKeyboardModifiers (uint16_t const mod)
uint16_t convertSDLtoJSKeyCode (SDL_Keycode sdl_keycode, bool shift, bool numlock)
int getWindowsKeyCode (SDL_Keysym const &key)
Function Documentation
uint16_t convertSDLtoJSKeyCode (SDL_Keycode sdl_keycode, bool shift, bool numlock)
References JSC_ASTERISK, JSC_BACK_SLASH, JSC_BRACE_LEFT, JSC_BRACE_RIGHT, JSC_BRACKET_LEFT, JSC_BRACKET_RIGHT, JSC_COMMA, JSC_DELETE, JSC_HASH, JSC_NUM_ADD, JSC_NUM_DIVIDE, JSC_NUM_MULTIPLY, JSC_NUM_SUBTRACT, JSC_PARENTHESES_LEFT, JSC_PARENTHESES_RIGHT, JSC_PIPE, JSC_PLUS, JSC_QUESTION, JSC_SEMI_COLON, JSC_SINGLE_QUOTE, JSC_SUBTRACT, JSC_TILDE, JSC_UNDERSCORE, JSK_ADD, JSK_BACKSPACE, JSK_CAPS_LOCK, JSK_CTRL, JSK_DECIMAL_POINT, JSK_DELETE, JSK_DIVIDE, JSK_DOWN_ARROW, JSK_END, JSK_ENTER, JSK_ESCAPE, JSK_F1, JSK_HOME, JSK_INSERT, JSK_LEFT_ALT, JSK_LEFT_ARROW, JSK_LEFT_WIN, JSK_MULTIPLY, JSK_NUM5_SECOND, JSK_NUM_LOCK, JSK_PAGE_DOWN, JSK_PAGE_UP, JSK_PAUSE, JSK_RIGHT_ALT, JSK_RIGHT_ARROW, JSK_RIGHT_WIN, JSK_SCROLL_LOCK, JSK_SELECT, JSK_SHIFT, JSK_SUBTRACT, JSK_TAB, and JSK_UP_ARROW.
Referenced by inexor::ui::input::InexorKeyboardManager::SendKeyEvent().
int getKeyboardModifiers (uint16_t const mod)
References result().
Referenced by inexor::ui::input::InexorKeyboardManager::SendKeyEvent().
int getWindowsKeyCode (SDL_Keysym const & key)
References result().