Inexor: inexor/server/main.cpp File Reference
main.cpp File Reference
#include <limits.h>
#include <stdlib.h>
#include <algorithm>
#include <memory>
#include <enet/enet.h>
#include "inexor/crashreporter/CrashReporter.hpp"
#include "inexor/fpsgame/server.hpp"
#include "inexor/io/Error.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/network/legacy/cube_network.hpp"
#include "inexor/network/legacy/game_types.hpp"
#include "inexor/server/client_management.hpp"
#include "inexor/server/windows_integration.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_loops.hpp"
#include "inexor/shared/cube_tools.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/util/Subsystem.hpp"
#include "inexor/util/legacy_time.hpp"
Namespaces
server
Macros
#define MAXPINGDATA 32
Functions
void conline (int type, const char *sf)
Function which displayes console text ingame. (legacy UI)
void server::cleanupserver ()
void cleanup_application ()
void server::process (ENetPacket *packet, int sender, int chan)
int server::getservermtu ()
bool server::resolverwait (const char *name, ENetAddress *address)
int server::connectwithtimeout (ENetSocket sock, const char *hostname, const ENetAddress &remoteaddress)
void server::sendserverinforeply (ucharbuf &p)
void server::checkserversockets ()
Reply all server info requests.
server::VAR (serveruprate, 0, 0, INT_MAX)
server::SVAR (serverip,"")
server::VARF (serverport, 0, INEXOR_SERVER_PORT, MAX_POSSIBLE_PORT,{if(!serverport) serverport=server_port();})
void server::serverslice (uint timeout)
main server update
void server::flushserver (bool force)
void server::run_server ()
bool server::servererror (const char *desc)
bool server::setup_network_sockets ()
int main (int argc, char **argv)
Variables
const char * initscript = nullptr
inexor::util::Metasystem metapp
int server::laststatus = 0
ENetSocket server::pongsock = ENET_SOCKET_NULL
ENetSocket server::lansock = ENET_SOCKET_NULL
ENetAddress server::serveraddress = { ENET_HOST_ANY, ENET_PORT_ANY }
static ENetAddress server::pongaddr
Macro Definition Documentation
#define MAXPINGDATA 32
Referenced by server::checkserversockets().
Function Documentation
void cleanup_application ()
References inexor::rendering::screen::ScreenManager::cleanupSDL(), server::cleanupserver(), and inexor::rendering::screen::screen_manager.
void conline (int type, const char * sf)
Function which displayes console text ingame. (legacy UI)
References conlines, CONSTRLEN, copystring(), cline::line, newstring(), cline::outtime, totalmillis, and cline::type.
Referenced by inexor::util::InexorConsoleSink::log().
int main (int argc, char ** argv)
References execfile(), fatal(), inexor::util::Metasystem::initialize(), initscript, Log, inexor::util::log_manager::logfile, server::run_server(), server::serverinit(), server::setup_network_sockets(), inexor::util::Metasystem::start(), SUBSYSTEM_REQUIRE, and UNUSED.
Variable Documentation
const char* initscript = nullptr
Referenced by main().
inexor::util::Metasystem metapp