Inexor: inexor/engine/shadowmap.hpp File Reference
shadowmap.hpp File Reference
#include "inexor/network/SharedVar.hpp"
#include "inexor/shared/geom.hpp"
Functions
bool isshadowmapcaster (const vec &o, float rad)
bool addshadowmapcaster (const vec &o, float xyrad, float zrad)
bool isshadowmapreceiver (vtxarray *va)
void rendershadowmap ()
void pushshadowmap ()
void popshadowmap ()
void rendershadowmapreceivers ()
void guessshadowdir ()
Variables
SharedVar< int > shadowmap
int shadowmapcasters
bool shadowmapping
matrix4 shadowmatrix
Function Documentation
bool addshadowmapcaster (const vec & o, float xyrad, float zrad)
References rendertarget::addblurtiles(), calcshadowmapbb(), inexor::rpc::max(), shadowfocus, shadowmapcasters, and shadowmaptex.
Referenced by cullmodel().
void guessshadowdir ()
References vec::add(), entity::attr1, dir, vec::div(), entities::ents, ET_GAMESPECIFIC, ET_LIGHT, ET_MAPMODEL, entities::getents(), vec::iszero(), loopv, vec::mul(), vec::normalize(), entity::o, shadowdir, SHADOWSKEW, vec::sub(), sunlightdir, and entity::type.
Referenced by allchanged().
bool isshadowmapcaster (const vec & o, float rad)
References shadowdir, shadowfocus, and SHADOWSKEW.
Referenced by cullmodel().
bool isshadowmapreceiver (vtxarray * va)
References vec::add(), calcshadowmapbb(), rendertarget::checkblurtiles(), f(), inexor::rpc::max(), vec::mul(), vtxarray::o, shadowdir, shadowfocus, shadowmap, shadowmapcasters, vtxarray::shadowmapmax, vtxarray::shadowmapmin, shadowmaptex, SHADOWSKEW, vtxarray::size, and SQRT2.
Referenced by rendershadowmapreceivers(), and renderva().
void popshadowmap ()
References rendertarget::rendertex, shadowmap, and shadowmaptex.
Referenced by rendergeom().
void pushshadowmap ()
References ambientcolor, f(), glActiveTexture_, GLOBALPARAM, GLOBALPARAMF, inexor::rpc::max(), matrix4::projective(), rendertarget::rendertex, shadowmap, shadowmapambientcolor, shadowmaptex, shadowmatrix, and skylightcolor.
Referenced by rendergeom().
void rendershadowmap ()
References f(), rendertarget::render(), shadowmap, and shadowmaptex.
Referenced by rendergeom().
void rendershadowmapreceivers ()
References gle::bindebo(), gle::bindvbo(), gle::clearebo(), gle::clearvbo(), drawvatris(), GL_ONE, glBlendEquation_, isshadowmapreceiver(), vtxarray::next, vertex::pos, SETSHADER, vtxarray::vbuf, VFC_FOGGED, and xtravertsva.
Referenced by shadowmaptexture::dorender().
Variable Documentation
SharedVar<int> shadowmap
Referenced by gl_checkextensions(), isshadowmapreceiver(), popshadowmap(), pushshadowmap(), rendergeom(), rendermodel(), rendershadowmap(), and viewshadowmap().
int shadowmapcasters
Referenced by addshadowmapcaster(), shadowmaptexture::dodebug(), shadowmaptexture::dorender(), and isshadowmapreceiver().
bool shadowmapping
Referenced by animmodel::skin::bind(), canaddparticles(), cullmodel(), endmodelbatches(), animmodel::part::render(), renderbatchedmodel(), rendergame(), and rendermodel().
matrix4 shadowmatrix
Referenced by pushshadowmap(), and animmodel::part::render().