Inexor: inexor/texture/slot.cpp File Reference
slot.cpp File Reference
#include <boost/algorithm/clamp.hpp>
#include <stdlib.h>
#include <string.h>
#include <algorithm>
#include <memory>
#include "inexor/client/network.hpp"
#include "inexor/engine/material.hpp"
#include "inexor/engine/octa.hpp"
#include "inexor/engine/octaedit.hpp"
#include "inexor/engine/octarender.hpp"
#include "inexor/engine/octree.hpp"
#include "inexor/engine/renderbackground.hpp"
#include "inexor/engine/renderva.hpp"
#include "inexor/engine/world.hpp"
#include "inexor/fpsgame/client.hpp"
#include "inexor/io/Logging.hpp"
#include "inexor/io/filesystem/mediadirs.hpp"
#include "inexor/io/legacy/stream.hpp"
#include "inexor/network/SharedVar.hpp"
#include "inexor/network/legacy/cube_network.hpp"
#include "inexor/shared/command.hpp"
#include "inexor/shared/cube_formatting.hpp"
#include "inexor/shared/tools.hpp"
#include "inexor/texture/cubemap.hpp"
#include "inexor/texture/image.hpp"
#include "inexor/texture/macros.hpp"
#include "inexor/texture/slot.hpp"
#include "inexor/texture/texture.hpp"
Classes
struct slottex
Legacy texture slot loading.
Functions
void texturereset (int first, int num)
Resets all textures from the slots-stack.
ICOMMAND (texturereset,"ii",(int *first, int *last), texturereset(*first,*last))
void materialreset ()
COMMAND (materialreset,"")
void clearslots ()
static void assignvslot (VSlot &vs)
Set the vs.index according to compactvslots global counter.
static void assignvslotlayer (VSlot &vs)
void compactvslot (int &index)
compacting mode: set index to compactvslots++ = vs.index, marking mode, just set vs.index
void compactvslot (VSlot &vs)
void compactvslots (cube *c, int n)
Loops through all n subcubes of c, (reassigning vs.index to compactvslots++ in markmode and otherwise sets cubetexture to the new vslot) when texture was used.
int compactvslots ()
ICOMMAND (compactvslots,"",(),{extern SharedVar< int > nompedit;if(nompedit &&multiplayer()) return;int oldamount=vslots.length();compactvslots();Log.std->info("compacted virtual Slots (before: {0}, now: {1})", oldamount, vslots.length());allchanged();})
static void clampvslotoffset (VSlot &dst, Slot *slot=nullptr)
static void propagatevslot (VSlot &dst, const VSlot &src, int diff, bool edit=false)
void propagatevslot (VSlot *root, int changed)
Apply changes to all following neighbors of root.
static void mergevslot (VSlot &dst, const VSlot &src, int diff, Slot *slot=nullptr)
void mergevslot (VSlot &dst, const VSlot &src, const VSlot &delta)
static bool comparevslot (const VSlot &dst, const VSlot &src, int diff)
void packvslot (vector< uchar > &buf, const VSlot &src)
Pack a virtual Slot after it has been modified for broadcasting it to the other clients.
void packvslot (vector< uchar > &buf, int index)
void packvslot (vector< uchar > &buf, const VSlot *vs)
bool unpackvslot (ucharbuf &buf, VSlot &dst, bool delta)
Unpack a virtual Slot modified by another client.
VSlot * emptyvslot (Slot &owner)
Wrapper around new VSlot to reuse unused dead vslots.
static VSlot * clonevslot (const VSlot &src, const VSlot &delta)
VARP (autocompactvslots, 0, 256, 0x10000)
VSlot * editvslot (const VSlot &src, const VSlot &delta)
Select a VSlot beeing src but having modifications based on delta (??)
static void fixinsidefaces (cube *c, const ivec &o, int size, int tex)
ICOMMAND (fixinsidefaces,"i",(int *tex),{extern SharedVar< int > nompedit;if(noedit(true)||(nompedit &&multiplayer())) return;fixinsidefaces(worldroot, ivec(0, 0, 0), worldsize >> 1,*tex &&vslots.inrange(*tex)?*tex:DEFAULT_GEOM);allchanged();})
static void addglow (ImageData &c, ImageData &g, const vec &glowcolor)
static void mergespec (ImageData &c, ImageData &s, bool envmap=false)
static void mergedepth (ImageData &c, ImageData &z)
static void addname (vector< char > &key, Slot::Tex &t, bool combined=false, const char *prefix=nullptr)
void gencombinedname (vector< char > &name, int &texmask, Slot &s, Slot::Tex &t, int index, bool forceload)
Generate a keyname to find a combined texture in the texture registry.
MSlot & lookupmaterialslot (int index, bool load)
Slot & lookupslot (int index, bool load)
VSlot & lookupvslot (int index, bool load)
void linkslotshaders ()
void loadlayermasks ()
void cleanupslots ()
void cleanupvslots ()
void cleanupmaterialslots ()
int findslottex (const char *name)
void texture (char *type, char *name, int *rot, int *xoffset, int *yoffset, float *scale)
COMMAND (texture,"ssiiif")
void autograss (char *name)
COMMAND (autograss,"s")
void texscroll (float *scrollS, float *scrollT)
COMMAND (texscroll,"ff")
void texoffset_ (int *xoffset, int *yoffset)
COMMANDN (texoffset, texoffset_,"ii")
void texrotate_ (int *rot)
COMMANDN (texrotate, texrotate_,"i")
void texscale (float *scale)
COMMAND (texscale,"f")
void texlayer (int *layer, char *name, int *mode, float *scale)
COMMAND (texlayer,"isif")
void texalpha (float *front, float *back)
COMMAND (texalpha,"ff")
void texcolor (float *r, float *g, float *b)
COMMAND (texcolor,"fff")
Variables
vector< VSlot * > vslots
vector< Slot * > slots
MSlot materialslots [(MATF_VOLUME|MATF_INDEX)+1]
Slot dummyslot
static int compactedvslots = 0
static int compactvslotsprogress = 0
static int clonedvslots = 0
static bool markingvslots = false
const struct slottex slottexs []
Class Documentation
struct slottex
Legacy texture slot loading.
Class Members
int id
const char * name
Function Documentation
static void addglow (ImageData & c, ImageData & g, const vec & glowcolor) static
References ImageData::bpp, loopk, and readwritergbtex.
Referenced by Slot::loadthumbnail().
static void addname (vector< char > & key, Slot::Tex & t, bool combined = false, const char * prefix = nullptr) static
References vector< T, MINSIZE >::add(), and Slot::Tex::name.
Referenced by gencombinedname(), and Slot::loadthumbnail().
static void assignvslot (VSlot & vs) static
Set the vs.index according to compactvslots global counter.
References assignvslotlayer(), compactedvslots, and VSlot::index.
Referenced by assignvslotlayer(), compactvslot(), and compactvslots().
static void assignvslotlayer (VSlot & vs) inline static
References assignvslot(), VSlot::index, VSlot::layer, and vslots.
Referenced by assignvslot(), and compactvslots().
void autograss (char * name)
References Slot::autograss, DELETEA, getcurexecdir(), makerelpath(), newstring(), and slots.
static void clampvslotoffset (VSlot & dst, Slot * slot = nullptr) static
References Slot::load(), ivec2::max(), VSlot::offset, VSlot::rotation, VSlot::slot, and Slot::sts.
Referenced by mergevslot(), and propagatevslot().
void cleanupmaterialslots ()
References MSlot::cleanup(), loopi(), materialslots, MATF_INDEX, and MATF_VOLUME.
Referenced by cleanuptextures().
void cleanupslots ()
References loopv, and slots.
Referenced by cleanuptextures().
void cleanupvslots ()
References loopv, and vslots.
Referenced by cleanuptextures().
void clearslots ()
References clonedvslots, loopi(), materialslots, MATF_INDEX, MATF_VOLUME, MSlot::reset(), resetinvalidtextslots(), resetslotshader(), slots, and vslots.
Referenced by resetmap().
static VSlot* clonevslot (const VSlot & src, const VSlot & delta) static
References VSlot::changed, propagatevslot(), VSlot::slot, VSLOT_NUM, and vslots.
Referenced by editvslot().
COMMAND (materialreset , "")
COMMAND (texture , "ssiiif")
COMMAND (autograss , "s")
COMMAND (texscroll , "ff")
COMMAND (texscale , "f")
COMMAND (texlayer , "isif")
COMMAND (texalpha , "ff")
COMMAND (texcolor , "fff")
COMMANDN (texoffset , texoffset_ , "ii")
COMMANDN (texrotate , texrotate_ , "i")
void compactvslot (int & index)
compacting mode: set index to compactvslots++ = vs.index, marking mode, just set vs.index
References assignvslot(), VSlot::index, markingvslots, and vslots.
Referenced by compacteditvslots().
void compactvslot (VSlot & vs)
References assignvslot(), and VSlot::index.
void compactvslots (cube * c, int n)
Loops through all n subcubes of c, (reassigning vs.index to compactvslots++ in markmode and otherwise sets cubetexture to the new vslot) when texture was used.
References allocnodes, assignvslot(), compactvslots(), compactvslotsprogress, f(), VSlot::index, loopi(), loopj, markingvslots, inexor::rpc::min(), renderprogress(), cube::texture, and vslots.
Referenced by compacteditvslots(), compactvslots(), editvslot(), and save_world().
int compactvslots ()
References assignvslotlayer(), VSlot::changed, clonedvslots, compacteditvslots(), compactedvslots, compactmruvslots(), compactvslots(), compactvslotsprogress, VSlot::index, VSlot::layer, loopv, markingvslots, VSlot::next, slots, vslots, and worldroot.
static bool comparevslot (const VSlot & dst, const VSlot & src, int diff) static
References VSlot::alphaback, VSlot::alphafront, VSlot::colorscale, VSlot::layer, vector< T, MINSIZE >::length(), loopv, SlotShaderParam::name, VSlot::offset, VSlot::params, VSlot::rotation, VSlot::scale, VSlot::scroll, SlotShaderParam::val, VSLOT_ALPHA, VSLOT_COLOR, VSLOT_LAYER, VSLOT_OFFSET, VSLOT_ROTATION, VSLOT_SCALE, VSLOT_SCROLL, and VSLOT_SHPARAM.
Referenced by Slot::findvariant().
VSlot* editvslot (const VSlot & src, const VSlot & delta)
Select a VSlot beeing src but having modifications based on delta (??)
References allchanged(), clonedvslots, clonevslot(), compactvslots(), Slot::findvariant(), VSlot::slot, and vslots.
Referenced by remapvslot(), unpacktex(), and unpackvslots().
VSlot* emptyvslot (Slot & owner)
Wrapper around new VSlot to reuse unused dead vslots.
Warning
not threadsafe since it accesses slots and vslots globals.
References changed(), loopvrev, Slot::setvariantchain(), slots, and vslots.
Referenced by texture().
int findslottex (const char * name)
References slottex::id, loopi(), and slottexs.
Referenced by texture().
static void fixinsidefaces (cube * c, const ivec & o, int size, int tex) static
References loopi(), loopj, cube::texture, and visibletris().
void gencombinedname (vector< char > & name, int & texmask, Slot & s, Slot::Tex & t, int index, bool forceload)
Generate a keyname to find a combined texture in the texture registry.
References vector< T, MINSIZE >::add(), addname(), Slot::Tex::combined, Slot::findtexture(), TEX_DEPTH, TEX_DIFFUSE, TEX_NORMAL, TEX_SPEC, and Slot::Tex::type.
Referenced by Slot::combinetextures().
ICOMMAND (texturereset , "ii" , (int *first, int *last) , texturereset *,* last)
ICOMMAND (compactvslots , "" , () , {extern SharedVar< int > nompedit;if(nompedit &&multiplayer()) return;int oldamount=vslots.length();compactvslots();Log.std->info("compacted virtual Slots (before: {0}, now: {1})", oldamount, vslots.length());allchanged();})
ICOMMAND (fixinsidefaces , "i" , (int *tex) , {extern SharedVar< int > nompedit;if(noedit(true)||(nompedit &&multiplayer())) return;fixinsidefaces(worldroot, ivec(0, 0, 0), worldsize >> 1,*tex &&vslots.inrange(*tex)?*tex:DEFAULT_GEOM);allchanged();})
void linkslotshaders ()
References linkslotshader(), linkvslotshader(), loopi(), loopv, materialslots, MATF_INDEX, MATF_VOLUME, slots, and vslots.
Referenced by fixshaderdetail(), and reloadshaders().
void loadlayermasks ()
References loopv, and slots.
Referenced by calclight(), patchlight(), and previewblends().
MSlot& lookupmaterialslot (int index, bool load)
References VSlot::linked, linkvslotshader(), Slot::load(), Slot::loaded, and materialslots.
Referenced by rendermaterials(), renderwater(), setupmaterials(), and texture().
Slot& lookupslot (int index, bool load)
References DEFAULT_GEOM, dummyslot, Slot::load(), Slot::loaded, and slots.
Referenced by texturegui::gui(), unpacktex(), and unpackvslots().
VSlot& lookupvslot (int index, bool load)
References DEFAULT_GEOM, dummyvslot, VSlot::linked, linkvslotshader(), Slot::load(), Slot::loaded, VSlot::slot, slots, and vslots.
Referenced by addmergedverts(), gencubeverts(), gengrassquads(), genmergedfaces(), gettexname(), Slot::loadthumbnail(), precachetextures(), previewblends(), gui::previewslot(), vacollect::remapunlit(), remapvslot(), rendertexturepanel(), rotatenormals(), vacollect::setupdata(), setupsurfaces(), texturegui::showtextures(), vacollect::texsort(), and writeobj().
void materialreset ()
References game::allowedittoggle(), identflags, IDF_OVERRIDDEN, loopi(), materialslots, MATF_INDEX, MATF_VOLUME, and MSlot::reset().
static void mergedepth (ImageData & c, ImageData & z) static
References readwritergbatex.
Referenced by Slot::combinetextures().
static void mergespec (ImageData & c, ImageData & s, bool envmap = false) static
References ImageData::bpp, and readwritergbatex.
Referenced by Slot::combinetextures().
static void mergevslot (VSlot & dst, const VSlot & src, int diff, Slot * slot = nullptr) static
References vector< T, MINSIZE >::add(), vec2::add(), ivec2::add(), VSlot::alphaback, VSlot::alphafront, clampvslotoffset(), VSlot::colorscale, ivec2::iszero(), VSlot::layer, loopv, loopvj, vec::mul(), SlotShaderParam::name, VSlot::offset, VSlot::params, VSlot::rotation, VSlot::scale, VSlot::scroll, SlotShaderParam::val, VSLOT_ALPHA, VSLOT_COLOR, VSLOT_LAYER, VSLOT_OFFSET, VSLOT_ROTATION, VSLOT_SCALE, VSLOT_SCROLL, and VSLOT_SHPARAM.
Referenced by mergevslot(), and remapvslot().
void mergevslot (VSlot & dst, const VSlot & src, const VSlot & delta)
References VSlot::changed, mergevslot(), propagatevslot(), VSlot::slot, and VSLOT_NUM.
void packvslot (vector< uchar > & buf, const VSlot & src)
Pack a virtual Slot after it has been modified for broadcasting it to the other clients.
References VSlot::alphaback, VSlot::alphafront, VSlot::changed, VSlot::colorscale, VSlot::layer, loopj, loopv, SlotShaderParam::name, VSlot::offset, VSlot::params, vector< T, MINSIZE >::put(), putfloat(), putint(), putuint(), VSlot::rotation, VSlot::scale, VSlot::scroll, sendstring(), SlotShaderParam::val, VSLOT_ALPHA, VSLOT_COLOR, VSLOT_LAYER, VSLOT_OFFSET, VSLOT_ROTATION, VSLOT_SCALE, VSLOT_SCROLL, VSLOT_SHPARAM, and vslots.
Referenced by game::edittrigger(), packvslot(), and packvslots().
void packvslot (vector< uchar > & buf, int index)
References packvslot(), vector< T, MINSIZE >::put(), and vslots.
void packvslot (vector< uchar > & buf, const VSlot * vs)
References packvslot(), and vector< T, MINSIZE >::put().
static void propagatevslot (VSlot & dst, const VSlot & src, int diff, bool edit = false) static
References vector< T, MINSIZE >::add(), VSlot::alphaback, VSlot::alphafront, clampvslotoffset(), VSlot::colorscale, ivec2::iszero(), VSlot::layer, loopv, VSlot::offset, VSlot::params, VSlot::rotation, VSlot::scale, VSlot::scroll, VSLOT_ALPHA, VSLOT_COLOR, VSLOT_LAYER, VSLOT_OFFSET, VSLOT_ROTATION, VSLOT_SCALE, VSLOT_SCROLL, and VSLOT_SHPARAM.
Referenced by clonevslot(), mergevslot(), propagatevslot(), texalpha(), texcolor(), texlayer(), texoffset_(), texrotate_(), texscale(), texscroll(), and texture().
void propagatevslot (VSlot * root, int changed)
Apply changes to all following neighbors of root.
Making it accordingly to roots vslot
Parameters
root Root of neighbours
changed includes info about what changed
References VSlot::next, and propagatevslot().
void texalpha (float * front, float * back)
References VSlot::alphaback, VSlot::alphafront, f(), propagatevslot(), slots, Slot::variants, and VSLOT_ALPHA.
void texcolor (float * r, float * g, float * b)
References VSlot::colorscale, f(), propagatevslot(), slots, Slot::variants, and VSLOT_COLOR.
void texlayer (int * layer, char * name, int * mode, float * scale)
References getcurexecdir(), VSlot::layer, Slot::layermaskmode, Slot::layermaskname, Slot::layermaskscale, makerelpath(), inexor::rpc::max(), newstring(), path(), propagatevslot(), slots, Slot::variants, and VSLOT_LAYER.
void texoffset_ (int * xoffset, int * yoffset)
References ivec2::max(), VSlot::offset, propagatevslot(), slots, Slot::variants, and VSLOT_OFFSET.
void texrotate_ (int * rot)
References propagatevslot(), VSlot::rotation, slots, Slot::variants, and VSLOT_ROTATION.
void texscale (float * scale)
References propagatevslot(), VSlot::scale, slots, Slot::variants, and VSLOT_SCALE.
Referenced by binddepthfxparams(), gengrassquads(), and setupsurface().
void texscroll (float * scrollS, float * scrollT)
References vec2::div(), f(), propagatevslot(), VSlot::scroll, slots, Slot::variants, and VSLOT_SCROLL.
Referenced by animmodel::skin::setshaderparams().
void texture (char * type, char * name, int * rot, int * xoffset, int * yoffset, float * scale)
References Slot::addtexture(), emptyvslot(), findmaterial(), findslottex(), Slot::loaded, Log, lookupmaterialslot(), ivec2::max(), VSlot::offset, propagatevslot(), VSlot::reset(), VSlot::rotation, VSlot::scale, setslotshader(), slots, inexor::util::log_manager::std, Slot::sts, TEX_DIFFUSE, Slot::texmask, and VSLOT_NUM.
void texturereset (int first, int num)
Resets all textures from the slots-stack.
Parameters
first the texturepos from whereon you want to reset
num the number of slots you want to reset from thereon. All if 0 for example texturereset(0, 40); resets the first 40 textures
References game::allowedittoggle(), VSlot::changed, dummyslot, identflags, IDF_OVERRIDDEN, loopi(), VSlot::next, resetslotshader(), VSlot::slot, slots, Slot::variants, and vslots.
bool unpackvslot (ucharbuf & buf, VSlot & dst, bool delta)
Unpack a virtual Slot modified by another client.
References vector< T, MINSIZE >::add(), VSlot::alphaback, VSlot::alphafront, VSlot::changed, changed(), VSlot::colorscale, f(), databuf< T >::get(), getfloat(), getint(), getshaderparamname(), getstring(), getuint(), VSlot::layer, loopi(), ivec2::max(), SlotShaderParam::name, VSlot::offset, databuf< T >::overread(), VSlot::params, databuf< T >::remaining(), VSlot::rotation, VSlot::scale, VSlot::scroll, SlotShaderParam::val, VSLOT_ALPHA, VSLOT_COLOR, VSLOT_LAYER, VSLOT_OFFSET, VSLOT_ROTATION, VSLOT_SCALE, VSLOT_SCROLL, VSLOT_SHPARAM, and vslots.
Referenced by mpeditvslot(), unpacktex(), and unpackvslots().
VARP (autocompactvslots , 0 , 256 , 0x10000)
Variable Documentation
int clonedvslots = 0 static
Referenced by clearslots(), compactvslots(), and editvslot().
int compactedvslots = 0 static
Referenced by assignvslot(), and compactvslots().
int compactvslotsprogress = 0 static
Referenced by compactvslots().
VSlot dummyvslot& dummyslot
Referenced by loadshaders(), lookupslot(), setupshaders(), and texturereset().
bool markingvslots = false static
Referenced by compactvslot(), and compactvslots().
MSlot materialslots[(MATF_VOLUME|MATF_INDEX)+1]
Referenced by cleanupmaterialslots(), clearslots(), linkslotshaders(), lookupmaterialslot(), and materialreset().
vector<Slot *> slots
Referenced by inexor::sound::soundtype::addslot(), autograss(), inexor::sound::soundconfig::chooseslot(), cleanupslots(), inexor::sound::soundtype::clear(), clearslots(), compactvslots(), emptyvslot(), inexor::sound::soundtype::findsound(), texturegui::gui(), inexor::sound::soundconfig::hasslot(), linkslotshaders(), loadlayermasks(), lookupslot(), lookupvslot(), inexor::sound::soundtype::playing(), inexor::sound::soundtype::preloadsound(), inexor::sound::soundtype::reset(), texturegui::showtextures(), texalpha(), texcolor(), texlayer(), texoffset_(), texrotate_(), texscale(), texscroll(), texture(), and texturereset().
const struct slottex slottexs[]
Initial value:
=
{
    { "c", TEX_DIFFUSE },
    { "u", TEX_UNKNOWN },
    { "d", TEX_DECAL },
    { "n", TEX_NORMAL },
    { "g", TEX_GLOW },
    { "s", TEX_SPEC },
    { "z", TEX_DEPTH },
    { "e", TEX_ENVMAP }
}
Referenced by findslottex().
vector<VSlot *> vslots
Referenced by assignvslotlayer(), cleanupvslots(), clearslots(), clonevslot(), compactmruvslots(), compactvslot(), compactvslots(), editvslot(), emptyvslot(), filltexlist(), linkslotshaders(), loadvslots(), lookupvslot(), packvslot(), packvslots(), save_world(), savevslots(), shouldpacktex(), texturereset(), unpackvslot(), and vlayer().