Inexor: inexor/texture/slot.hpp File Reference
slot.hpp File Reference
management of texture slots as visible ingame.
#include "inexor/engine/shader.hpp"
#include "inexor/network/legacy/buffer_types.hpp"
#include "inexor/shared/cube_types.hpp"
#include "inexor/shared/cube_vector.hpp"
#include "inexor/shared/geom.hpp"
Classes
class VSlot
A virtual Slot.
class Slot
struct Slot::Tex
struct MSlot
Enumerations
enum {
VSLOT_SHPARAM = 0, VSLOT_SCALE, VSLOT_ROTATION, VSLOT_OFFSET,
VSLOT_SCROLL, VSLOT_LAYER, VSLOT_ALPHA, VSLOT_COLOR,
VSLOT_NUM
}
Functions
void loadlayermasks ()
void clearslots ()
void cleanupslots ()
void cleanupvslots ()
void cleanupmaterialslots ()
void propagatevslot (VSlot *root, int changed)
Apply changes to all following neighbors of root.
void texturereset (int first, int num=0)
Resets all textures from the slots-stack.
MSlot & lookupmaterialslot (int slot, bool load=true)
Slot & lookupslot (int slot, bool load=true)
VSlot & lookupvslot (int slot, bool load=true)
VSlot * emptyvslot (Slot &owner)
Wrapper around new VSlot to reuse unused dead vslots.
VSlot * editvslot (const VSlot &src, const VSlot &delta)
Select a VSlot beeing src but having modifications based on delta (??)
void mergevslot (VSlot &dst, const VSlot &src, const VSlot &delta)
bool texturedata (ImageData &d, const char *tname, Slot::Tex *tex=nullptr, bool msg=true, int *compress=nullptr)
void compactvslots (cube *c, int n=8)
Loops through all n subcubes of c, (reassigning vs.index to compactvslots++ in markmode and otherwise sets cubetexture to the new vslot) when texture was used.
void compactvslot (int &index)
compacting mode: set index to compactvslots++ = vs.index, marking mode, just set vs.index
void compactvslot (VSlot &vs)
int compactvslots ()
void compacteditvslots ()
void compactmruvslots ()
void packvslot (vector< uchar > &buf, const VSlot &src)
Pack a virtual Slot after it has been modified for broadcasting it to the other clients.
void packvslot (vector< uchar > &buf, int index)
void packvslot (vector< uchar > &buf, const VSlot *src)
bool unpackvslot (ucharbuf &buf, VSlot &dst, bool delta)
Unpack a virtual Slot modified by another client.
Variables
vector< Slot * > slots
vector< VSlot * > vslots
Detailed Description
management of texture slots as visible ingame.
each texture slot can have multiple images. additional images can be used for various shaders. It is organized in two structures: virtual Slots and normal Slots. Each Slot can have a node-chain of numerous virtual Slots which contain differing shader stuff, or scaling, color, rotation.. So a bunch of textures (a Slot) can easily be varying ingame.
Class Documentation
struct Slot::Tex
Class Members
int combined
string name
Texture * t
int type
Enumeration Type Documentation
anonymous enum
Enumerator
VSLOT_SHPARAM
VSLOT_SCALE
VSLOT_ROTATION
VSLOT_OFFSET
VSLOT_SCROLL
VSLOT_LAYER
VSLOT_ALPHA
VSLOT_COLOR
VSLOT_NUM
Function Documentation
void cleanupmaterialslots ()
References MSlot::cleanup(), loopi(), materialslots, MATF_INDEX, and MATF_VOLUME.
Referenced by cleanuptextures().
void cleanupslots ()
References loopv, and slots.
Referenced by cleanuptextures().
void cleanupvslots ()
References loopv, and vslots.
Referenced by cleanuptextures().
void clearslots ()
References clonedvslots, loopi(), materialslots, MATF_INDEX, MATF_VOLUME, MSlot::reset(), resetinvalidtextslots(), resetslotshader(), slots, and vslots.
Referenced by resetmap().
void compacteditvslots ()
References block3::c(), compactvslot(), compactvslots(), editinfo::copy, editinfos, editingvslots, undolist::first, loopv, undoblock::next, redos, block3::size(), undos, and unpackingvslots.
Referenced by compactvslots().
void compactmruvslots ()
References curtexindex, VSlot::index, lasttex, loopvrev, remappedvslots, vector< T, MINSIZE >::remove(), reptex, texmru, and vslots.
Referenced by compactvslots().
void compactvslot (int & index)
compacting mode: set index to compactvslots++ = vs.index, marking mode, just set vs.index
References assignvslot(), VSlot::index, markingvslots, and vslots.
Referenced by compacteditvslots().
void compactvslot (VSlot & vs)
References assignvslot(), and VSlot::index.
void compactvslots (cube * c, int n = 8)
Loops through all n subcubes of c, (reassigning vs.index to compactvslots++ in markmode and otherwise sets cubetexture to the new vslot) when texture was used.
References allocnodes, assignvslot(), compactvslots(), compactvslotsprogress, f(), VSlot::index, loopi(), loopj, markingvslots, inexor::rpc::min(), renderprogress(), cube::texture, and vslots.
Referenced by compacteditvslots(), compactvslots(), editvslot(), and save_world().
int compactvslots ()
References assignvslotlayer(), VSlot::changed, clonedvslots, compacteditvslots(), compactedvslots, compactmruvslots(), compactvslots(), compactvslotsprogress, VSlot::index, VSlot::layer, loopv, markingvslots, VSlot::next, slots, vslots, and worldroot.
VSlot* editvslot (const VSlot & src, const VSlot & delta)
Select a VSlot beeing src but having modifications based on delta (??)
References allchanged(), clonedvslots, clonevslot(), compactvslots(), Slot::findvariant(), VSlot::slot, and vslots.
Referenced by remapvslot(), unpacktex(), and unpackvslots().
VSlot* emptyvslot (Slot & owner)
Wrapper around new VSlot to reuse unused dead vslots.
Warning
not threadsafe since it accesses slots and vslots globals.
References changed(), loopvrev, Slot::setvariantchain(), slots, and vslots.
Referenced by texture().
void loadlayermasks ()
References loopv, and slots.
Referenced by calclight(), patchlight(), and previewblends().
MSlot& lookupmaterialslot (int slot, bool load = true)
References VSlot::linked, linkvslotshader(), Slot::load(), Slot::loaded, and materialslots.
Referenced by rendermaterials(), renderwater(), setupmaterials(), and texture().
Slot& lookupslot (int slot, bool load = true)
References DEFAULT_GEOM, dummyslot, Slot::load(), Slot::loaded, and slots.
Referenced by texturegui::gui(), unpacktex(), and unpackvslots().
VSlot& lookupvslot (int slot, bool load = true)
References DEFAULT_GEOM, dummyvslot, VSlot::linked, linkvslotshader(), Slot::load(), Slot::loaded, VSlot::slot, slots, and vslots.
Referenced by addmergedverts(), gencubeverts(), gengrassquads(), genmergedfaces(), gettexname(), Slot::loadthumbnail(), precachetextures(), previewblends(), gui::previewslot(), vacollect::remapunlit(), remapvslot(), rendertexturepanel(), rotatenormals(), vacollect::setupdata(), setupsurfaces(), texturegui::showtextures(), vacollect::texsort(), and writeobj().
void mergevslot (VSlot & dst, const VSlot & src, const VSlot & delta)
References VSlot::changed, mergevslot(), propagatevslot(), VSlot::slot, and VSLOT_NUM.
void packvslot (vector< uchar > & buf, const VSlot & src)
Pack a virtual Slot after it has been modified for broadcasting it to the other clients.
References VSlot::alphaback, VSlot::alphafront, VSlot::changed, VSlot::colorscale, VSlot::layer, loopj, loopv, SlotShaderParam::name, VSlot::offset, VSlot::params, vector< T, MINSIZE >::put(), putfloat(), putint(), putuint(), VSlot::rotation, VSlot::scale, VSlot::scroll, sendstring(), SlotShaderParam::val, VSLOT_ALPHA, VSLOT_COLOR, VSLOT_LAYER, VSLOT_OFFSET, VSLOT_ROTATION, VSLOT_SCALE, VSLOT_SCROLL, VSLOT_SHPARAM, and vslots.
Referenced by game::edittrigger(), packvslot(), and packvslots().
void packvslot (vector< uchar > & buf, int index)
References packvslot(), vector< T, MINSIZE >::put(), and vslots.
void packvslot (vector< uchar > & buf, const VSlot * src)
References packvslot(), and vector< T, MINSIZE >::put().
void propagatevslot (VSlot * root, int changed)
Apply changes to all following neighbors of root.
Making it accordingly to roots vslot
Parameters
root Root of neighbours
changed includes info about what changed
References VSlot::next, and propagatevslot().
bool texturedata (ImageData & d, const char * tname, Slot::Tex * tex = nullptr, bool msg = true, int * compress = nullptr)
References canloadsurface(), tiger::compress(), ImageData::compressed, copystring(), ImageData::data, recorder::file, formatstring(), ImageData::h, loaddds(), loadprogress, loadsurface(), Log, matchstring(), inexor::rpc::max(), Slot::Tex::name, PARSETEXCOMMANDS, parsevec(), path(), renderprogress(), scaleimage(), inexor::util::log_manager::std, TEX_NORMAL, texagrad(), texblur(), texcolorify(), texcolormask(), texdup(), texformat(), texgrey(), texmad(), texmix(), texnormal(), texoffset(), texpremul(), texreorient(), texrotate(), Slot::Tex::type, ImageData::w, and ImageData::wrap().
Referenced by Slot::combinetextures(), cubemaploadwildcard(), loadalphamask(), Slot::loadlayermask(), Slot::loadthumbnail(), reloadtexture(), and textureload().
void texturereset (int first, int num)
Resets all textures from the slots-stack.
Parameters
first the texturepos from whereon you want to reset
num the number of slots you want to reset from thereon. All if 0 for example texturereset(0, 40); resets the first 40 textures
References game::allowedittoggle(), VSlot::changed, dummyslot, identflags, IDF_OVERRIDDEN, loopi(), VSlot::next, resetslotshader(), VSlot::slot, slots, Slot::variants, and vslots.
bool unpackvslot (ucharbuf & buf, VSlot & dst, bool delta)
Unpack a virtual Slot modified by another client.
References vector< T, MINSIZE >::add(), VSlot::alphaback, VSlot::alphafront, VSlot::changed, changed(), VSlot::colorscale, f(), databuf< T >::get(), getfloat(), getint(), getshaderparamname(), getstring(), getuint(), VSlot::layer, loopi(), ivec2::max(), SlotShaderParam::name, VSlot::offset, databuf< T >::overread(), VSlot::params, databuf< T >::remaining(), VSlot::rotation, VSlot::scale, VSlot::scroll, SlotShaderParam::val, VSLOT_ALPHA, VSLOT_COLOR, VSLOT_LAYER, VSLOT_OFFSET, VSLOT_ROTATION, VSLOT_SCALE, VSLOT_SCROLL, VSLOT_SHPARAM, and vslots.
Referenced by mpeditvslot(), unpacktex(), and unpackvslots().
Variable Documentation
vector<Slot *> slots
Referenced by inexor::sound::soundtype::addslot(), autograss(), inexor::sound::soundconfig::chooseslot(), cleanupslots(), inexor::sound::soundtype::clear(), clearslots(), compactvslots(), emptyvslot(), inexor::sound::soundtype::findsound(), texturegui::gui(), inexor::sound::soundconfig::hasslot(), linkslotshaders(), loadlayermasks(), lookupslot(), lookupvslot(), inexor::sound::soundtype::playing(), inexor::sound::soundtype::preloadsound(), inexor::sound::soundtype::reset(), texturegui::showtextures(), texalpha(), texcolor(), texlayer(), texoffset_(), texrotate_(), texscale(), texscroll(), texture(), and texturereset().
vector<VSlot *> vslots
Referenced by assignvslotlayer(), cleanupvslots(), clearslots(), clonevslot(), compactmruvslots(), compactvslot(), compactvslots(), editvslot(), emptyvslot(), filltexlist(), linkslotshaders(), loadvslots(), lookupvslot(), packvslot(), packvslots(), save_world(), savevslots(), shouldpacktex(), texturereset(), unpackvslot(), and vlayer().