Inexor: server::explodeevent Struct Reference
server::explodeevent Struct Reference
#include <client_management.hpp>
Public Member Functions
bool keepable () const override
void process (clientinfo *ci) override
bool flush (clientinfo *ci, int fmillis) override
Public Attributes
int id
int gun
vector< hitinfo > hits
int millis
Member Function Documentation
bool server::timedevent::flush (clientinfo * ci, int fmillis) override virtual inherited
Reimplemented from server::gameevent.
References server::clientinfo::lastevent, server::timedevent::millis, and server::gameevent::process().
bool server::explodeevent::keepable () const inline override virtual
Reimplemented from server::gameevent.
void server::explodeevent::process (clientinfo * ci) override virtual
Reimplemented from server::gameevent.
References fpsstate::ammo, server::gamestate::bombs, server::clientinfo::clientnum, CS_ALIVE, guninfo::damage, server::hitinfo::dir, server::hitinfo::dist, server::dodamage(), EXP_DISTSCALE, EXP_SELFDAMDIV, guninfo::exprad, server::get_client_info(), server::gamestate::grenades, gun, GUN_BOMB, GUN_GL, GUN_RL, GUN_SPLINTER, guns, hits, itemstats, server::gamestate::lifesequence, server::hitinfo::lifesequence, loopj, loopv, itemstat::max, N_EXPLODEFX, server::clientinfo::ownernum, fpsstate::quadmillis, server::projectilestate< N >::remove(), server::gamestate::rockets, sendf(), server::gamestate::state, server::clientinfo::state, and server::hitinfo::target.
Member Data Documentation
int server::explodeevent::gun
Referenced by server::parsepacket(), and process().
vector<hitinfo> server::explodeevent::hits
Referenced by server::parsepacket(), and process().
int server::explodeevent::id
Referenced by server::parsepacket().
int server::timedevent::millis inherited
Referenced by server::timedevent::flush(), server::parsepacket(), and server::shotevent::process().
The documentation for this struct was generated from the following files:
inexor/server/client_management.hpp
inexor/fpsgame/server.cpp