Inexor: model Struct Reference
model Struct Reference abstract
#include <model.hpp>
Public Member Functions
model (const char *name)
virtual ~model ()
virtual void calcbb (vec &center, vec &radius)=0
virtual void render (int anim, int basetime, int basetime2, const vec &o, float yaw, float pitch, dynent *d, modelattach *a=nullptr, const vec &color=vec(0, 0, 0), const vec &dir=vec(0, 0, 0), float transparent=1)=0
virtual bool load ()=0
virtual int type () const =0
virtual BIH * setBIH ()
virtual bool envmapped ()
virtual bool skeletal () const
virtual void setshader (Shader *shader)
virtual void setenvmap (float envmapmin, float envmapmax, Texture *envmap)
virtual void setspec (float spec)
virtual void setambient (float ambient)
virtual void setglow (float glow, float glowdelta, float glowpulse)
virtual void setglare (float specglare, float glowglare)
virtual void setalphatest (float alpha)
virtual void setalphablend (bool blend)
virtual void setfullbright (float fullbright)
virtual void setcullface (bool cullface)
virtual void preloadBIH ()
virtual void preloadshaders (bool force=false)
virtual void preloadmeshes ()
virtual void cleanup ()
virtual void startrender ()
virtual void endrender ()
void boundbox (vec &center, vec &radius)
float collisionbox (vec &center, vec &radius)
float boundsphere (vec &center)
float above ()
Public Attributes
char * name
float spinyaw
float spinpitch
float offsetyaw
float offsetpitch
bool collide
bool ellipsecollide
bool shadow
bool alphadepth
bool depthoffset
float scale
vec translate
BIH * bih
vec bbcenter
vec bbradius
vec bbextend
vec collidecenter
vec collideradius
float rejectradius
float eyeheight
float collidexyradius
float collideheight
int batch
Constructor & Destructor Documentation
model::model (const char * name) inline
virtual model::~model () inline virtual
References bih, and name.
Member Function Documentation
float model::above () inline
References boundbox().
Referenced by abovemodel(), and lightent().
void model::boundbox (vec & center, vec & radius) inline
References vec::add(), bbcenter, bbextend, bbradius, and calcbb().
Referenced by above(), boundsphere(), collisionbox(), endmodelbatches(), getentboundingbox(), mmboundbox(), gui::modelpreview(), and rendermodel().
float model::boundsphere (vec & center) inline
References boundbox(), and vec::magnitude().
virtual void model::calcbb (vec & center, vec & radius) pure virtual
Implemented in animmodel.
Referenced by boundbox().
virtual void model::cleanup () inline virtual
Reimplemented in animmodel.
Referenced by cleanupmodels().
float model::collisionbox (vec & center, vec & radius) inline
References boundbox(), collidecenter, collideheight, collideradius, collidexyradius, vec::magnitude(), and rejectradius.
Referenced by entselectionbox(), mmcollide(), mmcollisionbox(), rendermodel(), and setbbfrommodel().
virtual void model::endrender () inline virtual
Reimplemented in animmodel.
Referenced by endmodelbatches(), endmodelquery(), and rendermodel().
virtual bool model::envmapped () inline virtual
Reimplemented in animmodel.
virtual bool model::load () pure virtual
Implemented in smd, md5, iqm, md2, obj, and md3.
Referenced by loadmodel().
virtual void model::preloadBIH () inline virtual
Reimplemented in animmodel.
References bih, and setBIH().
Referenced by animmodel::preloadBIH(), and preloadusedmapmodels().
virtual void model::preloadmeshes () inline virtual
Reimplemented in animmodel.
Referenced by flushpreloadedmodels(), and preloadusedmapmodels().
virtual void model::preloadshaders (bool force = false) inline virtual
Reimplemented in animmodel.
Referenced by loadmodel(), and preloadmodelshaders().
virtual void model::render (int anim, int basetime, int basetime2, const vec & o, float yaw, float pitch, dynent * d, modelattach * a = nullptr, const vec & color = vec(0, 0, 0), const vec & dir = vec(0, 0, 0), float transparent = 1) pure virtual
Implemented in animmodel.
Referenced by renderbatchedmodel(), and rendermodel().
virtual void model::setalphablend (bool blend) inline virtual
Reimplemented in animmodel.
Referenced by mdlalphablend().
virtual void model::setalphatest (float alpha) inline virtual
Reimplemented in animmodel.
Referenced by mdlalphatest().
virtual void model::setambient (float ambient) inline virtual
Reimplemented in animmodel.
Referenced by mdlambient().
virtual BIH* model::setBIH () inline virtual
Reimplemented in animmodel.
Referenced by mmintersect(), and preloadBIH().
virtual void model::setcullface (bool cullface) inline virtual
Reimplemented in animmodel.
Referenced by mdlcullface().
virtual void model::setenvmap (float envmapmin, float envmapmax, Texture * envmap) inline virtual
Reimplemented in animmodel.
Referenced by mdlenvmap().
virtual void model::setfullbright (float fullbright) inline virtual
Reimplemented in animmodel.
Referenced by mdlfullbright().
virtual void model::setglare (float specglare, float glowglare) inline virtual
Reimplemented in animmodel.
Referenced by mdlglare().
virtual void model::setglow (float glow, float glowdelta, float glowpulse) inline virtual
Reimplemented in animmodel.
Referenced by mdlglow().
virtual void model::setshader (Shader * shader) inline virtual
Reimplemented in animmodel.
Referenced by mdlshader().
virtual void model::setspec (float spec) inline virtual
Reimplemented in animmodel.
Referenced by mdlspec().
virtual bool model::skeletal () const inline virtual
Reimplemented in skelmodel.
virtual void model::startrender () inline virtual
Reimplemented in animmodel.
Referenced by endmodelbatches(), endmodelquery(), and rendermodel().
virtual int model::type () const pure virtual
Implemented in iqm, md2, md3, md5, smd, and obj.
Referenced by skelmodel::linktype().
Member Data Documentation
bool model::alphadepth
Referenced by mdlalphadepth(), and animmodel::render().
int model::batch
Referenced by addbatchedmodel().
vec model::bbcenter
Referenced by boundbox().
vec model::bbextend
Referenced by boundbox(), and mdlextendbb().
vec model::bbradius
Referenced by boundbox().
BIH* model::bih
Referenced by mmintersect(), preloadBIH(), animmodel::preloadBIH(), animmodel::setBIH(), and ~model().
bool model::collide
Referenced by mdlcollide(), mmcollide(), and mmintersect().
vec model::collidecenter
Referenced by collisionbox().
float model::collideheight
Referenced by collisionbox(), and mdlbb().
vec model::collideradius
Referenced by collisionbox().
float model::collidexyradius
Referenced by collisionbox(), and mdlbb().
bool model::depthoffset
Referenced by mdldepthoffset(), and animmodel::render().
bool model::ellipsecollide
Referenced by mdlellipsecollide(), mmcollide(), and setbbfrommodel().
float model::eyeheight
Referenced by mdlbb(), and setbbfrommodel().
char* model::name
Referenced by obj::objmeshgroup::load(), md5::md5mesh::load(), md3::load(), obj::load(), md2::load(), md5::md5meshgroup::load(), iqm::load(), md5::load(), smd::load(), md3::loaddefaultparts(), obj::loaddefaultparts(), iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), iqm::iqmmeshgroup::loadiqmanims(), md5::md5meshgroup::loadmesh(), iqm::iqmmeshgroup::loadmesh(), loadmodel(), animmodel::skin::loadshader(), mdlname(), animmodel::part::setanim(), animmodel::sharemeshes(), and ~model().
float model::offsetpitch
Referenced by animmodel::initmatrix(), mdlpitch(), and animmodel::render().
float model::offsetyaw
Referenced by animmodel::initmatrix(), mdlyaw(), and animmodel::render().
float model::rejectradius
Referenced by collisionbox().
float model::scale
Referenced by animmodel::part::calcbb(), vertmodel::vertmeshgroup::calctagmatrix(), skelmodel::skeleton::calctags(), vertmodel::vertmeshgroup::concattagtransform(), skelmodel::skeleton::concattagtransform(), animmodel::part::genBIH(), skelmodel::skeleton::genragdollbones(), skelmodel::skeleton::initragdoll(), animmodel::loaded(), mdlscale(), animmodel::part::render(), skelmodel::skelmeshgroup::render(), and animmodel::skin::setshaderparams().
bool model::shadow
Referenced by mdlshadow(), and mmintersect().
float model::spinpitch
Referenced by mdlspin(), and animmodel::render().
float model::spinyaw
Referenced by mdlspin(), and animmodel::render().
vec model::translate
Referenced by animmodel::link(), md3::load(), obj::load(), md2::load(), animmodel::loaded(), and mdltrans().
The documentation for this struct was generated from the following file:
inexor/model/model.hpp