Inexor: server::bombservermode Struct Reference
server::bombservermode Struct Reference
#include <bomb_server.hpp>
Public Member Functions
void setup () override
bool parsespawnloc (ucharbuf &p, bool commit)
void updatelimbo () override
void leavegame (clientinfo *ci, bool disconnecting) override
void sendspawnlocs (bool resuscitate=false)
bool gamerunning ()
bool canspawn (clientinfo *ci, bool connecting) override
void pushentity (int type, vec o)
void died (clientinfo *target, clientinfo *actor) override
bool canchangeteam (clientinfo *ci, const char *oldteam, const char *newteam) override
void cleanup () override
bool parse_network_message (int type, clientinfo *ci, clientinfo *cq, packetbuf &p) override
process gamemode specific network messages.
virtual void entergame (clientinfo *ci)
virtual void connected (clientinfo *ci)
virtual void moved (clientinfo *ci, const vec &oldpos, bool oldclip, const vec &newpos, bool newclip)
virtual void spawned (clientinfo *ci)
virtual int fragvalue (clientinfo *victim, clientinfo *actor)
virtual bool canhit (clientinfo *victim, clientinfo *actor)
virtual void changeteam (clientinfo *ci, const char *oldteam, const char *newteam)
virtual void initclient (clientinfo *ci, packetbuf &p, bool connecting)
virtual void update ()
virtual void newmap ()
virtual void intermission ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual bool extinfoteam (const char *team, ucharbuf &p)
Public Attributes
bool notgotspawnlocations
vector< spawnloc * > spawnlocs
int sequence
int timecounter
int countdown
Static Public Attributes
static constexpr int COUNTDOWNSECONDS = 3
Member Function Documentation
bool server::bombservermode::canchangeteam (clientinfo * ci, const char * oldteam, const char * newteam) override virtual
Reimplemented from server::servmode.
References bombteamname, and m_teammode.
virtual bool server::servmode::canhit (clientinfo * victim, clientinfo * actor) inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::dodamage().
bool server::bombservermode::canspawn (clientinfo * ci, bool connecting) override virtual
Reimplemented from server::servmode.
References server::clientinfo::clientnum, server::gamestate::deaths, E_ZOOM_IN, gamerunning(), vector< T, MINSIZE >::length(), Log, m_lms, N_HUDANNOUNCE, notgotspawnlocations, sendf(), spawnlocs, server::clientinfo::state, and inexor::util::log_manager::std.
virtual void server::servmode::changeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline virtual inherited
Reimplemented in server::captureservermode, server::ctfservermode, and server::collectservermode.
Referenced by aiman::balanceteams().
void server::bombservermode::cleanup () inline override virtual
Reimplemented from server::servmode.
References vector< T, MINSIZE >::deletecontents(), and spawnlocs.
virtual void server::servmode::connected (clientinfo * ci) inline virtual inherited
Reimplemented in server::hideandseekservermode.
void server::bombservermode::died (clientinfo * target, clientinfo * actor) override virtual
Reimplemented from server::servmode.
References fpsstate::ammo, fpsstate::bombdelay, fpsstate::bombradius, defformatstring, E_ZOOM_OUT, GUN_BOMB, I_BOMBDELAY, I_BOMBRADIUS, I_BOMBS, N_HUDANNOUNCE, server::clientinfo::name, server::gamestate::o, pushentity(), sendf(), and server::clientinfo::state.
virtual void server::servmode::entergame (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::extinfoteam (const char * team, ucharbuf & p) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::extinfoteamscore().
virtual int server::servmode::fragvalue (clientinfo * victim, clientinfo * actor) inline virtual inherited
References isteam, and server::clientinfo::team.
Referenced by server::dodamage(), and server::suicide().
bool server::bombservermode::gamerunning ()
References server::clients, and recorder::state.
Referenced by canspawn().
virtual int server::servmode::getteamscore (const char * team) inline virtual inherited
virtual void server::servmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by server::extinfoteams().
virtual bool server::servmode::hidefrags () inline virtual inherited
Referenced by server::autoteam(), server::chooseworstteam(), and server::extinfoteams().
virtual void server::servmode::initclient (clientinfo * ci, packetbuf & p, bool connecting) inline virtual inherited
Reimplemented in server::ctfservermode, server::collectservermode, server::captureservermode, and server::hideandseekservermode.
virtual void server::servmode::intermission () inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::checkintermission().
void server::bombservermode::leavegame (clientinfo * ci, bool disconnecting) override virtual
Reimplemented from server::servmode.
References server::clientinfo::clientnum, loopv, and spawnlocs.
virtual void server::servmode::moved (clientinfo * ci, const vec & oldpos, bool oldclip, const vec & newpos, bool newclip) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual void server::servmode::newmap () inline virtual inherited
Reimplemented in server::ctfservermode, server::collectservermode, and server::captureservermode.
Referenced by server::parsepacket().
bool server::bombservermode::parse_network_message (int type, clientinfo * ci, clientinfo * cq, packetbuf & p) override virtual
process gamemode specific network messages.
Parameters
type the N_ network message type
ci the sender.
cq the currently focused player (sender or bot from senders pc)
p the network packet containing the data
Returns
whether this messages got processed.
Implements server::servmode.
References server::clientinfo::clientmap, server::clientinfo::clientnum, CS_SPECTATOR, DISC_MSGERR, server::disconnect_client(), N_SPAWNLOC, parsespawnloc(), server::clientinfo::privilege, server::smapname, server::gamestate::state, and server::clientinfo::state.
bool server::bombservermode::parsespawnloc (ucharbuf & p, bool commit)
References vector< T, MINSIZE >::add(), DMF, f(), getint(), loopi(), loopk, m_teammode, inexor::rpc::max(), notgotspawnlocations, databuf< T >::overread(), sendspawnlocs(), and spawnlocs.
Referenced by parse_network_message().
void server::bombservermode::pushentity (int type, vec o)
References DMF, server::ments, vec::mul(), N_ITEMPUSH, NOTUSED, entity::o, rnd(), sendf(), server::sents, and entity::type.
Referenced by died().
void server::bombservermode::sendspawnlocs (bool resuscitate = false)
References vector< T, MINSIZE >::add(), bombteamname, server::clients, CS_SPECTATOR, vector< T, MINSIZE >::length(), loopi(), loopv, m_teammode, N_SPAWNLOC, vector< T, MINSIZE >::removeunordered(), sendf(), server::sendspawn(), vector< T, MINSIZE >::shuffle(), spawnlocs, server::gamestate::state, and server::clientinfo::state.
Referenced by parsespawnloc(), and setup().
void server::bombservermode::setup () override virtual
Reimplemented from server::servmode.
References vector< T, MINSIZE >::add(), entity::attr2, countdown, COUNTDOWNSECONDS, vector< T, MINSIZE >::deletecontents(), loopv, server::ments, server::notgotitems, notgotspawnlocations, entity::o, server::pausegame(), PLAYERSTART, sendspawnlocs(), sequence, spawnlocs, timecounter, and totalmillis.
virtual void server::servmode::spawned (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual void server::servmode::update () inline virtual inherited
Reimplemented in server::ctfservermode, server::collectservermode, server::hideandseekservermode, and server::captureservermode.
Referenced by server::serverupdate().
void server::bombservermode::updatelimbo () override virtual
Reimplemented from server::servmode.
References AI_NONE, fpsstate::aitype, server::clientinfo::clientmap, countdown, COUNTDOWNSECONDS, CS_SPECTATOR, defformatstring, E_STATIC_BOTTOM, E_ZOOM_IN, server::get_client_info(), loopv, server::clientinfo::mapcrc, N_HUDANNOUNCE, notgotspawnlocations, server::pausegame(), sendf(), sequence, spawnlocs, server::gamestate::state, server::clientinfo::state, timecounter, and totalmillis.
Member Data Documentation
int server::bombservermode::countdown
Referenced by setup(), and updatelimbo().
constexpr int server::bombservermode::COUNTDOWNSECONDS = 3 static
Referenced by setup(), and updatelimbo().
bool server::bombservermode::notgotspawnlocations
Referenced by canspawn(), parsespawnloc(), setup(), and updatelimbo().
int server::bombservermode::sequence
Referenced by setup(), and updatelimbo().
vector<spawnloc*> server::bombservermode::spawnlocs
Referenced by canspawn(), cleanup(), leavegame(), parsespawnloc(), sendspawnlocs(), setup(), and updatelimbo().
int server::bombservermode::timecounter
Referenced by setup(), and updatelimbo().
The documentation for this struct was generated from the following files:
inexor/server/gamemode/bomb_server.hpp
inexor/server/gamemode/bomb_server.cpp