Inexor: server::ctfservermode Struct Reference
server::ctfservermode Struct Reference
#include <ctf_server.hpp>
Public Member Functions
bool addflag (int i, const vec &o, int team, int invistime=0)
void ownflag (int i, int owner, int owntime)
void returnflag (int i, int invistime=0)
ctfservermode ()
void reset (bool empty)
void cleanup () override
void setupholdspawns ()
void setup () override
void newmap () override
void dropflag (int i, const vec &o, int droptime, int dropper=-1, bool penalty=false)
void dropflag (clientinfo *ci, clientinfo *dropper=nullptr)
void leavegame (clientinfo *ci, bool disconnecting=false) override
void died (clientinfo *ci, clientinfo *actor) override
bool canspawn (clientinfo *ci, bool connecting) override
bool canchangeteam (clientinfo *ci, const char *oldteam, const char *newteam) override
void changeteam (clientinfo *ci, const char *oldteam, const char *newteam) override
void spawnflag (int i)
void scoreflag (clientinfo *ci, int goal, int relay=-1)
void takeflag (clientinfo *ci, int i, int version)
void update () override
void initclient (clientinfo *ci, packetbuf &p, bool connecting) override
void parseflags (ucharbuf &p, bool commit)
bool parse_network_message (int type, clientinfo *ci, clientinfo *cq, packetbuf &p) override
process gamemode specific network messages.
virtual void entergame (clientinfo *ci)
virtual void connected (clientinfo *ci)
virtual void moved (clientinfo *ci, const vec &oldpos, bool oldclip, const vec &newpos, bool newclip)
virtual void spawned (clientinfo *ci)
virtual int fragvalue (clientinfo *victim, clientinfo *actor)
virtual bool canhit (clientinfo *victim, clientinfo *actor)
virtual void updatelimbo ()
virtual void intermission ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual bool extinfoteam (const char *team, ucharbuf &p)
void resetflags ()
bool addflag (int i, const vec &o, int team)
bool addholdspawn (const vec &o)
int totalscore (int team)
int setscore (int team, int score)
int addscore (int team, int score)
bool hidefrags ()
int getteamscore (const char *team)
void getteamscores (vector< teamscore > &tscores)
bool insidebase (const flag &f, const vec &o)
Public Attributes
bool notgotflags
vector< holdspawn > holdspawns
vector< flag > flags
int scores [2]
Static Public Attributes
static const int RESETFLAGTIME = 10000
static const int INVISFLAGTIME = 20000
static const int BASERADIUS = 64
static const int BASEHEIGHT = 24
static const int MAXFLAGS = 20
static const int FLAGRADIUS = 16
static const int FLAGLIMIT = 10
static const int MAXHOLDSPAWNS = 100
static const int HOLDSECS = 20
static const int HOLDFLAGS = 1
static const int RESPAWNSECS = 5
Constructor & Destructor Documentation
server::ctfservermode::ctfservermode () inline
Member Function Documentation
bool server::ctfservermode::addflag (int i, const vec & o, int team, int invistime = 0)
References ctfmode::addflag(), f(), ctfmode::flags, and flag::invistime.
Referenced by parseflags(), setup(), and setupholdspawns().
bool ctfmode::addflag (int i, const vec & o, int team) inline inherited
References vector< T, MINSIZE >::add(), f(), ctfmode::flags, flag::id, vector< T, MINSIZE >::length(), ctfmode::MAXFLAGS, flag::reset(), flag::spawnloc, and flag::team.
Referenced by addflag(), and game::ctfclientmode::addflag().
bool ctfmode::addholdspawn (const vec & o) inline inherited
References ctfmode::holdspawns, ctfmode::MAXHOLDSPAWNS, and ctfmode::holdspawn::o.
Referenced by parseflags(), setup(), and game::ctfclientmode::setup().
int ctfmode::addscore (int team, int score) inline inherited
References ctfmode::scores.
Referenced by scoreflag(), and update().
bool server::ctfservermode::canchangeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline override virtual
Reimplemented from server::servmode.
References ctfteamflag.
virtual bool server::servmode::canhit (clientinfo * victim, clientinfo * actor) inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::dodamage().
bool server::ctfservermode::canspawn (clientinfo * ci, bool connecting) inline override virtual
Reimplemented from server::servmode.
References curtime, gamemillis, server::gamestate::lastdeath, m_efficiency, m_protect, ctfmode::RESPAWNSECS, and server::clientinfo::state.
void server::ctfservermode::changeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline override virtual
Reimplemented from server::servmode.
References dropflag().
void server::ctfservermode::cleanup () inline override virtual
Reimplemented from server::servmode.
References reset().
virtual void server::servmode::connected (clientinfo * ci) inline virtual inherited
Reimplemented in server::hideandseekservermode.
void server::ctfservermode::died (clientinfo * ci, clientinfo * actor) override virtual
Reimplemented from server::servmode.
References server::clientinfo::clientnum, dropflag(), ctfmode::flags, isteam, loopv, and server::clientinfo::team.
void server::ctfservermode::dropflag (int i, const vec & o, int droptime, int dropper = -1, bool penalty = false)
References flag::dropcount, flag::droploc, flag::dropper, flag::droptime, f(), ctfmode::flags, flag::invistime, flag::owner, flag::owner_id, and flag::vistime.
Referenced by changeteam(), died(), dropflag(), leavegame(), and parse_network_message().
void server::ctfservermode::dropflag (clientinfo * ci, clientinfo * dropper = nullptr)
References server::clientinfo::clientnum, DMF, dropflag(), f(), ctfmode::flags, ctfmode::insidebase(), lastmillis, loopv, m_protect, vec::mul(), N_DROPFLAG, N_RETURNFLAG, notgotflags, server::gamestate::o, returnflag(), sendf(), server::clientinfo::state, and flag::version.
virtual void server::servmode::entergame (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::extinfoteam (const char * team, ucharbuf & p) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::extinfoteamscore().
virtual int server::servmode::fragvalue (clientinfo * victim, clientinfo * actor) inline virtual inherited
References isteam, and server::clientinfo::team.
Referenced by server::dodamage(), and server::suicide().
virtual int server::servmode::getteamscore (const char * team) inline virtual inherited
int ctfmode::getteamscore (const char * team) inline inherited
References ctfteamflag, and ctfmode::totalscore().
virtual void server::servmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by server::extinfoteams().
void ctfmode::getteamscores (vector< teamscore > & tscores) inline inherited
References vector< T, MINSIZE >::add(), ctfflagteam, loopk, and ctfmode::scores.
virtual bool server::servmode::hidefrags () inline virtual inherited
Referenced by server::autoteam(), server::chooseworstteam(), and server::extinfoteams().
bool ctfmode::hidefrags () inline inherited
void server::ctfservermode::initclient (clientinfo * ci, packetbuf & p, bool connecting) override virtual
Reimplemented from server::servmode.
References DMF, flag::droploc, flag::droptime, f(), ctfmode::flags, flag::invistime, vector< T, MINSIZE >::length(), loopk, loopv, N_INITFLAGS, flag::owner_id, putint(), ctfmode::scores, flag::spawnindex, and flag::version.
bool ctfmode::insidebase (const flag & f, const vec & o) inline inherited
References ctfmode::BASEHEIGHT, ctfmode::BASERADIUS, and flag::spawnloc.
Referenced by dropflag(), and game::ctfclientmode::rendergame().
virtual void server::servmode::intermission () inline virtual inherited
Reimplemented in server::hideandseekservermode.
Referenced by server::checkintermission().
void server::ctfservermode::leavegame (clientinfo * ci, bool disconnecting = false) override virtual
Reimplemented from server::servmode.
References server::clientinfo::clientnum, dropflag(), ctfmode::flags, and loopv.
virtual void server::servmode::moved (clientinfo * ci, const vec & oldpos, bool oldclip, const vec & newpos, bool newclip) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
void server::ctfservermode::newmap () inline override virtual
Reimplemented from server::servmode.
References reset().
void server::ctfservermode::ownflag (int i, int owner, int owntime)
References flag::dropcount, flag::dropper, f(), ctfmode::flags, flag::invistime, flag::owner_id, and flag::owntime.
Referenced by takeflag().
bool server::ctfservermode::parse_network_message (int type, clientinfo * ci, clientinfo * cq, packetbuf & p) override virtual
process gamemode specific network messages.
Parameters
type the N_ network message type
ci the sender.
cq the currently focused player (sender or bot from senders pc)
p the network packet containing the data
Returns
whether this messages got processed.
Implements server::servmode.
References server::clientinfo::clientmap, CS_SPECTATOR, dropflag(), getint(), N_INITFLAGS, N_TAKEFLAG, N_TRYDROPFLAG, parseflags(), server::clientinfo::privilege, server::smapname, server::gamestate::state, server::clientinfo::state, and takeflag().
void server::ctfservermode::parseflags (ucharbuf & p, bool commit)
References addflag(), ctfmode::addholdspawn(), DMF, f(), getint(), lastmillis, loopi(), loopk, m_hold, m_protect, inexor::rpc::max(), notgotflags, databuf< T >::overread(), and setupholdspawns().
Referenced by parse_network_message().
void server::ctfservermode::reset (bool empty) inline
References notgotflags, and ctfmode::resetflags().
Referenced by cleanup(), newmap(), and setup().
void ctfmode::resetflags () inline inherited
References ctfmode::flags, ctfmode::holdspawns, loopk, ctfmode::scores, and vector< T, MINSIZE >::shrink().
Referenced by reset(), and game::ctfclientmode::setup().
void server::ctfservermode::returnflag (int i, int invistime = 0)
References flag::dropcount, flag::dropper, flag::droptime, f(), ctfmode::flags, flag::invistime, flag::owner_id, and flag::runstart.
Referenced by dropflag(), scoreflag(), takeflag(), and update().
void server::ctfservermode::scoreflag (clientinfo * ci, int goal, int relay = -1)
References ctfmode::addscore(), server::clientinfo::clientnum, ctfteamflag, ctfmode::FLAGLIMIT, ctfmode::flags, server::gamestate::flags, vector< T, MINSIZE >::inrange(), lastmillis, m_ctf, m_hold, m_protect, N_SCOREFLAG, returnflag(), sendf(), spawnflag(), server::startintermission(), server::clientinfo::state, and server::clientinfo::team.
Referenced by takeflag(), and update().
int ctfmode::setscore (int team, int score) inline inherited
References ctfmode::scores.
Referenced by game::ctfclientmode::resetflag(), and game::ctfclientmode::scoreflag().
void server::ctfservermode::setup () override virtual
Reimplemented from server::servmode.
References addflag(), ctfmode::addholdspawn(), entity::attr2, BASE, FLAG, ctfmode::flags, lastmillis, vector< T, MINSIZE >::length(), loopv, m_hold, m_protect, server::ments, notgotflags, server::notgotitems, entity::o, reset(), setupholdspawns(), and entity::type.
void server::ctfservermode::setupholdspawns ()
References addflag(), f(), ctfmode::flags, ctfmode::HOLDFLAGS, ctfmode::holdspawns, vector< T, MINSIZE >::length(), m_hold, N_RESETFLAG, sendf(), spawnflag(), flag::spawnindex, and flag::version.
Referenced by parseflags(), and setup().
virtual void server::servmode::spawned (clientinfo * ci) inline virtual inherited
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
void server::ctfservermode::spawnflag (int i)
References ctfmode::flags, ctfmode::holdspawns, loopj, and rnd().
Referenced by scoreflag(), setupholdspawns(), and update().
void server::ctfservermode::takeflag (clientinfo * ci, int i, int version)
References server::clientinfo::clientnum, CS_ALIVE, ctfflagteam, ctfteamflag, flag::dropcount, flag::dropper, flag::droptime, f(), ctfmode::flags, vector< T, MINSIZE >::inrange(), flag::invistime, lastmillis, loopvj, m_hold, m_protect, N_RETURNFLAG, N_TAKEFLAG, notgotflags, flag::owner_id, ownflag(), returnflag(), flag::runstart, scoreflag(), sendf(), flag::spawnindex, server::gamestate::state, server::clientinfo::state, flag::team, server::clientinfo::team, and flag::version.
Referenced by parse_network_message().
int ctfmode::totalscore (int team) inline inherited
References ctfmode::scores.
Referenced by ctfmode::getteamscore().
void server::ctfservermode::update () override virtual
Reimplemented from server::servmode.
References ctfmode::addscore(), flag::droptime, f(), ctfmode::flags, server::gamelimit, gamemillis, server::get_client_info(), ctfmode::HOLDSECS, INVISFLAGTIME, flag::invistime, lastmillis, loopv, m_hold, m_protect, N_INVISFLAG, N_RESETFLAG, notgotflags, flag::owner_id, flag::owntime, RESETFLAGTIME, returnflag(), scoreflag(), sendf(), spawnflag(), flag::spawnindex, flag::team, and flag::version.
virtual void server::servmode::updatelimbo () inline virtual inherited
Reimplemented in server::bombservermode.
Referenced by server::serverupdate().
Member Data Documentation
const int ctfmode::BASEHEIGHT = 24 static inherited
Referenced by ctfmode::insidebase().
const int ctfmode::BASERADIUS = 64 static inherited
Referenced by ctfmode::insidebase().
const int ctfmode::FLAGLIMIT = 10 static inherited
Referenced by game::ctfclientmode::scoreflag(), and scoreflag().
const int ctfmode::FLAGRADIUS = 16 static inherited
Referenced by game::ctfclientmode::aidefend(), game::ctfclientmode::aifind(), game::ctfclientmode::checkitems(), game::ctfclientmode::respawned(), game::ctfclientmode::returnflag(), and game::ctfclientmode::scoreflag().
vector<flag> ctfmode::flags inherited
Referenced by addflag(), game::ctfclientmode::addflag(), ctfmode::addflag(), game::ctfclientmode::aicheck(), game::ctfclientmode::aidefend(), game::ctfclientmode::aifind(), game::ctfclientmode::aihomerun(), game::ctfclientmode::aipursue(), game::ctfclientmode::checkitems(), died(), game::ctfclientmode::drawblip(), game::ctfclientmode::drawhud(), dropflag(), game::ctfclientmode::dropflag(), initclient(), game::ctfclientmode::invisflag(), leavegame(), ownflag(), game::ctfclientmode::ownflag(), game::ctfclientmode::parseflags(), game::ctfclientmode::pickholdspawn(), game::ctfclientmode::removeplayer(), game::ctfclientmode::rendergame(), game::ctfclientmode::resetflag(), ctfmode::resetflags(), game::ctfclientmode::respawned(), returnflag(), game::ctfclientmode::returnflag(), game::ctfclientmode::scoreflag(), scoreflag(), game::ctfclientmode::senditems(), setup(), game::ctfclientmode::setup(), setupholdspawns(), spawnflag(), game::ctfclientmode::takeflag(), takeflag(), game::ctfclientmode::trydropflag(), and update().
const int ctfmode::HOLDFLAGS = 1 static inherited
Referenced by game::ctfclientmode::setup(), and setupholdspawns().
const int ctfmode::HOLDSECS = 20 static inherited
Referenced by game::ctfclientmode::drawhud(), and update().
vector<holdspawn> ctfmode::holdspawns inherited
Referenced by ctfmode::addholdspawn(), game::ctfclientmode::drawhud(), ctfmode::resetflags(), game::ctfclientmode::senditems(), game::ctfclientmode::setup(), setupholdspawns(), game::ctfclientmode::spawnflag(), and spawnflag().
const int server::ctfservermode::INVISFLAGTIME = 20000 static
Referenced by update().
const int ctfmode::MAXFLAGS = 20 static inherited
Referenced by ctfmode::addflag().
const int ctfmode::MAXHOLDSPAWNS = 100 static inherited
Referenced by ctfmode::addholdspawn().
bool server::ctfservermode::notgotflags
Referenced by dropflag(), parseflags(), reset(), setup(), takeflag(), and update().
const int server::ctfservermode::RESETFLAGTIME = 10000 static
Referenced by update().
const int ctfmode::RESPAWNSECS = 5 static inherited
Referenced by canspawn(), and game::ctfclientmode::respawnwait().
int ctfmode::scores[2] inherited
Referenced by ctfmode::addscore(), ctfmode::getteamscores(), initclient(), game::ctfclientmode::parseflags(), ctfmode::resetflags(), ctfmode::setscore(), and ctfmode::totalscore().
The documentation for this struct was generated from the following files:
inexor/server/gamemode/ctf_server.hpp
inexor/server/gamemode/ctf_server.cpp