Inexor: vector< T, MINSIZE > Struct Template Reference
vector< T, MINSIZE > Struct Template Reference
Vector template.
#include <cube_vector.hpp>
Public Member Functions
vector ()
Default constructor.
vector (const vector &v)
Copy constructor.
~vector ()
Destructor.
vector< T > & operator= (const vector< T > &v)
Operator =.
T & add (const T &x)
Add new index to vector.
T & add ()
Add new EMPTY index to vector.
T & dup ()
Duplicate vector's last index.
void move (vector< T > &v)
copy vector from vector reference
bool inrange (size_t i) const
safety check: tests if index i exists in this vector
bool inrange (int i) const
safety check: tests if index i exists in this vector integer version: i must be greater (or equal to) 0
T & pop ()
get the last index and decrement the vector's size
T & last ()
get the last index
void drop ()
decrement vector's size and call the DESTRUCTOR of the template in the last index
bool empty () const
is this vector empty?
int capacity () const
return size of reserved memory
int length () const
return size of used memory
T & operator[] (int i)
[] array access operators
const T & operator[] (int i) const
void disown ()
resets all members to 0
void shrink (int i)
shrink vector memory size AND DELETE UNUSED MEMORY
void setsize (int i)
shrink vector memory size
void deletecontents ()
void deletearrays ()
T * getbuf ()
get the whole vector
const T * getbuf () const
get the whole vector as const value
bool inbuf (const T *e) const
template<class F >
void sort (F fun, int i=0, int n=-1)
sort the vector using quicksort template and sort criteria F
void sort ()
void sortname ()
void shuffle ()
mix the vector's indices randomly
void growbuf (int sz)
reallocate memory for vector (its size)
databuf< T > reserve (int sz)
reserved memory and returns vector of the reserved memory
void advance (int sz)
increase value of used bytes manually (?)
void addbuf (const databuf< T > &p)
increase value of used bytes by size of a vector
T * pad (int n)
void put (const T &v)
write bytes to vector
void put (const T *v, int n)
void remove (int i, int n)
remove indices from vector remove ordered?
T remove (int i)
remove element from given position.
T removeunordered (int i)
template<class U >
int find (const U &o)
find (first) index in vector.
void addunique (const T &o)
only add new element if it is unique.
void removeobj (const T &o)
remove an element if equal to to given one.
void replacewithlast (const T &o)
replace an index with the last vector index using a template parameter key
T & insert (int i, const T &e)
insertion functions
T * insert (int i, const T *e, int n)
void reverse ()
reverse all indices (first becomes last and so on...)
void buildheap ()
?
int upheap (int i)
?
T & addheap (const T &x)
?
int downheap (int i)
?
T removeheap ()
?
template<class K >
int htfind (const K &key)
similar to find but uses hashtable keys
Static Public Member Functions
static int heapparent (int i)
?
static int heapchild (int i)
Public Attributes
T * buf
data pointer
int alen
ALLOCATED memory size.
int ulen
USED memory size.
Detailed Description
template<class T, int MINSIZE = 8>
struct vector< T, MINSIZE >
Vector template.
a manual implementation of vector templates (self managing dynamic arrays which store one type).
Constructor & Destructor Documentation
template<class T, int MINSIZE = 8> vector< T, MINSIZE >::vector () inline
Default constructor.
sets all members to 0
template<class T, int MINSIZE = 8> vector< T, MINSIZE >::vector (const vector< T, MINSIZE > & v) inline
Copy constructor.
this constructor initialises the vector by copying another vector.
Parameters
v the vector from which data will be copied (call by reference).
template<class T, int MINSIZE = 8> vector< T, MINSIZE >::~vector () inline
Destructor.
Deletes all allocated memory and sets vector size to 0.
Member Function Documentation
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::add (const T & x) inline
Add new index to vector.
Pushs a new element at the end of the vector. Allocates memory automaticly if neccesary.
Parameters
x Element which will be added at the end May allocates a lot of memory without your notice
See Also
growbuf
Returns
The last element of the vector (which is parameter x)
Referenced by ai::avoidset::add(), aiman::addai(), addbatchedmodel(), addblendbrush(), addchange(), ctfmode::addflag(), addglobalparam(), addgrasstri(), addident(), addlight(), addlocalparam(), addname(), addnormal(), addpackagedir(), addreflection(), addskyverts(), addsleep(), addslotparam(), addtjoint(), addtnormal(), addtris(), addvbo(), verthash::addvert(), addwaterfallrefraction(), game::ctfclientmode::aicheck(), game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::collectclientmode::aifind(), game::ctfclientmode::aifind(), ai::anynode(), ai::assist(), server::autoteam(), aiman::balanceteams(), ai::wpcache::build(), server::buildworldstate(), skelmodel::skeleton::calcantipodes(), aiman::calcteams(), changedvars(), checkdynentcache(), checklightcache(), server::checklms(), server::checkmaps(), ai::checkothers(), ai::checkroute(), server::checkvotes(), editor::clear(), compileblock(), compileblockstr(), compileblocksub(), compilefloat(), compileident(), compileint(), compilelookup(), compilemain(), compilenull(), compilestatements(), compilestr(), compileval(), compileword(), conc(), editor::copyselectionto(), editor::del(), destroyva(), editor::editor(), endmodelbatches(), entadd(), escapestring(), explodelist(), server::extinfoteams(), filltexlist(), findanims(), findents(), findwaterplanes(), fonttex(), format(), genattriblocs(), animmodel::mesh::genBIH(), gencombinedname(), gencubeedges(), gengrassquads(), genlightmaptexs(), genmatsurfs(), genmergedfaces(), genprefabmesh(), genreservedlightmaptexs(), genskyfaces(), genuniformlocs(), vertmodel::vertmesh::genvbo(), skelmodel::skelmesh::genvbo(), md2::md2meshgroup::genverts(), pvsworker::genviewcell(), server::hideandseekservermode::getactiveplayers(), game::getbestplayers(), game::getbestteams(), collectmode_common::getteamscores(), ctfmode::getteamscores(), capturemode_common::getteamscores(), game::groupplayers(), applymenu::gui(), guibutton(), guiimage(), guilistslider(), guimodelpreview(), guinameslider(), guiplayerpreview(), guiprefabpreview(), game::ignore(), game::initclient(), game::listclients(), listdel(), listdir(), listfilter(), listsplice(), obj::objmeshgroup::load(), editor::load(), load_world(), md5::md5meshgroup::loadanim(), loadents(), md5::md5meshgroup::loadmesh(), loadmodel(), Slot::loadthumbnail(), loadvslot(), loopconc(), looplistconc(), mergepolys(), mergetexs(), mergevslot(), mmodel(), modifyoctaent(), modifyoctaentity(), moveplatform(), mpeditvslot(), game::newclient(), newentity(), newfont(), game::newprojectile(), newshader(), newva(), vacollect::optimize(), packvslots(), server::parsepacket(), server::bombservermode::parsespawnloc(), obj::objmeshgroup::parsevert(), pasteundoent(), game::ctfclientmode::pickholdspawn(), precachetextures(), preloadmodel(), preloadusedmapmodels(), prettylist(), propagatevslot(), pushfont(), pushgui(), ai::randomlink(), smd::smdmeshgroup::readnodes(), smd::smdmeshgroup::readtriangles(), vacollect::remapunlit(), ai::remapwaypoints(), renderalphageom(), rendercube(), rendermodel(), renderva(), ai::route(), runcode(), game::saveragdoll(), searchbinds(), editor::selectiontostring(), game::bombclientmode::senditems(), server::bombservermode::sendspawnlocs(), skelcommands< MDL >::setanimpart(), setslotshader(), server::bombservermode::setup(), setupmaterials(), sortlist(), sortmaterials(), strreplace(), ai::target(), ai::tryitem(), unpackvslot(), server::collectservermode::update(), updatedynentcache(), updateva(), updateval(), useeditor(), vshaderparam(), writebinds(), writecfg(), writecompletions(), and writeobj().
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::add () inline
Add new EMPTY index to vector.
Pushs a new EMPTY element at the end of the vector. Allocates memory automaticly if neccesary.
See Also
growbuf May allocates a lot of memory without your notice.
Returns
The last element of the vector (which is parameter x).
Referenced by vector< facebounds >::addheap(), vector< facebounds >::addunique(), vector< facebounds >::insert(), vector< facebounds >::operator=(), and vector< facebounds >::put().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::addbuf (const databuf< T > & p) inline
increase value of used bytes by size of a vector
Referenced by vector< facebounds >::put(), and smd::smdmeshgroup::readframes().
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::addheap (const T & x) inline
?
Referenced by ai::route().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::addunique (const T & o) inline
only add new element if it is unique.
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::advance (int sz) inline
increase value of used bytes manually (?)
Referenced by vector< facebounds >::addbuf(), addvbo(), compileblockstr(), loadpvs(), vector< facebounds >::pad(), and smd::smdmeshgroup::readframes().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::buildheap () inline
?
template<class T, int MINSIZE = 8> int vector< T, MINSIZE >::capacity () const inline
return size of reserved memory
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::deletearrays () inline
Referenced by flushpreloadedmodels(), and skelcommands< MDL >::setanimpart().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::deletecontents () inline
Referenced by server::bombservermode::cleanup(), game::clearragdolls(), and server::bombservermode::setup().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::disown () inline
resets all members to 0
Warning
This member does NOT clean up its memory!
Referenced by callcommand(), execute(), executeret(), and runcode().
template<class T, int MINSIZE = 8> int vector< T, MINSIZE >::downheap (int i) inline
?
Referenced by vector< facebounds >::buildheap(), and vector< facebounds >::removeheap().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::drop () inline
decrement vector's size and call the DESTRUCTOR of the template in the last index
call template's destructor
Referenced by server::buildworldstate(), game::getbestplayers(), game::getbestteams(), and vector< facebounds >::shrink().
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::dup () inline
Duplicate vector's last index.
Duplicates last index of the vector and appends it to the end. Allocates memory automaticly if neccesary.
See Also
growbuf
Note
May allocates a lot of memory without your notice.
Returns
The last element of the vector.
template<class T, int MINSIZE = 8> bool vector< T, MINSIZE >::empty () const inline
is this vector empty?
Referenced by addmergedverts(), server::addmessages(), server::addposition(), addskyverts(), game::ctfclientmode::aicheck(), game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), BIH::BIH(), ai::checkothers(), ai::checkroute(), clearchanges(), cleargui(), editline::combinelines(), editor::copyselectionto(), editor::del(), delblendbrush(), vector< facebounds >::deletearrays(), vector< facebounds >::deletecontents(), drawreflections(), edittex_(), vacollect::emptyva(), endmodelbatches(), endmodelquery(), smd::smdmeshgroup::smdmeshdata::finalize(), ai::findassist(), server::flushclientposition(), flushvbo(), freeoctaentities(), g3d_key(), g3d_mainmenu(), generategrass(), genuniformdefs(), applymenu::gui(), guilistslider(), guinameslider(), guionclear(), hoveringonent(), ai::hunt(), isheightmap(), listdel(), listsplice(), editor::load(), smd::smdmeshgroup::loadmesh(), menuprocess(), modifyoctaentity(), nextblendbrush(), game::nextfollow(), ai::parseinterests(), ai::patrol(), game::ctfclientmode::pickholdspawn(), popfont(), pushgui(), ai::randomlink(), ai::randomnode(), ai::render(), renderalphageom(), rendergrass(), rendermaterials(), renderwater(), ai::route(), vertcommands< MDL >::setanim(), skelcommands< MDL >::setanim(), and setdynlights().
template<class T, int MINSIZE = 8> template<class U > int vector< T, MINSIZE >::find (const U & o) inline
find (first) index in vector.
Referenced by addchange(), vector< facebounds >::addunique(), game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), ai::checkothers(), enttoggle(), filltexlist(), game::ignore(), isheightmap(), game::isignored(), loadmodel(), modifyoctaent(), moveplatform(), mpeditvslot(), packvslots(), precachetextures(), preloadusedmapmodels(), ai::randomlink(), game::renderplayer(), showgui(), ai::target(), game::unignore(), updatedynentcache(), and writeobj().
template<class T, int MINSIZE = 8> T* vector< T, MINSIZE >::getbuf () inline
get the whole vector
Referenced by ai::avoidset::add(), server::addmessages(), server::addposition(), addskyverts(), BIH::BIH(), ai::wpcache::build(), callcommand(), Slot::combinetextures(), compilecode(), conc(), escapestring(), execute(), executeret(), smd::smdmeshgroup::smdmeshdata::finalize(), server::flushclientposition(), flushvbo(), format(), gendynlightvariant(), generategrass(), gengenericvariant(), genshadowmapvariant(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), genwatervariant(), inexor::sound::soundconfig::hasslot(), game::listclients(), listdel(), listfilter(), listsplice(), md2::md2meshgroup::load(), smd::smdmeshgroup::loadanim(), Slot::loadthumbnail(), loopconc(), looplistconc(), vacollect::optimize(), packeditinfo(), packundo(), prettylist(), smd::smdmeshgroup::readframes(), runcode(), savepvs(), editor::selectiontostring(), game::sendmessages(), skelcommands< MDL >::setanimpart(), vacollect::setupdata(), strreplace(), and server::collectservermode::update().
template<class T, int MINSIZE = 8> const T* vector< T, MINSIZE >::getbuf () const inline
get the whole vector as const value
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::growbuf (int sz) inline
reallocate memory for vector (its size)
Referenced by vector< facebounds >::add(), vector< facebounds >::dup(), vector< facebounds >::insert(), vector< facebounds >::move(), vector< facebounds >::operator=(), and vector< facebounds >::reserve().
template<class T, int MINSIZE = 8> static int vector< T, MINSIZE >::heapchild (int i) inline static
Referenced by vector< facebounds >::downheap().
template<class T, int MINSIZE = 8> static int vector< T, MINSIZE >::heapparent (int i) inline static
?
Referenced by vector< facebounds >::upheap().
template<class T, int MINSIZE = 8> template<class K > int vector< T, MINSIZE >::htfind (const K & key) inline
similar to find but uses hashtable keys
Referenced by aiman::calcteams(), server::extinfoteams(), and game::getbestteams().
template<class T, int MINSIZE = 8> bool vector< T, MINSIZE >::inbuf (const T * e) const inline
template<class T, int MINSIZE = 8> bool vector< T, MINSIZE >::inrange (size_t i) const inline
safety check: tests if index i exists in this vector
Referenced by game::ctfclientmode::aidefend(), game::ctfclientmode::aihomerun(), game::ctfclientmode::aipursue(), canpaintblendmap(), ai::checkroute(), checksleep(), game::clientdisconnected(), ai::drawroute(), game::ctfclientmode::dropflag(), getblendbrushname(), game::getclient(), getcurtex(), getmminfo(), getselpos(), htcmp(), ai::hunt(), game::ctfclientmode::invisflag(), md5::md5meshgroup::loadanim(), iqm::iqmmeshgroup::loadiqmanims(), loadmapmodel(), loadmodel(), mapmodelname(), modifyoctaent(), newentity(), nextblendbrush(), game::ctfclientmode::parseflags(), game::parseplayer(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readnodes(), renderblendbrush(), game::ctfclientmode::rendergame(), rendertexturepanel(), game::ctfclientmode::resetflag(), LocalShaderParam::resolve(), game::ctfclientmode::returnflag(), game::sayprivate(), game::ctfclientmode::scoreflag(), server::ctfservermode::scoreflag(), game::ctfclientmode::takeflag(), server::ctfservermode::takeflag(), and tofronttex().
template<class T, int MINSIZE = 8> bool vector< T, MINSIZE >::inrange (int i) const inline
safety check: tests if index i exists in this vector integer version: i must be greater (or equal to) 0
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::insert (int i, const T & e) inline
insertion functions
Referenced by adddynlight(), Shader::addvariant(), ai::anynode(), finddynlights(), editor::insert(), editor::insertallfrom(), pushgui(), tofronttex(), and useeditor().
template<class T, int MINSIZE = 8> T* vector< T, MINSIZE >::insert (int i, const T * e, int n) inline
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::last () inline
get the last index
Referenced by aiman::balanceteams(), aiman::chooseteam(), currentfocus(), endmodelquery(), entdrag(), g3d_mainmenu(), game::getbestplayers(), game::getbestteams(), guionclear(), hoveringonent(), and newfont().
template<class T, int MINSIZE = 8> int vector< T, MINSIZE >::length () const inline
return size of used memory
Referenced by ai::avoidset::add(), addbatchedmodel(), addblendbrush(), addchange(), ctfmode::addflag(), addlocalparam(), server::addmaprotations(), server::addmessages(), addnormal(), server::addposition(), addskyverts(), addtjoint(), addtnormal(), Shader::addvariant(), verthash::addvert(), game::ctfclientmode::aicheck(), aiman::balanceteams(), BIH::BIH(), ai::wpcache::build(), server::buildworldstate(), animmodel::part::calcanim(), skelmodel::skeleton::calcantipodes(), ragdolldata::calcboundsphere(), pvsworker::calcpvs(), aiman::calcteams(), server::bombservermode::canspawn(), server::checklms(), server::checkmaps(), ai::checkroute(), aiman::chooseteam(), clearblendbrushes(), cleargui(), clearguis(), commitchanges(), geombatch::compare(), comparevslot(), compileblock(), compileblockstr(), compilecode(), compileval(), editor::copyselectionto(), currentfocus(), editor::currentline(), editor::del(), delblendbrush(), editor::draw(), edittex_(), game::edittrigger(), endmodelbatches(), endmodelquery(), enlargemap(), entautoview(), explodelist(), filltexlist(), smd::smdmeshgroup::smdmeshdata::finalize(), ai::findassist(), finddynlights(), findentity(), findlights(), findreflectedvas(), findvisiblevas(), findwaterplanes(), server::flushclientposition(), flushpreloadedmodels(), flushvbo(), fontalias(), fonttex(), g3d_key(), gencubeedges(), generategrass(), gengrassquads(), genlightmaptexs(), genpvs(), genreservedlightmaptexs(), vertmodel::vertmesh::genvbo(), skelmodel::skelmesh::genvbo(), vertmodel::vertmeshgroup::genvbo(), skelmodel::skelmeshgroup::genvbo(), md2::md2meshgroup::genverts(), pvsworker::genviewcell(), game::getbestplayers(), game::getbestteams(), getselpos(), guilistslider(), guimodelpreview(), guinameslider(), inexor::sound::soundconfig::hasslot(), haveselent(), editor::hit(), ai::hunt(), server::ctfservermode::initclient(), server::hideandseekservermode::initplayers(), editor::insert(), editor::insertallfrom(), game::iterdynents(), editor::key(), editor::limitscrolly(), listdel(), listfilter(), listsplice(), obj::objmeshgroup::load(), md2::md2meshgroup::load(), editor::load(), md5::md5meshgroup::loadanim(), smd::smdmeshgroup::loadanim(), md5::md5meshgroup::loadmesh(), smd::smdmeshgroup::loadmesh(), loopconc(), looplistconc(), ai::makeroute(), mapmodelreset(), menuprocess(), mergepolys(), mergetexs(), ragdolldata::move(), moveplatform(), mpeditent(), mpeditvslot(), game::newclient(), newentity(), newundoent(), nextblendbrush(), game::nextfollow(), game::numdynents(), vector< facebounds >::operator=(), vacollect::optimize(), packeditinfo(), packundo(), ai::parseinterests(), pasteundoent(), game::ctfclientmode::pickholdspawn(), precachetextures(), preloadusedmapmodels(), pushgui(), pvsstats(), queryreflections(), ai::randomlink(), ai::randomnode(), smd::smdmeshgroup::readtriangles(), editor::region(), game::removeprojectiles(), ai::render(), renderalphageom(), rendercube(), renderentselection(), rendergeom(), rendergeommultipass(), rendermodel(), renderreflectedskyvas(), game::renderscoreboard(), renderva(), restoregui(), save_world(), savepvs(), savevslot(), game::scoregroupcmp(), searchbinds(), editor::selectiontostring(), game::bombclientmode::senditems(), game::ctfclientmode::senditems(), game::sendmessages(), game::sendpositions(), server::bombservermode::sendspawnlocs(), server::servercompatible(), skelcommands< MDL >::setanimpart(), server::ctfservermode::setup(), game::ctfclientmode::setup(), vacollect::setupdata(), server::ctfservermode::setupholdspawns(), setupmaterials(), ragdollskel::setuprotfrictions(), setva(), shader(), shrinkmap(), sortlist(), strreplace(), vacollect::texsort(), ragdolldata::tryunstick(), server::collectservermode::update(), updateva(), variantshader(), and writeobj().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::move (vector< T > & v) inline
copy vector from vector reference
Referenced by vacollect::setupdata(), and updateva().
template<class T, int MINSIZE = 8> vector<T>& vector< T, MINSIZE >::operator= (const vector< T > & v) inline
Operator =.
Resets own memory and copies all data from the other vector.
Parameters
v The vector from which data will be copied.
Returns
Returns a pointer to itself.
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::operator[] (int i) inline
[] array access operators
template<class T, int MINSIZE = 8> const T& vector< T, MINSIZE >::operator[] (int i) const inline
template<class T, int MINSIZE = 8> T* vector< T, MINSIZE >::pad (int n) inline
Referenced by addlocalparam(), game::edittrigger(), packundo(), and packvslots().
template<class T, int MINSIZE = 8> T& vector< T, MINSIZE >::pop () inline
get the last index and decrement the vector's size
Referenced by addgrasstri(), ai::checkroute(), clearblendbrushes(), compileblock(), vector< facebounds >::deletearrays(), vector< facebounds >::deletecontents(), endmodelquery(), enlargemap(), freeoctaentities(), ai::hunt(), editor::load(), load_world(), loadents(), popfont(), popgui(), shrinkmap(), and updateva().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::put (const T & v) inline
write bytes to vector
Referenced by ai::avoidset::add(), game::addmsg(), compilestr(), conc(), game::edittrigger(), escapestring(), gendynlightvariant(), genfogshader(), gengenericvariant(), genshadowmapvariant(), genuniformdefs(), pvsworker::genviewcell(), genwatervariant(), game::listclients(), listdel(), listfilter(), listsplice(), loopconc(), looplistconc(), packundo(), packvslot(), prettylist(), searchbinds(), editor::selectiontostring(), and vacollect::setupdata().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::put (const T * v, int n) inline
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::remove (int i, int n) inline
remove indices from vector remove ordered?
Referenced by aiman::balanceteams(), checksleep(), clearchanges(), cleardynlights(), compactmruvslots(), delblendbrush(), enttoggle(), game::explodeeffects(), filltexlist(), flusheditors(), game::moveragdolls(), removegui(), editor::removelines(), game::removeprojectiles(), removetrackeddynlights(), tofronttex(), game::updateprojectiles(), and useeditor().
template<class T, int MINSIZE = 8> T vector< T, MINSIZE >::remove (int i) inline
remove element from given position.
Returns
the removed element.
template<class T, int MINSIZE = 8> T vector< T, MINSIZE >::removeheap () inline
?
Referenced by ai::route().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::removeobj (const T & o) inline
remove an element if equal to to given one.
Referenced by game::clientdisconnected(), copyundoents(), aiman::deleteai(), destroyva(), modifyoctaentity(), vacollect::optimize(), and game::unignore().
template<class T, int MINSIZE = 8> T vector< T, MINSIZE >::removeunordered (int i) inline
Referenced by aiman::balanceteams(), server::cleanworldstate(), ai::findassist(), modifyoctaent(), ai::parseinterests(), ai::randomnode(), vector< facebounds >::removeheap(), and server::bombservermode::sendspawnlocs().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::replacewithlast (const T & o) inline
replace an index with the last vector index using a template parameter key
template<class T, int MINSIZE = 8> databuf<T> vector< T, MINSIZE >::reserve (int sz) inline
reserved memory and returns vector of the reserved memory
Referenced by addvbo(), callcommand(), compileblockstr(), compilecode(), execute(), executeret(), loadpvs(), packundo(), vector< facebounds >::pad(), vector< facebounds >::put(), smd::smdmeshgroup::readframes(), and runcode().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::reverse () inline
reverse all indices (first becomes last and so on...)
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::setsize (int i) inline
shrink vector memory size
Referenced by addbatchedmodel(), addmergedverts(), server::addmessages(), server::addposition(), addreflection(), addskyverts(), addwaterfallrefraction(), game::ctfclientmode::aicheck(), game::captureclientmode::aidefend(), game::ctfclientmode::aidefend(), game::captureclientmode::aifind(), game::ctfclientmode::aifind(), game::ctfclientmode::aihomerun(), allchanged(), checklightcache(), ai::checkothers(), ai::checkroute(), cleanreflection(), ai::avoidset::clear(), ai::aiinfo::clear(), vacollect::clear(), cleardynlights(), clearlightcache(), clearnormals(), clearpvs(), verthash::clearverts(), server::dodamage(), endmodelquery(), escapestring(), ai::find(), ai::findassist(), finddynlights(), findlights(), findtjoints(), findwaterplanes(), server::flushclientposition(), flushvbo(), game::gamedisconnect(), gendynlightvariant(), generategrass(), md2::md2meshgroup::genverts(), pvsworker::genviewcell(), game::groupplayers(), hmapcancel(), iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), moveplatform(), newshader(), octarender(), server::parsepacket(), queryreflections(), ai::randomlink(), ai::randomnode(), vector< facebounds >::removeobj(), renderalphageom(), renderfoggedvas(), server::clientinfo::reset(), resetbatches(), resetmap(), ai::route(), game::sendmessages(), setva(), startmodelbatches(), server::suicide(), and ai::target().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::shrink (int i) inline
shrink vector memory size AND DELETE UNUSED MEMORY
Referenced by checkdynentcache(), editor::clear(), applymenu::clear(), game::clearprojectiles(), clearsleep(), emptymap(), entcancel(), Shader::force(), load_world(), mapmodelreset(), menuprocess(), newfont(), vector< facebounds >::operator=(), vacollect::optimize(), game::rendergame(), ctfmode::resetflags(), resetslotshader(), setshader(), shader(), and vector< facebounds >::~vector().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::shuffle () inline
mix the vector's indices randomly
Referenced by server::bombservermode::sendspawnlocs().
template<class T, int MINSIZE = 8> template<class F > void vector< T, MINSIZE >::sort (F fun, int i = 0, int n = -1) inline
sort the vector using quicksort template and sort criteria F
Referenced by aiman::calcteams(), server::checkmaps(), endmodelbatches(), generategrass(), game::getbestplayers(), game::getbestteams(), game::groupplayers(), vacollect::optimize(), skelcommands< MDL >::setanimpart(), sortlist(), sortmaterials(), writecompletions(), and writeobj().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::sort () inline
Referenced by vector< facebounds >::sort(), and vector< facebounds >::sortname().
template<class T, int MINSIZE = 8> void vector< T, MINSIZE >::sortname () inline
Referenced by changedvars(), writebinds(), and writecfg().
template<class T, int MINSIZE = 8> int vector< T, MINSIZE >::upheap (int i) inline
?
Referenced by vector< facebounds >::addheap(), and ai::route().
Member Data Documentation
template<class T, int MINSIZE = 8> int vector< T, MINSIZE >::alen
ALLOCATED memory size.
Referenced by vector< facebounds >::add(), vector< facebounds >::capacity(), vector< facebounds >::disown(), vector< facebounds >::dup(), vector< facebounds >::growbuf(), vector< facebounds >::insert(), vector< facebounds >::move(), vector< facebounds >::operator=(), and vector< facebounds >::reserve().
template<class T, int MINSIZE = 8> T* vector< T, MINSIZE >::buf
data pointer
Referenced by vector< facebounds >::add(), vector< facebounds >::addheap(), vector< facebounds >::disown(), vector< facebounds >::downheap(), vector< facebounds >::drop(), vector< facebounds >::dup(), vector< facebounds >::find(), vector< facebounds >::getbuf(), vector< facebounds >::growbuf(), vector< facebounds >::htfind(), vector< facebounds >::inbuf(), vector< facebounds >::insert(), vector< facebounds >::last(), vector< facebounds >::move(), vector< facebounds >::operator[](), vector< facebounds >::pad(), vector< facebounds >::pop(), vector< facebounds >::put(), vector< facebounds >::remove(), vector< facebounds >::removeobj(), vector< facebounds >::removeunordered(), vector< facebounds >::replacewithlast(), vector< facebounds >::reserve(), vector< facebounds >::reverse(), vector< facebounds >::shuffle(), vector< facebounds >::sort(), vector< facebounds >::upheap(), and vector< facebounds >::~vector().
template<class T, int MINSIZE = 8> int vector< T, MINSIZE >::ulen
USED memory size.
Referenced by vector< facebounds >::add(), vector< facebounds >::addheap(), vector< facebounds >::advance(), vector< facebounds >::buildheap(), vector< facebounds >::disown(), vector< facebounds >::downheap(), vector< facebounds >::drop(), vector< facebounds >::dup(), vector< facebounds >::empty(), vector< facebounds >::find(), vector< facebounds >::htfind(), vector< facebounds >::inbuf(), vector< facebounds >::inrange(), vector< facebounds >::insert(), vector< facebounds >::last(), vector< facebounds >::length(), vector< facebounds >::move(), vector< facebounds >::operator[](), vector< facebounds >::pop(), vector< facebounds >::remove(), vector< facebounds >::removeheap(), vector< facebounds >::removeobj(), vector< facebounds >::removeunordered(), vector< facebounds >::replacewithlast(), vector< facebounds >::reserve(), vector< facebounds >::reverse(), vector< facebounds >::setsize(), vector< facebounds >::shrink(), vector< facebounds >::shuffle(), and vector< facebounds >::sort().
The documentation for this struct was generated from the following file:
inexor/shared/cube_vector.hpp