Inexor: blobrenderer Struct Reference
blobrenderer Struct Reference
Public Member Functions
blobrenderer (const char *texname)
~blobrenderer ()
void cleanup ()
void init (int tris)
bool freeblob ()
blobinfo & newblob (const vec &o, float radius)
void dupblob ()
int addvert (const vec &pos)
void addtris (const vec *v, int numv)
void gentris (cube &cu, int orient, const ivec &o, int size, materialsurface *mat=nullptr, int vismask=0)
void findmaterials (vtxarray *va)
void findescaped (cube *cu, const ivec &o, int size, int escaped)
void gentris (cube *cu, const ivec &o, int size, int escaped=0)
blobinfo * addblob (const vec &o, float radius, float fade)
void fadeblob (blobinfo *b, float fade)
void renderblob (const vec &o, float radius, float fade)
void flushblobs ()
Static Public Member Functions
template<int C>
static int split (const vec *in, int numin, float below, float above, vec *out)
template<int C>
static int clip (const vec *in, int numin, float below, float above, vec *out)
static void setuprenderstate ()
static void cleanuprenderstate ()
static void reset ()
Public Attributes
const char * texname
Texture * tex
ushort * cache
int cachesize
blobinfo * blobs
int maxblobs
int startblob
int endblob
blobvert * verts
int maxverts
int startvert
int endvert
int availverts
ushort * indexes
int maxindexes
int startindex
int endindex
int availindexes
GLuint ebo
GLuint vbo
ushort * edata
blobvert * vdata
int numedata
int numvdata
blobinfo * startrender
blobinfo * endrender
blobinfo * lastblob
vec blobmin
vec blobmax
ivec bbmin
ivec bbmax
float blobalphalow
float blobalphahigh
uchar blobalpha
Static Public Attributes
static int lastreset = 0
static blobrenderer * lastrender = nullptr
Constructor & Destructor Documentation
blobrenderer::blobrenderer (const char * texname) inline
blobrenderer::~blobrenderer () inline
References blobs, cache, DELETEA, indexes, and verts.
Member Function Documentation
blobinfo* blobrenderer::addblob (const vec & o, float radius, float fade) inline
References bbmax, bbmin, BL_DUP, blobalpha, blobalphahigh, blobalphalow, blobmax, blobmin, blobs, endblob, blobinfo::flags, gentris(), lastblob, newblob(), worldroot, and worldsize.
Referenced by renderblob().
void blobrenderer::addtris (const vec * v, int numv) inline
References addvert(), availindexes, availverts, cur, dupblob(), gle::end(), blobinfo::endindex, endindex, blobinfo::endvert, endvert, freeblob(), indexes, lastblob, loopk, maxindexes, maxverts, and inexor::rpc::min().
Referenced by gentris().
int blobrenderer::addvert (const vec & pos) inline
References blobalpha, blobalphahigh, blobalphalow, blobmax, blobmin, blobvert::color, endvert, blobvert::pos, blobvert::tc, and verts.
Referenced by addtris().
void blobrenderer::cleanup () inline
References DELETEA, ebo, edata, endrender, glDeleteBuffers_, numedata, numvdata, startrender, vbo, and vdata.
Referenced by cleanupblobs(), and init().
static void blobrenderer::cleanuprenderstate () inline static
References gle::clearebo(), gle::clearvbo(), disablepolygonoffset(), and glversion.
Referenced by flushblobs().
template<int C> static int blobrenderer::clip (const vec * in, int numin, float below, float above, vec * out) inline static
References vec::add(), C, loopi(), vec::mul(), and vec::sub().
void blobrenderer::dupblob () inline
References BL_DUP, blobinfo::endindex, endindex, blobinfo::endvert, endvert, blobinfo::flags, lastblob, newblob(), blobinfo::o, blobinfo::radius, blobinfo::startindex, and blobinfo::startvert.
Referenced by addtris().
void blobrenderer::fadeblob (blobinfo * b, float fade) inline
References BL_DUP, blobs, gle::end(), endblob, blobinfo::endvert, blobinfo::flags, maxblobs, blobinfo::millis, blobinfo::o, startblob, blobinfo::startvert, totalmillis, and verts.
Referenced by renderblob().
void blobrenderer::findescaped (cube * cu, const ivec & o, int size, int escaped) inline
References gentris(), loopi(), loopj, and cube::merged.
Referenced by gentris().
void blobrenderer::findmaterials (vtxarray * va) inline
References blobmax, blobmin, C, materialsurface::csize, dimension, gentris(), isclipped, loopi(), vtxarray::matbuf, materialsurface::material, MATF_VOLUME, vtxarray::matsurfs, inexor::rpc::max(), materialsurface::o, O_BOTTOM, materialsurface::orient, R, materialsurface::rsize, and materialsurface::skip.
Referenced by gentris().
void blobrenderer::flushblobs () inline
References gle::bindebo(), gle::bindvbo(), BL_RENDER, blobs, blobvert::color, ebo, edata, endindex, endrender, GL_MAP_INVALIDATE_RANGE_BIT, GL_MAP_UNSYNCHRONIZED_BIT, GL_MAP_WRITE_BIT, glBufferData_, glBufferSubData_, glDrawRangeElements_, glGenBuffers_, glMapBufferRange_, glUnmapBuffer_, glversion, Texture::id, indexes, lastrender, maxblobs, maxindexes, maxverts, numedata, numvdata, blobvert::pos, setuprenderstate(), startrender, blobvert::tc, tex, vbo, vdata, and verts.
Referenced by flushblobs(), and freeblob().
bool blobrenderer::freeblob () inline
References availindexes, availverts, BL_RENDER, blobs, blobinfo::endindex, blobinfo::endvert, blobinfo::flags, flushblobs(), lastblob, lastreset, maxblobs, maxindexes, maxverts, blobinfo::millis, startblob, blobinfo::startindex, startindex, blobinfo::startvert, and startvert.
Referenced by addtris(), and newblob().
void blobrenderer::gentris (cube & cu, int orient, const ivec & o, int size, materialsurface * mat = nullptr, int vismask = 0) inline
References vec::add(), addtris(), blobmax, blobmin, CLIPSIDE, DEFAULT_SKY, dimension, cube::ext, f(), faceconvexity(), flataxisface(), GENFACEVERTS, genfaceverts(), loopj, loopl, ivec::mask(), MAT_AIR, MAT_ALPHA, cube::material, vec::max(), MAXFACEVERTS, cube::merged, vec::min(), vec::mul(), sphere::numverts, surfaceinfo::numverts, orient, ivec::shl(), cubeext::surfaces, cube::texture, verts, surfaceinfo::verts, cubeext::verts(), and visibleface().
Referenced by addblob(), findescaped(), findmaterials(), and gentris().
void blobrenderer::gentris (cube * cu, const ivec & o, int size, int escaped = 0) inline
References bbmax, bbmin, ext(), cube::ext, findescaped(), findmaterials(), gentris(), loopi(), loopj, vtxarray::matsurfs, cube::merged, octaboxoverlap(), and cubeext::va.
void blobrenderer::init (int tris) inline
References availindexes, availverts, blobs, cache, cachesize, cleanup(), DELETEA, endblob, endindex, endvert, indexes, maxblobs, maxindexes, maxverts, inexor::rpc::min(), startblob, startindex, startvert, tex, texname, textureload(), and verts.
blobinfo& blobrenderer::newblob (const vec & o, float radius) inline
References blobs, endblob, blobinfo::endindex, endindex, blobinfo::endvert, endvert, blobinfo::flags, freeblob(), lastblob, maxblobs, blobinfo::millis, blobinfo::next, blobinfo::o, blobinfo::radius, startblob, blobinfo::startindex, blobinfo::startvert, and totalmillis.
Referenced by addblob(), and dupblob().
void blobrenderer::renderblob (const vec & o, float radius, float fade) inline
References addblob(), BL_DUP, BL_RENDER, blobs, cache, cachesize, blobvert::color, endblob, blobinfo::endindex, endrender, blobinfo::endvert, f(), fadeblob(), blobinfo::flags, glDrawRangeElements_, glversion, tiger::hash(), Texture::id, indexes, initblobs(), lastrender, maxblobs, blobinfo::millis, blobinfo::next, numedata, numvdata, blobvert::pos, blobinfo::radius, setuprenderstate(), startblob, blobinfo::startindex, startrender, blobinfo::startvert, blobvert::tc, tex, verts, and xtravertsva.
Referenced by renderblob().
static void blobrenderer::reset () inline static
References lastreset, and totalmillis.
Referenced by resetblobs().
static void blobrenderer::setuprenderstate () inline static
References enablepolygonoffset(), foggedshader, and Shader::set().
Referenced by flushblobs(), and renderblob().
template<int C> static int blobrenderer::split (const vec * in, int numin, float below, float above, vec * out) inline static
References vec::add(), C, loopi(), vec::mul(), and vec::sub().
Member Data Documentation
int blobrenderer::availindexes
Referenced by addtris(), freeblob(), and init().
int blobrenderer::availverts
Referenced by addtris(), freeblob(), and init().
ivec blobrenderer::bbmax
Referenced by addblob(), and gentris().
ivec blobrenderer::bbmin
Referenced by addblob(), and gentris().
uchar blobrenderer::blobalpha
Referenced by addblob(), and addvert().
float blobrenderer::blobalphahigh
Referenced by addblob(), and addvert().
float blobrenderer::blobalphalow
Referenced by addblob(), and addvert().
vec blobrenderer::blobmax
Referenced by addblob(), addvert(), findmaterials(), and gentris().
vec blobrenderer::blobmin
Referenced by addblob(), addvert(), findmaterials(), and gentris().
blobinfo* blobrenderer::blobs
Referenced by addblob(), fadeblob(), flushblobs(), freeblob(), init(), newblob(), renderblob(), and ~blobrenderer().
ushort* blobrenderer::cache
Referenced by init(), renderblob(), and ~blobrenderer().
int blobrenderer::cachesize
Referenced by init(), and renderblob().
GLuint blobrenderer::ebo
Referenced by cleanup(), and flushblobs().
ushort* blobrenderer::edata
Referenced by cleanup(), and flushblobs().
int blobrenderer::endblob
Referenced by addblob(), fadeblob(), init(), newblob(), and renderblob().
int blobrenderer::endindex
Referenced by addtris(), dupblob(), flushblobs(), init(), and newblob().
blobinfo * blobrenderer::endrender
Referenced by cleanup(), flushblobs(), and renderblob().
int blobrenderer::endvert
Referenced by addtris(), addvert(), dupblob(), init(), and newblob().
ushort* blobrenderer::indexes
Referenced by addtris(), flushblobs(), init(), renderblob(), and ~blobrenderer().
blobinfo* blobrenderer::lastblob
Referenced by addblob(), addtris(), dupblob(), freeblob(), and newblob().
blobrenderer * blobrenderer::lastrender = nullptr static
Referenced by flushblobs(), and renderblob().
int blobrenderer::lastreset = 0 static
Referenced by freeblob(), and reset().
int blobrenderer::maxblobs
Referenced by fadeblob(), flushblobs(), freeblob(), init(), newblob(), and renderblob().
int blobrenderer::maxindexes
Referenced by addtris(), flushblobs(), freeblob(), and init().
int blobrenderer::maxverts
Referenced by addtris(), flushblobs(), freeblob(), and init().
int blobrenderer::numedata
Referenced by cleanup(), flushblobs(), and renderblob().
int blobrenderer::numvdata
Referenced by cleanup(), flushblobs(), and renderblob().
int blobrenderer::startblob
Referenced by fadeblob(), freeblob(), init(), newblob(), and renderblob().
int blobrenderer::startindex
Referenced by freeblob(), and init().
blobinfo* blobrenderer::startrender
Referenced by cleanup(), flushblobs(), and renderblob().
int blobrenderer::startvert
Referenced by freeblob(), and init().
Texture* blobrenderer::tex
Referenced by flushblobs(), init(), and renderblob().
const char* blobrenderer::texname
Referenced by init().
GLuint blobrenderer::vbo
Referenced by cleanup(), and flushblobs().
blobvert* blobrenderer::vdata
Referenced by cleanup(), and flushblobs().
blobvert* blobrenderer::verts
Referenced by addvert(), fadeblob(), flushblobs(), gentris(), init(), renderblob(), and ~blobrenderer().
The documentation for this struct was generated from the following file:
inexor/engine/blob.cpp