Inexor: skelmodel::skelmesh Struct Reference
skelmodel::skelmesh Struct Reference
#include <skelmodel.hpp>
Public Member Functions
skelmesh ()
~skelmesh () override
int addblendcombo (const blendcombo &c)
void smoothnorms (float limit=0, bool areaweight=true)
void buildnorms (bool areaweight=true)
void calctangents (bool areaweight=true)
void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m) override
void genBIH (BIH::mesh &m) override
void assignvert (vvertbump &vv, int j, vert &v, blendcombo &c)
void assignvert (vvertbumpw &vv, int j, vert &v, blendcombo &c)
template<class T >
int genvbo (vector< ushort > &idxs, int offset, vector< T > &vverts)
template<class T >
int genvbo (vector< ushort > &idxs, int offset, vector< T > &vverts, int *htdata, int htlen)
int genvbo (vector< ushort > &idxs, int offset)
template<class T >
void fillverts (T *vdata)
void interpverts (const dualquat *RESTRICT bdata1, const dualquat *RESTRICT bdata2, bool tangents, void *RESTRICT vdata, skin &s)
void setshader (Shader *s) override
void render (const animstate *as, skin &s, vbocacheentry &vc)
Static Public Member Functions
static void assignvert (vvertn &vv, int j, vert &v, blendcombo &c)
static void assignvert (vvertnw &vv, int j, vert &v, blendcombo &c)
template<class T >
static void fillvert (T &vv, int j, vert &v)
Public Attributes
vert * verts
bumpvert * bumpverts
tri * tris
int numverts
int numtris
int maxweights
int voffset
int eoffset
int elen
ushort minvert
ushort maxvert
Constructor & Destructor Documentation
skelmodel::skelmesh::skelmesh () inline
skelmodel::skelmesh::~skelmesh () inline override
References bumpverts, DELETEA, tris, and verts.
Member Function Documentation
int skelmodel::skelmesh::addblendcombo (const blendcombo & c) inline
References inexor::rpc::max(), maxweights, and skelmodel::blendcombo::size().
Referenced by md5::md5mesh::buildverts(), iqm::iqmmeshgroup::loadiqmmeshes(), and smd::smdmeshgroup::readtriangles().
static void skelmodel::skelmesh::assignvert (vvertn & vv, int j, vert & v, blendcombo & c) inline static
References skelmodel::vert::norm, skelmodel::vvertn::norm, skelmodel::vert::pos, skelmodel::vvert::pos, skelmodel::vert::tc, and skelmodel::vvert::tc.
Referenced by genvbo().
void skelmodel::skelmesh::assignvert (vvertbump & vv, int j, vert & v, blendcombo & c) inline
References bumpverts, skelmodel::vert::pos, skelmodel::vvert::pos, skelmodel::vvertbump::tangent, skelmodel::bumpvert::tangent, skelmodel::vert::tc, and skelmodel::vvert::tc.
static void skelmodel::skelmesh::assignvert (vvertnw & vv, int j, vert & v, blendcombo & c) inline static
References skelmodel::vert::norm, skelmodel::vvertn::norm, skelmodel::vert::pos, skelmodel::vvert::pos, skelmodel::blendcombo::serialize(), skelmodel::vert::tc, and skelmodel::vvert::tc.
void skelmodel::skelmesh::assignvert (vvertbumpw & vv, int j, vert & v, blendcombo & c) inline
References bumpverts, skelmodel::vert::pos, skelmodel::vvert::pos, skelmodel::blendcombo::serialize(), skelmodel::vvertbump::tangent, skelmodel::bumpvert::tangent, skelmodel::vert::tc, and skelmodel::vvert::tc.
void skelmodel::skelmesh::buildnorms (bool areaweight = true) inline
References animmodel::mesh::buildnorms(), numtris, numverts, tris, and verts.
Referenced by md5::md5meshgroup::loadmesh().
void skelmodel::skelmesh::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline override
References loopi(), loopj, inexor::rpc::max(), inexor::rpc::min(), numverts, matrix4x3::transform(), and verts.
void skelmodel::skelmesh::calctangents (bool areaweight = true) inline
References bumpverts, animmodel::mesh::calctangents(), numtris, numverts, tris, and verts.
template<class T > static void skelmodel::skelmesh::fillvert (T & vv, int j, vert & v) inline static
References skelmodel::vert::tc.
Referenced by fillverts().
template<class T > void skelmodel::skelmesh::fillverts (T * vdata) inline
References fillvert(), loopi(), numverts, verts, and voffset.
void skelmodel::skelmesh::genBIH (BIH::mesh & m) inline override
References BIH::mesh::numtris, numtris, skelmodel::vert::pos, BIH::mesh::pos, BIH::mesh::posstride, skelmodel::vert::tc, BIH::mesh::tc, BIH::mesh::tcstride, BIH::mesh::tris, tris, and verts.
template<class T > int skelmodel::skelmesh::genvbo (vector< ushort > & idxs, int offset, vector< T > & vverts) inline
References vector< T, MINSIZE >::add(), assignvert(), elen, eoffset, vector< T, MINSIZE >::length(), loopi(), loopj, maxvert, minvert, numtris, numverts, tris, verts, and voffset.
template<class T > int skelmodel::skelmesh::genvbo (vector< ushort > & idxs, int offset, vector< T > & vverts, int * htdata, int htlen) inline
References vector< T, MINSIZE >::add(), assignvert(), skelmodel::vert::blend, elen, eoffset, hthash(), vector< T, MINSIZE >::length(), loopi(), loopj, loopk, inexor::rpc::max(), maxvert, inexor::rpc::min(), minvert, numtris, skelmodel::vert::pos, anonymous_namespace{utilTest.cpp}::t(), tris, skelmodel::tri::vert, verts, and voffset.
int skelmodel::skelmesh::genvbo (vector< ushort > & idxs, int offset) inline
References vector< T, MINSIZE >::add(), elen, eoffset, skelmodel::vert::interpindex, vector< T, MINSIZE >::length(), loopi(), loopj, maxvert, minvert, numtris, numverts, anonymous_namespace{utilTest.cpp}::t(), tris, skelmodel::tri::vert, verts, and voffset.
void skelmodel::skelmesh::interpverts (const dualquat *RESTRICT bdata1, const dualquat *RESTRICT bdata2, bool tangents, void *RESTRICT vdata, skin & s) inline
References bumpverts, IPLOOP, and skelmodel::vvertn::norm.
Referenced by skelmodel::skelmeshgroup::render().
void skelmodel::skelmesh::render (const animstate * as, skin & s, vbocacheentry & vc) inline
References elen, eoffset, glde, glDrawRangeElements_, maxvert, minvert, numverts, and xtravertsva.
Referenced by skelmodel::skelmeshgroup::render().
void skelmodel::skelmesh::setshader (Shader * s) inline override
References glaring, maxweights, inexor::rpc::min(), Shader::set(), Shader::setvariant(), skelmodel::skelmeshgroup::skel, skelmodel::skeleton::usegpuskel, and skelmodel::skelmeshgroup::vweights.
void skelmodel::skelmesh::smoothnorms (float limit = 0, bool areaweight = true) inline
References numtris, numverts, animmodel::mesh::smoothnorms(), tris, and verts.
Referenced by md5::md5meshgroup::loadmesh().
Member Data Documentation
bumpvert* skelmodel::skelmesh::bumpverts
Referenced by assignvert(), calctangents(), interpverts(), iqm::iqmmeshgroup::loadiqmmeshes(), and ~skelmesh().
int skelmodel::skelmesh::elen
Referenced by genvbo(), and render().
int skelmodel::skelmesh::eoffset
Referenced by genvbo(), and render().
ushort skelmodel::skelmesh::maxvert
Referenced by genvbo(), and render().
int skelmodel::skelmesh::maxweights
Referenced by addblendcombo(), and setshader().
ushort skelmodel::skelmesh::minvert
Referenced by genvbo(), and render().
int skelmodel::skelmesh::numtris
Referenced by buildnorms(), calctangents(), genBIH(), genvbo(), md5::md5mesh::load(), iqm::iqmmeshgroup::loadiqmmeshes(), md5::md5meshgroup::loadmesh(), and smoothnorms().
int skelmodel::skelmesh::numverts
Referenced by buildnorms(), md5::md5mesh::buildverts(), calcbb(), calctangents(), fillverts(), genvbo(), md5::md5mesh::load(), iqm::iqmmeshgroup::loadiqmmeshes(), md5::md5meshgroup::loadmesh(), render(), smoothnorms(), and skelmodel::skelmeshgroup::sortblendcombos().
tri* skelmodel::skelmesh::tris
Referenced by buildnorms(), calctangents(), genBIH(), genvbo(), md5::md5mesh::load(), iqm::iqmmeshgroup::loadiqmmeshes(), smoothnorms(), and ~skelmesh().
vert* skelmodel::skelmesh::verts
Referenced by buildnorms(), md5::md5mesh::buildverts(), calcbb(), calctangents(), fillverts(), genBIH(), genvbo(), md5::md5mesh::load(), iqm::iqmmeshgroup::loadiqmmeshes(), smoothnorms(), skelmodel::skelmeshgroup::sortblendcombos(), and ~skelmesh().
int skelmodel::skelmesh::voffset
Referenced by fillverts(), genvbo(), and skelmodel::skelmeshgroup::render().
The documentation for this struct was generated from the following file:
inexor/model/skelmodel.hpp