Inexor: flarerenderer Struct Reference
flarerenderer Struct Reference
#include <lensflare.hpp>
Public Member Functions
flarerenderer (const char *texname, int maxflares)
~flarerenderer () override
void reset () override
void newflare (vec &o, const vec &center, uchar r, uchar g, uchar b, float mod, float size, bool sun, bool sparkle)
void addflare (vec &o, uchar r, uchar g, uchar b, bool sun, bool sparkle)
void makelightflares ()
int count () override
bool haswork () override
void render () override
particle * addpart (const vec &o, const vec &d, int fade, int color, float size, int gravity=0) override
virtual void init (int n)
virtual void resettracked (physent *owner)
virtual int adddepthfx (vec &bbmin, vec &bbmax)
virtual void update ()
virtual void cleanup ()
virtual void seedemitter (particleemitter &pe, const vec &o, const vec &d, int fade, float size, int gravity)
void calc (particle *p, int &blend, int &ts, vec &o, vec &d, bool step=true)
const char * debuginfo ()
Public Attributes
int maxflares
int numflares
unsigned int shinetime
flare * flares
Texture * tex
const char * texname
int texclamp
uint type
int collide
string info
Constructor & Destructor Documentation
flarerenderer::flarerenderer (const char * texname, int maxflares) inline
References flares, and maxflares.
flarerenderer::~flarerenderer () inline override
References flares.
Member Function Documentation
virtual int partrenderer::adddepthfx (vec & bbmin, vec & bbmax) inline virtual inherited
Referenced by finddepthfxranges().
void flarerenderer::addflare (vec & o, uchar r, uchar g, uchar b, bool sun, bool sparkle) inline
References camdir, camera1, vec::dot(), f(), isvisiblesphere(), vec::magnitude(), vec::mul(), newflare(), physent::o, vec::squaredlen(), vec::sub(), VFC_FOGGED, and VFC_FULL_VISIBLE.
Referenced by makeparticles().
particle* flarerenderer::addpart (const vec & o, const vec & d, int fade, int color, float size, int gravity = 0) inline override virtual
Implements partrenderer.
void partrenderer::calc (particle * p, int & blend, int & ts, vec & o, vec & d, bool step = true) inherited
References vec::add(), adddecal(), mpr::collide(), COLLIDEERROR, COLLIDERADIUS, particle::color, particle::d, f(), particle::fade, particle::flags, particle::gravity, lastmillis, inexor::rpc::max(), particle::millis, vec::normalize(), particle::o, game::particletrack(), PT_RND4, PT_TRACK, RAY_CLIPMAT, rayfloor(), particle::size, vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
virtual void partrenderer::cleanup () inline virtual inherited
Reimplemented in varenderer< T >, and fireballrenderer.
Referenced by cleanupparticles().
int flarerenderer::count () inline override virtual
Implements partrenderer.
References numflares.
const char * partrenderer::debuginfo () inherited
References mpr::collide(), concatstring(), concformatstring(), formatstring(), partnames, PT_FLIP, PT_GLARE, PT_LERP, PT_MOD, PT_RND4, and PT_SOFT.
Referenced by renderparticles().
bool flarerenderer::haswork () inline override virtual
Implements partrenderer.
References glaring, numflares, reflecting, and refracting.
virtual void partrenderer::init (int n) inline virtual inherited
Reimplemented in varenderer< T >.
Referenced by particleinit().
void flarerenderer::makelightflares () inline
References entity::attr1, entity::attr2, entity::attr3, entity::attr4, camdir, camera1, checklightcache(), vec::dot(), editmode, entities::ents, ET_LIGHT, f(), entities::getents(), isvisiblesphere(), lastmillis, loopv, vec::magnitude(), vec::mul(), newflare(), numflares, entity::o, physent::o, shinetime, vec::sub(), entity::type, VFC_FOGGED, and VFC_FULL_VISIBLE.
Referenced by updateparticles().
void flarerenderer::newflare (vec & o, const vec & center, uchar r, uchar g, uchar b, float mod, float size, bool sun, bool sparkle) inline
References camera1, flare::center, flare::color, f(), flares, maxflares, numflares, flare::o, physent::o, raycubelos(), flare::size, flare::sparkle, and ai::target().
Referenced by addflare(), and makelightflares().
void flarerenderer::render () inline override virtual
Implements partrenderer.
References vec::add(), flaretype::alpha, gle::attrib(), gle::ATTRIB_COLOR, gle::ATTRIB_TEXCOORD0, gle::ATTRIB_VERTEX, gle::begin(), camright, camup, flare::center, flare::color, gle::color(), gle::defattrib(), gle::end(), f(), flares, flaretypes, Texture::id, flaretype::loc, loopi(), loopj, vec::mul(), numflares, flare::o, flaretype::scale, Shader::set(), shinetime, flare::size, flare::sparkle, vec::sub(), partrenderer::tex, partrenderer::texname, textureload(), textureshader, and flaretype::type.
void flarerenderer::reset () inline override virtual
Implements partrenderer.
References numflares.
virtual void partrenderer::resettracked (physent * owner) inline virtual inherited
Reimplemented in varenderer< T >, and listrenderer.
Referenced by removetrackedparticles().
virtual void partrenderer::seedemitter (particleemitter & pe, const vec & o, const vec & d, int fade, float size, int gravity) inline virtual inherited
Reimplemented in varenderer< T >, lightningrenderer, and fireballrenderer.
Referenced by newparticle().
virtual void partrenderer::update () inline virtual inherited
Reimplemented in varenderer< T >, and lightningrenderer.
Referenced by renderparticles().
Member Data Documentation
int partrenderer::collide inherited
Referenced by fireballrenderer::finddepthfxranges(), regularshape(), and splash().
flare* flarerenderer::flares
Referenced by flarerenderer(), newflare(), render(), and ~flarerenderer().
string partrenderer::info inherited
int flarerenderer::maxflares
Referenced by flarerenderer(), and newflare().
int flarerenderer::numflares
Referenced by count(), haswork(), makelightflares(), newflare(), render(), and reset().
unsigned int flarerenderer::shinetime
Referenced by makelightflares(), and render().
Texture* partrenderer::tex inherited
Referenced by render(), and lightningrenderer::renderpart().
int partrenderer::texclamp inherited
const char* partrenderer::texname inherited
Referenced by render().
uint partrenderer::type inherited
Referenced by fireballrenderer::finddepthfxranges(), finddepthfxranges(), regularshape(), lightningrenderer::renderpart(), and renderparticles().
The documentation for this struct was generated from the following file:
inexor/engine/lensflare.hpp