Inexor: game::captureclientmode Struct Reference
game::captureclientmode Struct Reference
#include <capture_client.hpp>
Public Member Functions
void respawned (fpsent *d) override
void replenishammo ()
void receiveammo (fpsent *d, int type)
void checkitems (fpsent *d) override
void rendertether (fpsent *d)
void preload () override
void rendergame () override
void drawblips (fpsent *d, float blipsize, int fw, int fh, int type, bool skipenemy=false)
int respawnwait (fpsent *d) override
int clipconsole (int w, int h) override
void drawhud (fpsent *d, int w, int h) override
void setup () override
void senditems (packetbuf &p) override
void updatebase (int i, const char *owner, const char *enemy, int converted, int ammo)
void setscore (int base, const char *team, int total)
int closesttoenemy (const char *team, bool noattacked=false, bool farthest=false)
int pickteamspawn (const char *team)
void pickspawn (fpsent *d) override
bool aicheck (fpsent *d, ai::aistate &b) override
void aifind (fpsent *d, ai::aistate &b, vector< ai::interest > &interests) override
bool aidefend (fpsent *d, ai::aistate &b) override
bool aipursue (fpsent *d, ai::aistate &b) override
bool parse_network_message (int type, ucharbuf &p) override
Parse game mode specific network messages.
virtual bool isinvisible (fpsent *d)
virtual void addplayer (fpsent *d)
virtual void removeplayer (fpsent *d)
virtual void gameover ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual void killed (fpsent *d, fpsent *actor)
virtual void gameconnect (fpsent *d)
virtual void renderscoreboard (g3d_gui &g, scoregroup &sg, int fgcolor, int bgcolor)
void resetbases ()
bool hidefrags ()
int getteamscore (const char *team)
void getteamscores (vector< teamscore > &teamscores)
score & findscore (const char *team)
void addbase (int ammotype, const vec &o)
void initbase (int i, int ammotype, const char *owner, const char *enemy, int converted, int ammo)
bool hasbases (const char *team)
float disttoenemy (baseinfo &b)
bool insidebase (const baseinfo &b, const vec &o)
Public Attributes
vector< baseinfo > bases
vector< score > scores
int captures = 0
Static Public Attributes
static const int AMMOHEIGHT = 5
static const int CAPTURERADIUS = 64
static const int CAPTUREHEIGHT = 24
static const int OCCUPYBONUS = 1
static const int OCCUPYPOINTS = 1
static const int OCCUPYENEMYLIMIT = 28
static const int OCCUPYNEUTRALLIMIT = 14
static const int SCORESECS = 10
static const int AMMOSECS = 15
static const int REGENSECS = 1
static const int REGENHEALTH = 10
static const int REGENARMOUR = 10
static const int REGENAMMO = 20
static const int MAXAMMO = 5
static const int REPAMMODIST = 32
static const int RESPAWNSECS = 10
static const int REGENRESPAWNSECS = 0
static const int MAXBASES = 100
Member Function Documentation
void capturemode_common::addbase (int ammotype, const vec & o) inline inherited
References capturemode_common::baseinfo::ammogroup, capturemode_common::baseinfo::ammotype, capturemode_common::bases, I_GRENADES, I_SHELLS, loopi(), loopj, capturemode_common::MAXBASES, inexor::rpc::min(), capturemode_common::baseinfo::o, and rnd().
Referenced by server::captureservermode::parsebases(), and server::captureservermode::setup().
virtual void game::clientmode::addplayer (fpsent * d) inline virtual inherited
bool game::captureclientmode::aicheck (fpsent * d, ai::aistate & b) inline override virtual
Reimplemented from game::clientmode.
bool game::captureclientmode::aidefend (fpsent * d, ai::aistate & b) override virtual
Reimplemented from game::clientmode.
References vector< T, MINSIZE >::add(), fpsent::ai, ai::AI_S_DEFEND, ai::AI_T_AFFINITY, capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammotype, ai::checkothers(), fpsent::clientnum, CS_ALIVE, ai::defend(), vector< T, MINSIZE >::empty(), capturemode_common::baseinfo::enemy, f(), physent::feetpos(), vector< T, MINSIZE >::find(), fpsstate::hasmaxammo(), fpsstate::health, I_SHELLS, isteam, game::iterdynents(), lastmillis, loopi(), m_regencapture, ai::aistate::millis, game::numdynents(), capturemode_common::baseinfo::o, capturemode_common::baseinfo::owner, vector< T, MINSIZE >::setsize(), fpsstate::skill, vec::squaredist(), physent::state, ai::aistate::target, ai::targets, fpsent::team, ai::aiinfo::trywipe, and capturemode_common::baseinfo::valid().
Referenced by aipursue().
void game::captureclientmode::aifind (fpsent * d, ai::aistate & b, vector< ai::interest > & interests) override virtual
Reimplemented from game::clientmode.
References vector< T, MINSIZE >::add(), fpsent::ai, ai::AI_S_DEFEND, ai::AI_T_AFFINITY, capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammotype, ai::checkothers(), fpsent::clientnum, ai::closestwaypoint(), CS_ALIVE, vector< T, MINSIZE >::empty(), capturemode_common::baseinfo::enemy, f(), physent::feetpos(), vector< T, MINSIZE >::find(), fpsstate::hasmaxammo(), fpsstate::health, I_SHELLS, isteam, game::iterdynents(), loopi(), loopvj, m_regencapture, ai::interest::node, game::numdynents(), capturemode_common::baseinfo::o, capturemode_common::baseinfo::owner, ai::interest::score, vector< T, MINSIZE >::setsize(), ai::SIGHTMIN, vec::squaredist(), physent::state, ai::interest::state, ai::interest::target, ai::targets, ai::interest::targtype, fpsent::team, capturemode_common::baseinfo::valid(), and ai::aiinfo::weappref.
bool game::captureclientmode::aipursue (fpsent * d, ai::aistate & b) inline override virtual
Reimplemented from game::clientmode.
References ai::AI_S_DEFEND, aidefend(), and ai::aistate::type.
void game::captureclientmode::checkitems (fpsent * d) override virtual
Reimplemented from game::clientmode.
References game::addmsg(), capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammotype, CS_ALIVE, vec::dist(), physent::feetpos(), fpsstate::hasmaxammo(), I_SHELLS, fpsent::lastrepammo, loopv, m_regencapture, N_REPAMMO, capturemode_common::baseinfo::o, capturemode_common::baseinfo::owner, game::player1, physent::state, fpsent::team, and capturemode_common::baseinfo::valid().
int game::captureclientmode::clipconsole (int w, int h) inline override virtual
Reimplemented from game::clientmode.
int game::captureclientmode::closesttoenemy (const char * team, bool noattacked = false, bool farthest = false)
References capturemode_common::baseinfo::enemies, capturemode_common::baseinfo::enemy, loopv, and capturemode_common::baseinfo::owner.
float capturemode_common::disttoenemy (baseinfo & b) inline inherited
References capturemode_common::bases, vec::dist(), loopv, inexor::rpc::min(), capturemode_common::baseinfo::o, and capturemode_common::baseinfo::owner.
void game::captureclientmode::drawblips (fpsent * d, float blipsize, int fw, int fh, int type, bool skipenemy = false)
References gle::begin(), game::calcradarscale(), camera1, dir, vec::div(), draw_text(), gle::end(), capturemode_common::baseinfo::enemy, f(), formatstring(), loopv, vec::magnitude2(), vec::mul(), capturemode_common::baseinfo::o, physent::o, capturemode_common::baseinfo::owner, game::player1, RAD, vec::rotate_around_z(), vec::sub(), fpsent::team, text_bounds(), capturemode_common::baseinfo::valid(), and physent::yaw.
void game::captureclientmode::drawhud (fpsent * d, int w, int h) override virtual
Reimplemented from game::clientmode.
References bindminimap(), COL_RED, CS_DEAD, draw_textf(), game::drawminimap(), game::drawradar(), game::drawteammates(), f(), flushhudmatrix(), hudmatrix, lastmillis, game::lastspawnattempt, game::minimapalpha, game::player1, popfont(), pophudmatrix(), pushfont(), pushhudmatrix(), matrix4::scale(), game::setbliptex(), setfont(), game::setradartex(), physent::state, TEAM_NONE, TEAM_OPPONENT, TEAM_OWN, text_bounds(), and matrix4::translate().
score& capturemode_common::findscore (const char * team) inline inherited
References copystring(), loopv, capturemode_common::scores, capturemode_common::score::team, and capturemode_common::score::total.
Referenced by server::captureservermode::addscore(), and server::captureservermode::endcheck().
virtual void game::clientmode::gameconnect (fpsent * d) inline virtual inherited
Reimplemented in game::bombclientmode.
virtual void game::clientmode::gameover () inline virtual inherited
Referenced by game::timeupdate().
virtual int game::clientmode::getteamscore (const char * team) inline virtual inherited
Referenced by game::groupplayers().
int capturemode_common::getteamscore (const char * team) inline inherited
References loopv, capturemode_common::scores, capturemode_common::score::team, and capturemode_common::score::total.
virtual void game::clientmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by game::getbestteams().
void capturemode_common::getteamscores (vector< teamscore > & teamscores) inline inherited
References vector< T, MINSIZE >::add(), loopv, and capturemode_common::scores.
bool capturemode_common::hasbases (const char * team) inline inherited
References capturemode_common::bases, loopv, and capturemode_common::baseinfo::owner.
virtual bool game::clientmode::hidefrags () inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::getbestteams(), game::groupplayers(), game::parsemessages(), and game::renderscoreboard().
bool capturemode_common::hidefrags () inline inherited
void capturemode_common::initbase (int i, int ammotype, const char * owner, const char * enemy, int converted, int ammo) inline inherited
References capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammotype, capturemode_common::bases, capturemode_common::baseinfo::converted, copystring(), capturemode_common::baseinfo::enemy, and capturemode_common::baseinfo::owner.
bool capturemode_common::insidebase (const baseinfo & b, const vec & o) inline inherited
References capturemode_common::CAPTUREHEIGHT, capturemode_common::CAPTURERADIUS, and capturemode_common::baseinfo::o.
Referenced by server::captureservermode::movebases(), server::captureservermode::regenowners(), server::captureservermode::replenishammo(), and server::captureservermode::stealbase().
virtual bool game::clientmode::isinvisible (fpsent * d) inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::rendergame().
virtual void game::clientmode::killed (fpsent * d, fpsent * actor) inline virtual inherited
Reimplemented in game::hideandseekclientmode, and game::bombclientmode.
Referenced by game::killed().
bool game::captureclientmode::parse_network_message (int type, ucharbuf & p) override virtual
Parse game mode specific network messages.
Returns
true if message got handled.
Implements game::clientmode.
References A_GREEN, fpsstate::ammo, fpsstate::armour, fpsstate::armourtype, fpsent::clientnum, copystring(), ai::enemy(), game::getclient(), getint(), getstring(), GUN_PISTOL, GUN_SG, fpsstate::health, loopi(), m_capture, MAXTRANS, N_BASEINFO, N_BASEREGEN, N_BASES, N_BASESCORE, N_REPAMMO, and game::player1.
void game::captureclientmode::pickspawn (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
References findplayerspawn(), pickteamspawn(), and fpsent::team.
int game::captureclientmode::pickteamspawn (const char * team)
References entity::attr2, vec::dist(), entities::ents, loopv, m_regencapture, capturemode_common::baseinfo::o, entity::o, PLAYERSTART, rnd(), and entity::type.
Referenced by pickspawn().
void game::captureclientmode::preload () override virtual
Reimplemented from game::clientmode.
References loopi(), preloadmodel(), inexor::sound::preloadsound(), S_V_BASECAP, and S_V_BASELOST.
void game::captureclientmode::receiveammo (fpsent * d, int type)
References physent::abovehead(), I_CARTRIDGES, I_SHELLS, itemstat::icon, itemstats, PART_HUD_ICON_GREY, particle_icon(), game::player1, and entities::repammo().
virtual void game::clientmode::removeplayer (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode.
Referenced by game::clientdisconnected().
void game::captureclientmode::rendergame () override virtual
Reimplemented from game::clientmode.
References abovemodel(), capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammopos, capturemode_common::baseinfo::ammotype, ANIM_LOOP, ANIM_MAPMODEL, canaddparticles(), capturemode_common::baseinfo::converted, copystring(), hmap::d, capturemode_common::baseinfo::enemy, entities::entmdlname(), f(), formatstring(), I_SHELLS, capturemode_common::baseinfo::info, lastmillis, capturemode_common::baseinfo::light, loopj, loopv, m_regencapture, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_SHADOW, capturemode_common::baseinfo::name, capturemode_common::baseinfo::o, capturemode_common::baseinfo::owner, PART_FLAME, PART_METER, PART_METER_VS, PART_TEXT, particle_meter(), particle_text(), game::player1, game::players, regular_particle_flame(), rendermodel(), fpsent::team, and capturemode_common::baseinfo::valid().
virtual void game::clientmode::renderscoreboard (g3d_gui & g, scoregroup & sg, int fgcolor, int bgcolor) inline virtual inherited
Reimplemented in game::bombclientmode, and game::hideandseekclientmode.
Referenced by game::renderscoreboard().
void game::captureclientmode::rendertether (fpsent * d)
References physent::aboveeye, capturemode_common::baseinfo::ammopos, CS_ALIVE, capturemode_common::baseinfo::enemy, physent::eyeheight, f(), physent::feetpos(), fpsent::lastbase, lookupmaterial(), loopv, MAT_GAMECLIP, MATF_CLIP, physent::o, capturemode_common::baseinfo::owner, PART_EXPLOSION, PART_LIGHTNING, PART_SPARK, particle_fireball(), particle_flare(), particle_splash(), game::player1, physent::state, fpsent::team, and capturemode_common::baseinfo::valid().
void game::captureclientmode::replenishammo ()
References game::addmsg(), capturemode_common::baseinfo::ammotype, physent::feetpos(), fpsstate::hasmaxammo(), I_SHELLS, loopv, m_capture, m_regencapture, N_REPAMMO, game::player1, and capturemode_common::baseinfo::valid().
void capturemode_common::resetbases () inline inherited
References capturemode_common::bases, capturemode_common::captures, and capturemode_common::scores.
Referenced by server::captureservermode::reset().
void game::captureclientmode::respawned (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
int game::captureclientmode::respawnwait (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
References lastmillis, fpsent::lastpain, m_regencapture, inexor::rpc::max(), capturemode_common::REGENRESPAWNSECS, and capturemode_common::RESPAWNSECS.
void game::captureclientmode::senditems (packetbuf & p) override virtual
Reimplemented from game::clientmode.
References capturemode_common::baseinfo::ammotype, DMF, databuf< T >::length(), loopv, N_BASES, capturemode_common::baseinfo::o, and putint().
void game::captureclientmode::setscore (int base, const char * team, int total)
References capturemode_common::baseinfo::ammopos, defformatstring, server::findscore(), inexor::util::log_manager::game, isteam, Log, capturemode_common::baseinfo::owner, PART_TEXT, particle_textcopy(), game::player1, fpsent::team, and game::teamcolor().
void game::captureclientmode::setup () override virtual
Reimplemented from game::clientmode.
References abovemodel(), alias(), capturemode_common::baseinfo::ammopos, capturemode_common::baseinfo::ammotype, entity::attr1, entity::attr2, BASE, copystring(), defformatstring, entities::ents, getalias(), capturemode_common::baseinfo::light, extentity::light, loopv, capturemode_common::baseinfo::name, capturemode_common::baseinfo::o, entity::o, and entity::type.
void game::captureclientmode::updatebase (int i, const char * owner, const char * enemy, int converted, int ammo)
References capturemode_common::baseinfo::ammo, capturemode_common::baseinfo::ammopos, capturemode_common::baseinfo::ammotype, capturemode_common::baseinfo::converted, copystring(), capturemode_common::baseinfo::enemy, inexor::util::log_manager::game, itemstat::icon, itemstats, Log, capturemode_common::baseinfo::name, capturemode_common::baseinfo::o, capturemode_common::baseinfo::owner, PART_HUD_ICON, PART_SPARK, particle_icon(), particle_splash(), game::player1, inexor::sound::playsound(), S_ITEMSPAWN, S_V_BASECAP, S_V_BASELOST, fpsent::team, game::teamcolor(), and capturemode_common::baseinfo::valid().
Member Data Documentation
const int game::captureclientmode::AMMOHEIGHT = 5 static
const int capturemode_common::AMMOSECS = 15 static inherited
Referenced by server::captureservermode::update().
vector<baseinfo> capturemode_common::bases inherited
Referenced by capturemode_common::addbase(), capturemode_common::disttoenemy(), server::captureservermode::endcheck(), server::captureservermode::extinfoteam(), capturemode_common::hasbases(), capturemode_common::initbase(), server::captureservermode::initclient(), server::captureservermode::movebases(), server::captureservermode::replenishammo(), capturemode_common::resetbases(), server::captureservermode::sendbaseinfo(), server::captureservermode::stealbase(), and server::captureservermode::update().
const int capturemode_common::CAPTUREHEIGHT = 24 static inherited
Referenced by capturemode_common::insidebase().
const int capturemode_common::CAPTURERADIUS = 64 static inherited
Referenced by capturemode_common::insidebase().
int capturemode_common::captures = 0 inherited
Referenced by capturemode_common::resetbases().
const int capturemode_common::MAXAMMO = 5 static inherited
Referenced by capturemode_common::baseinfo::addammo().
const int capturemode_common::MAXBASES = 100 static inherited
Referenced by capturemode_common::addbase().
const int capturemode_common::OCCUPYBONUS = 1 static inherited
Referenced by server::captureservermode::update().
const int capturemode_common::OCCUPYENEMYLIMIT = 28 static inherited
Referenced by capturemode_common::baseinfo::occupy().
const int capturemode_common::OCCUPYNEUTRALLIMIT = 14 static inherited
Referenced by capturemode_common::baseinfo::occupy().
const int capturemode_common::OCCUPYPOINTS = 1 static inherited
Referenced by server::captureservermode::update().
const int capturemode_common::REGENAMMO = 20 static inherited
Referenced by server::captureservermode::regenowners().
const int capturemode_common::REGENARMOUR = 10 static inherited
Referenced by server::captureservermode::regenowners().
const int capturemode_common::REGENHEALTH = 10 static inherited
Referenced by server::captureservermode::regenowners().
const int capturemode_common::REGENRESPAWNSECS = 0 static inherited
Referenced by server::captureservermode::canspawn(), and respawnwait().
const int capturemode_common::REGENSECS = 1 static inherited
Referenced by server::captureservermode::update().
const int capturemode_common::REPAMMODIST = 32 static inherited
const int capturemode_common::RESPAWNSECS = 10 static inherited
Referenced by server::captureservermode::canspawn(), and respawnwait().
vector<score> capturemode_common::scores inherited
Referenced by capturemode_common::findscore(), capturemode_common::getteamscore(), capturemode_common::getteamscores(), server::captureservermode::initclient(), and capturemode_common::resetbases().
const int capturemode_common::SCORESECS = 10 static inherited
Referenced by server::captureservermode::update().
The documentation for this struct was generated from the following files:
inexor/client/gamemode/capture_client.hpp
inexor/client/gamemode/capture_client.cpp