Inexor: game::scoreboardgui Struct Reference
game::scoreboardgui Struct Reference
Public Member Functions
scoreboardgui ()
void show (bool on)
void gui (g3d_gui &g, bool firstpass) override
void render ()
int starttime ()
Public Attributes
bool showing
vec menupos
int menustart
Constructor & Destructor Documentation
game::scoreboardgui::scoreboardgui () inline
Member Function Documentation
void game::scoreboardgui::gui (g3d_gui & g, bool firstpass) inline override virtual
Implements g3d_callback.
References g3d_gui::end(), f(), menustart, game::renderscoreboard(), and g3d_gui::start().
void game::scoreboardgui::render () inline
References g3d_addgui(), GUI_2D, GUI_BOTTOM, GUI_FOLLOW, GUI_FORCE_2D, menupos, and showing.
Referenced by game::g3d_gamemenus().
void game::scoreboardgui::show (bool on) inline
References menuinfrontofplayer(), menupos, menustart, showing, and g3d_callback::starttime().
Referenced by game::showscores().
int g3d_callback::starttime () inherited
References totalmillis.
Referenced by show().
Member Data Documentation
vec game::scoreboardgui::menupos
Referenced by render(), and show().
int game::scoreboardgui::menustart
Referenced by gui(), and show().
bool game::scoreboardgui::showing
Referenced by render(), and show().
The documentation for this struct was generated from the following file:
inexor/fpsgame/scoreboard.cpp