Inexor: ai::wpcache Struct Reference
ai::wpcache Struct Reference
Classes
struct node
Public Member Functions
wpcache ()
void clear ()
void build (int first=0, int last=-1)
void build (int *indices, int numindices, const vec &vmin, const vec &vmax)
Public Attributes
vector< node > nodes
int firstwp
int lastwp
vec bbmin
vec bbmax
Constructor & Destructor Documentation
ai::wpcache::wpcache () inline
Member Function Documentation
void ai::wpcache::build (int first = 0, int last = -1) inline
References vector< T, MINSIZE >::add(), vec::add(), vector< T, MINSIZE >::getbuf(), sphere::indices, vector< T, MINSIZE >::length(), inexor::rpc::max(), ai::waypoint::o, vec::sub(), ai::WAYPOINTRADIUS, and ai::waypoints.
Referenced by ai::buildwpcache().
void ai::wpcache::build (int * indices, int numindices, const vec & vmin, const vec & vmax) inline
References vec::add(), ai::wpcache::node::child, loopi(), loopk, vec::max(), inexor::rpc::max(), inexor::rpc::min(), ai::waypoint::o, ai::wpcache::node::split, vec::sub(), ai::WAYPOINTRADIUS, and ai::waypoints.
void ai::wpcache::clear () inline
Referenced by ai::clearwpcache().
Member Data Documentation
vec ai::wpcache::bbmax
vec ai::wpcache::bbmin
int ai::wpcache::firstwp
int ai::wpcache::lastwp
vector<node> ai::wpcache::nodes
The documentation for this struct was generated from the following file:
inexor/fpsgame/waypoint.cpp