Inexor: squat Struct Reference
squat Struct Reference
#include <geom.hpp>
Public Member Functions
squat ()
squat (const vec4 &q)
void convert (const vec4 &q)
void lerp (const vec4 &a, const vec4 &b, float t)
Public Attributes
short x
short y
short z
short w
Constructor & Destructor Documentation
squat::squat () inline
squat::squat (const vec4 & q) inline
References convert().
Member Function Documentation
void squat::convert (const vec4 & q) inline
References w, x, y, and z.
Referenced by lerp(), and squat().
void squat::lerp (const vec4 & a, const vec4 & b, float t) inline
References convert(), and vec4::lerp().
Member Data Documentation
short squat::w
Referenced by convert().
short squat::x
Referenced by convert().
short squat::y
Referenced by convert().
short squat::z
Referenced by convert().
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp