Inexor: prefabmesh Struct Reference
prefabmesh Struct Reference
Classes
struct vertex
Public Member Functions
prefabmesh ()
int addvert (const vertex &v)
int addvert (const vec &pos, const bvec &norm)
void setup (prefab &p)
Public Attributes
int table [SIZE]
vector< vertex > verts
vector< int > chain
vector< ushort > tris
Static Public Attributes
static const int SIZE = 1<<9
Class Documentation
struct prefabmesh::vertex
Class Members
bvec4 norm
vec pos
Constructor & Destructor Documentation
prefabmesh::prefabmesh () inline
Member Function Documentation
int prefabmesh::addvert (const vertex & v) inline
References hthash(), prefabmesh::vertex::norm, prefabmesh::vertex::pos, and sphere::verts.
Referenced by genprefabmesh().
int prefabmesh::addvert (const vec & pos, const bvec & norm) inline
References prefabmesh::vertex::norm, and prefabmesh::vertex::pos.
void prefabmesh::setup (prefab & p) inline
References gle::bindebo(), gle::bindvbo(), prefab::cleanup(), gle::clearebo(), gle::clearvbo(), prefab::ebo, glBufferData_, glGenBuffers_, loopv, prefab::numtris, prefab::numverts, prefab::vbo, and sphere::verts.
Member Data Documentation
vector<int> prefabmesh::chain
const int prefabmesh::SIZE = 1<<9 static
int prefabmesh::table[SIZE]
vector<ushort> prefabmesh::tris
Referenced by genprefabmesh().
vector<vertex> prefabmesh::verts
The documentation for this struct was generated from the following file:
inexor/engine/octaedit.cpp