Inexor: BlendBrush Struct Reference
BlendBrush Struct Reference
Public Member Functions
BlendBrush (const char *name, int w, int h)
~BlendBrush ()
void cleanup ()
void gentex ()
void reorient (bool flipx, bool flipy, bool swapxy)
Public Attributes
char * name
int w
int h
uchar * data
GLuint tex
Constructor & Destructor Documentation
BlendBrush::BlendBrush (const char * name, int w, int h) inline
BlendBrush::~BlendBrush () inline
References cleanup(), data, and name.
Member Function Documentation
void BlendBrush::cleanup () inline
References tex.
Referenced by ~BlendBrush().
void BlendBrush::gentex () inline
References createtexture(), data, GL_R8, h, hasTRG, loopi(), loopj, tex, and w.
Referenced by renderblendbrush(), and reorient().
void BlendBrush::reorient (bool flipx, bool flipy, bool swapxy) inline
References data, gentex(), h, loopi(), loopj, tex, and w.
Referenced by rotateblendbrush().
Member Data Documentation
uchar* BlendBrush::data
Referenced by addblendbrush(), gentex(), paintblendmap(), reorient(), and ~BlendBrush().
int BlendBrush::h
Referenced by gentex(), paintblendmap(), renderblendbrush(), and reorient().
char* BlendBrush::name
Referenced by ~BlendBrush().
GLuint BlendBrush::tex
Referenced by cleanup(), gentex(), renderblendbrush(), and reorient().
int BlendBrush::w
Referenced by gentex(), paintblendmap(), renderblendbrush(), and reorient().
The documentation for this struct was generated from the following file:
inexor/engine/blend.cpp