Inexor: animmodel::skin Struct Reference
animmodel::skin Struct Reference
#include <animmodel.hpp>
Public Member Functions
skin ()
bool masked () const
bool envmapped ()
bool bumpmapped ()
bool tangents ()
bool alphatested () const
void setkey ()
void setshaderparams (mesh *m, const animstate *as)
Shader * loadshader ()
void cleanup ()
void preloadBIH ()
void preloadshader (bool force)
void setshader (mesh *m, const animstate *as)
void bind (mesh *b, const animstate *as)
Public Attributes
part * owner
Texture * tex
Texture * masks
Texture * envmap
Texture * normalmap
Shader * shader
bool alphablend
bool cullface
shaderparamskey * key
float spec
float ambient
float glow
float glowdelta
float glowpulse
float specglare
float glowglare
float fullbright
float envmapmin
float envmapmax
float scrollu
float scrollv
float alphatest
Constructor & Destructor Documentation
animmodel::skin::skin () inline
Member Function Documentation
bool animmodel::skin::alphatested () const inline
References Texture::ALPHA, animmodel::shaderparams::alphatest, tex, and Texture::type.
Referenced by loadshader(), and setshaderparams().
void animmodel::skin::bind (mesh * b, const animstate * as) inline
References Texture::ALPHA, alphablend, animmodel::animpos::anim, ANIM_NOSKIN, bumpmapped(), animmodel::closestenvmaptex, cullface, animmodel::animstate::cur, animmodel::enablealphablend, animmodel::enablecullface, envmapped(), glActiveTexture_, GLuint(), Texture::id, animmodel::lastenvmaptex, animmodel::lastmasks, animmodel::lastnormalmap, animmodel::lasttex, masked(), masks, normalmap, reflecting, refracting, SETMODELSHADER, setshader(), setshaderparams(), shadowmapping, tex, animmodel::transparent, and Texture::type.
bool animmodel::skin::bumpmapped () inline
References normalmap.
Referenced by bind(), loadshader(), and tangents().
void animmodel::skin::cleanup () inline
References shader, and Shader::standard.
Referenced by preloadshader().
bool animmodel::skin::envmapped () inline
References animmodel::shaderparams::envmapmax.
Referenced by bind(), loadshader(), and setshaderparams().
Shader* animmodel::skin::loadshader () inline
References alphatested(), bumpmapped(), defformatstring, envmapped(), f(), animmodel::shaderparams::fullbright, generateshader(), masked(), model::name, owner, shader, animmodel::shaderparams::spec, and animmodel::part::tangents().
Referenced by preloadshader(), and setshader().
bool animmodel::skin::masked () const inline
References masks, and notexture.
Referenced by bind(), and loadshader().
void animmodel::skin::preloadBIH () inline
References loadalphamask(), and tex.
void animmodel::skin::preloadshader (bool force) inline
References cleanup(), and loadshader().
void animmodel::skin::setkey () inline
References key, and animmodel::shaderparamskey::keys.
void animmodel::skin::setshader (mesh * m, const animstate * as) inline
References loadshader(), and animmodel::mesh::setshader().
Referenced by bind().
void animmodel::skin::setshaderparams (mesh * m, const animstate * as) inline
References animmodel::shaderparams::alphatest, alphatested(), animmodel::shaderparams::ambient, animmodel::animpos::anim, ANIM_FULLBRIGHT, animmodel::shaderparamskey::checkversion(), gle::color(), animmodel::animstate::cur, animmodel::shaderparams::envmapmax, animmodel::shaderparams::envmapmin, envmapped(), f(), animmodel::shaderparams::fullbright, animmodel::shaderparams::glow, animmodel::shaderparams::glowdelta, animmodel::shaderparams::glowglare, animmodel::shaderparams::glowpulse, key, lastmillis, Shader::lastshader, animmodel::lightcolor, LOCALPARAMF, inexor::rpc::max(), Shader::owner, model::scale, animmodel::shaderparams::scrollu, animmodel::shaderparams::scrollv, animmodel::shaderparams::spec, animmodel::shaderparams::specglare, texscroll(), and animmodel::transparent.
Referenced by bind().
bool animmodel::skin::tangents () inline
References bumpmapped().
Member Data Documentation
bool animmodel::skin::alphablend
Referenced by bind().
float animmodel::shaderparams::alphatest inherited
Referenced by alphatested(), and setshaderparams().
float animmodel::shaderparams::ambient inherited
Referenced by setshaderparams().
bool animmodel::skin::cullface
Referenced by bind(), and animmodel::mesh::genBIH().
Texture * animmodel::skin::envmap
Referenced by animmodel::setenvmap().
float animmodel::shaderparams::envmapmax inherited
Referenced by envmapped(), animmodel::setenvmap(), and setshaderparams().
float animmodel::shaderparams::envmapmin inherited
Referenced by animmodel::setenvmap(), and setshaderparams().
float animmodel::shaderparams::fullbright inherited
Referenced by loadshader(), and setshaderparams().
float animmodel::shaderparams::glow inherited
Referenced by animmodel::setglow(), and setshaderparams().
float animmodel::shaderparams::glowdelta inherited
Referenced by animmodel::setglow(), and setshaderparams().
float animmodel::shaderparams::glowglare inherited
Referenced by animmodel::setglare(), and setshaderparams().
float animmodel::shaderparams::glowpulse inherited
Referenced by animmodel::setglow(), and setshaderparams().
shaderparamskey* animmodel::skin::key
Referenced by setkey(), and setshaderparams().
Texture * animmodel::skin::masks
Referenced by bind(), animmodel::part::initskins(), and masked().
Texture * animmodel::skin::normalmap
Referenced by bind(), and bumpmapped().
part* animmodel::skin::owner
Referenced by animmodel::part::initskins(), and loadshader().
float animmodel::shaderparams::scrollu inherited
Referenced by setshaderparams().
float animmodel::shaderparams::scrollv inherited
Referenced by setshaderparams().
Shader* animmodel::skin::shader
Referenced by cleanup(), and loadshader().
float animmodel::shaderparams::spec inherited
Referenced by loadshader(), and setshaderparams().
float animmodel::shaderparams::specglare inherited
Referenced by animmodel::setglare(), and setshaderparams().
Texture* animmodel::skin::tex
Referenced by alphatested(), bind(), animmodel::mesh::genBIH(), animmodel::part::initskins(), md5::md5mesh::load(), and preloadBIH().
The documentation for this struct was generated from the following file:
inexor/model/animmodel.hpp