Inexor: PackNode Struct Reference
PackNode Struct Reference
#include <lightmap.hpp>
Public Member Functions
PackNode ()
PackNode (ushort x, ushort y, ushort w, ushort h)
void clear ()
~PackNode ()
bool insert (ushort &tx, ushort &ty, ushort tw, ushort th)
Public Attributes
PackNode * child1
PackNode * child2
ushort x
ushort y
ushort w
ushort h
int available
Constructor & Destructor Documentation
PackNode::PackNode ()
PackNode::PackNode (ushort x, ushort y, ushort w, ushort h)
PackNode::~PackNode () inline
References clear().
Member Function Documentation
void PackNode::clear ()
References DELETEP.
Referenced by LightMap::finalize(), and ~PackNode().
bool PackNode::insert (ushort & tx, ushort & ty, ushort tw, ushort th)
References inexor::rpc::max().
Referenced by LightMap::insert().
Member Data Documentation
int PackNode::available
Referenced by LightMap::finalize().
PackNode* PackNode::child1
PackNode * PackNode::child2
ushort PackNode::h
ushort PackNode::w
ushort PackNode::x
ushort PackNode::y
The documentation for this struct was generated from the following files:
inexor/engine/lightmap.hpp
inexor/engine/lightmap.cpp