Inexor: animmodel::meshgroup Struct Reference
animmodel::meshgroup Struct Reference
#include <animmodel.hpp>
Public Member Functions
meshgroup ()
virtual ~meshgroup ()
virtual int findtag (const char *name)
virtual void concattagtransform (part *p, int i, const matrix4x3 &m, matrix4x3 &n)
void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m)
void genBIH (vector< skin > &skins, vector< BIH::mesh > &bih, const matrix4x3 &t)
virtual void * animkey ()
virtual int totalframes () const
bool hasframe (int i) const
bool hasframes (int i, int n) const
int clipframes (int i, int n) const
virtual void cleanup ()
virtual void preload (part *p)
virtual void render (const animstate *as, float pitch, const vec &axis, const vec &forward, dynent *d, part *p)
void bindpos (GLuint ebuf, GLuint vbuf, void *v, int stride)
void bindtc (void *v, int stride)
void bindnormals (void *v, int stride)
void bindtangents (void *v, int stride)
void bindbones (void *wv, void *bv, int stride)
Public Attributes
meshgroup * next
int shared
char * name
vector< mesh * > meshes
Constructor & Destructor Documentation
animmodel::meshgroup::meshgroup () inline
virtual animmodel::meshgroup::~meshgroup () inline virtual
References DELETEA, DELETEP, meshes, name, and next.
Member Function Documentation
virtual void* animmodel::meshgroup::animkey () inline virtual
Reimplemented in skelmodel::skelmeshgroup.
Referenced by animmodel::part::calcanim().
void animmodel::meshgroup::bindbones (void * wv, void * bv, int stride) inline
References animmodel::enablebones, animmodel::lastbbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindnormals (void * v, int stride) inline
References animmodel::enablenormals, animmodel::lastnbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindpos (GLuint ebuf, GLuint vbuf, void * v, int stride) inline
References gle::bindebo(), gle::bindvbo(), sphere::ebuf, animmodel::lastebuf, animmodel::lastvbuf, and sphere::vbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindtangents (void * v, int stride) inline
References animmodel::enabletangents, animmodel::lastvbuf, and animmodel::lastxbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindtc (void * v, int stride) inline
References animmodel::enabletc, animmodel::lasttcbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline
References loopv, and meshes.
Referenced by animmodel::part::calcbb().
virtual void animmodel::meshgroup::cleanup () inline virtual
Reimplemented in skelmodel::skelmeshgroup, and vertmodel::vertmeshgroup.
Referenced by animmodel::part::cleanup().
int animmodel::meshgroup::clipframes (int i, int n) const inline
References inexor::rpc::min(), and totalframes().
Referenced by animmodel::part::calcanim().
virtual void animmodel::meshgroup::concattagtransform (part * p, int i, const matrix4x3 & m, matrix4x3 & n) inline virtual
Reimplemented in skelmodel::skelmeshgroup, and vertmodel::vertmeshgroup.
Referenced by animmodel::part::calcbb(), and animmodel::part::genBIH().
virtual int animmodel::meshgroup::findtag (const char * name) inline virtual
Reimplemented in skelmodel::skelmeshgroup, and vertmodel::vertmeshgroup.
Referenced by animmodel::part::link().
void animmodel::meshgroup::genBIH (vector< skin > & skins, vector< BIH::mesh > & bih, const matrix4x3 & t) inline
References loopv, and meshes.
Referenced by animmodel::part::genBIH().
bool animmodel::meshgroup::hasframe (int i) const inline
References totalframes().
Referenced by animmodel::part::calcanim().
bool animmodel::meshgroup::hasframes (int i, int n) const inline
References totalframes().
Referenced by animmodel::part::calcanim().
virtual void animmodel::meshgroup::preload (part * p) inline virtual
Reimplemented in skelmodel::skelmeshgroup, and vertmodel::vertmeshgroup.
Referenced by animmodel::part::preloadmeshes().
virtual void animmodel::meshgroup::render (const animstate * as, float pitch, const vec & axis, const vec & forward, dynent * d, part * p) inline virtual
Reimplemented in skelmodel::skelmeshgroup, and vertmodel::vertmeshgroup.
Referenced by animmodel::part::render().
virtual int animmodel::meshgroup::totalframes () const inline virtual
Reimplemented in skelmodel::skelmeshgroup, and vertmodel::vertmeshgroup.
Referenced by animmodel::part::calcanim(), clipframes(), hasframe(), and hasframes().
Member Data Documentation
vector<mesh *> animmodel::meshgroup::meshes
Referenced by calcbb(), genBIH(), skelmodel::skelmeshgroup::genvbo(), animmodel::part::initskins(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), smd::smdmeshgroup::readtriangles(), skelmodel::skelmeshgroup::render(), skelmodel::skelmeshgroup::sortblendcombos(), and ~meshgroup().
char* animmodel::meshgroup::name
Referenced by md3::md3meshgroup::load(), md2::md2meshgroup::load(), smd::smdmeshgroup::load(), smd::smdmeshgroup::readmaterial(), smd::smdmeshgroup::readname(), smd::smdmeshgroup::readnodes(), and ~meshgroup().
meshgroup* animmodel::meshgroup::next
Referenced by ~meshgroup().
int animmodel::meshgroup::shared
Referenced by animmodel::part::loaded().
The documentation for this struct was generated from the following file:
inexor/model/animmodel.hpp