Inexor: ivec Struct Reference
ivec Struct Reference
3-dimensional INTEGER vectors
#include <geom.hpp>
Public Member Functions
ivec ()
ivec (const vec &v)
ivec (int a, int b, int c)
ivec (int d, int row, int col, int depth)
ivec (int i, const ivec &co, int size)
ivec (const ivec4 &v)
ivec (const ivec2 &v, int z=0)
ivec (const usvec &v)
ivec (const svec &v)
int & operator[] (int i)
int operator[] (int i) const
bool operator== (const ivec &v) const
bool operator!= (const ivec &v) const
bool iszero () const
ivec & shl (int n)
ivec & shr (int n)
ivec & mul (int n)
ivec & div (int n)
ivec & add (int n)
ivec & sub (int n)
ivec & mul (const ivec &v)
ivec & div (const ivec &v)
ivec & add (const ivec &v)
ivec & sub (const ivec &v)
ivec & mask (int n)
ivec & neg ()
ivec & min (const ivec &o)
ivec & max (const ivec &o)
ivec & min (int n)
ivec & max (int n)
ivec & abs ()
ivec & clamp (int l, int h)
ivec & cross (const ivec &a, const ivec &b)
int dot (const ivec &o) const
float dist (const plane &p) const
Static Public Member Functions
static ivec floor (const vec &o)
static ivec ceil (const vec &o)
Public Attributes
union {
struct {
int x
int y
int z
}
struct {
int r
int g
int b
}
int v [3]
};
Friends
std::ostream & operator<< (std::ostream &os, const ivec &v)
Output operator, used for simple << ivec << functionality: output of form "(x, y, z)".
Detailed Description
3-dimensional INTEGER vectors
Constructor & Destructor Documentation
ivec::ivec () inline
Referenced by ceil(), and floor().
ivec::ivec (const vec & v) inline explicit
ivec::ivec (int a, int b, int c) inline
ivec::ivec (int d, int row, int col, int depth) inline
References C, D, hmap::d, and R.
ivec::ivec (int i, const ivec & co, int size) inline
ivec::ivec (const ivec4 & v) inline explicit
ivec::ivec (const ivec2 & v, int z = 0) inline explicit
ivec::ivec (const usvec & v) inline explicit
ivec::ivec (const svec & v) inline explicit
Member Function Documentation
ivec& ivec::abs () inline
Referenced by pvsworker::cullpvs().
ivec& ivec::add (int n) inline
Referenced by decalrenderer::adddecal(), blockcube(), BIH::build(), calcvert(), changed(), collide(), convertoldsurfaces(), pvsworker::cullpvs(), entdrag(), gencubeedges(), genpoly(), modifyoctaentity(), octaboxoverlap(), octaentities::octaentities(), renderquery(), hmap::run(), and updatevabb().
ivec& ivec::add (const ivec & v) inline
static ivec ivec::ceil (const vec & o) inline static
References ceil(), and ivec().
Referenced by BIH::BIH(), and ceil().
ivec& ivec::clamp (int l, int h) inline
ivec& ivec::cross (const ivec & a, const ivec & b) inline
Referenced by collapsedface(), convertoldsurfaces(), faceconvexity(), genpoly(), loadc(), and visibletris().
float ivec::dist (const plane & p) const inline
References plane::offset.
Referenced by isfoggedcube(), ishiddencube(), and isvisiblecube().
ivec& ivec::div (int n) inline
Referenced by calcvert(), and reduceslope().
ivec& ivec::div (const ivec & v) inline
int ivec::dot (const ivec & o) const inline
Referenced by convertoldsurfaces(), faceconvexity(), genpoly(), loadc(), and visibletris().
static ivec ivec::floor (const vec & o) inline static
References floor(), and ivec().
Referenced by BIH::BIH(), and floor().
bool ivec::iszero () const inline
Referenced by changed(), convertoldsurfaces(), faceconvexity(), gencubeedges(), genpoly(), loadc(), makeundo(), and visibletris().
ivec& ivec::mask (int n) inline
Referenced by calcmergedsize(), classifyface(), convertoldsurfaces(), entdrag(), gencubeedges(), genpoly(), blobrenderer::gentris(), decalrenderer::gentris(), loadc(), lookupcube(), neighbourcube(), previewblends(), rendereditcursor(), setupsurfaces(), testpvs(), visibleface(), and visibletris().
ivec& ivec::max (const ivec & o) inline
References inexor::rpc::max().
Referenced by BIH::build(), pvsworker::calcpvs(), modifyoctaentity(), and updatevabb().
ivec& ivec::max (int n) inline
References inexor::rpc::max().
ivec& ivec::min (const ivec & o) inline
References inexor::rpc::min().
Referenced by BIH::build(), modifyoctaentity(), and updatevabb().
ivec& ivec::min (int n) inline
References inexor::rpc::min().
ivec& ivec::mul (int n) inline
Referenced by calcvert(), changed(), convertoldsurfaces(), countselchild(), pvsworker::cullpvs(), gencubeedges(), genpoly(), getentboundingbox(), neg(), and subdividecube().
ivec& ivec::mul (const ivec & v) inline
ivec& ivec::neg () inline
References mul().
Referenced by addnormals(), and gencubeedges().
bool ivec::operator!= (const ivec & v) const inline
bool ivec::operator== (const ivec & v) const inline
int& ivec::operator[] (int i) inline
int ivec::operator[] (int i) const inline
ivec& ivec::shl (int n) inline
Referenced by calcmergedsize(), convertoldsurfaces(), gencubeedges(), genpoly(), blobrenderer::gentris(), decalrenderer::gentris(), loadc(), previewblends(), hmap::select(), and setupsurfaces().
ivec& ivec::shr (int n) inline
Referenced by calcgeombb(), pvsworker::cullpvs(), faceconvexity(), reduceslope(), hmap::run(), and setva().
ivec& ivec::sub (int n) inline
Referenced by decalrenderer::adddecal(), BIH::build(), changed(), collapsedface(), pvsworker::cullpvs(), faceconvexity(), gencubeedges(), getentboundingbox(), pvsworker::hasvoxel(), loadc(), rendermapmodels(), renderquery(), and hmap::run().
ivec& ivec::sub (const ivec & v) inline
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const ivec & v) friend
Output operator, used for simple << ivec << functionality: output of form "(x, y, z)".
Member Data Documentation
union { ... }
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp