Inexor: block3 Struct Reference
block3 Struct Reference
#include <octree.hpp>
Public Member Functions
block3 ()
block3 (const selinfo &sel)
cube * c ()
int size () const
Public Attributes
ivec o
ivec s
int grid
int orient
Constructor & Destructor Documentation
block3::block3 () inline
block3::block3 (const selinfo & sel) inline
Member Function Documentation
cube* block3::c () inline
Referenced by blockcopy(), compacteditvslots(), countblock(), freeblock(), genprefabmesh(), undoblock::gridmap(), packblock(), packvslots(), pasteblock(), pasteundoblock(), undosize(), unpackblock(), and unpackvslots().
int block3::size () const inline
References s.
Referenced by blockcopy(), compacteditvslots(), countblock(), freeblock(), undoblock::gridmap(), packblock(), packundo(), packvslots(), undosize(), unpackblock(), unpackundo(), and unpackvslots().
Member Data Documentation
int block3::grid
Referenced by blockcube(), changed(), genprefabmesh(), packblock(), previewprefab(), renderprefab(), swapundo(), unpackblock(), and unpackundo().
ivec block3::o
Referenced by blockcube(), changed(), genprefabmesh(), packblock(), swapundo(), and unpackblock().
int block3::orient
Referenced by blockcube(), packblock(), pasteblock(), swapundo(), and unpackblock().
ivec block3::s
Referenced by blockcube(), changed(), genprefabmesh(), packblock(), pasteblock(), pastehilite(), previewprefab(), renderprefab(), size(), swapundo(), and unpackblock().
The documentation for this struct was generated from the following file:
inexor/engine/octree.hpp