Inexor: BIH Struct Reference
BIH Struct Reference
#include <bih.hpp>
Classes
struct mesh
struct node
struct tri
struct tribb
Public Types
enum { MESH_NOCLIP = 1<<0, MESH_ALPHA = 1<<1, MESH_CULLFACE = 1<<2 }
Public Member Functions
BIH (vector< mesh > &buildmeshes)
~BIH ()
void build (mesh &m, ushort *indices, int numindices, const ivec &vmin, const ivec &vmax)
bool traverse (const vec &o, const vec &ray, float maxdist, float &dist, int mode)
bool traverse (const mesh &m, const vec &o, const vec &ray, const vec &invray, float maxdist, float &dist, int mode, node *curnode, float tmin, float tmax)
bool triintersect (const mesh &m, int tidx, const vec &mo, const vec &mray, float maxdist, float &dist, int mode)
void preload ()
Public Attributes
mesh * meshes
int nummeshes
node * nodes
int numnodes
tribb * tribbs
int numtris
vec bbmin
vec bbmax
vec center
float radius
float entradius
Class Documentation
struct BIH::tri
Class Members
ushort vert[3]
Member Enumeration Documentation
anonymous enum
Enumerator
MESH_NOCLIP
MESH_ALPHA
MESH_CULLFACE
Constructor & Destructor Documentation
BIH::BIH (vector< mesh > & buildmeshes)
References matrix4x3::a, vec::add(), BIH::mesh::bbmax, bbmax, BIH::mesh::bbmin, bbmin, build(), ivec::ceil(), BIH::tribb::center, center, vector< T, MINSIZE >::empty(), entradius, f(), ivec::floor(), vector< T, MINSIZE >::getbuf(), BIH::mesh::getpos(), sphere::indices, matrix4x3::invert(), BIH::mesh::invscale, BIH::mesh::invxform, BIH::mesh::invxformnorm, vector< T, MINSIZE >::length(), loopi(), loopj, loopv, vec::magnitude(), vec::max(), inexor::rpc::max(), meshes, vec::min(), vec::mul(), BIH::mesh::nodes, nodes, matrix3::normalize(), nummeshes, BIH::mesh::numnodes, numnodes, BIH::mesh::numtris, numtris, BIH::tribb::radius, radius, BIH::mesh::scale, vec::squaredlen(), vec::sub(), matrix4x3::transform(), BIH::mesh::tribbs, tribbs, BIH::mesh::tris, BIH::tri::vert, BIH::mesh::xform, and BIH::mesh::xformnorm.
BIH::~BIH ()
References meshes, nodes, and tribbs.
Member Function Documentation
void BIH::build (mesh & m, ushort * indices, int numindices, const ivec & vmin, const ivec & vmax)
References ivec::add(), BIH::tribb::center, BIH::node::child, loopi(), loopk, inexor::rpc::max(), ivec::max(), inexor::rpc::min(), ivec::min(), BIH::mesh::nodes, BIH::mesh::numnodes, BIH::tribb::radius, BIH::node::split, ivec::sub(), and BIH::mesh::tribbs.
Referenced by BIH().
void BIH::preload ()
bool BIH::traverse (const vec & o, const vec & ray, float maxdist, float & dist, int mode) inline
References BIH::mesh::bbmax, BIH::mesh::bbmin, BIH::mesh::flags, loopi(), inexor::rpc::max(), MESH_NOCLIP, meshes, inexor::rpc::min(), BIH::mesh::nodes, nummeshes, and RAY_SHADOW.
Referenced by mmintersect(), and traverse().
bool BIH::traverse (const mesh & m, const vec & o, const vec & ray, const vec & invray, float maxdist, float & dist, int mode, node * curnode, float tmin, float tmax) inline
References BIH::node::axis(), BIH::node::childindex(), BIH::mesh::invxform, BIH::mesh::invxformnorm, BIH::node::isleaf(), inexor::rpc::max(), inexor::rpc::min(), traversestate::node, save(), BIH::node::split, traversestate::tmax, traversestate::tmin, matrix3::transform(), matrix4x3::transform(), traverse(), and triintersect().
bool BIH::triintersect (const mesh & m, int tidx, const vec & mo, const vec & mray, float maxdist, float & dist, int mode)
References vec2::add(), Texture::alphamask, at(), vec::cross(), vec::dot(), f(), BIH::mesh::flags, BIH::mesh::getpos(), BIH::mesh::gettc(), lightmapping, loadalphamask(), MESH_ALPHA, MESH_CULLFACE, vec2::mul(), RAY_ALPHAPOLY, RAY_SHADOW, BIH::mesh::scale, vec2::sub(), vec::sub(), anonymous_namespace{utilTest.cpp}::t(), BIH::mesh::tex, BIH::mesh::tris, BIH::tri::vert, Texture::xs, and Texture::ys.
Referenced by traverse().
Member Data Documentation
vec BIH::bbmax
Referenced by BIH().
vec BIH::bbmin
Referenced by BIH().
vec BIH::center
Referenced by BIH().
float BIH::entradius
Referenced by BIH(), and mmintersect().
mesh* BIH::meshes
Referenced by BIH(), traverse(), and ~BIH().
node* BIH::nodes
Referenced by BIH(), and ~BIH().
int BIH::nummeshes
Referenced by BIH(), and traverse().
int BIH::numnodes
Referenced by BIH().
int BIH::numtris
Referenced by BIH().
float BIH::radius
Referenced by BIH().
tribb* BIH::tribbs
Referenced by BIH(), and ~BIH().
The documentation for this struct was generated from the following files:
inexor/physics/bih.hpp
inexor/physics/bih.cpp