Inexor: game::ctfclientmode Struct Reference
game::ctfclientmode Struct Reference
#include <ctf_client.hpp>
Public Member Functions
bool addflag (int i, const vec &o, int team, int vistime=-1000)
void ownflag (int i, fpsent *owner, int owntime)
void returnflag (int i, int vistime=-1000)
void preload () override
void drawblip (fpsent *d, float x, float y, float s, const vec &pos, bool flagblip)
void drawblip (fpsent *d, float x, float y, float s, int i, bool flagblip)
int clipconsole (int w, int h) override
void drawhud (fpsent *d, int w, int h) override
void removeplayer (fpsent *d) override
vec interpflagpos (flag &f, float &angle)
vec interpflagpos (flag &f)
void rendergame () override
void setup () override
void senditems (packetbuf &p) override
void parseflags (ucharbuf &p, bool commit)
void trydropflag ()
const char * teamcolorflag (flag &f)
void dropflag (int i, const vec &o, float yaw, int droptime)
void dropflag (fpsent *d, int i, int version, const vec &droploc)
void flagexplosion (int i, int team, const vec &loc)
void flageffect (int i, int team, const vec &from, const vec &to)
void returnflag (fpsent *d, int i, int version)
void spawnflag (flag &f)
void resetflag (int i, int version, int spawnindex, int team, int score)
void scoreflag (fpsent *d, int relay, int relayversion, int goal, int goalversion, int goalspawn, int team, int score, int dflags, int time)
void takeflag (fpsent *d, int i, int version)
void invisflag (int i, int invis)
void checkitems (fpsent *d) override
void respawned (fpsent *d) override
int respawnwait (fpsent *d) override
bool pickholdspawn (fpsent *d)
void pickspawn (fpsent *d) override
bool aihomerun (fpsent *d, ai::aistate &b)
bool aicheck (fpsent *d, ai::aistate &b) override
void aifind (fpsent *d, ai::aistate &b, vector< ai::interest > &interests) override
bool aidefend (fpsent *d, ai::aistate &b) override
bool aipursue (fpsent *d, ai::aistate &b) override
bool parse_network_message (int type, ucharbuf &p) override
Parse game mode specific network messages.
virtual bool isinvisible (fpsent *d)
virtual void addplayer (fpsent *d)
virtual void gameover ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual void killed (fpsent *d, fpsent *actor)
virtual void gameconnect (fpsent *d)
virtual void renderscoreboard (g3d_gui &g, scoregroup &sg, int fgcolor, int bgcolor)
void resetflags ()
bool addflag (int i, const vec &o, int team)
bool addholdspawn (const vec &o)
int totalscore (int team)
int setscore (int team, int score)
int addscore (int team, int score)
bool hidefrags ()
int getteamscore (const char *team)
void getteamscores (vector< teamscore > &tscores)
bool insidebase (const flag &f, const vec &o)
Public Attributes
vector< holdspawn > holdspawns
vector< flag > flags
int scores [2]
Static Public Attributes
static const int BASERADIUS = 64
static const int BASEHEIGHT = 24
static const int MAXFLAGS = 20
static const int FLAGRADIUS = 16
static const int FLAGLIMIT = 10
static const int MAXHOLDSPAWNS = 100
static const int HOLDSECS = 20
static const int HOLDFLAGS = 1
static const int RESPAWNSECS = 5
Member Function Documentation
bool game::ctfclientmode::addflag (int i, const vec & o, int team, int vistime = -1000)
References ctfmode::addflag(), f(), ctfmode::flags, flag::id, loopv, game::players, and flag::vistime.
Referenced by setup().
bool ctfmode::addflag (int i, const vec & o, int team) inline inherited
References vector< T, MINSIZE >::add(), f(), ctfmode::flags, flag::id, vector< T, MINSIZE >::length(), ctfmode::MAXFLAGS, flag::reset(), flag::spawnloc, and flag::team.
Referenced by server::ctfservermode::addflag(), and addflag().
bool ctfmode::addholdspawn (const vec & o) inline inherited
References ctfmode::holdspawns, ctfmode::MAXHOLDSPAWNS, and ctfmode::holdspawn::o.
Referenced by server::ctfservermode::parseflags(), server::ctfservermode::setup(), and setup().
virtual void game::clientmode::addplayer (fpsent * d) inline virtual inherited
int ctfmode::addscore (int team, int score) inline inherited
References ctfmode::scores.
Referenced by server::ctfservermode::scoreflag(), and server::ctfservermode::update().
bool game::ctfclientmode::aicheck (fpsent * d, ai::aistate & b) override virtual
Reimplemented from game::clientmode.
References vector< T, MINSIZE >::add(), fpsent::ai, ai::AI_S_PURSUE, ai::AI_T_AFFINITY, aihomerun(), ai::badhealth(), fpsent::clientnum, ctfteamflag, flag::droptime, vector< T, MINSIZE >::empty(), ctfmode::flags, vector< T, MINSIZE >::length(), loopv, flag::owner, flag::owner_id, rnd(), vector< T, MINSIZE >::setsize(), ai::aiinfo::switchstate(), flag::team, and fpsent::team.
bool game::ctfclientmode::aidefend (fpsent * d, ai::aistate & b) override virtual
Reimplemented from game::clientmode.
References vector< T, MINSIZE >::add(), fpsent::ai, ai::AI_S_DEFEND, ai::AI_T_AFFINITY, aihomerun(), ai::checkothers(), fpsent::clientnum, CS_ALIVE, ai::defend(), flag::droptime, vector< T, MINSIZE >::empty(), f(), physent::feetpos(), vector< T, MINSIZE >::find(), ctfmode::FLAGRADIUS, ctfmode::flags, vector< T, MINSIZE >::inrange(), isteam, game::iterdynents(), lastmillis, loopi(), loopv, m_hold, m_protect, ai::makeroute(), ai::aistate::millis, game::numdynents(), flag::owner, flag::owner_id, flag::pos(), vector< T, MINSIZE >::setsize(), fpsstate::skill, vec::squaredist(), physent::state, ai::aistate::target, ai::targets, fpsent::team, ai::aiinfo::trywipe, and ai::violence().
void game::ctfclientmode::aifind (fpsent * d, ai::aistate & b, vector< ai::interest > & interests) override virtual
Reimplemented from game::clientmode.
References vector< T, MINSIZE >::add(), fpsent::ai, ai::AI_S_DEFEND, ai::AI_S_PURSUE, ai::AI_T_AFFINITY, ai::AI_T_PLAYER, ai::checkothers(), fpsent::clientnum, ai::closestwaypoint(), CS_ALIVE, ctfteamflag, flag::droptime, vector< T, MINSIZE >::empty(), f(), physent::feetpos(), vector< T, MINSIZE >::find(), ctfmode::FLAGRADIUS, ctfmode::flags, game::getclient(), GUN_FIST, GUN_PISTOL, fpsstate::gunselect, fpsstate::hasammo(), isteam, game::iterdynents(), fpsent::lastnode, loopi(), loopvj, loopvk, m_hold, m_protect, ai::interest::node, game::numdynents(), physent::o, flag::owner, flag::owner_id, flag::pos(), ai::interest::score, vector< T, MINSIZE >::setsize(), ai::SIGHTMIN, vec::squaredist(), physent::state, ai::interest::state, anonymous_namespace{utilTest.cpp}::t(), ai::interest::target, ai::targets, ai::interest::targtype, flag::team, fpsent::team, and ai::aiinfo::weappref.
bool game::ctfclientmode::aihomerun (fpsent * d, ai::aistate & b)
References fpsent::ai, ai::AI_S_INTEREST, ai::AI_S_PURSUE, ai::AI_T_AFFINITY, ai::AI_T_NODE, ai::assist(), ctfteamflag, flag::droptime, physent::feetpos(), ctfmode::flags, vector< T, MINSIZE >::inrange(), loopk, loopv, m_hold, m_protect, ai::makeroute(), flag::owner, ai::parseinterests(), flag::pos(), ai::randomnode(), ai::aiinfo::route, vector< T, MINSIZE >::setsize(), ai::SIGHTMIN, vec::squaredist(), ai::aiinfo::switchstate(), ai::aistate::targtype, flag::team, fpsent::team, and ai::aistate::type.
Referenced by aicheck(), aidefend(), and aipursue().
bool game::ctfclientmode::aipursue (fpsent * d, ai::aistate & b) override virtual
Reimplemented from game::clientmode.
References aihomerun(), fpsent::clientnum, ctfteamflag, flag::droptime, f(), ctfmode::flags, vector< T, MINSIZE >::inrange(), loopv, m_hold, ai::makeroute(), flag::owner, flag::owner_id, flag::pos(), ai::aistate::target, flag::team, fpsent::team, and ai::violence().
void game::ctfclientmode::checkitems (fpsent * d) override virtual
Reimplemented from game::clientmode.
References game::addmsg(), CS_ALIVE, ctfflagteam, vec::dist(), flag::droploc, flag::droptime, f(), physent::feetpos(), fpsent::flagpickup, ctfmode::FLAGRADIUS, ctfmode::flags, flag::id, lookupmaterial(), loopv, m_hold, MAT_GAMECLIP, MATF_CLIP, N_TAKEFLAG, flag::owner, flag::spawnindex, flag::spawnloc, physent::state, flag::team, and flag::version.
int game::ctfclientmode::clipconsole (int w, int h) inline override virtual
Reimplemented from game::clientmode.
void game::ctfclientmode::drawblip (fpsent * d, float x, float y, float s, const vec & pos, bool flagblip)
References game::calcradarscale(), camera1, dir, vec::div(), game::drawradar(), f(), vec::magnitude2(), vec::mul(), physent::o, RAD, vec::rotate_around_z(), vec::sub(), and physent::yaw.
Referenced by drawblip(), and drawhud().
void game::ctfclientmode::drawblip (fpsent * d, float x, float y, float s, int i, bool flagblip)
References ctfteamflag, drawblip(), flag::droploc, flag::droptime, f(), ctfmode::flags, lastmillis, m_hold, physent::o, flag::owner, game::player1, game::setbliptex(), flag::spawnloc, flag::team, fpsent::team, TEAM_NONE, TEAM_OPPONENT, and TEAM_OWN.
void game::ctfclientmode::drawhud (fpsent * d, int w, int h) override virtual
Reimplemented from game::clientmode.
References bindminimap(), fpsent::clientnum, COL_RED, CS_ALIVE, CS_DEAD, ctfflagteam, ctfteamflag, draw_textf(), drawblip(), game::drawicon(), game::drawminimap(), game::drawradar(), game::drawteammates(), flag::droploc, flag::droptime, f(), ctfmode::flags, flushhudmatrix(), HICON_BLUE_FLAG, HICON_NEUTRAL_FLAG, HICON_RED_FLAG, HICON_SIZE, HICON_SPACE, HICON_STEP, HICON_TEXTY, HICON_X, HICON_Y, ctfmode::HOLDSECS, ctfmode::holdspawns, hudmatrix, lastmillis, game::lastspawnattempt, loopv, m_efficiency, m_hold, m_protect, inexor::rpc::max(), game::minimapalpha, flag::owner_id, game::player1, pophudmatrix(), pushhudmatrix(), fpsstate::quadmillis, respawnwait(), matrix4::scale(), game::setbliptex(), game::setradartex(), flag::spawnindex, physent::state, flag::team, fpsent::team, and TEAM_NONE.
void game::ctfclientmode::dropflag (int i, const vec & o, float yaw, int droptime)
References flag::dropangle, flag::droploc, flag::droptime, f(), ctfmode::flags, flag::id, loopv, flag::owner, game::players, and flag::vistime.
Referenced by dropflag(), parse_network_message(), and removeplayer().
void game::ctfclientmode::dropflag (fpsent * d, int i, int version, const vec & droploc)
References dropflag(), flag::droploc, droptofloor(), f(), fpsent::flagpickup, ctfmode::flags, inexor::util::log_manager::game, flag::id, vector< T, MINSIZE >::inrange(), flag::interpangle, interpflagpos(), flag::interploc, flag::interptime, lastmillis, Log, inexor::sound::playsound(), S_FLAGDROP, teamcolorflag(), game::teamcolorname(), flag::version, and physent::yaw.
void game::ctfclientmode::flageffect (int i, int team, const vec & from, const vec & to)
References ctfteamflag, flagexplosion(), PART_LIGHTNING, particle_flare(), game::player1, and fpsent::team.
Referenced by resetflag(), returnflag(), and scoreflag().
void game::ctfclientmode::flagexplosion (int i, int team, const vec & loc)
References adddynlight(), gle::color(), ctfteamflag, f(), PART_EXPLOSION, PART_SPARK, particle_fireball(), particle_splash(), game::player1, and fpsent::team.
Referenced by flageffect().
virtual void game::clientmode::gameconnect (fpsent * d) inline virtual inherited
Reimplemented in game::bombclientmode.
virtual void game::clientmode::gameover () inline virtual inherited
Referenced by game::timeupdate().
virtual int game::clientmode::getteamscore (const char * team) inline virtual inherited
Referenced by game::groupplayers().
int ctfmode::getteamscore (const char * team) inline inherited
References ctfteamflag, and ctfmode::totalscore().
virtual void game::clientmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by game::getbestteams().
void ctfmode::getteamscores (vector< teamscore > & tscores) inline inherited
References vector< T, MINSIZE >::add(), ctfflagteam, loopk, and ctfmode::scores.
virtual bool game::clientmode::hidefrags () inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::getbestteams(), game::groupplayers(), game::parsemessages(), and game::renderscoreboard().
bool ctfmode::hidefrags () inline inherited
bool ctfmode::insidebase (const flag & f, const vec & o) inline inherited
References ctfmode::BASEHEIGHT, ctfmode::BASERADIUS, and flag::spawnloc.
Referenced by server::ctfservermode::dropflag(), and rendergame().
vec game::ctfclientmode::interpflagpos (flag & f, float & angle)
References physent::abovehead(), camera1, flag::dropangle, flag::droploc, flag::droptime, flag::interpangle, flag::interploc, flag::interptime, lastmillis, vec::lerp(), m_hold, inexor::rpc::min(), physent::o, flag::owner, flag::spawnangle, flag::spawnloc, anonymous_namespace{utilTest.cpp}::t(), vectoyawpitch(), and physent::yaw.
Referenced by dropflag(), rendergame(), resetflag(), returnflag(), scoreflag(), and takeflag().
vec game::ctfclientmode::interpflagpos (flag & f) inline
References interpflagpos().
Referenced by interpflagpos().
void game::ctfclientmode::invisflag (int i, int invis)
References f(), ctfmode::flags, vector< T, MINSIZE >::inrange(), lastmillis, and flag::vistime.
Referenced by parse_network_message().
virtual bool game::clientmode::isinvisible (fpsent * d) inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::rendergame().
virtual void game::clientmode::killed (fpsent * d, fpsent * actor) inline virtual inherited
Reimplemented in game::hideandseekclientmode, and game::bombclientmode.
Referenced by game::killed().
void game::ctfclientmode::ownflag (int i, fpsent * owner, int owntime)
References fpsent::clientnum, f(), ctfmode::flags, flag::id, loopv, flag::owner, flag::owner_id, flag::owntime, game::players, and flag::vistime.
Referenced by takeflag().
bool game::ctfclientmode::parse_network_message (int type, ucharbuf & p) override virtual
Parse game mode specific network messages.
Returns
true if message got handled.
Implements game::clientmode.
References fpsent::clientnum, DMF, dropflag(), getint(), invisflag(), loopk, m_ctf, N_DROPFLAG, N_INITFLAGS, N_INVISFLAG, N_RESETFLAG, N_RETURNFLAG, N_SCOREFLAG, N_TAKEFLAG, game::newclient(), parseflags(), game::player1, resetflag(), returnflag(), scoreflag(), and takeflag().
void game::ctfclientmode::parseflags (ucharbuf & p, bool commit)
References fpsent::clientnum, DMF, flag::droploc, flag::droptime, droptofloor(), f(), ctfmode::flags, getint(), vector< T, MINSIZE >::inrange(), flag::interptime, loopi(), loopk, m_hold, game::newclient(), databuf< T >::overread(), flag::owner, flag::owner_id, game::player1, ctfmode::scores, spawnflag(), flag::spawnindex, flag::spawnloc, flag::version, and flag::vistime.
Referenced by parse_network_message().
bool game::ctfclientmode::pickholdspawn (fpsent * d)
References vector< T, MINSIZE >::add(), entity::attr2, vec::dist(), flag::droploc, flag::droptime, vector< T, MINSIZE >::empty(), entinmap(), entities::ents, f(), ctfmode::flags, vector< T, MINSIZE >::length(), loopk, loopv, loopvj, entity::o, physent::o, flag::owner, physent::pitch, PLAYERSTART, rnd(), physent::roll, flag::spawnindex, entity::type, and physent::yaw.
Referenced by pickspawn().
void game::ctfclientmode::pickspawn (fpsent * d) override virtual
Reimplemented from game::clientmode.
References ctfteamflag, findplayerspawn(), m_hold, pickholdspawn(), and fpsent::team.
void game::ctfclientmode::preload () override virtual
Reimplemented from game::clientmode.
References loopi(), m_hold, preloadmodel(), inexor::sound::preloadsound(), S_FLAGDROP, S_FLAGFAIL, S_FLAGPICKUP, S_FLAGRESET, S_FLAGRETURN, and S_FLAGSCORE.
void game::ctfclientmode::removeplayer (fpsent * d) override virtual
Reimplemented from game::clientmode.
References fpsent::clientnum, dropflag(), f(), ctfmode::flags, flag::interploc, flag::interptime, loopv, physent::o, flag::owner, and physent::yaw.
void game::ctfclientmode::rendergame () override virtual
Reimplemented from game::clientmode.
References ANIM_LOOP, ANIM_MAPMODEL, canaddparticles(), fpsent::clientnum, ctfteamflag, hmap::d, flag::droploc, flag::droptime, f(), physent::feetpos(), ctfmode::flags, vector< T, MINSIZE >::inrange(), ctfmode::insidebase(), interpflagpos(), fpsent::lastbase, lastmillis, flag::light, loopv, m_hold, m_protect, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_DYNSHADOW, MDL_GHOST, MDL_LIGHT, inexor::rpc::min(), flag::owner, flag::owner_id, PART_EXPLOSION, PART_LIGHTNING, PART_SPARK, particle_fireball(), particle_flare(), particle_splash(), game::player1, game::players, rendermodel(), flag::spawnindex, flag::spawnloc, flag::team, fpsent::team, and flag::vistime.
virtual void game::clientmode::renderscoreboard (g3d_gui & g, scoregroup & sg, int fgcolor, int bgcolor) inline virtual inherited
Reimplemented in game::bombclientmode, and game::hideandseekclientmode.
Referenced by game::renderscoreboard().
void game::ctfclientmode::resetflag (int i, int version, int spawnindex, int team, int score)
References f(), flageffect(), ctfmode::flags, inexor::util::log_manager::game, vector< T, MINSIZE >::inrange(), interpflagpos(), flag::interptime, Log, m_hold, m_protect, inexor::sound::playsound(), returnflag(), S_FLAGRESET, ctfmode::setscore(), spawnflag(), flag::spawnindex, flag::spawnloc, teamcolorflag(), and flag::version.
Referenced by parse_network_message().
void ctfmode::resetflags () inline inherited
References ctfmode::flags, ctfmode::holdspawns, loopk, ctfmode::scores, and vector< T, MINSIZE >::shrink().
Referenced by server::ctfservermode::reset(), and setup().
void game::ctfclientmode::respawned (fpsent * d) override virtual
Reimplemented from game::clientmode.
References ctfflagteam, vec::dist(), flag::droploc, flag::droptime, f(), physent::feetpos(), fpsent::flagpickup, ctfmode::FLAGRADIUS, ctfmode::flags, flag::id, loopv, m_hold, flag::owner, flag::spawnindex, flag::spawnloc, and flag::team.
int game::ctfclientmode::respawnwait (fpsent * d) override virtual
Reimplemented from game::clientmode.
References lastmillis, fpsent::lastpain, m_efficiency, m_protect, inexor::rpc::max(), and ctfmode::RESPAWNSECS.
Referenced by drawhud().
void game::ctfclientmode::returnflag (int i, int vistime = -1000)
References flag::droptime, f(), ctfmode::flags, flag::id, loopv, flag::owner, flag::owner_id, game::players, and flag::vistime.
Referenced by parse_network_message(), resetflag(), returnflag(), and scoreflag().
void game::ctfclientmode::returnflag (fpsent * d, int i, int version)
References vec::dist(), f(), physent::feetpos(), flageffect(), fpsent::flagpickup, ctfmode::FLAGRADIUS, ctfmode::flags, inexor::util::log_manager::game, flag::id, vector< T, MINSIZE >::inrange(), interpflagpos(), flag::interptime, Log, m_protect, inexor::sound::playsound(), returnflag(), S_FLAGRETURN, flag::spawnloc, flag::team, teamcolorflag(), game::teamcolorname(), and flag::version.
void game::ctfclientmode::scoreflag (fpsent * d, int relay, int relayversion, int goal, int goalversion, int goalspawn, int team, int score, int dflags, int time)
References physent::abovehead(), ctfflagteam, ctfteamflag, defformatstring, vec::dist(), f(), physent::feetpos(), flageffect(), ctfmode::FLAGLIMIT, fpsent::flagpickup, ctfmode::FLAGRADIUS, fpsent::flags, ctfmode::flags, inexor::util::log_manager::game, flag::id, vector< T, MINSIZE >::inrange(), interpflagpos(), flag::interptime, Log, m_hold, m_protect, PART_TEXT, particle_textcopy(), game::player1, inexor::sound::playsound(), returnflag(), S_FLAGFAIL, S_FLAGSCORE, ctfmode::setscore(), spawnflag(), flag::spawnindex, flag::spawnloc, fpsent::team, game::teamcolor(), game::teamcolorname(), and flag::version.
Referenced by parse_network_message().
void game::ctfclientmode::senditems (packetbuf & p) override virtual
Reimplemented from game::clientmode.
References DMF, f(), ctfmode::flags, ctfmode::holdspawns, vector< T, MINSIZE >::length(), loopk, loopv, m_hold, N_INITFLAGS, ctfmode::holdspawn::o, putint(), flag::spawnloc, and flag::team.
int ctfmode::setscore (int team, int score) inline inherited
References ctfmode::scores.
Referenced by resetflag(), and scoreflag().
void game::ctfclientmode::setup () override virtual
Reimplemented from game::clientmode.
References addflag(), ctfmode::addholdspawn(), entity::attr1, entity::attr2, BASE, entities::ents, FLAG, ctfmode::flags, ctfmode::HOLDFLAGS, ctfmode::holdspawns, vector< T, MINSIZE >::length(), extentity::light, loopv, m_hold, m_protect, entity::o, ctfmode::resetflags(), and entity::type.
void game::ctfclientmode::spawnflag (flag & f)
References ctfmode::holdspawns, flag::light, ctfmode::holdspawn::light, ctfmode::holdspawn::o, flag::spawnindex, and flag::spawnloc.
Referenced by parseflags(), resetflag(), and scoreflag().
void game::ctfclientmode::takeflag (fpsent * d, int i, int version)
References flag::droptime, f(), ctfmode::flags, inexor::util::log_manager::game, vector< T, MINSIZE >::inrange(), flag::interpangle, interpflagpos(), flag::interploc, flag::interptime, lastmillis, Log, m_hold, m_protect, ownflag(), inexor::sound::playsound(), S_FLAGPICKUP, fpsent::team, game::teamcolor(), teamcolorflag(), game::teamcolorname(), and flag::version.
Referenced by parse_network_message().
const char * game::ctfclientmode::teamcolorflag (flag & f)
References ctfflagteam, m_hold, flag::team, and game::teamcolor().
Referenced by dropflag(), resetflag(), returnflag(), and takeflag().
int ctfmode::totalscore (int team) inline inherited
References ctfmode::scores.
Referenced by ctfmode::getteamscore().
void game::ctfclientmode::trydropflag ()
References game::addmsg(), fpsent::clientnum, ctfmode::flags, loopv, m_ctf, N_TRYDROPFLAG, and game::player1.
Member Data Documentation
const int ctfmode::BASEHEIGHT = 24 static inherited
Referenced by ctfmode::insidebase().
const int ctfmode::BASERADIUS = 64 static inherited
Referenced by ctfmode::insidebase().
const int ctfmode::FLAGLIMIT = 10 static inherited
Referenced by scoreflag(), and server::ctfservermode::scoreflag().
const int ctfmode::FLAGRADIUS = 16 static inherited
Referenced by aidefend(), aifind(), checkitems(), respawned(), returnflag(), and scoreflag().
vector<flag> ctfmode::flags inherited
Referenced by server::ctfservermode::addflag(), addflag(), ctfmode::addflag(), aicheck(), aidefend(), aifind(), aihomerun(), aipursue(), checkitems(), server::ctfservermode::died(), drawblip(), drawhud(), server::ctfservermode::dropflag(), dropflag(), server::ctfservermode::initclient(), invisflag(), server::ctfservermode::leavegame(), server::ctfservermode::ownflag(), ownflag(), parseflags(), pickholdspawn(), removeplayer(), rendergame(), resetflag(), ctfmode::resetflags(), respawned(), server::ctfservermode::returnflag(), returnflag(), scoreflag(), server::ctfservermode::scoreflag(), senditems(), server::ctfservermode::setup(), setup(), server::ctfservermode::setupholdspawns(), server::ctfservermode::spawnflag(), takeflag(), server::ctfservermode::takeflag(), trydropflag(), and server::ctfservermode::update().
const int ctfmode::HOLDFLAGS = 1 static inherited
Referenced by setup(), and server::ctfservermode::setupholdspawns().
const int ctfmode::HOLDSECS = 20 static inherited
Referenced by drawhud(), and server::ctfservermode::update().
vector<holdspawn> ctfmode::holdspawns inherited
Referenced by ctfmode::addholdspawn(), drawhud(), ctfmode::resetflags(), senditems(), setup(), server::ctfservermode::setupholdspawns(), spawnflag(), and server::ctfservermode::spawnflag().
const int ctfmode::MAXFLAGS = 20 static inherited
Referenced by ctfmode::addflag().
const int ctfmode::MAXHOLDSPAWNS = 100 static inherited
Referenced by ctfmode::addholdspawn().
const int ctfmode::RESPAWNSECS = 5 static inherited
Referenced by server::ctfservermode::canspawn(), and respawnwait().
int ctfmode::scores[2] inherited
Referenced by ctfmode::addscore(), ctfmode::getteamscores(), server::ctfservermode::initclient(), parseflags(), ctfmode::resetflags(), ctfmode::setscore(), and ctfmode::totalscore().
The documentation for this struct was generated from the following files:
inexor/client/gamemode/ctf_client.hpp
inexor/client/gamemode/ctf_client.cpp