Inexor: GlobalShaderParam Struct Reference
GlobalShaderParam Struct Reference
#include <shader.hpp>
Public Member Functions
GlobalShaderParam (const char *name)
GlobalShaderParamState * resolve ()
void setf (float x=0, float y=0, float z=0, float w=0)
void set (const vec &v, float w=0)
void set (const vec2 &v, float z=0, float w=0)
void set (const vec4 &v)
void set (const plane &p)
void set (const matrix2 &m)
void set (const matrix3 &m)
void set (const matrix4 &m)
template<class T >
void setv (const T *v, int n=1)
void seti (int x=0, int y=0, int z=0, int w=0)
void set (const ivec &v, int w=0)
void set (const ivec2 &v, int z=0, int w=0)
void set (const ivec4 &v)
void setu (uint x=0, uint y=0, uint z=0, uint w=0)
template<class T >
T * reserve (int n=1)
Public Attributes
const char * name
GlobalShaderParamState * param
Constructor & Destructor Documentation
GlobalShaderParam::GlobalShaderParam (const char * name) inline
Member Function Documentation
template<class T > T* GlobalShaderParam::reserve (int n = 1) inline
References resolve().
GlobalShaderParamState* GlobalShaderParam::resolve () inline
References GlobalShaderParamState::changed(), getglobalparam(), name, and param.
Referenced by reserve(), set(), setf(), seti(), setu(), and setv().
void GlobalShaderParam::set (const vec & v, float w = 0) inline
References setf().
void GlobalShaderParam::set (const vec2 & v, float z = 0, float w = 0) inline
References setf().
void GlobalShaderParam::set (const vec4 & v) inline
References setf().
void GlobalShaderParam::set (const plane & p) inline
References plane::offset, and setf().
void GlobalShaderParam::set (const matrix2 & m) inline
References matrix2::a, and resolve().
void GlobalShaderParam::set (const matrix3 & m) inline
References matrix3::a, and resolve().
void GlobalShaderParam::set (const matrix4 & m) inline
References matrix4::a, and resolve().
void GlobalShaderParam::set (const ivec & v, int w = 0) inline
References seti().
void GlobalShaderParam::set (const ivec2 & v, int z = 0, int w = 0) inline
References seti().
void GlobalShaderParam::set (const ivec4 & v) inline
References seti().
void GlobalShaderParam::setf (float x = 0, float y = 0, float z = 0, float w = 0) inline
References resolve().
Referenced by set().
void GlobalShaderParam::seti (int x = 0, int y = 0, int z = 0, int w = 0) inline
References resolve().
Referenced by set().
void GlobalShaderParam::setu (uint x = 0, uint y = 0, uint z = 0, uint w = 0) inline
References resolve().
template<class T > void GlobalShaderParam::setv (const T * v, int n = 1) inline
References resolve().
Member Data Documentation
const char* GlobalShaderParam::name
Referenced by resolve().
GlobalShaderParamState* GlobalShaderParam::param
Referenced by resolve().
The documentation for this struct was generated from the following file:
inexor/engine/shader.hpp