Inexor: game::collectclientmode Struct Reference
game::collectclientmode Struct Reference
#include <collect_client.hpp>
Public Member Functions
token & droptoken (int id, const vec &o, int team, int droptime)
void preload () override
void drawblip (fpsent *d, float x, float y, float s, const vec &pos, float size=0.05f)
void drawbaseblip (fpsent *d, float x, float y, float s, int i)
int clipconsole (int w, int h) override
void drawhud (fpsent *d, int w, int h) override
void rendergame () override
void setup () override
void senditems (packetbuf &p) override
vec movetoken (const vec &o, int yaw)
void parsetokens (ucharbuf &p, bool commit)
void baseexplosion (int i, int team, const vec &loc)
void baseeffect (int i, int team, const vec &from, const vec &to, bool showfrom=true, bool showto=true)
void expiretoken (int id)
void taketoken (fpsent *d, int id, int total)
token * droptoken (fpsent *d, int id, const vec &o, int team, int yaw, int n)
void stealtoken (fpsent *d, int id, const vec &o, int team, int yaw, int n, int basenum, int enemyteam, int score)
void deposittokens (fpsent *d, int basenum, int deposited, int team, int score, int flags)
void checkitems (fpsent *d) override
int respawnwait (fpsent *d) override
void pickspawn (fpsent *d) override
bool aicheck (fpsent *d, ai::aistate &b) override
void aifind (fpsent *d, ai::aistate &b, vector< ai::interest > &interests) override
bool aipursue (fpsent *d, ai::aistate &b) override
bool parse_network_message (int type, ucharbuf &p) override
Parse game mode specific network messages.
virtual bool isinvisible (fpsent *d)
virtual void respawned (fpsent *d)
virtual void addplayer (fpsent *d)
virtual void removeplayer (fpsent *d)
virtual void gameover ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual bool aidefend (fpsent *d, ai::aistate &b)
virtual void killed (fpsent *d, fpsent *actor)
virtual void gameconnect (fpsent *d)
virtual void renderscoreboard (g3d_gui &g, scoregroup &sg, int fgcolor, int bgcolor)
void resetbases ()
bool addbase (int i, const vec &o, int team)
token * findtoken (int id)
token & droptoken (const vec &o, int team, int droptime)
bool removetoken (int id)
int totalscore (int team)
int setscore (int team, int score)
int addscore (int team, int score)
bool hidefrags ()
int getteamscore (const char *team)
void getteamscores (vector< teamscore > &tscores)
bool insidebase (const base &b, const vec &o)
Public Attributes
vector< base > bases
int scores [2]
vector< token > tokens
int nexttoken
Static Public Attributes
static const int TOKENHEIGHT = 5
static const int BASERADIUS = 16
static const int BASEHEIGHT = 16
static const int MAXBASES = 20
static const int TOKENRADIUS = 16
static const int TOKENLIMIT = 5
static const int UNOWNEDTOKENLIMIT = 15
static const int TOKENDIST = 16
static const int SCORELIMIT = 50
static const int RESPAWNSECS = 5
static const int EXPIRETOKENTIME = 10000
static const int STEALTOKENTIME = 5000
Member Function Documentation
bool collectmode_common::addbase (int i, const vec & o, int team) inline inherited
References collectmode_common::bases, collectmode_common::base::id, collectmode_common::MAXBASES, collectmode_common::base::o, collectmode_common::base::reset(), and collectmode_common::base::team.
Referenced by server::collectservermode::parsebases(), server::collectservermode::setup(), and setup().
virtual void game::clientmode::addplayer (fpsent * d) inline virtual inherited
int collectmode_common::addscore (int team, int score) inline inherited
References collectmode_common::scores.
Referenced by server::collectservermode::deposittokens().
bool game::collectclientmode::aicheck (fpsent * d, ai::aistate & b) override virtual
Reimplemented from game::clientmode.
References fpsent::ai, ai::AI_S_PURSUE, ai::AI_T_AFFINITY, ai::badhealth(), collectmode_common::bases, collectteambase, vec::dist(), f(), loopv, ai::makeroute(), collectmode_common::base::o, collectmode_common::token::o, physent::o, ai::aiinfo::switchstate(), anonymous_namespace{utilTest.cpp}::t(), fpsent::team, collectmode_common::base::team, collectmode_common::token::team, fpsent::tokens, and collectmode_common::tokens.
virtual bool game::clientmode::aidefend (fpsent * d, ai::aistate & b) inline virtual inherited
Reimplemented in game::ctfclientmode, and game::captureclientmode.
Referenced by ai::dodefend().
void game::collectclientmode::aifind (fpsent * d, ai::aistate & b, vector< ai::interest > & interests) override virtual
Reimplemented from game::clientmode.
References vector< T, MINSIZE >::add(), ai::AI_S_PURSUE, ai::AI_T_AFFINITY, collectmode_common::bases, ai::closestwaypoint(), collectteambase, f(), physent::feetpos(), collectmode_common::token::id, loopv, ai::interest::node, collectmode_common::base::o, collectmode_common::token::o, ai::interest::score, ai::SIGHTMIN, vec::squaredist(), ai::interest::state, anonymous_namespace{utilTest.cpp}::t(), ai::interest::target, ai::interest::targtype, fpsent::team, collectmode_common::base::team, collectmode_common::token::team, collectmode_common::TOKENLIMIT, fpsent::tokens, and collectmode_common::tokens.
bool game::collectclientmode::aipursue (fpsent * d, ai::aistate & b) override virtual
Reimplemented from game::clientmode.
References collectmode_common::bases, collectteambase, collectmode_common::findtoken(), ai::makeroute(), collectmode_common::base::o, collectmode_common::token::o, anonymous_namespace{utilTest.cpp}::t(), ai::aistate::target, fpsent::team, collectmode_common::base::team, and fpsent::tokens.
void game::collectclientmode::baseeffect (int i, int team, const vec & from, const vec & to, bool showfrom = true, bool showto = true)
References baseexplosion(), collectteambase, PART_LIGHTNING, particle_flare(), game::player1, and fpsent::team.
Referenced by deposittokens().
void game::collectclientmode::baseexplosion (int i, int team, const vec & loc)
References adddynlight(), collectteambase, gle::color(), f(), PART_EXPLOSION, PART_SPARK, particle_fireball(), particle_splash(), game::player1, and fpsent::team.
Referenced by baseeffect().
void game::collectclientmode::checkitems (fpsent * d) override virtual
Reimplemented from game::clientmode.
References game::addmsg(), collectmode_common::bases, collectbaseteam, collectteambase, CS_ALIVE, vec::dist(), physent::feetpos(), collectmode_common::token::id, collectmode_common::insidebase(), fpsent::lastcollect, lookupmaterial(), loopv, MAT_GAMECLIP, MATF_CLIP, N_DEPOSITTOKENS, N_TAKETOKEN, collectmode_common::token::o, physent::state, anonymous_namespace{utilTest.cpp}::t(), fpsent::team, collectmode_common::base::team, collectmode_common::TOKENLIMIT, collectmode_common::TOKENRADIUS, fpsent::tokens, and collectmode_common::tokens.
int game::collectclientmode::clipconsole (int w, int h) inline override virtual
Reimplemented from game::clientmode.
void game::collectclientmode::deposittokens (fpsent * d, int basenum, int deposited, int team, int score, int flags)
References baseeffect(), collectmode_common::bases, collectbaseteam, collectteambase, fpsent::flags, hmap::flags, inexor::util::log_manager::game, lastmillis, collectmode_common::base::laststeal, Log, loopv, game::player1, inexor::sound::playsound(), S_FLAGFAIL, S_FLAGSCORE, collectmode_common::SCORELIMIT, collectmode_common::setscore(), fpsent::team, collectmode_common::base::team, game::teamcolor(), game::teamcolorname(), collectmode_common::base::tokenpos, and fpsent::tokens.
Referenced by parse_network_message().
void game::collectclientmode::drawbaseblip (fpsent * d, float x, float y, float s, int i)
References collectmode_common::bases, collectteambase, drawblip(), collectmode_common::base::o, game::player1, game::setbliptex(), fpsent::team, collectmode_common::base::team, TEAM_OPPONENT, and TEAM_OWN.
Referenced by drawhud().
void game::collectclientmode::drawblip (fpsent * d, float x, float y, float s, const vec & pos, float size = 0.05f)
References game::calcradarscale(), camera1, dir, vec::div(), game::drawradar(), f(), vec::magnitude2(), vec::mul(), physent::o, RAD, vec::rotate_around_z(), vec::sub(), and physent::yaw.
Referenced by drawbaseblip(), and drawhud().
void game::collectclientmode::drawhud (fpsent * d, int w, int h) override virtual
Reimplemented from game::clientmode.
References collectmode_common::bases, bindminimap(), COL_RED, collectbaseteam, CS_ALIVE, CS_DEAD, draw_textf(), drawbaseblip(), drawblip(), game::drawicon(), game::drawminimap(), game::drawradar(), game::drawteammates(), flushhudmatrix(), HICON_SIZE, HICON_SPACE, HICON_STEP, HICON_TEXTY, HICON_TOKEN, HICON_X, HICON_Y, hudmatrix, isteam, lastmillis, game::lastspawnattempt, loopv, game::minimapalpha, physent::o, game::player1, game::players, pophudmatrix(), pushhudmatrix(), fpsstate::quadmillis, respawnwait(), matrix4::scale(), game::setbliptex(), game::setradartex(), physent::state, fpsent::team, collectmode_common::base::team, TEAM_OPPONENT, and fpsent::tokens.
collectmode_common::token & game::collectclientmode::droptoken (int id, const vec & o, int team, int droptime)
References collectmode_common::droptoken(), collectmode_common::token::id, and anonymous_namespace{utilTest.cpp}::t().
Referenced by droptoken(), parse_network_message(), parsetokens(), and stealtoken().
collectmode_common::token * game::collectclientmode::droptoken (fpsent * d, int id, const vec & o, int team, int yaw, int n)
References vec::add(), collectteambase, entitylight::color, entitylight::dir, droptoken(), lastmillis, collectmode_common::token::light, lightreaching(), movetoken(), collectmode_common::token::o, physent::o, PART_EXPLOSION, PART_LIGHTNING, PART_SPARK, particle_fireball(), particle_flare(), particle_splash(), game::player1, inexor::sound::playsound(), S_ITEMSPAWN, anonymous_namespace{utilTest.cpp}::t(), fpsent::team, and TOKENHEIGHT.
token& collectmode_common::droptoken (const vec & o, int team, int droptime) inline inherited
References collectmode_common::token::droptime, collectmode_common::token::o, anonymous_namespace{utilTest.cpp}::t(), collectmode_common::token::team, and collectmode_common::tokens.
Referenced by server::collectservermode::droptoken(), and droptoken().
void game::collectclientmode::expiretoken (int id)
References collectmode_common::findtoken(), collectmode_common::token::o, inexor::sound::playsound(), collectmode_common::removetoken(), S_ITEMAMMO, and anonymous_namespace{utilTest.cpp}::t().
Referenced by parse_network_message().
token* collectmode_common::findtoken (int id) inline inherited
References loopv, and collectmode_common::tokens.
Referenced by aipursue(), expiretoken(), taketoken(), and server::collectservermode::taketoken().
virtual void game::clientmode::gameconnect (fpsent * d) inline virtual inherited
Reimplemented in game::bombclientmode.
virtual void game::clientmode::gameover () inline virtual inherited
Referenced by game::timeupdate().
virtual int game::clientmode::getteamscore (const char * team) inline virtual inherited
Referenced by game::groupplayers().
int collectmode_common::getteamscore (const char * team) inline inherited
References collectteambase, and collectmode_common::totalscore().
virtual void game::clientmode::getteamscores (vector< teamscore > & scores) inline virtual inherited
Referenced by game::getbestteams().
void collectmode_common::getteamscores (vector< teamscore > & tscores) inline inherited
References vector< T, MINSIZE >::add(), collectbaseteam, loopk, and collectmode_common::scores.
virtual bool game::clientmode::hidefrags () inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::getbestteams(), game::groupplayers(), game::parsemessages(), and game::renderscoreboard().
bool collectmode_common::hidefrags () inline inherited
bool collectmode_common::insidebase (const base & b, const vec & o) inline inherited
References collectmode_common::BASEHEIGHT, collectmode_common::BASERADIUS, and collectmode_common::base::o.
Referenced by checkitems().
virtual bool game::clientmode::isinvisible (fpsent * d) inline virtual inherited
Reimplemented in game::hideandseekclientmode.
Referenced by game::rendergame().
virtual void game::clientmode::killed (fpsent * d, fpsent * actor) inline virtual inherited
Reimplemented in game::hideandseekclientmode, and game::bombclientmode.
Referenced by game::killed().
vec game::collectclientmode::movetoken (const vec & o, int yaw)
References hmap::d, dropent(), droptofloor(), ENT_BOUNCE, movecamera(), vec::mul(), collectmode_common::TOKENDIST, and vecfromyawpitch().
Referenced by droptoken(), and parsetokens().
bool game::collectclientmode::parse_network_message (int type, ucharbuf & p) override virtual
Parse game mode specific network messages.
Returns
true if message got handled.
Implements game::clientmode.
References fpsent::clientnum, deposittokens(), DMF, droptoken(), expiretoken(), hmap::flags, getint(), loopk, m_collect, N_DEPOSITTOKENS, N_DROPTOKENS, N_EXPIRETOKENS, N_INITTOKENS, N_STEALTOKENS, N_TAKETOKEN, game::newclient(), databuf< T >::overread(), parsetokens(), game::player1, stealtoken(), and taketoken().
void game::collectclientmode::parsetokens (ucharbuf & p, bool commit)
References fpsent::clientnum, hmap::d, DMF, droptoken(), getint(), lastmillis, loopi(), loopk, movetoken(), game::newclient(), databuf< T >::overread(), game::player1, collectmode_common::scores, fpsent::tokens, and collectmode_common::tokens.
Referenced by parse_network_message().
void game::collectclientmode::pickspawn (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
References collectteambase, findplayerspawn(), and fpsent::team.
void game::collectclientmode::preload () override virtual
Reimplemented from game::clientmode.
References loopi(), preloadmodel(), inexor::sound::preloadsound(), S_FLAGDROP, S_FLAGFAIL, and S_FLAGSCORE.
virtual void game::clientmode::removeplayer (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode.
Referenced by game::clientdisconnected().
bool collectmode_common::removetoken (int id) inline inherited
References loopv, and collectmode_common::tokens.
Referenced by expiretoken(), and taketoken().
void game::collectclientmode::rendergame () override virtual
Reimplemented from game::clientmode.
References physent::abovehead(), abovemodel(), vec::add(), ANIM_LOOP, ANIM_MAPMODEL, collectmode_common::bases, collectteambase, entitylight::color, CS_ALIVE, hmap::d, entitylight::dir, f(), formatstring(), game::hudplayer(), collectmode_common::base::info, isthirdperson(), lastmillis, collectmode_common::base::laststeal, collectmode_common::base::light, collectmode_common::token::light, lightreaching(), loopj, loopv, MDL_CULL_DIST, MDL_CULL_OCCLUDED, MDL_CULL_VFC, MDL_SHADOW, collectmode_common::base::o, collectmode_common::token::o, PART_FLAME, PART_TEXT, particle_text(), game::player1, game::players, regular_particle_flame(), rendermodel(), physent::state, collectmode_common::STEALTOKENTIME, anonymous_namespace{utilTest.cpp}::t(), fpsent::team, collectmode_common::base::team, collectmode_common::token::team, TOKENHEIGHT, collectmode_common::base::tokenpos, fpsent::tokens, collectmode_common::tokens, collectmode_common::totalscore(), and physent::yaw.
virtual void game::clientmode::renderscoreboard (g3d_gui & g, scoregroup & sg, int fgcolor, int bgcolor) inline virtual inherited
Reimplemented in game::bombclientmode, and game::hideandseekclientmode.
Referenced by game::renderscoreboard().
void collectmode_common::resetbases () inline inherited
References collectmode_common::bases, loopk, collectmode_common::nexttoken, collectmode_common::scores, and collectmode_common::tokens.
Referenced by server::collectservermode::reset(), and setup().
virtual void game::clientmode::respawned (fpsent * d) inline virtual inherited
Reimplemented in game::ctfclientmode, game::hideandseekclientmode, and game::captureclientmode.
Referenced by game::parsemessages().
int game::collectclientmode::respawnwait (fpsent * d) inline override virtual
Reimplemented from game::clientmode.
References lastmillis, fpsent::lastpain, inexor::rpc::max(), and collectmode_common::RESPAWNSECS.
Referenced by drawhud().
void game::collectclientmode::senditems (packetbuf & p) override virtual
Reimplemented from game::clientmode.
References collectmode_common::bases, DMF, loopk, loopv, N_INITTOKENS, collectmode_common::base::o, putint(), and collectmode_common::base::team.
int collectmode_common::setscore (int team, int score) inline inherited
References collectmode_common::scores.
Referenced by deposittokens(), and stealtoken().
void game::collectclientmode::setup () override virtual
Reimplemented from game::clientmode.
References abovemodel(), collectmode_common::addbase(), entity::attr2, collectmode_common::bases, entities::ents, FLAG, collectmode_common::base::light, extentity::light, loopv, collectmode_common::base::o, entity::o, collectmode_common::resetbases(), TOKENHEIGHT, collectmode_common::base::tokenpos, and entity::type.
void game::collectclientmode::stealtoken (fpsent * d, int id, const vec & o, int team, int yaw, int n, int basenum, int enemyteam, int score)
References collectmode_common::bases, collectbaseteam, collectteambase, droptoken(), inexor::util::log_manager::game, lastmillis, collectmode_common::base::laststeal, Log, collectmode_common::token::o, PART_LIGHTNING, particle_flare(), game::player1, inexor::sound::playsound(), S_FLAGDROP, collectmode_common::setscore(), anonymous_namespace{utilTest.cpp}::t(), fpsent::team, game::teamcolor(), game::teamcolorname(), TOKENHEIGHT, and collectmode_common::base::tokenpos.
Referenced by parse_network_message().
void game::collectclientmode::taketoken (fpsent * d, int id, int total)
References collectteambase, collectmode_common::findtoken(), physent::o, game::player1, inexor::sound::playsound(), collectmode_common::removetoken(), S_ITEMAMMO, S_ITEMHEALTH, anonymous_namespace{utilTest.cpp}::t(), fpsent::team, collectmode_common::token::team, and fpsent::tokens.
Referenced by parse_network_message().
int collectmode_common::totalscore (int team) inline inherited
References collectmode_common::scores.
Referenced by server::collectservermode::deposittokens(), collectmode_common::getteamscore(), and rendergame().
Member Data Documentation
const int collectmode_common::BASEHEIGHT = 16 static inherited
Referenced by collectmode_common::insidebase().
const int collectmode_common::BASERADIUS = 16 static inherited
Referenced by collectmode_common::insidebase().
vector<base> collectmode_common::bases inherited
Referenced by collectmode_common::addbase(), aicheck(), aifind(), aipursue(), checkitems(), deposittokens(), server::collectservermode::deposittokens(), drawbaseblip(), drawhud(), rendergame(), collectmode_common::resetbases(), senditems(), server::collectservermode::setup(), setup(), and stealtoken().
const int collectmode_common::EXPIRETOKENTIME = 10000 static inherited
Referenced by server::collectservermode::update().
const int collectmode_common::MAXBASES = 20 static inherited
Referenced by collectmode_common::addbase().
int collectmode_common::nexttoken inherited
Referenced by server::collectservermode::droptoken(), and collectmode_common::resetbases().
const int collectmode_common::RESPAWNSECS = 5 static inherited
Referenced by server::collectservermode::canspawn(), and respawnwait().
const int collectmode_common::SCORELIMIT = 50 static inherited
Referenced by deposittokens(), and server::collectservermode::deposittokens().
int collectmode_common::scores[2] inherited
Referenced by collectmode_common::addscore(), collectmode_common::getteamscores(), server::collectservermode::initclient(), parsetokens(), collectmode_common::resetbases(), collectmode_common::setscore(), and collectmode_common::totalscore().
const int collectmode_common::STEALTOKENTIME = 5000 static inherited
Referenced by server::collectservermode::deposittokens(), and rendergame().
const int collectmode_common::TOKENDIST = 16 static inherited
Referenced by movetoken().
const int game::collectclientmode::TOKENHEIGHT = 5 static
Referenced by droptoken(), rendergame(), setup(), and stealtoken().
const int collectmode_common::TOKENLIMIT = 5 static inherited
Referenced by aifind(), checkitems(), server::collectservermode::deposittokens(), server::collectservermode::droptokens(), and server::collectservermode::taketoken().
const int collectmode_common::TOKENRADIUS = 16 static inherited
Referenced by checkitems().
vector<token> collectmode_common::tokens inherited
Referenced by aicheck(), aifind(), checkitems(), server::collectservermode::deposittokens(), collectmode_common::droptoken(), server::collectservermode::droptokens(), collectmode_common::findtoken(), server::collectservermode::initclient(), server::collectservermode::leavegame(), parsetokens(), collectmode_common::removetoken(), rendergame(), collectmode_common::resetbases(), and server::collectservermode::update().
const int collectmode_common::UNOWNEDTOKENLIMIT = 15 static inherited
Referenced by server::collectservermode::leavegame().
The documentation for this struct was generated from the following files:
inexor/client/gamemode/collect_client.hpp
inexor/client/gamemode/collect_client.cpp