Inexor: undolist Struct Reference
undolist Struct Reference
Public Member Functions
undolist ()
bool empty ()
void add (undoblock *u)
undoblock * popfirst ()
undoblock * poplast ()
Public Attributes
undoblock * first
undoblock * last
Constructor & Destructor Documentation
undolist::undolist () inline
Member Function Documentation
void undolist::add (undoblock * u) inline
References undoblock::next, and undoblock::prev.
Referenced by addundo(), and swapundo().
bool undolist::empty () inline
Referenced by packundo(), pruneundos(), and swapundo().
undoblock* undolist::popfirst () inline
References undoblock::next, and undoblock::prev.
Referenced by pruneundos().
undoblock* undolist::poplast () inline
References undoblock::next, and undoblock::prev.
Referenced by swapundo().
Member Data Documentation
undoblock* undolist::first
Referenced by compacteditvslots().
undoblock * undolist::last
Referenced by packundo(), and swapundo().
The documentation for this struct was generated from the following file:
inexor/engine/octaedit.cpp