Inexor: animmodel::mesh Struct Reference
animmodel::mesh Struct Reference
#include <animmodel.hpp>
Public Member Functions
mesh ()
virtual ~mesh ()
virtual void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m)
virtual void genBIH (BIH::mesh &m)
void genBIH (skin &s, vector< BIH::mesh > &bih, const matrix4x3 &t)
virtual void setshader (Shader *s)
template<class V , class T >
void smoothnorms (V *verts, int numverts, T *tris, int numtris, float limit, bool areaweight)
template<class V , class T >
void buildnorms (V *verts, int numverts, T *tris, int numtris, bool areaweight)
template<class V , class T >
void buildnorms (V *verts, int numverts, T *tris, int numtris, bool areaweight, int numframes)
template<class B , class V , class TC , class T >
void calctangents (B *bumpverts, V *verts, TC *tcverts, int numverts, T *tris, int numtris, bool areaweight)
template<class B , class V , class TC , class T >
void calctangents (B *bumpverts, V *verts, TC *tcverts, int numverts, T *tris, int numtris, bool areaweight, int numframes)
Static Public Member Functions
static void fixqtangent (quat &q, float bt)
template<class V >
static void calctangent (V &v, const vec &n, const vec &t, float bt)
Public Attributes
meshgroup * group
char * name
bool noclip
Constructor & Destructor Documentation
animmodel::mesh::mesh () inline
virtual animmodel::mesh::~mesh () inline virtual
References DELETEA, and name.
Member Function Documentation
template<class V , class T > void animmodel::mesh::buildnorms (V * verts, int numverts, T * tris, int numtris, bool areaweight) inline
References vec::add(), vec::cross(), loopi(), vec::normalize(), vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by vertmodel::vertmesh::buildnorms(), skelmodel::skelmesh::buildnorms(), and buildnorms().
template<class V , class T > void animmodel::mesh::buildnorms (V * verts, int numverts, T * tris, int numtris, bool areaweight, int numframes) inline
References buildnorms(), and loopi().
virtual void animmodel::mesh::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline virtual
Reimplemented in vertmodel::vertmesh.
template<class V > static void animmodel::mesh::calctangent (V & v, const vec & n, const vec & t, float bt) inline static
References matrix3::a, matrix3::b, matrix3::c, vec::cross(), fixqtangent(), and anonymous_namespace{utilTest.cpp}::t().
template<class B , class V , class TC , class T > void animmodel::mesh::calctangents (B * bumpverts, V * verts, TC * tcverts, int numverts, T * tris, int numtris, bool areaweight) inline
References matrix3::a, vec::add(), matrix3::b, matrix3::c, vec::cross(), vec::dot(), fixqtangent(), loopi(), loopj, vec::mul(), vec::neg(), vec::normalize(), sphere::numverts, vec::sub(), anonymous_namespace{utilTest.cpp}::t(), and gle::tangent().
Referenced by vertmodel::vertmesh::calctangents(), skelmodel::skelmesh::calctangents(), and calctangents().
template<class B , class V , class TC , class T > void animmodel::mesh::calctangents (B * bumpverts, V * verts, TC * tcverts, int numverts, T * tris, int numtris, bool areaweight, int numframes) inline
References calctangents(), and loopi().
static void animmodel::mesh::fixqtangent (quat & q, float bt) inline static
References vec4::mul3(), and vec4::neg().
Referenced by calctangent(), and calctangents().
virtual void animmodel::mesh::genBIH (BIH::mesh & m) inline virtual
Reimplemented in vertmodel::vertmesh.
Referenced by genBIH().
void animmodel::mesh::genBIH (skin & s, vector< BIH::mesh > & bih, const matrix4x3 & t) inline
References vector< T, MINSIZE >::add(), Texture::ALPHA, animmodel::skin::cullface, BIH::mesh::flags, genBIH(), BIH::MESH_ALPHA, BIH::MESH_CULLFACE, BIH::MESH_NOCLIP, noclip, anonymous_namespace{utilTest.cpp}::t(), BIH::mesh::tex, animmodel::skin::tex, Texture::type, and BIH::mesh::xform.
virtual void animmodel::mesh::setshader (Shader * s) inline virtual
References glaring, Shader::set(), and Shader::setvariant().
Referenced by animmodel::skin::setshader().
template<class V , class T > void animmodel::mesh::smoothnorms (V * verts, int numverts, T * tris, int numtris, float limit, bool areaweight) inline
References hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::access(), vec::add(), vec::cross(), loopi(), vec::magnitude(), vec::normalize(), sphere::numverts, vec::sub(), and anonymous_namespace{utilTest.cpp}::t().
Referenced by vertmodel::vertmesh::smoothnorms(), and skelmodel::skelmesh::smoothnorms().
Member Data Documentation
meshgroup* animmodel::mesh::group
Referenced by vertmodel::vertmesh::buildnorms(), vertmodel::vertmesh::calctangents(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), vertmodel::vertmesh::render(), and vertmodel::vertmesh::smoothnorms().
char* animmodel::mesh::name
Referenced by md3::md3meshgroup::load(), ~mesh(), and vertmodel::tag::~tag().
bool animmodel::mesh::noclip
Referenced by genBIH().
The documentation for this struct was generated from the following file:
inexor/model/animmodel.hpp