Inexor: vec4 Struct Reference
vec4 Struct Reference
4-dimensional float vector all methods stay basicly the same but with an extra dimension
#include <geom.hpp>
Public Member Functions
vec4 ()
constructors
vec4 (const vec &p, float w=0)
vec4 (float x, float y, float z, float w)
vec4 (const float *v)
float & operator[] (int i)
operators for XYZ coordinate access
float operator[] (int i) const
template<class T >
float dot3 (const T &o) const
dot products
float dot (const vec4 &o) const
float dot (const vec &o) const
float squaredlen () const
float magnitude () const
float magnitude3 () const
vec4 & normalize ()
vec4 & lerp (const vec4 &b, float t)
vec4 & lerp (const vec4 &a, const vec4 &b, float t)
vec4 & mul3 (float f)
basic algebraic methods
vec4 & mul (float f)
vec4 & mul (const vec4 &o)
vec4 & div3 (float f)
vec4 & div (float f)
vec4 & div (const vec4 &o)
vec4 & add (const vec4 &o)
vec4 & addw (float f)
vec4 & sub (const vec4 &o)
vec4 & subw (float f)
vec4 & neg3 ()
vec4 & neg ()
template<class B >
vec4 & madd (const vec4 &a, const B &b)
template<class B >
vec4 & msub (const vec4 &a, const B &b)
void setxyz (const vec &v)
vec4 & rotate_around_z (float c, float s)
rotation members
vec4 & rotate_around_x (float c, float s)
vec4 & rotate_around_y (float c, float s)
vec4 & rotate_around_z (float angle)
vec4 & rotate_around_x (float angle)
vec4 & rotate_around_y (float angle)
Public Attributes
union {
struct {
float x
float y
float z
float w
}
struct {
float r
float g
float b
float a
}
float v [4]
};
Friends
std::ostream & operator<< (std::ostream &os, const vec4 &v)
Output operator, used for simple << vec4 << functionality: output of form "(x, y, z, w)" You may want to set the precision beforehand with std::setprecision()
Detailed Description
4-dimensional float vector all methods stay basicly the same but with an extra dimension
Constructor & Destructor Documentation
vec4::vec4 () inline
constructors
Referenced by madd(), and msub().
vec4::vec4 (const vec & p, float w = 0) inline explicit
vec4::vec4 (float x, float y, float z, float w) inline
vec4::vec4 (const float * v) inline explicit
Member Function Documentation
vec4& vec4::add (const vec4 & o) inline
Referenced by quat::add(), madd(), matrix4::reflectz(), setvfcP(), and matrix4::transform().
vec4& vec4::addw (float f) inline
References f().
vec4& vec4::div (float f) inline
References div3(), and f().
vec4& vec4::div (const vec4 & o) inline
vec4& vec4::div3 (float f) inline
References f().
Referenced by div().
float vec4::dot (const vec4 & o) const inline
References dot3().
Referenced by dualquat::accumulate(), addcubeverts(), dualquat::fixantipodal(), gengrassquads(), dualquat::invert(), dualquat::lerp(), dualquat::mulorient(), and squaredlen().
float vec4::dot (const vec & o) const inline
template<class T > float vec4::dot3 (const T & o) const inline
dot products
Referenced by quat::calcangleaxis(), plane::dist(), dot(), magnitude3(), matrix4::transposedtransform(), and matrix4::transposedtransformnormal().
vec4& vec4::lerp (const vec4 & b, float t) inline
Referenced by squat::lerp().
vec4& vec4::lerp (const vec4 & a, const vec4 & b, float t) inline
template<class B > vec4& vec4::madd (const vec4 & a, const B & b) inline
References add(), mul(), and vec4().
Referenced by matrix4::mul(), matrix4::mult(), matrix4::rotate_around_x(), matrix4::rotate_around_y(), matrix4::rotate_around_z(), matrix4::transform(), matrix4::transformnormal(), and matrix4::translate().
float vec4::magnitude () const inline
References squaredlen().
Referenced by normalize(), and dualquat::normalize().
float vec4::magnitude3 () const inline
References dot3().
template<class B > vec4& vec4::msub (const vec4 & a, const B & b) inline
References mul(), sub(), and vec4().
Referenced by matrix4::rotate_around_x(), matrix4::rotate_around_y(), and matrix4::rotate_around_z().
vec4& vec4::mul (float f) inline
References f(), and mul3().
Referenced by dualquat::accumulate(), drawminimap(), dualquat::lerp(), madd(), matrix4x3::matrix4x3(), msub(), quat::mul(), matrix4::mul(), matrix4::mult(), normalize(), matrix4::rotate_around_x(), matrix4::rotate_around_y(), matrix4::rotate_around_z(), matrix4::scale(), matrix4::transform(), and matrix4::transformnormal().
vec4& vec4::mul (const vec4 & o) inline
vec4& vec4::mul3 (float f) inline
basic algebraic methods
References f().
Referenced by animmodel::mesh::fixqtangent(), and mul().
vec4& vec4::neg () inline
References neg3().
Referenced by dualquat::fixantipodal(), animmodel::mesh::fixqtangent(), and matrix4::reflectz().
vec4& vec4::neg3 () inline
Referenced by quat::invert(), and neg().
vec4& vec4::normalize () inline
References magnitude(), and mul().
Referenced by iqm::iqmmeshgroup::loadiqmanims(), and iqm::iqmmeshgroup::loadiqmmeshes().
float& vec4::operator[] (int i) inline
operators for XYZ coordinate access
float vec4::operator[] (int i) const inline
vec4& vec4::rotate_around_x (float c, float s) inline
vec4& vec4::rotate_around_x (float angle) inline
References rotate_around_x().
Referenced by rotate_around_x().
vec4& vec4::rotate_around_y (float c, float s) inline
vec4& vec4::rotate_around_y (float angle) inline
References rotate_around_y().
Referenced by rotate_around_y().
vec4& vec4::rotate_around_z (float c, float s) inline
rotation members
vec4& vec4::rotate_around_z (float angle) inline
References rotate_around_z().
Referenced by rotate_around_z().
void vec4::setxyz (const vec & v) inline
Referenced by matrix4::settranslation().
float vec4::squaredlen () const inline
References dot().
Referenced by magnitude(), and matrix4x3::matrix4x3().
vec4& vec4::sub (const vec4 & o) inline
Referenced by msub(), setvfcP(), and quat::sub().
vec4& vec4::subw (float f) inline
References f().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const vec4 & v) friend
Output operator, used for simple << vec4 << functionality: output of form "(x, y, z, w)" You may want to set the precision beforehand with std::setprecision()
Member Data Documentation
union { ... }
The documentation for this struct was generated from the following file:
inexor/shared/geom.hpp