Inexor: ragdolldata Struct Reference
ragdolldata Struct Reference
#include <ragdoll.hpp>
Classes
struct vert
Public Member Functions
ragdolldata (ragdollskel *skel, float scale=1)
~ragdolldata ()
void calcanimjoint (int i, const matrix4x3 &anim)
void calctris ()
void calcboundsphere ()
void init (dynent *d)
void move (dynent *pl, float ts)
void updatepos ()
void constrain ()
void constraindist ()
void applyrotlimit (ragdollskel::tri &t1, ragdollskel::tri &t2, float angle, const vec &axis)
void constrainrot ()
void calcrotfriction ()
void applyrotfriction (float ts)
void tryunstick (float speed)
Static Public Member Functions
static bool collidevert (const vec &pos, const vec &dir, float radius)
Public Attributes
ragdollskel * skel
int millis
int collidemillis
int collisions
int floating
int lastmove
int unsticks
vec offset
vec center
float radius
float timestep
float scale
vert * verts
matrix3 * tris
matrix4x3 * animjoints
dualquat * reljoints
Constructor & Destructor Documentation
ragdolldata::ragdolldata (ragdollskel * skel, float scale = 1)
ragdolldata::~ragdolldata () inline
References animjoints, reljoints, tris, and verts.
Member Function Documentation
void ragdolldata::applyrotfriction (float ts)
References applyrotlimit(), matrix3::calcangleaxis(), calctris(), vec::div(), f(), loopv, ragdollskel::rotfriction::middle, matrix3::mul(), matrix3::multranspose(), ragdolldata::vert::newpos, ragdolldata::vert::pos, ragdollskel::rotfrictions, skel, ragdollskel::rotfriction::tri, ragdollskel::tris, tris, ragdollskel::verts, verts, and ragdolldata::vert::weight.
Referenced by move().
void ragdolldata::applyrotlimit (ragdollskel::tri & t1, ragdollskel::tri & t2, float angle, const vec & axis) inline
References vec::add(), vec::cross(), vec::div(), f(), vec::mul(), ragdolldata::vert::newpos, ragdolldata::vert::pos, vec::sub(), ragdollskel::tri::vert, verts, and ragdolldata::vert::weight.
Referenced by applyrotfriction(), and constrainrot().
void ragdolldata::calcanimjoint (int i, const matrix4x3 & anim) inline
References matrix4x3::a, vec::add(), animjoints, matrix4x3::b, matrix4x3::c, vec::cross(), matrix4x3::d, ragdollskel::joints, loopk, vec::mul(), vec::normalize(), ragdolldata::vert::pos, skel, vec::sub(), anonymous_namespace{utilTest.cpp}::t(), matrix4x3::transposemul(), ragdollskel::joint::tri, ragdollskel::tris, ragdollskel::tri::vert, ragdollskel::joint::vert, verts, and ragdollskel::joint::weight.
Referenced by skelmodel::skeleton::initragdoll().
void ragdolldata::calcboundsphere () inline
References vec::add(), center, vec::div(), vector< T, MINSIZE >::length(), loopv, inexor::rpc::max(), radius, skel, ragdollskel::verts, and verts.
Referenced by init(), and move().
void ragdolldata::calcrotfriction ()
References loopv, ragdollskel::rotfriction::middle, ragdollskel::rotfrictions, skel, matrix3::transposemul(), ragdollskel::rotfriction::tri, and tris.
Referenced by move().
void ragdolldata::calctris () inline
References matrix3::a, matrix3::b, matrix3::c, vec::cross(), loopv, vec::normalize(), ragdolldata::vert::pos, skel, vec::sub(), anonymous_namespace{utilTest.cpp}::t(), ragdollskel::tris, tris, ragdollskel::tri::vert, and verts.
Referenced by applyrotfriction(), constrain(), init(), and move().
static bool ragdolldata::collidevert (const vec & pos, const vec & dir, float radius) inline static
References mpr::collide(), ENT_BOUNCE, and radius.
Referenced by move(), tryunstick(), and updatepos().
void ragdolldata::constrain ()
References calctris(), constraindist(), constrainrot(), loopi(), and updatepos().
Referenced by move().
void ragdolldata::constraindist ()
References vec::add(), center, hmap::d, dir, ragdollskel::distlimits, f(), loopv, vec::magnitude(), ragdollskel::distlimit::maxdist, ragdollskel::distlimit::mindist, vec::mul(), ragdolldata::vert::newpos, ragdolldata::vert::pos, scale, skel, vec::sub(), ragdollskel::distlimit::vert, verts, and ragdolldata::vert::weight.
Referenced by constrain().
void ragdolldata::constrainrot ()
References applyrotlimit(), matrix3::calcangleaxis(), f(), loopv, ragdollskel::rotlimit::maxangle, ragdollskel::rotlimit::middle, matrix3::mul(), matrix3::multranspose(), ragdollskel::rotlimits, skel, ragdollskel::rotlimit::tri, ragdollskel::tris, and tris.
Referenced by constrain().
void ragdolldata::init (dynent * d) inline
References physent::aboveeye, vec::add(), calcboundsphere(), calctris(), center, ragdollskel::eye, physent::eyeheight, physent::falling, loopv, vec::mul(), physent::o, ragdolldata::vert::oldpos, ragdolldata::vert::pos, skel, vec::sub(), timestep, physent::vel, ragdollskel::verts, and verts.
Referenced by skelmodel::skelmeshgroup::render().
void ragdolldata::move (dynent * pl, float ts)
References vec::add(), applyrotfriction(), calcboundsphere(), calcrotfriction(), calctris(), center, ragdolldata::vert::collided, collidemillis, collidevert(), collidewall, collisions, constrain(), dir, f(), floating, GRAVITY, physent::inwater, isliquid, lastmillis, vector< T, MINSIZE >::length(), lookupmaterial(), loopv, MAT_AIR, MATF_VOLUME, inexor::rpc::min(), vec::mul(), ragdolldata::vert::oldpos, game::physicstrigger(), ragdolldata::vert::pos, RAD, radius, vec::reflect(), skel, vec::sub(), timestep, tryunstick(), unsticks, ragdollskel::verts, and verts.
Referenced by moveragdoll().
void ragdolldata::tryunstick (float speed)
References vec::add(), collidevert(), vec::div(), vector< T, MINSIZE >::length(), loopv, ragdolldata::vert::pos, vec::rescale(), skel, ragdolldata::vert::stuck, unsticks, ragdollskel::verts, and verts.
Referenced by move().
void ragdolldata::updatepos ()
References ragdolldata::vert::collided, collidevert(), collidewall, dir, vec::div(), vec::dot(), loopv, ragdolldata::vert::newpos, ragdolldata::vert::oldpos, ragdolldata::vert::pos, vec::reflect(), skel, vec::sub(), ragdollskel::verts, verts, and ragdolldata::vert::weight.
Referenced by constrain().
Member Data Documentation
matrix4x3* ragdolldata::animjoints
Referenced by calcanimjoint(), skelmodel::skeleton::genragdollbones(), and ~ragdolldata().
vec ragdolldata::center
Referenced by calcboundsphere(), constraindist(), endmodelbatches(), init(), move(), moveragdoll(), and rendermodel().
int ragdolldata::collidemillis
Referenced by move(), and moveragdoll().
int ragdolldata::collisions
Referenced by move().
int ragdolldata::floating
Referenced by move().
int ragdolldata::lastmove
Referenced by skelmodel::skeleton::checkskelcache(), moveragdoll(), and skelmodel::animcacheentry::operator==().
int ragdolldata::millis
vec ragdolldata::offset
Referenced by moveragdoll().
float ragdolldata::radius
Referenced by calcboundsphere(), collidevert(), move(), and rendermodel().
dualquat* ragdolldata::reljoints
Referenced by skelmodel::skeleton::genragdollbones(), skelmodel::skeleton::initragdoll(), and ~ragdolldata().
float ragdolldata::scale
Referenced by constraindist().
ragdollskel* ragdolldata::skel
Referenced by applyrotfriction(), calcanimjoint(), calcboundsphere(), calcrotfriction(), calctris(), constraindist(), constrainrot(), init(), move(), moveragdoll(), skelmodel::skelmeshgroup::render(), tryunstick(), and updatepos().
float ragdolldata::timestep
Referenced by init(), and move().
matrix3* ragdolldata::tris
Referenced by applyrotfriction(), calcrotfriction(), calctris(), constrainrot(), skelmodel::skeleton::genragdollbones(), and ~ragdolldata().
int ragdolldata::unsticks
Referenced by move(), and tryunstick().
vert* ragdolldata::verts
Referenced by applyrotfriction(), applyrotlimit(), calcanimjoint(), calcboundsphere(), calctris(), constraindist(), skelmodel::skeleton::genragdollbones(), init(), skelmodel::skeleton::initragdoll(), move(), moveragdoll(), tryunstick(), updatepos(), and ~ragdolldata().
The documentation for this struct was generated from the following files:
inexor/model/ragdoll.hpp
inexor/model/ragdoll.cpp