Inexor: shadowmaptexture Struct Reference
shadowmaptexture Struct Reference
Public Member Functions
const GLenum * colorformats () const override
bool swaptexs () const override
bool scissorblur (int &x, int &y, int &w, int &h) override
bool scissorrender (int &x, int &y, int &w, int &h) override
void doclear () override
bool dorender () override
bool flipdebug () const override
void dodebug (int w, int h) override
virtual GLenum attachment () const
virtual const GLenum * depthformats () const
virtual bool depthtest () const
void cleanup (bool fullclean=false)
void cleanupblur ()
void setupblur ()
void setup (int w, int h)
bool addblurtiles (float x1, float y1, float x2, float y2, float blurmargin=0)
bool checkblurtiles (float x1, float y1, float x2, float y2, float blurmargin=0)
void rendertiles ()
void blur (int wantsblursize, float wantsblursigma, int x, int y, int w, int h, bool scissor)
virtual bool shouldrender ()
virtual void doblur (int blursize, float blursigma)
virtual bool screenrect () const
virtual bool filter () const
void render (int w, int h, int blursize=0, float blursigma=0)
void debugscissor (int w, int h, bool lines=false)
void debugblurtiles (int w, int h, bool lines=false)
void debug ()
Public Attributes
int texw
int texh
int vieww
int viewh
GLenum colorfmt
GLenum depthfmt
GLuint rendertex
GLuint renderfb
GLuint renderdb
GLuint blurtex
GLuint blurfb
GLuint blurdb
int blursize
float blursigma
float blurweights [MAXBLURRADIUS+1]
float bluroffsets [MAXBLURRADIUS+1]
float scissorx1
float scissory1
float scissorx2
float scissory2
uint blurtiles [BLURTILES+1]
bool initialized
Member Function Documentation
bool rendertarget::addblurtiles (float x1, float y1, float x2, float y2, float blurmargin = 0) inline inherited
References rendertarget::blursize, BLURTILEMASK, BLURTILES, rendertarget::blurtiles, f(), inexor::rpc::max(), inexor::rpc::min(), rendertarget::scissorx1, rendertarget::scissorx2, rendertarget::scissory1, rendertarget::scissory2, rendertarget::viewh, and rendertarget::vieww.
Referenced by depthfxtexture::addscissorbox(), and addshadowmapcaster().
virtual GLenum rendertarget::attachment () const inline virtual inherited
References GL_COLOR_ATTACHMENT0.
Referenced by rendertarget::render(), and rendertarget::setup().
void rendertarget::blur (int wantsblursize, float wantsblursigma, int x, int y, int w, int h, bool scissor) inline inherited
References rendertarget::blurfb, rendertarget::bluroffsets, rendertarget::blursigma, rendertarget::blursize, rendertarget::blurtex, rendertarget::blurweights, GL_COLOR_ATTACHMENT0, GL_FRAMEBUFFER, glBindFramebuffer_, glFramebufferTexture2D_, loopi(), rendertarget::renderfb, rendertarget::rendertex, rendertarget::rendertiles(), setblurshader(), rendertarget::setupblur(), setupblurkernel(), rendertarget::swaptexs(), rendertarget::texh, and rendertarget::texw.
Referenced by rendertarget::doblur().
bool rendertarget::checkblurtiles (float x1, float y1, float x2, float y2, float blurmargin = 0) inline inherited
References rendertarget::blursize, BLURTILEMASK, BLURTILES, rendertarget::blurtiles, inexor::rpc::max(), inexor::rpc::min(), rendertarget::scissorx1, rendertarget::scissorx2, rendertarget::scissory1, rendertarget::scissory2, rendertarget::viewh, and rendertarget::vieww.
Referenced by isshadowmapreceiver().
void rendertarget::cleanup (bool fullclean = false) inherited
References rendertarget::cleanupblur(), rendertarget::colorfmt, rendertarget::depthfmt, glDeleteFramebuffers_, glDeleteRenderbuffers_, rendertarget::renderdb, rendertarget::renderfb, rendertarget::rendertex, rendertarget::texh, and rendertarget::texw.
Referenced by cleanshadowmap(), cleanupdepthfx(), cleanupglare(), and rendertarget::render().
void rendertarget::cleanupblur () inline inherited
References rendertarget::blurdb, rendertarget::blurfb, rendertarget::blursigma, rendertarget::blursize, rendertarget::blurtex, glDeleteFramebuffers_, and glDeleteRenderbuffers_.
Referenced by rendertarget::cleanup(), and rendertarget::render().
const GLenum* shadowmaptexture::colorformats () const inline override virtual
Reimplemented from rendertarget.
References GL_RGBA16F, GLenum(), and hasTF.
void rendertarget::debug () inline inherited
References rendertarget::dodebug(), rendertarget::flipdebug(), hudnotextureshader, hudquad(), hudshader, inexor::rpc::min(), rendertarget::rendertex, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::screenh, inexor::rendering::screen::screenw, and Shader::set().
Referenced by viewdepthfxtex(), viewglaretex(), and viewshadowmap().
void rendertarget::debugblurtiles (int w, int h, bool lines = false) inline inherited
References gle::begin(), BLURTILEMASK, BLURTILES, rendertarget::blurtiles, gle::end(), f(), rendertarget::flipdebug(), loop, and loopi().
Referenced by depthfxtexture::dodebug(), and dodebug().
void rendertarget::debugscissor (int w, int h, bool lines = false) inline inherited
References gle::begin(), gle::end(), f(), rendertarget::flipdebug(), rendertarget::scissorx1, rendertarget::scissorx2, rendertarget::scissory1, and rendertarget::scissory2.
Referenced by depthfxtexture::dodebug(), and dodebug().
virtual const GLenum* rendertarget::depthformats () const inline virtual inherited
References GLenum().
Referenced by rendertarget::setup().
virtual bool rendertarget::depthtest () const inline virtual inherited
Referenced by rendertarget::render(), rendertarget::setup(), and rendertarget::setupblur().
virtual void rendertarget::doblur (int blursize, float blursigma) inline virtual inherited
References rendertarget::blur(), rendertarget::scissorblur(), scissoring, rendertarget::viewh, and rendertarget::vieww.
Referenced by rendertarget::render().
void shadowmaptexture::doclear () inline override virtual
Reimplemented from rendertarget.
void shadowmaptexture::dodebug (int w, int h) inline override virtual
Reimplemented from rendertarget.
References rendertarget::debugblurtiles(), rendertarget::debugscissor(), and shadowmapcasters.
bool shadowmaptexture::dorender () inline override virtual
Reimplemented from rendertarget.
References vec::add(), camera1, dir, vec::dot(), GLOBALPARAM, GLOBALPARAMF, vec::magnitude(), inexor::rpc::min(), vec::mul(), matrix4::mul(), vec::neg(), physent::o, matrix4::ortho(), physent::pitch, RAD, rendergame(), rendershadowmapreceivers(), vec::rotate_around_z(), matrix4::rotate_around_z(), rtscissor, scissorblur(), scissoring, shadowdir, shadowfocus, shadowmapcasters, shadowoffset, matrix4::translate(), vecfromyawpitch(), rendertarget::viewh, rendertarget::vieww, and physent::yaw.
virtual bool rendertarget::filter () const inline virtual inherited
Reimplemented in depthfxtexture.
Referenced by rendertarget::render(), and rendertarget::setup().
bool shadowmaptexture::flipdebug () const inline override virtual
Reimplemented from rendertarget.
void rendertarget::render (int w, int h, int blursize = 0, float blursigma = 0) inline inherited
References rendertarget::attachment(), rendertarget::blurdb, rendertarget::blurfb, rendertarget::blursigma, rendertarget::blursize, rendertarget::blurtex, rendertarget::blurtiles, rendertarget::cleanup(), rendertarget::cleanupblur(), rendertarget::depthtest(), rendertarget::doblur(), rendertarget::doclear(), rendertarget::dorender(), rendertarget::filter(), GL_FRAMEBUFFER, glBindFramebuffer_, glFramebufferTexture2D_, hwtexsize, rendertarget::initialized, inexor::rpc::min(), rendertarget::renderdb, rendertarget::renderfb, rendertarget::rendertex, scissoring, rendertarget::scissorrender(), rendertarget::scissorx1, rendertarget::scissorx2, rendertarget::scissory1, rendertarget::scissory2, inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, inexor::rendering::screen::screenh, rendertarget::screenrect(), inexor::rendering::screen::ScreenManager::screenw, inexor::rendering::screen::screenw, rendertarget::setup(), rendertarget::setupblur(), rendertarget::shouldrender(), rendertarget::swaptexs(), rendertarget::texh, rendertarget::texw, rendertarget::viewh, and rendertarget::vieww.
Referenced by drawdepthfxtex(), drawglaretex(), and rendershadowmap().
void rendertarget::rendertiles () inline inherited
References gle::begin(), BLURTILEMASK, BLURTILES, rendertarget::blurtiles, gle::end(), f(), LOCALPARAMF, loop, rendertarget::scissorx1, rendertarget::scissorx2, rendertarget::scissory1, rendertarget::scissory2, screenquad(), rendertarget::texh, rendertarget::texw, rendertarget::viewh, and rendertarget::vieww.
Referenced by rendertarget::blur().
bool shadowmaptexture::scissorblur (int & x, int & y, int & w, int & h) inline override virtual
Reimplemented from rendertarget.
References rendertarget::blursize, inexor::rpc::max(), inexor::rpc::min(), rendertarget::scissorx1, rendertarget::scissorx2, rendertarget::scissory1, rendertarget::scissory2, rendertarget::viewh, and rendertarget::vieww.
Referenced by dorender().
bool shadowmaptexture::scissorrender (int & x, int & y, int & w, int & h) inline override virtual
Reimplemented from rendertarget.
References rendertarget::viewh, and rendertarget::vieww.
virtual bool rendertarget::screenrect () const inline virtual inherited
Reimplemented in depthfxtexture.
Referenced by rendertarget::render().
void rendertarget::setup (int w, int h) inline inherited
References rendertarget::attachment(), rendertarget::colorfmt, rendertarget::colorformats(), createtexture(), rendertarget::depthfmt, rendertarget::depthformats(), rendertarget::depthtest(), rendertarget::filter(), ai::find(), GL_DEPTH_ATTACHMENT, GL_FRAMEBUFFER, GL_FRAMEBUFFER_COMPLETE, GL_RENDERBUFFER, glBindFramebuffer_, glBindRenderbuffer_, glCheckFramebufferStatus_, GLenum(), glFramebufferRenderbuffer_, glFramebufferTexture2D_, glGenFramebuffers_, glGenRenderbuffers_, glRenderbufferStorage_, rendertarget::initialized, rendertarget::renderdb, rendertarget::renderfb, rendertarget::rendertex, rendertarget::texh, and rendertarget::texw.
Referenced by rendertarget::render().
void rendertarget::setupblur () inline inherited
References rendertarget::blurdb, rendertarget::blurfb, rendertarget::blurtex, rendertarget::colorfmt, createtexture(), rendertarget::depthfmt, rendertarget::depthtest(), GL_COLOR_ATTACHMENT0, GL_DEPTH_ATTACHMENT, GL_FRAMEBUFFER, GL_RENDERBUFFER, glBindFramebuffer_, glBindRenderbuffer_, glFramebufferRenderbuffer_, glFramebufferTexture2D_, glGenFramebuffers_, glGenRenderbuffers_, glRenderbufferStorage_, rendertarget::swaptexs(), rendertarget::texh, and rendertarget::texw.
Referenced by rendertarget::blur(), and rendertarget::render().
virtual bool rendertarget::shouldrender () inline virtual inherited
Reimplemented in depthfxtexture.
Referenced by rendertarget::render().
bool shadowmaptexture::swaptexs () const inline override virtual
Reimplemented from rendertarget.
Member Data Documentation
GLuint rendertarget::blurdb inherited
Referenced by rendertarget::cleanupblur(), rendertarget::render(), and rendertarget::setupblur().
GLuint rendertarget::blurfb inherited
Referenced by rendertarget::blur(), rendertarget::cleanupblur(), rendertarget::render(), and rendertarget::setupblur().
float rendertarget::bluroffsets[MAXBLURRADIUS+1] inherited
Referenced by rendertarget::blur().
float rendertarget::blursigma inherited
Referenced by rendertarget::blur(), rendertarget::cleanupblur(), and rendertarget::render().
int rendertarget::blursize inherited
Referenced by rendertarget::addblurtiles(), rendertarget::blur(), rendertarget::checkblurtiles(), rendertarget::cleanupblur(), rendertarget::render(), scissorblur(), and rendertarget::scissorrender().
GLuint rendertarget::blurtex inherited
Referenced by rendertarget::blur(), rendertarget::cleanupblur(), rendertarget::render(), and rendertarget::setupblur().
uint rendertarget::blurtiles[BLURTILES+1] inherited
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::debugblurtiles(), rendertarget::render(), and rendertarget::rendertiles().
float rendertarget::blurweights[MAXBLURRADIUS+1] inherited
Referenced by rendertarget::blur().
GLenum rendertarget::colorfmt inherited
Referenced by rendertarget::cleanup(), depthfxtexture::highprecision(), rendertarget::setup(), and rendertarget::setupblur().
GLenum rendertarget::depthfmt inherited
Referenced by rendertarget::cleanup(), rendertarget::setup(), and rendertarget::setupblur().
bool rendertarget::initialized inherited
Referenced by rendertarget::render(), and rendertarget::setup().
GLuint rendertarget::renderdb inherited
Referenced by rendertarget::cleanup(), rendertarget::render(), and rendertarget::setup().
GLuint rendertarget::renderfb inherited
Referenced by rendertarget::blur(), rendertarget::cleanup(), rendertarget::render(), and rendertarget::setup().
GLuint rendertarget::rendertex inherited
Referenced by addglare(), binddepthfxparams(), binddepthfxtex(), rendertarget::blur(), rendertarget::cleanup(), rendertarget::debug(), popshadowmap(), pushshadowmap(), rendertarget::render(), rendertarget::setup(), and fireballrenderer::startrender().
float rendertarget::scissorx1 inherited
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::debugscissor(), rendertarget::render(), rendertarget::rendertiles(), scissorblur(), rendertarget::scissorblur(), rendertarget::scissorrender(), and depthfxtexture::shouldrender().
float rendertarget::scissorx2 inherited
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::debugscissor(), rendertarget::render(), rendertarget::rendertiles(), scissorblur(), rendertarget::scissorblur(), rendertarget::scissorrender(), and depthfxtexture::shouldrender().
float rendertarget::scissory1 inherited
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::debugscissor(), rendertarget::render(), rendertarget::rendertiles(), scissorblur(), rendertarget::scissorblur(), rendertarget::scissorrender(), and depthfxtexture::shouldrender().
float rendertarget::scissory2 inherited
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::debugscissor(), rendertarget::render(), rendertarget::rendertiles(), scissorblur(), rendertarget::scissorblur(), rendertarget::scissorrender(), and depthfxtexture::shouldrender().
int rendertarget::texh inherited
Referenced by rendertarget::blur(), rendertarget::cleanup(), rendertarget::render(), rendertarget::rendertiles(), rendertarget::scissorblur(), rendertarget::scissorrender(), rendertarget::setup(), and rendertarget::setupblur().
int rendertarget::texw inherited
Referenced by rendertarget::blur(), rendertarget::cleanup(), rendertarget::render(), rendertarget::rendertiles(), rendertarget::scissorblur(), rendertarget::scissorrender(), rendertarget::setup(), and rendertarget::setupblur().
int rendertarget::viewh inherited
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::doblur(), dorender(), rendertarget::render(), rendertarget::rendertiles(), scissorblur(), rendertarget::scissorblur(), scissorrender(), and rendertarget::scissorrender().
int rendertarget::vieww inherited
Referenced by rendertarget::addblurtiles(), rendertarget::checkblurtiles(), rendertarget::doblur(), dorender(), rendertarget::render(), rendertarget::rendertiles(), scissorblur(), rendertarget::scissorblur(), scissorrender(), and rendertarget::scissorrender().
The documentation for this struct was generated from the following file:
inexor/engine/shadowmap.cpp