Inexor: skelmodel::skelmeshgroup Struct Reference
skelmodel::skelmeshgroup Struct Reference
#include <skelmodel.hpp>
Public Member Functions
skelmeshgroup ()
~skelmeshgroup () override
void shareskeleton (char *name)
int findtag (const char *name) override
void * animkey () override
int totalframes () const override
virtual skelanimspec * loadanim (const char *filename)
void genvbo (bool tangents, vbocacheentry &vc)
void bindvbo (const animstate *as, vbocacheentry &vc, skelcacheentry *sc=nullptr, blendcacheentry *bc=nullptr)
void concattagtransform (part *p, int i, const matrix4x3 &m, matrix4x3 &n) override
int addblendcombo (const blendcombo &c)
void sortblendcombos ()
int remapblend (int blend)
void blendbones (const skelcacheentry &sc, blendcacheentry &bc)
void cleanup () override
vbocacheentry & checkvbocache (skelcacheentry &sc, int owner)
blendcacheentry & checkblendcache (skelcacheentry &sc, int owner)
void preload (part *p) override
void render (const animstate *as, float pitch, const vec &axis, const vec &forward, dynent *d, part *p) override
void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m)
void genBIH (vector< skin > &skins, vector< BIH::mesh > &bih, const matrix4x3 &t)
bool hasframe (int i) const
bool hasframes (int i, int n) const
int clipframes (int i, int n) const
void bindpos (GLuint ebuf, GLuint vbuf, void *v, int stride)
void bindtc (void *v, int stride)
void bindnormals (void *v, int stride)
void bindtangents (void *v, int stride)
void bindbones (void *wv, void *bv, int stride)
Static Public Member Functions
static void blendbones (dualquat &d, const dualquat *bdata, const blendcombo &c)
Public Attributes
skeleton * skel
vector< blendcombo > blendcombos
int numblends [4]
blendcacheentry blendcache [MAXBLENDCACHE]
vbocacheentry vbocache [MAXVBOCACHE]
ushort * edata
GLuint ebuf
bool vtangents
int vlen
int vertsize
int vblends
int vweights
uchar * vdata
meshgroup * next
int shared
char * name
vector< mesh * > meshes
Static Public Attributes
static const int MAXBLENDCACHE = 16
static const int MAXVBOCACHE = 16
Constructor & Destructor Documentation
skelmodel::skelmeshgroup::skelmeshgroup () inline
References numblends.
skelmodel::skelmeshgroup::~skelmeshgroup () inline override
References blendcache, DELETEA, DELETEP, ebuf, glDeleteBuffers_, loopi(), MAXBLENDCACHE, MAXVBOCACHE, skelmodel::skeleton::shared, skel, skelmodel::skeleton::users, vbocache, sphere::vbuf, and vdata.
Member Function Documentation
int skelmodel::skelmeshgroup::addblendcombo (const blendcombo & c) inline
References blendcombos, skelmodel::blendcombo::interpindex, loopv, numblends, skelmodel::blendcombo::size(), and skelmodel::blendcombo::uses.
void* skelmodel::skelmeshgroup::animkey () inline override virtual
Reimplemented from animmodel::meshgroup.
References skel.
void animmodel::meshgroup::bindbones (void * wv, void * bv, int stride) inline inherited
References animmodel::enablebones, animmodel::lastbbuf, and animmodel::lastvbuf.
Referenced by bindvbo().
void animmodel::meshgroup::bindnormals (void * v, int stride) inline inherited
References animmodel::enablenormals, animmodel::lastnbuf, and animmodel::lastvbuf.
Referenced by bindvbo().
void animmodel::meshgroup::bindpos (GLuint ebuf, GLuint vbuf, void * v, int stride) inline inherited
References gle::bindebo(), gle::bindvbo(), sphere::ebuf, animmodel::lastebuf, animmodel::lastvbuf, and sphere::vbuf.
Referenced by bindvbo().
void animmodel::meshgroup::bindtangents (void * v, int stride) inline inherited
References animmodel::enabletangents, animmodel::lastvbuf, and animmodel::lastxbuf.
Referenced by bindvbo().
void animmodel::meshgroup::bindtc (void * v, int stride) inline inherited
References animmodel::enabletc, animmodel::lasttcbuf, and animmodel::lastvbuf.
Referenced by bindvbo().
void skelmodel::skelmeshgroup::bindvbo (const animstate * as, vbocacheentry & vc, skelcacheentry * sc = nullptr, blendcacheentry * bc = nullptr) inline
References animmodel::animpos::anim, ANIM_NOSKIN, animmodel::meshgroup::bindbones(), animmodel::meshgroup::bindnormals(), animmodel::meshgroup::bindpos(), animmodel::meshgroup::bindtangents(), animmodel::meshgroup::bindtc(), skelmodel::vvertw::bones, animmodel::animstate::cur, animmodel::disablebones(), animmodel::disablenormals(), animmodel::disabletangents(), animmodel::disabletc(), ebuf, animmodel::enablebones, animmodel::enablenormals, animmodel::enabletangents, animmodel::enabletc, skelmodel::vvertn::norm, skelmodel::vvert::pos, skel, skelmodel::vvertbump::tangent, skelmodel::vvert::tc, skelmodel::skeleton::usegpuskel, skelmodel::vbocacheentry::vbuf, vertsize, vtangents, vverts, and skelmodel::vvertw::weights.
Referenced by render().
static void skelmodel::skelmeshgroup::blendbones (dualquat & d, const dualquat * bdata, const blendcombo & c) inline static
References dualquat::accumulate(), skelmodel::blendcombo::interpbones, dualquat::mul(), and skelmodel::blendcombo::weights.
Referenced by blendbones(), and render().
void skelmodel::skelmeshgroup::blendbones (const skelcacheentry & sc, blendcacheentry & bc) inline
References skelmodel::skelcacheentry::bdata, blendbones(), blendcombos, hmap::d, skelmodel::blendcombo::interpindex, loopv, skelmodel::skelcacheentry::nextversion(), dualquat::normalize(), skelmodel::skeleton::numgpubones, skel, skelmodel::skeleton::usegpuskel, vblends, and vweights.
void animmodel::meshgroup::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline inherited
References loopv, and animmodel::meshgroup::meshes.
Referenced by animmodel::part::calcbb().
blendcacheentry& skelmodel::skelmeshgroup::checkblendcache (skelcacheentry & sc, int owner) inline
References blendcache, MAXBLENDCACHE, and SEARCHCACHE.
Referenced by render().
vbocacheentry& skelmodel::skelmeshgroup::checkvbocache (skelcacheentry & sc, int owner) inline
References MAXVBOCACHE, SEARCHCACHE, vbocache, and skelmodel::vbocacheentry::vbuf.
Referenced by render().
void skelmodel::skelmeshgroup::cleanup () inline override virtual
Reimplemented from animmodel::meshgroup.
References skelmodel::skelcacheentry::bdata, blendcache, skelmodel::skeleton::cleanup(), DELETEA, ebuf, glDeleteBuffers_, loopi(), MAXBLENDCACHE, MAXVBOCACHE, skelmodel::vbocacheentry::owner, skelmodel::blendcacheentry::owner, skel, vbocache, and skelmodel::vbocacheentry::vbuf.
Referenced by preload(), and render().
int animmodel::meshgroup::clipframes (int i, int n) const inline inherited
References inexor::rpc::min(), and animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
void skelmodel::skelmeshgroup::concattagtransform (part * p, int i, const matrix4x3 & m, matrix4x3 & n) inline override virtual
Reimplemented from animmodel::meshgroup.
References skelmodel::skeleton::concattagtransform(), and skel.
int skelmodel::skelmeshgroup::findtag (const char * name) inline override virtual
Reimplemented from animmodel::meshgroup.
References skelmodel::skeleton::findtag(), and skel.
void animmodel::meshgroup::genBIH (vector< skin > & skins, vector< BIH::mesh > & bih, const matrix4x3 & t) inline inherited
References loopv, and animmodel::meshgroup::meshes.
Referenced by animmodel::part::genBIH().
void skelmodel::skelmeshgroup::genvbo (bool tangents, vbocacheentry & vc) inline
References skelmodel::skeleton::availgpubones(), gle::bindebo(), gle::bindvbo(), blendcombos, gle::clearebo(), gle::clearvbo(), DELETEA, ebuf, FILLVDATA, GENVBOANIM, GENVBOSTAT, vector< T, MINSIZE >::getbuf(), glBufferData_, glGenBuffers_, skelmodel::blendcombo::interpindex, vector< T, MINSIZE >::length(), loopv, animmodel::meshgroup::meshes, numblends, skelmodel::skeleton::numframes, skelmodel::skeleton::numgpubones, sphere::numverts, skelmodel::blendcombo::size(), skel, skelmodel::skeleton::usegpuskel, vblends, skelmodel::vbocacheentry::vbuf, vdata, vertsize, vlen, vtangents, vweights, and skelmodel::blendcombo::weights.
Referenced by preload(), and render().
bool animmodel::meshgroup::hasframe (int i) const inline inherited
References animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
bool animmodel::meshgroup::hasframes (int i, int n) const inline inherited
References animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
virtual skelanimspec* skelmodel::skelmeshgroup::loadanim (const char * filename) inline virtual
Reimplemented in smd::smdmeshgroup.
void skelmodel::skelmeshgroup::preload (part * p) inline override virtual
Reimplemented from animmodel::meshgroup.
References skelmodel::skeleton::canpreload(), skelmodel::skeleton::cleanup(), cleanup(), genvbo(), loopv, skelmodel::skeleton::preload(), skelmodel::skeleton::shouldcleanup(), skel, animmodel::part::skins, vbocache, skelmodel::vbocacheentry::vbuf, and vtangents.
int skelmodel::skelmeshgroup::remapblend (int blend) inline
References blendcombos, skelmodel::blendcombo::interpbones, skelmodel::blendcombo::interpindex, and skelmodel::blendcombo::weights.
void skelmodel::skelmeshgroup::render (const animstate * as, float pitch, const vec & axis, const vec & forward, dynent * d, part * p) inline override virtual
Reimplemented from animmodel::meshgroup.
References animmodel::animpos::anim, ANIM_NORENDER, ANIM_RAGDOLL, skelmodel::skelcacheentry::bdata, gle::bindvbo(), bindvbo(), blendbones(), skelmodel::skeleton::calctags(), checkblendcache(), skelmodel::skeleton::checkskelcache(), checkvbocache(), skelmodel::skeleton::cleanup(), cleanup(), animmodel::animstate::cur, animmodel::disablevbo(), genvbo(), glBufferData_, ragdolldata::init(), skelmodel::skeleton::initragdoll(), skelmodel::skelmesh::interpverts(), lastmillis, loopv, animmodel::meshgroup::meshes, skelmodel::animcacheentry::millis, animmodel::part::model, skelmodel::skeleton::numframes, skelmodel::vbocacheentry::owner, skelmodel::blendcacheentry::owner, dynent::ragdoll, skelmodel::skeleton::ragdoll, skelmodel::skelmesh::render(), model::scale, skelmodel::skeleton::setgpubones(), skelmodel::skeleton::shouldcleanup(), ragdolldata::skel, skel, skelmodel::skeleton::skelcache, animmodel::part::skins, skelmodel::skeleton::usegpuskel, vblends, vbocache, skelmodel::vbocacheentry::vbuf, vc, vdata, vertsize, vlen, skelmodel::skelmesh::voffset, and vtangents.
void skelmodel::skelmeshgroup::shareskeleton (char * name) inline
References hashbase< hashnameset< T >, T, const char *, T >::access(), hashnameset< T >::add(), skelmodel::skeleton::name, newstring(), skelmodel::skeleton::shared, skel, and skelmodel::skeleton::users.
Referenced by smd::loadmeshes().
void skelmodel::skelmeshgroup::sortblendcombos () inline
References skelmodel::vert::blend, blendcombos, loopj, loopv, animmodel::meshgroup::meshes, skelmodel::skelmesh::numverts, skelmodel::blendcombo::sortcmp(), and skelmodel::skelmesh::verts.
Referenced by smd::smdmeshgroup::loadmesh().
int skelmodel::skelmeshgroup::totalframes () const inline override virtual
Reimplemented from animmodel::meshgroup.
References inexor::rpc::max(), skelmodel::skeleton::numframes, and skel.
Member Data Documentation
blendcacheentry skelmodel::skelmeshgroup::blendcache[MAXBLENDCACHE]
Referenced by checkblendcache(), cleanup(), and ~skelmeshgroup().
vector<blendcombo> skelmodel::skelmeshgroup::blendcombos
Referenced by addblendcombo(), blendbones(), genvbo(), remapblend(), skelmodel::skeleton::remapbones(), and sortblendcombos().
GLuint skelmodel::skelmeshgroup::ebuf
Referenced by bindvbo(), cleanup(), genvbo(), and ~skelmeshgroup().
ushort* skelmodel::skelmeshgroup::edata
const int skelmodel::skelmeshgroup::MAXBLENDCACHE = 16 static
Referenced by checkblendcache(), cleanup(), and ~skelmeshgroup().
const int skelmodel::skelmeshgroup::MAXVBOCACHE = 16 static
Referenced by checkvbocache(), cleanup(), and ~skelmeshgroup().
vector<mesh *> animmodel::meshgroup::meshes inherited
Referenced by animmodel::meshgroup::calcbb(), animmodel::meshgroup::genBIH(), genvbo(), animmodel::part::initskins(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), smd::smdmeshgroup::readtriangles(), render(), sortblendcombos(), and animmodel::meshgroup::~meshgroup().
char* animmodel::meshgroup::name inherited
Referenced by md3::md3meshgroup::load(), md2::md2meshgroup::load(), smd::smdmeshgroup::load(), smd::smdmeshgroup::readmaterial(), smd::smdmeshgroup::readname(), smd::smdmeshgroup::readnodes(), and animmodel::meshgroup::~meshgroup().
meshgroup* animmodel::meshgroup::next inherited
Referenced by animmodel::meshgroup::~meshgroup().
int skelmodel::skelmeshgroup::numblends[4]
Referenced by addblendcombo(), genvbo(), and skelmeshgroup().
int animmodel::meshgroup::shared inherited
Referenced by animmodel::part::loaded().
skeleton* skelmodel::skelmeshgroup::skel
Referenced by animkey(), bindvbo(), blendbones(), cleanup(), concattagtransform(), findtag(), genvbo(), smd::smdmeshgroup::loadanim(), smd::smdmeshgroup::loadmesh(), preload(), smd::smdmeshgroup::readframes(), smd::smdmeshgroup::readskeleton(), render(), skelmodel::skelmesh::setshader(), shareskeleton(), totalframes(), and ~skelmeshgroup().
int skelmodel::skelmeshgroup::vblends
Referenced by blendbones(), genvbo(), and render().
vbocacheentry skelmodel::skelmeshgroup::vbocache[MAXVBOCACHE]
Referenced by checkvbocache(), cleanup(), preload(), render(), and ~skelmeshgroup().
uchar* skelmodel::skelmeshgroup::vdata
Referenced by genvbo(), render(), and ~skelmeshgroup().
int skelmodel::skelmeshgroup::vertsize
Referenced by bindvbo(), genvbo(), and render().
int skelmodel::skelmeshgroup::vlen
Referenced by genvbo(), and render().
bool skelmodel::skelmeshgroup::vtangents
Referenced by bindvbo(), genvbo(), preload(), and render().
int skelmodel::skelmeshgroup::vweights
Referenced by blendbones(), genvbo(), and skelmodel::skelmesh::setshader().
The documentation for this struct was generated from the following file:
inexor/model/skelmodel.hpp