Inexor: shaftbb Struct Reference
shaftbb Struct Reference
Public Member Functions
shaftbb ()
shaftbb (const ivec &o, int size)
shaftbb (const ivec &o, int size, const bvec &edges)
ushort & operator[] (int i)
ushort operator[] (int i) const
bool contains (const shaftbb &o) const
bool outside (const ivec &o, int size) const
bool outside (const shaftbb &o) const
bool notinside (const shaftbb &o) const
Public Attributes
union {
ushort v [6]
struct {
usvec min
usvec max
}
};
Constructor & Destructor Documentation
shaftbb::shaftbb () inline
shaftbb::shaftbb (const ivec & o, int size) inline
References inexor::rpc::max(), and inexor::rpc::min().
shaftbb::shaftbb (const ivec & o, int size, const bvec & edges) inline
References inexor::rpc::max(), and inexor::rpc::min().
Member Function Documentation
bool shaftbb::contains (const shaftbb & o) const inline
References inexor::rpc::max(), and inexor::rpc::min().
Referenced by pvsworker::cullpvs().
bool shaftbb::notinside (const shaftbb & o) const inline
References inexor::rpc::max(), and inexor::rpc::min().
ushort& shaftbb::operator[] (int i) inline
ushort shaftbb::operator[] (int i) const inline
bool shaftbb::outside (const ivec & o, int size) const inline
References inexor::rpc::max(), and inexor::rpc::min().
Referenced by countviewcells(), and genviewcells().
bool shaftbb::outside (const shaftbb & o) const inline
References inexor::rpc::max(), and inexor::rpc::min().
Member Data Documentation
union { ... }
The documentation for this struct was generated from the following file:
inexor/engine/pvs.cpp