Inexor: smd::smdmeshgroup Struct Reference
smd::smdmeshgroup Struct Reference
#include <smd.hpp>
Classes
struct smdmeshdata
struct smdvertkey
Public Member Functions
smdmeshgroup ()
bool skipcomment (char *&curbuf)
void skipsection (stream *f, char *buf, size_t bufsize)
void readname (char *&curbuf, char *name, size_t namesize)
void readnodes (stream *f, char *buf, size_t bufsize, vector< smdbone > &bones)
void readmaterial (char *&curbuf, char *name, size_t namesize)
void readtriangles (stream *f, char *buf, size_t bufsize)
void readskeleton (stream *f, char *buf, size_t bufsize)
bool loadmesh (const char *filename)
int readframes (stream *f, char *buf, size_t bufsize, vector< dualquat > &animbones)
skelanimspec * loadanim (const char *filename) override
bool load (const char *meshfile)
void shareskeleton (char *name)
int findtag (const char *name) override
void * animkey () override
int totalframes () const override
void genvbo (bool tangents, vbocacheentry &vc)
void bindvbo (const animstate *as, vbocacheentry &vc, skelcacheentry *sc=nullptr, blendcacheentry *bc=nullptr)
void concattagtransform (part *p, int i, const matrix4x3 &m, matrix4x3 &n) override
int addblendcombo (const blendcombo &c)
void sortblendcombos ()
int remapblend (int blend)
void blendbones (const skelcacheentry &sc, blendcacheentry &bc)
void cleanup () override
vbocacheentry & checkvbocache (skelcacheentry &sc, int owner)
blendcacheentry & checkblendcache (skelcacheentry &sc, int owner)
void preload (part *p) override
void render (const animstate *as, float pitch, const vec &axis, const vec &forward, dynent *d, part *p) override
void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m)
void genBIH (vector< skin > &skins, vector< BIH::mesh > &bih, const matrix4x3 &t)
bool hasframe (int i) const
bool hasframes (int i, int n) const
int clipframes (int i, int n) const
void bindpos (GLuint ebuf, GLuint vbuf, void *v, int stride)
void bindtc (void *v, int stride)
void bindnormals (void *v, int stride)
void bindtangents (void *v, int stride)
void bindbones (void *wv, void *bv, int stride)
Static Public Member Functions
static void blendbones (dualquat &d, const dualquat *bdata, const blendcombo &c)
Public Attributes
skeleton * skel
vector< blendcombo > blendcombos
int numblends [4]
blendcacheentry blendcache [MAXBLENDCACHE]
vbocacheentry vbocache [MAXVBOCACHE]
ushort * edata
GLuint ebuf
bool vtangents
int vlen
int vertsize
int vblends
int vweights
uchar * vdata
meshgroup * next
int shared
char * name
vector< mesh * > meshes
Static Public Attributes
static const int MAXBLENDCACHE = 16
static const int MAXVBOCACHE = 16
Constructor & Destructor Documentation
smd::smdmeshgroup::smdmeshgroup () inline
Member Function Documentation
int skelmodel::skelmeshgroup::addblendcombo (const blendcombo & c) inline inherited
References skelmodel::skelmeshgroup::blendcombos, skelmodel::blendcombo::interpindex, loopv, skelmodel::skelmeshgroup::numblends, skelmodel::blendcombo::size(), and skelmodel::blendcombo::uses.
void* skelmodel::skelmeshgroup::animkey () inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References skelmodel::skelmeshgroup::skel.
void animmodel::meshgroup::bindbones (void * wv, void * bv, int stride) inline inherited
References animmodel::enablebones, animmodel::lastbbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindnormals (void * v, int stride) inline inherited
References animmodel::enablenormals, animmodel::lastnbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindpos (GLuint ebuf, GLuint vbuf, void * v, int stride) inline inherited
References gle::bindebo(), gle::bindvbo(), sphere::ebuf, animmodel::lastebuf, animmodel::lastvbuf, and sphere::vbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindtangents (void * v, int stride) inline inherited
References animmodel::enabletangents, animmodel::lastvbuf, and animmodel::lastxbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void animmodel::meshgroup::bindtc (void * v, int stride) inline inherited
References animmodel::enabletc, animmodel::lasttcbuf, and animmodel::lastvbuf.
Referenced by skelmodel::skelmeshgroup::bindvbo().
void skelmodel::skelmeshgroup::bindvbo (const animstate * as, vbocacheentry & vc, skelcacheentry * sc = nullptr, blendcacheentry * bc = nullptr) inline inherited
References animmodel::animpos::anim, ANIM_NOSKIN, animmodel::meshgroup::bindbones(), animmodel::meshgroup::bindnormals(), animmodel::meshgroup::bindpos(), animmodel::meshgroup::bindtangents(), animmodel::meshgroup::bindtc(), skelmodel::vvertw::bones, animmodel::animstate::cur, animmodel::disablebones(), animmodel::disablenormals(), animmodel::disabletangents(), animmodel::disabletc(), skelmodel::skelmeshgroup::ebuf, animmodel::enablebones, animmodel::enablenormals, animmodel::enabletangents, animmodel::enabletc, skelmodel::vvertn::norm, skelmodel::vvert::pos, skelmodel::skelmeshgroup::skel, skelmodel::vvertbump::tangent, skelmodel::vvert::tc, skelmodel::skeleton::usegpuskel, skelmodel::vbocacheentry::vbuf, skelmodel::skelmeshgroup::vertsize, skelmodel::skelmeshgroup::vtangents, vverts, and skelmodel::vvertw::weights.
Referenced by skelmodel::skelmeshgroup::render().
static void skelmodel::skelmeshgroup::blendbones (dualquat & d, const dualquat * bdata, const blendcombo & c) inline static inherited
References dualquat::accumulate(), skelmodel::blendcombo::interpbones, dualquat::mul(), and skelmodel::blendcombo::weights.
Referenced by skelmodel::skelmeshgroup::blendbones(), and skelmodel::skelmeshgroup::render().
void skelmodel::skelmeshgroup::blendbones (const skelcacheentry & sc, blendcacheentry & bc) inline inherited
References skelmodel::skelcacheentry::bdata, skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::blendcombos, hmap::d, skelmodel::blendcombo::interpindex, loopv, skelmodel::skelcacheentry::nextversion(), dualquat::normalize(), skelmodel::skeleton::numgpubones, skelmodel::skelmeshgroup::skel, skelmodel::skeleton::usegpuskel, skelmodel::skelmeshgroup::vblends, and skelmodel::skelmeshgroup::vweights.
void animmodel::meshgroup::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline inherited
References loopv, and animmodel::meshgroup::meshes.
Referenced by animmodel::part::calcbb().
blendcacheentry& skelmodel::skelmeshgroup::checkblendcache (skelcacheentry & sc, int owner) inline inherited
References skelmodel::skelmeshgroup::blendcache, skelmodel::skelmeshgroup::MAXBLENDCACHE, and SEARCHCACHE.
Referenced by skelmodel::skelmeshgroup::render().
vbocacheentry& skelmodel::skelmeshgroup::checkvbocache (skelcacheentry & sc, int owner) inline inherited
References skelmodel::skelmeshgroup::MAXVBOCACHE, SEARCHCACHE, skelmodel::skelmeshgroup::vbocache, and skelmodel::vbocacheentry::vbuf.
Referenced by skelmodel::skelmeshgroup::render().
void skelmodel::skelmeshgroup::cleanup () inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References skelmodel::skelcacheentry::bdata, skelmodel::skelmeshgroup::blendcache, skelmodel::skeleton::cleanup(), DELETEA, skelmodel::skelmeshgroup::ebuf, glDeleteBuffers_, loopi(), skelmodel::skelmeshgroup::MAXBLENDCACHE, skelmodel::skelmeshgroup::MAXVBOCACHE, skelmodel::vbocacheentry::owner, skelmodel::blendcacheentry::owner, skelmodel::skelmeshgroup::skel, skelmodel::skelmeshgroup::vbocache, and skelmodel::vbocacheentry::vbuf.
Referenced by skelmodel::skelmeshgroup::preload(), and skelmodel::skelmeshgroup::render().
int animmodel::meshgroup::clipframes (int i, int n) const inline inherited
References inexor::rpc::min(), and animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
void skelmodel::skelmeshgroup::concattagtransform (part * p, int i, const matrix4x3 & m, matrix4x3 & n) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References skelmodel::skeleton::concattagtransform(), and skelmodel::skelmeshgroup::skel.
int skelmodel::skelmeshgroup::findtag (const char * name) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References skelmodel::skeleton::findtag(), and skelmodel::skelmeshgroup::skel.
void animmodel::meshgroup::genBIH (vector< skin > & skins, vector< BIH::mesh > & bih, const matrix4x3 & t) inline inherited
References loopv, and animmodel::meshgroup::meshes.
Referenced by animmodel::part::genBIH().
void skelmodel::skelmeshgroup::genvbo (bool tangents, vbocacheentry & vc) inline inherited
References skelmodel::skeleton::availgpubones(), gle::bindebo(), gle::bindvbo(), skelmodel::skelmeshgroup::blendcombos, gle::clearebo(), gle::clearvbo(), DELETEA, skelmodel::skelmeshgroup::ebuf, FILLVDATA, GENVBOANIM, GENVBOSTAT, vector< T, MINSIZE >::getbuf(), glBufferData_, glGenBuffers_, skelmodel::blendcombo::interpindex, vector< T, MINSIZE >::length(), loopv, animmodel::meshgroup::meshes, skelmodel::skelmeshgroup::numblends, skelmodel::skeleton::numframes, skelmodel::skeleton::numgpubones, sphere::numverts, skelmodel::blendcombo::size(), skelmodel::skelmeshgroup::skel, skelmodel::skeleton::usegpuskel, skelmodel::skelmeshgroup::vblends, skelmodel::vbocacheentry::vbuf, skelmodel::skelmeshgroup::vdata, skelmodel::skelmeshgroup::vertsize, skelmodel::skelmeshgroup::vlen, skelmodel::skelmeshgroup::vtangents, skelmodel::skelmeshgroup::vweights, and skelmodel::blendcombo::weights.
Referenced by skelmodel::skelmeshgroup::preload(), and skelmodel::skelmeshgroup::render().
bool animmodel::meshgroup::hasframe (int i) const inline inherited
References animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
bool animmodel::meshgroup::hasframes (int i, int n) const inline inherited
References animmodel::meshgroup::totalframes().
Referenced by animmodel::part::calcanim().
bool smd::smdmeshgroup::load (const char * meshfile) inline
References loadmesh(), animmodel::meshgroup::name, and newstring().
Referenced by smd::loadmeshes().
skelanimspec* smd::smdmeshgroup::loadanim (const char * filename) inline override virtual
Reimplemented from skelmodel::skelmeshgroup.
References skelmodel::skeleton::addskelanim(), f(), skelmodel::skeleton::findskelanim(), skelmodel::skelanimspec::frame, skelmodel::skeleton::framebones, vector< T, MINSIZE >::getbuf(), stream::getline(), vector< T, MINSIZE >::length(), skelmodel::skeleton::numbones, skelmodel::skeleton::numframes, openfile(), skelmodel::skelanimspec::range, readframes(), readnodes(), skelmodel::skelmeshgroup::skel, skipcomment(), and skipsection().
bool smd::smdmeshgroup::loadmesh (const char * filename) inline
References skelmodel::skeleton::bones, vector< T, MINSIZE >::empty(), f(), stream::getline(), vector< T, MINSIZE >::length(), skelmodel::skeleton::linkchildren(), loopv, smdbone::name, skelmodel::boneinfo::name, newstring(), skelmodel::skeleton::numbones, openfile(), smdbone::parent, skelmodel::boneinfo::parent, readnodes(), readskeleton(), readtriangles(), skelmodel::skeleton::shared, skelmodel::skelmeshgroup::skel, skipcomment(), skipsection(), and skelmodel::skelmeshgroup::sortblendcombos().
Referenced by load().
void skelmodel::skelmeshgroup::preload (part * p) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References skelmodel::skeleton::canpreload(), skelmodel::skeleton::cleanup(), skelmodel::skelmeshgroup::cleanup(), skelmodel::skelmeshgroup::genvbo(), loopv, skelmodel::skeleton::preload(), skelmodel::skeleton::shouldcleanup(), skelmodel::skelmeshgroup::skel, animmodel::part::skins, skelmodel::skelmeshgroup::vbocache, skelmodel::vbocacheentry::vbuf, and skelmodel::skelmeshgroup::vtangents.
int smd::smdmeshgroup::readframes (stream * f, char * buf, size_t bufsize, vector< dualquat > & animbones) inline
References vector< T, MINSIZE >::addbuf(), skelloader< smd >::adjustments, vector< T, MINSIZE >::advance(), skelmodel::boneinfo::base, skelmodel::skeleton::bones, dualquat::fixantipodal(), skelmodel::skeleton::framebones, vector< T, MINSIZE >::getbuf(), stream::getline(), vector< T, MINSIZE >::inrange(), skelmodel::boneinfo::invbase, loopi(), dualquat::mul(), skelmodel::skeleton::numbones, skelmodel::skeleton::numframes, skelmodel::boneinfo::parent, databuf< T >::put(), vector< T, MINSIZE >::reserve(), skelmodel::skelmeshgroup::skel, and skipcomment().
Referenced by loadanim().
void smd::smdmeshgroup::readmaterial (char *& curbuf, char * name, size_t namesize) inline
References animmodel::meshgroup::name.
Referenced by readtriangles().
void smd::smdmeshgroup::readname (char *& curbuf, char * name, size_t namesize) inline
References animmodel::meshgroup::name.
Referenced by readnodes().
void smd::smdmeshgroup::readnodes (stream * f, char * buf, size_t bufsize, vector< smdbone > & bones) inline
References vector< T, MINSIZE >::add(), copystring(), stream::getline(), vector< T, MINSIZE >::inrange(), smdbone::name, animmodel::meshgroup::name, smdbone::parent, readname(), and skipcomment().
Referenced by loadanim(), and loadmesh().
void smd::smdmeshgroup::readskeleton (stream * f, char * buf, size_t bufsize) inline
References skelmodel::boneinfo::base, skelmodel::skeleton::bones, stream::getline(), skelmodel::boneinfo::invbase, dualquat::mul(), skelmodel::skeleton::numbones, skelmodel::boneinfo::parent, skelmodel::skelmeshgroup::skel, and skipcomment().
Referenced by loadmesh().
void smd::smdmeshgroup::readtriangles (stream * f, char * buf, size_t bufsize) inline
References hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::access(), hashbase< hashset< T >, T, T, T >::access(), vector< T, MINSIZE >::add(), skelmodel::skelmesh::addblendcombo(), skelmodel::blendcombo::addweight(), skelmodel::vert::blend, enumerate, skelmodel::blendcombo::finalize(), smd::smdmeshgroup::smdmeshdata::finalize(), stream::getline(), vector< T, MINSIZE >::length(), loopi(), materials, smd::smdmeshgroup::smdmeshdata::mesh, animmodel::meshgroup::meshes, newstring(), skelmodel::vert::norm, skelmodel::vert::pos, readmaterial(), skipcomment(), skelmodel::vert::tc, smd::smdmeshgroup::smdmeshdata::tris, skelmodel::tri::vert, sphere::verts, and smd::smdmeshgroup::smdmeshdata::verts.
Referenced by loadmesh().
int skelmodel::skelmeshgroup::remapblend (int blend) inline inherited
References skelmodel::skelmeshgroup::blendcombos, skelmodel::blendcombo::interpbones, skelmodel::blendcombo::interpindex, and skelmodel::blendcombo::weights.
void skelmodel::skelmeshgroup::render (const animstate * as, float pitch, const vec & axis, const vec & forward, dynent * d, part * p) inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References animmodel::animpos::anim, ANIM_NORENDER, ANIM_RAGDOLL, skelmodel::skelcacheentry::bdata, gle::bindvbo(), skelmodel::skelmeshgroup::bindvbo(), skelmodel::skelmeshgroup::blendbones(), skelmodel::skeleton::calctags(), skelmodel::skelmeshgroup::checkblendcache(), skelmodel::skeleton::checkskelcache(), skelmodel::skelmeshgroup::checkvbocache(), skelmodel::skeleton::cleanup(), skelmodel::skelmeshgroup::cleanup(), animmodel::animstate::cur, animmodel::disablevbo(), skelmodel::skelmeshgroup::genvbo(), glBufferData_, ragdolldata::init(), skelmodel::skeleton::initragdoll(), skelmodel::skelmesh::interpverts(), lastmillis, loopv, animmodel::meshgroup::meshes, skelmodel::animcacheentry::millis, animmodel::part::model, skelmodel::skeleton::numframes, skelmodel::vbocacheentry::owner, skelmodel::blendcacheentry::owner, dynent::ragdoll, skelmodel::skeleton::ragdoll, skelmodel::skelmesh::render(), model::scale, skelmodel::skeleton::setgpubones(), skelmodel::skeleton::shouldcleanup(), ragdolldata::skel, skelmodel::skelmeshgroup::skel, skelmodel::skeleton::skelcache, animmodel::part::skins, skelmodel::skeleton::usegpuskel, skelmodel::skelmeshgroup::vblends, skelmodel::skelmeshgroup::vbocache, skelmodel::vbocacheentry::vbuf, vc, skelmodel::skelmeshgroup::vdata, skelmodel::skelmeshgroup::vertsize, skelmodel::skelmeshgroup::vlen, skelmodel::skelmesh::voffset, and skelmodel::skelmeshgroup::vtangents.
void skelmodel::skelmeshgroup::shareskeleton (char * name) inline inherited
References hashbase< hashnameset< T >, T, const char *, T >::access(), hashnameset< T >::add(), skelmodel::skeleton::name, newstring(), skelmodel::skeleton::shared, skelmodel::skelmeshgroup::skel, and skelmodel::skeleton::users.
Referenced by smd::loadmeshes().
bool smd::smdmeshgroup::skipcomment (char *& curbuf) inline
Referenced by loadanim(), loadmesh(), readframes(), readnodes(), readskeleton(), readtriangles(), and skipsection().
void smd::smdmeshgroup::skipsection (stream * f, char * buf, size_t bufsize) inline
References stream::getline(), and skipcomment().
Referenced by loadanim(), and loadmesh().
void skelmodel::skelmeshgroup::sortblendcombos () inline inherited
References skelmodel::vert::blend, skelmodel::skelmeshgroup::blendcombos, loopj, loopv, animmodel::meshgroup::meshes, skelmodel::skelmesh::numverts, skelmodel::blendcombo::sortcmp(), and skelmodel::skelmesh::verts.
Referenced by loadmesh().
int skelmodel::skelmeshgroup::totalframes () const inline override virtual inherited
Reimplemented from animmodel::meshgroup.
References inexor::rpc::max(), skelmodel::skeleton::numframes, and skelmodel::skelmeshgroup::skel.
Member Data Documentation
blendcacheentry skelmodel::skelmeshgroup::blendcache[MAXBLENDCACHE] inherited
Referenced by skelmodel::skelmeshgroup::checkblendcache(), skelmodel::skelmeshgroup::cleanup(), and skelmodel::skelmeshgroup::~skelmeshgroup().
vector<blendcombo> skelmodel::skelmeshgroup::blendcombos inherited
Referenced by skelmodel::skelmeshgroup::addblendcombo(), skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::genvbo(), skelmodel::skelmeshgroup::remapblend(), skelmodel::skeleton::remapbones(), and skelmodel::skelmeshgroup::sortblendcombos().
GLuint skelmodel::skelmeshgroup::ebuf inherited
Referenced by skelmodel::skelmeshgroup::bindvbo(), skelmodel::skelmeshgroup::cleanup(), skelmodel::skelmeshgroup::genvbo(), and skelmodel::skelmeshgroup::~skelmeshgroup().
ushort* skelmodel::skelmeshgroup::edata inherited
const int skelmodel::skelmeshgroup::MAXBLENDCACHE = 16 static inherited
Referenced by skelmodel::skelmeshgroup::checkblendcache(), skelmodel::skelmeshgroup::cleanup(), and skelmodel::skelmeshgroup::~skelmeshgroup().
const int skelmodel::skelmeshgroup::MAXVBOCACHE = 16 static inherited
Referenced by skelmodel::skelmeshgroup::checkvbocache(), skelmodel::skelmeshgroup::cleanup(), and skelmodel::skelmeshgroup::~skelmeshgroup().
vector<mesh *> animmodel::meshgroup::meshes inherited
Referenced by animmodel::meshgroup::calcbb(), animmodel::meshgroup::genBIH(), skelmodel::skelmeshgroup::genvbo(), animmodel::part::initskins(), md3::md3meshgroup::load(), md2::md2meshgroup::load(), readtriangles(), skelmodel::skelmeshgroup::render(), skelmodel::skelmeshgroup::sortblendcombos(), and animmodel::meshgroup::~meshgroup().
char* animmodel::meshgroup::name inherited
Referenced by md3::md3meshgroup::load(), md2::md2meshgroup::load(), load(), readmaterial(), readname(), readnodes(), and animmodel::meshgroup::~meshgroup().
meshgroup* animmodel::meshgroup::next inherited
Referenced by animmodel::meshgroup::~meshgroup().
int skelmodel::skelmeshgroup::numblends[4] inherited
Referenced by skelmodel::skelmeshgroup::addblendcombo(), skelmodel::skelmeshgroup::genvbo(), and skelmodel::skelmeshgroup::skelmeshgroup().
int animmodel::meshgroup::shared inherited
Referenced by animmodel::part::loaded().
skeleton* skelmodel::skelmeshgroup::skel inherited
Referenced by skelmodel::skelmeshgroup::animkey(), skelmodel::skelmeshgroup::bindvbo(), skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::cleanup(), skelmodel::skelmeshgroup::concattagtransform(), skelmodel::skelmeshgroup::findtag(), skelmodel::skelmeshgroup::genvbo(), loadanim(), loadmesh(), skelmodel::skelmeshgroup::preload(), readframes(), readskeleton(), skelmodel::skelmeshgroup::render(), skelmodel::skelmesh::setshader(), skelmodel::skelmeshgroup::shareskeleton(), skelmodel::skelmeshgroup::totalframes(), and skelmodel::skelmeshgroup::~skelmeshgroup().
int skelmodel::skelmeshgroup::vblends inherited
Referenced by skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::genvbo(), and skelmodel::skelmeshgroup::render().
vbocacheentry skelmodel::skelmeshgroup::vbocache[MAXVBOCACHE] inherited
Referenced by skelmodel::skelmeshgroup::checkvbocache(), skelmodel::skelmeshgroup::cleanup(), skelmodel::skelmeshgroup::preload(), skelmodel::skelmeshgroup::render(), and skelmodel::skelmeshgroup::~skelmeshgroup().
uchar* skelmodel::skelmeshgroup::vdata inherited
Referenced by skelmodel::skelmeshgroup::genvbo(), skelmodel::skelmeshgroup::render(), and skelmodel::skelmeshgroup::~skelmeshgroup().
int skelmodel::skelmeshgroup::vertsize inherited
Referenced by skelmodel::skelmeshgroup::bindvbo(), skelmodel::skelmeshgroup::genvbo(), and skelmodel::skelmeshgroup::render().
int skelmodel::skelmeshgroup::vlen inherited
Referenced by skelmodel::skelmeshgroup::genvbo(), and skelmodel::skelmeshgroup::render().
bool skelmodel::skelmeshgroup::vtangents inherited
Referenced by skelmodel::skelmeshgroup::bindvbo(), skelmodel::skelmeshgroup::genvbo(), skelmodel::skelmeshgroup::preload(), and skelmodel::skelmeshgroup::render().
int skelmodel::skelmeshgroup::vweights inherited
Referenced by skelmodel::skelmeshgroup::blendbones(), skelmodel::skelmeshgroup::genvbo(), and skelmodel::skelmesh::setshader().
The documentation for this struct was generated from the following file:
inexor/model/smd.hpp