Inexor: g3d_gui Struct Reference
g3d_gui Struct Reference abstract
#include <3dgui.hpp>
Public Member Functions
virtual ~g3d_gui ()
virtual void start (int starttime, float basescale, int *tab=nullptr, bool allowinput=true)=0
virtual void end ()=0
virtual int text (const char *text, int color, const char *icon=nullptr)=0
int textf (const char *fmt, int color, const char *icon=nullptr,...) PRINTFARGS(2
int return text (str, color, icon)
virtual int button (const char *text, int color, const char *icon=nullptr)=0
int buttonf (const char *fmt, int color, const char *icon=nullptr,...) PRINTFARGS(2
int return button (str, color, icon)
virtual int title (const char *text, int color, const char *icon=nullptr)=0
int titlef (const char *fmt, int color, const char *icon=nullptr,...) PRINTFARGS(2
int return title (str, color, icon)
virtual void background (int color, int parentw=0, int parenth=0)=0
virtual void pushlist ()
virtual void poplist ()
virtual bool allowautotab (bool on)=0
virtual bool shouldtab ()
virtual void tab (const char *name=nullptr, int color=0)=0
virtual int image (Texture *t, float scale, bool overlaid=false)=0
virtual int texture (VSlot &vslot, float scale, bool overlaid=true)=0
virtual int playerpreview (int model, int team, int weap, float scale, bool overlaid=false)
virtual int modelpreview (const char *name, int anim, float scale, bool overlaid=false)
virtual int prefabpreview (const char *prefab, const vec &color, float scale, bool overlaid=false)
virtual void slider (int &val, int vmin, int vmax, int color, const char *label=nullptr)=0
virtual void separator ()=0
virtual void progress (float percent)=0
virtual void strut (float size)=0
virtual void space (float size)=0
virtual void spring (int weight=1)=0
virtual void column (int col)=0
virtual char * keyfield (const char *name, int color, int length, int height=0, const char *initval=nullptr, int initmode=EDITORFOCUSED)=0
virtual char * field (const char *name, int color, int length, int height=0, const char *initval=nullptr, int initmode=EDITORFOCUSED)=0
virtual void textbox (const char *text, int width, int height, int color=0xFFFFFF)=0
virtual bool mergehits (bool on)=0
Constructor & Destructor Documentation
virtual g3d_gui::~g3d_gui () inline virtual
Member Function Documentation
virtual bool g3d_gui::allowautotab (bool on) pure virtual
Implemented in gui.
Referenced by guinoautotab().
virtual void g3d_gui::background (int color, int parentw = 0, int parenth = 0) pure virtual
Implemented in gui.
Referenced by game::renderscoreboard().
virtual int g3d_gui::button (const char * text, int color, const char * icon = nullptr) pure virtual
Implemented in gui.
Referenced by applymenu::gui(), guibitfield(), guibutton(), guicheckbox(), and guiradio().
int return g3d_gui::button (str , color , icon)
int g3d_gui::buttonf (const char * fmt, int color, const char * icon = nullptr, ...)
virtual void g3d_gui::column (int col) pure virtual
Implemented in gui.
Referenced by guicolumn().
virtual void g3d_gui::end () pure virtual
Implemented in gui.
Referenced by menu::gui(), game::scoreboardgui::gui(), applymenu::gui(), and texturegui::gui().
virtual char* g3d_gui::field (const char * name, int color, int length, int height = 0, const char * initval = nullptr, int initmode = EDITORFOCUSED) pure virtual
Implemented in gui.
Referenced by guieditor(), and guifield().
virtual int g3d_gui::image (Texture * t, float scale, bool overlaid = false) pure virtual
Implemented in gui.
Referenced by guiimage().
virtual char* g3d_gui::keyfield (const char * name, int color, int length, int height = 0, const char * initval = nullptr, int initmode = EDITORFOCUSED) pure virtual
Implemented in gui.
Referenced by guikeyfield().
virtual bool g3d_gui::mergehits (bool on) pure virtual
Implemented in gui.
Referenced by guimerge().
virtual int g3d_gui::modelpreview (const char * name, int anim, float scale, bool overlaid = false) inline virtual
Reimplemented in gui.
Referenced by guimodelpreview().
virtual int g3d_gui::playerpreview (int model, int team, int weap, float scale, bool overlaid = false) inline virtual
Reimplemented in gui.
Referenced by guiplayerpreview().
virtual void g3d_gui::poplist () inline virtual
Reimplemented in gui.
Referenced by texturegui::gui(), guialign(), guilist(), game::bombclientmode::renderscoreboard(), and game::renderscoreboard().
virtual int g3d_gui::prefabpreview (const char * prefab, const vec & color, float scale, bool overlaid = false) inline virtual
Reimplemented in gui.
Referenced by guiprefabpreview().
virtual void g3d_gui::progress (float percent) pure virtual
Implemented in gui.
virtual void g3d_gui::pushlist () inline virtual
Reimplemented in gui.
Referenced by texturegui::gui(), guialign(), guilist(), game::bombclientmode::renderscoreboard(), and game::renderscoreboard().
virtual void g3d_gui::separator () pure virtual
Implemented in gui.
Referenced by applymenu::gui(), guibar(), and game::renderscoreboard().
virtual bool g3d_gui::shouldtab () inline virtual
Reimplemented in gui.
virtual void g3d_gui::slider (int & val, int vmin, int vmax, int color, const char * label = nullptr) pure virtual
Implemented in gui.
Referenced by guilistslider(), guinameslider(), and guislider().
virtual void g3d_gui::space (float size) pure virtual
Implemented in gui.
Referenced by guistrut(), and game::renderscoreboard().
virtual void g3d_gui::spring (int weight = 1) pure virtual
Implemented in gui.
Referenced by guialign(), guispring(), and game::renderscoreboard().
virtual void g3d_gui::start (int starttime, float basescale, int * tab = nullptr, bool allowinput = true) pure virtual
Implemented in gui.
Referenced by menu::gui(), game::scoreboardgui::gui(), applymenu::gui(), and texturegui::gui().
virtual void g3d_gui::strut (float size) pure virtual
Implemented in gui.
Referenced by guistrut(), game::bombclientmode::renderscoreboard(), and game::renderscoreboard().
virtual void g3d_gui::tab (const char * name = nullptr, int color = 0) pure virtual
Implemented in gui.
Referenced by menu::gui(), texturegui::gui(), and guitab().
virtual int g3d_gui::text (const char * text, int color, const char * icon = nullptr) pure virtual
Implemented in gui.
Referenced by applymenu::gui(), guicolor(), guitext(), game::bombclientmode::renderscoreboard(), and game::renderscoreboard().
int return g3d_gui::text (str , color , icon)
virtual void g3d_gui::textbox (const char * text, int width, int height, int color = 0xFFFFFF) pure virtual
Implemented in gui.
Referenced by guitextbox().
int g3d_gui::textf (const char * fmt, int color, const char * icon = nullptr, ...)
Referenced by game::bombclientmode::renderscoreboard(), and game::renderscoreboard().
virtual int g3d_gui::texture (VSlot & vslot, float scale, bool overlaid = true) pure virtual
Implemented in gui.
Referenced by texturegui::gui().
virtual int g3d_gui::title (const char * text, int color, const char * icon = nullptr) pure virtual
Implemented in gui.
Referenced by guititle().
int return g3d_gui::title (str , color , icon)
int g3d_gui::titlef (const char * fmt, int color, const char * icon = nullptr, ...)
Referenced by game::renderscoreboard().
The documentation for this struct was generated from the following file:
inexor/ui/legacy/3dgui.hpp