Inexor: aviwriter Struct Reference
aviwriter Struct Reference
Public Types
enum { MAX_CHUNK_DEPTH = 16, MAX_SUPER_INDEX = 1024 }
enum { VID_RGB = 0, VID_YUV, VID_YUV420 }
Public Member Functions
aviindexentry & addindex (int frame, int type, int size)
double filespaceguess ()
void startchunk (const char *fcc, uint size=0)
void listchunk (const char *fcc, const char *lfcc)
void endchunk ()
void endlistchunk ()
void writechunk (const char *fcc, const void *data, uint len)
void close ()
aviwriter (const char *name, uint w, uint h, uint fps, bool sound)
~aviwriter ()
bool open ()
void scaleyuv (const uchar *pixels, uint srcw, uint srch)
void encodeyuv (const uchar *pixels)
void compressyuv (const uchar *pixels)
bool writesound (uchar *data, uint framesize, uint frame)
void flushsegment ()
bool nextsegment ()
bool writevideoframe (const uchar *pixels, uint srcw, uint srch, int format, uint frame)
Static Public Member Functions
static void boxsample (const uchar *src, const uint stride, const uint area, const uint w, uint h, const uint xlow, const uint xhigh, const uint ylow, const uint yhigh, uint &bdst, uint &gdst, uint &rdst)
Public Attributes
stream * f
uchar * yuv
uint videoframes
stream::offset totalsize
const uint videow
const uint videoh
const uint videofps
string filename
int soundfrequency
int soundchannels
Uint16 soundformat
vector< aviindexentry > index
vector< avisegmentinfo > segments
stream::offset fileframesoffset
stream::offset fileextframesoffset
stream::offset filevideooffset
stream::offset filesoundoffset
stream::offset superindexvideooffset
stream::offset superindexsoundoffset
stream::offset chunkoffsets [MAX_CHUNK_DEPTH]
int chunkdepth
Member Enumeration Documentation
anonymous enum
Enumerator
MAX_CHUNK_DEPTH
MAX_SUPER_INDEX
anonymous enum
Enumerator
VID_RGB
VID_YUV
VID_YUV420
Constructor & Destructor Documentation
aviwriter::aviwriter (const char * name, uint w, uint h, uint fps, bool sound) inline
References concatstring(), copystring(), and path().
aviwriter::~aviwriter () inline
Member Function Documentation
aviindexentry& aviwriter::addindex (int frame, int type, int size) inline
References avisegmentinfo::firstindex, aviindexentry::frame, and aviindexentry::type.
static void aviwriter::boxsample (const uchar * src, const uint stride, const uint area, const uint w, uint h, const uint xlow, const uint xhigh, const uint ylow, const uint yhigh, uint & bdst, uint & gdst, uint & rdst) inline static
References cur, and gle::end().
void aviwriter::close () inline
References DELETEP, f(), avisegmentinfo::indexframes, Log, loopv, avisegmentinfo::soundframes, avisegmentinfo::soundindexoffset, avisegmentinfo::soundindexsize, inexor::util::log_manager::std, avisegmentinfo::videoframes, avisegmentinfo::videoindexoffset, and avisegmentinfo::videoindexsize.
void aviwriter::compressyuv (const uchar * pixels) inline
References flip().
void aviwriter::encodeyuv (const uchar * pixels) inline
References flip().
void aviwriter::endchunk () inline
References ASSERT.
void aviwriter::endlistchunk () inline
References ASSERT, and f().
double aviwriter::filespaceguess () inline
Referenced by recorder::drawhud().
void aviwriter::flushsegment () inline
References f(), avisegmentinfo::firstindex, loopv, aviindexentry::offset, avisegmentinfo::offset, aviindexentry::size, avisegmentinfo::soundframes, avisegmentinfo::soundindexoffset, avisegmentinfo::soundindexsize, aviindexentry::type, avisegmentinfo::videoframes, avisegmentinfo::videoindexoffset, and avisegmentinfo::videoindexsize.
void aviwriter::listchunk (const char * fcc, const char * lfcc) inline
References f().
bool aviwriter::nextsegment () inline
bool aviwriter::open () inline
References f(), loopi(), openfile(), inexor::rendering::screen::screen_manager, inexor::rendering::screen::ScreenManager::screenh, and inexor::rendering::screen::ScreenManager::screenw.
Referenced by recorder::start().
void aviwriter::scaleyuv (const uchar * pixels, uint srcw, uint srch) inline
References flip().
void aviwriter::startchunk (const char * fcc, uint size = 0) inline
References f().
void aviwriter::writechunk (const char * fcc, const void * data, uint len) inline
References f().
bool aviwriter::writesound (uchar * data, uint framesize, uint frame) inline
References gle::end(), and endianswap().
Referenced by recorder::videoencoder().
bool aviwriter::writevideoframe (const uchar * pixels, uint srcw, uint srch, int format, uint frame) inline
Referenced by recorder::videoencoder().
Member Data Documentation
int aviwriter::chunkdepth
stream::offset aviwriter::chunkoffsets[MAX_CHUNK_DEPTH]
stream* aviwriter::f
stream::offset aviwriter::fileextframesoffset
stream::offset aviwriter::fileframesoffset
string aviwriter::filename
Referenced by recorder::start().
stream::offset aviwriter::filesoundoffset
stream::offset aviwriter::filevideooffset
vector<aviindexentry> aviwriter::index
vector<avisegmentinfo> aviwriter::segments
int aviwriter::soundchannels
Uint16 aviwriter::soundformat
int aviwriter::soundfrequency
Referenced by recorder::start(), and recorder::videoencoder().
stream::offset aviwriter::superindexsoundoffset
stream::offset aviwriter::superindexvideooffset
stream::offset aviwriter::totalsize
const uint aviwriter::videofps
Referenced by recorder::calcquality(), recorder::readbuffer(), recorder::soundencoder(), recorder::start(), and recorder::videoencoder().
uint aviwriter::videoframes
Referenced by recorder::stop(), and recorder::videoencoder().
const uint aviwriter::videoh
Referenced by recorder::readbuffer(), and recorder::start().
const uint aviwriter::videow
Referenced by recorder::readbuffer(), and recorder::start().
uchar* aviwriter::yuv
The documentation for this struct was generated from the following file:
inexor/engine/movie.cpp