Inexor: applymenu Struct Reference
applymenu Struct Reference
Public Member Functions
void gui (g3d_gui &g, bool firstpass) override
void clear () override
int starttime ()
Public Attributes
char * name
char * header
uint * contents
uint * init
uint * onclear
bool showtab
Member Function Documentation
void applymenu::clear () inline override virtual
Reimplemented from menu.
References menu::clear(), and vector< T, MINSIZE >::shrink().
void applymenu::gui (g3d_gui & g, bool firstpass) inline override virtual
Reimplemented from menu.
References vector< T, MINSIZE >::add(), g3d_gui::button(), CHANGE_GFX, CHANGE_SOUND, clearlater, vector< T, MINSIZE >::empty(), g3d_gui::end(), f(), G3D_UP, GUI_BUTTON_COLOR, GUI_TEXT_COLOR, loopv, menustart, delayedupdate::schedule(), g3d_gui::separator(), g3d_gui::start(), and g3d_gui::text().
int g3d_callback::starttime () inherited
References totalmillis.
Referenced by game::scoreboardgui::show().
Member Data Documentation
uint* menu::contents inherited
Referenced by menu::gui(), and newgui().
char * menu::header inherited
Referenced by menu::gui(), and newgui().
uint * menu::init inherited
Referenced by newgui(), and pushgui().
char* menu::name inherited
Referenced by menu::gui(), and newgui().
uint * menu::onclear inherited
Referenced by menu::clear(), clearguis(), and guionclear().
bool menu::showtab inherited
Referenced by menu::gui(), and newgui().
The documentation for this struct was generated from the following file:
inexor/ui/legacy/menus.cpp