Inexor: obj::objmeshgroup Struct Reference
obj::objmeshgroup Struct Reference
#include <obj.hpp>
Public Member Functions
void parsevert (char *s, vector< vec > &out)
bool load (const char *filename, float smooth)
Member Function Documentation
bool obj::objmeshgroup::load (const char * filename, float smooth) inline
References hashbase< hashtable< K, T >, hashtableentry< K, T >, K, T >::access(), vector< T, MINSIZE >::add(), gle::attrib(), copystring(), recorder::file, FLUSHMESH, stream::getline(), vector< T, MINSIZE >::length(), loopi(), inexor::rpc::min(), model::name, newstring(), vertmodel::vert::norm, openfile(), parsevert(), vertmodel::vert::pos, STARTMESH, anonymous_namespace{utilTest.cpp}::t(), vertmodel::tcvert::tc, vertmodel::tri::vert, and sphere::verts.
Referenced by obj::loadmeshes().
void obj::objmeshgroup::parsevert (char * s, vector< vec > & out) inline
References vector< T, MINSIZE >::add(), and loopi().
Referenced by load().
The documentation for this struct was generated from the following file:
inexor/model/obj.hpp