Inexor: inexor::sound::soundconfig Struct Reference
inexor::sound::soundconfig Struct Reference
Public Member Functions
bool hasslot (const soundslot *p, const vector< soundslot > &v) const
int chooseslot () const
Public Attributes
int slots
int numslots
int maxuses
Member Function Documentation
int inexor::sound::soundconfig::chooseslot () const inline
References rnd(), and slots.
Referenced by inexor::sound::playsound().
bool inexor::sound::soundconfig::hasslot (const soundslot * p, const vector< soundslot > & v) const inline
References vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), and slots.
Referenced by inexor::sound::soundtype::playing().
Member Data Documentation
int inexor::sound::soundconfig::maxuses
Referenced by inexor::sound::soundtype::addsound(), and inexor::sound::playsound().
int inexor::sound::soundconfig::numslots
Referenced by inexor::sound::soundtype::addsound(), inexor::sound::soundtype::findsound(), and inexor::sound::soundtype::preloadsound().
int inexor::sound::soundconfig::slots
Referenced by inexor::sound::soundtype::addsound(), inexor::sound::soundtype::findsound(), and inexor::sound::soundtype::preloadsound().
The documentation for this struct was generated from the following file:
inexor/sound/sound.cpp