Inexor: server::servmode Struct Reference
server::servmode Struct Reference abstract
#include <gamemode_server.hpp>
Public Member Functions
virtual ~servmode ()
virtual void entergame (clientinfo *ci)
virtual void leavegame (clientinfo *ci, bool disconnecting=false)
virtual void connected (clientinfo *ci)
virtual void moved (clientinfo *ci, const vec &oldpos, bool oldclip, const vec &newpos, bool newclip)
virtual bool canspawn (clientinfo *ci, bool connecting=false)
virtual void spawned (clientinfo *ci)
virtual int fragvalue (clientinfo *victim, clientinfo *actor)
virtual bool canhit (clientinfo *victim, clientinfo *actor)
virtual void died (clientinfo *victim, clientinfo *actor)
virtual bool canchangeteam (clientinfo *ci, const char *oldteam, const char *newteam)
virtual void changeteam (clientinfo *ci, const char *oldteam, const char *newteam)
virtual void initclient (clientinfo *ci, packetbuf &p, bool connecting)
virtual void update ()
virtual void updatelimbo ()
virtual void cleanup ()
virtual void setup ()
virtual void newmap ()
virtual void intermission ()
virtual bool hidefrags ()
virtual int getteamscore (const char *team)
virtual void getteamscores (vector< teamscore > &scores)
virtual bool extinfoteam (const char *team, ucharbuf &p)
virtual bool parse_network_message (int type, clientinfo *ci, clientinfo *cq, packetbuf &p)=0
process gamemode specific network messages.
Constructor & Destructor Documentation
virtual server::servmode::~servmode () inline virtual
Member Function Documentation
virtual bool server::servmode::canchangeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline virtual
Reimplemented in server::hideandseekservermode, server::ctfservermode, server::collectservermode, and server::bombservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::canhit (clientinfo * victim, clientinfo * actor) inline virtual
Reimplemented in server::hideandseekservermode.
Referenced by server::dodamage().
virtual bool server::servmode::canspawn (clientinfo * ci, bool connecting = false) inline virtual
Reimplemented in server::captureservermode, server::hideandseekservermode, server::ctfservermode, server::collectservermode, and server::bombservermode.
Referenced by server::changemap(), and server::parsepacket().
virtual void server::servmode::changeteam (clientinfo * ci, const char * oldteam, const char * newteam) inline virtual
Reimplemented in server::captureservermode, server::ctfservermode, and server::collectservermode.
Referenced by aiman::balanceteams().
virtual void server::servmode::cleanup () inline virtual
Reimplemented in server::hideandseekservermode, server::bombservermode, server::ctfservermode, server::collectservermode, and server::captureservermode.
Referenced by server::changemap().
virtual void server::servmode::connected (clientinfo * ci) inline virtual
Reimplemented in server::hideandseekservermode.
virtual void server::servmode::died (clientinfo * victim, clientinfo * actor) inline virtual
Reimplemented in server::captureservermode, server::hideandseekservermode, server::ctfservermode, server::collectservermode, and server::bombservermode.
Referenced by server::dodamage(), and server::suicide().
virtual void server::servmode::entergame (clientinfo * ci) inline virtual
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::extinfoteam (const char * team, ucharbuf & p) inline virtual
Reimplemented in server::captureservermode.
Referenced by server::extinfoteamscore().
virtual int server::servmode::fragvalue (clientinfo * victim, clientinfo * actor) inline virtual
References isteam, and server::clientinfo::team.
Referenced by server::dodamage(), and server::suicide().
virtual int server::servmode::getteamscore (const char * team) inline virtual
virtual void server::servmode::getteamscores (vector< teamscore > & scores) inline virtual
Referenced by server::extinfoteams().
virtual bool server::servmode::hidefrags () inline virtual
Referenced by server::autoteam(), server::chooseworstteam(), and server::extinfoteams().
virtual void server::servmode::initclient (clientinfo * ci, packetbuf & p, bool connecting) inline virtual
Reimplemented in server::ctfservermode, server::collectservermode, server::captureservermode, and server::hideandseekservermode.
virtual void server::servmode::intermission () inline virtual
Reimplemented in server::hideandseekservermode.
Referenced by server::checkintermission().
virtual void server::servmode::leavegame (clientinfo * ci, bool disconnecting = false) inline virtual
Reimplemented in server::captureservermode, server::ctfservermode, server::hideandseekservermode, server::collectservermode, and server::bombservermode.
Referenced by server::checkmaps(), aiman::deleteai(), server::disconnect_client(), server::forcespectator(), server::parsepacket(), and aiman::shiftai().
virtual void server::servmode::moved (clientinfo * ci, const vec & oldpos, bool oldclip, const vec & newpos, bool newclip) inline virtual
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual void server::servmode::newmap () inline virtual
Reimplemented in server::ctfservermode, server::collectservermode, and server::captureservermode.
Referenced by server::parsepacket().
virtual bool server::servmode::parse_network_message (int type, clientinfo * ci, clientinfo * cq, packetbuf & p) pure virtual
process gamemode specific network messages.
Parameters
type the N_ network message type
ci the sender.
cq the currently focused player (sender or bot from senders pc)
p the network packet containing the data
Returns
whether this messages got processed.
Implemented in server::captureservermode, server::hideandseekservermode, server::ctfservermode, server::collectservermode, and server::bombservermode.
Referenced by server::parsepacket().
virtual void server::servmode::setup () inline virtual
Reimplemented in server::ctfservermode, server::hideandseekservermode, server::collectservermode, server::captureservermode, and server::bombservermode.
Referenced by server::changemap().
virtual void server::servmode::spawned (clientinfo * ci) inline virtual
Reimplemented in server::captureservermode.
Referenced by server::parsepacket().
virtual void server::servmode::update () inline virtual
Reimplemented in server::ctfservermode, server::collectservermode, server::hideandseekservermode, and server::captureservermode.
Referenced by server::serverupdate().
virtual void server::servmode::updatelimbo () inline virtual
Reimplemented in server::bombservermode.
Referenced by server::serverupdate().
The documentation for this struct was generated from the following file:
inexor/server/gamemode/gamemode_server.hpp