Inexor: decalrenderer Struct Reference
decalrenderer Struct Reference
Public Member Functions
decalrenderer (const char *texname, int flags=0, int fadeintime=0, int fadeouttime=1000, int timetolive=-1)
~decalrenderer ()
void init (int tris)
int hasdecals ()
void cleanup ()
void cleardecals ()
int freedecal ()
void fadedecal (decalinfo &d, uchar alpha)
void clearfadeddecals ()
void fadeindecals ()
void fadeoutdecals ()
void render ()
decalinfo & newdecal ()
void adddecal (const vec &center, const vec &dir, float radius, const bvec &color, int info)
void gentris (cube &cu, int orient, const ivec &o, int size, materialsurface *mat=nullptr, int vismask=0)
void findmaterials (vtxarray *va)
void findescaped (cube *cu, const ivec &o, int size, int escaped)
void gentris (cube *cu, const ivec &o, int size, int escaped=0)
Static Public Member Functions
static void setuprenderstate ()
static void cleanuprenderstate ()
static int clip (const vec *in, int numin, const vec &dir, float below, float above, vec *out)
Public Attributes
const char * texname
int flags
int fadeintime
int fadeouttime
int timetolive
Texture * tex
decalinfo * decals
int maxdecals
int startdecal
int enddecal
decalvert * verts
int maxverts
int startvert
int endvert
int lastvert
int availverts
GLuint vbo
bool dirty
ivec bbmin
ivec bbmax
vec decalcenter
vec decalnormal
vec decaltangent
vec decalbitangent
float decalradius
float decalu
float decalv
bvec4 decalcolor
Constructor & Destructor Documentation
decalrenderer::decalrenderer (const char * texname, int flags = 0, int fadeintime = 0, int fadeouttime = 1000, int timetolive = -1) inline
decalrenderer::~decalrenderer () inline
References decals, DELETEA, and verts.
Member Function Documentation
void decalrenderer::adddecal (const vec & center, const vec & dir, float radius, const bvec & color, int info) inline
References ivec::add(), availverts, bbmax, bbmin, decalinfo::color, gle::color(), vec::cross(), hmap::d, decalbitangent, decalcenter, decalcolor, decalnormal, decalradius, decaltangent, decalu, decalv, DF_RND4, DF_ROTATE, dir, vec::dot(), decalinfo::endvert, endvert, flags, gentris(), lastmillis, lastvert, Log, maxverts, decalinfo::millis, newdecal(), vec::normalize(), vec::orthogonal(), RAD, rnd(), vec::rotate(), decalinfo::startvert, inexor::util::log_manager::std, vec::sub(), ivec::sub(), worldroot, and worldsize.
Referenced by adddecal().
void decalrenderer::cleanup () inline
References glDeleteBuffers_, and vbo.
Referenced by cleanupdecals().
static void decalrenderer::cleanuprenderstate () inline static
References gle::clearvbo(), and disablepolygonoffset().
Referenced by renderdecals().
void decalrenderer::cleardecals () inline
References availverts, dirty, enddecal, endvert, lastvert, maxverts, startdecal, and startvert.
Referenced by cleardecals().
void decalrenderer::clearfadeddecals () inline
References availverts, hmap::d, decals, dirty, gle::end(), enddecal, endvert, fadeouttime, lastmillis, lastvert, maxdecals, maxverts, startdecal, startvert, and timetolive.
Referenced by renderdecals().
static int decalrenderer::clip (const vec * in, int numin, const vec & dir, float below, float above, vec * out) inline static
References vec::add(), vec::dot(), loopi(), vec::mul(), and vec::sub().
Referenced by gentris().
void decalrenderer::fadedecal (decalinfo & d, uchar alpha) inline
References decalvert::color, decalinfo::color, gle::color(), DF_ADD, DF_INVMOD, DF_OVERBRIGHT, dirty, gle::end(), decalinfo::endvert, flags, maxverts, bvec::scale(), decalinfo::startvert, and verts.
Referenced by fadeindecals(), and fadeoutdecals().
void decalrenderer::fadeindecals () inline
References hmap::d, decals, gle::end(), enddecal, fadedecal(), fadeintime, lastmillis, maxdecals, decalinfo::millis, and startdecal.
Referenced by renderdecals().
void decalrenderer::fadeoutdecals () inline
References hmap::d, decals, gle::end(), enddecal, fadedecal(), fadeouttime, lastmillis, maxdecals, decalinfo::millis, startdecal, and timetolive.
Referenced by renderdecals().
void decalrenderer::findescaped (cube * cu, const ivec & o, int size, int escaped) inline
References gentris(), loopi(), loopj, and cube::merged.
Referenced by gentris().
void decalrenderer::findmaterials (vtxarray * va) inline
References bbmax, bbmin, C, materialsurface::csize, hmap::dc, decalnormal, dimcoord, dimension, gentris(), isclipped, loopi(), vtxarray::matbuf, materialsurface::material, MATF_VOLUME, vtxarray::matsurfs, inexor::rpc::max(), materialsurface::o, materialsurface::orient, R, materialsurface::rsize, and materialsurface::skip.
Referenced by gentris().
int decalrenderer::freedecal () inline
References availverts, hmap::d, decals, enddecal, decalinfo::endvert, endvert, lastvert, maxdecals, maxverts, startdecal, decalinfo::startvert, and startvert.
Referenced by gentris(), and newdecal().
void decalrenderer::gentris (cube & cu, int orient, const ivec & o, int size, materialsurface * mat = nullptr, int vismask = 0) inline
References vec::add(), availverts, clip(), vec::cross(), decalbitangent, decalcenter, decalcolor, decalnormal, decalradius, decaltangent, decalu, decalv, DEFAULT_SKY, DF_RND4, vec::dot(), endvert, cube::ext, f(), faceconvexity(), flags, flataxisface(), freedecal(), GENFACEVERTS, genfaceverts(), loopj, loopk, loopl, ivec::mask(), MAT_AIR, MAT_ALPHA, cube::material, MAXFACEVERTS, maxverts, cube::merged, vec::mul(), vec::normalize(), sphere::numverts, surfaceinfo::numverts, orient, vec::orthogonal(), decalvert::pos, ivec::shl(), vec::sub(), cubeext::surfaces, cube::texture, verts, surfaceinfo::verts, cubeext::verts(), and visibleface().
Referenced by adddecal(), findescaped(), findmaterials(), and gentris().
void decalrenderer::gentris (cube * cu, const ivec & o, int size, int escaped = 0) inline
References bbmax, bbmin, ext(), cube::ext, findescaped(), findmaterials(), gentris(), loopi(), loopj, vtxarray::matsurfs, cube::merged, octaboxoverlap(), and cubeext::va.
int decalrenderer::hasdecals () inline
References enddecal, maxdecals, and startdecal.
Referenced by renderdecals().
void decalrenderer::init (int tris) inline
References availverts, decals, DELETEA, enddecal, endvert, lastvert, maxdecals, maxverts, startdecal, startvert, tex, texname, textureload(), and verts.
Referenced by initdecals().
decalinfo& decalrenderer::newdecal () inline
References hmap::d, decals, dirty, enddecal, freedecal(), maxdecals, and startdecal.
Referenced by adddecal().
void decalrenderer::render () inline
References gle::bindvbo(), decalvert::color, DF_ADD, DF_INVMOD, DF_OVERBRIGHT, DF_SATURATE, dirty, endvert, flags, foggedshader, GL_ONE, glBufferData_, glBufferSubData_, glGenBuffers_, Texture::id, maxverts, decalvert::pos, resetfogcolor(), Shader::set(), SETSHADER, startvert, decalvert::tc, tex, vbo, verts, xtravertsva, and zerofogcolor().
Referenced by renderdecals().
static void decalrenderer::setuprenderstate () inline static
References enablepolygonoffset().
Referenced by renderdecals().
Member Data Documentation
int decalrenderer::availverts
Referenced by adddecal(), cleardecals(), clearfadeddecals(), freedecal(), gentris(), and init().
ivec decalrenderer::bbmax
Referenced by adddecal(), findmaterials(), and gentris().
ivec decalrenderer::bbmin
Referenced by adddecal(), findmaterials(), and gentris().
vec decalrenderer::decalbitangent
Referenced by adddecal(), and gentris().
vec decalrenderer::decalcenter
Referenced by adddecal(), and gentris().
bvec4 decalrenderer::decalcolor
Referenced by adddecal(), and gentris().
vec decalrenderer::decalnormal
Referenced by adddecal(), findmaterials(), and gentris().
float decalrenderer::decalradius
Referenced by adddecal(), and gentris().
decalinfo* decalrenderer::decals
Referenced by clearfadeddecals(), fadeindecals(), fadeoutdecals(), freedecal(), init(), newdecal(), and ~decalrenderer().
vec decalrenderer::decaltangent
Referenced by adddecal(), and gentris().
float decalrenderer::decalu
Referenced by adddecal(), and gentris().
float decalrenderer::decalv
Referenced by adddecal(), and gentris().
bool decalrenderer::dirty
Referenced by cleardecals(), clearfadeddecals(), fadedecal(), newdecal(), and render().
int decalrenderer::enddecal
Referenced by cleardecals(), clearfadeddecals(), fadeindecals(), fadeoutdecals(), freedecal(), hasdecals(), init(), and newdecal().
int decalrenderer::endvert
Referenced by adddecal(), cleardecals(), clearfadeddecals(), freedecal(), gentris(), init(), and render().
int decalrenderer::fadeintime
Referenced by fadeindecals().
int decalrenderer::fadeouttime
Referenced by clearfadeddecals(), and fadeoutdecals().
int decalrenderer::flags
Referenced by adddecal(), fadedecal(), gentris(), and render().
int decalrenderer::lastvert
Referenced by adddecal(), cleardecals(), clearfadeddecals(), freedecal(), and init().
int decalrenderer::maxdecals
Referenced by clearfadeddecals(), fadeindecals(), fadeoutdecals(), freedecal(), hasdecals(), init(), and newdecal().
int decalrenderer::maxverts
Referenced by adddecal(), cleardecals(), clearfadeddecals(), fadedecal(), freedecal(), gentris(), init(), and render().
int decalrenderer::startdecal
Referenced by cleardecals(), clearfadeddecals(), fadeindecals(), fadeoutdecals(), freedecal(), hasdecals(), init(), and newdecal().
int decalrenderer::startvert
Referenced by cleardecals(), clearfadeddecals(), freedecal(), init(), and render().
Texture* decalrenderer::tex
Referenced by init(), and render().
const char* decalrenderer::texname
Referenced by init().
int decalrenderer::timetolive
Referenced by clearfadeddecals(), and fadeoutdecals().
GLuint decalrenderer::vbo
Referenced by cleanup(), and render().
decalvert* decalrenderer::verts
Referenced by fadedecal(), gentris(), init(), render(), and ~decalrenderer().
The documentation for this struct was generated from the following file:
inexor/engine/decal.cpp