Inexor: verthash Struct Reference
verthash Struct Reference
Public Member Functions
verthash ()
void clearverts ()
int addvert (const vertex &v)
int addvert (const vec &pos, const vec2 &tc=vec2(0, 0), const svec2 &lm=svec2(0, 0), const bvec &norm=bvec(128, 128, 128), const bvec4 &tangent=bvec4(128, 128, 128, 128))
Public Attributes
int table [SIZE]
vector< vertex > verts
vector< int > chain
Static Public Attributes
static const int SIZE = 1<<13
Constructor & Destructor Documentation
verthash::verthash () inline
References clearverts().
Member Function Documentation
int verthash::addvert (const vertex & v) inline
References vector< T, MINSIZE >::add(), chain, hthash(), svec2::iszero(), vector< T, MINSIZE >::length(), vertex::lm, vertex::norm, vertex::pos, SIZE, table, vertex::tangent, vertex::tc, and verts.
Referenced by addcubeverts(), addskyverts(), addtris(), addvert(), and vacollect::remapunlit().
int verthash::addvert (const vec & pos, const vec2 & tc = vec2(0, 0), const svec2 & lm = svec2(0, 0), const bvec & norm = bvec(128, 128, 128), const bvec4 & tangent = bvec4(128, 128, 128, 128)) inline
References addvert(), vertex::lm, vertex::norm, vertex::pos, gle::tangent(), vertex::tangent, and vertex::tc.
void verthash::clearverts () inline
References chain, vector< T, MINSIZE >::setsize(), table, and verts.
Referenced by vacollect::clear(), and verthash().
Member Data Documentation
vector<int> verthash::chain
Referenced by addvert(), and clearverts().
const int verthash::SIZE = 1<<13 static
Referenced by addvert().
int verthash::table[SIZE]
Referenced by addvert(), and clearverts().
vector<vertex> verthash::verts
Referenced by addvert(), calcgeombb(), clearverts(), vacollect::emptyva(), vacollect::remapunlit(), and vacollect::setupdata().
The documentation for this struct was generated from the following file:
inexor/engine/octarender.cpp