Inexor: bigint< BI_DIGITS > Struct Template Reference
bigint< BI_DIGITS > Struct Template Reference
Public Types
typedef ushort digit
typedef uint dbldigit
Public Member Functions
bigint ()
bigint (digit n)
bigint (const char *s)
template<int Y_DIGITS>
bigint (const bigint< Y_DIGITS > &y)
void parse (const char *s)
void zero ()
template<int Y_DIGITS>
bigint & operator= (const bigint< Y_DIGITS > &y)
bool iszero () const
bool isone () const
int numbits () const
bool hasbit (int n) const
bool morebits (int n) const
template<int X_DIGITS, int Y_DIGITS>
bigint & add (const bigint< X_DIGITS > &x, const bigint< Y_DIGITS > &y)
template<int Y_DIGITS>
bigint & add (const bigint< Y_DIGITS > &y)
template<int X_DIGITS, int Y_DIGITS>
bigint & sub (const bigint< X_DIGITS > &x, const bigint< Y_DIGITS > &y)
template<int Y_DIGITS>
bigint & sub (const bigint< Y_DIGITS > &y)
void shrink ()
void shrinkdigits (int n)
void shrinkbits (int n)
template<int Y_DIGITS>
void copyshrinkdigits (const bigint< Y_DIGITS > &y, int n)
template<int Y_DIGITS>
void copyshrinkbits (const bigint< Y_DIGITS > &y, int n)
template<int X_DIGITS, int Y_DIGITS>
bigint & mul (const bigint< X_DIGITS > &x, const bigint< Y_DIGITS > &y)
bigint & rshift (int n)
bigint & lshift (int n)
void zerodigits (int i, int n)
void zerobits (int i, int n)
template<int Y_DIGITS>
void copydigits (int to, const bigint< Y_DIGITS > &y, int from, int n)
template<int Y_DIGITS>
void copybits (int to, const bigint< Y_DIGITS > &y, int from, int n)
void dupdigits (int to, int from, int n)
void dupbits (int to, int from, int n)
template<int Y_DIGITS>
bool operator== (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator!= (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator< (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator> (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator<= (const bigint< Y_DIGITS > &y) const
template<int Y_DIGITS>
bool operator>= (const bigint< Y_DIGITS > &y) const
Static Public Member Functions
static int parsedigits (ushort *digits, int maxlen, const char *s)
Public Attributes
int len
digit digits [BI_DIGITS]
Member Typedef Documentation
template<int BI_DIGITS> typedef uint bigint< BI_DIGITS >::dbldigit
template<int BI_DIGITS> typedef ushort bigint< BI_DIGITS >::digit
Constructor & Destructor Documentation
template<int BI_DIGITS> bigint< BI_DIGITS >::bigint () inline
template<int BI_DIGITS> bigint< BI_DIGITS >::bigint (digit n) inline
References bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
template<int BI_DIGITS> bigint< BI_DIGITS >::bigint (const char * s) inline
References bigint< BI_DIGITS >::parse().
template<int BI_DIGITS> template<int Y_DIGITS> bigint< BI_DIGITS >::bigint (const bigint< Y_DIGITS > & y) inline
Member Function Documentation
template<int BI_DIGITS> template<int X_DIGITS, int Y_DIGITS> bigint& bigint< BI_DIGITS >::add (const bigint< X_DIGITS > & x, const bigint< Y_DIGITS > & y) inline
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and inexor::rpc::max().
Referenced by gfield::add(), gfield::div2(), gfield::invert(), and gfield::sub().
template<int BI_DIGITS> template<int Y_DIGITS> bigint& bigint< BI_DIGITS >::add (const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::add().
Referenced by bigint< BI_DIGITS >::add().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copybits (int to, const bigint< Y_DIGITS > & y, int from, int n) inline
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::copydigits().
Referenced by gfield::reduce().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copydigits (int to, const bigint< Y_DIGITS > & y, int from, int n) inline
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and inexor::rpc::min().
Referenced by bigint< BI_DIGITS >::copybits().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copyshrinkbits (const bigint< Y_DIGITS > & y, int n) inline
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::copyshrinkdigits().
template<int BI_DIGITS> template<int Y_DIGITS> void bigint< BI_DIGITS >::copyshrinkdigits (const bigint< Y_DIGITS > & y, int n) inline
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, inexor::rpc::min(), and bigint< BI_DIGITS >::shrink().
Referenced by bigint< BI_DIGITS >::copyshrinkbits(), and gfield::reduce().
template<int BI_DIGITS> void bigint< BI_DIGITS >::dupbits (int to, int from, int n) inline
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::dupdigits().
Referenced by gfield::reduce().
template<int BI_DIGITS> void bigint< BI_DIGITS >::dupdigits (int to, int from, int n) inline
References bigint< BI_DIGITS >::digits.
Referenced by bigint< BI_DIGITS >::dupbits().
template<int BI_DIGITS> bool bigint< BI_DIGITS >::hasbit (int n) const inline
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by ecjacobian::calcy(), gfield::div2(), gfield::invert(), ecjacobian::mul(), and gfield::pow().
template<int BI_DIGITS> bool bigint< BI_DIGITS >::isone () const inline
References bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by ecjacobian::add(), and ecjacobian::normalize().
template<int BI_DIGITS> bool bigint< BI_DIGITS >::iszero () const inline
References bigint< BI_DIGITS >::len.
Referenced by ecjacobian::add(), ecjacobian::mul2(), and ecjacobian::normalize().
template<int BI_DIGITS> bigint& bigint< BI_DIGITS >::lshift (int n) inline
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and loopirev.
template<int BI_DIGITS> bool bigint< BI_DIGITS >::morebits (int n) const inline
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::len.
Referenced by gfield::reduce().
template<int BI_DIGITS> template<int X_DIGITS, int Y_DIGITS> bigint& bigint< BI_DIGITS >::mul (const bigint< X_DIGITS > & x, const bigint< Y_DIGITS > & y) inline
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, loopi(), loopj, and bigint< BI_DIGITS >::shrink().
Referenced by gfield::mul().
template<int BI_DIGITS> int bigint< BI_DIGITS >::numbits () const inline
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by ecjacobian::mul(), and gfield::pow().
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator!= (const bigint< Y_DIGITS > & y) const inline
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator< (const bigint< Y_DIGITS > & y) const inline
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and loopirev.
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator<= (const bigint< Y_DIGITS > & y) const inline
template<int BI_DIGITS> template<int Y_DIGITS> bigint& bigint< BI_DIGITS >::operator= (const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by gfield::operator=().
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator== (const bigint< Y_DIGITS > & y) const inline
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and loopirev.
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator> (const bigint< Y_DIGITS > & y) const inline
template<int BI_DIGITS> template<int Y_DIGITS> bool bigint< BI_DIGITS >::operator>= (const bigint< Y_DIGITS > & y) const inline
template<int BI_DIGITS> void bigint< BI_DIGITS >::parse (const char * s) inline
References bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, bigint< BI_DIGITS >::parsedigits(), and bigint< BI_DIGITS >::shrink().
Referenced by bigint< BI_DIGITS >::bigint(), and ecjacobian::parse().
template<int BI_DIGITS> static int bigint< BI_DIGITS >::parsedigits (ushort * digits, int maxlen, const char * s) inline static
References bigint< BI_DIGITS >::len, and loopi().
Referenced by bigint< BI_DIGITS >::parse().
template<int BI_DIGITS> bigint& bigint< BI_DIGITS >::rshift (int n) inline
References BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and bigint< BI_DIGITS >::shrink().
Referenced by gfield::div2(), gfield::invert(), gfield::legendre(), and gfield::sqrt().
template<int BI_DIGITS> void bigint< BI_DIGITS >::shrink () inline
References bigint< BI_DIGITS >::digits, and bigint< BI_DIGITS >::len.
Referenced by bigint< BI_DIGITS >::copyshrinkdigits(), bigint< BI_DIGITS >::mul(), bigint< BI_DIGITS >::parse(), bigint< BI_DIGITS >::rshift(), bigint< BI_DIGITS >::shrinkdigits(), and bigint< BI_DIGITS >::sub().
template<int BI_DIGITS> void bigint< BI_DIGITS >::shrinkbits (int n) inline
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::shrinkdigits().
Referenced by gfield::reduce().
template<int BI_DIGITS> void bigint< BI_DIGITS >::shrinkdigits (int n) inline
References bigint< BI_DIGITS >::len, and bigint< BI_DIGITS >::shrink().
Referenced by gfield::reduce(), and bigint< BI_DIGITS >::shrinkbits().
template<int BI_DIGITS> template<int X_DIGITS, int Y_DIGITS> bigint& bigint< BI_DIGITS >::sub (const bigint< X_DIGITS > & x, const bigint< Y_DIGITS > & y) inline
References ASSERT, BI_DIGIT_BITS, bigint< BI_DIGITS >::digits, bigint< BI_DIGITS >::len, and bigint< BI_DIGITS >::shrink().
Referenced by gfield::add(), gfield::invert(), gfield::neg(), gfield::reduce(), and gfield::sub().
template<int BI_DIGITS> template<int Y_DIGITS> bigint& bigint< BI_DIGITS >::sub (const bigint< Y_DIGITS > & y) inline
References bigint< BI_DIGITS >::sub().
Referenced by bigint< BI_DIGITS >::sub().
template<int BI_DIGITS> void bigint< BI_DIGITS >::zero () inline
References bigint< BI_DIGITS >::len.
Referenced by ecjacobian::calcy().
template<int BI_DIGITS> void bigint< BI_DIGITS >::zerobits (int i, int n) inline
References BI_DIGIT_BITS, and bigint< BI_DIGITS >::zerodigits().
Referenced by gfield::reduce().
template<int BI_DIGITS> void bigint< BI_DIGITS >::zerodigits (int i, int n) inline
References bigint< BI_DIGITS >::digits.
Referenced by bigint< BI_DIGITS >::zerobits().
Member Data Documentation
template<int BI_DIGITS> digit bigint< BI_DIGITS >::digits[BI_DIGITS]
Referenced by bigint< BI_DIGITS >::add(), bigint< BI_DIGITS >::bigint(), bigint< BI_DIGITS >::copydigits(), bigint< BI_DIGITS >::copyshrinkdigits(), bigint< BI_DIGITS >::dupdigits(), bigint< BI_DIGITS >::hasbit(), gfield::invert(), bigint< BI_DIGITS >::isone(), bigint< BI_DIGITS >::lshift(), bigint< BI_DIGITS >::mul(), bigint< BI_DIGITS >::numbits(), bigint< BI_DIGITS >::operator<(), bigint< BI_DIGITS >::operator=(), bigint< BI_DIGITS >::operator==(), bigint< BI_DIGITS >::parse(), gfield::pow(), bigint< BI_DIGITS >::rshift(), bigint< BI_DIGITS >::shrink(), gfield::sqrt(), bigint< BI_DIGITS >::sub(), and bigint< BI_DIGITS >::zerodigits().
template<int BI_DIGITS> int bigint< BI_DIGITS >::len
Referenced by bigint< BI_DIGITS >::add(), bigint< BI_DIGITS >::bigint(), bigint< BI_DIGITS >::copydigits(), bigint< BI_DIGITS >::copyshrinkdigits(), bigint< BI_DIGITS >::hasbit(), gfield::invert(), bigint< BI_DIGITS >::isone(), bigint< BI_DIGITS >::iszero(), gfield::legendre(), bigint< BI_DIGITS >::lshift(), bigint< BI_DIGITS >::morebits(), bigint< BI_DIGITS >::mul(), bigint< BI_DIGITS >::numbits(), bigint< BI_DIGITS >::operator<(), bigint< BI_DIGITS >::operator=(), bigint< BI_DIGITS >::operator==(), bigint< BI_DIGITS >::parse(), bigint< BI_DIGITS >::parsedigits(), gfield::pow(), bigint< BI_DIGITS >::rshift(), bigint< BI_DIGITS >::shrink(), bigint< BI_DIGITS >::shrinkdigits(), gfield::sqrt(), bigint< BI_DIGITS >::sub(), and bigint< BI_DIGITS >::zero().
The documentation for this struct was generated from the following file:
inexor/network/legacy/crypto.cpp