Inexor: animmodel::part Struct Reference
animmodel::part Struct Reference
#include <animmodel.hpp>
Public Member Functions
part (animmodel *model, int index=0)
virtual ~part ()
virtual void cleanup ()
void calcbb (vec &bbmin, vec &bbmax, const matrix4x3 &m)
void genBIH (vector< BIH::mesh > &bih, const matrix4x3 &m)
bool link (part *p, const char *tag, const vec &translate=vec(0, 0, 0), int anim=-1, int basetime=0, vec *pos=nullptr)
bool unlink (part *p)
void initskins (Texture *tex=notexture, Texture *masks=notexture, int limit=0)
bool envmapped ()
bool tangents ()
void preloadBIH ()
void preloadshaders (bool force)
void preloadmeshes ()
virtual void getdefaultanim (animinfo &info, int anim, uint varseed, dynent *d)
bool calcanim (int animpart, int anim, int basetime, int basetime2, dynent *d, int interp, animinfo &info, int &aitime)
void render (int anim, int basetime, int basetime2, float pitch, const vec &axis, const vec &forward, dynent *d)
void render (int anim, int basetime, int basetime2, float pitch, const vec &axis, const vec &forward, dynent *d, animstate *as)
void setanim (int animpart, int num, int frame, int range, float speed, int priority=0)
virtual void loaded ()
Public Attributes
animmodel * model
int index
meshgroup * meshes
vector< linkedpart > links
vector< skin > skins
vector< animspec > * anims [MAXANIMPARTS]
int numanimparts
float pitchscale
float pitchoffset
float pitchmin
float pitchmax
vec translate
Constructor & Destructor Documentation
animmodel::part::part (animmodel * model, int index = 0) inline
References anims, loopk, and MAXANIMPARTS.
virtual animmodel::part::~part () inline virtual
References anims, DELETEA, loopk, and MAXANIMPARTS.
Member Function Documentation
bool animmodel::part::calcanim (int animpart, int anim, int basetime, int basetime2, dynent * d, int interp, animinfo & info, int & aitime) inline
References animinfo::anim, ANIM_ALL, ANIM_CLAMP, ANIM_DIR, ANIM_END, ANIM_FLAGS, ANIM_INDEX, ANIM_LOOP, ANIM_RAGDOLL, ANIM_SECONDARY, ANIM_SETSPEED, ANIM_SETTIME, ANIM_START, animmodel::meshgroup::animkey(), anims, animinfo::basetime, animmodel::meshgroup::clipframes(), animinterpinfo::cur, f(), animmodel::animspec::frame, animinfo::frame, getdefaultanim(), animmodel::meshgroup::hasframe(), animmodel::meshgroup::hasframes(), lastmillis, animinterpinfo::lastmodel, animinterpinfo::lastswitch, vector< T, MINSIZE >::length(), meshes, inexor::rpc::min(), NUMANIMS, animinterpinfo::prev, animmodel::animspec::priority, animmodel::animspec::range, animinfo::range, animmodel::animspec::speed, animinfo::speed, animmodel::meshgroup::totalframes(), and animinfo::varseed.
Referenced by render().
void animmodel::part::calcbb (vec & bbmin, vec & bbmax, const matrix4x3 & m) inline
References animmodel::meshgroup::calcbb(), animmodel::meshgroup::concattagtransform(), links, loopv, meshes, model::scale, matrix4x3::scale(), anonymous_namespace{utilTest.cpp}::t(), translate, and matrix4x3::translate().
virtual void animmodel::part::cleanup () inline virtual
References animmodel::meshgroup::cleanup(), loopv, meshes, and skins.
bool animmodel::part::envmapped () inline
References loopv, and skins.
Referenced by render().
void animmodel::part::genBIH (vector< BIH::mesh > & bih, const matrix4x3 & m) inline
References animmodel::meshgroup::concattagtransform(), animmodel::meshgroup::genBIH(), links, loopv, meshes, model::scale, matrix4x3::scale(), skins, anonymous_namespace{utilTest.cpp}::t(), translate, and matrix4x3::translate().
virtual void animmodel::part::getdefaultanim (animinfo & info, int anim, uint varseed, dynent * d) inline virtual
Reimplemented in md2::md2part.
References animinfo::frame, and animinfo::range.
Referenced by calcanim().
void animmodel::part::initskins (Texture * tex = notexture, Texture * masks = notexture, int limit = 0) inline
References animmodel::skin::masks, animmodel::meshgroup::meshes, meshes, animmodel::skin::owner, skins, and animmodel::skin::tex.
Referenced by md5::md5mesh::load(), md2::load(), md3::loaddefaultparts(), obj::loaddefaultparts(), iqm::loaddefaultparts(), md5::loaddefaultparts(), and smd::loaddefaultparts().
bool animmodel::part::link (part * p, const char * tag, const vec & translate = vec(0, 0, 0), int anim = -1, int basetime = 0, vec * pos = nullptr) inline
References animmodel::linkedpart::anim, animmodel::linkedpart::basetime, animmodel::meshgroup::findtag(), link(), links, loopv, meshes, animmodel::linkedpart::p, animmodel::linkedpart::pos, animmodel::linkedpart::tag, animmodel::linkedpart::translate, and translate.
Referenced by link(), and render().
virtual void animmodel::part::loaded () inline virtual
Reimplemented in skelmodel::skelpart.
References loopv, meshes, animmodel::meshgroup::shared, and skins.
Referenced by skelmodel::skelpart::loaded().
void animmodel::part::preloadBIH () inline
References loopv, and skins.
void animmodel::part::preloadmeshes () inline
References meshes, and animmodel::meshgroup::preload().
void animmodel::part::preloadshaders (bool force) inline
References loopv, and skins.
void animmodel::part::render (int anim, int basetime, int basetime2, float pitch, const vec & axis, const vec & forward, dynent * d) inline
References MAXANIMPARTS.
Referenced by render(), and animmodel::render().
void animmodel::part::render (int anim, int basetime, int basetime2, float pitch, const vec & axis, const vec & forward, dynent * d, animstate * as) inline
References animmodel::animpos::anim, animmodel::linkedpart::anim, ANIM_FLAGS, ANIM_NOPITCH, ANIM_NORENDER, ANIM_NOSKIN, ANIM_REUSE, dynent::animinterp, animmodel::linkedpart::basetime, calcanim(), camera1, camprojmatrix, animmodel::animstate::cur, vec::div(), envmapped(), matrix4::gettranslation(), GLOBALPARAM, animmodel::animstate::interp, vec::iszero(), lastmillis, animinterpinfo::lastswitch, animmodel::lightdir, link(), links, loopi(), loopv, animmodel::linkedpart::matrix, animmodel::matrixpos, animmodel::matrixstack, MAXANIMPARTS, meshes, matrix4::mul(), numanimparts, physent::o, animmodel::animstate::owner, animmodel::linkedpart::p, pitchmax, pitchmin, pitchoffset, pitchscale, animmodel::linkedpart::pos, animmodel::animstate::prev, animinterpinfo::prev, RAD, animinfo::range, animmodel::meshgroup::render(), render(), matrix4::rotate(), model::scale, matrix4::scale(), animmodel::animpos::setframes(), shadowmapping, shadowmatrix, vec::sub(), translate, matrix4::translate(), matrix4::transposedtransform(), and matrix4::transposedtransformnormal().
void animmodel::part::setanim (int animpart, int num, int frame, int range, float speed, int priority = 0) inline
References anims, animmodel::animspec::frame, Log, MAXANIMPARTS, model::name, NUMANIMS, animmodel::animspec::priority, animmodel::animspec::range, animmodel::animspec::speed, and inexor::util::log_manager::std.
bool animmodel::part::tangents () inline
References loopv, and skins.
Referenced by animmodel::skin::loadshader(), vertmodel::vertmeshgroup::preload(), and vertmodel::vertmeshgroup::render().
bool animmodel::part::unlink (part * p) inline
References links, loopv, loopvrev, and unlink().
Referenced by unlink().
Member Data Documentation
vector<animspec>* animmodel::part::anims[MAXANIMPARTS]
Referenced by calcanim(), part(), setanim(), and ~part().
int animmodel::part::index
Referenced by animmodel::render().
vector<linkedpart> animmodel::part::links
Referenced by calcbb(), skelmodel::skeleton::calctags(), genBIH(), link(), vertmodel::vertmeshgroup::render(), render(), and unlink().
meshgroup* animmodel::part::meshes
Referenced by skelmodel::skelpart::addanimpart(), calcanim(), calcbb(), cleanup(), skelmodel::skelpart::endanimparts(), genBIH(), initskins(), link(), md2::load(), md3::loaddefaultparts(), obj::loaddefaultparts(), iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), loaded(), skelmodel::skelpart::newpartmask(), preloadmeshes(), and render().
animmodel* animmodel::part::model
Referenced by vertmodel::vertmeshgroup::calctagmatrix(), skelmodel::skeleton::calctags(), vertmodel::vertmeshgroup::concattagtransform(), skelmodel::skeleton::concattagtransform(), skelmodel::skeleton::genragdollbones(), skelmodel::skeleton::initragdoll(), and skelmodel::skelmeshgroup::render().
int animmodel::part::numanimparts
Referenced by skelmodel::skelpart::addanimpart(), render(), and animmodel::render().
float animmodel::part::pitchmax
Referenced by iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), and render().
float animmodel::part::pitchmin
Referenced by iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), and render().
float animmodel::part::pitchoffset
Referenced by iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), and render().
float animmodel::part::pitchscale
Referenced by iqm::loaddefaultparts(), md5::loaddefaultparts(), smd::loaddefaultparts(), and render().
vector<skin> animmodel::part::skins
Referenced by cleanup(), envmapped(), genBIH(), initskins(), md5::md5mesh::load(), loaded(), skelmodel::skelmeshgroup::preload(), preloadBIH(), preloadshaders(), vertmodel::vertmeshgroup::render(), skelmodel::skelmeshgroup::render(), and tangents().
vec animmodel::part::translate
Referenced by calcbb(), vertmodel::vertmeshgroup::calctagmatrix(), skelmodel::skeleton::calctags(), vertmodel::vertmeshgroup::concattagtransform(), skelmodel::skeleton::concattagtransform(), genBIH(), skelmodel::skeleton::genragdollbones(), skelmodel::skeleton::initragdoll(), link(), and render().
The documentation for this struct was generated from the following file:
inexor/model/animmodel.hpp