Inexor: texturegui Struct Reference
texturegui Struct Reference
Public Member Functions
texturegui ()
void gui (g3d_gui &g, bool firstpass) override
void showtextures (bool on)
void show ()
int starttime ()
Public Attributes
bool menuon
vec menupos
int menustart
int menutab
Constructor & Destructor Documentation
texturegui::texturegui () inline
Member Function Documentation
void texturegui::gui (g3d_gui & g, bool firstpass) inline override virtual
Implements g3d_callback.
References dummyvslot, edittex(), g3d_gui::end(), f(), G3D_UP, hudshader, VSlot::index, lastthumbnail, Slot::loaded, Slot::loadthumbnail(), lookupslot(), loop, loopi(), inexor::rpc::max(), menustart, menutab, notexture, g3d_gui::poplist(), g3d_gui::pushlist(), Shader::set(), slots, g3d_gui::start(), Slot::sts, g3d_gui::tab(), g3d_gui::texture(), Slot::thumbnail, totalmillis, and Slot::variants.
void texturegui::show () inline
References camera1, vec::dist(), editmode, filltexlist(), g3d_addgui(), GUI_2D, menuautoclose, menupos, and physent::o.
void texturegui::showtextures (bool on) inline
References VSlot::index, lasttex, lasttexmillis, lookupvslot(), menuinfrontofplayer(), menupos, menustart, menutab, slots, and recorder::starttime.
int g3d_callback::starttime () inherited
References totalmillis.
Referenced by game::scoreboardgui::show().
Member Data Documentation
bool texturegui::menuon
vec texturegui::menupos
int texturegui::menustart
int texturegui::menutab
The documentation for this struct was generated from the following file:
inexor/engine/octaedit.cpp