Inexor: server::maprotation Struct Reference
server::maprotation Struct Reference
Public Member Functions
long calcmodemask () const
bool hasmode (int mode, int offset=0) const
int findmode (int mode) const
bool match (int reqmode, const char *reqmap) const
bool includes (const maprotation &rot) const
Public Attributes
long modes
string map
Static Public Attributes
static int exclude = 0
Member Function Documentation
long server::maprotation::calcmodemask () const inline
References exclude, modes, and NUMGAMEMODES.
Referenced by hasmode().
int server::maprotation::findmode (int mode) const inline
References hasmode(), loopi(), and NUMGAMEMODES.
Referenced by server::rotatemap().
bool server::maprotation::hasmode (int mode, int offset = 0) const inline
References calcmodemask().
Referenced by findmode(), and match().
bool server::maprotation::includes (const maprotation & rot) const inline
bool server::maprotation::match (int reqmode, const char * reqmap) const inline
References hasmode(), and map.
Referenced by server::findmaprotation().
Member Data Documentation
int server::maprotation::exclude = 0 static
Referenced by server::addmaprotation(), calcmodemask(), and server::maprotationreset().
string server::maprotation::map
Referenced by server::addmaprotation(), match(), and server::rotatemap().
long server::maprotation::modes
Referenced by server::addmaprotation(), calcmodemask(), and server::findmaprotation().
The documentation for this struct was generated from the following file:
inexor/fpsgame/server.cpp