Inexor: editor Struct Reference
editor Struct Reference
#include <textedit.hpp>
Public Member Functions
editor (const char *name, int mode, const char *initval)
~editor ()
void clear (const char *init="")
void setfile (const char *fname)
void load ()
void save ()
void mark (bool enable)
void selectall ()
bool region (int &sx, int &sy, int &ex, int &ey)
bool region ()
editline & currentline ()
void copyselectionto (editor *b)
char * tostring ()
char * selectiontostring ()
void removelines (int start, int count)
bool del ()
void insert (char ch)
void insert (const char *s)
void insertallfrom (editor *b)
void key (int code)
void input (const char *str, int len)
void hit (int hitx, int hity, bool dragged)
int limitscrolly ()
void draw (int x, int y, int color, bool hit)
Public Attributes
int mode
bool active
bool rendered
const char * name
const char * filename
int cx
int cy
int mx
int my
int maxx
int maxy
int scrolly
bool linewrap
int pixelwidth
int pixelheight
vector< editline > lines
Constructor & Destructor Documentation
editor::editor (const char * name, int mode, const char * initval) inline
References vector< T, MINSIZE >::add(), lines, and editline::set().
editor::~editor () inline
References clear(), DELETEA, filename, and name.
Member Function Documentation
void editor::clear (const char * init = "") inline
References vector< T, MINSIZE >::add(), cx, cy, sphere::init(), lines, loopv, mark(), editline::set(), and vector< T, MINSIZE >::shrink().
Referenced by copyselectionto(), gui::field_(), load(), and ~editor().
void editor::copyselectionto (editor * b) inline
References vector< T, MINSIZE >::add(), clear(), vector< T, MINSIZE >::empty(), vector< T, MINSIZE >::length(), lines, loopi(), maxy, region(), and editline::set().
editline& editor::currentline () inline
References ASSERT, cx, cy, vector< T, MINSIZE >::length(), and lines.
Referenced by del(), gui::field_(), insert(), insertallfrom(), and key().
bool editor::del () inline
References vector< T, MINSIZE >::add(), editline::append(), currentline(), cx, cy, vector< T, MINSIZE >::empty(), editline::len, vector< T, MINSIZE >::length(), lines, mark(), region(), removelines(), and editline::set().
Referenced by insert(), insertallfrom(), and key().
void editor::draw (int x, int y, int color, bool hit) inline
References gle::begin(), cx, cy, draw_text(), gle::end(), FONTH, FONTW, hudnotextureshader, hudshader, vector< T, MINSIZE >::length(), lines, linewrap, maxy, pixelheight, pixelwidth, region(), scrolly, Shader::set(), text_bounds(), and text_pos().
Referenced by gui::field_().
void editor::hit (int hitx, int hity, bool dragged) inline
References cx, cy, vector< T, MINSIZE >::length(), lines, linewrap, mx, my, pixelheight, pixelwidth, scrolly, text_bounds(), and text_visible().
Referenced by gui::field_().
void editor::input (const char * str, int len) inline
References insert(), and loopi().
Referenced by g3d_input().
void editor::insert (char ch) inline
References editline::chop(), currentline(), cx, cy, del(), editline::insert(), vector< T, MINSIZE >::insert(), editline::len, vector< T, MINSIZE >::length(), lines, maxx, maxy, inexor::rpc::min(), and editline::text.
Referenced by g3d_key(), input(), insert(), and key().
void editor::insert (const char * s) inline
References insert().
void editor::insertallfrom (editor * b) inline
References currentline(), cx, cy, del(), editline::insert(), vector< T, MINSIZE >::insert(), editline::len, vector< T, MINSIZE >::length(), lines, loopv, inexor::rpc::max(), maxx, and maxy.
void editor::key (int code) inline
References editline::append(), currentline(), cx, cy, editline::del(), del(), FONTH, insert(), editline::len, vector< T, MINSIZE >::length(), lines, linewrap, pixelheight, pixelwidth, removelines(), editline::text, text_bounds(), text_pos(), and text_visible().
Referenced by g3d_key().
int editor::limitscrolly () inline
References vector< T, MINSIZE >::length(), lines, linewrap, pixelheight, pixelwidth, and text_bounds().
Referenced by gui::field_().
void editor::load () inline
References vector< T, MINSIZE >::add(), editline::clear(), clear(), vector< T, MINSIZE >::empty(), recorder::file, filename, vector< T, MINSIZE >::length(), lines, maxx, maxy, openutf8file(), vector< T, MINSIZE >::pop(), editline::read(), and editline::set().
void editor::mark (bool enable) inline
References cx, cy, sphere::enable(), mx, and my.
Referenced by clear(), del(), and gui::field_().
bool editor::region (int & sx, int & sy, int & ex, int & ey) inline
References ASSERT, cx, cy, vector< T, MINSIZE >::length(), lines, mx, and my.
bool editor::region () inline
References region().
Referenced by copyselectionto(), del(), draw(), region(), and selectiontostring().
void editor::removelines (int start, int count) inline
References lines, loopi(), and vector< T, MINSIZE >::remove().
Referenced by del(), and key().
void editor::save () inline
References recorder::file, filename, lines, loopv, openutf8file(), and stream::putline().
void editor::selectall () inline
References cx, cy, mx, and my.
char* editor::selectiontostring () inline
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::getbuf(), vector< T, MINSIZE >::length(), lines, loopi(), newstring(), vector< T, MINSIZE >::put(), and region().
void editor::setfile (const char * fname) inline
References DELETEA, filename, and newstring().
char* editor::tostring () inline
References editline::len, lines, loopv, newstring(), and editline::text.
Member Data Documentation
bool editor::active
Referenced by gui::field_(), and useeditor().
int editor::cx
Referenced by clear(), currentline(), del(), draw(), hit(), insert(), insertallfrom(), key(), mark(), region(), and selectall().
int editor::cy
Referenced by clear(), currentline(), del(), draw(), gui::field_(), hit(), insert(), insertallfrom(), key(), mark(), region(), and selectall().
const char* editor::filename
Referenced by load(), save(), setfile(), and ~editor().
vector<editline> editor::lines
Referenced by clear(), copyselectionto(), currentline(), del(), draw(), editor(), gui::field_(), g3d_key(), hit(), insert(), insertallfrom(), key(), limitscrolly(), load(), region(), removelines(), save(), selectiontostring(), and tostring().
bool editor::linewrap
Referenced by draw(), gui::field_(), hit(), key(), and limitscrolly().
int editor::maxx
Referenced by gui::field_(), insert(), insertallfrom(), and load().
int editor::maxy
Referenced by copyselectionto(), draw(), gui::field_(), g3d_key(), insert(), insertallfrom(), and load().
int editor::mode
Referenced by gui::field_().
int editor::mx
Referenced by hit(), mark(), region(), and selectall().
int editor::my
Referenced by hit(), mark(), region(), and selectall().
const char* editor::name
Referenced by ~editor().
int editor::pixelheight
Referenced by draw(), gui::field_(), hit(), key(), and limitscrolly().
int editor::pixelwidth
Referenced by draw(), gui::field_(), hit(), key(), and limitscrolly().
bool editor::rendered
Referenced by gui::field_().
int editor::scrolly
Referenced by draw(), gui::field_(), and hit().
The documentation for this struct was generated from the following file:
inexor/ui/legacy/textedit.hpp