Inexor: server::shotevent Struct Reference
server::shotevent Struct Reference
#include <client_management.hpp>
Public Member Functions
void process (clientinfo *ci) override
bool flush (clientinfo *ci, int fmillis) override
virtual bool keepable () const
Public Attributes
int id
int gun
vec from
vec to
vector< hitinfo > hits
int millis
Member Function Documentation
bool server::timedevent::flush (clientinfo * ci, int fmillis) override virtual inherited
Reimplemented from server::gameevent.
References server::clientinfo::lastevent, server::timedevent::millis, and server::gameevent::process().
virtual bool server::gameevent::keepable () const inline virtual inherited
Reimplemented in server::explodeevent.
void server::shotevent::process (clientinfo * ci) override virtual
Reimplemented from server::gameevent.
References server::projectilestate< N >::add(), fpsstate::ammo, guninfo::attackdelay, server::gamestate::bombs, server::clientinfo::clientnum, CS_ALIVE, guninfo::damage, server::hitinfo::dir, server::hitinfo::dist, vec::dist(), DMF, server::dodamage(), from, gamemillis, server::get_client_info(), server::gamestate::grenades, gun, GUN_BOMB, GUN_FIST, GUN_GL, GUN_RL, GUN_SPLINTER, guns, fpsstate::gunwait, hits, server::gamestate::isalive(), server::gamestate::lastshot, server::gamestate::lifesequence, server::hitinfo::lifesequence, loopv, server::timedevent::millis, N_SHOTFX, server::clientinfo::ownernum, fpsstate::quadmillis, guninfo::range, game::rays, guninfo::rays, server::hitinfo::rays, server::gamestate::rockets, sendf(), server::gamestate::shotdamage, server::gamestate::state, server::clientinfo::state, server::hitinfo::target, and to.
Member Data Documentation
vec server::shotevent::from
Referenced by server::parsepacket(), and process().
int server::shotevent::gun
Referenced by server::parsepacket(), and process().
vector<hitinfo> server::shotevent::hits
Referenced by server::parsepacket(), and process().
int server::shotevent::id
Referenced by server::parsepacket().
int server::timedevent::millis inherited
Referenced by server::timedevent::flush(), server::parsepacket(), and process().
vec server::shotevent::to
Referenced by server::parsepacket(), and process().
The documentation for this struct was generated from the following files:
inexor/server/client_management.hpp
inexor/fpsgame/server.cpp