Inexor: inexor::sound::soundtype Struct Reference
inexor::sound::soundtype Struct Reference
Public Member Functions
int findsound (const char *name, int vol)
int addslot (const char *name, int vol)
int addsound (const char *name, int vol, int maxuses=0)
void addalt (const char *name, int vol)
void clear ()
void reset ()
void preloadsound (int n)
bool playing (const soundchannel &chan, const soundconfig &config) const
Public Attributes
vector< soundslot > slots
vector< soundconfig > configs
Member Function Documentation
void inexor::sound::soundtype::addalt (const char * name, int vol) inline
Referenced by inexor::sound::altmapsound(), and inexor::sound::altsound().
int inexor::sound::soundtype::addslot (const char * name, int vol) inline
References inexor::sound::channels, inexor::sound::soundchannel::inuse, loopv, inexor::sound::soundsample::name, newstring(), inexor::sound::soundslot::sample, inexor::sound::samples, inexor::sound::soundchannel::slot, slots, and inexor::sound::soundslot::volume.
int inexor::sound::soundtype::addsound (const char * name, int vol, int maxuses = 0) inline
References inexor::sound::soundconfig::maxuses, inexor::sound::soundconfig::numslots, and inexor::sound::soundconfig::slots.
Referenced by inexor::sound::mapsound(), inexor::sound::playsoundname(), and inexor::sound::registersound().
void inexor::sound::soundtype::clear () inline
References slots.
Referenced by inexor::sound::clear_sound(), and inexor::sound::clearmapsounds().
int inexor::sound::soundtype::findsound (const char * name, int vol) inline
References loopj, loopv, inexor::sound::soundsample::name, inexor::sound::soundconfig::numslots, inexor::sound::soundslot::sample, slots, inexor::sound::soundconfig::slots, and inexor::sound::soundslot::volume.
Referenced by inexor::sound::playsoundname().
bool inexor::sound::soundtype::playing (const soundchannel & chan, const soundconfig & config) const inline
References inexor::sound::soundconfig::hasslot(), inexor::sound::soundchannel::inuse, inexor::sound::soundchannel::slot, and slots.
Referenced by inexor::sound::playsound(), and inexor::sound::stopsound().
void inexor::sound::soundtype::preloadsound (int n) inline
References loopk, inexor::sound::nosound, inexor::sound::soundconfig::numslots, slots, and inexor::sound::soundconfig::slots.
Referenced by inexor::sound::preloadmapsound(), inexor::sound::preloadmapsounds(), and inexor::sound::preloadsound().
void inexor::sound::soundtype::reset () inline
References inexor::sound::channels, inexor::sound::freechannel(), inexor::sound::soundchannel::inuse, loopv, inexor::sound::soundchannel::slot, and slots.
Referenced by inexor::sound::mapsoundreset(), and inexor::sound::soundreset().
Member Data Documentation
vector<soundconfig> inexor::sound::soundtype::configs
Referenced by inexor::sound::playsound(), and inexor::sound::stopsound().
vector<soundslot> inexor::sound::soundtype::slots
Referenced by inexor::sound::playsound().
The documentation for this struct was generated from the following file:
inexor/sound/sound.cpp