Inexor: pvsworker Struct Reference
pvsworker Struct Reference
Classes
struct cullorder
Public Member Functions
pvsworker ()
~pvsworker ()
void resetlevels ()
int hasvoxel (const ivec &p, int coord, int dir, int ocoord=0, int odir=0, int *omin=nullptr)
void hidepvs (pvsnode &p)
void shaftcullpvs (shaft &s, pvsnode &p, const ivec &co=ivec(0, 0, 0), int size=worldsize)
void cullpvs (pvsnode &p, const ivec &co=ivec(0, 0, 0), int size=worldsize)
bool compresspvs (pvsnode &p, int size, int threshold)
bool serializepvs (pvsnode &p, int storage=-1)
bool materialoccluded (pvsnode &p, const ivec &co, int size, const ivec &bbmin, const ivec &bbmax)
bool materialoccluded (vector< materialsurface * > &matsurfs)
void calcpvs (const ivec &co, int size)
uchar * testviewcell (const ivec &co, int size, int *waterpvs=nullptr, int *len=nullptr)
int genviewcell (const ivec &co, int size)
Static Public Member Functions
static int run (void *data)
Public Attributes
SDL_Thread * thread
pvsnode * pvsnodes
shaftbb viewcellbb
pvsnode * levels [32]
int curlevel
ivec origin
queue< shaftbb, 32 > prevblockers
vector< uchar > outbuf
int wateroccluded
int waterbytes
Constructor & Destructor Documentation
pvsworker::pvsworker () inline
pvsworker::~pvsworker () inline
Member Function Documentation
void pvsworker::calcpvs (const ivec & co, int size) inline
References vector< T, MINSIZE >::length(), loopi(), loopk, ivec::max(), numwaterplanes, origpvsnodes, waterfalls, waterplanes, and worldsize.
bool pvsworker::compresspvs (pvsnode & p, int size, int threshold) inline
References pvsnode::children, pvsnode::flags, hmap::flags, loopi(), and PVS_HIDE_BB.
void pvsworker::cullpvs (pvsnode & p, const ivec & co = ivec(0, 0, 0), int size = worldsize) inline
References ivec::abs(), ivec::add(), C, pvsnode::children, shaftbb::contains(), hmap::dc, dir, pvsworker::cullorder::dist, pvsnode::edges, pvsnode::flags, genpvs_canceled, pvsworker::cullorder::index, loopi(), loopj, loopvj, inexor::rpc::max(), inexor::rpc::min(), ivec::mul(), PVS_HIDE_BB, PVS_HIDE_GEOM, R, ivec::shr(), and ivec::sub().
int pvsworker::genviewcell (const ivec & co, int size) inline
References vector< T, MINSIZE >::add(), vector< T, MINSIZE >::length(), loopi(), numviewcells, vector< T, MINSIZE >::put(), pvs, pvsbuf, pvscompress, pvsmutex, and vector< T, MINSIZE >::setsize().
Referenced by run().
int pvsworker::hasvoxel (const ivec & p, int coord, int dir, int ocoord = 0, int odir = 0, int * omin = nullptr) inline
References pvsnode::children, cur, pvsnode::edges, pvsnode::flags, PVS_HIDE_BB, ivec::sub(), and worldsize.
void pvsworker::hidepvs (pvsnode & p) inline
References pvsnode::children, pvsnode::edges, pvsnode::flags, loopi(), PVS_HIDE_BB, and PVS_HIDE_GEOM.
bool pvsworker::materialoccluded (pvsnode & p, const ivec & co, int size, const ivec & bbmin, const ivec & bbmax) inline
References pvsnode::children, hmap::flags, loopoctabox, and PVS_HIDE_BB.
bool pvsworker::materialoccluded (vector< materialsurface * > & matsurfs) inline
References C, materialsurface::csize, dimcoord, dimension, hmap::flags, loopv, materialsurface::o, materialsurface::orient, PVS_HIDE_BB, R, materialsurface::rsize, and worldsize.
void pvsworker::resetlevels () inline
References worldscale.
static int pvsworker::run (void * data) inline static
References genviewcell(), viewcellrequest::o, viewcellrequest::result, result(), viewcellrequest::size, viewcellmutex, and viewcellrequests.
Referenced by genpvs().
bool pvsworker::serializepvs (pvsnode & p, int storage = -1) inline
References pvsnode::children, pvsnode::flags, loopi(), loopj, and PVS_HIDE_BB.
void pvsworker::shaftcullpvs (shaft & s, pvsnode & p, const ivec & co = ivec(0, 0, 0), int size = worldsize) inline
References pvsnode::children, pvsnode::edges, pvsnode::flags, hmap::flags, shaft::inside(), loopi(), shaft::outside(), PVS_HIDE_BB, and PVS_HIDE_GEOM.
uchar* pvsworker::testviewcell (const ivec & co, int size, int * waterpvs = nullptr, int * len = nullptr) inline
Referenced by testpvs().
Member Data Documentation
int pvsworker::curlevel
pvsnode* pvsworker::levels[32]
ivec pvsworker::origin
vector<uchar> pvsworker::outbuf
queue<shaftbb, 32> pvsworker::prevblockers
pvsnode* pvsworker::pvsnodes
SDL_Thread* pvsworker::thread
Referenced by genpvs().
shaftbb pvsworker::viewcellbb
int pvsworker::waterbytes
int pvsworker::wateroccluded
The documentation for this struct was generated from the following file:
inexor/engine/pvs.cpp