Inexor: iqm::iqmmeshgroup Struct Reference
iqm::iqmmeshgroup Struct Reference
#include <iqm.hpp>
Public Member Functions
iqmmeshgroup ()
bool loadiqmmeshes (const char *filename, const iqmheader &hdr, uchar *buf)
bool loadiqmanims (const char *filename, const iqmheader &hdr, uchar *buf)
bool loadiqm (const char *filename, bool doloadmesh, bool doloadanim)
bool loadmesh (const char *filename)
skelanimspec * loadanim (const char *animname) override
Constructor & Destructor Documentation
iqm::iqmmeshgroup::iqmmeshgroup () inline
Member Function Documentation
skelanimspec* iqm::iqmmeshgroup::loadanim (const char * animname) inline override
References copystring(), and loadiqm().
bool iqm::iqmmeshgroup::loadiqm (const char * filename, bool doloadmesh, bool doloadanim) inline
References f(), iqmheader::filesize, lilswap(), loadiqmanims(), loadiqmmeshes(), iqmheader::magic, openfile(), stream::read(), and iqmheader::version.
Referenced by loadanim(), and loadmesh().
bool iqm::iqmmeshgroup::loadiqmanims (const char * filename, const iqmheader & hdr, uchar * buf) inline
References skelloader< iqm >::adjustments, concatstring(), copystring(), iqmanim::first_frame, dualquat::fixantipodal(), skelmodel::skelanimspec::frame, vector< T, MINSIZE >::inrange(), skelmodel::boneinfo::invbase, lilswap(), loopi(), loopj, loopk, iqmpose::mask, dualquat::mul(), model::name, iqmanim::name, vec4::normalize(), iqmheader::num_anims, iqmheader::num_framechannels, iqmheader::num_frames, iqmanim::num_frames, iqmheader::num_poses, iqmpose::offsetorient, iqmpose::offsetpos, iqmheader::ofs_anims, iqmheader::ofs_frames, iqmheader::ofs_poses, iqmheader::ofs_text, orient, skelmodel::boneinfo::parent, skelmodel::skelanimspec::range, iqmpose::scaleorient, and iqmpose::scalepos.
Referenced by loadiqm().
bool iqm::iqmmeshgroup::loadiqmmeshes (const char * filename, const iqmheader & hdr, uchar * buf) inline
References skelmodel::skelmesh::addblendcombo(), skelmodel::blendcombo::addweight(), skelmodel::boneinfo::base, skelmodel::vert::blend, skelmodel::skelmesh::bumpverts, skelmodel::blendcombo::finalize(), iqmmesh::first_triangle, iqmmesh::first_vertex, iqmvertexarray::format, fv, skelmodel::boneinfo::invbase, IQM_BLENDINDEXES, IQM_BLENDWEIGHTS, IQM_FLOAT, IQM_NORMAL, IQM_POSITION, IQM_TANGENT, IQM_TEXCOORD, IQM_UBYTE, lilswap(), Log, loopi(), loopj, loopk, dualquat::mul(), iqmmesh::name, iqmjoint::name, skelmodel::boneinfo::name, newstring(), skelmodel::vert::norm, vec4::normalize(), iqmheader::num_joints, iqmheader::num_meshes, iqmheader::num_triangles, iqmmesh::num_triangles, iqmheader::num_vertexarrays, iqmheader::num_vertexes, iqmmesh::num_vertexes, skelmodel::skelmesh::numtris, skelmodel::skelmesh::numverts, iqmvertexarray::offset, iqmheader::ofs_joints, iqmheader::ofs_meshes, iqmheader::ofs_text, iqmheader::ofs_triangles, iqmheader::ofs_vertexarrays, iqmjoint::orient, iqmjoint::parent, skelmodel::boneinfo::parent, skelmodel::vert::pos, iqmjoint::pos, iqmvertexarray::size, inexor::util::log_manager::std, anonymous_namespace{utilTest.cpp}::t(), skelmodel::vert::tc, skelmodel::skelmesh::tris, iqmvertexarray::type, skelmodel::tri::vert, iqmtriangle::vertex, and skelmodel::skelmesh::verts.
Referenced by loadiqm().
bool iqm::iqmmeshgroup::loadmesh (const char * filename) inline
References loadiqm(), model::name, and newstring().
Referenced by iqm::loadmeshes().
The documentation for this struct was generated from the following file:
inexor/model/iqm.hpp