Inexor: inexor/test/util/random.cpp File Reference
random.cpp File Reference
#include <array>
#include <ostream>
#include <random>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include "gtest/gtest-message.h"
#include "gtest/gtest-test-part.h"
#include "gtest/gtest.h"
#include "inexor/util/random.hpp"
#include <boost/thread/thread.hpp>
#include <boost/thread/lock_guard.hpp>
#include <boost/thread/mutex.hpp>
Classes
class range
Functions
TEST (DeterministicRandom, XToYRange)
TEST (PseudoRandom, XToYRange)
TEST (PseudoRandom, TypeFullRange)
TEST (PseudoRandom, NumbersDifferAmongThreads)
Variables
array< int, 24 > seeds
array< range, 5 > ranges
Class Documentation
class range
Class Members
int a
int same_compares
int tries
int z
Function Documentation
TEST (DeterministicRandom , XToYRange)
References inexor::util::random::deterministic_rnd(), ranges, and seeds.
TEST (PseudoRandom , XToYRange)
References ranges, and rnd().
TEST (PseudoRandom , TypeFullRange)
TEST (PseudoRandom , NumbersDifferAmongThreads)
References inexor::util::random::generator, anonymous_namespace{utilTest.cpp}::t(), and recorder::thread.
Variable Documentation
array<range, 5> ranges
Initial value:
{
    range({0, 2, 10, 20}),
    range({-10, 10, 100, 2}),
    range({-30000, -29900, 100, 1}),
    range({5000, 7000, 100, 1}),
    range({300,302, 4, 20})
}
Referenced by depthfxtexture::dorender(), and TEST().
array<int, 24> seeds
Initial value:
= {
    0,       -2000,      1,     -1,
    -2000000,  999,    256,  -1024,
    12516,    9124,    882,   8843,
    23619,   17610,   3270,  19176,
    21357,    8158,   7774,  19288,
    2382,     1890,  22445,   5097
}
Referenced by TEST().